### ISSUE TITLE
No file completion for `sudo -e`

### ISSUE THREAD

**Issue by JunnanZ** [fish-shell/fish-shell#6422] opened 2019-12-12 01:55 UTC
version 3.0.2
Linux 5.4.2-arch1-1
rxvt-unicode-256color
This issue persists without any customizations.

The completion for `sudo -e` only includes directories but no files. However, this command is for editing files.

**Comment by zanchey** [comment] 2019-12-12 06:49
Duplicate of #5646, which is fixed in the upcoming 3.1.0 release.

**Closed by zanchey** 2019-12-12 06:49 UTC
Labels: duplicate
