### ISSUE TITLE
Duplicates in history after history merge

### ISSUE THREAD

**Issue by patrickf3139** [fish-shell/fish-shell#6278] opened 2019-11-02 23:56 UTC
Setup 
- fish version 3.0.2
- macOS
- xterm-256color

Bug
I can see in https://github.com/fish-shell/fish-shell/issues/900 that a feature of fish is that history is meant to be free of duplicates. However, studying the code a bit, I see that history merge seems to avoid the logic that catches duplicates. And indeed, in my testing it doesn't.

Repro steps
Open two instances of fish, F1 and F2. In F1 run `history | head`. Switch to F2 and run `history | head` again. Switch back to F1 and do `history merge`. Run `history | head` one more time. Notice that `history | head` appears twice in the output.

**Comment by ridiculousfish** [comment] 2019-11-03 01:52
Heh, nice find. Duplicate entries are permitted in the file - the problem is actually in `history_t::search` which needs to filter for duplicates.

**Comment by patrickf3139** [comment] 2019-11-03 02:52
Thanks! Hope it'll be an easy fix :)
For what it's worth, I and a lot of my friends I introduced fish to use a fzf plugin for reverse-i-search. It calls `history merge` as you can see here https://github.com/jethrokuan/fzf/blob/master/functions/__fzf_reverse_isearch.fish. So my guess is that this is mildly annoying for many, many fish users.

**Comment by ridiculousfish** [comment] 2019-11-03 03:08
Should be fixed. Thanks for filing!

**Closed** 2019-11-03 03:07 UTC

**Comment by patrickf3139** [comment] 2019-11-03 04:30
@ridiculousfish Wow that was fast! I really appreciate it. Thank you so much for making fish and fielding these requests on your free time :)
