### ISSUE TITLE
array not interpreted correctly?

### ISSUE THREAD

**Issue by tkossak** [fish-shell/fish-shell#5594] opened 2019-01-28 20:40 UTC
```
$ fish --version
fish, version 3.0.0
$ uname -a
Linux lman 4.14.94-1-MANJARO #1 SMP PREEMPT Fri Jan 18 17:55:41 UTC 2019 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```
My terminal is xfce-terminal 0.8.7.4
Fish 3.0.0 seems to wrongly interpret arrays in its startup file. Seems to be regression bug - it worked in fish 2.7.1. How to reproduce:

Insert this code into your config.fish:
```fish
echo "BEFORE:"
set -S list

set -l check_dirs 1 2 3
for x in $check_dirs
    if not contains $x $list
        set -gx list $list $x
    end
end

echo "AFTER:"
set -S list
```
This code should be adding elements to `$list` variable (array) only if it doesn't contain them already.

Now start new terminal and write "fish" in it, to start new nested shell. The output is:

```
BEFORE:
$list: not set in local scope
$list: not set in global scope
$list: not set in universal scope

AFTER:
$list: not set in local scope
$list: set in global scope, exported, with 3 elements
$list[1]: length=1 value=|1|
$list[2]: length=1 value=|2|
$list[3]: length=1 value=|3|
$list: not set in universal scope

$ fish
BEFORE:
$list: not set in local scope
$list: set in global scope, exported, with 1 elements
$list[1]: length=5 value=|1 2 3|
$list: not set in universal scope

AFTER:
$list: not set in local scope
$list: set in global scope, exported, with 4 elements
$list[1]: length=5 value=|1 2 3|
$list[2]: length=1 value=|1|
$list[3]: length=1 value=|2|
$list[4]: length=1 value=|3|
$list: not set in universal scope

$
```
Result:
In the second shell (in "BEFORE" section) the `$list` variable is interpreted as single string (array with 1 element) with `1 2 3` value instead of array with 3 elements `1`, `2` and `3`

Expected result:
The second "BEFORE" section should interpret `$list` as variable with 3 elements, not 1.

Is this bug or maybe a deliberate breaking change in behavior? Or I'm doing something wrong?

**Comment by faho** [comment] 2019-01-28 20:47
>Is this bug or maybe a deliberate breaking change in behavior?

The latter. The problem is that unix doesn't have arrays in environment variables, so we had a choice between either exporting our own variables to fish properly, or interacting better with other tools (e.g. passing $EDITOR to git - I have `set -gx EDITOR emacs -nw`. Previously that would export `emacs\x1e-nw`, which would mess git up, so I'd have had to set it to `"emacs -nw"` instead, which wouldn't allow me to use it as a variable.).

The way it works now is that a variable can be marked as a "path" variable, which means it will be implicitly split on ":", and when quoted or exported joined with ":".

By default, variables whose name ends in "PATH" (like $PATH, $CDPATH and $MANPATH, but also $GOPATH) are path variables.

See e.g. `echo $PATH` vs `echo "$PATH"`.

To create path variable, use `set --path NAME`.

**Comment by tkossak** [comment] 2019-01-29 11:46
Thank you. It seems that I need to apply the same treatment (`set --path ...`) to `fish_user_paths` variable. But when I do, there is still one strange thing happening: the paths are duplicated in `$PATH`.  I have this in my `config.fish`:

```fish
set --path fish_user_paths $fish_user_paths
set -l dirs /dir1 /dir2 /dir3

for i in $dirs
    if contains $i $fish_user_paths
        echo "Not adding: $i"
    else
        echo "Adding: $i"
        set -gx fish_user_paths $fish_user_paths $i
    end
end
```

Now when I start new terminal and run nested shells this happens:

```fish
Adding: /dir1
Adding: /dir2
Adding: /dir3
kossak@manj ~/.c/fish> echo $fish_user_paths
/dir1 /dir2 /dir3
kossak@manj ~/.c/fish> echo $PATH
/dir1 /dir2 /dir3 /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl

kossak@manj ~/.c/fish> fish
Not adding: /dir1
Not adding: /dir2
Not adding: /dir3
kossak@manj ~/.c/fish> echo $fish_user_paths
/dir1 /dir2 /dir3
kossak@manj ~/.c/fish> echo $PATH
/dir1 /dir2 /dir3 /dir1 /dir2 /dir3 /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

The last line has duplicated directories. How should I handle adding paths to `$fish_use_paths` and `$PATH` correctly for nested shells?

**Comment by faho** [comment] 2019-01-30 10:19
>Maybe I shouldn't set global fish_user_paths variable in fish 3.0.0, only universal one?

Honestly, I don't really see the point of a global fish_user_paths. Instead of doing that you can just add to $PATH directly. I especially don't see the point of exporting it - if you start another fish, it'll read config.fish again and set it again, and if you start anything else, it won't know what to do with $fish_user_paths.

-------

I think I know what's going on here. The problem is that `set --path` happens too late. We add $fish_user_paths to $PATH pretty early on, so in that case it'll still be just one string of "/dir1:/dir2:/dir3". We check if that is in $PATH as one component, which it isn't, so we insert it. $PATH then splits it so it'll appear as three separate ones, which happen to be duplicated.

There's three different workarounds:

- Use universal $fish_user_paths

- Use global-but-unexported $fish_user_paths

- Use $PATH directly

The solution is probably to just split $fish_user_paths on ":" manually in the code where we add it to $PATH. It's defensive anyway.

**Comment by ridiculousfish** [comment] 2019-02-01 21:59
Yes the intended behavior of fish_user_paths is to be universal and not exported:

    set -U fish_user_paths path1 path2

**Closed** 2019-02-13 11:36 UTC
Labels: question
