### ISSUE TITLE
Inconsistency when running commands in background

### ISSUE THREAD

**Issue by MonAaraj** [fish-shell/fish-shell#7808] opened 2021-03-09 22:12 UTC
Fish version 3.2.0, uname output:
```
Linux artix-pc 5.10.15-artix1-1 #1 SMP PREEMPT Fri, 12 Feb 2021 23:37:53 +0000 x86_64 GNU/Linux
```

$TERM is alacritty, and the problem still occurs after trying it in `sh -c 'env HOME=$(mktemp -d) fish'`

---
Coming from https://github.com/jorgebucaran/fisher/issues/664, it looks like I am getting weird behaviour while running a process in the background, after a bit of research, it looks like this issue may relate to #238, but I'm getting sort of different behaviour. When trying to use something like fisher, or something as simple as just running `fish -c "sleep 3" &`, I get something like:
```
[I] mon@artix-pc ~> fish -c "sleep 3" &
[I] mon@artix-pc ~> fish: Job 1, 'fish -c "sleep 3" &' has stopped
```
And then I have to run `fg` to bring it to foreground, and then it will run and finish. Seems like the way to "fix" it would be running `fish -c "sleep 3" < /dev/null &`, but weirdly, that issue seems to only happen for me, as far as I've seen. So, Fisher works for other people, but not for me, because of that error. I'm not quite sure why the behaviour is so inconsistent between users.

**Comment by faho** [comment] 2021-03-10 07:56
This works for me as well.

What could cause this is if something in your config tried to access the terminal in ways it's not allowed to, causing the OS to send a SIGTTOU/SIGTTIN.

This can be your own config, or something artix adds on - check both ~/.config/fish and /etc/fish.

> $TERM is alacritty, and the problem still occurs after trying it in sh -c 'env HOME=$(mktemp -d) fish'

Note that this will only work if you haven't set $XDG_CONFIG_HOME explicitly (and don't set it after!).

Also:

>Fish version 3.2.0, uname output:

Artix (which is an arch derivative) still ships fish 3.1.2. Have you built fish yourself or are you still running that?

**Comment by MonAaraj** [comment] 2021-03-10 08:01
I have just installed the fish-git package, which had fish version 3.2.0. And, I did comment out my `~/.config/fish` to test it out in Fisher's issue, but I'll see `/etc/fish`, thank you

**Comment by MonAaraj** [comment] 2021-03-10 08:06
Hmm, looks like there's nothing in there, neither. All the code in `/etc/fish/config.fish` is commented, and every other directory inside it is empty... But I might have an idea: I had fish 3.1.2 *earlier* before I tried to install tide, so I installed fish-git and replaced the original fish, could that cause it, or give a hint towards a solution?

**Comment by faho** [comment] 2021-03-10 08:14
Ah, I've managed to reproduce this.

It's **not** in 3.2.0, you're using the fish-git package, which **does not** have 3.2.0, it has whatever is in git master. It's moved past 3.2.0.

Running a bisect, but honestly it's probably dbb74f87ba6ac89c13ca6826a7448004b019885a.

**Comment by MonAaraj** [comment] 2021-03-10 08:19
Ohhh... I think I managed to miss a detail: `fish, version 3.2.0-44-g4218c1f1a`, it isn't exactly 3.2.0, but I didn't know the numbers after it would be important, thank you so much!

**Comment by faho** [comment] 2021-03-10 08:39
Alright, should be fixed now, you'd get it if you re-build fish-git.

Good thing we caught this before 3.2.1, it would have been quite annoying otherwise.

**Closed** 2021-03-10 08:39 UTC
Labels: regression

**Comment by MonAaraj** [comment] 2021-03-10 16:36
Thank you very much, once again! I've been trying to rebuild it but one of the test fails because it turns out I have some zombie processes, but trying every single way to try to kill them, including just straight up reboots, doesn't really work for me. Is there some sort of bug that makes fish keep spawning zombie processes?

**Comment by faho** [comment] 2021-03-10 16:55
None that I know of, the tests succeed on my end.

What is the exact error you get in which context?

(also you can always run `makepkg --nocheck` to skip the tests)

**Comment by MonAaraj** [comment] 2021-03-10 17:03
```
Testing file checks/job-ids.fish ... ok (17 ms)
Testing file checks/jobs.fish ... Failure:

  The CHECK on line 11 wants:
    All clear of zombies.

  which failed to match line stdout:1:
    Found existing zombie processes. Clean up zombies before running this test.

  Context:
    Found existing zombie processes. Clean up zombies before running this test. <= does not match CHECK 'All clear of zombies.' on line 11
     <= nothing to match CHECK 'Trigger process reaping' on line 21
     <= nothing to match CHECK '1' on line 30
     <= nothing to match CHECK 'Command' on line 34
     <= nothing to match CHECK 'sleep' on line 35
     <= nothing to match CHECK 'sleep' on line 36
     <= nothing to match CHECK '0' on line 39
     <= nothing to match CHECK 'Command' on line 50
     <= nothing to match CHECK 'sleep' on line 51
     <= nothing to match CHECK 'sleep' on line 52
     <= nothing to match CHECK '1' on line 55
     <= nothing to match CHECK '2' on line 59
     <= nothing to match CHECK '1' on line 63
     <= nothing to match CHECK '2' on line 66
     <= nothing to match CHECK 'Command' on line 94
     <= nothing to match CHECK 'sleep' on line 95
     <= nothing to match CHECK 'sleep is done' on line 96
     <= nothing to match CHECK '1' on line 97
     <= nothing to match CHECK 'Command' on line 101
     <= nothing to match CHECK 'sleep' on line 102
     <= nothing to match CHECK '0' on line 103
     <= nothing to match CHECK 'foo' on line 117
     <= nothing to match CHECK 'caller' on line 118

  when running command:
    ../test/root/bin/fish checks/jobs.fish
```
Here's the error, and I just get it when I run `yay -S fish-git`, in the test portion. I'll try using `makepkg --nocheck`, thank you for suggesting it!

**Comment by faho** [comment] 2021-03-10 17:06
Ah, okay, you still *have* zombies running, because you've been running the broken fish.

That's not actually an error in the test, your environment isn't clean for the test to run.

**Comment by MonAaraj** [comment] 2021-03-10 17:07
Ah, I see. Thank you for helping, I really appreciate it!
