### ISSUE TITLE
Feature request: Enhance abbr to support global expansion when wanted

### ISSUE THREAD

**Issue by manfredlotz** [fish-shell/fish-shell#5760] opened 2019-03-24 12:41 UTC

**Comment by manfredlotz** [comment] 2019-03-24 12:44
Want to have global aliases in a way the zsh shell offers it. One important
feature of the global alias in the zsh shell is that it gets expanded anywhere
in the command line, i.e. not only at the beginning

So I propose to enhance abbr to allow an option which says that the expansion may take place anywhere in the command line, thus allowing the following definition

```
abbr --everywhere S '| sort'
```

and then I could type: `ls -l S<space>` and get `ls -l | sort `

**Comment by faho** [comment] 2019-03-24 12:48
Duplicate of #5003

**Closed by faho** 2019-03-24 12:48 UTC

**Comment by manfredlotz** [comment] 2019-03-24 12:54
Which was closed. Does it mean it will not be implemented at all?

**Comment by faho** [comment] 2019-03-24 12:55
It's not closed?

**Comment by manfredlotz** [comment] 2019-03-24 12:55
Sorry, I misread #5003
