### ISSUE TITLE
Signing Git commit with GPG ask passphrase everytime

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#4665] opened 2018-01-16 16:04 UTC
### Env

**fish**

    fish, version 2.7.1

**OS**

    lsb_release -a
    No LSB modules are available.
    Distributor ID: LinuxMint
    Description:    Linux Mint 18.3 Sylvia
    Release:        18.3
    Codename:       sylvia

**Kernel**

    Linux x1 4.13.0-21-generic #24~16.04.1-Ubuntu SMP Mon Dec 18 19:39:31 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Terminal**

    screen-256color

### Reproduce

    git config --global commit.gpgsign true
    git config --global user.signingkey <GPG-ID>

Then, working on a git project I do

    git add .
    git commit --message="do something useful"
    git commit --amend --no-edit

### Clean env

```
❯ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
$ cd /tmp/
$ mkdir tmp-git
$ cd tmp-git/
$ git init
Initialized empty Git repository in /tmp/tmp-git/.git/
$ touch toto.txt
$ git add .
$ git commit -m 'boom'
$ git config user.email "you@example.com"
$ git config user.name "Your Name"
$ git config commit.gpgsign true
$ git config user.signingkey <GPG_KEY_ID>
$ git commit -m 'boom'
error: gpg failed to sign the data
fatal: failed to write commit object


$ set -x GPG_TTY (tty)
$ git commit -m 'boom'
error: gpg failed to sign the data
fatal: failed to write commit object
$ set -x GIT_TRACE 1; git commit -m 'boom'
16:54:47.683461 git.c:344               trace: built-in: git 'commit' '-m' 'boom'
16:54:47.684372 run-command.c:626       trace: run_command: 'gpg' '--status-fd=2' '-bsau' '<GPG_KEY_ID>'
error: gpg failed to sign the data
fatal: failed to write commit object
$ gpg --status-fd=2 -bsau <GPG_KEY_ID>
gpg: skipped "<GPG_KEY_ID>": secret key not available
gpg: signing failed: secret key not available

$ git config --global gpg.program /usr/bin/gpg2 
16:58:07.096435 git.c:344               trace: built-in: git 'config' '--global' 'gpg.program' '/usr/bin/gpg2'
$ set -x GIT_TRACE 1; git commit -m 'boom'
16:58:09.585478 git.c:344               trace: built-in: git 'commit' '-m' 'boom'
16:58:09.586187 run-command.c:626       trace: run_command: '/usr/bin/gpg2' '--status-fd=2' '-bsau' '<GPG_KEY_ID>'
error: gpg failed to sign the data
fatal: failed to write commit object
$ git config --global user.signingkey <GPG_KEY_ID>
16:58:34.822342 git.c:344               trace: built-in: git 'config' '--global' 'user.signingkey' '<GPG_KEY_ID>'
$ set -x GIT_TRACE 1; git commit -m 'boom'
16:58:36.734318 git.c:344               trace: built-in: git 'commit' '-m' 'boom'
16:58:36.734945 run-command.c:626       trace: run_command: '/usr/bin/gpg2' '--status-fd=2' '-bsau' '<GPG_KEY_ID>'
error: gpg failed to sign the data
fatal: failed to write commit object
$ set -gx GPG_TTY (tty)
$ set -x GIT_TRACE 1; git commit -m 'boom'
16:59:18.965959 git.c:344               trace: built-in: git 'commit' '-m' 'boom'
16:59:18.966596 run-command.c:626       trace: run_command: '/usr/bin/gpg2' '--status-fd=2' '-bsau' '<GPG_KEY_ID>'
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by faho** [comment] 2018-01-16 17:26
This is one of those things that won't work with a "clean env", because that means gpg can no longer locate its socket or the private key.

Just to be clear, when you're not running in a "clean environment", you get the following:

- You `git commit`, pinentry pops up and asks for a  passphrase
- You enter the passphrase and the commit goes through
- You `git commit` again, and it again asks for the passphrase

So the issue is that it doesn't remember the passphrase for a couple of minutes?

And this works when running `git commit` under bash instead?

**Comment by edouard-lopez** [comment] 2018-01-18 11:22
Got the same behavior with `bash` :S

**Comment by faho** [comment] 2018-01-18 17:11
>got the same behavior with bash

That means it's not a fish issue. You might be better off consulting  the gpg documentation.

Some things to look into: You're using gpg2, which means you are using gpg-agent - a service that runs in the background and handles the private keys and stuff. Check into how you are launching that, and how that is configured. Especially look at the `*cache-ttl` settings e.g. in ~/.gnupg/gpg-agent.conf, and wherever it is you are starting it from. If one of those is set to 0 (i.e. no "cache"), you should see this behavior.

Personally, I haven't configured any of that. I've just enabled the systemd-user "gpg-agent.socket" and it works. This might however require a newer gpg than what your distro provides.

Since this isn't really the forum for this, I'll close the issue.

**Closed by faho** 2018-01-18 17:11 UTC

**Comment by edouard-lopez** [comment] 2018-01-19 16:38
The following helped me fix my issue:

* [“gpg: problem with the agent: No pinentry” — SOLVED](https://chaosfreakblog.wordpress.com/2013/06/21/gpg-problem-with-the-agent-no-pinentry-solved/)
* [Signing Git Commits & Tags with GPG2 and Verified on GitHub](https://w3guy.com/sign-git-commits-tags-gpg-github-verified/)

### Using `gpg2` to sign commit
 
    git config --global gpg.program /usr/bin/gpg2 

### `gpg-agent` config

    $ vim ~/.gnupg/gpg-agent.conf 
    pinentry-timeout 0
    pinentry-program /usr/bin/pinentry-curses
