### ISSUE TITLE
Write a converter or add a mode to accept regular old shell scripts

### ISSUE THREAD

**Issue by shouze** [fish-shell/fish-shell#522] opened 2013-01-15 15:24 UTC
This is the only way to adopt fish definitively for me. It's not appropriate to make the switch without that.

**Comment by pik** [comment] 2015-09-05 09:55
:+1: for this. I've been using fish for a lately but been thinking more and more about switching back to bash and zsh.

For compatibility I always have to script in bash anyways - and having to hack-around obviously simple things such as `eval "$(docker-machine env my_env)"` just because fish has it's own "approach" which is a very minor aesthetic when it comes down to it -.

**Comment by sghiassy** [comment] 2016-10-01 00:51
I could really use this as well

**Comment by krader1961** [comment] 2016-10-02 02:46
There seem to be two different use cases. Some people seem to feel we should add full support for bash, or at least sh, syntax. That would allow fish to use native functions (e.g., the `cd` override mentioned earlier) written for those shells. I am quite confident there will never be a full /bin/sh, let alone bash, emulation layer added to fish. It's highly unlikely that even a sufficiently large subset of /bin/sh syntax and behavior will be added to fish to allow arbitrary scripts to be run with confidence  they will work correctly inside fish. That proposal is a non-starter AFAICT.

The second use case is more reasonable: Make it possible to recognize changes to environment vars made by scripts like *nvm.sh* and incorporate those changes into the current fish environment. That's what the [`bass`](https://github.com/edc/bass) aims to support.

I vote for closing this issue since the first goal is impractical and the second goal appears to have already been achieved.

**Comment by krader1961** [comment] 2016-10-15 04:51
Okay, I'm closing this since the broader goal (full /bin/sh or bash compatibility) will never be implemented. It's akin to asking that Python allow Perl syntax. And the narrower goal of dealing with sh/bash scripts that set environment variables has already been solved. To the extent the latter solution is imperfect I invite people to open a new issue to discuss how to improve handling that use case.

**Closed by krader1961** 2016-10-15 04:51 UTC
Labels: enhancement, posix-me-harder

**Comment by sghiassy** [comment] 2016-10-15 05:57
I'm not entirely sure of the conclusion to close this issue. Cross-platform compatibility to increase a software's reach has ton's of precedence:

- Parallels runs Windows programs on Mac
- Windows now runs Linux shell commands
- PCI.js runs DOS in the browser
- Ecmascripten transpiles C/C++ to JavaScript

If you can transpile C++ to JavaScript then you can certainly figure out a way to run bash scripts in Fish terminal.

Seeing as I'm not willing to do with work, I have no room to complain. But my 2cents is that Fish shell will not gain mainstream traction without such support.

Best of luck,
-- Shaheen

**Comment by faho** [comment] 2016-10-15 10:56
@sghiassy: Those examples don't really apply here. You might notice that three out of those are special programs that "just" achieve this compatibility. Parallels is a VM. It's sole purpose is doing this stuff.

Also, without these (or equivalent programs), there'd be no way to run the "guest language" in that context at all. You need ecmascripten to write something in C that then runs in the browser.

But we already have a way to run bash script inside of fish - `bash -c` and running via shebang. Just like we have a way to run python or C code inside of fish. The one missing piece was when you needed to keep environment changes, but that's now also been solved.

Also, I don't think "mainstream traction" is our goal. Making fish the best shell we can is.

If anyone wishes to write a bash-to-fish transpiler, feel free to do so.

**Comment by ShalokShalom** [comment] 2017-06-21 13:34
Agree :+1:

**Comment by ShalokShalom** [comment] 2017-06-21 13:35
Then, no fish for me.

**Comment by timofonic** [comment] 2017-11-09 11:42
Sorry for the long reply.

I understand a (Ba/Z/TC/..)sh converter to fish would be a titanic task , but I consider it to make it essential to get a massive adption.

- There's lots of shell scripts many people find useful, yet they are hacked and hacked forever. The task of rewriting them is not pragmatic for the user most of the time.
- Even if the initial transpiler (consider it like those javascript transpilers) might not be perfect, it may ease the  factorization process.
- The possibility of having a Linux/BSD/Whatever only-fish distro: No more clunky old .sh files and easier for fish users to modify them. No more need of "POSIX" shell interpreters but a modern one only.
- It can motivate people to switch to Fish and have their scripts in fish. As much as good the conversion might get better, it can be optimized later.
- It can convince old school (z/ba/*)shists to be fishers ;)

About the program: Why writing from scratch? Maybe some framework could help at it :)

What about doing "POSIX SHELL" -> INTERMEDIATE CODE -> FISH ?

There's bash2fish. Maybe a similar approach can be possible too :)

https://zwischenzugs.com/2016/08/29/bash-to-python-converter/
http://ieeexplore.ieee.org/document/7081866/
http://www.swag.uwaterloo.ca/bash2py/

https://gitlab.com/ps1260/bash2fish

And...
https://gitlab.com/ps1260/bash2fish_rs

**Comment by faho** [comment] 2017-11-09 16:49
>I understand a (Ba/Z/TC/..)sh converter to fish would be a titanic task

That's... an understatement. See e.g. http://www.oilshell.org/blog/tags.html?tag=parsing-shell#parsing-shell to understand how hard parsing shell scripts actually is.

>There's lots of shell scripts many people find useful, yet they are hacked and hacked forever. The task of rewriting them is not pragmatic for the user most of the time.

Yes, and 99% of those can just run in whatever they were written for. In practice the only ones that actually need to be converted are those that modify the environment of the running shell (and hence need to be `source`d, not "./script" executed).

>Even if the initial transpiler (consider it like those javascript transpilers) might not be perfect, it may ease the factorization process.

At the very least it would produce a whole bunch of non-idiomatic weird fish script. Most likely it would introduce a lot of bugs.

>The possibility of having a Linux/BSD/Whatever only-fish distro: No more clunky old .sh files and easier for fish users to modify them. No more need of "POSIX" shell interpreters but a modern one only.

There is really no _need_ for that! You can have bash installed just like you have python or perl.

>It can convince old school (z/ba/*)shists to be fishers ;)

Nah. Like I said above, it doesn't matter what 99% of your scripts are written in.

----

If you would like to write a transpiler, go right ahead! That would be a really cool thing!

But this issue is closed because

- It wouldn't have as much utility as you suggest

- It would be bootloads of work

- We're not going to do that

**Comment by ShalokShalom** [comment] 2017-11-10 09:17
> "Yes, and 99% of those can just run in whatever they were written for."

Which is completely untrue. I had issues with A LOT of scripts and use ZSH with Oh-my-zsh and [zsh-autocomplete](https://github.com/zsh-users/zsh-autosuggestions) since some months. 

Never looked back since then and I recommend everyone to switch.

To me, fish is broken in its design. 

Cheers

**Comment by maxadamo** [comment] 2017-12-10 19:08
I want to add my personal consideration to the discussion. 
A part from the considerations on POSIX standards, why should we deviate from what is commonly considered an expected behaviors, a default behaviour, a standard? 
Most Unixes adopted bash as default shell: OS-X, all Linux, even Solaris used the bash. Other flavours use all different kind of shell (freebsd and openbsd have different default shell)  
As a consequence, for instance, majority of users today use Ctrl-r to access the shell history. 
So, why moving back to Korn Shell behaviour? Is it any better to use Esc-k, instead of Ctrl-r? 
Even editing the command line it's korn style, but it's not what a user expects to see (even if you make Mac users happy, as they only have a backspace key) 
Secondly, if you adopt the same standards, you'll make life easier to those who want to move from bash ti fish.

**Comment by faho** [comment] 2018-11-22 16:31
@evert-mouw: That particular bit has been added to the upcoming 3.0.

**Comment by evert-mouw** [comment] 2018-11-22 16:34
> @evert-mouw: That particular bit has been added to the upcoming 3.0.

Cool, thanks! :+1:
