### ISSUE TITLE
macOS 10.9 Terminal.app mishandles clr_eos

### ISSUE THREAD

**Issue by krackers** [fish-shell/fish-shell#7549] opened 2020-12-14 00:27 UTC
Version: Fish 3.1.2. Issue verified on 2 separate linux machines (Debian Debian GNU/Linux 9.13 and Ubuntu 18.04.5) as well as macos 10.9.5

Terminal: Terminal.app on osx 10.9.5, ssh-ing into the two linux machines.

Reproduction steps:

Begin the autocompletion pager by e.g. typing `curl --` and pressing tab. After selecting an entry from the list, the screen is blank

![image](https://user-images.githubusercontent.com/20675996/102028461-455f6800-3d5f-11eb-84cb-11c3282d05a7.png)

However, scrolling the terminal up we see that all the autocomplete entries as well as the original input are still present above, which seems to indicate that something's not being cleared properly.

```
~ > curl --compressed-ssh 
--abstract-unix-socket  ((HTTP) Connect through an abstract Unix domain socket, instead of using t…)
--anyauth                               ((HTTP) Use most secure authentication method automatically)
--append                                              ((FTP SFTP) Upload: append to the target file)
--basic                                                       ((HTTP) Use HTTP Basic authentication)
--cacert                                                  ((TLS) Use the specified certificate file)
--capath                                             ((TLS) Use the specified certificate directory)
--cert                                                                         ((TLS) Use this cert)
--cert-status                             ((TLS) Use Certificate Status Request (aka OCSP stapling))
--cert-type                                      ((TLS) Set type of the provided client certificate)
--cert-type=                                     ((TLS) Set type of the provided client certificate)
--ciphers                                                     ((TLS) Specifies which ciphers to use)
--compressed                                                  ((HTTP) Request a compressed response)
--compressed-ssh                                       ((SCP SFTP) Enables built-in SSH compression)
--config                                           (Specify a text file to read curl arguments from)
--connect-timeout                             (Maximum time in seconds you allow connection to take)
--connect-to           (For a request to the given HOST1:PORT1 pair, connect to HOST2:PORT2 instead)
--continue-at                         (Continue/Resume a previous file transfer at the given offset)
--cookie                              ((HTTP) Pass the data to the HTTP server in the Cookie header)
--cookie-jar                                                 ((HTTP) Write all cookies to this file)
--create-dirs                                                          (Create dirs for -o/--output)
--crlf                            ((FTP SMTP) Convert LF to CRLF in upload. Useful for MVS (OS/390))
--crlfile                 ((TLS) Provide a file using PEM format with a Certificate Revocation List)
--data                        ((HTTP) Sends the specified data in a POST request to the HTTP server)
--data-ascii                                                           ((HTTP) Alias for -d, --data)
--data-binary                             ((HTTP) Post data exactly as specified with no processing)
--data-raw                                ((HTTP) Post data like --data but without interpeting "@")
rows 1 to 26 of 226
```

Interestingly, if I SSH into the linux machines and then running fish inside tmux, the screen paints properly. If I use XTerm instead of Terminal.app the issue is also not present.

Bisecting, I find that the issue was first introduced somewhere in 3.1.0beta (aabc208). The bug does not happen in 3.0.3

Edit: I git bisected my way to the culprit:

```
d502ad2c253d931a1674909a4b402285e8c4a4cf is the first bad commit
commit d502ad2c253d931a1674909a4b402285e8c4a4cf
Author: Per Bothner <per@bothner.com>
Date:   Thu Oct 10 11:15:04 2019 -0700

    Prefer using clr_eos to clear "remaining lines"
    
    This is both more efficient than multiple clr_eol sequences,
    and also works better with shell-integration.
```

and I can confirm that reverting that fixes the issue. I'm not too sure about why that is though, since it seems like Terminal.app _should_ support clr_eos? If any of you have an older osx vm lying around, can you try testing it to see its behavior? I also tried using the prebuilt fish package which should rule out any issue with ncurses.

**Comment by ridiculousfish** [comment] 2020-12-14 04:14
The clr_eos change was first introduced in d502ad2c253d931a1674909a4b402285e8c4a4cf, then reverted as ec4bbe248e29565fa8446eda6f749362b048676e, then re-introduced as 87d2cd6503b8c10cf6fdcf30f3d6f92b62dc9707.

I was able to reproduce on 10.9. Mercifully, one can copy 10.9's Terminal app to a Big Sur (10.11) machine, it runs fine and reproduces the problem, but the Terminal.app that shipped with Big Sur itself does not. So this is probably a bug in how macOS 10.9 Terminal handles `clr_eos` that was fixed in a later version of macOS.

I think if there's a straightforward way to detect running under 10.9 Terminal app we can avoid using `clr_eos`. Probably we can do that by looking at `$TERM_PROGRAM` and also `$TERM_PROGRAM_VERSION` which are both set.

@krackers can you confirm what `env | grep TERM_PROGRAM` shows? I get:

    > env | grep TERM_PROGRAM
    TERM_PROGRAM=Apple_Terminal
    TERM_PROGRAM_VERSION=326

and that's probably what we could key off of.

**Comment by krackers** [comment] 2020-12-14 04:23
I get
```
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=334
```
but that's because I'm using a version of Terminal.app that was shipped with one of the Yosmite betas. So as far as I know anything `< 334` has the bug.

I wonder if this issue is present on Yosemite/El Capitan as well?

**Comment by krackers** [comment] 2020-12-14 04:59
Out of curiosity, in what way is the behavior of `clr_eos` incorrect? When I try `echo -e "\e[2J"` I see that the screen is indeed erased, and even in xterm the old output is still available in scrollback.

**Comment by ridiculousfish** [comment] 2020-12-15 04:52
Disassembling Terminal to investigate its clr_eos handling is some next level.

**Comment by faho** [comment] 2021-02-04 13:16
Okay, I'm closing this because nobody seems to be stepping up to do it, and it's not a priority because macOS 10.9 has been EOL since 2016. The workaround is also simple - just use a different terminal.

If someone sends a patch, we'll merge it, of course.

**Closed by faho** 2021-02-04 13:16 UTC
Labels: enhancement
