### ISSUE TITLE
Some copy paste are not saved in history (starting with empty space)

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5101] opened 2018-07-19 19:33 UTC
fish 2.7.1

When I copy paste a command like:

         ls 

It doesn't stay in history. Why? Because there are extra spaces/tabs at the beginning. But most of the time when I copy I have empty spaces before the command, so it's kind of annoying it doesn't stay in history.

How to make it save the command?

**Comment by faho** [comment] 2018-07-19 20:13
It's not a bug, it's a feature.

Remove the leading spaces and it'll be saved.

There is also #4327, asking for this to be removed.

**Comment by krader1961** [comment] 2018-07-19 20:14
From the [documentation](http://fishshell.com/docs/current/index.html#history-search):

> Prefixing the commandline with a space will prevent the entire line from being stored in the history.

Personally I'm not a fan of this feature and have argued in the past for its removal. But there are lots of people who like it so it remains.

**Comment by BarbzYHOOL** [comment] 2018-07-19 22:07
I guessed it wasn't a bug but I couldn't make a better title so it sounds like a bug report :P


> Remove the leading spaces and it'll be saved.

Yes, I think I already understood this but goddamn it's annoying to me (unless there is a shortcut to delete leading spaces). Especially when you come from bash


What would be nice is to have it as a config option, so we could disable that feature. Even though fish doesn't like to let the user config much (from the official motto :P)

**Comment by faho** [comment] 2018-07-19 22:09
Closing as a duplicate of #4327 then.

**Closed by faho** 2018-07-19 22:09 UTC
Labels: question

**Comment by BarbzYHOOL** [comment] 2018-10-08 18:32
Seriously, is there a way for me to remove this feature? this is really making me waste time, some people prefer it that's okay, but is there a solution for me?

**Comment by faho** [comment] 2018-10-08 19:00
It is possible to change pasting so that it will remove leading whitespace.

E.g. you can modify `fish_clipboard_paste` (which you trigger with ctrl-v by default, not to be confused with ctrl-shift-v, which often triggers the terminals paste) to add a `string trim`:

```fish
# after:
    set data (string split \r -- $data)

# insert:
    set -l cmd (commandline)
    if test -z "$cmd"
        # Remove leading whitespace from the first line so it won't skip the history.
        set data[1] (string trim -l -- $data[1])
    end
# ...
```

Otherwise, you're gonna have to wait for #4327.

**Comment by faho** [comment] 2018-10-11 10:40
>it opened my visual editor (I have set $VISUAL to Sublimetext) but it was empty

The problem there is that `subl3` opens sublime but exits immediately. That won't work because `funced` (like most other things that use $EDITOR or $VISUAL) has to wait for the editor to finish editting. You need `subl3 -w`.

**Comment by BarbzYHOOL** [comment] 2018-10-12 19:22
Really awesome, `set VISUAL "subl -w"` did it.

Why it's not the default setting? Apparently I'm not the only one https://forum.sublimetext.com/t/subl-w/6825

Anyway thank you @faho
