### ISSUE TITLE
Adding an option to force string escape to use quoted escape style

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#8498] opened 2021-11-29 05:09 UTC
I found `string escape` is trying to choose escape style between quoted escape and no-quoted escape by itself.
See the following two examples.
``` fish
# quoted escape
$ echo '$ ' | string escape
'$ '

# no-quoted escape
$ echo '$\ ' | string escape
\$\\\ 
```

As there is already an option `--no-quoted` to explicitly flag no-quoted escape, I think it's reasonable to add a reversed option like `--quoted` to enforce quoted escape.

**Comment by faho** [comment] 2021-11-29 07:18
Duplicate of #5433

**Closed by faho** 2021-11-29 07:18 UTC

**Comment by imcaizheng** [comment] 2021-11-29 12:14
I believe this issue is not a duplicate to #5433. #5433 is all about whether to provide an option to change how auto-suggestion behaves or not but in my case I'm looking for a way to use the `string escape` command to process arbitrary string from stdin or from command line arguments.

Specifically, I'm expecting an option adding to the `string escape` command so we can do something like 

``` bash
echo '$\ ' | string escape --quoted
```

 instead of, e.g.,
``` bash
echo '$\ ' | string replace \\ \\\\ --all | string replace -r '^' \' | string replace -r '$' \'
```

**Comment by faho** [comment] 2021-11-29 12:21
The escaping code is currently unable to escape with quotes if there already are quotes embedded. That would have to be fixed to add a string escape mode, and that's part of #5433. Adding the string escape mode on top is a few lines extra, so we can simply do it in the same step.
