### ISSUE TITLE
Vi like command line 'b' and 'e' command doesn't behave properly

### ISSUE THREAD

**Issue by dgsb** [fish-shell/fish-shell#4371] opened 2017-09-01 09:25 UTC
fish version: 2.6.0 on OSX

Some sequence of 'b' and 'e' sometimes skip words or position the cursor one character before or after the expected position.
It seems to be related with non alphanum characters ('-', '(', etc ...)

**Comment by timofonic** [comment] 2017-09-01 11:58
@dgsb I'm totally new to fish, but I think the title is incorrect. Did you mean " Vi like command line 'b' and 'e' command doesn't behave properly" instead? I think "Vi like command line 'b' and 'e' command doesn't behave properly on *macOS" or even better "Vi like command line 'b' and 'e' command doesn't behave properly on macOS(1) VERSION(2)"

1. I understand OSX, but macOS is the actual official name for the Apple's operating system. 
2. You also didn't specify your macOS version, it would be interesting to know it.
3. It would be nice to provide more information: fish versions, extensions/addons/scripts added, your fish configuration, etc. I'm sure others would inform you better at this.

**Comment by dgsb** [comment] 2017-09-01 13:50
Indeed the title was wrong, corrected.
The issue does not seem to be os x not specific, I've reproduced it on linux ubuntu 16 with a fresh fish 2.2.0 installed form system package.
Can be easily reproduced by typing:
```shell
fish --version
```
Don't type enter.
Type <Esc>, $, b and b
The cursor should on the first dash, but it is positioned on the space character just before it

**Comment by faho** [comment] 2017-09-06 08:27
Duplicate of #4025.

**Closed by faho** 2017-09-06 08:27 UTC
