### ISSUE TITLE
Completion of `open -a` with paths

### ISSUE THREAD

**Issue by mlhetland** [fish-shell/fish-shell#5161] opened 2018-08-26 11:21 UTC
On macOS, the `open` command has tab completion for `-a`, which lets you open files with a specific app. This completion is restricted to application names, though the command it self works with paths to apps as well. In general, restricting the completion to application names makes sense, and permitting arbitrary paths would just clutter things; however, there are cases where one might want to differentiate between apps based on paths. For example, because of compatibility issues, I need to open files in both `/Applications/Keynote.app` and `/Application/iWorks '09/Keynote.app`. It might still be reaasonable to only complete paths in `/Application`, I guess?

(Using fish 2.7.1 on Darwin dora 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64). Running without third-party customizations did not affect the issue. If the requested behavior is already avaiable through configuration, I apologize for the noise.)

**Comment by faho** [comment] 2018-08-26 12:58
Duplicate of #4993, solved by #4994.

**Closed by faho** 2018-08-26 12:58 UTC

**Comment by mlhetland** [comment] 2018-08-26 13:59
Dang, sorry. Tried to search for it, but now realize I only searched open issues.

**Comment by faho** [comment] 2018-08-26 14:31
No worries!
