### ISSUE TITLE
Suppress wildcards-globbing for http(s) parameters

### ISSUE THREAD

**Issue by karstenBriksoft** [fish-shell/fish-shell#10416] opened 2024-04-04 10:00 UTC
I'm using fish, version 3.7.1

Sometimes I issue commands that take a URL parameter and oftentimes I forget to explicitly quote the parameter, resulting in the message `No matches for wildcard 'https://....'. See help \`wildcards-globbing\`.`

As far as I understand the documentation, this whole concept is there exclusively for files, making it a host-only solution. It would be super convenient if parameters that start with http:// or https:// (or other protocols) simply run until the next whitespace and do not try to interpret question marks, ampersands or asterisk characters.

**Comment by faho** [comment] 2024-04-04 10:19
We don't do special-cases like that.

Here's what you can do:

- Enable the [qmark-noglob feature-flag](https://fishshell.com/docs/current/language.html#featureflags), which turns off the `?` glob entirely. This will be enabled by default and then made read-only in future.
- Paste the URL inside single-quotes, where fish will escape it automatically
- Just quote it

I'm going to close this as a duplicate of #3649, because the `?` glob is the important character for URLs.

**Closed by faho** 2024-04-04 10:19 UTC
