### ISSUE TITLE
Newline after upgrading to 3.2.1 from 3.1.*

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#7993] opened 2021-05-12 08:27 UTC
When starting a new shell I get a newline symbol and multiple new lines:

![screenshot](https://user-images.githubusercontent.com/3178666/117943400-61fecc80-b30c-11eb-81b5-1f3b3ba8feb8.png)

This only happend after updating fish to version `3.2.1`, before I did not have this problem. 

I disable the greeting in my `config.fish` but this should not create these new lines:

``` fish
# Disable greeting
set -U fish_greeting ""
```

**Comment by faho** [comment] 2021-05-12 08:56
Duplicate of #7893

**Closed by faho** 2021-05-12 08:56 UTC
