### ISSUE TITLE
Can't use the output of a subcommand as a command

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#3838] opened 2017-02-10 18:53 UTC
- [X] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.5.0

**OS/terminal used**: macOS 10.12, iTerm2

Can't use the output of a subcommand as a command to execute. i.e. (which ls) doesn't work like other shells.

## Results
```console
~ $ (which ls)
Illegal command name “(which ls)”
```
but "$(whence ls)" in zsh or "$(which ls)" bash both list the current directory's contents.

**Comment by krader1961** [comment] 2017-02-10 19:05
Duplicate of issue #154. This is by design. We've started work on implementing a fish solution.

Note that you're specific example would normally be done with `command ls` in fish to force the use of the external command by that name rather than a function or builtin.

**Closed by krader1961** 2017-02-10 19:05 UTC
Labels: duplicate

**Comment by soumya92** [comment] 2017-02-10 19:07
The specific example was just that, but good to know this is being worked on. Thanks for the very prompt responses!
