### ISSUE TITLE
Completion does not know about "git switch"

### ISSUE THREAD

**Issue by grossjohann** [fish-shell/fish-shell#6339] opened 2019-11-22 09:31 UTC
I'm running fish version 3.0.2 on macOS Catalina 10.15.1, fish was installed via Homebrew.

It seems that completion does not know about the `git switch` command.  I think it is a pretty recent new feature in git.

I ran `sh -c 'env HOME=$(mktemp -d) fish'`, changed directory to a git repository (I mean the output of `git clone`, not sure if git repository is the right term for this).  Then I typed `git sw` and hit the tab key.  This offered me `git show` and `git show-branch`.  `git switch` was missing.

**Comment by faho** [comment] 2019-11-22 11:05
Fixed in master

**Closed by faho** 2019-11-22 11:05 UTC

**Comment by faho** [comment] 2019-11-23 09:26
Duplicate of #6045
