### ISSUE TITLE
Can't get completions of relative paths to print for empty token completion

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4970] opened 2018-05-10 18:15 UTC
Can anyone shed some light on why this doesn't work?

```fish
sudo touch /usr/local/bin/foo
sudo chmod +x /usr/local/bin/foo # to bypass the command-doesn't-exist no completions check
complete -c foo -f -a '../bar'
complete -C"foo " # prints nothing
complete -C"foo ." # prints ../bar as expected
complete -c foo -f -a 'bar'
complete -C"foo " # prints bar
```

It seems only paths are subject to the "prints nothing if `commandline -ct` is empty" issue?

**Comment by faho** [comment] 2019-04-26 13:01
I'm gonna call this a duplicate of #3707.

**Closed by faho** 2019-04-26 13:01 UTC
Labels: completions, enhancement
