### ISSUE TITLE
Focus events not handled inside binding

### ISSUE THREAD

**Issue by mk12** [fish-shell/fish-shell#9256] opened 2022-10-03 16:37 UTC
### Environment

* fish 3.5.1
* tmux 3.3a
* macOS 12.6
* Terminal.app 2.12.7 (445)
* `TERM` is xterm-256color outside tmux
* `TERM` is tmux-256color inside tmux

### Summary

Fish correctly handles tmux's `^[[O` and `^[[I` focus events most of the time (see #1917). However, it does not when inside another keybinding.

### Correct behavior (no bind)

This works as expected:

```
echo "
set -g default-command 'env HOME=\$(mktemp -d) fish'
set -g focus-events on
" > tmux_config
tmux kill-server
tmux -f tmux_config new -s test
# In tmux:
/bin/cat -v
# Enter 'C-b %' to split pane
# Enter 'C-b o' several times
# No control characters appear anywhere.
```

[![asciicast](https://asciinema.org/a/525372.svg)](https://asciinema.org/a/525372)

### Incorrect behavior (with bind)

This does not work as expected:

```
echo "
set -g default-command 'env HOME=\$(mktemp -d) fish'
set -g focus-events on
" > tmux_config
tmux kill-server
tmux -f tmux_config new -s test
# In tmux:
bind \co '/bin/cat -v'
# Enter 'C-o' to invoke the binding
# Enter 'C-b %' to split pane.
# Notice '^[[O' appears in first pane.
# Enter 'C-b o' several times.
# Notice '^[[I' appears when entering the first pane and '^[[O' when leaving.
```

[![asciicast](https://asciinema.org/a/525373.svg)](https://asciinema.org/a/525373)

I run into this in practice because my plugin https://github.com/mk12/fish-fzf binds a shortcut to `fzf`. The control characters are appearing in the fzf prompt.

**Comment by faho** [comment] 2022-10-03 18:54
Duplicate of #6942

**Closed by faho** 2022-10-03 18:54 UTC
