### ISSUE TITLE
echo'ing from fish generates 1 byte writes which breaks interaction with some kernel interface files

### ISSUE THREAD

**Issue by htejun** [fish-shell/fish-shell#7978] opened 2021-05-06 15:45 UTC
## Summary

In recent versions (first noticed on 3.2.1), fish generates 1-byte writes when redirecting echo to a file. Some linux kernel interface files consider single write operation as configuration unit and fails on 1 byte writes.

The following is a part of strace trace of `echo '259:4 enable=1' > /sys/fs/cgroup/io.cost.qos`.
```
openat(AT_FDCWD, "/sys/fs/cgroup/io.cost.qos", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 7
write(7, "2", 1)                        = -1 EINVAL (Invalid argument)
write(2, "write: Invalid a", 16)        = 16
write(2, "rgument\n", 8)                = 8
close(7)                                = 0
```

Running the same command in bash:
```
openat(AT_FDCWD, "/sys/fs/cgroup/io.cost.qos", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
fcntl(1, F_GETFD)                       = 0
fcntl(1, F_DUPFD, 10)                   = 10
fcntl(1, F_GETFD)                       = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 1)                              = 1
close(3)                                = 0
write(1, "259:4 enable=1\n", 15)        = 15
dup2(10, 1)                             = 1
fcntl(10, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
close(10)                               = 0
```

## version:
```
root@rbw ~# fish --version
fish, version 3.2.1
root@rbw ~# echo $version
3.2.1
```

## OS and terminal
```
root@rbw ~# uname -a
Linux rbw 5.12.0-rc6-work+ #544 SMP PREEMPT Mon Apr 5 12:54:23 EDT 2021 x86_64 GNU/Linux
root@rbw ~# echo $TERM
screen
```
tmux connected thought mosh from iterm2 on mac.

## Custom modules / configuration
No custom configuration and the vanilla run shows the same behavior.

**Comment by faho** [comment] 2021-05-06 15:49
Duplicate of #7836

**Closed by faho** 2021-05-06 15:49 UTC
