### ISSUE TITLE
Parsing of multiple stream redirections leads to unexpected results

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4416] opened 2017-09-19 01:31 UTC
Using both `1>|` and `2>|` in the same command results breaks redirections:

```fish
~> fish -c "echo stdout; echo stderr 1>&2"
stdout
stderr

~> fish -c "echo stdout; echo stderr 1>&2" 1>| egrep nostdout
stderr

~> fish -c "echo stdout; echo stderr 1>&2" 2>| egrep nostderr
stdout

~> fish -c "echo stdout; echo stderr 1>&2" 1>| egrep nostdout 2>| egrep nostderr
stderr
```

I think everything after the first `1>|` is considered part of the redirection of stdout and not parsed as belonging to the original command.

Attempts at reordering the redirections are futile:

```fish
~> fish -c "echo stdout; echo stderr 1>&2" | egrep nostdout 2>| egrep nostderr
stderr

~> fish -c "echo stdout; echo stderr 1>&2" 2>| egrep nostderr | egrep nostdout
stdout
```

**Comment by krader1961** [comment] 2017-09-19 03:11
That's how pipelines work. Once you introduce a pipe everything to its right, including redirections, apply to that command -- not the command to the left of the pipe. You can't have two `|` instances apply to the same left hand side in any UNIX shell I've ever used. Is there something in the fish docs which suggests what you tried should work? If so it should be reworded.

The only way to do what you're attempting is to jump through some hoops. In bash you would solve this as documented in this [stackoverflow question](https://stackoverflow.com/questions/9112979/pipe-stdout-and-stderr-to-two-different-processes-in-shell-script). I can't think of a way to achieve the same result in fish script. It might be worth turning this into an enhancement request to discuss how to make that result possible but this is not a bug as implied by the first comment and subject line.

**Comment by faho** [comment] 2017-09-19 11:56
@krader1961 is correct. You're misunderstanding how the pipes group here.

Let's translate your calls:

>~> fish -c "echo stdout; echo stderr 1>&2"

The string "stdout" goes to fish's stdout, the string "stderr" goes to fish's stderr. Both are not redirected, so they go to the terminal.

>~> fish -c "echo stdout; echo stderr 1>&2" 1>| egrep nostdout

Fish's stdout is redirected to egrep, which filters the "stdout" line (since it doesn't match). Egrep's stdout (and stderr) _and fish's stderr_ are not redirected, so they go to the terminal.

>~> fish -c "echo stdout; echo stderr 1>&2" 2>| egrep nostderr

Fish's stderr is redirected to egrep, which filters it.

Egrep's output _and fish's stdout_ are not redirected.

>~> fish -c "echo stdout; echo stderr 1>&2" 1>| egrep nostdout 2>| egrep nostderr

Fish's stdout is redirected to the first egrep, which filters the "stdout" line.

The first egrep's stderr goes to the second egrep - but since it prints nothing, the second egrep does nothing.

Fish's stderr, the first egrep's stdout and the second egrep's stdout and stderr are not redirected, so they print to the terminal.

So we see "stderr" on the terminal.

What you expect here is that the second pipe also applies to `fish`, but that's not how that groups.

You can, in this case, achieve the desired result with

```fish
begin
   fish -c 'echo stdout; echo stderr 1>&2' | egrep nostdout
end 2>| egrep nostderr
```

though this will redirect stderr from both fish and the first egrep, which doesn't matter in this case - the first egrep shouldn't error here.

The ability to redirect stdout and stderr to pipes separately is something shells have struggled with - it pretty much requires messing with file descriptors.

-----

What interests me here: What do you need this for?

**Comment by mqudsi** [comment] 2017-09-19 17:03
@faho Yeah, I had deduced what was going on, but thanks for the explanation. The `begin ... end` hack is awesome, that probably takes care of a lot of the cases.

My case was simple, I wanted to wrap `find` to always hide errors (`/path/something: access denied`, anyone?) _except_ if stdout was empty.

So 

```
/path/file1
/path/subdir: access denied #on stdout
/path/file3
```

would be transformed to

```
/path/file1
/path/file3
```

but 

```
-v is not a valid parameter #on stdout
````

would print the same thing post-filtering.


With your begin/end hack, I came up with this:

```fish
function find
	set -l find (which gfind > /dev/null; and echo gfind; or echo find;)
	set -l stderr ""
	set -l has_stdout 0
	begin
		#use fish -c to work around #4415
		fish -c "$find $argv" | while read -l line
			echo stdout: $line
			if not echo $line | string match ""
				set -l has_stdout 1
			end
		end
	end 2>| while read -l errline
		set stderr $errline\n
	end
	set stderr |
	if test $has_stdout -eq 0
		echo -n stderr: $stderr 1>&2
	end
end
```

But this suffers from #4415 (which is why the entire script is so convoluted in the first place) because the `stdout` output of the `begin/end` block is buffered in its entirety before being printed.

**Comment by mqudsi** [comment] 2017-09-19 17:14
I can of course work around it by writing directly to the terminal (`echo stdout: $line` becomes `echo stdout: $line > /dev/tty`) but that's a nasty hack.

**Comment by faho** [comment] 2018-05-11 15:08
I don't think there's anything to do here, so I'm closing.

**Closed by faho** 2018-05-11 15:08 UTC
Labels: question
