### ISSUE TITLE
Execute command on startup?

### ISSUE THREAD

**Issue by egasimus** [fish-shell/fish-shell#1527] opened 2014-07-03 19:07 UTC
It's inconvenient to modify `config.fish` for one-time commands, and `fish -c` exits once the command is done. Is there an idiomatic way of starting a command in Fish, but keeping the shell running after it's done? Even something as simple as setting the start directory with `sh -c 'cd /tmp && fish'` doesn't seem to work, and I was actually hoping I would be able to go beyond that and start a console application which exits to Fish when it's done.

**Comment by fzakaria** [comment] 2015-10-08 23:03
I used the following

    eval jenv init - > /dev/null 2>&1

**Comment by ofek** [comment] 2017-09-10 03:59
Any progress on this?

**Comment by mqudsi** [comment] 2017-09-10 04:05
The example in the original post `sh -c 'cd /tmp && fish'` now works (shell does not exit, accepts input).

This can probably be closed.

**Comment by krader1961** [comment] 2017-09-10 04:08
This is a duplicate of #4164 which has been implemented and will be in the upcoming 2.7.0 release.

**Closed** 2017-09-10 15:14 UTC
Labels: enhancement
