### ISSUE TITLE
`git add` + TAB completion not showing dotfiles

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#5652] opened 2019-02-13 02:29 UTC
fish 3.0.0 && 3.0.1
git version 2.20.1
Linux archlinux 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
xterm-256color
Tried `sh -c 'env HOME=$(mktemp -d) fish'`

I could have sworn that a `git add <string>` + TAB would bring up some options, the kind prefixed with `:/` but lately that hasn't been happening anymore. I can do a `git add :/` + TAB and it will show me some options but not the fuzzy matching I am used too. `git add` + TAB does nothing, which I remember used to give me options too. 

Not sure this is actually a bug but would like someone to at least validate the behavior I am looking for did or did not exist. 

relevant links I scanned:
https://github.com/fish-shell/fish-shell/commits/master/share/completions/git.fish
#5229
#5574

**Comment by ElijahLynn** [comment] 2019-02-13 02:37
Hrm, okay, maybe 3.0.1 did fix this. I had tested with a dot file for 3.0.1 and didn't start the filename with a dot. And `git add` + TAB does show options just not dot file options (bug or by design?). 

3.0.0 definitely didn't do this, and I just updated but had already staged my non-dotfile. So it does appear 3.0.1 works. Yay!

I'll leave this open to see if a `git add`+ TAB should pickup dotfiles. A `git checkout` + TAB does pickup dotfiles so the behaviour is a bit inconsistent. I would personally like to see `git add` pick up dotfiles.

**Comment by ElijahLynn** [comment] 2019-02-13 02:39
Changed title for now. 

To summarize:
`git add` + TAB doesn't show any dotfile options
`git add <string>` doesn't fuzzy match dot files, must start with a `.`

Is this by design?

**Comment by floam** [comment] 2019-02-13 04:03
Completions hide files starting with `.` unless you look for them, it happens the same for `git` as it would `ls` in your home directory. `git add .` + <TAB> should show you stuff.

**Comment by ElijahLynn** [comment] 2019-02-13 04:08
Thanks for confirming that. From a developer experience perspective it makes sense `git add` _should_ include dot files because it is in version control and it changed so I will want to commit it at some point. Why would I _not_ want the dotfile I just changed suggested?

**Comment by floam** [comment] 2019-02-13 04:11
Yes, I agree, because we're dealing with a whittled down subset of the files, it would make sense to see the dot file without the first character typed. However, that's basic behavior of the completion pager and not something the git completions could change (as far as I know) without some changes to nitty gritty fish internals.

**Comment by floam** [comment] 2019-02-13 04:15
(or, just spitballing, maybe it could be done with less fuss across the board, depending on the number of completions there are. Like, under 5, the pager will always also show dot files? I'm not too sure about that though.)

**Comment by faho** [comment] 2019-02-13 08:33
Duplicate of #3707

**Closed by faho** 2019-02-13 08:33 UTC

**Comment by ElijahLynn** [comment] 2019-02-13 17:23
Thanks
