### ISSUE TITLE
Lots of issues with Vim bindings, especially around newlines or character movement

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8189] opened 2021-07-30 23:43 UTC
fish 3.3.1

(Note: I'm using "yank" here the way Vim does, to mean copying text into the killring; fish input functions use "yank" to mean the opposite)

I've already filed two issues about problems around newlines (#8188 and #8186). But there are plenty more issues. For example, in Vim, <kbd>yh</kbd> at the start of a line selects the last character from the previous line (and moves the cursor to that character). In fish, it yanks the newline instead. It also doesn't move the cursor (regardless of newline).

<kbd>yl</kbd> is similarly broken. Not only does it move the cursor when it shouldn't, it also copies the newline (in Vim it copies nothing, instead clearing the killring; this is true even if `whichwrap` contains `h,l`).

<kbd>$</kbd> leaves the cursor in the one-past-the-last spot. This is very surprising. In Vim it always leaves the cursor on the last character (backing up if the cursor was on the one-past-the-last spot). Not strictly related to newlines except in that the one-past-the-last spot represents the newline.

<kbd>dd</kbd> on the last line does not remove the newline, leaving the cursor at the start of a blank line. In Vim it removes the newline too. Similarly, in fish it yanks text that contains no newline, whereas in Vim the yanked text contains a trailing newline as expected. The Vim model here is that every line ends in a newline, including the last one, and that you only have a blank line at the end of the buffer if the buffer ends in two newlines. So in Vim, <kbd>dd</kbd> on the last line removes the line and its trailing newline, and as the buffer now only has one trailing newline there's no empty line at the end either. Fish doesn't have this model, though it does have one-past-the-end on all lines. The Vim bindings need to understand and reproduce this model, otherwise it's very confusing. So in this case, <kbd>dd</kbd> (or more likely the `kill-whole-line` input function) needs to always ensure there's a trailing newline on the yanked text and, if the killed line did not have a newline, it needs to remove the preceding newline.

<kbd>x</kbd> (and <kbd>Del</kbd> or `-k dc`) also has weird problems. In the default bindings it's just `delete-char`. But in the vim bindings its `delete-char forward-single-char backward-char`. I can't figure out why it's written this way; the net effect is it normally acts like `delete-char` except when the cursor is at the end of the input. If the input has an autosuggest, then it actually adds the first character of the autosuggest to the input. By that I mean if I have something like:

<pre><code>echo <b>|</b><ins>autosuggest</ins></code></pre>

and I press <kbd>x</kbd> or <kbd>Del</kbd> then I end up with

<pre><code>echo <b>|</b>a<ins>utosuggest</ins></code></pre>

Note how it's now converted the `a` to normal text. A subsequent <kbd>x</kbd> or <kbd>Del</kbd> then deletes it. This is true for <kbd>Del</kbd> in insert mode as well.

These are just what I've found with quick experimentation. Checking out the bindings I see a lot of uses of `forward-single-char` in the Vim bindings and I'm rather skeptical of whether any of these are correct. The only one I actually tested was <kbd>&#x7e;</kbd> (`togglecase-char forward-single-char`) which does indeed behave surprisingly at autosuggest. In particular, it tries to toggle the case before accepting the char, meaning that if I hit <kbd>&#x7e;</kbd> while at the end of input with autosuggest, it accepts one autosuggest char without toggling case. I'm not sure whether it should just not accept autosuggest at all (which probably requires some sort of `forward-char-no-autosuggest` input function), or whether it should accept one character and toggle its case (which will most likely clear autosuggest).

I'm certain there are lots more issues like this, but I think I've listed enough, and I'm not inclined to test every single binding.

**Comment by ridiculousfish** [comment] 2021-07-31 02:41
Yes the vim bindings don't receive a lot of love, as none of the regular committers use them. I'd like to incorporate zsh's zle vim bindings, but it's certainly not trivial.

**Comment by faho** [comment] 2021-07-31 05:32
Honestly, sometimes I want to remove the entire thing and replace it with one issue "Bring back vi-mode".

The amount of annoyance it's caused and the comparative lack of patches isn't worth it for something I have zero interest in.

**Comment by lilyball** [comment] 2021-07-31 06:56
Surely some user must have built their own workable set of vi bindings, I wish we could just encourage them to donate them.

**Comment by faho** [comment] 2021-07-31 07:22
I don't see any indication of that being the case and I don't believe imagining that is in any way productive.

**Comment by faho** [comment] 2024-02-06 16:49
I'm closing this because it's an awkward omnibus issue that tracks five different things.

I cannot reproduce the `dd` issue, I see the bindings for `x` and `yl` have changed and the issue of the cursor being off is #10286.

**Closed by faho** 2024-02-06 16:49 UTC
Labels: vi-mode
