### ISSUE TITLE
Vi mode word separators should not include underscore.

### ISSUE THREAD

**Issue by dpacbach** [fish-shell/fish-shell#7098] opened 2020-06-08 22:11 UTC
Fish version: 3.1.0.
OS: Linux

When in vi mode, the underscore appears to be considered a word boundary, so that e.g. when I hit 'w' it stops on underscores.  This is making vi mode hard to use for me because vi itself does not consider underscore to be a word boundary.  Can we change this?  Thanks

**Comment by faho** [comment] 2020-06-14 07:32
Duplicate of #3285

**Closed by faho** 2020-06-14 07:32 UTC
