### ISSUE TITLE
tmuxinator autocomplete crash

### ISSUE THREAD

**Issue by vicmunoz** [fish-shell/fish-shell#9188] opened 2022-09-08 08:03 UTC
❯ fish --version
fish, version 3.4.1
❯ uname -a
Darwin Victors-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64
❯  echo $TERM
screen-256color

tmuxinator plugin autocompletes with subcommands and tmuxinator sessions saved as config files.

Some times with TAB to show, autocomplete it crashes

An example:

```
❯ tmuxinator apcomplete: too many arguments

~/.config/fish/completions/tmuxinator.fish (line 17):
complete -f -c $__fish_tmuxinator_program_cmd                                                -a '(__fish_tmuxinator_program completions start)'
^
from sourcing file ~/.config/fish/completions/tmuxinator.fish
in command substitution

(Type 'help complete' for related documentation)
complete: too many arguments

~/.config/fish/completions/tmuxinator.fish (line 18):
complete -f -c $__fish_tmuxinator_program_cmd -n '__fish_use_subcommand'                  -x -a "(__fish_tmuxinator_program commands)"
^
from sourcing file ~/.config/fish/completions/tmuxinator.fish
in command substitution

(Type 'help complete' for related documentation)
complete: too many arguments

~/.config/fish/completions/tmuxinator.fish (line 19):
complete -f -c $__fish_tmuxinator_program_cmd -n '__fish_tmuxinator_using_command start'     -a "(__fish_tmuxinator_program completions start)"
^
from sourcing file ~/.config/fish/completions/tmuxinator.fish
in command substitution

(Type 'help complete' for related documentation)
complete: too many arguments

~/.config/fish/completions/tmuxinator.fish (line 20):
complete -f -c $__fish_tmuxinator_program_cmd -n '__fish_tmuxinator_using_command open'      -a "(__fish_tmuxinator_program completions open)"
^
from sourcing file ~/.config/fish/completions/tmuxinator.fish
in command substitution

(Type 'help complete' for related documentation)
complete: too many arguments

~/.config/fish/completions/tmuxinator.fish (line 21):
complete -f -c $__fish_tmuxinator_program_cmd -n '__fish_tmuxinator_using_command copy'      -a "(__fish_tmuxinator_program completions copy)"
^
from sourcing file ~/.config/fish/completions/tmuxinator.fish
in command substitution

(Type 'help complete' for related documentation)
complete: too many arguments

~/.config/fish/completions/tmuxinator.fish (line 22):
complete -f -c $__fish_tmuxinator_program_cmd -n '__fish_tmuxinator_using_command delete'    -a "(__fish_tmuxinator_program completions delete)"
^
from sourcing file ~/.config/fish/completions/tmuxinator.fish
in command substitution

(Type 'help complete' for related documentation)
```

**Comment by faho** [comment] 2022-09-08 08:14
These aren't our completions - that's why they are in ~/.config/fish/completions/tmuxinator.fish.

They are carried by tmuxinator, so that's where the bug needs to be reported.

Duplicate of https://github.com/tmuxinator/tmuxinator/issues/857

**Closed by faho** 2022-09-08 08:14 UTC
