### ISSUE TITLE
Implementation $CMD_LAST variable

### ISSUE THREAD

**Issue by xdudi** [fish-shell/fish-shell#1430] opened 2014-04-25 19:08 UTC
I write small script in fish and i have construction like this one:
`ls | grep "xxxx" | sort | wc -l; check_error`
And i have problem, how get last executed command. Function check_error should check status and if is nonzero, should print last command to log (`echo $history[1]` doesn't work in script).

**Comment by krader1961** [comment] 2017-03-21 04:25
This is essentially a duplicate of #2039 since what is being asked for requires a way to determine the status of each command in a pipeline.

**Closed by krader1961** 2017-03-21 04:25 UTC
Labels: duplicate
