### ISSUE TITLE
Support for history-beginning-search-{forward,backward}

### ISSUE THREAD

**Issue by padde** [fish-shell/fish-shell#1072] opened 2013-10-29 14:36 UTC
Fish allows to bind keys to `history-search-forward` and `history-search-backward` (among others). One useful addition that I personally prefer which is available in ZSH is `history-beginning-search-forward` and `history-beginning-search-backward`. These will only loop through the lines starting with the text in front of the cursor.

**Comment by faho** [comment] 2016-04-04 18:15
This is a duplicate of #992.

**Closed by faho** 2016-04-04 18:15 UTC
