### ISSUE TITLE
Fish completions, function with same name

### ISSUE THREAD

**Issue by FabioAntunes** [fish-shell/fish-shell#3158] opened 2016-06-20 10:46 UTC
I'm having a hard time with completions and a function I have created. 

```
function npm -d "node package manager"
  __nvm_run "npm" $argv
end
```

So this function basically calls `__nvm_run` checks if nvm has already sourced node, if not sources it and then runs npm, if node is already sourced then it just runs npm.

That function creates this issue https://github.com/fish-shell/fish-shell/issues/3152

If I change the function to this:

```
function npm -d "node package manager" -c npm -w npm
   echo "This won't run"
  __nvm_run "npm" $argv
end
```

The completions works fine, but the function it's not called anymore.

any help?

**Comment by faho** [comment] 2016-06-20 11:06
The latter is a broken function definition - there's no "-c" option to "function", so the definition is invalid. That it doesn't print an error is #2827 (though it appears it also applies to short options, despite what the title says).

The rest is #3152, so I'll close this as a duplicate of that, and it seems that the blame lies with the `__nvm_run` function.

**Comment by FabioAntunes** [comment] 2016-06-20 11:16
I'm sorry but I don't think there's something wrong with my function, if you create a function like this:

```
function npm -d "node package manager" -w npm
  command npm $argv
end
```

You wil get the same result from https://github.com/fish-shell/fish-shell/issues/3152

**Comment by FabioAntunes** [comment] 2016-06-20 11:27
In fact if I create a function with a different name let's say npm2, everything works fine:

function npm2 -d "node package manager" -w npm
  __nvm_run "npm" $argv
end

**Comment by FabioAntunes** [comment] 2016-06-20 12:20
@faho I submited a pull request that fixes the issue with completions

**Closed** 2016-06-21 10:07 UTC
