### ISSUE TITLE
Alias doesn't preserve stdin behavior of string command

### ISSUE THREAD

**Issue by xixixao** [fish-shell/fish-shell#6195] opened 2019-10-12 03:17 UTC
fish, version 3.0.2
Linux <redacted><redacted> x86_64 x86_64 x86_64 GNU/Linux
screen-256color

Repro:
```fish
# in fish
alias rep 'string replace'
echo a | rep a b
# no output
```
while I expected `b`, which is the output of:
```fish
# in fish
echo a | string replace a b
# prints `b`
```

Now to be sure, this also doesn't work:
```fish
# in fish
alias rep 'string replace a b'
echo a | rep
# no output
```

But this does:

```fish
# in fish
alias rep 'perl -pi -w -e s/a/b/'
echo a | rep
# prints `b`
```

**Comment by faho** [comment] 2019-10-13 12:34
`alias` has nothing to do with it.

`alias` creates a function, and string refuses to read from stdin unless it's "directly redirected".

Which means this is a duplicate of #5714.

**Closed by faho** 2019-10-13 12:34 UTC
