### ISSUE TITLE
setpgid: Operation not permitted on fish shell 2.7.1 / ubuntu 16.04 / invoked from fisher + fzf plugin

### ISSUE THREAD

**Issue by arooni** [fish-shell/fish-shell#4776] opened 2018-03-03 20:16 UTC
ENV:
fish shell 2.7.1
Linux brazil 4.14.17-x86_64-linode99 #1 SMP Tue Feb 6 19:09:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
screen-256color

 1. install fisher
2. install fzf plugin
3. hit control r to pull up reverse search;
4. select any term.
5. see error message below:

```
Could not send process 23992, '__fzfcmd' in job 2, 'history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r ' from group 30993 to group 23717
setpgid: Operation not permitted
Could not send job 2 ('history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r ') to foreground
tcsetpgrp: No such process
ls
<W> fish: Could not send job 2 ('history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r | read -l select') to foreground
tcsetpgrp: No such process
```

ideas?  thanks very much

**Comment by arooni** [comment] 2018-03-03 20:18
Related to #4715

**Comment by zanchey** [comment] 2018-03-04 05:07
I don't think this is related to #4715, as the changes that caused that problem landed after fish 2.7.1.

Could you show the output of:

```
bind \cr
type __fzfcmd
```

**Comment by zanchey** [comment] 2018-03-04 05:08
If there's any way you can try a development build, a lot of this stuff has been changed in development versions - for Ubuntu you can use https://launchpad.net/~fish-shell/+archive/ubuntu/nightly-master

**Comment by arooni** [comment] 2018-03-04 18:57
[I]  brazil ÓÇ∞ /v/w/m/wp-content ÓÇ∞ bind \cr
bind \cr __fzf_ctrl_r

[I]  brazil ÓÇ∞ /v/w/m/wp-content ÓÇ∞ type __fzfcmd

__fzfcmd is a function with definition
# Defined in /home/david/.config/fish/functions/__fzfcmd.fish @ line 1
function __fzfcmd
    set -q FZF_TMUX
    or set -l FZF_TMUX 0
    if test "$FZF_TMUX" -eq 1
        set -q FZF_TMUX_HEIGHT
        or set -l FZF_TMUX_HEIGHT 40%
        fzf-tmux -d$FZF_TMUX_HEIGHT $argv
    else
        fzf $argv
    end
end

**Comment by arooni** [comment] 2018-03-04 19:08
@zanchey thanks for that handy link to the PPA.  I went ahead and added it, updated it, and this error no longer occurs.. yay!

So maybe you can mark this as closed.

As a quick aside:
1) Is it safe to be running this development version of fish on a production server? 
2) [slightly off topic] TO move away from this development version of fish to the next final release, is it enough to remove the nightly PPA from my /etc/apt/sources.list.d/ and then when i'm running apt update & apt upgrade ubuntu can find that the next production release is more recent than the development build I have ?  

Thanks!

**Comment by mqudsi** [comment] 2018-03-05 01:40
@zanchey I was going to suggest a 2.7.2 with this patch backported, but then #4778 happened 😄

I'll probably stick an `if (wsl) ..` in there until the root cause is fixed and keep this solution as-is; I'm glad to finally have `exec_job` making some semblance of sense.

**Comment by zanchey** [comment] 2018-03-15 14:17
I suppose it depends on what you mean by production server - I run head builds of fish on my production machines, but if something explodes and takes out the filesystem nobody dies or loses any money, so you need to make your own risk assessment!

To answer your second question, yes, that should work - although the fish 3.0 release will likely come from a different PPA (not `release-2` but `release-3`) well before it lands in Ubuntu.

**Closed by zanchey** 2018-03-15 14:17 UTC
