### ISSUE TITLE
Event handlers don't work

### ISSUE THREAD

**Issue by bakhtiyarneyman** [fish-shell/fish-shell#7696] opened 2021-02-08 09:10 UTC
I am running a simple script with a bunch of event handlers that should echo something, but nothing echoes.

Commands:
```
$ fish --version
fish, version 3.1.2
$ uname -a
Linux titanium 5.9.16 #1-NixOS SMP Mon Dec 21 12:28:21 UTC 2020 x86_64 GNU/Linux
$ echo $TERM
xterm-termite
$ sh -c 'env HOME=$(mktemp -d) fish'
$ fish ./script.fish
^C⏎   
$
```

script.fish:

```
function fish_exit_handler --on-event fish_exit
  echo "fish exit"
end
function fish_cancel_handler --on-event fish_cancel
  echo "fish cancel"
end

function SIGHUP_handler --on-signal SIGHUP
  echo "SIGHUP"
end
function SIGINT_handler --on-signal SIGINT
  echo "SIGINT"
end
function SIGQUIT_handler --on-signal SIGQUIT
  echo "SIGQUIT"
end
function SIGABRT_handler --on-signal SIGABRT
  echo "SIGABRT"
end
function SIGKILL_handler --on-signal SIGKILL
  echo "SIGKILL"
end
function SIGTERM_handler --on-signal SIGTERM
  echo "SIGTERM"
end
function SIGSTOP_handler --on-signal SIGSTOP
  echo "SIGSTOP"
end


trap "echo 'trap SIGHUP'" SIGHUP
trap "echo 'trap SIGINT'" SIGINT
trap "echo 'trap SIGQUIT'" SIGQUIT
trap "echo 'trap SIGABRT'" SIGABRT
trap "echo 'trap SIGKILL'" SIGKILL
trap "echo 'trap SIGTERM'" SIGTERM
trap "echo 'trap SIGSTOP'" SIGSTOP

sleep 10000
```

**Comment by faho** [comment] 2021-02-08 09:22
Duplicate of #6649

**Closed by faho** 2021-02-08 09:22 UTC
