### ISSUE TITLE
Cannot bind up arrow in insert mode when using `fish_vi_key_bindings`

### ISSUE THREAD

**Issue by mrjones2014** [fish-shell/fish-shell#8554] opened 2021-12-16 15:35 UTC
- Fish version: fish, version 3.3.1
- OS: macOS 12.0.1
- `uname -m` outputs `arm64`
- `$TERM` is `xterm-kitty`

I'm trying to use [atuin](https://github.com/ellie/atuin). One setup step is to add `atuin init fish | source` to `config.fish` which sets up some key binds.

```
# workaround for https://github.com/fish-shell/fish-shell/issues/3481
function fish_vi_cursor
end
fish_vi_key_bindings
# jk to go to normal mode
bind -M insert jk "if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char force-repaint; end"

# I also tried putting this line inside the `fish_user_key_binds` function
# also tried putting it inside an `if status is-interactive` block
# this line tries to bind up arrow to trigger the atuin finder
atuin init fish | source
```

With this config, the up arrow key bind works from vi normal mode, but not from insert mode. Adding an explicit `bind -k up --mode insert '_atuin_search'` does not fix the issue either. The key binds work correctly if you don't use vi mode (comment out the whole top block in the config above, then run `fish_default_key_bindings`, then restart shell).

Here's the fish code that `atuin init fish` outputs:

```

set -gx ATUIN_SESSION (atuin uuid)
set -gx ATUIN_HISTORY (atuin history list)

function _atuin_preexec --on-event fish_preexec
    set -gx ATUIN_HISTORY_ID (atuin history start "$argv[1]")
end

function _atuin_postexec --on-event fish_postexec
    set s $status
    if test -n "$ATUIN_HISTORY_ID"
        RUST_LOG=error atuin history end $ATUIN_HISTORY_ID --exit $s &; disown
    end
end

function _atuin_search
    set h (RUST_LOG=error atuin search -i (commandline -b) 3>&1 1>&2 2>&3)
    commandline -f repaint
    if test -n "$h"
        commandline -r $h
    end
end

if test -z $ATUIN_NOBIND
    bind -k up '_atuin_search'
    bind \eOA '_atuin_search'
    bind \e\[A '_atuin_search'
end
```

**Comment by faho** [comment] 2021-12-16 16:05
Duplicate of #8428

**Closed by faho** 2021-12-16 16:05 UTC

**Comment by mrjones2014** [comment] 2021-12-16 16:11
@faho sorry, maybe I'm missing something. What is the fix here? That issue is closed but I don't see how it's resolved?

**Comment by IlanCosman** [comment] 2021-12-16 16:14
@mrjones2014 Will be fixed in 3.4 is what he's saying.

**Comment by mrjones2014** [comment] 2021-12-16 16:16
Ah okay gotcha. Any release timeline?

**Comment by IlanCosman** [comment] 2021-12-16 16:18
Looks like it will be soon, but no concrete dates.
