### ISSUE TITLE
sudo !! not working on FISH shell

### ISSUE THREAD

**Issue by NabarajDhungel01** [fish-shell/fish-shell#9290] opened 2022-10-19 10:02 UTC
I am using the fish version 3.5.1 .
When i want to use the " sudo !! " command it wont work.
What the command actually does is when you want to execute the previous command
with sudo ( in other shell using sudo !! ) work...

How to create the issue?
1. Run " apt install package " ( will say permission denied , )
2. Run " sudo !! " ( sudo !! not found is shown)

It should run the command " sudo apt install package " when running the command " sudo !! "

It shows the error like this ...
I am using the fish version 3.5.1 .
When i want to use the " sudo !! " command it wont work.
What the command actually does is when you want to execute the previous command
with sudo ( in other shell using sudo !! ) work...

How to create the issue?
1. Run " apt install package " ( will say permission denied , )
2. Run " sudo !! " ( sudo !! not found is shown)

It should run the command " sudo apt install package " when running the command " sudo !! "

It shows the error like this ...
![image](https://user-images.githubusercontent.com/76202384/196661114-af3fe1f0-208b-41de-8344-fac11dbacb2d.png)

**Comment by faho** [comment] 2022-10-19 10:38
Please [read the FAQ](https://fishshell.com/docs/current/faq.html#why-doesn-t-history-substitution-etc-work) or search for duplicates.

This is a feature we have intentionally not included. Just press alt+s to prefix your previous command with `sudo` (or `doas` if you use that).

Closing as a duplicate of #9169.

**Closed by faho** 2022-10-19 10:38 UTC
