### ISSUE TITLE
Lost command history after power outage

### ISSUE THREAD

**Issue by splatch** [fish-shell/fish-shell#4942] opened 2018-04-25 21:43 UTC
Hi
I am (or I was - depending on this issue) happy user of fish since almost a year. Today my neighborhood had short power outage due to heavy rain and wind. This isn't something unusual - it was happening before few times.

What changed this time is that after launching my computer (it's desktop) back, I started navigating to usual places where I do commands. I found that completion doesn't work. I started looking for history and it turned out that it's empty and contains only entries from session I've launched.

Version details
fish --version: 2.7.1
System: Linux arch 4.16.3-1-MANJARO (updated April 19th)
$TERM: xterm-color / terminator

I am completely lost because I have no idea what happened with history file and why it might be empty. Is there a way to recover past history? I have no issues with display nor anything else.

**Comment by faho** [comment] 2018-04-30 19:07
>I am completely lost because I have no idea what happened with history file and why it might be empty.

I'm not sure either. What fish does is to write the entire history to a new temporary file, then move it into place (via `rename(3)`).

Which is what I've always heard suggested as the thing to do.

So, as much as I hate to say it: It seems to me like this might be a filesystem or even hardware issue (though I could obviously be wrong). @ridiculousfish might have more to say.

>Is there a way to recover past history?

Not unless you can recover the old file. Fish doesn't store multiple copies because this shouldn't happen to begin with.

**Comment by faho** [comment] 2018-09-15 09:12
No new information in quite a while, closing!

**Closed by faho** 2018-09-15 09:12 UTC
Labels: needs more info, question

**Comment by splatch** [comment] 2023-08-17 16:29
Its been quite a while since I reported this issue, today I experienced it again. I am not sure why, cause this time I had to terminate my desktop (hanged system). I made system upgrade after which I realized that I lost fish history. I checked both: `~/.config/fish` and `~/.local/share/fish/`, there are not remarks of stale or backup file.
Interestingly enough I do not remember any message from fish during bootstrap about any issues with history file being corrupted.

**Comment by jesseskinner** [comment] 2024-10-02 17:26
Adding in case it's helpful to anyone: I had the same thing happen, my history disappearing after a power loss.

I found my complete 1.5mb history in `~/.local/share/fish/fish_history` though, fortunately. But it still wasn't auto-completing. I edited the file (with nano) and found a bunch of ^@^@^@^@ characters at some point near the end of the file, and the completions only included history after that line. I deleted that line and the following line, saved, opened a new fish shell and it was fixed!

Hope that helps someone - or helps the fish developers figure out what might be happening here.

**Comment by EgZvor** [comment] 2024-10-22 07:19
@jesseskinner same thing happened to me after a system update (Arch Linux)

**Comment by fabriziosestito** [comment] 2024-10-29 16:39
@jesseskinner thanks for this! I can confirm the same behavior on Arch Linux after a power outage.

**Comment by rpodgorny** [comment] 2024-12-10 15:25
this keeps happening to me randomly even without power outage. i just spawn new shell and sometimes there's no history. the history file itself is fine. i think we should reopen this.

**Comment by zarkone** [comment] 2025-11-24 17:40
Consistent write is a big issue, especially given that fish writes from multiple processes to the same file. relying on `fsync` solely wouldn't cure this issue entirely, depending on disc controller behaviour and mount options it is not guaranteed to be committed. 

Maybe we could return `Result` here instead of `Option` and `Error` if e.g. `len > 0` here, and other places like this? https://github.com/fish-shell/fish-shell/blob/master/src/history/yaml_backend.rs#L151

So we could at least emit a warning and corrupted line so that it would be clear to user that history is corrupted. Otherwise now history file exists but history is ignored, without any notification.

**Comment by krobelus** [comment] 2025-11-30 06:23
> So we could at least emit a warning and corrupted line so that it
> would be clear to user that history is corrupted.

Yes, that would be a good change (either log directly or return an error).
We already have an on-by-default (error) log for the most common case of corruption
(a history item starting with a NUL byte).
Hopefully that's the only one, and it should be fixed in 4.1. except for hardware failures;
but checking for other cases that should never happen would be a good idea.
Better for a separate issue/PR though.
