### ISSUE TITLE
The man page looks strange

### ISSUE THREAD

**Issue by wimi9u0** [fish-shell/fish-shell#4628] opened 2017-12-29 03:37 UTC
Hello, I'm new to fish and I often read the manual pages for help. I found the format of manual pages from fish is different from others. By the way, I work on macOS High Sierra.
The manual pages in fish are strange:
1. The name section repeat the command, and it looks like:
NAME
       fishfish - the friendly interactive shell
2. The other sections start with one more indents, and it looks like:
NAME
[indent]fishfish - the friendly interactive shell
          -

[indent] Synopsis
[indent][indent]fish [OPTIONS] [-c command] [FILE [ARGUMENTS...]]

[indent]Description
[indent][indent]fish is a ....
These are all detailed problems, but I like fish-shell, I wish it becomes better.

**Comment by krader1961** [comment] 2017-12-29 03:49
Duplicate of #4016.

**Comment by faho** [comment] 2017-12-29 09:49
Yup, and that one's been fixed by 8e93041205b915eeb285c49220d942edf820ba38.

**Closed by faho** 2017-12-29 09:49 UTC
