### ISSUE TITLE
fish hangs if one attempts to source from a non-existing process-substituion

### ISSUE THREAD

**Issue by mattgodbolt** [fish-shell/fish-shell#1938] opened 2015-02-04 18:24 UTC
If one attempts to source the output of a command, and that command doesn't exist, fish hangs and never comes back:

    ~ $ source (notacommand)
    notacommand: command not found
    in command substitution
        called on standard input
    ^C^C^C^C^C^Z^Z^X^C^Z^X^C

Nothing brings it back, and it needs to be hard KILL'ed from another session.

I'm running a build from git:
~ $ fish --version
fish, version 2.1.1-1190-g3974887

**Comment by xfix** [comment] 2015-02-04 21:13
Press CTRL+D. Source was called with no arguments, so it reads from STDIN. As for not reacting to CTRL+C, it's duplicate of #956.

**Closed by xfix** 2015-02-04 21:13 UTC

**Comment by mattgodbolt** [comment] 2015-02-04 21:59
LOL thanks - sorry for the spam :)
