### ISSUE TITLE
Up Key acting weirdly after updating to 3.3.0

### ISSUE THREAD

**Issue by IndianBoy42** [fish-shell/fish-shell#8093] opened 2021-06-29 19:16 UTC
I updated to 3.3.0 earlier today and have found some strange behaviour. This is probably due to my configuration as it doesn't happen with a blank config. But I don't know where it comes from and it didn't happen in 3.2.2

1. (From the title) If I run a command with arguments, and then immediately hit the up key from the next prompt, it behaves as if I am pressing 'Alt+Up', ie it substitutes the argument from the previous command.
 - Any subsequent up arrow presses act 'normal' in that it searches through the history using what was 'entered' in the command line.
 - If I type a character and backspace it before hitting Up on a new prompt then it works normally, substituting the whole previous command
 - If I `Ctrl+C` on the new prompt (or Ctrl+C on some command) then on the next prompt Up arrow presses are normal 
 - The 'k' normal mode bindings from fish_vi_key_bindings always work correctly

2. The prompt doesn't appear immediately when launching a new shell. I have to hit enter or start typing.
 - I have a feeling this is about tide prompt not triggering repaints when it needs to. Did something about this change from the previous fish3.2.2?

**Comment by faho** [comment] 2021-06-29 20:52
Duplicate of #8088

**Closed by faho** 2021-06-29 20:52 UTC
