### ISSUE TITLE
request: add the command "!!" to fish.

### ISSUE THREAD

**Issue by ANDROID2468** [fish-shell/fish-shell#5721] opened 2019-03-05 05:54 UTC
current fish version:3.0.2

Not a lot of people know this, if you type sudo !! in the terminal (under bash) when you forget to run as sudo, it will run the previous command as sudo. It will be nice to see this command in fish!

**Comment by zanchey** [comment] 2019-03-05 06:21
This is a duplicate of #288, which is an epic saga, but thanks for filing.

**Closed by zanchey** 2019-03-05 06:21 UTC
Labels: duplicate
