### ISSUE TITLE
Functions swallow SIGWINCH

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#3180] opened 2016-06-28 20:45 UTC
I have a function that watches for the change of an ENV variable and runs tmux - here it is verbatim:

```
function autotmux --on-variable TMUX_SESSION_NAME
  if test -n "$TMUX_SESSION_NAME" #only if set
    if test -z $TMUX #not if in TMUX
      tmux new-session -t "$TMUX_SESSION_NAME"; or tmux new-session -s "$TMUX_SESSION_NAME"
    end
  end
end
```

I've noticed that tmux run this way doesn't appear to receive SIGWINCH from terminal resizes, especially if they're sudden (as is caused by a tiling WM or maximizing windows etc.) The problem is consistent enough that I've set up keystrokes to `pkill -SIGWINCH tmux`.

On the strength of an issue filed on tmux, I finally looked into the cause being my `autotmux` function, and have just determined that a tmux session started this way exhibits the problem (doesn't resize to match the size of the terminal) and a tmux session run directly does not (i.e. it resizes.)
### Reproduction Steps:
1. Install tmux
2. Save the above as a function
3. `set -x TMUX_SESSION_NAME test`
4. Resize the window - especially with sudden resizes: use a tiling manager, or drag the window to the OS X menu bar etc.
### Expected behavior:

Tmux should resize immediately - the tmux status line should remain the last line of the window and be the correct length.
### Observed behavior:

Tmux behaves as if it hasn't received the SIGWINCH - the status bar remains in the same place relative to the upper left corner of the window.

---

Fish version: [from the output of fish --version]

2.2.0

Operating system: [your operating system and how you installed fish e.g. Homebrew, Ubuntu PPA, distribution package]

OS X, with homebrew, Gentoo and NixOS Linux

Terminal or terminal emulator: [e.g. PuTTy, iTerm2, GNOME Terminal, VT220]

iTerm2, urxvt, (others on Linux, don't remember which ones.)

**Comment by krader1961** [comment] 2016-06-29 00:43
This is almost certainly a manifestation of issue #2980. I would normally close this as a dup but I'm only 98% certain it's the same issue. So leaving it open until I've commited the fix for #2980 and we can confirm it also fixes this issue.

**Comment by zanchey** [comment] 2016-06-29 00:47
My suspicion was on the tmux process not getting assigned the correct controlling TTY, but I haven't been able to prove that.

**Comment by nyarly** [comment] 2016-06-29 17:45
I'm not sure if it's the same as a) the outputs of `stty -a` are the same in either scenario and b) this is in 2.2.0, where #2980 was reported as working as expected.

What I can confirm is that if I complicate my function a little to allow for `exec tmux`, that tmux processes terminal resizes correctly, so I've got a workaround. The behavior is still surprising, and it took me months  to figure out enough to post a useful issue anywhere.

**Comment by krader1961** [comment] 2016-06-29 18:46
> `exec tmux`, that tmux processes terminal resizes correctly

That makes me 99% certain this is the same as #2980. Using `exec` inside a script or function causes fish to set the tty modes and foreground process group in the same way it does if you enter the exec'd command at an interactive prompt. Otherwise it doesn't and you see the type of symptom you're reporting.

**Comment by faho** [comment] 2020-01-24 17:26
Duplicate of #2980

**Closed by faho** 2020-01-24 17:26 UTC
Labels: bug
