### ISSUE TITLE
Allowing commandline -f repaint to be executed synchronously

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#8488] opened 2021-11-25 11:32 UTC
## Fish Version
``` fish
$ fish --version
fish, version 3.3.1
```

## Problem
It seems `commandline -f repaint` cannot be executed immediately inside a function/block. Is there any way to allow repainting to take effect right after the command is fired?

## Examples

``` fish
# fish along
sh -c 'env HOME=$(mktemp -d) fish'

# create a key binding that involving two fzf command
bind \cq 'fzf --height 50%' 'commandline -f repaint' 'fzf --height 50%'

# press <C-q>, the first fzf command is executed
caizheng@caizheng-nuc10i7fnk /h/c/Downloads>git checkout 
>
  3/3
  001.tar
  002.tar
> 003.tar

# after the first fzf command exits, the other fzf command is immediately executed
# but the command line prompt disappear
>
  3/3
  001.tar
  002.tar
> 003.tar


# Can we force repainting the command line
# (preserving both fish prompt and the "git checkout" command)
# right between the two fzf commands?
```

**Comment by faho** [comment] 2021-11-25 11:47
Duplicate of #3031

**Closed by faho** 2021-11-25 11:47 UTC
