### ISSUE TITLE
How to install on debian 9?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5733] opened 2019-03-10 15:11 UTC
On my clean debian 9 container, I follow the installation instructions:
https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish

```shell
apt list -a fish
Listing... Done
fish/unknown 3.0.2-1 amd64
fish/stable,now 2.4.0-1 amd64 [installed]
```

If I try to update it:

```
apt-get install fish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fish is already the newest version (2.4.0-1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
```

I always end up with the 2.4 version...

I even tried this weird thing because i'm confused:

```
apt-get install fish -t unknown
Reading package lists... Done
E: The value 'unknown' is invalid for APT::Default-Release as such a release is not available in the sources
```

How do I install 3.x now that it has been officially released?

EDIT: I can install it with `apt-get install fish=3.0.2-1` but it's not how I want to proceed when I install it automatically (can't know the exact version)

**Comment by BarbzYHOOL** [comment] 2019-03-10 18:16
Found another method but still weird `apt-get install fish -t /`

**Comment by BarbzYHOOL** [comment] 2019-03-11 15:43
Anybody installs fish 3 on debian9?

**Comment by zanchey** [comment] 2019-03-11 15:55
This works for me with a clean checkout.

What does `apt-cache policy fish` tell you?

**Comment by BarbzYHOOL** [comment] 2019-03-11 16:31
```
fish:
  Installed: 3.0.2-1
  Candidate: 3.0.2-1
  Version table:
 *** 3.0.2-1 500
        500 http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_9.0  Packages
        100 /var/lib/dpkg/status
     3.0.2-1 -1
         -1 http://ftp.fr.debian.org/debian testing/main amd64 Packages
         -1 http://ftp.fr.debian.org/debian unstable/main amd64 Packages
     2.4.0-1 990
        990 http://ftp.debian.org/debian stretch/main amd64 Packages
```

But I was forced to install 3.0.2 with `apt-get install fish -t /`, else fish 2.4 was taking 1 second to display a letter when typing.

Should I purge and retry from scratch?

**Comment by zanchey** [comment] 2019-03-12 08:00
Do you have something in /etc/apt/apt.conf like `APT::Default-Release "stable";`?

**Comment by zanchey** [comment] 2019-03-15 15:51
Any luck?

**Comment by BarbzYHOOL** [comment] 2019-03-15 21:32
@zanchey this in a config file

```
APT::Default-Release "stretch";

```

**Comment by zanchey** [comment] 2019-03-26 13:28
Right. That will override the standard preferences; I suggest instead you use `stretch` rather than `stable` in your `/etc/apt/sources.list`.

Anyhow, this all looks like it is working as intended, so I'll close the issue.

**Closed by zanchey** 2019-03-26 13:28 UTC
Labels: question

**Comment by BarbzYHOOL** [comment] 2019-03-28 20:36
I use stretch rather than stable already

**Comment by faho** [comment] 2019-03-28 20:53
@BarbzYHOOL: The issue is that you then also set the default release in apt.conf, so it'll only get the fish package from stretch.
