### ISSUE TITLE
Path completition does not work, if Path contains whitespaces

### ISSUE THREAD

**Issue by slartibartfas** [fish-shell/fish-shell#2650] opened 2016-01-03 17:03 UTC
If a Path contains whitespaces, the completition suggestions acessed with the TAB key, are not correct.
For example if I want to cd to Deutsch/Die\ Physiker/ I get:

$ cd Deutsch/<TAB>
Deutsch/Die   Deutsch/Physiker

The issue also occurs with other commands

**Comment by faho** [comment] 2016-01-03 18:07
This looks to me like a duplicate of #2447 or possibly #2300 - with a dash of issues fixed by #2289 thrown in.

>Die\ Physiker

Dürrenmatt? Surprisingly nice.

**Comment by slartibartfas** [comment] 2016-01-03 19:40
Sorry, after doing a bit of testing and research I finally found that the error was mine. I forgot the backslash when creating the directory. I think I'll help a bit with testing fish as a revance. 

>> Die\ Physiker

> Dürrenmatt? Surprisingly nice.

Yes, great book. Preparing a presentation about it for school.

**Closed** 2016-01-03 19:43 UTC
