### ISSUE TITLE
$last_pid somehow referring to current shell

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7692] opened 2021-02-07 23:30 UTC
Perfectly clean fish 3.1.2

### ⚠️ CAUTION: Set this interactively, or have another method of not loading this on startup

```fish
function fish_prompt
    set -l last_pid_copy $last_pid
    fish --command "kill $last_pid_copy" &
    echo $PWD
end
```

This will kill your Fish instance after you press `Enter` once. I assume that `$last_pid` is somehow set to the current Fish instance for some reason, but I can't imagine how. Interestingly, replacing `$last_pid` with `(jobs --last --pid)` will work just fine.

**Comment by faho** [comment] 2021-02-08 07:07
Ah, okay. So what happens is that the last_"pid" is a bit of a misnomer - because this is for the entire *job*, it's the last p*g*id, which can be shared among multiple processes but is the same number as the lead processes' pid.

Which is all fine and dandy, until fish creates a process that it doesn't assign its own pgroup to, because then it keeps it in fish's pgroup. And the pgid of that is... fish's pid.

So we can reduce this to:

```fish
function fish_prompt
    echo $last_pid $fish_pid
end
```

If the two are equal, `kill` will do what we'll call "the wrong thing".

The "solution" here is to set `status job-control full` - this will assign pgroups to *all* jobs, not just "interactive" ones. We should default to this and eventually remove the knob, but we've been wary of doing this and should do it in the beginning of the cycle - see #5036.

Which I'm now closing this as a duplicate of.

**Closed by faho** 2021-02-08 07:07 UTC
