### ISSUE TITLE
read -s stores sensitive information in history

### ISSUE THREAD

**Issue by dr4Ke** [fish-shell/fish-shell#6438] opened 2019-12-17 08:14 UTC
Issue: when we use `read -s`, it's probably to enter sensitive information. Then the read history contains sensitive information. I suggest to not store `read -s` input to history.

Or add the ability to disable read history without touching the shell history. Currently, I understand we disable history for both by setting `fish_history` to an empty string.

Before that, `read --mode-name /dev/null` could be used but it's now deprecated and ignored. So we either have sensitive information in history (when using `read -s`) or no history at all. Am I wrong?

Versions:

    fish, version 3.0.2
    Linux COMPUTER 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux

Related to #1504, #102

**Comment by faho** [comment] 2019-12-17 08:58
Fixed in master by not storing read history.

**Closed by faho** 2019-12-17 08:58 UTC

**Comment by faho** [comment] 2019-12-17 08:59
Duplicate of #5904
