### ISSUE TITLE
fish shell live demo in a browser

### ISSUE THREAD

**Issue by psviderski** [fish-shell/fish-shell#4385] opened 2017-09-07 21:08 UTC
Hi guys, we've launched a platform that hosts live demos of command line tools in a browser. It makes the process of trying out their features easier for new users.

Please, take a look at this oh my zsh demo: https://rootnroll.com/d/oh-my-zsh. Would you be interested in creating such a one for the fish shell? It might be helpful for new users to be able to instantly play with it in a browser without setting it up.

You can find a Dockerfile that was used to build the oh my zsh demo in this repo: https://github.com/rootnroll/library/tree/master/oh-my-zsh
All you need is to create a similar docker image with a README file and push it to the [Docker Hub](https://hub.docker.com/). Then we will create a demo page based on the provided image.

**Comment by krader1961** [comment] 2017-09-08 03:12
This is basically a duplicate of issue #1604.

Who is "we", @psviderski? The project you linked to has scant documentation and only one example implementation. It also seems to be based on something that hasn't been updated in over [two years](https://github.com/rootnroll/rootnroll-client).

**Comment by psviderski** [comment] 2017-09-08 07:49
@krader1961 Thanks for the link to the related issue! It looks like rootnroll might be useful for fish shell.

We're a small group of enthusiasts working on rootnroll.com. It is already integrated in digital learning environment https://stepik.org. There are some online courses (for now in Russian only) in which students can practice solving problems via Linux command line interface directly in their browsers. Please take a look at this intro lesson with Linux challenges driven by rootnroll: https://stepik.org/lesson/9180.

Now I think rootnoll can be used not only for educational purposes but also for hosting tool demos. You wrote https://github.com/fish-shell/fish-shell/issues/4054#issuecomment-303290828 that you're looking for a free solution. We can make it with a reasonable number of simultaneous online sessions.

**Comment by ridiculousfish** [comment] 2017-09-09 06:49
@psviderski this is very cool, thanks for sharing. Can you describe more about how rootnroll works?

Also what sort of traffic would you consider reasonable? FYI fishshell.com currently gets around ~15k hits per month, with spikes to ~5k hits per day - IMO pretty low.

**Comment by psviderski** [comment] 2017-09-11 18:38
@ridiculousfish In a nutshell, each demo launch starts a new Docker container in our container cloud. Then a web terminal connects to the shell process in the created container. A user gets full root access to their isolated container. Currently it's not possible to create a demo page on your own. We're thinking of creating a panel where you'll be able to manage your demo data.

For now to create your demo you need a repo with `DEMO.md` file in its root (you can use this particular repo or create a separate one) and a Docker image with fish-shell inside. It should be pushed to the public docker hub: https://docs.docker.com/docker-hub/repos/. You can take this [Dockerfile](https://github.com/rootnroll/library/blob/master/oh-my-zsh/Dockerfile) for an example. The `latest` tag of your image will be used for launching demo containers.

We can start with 10 simultaneous sessions that are automatically terminated in 30 minutes. I believe it should be enough for your traffic.

**Comment by psviderski** [comment] 2018-04-03 19:48
Please, check out the playground I created: https://rootnroll.com/d/fish-shell.
It is built from this source: https://github.com/rootnroll/library/tree/master/fish-shell.
Automated build on docker hub: https://hub.docker.com/r/rootnroll/demo-fish-shell/
Any feedback is highly welcome including PRs.
It seems it'll be great to add a link to it on fishshell website to see whether it'd be useful for new potential users.

**Comment by ridiculousfish** [comment] 2018-04-06 03:29
That's awesome! I'll figure out where to add the link. Thanks for doing that!

**Comment by faho** [comment] 2018-11-03 10:44
This has been added in #4887.

**Closed by faho** 2018-11-03 10:44 UTC
Labels: enhancement
