### ISSUE TITLE
golang printf with fish shell

### ISSUE THREAD

**Issue by zscfde** [fish-shell/fish-shell#3941] opened 2017-04-06 09:51 UTC
<img width="376" alt="screen shot 2017-04-06 at 5 45 46 pm" src="https://cloud.githubusercontent.com/assets/20477170/24748168/71d32d48-1af1-11e7-83e9-1a2c882cef10.png">

package main

import (
    "fmt"
)

func main() {
    // k:=1
    fmt.Printf("1")
}

Why it won't print out with printf("1") ? 
But it works in printf("1 ") with a space.

**Comment by faho** [comment] 2017-04-06 09:58
I believe this is a duplicate of #3850, which should be fixed in 2.6.0. If you can still reproduce it with a fish built from the master branch, we'll reopen.

**Closed by faho** 2017-04-06 09:58 UTC
