### ISSUE TITLE
Make changing the color of the "@" and the ">" sign a "setuvar fish_color" option

### ISSUE THREAD

**Issue by CardboardTurtle** [fish-shell/fish-shell#7490] opened 2020-11-20 01:46 UTC
using Ubuntu 20.04
version 3.1.2
xterm-256color (Terminator is my terminal emulator if that matters)
Ive looked everywhere for how to do this including fish's own documentation multiple times but I can't find out how to do this. I think it should just be in the fish_variables file so that its easier for users to change what color they are.

**Comment by faho** [comment] 2020-11-20 07:10
Duplicate of #7186

**Closed by faho** 2020-11-20 07:10 UTC
