### ISSUE TITLE
Pasting large text then CTRL+C makes the terminal freeze

### ISSUE THREAD

**Issue by verdie-g** [fish-shell/fish-shell#5572] opened 2019-01-22 22:30 UTC
Hi,

Fish version: 3.0.0
OS: 4.20.3-arch1-1-ARCH

Steps to reproduce:
- select large text ([this one for example](https://pastebin.com/raw/dT9fkv2D))
- paste it in alacritty
- CTRL+C before the pasting is done

The pasting stops but no prompt is displayed, I need to restart the term.

The bug remains without third-party customizations and was tested in alacritty, urxvt, termite.

**Comment by zanchey** [comment] 2019-01-26 13:20
On first inspection, this looks the same as #1893.

**Comment by ridiculousfish** [comment] 2019-01-27 03:20
So what's happening here is that we discard input (I think) on Control-C, so we get stuck in bracketed paste mode. Probably we need to forcibly exit bracketed paste mode on interrupt.

**Comment by ridiculousfish** [comment] 2019-01-27 04:00
This fix isn't trivial; the obvious `bind --present -M paste \cc '__fish_stop_bracketed_paste'` doesn't seem to work.

**Comment by faho** [comment] 2019-05-28 20:16
I think the problem is really just that we get a SIGINT on Control-C because we don't turn off ISIG?

I.e. adding `stty -isig` to the bracketed paste starting function fixes it.

I'm not quite sure why we'd want to have SIGINT enabled, but I don't know how signal handling is supposed to work in general.

**Comment by faho** [comment] 2020-09-17 16:00
This works for me now with the fixes to #6603, so I'm closing.

**Closed by faho** 2020-09-17 16:00 UTC
Labels: bug
