### ISSUE TITLE
should `string` be modified to not append a newline to its final line of output?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3847] opened 2017-02-12 20:34 UTC
While working on issue #2855 I noticed that we can't simply do `clear | string replace \e\[3J ""` because the string replace will append an unwanted newline. The solution in this case is simple enough: just use a command substitution to eat the newline. But it got me wondering if perhaps we should only append a newline to all but the final line of output unless reading from stdin and the final line of input ended with a newline. Note that doing something like `string replace x y axxb | some_command` would still send a newline terminated string to some_command.

This change would make mistakes involving piping arbitrary strings through `string` less likely. On the other hand it's an exception to the general rule that `string` writes "lines" (defined as ending with a newline).

**Comment by ridiculousfish** [comment] 2017-02-12 23:30
Good question. What are the uses for `string` that don't involve a command substitution? I don't follow how you would have liked to use this for `clear`

**Comment by krader1961** [comment] 2017-02-13 01:26
In this instance, and some others I've seen, it is more natural to use `clear | string replace \e\[3J ""` rather than `echo -n (clear | string replace \e\[3J "")`. This is obviously a niche situation but it bit @faho when he changed the `\cL` binding to use the first solution and will undoubtedly bite other people.

**Comment by zanchey** [comment] 2017-02-17 09:01
I think this is a duplicate of #3082.

**Comment by krader1961** [comment] 2017-02-17 16:40
Indeed, it is a dup of #3082, @zanchey. And another example of how the current behavior surprises people. There is one subtle difference, however, that may not be clear from my poorly worded problem description. I am not proposing that we change the behavior when iterating over CLI arguments. In that case all arguments, even if there is only one, would still be written with a terminating newline. I'm only proposing changing how input from stdin is handled. In that case string would include a terminating newline iff the input ended with a newline. That keeps constructs like

```
echo -n hello | string replace l L
```

from surprisingly appending a newline that wasn't present in the input. If we decide not to make that change in behavior then the documentation should be augmented to make the current behavior abundantly clear.

**Comment by krader1961** [comment] 2017-02-18 06:55
Also, regardless of whether we change the behavior I think we should clarify the documentation.

**Comment by krader1961** [comment] 2017-04-02 05:25
@faho and I had a conversation on Gitter earlier today which referenced this issue. The result was the proposal the  `string` should also have a `-z` flag to complement `read -z`, etc. That would cause it to split input from stdin on null bytes rather than newlines. It would also cause its output to be null separated. In which case we'll want fish command substitution output parsing to split on null characters if any are present else newlines. Something it should probably do regardless so that you can do things like `set files (find . -print0)`.

However, I think that is orthogonal to this proposal. Which is that if the input from stdin does not contain a terminating newline, and either no null characters or the proposed `-z` flag is not used, then the output should not be terminated with a null or newline character. That way you can safely transform strings containing neither without adding either one. For example, `echo -n hello | string replace -a l L` would not add a newline to the string written to stdout.

**Comment by luolong** [comment] 2017-05-19 08:12
I use command line quite often to copy path to a CLI tool to the system clipboard so that I can paste it in to some editor. Something along the lines of:

```fish
> which rustfmt | pbcopy
```

Sometimes, this causes problems when the paste destination is inside a json string for example. The result is annoying, as I always have to delete the newline after pasting. Having a simple enough option to remove trailing line feed from the string being copied to clipboard would be one of those little paper cuts less to worry about...

**Comment by ThomasAH** [comment] 2020-03-12 15:53
+1 for changing/fixing this. I just updated our company's internal documentation for fish and removed most of the issues solved in fish 3.x compared to older versions, and this is the only issue that survived the upgrade to 3.x

**Comment by ridiculousfish** [comment] 2020-03-14 20:52
@ThomasAH can you describe the particular problem you're facing, and what would address it for you?  Thanks!

**Comment by ThomasAH** [comment] 2020-07-22 15:27
> @ThomasAH can you describe the particular problem you're facing, and what would address it for you? Thanks!

When working with existing files that do not end with a newline, using "string replace" adds a newline. Example:
```
echo -n foo > x
cat x
Output: foo⏎                                                                                                                                                        
string replace foo bar < x > y
cat y
Output: bar
```

One place where I encountered this was when working with MAC addresses and wanted to replace dashes with colons to be used in a config file. Here my workaround is to use an additional variable:
```
echo -n "00-11-22-33-44-55" > mac
set MAC (cat mac)
echo -n "$MAC"
Output: 00-11-22-33-44-55⏎
set MAC2 (string replace -a - : $MAC)
echo -n "$MAC2"
Output: 00:11:22:33:44:55⏎
```

But having to use workarounds isn't nice.

string replace should not add newlines by itself.
If the behavior shouldn't be changed this late in the life of frish, at least an option to prevent it is important.
Maybe use -N/--no-newline like with string repeat?

**Comment by ridiculousfish** [comment] 2020-07-25 23:13
Ok, let's try to fix this for 3.2. Hopefully we can just stop emitting them and won't need a new option.

**Comment by krobelus** [comment] 2020-08-30 10:31
I think it's safe to stop adding a newline if the input to `string replace` is piped or redirected.

Not sure about when inputs are given on the commandline. I'd leave that case as is.

**Comment by faho** [comment] 2021-02-01 17:44
Okay, I'm going to punt this from the 3.2.0 milestone.

**Comment by schuelermine** [comment] 2021-11-21 16:06
How about using a flag to do this? Something like `--no-final-newline`/`-n`…﻿

**Comment by ThomasAH** [comment] 2021-11-22 05:46
At this point any solution is better than the current situation, but the default behavior is still problematic.

**Comment by krobelus** [comment] 2021-11-22 23:44
Here's a patch that fixes this case and probably doesn't break too many others: https://github.com/fish-shell/fish-shell/pull/8473

**Comment by faho** [comment] 2022-01-07 13:47
We removed #8473 from the 3.4 milestone, removing this as well.

**Closed** 2022-03-13 10:22 UTC
Labels: enhancement, RFC

**Comment by i-am-the-slime** [comment] 2022-11-21 10:01
This is closed, how do you do it in the `pbcopy` case:

From further above
```fish
git rev-parse HEAD | string trim | pbcopy
```

I only want to use `string trim` to remove the newline but it doesn't work.

**Comment by faho** [comment] 2022-11-21 10:58
>I only want to use string trim to remove the newline but it doesn't work.

@i-am-the-slime 

All `string` commands will read their input from stdin, separated by newlines.

Then, most will not add a newline if the last entry didn't have one. In this case `string trim` reads "the last line" (i.e. up to the newline), trims it (i.e. removes spaces and such) and adds the newline because it had one. It'll never trim newlines because it treats the input as separate lines to begin with.

The simplest way to trim the newline here is to use a command substitution, and then print it without adding a newline, e.g. by using `printf %s`:

```fish
set head (git rev-parse HEAD)
printf %s $head | pbcopy
```
