### ISSUE TITLE
alias completions for fish 3.0

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4345] opened 2017-08-19 15:57 UTC
Going off of @krader1961's request to come up with ideas for fish 3.0 that would make it a convincing/appealing upgrade, I was thinking it might be possible to implement a _very basic_ automated import of completions when aliasing a command.

This isn't very well thought-out, but imagine if `alias oldname newname maybe_args` did something like 

`source newname.fish`

where `newname.fish` is generated equivalent to the following:

`cat /usr/local/share/fish/completions/oldname.fish ~/.config/fish/completions/oldname.fish | sed -r -e "s/-c ?['\"]oldname['\"]/newname/g" > newname.fish`

**Comment by krader1961** [comment] 2017-08-19 21:47
How does this differ from `function --wraps`?

**Comment by faho** [comment] 2017-08-21 10:52
@mqudsi: alias already does `function --wraps`, which causes the completions from the main command to appear.

The issue is #1976 - "--wraps" only uses the _command_, not a fake _commandline_, so it can be used to wrap e.g. `git`, but not `git checkout`.

Of course we could add a bandaid to e.g. call `complete -C"$alias "`, but I don't think that's worthwhile.

I'm closing this as a duplicate of #1976 - if you disagree, feel free to reopen.

**Closed by faho** 2017-08-21 10:52 UTC
