### ISSUE TITLE
Escape timeout is triggered even if no binding is found

### ISSUE THREAD

**Issue by yyy33** [fish-shell/fish-shell#6996] opened 2020-05-12 07:58 UTC
- 

````
fish, version 3.1.1
````
- 
````
yyy@x550vc-yyy ~> uname -a; echo $TMUX
Linux x550vc-yyy 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux
/tmp/tmux-1000/default,16845,0

````

````
yyy@x550vc-yyy /h/yyy> sh -c 'env HOME=$(mktemp -d) fish'

Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish

````
- Why pressing `Alt +shift+a` in vi insert mode jumps the cursor to the second to last character instead of the first to last character,I checked that there is no other binding

**Comment by faho** [comment] 2020-05-12 14:41
It would be nice to know what your terminal sends for alt+shift+a. Mine sends `\eA` (i.e. an escape character and an uppercase A) and we don't bind that, at all.

Use `fish_key_reader` and press alt+shift+a.

**Comment by zanchey** [comment] 2020-05-12 14:43
I can reproduce this with the stock bindings; the problem is that `\eA` as a combination seems to get processed differently to `\e` followed by `A`. Turn `fish_escape_delay_ms` up to 1000 and then the behaviour is the same (but wrong). I think this is a bug.

**Comment by yyy33** [comment] 2020-05-12 14:50
> It would be nice to know what your terminal sends for alt+shift+a. Mine sends `\eA` (i.e. an escape character and an uppercase A) and we don't bind that, at all.
> 
> Use `fish_key_reader` and press alt+shift+a.
> 
> Then it would be good to know what you've bound it to, with
> 
> ```fish
> bind -M insert \eA
> ```
> 
> (replacing `\eA` with whatever fish_key_reader told you)

Hello,this is my output
````
[I] yyy@x550vc-yyy ~> bind -M insert \eA
bind: No binding found for sequence “\eA”
[I] yyy@x550vc-yyy ~ [1]> fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.072 ms)  hex:   41  char: A
bind \eA 'do something'

````

**Comment by faho** [comment] 2020-05-18 16:57
Ah, okay. The issue here is this:

- After we read an escape character, we wait for the timeout to elapse
- In this case we get an "A" inside the timeout
- `\eA` doesn't match anything, but `\e` and `A` do separately

What we should do is to count this as an unmatched sequence `\eA` and do nothing.

**Comment by ridiculousfish** [comment] 2020-05-22 05:44
Hmm, how will we know how long the unmatched sequence is?

**Comment by faho** [comment] 2024-05-06 11:29
Fixed with the bind rework.

**Closed by faho** 2024-05-06 11:29 UTC
Labels: bug
