### ISSUE TITLE
Don't glob URL:s

### ISSUE THREAD

**Issue by maxnordlund** [fish-shell/fish-shell#1919] opened 2015-01-28 08:26 UTC
First let me say thanks for this awesome shell, it make my life much better. By the above I mean if I want to `curl` or `wget` some URL and it happens to contain a glob pattern, most often `?`, then I get this error:

```
No matches for wildcard 'https://www.example.com/wiki/index.php?page=About'.
fish: wget https://www.example.com/wiki/index.php?page=About
           ^
```

I believe fish should recognize URL:s and skip globbing them, or maybe try to glob and if it fails ignore the error. To make it more predicable I suggest only matching a regular expression like `https?://.*`.

What do you think?

**Comment by zanchey** [comment] 2015-01-28 08:37
It's definitely something that keeps biting people - see the rationale in #683 and #967. Note that zsh does this too. I'll close this as a duplicate of #967 for now, if that's ok.

**Closed by zanchey** 2015-01-28 08:37 UTC

**Comment by maxnordlund** [comment] 2015-01-28 12:44
Yeah, I tried to search for this but came up short. Must have been to tiered last night. But I think it is more  close to #967.
