### ISSUE TITLE
Allow command continuation for lines that end with pipes

### ISSUE THREAD

**Issue by tbodt** [fish-shell/fish-shell#3784] opened 2017-01-26 21:54 UTC
It would be nice if you could type:

    echo hi |

and press enter and have the command continue on the next line. Currently this is a syntax error, although you can add a backslash to make it work.

**Comment by krader1961** [comment] 2017-01-26 22:08
Duplicate of issue #1285.

**Closed by krader1961** 2017-01-26 22:08 UTC
Labels: duplicate
