### ISSUE TITLE
space infront of command leads to missing in history

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#6805] opened 2020-03-25 00:24 UTC
fish, version 3.1.0
Darwin zoro.local 18.2.0 Darwin Kernel Version 18.2.0  (Mojave)
iTerm2
tmux
TERM: screen-256color

Steps to reproduce:
1. type any command after putting a space infront, and hit enter

expected:
the command should run and it should appear in history

result:
The command runs, but hitting up arrow and it's missing, and it's missing from history

See:
<img width="298" alt="Screen Shot 2020-03-24 at 17 20 54" src="https://user-images.githubusercontent.com/26678/77489056-3eb94b00-6df4-11ea-9a18-3cb133fe558a.png">

**Comment by zanchey** [comment] 2020-03-25 01:20
It's not a bug, it's a feature!

From https://fishshell.com/docs/current/#history-search:

> Prefixing the commandline with a space will prevent the entire line from being stored in the history.

See also #615. We do get a lot of questions about this, it might be worth adding to the FAQ.

**Comment by danielb2** [comment] 2020-03-25 01:30
funny, I even read that part of the docs and I missed it. I checked other shells, and then I thought it's unintuitive because it's not expected. I had put a space in by accident.

**Comment by zanchey** [comment] 2020-03-25 02:19
Yeah. I think it would be fair to describe it as polarising. Since #4327 got merged it's been harder to trip over, though.

**Closed** 2020-05-10 13:37 UTC
Labels: question
