### ISSUE TITLE
"Due to a bug of fish, we cannot use command substitution"

### ISSUE THREAD

**Issue by andrewrk** [fish-shell/fish-shell#3544] opened 2016-11-12 22:27 UTC
Looking at https://github.com/junegunn/fzf/blob/a2beb159f1757961f1314b2739b5707ea2af2ea0/shell/key-bindings.fish I see this:

```fish
  # Due to a bug of fish, we cannot use command substitution,
  # so we use temporary file instead
  if [ -z "$TMPDIR" ]
    set -g TMPDIR /tmp
  end
```

I propose that we:

1. Identify if this is actually a bug in fish.
2. If it is, fix it, and then make a pull request to fzf to remove the workaround.
3. If it is not, make a pull request to fzf to remove the comment saying that it's a bug in fish. (Maybe the workaround can still be removed?)

**Comment by krader1961** [comment] 2016-11-12 22:54
It would help if you could explain the nature of the bug alluded to in that comment. There are some known issues with command substitutions. Such as issue #1949 and #1362. Without more detail about the nature of the problem being worked around there isn't much we can do.

**Comment by faho** [comment] 2016-11-12 23:09
Those actually appear to be the same thing. In any case, fzf has been mentioned as an example in #1362, so this is a duplicate of that.

**Closed by faho** 2016-11-12 23:09 UTC
Labels: needs-more-info
