### ISSUE TITLE
Unexpected end of string, incomplete parameter expansion begin

### ISSUE THREAD

**Issue by Martinfx** [fish-shell/fish-shell#6457] opened 2019-12-28 14:56 UTC
Hi,
i use fish shell but on FreeBSD have issue with command

```
fish, version 3.0.2
echo $version 3.0.2

uname -a 
FreeBSD  12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 GENERIC  amd64

echo $TERM 
xterm-256color
```

```
sudo portmaster c{- (line 1): Unexpected end of string, incomplete parameter expansion
begin; set all /usr/ports/c{*/ 
 ;end <&3 3<&-
               ^
from sourcing file -
	called on line 61 of file /usr/local/share/fish/functions/eval.fish

in function “eval”
	called on line 75 of file /usr/local/share/fish/functions/__fish_complete_suffix.fish

in function “__fish_complete_suffix”
	called on line 7 of file /usr/local/share/fish/functions/__fish_complete_directories.fish
	with parameter list “/usr/ports/c{ /”

in command substitution
	called on line 23 of file /usr/local/share/fish/functions/__fish_complete_directories.fish

in function “__fish_complete_directories”
	called on line 35 of file /usr/local/share/fish/completions/sudo.fish
	with parameter list “/usr/ports/c{”

in command substitution
	called on line 36 of file /usr/local/share/fish/completions/sudo.fish

in command substitution
	called on line 70 of file /usr/local/share/fish/completions/sudo.fish

in function “__fish_complete_sudo_subcommand”
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “-”
- (line 1): Unexpected end of string, incomplete parameter expansion
begin; set expanded /usr/ports/c{ 
 ;end <&3 3<&-
                    ^
from sourcing file -
	called on line 61 of file /usr/local/share/fish/functions/eval.fish

in function “eval”
	called on line 100 of file /usr/local/share/fish/functions/__fish_complete_suffix.fish

in function “__fish_complete_suffix”
	called on line 7 of file /usr/local/share/fish/functions/__fish_complete_directories.fish
	with parameter list “/usr/ports/c{ /”

in command substitution
	called on line 23 of file /usr/local/share/fish/functions/__fish_complete_directories.fish

in function “__fish_complete_directories”
	called on line 35 of file /usr/local/share/fish/completions/sudo.fish
	with parameter list “/usr/ports/c{”

in command substitution
	called on line 36 of file /usr/local/share/fish/completions/sudo.fish

in command substitution
	called on line 70 of file /usr/local/share/fish/completions/sudo.fish

in function “__fish_complete_sudo_subcommand”
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “-”
string replace: Expected argument
```

**Comment by faho** [comment] 2019-12-28 15:09
Duplicate of #6456

**Closed by faho** 2019-12-28 15:09 UTC
