### ISSUE TITLE
Strange key inputs when I use fishshell bind + fzf + tmux

### ISSUE THREAD

**Issue by gavin-jeong** [fish-shell/fish-shell#8945] opened 2022-05-10 02:10 UTC
When I use fishshell on the tmux,
fishshell's bind makes strange key input to my fzf prompt.

versions I use
```bash
$ fish --version
fish, version 3.3.1
$ uname -a
Darwin Gavin.Jeong's-MacBook-Pro 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 x86_64
$ echo $TERM
screen-256color
```

reproduction, starting from one of tmux pane
```bash
$ sh -c 'env HOME=$(mktemp -d) fish' # run plane fish
fish$ bind \cn fzf # create bind to fzf
```

and put ctrl-n to run fzf
and move to another tmux pane or just choose another pane with mouse

![image](https://user-images.githubusercontent.com/96432437/167527582-f27b15b6-200e-4a66-a8c8-5944c6a7690a.png)

Some characters, OIOIO are appeared on the fzf prompt.
There is no issue if I run fzf without key binding.

It makes hard to work with multiple pane on tmux+fzf+fishshell

**Comment by faho** [comment] 2022-05-10 05:02
Duplicate of #6942

**Closed by faho** 2022-05-10 05:02 UTC
