### ISSUE TITLE
Adding new syntax or commands for scoped `cd`

### ISSUE THREAD

**Issue by clo4** [fish-shell/fish-shell#9620] opened 2023-02-27 10:10 UTC
Sorry if this has been brought up before. I did search and couldn't find anything like it, but it's possible I missed an issue

pushd and popd solve the problem of "I want to run some code in a directory, then return to wherever I was before", but introduce the following problem:

## The issue

Say we have this function that cd's to some directory and runs a long-running command.

```fish
function example
    pushd $SOME_DIR
    cargo build --release
    popd
end
```

If you hit ctrl+c during the execution of the long running command (in this case `cargo build`), you're now in $SOME_DIR in your interactive session. This is unexpected and surprising if you're _not_ expecting it, and I think it would be unreasonable for people to always expect it.

It's not a huge deal, but it's definitely not a good experience, and you need to remember that you can also `popd` to exit it. Maybe someone else is running your function, and they don't even know you can _do_ that! It also requires the author to have used pushd/popd, and I think we've all seen enough shell scripts to know _that_ doesn't happen...

You could _probably_ solve this problem with event handlers, but that is a lot of extra complexity for what shouldn't really take more than three lines in a shell script.

## A possible solution

Fish already has the concept of blocks. We could use a block to define a scope for executing in a directory.

```fish
function example
    begin cd $SOME_DIR
        cargo build
    end
end
```

That's just an example. It could use a different keyword to avoid overloading `begin` such as `in $SOME_DIR; ...; end`

This is not the only solution, but it is the most flexible.

## Other solutions

* Continue to use `pushd` but add something like `--scope block` (requiring an argument leaves the door open for additional scopes in the future, and makes it more explicit in the present). This could build up a separate stack of directories specifically scoped to the block, which are all removed when the block ends.
  ```fish
  function example
      pushd --scope block $SOME_DIR
      cargo build
  end
  ```

* Add something like Go's `defer` to queue a command to be executed when the scope ends. The command would be executed even if the function exits due to ctrl+c, etc.
  ```fish
  function example
      pushd $SOME_DIR
      defer popd
      cargo build
  end
  ```

## Implementation

If it's accepted as a good idea, once the Rust port is (mostly) complete I'd love to contribute by implementing one of these solutions.

These are just suggestions of course. I'd love to have some feedback of the ideas -- do you think the reasoning is valid? Have I missed something glaringly obvious that someone who's used fish for many years should really have known already?

**Comment by faho** [comment] 2023-02-27 10:17
Duplicate of #1439

**Comment by faho** [comment] 2023-02-27 10:18
The general idea here is a "subshell", which isolates state like the current directory. So I've marked it as a duplicate of that.

**Closed by faho** 2023-02-27 10:17 UTC
