### ISSUE TITLE
"NameError: name 'httpd' is not defined" with Python 3.2.1

### ISSUE THREAD

**Issue by cmarqu** [fish-shell/fish-shell#3530] opened 2016-11-07 09:01 UTC
**fish version installed** *(`fish --version`)*:
```
> fish --version 
fish, version 2.3.1-729-g23c3101
```
**OS/terminal used**: 
SuSE 11 x86_64, gnome-terminal, tmux

In an environment with Python 3.2.1., I get the following:
```
> fish_config 
getsockaddrarg: bad family
Web config started at 'file:///home/maq3rt/.cache/fish/web_config-0EDZWM.html'. Hit enter to stop.
Traceback (most recent call last):
  File "/home/maq3rt/tools/share/fish/tools/web_config/webconfig.py", line 1035, in <module>
    ready_read = select.select([sys.stdin.fileno(), httpd.fileno()], [], [])
NameError: name 'httpd' is not defined
> python --version
Python 3.2.1
```

**Comment by zanchey** [comment] 2016-11-07 09:09
This isn't a duplicate of #1754, but it's close. I wonder if you have IPv6 disabled on your system?

**Comment by zanchey** [comment] 2016-11-07 09:11
... and if so, does `getent hosts localhost` give you an IPv6 address?

**Comment by cmarqu** [comment] 2016-11-07 09:15
I don't know about whether IPv6 is disabled (this is at work), but ``getent hosts localhost`` does not get me an IPv6 address.
The behavior seems to depend on the Python version I'm using (we have several installed from what I think are not packages from the distribution, so potentially strange configs). It works with Python 2.7.10 and 3.4.3, but not 2.7.3 (and 3.2.1 as above).

**Comment by krader1961** [comment] 2016-11-08 23:54
Googling "getsockaddrarg bad family" returned [this](https://github.com/majek/puka/issues/27) as the top result. The fix for that project is to check `socket.has_ipv6`. I don't see why our existing check added to fix issue #1754 doesn't work with all python versions. Probably a bug in those specific python versions.

@cmarqu: On a system exhibiting this problem what does

```
python -c "import socket; print socket.has_ipv6"
```

output using the python2 version that doesn't work? Put parentheses around the `socket.has_ipv6` when testing with the python3 version that doesn't work.

**Comment by cmarqu** [comment] 2016-11-09 08:52
The results are:
```
2.6.4 - False
2.7.3 - False
2.7.10 - True
3.2.1 - False
3.2.3 - False
3.4.3 - True

```

**Closed** 2016-11-10 23:44 UTC
Labels: bug

**Comment by cmarqu** [comment] 2016-11-11 09:15
Fix confirmed, thanks.
