### ISSUE TITLE
Completions in command position should offer commands

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5418] opened 2018-12-16 10:32 UTC
It seems to me that fish should not complete files when we are in the command position unless the user has already typed `./` or some other path component. We should show available commands.

And by command position, I mean after a \<TAB\> with an empty command line, and also `if <TAB>`, `and <TAB>`, `echo (<TAB>`, etc.

**Comment by faho** [comment] 2018-12-16 10:48
See https://github.com/fish-shell/fish-shell/blob/master/src/complete.cpp#L571-L573.

We complete commands, but only if the user has entered at least 2 characters.

The idea here is that it's far too slow, but on my system that's basically instantaneous.

**Comment by ridiculousfish** [comment] 2018-12-17 01:37
fish does not tab-complete commands in the current directory without `./`, with two exceptions:

1. Implicit cd
2. If `.` is in PATH

Are you seeing something different? I couldn't reproduce this given the description.

**Comment by floam** [comment] 2018-12-17 02:11
@ridiculousfish I'm kind of confused by your reply here, so I think there's a misunderstanding of the issue being reported.

Here's how to reproduce what I'm talking about. 

Start fish. Hit tab. Look at pager. Or: start fish, type `if `, hit tab. Look at pager.

I see files in the current directory, not commands in $PATH and builtins.

**Comment by floam** [comment] 2018-12-17 02:14
I do not want the file completions here unless I've already typed something starting with `./` or `/`.

**Comment by ridiculousfish** [comment] 2018-12-17 06:19
Ok, I see this when the command line is completely empty. I missed that part of your original post, my mistake.

**Comment by krobelus** [comment] 2019-11-05 09:00
I have pushed 277fca9c6a26600ce8dc7cb2a035d412a9476868 which completes all available commands on the empty commandline. Should be fine but I don't know if it's always desirable.

**Comment by floam** [comment] 2019-11-07 21:11
Thanks man! Yeah, alphabetical isn't super great here. You can scroll like mad or use ^S to initiate a search and get an idea of the available commands on a system or something but it seems possibly useful to sort by frequency. Or perhaps builtins followed by alphabetical per PATH component. That'd sort stuff from /bin/ first. But not until stuff like `echo`. I'm not sure.

**Comment by faho** [comment] 2019-11-16 14:05
This seems to be fixed by 277fca9c6a26600ce8dc7cb2a035d412a9476868, so I'm closing.

Any enhancements can be handled separately.

**Closed by faho** 2019-11-16 14:05 UTC
Labels: completions, enhancement
