### ISSUE TITLE
Unable to get file name tab completions for git add subcommand when using dot slash prefix

### ISSUE THREAD

**Issue by PAI5REECHO** [fish-shell/fish-shell#9091] opened 2022-07-27 06:42 UTC
**fish version:** `3.5.0`
**OS version:** `Linux 5.18.4, NixOS, 22.11 (Raccoon), 22.11.20220619.0d68d7c`

File path completions with leading dot slash prefixes (`git add ./`<kbd>Tab</kbd>) don't work. When trying with `sh -c 'env HOME=$(mktemp -d) fish'` only hidden files are suggested. I also tested in a Ubuntu 22.04 Docker container with the PPA version of fish and filepath completions with a leading `./` didn't work at all.

**Comment by faho** [comment] 2022-07-27 07:00
Duplicate of #9053

**Comment by faho** [comment] 2022-07-27 07:46
Please try 3.5.1, which fixed an important bug related to git file completion.

**Comment by PAI5REECHO** [comment] 2022-07-30 12:43
> Please try 3.5.1, which fixed an important bug related to git file completion.

Gave `3.5.1` a try, the behavior is still the same

**Closed** 2022-07-30 22:16 UTC
Labels: enhancement, completions
