### ISSUE TITLE
Fish shells that start in windows created by kitty's "new_window_with_cwd" aren't aware of the current working directory

### ISSUE THREAD

**Issue by bool3max** [fish-shell/fish-shell#5717] opened 2019-03-03 17:33 UTC
* fish version: `3.0.1`
* `uname -a`: `Linux Arch 4.20.11-arch2-1-ARCH `
* terminal: `kitty 0.13.3`, `$TERM`: `xterm-kitty`.

When using kitty's `new_window_with_cwd` command to open a new terminal window with the shell's PWD being that of the previously focused terminal window, fish itself seems not to be aware of the new PWD (it acts as if it's `$HOME`), yet all the programs started by that fish instance inherit the new PWD. 

# Example: 

first terminal window: 

```
~/Downloads $ ls

file1 file2

~/Downloads $ pwd

/home/user/Downloads
```

open a new kitty terminal window with `new_window_with_cwd`:

```
~ $ ls

file1 file2

~ $ pwd

/home/user

~ $ echo $PWD

/home/user
```

The `fish_prompt` function, the `$PWD` variable and the `pwd` builtin all act as if the PWD is `$HOME`, yet processes spawned by fish clearly indicate that the PWD actually got updated (shown by the `ls` example).

**Comment by faho** [comment] 2019-03-03 17:40
Upgrade to 3.0.2, that's the one and only issue fixed there.

(Unfortunately arch has been a bit slow to upgrade)

Duplicate of #5647

**Closed by faho** 2019-03-03 17:40 UTC
