### ISSUE TITLE
Modify command line buffer after running command

### ISSUE THREAD

**Issue by viveksjain** [fish-shell/fish-shell#8989] opened 2022-06-02 06:50 UTC
fish, version 3.4.1

I'm not sure if I'm missing something obvious here, but I'd like to run some function which uses `commandline` to update the buffer of the prompt (either the current one or next one). E.g. something like
```
> function myfzf
  command fzf | while read -l r; set result $result (string escape $r); end
  commandline -at -- ' '(string join " " $result)
end
> ls | myfzf
>
```
What I want is the line to get updated with the fzf item that I selected. It works for any functions that I `bind` to a shortcut. But is `commandline` not supported for functions that are actually typed out and run?

**Comment by faho** [comment] 2022-06-02 07:58
Correct, this isn't supported.

The logic currently is that, after execution, the commandline will be cleared for the next command to be accepted.

There's not really a good idea for how the commandline should end up if we allow arbitrary modification here - if you do `commandline -rt foo`, that replaces the current token with "foo". So should the commandline now *stay*, except the token was replaced with foo? So any modification to any one token causes the commandline to stay. That's weird.

So: If you want to modify the commandline, simply bind whatever does that to a key.

I'm closing this as a

Duplicate of #8807

**Closed by faho** 2022-06-02 07:58 UTC

**Comment by viveksjain** [comment] 2022-06-03 05:47
Ah thanks, my previous searches weren't able to find the duplicate, that has some useful ideas IMHO the semantics (that I want) are quite clear, if you've hit enter then the new commandline always starts out as empty and the command should behave as such.
