### ISSUE TITLE
functions with redirected streams break line buffering

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4415] opened 2017-09-19 01:04 UTC
*I tried to come up with a self-contained example to reproduce this, but was unable. I've tried to present as portable a test case as possible here.*

Compare the behavior of
```fish
command gfind . 2>| read -l stderr
```

to that of 

```fish
alias _find gfind
_find . 2>| read -l stderr
```

In the first case, the output is what you'd expect: lines written by `find` to stdout are printed in real-time to the terminal.

In the second case, all gfind output is buffered until the command finishes running and is only printed once it has exited.

Interestingly enough, 

```fish
fish -c "gfind ." 2>| read -l stderr
```

does not result in the same behavior.

**Comment by krader1961** [comment] 2017-09-19 01:15
This is essentially the same as issue #1396. In addition to constructs like `for...; ...; end | a_command` the output of functions is also fully buffered when on the left side of a pipe.

**Comment by faho** [comment] 2017-09-19 17:41
Yeah, let's track this in #1396.

Duplicate of #1396.

**Closed by faho** 2017-09-19 17:41 UTC
