### ISSUE TITLE
Right prompt issues with reflowing terminal

### ISSUE THREAD

**Issue by TheEvilSkeleton** [fish-shell/fish-shell#7491] opened 2020-11-20 02:35 UTC
> Please tell us which fish version you are using by executing the following:
> 
>   fish --version
>   echo $version

fish, version 3.1.2

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
> 
>   sh -c 'env HOME=$(mktemp -d) fish'

```
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```

I am only using [Tide](https://github.com/IlanCosman/tide) for customization. The maintainer told me it was an upstream issue with right prompts.

> Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

`uname -a`: `Linux TheMainDesktop 5.9.8-200.fc33.x86_64 #1 SMP Tue Nov 10 21:58:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

`echo $TERM`: `xterm-256color`

## Issue

Resizing the window of a terminal when using a right prompt will make the terminal look super ugly. The prompt will show up everywhere every time it gets resized.

![fish](https://user-images.githubusercontent.com/50847364/99743022-c5691980-2aa2-11eb-8c92-7bd7aa81e47b.gif)

Related issue: https://github.com/IlanCosman/tide/issues/48

**Comment by IlanCosman** [comment] 2020-11-20 16:13
Oh gosh, this is awkward 😅 This might not be a fish issue upon closer inspection. 

There _is_ the very similar upstream issue where if you have a multi-line left prompt and a right prompt, then window resizing does this.

Can demonstrate with:

```fish
function fish_prompt
    echo foo
    echo bar
end

function fish_right_prompt
    echo blah
end
```

But this bug doesn't appear if the right prompt isn't displaying anything, so it doesn't apply to your issue.

I'd love to get a fish maintainer's comments on this though, as I couldnt find the bug I described above in the open issues. I'll reopen the Tide issue and poke around on this. Sorry if I was mistaken in kicking this upstream 😅

**Comment by IlanCosman** [comment] 2020-11-20 16:30
Ok, yeah, this was a Tide issue (though caused by the upstream bug in my defense 😛).

I was setting the right prompt display to a space when I wanted it to not display anything. Space counts as a character obviously, thus producing the bug.

```fish
set -g _tide_fish_right_prompt_display ' '
```

Instead I'll set it to truly empty.

```fish
set -g _tide_fish_right_prompt_display
```

You'll still have this issue if anything is actually displaying in the right prompt, but if not it'll be fine. Feel free to close this issue.

**Comment by TheEvilSkeleton** [comment] 2020-11-20 16:59
Thank you for the detailed explanation, it fixed this issue

I'll keep it opened, but I'll change the title. As you said, it's an upstream bug so I'd prefer it to be fixed so it doesn't happen to others when they set up Tide or other right prompts.

**Comment by mqudsi** [comment] 2020-11-20 21:32
Does this help? https://github.com/fish-shell/fish-shell/pull/7404

It's in the latest master, so you could try that.

**Comment by TheEvilSkeleton** [comment] 2020-11-23 20:56
@mqudsi I just compiled it from source, and the issue persists:

```console
❯ fish --version 
fish, version 3.1.2-1651-g9b3f4faa5
```

**Comment by faho** [comment] 2020-11-23 21:09
Yeah, this is the terminal reflowing, and because we have actual spaces between the left and right prompt it'll do weird things.

The solution would be to make those spaces *empty* instead, but I'm not sure how that works.

For the moment: Don't use a multiline prompt plus a right prompt in a terminal that will reflow (mostly iTerm and VTE).

**Comment by faho** [comment] 2020-11-30 19:04
Okay, some news: 1. this also happens with bash, and with zsh, especially have a right prompt enabled.

The VTE developers propose two things we could do:

- [not redraw in terminals that reflow](https://github.com/thestinger/termite/issues/549#issuecomment-352208168)
- wrap the terminal in sequences that disable wraparound (https://bugzilla.gnome.org/show_bug.cgi?id=778547#c11) ("DEC[RE]SET 7, that is, "\e[?7l" to disable and then "\e[?7h" to re-enable")

Given how awful detecting terminals is (especially since VTE claims to be xterm), I'm going to go with the first and disable the winch handler inside of these. Better to do less than do more.

I'm just going to start with iTerm and VTE, since I know they do this and how to detect them. I know konsole, alacritty, xterm and kitty don't.

**Comment by faho** [comment] 2020-11-30 19:04
Here's a screenshot:

![Screenshot_20201130_200028](https://user-images.githubusercontent.com/5185367/100652454-3df39400-3347-11eb-95ac-d8fd8e16cf16.png)

The upper fish has the resize handler enabled, the lower has it disabled, I resized the terminal for both.

**Closed** 2020-11-30 19:05 UTC
Labels: enhancement

**Comment by ridiculousfish** [comment] 2020-11-30 19:29
I think this disabling reflow is strictly worse in iTerm2, as the prompt doesn't get redrawn. Compare reflow (before this change):

http://ridiculousfish.com/temp/reflow_crop.mp4

and with this change:

http://ridiculousfish.com/temp/noreflow_crop.mp4

There's more chaos during the resize but it ends up better. Should we disable this for VTE only?

**Comment by faho** [comment] 2020-11-30 19:38
Oh, iTerm apparently *doesn't* reflow? I could have sworn it does.

Can you check if you've disabled it via an option?

**Comment by ridiculousfish** [comment] 2020-11-30 20:01
iTerm2 does reflow. I also tried in gnome-terminal (VTE) and see the same issue: without a repaint the cursor can end up floating in space after the resize is done. But I also see the garbage printed above it too; it depends a lot on how fast you resize and what else is on the terminal.

The main problem is the race between redrawing and resizing. I think the right fix is to add some hysteresis, so that fish waits to redraw until (say) 500 msec after the last SIGWINCH. So in most cases it will do nothing until after the resize is done. But that's not trivial to implement.

**Comment by faho** [comment] 2020-11-30 20:10
For the record, this looks *much* better for me without resizing in gnome-terminal, because with resizing it ends up losing the cursor position and prints additional lines. I much prefer in some cases having the right prompt not precisely at the edge. Also once you start typing it snaps back into place, apparently?

What happens in your video in iTerm looks acceptable with resizing, so let's leave the winch handler in place there.

**Comment by faho** [comment] 2021-01-01 19:32
Also disabled for alacritty (with the supported "alacritty" $TERM) in 8a585bb, and we might want to look into adding a more flexible mechanism (overriding event handlers is annoying).

Tbh I'm not averse to simply having a variable that we default, like term24bit or the vi cursor. (Ideally this would simply be autonegotiated, but that would require terminals to be good, and we can't have that).

See https://github.com/alacritty/alacritty/issues/4419.
