### ISSUE TITLE
psub help argument

### ISSUE THREAD

**Issue by trevor** [fish-shell/fish-shell#715] opened 2013-05-08 01:30 UTC
it makes sense, but if this is expected behavior then should the completion assistance be changed, or maybe a more detailed error message?

```
% psub -h
psub: Not inside of command substitution
```

**Comment by krader1961** [comment] 2015-12-08 04:17
Please, will someone close this pull request? It's more than two years old and either is no longer relevant or no one cares enough that it be merged.

FWIW, Mac OS X is my primary OS and I despise its standard getopt command; so much that I ran

```
brew install gnu-getopt
brew link --force gnu-getopt
```

I can't reproduce the problem but that may be because I've installed the GNU version of getopt. Regardless, this is so moldy (more than two years old) that it should be closed without further discussion. If someone thinks this is still a problem please open an issue.

**Comment by ridiculousfish** [comment] 2015-12-09 05:18
Closing, thanks

**Closed by ridiculousfish** 2015-12-09 05:18 UTC
