### ISSUE TITLE
fish doesn't handle `x` correctly in vi bindings

### ISSUE THREAD

**Issue by mikebenfield** [fish-shell/fish-shell#9025] opened 2022-06-20 04:04 UTC
```
>  fish --version
fish, version 3.4.1
>  echo $version
3.3.1
```

This is MacOS 11.3.  iTerm2. 

`sh -c 'env HOME=$(mktemp -d) fish'` doesn't affect the behavior. 

When I run `fish_vi_key_bindings`, in Normal mode, `x` will delete the character under the cursor (correct), but it doesn't change the text in the buffer. It should put the character in the buffer so I can put/paste it. This is also true of the `X` key.

**Comment by faho** [comment] 2022-06-20 10:09
```
>  fish --version
fish, version 3.4.1
>  echo $version
3.3.1
```

Note: This means your configuration is inconsistent. You've updated fish to 3.4.1 but the shell you are running is still version 3.3.1.

In this case it's unlikely to make a difference but typically that's a bad start to a bug report. Also we've recently released version 3.5.0, so you'll want to upgrade.

-----------

What is happening here is already mentioned in #8189 - our "x" bindings do weird things in order to break them down to emacsy movement, and that ends up not filling the killring correctly.

I'm closing this as a duplicate of that.

**Closed by faho** 2022-06-20 10:09 UTC
