### ISSUE TITLE
Incorrect keyboard symbols in Raku RELP in Fish Shell

### ISSUE THREAD

**Issue by emakei** [fish-shell/fish-shell#9046] opened 2022-06-29 19:52 UTC
fish, version 3.5.0
3.5.0
Yes, I had tied "sh -c 'env HOME=$(mktemp -d) fish'" and it produced same result.
I have raku (https://raku.org) installed. And when starting Raku REPL from Fish I have problems whith reading correct keyboard codes. When I'm pressing "О" in REPL I see nothing but when pressing some more keys then appear some signs but not I had entered. There is no problems with '/bin/zsh' but same issue in '/bin/bash' (3.2.57).
I'm use MacBook Air M1 (Darwin MacBook-Air-Eugene.local 21.5.0 Darwin Kernel Version 21.5.0)

**Comment by faho** [comment] 2022-06-29 20:34
It would be great to know which raku *version* you've installed.

I've waded through the links, figured out that "Rakudo" is apparently the thing to use, picked the current binary of that (v2022.06, on linux), and could not reproduce your problem.

Then there's the question of your *raku configuration*. I start the `raku` from that binary distro and it tells me that

> You may want to `zef install Readline`, `zef install Linenoise`, or `zef install Terminal::LineEditor` or use rlwrap for a line editor

These are very different modes of interacting with the terminal, and so would have a big impact.

**Comment by emakei** [comment] 2022-07-01 05:25
> It would be great to know which raku _version_ you've installed.
> 
> I've waded through the links, figured out that "Rakudo" is apparently the thing to use, picked the current binary of that (v2022.06, on linux), and could not reproduce your problem.
> 
> Then there's the question of your _raku configuration_. I start the `raku` from that binary distro and it tells me that
> 
> > You may want to `zef install Readline`, `zef install Linenoise`, or `zef install Terminal::LineEditor` or use rlwrap for a line editor
> 
> These are very different modes of interacting with the terminal, and so would have a big impact.

I use Raku v2022.06 without Readline, Linenoise, Terminal::LineEditor

**Comment by faho** [comment] 2022-07-01 06:41
> When I'm pressing "О" in REPL I see nothing but when pressing some more keys then appear some signs but not I had entered

You mean the normal letter "o" (not the number "0", and especially not via the numpad?), with shift to enter a capital "O"? What symbols do appear? Chances are they aren't random.

>I use Raku v2022.06 without Readline, Linenoise, Terminal::LineEditor

You mean Raku*do* Raku, the one I installed and you haven't configured one of these editor modules? Do you have anything else configured?

What does `locale` say in fish? What does it say in zsh?

What about `stty -a` in both?

**Comment by emakei** [comment] 2022-07-04 17:23
> What does `locale` say in fish? What does it say in zsh? In bash?
Everywhere same
```
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
> What about stty -a in all three?
Same result
```
speed 9600 baud; 24 rows; 80 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```
> What about echo $TERM in all three?
Same result
```
xterm-256color
```
> You mean the normal letter "o" (not the number "0", and especially not via the numpad?), with shift to enter a capital "O"? What symbols do appear? Chances are they aren't random.
I mean cyrillic symbol "О" on my laptops keyboard (with Shift). When I'm try enter this letter with Caps happens just nothing and REPL hanging. When I'm use Shift every time I see same symbol after enter whenever few symbols (it happens only if I repeat press buttons). The symbol is Є.
Btw I found that with bash this issue happens only after in terminal was started fish and this error appeared and exiting fish.

**Comment by faho** [comment] 2022-07-04 17:31
>When I'm try enter this letter with Caps happens just nothing and REPL hanging.

Okay. Please start fish_key_reader and press that key.

>Btw I found that with bash this issue happens only after in terminal was started fish and this error appeared and exiting fish.

Did you run `locale` and `stty -a` in a terminal that had a fish running before? Try it without.

**Comment by emakei** [comment] 2022-07-04 18:28
> Okay. Please start fish_key_reader and press that key.

```
bind \u041E 'do something'
```
> Did you run locale and stty -a in a terminal that had a fish running before? Try it without.

This time I'm starting fish from zsh. problem appears every time.

**Comment by faho** [comment] 2022-07-04 18:42
Please start a terminal that starts zsh. Then confirm that you don't see the error with raku, then run `stty -a` and `locale` inside that zsh.

There's a reason I am asking, and that is that it is possible fish is changing terminal modes or locale in a way that raku doesn't like, and because bash pretty much doesn't touch those (including letting them just completely break), it would also be reproduced if you started bash from fish.

**Comment by emakei** [comment] 2022-07-04 19:39
> Please start a terminal that starts zsh. Then confirm that you don't see the error with raku, then run `stty -a` and `locale` inside that zsh.
> 
> There's a reason I am asking, and that is that it is possible fish is changing terminal modes or locale in a way that raku doesn't like, and because bash pretty much doesn't touch those (including letting them just completely break), it would also be reproduced if you started bash from fish.

Well now I see error in Raku started from /bin/zsh. But now I'm using Raku v2022.04 arm64. v2022.06 was x86_64 version installed from rakudobrew.
After upgrading to v2022.06 arm64 there is no problem on zsh or fish.

**Comment by faho** [comment] 2022-07-04 20:22
Closing this as an installation error, then.

**Closed by faho** 2022-07-04 20:22 UTC
Labels: needs more info
