### ISSUE TITLE
fish_vi_cursor.fish should support st

### ISSUE THREAD

**Issue by TieDyedDevil** [fish-shell/fish-shell#3523] opened 2016-11-03 17:12 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: HEAD

**OS/terminal used**: Fedora/st

Talk about the the issue here. 

## Reproduction steps
1. Run fish in st terminal.

## Results
Cursor should change with vi mode, but doesn't.

st does support the DECCUSR escape sequence to change the cursor, but does not advertise a terminfo Ss capability. (BTW, the Ss capability does not seem to be documented in Fedora 24.)

One possible approach would be to skip the tput Ss test in fish_vi_cursor.fish in the case where $TERM is `st-256color` and treat st-256color the same as xterm in the switch statement.

**Comment by krader1961** [comment] 2016-11-03 17:44
What version of st added the capability and how would we detect that fish is running in a version that supports the capability?

**Comment by TieDyedDevil** [comment] 2016-11-03 18:28
The DECSCUSR support (sorry for the earlier misspelling) came in st version 0.6.

`st -v` prints the version. The format has evolved since the initial release. From oldest to current, you'll see:

`st-<version> ...`

`st <version> ...`

and `<argv0> <version> ...`

The version number is always dotted. `...` represents copyright information, which may start with either `(c)` or `©`.

**Comment by faho** [comment] 2016-11-03 18:28
This was added to st 0.6 in commit [580302f3179ef3f24cf0329755686dfa7100996b](http://git.suckless.org/st/commit/?id=580302f3179ef3f24cf0329755686dfa7100996b), last year.

I cannot find any way to detect an st version, though given that, like other suckless programs, it is configured via patching, I'd guess that most users are up-to-date (since they probably don't get it via a binary repository).

**Comment by faho** [comment] 2016-11-03 18:29
>st -v prints the version.

That's kind of a non-starter. For one, the `st` in $PATH may not be the currently running st.

**Comment by TieDyedDevil** [comment] 2016-11-03 19:12
How about checking the terminfo `kbs` capability? `st` changed that capability from 0x08 (BS) to 0x7F (DEL) shortly before the 0.6 release. So an `st` that reports BS is version 0.5 or earlier and does not support DECSCUSR.

See `st` commit 230d0c8428456603ce3629dac75c46abc4c9f016 .

**Comment by legovini** [comment] 2016-11-03 19:24
Some time ago I submitted a patch to add the Ss capability to st's terminfo:

http://lists.suckless.org/hackers/1610/12269.html

The patch was well received (on IRC), but it still has to be merged by the maintainer.
I'm confident that st-0.8 will get it included.

**Comment by faho** [comment] 2016-11-03 19:26
> I'm confident that st-0.8 will get it included.

@legovini: That's nice to hear and would be my preferred solution. Any idea when 0.8 will be released?

**Comment by TieDyedDevil** [comment] 2016-11-03 19:30
Meanwhile:

```
tput kbs | hexdump -e '"%_u"'
```

will print `del` for st 0.6 and later; `bs` for st 0.5 and earlier.

**Comment by faho** [comment] 2016-11-03 19:35
@TieDyedDevil: If the next st release isn't a year way, I'd prefer to just wait for it.

I mean we could add `string match -q "st*" -- $TERM; and test (tput kbs) = \x7f` to the list of conditions, but I'm not touching that anymore before release unless there's an actual bug. It's hairy enough as it is, and difficult enough to test.

**Comment by TieDyedDevil** [comment] 2016-11-03 19:49
OK. Thanks.

**Comment by krader1961** [comment] 2016-11-05 04:07
> That's kind of a non-starter. For one, the st in $PATH may not be the currently running st.

Personally I'm not bothered by that unlikely scenario. If the user has multiple version of `st` installed on their system and have set things up such that $PATH finds a version they're not running they deserve unexpected behavior. On the other hand the only script I could find that tests the version of a command is *share/completions/which.fish* and that isn't really analogous. Too, I installed stterm on Ubuntu 16.04 and `stterm -v` writes a usage message to stderr despite the usage message (and man page) saying that only the version will be written to stderr. That fubar behavior is a stronger argument for not using that mechanism. Also, AFAICT it does't export any useful env vars that we could inspect.

I'm closing this because there isn't a reasonable way for fish to detect if the user is using a version of stterm that supports the DECCUSR capability.

**Closed by krader1961** 2016-11-05 04:07 UTC
Labels: enhancement
