### ISSUE TITLE
Redirecting stdin into a begin/end block surrounding count does not work as expected

### ISSUE THREAD

**Issue by andrey-mishchenko** [fish-shell/fish-shell#8454] opened 2021-11-17 22:54 UTC
```
~/tmp $ cat bug_demo_file 
The quick brown
fox jumped over
the lazy dog
~/tmp $ begin
            cat | count
        end < bug_demo_file 
3
~/tmp $ begin
            count
        end < bug_demo_file
0
~/tmp $ echo $status
1
~/tmp $ 
```

Fish version: 3.3.1
OS: macOS 11
TERM: xterm-kitty

I successfully reproduced this in `sh -c 'env HOME=$(mktemp -d) fish'`.

**Comment by andrey-mishchenko** [comment] 2021-11-17 22:56
(For some context, I found this while using Neovim. I highlighted some lines and passed them through a `!count`, which is supposed to filter/pipe them through the `count` terminal command. I am using `fish` as my shell in Neovim. It seems like Neovim surrounds filter commands with `begin`/`end` when targeting `fish`. Doing `!cat | count` works there.)

**Comment by faho** [comment] 2021-11-18 13:45
What happens here is that `count`  either counts its given arguments or stdin.

In order to avoid always reading all the data, it only does that when it's "directly redirected", meaning it's immediately attached to a pipe or redirection.

Imagine what would otherwise happen here:

```fish
function mycount
    count $argv
    read foo
    echo foo is $foo
end

echo bar | mycount
```

This will print 0 (because it wasn't given any arguments) and then "foo is bar".

`string` works along the same principles.

**Comment by ridiculousfish** [comment] 2021-11-18 17:43
Closing since this is working as designed. Thanks for filing.

**Closed by ridiculousfish** 2021-11-18 17:43 UTC
Labels: question

**Comment by andrey-mishchenko** [comment] 2021-11-18 18:48
Man ... shells are complicated.

Ok, I understand. And there is no way that the behavior of `count` will be changed at this point, and it doesn't make sense for `count` to read all of stdin in the special case when it is passed no arguments because `if count $argv` is still useful in a `function`.

I poked around the source. It looks like the `math` builtin has the same behavior (confirmed experimentally). So if I understand correctly, there are exactly 3 shell commands in fish (all builtins: `count`, `math`, `string`) which selectively avoid reading all of stdin specifically in the case of indirect redirection (one example of which is redirection into a block containing (a pipeline beginning with) the command -- are there other examples?).

**Comment by faho** [comment] 2021-11-18 19:06
>are there other examples?

`source`. It can either read from a given filename - `source foo.fish` - or a script from stdin - `echo echo foo | source` will run `echo foo`.

The issue there is that you might try `source $filename` and $filename might not be set. This would appear to hang your shell. This isn't just a theoretical problem but has bitten users in the past.

Because it takes a filename we made the special filename `-` force it to read from stdin. This is a widely used convention (e.g. just now I used `du --files0-from=-` to make du read filenames from stdin).

>And there is no way that the behavior of count will be changed at this point

Correct.  Making count always read from stdin would break every single existent use of count, in a rather horrible way (the breakage would only appear at the *next* command that tried to read from stdin!). Making it only read from stdin if given no arguments would trigger the breakage less often, but would also be harder to *detect* - `count` is often used to figure out if something specifically has 0 or more (it even returns a different return code if given 0 arguments!).

It would be acceptable to add an option, but not for `count` specifically because that currently takes no options at all, and adding any there would break the invariant that you can pass whatever data to it and it would just count.

So you would, in general, have to run count like `count -- $arguments`, because your arguments could contain that `--stdin` option. That's also a rather large breaking change.

For `string` that's less of an issue because it already has options  (and would fail if you gave it an unknown option) and for `math` even less because `--stdin` doesn't look like something you can compute anyway.

**Comment by andrey-mishchenko** [comment] 2021-11-18 19:21
It sounds like the way this is built now is the way users expect it to work, and unless I misunderstand something, you can always `begin ; ... ; cat | count ; ...` if you want to consume all of stdin. The reason I ran into this is that if you execute a shell command from Neovim, it wraps it in a `begin ; {your command text} ; end < input_tmp_file > output_tmp_file`, so piping some lines in Neovim through `count` didn't work. Any change to the builtins (adding command line arguments) would not have avoided my encountering an issue. And in my case I can just `wc -l` for this particular use case in the future.

It might be nice to add a warning to the docs (maybe in https://fishshell.com/docs/current/cmds/begin.html?highlight=blocks -- or I'm open to hearing about a better place for it) that there is this special case related to how redirection works with blocks. I would be happy to take a stab at that if you think it's reasonable. Actually, I don't remember seeing it anywhere in the docs (except `man begin`) that redirection and piping works this way for blocks. But maybe this is such a rare edge case that it would just be noise in the docs.
