### ISSUE TITLE
"d0" in vi-normal-mode does not delete to the beginning of the line

### ISSUE THREAD

**Issue by sashasylona** [fish-shell/fish-shell#5585] opened 2019-01-26 12:39 UTC
Fish version: 3.0.0 
OS: Arch
Terminal: Kitty

sh -c 'env HOME=$(mktemp -d) fish' does not solve the issue

How to reproduce: Enable Fish's vi-mode keybindings. Enter normal mode. Type some text. The 0 moves to the beginning of the line as in compliance with Vim's spec, however modifiers put before this (such as d, y, &.c) do not work. Despite not deleting to the beginning of the line, d0 does indeed return to the beginning.

This is not a regression from Fish <3.0.0

**Comment by faho** [comment] 2019-01-26 13:54
This is supposed to work, and it does on my system.

Please post the output of `bind 0`.

**Comment by sashasylona** [comment] 2019-01-26 13:59
My apologies, I egregiously misremembered the issue itself; I've now changed the title of the issue to properly reflect it. 0 Does indeed return to the beginning of the line, however modifiers do not work in association with it (e.g. d0 does not delete to beginning of line, y0 does not yank, et al). Those modifiers _do_ work with $ and l/h. After having tested it slightly more, this also does not work with gg/G.

**Comment by faho** [comment] 2019-01-26 14:01
In that case, this is a duplicate of #4019.

**Closed by faho** 2019-01-26 14:01 UTC
Labels: vi-mode

**Comment by sashasylona** [comment] 2019-01-26 14:04
Great, cheers!
