### ISSUE TITLE
Custom format for match results?

### ISSUE THREAD

**Issue by rafaelrinaldi** [fish-shell/fish-shell#2593] opened 2015-12-09 19:17 UTC
Is there a way I can format the output of match results? I wanted to highlight the current match on the suggestions list.
I've tried a bunch of options from the [color variables](http://fishshell.com/docs/current/index.html#variables-color) but none of them seem to achieve what I want.

Here's an example of the current output that I see whenever a suggestion list is offered based on my input:

![fish-highlight](https://cloud.githubusercontent.com/assets/87162/11695852/775bc2c4-9e98-11e5-8c26-d7622a65e361.gif)

I wanted to highlight the current suggestion of the list so its easier to navigate through it.

Is there any way to do this?

**Comment by faho** [comment] 2015-12-09 19:22
$fish_color_search_match should do what you want, though it should already be set by default. Mine is set to "--background=purple".

Which terminal are you using and what is your $TERM?

**Comment by rafaelrinaldi** [comment] 2015-12-09 19:33
@faho hey, thanks! This is very close to what I want. I was able to change the background color but not the text color.
The command I'm using is:

```sh
set fish_color_search_match white --background=yellow
```

What am I doing wrong?

Oh, and my `$TERM` is `xterm-256color`.

**Comment by faho** [comment] 2015-12-09 19:37
You're not doing anything wrong, we're [only using the background color](https://github.com/fish-shell/fish-shell/blob/master/src/pager.cpp#L128).

**Comment by rafaelrinaldi** [comment] 2015-12-09 19:38
@faho Gotcha. So, the text color is not customizable at all?

**Comment by faho** [comment] 2015-12-09 19:40
>So, the text color is not customizable at all?

Right now, no.

I've just found this is a duplicate of #2442. Thanks!

**Closed by faho** 2015-12-09 19:40 UTC

**Comment by rafaelrinaldi** [comment] 2015-12-09 20:37
@faho Thanks for the help.
