### ISSUE TITLE
default flatpak autocompletions load up incorrect completions for package names

### ISSUE THREAD

**Issue by fluoriteByte** [fish-shell/fish-shell#10661] opened 2024-08-10 12:42 UTC
fish version: 3.7.1
OS: Vanilla-OS, based on debian sid

Behavior observed also on debian 12 system, can be reproduced in any terminal emulator or tty

asciinema recording:
https://asciinema.org/a/sEBlKEDzmatp5DFJtjrv2Q2H6

**Comment by faho** [comment] 2024-08-10 12:45
Duplicate of #10514

**Closed by faho** 2024-08-10 12:45 UTC
