### ISSUE TITLE
completion fails on certain file

### ISSUE THREAD

**Issue by derhuerst** [fish-shell/fish-shell#3886] opened 2017-03-09 23:24 UTC
- `fish --version`: `fish, version 2.5.0`
- Terminal: macOS `10.12.3` `Terminal.app` `2.7.1 (388)`
- `echo $TERM`: `xterm-256color`
- [x] tried fish without third-party customizations

When trying to run any command (I tried `mkcd`, a custom function, as well as `ls`), the completion breaks with a certain file name, as shown in the following Asciicast:

[![asciicast](https://asciinema.org/a/106555.png)](https://asciinema.org/a/106555)

`ls -l J*` gives me the following:

```
-rw-r--r--  1 j  staff  4505082 Nov  1 20:44 Jacob's Kelly ‎– Funk Key-SbtjBKeqEgA.opus
```

**Comment by faho** [comment] 2017-03-09 23:41
These issues happen when fish and your terminal disagree on where the cursor is, which happens when there's a character that has a display-width different from its length in bytes that either of the two doesn't know about.

That dash there between artist and song appears to be an en-dash. In UTF-8, it's 3 bytes long (e2 80 93).

IIRC Terminal.app has an option somewhere about how to treat "ambiguous width" characters or something. Try switching that.

**Comment by derhuerst** [comment] 2017-03-09 23:56
> IIRC Terminal.app has an option somewhere about how to treat "ambiguous width" characters or something. Try switching that.

Didn't change anything.

Also stumbled upon #2451 btw.

**Comment by faho** [comment] 2017-03-10 00:06
Okay, this is actually even worse. Github swallowed something here, the json file I downloaded from asciinema revealed that it's not _just_ an en-dash.

`echo '–' | od -t x1z` here says it's `e2 80 8e e2 80 93` - i.e an en-dash preceded by a \u200e - a "left-to-right mark".

Obviously this can be worked around by renaming the file (and possibly deleting all relevant entries from history, though for suggestions that shouldn't be relevant once they've been pushed from the top of the stack), and that's not going to be much of an issue because this "character" is bogus here anyway.

A real fix is going to be much harder.

**Comment by faho** [comment] 2017-03-10 00:14
I'm going to close this as a duplicate of #2652, since the underlying issue is that unicode support is _hard_, especially when you need to coordinate across two different programs that don't know each other and only communicate via an in-band signalling protocol from the seventies.

**Closed by faho** 2017-03-10 00:14 UTC
