### ISSUE TITLE
FIFOs don't support multiple readers on Cygwin

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#2152] opened 2015-06-26 07:06 UTC
[On the mailing list, Andrew reports](http://sourceforge.net/p/fish/mailman/message/34124593/):

> I'm testing in Cygwin x86_64.  fish 2.2b1 builds and runs fine there.
> However, whenever I start a subshell, I get an error message on the console:
> 
> ```
> andrex@... ~> fish
> andrex@... ~> Unable to make or open a FIFO for universal variables with
> path '/tmp/fish.andrex/fishd.arsenic.notifier': Device or resource busy
> ```

This is because [Cygwin only allows single writers on FIFOs](https://www.cygwin.com/ml/cygwin/2013-01/msg00292.html).

The problem goes away if you launch fish with the `fish_universal_notifier` variable set to "shmem".

**Comment by zanchey** [comment] 2015-06-26 07:11
https://cygwin.com/ml/cygwin/2009-07/msg00891.html is also relevant.

**Comment by ridiculousfish** [comment] 2015-06-26 18:00
Nice catch, we should default to shmem on Cygwin then.

**Comment by andrex-e-schulman** [comment] 2015-08-11 01:37
I'm working through some other problems in fish 2.2 in Cygwin right now, so I haven't been able to verify yet that this is fixed.  Once I have fish in an otherwise usable state there, I'll report back here on whether it's fixed.

**Comment by andrex-e-schulman** [comment] 2015-08-11 16:32
Confirmed that this issue is fixed in 2.2.0.  fish 2.2.0 still uses fishd in Cygwin, which I guess is what "shmem" does?

**Comment by ridiculousfish** [comment] 2015-08-11 16:53
shmem mode opens a piece of shared memory, and polls it to check for changes in the universal variables file. fishd is definitely no longer involved :)

**Comment by andrex-e-schulman** [comment] 2015-08-11 19:39
OK, right, no fishd.  That was because of my previous installation error.  So now I'm definitely running fish 2.2.0:

    ASchulma@LC77E1AASCHULMA ~> echo $FISH_VERSION
    2.2.0

But now before every command prompt and at many other times I get a bunch of errors like this:

    Unable to rename file from '/home/ASchulma/.config/fish/fishd.tmp.ZheEU7' to '/home/ASchulma/.config/fish/fishd.LC77E1AASCHULMA': Permission denied
    Unable to rename file from '/home/ASchulma/.config/fish/fishd.tmp.DLDzLz' to '/home/ASchulma/.config/fish/fishd.LC77E1AASCHULMA': Permission denied

I can't figure out why a move within a directory would give "Permission denied".  The directory is writeable by me:

    ASchulma@LC77E1AASCHULMA ~> ll -d /home/ASchulma/.config/fish
    Unable to rename file from '/home/ASchulma/.config/fish/fishd.tmp.37wA6G' to '/home/ASchulma/.config/fish/fishd.LC77E1AASCHULMA': Permission denied
    drwx------ 1 ASchulma Domain Users 0 Aug 11 15:34 /home/ASchulma/.config/fish/

And even when I make it world-writeable, I still get the errors.

And at startup I get a few errors like

    fish: Old versions of fish appear to be running. You will not be able to share variable values between
    old and new fish sessions. For best results, restart all running instances of fish.

although no old versions of fish are running.  And universal variables aren't shared.  

So is my build using shmem?  How can I tell?  I looked around in config.h and config.log and didn't see it.

**Comment by ridiculousfish** [comment] 2015-08-11 19:49
That message shows up when fish determines that fishd is running. The technique is a little tricky and may not work on Cygwin. Is fishd running? If so you can just kill it.

The shmem notifier is just for live updates, i.e. "watch my colors change." fish always checks for changes after running a command, so if universal variables are not updating even after running a new command then it's not related to the shmem notifier.

The error about file renaming is likely the culprit. Does `/home/ASchulma/.config/fish/fishd.LC77E1AASCHULMA` already exist? (I'd expect it to). If so, does it have bad ownership or permissions?

**Comment by ridiculousfish** [comment] 2015-08-11 19:49
Thanks for taking the time to work through these issues!

**Comment by faho** [comment] 2015-08-12 12:35
>If so, does it have bad ownership or permissions?

In particular, this might be caused by #2176.

**Comment by andrex-e-schulman** [comment] 2015-08-12 13:57
Alas, no, there's no file `/home/ASchulma/.config/fish/fishd.LC77E1AASCHULMA`, and no permission problem:

    ASchulma@LC77E1AASCHULMA ~> ls -al .config/fish/
    total 412K
    drwx------ 1 ASchulma Domain Users    0 Aug 12 09:46 ./
    drwx------ 1 ASchulma root            0 Aug 12 09:32 ../
    drwx------ 1 ASchulma Domain Users    0 Nov  3  2014 completions/
    -rw------- 1 ASchulma Domain Users 4.4K Jul 24 07:02 config.fish
    -rw------- 1 ASchulma Domain Users 157K Aug 12 09:46 fish_history
    -rw-r--r-- 1 ASchulma Domain Users 154K Aug 10 14:26 fish_history.v4XSD7
    drwx------ 1 ASchulma Domain Users    0 Aug 12 09:34 functions/

(error messages suppressed)  In fact as soon as I create that file, it gets removed again:

    ASchulma@LC77E1AASCHULMA ~> touch .config/fish/fishd.LC77E1AASCHULMA
    
    ASchulma@LC77E1AASCHULMA ~> ls -al .config/fish/
    total 412K
    drwx------ 1 ASchulma Domain Users    0 Aug 12 09:48 ./
    drwx------ 1 ASchulma root            0 Aug 12 09:32 ../
    drwx------ 1 ASchulma Domain Users    0 Nov  3  2014 completions/
    -rw------- 1 ASchulma Domain Users 4.4K Jul 24 07:02 config.fish
    -rw------- 1 ASchulma Domain Users 157K Aug 12 09:48 fish_history
    -rw-r--r-- 1 ASchulma Domain Users 154K Aug 10 14:26 fish_history.v4XSD7
    drwx------ 1 ASchulma Domain Users    0 Aug 12 09:34 functions/

Error messages suppressed again, but it seems that whatever is going wrong in them is causing that file to be removed.

No, no fishd is running.  I verified that in process monitor.

BTW I've set `fish_universal_notifier=shmem` in the Windows shell environment, and verified that it's set after I start fish.  But it doesn't help.  Unless that's something I should change in the build configuration?

At this point I think I'm going to have to do some debugging.  Any pointers to particular source files would be helpful.

**Comment by nekulturny** [comment] 2015-08-19 05:24
This issue is where I got the idea to change the default notifier.  It's an easy change to make.  I just thought maybe there was a better way to do it.  I can post a patch tomorrow but really it's trivial.

The only insight I might have to offer now is related to this:

```
fish: Old versions of fish appear to be running. You will not be able to share variable values between
old and new fish sessions. For best results, restart all running instances of fish.
```

I had that issue too.  But what I eventually figured out is that it was related to building different versions of fish.  I was trying every version of fish under the sun to try to get it to work on Cygwin.  The way I made those errors stop happening is by just closing all instances of fish, removing /tmp/fish.$username, and starting fish again.  Any time I built a different version I would have to go do that (e.g. switching from 2.2.0 to 2.1.2 or vice versa).  I might have also removed ~/.config/fish/fishd.$hostname ... to be honest I don't remember.

fish is working very well for me on Cygwin right now.  However I don't really set a lot of universal variables.  If that feature wasn't working I am not sure I would even notice it.  But I'm not getting any of the errors you're talking about.  I'll review this issue again tomorrow and see if I have anything to add.  It's too late for me to say anything more right now.

**Comment by andrex-e-schulman** [comment] 2015-08-21 14:45
OK, so the following patch sets fish to use shmem for universal variable sharing:

    diff -urN fish-2.2.0.orig/env_universal_common.cpp fish-2.2.0/env_universal_common.cpp
    --- fish-2.2.0.orig/env_universal_common.cpp    2015-07-03 15:46:59.000000000 -0400
    +++ fish-2.2.0/env_universal_common.cpp 2015-08-21 08:25:00.930728300 -0400
    @@ -1611,11 +1611,7 @@
         {
             return s_explicit_strategy;
         }
    -#if FISH_NOTIFYD_AVAILABLE
    -    return strategy_notifyd;
    -#else
    -    return strategy_named_pipe;
    -#endif
    +    return strategy_shmem_polling;
     }
    
     universal_notifier_t &universal_notifier_t::default_notifier()

I didn't know the right way to test for Cygwin, so this is a Cygwin-only patch that just wipes out the other options and always uses `shmem_polling`.  Obviously it would be better to add a test for Cygwin instead.

With this change, the original issue that I reported is resolved.  So once it's committed, I think this bug should be closed.  The other "Permission denied" errors that I reported here seem to be unrelated.  I'm still chasing them down, but they seem to be occur only in the i686 architecture.  I'll open a separate issue for them if that's needed.

**Comment by nekulturny** [comment] 2015-08-22 02:27
I gave putting together a more portable solution a shot.  It just tests for Cygwin.  I think the autoconf philosophy is to test for the actual feature you would like to use, but testing for usable FIFOs is not within my current capabilities.  Note this is my first exposure to autoconf and I don't have any code sense for C or the norms of this project, if there's a better way to go I welcome criticism.

```
diff -r -u fish-shell-master-2015-08-16-21-15-orig/fish-shell-master/configure.ac fish-shell-master-2015-08-16-21-15/fish-shell-master/configure.ac
--- fish-shell-master-2015-08-16-21-15-orig/fish-shell-master/configure.ac      2015-08-16 19:45:42.000000000 -0600
+++ fish-shell-master-2015-08-16-21-15/fish-shell-master/configure.ac   2015-08-21 19:14:59.353202900 -0600
@@ -822,6 +822,24 @@
   AC_MSG_RESULT(no)
 fi

+# Check for usable FIFO (Cygwin allows only a single reader which causes problems)
+AC_MSG_CHECKING([if we have usable FIFOs.])
+AC_CANONICAL_HOST
+case $host_os in
+  *cygwin* ) usable_fifos=no;;
+         * ) usable_fifos=yes;;
+esac
+if test "x$usable_fifos" = "xyes"; then
+  AC_MSG_RESULT(yes)
+  AC_DEFINE(
+    [HAVE_USABLE_FIFOS],
+    [1],
+    [Define to 1 if we have usable FIFOs.]
+  )
+else
+  AC_MSG_RESULT(no)
+fi
+
 # Tell the world what we know
 AC_CONFIG_FILES([Makefile])
 AC_OUTPUT

diff -r -u fish-shell-master-2015-08-16-21-15-orig/fish-shell-master/src/env_universal_common.cpp fish-shell-master-2015-08-16-21-15/fish-shell-master/src/env_universal_common.cpp
--- fish-shell-master-2015-08-16-21-15-orig/fish-shell-master/src/env_universal_common.cpp      2015-08-16 19:45:42.000000000 -0600
+++ fish-shell-master-2015-08-16-21-15/fish-shell-master/src/env_universal_common.cpp   2015-08-21 19:20:19.077247900 -0600
@@ -1626,8 +1626,10 @@
     }
 #if FISH_NOTIFYD_AVAILABLE
     return strategy_notifyd;
-#else
+#elif HAVE_USABLE_FIFOS
     return strategy_named_pipe;
+#else
+    return strategy_shmem_polling;
 #endif
 }
```

**Closed** 2015-08-24 10:47 UTC
Labels: windows
