### ISSUE TITLE
commandline coloring broken on keybindings which call execute

### ISSUE THREAD

**Issue by mamiu** [fish-shell/fish-shell#7420] opened 2020-10-24 17:01 UTC
<img width="823" alt="Screen Shot 2020-10-25 at 02 52 52" src="https://user-images.githubusercontent.com/3653465/97087483-eee28100-166d-11eb-8bd1-f763daeab776.png">

If I now press `Alt` + `Enter` it still show the command in red instead of repainting it correctly. I already tried all combinations with `repaint` but unfortunately that didn't work.

<img width="820" alt="Screen Shot 2020-10-25 at 02 53 26" src="https://user-images.githubusercontent.com/3653465/97087488-f43fcb80-166d-11eb-9317-00dc0a50b7c5.png">

This is a key binding I use quite a lot but therefore many commandlines in an open terminal window look red like in this picture.

Here's another example with a key binding that has a similar coloring issue.

<img width="550" alt="Screen Shot 2020-10-25 at 02 55 48" src="https://user-images.githubusercontent.com/3653465/97087492-f7d35280-166d-11eb-86cc-6daa4a3e8408.png">

I sometimes even have that issue that the commandline shows incorrect colors by pasting commands.

**Comment by faho** [comment] 2020-10-24 17:38
Duplicate of #5912

**Closed by faho** 2020-10-24 17:38 UTC

**Comment by mamiu** [comment] 2020-10-24 19:10
Thanks @faho! Sorry that I didn't find it by myself.

PS:
Hab anscheinend Tomaten auf den Augen 🙈
Schöne Grüße aus Australien

**Comment by mamiu** [comment] 2020-11-06 07:55
This was fixed with https://github.com/fish-shell/fish-shell/issues/5912#issuecomment-722811624
