### ISSUE TITLE
Background color is not part of the theme (fish_config)

### ISSUE THREAD

**Issue by jh3y** [fish-shell/fish-shell#2421] opened 2015-09-24 13:57 UTC
Hi there, 

I may have possibly overlooked something but I have fish shell installed via homebrew, I've just upgraded to `2.2.0` from what I assume was a much older version. I'm trying to use the web interface to configure colors. However, whenever I set a theme using the interface, it seems the changes aren't applied in Terminal (tried different tabs, restarting terminal etc.) Is there a step I'm maybe missing? I've also tried setting colors within `fish_prompt.fish` with the `-g` flag as used in previous versions.

For example;

``` shell
  set -g __fish_git_prompt_color_dirtystate cyan
```

Thanks for any info in advance!

@jh3y

**Comment by faho** [comment] 2015-09-24 14:33
Works for me with current master (both with `set` and `fish_config`). Try `set fish_color_autosuggestion blue`. You should see an effect pretty much immediately.

**Comment by jh3y** [comment] 2015-09-24 14:36
Yeah for some reason doesn't work anymore for me with this version :cry: 

Had already tried setting `autosuggestion` to blue in `fish/functions/fish_prompt.fish`.

Hmmm.

**Comment by faho** [comment] 2015-09-24 14:48
Humm... I'm gonna reinstall fish 2.2.0 and see if we fixed anything in the meantime.

**Comment by faho** [comment] 2015-09-24 14:52
Nope, works for me in 2.2.0 proper, no patches applied, on archlinux (though I can't see what would be OS-specific about this).

**Comment by jh3y** [comment] 2015-09-24 14:58
Hmm. Strange one. I've tried removing `fish`, upgrading `homebrew` then reinstalling. I'm on OSX Yosemite. My config files are symlinked. However, this shouldn't be an issue because making changes such as changing the welcome greeting show correctly after change.

**Comment by zanchey** [comment] 2015-10-15 06:30
Is this still happening? I wonder if you were running some old shells that couldn't communicate with the new version properly.

**Comment by jh3y** [comment] 2015-10-15 13:16
Hey @zanchey , yeah I believe so. I gave up on trying to get it working in the end and just settled for the color scheme it was outputting. `homebrew` and `fish` both up to date. Running on OSX 10.10.3 in `Terminal`.

@jh3y

**Comment by zanchey** [comment] 2015-10-16 04:16
Works OK for me with 10.10. If you are interested in trying to work out what's going on, I think we should start with the output of `set -U | grep color` and the contents of `~/.config/fish/functions/fish_prompt.fish`.

**Comment by crzrcn** [comment] 2015-10-17 19:47
@zanchey,

I have the same problem as @jh3y. I'm on a OSX 10.11 clean install with iterm2, brew, and fish on their latest versions with default configs.

Result of `set -U | grep color`:

```
fish_color_autosuggestion 586e75
fish_color_command 93a1a1
fish_color_comment 586e75
fish_color_cwd green
fish_color_cwd_root red
fish_color_end 268bd2
fish_color_error dc322f
fish_color_escape cyan
fish_color_history_current cyan
fish_color_host '-o'  'cyan'
fish_color_match cyan
fish_color_normal normal
fish_color_operator cyan
fish_color_param 839496
fish_color_quote 657b83
fish_color_redirection 6c71c4
fish_color_search_match --background=purple
fish_color_selection --background=purple
fish_color_status red
fish_color_user '-o'  'green'
fish_color_valid_path --underline
fish_pager_color_completion normal
fish_pager_color_description '555'  'yellow'
fish_pager_color_prefix cyan
fish_pager_color_progress cyan
```

Contents of `~/.config/fish/functions/fish_prompt.fish`:

```
function fish_prompt --description 'Write out the prompt'
	set -l last_status $status

	# Just calculate this once, to save a few cycles when displaying the prompt
	if not set -q __fish_prompt_hostname
		set -g __fish_prompt_hostname (hostname|cut -d . -f 1)
	end

	set -l normal (set_color normal)

	# Hack; fish_config only copies the fish_prompt function (see #736)
	if not set -q -g __fish_classic_git_functions_defined
		set -g __fish_classic_git_functions_defined

		function __fish_repaint_user --on-variable fish_color_user --description "Event handler, repaint when fish_color_user changes"
			if status --is-interactive
				commandline -f repaint ^/dev/null
			end
		end

		function __fish_repaint_host --on-variable fish_color_host --description "Event handler, repaint when fish_color_host changes"
			if status --is-interactive
				commandline -f repaint ^/dev/null
			end
		end

		function __fish_repaint_status --on-variable fish_color_status --description "Event handler; repaint when fish_color_status changes"
			if status --is-interactive
				commandline -f repaint ^/dev/null
			end
		end

		function __fish_repaint_bind_mode --on-variable fish_key_bindings --description "Event handler; repaint when fish_key_bindings changes"
			if status --is-interactive
				commandline -f repaint ^/dev/null
			end
		end

		# initialize our new variables
		if not set -q __fish_classic_git_prompt_initialized
			set -qU fish_color_user; or set -U fish_color_user -o green
			set -qU fish_color_host; or set -U fish_color_host -o cyan
			set -qU fish_color_status; or set -U fish_color_status red
			set -U __fish_classic_git_prompt_initialized
		end
	end

	set -l color_cwd
	set -l prefix
	switch $USER
	case root toor
		if set -q fish_color_cwd_root
			set color_cwd $fish_color_cwd_root
		else
			set color_cwd $fish_color_cwd
		end
		set suffix '#'
	case '*'
		set color_cwd $fish_color_cwd
		set suffix '>'
	end

	set -l prompt_status
	if test $last_status -ne 0
		set prompt_status ' ' (set_color $fish_color_status) "[$last_status]" "$normal"
	end

	set -l mode_str
	switch "$fish_key_bindings"
	case '*_vi_*' '*_vi'
		# possibly fish_vi_key_bindings, or custom key bindings
		# that includes the name "vi"
		set mode_str (
			echo -n " "
			switch $fish_bind_mode
			case default
				set_color --bold --background red white
				echo -n "[N]"
			case insert
				set_color --bold green
				echo -n "[I]"
			case visual
				set_color --bold magenta
				echo -n "[V]"
			end
			set_color normal
		)
	end

	echo -n -s (set_color $fish_color_user) "$USER" $normal @ (set_color $fish_color_host) "$__fish_prompt_hostname" $normal ' ' (set_color $color_cwd) (prompt_pwd) $normal (__fish_git_prompt) $normal $prompt_status "$mode_str" "> "
end
```

**Comment by ridiculousfish** [comment] 2015-10-17 19:52
@crzrcn Which color is different than what you expect? Does the output of `set -U | grep color` match what you set in the config, or does it match what you see on the command line?

**Comment by crzrcn** [comment] 2015-10-17 20:46
@ridiculousfish,

The output of `set -U | grep color` matches what I see on the command line, and I'm assuming it matches the default config since I have not changed the defaults.

My problem is that if I set a theme on the web UI, the changes are not reflected on the command line, nor  on the web UI config if I refresh or reopen.

**Comment by ridiculousfish** [comment] 2015-10-17 20:49
Dumb question: you are actually clicking the button titled 'Set Theme' in the web UI, right? Not just previewing a theme.

**Comment by crzrcn** [comment] 2015-10-17 20:50
Haha, fair question. 

I am. The button text changes to "Theme Set!".

**Comment by ridiculousfish** [comment] 2015-10-18 01:10
If you run, say, `set fish_color_command purple` does it successfully make commands purple?

I wonder if you have an old version of fish installed, which is what the web config is invoking. Does running `which -a fish` show more than one fish installed?

You may have shadowed the universal variables. If you run `set -g | grep color` does it show any fish_color_* variables? If so, that would explain it.

You might also try editing `/usr/local/share/fish/tools/web_config/webconfig.py` (or wherever homebrew put it). In the function `run_fish_cmd` try adding the line `print(text)`. Then when you run `fish_config` it should show the commands that are being executed. When you set a theme, does it show normal looking commands?

Thanks for helping us debug this!!

**Comment by crzrcn** [comment] 2015-10-18 05:43
After my last comment, I have installed and started using [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish). Let me know if you think this would affect anything.

> If you run, say, set fish_color_command purple does it successfully make commands purple?

It does.

> I wonder if you have an old version of fish installed, which is what the web config is invoking. Does running which -a fish show more than one fish installed?

```
~ which -a fish
/usr/local/bin/fish
```

> You may have shadowed the universal variables. If you run set -g | grep color does it show any fish_color_* variables? If so, that would explain it.

```
 ~ set -g | grep color
TERM xterm-256color
history 'which -a fish'  'set fish_color_command 93a1a1'  'echo '  'eval fish_'…
```

Is there a way to expand the "..."? Dunno if there's useful info hidden further in the history.

> You might also try editing /usr/local/share/fish/tools/web_config/webconfig.py (or wherever homebrew put it). In the function run_fish_cmd try adding the line print(text). Then when you run fish_config it should show the commands that are being executed. When you set a theme, does it show normal looking commands?

I ran `fish_config`, and selected the Solarized Dark preview, and then click on "Set theme".

```
 web_config master fish_config
Web config started at 'file:///Users/crzrcn/.cache/fish/web_config-IO0B4V.html'. Hit enter to stop.
set -L
::1 - - [17/Oct/2015 22:35:30] code 403, message Forbidden, path /favicon.ico
set -U fish_color_autosuggestion 586e75
set -U fish_color_command 93a1a1
set -U fish_color_param 839496
set -U fish_color_redirection 6c71c4
set -U fish_color_comment 586e75
set -U fish_color_error dc322f
set -U fish_color_quote 657b83
set -U fish_color_end 268bd2
```

The colors outputted by `print(text)` don't quite match the ones given in the web UI. I'm using [Digital Color Meter](https://en.wikipedia.org/wiki/DigitalColor_Meter) to get the RGB value from the web UI and converting that to hex for comparison with the ones outputted by the `print(text)`.

**Comment by crzrcn** [comment] 2015-10-19 02:48
@ridiculousfish I made a mistake. I was assuming that the background color was part of the theme. This is clearly not the case. I tried changing the theme today, and paid more attention this time; the colors are being set correctly for me.

Sorry for wasting your time.

**Comment by ridiculousfish** [comment] 2015-10-19 05:17
Ah-ha! That's a relief.

You're not the first to be tripped up by that. Any ideas for how we could make it more clear that the background color is just for previewing?

**Comment by crzrcn** [comment] 2015-10-19 06:12
I _just_ saw the title for the background color picker. A quick fix, but not quite so subtle would be to add a small caption with a shorter version of the background color picker title to the right of "Preview a theme below:", right below the "Customize", and "Set Theme" buttons. Something like "Background color for preview only. Fish cannot change the background color of your terminal."

Moving the background color picker to outside the preview box might help solidify the idea that they are separate.

**Comment by pickfire** [comment] 2015-10-19 06:18
Just add something like that in the background page:
```
⚠ The background color is just for preview purpose!
```

**Comment by ridiculousfish** [comment] 2015-10-19 18:30
Maybe change the text from "Background" to "Demo on Background", and have some rollover or click-to-reveal explanatory text.

**Comment by d12frosted** [comment] 2015-11-11 17:17
When I run `fish_config` and try to set theme I see following message.

```
::1 - - [11/Nov/2015 19:07:29] code 403, message Forbidden, path /431e01680a820bd6e56e1f58cb21aba8/set_color/
```

I can't setup theme via that web view, but I can change colours via `set fish_color_xxx HEX`. 

My setup:

* `OS X 10.11.1 (15B42)` – though it wasn't working on OS X 10.10 as well
* `brew 0.9.5 (git revision d872c; last commit 2015-11-10)`
* `fish, version 2.2.0-394-g0918ad6`

**Comment by krader1961** [comment] 2015-12-31 01:09
FYI, we just had a discussion about this on the fish-users mailing list. The web UI is definitely confusing people. Heck, it even confused me until I noticed palette in the upper right corner for changing the background which caused me to go "Aha, the background color probably isn't part of the theme."

**Comment by krader1961** [comment] 2015-12-31 03:05
See also issue #2184 where someone points out that the background color "chosen" in the web UI isn't persisted leading to confusion the next time `fish_config` is run. The problem is, of course, that no window background color is being chosen in the sense that fish will remember the choice and set it when fish runs.

I'll take a stab at updating the documentation to try and make the existing behavior clearer. I don't know if I'll be able to update the web UI. I've written raw Javascript but I've never used AngularJS.

**Comment by krader1961** [comment] 2016-01-06 05:03
Once I started to address this issue it became clear no knowledge of Angular.js was required. See the attached image for what I propose as a solution to this issue. My change will also modify the set_color man page with similar verbiage.
![screenshot 2016-01-05 20 59 30](https://cloud.githubusercontent.com/assets/7545917/12135379/bffb60cc-b3ef-11e5-94bd-4c5b3d55db44.png)

**Comment by ridiculousfish** [comment] 2016-01-06 05:56
That text is visible all the time? That's way too busy and too much to read. I suggest a little tooltip that appears on hover over the background color that says "Preview only".

**Comment by krader1961** [comment] 2016-01-07 02:10
The widget that sets the background color already has a tooltip that explains it isn't sticky. I suppose that could be repurposed for the entire theme preview division. However, given how often people are confused by this aspect of selecting a theme I'm skeptical a tooltip that appears only when hovering over the theme will be enough to keep people from being surprised and thinking the mechanism is broken. As for the text being "too busy" I think truncating it to just the first two sentences is adequate to address this issue. The extra text is just me being pedantic about providing a complete explanation.

**Comment by faho** [comment] 2016-01-07 11:42
How about just changing the text from "Background:" to "Background (Preview):" or "Illustration"?

**Comment by ridiculousfish** [comment] 2016-01-07 21:07
Maybe something like:

**Preview on Background**
(Use your terminal to change your actual background color)

except even that second line is too verbose.

**Comment by krader1961** [comment] 2016-01-08 03:51
@faho and @ridiculousfish: I think you are overestimating the ability of typical users to correctly interpret your proposed text. Having said that what about this compromise:
![screenshot 2016-01-07 19 50 02](https://cloud.githubusercontent.com/assets/7545917/12189968/fc8c8d52-b577-11e5-97ee-456dce659205.png)

**Comment by faho** [comment] 2016-01-08 12:01
@krader1961: I actually believe that might work.

**Comment by ridiculousfish** [comment] 2016-01-08 19:23
Can we try moving the text to inside the box, perhaps under the "Background Color" section? Basically keep it next to the thing it's talking about, and get it out of the center where it grabs more attention than it needs.

(I should get my wife to take a look, she's a designer)

**Comment by pickfire** [comment] 2016-01-09 07:55
Maybe the color of button can be changed depending on the background color so that it have better interface (The button seems weird with light colors) when using light background.

**Comment by krader1961** [comment] 2016-01-10 01:43
Here's another example that shows the popup that users will see if they hover the mouse over the theme preview box. For extra measure I've also changed the "Set Theme" button text to make it crystal clear the background will not be saved. With this iteration we can probably drop the "(illustration only)" from the background color picker text.

![screenshot 2016-01-09 17 38 49](https://cloud.githubusercontent.com/assets/7545917/12219437/1302f3f6-b6f8-11e5-92bd-d6d94373fc79.png)

**Comment by krader1961** [comment] 2016-01-15 05:51
Since no one has commented on my most recent proposal I'm going to assume no one has any objections and push that change to my pull request.

**Comment by quicksketch** [comment] 2016-08-31 04:57
Hi all, I recently just had this whole experience all over again. I'm using the latest fish (2.3.0) but even the preview title text didn't drive this home for me at all. I had to find this issue and read through it, and even then I still didn't understand *how* to change the background color (but some extra Googling helped me out).

After changing the background color in my terminal preferences (finally! `gnome-terminal` hides it under "Profile preferences" instead of "Preferences"), I then found the helpful description text when hovering over the `fish_config` UI in the browser.

So my suggestion is this: The help text is great but the visibility of it is poor. I would suggest that an old-school `window.alert()` be used the *first time per page load* that contains this help text when changing the background color. That's how important this message is (in my opinion).

**Comment by ridiculousfish** [comment] 2016-09-01 19:01
@quicksketch are you suggesting we show an alert at the time the page is loaded, or when the user attempts to changes the background color via the UI?

**Comment by quicksketch** [comment] 2016-09-02 04:51
Oh, definitely only when the user attempts to change the background color. But only the first time (once per page load) so that if you're trying out lots of different colors you don't keep getting the alert.

**Comment by ridiculousfish** [comment] 2016-09-02 04:52
Cool, that makes sense to me.

**Comment by zanchey** [comment] 2016-09-13 01:15
If the solution we have isn't enough, let's reopen the issue.

**Comment by floam** [comment] 2016-09-13 01:17
What's the preferred issue label for stuff we probably agree is a UX/usability issue? "bug" and "enhancement" both are not quite right.

**Comment by quicksketch** [comment] 2016-09-14 01:42
Thanks @zanchey et al. I love that the Fish team is so receptive to feedback!

**Comment by krader1961** [comment] 2017-03-17 05:16
Closing this issue because the `fish_config` UI has been changed in an attempt to address the original issue. I think it makes sense to wait for a new issue if people are still confused rather than leave this issue open indefinitely.

**Closed by krader1961** 2017-03-17 05:16 UTC
Labels: enhancement
