### ISSUE TITLE
fish_config (web interface) suggests 'file' protocol, not 'http'

### ISSUE THREAD

**Issue by llagerlof** [fish-shell/fish-shell#6108] opened 2019-09-12 16:46 UTC
When I try to run fish_config his web server is not launched. The command only show a filesystem url:

```
lawrence@myubuntu /m/c/r/d/w/s/cron> fish_config
Web config started at 'file:///home/lawrence/.cache/fish/web_config-ZR4S6H.html'. Hit enter to stop.
```

I am not using the 8080 port.

I am using Ubuntu under WLS.

**Comment by zanchey** [comment] 2019-09-13 12:40
`fish_config` provides a file path to a generated HTML file that redirects to the web server with the correct authentication path. This is for security reasons - see #1438 and friends.

What version are you running?

**Comment by llagerlof** [comment] 2019-09-13 16:50
I made more tests. Just to be sure we are all in the same page:

- I already use a web server in ubuntu wls and access it sucessfully using a browser on Windows and Ubuntu (links).
- I am using default port on Apache (80).

The tests I made:

- On Ubuntu I started the fish_config inside fish shell.
- In another shell I tried a telnet localhost 8000. The port is open (i don't know why in the last time the port was closed).
- In another shell I tried to access http://localhost:8000/HASH_PROVIDED_BY_FISH_CONFIG using links. After some time the browser returns an error 408 (timeout).
- I made the same tests on Windows Command Prompt (cmd.exe) using telnet and Firefox. Same results.

So, yes, the web server started sucefully. It's just not responding the requests.

> What version are you running?

- fish, version 2.7.1

**Comment by llagerlof** [comment] 2019-09-13 17:50
I uninstalled the 2.7.1 (package from repository), downloaded the 3.0.2 and compiled the source.

Now the web server created by fish_shell is working. I am accessing it from Ubuntu and Windows.

Thanks guys.

**Comment by zanchey** [comment] 2019-09-14 13:05
Closing as a duplicate of #4299.

**Closed by zanchey** 2019-09-14 13:05 UTC
Labels: duplicate

**Comment by gilvaju** [comment] 2019-12-16 12:15
Same problem.

![image](https://user-images.githubusercontent.com/677039/70906079-5064a880-1fe4-11ea-9888-9e8788801137.png)

I am not using the 8080 port.
I am using Ubuntu under WLS.

![image](https://user-images.githubusercontent.com/677039/70906148-83a73780-1fe4-11ea-8a2b-c3156d7b66e5.png)

I using ubuntu 18.04 on wsl2
