### ISSUE TITLE
Tab filename completion icon

### ISSUE THREAD

**Issue by lqvsyi2** [fish-shell/fish-shell#10974] opened 2024-12-30 13:35 UTC
Please tell us which fish version you are using by executing the following:
  
~ fish --version
fish, version 3.7.1
~ echo $version
3.7.1
~

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

~ uname -a
Linux localhost 5.4.86-qgki-gceb92b89aa28 #1 SMP PREEMPT Wed Aug 14 03:39:32 CST 2024 aarch64 Android
~ echo $TERM
xterm-256color
~

It looks like this.

![Screenshot_20241228_164417](https://github.com/user-attachments/assets/51b89524-f6f7-4a93-b31a-5c3c72bb3fff)

[lsd command](https://github.com/lsd-rs/lsd)

**Comment by faho** [comment] 2024-12-30 13:37
Duplicate of #2868

**Comment by faho** [comment] 2024-12-30 13:38
Completions currently cannot print anything that doesn't show up in the finished token.

Doing that requires the same work that it would require to print them as colored, so I'm counting this as a piece of #2868.

**Closed by faho** 2024-12-30 13:37 UTC
