### ISSUE TITLE
Non English speaking country + language set to EN results in fish: Tried to print invalid wide character string"

### ISSUE THREAD

**Issue by MaciekTalaska** [fish-shell/fish-shell#2716] opened 2016-02-07 18:37 UTC
I am experiencing an error starting fish shell when my country is set to Poland, but language is set to English. The official language in Poland is Polish, but I prefer it that way.

I am using powerline-shell (https://github.com/milkbikis/powerline-shell) and powerline-fonts (https://github.com/powerline/fonts)

Whenever I start fish, I get the following error: "fish: Tried to print invalid wide character string"

I have commented out my entire configuration in fish.config and I know that this is related to powerline trying to print something weird.  (If I comment the powerline related section fish starts normally).

Exporting LANG as en_US doesn't fix the problem. Fish shell starts, but powerline produces strange results.

What 'locale' outputs is:

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_PL.UTF-8
LANGUAGE=en
LC_CTYPE="en_PL.UTF-8"
LC_NUMERIC=en_PL.UTF-8
LC_TIME=en_PL.UTF-8
LC_COLLATE="en_PL.UTF-8"
LC_MONETARY=en_PL.UTF-8
LC_MESSAGES="en_PL.UTF-8"
LC_PAPER=en_PL.UTF-8
LC_NAME=en_PL.UTF-8
LC_ADDRESS=en_PL.UTF-8
LC_TELEPHONE=en_PL.UTF-8
LC_MEASUREMENT=en_PL.UTF-8
LC_IDENTIFICATION=en_PL.UTF-8
LC_ALL=

Other details:
fish --version:
fish, version 2.2.0

I am on Kubuntu (Ubuntu spin-off with KDE):
lsb_release -a:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

uname -a

Linux xps 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

What is funny, if I set the country back to US, and customize Country/Region & Language (so I set date format, number format, currency etc. to the format used in Poland) all works well (fish starts, I have nice powerline command prompt etc.).

In such case, the locale reports:

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_PL.UTF-8
LANGUAGE=en
LC_CTYPE="en_PL.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_PL.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_PL.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

There are couple of differences:
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8

I have tried to set these directly in fish.config (before overriding fish_prompt with powerline-shell, but with no luck).
I have also tried to set everything to pl_PL.UTF-8 - without any success.

Any help with this?

Is this a bug in fish shell? Or is it something rather related to powerline-shell?

**Comment by bucaran** [comment] 2016-02-07 18:44
I was helping a friend migrate from Bash to Fish the other day [here](https://github.com/bucaran/ben-learns-fish/commit/1843c26f3100ddcb3b3d2c355ea100f35d935b92) and I know for a fact he is using the same Powerline-shell and also changing his locale to English.

He is using the following and while we were troubleshooting together, the locale issue never came up.

```fish
set -x LC_ALL en_US.UTF-8
set -x LANG en_US.UTF-8
```

**Comment by MaciekTalaska** [comment] 2016-02-07 19:04
Yes, you're right - I meant `config.fish` under `.config\fish` folder.

As for your suggestion, I have put it before the `powerline-shell` related stuff, like below:

```fish
set -x LC_ALL en_US.UTF-8
set -x LANG en_US.UTF-8

function fish_prompt
    ~/configuration/powerline-shell/powerline-shell.py $status --shell bare ^/dev/null
end
```

unfortunately it didn't work for me - i.e. fish starts, but powerline is not producing proper prompt.

I have never experienced this problem, until I have switched my "Country" to Poland yesterday.

**Comment by faho** [comment] 2016-02-07 19:07
@bucaran: LC_ALL is meant as an override for all other language settings. You shouldn't use it in this way.

@MaciekTalaska: Does the locale "en_US.UTF-8" (and en_PL.UTF-8) exist on your system, ie. is it included in the output of `locale -a`? If not, you might need to run `locale-gen en_US.UTF-8` (as root).

**Comment by bucaran** [comment] 2016-02-07 19:09
@faho I am not using it. I just took it verbatim from my friend's `config.fish`, but I'll read up on `LC_ALL` as obviously I didn't find that odd in the first place, thanks.

**Comment by MaciekTalaska** [comment] 2016-02-07 19:36
@faho 
Among many others the `en_US.utf8` and `pl_PL.utf8` exist on my machine. 

I tried to `sudo locale-gen en_PL.UTF-8` (as well as `sudo locale-gen en_PL.utf8`) but that didn't result in a locale being generated. 

I think this is due to the fact that English is not official language in Poland. 
All the other locales for English on my machine are only for the countries that are English speaking countries/territories, like: Ireland, Great Britain, New Zealand, Canada, Hong-Kong, Singapore, Zambia (well... apart from DK - Denmark - Danish is the official language in Denmark).

**Comment by faho** [comment] 2016-02-07 19:40
>I think this is due to the fact that English is not official language in Poland.
All the other locales for English on my machine are only for the countries that are English speaking countries/territories

Yeah, that's how the locale thing works - you choose a certain variant of a language - like en_US if you want everything to say "color" and en_GB if you're a fan of silly superfluous "u"s. It's not that you say "language_COUNTRY", but that "country" is a certain version of the language - "pt_BR" is a thing because brazilian portuguese is different from portuguese portuguese, but there's no "polish english", so "en_PL" isn't a thing.

However, it should still work if you set your locale to something actually existent (and "compiled") like "en_US.UTF-8".

If you do that, do you still get the "wide character" message? It's possible the powerline thing is a different issue.

**Comment by MaciekTalaska** [comment] 2016-02-07 20:05
If I set my country to Poland, restart machine, and then launch Konsole - I will get the "wide character" message.

If I put `set -x LANG en_US.UTF-8` in the `config.fish` the message does not appear. Although the powerline's prompt is broken.

I don't really understand why some of the variables (such as LC_TIME, LC_PAPER, LC_NAME, LC_ADDRESS, LC_TELEPHONE, LC_MEASUREMENT, LC_IDENTIFICATION) are set to `en_PL.UTF-8`). That doesn't make any sense - as this is not a proper locale.
I have checked the list of locales that are supported and for Poland there is no `en_PL.*` (as I expected). 

Could that be a problem? I mean - setting country to Poland, but insisting on using EN as language?

When `set -x LANG en_US.UTF-8` is in config file, invoking `locale` results in 

```
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_PL.UTF-8
LC_TIME=en_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_PL.UTF-8
LC_NAME=en_PL.UTF-8
LC_ADDRESS=en_PL.UTF-8
LC_TELEPHONE=en_PL.UTF-8
LC_MEASUREMENT=en_PL.UTF-8
LC_IDENTIFICATION=en_PL.UTF-8
LC_ALL=
```

I think the message about the non-existing file/directory could be a clue.

I have also tried bash. Powerline is broken under bash as well (but I don't specify a locale in bash.rc). Bash gives a bit different error:

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_PL.UTF-8
```

(rest is the same as the output of `locale` when invoked from fish shell).

**Comment by faho** [comment] 2016-02-07 20:17
>I don't really understand why some of the variables (such as LC_TIME, LC_PAPER, LC_NAME, LC_ADDRESS, LC_TELEPHONE, LC_MEASUREMENT, LC_IDENTIFICATION) are set to en_PL.UTF-8). That doesn't make any sense - as this is not a proper locale.

You're right - "en_PL" is nonsense. You'll want to set those that should be english to "en_US" or "en_GB" or something (or empty since they'll then be overridden by LANG), and the ones where you want the polish semantics (like e.g. for displaying time) to "pl_PL" - all in the ".UTF-8" version. Ideally you'll set them outside (e.g. in KDE) and let fish inherit them, but if that doesn't work you should also be able to set them in config.fish.

>I have also tried bash. Powerline is broken under bash as well (but I don't specify a locale in bash.rc). Bash gives a bit different error:

That error is also because of en_PL, so we still don't quite know if you've set up powerline correctly.

**Comment by MaciekTalaska** [comment] 2016-02-07 20:31
@faho 

Those variables are not set by myself. These are inherited by fish after the country is set to Poland, but the language is set to American English (this is via 'Country/Region & Language' provided by KDE).

In such a situation, do you think I should manually set LANG, and all the variables above mentioned to en_US.UTF-8? This is the only thing that comes to my mind.

As for the configuration of powerline-shell - I haven't made any changes to it, but looking at its `config.py` right now I can't see anything that would be related to languages/locale etc.

**Comment by xfix** [comment] 2016-02-07 20:45
en_PL.UTF-8 locale is quite strange, I admit. I tried to set KDE language to English, but my locale is still pl_PL.UTF-8.

Anyway, I would recommend checking Regional Settings > Formats, and pick "Polska - polski (pl_PL)" here, without detailed settings.

If that doesn't work, use Settings > Edit current profile > General > Environment > Edit, and add line saying LANG=en_US.UTF-8 if you want English commands in terminal, or LANG=pl_PL.UTF-8 if you want Polish commands in terminal.

**Comment by MaciekTalaska** [comment] 2016-02-07 20:59
@xfix 

I am under KDE, and I am not sure where do I find the 'Regional Settings'. If I set Country to Poland and language to Polish - I will end up having everything in Polish (all apps etc. - I have done that for my parents). 

My plan was to have all things set as for Poland but without changing language to Polish. I am starting to believe, that the only way is to leave the whole thing set to en_US, and make small changes to numbering formats, currency, date & time and so on...

**Comment by MaciekTalaska** [comment] 2016-02-07 21:23
OK. I think I have found a solution.

After setting Country to "Poland" (via 'Country/Region & Language) one needs to at least log off/log in (so the changes are picked up by the environment).

Add the `set -x LANG en_US.UTF-8` in the `config.fish`

In the Konsole: Settings -> Edit Current Profile -> Advanced -> Encoding (this is normally set to UTF-8, by after changing country to Poland it is set to ISO 8859-1). Change i back to UTF-8.

That would make fish shell start without any complaint, and the powerline prompt is rendered correctly.

The only drawback is that after invoking `locale` there is still complaint about LC_ALL, and some variables are set to the nonsensical `en_PL`:

```fish
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_PL.UTF-8
LC_TIME=en_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_PL.UTF-8
LC_NAME=en_PL.UTF-8
LC_ADDRESS=en_PL.UTF-8
LC_TELEPHONE=en_PL.UTF-8
LC_MEASUREMENT=en_PL.UTF-8
LC_IDENTIFICATION=en_PL.UTF-8
LC_ALL=
```
I suspect this could lead to some problems later on, so just to spare myself a bit of Computer-Science-Investigation - I will probably switch back to en_US.

Thanks.

**Comment by faho** [comment] 2016-02-07 21:31
@MaciekTalaska: All of this seems like weird behavior by KDE's regional settings KCM. I unfortunately can't reproduce this as I'm on Plasma 5, which has basically a complete overhaul of that. 

For fish, at least, you can override all that by putting something like

```fish
set -gx LANG en_US.UTF-8
for lc in LC_TIME LC_MONETARY LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
    set -gx $lc pl_PL.UTF-8
ed
```

That should answer your question, so I'll close this issue. If you have any more questions feel free to ask!

**Closed by faho** 2016-02-07 21:31 UTC

**Comment by xfix** [comment] 2016-02-07 21:33
Oh, right, you are using KDE 4, not KDE 5. Sorry for providing wrong instructions.

**Comment by tojamrok** [comment] 2020-11-02 12:22
`LC_COLLATE` should stay `en_US` or `C` though - required by `sort`, `ls -s` etc. (https://superuser.com/questions/1475533/why-does-the-ls-command-sort-files-like-this/1475550#1475550).
