### ISSUE TITLE
Terrible bug because of no primitive list support, real list

### ISSUE THREAD

**Issue by adamcavendish** [fish-shell/fish-shell#2627] opened 2015-12-22 09:51 UTC
If I have a directory called `VirtualBox VMs` (a lot of people do), and I hope to pass a command using eval, and here's the problem:

```
function fire
  set -l command $argv
  eval $command
end
```

Then I'd do:

```
fire ls "VirtualBox VMs"
```

It is expected to list the contents of the directory, however, because of no primitive list support, or the so-called list is flattened into one list. It report it as an error.

**Comment by faho** [comment] 2015-12-22 13:18
That's very much an issue of `eval`, not fish itself. As such, it's a duplicate of #2261.

If you have git fish, you can use the workaround I gave there:

```fish
function call
    set -l cmd $argv[1]
    set -e argv[1]
    eval $cmd (string escape -- $argv)
end
```

**Closed by faho** 2015-12-22 13:18 UTC
