### ISSUE TITLE
100% CPU and fish crashes

### ISSUE THREAD

**Issue by ginfuru** [fish-shell/fish-shell#5629] opened 2019-02-08 13:24 UTC
```shell
fish, version 3.0.0
Darwin MacDaddy 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```
empty terminal session sitting idle - CPU and fans kick on usually force quite fish by quitting terminal

here is the [crash log](https://gist.github.com/ginfuru/92b35f4fe91ad01ee94e4955370bb2a4)

no clue if this is regression issue.

**Comment by zanchey** [comment] 2019-02-08 13:58
Can you confirm the steps to reproduce?

If you start a new Terminal? iTerm? instance, does this happen, or do you need to interact with it?

**Comment by ginfuru** [comment] 2019-02-08 14:54
I literally start a new terminal window and the CPU spikes - I can confirm it **is not** every single time

**Comment by AnotherCoolDude** [comment] 2019-02-08 17:44
Had the same issue after running `brew upgrade fish`. This solved the issue for me: 
Uninstall fish via `brew uninstall fish`, then remove the folder `/usr/local/shared/fish` and these two files:
`/usr/local/share/man/man1/fish.1`
`/usr/local/share/man/man1/fish_indent.1`
install fish again via homebrew

**Comment by ginfuru** [comment] 2019-02-08 17:49
@AnotherCoolDude  Just tried that out, though I did not have the `man1` files -- I haven't gotten much spikes in the CPU yet.

**Comment by ginfuru** [comment] 2019-02-08 22:55
@AnotherCoolDude - Your solution did not work for me. 
CPU currently spiking  - this time I'm just working with git _(on a really small project)_
![screen shot 2019-02-08 at 5 51 59 pm](https://user-images.githubusercontent.com/402910/52510606-971a9280-2bca-11e9-870b-dfb4acda3b65.png)

**Comment by faho** [comment] 2019-02-09 11:15
>Uninstall fish via `brew uninstall fish`, then remove the folder `/usr/local/shared/fish` and these two files:

@AnotherCoolDude: What made you think of that?

----

We've had a few reports that might be related:

- #5596, where fish freezes because a process it started switched process groups and then crashed

- #5627, where disowned processes would be waited on wrongly

Both of these would be triggered by something in your config files. So

@ginfuru: Can you move your fish configuration out of the way and see if that doesn't show the issue?

Ideally, could you try the Integration_3.0.1 branch (https://github.com/fish-shell/fish-shell/tree/Integration_3.0.1) which has all those fixes applied, or alternatively master which includes those and a bunch more?

**Comment by mqudsi** [comment] 2019-02-09 18:37
@ginfuru's initial post includes the stack trace which shows that fish hit an assertion. I don't believe any of the referenced issues involved an assertion failure.

The stack trace says `process_mark_finished_children(bool) + 711`, but I have no clue if `711` is instructions, lines, or what. However, `process_mark_finished_children()` in 3.0.0 had only two assertions:

https://github.com/fish-shell/fish-shell/blob/938ce48d259d1ceee51312b6b3e005fabfc07d1f/src/proc.cpp#L418-L420

and 

https://github.com/fish-shell/fish-shell/blob/938ce48d259d1ceee51312b6b3e005fabfc07d1f/src/proc.cpp#L469

**Comment by floam** [comment] 2019-02-10 01:06
> but I have no clue if `711` is instructions, lines, or what.
The + number is the number of bytes offset from the entry point of the function to the instruction which caused the crash.

Since he installed 3.0.0 with homebrew on 10.14, it's a good bet we can inspect the same binary it installed in the tarball of the "bottle":

https://bintray.com/homebrew/bottles/download_file?file_path=fish-3.0.0.mojave.bottle.tar.gz

Should be able to figure out exactly which assert it was with lldb.

**Comment by floam** [comment] 2019-02-10 01:56
the disassembly around where the crash report indicated:

```hex
0x1012b57b2 <+679>: je     0x100094664               ; <+345>
0x1012b57b8 <+685>: leaq   0x4ce41(%rip), %rdi       ; "(!job_fg || !job_fg->job_chain_is_fully_constructed() || !j->job_chain_is_fully_constructed()) && "More than one active, fully-constructed foreground job!""
0x1012b57bf <+692>: leaq   0x4cc3a(%rip), %rsi       ; "/tmp/fish-20181228-21895-1ih942f/fish-3.0.0/src/proc.cpp"
0x1012b57c6 <+699>: movl   $0x1a4, %edx              ; imm = 0x1A4 
0x1012b57cb <+704>: xorl   %ecx, %ecx
0x1012b57cd <+706>: callq  0x100033a74               ; __fish_assert(char const*, char const*, unsigned long, int)
0x1012b57d2 <+711>: xorl   %r12d, %r12d
0x1012b57d5 <+714>: movq   0x56e3c(%rip), %r13       ; s_disowned_pids
0x1012b57dc <+721>: movq   0x56e3d(%rip), %r15       ; s_disowned_pids + 8
0x1012b57e3 <+728>: cmpq   %r15, %r13
0x1012b57e6 <+731>: je     0x10009480f               ; <+772>
0x1012b57e8 <+733>: leaq   -0x60(%rbp), %r14
```

**Comment by floam** [comment] 2019-02-10 03:21
Can you show us your prompt, @ginfuru? Is it the default?

`type fish_prompt`

**Comment by floam** [comment] 2019-02-10 03:50
I think there's some mechanism to make it so that the OS will put some "Application specific information" into the crash report files. It would be neat to figure out how to stick some better information about fish's internal state into these on Darwin.

**Comment by floam** [comment] 2019-02-10 08:47
I happened to discover that ridiculous function will lead to a fish process spinning at 100% CPU after the window goes away:

`function fish_title; read foo; end`

**Comment by ginfuru** [comment] 2019-02-10 18:11
@faho output of the two commands
`type fish_prompt` :
```shell
fish_prompt is a function with definition
# Defined in /Users/ed/.iterm2_shell_integration.fish @ line 72
function fish_prompt --description 'Write out the prompt; do not replace this. Instead, change fish_prompt before sourcing .iterm2_shell_integration.fish, or modify iterm2_fish_prompt instead.'

    # using the string builtin from fish, but to make sure any escape codes
    # are correctly interpreted, use %b for printf.
    printf "%b" (string join "\n" (iterm2_fish_prompt))

    iterm2_prompt_end
end
```
`type fish_titl` :
```shell
fish_title is a function with definition
# Defined in /usr/local/Cellar/fish/3.0.0/share/fish/functions/fish_title.fish @ line 1
function fish_title
    echo (status current-command) " " (__fish_pwd)
end
```

**Comment by ginfuru** [comment] 2019-02-10 18:16
when I comment out the `iterm2_shell_integration` 
`type fish_prompt`
```shell
fish_prompt is a function with definition
# Defined in /Users/ed/.config/fish/functions/fish_prompt.fish @ line 1
function fish_prompt

    set -g sf_exit_code $status
    set -g SPACEFISH_VERSION 2.2.0

    # ------------------------------------------------------------------------------
    # Configuration
    # ------------------------------------------------------------------------------

    __sf_util_set_default SPACEFISH_PROMPT_ADD_NEWLINE true
    __sf_util_set_default SPACEFISH_PROMPT_FIRST_PREFIX_SHOW false
    __sf_util_set_default SPACEFISH_PROMPT_PREFIXES_SHOW true
    __sf_util_set_default SPACEFISH_PROMPT_SUFFIXES_SHOW true
    __sf_util_set_default SPACEFISH_PROMPT_DEFAULT_PREFIX "via "
    __sf_util_set_default SPACEFISH_PROMPT_DEFAULT_SUFFIX " "
    __sf_util_set_default SPACEFISH_PROMPT_ORDER time user dir host git package node ruby golang php rust haskell julia docker aws conda pyenv dotnet kubecontext exec_time line_sep battery vi_mode jobs exit_code char

    # ------------------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------------------

    # Keep track of whether the prompt has already been opened
    set -g sf_prompt_opened $SPACEFISH_PROMPT_FIRST_PREFIX_SHOW

    if test "$SPACEFISH_PROMPT_ADD_NEWLINE" = "true"
        echo
    end

    for i in $SPACEFISH_PROMPT_ORDER
        eval __sf_section_$i
    end
    set_color normal
end
```

**Comment by faho** [comment] 2019-02-10 18:38
>when I comment out the `iterm2_shell_integration`

Just to make sure: That still triggers the problem?

If you change that `eval __sf_section_$i` to just `__sf_section_$i`, does that still trigger it? (eval does weird stuff with job control)?

**Comment by floam** [comment] 2019-02-10 19:03
Yeah, the only thing in there that seems like it has potential to trigger stuff is `eval`. Maybe also show us the output of `type fish_right_prompt`.

But I assume others use this prompt OK on 3.0.0? Same for iTerm. 

**But first, please make sure we're not barking up the wrong tree: does this still happen if you launch fish with the default configuration?**

`sh -c 'env HOME=$(mktemp -d) fish'`

**Comment by mqudsi** [comment] 2019-02-10 20:36
> I happened to discover that this ridiculous function will lead to a fish process spinning at 100% CPU after the window goes away:
> 
> `function fish_title; read foo; end`
> 
> (in master. On 3.0.0 it causes a segfault.)

@floam I'm not on my PC to test it, but this might work around that problem:

```diff
diff --git a/src/reader.cpp b/src/reader.cpp
index 34b0df04..a563d0bf 100644
--- a/src/reader.cpp
+++ b/src/reader.cpp
@@ -829,6 +829,7 @@ void reader_write_title(const wcstring &cmd, bool reset_cursor_position) {
             fish_title_command.append(
                 escape_string(cmd, ESCAPE_ALL | ESCAPE_NO_QUOTED | ESCAPE_NO_TILDE));
         }
+        fish_title_command.append(L"<&-");
     }
 
     wcstring_list_t lst;
```

**Comment by ginfuru** [comment] 2019-02-11 18:20
@floam Fish behaves fine with 
> `sh -c 'env HOME=$(mktemp -d) fish'`
But it also behaves most of the time with Spacefish

```shell
fish_right_prompt is a function with definition
# Defined in /Users/ed/.config/fish/functions/fish_right_prompt.fish @ line 1
function fish_right_prompt

    # Configuration
    # ------------------------------------------------------------------------------

    __sf_util_set_default SPACEFISH_RPROMPT_ORDER ""

    # ------------------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------------------

    [ -n "$SPACEFISH_RPROMPT_ORDER" ]
    or return

    for i in $SPACEFISH_RPROMPT_ORDER
        eval __sf_section_$i
    end
    set_color normal
end
```

**Comment by faho** [comment] 2019-02-13 11:11
@ginfuru: You definitely want to upgrade to the recently released 3.0.1, which has fixes for some similar issues.

**Comment by ginfuru** [comment] 2019-02-13 12:33
@faho I'll upgrade and see how that goes.

**Comment by faho** [comment] 2019-02-18 14:05
@mqudsi: I've reverted b247c8d since it stopped the title from working.

**Comment by faho** [comment] 2019-02-23 12:25
So, @ginfuru: Have you been able to reproduce this with 3.0.1?

**Comment by ginfuru** [comment] 2019-02-23 13:39
@faho I haven't had any issues with the update.

**Comment by faho** [comment] 2019-02-23 14:08
Then let's assume it's fixed in that.

**Closed by faho** 2019-02-23 14:08 UTC
Labels: needs more info
