### ISSUE TITLE
Deferred processes sometimes get the wrong pgroup

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5765] opened 2019-03-25 15:14 UTC
This is a regression between 77e71cfcb and eeec6cc2f:

```fish
ls | fzf
```

with `ls` being a function sometimes has the `fzf´ SIGTTOU'd. It happens in about 10% of attempts.

I'm assuming that it's down to the deferred process stuff (pretty cool btw), so I'm assigning @ridiculousfish.

**Comment by faho** [comment] 2019-03-27 13:37
`builtin history search --contains | less` actually _hangs_ unkillable.

**Comment by mqudsi** [comment] 2019-03-29 02:13
I can't reproduce this under WSL, but can under FreeBSD, fwiw.

**Comment by 0ion9** [comment] 2019-03-30 01:19
Seems to be dependent on ?system load?. `ls|fzf` immediately stops much less often than (silly toy example) `begin; echo (ls /tmp); echo (df); end | fzf -m`

I have a function that builds a list for fzf, invoking a few subshells (`fd`,`sort`,`string split`) and a fair bit of printf. That immediately stops about 90% of the time.

**Comment by mqudsi** [comment] 2019-03-30 02:16
It depends on whether or not the process leader for the pgroup the deferred process is intended to join is still around.

**Comment by ridiculousfish** [comment] 2019-04-03 05:20
Simplest case is `ls | less`, since `ls` is a function.

Before deferred processes, the jobs spawned by the `ls` function would get their own pgroup. After this, they get put in `less`'s pgroup because less is the first process in the job to run.

My first thought is we need something less clumsy than "the first thing to physically run in a job decides the job's pgroup." We should be more deliberate about it.

**Comment by ridiculousfish** [comment] 2019-04-06 22:12
Ok I finally wrapped my head around this. This is exposing a race that existed before but that deferred processes made a lot worse.

Recall that a terminal has a foreground process group (pgrp), which can be set via `tcsetpgrp()`. Only the foreground pgrp is expected to output terminal; if a background pgrp attempts it, it may be stopped via a signal (though the conditions here are unclear and contribute to making the race hard to repro).

If you imagine something like this:

    external_command | fish_function
    
after each job executes inside fish_function, fish will attempt to claim control of the terminal via tcsetpgrp(). If `external_command` wants to output to the terminal (e.g. print to stderr) it will then get stopped. This is not easy to run into accidentally because the external_command has a pipe for stdout, so it probably won't output to the terminal, though it might via stderr, and now that I understand it I can repro it easily.

What happens with a deferred process is that commands like this:

    fish_function | external_command
    
now cause `external_command` to start running before `fish_function` completes. And because `external_command` does not have a pipe, it probably will output to the terminal.

The only possible fix here is for fish to be less greedy about reclaiming the terminal after jobs complete, because the only way to avoid this potential race is to leave the terminal with the pgrp leader. This is not trivial but is a good thing to fix, since we need to rationalize our foreground pgrp management anyways. In particular `terminal_acquire_before_builtin()` probably needs to go.

**Comment by ridiculousfish** [comment] 2019-04-06 22:23
Here is simple way to repro the issue without deferred processes:

    `less somefile 2>| begin ; sleep 1 ; end`

after a second `less` will be backgrounded.

**Comment by ridiculousfish** [comment] 2019-04-07 22:03
I think nearly all of this is fixed by the stack ending in f5bb8639d61bebb34f6937cffe0b4bf3e399f867, which was much simpler than I thought it would be.

The remaining unfixed part is e.g. a function that invokes interactive `read` and also pipes to `less`. It's not clear how that should work. But certainly the regression is addressed and then some. Nice find on this.

**Closed** 2019-04-07 22:03 UTC
Labels: regression
