### ISSUE TITLE
Warn if `set` declares a huge variable.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1278] opened 2014-02-01 18:26 UTC
My proposal is that if `set` would declare variable over 5MB (example size, may vary) in size, the fish shell would make a warning. It could be ignored by redirecting STDERR (or by specifying a flag for `set`, but provide a way to ignore this warning in case the user really means this). This is just an example, and I'm sure it could be cleaner.

Example:

```
$ set variable (over5mb)
fish: Variable $variable is assigned with a huge value. This is most likely is a bug.
set variable (over5mb)
^
$
```

**Comment by krader1961** [comment] 2017-03-15 02:48
Closing as a duplicate of issue #3822 since I believe this should apply to all command substitutions, not just those in a `set` command.

**Closed by krader1961** 2017-03-15 02:48 UTC
Labels: duplicate
