### ISSUE TITLE
Add `history replace` subcommand

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#9049] opened 2022-07-01 12:33 UTC
Often I will have several commands in my history that were correct when they were originally run, but over time e.g. a directory name might been updated (`~/documents/` -> `~/docs/`) and now all commands that I'd previously run are now incorrect and need to be recalled, fixed, and then executed; all the while, the previously incorrect command is still in my history, so essentially a bunch of duplicates.

I've so far been editing `~/.local/share/fish/fish_history` manually to address this, but it occurred to me today that it would be nice to have a `history replace` subcommand (with the same parameters as `string replace`) to be able to do this automatically.

Would this be useful to anyone else?

**Comment by faho** [comment] 2022-07-01 12:53
Duplicate of #4506

**Closed by faho** 2022-07-01 12:53 UTC

**Comment by faho** [comment] 2022-07-01 12:57
To be clear: That one asks for a way to *insert* history, while you are asking for replacement.

I believe that, once the former is implemented, you can add the replacement bit yourself - given that deletion and search already exists.
