### ISSUE TITLE
Abbreviations for subcommands

### ISSUE THREAD

**Issue by bessey** [fish-shell/fish-shell#6283] opened 2019-11-04 00:13 UTC
fish version: 3.0.0
OS: MacOS X 19.0.0

This is a feature proposal for abbreviation support for, for lack of a better term, subcommands. Similar but not the same as #5003. By subcommands I mean `status` in `git status` and `get` in `kubectl get`

I find abbreviations super useful for amongst other things pair programming, saving on typing while keeping what is actually going on clear to the passenger, but I wish the following were possible:

I configure the following abbreviations:
```fish
abbr --add g git
abbr --add --scope=git co checkout
abbr --add --scope="git checkout" m master
```

I write `g co m `
I get `git checkout master`, with each word expanding at the space

If scoping simply meant "the scoped word must be to the left of the currently being written word for abbreviations to be considered" then this would allow for DRYing up shared arguments e.g.

```fish
abbr --add g git
abbr --add --scope=git co checkout
abbr --add --scope=git r rebase
abbr --add --scope=git m master  # note I didn't scope this to  "git checkout" like above

# so now
g r m # becomes
git rebase master

g co m # becomes
git checkout master
```

Thoughts?

**Comment by krobelus** [comment] 2019-11-04 08:09
Makes sense. Future global abbreviations could have a condition flag (like `complete --condition/-n`) to support this.

What you can do right now is override some bindings:
```fish
bind ' ' my-expand
bind \r 'my-expand execute'
bind \n 'my-expand execute'
```
where `my-expand` can be defined in `~/.config/fish/functions/my-expand.fish` like below

 ```fish
function my-expand
    set -l first_token (commandline -opc)[1]
    set -l current_token (commandline -ct)
    set -l exp
    switch $first_token
    case git
        switch $current_token
        case co; set exp checkout
        case r;  set exp rebase
        case m;  set exp master
        end
    case kubectl
        # ...
    end
    if string length -q $exp
        commandline --replace --current-token $exp
    end
        
    if string match -q execute $argv
        commandline -f execute
    else
        commandline --insert ' '
        commandline -f expand-abbr
    end
end
```

**Comment by equwal** [comment] 2019-11-10 02:48
If you are going to add these things, you may as well also add expansion at any location not the beginning of the line (issue https://github.com/fish-shell/fish-shell/issues/6309 now).

**Comment by markstos** [comment] 2019-11-11 15:24
I also use "git ci" as an abbreviation for "git commit" and am interested in having tab completion with command and sub-command abbreviations.

**Comment by faho** [comment] 2019-11-11 15:48
Duplicate of #5003

**Closed by faho** 2019-11-11 15:48 UTC
Labels: RFC, enhancement

**Comment by bessey** [comment] 2019-11-11 17:41
I disagree that this is a duplicate of #5003 as I explained in the OP. You might wish for a sub-command to expand to different abbreviations depending on the root command.

**Comment by equwal** [comment] 2019-11-11 22:15
> I disagree that this is a duplicate of #5003 as I explained in the OP. You might wish for a sub-command to expand to different abbreviations depending on the root command.

You might want that, though it seems far too complicated for an abbrev system. Use a function instead?
