### ISSUE TITLE
full compatibility with bash

### ISSUE THREAD

**Issue by ShalokShalom** [fish-shell/fish-shell#4152] opened 2017-06-21 09:14 UTC
I guess, this is already been discussed since the existence of this project, i like to suggest it anyway:

I use fish now for a week and what bothers me most - by far - is that i cant launch a couple of commands/scripts from the Internet, since they all assume its working on bash. 

As an example: find . -name plan.sh* -exec sed -i '/^arch=/d' {} + 
And so on.

Can you improve the compatibility until fish is a real drop in replacement?

**Comment by zanchey** [comment] 2017-06-21 10:10
This is a duplicate of #522, and I'm going to close this in favour of that issue, which has had extensive discussion.

**Closed by zanchey** 2017-06-21 10:10 UTC
Labels: duplicate
