### ISSUE TITLE
__fish_man_page function does not work with Neovim's built-in manpage viewer

### ISSUE THREAD

**Issue by khaveesh** [fish-shell/fish-shell#7973] opened 2021-05-03 20:11 UTC
Fish version: 3.2.2
OS: macOS 11.3

Steps to reproduce the issue:
```
set -Ux MANPAGER 'nvim +Man!'
```

And then use ALT-H on any command like 'fish'. It does not render and instead sends some junk escape codes to neovim which trip it up.

# Solution:
If __fish_man_page does not work with anything other than `less`, then I feel it should be hardcoded into fish instead of using the value of MANPAGER variable.

**Comment by faho** [comment] 2021-05-03 20:18
FIxed by #7863.

**Closed by faho** 2021-05-03 20:18 UTC

**Comment by faho** [comment] 2021-05-03 20:20
>If __fish_man_page does not work with anything other than less

Of course it doesn't. It's just that, like some broken less versions (that have since been fixed), nvim apparently doesn't like it when stderr is redirected but stdout isn't.

So, #7863 fixes this by not doing that. I can reproduce by running 3.2.2, and can confirm that it's fixed by sourcing the new __fish_man_page function.
