### ISSUE TITLE
Fish 2.6b1 crashes at auto completion

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#4030] opened 2017-05-14 20:14 UTC
Fish version: Fish 2.6b1
OS: Haiku x64 (hrev51152)
Third-party customizations : No.

Tab completion cause reproducible program crash.
"make test" cause Kernel Debugger Land. (Not good, really not good!)

See log below:
[fish_26b1_haiku_log.txt](https://github.com/fish-shell/fish-shell/files/999691/fish_26b1_haiku_log.txt)

**Comment by krader1961** [comment] 2017-05-14 21:44
This is almost certainly due to the lint cleanup in `wreaddir()` in *src/wutil.cpp* to replace the call to `readdir()` with the thread-safe `readdir_r()`. Mind instrumenting that function to see what is going wrong? FWIW, since no one else is reporting a problem with that straightforward change it suggests a problem with the Haiku `readdir_r()` implementation. But that's just a guess at this point and I'm happy to be proven wrong.

**Comment by miqlas** [comment] 2017-05-15 04:11
Thanks for the fast answer, krader1961!
I'm more Than happy to help track this Bug, but i need more Info what and where should i change.
Thanks!

**Comment by krader1961** [comment] 2017-05-15 04:22
@miqlas, It is mostly a matter of adding some debug printf() calls to narrow down where and why it is failing. You could use your native debugger to single-step through the code and examine the state after a crash but unless you regularly do that type of thing it is much simpler to use the debug printf approach. The simplest starting point is to add lines like the following to key places within `wreaddir()` and the places it is called:

```
fwprintf(stderr, L"WTF reached %s:%d\n", __FILE__, __LINE__);
```

Then `make fish` followed by `./fish`. Then perform an action which causes a failure and note the sequence of debug printf outputs. That will give us a good idea which statement is actually causing the failure. At that point more detailed debug printf output can be added to report the state of fish variables.

**Comment by krader1961** [comment] 2017-05-15 04:41
Also, @miqlas, if there is a VMware or VirtualBox image we can use to reproduce this, and similar, failures it would make it much easier for the fish developers to do the necessary debugging. Otherwise it is unlikely we will be motivated to go to the trouble of installing and configuring Haiku then installing fish.

**Comment by miqlas** [comment] 2017-05-15 05:35
I can provide a minimal Haiku x64 VMware image with compiler toolchain with all the prerequiments installed. Have a Server to host it.
Lemme do it tonight.

**Comment by miqlas** [comment] 2017-05-17 06:52
@krader1961 : here you go: http://extrowerk.com/temp/haiku_x86_64_vmware.zip
It is made with VmWare for mac, but i hope you can get it work. Everything preconfigured, the dependencies installed and i did you a testbuild too.
Let me know if you need anything else.

**Comment by krader1961** [comment] 2017-05-17 23:33
Thanks, @miqlas. I was able to get that VMware image up and running. It took a few minutes of fiddling to get it setup properly on my network with inbound SSH working and Vim installed. I haven't tried building and debugging fish yet but the readme you left on the desktop seems clear enough. Hopefully I'll have some insights soon.

Is it normal to do everything as root? That's the only account setup and I don't see an easy way to add another account short of using the `useradd` CLI. Or is that just because you find that convenient when doing Haiku development?

**Comment by zanchey** [comment] 2017-05-18 00:09
Haiku is [more or less single-user](https://discuss.haiku-os.org/t/su-useradd-userdel-groupmod/5610/9).

**Comment by krader1961** [comment] 2017-05-18 03:07
I've found the problem. The crash is because `readdir_r()` is stomping the stack. Why? Because the definition of `struct dirent` on Haiku looks like this:

```
typedef struct dirent {
        dev_t                   d_dev;          /* device */
        dev_t                   d_pdev;         /* parent device (only for queries) */
        ino_t                   d_ino;          /* inode number */
        ino_t                   d_pino;         /* parent inode (only for queries) */
        unsigned short  d_reclen;       /* length of this record, not the name */
        char                    d_name[1];      /* name of the entry (null byte terminated) */
} dirent_t;
```

Notice that `d_name` is a single char in length. On all the other platforms that I have access to it is either hardcoded to 256 or uses `NAME_MAX`. I need to research whether the user of that struct has to allocate the struct in a manner to ensure enough space for the `d_name` member.

**Comment by krader1961** [comment] 2017-05-18 04:43
The APUE book by W. Richard Stevens and Stephen Rago says, on page 131, that the `d_name` member must be long enough to hold at least `NAME_MAX` characters plus a terminating null. So the `struct dirent` definition on Haiku is wrong. I'll add a change to work around the problem but it's something that needs to be fixed in the Haiku C/C++ headers.

P.S., Googling turns up some questions about this which suggests other platforms have used a similarly broken definition for `struct dirent`. So it's probably a good idea in any event for us to handle this situation.

P.P.S., I want to thank you, @miqlas, for being willing to help us help you. Providing good problem descriptions and things like Haiku VM images goes a long way to motivating us to help ensure fish works well on Haiku.

**Closed** 2017-05-18 05:37 UTC
Labels: bug

**Comment by miqlas** [comment] 2017-05-18 06:00
Thank you very much!
Next time i'll preistall Vim too (just updated our port yesterday). 
Keep up this good work, mate!

-- Z.

2017.05.18. dátummal, 7:37 időpontban Kurtis Rader <notifications@github.com> írta:
