### ISSUE TITLE
`funcsave` doesn't save `--wraps`

### ISSUE THREAD

**Issue by nikersify** [fish-shell/fish-shell#6050] opened 2019-08-20 07:07 UTC
`fish 3.0.2`

```fish
$ function foo --wraps git; git $argv; end
$ foo <tab> # completes as expected
$ funcsave foo
```
```fish
# in a new fish instance
$ foo <tab> # no completions
```
```fish
# ~/.config/fish/functions/foo.fish
function foo
	git $argv;
end
```

This also breaks completions for the convenient `alias -s` option:
```fish
$ alias -s fun git
$ fun <tab> # completes as expected
```
```fish
# in a new fish instance
$ fun <tab> # no completions
```
```fish
# ~/.config/fish/functions/fun.fish
# Defined in - @ line 1
function fun --description 'alias fun git' # expected --wraps to show up here
	git  $argv;
end
```

Perhaps related to #1625?

**Comment by floam** [comment] 2019-08-24 02:51
This isn't an issue with `funcsave`, it's that fish actually doesn't keep a note around that `--wraps` was used and `functions fun` for example will also not show the `--wraps`. This is actually a duplicate of #1625 and `funcsave` will work for you the way you hope when that is fixed.

**Comment by floam** [comment] 2019-08-24 02:52
Duplicate of #1625

**Closed by floam** 2019-08-24 02:52 UTC
Labels: bug
