### ISSUE TITLE
fish_vi_mode $ command issues with autosuggestions

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#3299] opened 2016-08-13 23:01 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_:
git f3e93f06669dc36c68dd86573b4ca7caf59db63a

**OS/terminal used**: 
freebsd via putty, $TERM=xterm
## Reproduction steps
1. Launch fish
2. Type something matching the history so that an autocomplete suggestion comes up
3. Press Esc to leave insert mode
4. Press $ to jump to end of line
## Expected results

Fish should jump to end of line
## Actual results

The first time `$` is pressed, the cursor is moved by one character. Pressing `$` again jumps to the end of line.

**Comment by krader1961** [comment] 2016-08-14 02:13
Note that [right-arrow] behaves the same way in vi "normal" (i.e., default mode). This is perplexing. Both the emacs and vi bindings have `bind \e\[C forward-char`. Which means that in "normal" mode they should behave identically yet they don't.

**Comment by mqudsi** [comment] 2016-08-14 16:53
I guess we can add the `regression` tag as this was working correctly under 2.3b2-120 g3626c39

**Comment by faho** [comment] 2016-09-03 17:39
What I'm seeing is ("|" denotes cursor position, "xxxx" is the suggestion):

```fish
1> something |xxxxxxx # press escape to go to normal mode
2> something| xxxxxxx # notice cursor jumps a position back, press "$"
3> something |xxxxxxx # press '$' again
4> something xxxxxxx|
```

In emacs-mode, this would also be how it works - if the cursor isn't directly before the suggestion (i.e. the character after has never been typed before), then the suggestion won't be accepted.

This is interesting in something like `echo                               foo` - if you type `echo        ` yourself, move the cursor back and then press something that should accept a suggestion, it won't until you are after all those spaces.

Did pressing escape (i.e. executing "cancel") in vi-mode always move the cursor back? Should it?

**Comment by faho** [comment] 2016-09-03 17:55
Apparently fcc363333cfa32a3391596b1808cbbb08f74bc6c added this to "Make this consistent with vi.".

The PR (#1391) says "Really, the cursor shouldn't be able to go past the end of the line in command mode but I don't know if there is any simple way to fix this."

I see a couple of options here:

- Revert that commit, live with the inconsistency (personally I never got why moving to normal mode should move the cursor at all)

- Add "accept-autosuggestion" to the "$" binding (and possibly others), live with _that_ inconsistency

- Ignore "already typed whitespace" when determining if a suggestion should be accepted

- Don't do anything

**Comment by zanchey** [comment] 2016-10-02 01:51
@faho, do you think there's an easy way out here? I don't use vi-mode enough to really comment. Perhaps @msteed @furunkel @maxfl would like to chip in?

**Comment by maxfl** [comment] 2016-10-02 05:54
In my opinion is a broader topic than just the issue with '$'. I see here two items:

1. To my experience autosuggestion in vim normal mode is an unexpected behavior. You usually enter the normal mode explicitly and intentionally to quickly edit existing command line and usually you get surprised when it's changed when you move the cursor. It rarely happens that you enter the vim mode with autosuggestion highlighted though. 

The same issue happens not only to the normal-$ command but to the normal-right as well. 

2. I always wondered why at all autosuggestion is triggered by the forward-char and other commands. Instead of doing one thing the forward-char is actually doing two things: accept-autosuggestion and forward-char. This was introduced in the times when bind was only able to accept the single function as its argument.

Now as bind may evaluate several commands may be it worth making forward-char command to do only forward-char and update the other commands as well. By updating the bindings by explicitly adding accept-autosuggestion to each relevant bind call.

This will enable users to override the default autosuggestion behavior for the emacs mode by modifying their bindings if they need. As for vim the problem is then automatically solved by not doing implicit autosuggestion acceptance.

**Comment by maxfl** [comment] 2016-10-02 06:51
A simpler option would be to suppress-autosuggestion before entering the normal mode.

**Comment by dead10ck** [comment] 2016-11-15 18:47
After the 2.4 release, there doesn't seem to be a way to accept an auto suggestion in vi mode without taking your hand of the keys to hit the right arrow. The documentation says that Ctrl-X work, but it does not. The documentation says adding

```fish
function hybrid_bindings --description "Vi-style bindings that inherit emacs-style bindings in all modes"
    for mode in default insert visual
        fish_default_key_bindings -M $mode
    end
    fish_vi_key_bindings --no-erase
end
set -g fish_key_bindings hybrid_bindings
```

will fix it, but it does not. @faho I would suggest reverting whatever change did this until something sensible is figured out.

**Comment by krader1961** [comment] 2016-11-15 22:17
@dead10ck: Your problem is being tracked in #3068. The suggested hybrid_bindings approach can't work at the moment due to the `fish_vi_key_bindings` doing `set fish_key_bindings fish_vi_key_bindings`. Let's continue the hybrid binding discussion there since this issue is talking about a different problem.

**Comment by dead10ck** [comment] 2016-11-15 22:23
@krader1961 that issue is closed. Is anything being planned to fix it?

**Comment by egorf** [comment] 2017-03-20 23:26
@faho 

Hi!

I am sorry to bother, but if I wanted to take the road you mentioned by adding `accept-autosuggestion` to the `$` command in normal mode, how would I do that?

I have tried both these and they don't seem to change the behavior:

`bind -M default \$ end-of-line accept-autosuggestion`
`bind -M default \$ accept-autosuggestion`

**Comment by faho** [comment] 2017-03-20 23:51
@egorf: 

>bind -M default \$ end-of-line accept-autosuggestion

This one actually works for me. (Note: If we changed `accept-autosuggestion` to not move the cursor, which we probably should, you'd want to have this the other way around - accept the suggestion and then move the cursor to the end).

Which fish version are you using?

**Comment by egorf** [comment] 2017-03-21 08:50
@faho 

I am using **v2.5.0**, installed via brew. 

Here's the part of my config which handles the bindings:

```
fish_vi_key_bindings
bind \cl clear
bind -M default \$ end-of-line accept-autosuggestion
set -g fish_escape_delay_ms 10
```

I've just tried in a clean environment and it seems to work. What could be the difference?

**Comment by faho** [comment] 2017-03-21 10:09
>After some poking around, I have found that this only works if you run it manually in a new shell and doesn't, if it just resides in the config.fish file. Weird.

Ah yes. Bare `bind` statements in config.fish don't work because we define the bindings only after config.fish (because that is where you'd choose vi-mode). You need to define a function called "fish_user_key_bindings" and put the bind statements there.

So it would look like

```fish
function fish_user_key_bindings
     bind \cl clear
     bind -M default \$ end-of-line accept-autosuggestion
end
fish_vi_key_bindings
set -g fish_escape_delay_ms 10
```

**Comment by egorf** [comment] 2017-03-21 10:54
It works. Thanks for such detailed help!

**Closed** 2024-03-23 13:36 UTC
Labels: bug, vi-mode
