### ISSUE TITLE
fish_vi_key_bindings with tmux results in bind: Key with name “sleft” does not have any mapping

### ISSUE THREAD

**Issue by hazelnusse** [fish-shell/fish-shell#5853] opened 2019-04-30 05:55 UTC
I get the following in every tmux window I spawn:
bind: Key with name “sright” does not have any mapping
bind: Key with name “sleft” does not have any mapping
bind: Key with name “sright” does not have any mapping
bind: Key with name “sleft” does not have any mapping
bind: Key with name “sright” does not have any mapping
bind: Key with name “sleft” does not have any mapping

See:
https://asciinema.org/a/7PAQLCj1ja3VbpwUdFZoSV0SN

I] lukepeterson@T480s-LPeterson ~/r/asciinema> fish --version
fish, version 3.0.2-1003-ge8fd83c
[I] lukepeterson@T480s-LPeterson ~/r/asciinema> echo $version
3.0.2-1003-ge8fd83c
[I] lukepeterson@T480s-LPeterson ~/r/asciinema> 

I'm not sure if this is a regression from 2.7.1, I will try it and see.

If I remove the `fish_vi_key_bindings` from config.fish, the warnings go away.

**Comment by faho** [comment] 2019-04-30 08:18
Duplicate of #5028, sorry for the inconvenience!

**Comment by faho** [comment] 2019-04-30 08:20
Wait, no, that was included in 3.0.

**Comment by faho** [comment] 2019-04-30 08:21
Okay, @hazelnusse: Please check that you don't have an old version of the function left-over - `functions --details fish_vi_key_bindings` shows which one it is reading. If it's not from fish itself, remove it.

**Comment by faho** [comment] 2019-04-30 09:41
Ah, no:

0abcf9265efe5eb43e9992133638356f0f9c5c09 added the sleft/sright bindings to *the shared set*, and the vi-bindings, unlike the default ones, don't pass "-s" to `__fish_shared_key_bindings`.

**Closed** 2019-04-30 09:41 UTC
Labels: needs more info

**Comment by faho** [comment] 2019-04-30 09:49
Oh, one more thing: @hazelnusse, tmux knows these keys, screen doesn't. Set your $TERM to `tmux-256color` and they should start working.

**Comment by hazelnusse** [comment] 2019-04-30 14:21
Awesome @faho this indeed fixes the issue. Thank you!
