### ISSUE TITLE
Latest build on OS X yosemite causes disk errors

### ISSUE THREAD

**Issue by andrewsawczyn** [fish-shell/fish-shell#1859] opened 2014-12-20 12:51 UTC
I originally thought this was an issue with HomeBrew but am able to duplicate the issue while building directly from git and by downloading directly from fishshell.com

After building and installing fish 2.1.1 I receive the following error in the yosemite disk utility... incorrect number of file hard links".  It requires a reboot into single user mode to repair and will return if fish is used.  Another user has confirmed the issue.  If I build and install from macports this does not occur, but I've noticed that they are at version 2.1.0 and not the latest 2.1.1.

Thoughts?  If I download the pre-build app from fishshell.com the same thing happens.  I am happy to further research and debug the problem if anyone has tips on how to tackle this.  I am a developer but it's been awhile since I've worked in the c world.

fyi, clean install of yosemite with the latest xcode.  I have isolated this down to fish.

**Comment by TimSoethout** [comment] 2015-01-17 14:50
I am experiencing the same issue. 

```
diskutil verifyvolume <volume-guid>
Started file system verification on disk1 Macintosh HD
Verifying storage system
Checking volume
disk0s2: Scan for Volume Headers
disk0s2: Scan for Disk Labels
Logical Volume Group <guid> on 1 device
disk0s2: Scan for Metadata Volume
Logical Volume Group has a 17 MB Metadata Volume with double redundancy
Start scanning metadata for a valid checkpoint
Load and verify Segment Headers
Load and verify Checkpoint Payload
Load and verify Transaction Segment
Incorporate 0 newer non-checkpoint transactions
Load and verify Virtual Address Table
Load and verify Segment Usage Table
Load and verify Metadata Superblock
Load and verify Logical Volumes B-Trees
Logical Volume Group contains 1 Logical Volume
Load and verify <guid>
Load and verify <guid>
Load and verify Freespace Summary
Load and verify Block Accounting
Load and verify Live Virtual Addresses
Newest transaction commit checkpoint is valid
Load and verify Segment Cleaning
The volume <guid> appears to be OK
Storage system check exit code is 0
Verifying file system
Using live mode
Performing live verification
Checking Journaled HFS Plus volume
Checking extents overflow file
Checking catalog file
Incorrect number of file hard links
Checking catalog hierarchy
Checking extended attributes file
Checking volume information
File system check exit code is 8
Error: -69845: File system verify or repair failed
Underlying error: 8: POSIX reports: Exec format error
```

But it keeps coming back even when removing fish. It's driving me crazy.
This happens on a FileVault enabled disk and running Yosemite.

**Comment by ridiculousfish** [comment] 2015-01-17 21:30
My new Mac is up and running. I'll take a crack at this today.

**Comment by vaxo** [comment] 2015-02-01 15:05
I have this problem too. When will the next minor version? 
I can't live without FISH :-)

**Comment by Stapelzeiger** [comment] 2015-02-01 15:20
@vaxo downgrading solved the problem for me. You could do the same while waiting for a fix. (I'm running version 2.0.0, I haven't tried any others except 2.1.1)

**Comment by ridiculousfish** [comment] 2015-02-02 01:57
Still reproduces on 10.10.2

**Comment by ridiculousfish** [comment] 2015-02-02 02:01
@zanchey What would you think about using a symlink instead of a hard link for the socket file in /tmp? Any downside?

**Comment by zanchey** [comment] 2015-02-02 02:39
It would need testing on Ubuntu, as the Yama security module does its best to block it - I did try that initially and I'm pretty sure it doesn't work.

I'm really quite impressed that it's possible to corrupt the filesystem from userland, although most Linuxes long went down the path of using a RAM-backed FS for `/tmp`.

**Comment by zanchey** [comment] 2015-02-02 04:15
I wonder if `nc -Ul /tmp/foo &; ln /tmp/foo /tmp/bar` causes the same problems.

**Comment by ridiculousfish** [comment] 2015-02-02 18:47
Good idea zanchey. I'd love to find some simple repro steps for filling a bug against OS X. It looks like that particular command doesn't trigger it, but a similar one might.

**Comment by ridiculousfish** [comment] 2015-02-02 19:20
I take it back, that totally works! But you have to restart afterwards

So the steps are `nc -Ul /tmp/foo &; ln /tmp/foo /tmp/bar` then restart. I speculate that whatever clears the contents of /tmp does it in a way that messes up hard link counts. I'll file a bug.

One nasty workaround would be to use symlinks only on OS X, and hard links on Linux.

**Comment by ridiculousfish** [comment] 2015-02-02 19:33
This doesn't seem to reproduce with ordinary files, e.g. `touch /tmp/foo ; ln /tmp/foo /tmp/bar`

**Comment by ridiculousfish** [comment] 2015-02-02 19:42
Filed at bugreporter.apple.com and http://openradar.appspot.com/radar?id=6387155723091968

**Comment by zanchey** [comment] 2015-02-03 02:06
I'd be happy to roll a 2.1.2 just for OS X and nuke the link entirely on the proviso that "reboot your machine" goes in the release notes. If there's no old versions installed then the link never gets touched.

**Comment by zanchey** [comment] 2015-02-04 08:33
(OTOH is solved in master :-)

**Comment by ridiculousfish** [comment] 2015-02-04 20:28
I hate the idea of leaving a minor version with a serious bug like this - it means that when we regress issues we'll corrupt our filesystem. Maybe the thing to do is to commit a simple fix to 2.1.2 (perhaps as simple as disabling the link on OS X) but not release it, instead releasing a 2.2.0 from master.

**Comment by nmalzieu** [comment] 2015-02-06 22:07
@ridiculousfish @zanchey  I get the same problem. I'm not sure I understand correctly though:
the bug happens in 2.1.1, but not 2.0.0.
Should I downgrade to 2.0.0 ? Or is it fixed in master and should I build from master ?
Thanks !

**Comment by DomT4** [comment] 2015-02-06 22:22
> (OTOH is solved in master :-)

The problem is solved in the Master branch? Is there a specific set of commits with the fixes? It'd perhaps be worthwhile to get OS X package managers to backport the fix, if a new release with a fix isn't completely imminent.

**Comment by ridiculousfish** [comment] 2015-02-06 22:40
This is fixed in master by virtue of removing fishd entirely. This was an involved process with a lot of changes.

Probably the simplest thing to do would be to use a symlink on OS X, assuming it works.

**Comment by ridiculousfish** [comment] 2015-02-08 06:23
I confirmed that a symlink on OS X allows existing fish 2.0 instances to continue working, and does not produce the disk errors.

**Comment by DomT4** [comment] 2015-02-08 19:30
Are there plans for a new minor release or is the advice for people to use the git build for now?

**Comment by ridiculousfish** [comment] 2015-02-09 20:02
Let's do a release with just this fix. It can be OS X only (the Linux code isn't changing).

**Comment by DomT4** [comment] 2015-02-09 22:28
Alright, sounds good, Cheers! Will keep an eye out for that.

**Comment by ridiculousfish** [comment] 2015-02-10 23:14
New branch Integration_2.1.2 contains the fix

**Comment by zanchey** [comment] 2015-02-11 01:56
As the code is unchanged, is there any utility in doing new builds for Linux?

**Comment by ridiculousfish** [comment] 2015-02-11 01:57
We should test on Linux but I don't think there's value in doing a release on Linux.

**Comment by MerelyAPseudonym** [comment] 2015-02-21 00:39
@DomT4 @ridiculousfish I created a Homebrew PR to use version 2.1.2: https://github.com/Homebrew/homebrew/pull/37009

**Comment by zanchey** [comment] 2015-02-22 14:49
Although I appreciate the enthusiasm, after the mess with 2.1.1 I think it would have been better if updating Homebrew waited for the actual release (i.e. tarball and release announcement). Otherwise we get issues filed like #1953 (prevented by using the tarball).

We ended up moving the tag for 2.1.1 about six times in the end due to showstoppers discovered just before the release.

**Comment by DomT4** [comment] 2015-02-22 17:15
Apologies, from the discussion here I got the impression there wasn't going to be a full release for this as only OS X users needed the minor update, so I didn't say anything in the Homebrew/Homebrew PR on that front. I'll tee up a PR to use the official tarball when one is available.

**Comment by ridiculousfish** [comment] 2015-02-25 05:54
2.1.2 is finally released on the main site fishtail.com

**Comment by ridiculousfish** [comment] 2015-02-25 06:32
Homebrew PR here: https://github.com/Homebrew/homebrew/pull/37177

**Comment by DomT4** [comment] 2015-02-25 19:19
Thanks for the PR! :+1:

**Closed** 2015-02-27 08:47 UTC

**Comment by ekristen** [comment] 2015-04-07 14:38
I'm still seeing this issue on 2.1.2 (installed via Homebrew) with FileVault enabled on 10.10.2

**Comment by andrewsawczyn** [comment] 2015-04-07 15:57
I am not.  Although I'm not using FileVault.

I uninstalled fish, rebooted, installed fish, launched iTerm, played around, rebooted.  Ran disk utility a few times in that process and I am not seeing multi linked files.  I'll try to run disk utility for the next few days and see what happens.

**Comment by alec-c4** [comment] 2015-07-07 20:43
hi, guys. is this issue completely fixed on Yosemite or not?

**Comment by ridiculousfish** [comment] 2015-07-07 20:46
Yes, fish 2.1.2 will no longer cause filesystem corruption, though it cannot repair corruption that has already occurred (which AFAIK is harmless)

**Comment by DomT4** [comment] 2015-07-07 21:08
We haven't had any more issues around this reported to Homebrew.

**Comment by FrankZhang002** [comment] 2015-08-30 07:37
I using OS X 10.10.5, I have the same issue, but disk utility looks like can fix it?

**Comment by faho** [comment] 2015-08-30 16:47
@FrankZhang002: Caused by a fish version of at least 2.1.2?
