### ISSUE TITLE
fish cost 4.x GB memory on my computer!!

### ISSUE THREAD

**Issue by xialeizhou** [fish-shell/fish-shell#3357] opened 2016-09-07 02:21 UTC
**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
OS:  OS X EI Capitan 10.11.3
Terminal: iterm2, 3.0.4

## Reproduction steps
1. step1 
input `cp file.java ./src/main/java/com/xx`, but do not input `Enter`
2. step2
use `tab` key to jump between target matched files in directory `./src/main/java/com/xx/`
3. step3
input `/fil` key to search 

## Results
![fish](https://cloud.githubusercontent.com/assets/6303773/18297642/b1b23eb2-74e4-11e6-81e1-8e2ffed0ede8.png)

**Comment by ridiculousfish** [comment] 2016-09-07 02:25
Thanks for filing this! I'm not able to reproduce. What files are in `./src/main/java/com/xx/`?

**Comment by xialeizhou** [comment] 2016-09-07 03:46
sorry, i can not reproduce this issue, too。 but it really used so many memory and slow down my computer. would you need more info? what can i do?

**Comment by ridiculousfish** [comment] 2016-09-07 03:47
Steps to reproduce would be great! If you cannot find them but do have a large fish process, the output of `heap 12345` and `mmap 12345` with 12345 replaced with the pid of the big fish would help.

**Comment by krader1961** [comment] 2016-09-07 05:35
I can't reproduce this either on OS X. I ran the following to create a directory with an unreasonably large number of files, 1/3 of which matched "fil":

```
mkdir ~/tmp/xx
cd ~/tmp/xx
for x in (seq 100000)
    touch file$x
    touch abcd$x
    touch ghij$x
end
```

I then repeated the O.P.'s reproduction steps without difficulty. My shell grew in size from 11 to 300 MB. That took several seconds and was therefore painfully slow but even that absurd situation caused fish to grow to only 1/10th the size you reported, @xialeizhou.

Unfortunately, @xialeizhou, unless we can find a way to reproduce the problem it is very unlikely we will be able to fix whatever went wrong. Note that a common source of unwanted fish memory use is to create a function that reads or writes a lot of data. That is because fish functions buffer all the data they receive or write. So if you have a function that reads or writes a large amount of data that could cause your shell process to grow very large.

The `mmap` command doesn't exist on OS X but the `heap` command recommended by @ridiculousfish does and might provide insight into how the memory is being used if you have a fish process that is unreasonably large.

**Comment by floam** [comment] 2016-09-07 05:53
To add to what @ridiculousfish said, if it happens again `heap %self -showSizes -addresses all` in the window with the bad fish process should work and might give a bit more context as to what that data really is (it will even print out strings).  You can replace `%self` with the PID from Activity Monitor to do it from another terminal window.

I'd go further and suggest you also try: `sudo sysdiagnose %self`. This will run heap, and a bunch of other tools to hopefully provide a good snapshot of what's going on. It will open up Finder when it's done with the created zip file containing the results, which we would appreciate getting a look at.

**Comment by xialeizhou** [comment] 2016-09-08 17:20
many thanks to both of  @krader1961 @floam  I will try to reproduce this issue  in recent days with `vmmap <PID>` and `sudo sysdiagnose <PID>` on my computer.

**Comment by krader1961** [comment] 2016-09-28 05:11
@xialeizhou have you been able to reproduce the problem? Do you have personal or third-party extensions to fish that might affect how completions are handled?

**Comment by krader1961** [comment] 2016-10-02 03:35
@xialeizhou, We'll need to close this soon unless you can provide more information that would help us understand, or reproduce, this problem.

**Comment by krader1961** [comment] 2016-10-06 21:47
@xialeizhou I'm going to close this for lack of information. If you're able to provide more information that might help us determine the cause of the behavior you observed please reopen.

**Closed by krader1961** 2016-10-06 21:47 UTC
Labels: needs-more-info
