### ISSUE TITLE
eval in config.fish breaks ssh proxy command

### ISSUE THREAD

**Issue by hSATAC** [fish-shell/fish-shell#2405] opened 2015-09-18 12:58 UTC
OK this sounds crazy and I don't know why, I'll try do give every details. Perhaps related to #2160 
- OSX: 10.10.5
- fish: 2.2.0 installed via homebrew

I have a very simple SSH ProxyCommand in my `~/.ssh/config`:

```
Host server2
Hostname 10.11.4.165
User ubuntu
ProxyCommand ssh server1 nc  %h %p
```

This worked in bash, and of course fish.

But after I put this line in `my config.fish`, it was broken.

```
eval (docker-machine env default)
```

I can reproduce this with a empty config.fish only contains this line.

When I try `ssh server2` it gave this message:

```
Bad packet length 1349676916.
Disconnecting: Packet corrupt
Killed by signal 1.
```

But if I don't put this line in `config.fish`, instead, I execute this line directly in fish shell and try ssh, it's working.

btw the output of `docker-machine env default` is

```
set -x DOCKER_TLS_VERIFY "1";
set -x DOCKER_HOST "tcp://192.168.99.100:2376";
set -x DOCKER_CERT_PATH "/Users/cat/.docker/machine/machines/default";
set -x DOCKER_MACHINE_NAME "default";
# Run this command to configure your shell:
# eval (docker-machine env default)
```

I can't explain this, now what I did to solve this is manually paste these lines in `config.fish` to fix this. Can anyone confirm this behavior?

```
set -x DOCKER_TLS_VERIFY "1";
set -x DOCKER_HOST "tcp://192.168.99.100:2376";
set -x DOCKER_CERT_PATH "/Users/cat/.docker/machine/machines/default";
set -x DOCKER_MACHINE_NAME "default";
```

Thanks.

**Comment by faho** [comment] 2015-09-18 13:32
Did you try the workaround/solution suggested in #2160 (guard the offending lines in `if status --is-interactive`)?

**Comment by hSATAC** [comment] 2015-09-18 14:08
No I didn't try it. Because I need those docker env variables even when it's not an interactive shell. So this was not a valid solution in my case.

**Comment by zanchey** [comment] 2015-10-15 06:35
Can you try with `ssh -v`?

**Comment by hSATAC** [comment] 2015-10-15 06:43
Yes, I did give the output above. I'll paste the whole message here:
```
$ ssh server2 -vv
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/cat/.ssh/config
debug1: /Users/cat/.ssh/config line 1: Applying options for *
debug1: /Users/cat/.ssh/config line 44: Applying options for server2
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Executing proxy command: exec ssh server1 nc  10.11.3.212 22
debug1: permanently_drop_suid: 503
debug1: identity file /Users/cat/.ssh/id_rsa type 1
debug1: identity file /Users/cat/.ssh/id_rsa-cert type -1
debug1: identity file /Users/cat/.ssh/id_dsa type -1
debug1: identity file /Users/cat/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.9p1 Debian-5ubuntu1.4
debug1: match: OpenSSH_5.9p1 Debian-5ubuntu1.4 pat OpenSSH_5*
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: SSH2_MSG_KEXINIT sent
Bad packet length 1349676916.
Disconnecting: Packet corrupt
Killed by signal 1.
```

**Comment by zanchey** [comment] 2015-10-15 06:54
"Bad packet length 1349676916." turns up suspiciously often when searching the Web - it's "Prot" when converted to ASCII. Can you add `-vv` to the ProxyCommand SSH as well?

**Comment by jeffling** [comment] 2015-12-02 00:01
I also have the same problem! 
Added -vv to proxy command, pretty much the same stuff

```
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/jeff/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp SHA256:B/YeUxw1YcxQqg/q/ZOPz6v0gCIRzu+VN4hjTpbQGO0
debug1: Authentication succeeded (publickey).
Authenticated to ec2-54-172-162-166.compute-1.amazonaws.com ([54.172.162.166]:22).
debug2: fd 6 setting O_NONBLOCK
debug2: fd 7 setting O_NONBLOCK
debug1: channel 0: new [client-session]
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug1: Sending env LANG = en_CA.UTF-8
debug2: channel 0: request env confirm 0
debug1: Sending command: nc -q0 10.0.1.87 22
debug2: channel 0: request exec confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
Bad packet length 1349676916.
ssh_dispatch_run_fatal: Connection to UNKNOWN: message authentication code incorrect
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
debug1: fd 1 clearing O_NONBLOCK
Killed by signal 1.

````

**Comment by hSATAC** [comment] 2015-12-02 00:40
@jeffling Thanks for confirming this. Good to know that I am not alone. :)

**Comment by krader1961** [comment] 2015-12-02 02:03
I can't reproduce the problem if I create a `$HOME/bin/docker-machine` file with the following content and perms 755:

```
#!/bin/sh
cat <<'EOF'
set -x DOCKER_TLS_VERIFY "1";
set -x DOCKER_HOST "tcp://192.168.99.100:2376";
set -x DOCKER_CERT_PATH "/Users/cat/.docker/machine/machines/default";
set -x DOCKER_MACHINE_NAME "default";
# Run this command to configure your shell:
# eval (docker-machine env default)
EOF
```

If you do the same thing (and ensure that script is run rather than the "real" docker-machine program) does the problem still occur? I ask because in my experience most SSH failures of this nature are due to shell dot-files (e.g., ~/.config/fish/config.fish) producing unexpected output that screws up the SSH protocol. Which is why @faho asked if the problem goes away if you protect the eval with a test for an interactive shell. It is highly likely that the eval statement is writing something to stdout.

**Comment by hSATAC** [comment] 2015-12-02 03:21
@krader1961 Yes I agree with you. As I mentioned in the first post, I tested several scenarios, only `eval` + the "real" docker-machine program will cause this problem.

The issue should be between `eval` and the `docker-machine env` output and I am not sure where's the exact spot.

I checked the docker-machine source code but can't find anything suspicious, and it worked well in my bash and zsh environment. That's why I came here first to see if anyone got a clue.

**Comment by krader1961** [comment] 2015-12-02 03:33
@hSATAC The problem is almost certainly that the `docker-machine env` output is not exactly as you documented. A single character, such as a space or a non-printable control-char, can cause this type of failure. There are many layers involved. But let's start by focusing on the output of __docker-machine__. Please run `docker-machine env default | od -tx1z` from an interactive shell on server1 and server2.

**Comment by hSATAC** [comment] 2015-12-02 03:40
@krader1961 

I don't have docker-machine installed on my servers, only on my Macbook. The `od` command in osx doesn't recognize the `z` flag so I use gnu od instead.

Here's the output:

```
$ docker-machine env default | god -tx1z
0000000 73 65 74 20 2d 78 20 44 4f 43 4b 45 52 5f 54 4c  >set -x DOCKER_TL<
0000020 53 5f 56 45 52 49 46 59 20 22 31 22 3b 0a 73 65  >S_VERIFY "1";.se<
0000040 74 20 2d 78 20 44 4f 43 4b 45 52 5f 48 4f 53 54  >t -x DOCKER_HOST<
0000060 20 22 74 63 70 3a 2f 2f 31 39 32 2e 31 36 38 2e  > "tcp://192.168.<
0000100 39 39 2e 31 30 30 3a 32 33 37 36 22 3b 0a 73 65  >99.100:2376";.se<
0000120 74 20 2d 78 20 44 4f 43 4b 45 52 5f 43 45 52 54  >t -x DOCKER_CERT<
0000140 5f 50 41 54 48 20 22 2f 55 73 65 72 73 2f 63 61  >_PATH "/Users/ca<
0000160 74 2f 2e 64 6f 63 6b 65 72 2f 6d 61 63 68 69 6e  >t/.docker/machin<
0000200 65 2f 6d 61 63 68 69 6e 65 73 2f 64 65 66 61 75  >e/machines/defau<
0000220 6c 74 22 3b 0a 73 65 74 20 2d 78 20 44 4f 43 4b  >lt";.set -x DOCK<
0000240 45 52 5f 4d 41 43 48 49 4e 45 5f 4e 41 4d 45 20  >ER_MACHINE_NAME <
0000260 22 64 65 66 61 75 6c 74 22 3b 0a 23 20 52 75 6e  >"default";.# Run<
0000300 20 74 68 69 73 20 63 6f 6d 6d 61 6e 64 20 74 6f  > this command to<
0000320 20 63 6f 6e 66 69 67 75 72 65 20 79 6f 75 72 20  > configure your <
0000340 73 68 65 6c 6c 3a 20 0a 23 20 65 76 61 6c 20 28  >shell: .# eval (<
0000360 64 6f 63 6b 65 72 2d 6d 61 63 68 69 6e 65 20 65  >docker-machine e<
0000400 6e 76 20 64 65 66 61 75 6c 74 29 0a              >nv default).<
0000414
```

**Comment by krader1961** [comment] 2015-12-02 03:57
If you don't have __docker-machine__ installed on your servers how do you expect `ssh server2` to not report a "command not found" or similar error? It seems to me you need to, at a minimum, predicate the execution of `eval (docker-machine env default)` in your __config.fish__ on whether or not __docker-machine__ is executable. For example, using something like

```
if test -x (type -P which)
```

**Comment by hSATAC** [comment] 2015-12-02 04:27
I ssh into server2 from my Macbook, via `ProxyCommand ssh server1 nc  %h %p`. The fish shell, docker-machine are all in my Macbook. server1 & server2 don't not have fishshell, fishconfig and docker-machine.

**Comment by krader1961** [comment] 2017-03-16 06:30
Closing for lack of an ability to reproduce and we know that 99.99% of these types of problems are due to shell config scripts writing to stdout when not interactive.

**Closed by krader1961** 2017-03-16 06:30 UTC
Labels: bug

**Comment by zanchey** [comment] 2017-03-16 07:53
I feel like we've had this question a few times, although I can't see any direct duplicates - it might be worth adding to the FAQ if I'm not making that up.
