### ISSUE TITLE
Output not shown when missing EOL

### ISSUE THREAD

**Issue by apoco** [fish-shell/fish-shell#6831] opened 2020-03-30 01:31 UTC
Fish version: `3.1.0`
Terminal: `rxvt-unicode-256color`

It seems that the last line of stdout is failing to show up in the `rxvt-unicode-256color` terminal. To reproduce, I do a `cat foo.txt` where `foo.txt` is a text file with no EOL. It still occurs without third-party extensions. This doesn't seem to happen in the integrated vscode terminal. 

Strangely, if I open the file with `vim` and save it without making changes, that file prints out ok.

If I do `file foo.txt` beforehand: 
> foo.txt: ASCII text, with no line terminators

Afterward:
> foo.txt: ASCII text

It isn't just `cat` that has this behavior. I first noticed it with some `curl` output as well.

I suspect this has to do with the command prompt. In a bash session, the command prompt shows up on the same line as the output. Is the fish prompt erasing the current line before outputting, causing the last line in the terminal to get overwritten?

**Comment by apoco** [comment] 2020-03-30 01:35
I finally found the right search keywords. Seems like a regression similar to https://github.com/fish-shell/fish-shell/issues/3747

**Comment by zanchey** [comment] 2020-03-30 09:47
Does `echo -n sometext` reproduce the problem?

Do you know if this worked in an older version?

`src/screen.cpp`'s `s_reset` function is probably the culprit here.

**Comment by krobelus** [comment] 2020-03-30 17:21
I can't reproduce with `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23` (gosh that's old).

```fish
$ printf asdf > a
$ cat a
asdf⏎
$
```

**Comment by apoco** [comment] 2020-03-30 19:07
Yes, I did this without customization.

Did you make sure your `a` file has no line terminators?

**Comment by apoco** [comment] 2020-03-30 19:12
I didn't notice if this happened in older versions. I did recently upgrade from an older version (so I could get the nifty `&&` and `||` support).

Sadly, yesterday I used oh my fish to change my prompt, and now I can't get back to the state where this reproduces.

**Comment by krobelus** [comment] 2020-03-30 19:29
Yeah, printf does not print a line terminator. Vim adds one if you save the file.

> Yes, I did this without customization.

> now I can't get back to the state where this reproduces.

That's kind of contradictory, without customizations implies using the default prompt:
If it happens with `HOME=(mktemp -d) fish` then it's easy for us to reproduce.

Looks like it probably was something in your prompt or similar. 
Closing for now, if you see it again, please reopen.

**Closed by krobelus** 2020-03-30 19:29 UTC
Labels: bug
