### ISSUE TITLE
Functions in subdirectories not loaded

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5034] opened 2018-06-07 15:15 UTC
In "~/.config/fish/functions" I would like to organise my functions in subdirectories but they are not loaded. Is it possible to enable this or to add it in future fish rev?

I wanted to dissociate original fish functions modified with funced/funcsave from my own functions

**Comment by faho** [comment] 2018-06-07 15:17
Duplicate of #1819, where we rejected this.

**Closed by faho** 2018-06-07 15:17 UTC

**Comment by BarbzYHOOL** [comment] 2018-06-07 15:34
Functions named "__function" are builtin functions? I mean why do they have "__"?

**Comment by faho** [comment] 2018-06-07 15:56
>Functions named __function are builtin functions? I mean why do they have __?

They have `__` to not show up when you're completing, and to signify that these are internal things that you probably don't need to care about. We've probably overused it a bit, though.

Either way, I just found out #4947 is still open. If you have any new arguments why subdirectories are a good idea, and a plan for how it should work, then comment there.

**Comment by faho** [comment] 2018-06-07 16:39
>Just another question, do I need to name my files the same name as my functions?

Functions are identified by their name. If you wish to override a function, you have to use the same name, yes.

>Also had to add __ to fish_default_key_bindings.fish

No, you do not. There is no function called `__fish_default_key_bindings`. And like I said, you don't want to override that one. You want to add your own bindings in `fish_user_key_bindings`.

**Comment by BarbzYHOOL** [comment] 2018-06-07 17:19
Not override a function, just create a new one, like an alias.

**Comment by faho** [comment] 2018-06-07 17:27
In that case, you should pick a different, unused, name.

**Comment by BarbzYHOOL** [comment] 2018-06-07 17:30
I mean, I'm forced to call that file the name of the function.

Can't group all functions in one bigger file, right? (because I try to change the filename of my alias function and then the command doesn't exist)

**Comment by krader1961** [comment] 2018-06-07 18:19
You can put multiple functions in the same file. However, the file will only be autoloaded when you use the function with the same name (minus the *.fish* extension) as the file. You can, of course, manually load the file by putting `source ~/.config/fish/functions/my_multiple_functions.fish` in your *~/.config/fish/config.fish* file. Of course that means that you pay the cost of loading that file on every instance of fish you start whether or not you use any of the functions defined in that file.

Think about it. Let's say you have the following in *~/.config/fish/functions/foo.fish*:

```
function bar
    echo bar
end

function foo
    echo foo
end
```

When you run `bar` how would fish know to load *~/.config/fish/functions/foo.fish*?

**Comment by BarbzYHOOL** [comment] 2018-06-07 18:31
Ok I understand, that's to make the shell faster. Fair point! I'll avoid putting them in config then
