### ISSUE TITLE
Suggestions not shown when right prompt disappears and/or second line is reached

### ISSUE THREAD

**Issue by janernsting** [fish-shell/fish-shell#2400] opened 2015-09-17 08:45 UTC
With overly long lines, suggestions are no longer shown when the right prompt disappears. However, I can still accept suggestions using `forward-word` and/or `accept-suggestion`. The same holds true for commands that span more than one line; suggestions are shown for the first line only.

In the example below, I use `forward-word` for the second command. Even though the suggestion is not shown, I can still accept it.

![right_prompt_broken_completion](https://cloud.githubusercontent.com/assets/1137575/9928484/e680a7fe-5d26-11e5-9c6b-82d5ead1d5c2.gif)

I was able to reproduce this issue with a vanilla fish (no customisations), too, and tested for the issue using fish 2.2.0 on Ubuntu 14.04.

**Comment by zanchey** [comment] 2015-11-01 10:20
I can confirm that this occurs even without a right prompt set - if you use `forward-word` to accept past the ellipse, no further text is displayed but words from the autosuggestion can still be accepted.

**Comment by ridiculousfish** [comment] 2015-11-01 18:29
Nice gif :)

Is the ask here that you should not be able to accept an autosuggestion if it's not visible? Or is it that it should become visible when the right prompt disappears?

**Comment by janernsting** [comment] 2015-11-02 09:45
I would expect the suggestion to become visible as soon as the right prompt disappears. I would expect the same to hold true for multiline prompts.

**Comment by ridiculousfish** [comment] 2015-11-03 06:28
We don't show the suggestion even if removing the right prompt frees up enough space. This is because it feels really weird to take something away, only to put it back again after consuming *more* space. A hierarchy of stuff that gets removed is less surprising than some sort of knapsack best-fit algorithm.

**Comment by janernsting** [comment] 2015-11-04 08:01
I do not understand what you mean. What do you by *take something away, only to put it back again*?

My expectation would be the following:
* right prompt disappears --> suggestions until the end of the line are shown
* next line is reached --> suggestions until the end of that line are shown

Currently, suggestions are available for completion, but only in a hidden fashion (I can not see them, but use them).

**Comment by pickfire** [comment] 2015-11-04 08:16
@janernsting Hi, the default is to do the following:

1. Character overflowed
2. Right prompt disappeared
3. Character flooded the first line
4. Character continued at the next line

**Comment by janernsting** [comment] 2015-11-04 12:53
The [above GIF](https://cloud.githubusercontent.com/assets/1137575/9928484/e680a7fe-5d26-11e5-9c6b-82d5ead1d5c2.gif) shows what currently happens in `fish`: you can accept suggestions past the ellipse (using `forward-word` and/or `accept-suggestion`) even though they are not visible (i.e. not shown on the command line).

However, when I accept suggestions past the ellipse, I expect to *see* the extended suggestion I am about to accept on the command line.

**Comment by janernsting** [comment] 2015-11-04 13:10
1. This currently happens: ![img_20151104_140339](https://cloud.githubusercontent.com/assets/1137575/10938855/9d207ec0-82fd-11e5-96f3-b75105987e6a.jpg)
2. This what I expect to happen: ![img_20151104_140113](https://cloud.githubusercontent.com/assets/1137575/10938859/a8e7c09c-82fd-11e5-86a4-f5c5282a1906.jpg)

**Comment by pickfire** [comment] 2015-11-04 14:56
Look at the picture and take some time to rest:

![http://s11.postimg.org/t3iosih6r/2015_11_04_225201_1600x900_scrot.png](http://s11.postimg.org/t3iosih6r/2015_11_04_225201_1600x900_scrot.png)

There doesn't seem to have any problem with the **suggestions**. Did you use the latest git version?

**Comment by faho** [comment] 2015-11-04 15:11
@pickfire: That's exactly the behavior that was complained about (look at the gif in the opening post again) - the suggestion is _there_, you can accept it, but it's ellipsized/part of it is invisible.

And yes, this also happens with the latest git version (though I usually don't notice because my terminals usually 192 columns wide).

**Comment by pickfire** [comment] 2015-11-05 03:58
Oh, I understand now. After it covers the right prompt, the suggestions stop appearing.

**Comment by krader1961** [comment] 2017-03-23 04:34
I can no longer reproduce so I'm closing this.

**Closed by krader1961** 2017-03-23 04:34 UTC
Labels: bug
