### ISSUE TITLE
gettext underscore does not parse successfully

### ISSUE THREAD

**Issue by xaverdh** [fish-shell/fish-shell#7177] opened 2020-07-06 10:47 UTC
fish should correctly parse its own language, but:

`fish -n -c '_ hello'` outputs:
```
fish:
_ "echo"
^
```
while `fish  -c '_ hello'` runs just fine.

```
fish --version: fish, version 3.1.2
(running on NixOS)
```

**Comment by faho** [comment] 2020-07-06 10:56
Duplicate of #977

**Closed by faho** 2020-07-06 10:56 UTC

**Comment by xaverdh** [comment] 2020-07-06 12:08
right, sorry for the noise!
