### ISSUE TITLE
cd -L, cd -P "Too many args for cd command"

### ISSUE THREAD

**Issue by lapsio** [fish-shell/fish-shell#4845] opened 2018-03-23 00:00 UTC
fish, version 2.7.0, Linux linux-psg6 4.14.15-1-default #1 SMP PREEMPT Thu Jan 25 13:26:16 UTC 2018 (5b3d0ce) x86_64 x86_64 x86_64 GNU/Linux
xterm-256color, OpenSUSE 42.3

How can I preserve symlinks path in fish like `cd -L` in bash, so that I don't end up in the forest after 

    cd ./link ; cd ..

**Comment by zanchey** [comment] 2018-03-23 00:38
fish always dereferences symlinks, as if `cd -P` is always used - see #1957. 

I'm closing as a duplicate of that for now, although if I've got the wrong end of the stick please feel free to speak up.

**Closed by zanchey** 2018-03-23 00:38 UTC
Labels: duplicate

**Comment by lapsio** [comment] 2018-03-23 01:08
I found that thread. I have just one more question - it seems that cd ~- doesn't work in fish. Is the only way to reference prev dir as app param to use $dirprev[-1] ? It's quite long variable name...

**Comment by krader1961** [comment] 2018-03-23 01:19
> it seems that cd ~- doesn't work in fish

True, but `cd -` does the same thing and does work. There's also the `cdh` command. And, of course, you're free to override the stock `cd` function with your own which does recognize `cd ~-` and `cd ~+`.

**Comment by lapsio** [comment] 2018-03-23 01:20
I rather meant usage in non-cd programs such as `ls ~-`
