### ISSUE TITLE
No prompt output on a serial terminal

### ISSUE THREAD

**Issue by peoronoob** [fish-shell/fish-shell#3740] opened 2017-01-16 16:40 UTC
I have an Odroid-C2: a single-board computer similar to Raspberry Pi. It has a micro USB port that can be used in gadget mode and I'm using it as a serial port offering a TTY.

Both the Odroid-C2 and the laptop I connected it to run Arch Linux with fish 2.4.0 (that's my default shell). Linux 4.8.13 on the laptop and 3.14.79 on the Odroid.

I can successfully connect to the TTY (with `screen`, for instance) and log in, but then I cannot see any prompt (neither the prompt itself, nor the commands I'm typing). Commands output works fine instead (e.g. `ls` ).

If I run a bash, that one works fine as well. I tried to run fish with an empty configuration ( `sh -c 'env HOME=$(mktemp -d) fish'` ) but it doesn't work either. I also tried to play with the `TERM` env var (and with `LANG` as hinted in issue #2559), but to no avail.

Is there anything else I can try?

**Comment by faho** [comment] 2017-01-16 17:19
We're gonna need some more info here - the value of $TERM would be nice, as would a recording of your session with e.g. `asciinema` (`pacman -S asciinema; asciinema rec`).

**Comment by krader1961** [comment] 2017-01-16 20:37
I don't understand how you're using the `screen` command to attach to the console tty. Screen is not a communication program and doesn't have any way to "connect to [a] tty". So presumably you're using something else to connect to the Raspberry Pi USB console.

We recently (i.e., post 2.4.0) merged a bunch of changes to fix problems mixing narrow and wide stdio functions on Linux. Those may be relevant. So we're probably going to need you to install fish built from git head or the 2.5.0 beta recently announced. Assuming that the problem still occurs once we've confirmed that env vars like `LANG` and `TERM` are set correctly.

Also, when setting `LANG` and `TERM` it's the value on the Raspberry Pi, not your laptop, that matter. I'd like to know what `locale` outputs when run on the Raspberry Pi. If it's anything other than "C" or "POSIX" that's likely to be a problem on a Linux console VT. It's unlikely that `TERM` is relevant since there shouldn't be anything you can set it to that would cause all output from fish itself, but not external commands, to not be visible. Nonetheless, please report what `echo $TERM` reports when logged into the Raspberry Pi USB console. And `stty -a` might be interesting.

**Comment by peoronoob** [comment] 2017-01-17 02:54
Thanks for the quick replies guys!

Here is a recording of my session with asciinema: https://asciinema.org/a/chx1lo09bjqavbh1id0ay8lq9

It also includes the value of a few env vars and the ouput of a few commands:
 - `TERM` is `vt220`. I tried to change it to a few other values.
 - `LANG` is `en_US.UTF-8`. I tried changing it to `C` (both modifying the environment for the current session, and modifying `/etc/locale.conf` and logging out and back in).
 - The output for `locale` is:
    ```
    LANG=en_US.UTF-8
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=
    ```
    After I modified `/etc/locale.conf` it became:
    ```
    LANG=C
    LC_CTYPE="C"
    LC_NUMERIC="C"
    LC_TIME="C"
    LC_COLLATE="C"
    LC_MONETARY="C"
    LC_MESSAGES="C"
    LC_PAPER="C"
    LC_NAME="C"
    LC_ADDRESS="C"
    LC_TELEPHONE="C"
    LC_MEASUREMENT="C"
    LC_IDENTIFICATION="C"
    LC_ALL=
    ```
 - The output for `stty -a` is:
    ```
    speed 9600 baud; rows 0; columns 0; line = 0;
    intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
    eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
    werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
    -parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
    -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff
    -iuclc -ixany -imaxbel iutf8
    opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
    isig icanon -iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
    -echoctl echoke -flusho -extproc
    ```

Did I forget anything?

I'll proceed with installing fish from git and see what happens.

**Comment by peoronoob** [comment] 2017-01-17 03:38
I just installed [`fish-git` from AUR](https://aur.archlinux.org/packages/fish-git/). I believe it built and installed the latest commit, https://github.com/fish-shell/fish-shell/commit/d905ed33feadf5234f4bcaae016a290dbf4738ad.

It still suffers from the same bug: the prompt is completely invisible. I'm still using `LANG=C`.

**Comment by krader1961** [comment] 2017-01-17 03:44
Thanks for following directions, @peoronoob :smile: Too many people asking for help ignore half our questions. The stty output looks okay. I noticed your asciinema recording shows LANG en_US.UTF-8 and while that's problematic for the linux console VT I don't think it's the cause of this problem.

Your asciinema recording shows quite clearly that fish is writing the prompt. After we see

```
Last login: Sat Jan  7 01:55:05 on ttyGS0
```

we see that ` \b\e[K\n/home/peoro\r\n \b\e[K[peoro@odroid-l77 ~]$ ` is written followed by `pwd` being echoed. Then `\r\n/home/peoro\r\n` followed by another prompt. Then `echo $TERM`, etc.

The `\e[K` is the command to erase from the cursor through the end of the line. What I think is happening is that command is causing all subsequent output to be discarded by `screen` till the next `\r` character. And that char isn't written until your press [enter] after typing the command.

When running within `screen` or `tmux` you should never use a `$TERM` that is not `screen` or `screen-256color` (or the `tmux` equivalents).  What happens if you set `$TERM` to the correct value?

**Comment by krader1961** [comment] 2017-01-17 03:49
Also, I see my earlier comment about `screen` not being able to connect to a tty is wrong. I've never used it that way but sure enough the man page say that

> If a tty (character special device) name (e.g. "/dev/ttya") is specified as  the first  parameter,  then  the  window is directly connected to this device.

Personally I would never use it in that fashion. I'd use the `cu` command or something similar and only use `screen` if I wanted its other features. But to each their own. If it works for you (after correctly setting `$TERM` on the remote system) feel free to continue doing so.

**Comment by krader1961** [comment] 2017-01-17 04:09
Aha! Looking at `s_update()` in *src/screen.cpp* and your `stty -a` output I can't but wonder if the lack of a known terminal width and height is the problem. In fact, I'm willing to bet $10 that is the problem. Try running `exec /bin/sh` then `stty rows 24 cols 80` (or whatever values make sense) then `exec fish`. Does that fix the problem?

**Comment by peoronoob** [comment] 2017-01-17 04:15
I don't have much experience with serial consoles. The [ArchWiki](https://wiki.archlinux.org/index.php/working_with_the_serial_console) doesn't even mention `cu`, and I didn't know about it. Thanks for suggesting it, I do prefer avoiding screen, which is unnecessary for my use case.

I just tried following your last input, and yes! using `stty rows 24 cols 80` does fix the problem! I'm impressed by how quickly you found the culprit!

**Comment by krader1961** [comment] 2017-01-17 04:19
Fantastic. Solving problems like this is how I used to earn my living for over 20 years so I've gotten pretty good at it. I'm just annoyed with myself for not figuring this out a year ago in issue #2559.

I think the right thing to do is check for the tty device reporting a width and height of zero and substituting reasonable defaults (e.g., 24 x 80) with a warning. That way people won't have to do the tap dance I gave you. I'll create a patch in a few minutes.

**Comment by peoronoob** [comment] 2017-01-17 04:35
That's awesome!
I'm guessing that terminal emulators have no way to pass the terminal size to a serial console? Now I understand why sometimes lines were cut to 80 on some terminals (e.g. `adb shell`).

I'm adding a `stty rows 42 cols 263` to my `config.fish` (and probably will leave there forever, since 24x80 is way too small for me).

Thanks a lot for helping me out and fixing this issue so quickly!

**Comment by krader1961** [comment] 2017-01-17 04:41
> I'm adding a stty rows 42 cols 263 to my config.fish

Sadly that won't work at the moment because fish is very conservative about trusting tty termios values when returning from an external command (and `stty` is an external command). That's why I had you `exec bash` first, do the `stty`, then `exec fish`. We have an issue open where we're discussing how to safely allow using `stty` inside a fish session. For the moment you'll have to do that indirection through bash if defaults of 80 x 24 aren't appropriate.

> I'm guessing that terminal emulators have no way to pass the terminal size to a serial console?

Correct. There are ways to hack around this shortcoming but they're just that: hacks rather than robust solutions. Serial consoles basically date back to the days of hardware terminals, like a physical DEC VT220, when you could trust the information about columns and rows in the terminfo definition.

**Comment by krader1961** [comment] 2017-01-17 05:20
Note that bash has a complicated heuristic in its `_rl_get_screen_size()` function that also looks, optionally, at the `COLUMNS` and `LINES` env vars as well as the terminfo values. I don't think we need all that baggage. Especially once we allow using `stty` to set the terminal dimensions. I think it makes more sense to have exactly one place, the tty termios values, where we get this information.

**Comment by krader1961** [comment] 2017-01-17 16:06
I wrote earlier:

> Sadly that won't work at the moment because fish is very conservative about trusting tty termios values when returning from an external command (and stty is an external command).

Which is true but turns out to be irrelevant to this discussion because the terminal size is not stored with the other termios values (e.g., the interrupt character and flow-control setting). So, yes, you can fix this by running `stty rows 24 cols 80` inside the current fish session. Even within one of the startup scripts like *~/.config/fish/config.fish*.

**Comment by krader1961** [comment] 2017-01-18 01:08
I was going to implement falling back to the `COLUMNS` and `LINES` env vars like other shells do but found that they are "electric" vars. Meaning they cannot be set by the user. They're always derived from the function that needs to fall back to them if the system doesn't support `ioctl(TIOCGWINSZ)` or it returns zero for the size. Should we keep the current behavior and just default to 80x24? Or should those vars be semi-electric? Meaning that we always set them to the term size we calculate in `get_current_winsize()`; possibly after falling back to using the values those vars are set to? This means that if the system supports TIOCGWINSZ we always use it as the source of truth if non-zero and any value the user assigns to `COLUMNS` and `LINES` is ignored. If we keep them as electric vars then we'll always fall back to 80x24 if the system does not support TIOCGWINSZ or it returns zero.

**Comment by krader1961** [comment] 2017-01-18 06:31
FWIW, I feel pretty strongly that we should import, and allow the user to change, the `COLUMNS` and `LINES` env vars. While also setting those vars to the values reported by `ioctl(TIOCGWINSZ)` if that is supported. This is the most sane compromise. It allows users on systems that do not support `ioctl(TIOCGWINSZ)` to specify their terminal size using historical practice.

**Closed** 2017-01-20 23:37 UTC
Labels: enhancement

**Comment by izelnakri** [comment] 2019-01-03 15:45
@krader1961 how can I suppress "fish: Defaulting terminal size to 80x24." warning? I get it when I have several tmux panes open on my laptop. I would like to remove these warnings.

**Comment by faho** [comment] 2019-01-03 19:16
>how can I suppress "fish: Defaulting terminal size to 80x24." warning?

@izelnakri: You currently can't.

We should think about removing the "terminal is too small" one. If the terminal is _small_, it's quite likely there's some reason for it beyond it not being set properly. Having a size of 0 most likely signifies some form of error, so we should keep that one.
