### ISSUE TITLE
string replace at start only

### ISSUE THREAD

**Issue by mikelward** [fish-shell/fish-shell#7089] opened 2020-06-06 19:30 UTC
I would like to be able to delete a string from the start of another string.

In bash/zsh, this would be

    root=/home/mikel/src/project/
    dir=/home/mikel/src/project/subdir
    echo ${dir#$root}

I can do something similar in fish with

    string replace $root '' $dir

But there's no guarantee that the replacement will happen at the start, so it could have weird corner cases.

I could also do

    string replace --regex $root '' $dir

but then I have to escape any special characters in `$root`.

I would like to be able to do something like

    string replace --start $root '' $dir

**Comment by krobelus** [comment] 2020-06-06 19:51
Duplicate of #4002 

In this case `realpath $dir --relative-to=$root` could work.

Also `string replace --regex -- ^(string escape --style=regex -- $root) $dir` which is a bit unwieldy, but you can put it into a function.

**Closed by krobelus** 2020-06-06 19:51 UTC
