### ISSUE TITLE
dnf install <TAB> produces the string with all variants in one line

### ISSUE THREAD

**Issue by iRomanyshyn** [fish-shell/fish-shell#10954] opened 2024-12-27 14:20 UTC
fish, version 3.7.0

Fedora 41

Nothing changes after running `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'`.

After some moments, my Fish instance started to produce strange autocompletion for the `dnf install` command. For example, `sudo dnf install VirtualBox<TAB>` 
gives the string: 
```> sudo dnf install VirtualBoxVirtualBox-develVirtualBox-kmodsrcVirtualBox-serverVirtualBox-webserviceVirtualGLVirtualGL-develvirglrenderervirglrenderer-develvirglrenderer-test-servervirt-backupvirt-bootstrapvirt-installvirt-lightningvirt-managervirt-manager-commonvirt-p2vvirt-topvirt-v2vvirt-v2v-bash-completionvirt-v2v-man-pages-javirt-v2v-man-pages-ukvirt-viewervirt-whatvirt-whovirt-win-regvirtdetectvirtiofsdvirtme-ngvirtualbox-guest-additionsvirtualpgvirtualpg-devel```.

If there are many suggestions it may produce a couple of screens with a lot of space symbol at the end.
![image](https://github.com/user-attachments/assets/2a68af37-c3b4-4c7b-b5ee-68ce090943a2)

**Comment by faho** [comment] 2024-12-27 14:34
Duplicate of #9862

**Closed by faho** 2024-12-27 14:34 UTC
