### ISSUE TITLE
fish not work in a git repository

### ISSUE THREAD

**Issue by daydaygo** [fish-shell/fish-shell#3390] opened 2016-09-19 03:17 UTC
fish, version 2.2.0

if i am in a git repository, fish stops when i user any command even `cd` and `ls`, i have to use `Ctrl + c` .
but if i enter a command, this happens again.

**Comment by krader1961** [comment] 2016-09-19 03:38
This is almost certainly due to fish customizations you've made (possibly by installing third-party extensions) and/or something unusual about your git repository. For example, see issue #3290.

What happens if you start a shell without your local customizations? For example, `env XDG_CONFIG_HOME=/tmp/bogus fish`.

**Comment by ridiculousfish** [comment] 2016-09-19 06:20
This could be a bad prompt. What does `functions fish_prompt` show?

**Comment by krader1961** [comment] 2016-10-02 03:28
Ping? Did you resolve this, @daydaygo, or do you still need help?

**Comment by daydaygo** [comment] 2016-10-02 03:58
@krader1961 i use oh my fish to install a theme, such as Eden. Then  when i enter a git reposity, this happens. when i uninstall the theme, it works well.

**Comment by krader1961** [comment] 2016-10-02 04:05
@daydaygo, Can you show us what `functions fish_prompt` outputs as requested by @ridiculousfish? Also, please confirm this is the theme [eden](https://github.com/oh-my-fish/theme-eden) you are referring to.

Note that we can't provide much help with third-party prompts. It helps us if you can provide data to suggest the problem is with fish rather than the third-party prompt which might be executing hideously expensive (i.e., slow) commands.

**Comment by krader1961** [comment] 2016-10-02 04:37
Note that I use git on a daily basis and use a fish prompt that shows the git status I find useful. As do many other fish users. So clearly it is not the case that "fish not work in a git repository".

Assuming you're referring to the [oh-my-fish/theme-eden](https://github.com/oh-my-fish/theme-eden/) extension I think you need to talk to the author of that theme. When I looked at its code the first thing that caught my attention was [this](https://github.com/oh-my-fish/theme-eden/blob/master/fish_prompt.fish) code:

```
function _git_branch_name
  echo (command git symbolic-ref HEAD ^/dev/null | sed -e 's|^refs/heads/||')
end

function _is_git_dirty
  echo (command git status -s --ignore-submodules=dirty ^/dev/null)
end
```

The `echo` and subcommand invocation in those functions is superfluous. For example, that code should just do `command git symbolic-ref HEAD ^/dev/null | sed -e 's|^refs/heads/||'` inside  _git_branch_name`. That is a red flag that causes me to wonder if there are more serious problems with this code. Those pointless echoes of git subcommand output is unlikely to be the source of your problem but does make me wonder if there are more significant problems with that code.

Furthermore, that script calls `_git_branch_name` twice when only a single invocation is necessary. The author of this theme definitely does not understand how to avoid operations that do nothing but add overhead (i.e., slow down).

**Comment by daydaygo** [comment] 2016-10-02 04:44
show the git branch name is a good feature, so i use that theme. when i got into this problem, i changed other theme, it die not work until i uninstal all theme. @krader1961 can you recommend a theme which can show the git branch name?

**Comment by floam** [comment] 2016-10-02 08:17
Type `fish_config`, press enter. The 'informative' theme and others included with fish show the current git branch.

**Comment by floam** [comment] 2016-10-02 08:19
Let us know if you still get the issue with an included prompt, please!

**Comment by krader1961** [comment] 2016-10-10 03:14
@daydaygo, I use a customized prompt not directly derived from a single theme. So I can't recommend a theme. However, my prompt uses `__fish_vcs_prompt` which shows the git branch name (or commit ID if not at git head) and I've never seen any performance problems using it. Specifically, my `fish_prompt` function has this statement where I want the git branch name to appear in my prompt:

```
echo -ns (set_color $fish_color_git) (__fish_vcs_prompt)
```

I'm going to close this because the available data suggests the "Eden" prompt is inefficient. If you can provide more data, @daydaygo, that at least suggests fish itself (or the fish scripts/functions we provide) are the reason for your problem please reopen this issue with that data.

**Closed by krader1961** 2016-10-10 03:14 UTC
Labels: needs-more-info, question
