### ISSUE TITLE
Newline confusion with bind \cj

### ISSUE THREAD

**Issue by michaeljones** [fish-shell/fish-shell#4726] opened 2018-02-14 19:13 UTC
fish --version: `fish, version 2.6.0`
echo $version: `2.6.0`

uname -a: `Linux samurai 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

echo $TERM: `xterm-termite`

----

With a fresh fish set up I can type: sleep 5[enter]echo bob[enter] and I'll see:

```
> sleep 5 
echo bob
> echo bob
bob
> 
```
In the console after 5 seconds.

With `bind \cj history-search-forward`, doing the same thing, I see:

```
> sleep 5 
echo bob
> echo bob
```

After 5 seconds. I can do it one after the other with the bind command run in between.

My colleague cannot reproduce this, so I suspect it is a quirk of my set up. Unfortunately I am not experienced enough to figure out what it is. It happens both at home and at work. 

I have a locally compiled version of fish with a couple of changes but I can reproduce that with the system install so I don't think it is dependent on my changes.

I use termite as my terminal emulator but can also reproduce this in the xfce-terminal and an old build of alacritty that I have.

I would love to have this working as I like to use tmuxinator and set up my session with multiple commands and those commands are sometimes being concatenated or not run due to this problem. Any help would be much appreciated.

**Comment by faho** [comment] 2018-02-14 19:29
I'm afraid control-j **is** newline. What terminals do to generate "control-$char" is to take that char's uppercase ASCII code, and unset the 64-bit. Since J is 74 and "line feed" is 14, \cj _is_ \n.

You'll also find that ctrl-I is tab and ctrl-M is carriage return.

This is unfortunately how terminals work - it's 70s technology through and through.

**Comment by krader1961** [comment] 2018-02-14 19:37
The problem occurs because fish disables tty `icrnl` mode when accepting interactive input. That's what makes it possible to bind `\cj` (aka `\n`) and `\cr` (aka `\r`) independent of each other. However, when it runs an external command like `sleep` it enables tty `icrnl` mode because that's what most programs expect. So when you type `echo bob[enter]` the tty driver converts the `\cr` to `\cj` because at that point in time the tty is in `icrnl` mode as a consequence of the `sleep 5`.

What this means, and it should probably be documented in the FAQ and the `bind` man page, is that if you bind `\cj` (or `\n`) to something other than `execute` you can't reliably typeahead additional commands if any of the preceding commands are not fish builtins (or are functions that only run fish builtins).

**Comment by michaeljones** [comment] 2018-02-14 20:08
Thank you very much for the explanation. I think I follow it. I am attempting to convert from zsh as I love lots of the little touches in fish. Unfortunately the equivalent binding in zsh (`bindkey '^J' history-beginning-search-forward-end`) seems to not have this affect so my muscle memory is now deeply fond of this approach. 

I don't want to come across as 'zsh can do it, so why can't fish' but I would be interested to know if you know why it works there? Is there behaviour technically incorrect in this manner? 

Also, I asked my colleague to attempt the test with the `bind` command too and it seemed to continue working for them too. Is that surprising? Did they possibly do it wrong? Does the behaviour I'm seeing above happen for you too? 

Thanks again for the help.

**Comment by krader1961** [comment] 2018-02-14 22:53
I have no difficulty reproducing this. The surprise is that your colleague can't. I suspect they aren't faithfully executing the steps to reproduce the problem.

The reason this works in zsh is because of a hack it uses. Rather than disable `icrnl` and `inlcr` it enables both tty modes. From *zle_main.c*:

```
    ti.tio.c_iflag |= (INLCR | ICRNL);
 /* this line exchanges \n and \r; it's changed back in getbyte
        so that the net effect is no change at all inside the shell.
        This double swap is to allow typeahead in common cases, eg.

        % bindkey -s '^J' 'echo foo^M'
        % sleep 10
        echo foo<return>  <--- typed before sleep returns

        The shell sees \n instead of \r, since it was changed by the kernel
        while zsh wasn't looking. Then in getbyte() \n is changed back to \r,
        and it sees "echo foo<accept line>", as expected. Without the double
        swap the shell would see "echo foo\n", which is translated to
        "echo fooecho foo<accept line>" because of the binding.
        Note that if you type <line-feed> during the sleep the shell just sees
        \n, which is translated to \r in getbyte(), and you just get another
        prompt. For type-ahead to work in ALL cases you have to use
        stty inlcr.

        Unfortunately it's IMPOSSIBLE to have a general solution if both
        <return> and <line-feed> are mapped to the same character. The shell
        could check if there is input and read it before setting it's own
        terminal modes but if we get a \n we don't know whether to keep it or
        change to \r :-(
        */
```

Whether fish should adopt the same hack is debatable. It's one of those things that works as expected most of the time but has its own corner cases which produce surprising behavior.

**Comment by michaeljones** [comment] 2018-02-15 09:12
Thank you for the explanation. That makes a lot of sense. I wouldn't expect fish to adopt anything that feels like a hack. I will endeavour to retrain my fingers. Thanks again, I really appreciate understanding it more.

**Comment by faho** [comment] 2018-02-15 13:58
I don't think we want to add this, so I'm closing as an answered question.

**Closed by faho** 2018-02-15 13:58 UTC
Labels: question
