### ISSUE TITLE
cmd+tab error on WSL with win10

### ISSUE THREAD

**Issue by liweijian** [fish-shell/fish-shell#4631] opened 2018-01-01 06:58 UTC
Version:

```
liweijian@omen3:~$ fish -versionls
fish, version 2.2.0
liweijian@omen3:~$ fish -version
fish, version 2.2.0
liweijian@omen3:~$ uname -a
Linux omen3 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
liweijian@omen3:~$ echo $TERM
xterm-256color
```

When I type `lsTAB`, it shows as follows
![fish](https://user-images.githubusercontent.com/19320783/34466109-1b0b9e68-ef04-11e7-9af4-4a9bed2d84f7.png)

When I switched back to bash, it works well:
![bash](https://user-images.githubusercontent.com/19320783/34466110-2b5c6cac-ef04-11e7-95b9-a675989bb6e2.png)

**Comment by faho** [comment] 2018-01-01 09:49
Duplicate of #952, which was fixed in 2.3.0. You'll want to upgrade.

**Closed by faho** 2018-01-01 09:49 UTC
