### ISSUE TITLE
funced should create files with .fish extension

### ISSUE THREAD

**Issue by julien-f** [fish-shell/fish-shell#2718] opened 2016-02-08 22:06 UTC
So that my editor would do syntax highlighting :)

**Comment by faho** [comment] 2016-02-08 22:25
Already fixed in 616d848faccb75e5301e105aabc86c8681814812!

**Closed by faho** 2016-02-08 22:25 UTC

**Comment by julien-f** [comment] 2016-02-09 08:27
Thanks! The Debian package must be too old :)

Sorry for the useless report but I could not find a previous one regarding this issue.

**Comment by faho** [comment] 2016-02-09 12:44
No, the fix just isn't in a release yet. Though if you wish you can `funced funced` (not a typo - funced is itself a function) and apply it manually.

**Comment by julien-f** [comment] 2016-02-09 12:45
Good idea, thanks :)

**Comment by caesar** [comment] 2016-05-22 19:43
The fix in 616d848 doesn't work on OS X (using BSD `mktemp`).

It results in files with names like `/p/v/f/7/r/T/fish_funced.XXXXXXXXXX.fish.FqwzkCoR` which is clearly not intended.

I don't know of a solution other than(a) requiring the user to install GNU `coreutils` or (b) manually appending the extension ourselves after calling `mktemp`. I would vote for the latter for the sake of compatibility.

This works for me on both OS X and Debian:
`````diff
-    set tmpname (mktemp -t fish_funced.XXXXXXXXXX.fish)
+    set tmpname (mktemp fish_funced.XXXXXXXXXX).fish
`````

I have removed the `-t` flag because:
(a) it is deprecated in GNU coreutils and does nothing
(b) on OS X it causes the XXXXXXXXXX to be literal X characters instead of being replaced by digits.

Thoghts?

**Comment by faho** [comment] 2016-05-22 22:13
@caesar: Moving the ".fish" out of the mktemp call actually makes matters _worse_, because now the filename you generate isn't guaranteed to not be taken. Moving the "-t" away (which actually _does_ work on my system with mktemp from gnu coreutils 8.25) means the tmpfile will be generated in the current directory, which is also worse.

It seems GNU coreutils would like the "-p" flag more - with a very awkward `mktemp -p "" FILENAME`, but according to [the man page](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/mktemp.1.html) OSX mktemp doesn't know that flag (and it _does_ know "-t").

We can remove the "-t" if we do the logic ourselves - `set -q TMPDIR; or set -l TMPDIR /tmp`, but the suffix isn't gonna work on OSX - unless just "XXXXXX.fish" (without the "fish_funced") as a template works. Can someone with access to OSX test that?

**Comment by faho** [comment] 2016-05-22 22:40
So @laughedelic confirmed "XXXXXX.fish" does _not_ work with OSX mktemp (generating literal "XXXXXXX.fish"), so the only way I can see is to make a directory and generate a file in there. That would also allow us to pick the filename $function.fish - which might appear a bit nicer in some editors.

**Comment by faho** [comment] 2016-05-22 22:50
@caesar: 5accc7c6c5b2234998d1a88de2dfeb1057bd550 should fix it.

**Comment by caesar** [comment] 2016-05-23 00:02
@faho, that fixes it, great. Having the name of the function in the filename is even better.

Some of your other comments don't seem to agree with what I've read in the manpages or the behaviour I've observed – but it doesn't matter, no need to discuss, because your patch is a better solution anyway. :-)
