### ISSUE TITLE
Lines after fish inserted a line return character (⏎) are not resized correctly

### ISSUE THREAD

**Issue by azixMcAze** [fish-shell/fish-shell#3663] opened 2016-12-20 14:33 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.4.0

**OS/terminal used**: OSX 10.10.5 (Yosemite) with Apple Terminal 2.5.3, $TERM_PROGRAM_VERSION = 343.7

When commands do not end with a line break, fish inserts a line return character (⏎) and returns to the next line.
When you resize the terminal window, the line juste after this line return do not behave correctly.

Before resizing :
![capture d ecran 2016-12-20 a 15 16 28](https://cloud.githubusercontent.com/assets/1919205/21353780/d5be7c6e-c6c7-11e6-8c47-3d88e8eeb7ca.png)
After resizing :
![capture d ecran 2016-12-20 a 15 16 33](https://cloud.githubusercontent.com/assets/1919205/21353785/d9d84712-c6c7-11e6-9550-009b8442241d.png)

It looks like fish inserts space characters to complete the line instead of inserting a \n char
```
Last login: Tue Dec 20 15:15:15 on ttys001
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
mathieu@Mathieu ~$ echo test
test
mathieu@Mathieu ~$ echo -n test
test⏎                                           mathieu@Mathieu ~$ 
mathieu@Mathieu ~$ 
```
(copied from the terminal window)

**Comment by faho** [comment] 2016-12-20 15:05
This doesn't happen for me on konsole (on linux).

I think I recall that Terminal.app reflows text. That might interfere with our trick to get the prompt onto a new line (and insert the special linebreak character) - because we rely on it wrapping.

**Comment by azixMcAze** [comment] 2016-12-20 17:05
@faho Is there a reason to rely on wrapping and not just printing \n ?

**Comment by krader1961** [comment] 2016-12-20 21:31
If fish alway emitted a newline before the prompt, in place of what it does now, then 99% of the time you'll get an extra blank line before the prompt. Which seems like a worse problem than having the line wrapping behave weird in some terminals when they are resized. After all, how often do you resize your terminals? And many terminals, such as iTerm2, do the right thing. The only viable alternative is to not emit anything and let the prompt overwrite, or append to, the last line of output of the command if it did not end with a newline. Which is what many shells do such as /bin/sh on macOS:

```
sh-3.2$ /bin/echo -n hello
hellosh-3.2$
```

Which is an alternative that is worse than having lines rewrap in an odd manner when you resize the terminal.

P.S., Terminal.app version 388 (included in macOS Sierra) handles this better.

**Comment by ridiculousfish** [comment] 2016-12-20 23:43
Unfortunately there's no way to detect if the last line ended with a newline, so fish uses the "PROMPT_SP" hack from zsh, which requires using spaces. AFAIK this is unfixable.

**Comment by faho** [comment] 2017-01-03 18:06
Since we all seem to think there's nothing that can be done here, I'm closing this.

**Closed by faho** 2017-01-03 18:06 UTC
Labels: question

**Comment by krader1961** [comment] 2017-01-03 19:43
FWIW, There has been recent discussion on the tmux project about resizing windows causing problems with tmux pane resizing independent of the particular shell. The person raising the biggest fuss about the issue is using a tiling window manager that causes all his terminals to be resized whenever he opens a new window. To each his own but I have no sympathy for anyone using a setup with such silly behavior.
