### ISSUE TITLE
99% cpu in hung telnet session, fish process group not quit when terminal.app windows are closed

### ISSUE THREAD

**Issue by breathe** [fish-shell/fish-shell#1958] opened 2015-02-26 05:46 UTC
I'm on OS X Yosemite (10.10.2) with:

~> fish --version
fish, version 2.1.1-1191-g1ff9aba

I was debugging an issue with a mail-server via telnet -- after closing the window containing the fish process from which I ran the telnet sessions -- I'm seeing the process group that owning the telnet process fail to shut down ...  After awhile the two telnet processes each started using 99% cpu ...

 ~> ps
  PID TTY           TIME CMD
83498 ttys000    0:00.07 -fish
 7496 ttys001    0:00.08 -fish
 7506 ttys001  3210:46.14 telnet foo.smtp.com 25
70932 ttys004    0:00.15 -fish
71193 ttys004    0:00.06 ssh root@rr-ns
47337 ttys009    0:00.05 -fish
47346 ttys009  617:22.03 telnet foo.smtp.com 587
 3187 ttys015    0:00.09 /usr/local/bin/fish

processes 7506 (child of 7496) and 47346 (child of 47337) are each using 99% cpu.

It seems that neither closing all the terminal windows within terminal.app nor quitting terminal.app is sufficient to clean these processes up.  I'm not actually sure if this is a fish bug -- but this behaviour is unexpected to me and I'm if its the result of some non-ideal interaction between fish and terminal.app ...?

**Comment by breathe** [comment] 2015-02-26 05:47
Steps to reproduce:

1. open terminal.app
2. telnet somehost 25
3. <close window>

**Comment by ridiculousfish** [comment] 2015-02-26 05:55
Can't reproduce this with OS X Yosemite on 2.1.2 or ToT. I wonder if the remote server is sending some escape sequences or something else. Can you reproduce with a public telnet server, like `telnet telehack.com`?

**Comment by breathe** [comment] 2015-02-26 05:58
Hmm it doesn't reproduce with telehack.com -- but it does with `telnet smtp.gmail.com 587`

**Comment by ridiculousfish** [comment] 2015-02-26 06:59
Thanks, I can reproduce with that hint. Perhaps related to #1097.

```
Call graph:
    2706 Thread_2766970   DispatchQueue_1: com.apple.main-thread  (serial)
      2706 start  (in libdyld.dylib) + 1  [0x7fff8d8d65c9]
        2706 ???  (in telnet)  load address 0x10fef7000 + 0x73ca  [0x10fefe3ca]
          2706 ???  (in telnet)  load address 0x10fef7000 + 0x4e9a  [0x10fefbe9a]
            1906 ???  (in telnet)  load address 0x10fef7000 + 0x7ca9  [0x10fefeca9]
            + 1871 tcsetattr  (in libsystem_c.dylib) + 98  [0x7fff87b71e29]
            + ! 1835 __ioctl  (in libsystem_kernel.dylib) + 10  [0x7fff8e9c7c22]
            + ! 33 ioctl  (in libsystem_kernel.dylib) + 159,60,...  [0x7fff8e9c59b7,0x7fff8e9c5954,...]
            + ! 3 ioctl  (in libsystem_kernel.dylib) + 159  [0x7fff8e9c59b7]
            + !   3 __ioctl  (in libsystem_kernel.dylib) + 20  [0x7fff8e9c7c2c]
            + 35 tcsetattr  (in libsystem_c.dylib) + 140,98,...  [0x7fff87b71e53,0x7fff87b71e29,...]
            770 ???  (in telnet)  load address 0x10fef7000 + 0x7cb6  [0x10fefecb6]
            + 713 write  (in libsystem_kernel.dylib) + 10,0,...  [0x7fff8e9c9c22,0x7fff8e9c9c18,...]
            + 21 ???  (in telnet)  load address 0x10fef7000 + 0xbdac  [0x10ff02dac]
            + ! 15 cerror  (in libsystem_kernel.dylib) + 13  [0x7fff8e9c3c85]
            + ! : 10 _pthread_exit_if_canceled  (in libsystem_pthread.dylib) + 0,15,...  [0x7fff87594942,0x7fff87594951,...]
            + ! : 5 _pthread_exit_if_canceled  (in libsystem_kernel.dylib) + 10,0  [0x7fff8e9b2b32,0x7fff8e9b2b28]
            + ! 4 cerror  (in libsystem_kernel.dylib) + 5,0,...  [0x7fff8e9c3c7d,0x7fff8e9c3c78,...]
            + ! 1 ???  (in telnet)  load address 0x10fef7000 + 0x7a9f  [0x10fefea9f]
            + ! 1 ???  (in telnet)  load address 0x10fef7000 + 0x7aa6  [0x10fefeaa6]
            + 6 ???  (in telnet)  load address 0x10fef7000 + 0xbd7f  [0x10ff02d7f]
            + ! 3 ???  (in telnet)  load address 0x10fef7000 + 0x7955  [0x10fefe955]
            + ! 2 ???  (in telnet)  load address 0x10fef7000 + 0x7951  [0x10fefe951]
            + ! 1 ???  (in telnet)  load address 0x10fef7000 + 0x798b  [0x10fefe98b]
            + 6 ???  (in telnet)  load address 0x10fef7000 + 0xbd8a  [0x10ff02d8a]
            + ! 3 ???  (in telnet)  load address 0x10fef7000 + 0x798d  [0x10fefe98d]
            + ! 1 ???  (in telnet)  load address 0x10fef7000 + 0x7994  [0x10fefe994]
            + ! 1 ???  (in telnet)  load address 0x10fef7000 + 0x79a9  [0x10fefe9a9]
            + ! 1 ???  (in telnet)  load address 0x10fef7000 + 0x79c2  [0x10fefe9c2]
            + 6 ???  (in telnet)  load address 0x10fef7000 + 0xbe05  [0x10ff02e05]
            + 5 ???  (in telnet)  load address 0x10fef7000 + 0xbe2c  [0x10ff02e2c]
            + 3 ???  (in telnet)  load address 0x10fef7000 + 0xbd67  [0x10ff02d67]
            + 2 ???  (in telnet)  load address 0x10fef7000 + 0xbe2b  [0x10ff02e2b]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbd70  [0x10ff02d70]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbd7a  [0x10ff02d7a]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbd7f  [0x10ff02d7f]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbd8a  [0x10ff02d8a]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbd92  [0x10ff02d92]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbda1  [0x10ff02da1]
            + 1 ???  (in telnet)  load address 0x10fef7000 + 0xbdae  [0x10ff02dae]
            + 1 DYLD-STUB$$write  (in telnet) + 0  [0x10ff04e52]
            8 ???  (in telnet)  load address 0x10fef7000 + 0x7cad  [0x10fefecad]
            6 ???  (in telnet)  load address 0x10fef7000 + 0x7cb6  [0x10fefecb6]
            5 ???  (in telnet)  load address 0x10fef7000 + 0x7ca9  [0x10fefeca9]
            5 DYLD-STUB$$tcsetattr  (in telnet) + 0  [0x10ff04e34]
            3 ???  (in telnet)  load address 0x10fef7000 + 0x7c99  [0x10fefec99]
            2 ???  (in telnet)  load address 0x10fef7000 + 0x7cb1  [0x10fefecb1]
            1 ???  (in telnet)  load address 0x10fef7000 + 0x7c9c  [0x10fefec9c]
```

**Comment by ridiculousfish** [comment] 2015-02-26 07:07
The ioctls may be `TIOCSETAW`

**Comment by ridiculousfish** [comment] 2015-02-26 19:32
telnet is repeatedly calling write() on fd 1 (stdout), and getting EIO, which it doesn't handle properly. This is definitely a telnet bug, but there must be something fish is doing to trigger it. It may be because the process group is orphaned - perhaps we are not resetting the SIGHUP handler?

**Comment by ridiculousfish** [comment] 2015-02-26 21:59
Confirmed that when started under bash, telnet get SIGHUP, but when started under fish it does not. I wonder why?

**Comment by ridiculousfish** [comment] 2015-02-27 02:55
Looks like fish isn't getting SIGHUP at all - very weird. I wonder if we've messed up the term somehow.

**Comment by ridiculousfish** [comment] 2015-02-27 03:25
Bisects to e340baf6ccb9325073dbb10bf96ac911131c5960

**Comment by ridiculousfish** [comment] 2015-02-27 17:57
Fixed as b4aa2b7c2cdd640f4f5e1fb9efd37bb280573c89

"e340baf6cc introduced a bug where fish would not exit from job_continue
    when receiving a signal like SIGHUP. This means that it would not in turn
    deliver SIGHUP to its children, who would therefore never exit. Those
    children may attempt to write to stdout, in which case they would receive
    EIO; this can cause other weird issues, like telnet using 100% CPU."

**Comment by ridiculousfish** [comment] 2015-02-27 17:57
This was a very serious bug. Thank you for taking the time to report it!!

**Comment by turing-complete** [comment] 2015-03-28 14:08
I'm not quite sure, but I think the SIGHUP bug must still be there in other cases. I suspect that fish does not respect SIGHUP when using iTerm2. 

I have a similar effect with ghost fish processes when using ```fish, version 2.1.2-1236-gad61c3f```, with iTerm2 ```Build 2.9.20150324-nightly``` on Yosemite 10.10.3 (latest public beta). 

As far as I remember the issue is there during the past year and I think relates also to [this post](https://code.google.com/p/iterm2/issues/detail?id=1868).

Specifically, after using iTerm to do terminal work with several configurations, i.e. multiple tabs and/or windows, upon closing them (without having pending processes), usually leave fish ghost processes behind:

```
➤ ps -aef | grep fish
  501 28461 24008   0  2:59PM ??         0:00.00 (fish)
  501 28836 24008   0  2:59PM ttys000    0:00.18 -fish
  501 28309 28308   0  2:58PM ttys001    0:00.56 -fish
  501 29668 28309   0  3:00PM ttys001    0:00.00 grep fish
  501 29445 24008   0  3:00PM ttys002    0:00.17 -fish
  501 28583 24008   0  2:59PM ttys003    0:01.08 -fish
  501 28716 24008   0  2:59PM ttys004    0:00.19 -fish
  501 28932 24008   0  2:59PM ttys005    0:00.23 -fish
  501 29036 24008   0  2:59PM ttys006    0:00.18 -fish
  501 29135 24008   0  2:59PM ttys007    0:00.18 -fish
```

**Comment by ridiculousfish** [comment] 2015-03-28 18:38
Thanks for your analysis! Reopening for some investigation. We don't want to ship it like this.

**Comment by turing-complete** [comment] 2015-03-28 20:00
I suspect it's going to be a bit tricky. I originally thought the bug to appear in a kind of non-standard configuration, and it was due to my own fault.

For the past year, I have been developing my own utility framework, a la oh-my-zsh, on which I'm fiddling with the ```on_exit``` event handler:

```
function on_exit --on-process %self
    set -e sword_updated
    set -e fish_updated
    echo "bye"
    builtin exit
end
```

Apparently this is problematic, something I realised just now, due to the %self variable. I mean for one fish process it should work, but not when having multiple fish processes (as launched by each tab/window on iTerm).

However, removing the on_exit function, does not have any effect on the SIGHUP bug as I can confirm that even without the function I can still see past, ghost processes. 

Please let me know if I can help tracing this down.

**Comment by turing-complete** [comment] 2015-03-28 20:42
When searching a little further I tend to arrive to the conclusion that it might not be a fish bug, but rather an iTerm2 buggy feature. Let me explain:

First I noticed that no matter what, either fish sub-processes (jobs) or fish itself kept running after pressing command+w to close the corresponding window and/or tab.

The (sub)processes appeared still attached to their corresponding ttys for several seconds after closing the window. 

However after a few more seconds, they were attached to no ttys, still appearing in ```ps```.

Now, when going through iTerm's settings I saw under Profiles -> Session, a "Undo" setting which mentions: 

```"Undo" can revive a session that has been closed for up to "30" seconds```

Which indeed makes a lot of sense, as I've tried it and essentially with ```command+z``` you can bring back a closed window (session).

Which brings up the question, How iTerm2 handles it's session closing and what kind of SIG it sends to the shell?

Interesting observation: 

```ps``` output for currently active fish session:
```
UID   PID  PPID   C STIME   TTY           TIME CMD
501  3085  3084   0  9:31PM ttys000    0:00.40 -fish
```

```ps``` output for closed/ghost active fish session:
```
  501  2933  2715   0  9:24PM ??         0:00.00 (fish)
  501  2949  2715   0  9:24PM ??         0:00.00 (fish)
  501  2965  2715   0  9:24PM ??         0:00.00 (fish)
  501  2989  2715   0  9:24PM ??         0:00.00 (fish)
  501  3058  2715   0  9:28PM ??         0:00.00 (fish)
```

Notice how ```-fish``` turns to ```(fish)``` in CMD.

**Comment by turing-complete** [comment] 2015-03-28 21:16
I also made a quick session recording to illustrate this better. It can be found [here](https://asciinema.org/a/18146).

The steps are the following:

* I use an empty ```config.fish``` and I had set the "Undo" feature to 5 seconds

* T+00:08 I start opening new tabs/windows. In some of them I execute ```bash```.
* T+00:24 I close all the opened windows with ```command+w```
* T+00:29 As expected their sessions start to close one by one, but see what happens to their corresponding processes. 

Another interesting observation:
4 of the 8 fish processes which had no subprocesses exited normally.
The other 4 which had bash as as a sub-process turned into ```(fish)``` and remained in the ```ps``` list detached. 

Hope this gives a hint.

**Comment by ridiculousfish** [comment] 2015-03-29 01:30
@turing-complete  Do you have iTerm configured to run a login shell or a command at startup? You can check by going Preferences -> Profiles -> General tab.

**Comment by ridiculousfish** [comment] 2015-03-29 01:33
I have mine set to login shell, and I see iTerm2 orphaning `/usr/bin/login` processes. That's true even if my login shell is bash. So I don't think this is fish specific.

**Comment by turing-complete** [comment] 2015-03-29 08:20
@ridiculousfish Yes, you are right. I have iTerm use my login shell, where my login shell is fish.
Digging into iTerm's code I could see [this](https://github.com/gnachman/iTerm2/blob/master/sources/shell_launcher.c#L1-L5), which explains a few things. 

```
// This function the user's shell, replacing the current process with the shell, and
// inserting a "-" at the start of argv[0] to make it think it's a login shell. Unfortunately,
// Apple's login(1) doesn't let you preseve the working directory and also start a login shell,
// which iTerm2 needs to be able to do. This is meant to be run this way:
//   /usr/bin/login -fpl $USER iTerm.app --launch_shell
```

**Comment by ridiculousfish** [comment] 2015-03-29 18:51
Thanks, I agree. I'll close this and open an issue in iTerm2.

**Comment by ridiculousfish** [comment] 2015-03-29 19:01
iTerm2 issue opened at https://code.google.com/p/iterm2/issues/detail?id=3471

I may take a crack at fixing it.

**Comment by ridiculousfish** [comment] 2015-03-29 19:01
Thank you for reporting this!

**Closed by ridiculousfish** 2015-03-29 19:01 UTC

**Comment by turing-complete** [comment] 2015-03-29 19:04
anytime :)

**Comment by ridiculousfish** [comment] 2015-03-29 20:11
My iTerm2 PR: https://github.com/gnachman/iTerm2/pull/204/
