### ISSUE TITLE
Fish reports some weird stuff and hangs, when command not found

### ISSUE THREAD

**Issue by shevegen** [fish-shell/fish-shell#2605] opened 2015-12-12 16:29 UTC
Hi. I use fish 2.2.0, compiled from source.

I type a command that does not exist:

"gwjklhjklher"

Then suddenly I get this:

bash: gwjklhjklher: command not found...

I am confused as to why there is a leading bash. Does fish try to evluate something via bash?

Additionally it takes a long time before it continues, as if it tries to search around for something.

Is there perhaps an additional way to get at debug information while having a fish shell running? I assume it may be with one of my files that is autosourced normally perhaps but I am not sure how to find out.

**Comment by faho** [comment] 2015-12-12 17:02
That's the command-not-found-handler. See `type __fish_command_not_found_handler` for the definition of the current one (after the current shell has failed one command unfortunately).

The exact one depends on your operating system, which we try to detect on startup - which are you using? It seems this one somehow executes bash and then fails miserably.

If you wish to disable the feature completely, add an empty __fish_command_not_found_handler function to your setup (e.g. config.fish). `function __fish_command_not_found_handler; end` should do.

**Comment by faho** [comment] 2015-12-12 17:04
(Oh, also fish offers the `-d NUMBER` commandline argument, so you could try `fish -d 3`, though that's a bit verbose for my taste, and lower numbers don't output enough.

**Comment by ridiculousfish** [comment] 2015-12-12 20:14
@shevegen What is your operating system?

**Comment by zanchey** [comment] 2015-12-13 12:58
My suspicion is that this is a duplicate of #1918, because Fedora's command-not-found handler used to only print `bash`.

**Comment by faho** [comment] 2015-12-13 13:11
@zanchey: And you mentioned there that it now assumes the running shell is the login shell, so if @shevegen still has bash as the login shell even the newer versions would still mention bash.

**Comment by faho** [comment] 2015-12-24 23:40
@shevegen: Anything more we can help you with here?

**Comment by faho** [comment] 2015-12-30 18:39
All information I can think of has been given so I'm closing this.

If there's anything else, feel free to ask.

**Closed by faho** 2015-12-30 18:39 UTC
Labels: question
