### ISSUE TITLE
Emoji break fish

### ISSUE THREAD

**Issue by YaLTeR** [fish-shell/fish-shell#3887] opened 2017-03-10 07:43 UTC
fish 2.5.0, Arch Linux, Termite

Writing an emoji (for example '😀') through fish, whether by pasting it, printing in left/right prompts or having fish try to display it in autocomplete suggestion, messes up the spacing a lot. It's especially bad when combined with multi-line prompts.

[Asciinema recording showcasing the issue](https://asciinema.org/a/32kckggi8jyswynye71ieospc).

Doesn't happen with bash.

How to reproduce: do `echo 😀`. If you have a multi-line prompt that's enough. Otherwise try typing `echo` again to have the autocompletion attempt to display a '😀'.

**Comment by faho** [comment] 2017-03-10 10:09
This is the same thing as #3886, which I have just closed as a duplicate of #2652.

**Closed by faho** 2017-03-10 10:09 UTC
