### ISSUE TITLE
Disable history for the current session

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#2376] opened 2015-09-10 22:19 UTC
I realise that preceding a command with one or more space characters causes it to not be written to history, but I was wondering if there was a way to temporarily disable history for an entire session? From time to time, I need to repeatedly enter sensitive data (e.g customers' passwords) and it's cumbersome to constantly hit space before each command.

In `bash`, I'd simply just `unset HISTFILE` -- how would I do this in `fish`, if it's at all possible?

**Comment by zanchey** [comment] 2015-09-11 09:29
It's not possible easily (you can do some magic with `fish_prompt` by adding `commandline " "` to the prompt) - see #1156. I'm going to close as a duplicate of that for now.

**Closed by zanchey** 2015-09-11 09:29 UTC
Labels: duplicate

**Comment by Qix-** [comment] 2018-12-17 21:52
Since this is the first issue I could find in google, functionality _was_ implemented (if you follow the chain of linked issues):

I'm new to Fish so let me know if the following isn't correct, but you have to set `FISH_HISTFILE` to an empty string to stop recording commands (or set it to another file if you want to record history elsewhere).

```fish
set FISH_HISTFILE ""
```

**Comment by UnicodeAlt255** [comment] 2019-06-28 21:13
For the googlers: https://github.com/fish-shell/fish-shell/issues/102#issuecomment-371323607

The above comment is no longer correct.

Use `fish --private`.

**Comment by myrdd** [comment] 2019-06-30 11:50
> Use `fish --private`.

available since fish v3.0.  
documented here: https://fishshell.com/docs/current/#private-mode

not documented in the manpage yet. (https://github.com/fish-shell/fish-shell/blob/master/sphinx_doc_src/cmds/fish.rst)
