### ISSUE TITLE
Fish crashes on a specific command

### ISSUE THREAD

**Issue by mooskagh** [fish-shell/fish-shell#7687] opened 2021-02-07 08:44 UTC
I've just found a command that crashes fish for me. Here it is (note that I mistakenly redirected output to the directory, pressed enter too early).
Here it is:

`$ perl -e "print 42;" | cat - > /tmp/`

Fish version: 3.1.2.

Reproducible in all terminal emulators that I tried (alacritty, kitty, terminator, xterm).
If fish is run as a root process of the emulator, it crashes when running this command and the emulator closes. If it's run as a child process (e.g. running from bash), it hangs.

It's also reproducible with all customizations off.

**Comment by faho** [comment] 2021-02-07 08:49
Duplicate of #7517

**Closed by faho** 2021-02-07 08:49 UTC
