### ISSUE TITLE
Like wildcards: support sets as known from regular expressions

### ISSUE THREAD

**Issue by thfi** [fish-shell/fish-shell#2661] opened 2016-01-07 09:49 UTC
In addition to the generic wildcards and just like Bash and regular expressions, Fish should support _sets_ for filenames.
Example: `201[456]` should match `2014`, `2015`, and `2016`, but not `2013` or `2009`.

**Comment by krader1961** [comment] 2016-01-08 02:32
While I'm in favor of implementing this feature I have to ask: Where do we stop? This is an area that requires extreme caution and deliberation lest fish turn into zsh.

Consider the capabilities provided by zsh in the "FILENAME GENERATION" section of `man zshexpn`. In the functions shipped with zsh you'll find bogosities based on that rich syntax that would horrify a Perl language aficionado (a language whose detractors liken to "RS-232 line noise").

**Comment by ridiculousfish** [comment] 2016-01-08 02:41
If we were to do this, it would have to be part of a `glob` command or something. We don't want to make all brackets into wildcards.

**Comment by oranja** [comment] 2016-01-17 08:47
:+1:
I'm with @krader1961 on not getting carried away.

Both `201{3,4,5}` and `201(seq 3 5)` will match exactly the same as the proposed regular expression (`201[345]`). I don't see the benefit here.

@thfi  Perhaps other examples will provide a stronger case?

**Comment by faho** [comment] 2016-01-17 11:15
>Both 201{3,4,5} and 201(seq 3 5) will match exactly the same as the proposed regular expression (201[345]). I don't see the benefit here.

If I understand this correctly, it's a glob. In other words, that means that `201[345]` will expand to any of `2013`, `2014` and `2015` that are valid as files.

That means it should be possible to do this with a `filter_files` function that returns all input that is a valid filename.

**Comment by oranja** [comment] 2016-01-17 11:42
I think I get it now. So more or less a simplified:
```fish
basename -a (find -maxdepth 1 -regex '\./201[345]')
```

Sounds legit to implement such functionality in a  `glob`/`filter_files` Fish function.

**Comment by thfi** [comment] 2016-01-17 18:49
> Both `201{3,4,5}` and `201(seq 3 5)` will match exactly the same
> as the proposed regular expression (`201[345]`).

Yes, by result, all three alternatives are identical. The `seq` solution is maybe worst, as it requires forking/launching an external program.
As I do not require or request more complex regular expressions like `[0-5]+`, maybe it is sufficient to accept simple sets like `[345]` as a condensed alternative to `{3,4,5}`. Without knowing the internals of fish-shell, I'd assume that even a simple pre-processor could handle this transformation.

> I don't see the benefit here.

For someone who is used to Bash and regular expressions, writing `[345]` is both quicker and more intuitve than `{3,4,5}`.

**Comment by krader1961** [comment] 2016-01-17 21:06
Well, fish isn't bash or zsh and quite explicitly is not intended to be compatible with them. So find the argument from familiarity to be a weak argument. Nonetheless, a little more flexibility would be nice. Whatever we do to address this specific request should also accommodate issue #2680.

**Comment by faho** [comment] 2016-01-18 10:36
>As I do not require or request more complex regular expressions like [0-5]+, maybe it is sufficient to accept simple sets like [345] as a condensed alternative to {3,4,5}.

That actually sounds worse than how I interpreted it - preferably, there'd be one way to do this stuff. If there's more than one there's more to learn, more potential for confusion and more characters that are reserved and therefore need to be escaped if they are to be interpreted literally.

Currently, there's one case where "[1]" may be interpreted by fish in a non-literal manner, and that's if it is preceded by "$" and a valid variable name, in which case it is seen as a list index.

That trade-off doesn't sound good for one character per-element (and the `seq` way gets shorter the longer your list of allowable characters becomes).

Plus, that's not actually how bash behaves - bash treats `[345]` as a glob, meaning it will try to match filenames. Though bash, like with "*" will let the uninterpreted glob through if there is no match. That means e.g. `echo foo[345]` will print any combination of `foo3`, `foo4` and `foo5` if any of those exist and `foo[345]` otherwise.

> For someone who is used to Bash and regular expressions, writing [345] is both quicker and more intuitve than {3,4,5}.

Bash knows both, and having used bash for years, I've not used the former.

In summation: We should consider this for some other way of generating filenames (a `glob` builtin like @ridiculousfish has proposed), but the syntax itself does not seem to be a good idea IMHO.

**Comment by faho** [comment] 2016-04-04 18:40
This is a duplicate of #839.

**Closed by faho** 2016-04-04 18:40 UTC
Labels: enhancement, posix-me-harder
