### ISSUE TITLE
tab completion with combiners

### ISSUE THREAD

**Issue by wprater** [fish-shell/fish-shell#2025] opened 2015-04-12 01:22 UTC
currently there is no tab completion support while using combiners `cd foo ;and cmd <wants completion>`

**Comment by ridiculousfish** [comment] 2015-04-12 01:39
I wasn't able to reproduce this. I tried `cd foo; and grep --<tab>` and saw grep completions. What version of fish are you testing on, on what OS? Can you give steps to reproduce?

**Comment by wprater** [comment] 2015-04-12 02:22
its was with git commands.  should have used that example. `⟩ git checkout dev-wprater ;and git checkout  <tab>` should list branches (lists dir contents) and `git checkout dev-wprater ;and git ch<tab>` should suggest `checkout`

version 2.1.2 on OS X.

**Comment by ridiculousfish** [comment] 2015-04-12 02:27
Thanks. It may be a bug in the `commandline` builtin.

**Comment by JelteF** [comment] 2015-05-08 15:04
The same is the case for the `service` command, so it could very well be a bug in the `commandline` builtin. It probably counts `and` and `or` as commands as well.

**Comment by zanchey** [comment] 2015-05-26 09:46
`commandline -opc` in these instances returns `and git`.

**Comment by faho** [comment] 2015-08-05 19:04
I can reproduce it with git in current master, but not with #2145, so a change there seems to have affected it.

**Comment by faho** [comment] 2015-08-17 10:17
Okay, the line that should cause this issue:

```fish
if [ (count $cmd) -eq 1 -a $cmd[1] = 'git' ] 
```

It re-checks that the command is really git - which is stupid since fish is already certain it's git since it looked up the git completions. This should also break wrappers (e.g. "hub").

Just removing it (which I've done in #2145) is the correct solution and should be done for every single completion script that uses it.

**Comment by faho** [comment] 2015-08-17 10:21
Of course the proper solution would be to actually check if it has a command instead of just looking up commandline-length (i.e. `not __fish_seen_subcommand_from $commands`).

**Comment by faho** [comment] 2015-08-17 10:31
I've pushed the simple solution in 5e555fc1cfca001e689dc2598d0395472d8c6f4a as I'm uncomfortable with touching completions I can't test (like brew) beyond the minimum.

I believe this is now fixed (except for git, which is in #2145). If anyone pushes a completion that breaks it, please yell as loud as you can (get a megaphone or something).

**Closed by faho** 2015-08-17 10:31 UTC
