### ISSUE TITLE
Glitch while typing (showing unwanted chars in random places)

### ISSUE THREAD

**Issue by thomiaditya** [fish-shell/fish-shell#8733] opened 2022-02-16 02:22 UTC
Hello there,

I'm experiencing a glitch while typing in the prompt. It keeps showing me character like either 'l' or 'h' in random places.

![image](https://user-images.githubusercontent.com/18701474/154183964-36b1d29a-3757-40bb-a42d-6dd13e2b809e.png)
![image](https://user-images.githubusercontent.com/18701474/154184093-806625be-1a78-4fdd-beaf-0d8dd44478ed.png)
Is it a bug or just me?

Im using fish shell version 3.3.1.

Thanks.

**Comment by faho** [comment] 2022-02-16 06:35
Duplicate of #8714

**Closed by faho** 2022-02-16 06:35 UTC

**Comment by thomiaditya** [comment] 2022-02-17 06:54
Ok thanks.
