### ISSUE TITLE
Terminator + vi mode = odd character in prompt

### ISSUE THREAD

**Issue by LindyBalboa** [fish-shell/fish-shell#3647] opened 2016-12-14 14:26 UTC
Arch linux up to date, fish 2.4.0, terminator 1.0

When switching to vi mode I get an odd character inserted before the prompt, but is not controlled by the prompt. It shows up after the call to ``fish_vi_cursor``.

![image](https://cloud.githubusercontent.com/assets/20605205/21185620/b8de95b2-c211-11e6-8c5e-f794cc681ecd.png)

![image](https://cloud.githubusercontent.com/assets/20605205/21185647/d70b75a0-c211-11e6-8ea5-3acaeef30a09.png)

**Comment by faho** [comment] 2016-12-14 14:53
This is a duplicate of #3535, which is already fixed in git. Sorry for the inconvenience.

**Closed by faho** 2016-12-14 14:53 UTC
