### ISSUE TITLE
killall autocompletion errors out if killall does not exist

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#4252] opened 2017-07-27 00:10 UTC
```
[root@/s/x [130]]fish --version
fish, version 2.6.0
[root@/s/x]uname -a
Linux example 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```

The error message appears once I type the space after the `killall`. It happens with a clean fish config as well:
```
[root@/s/x]killall fish: Unknown command 'killall'
/usr/share/fish/completions/killall.fish (line 24): 
if killall --version >/dev/null ^/dev/null # GNU
   ^
from sourcing file /usr/share/fish/completions/killall.fish
	called on standard input

in command substitution
	called on standard input

```

**Comment by krader1961** [comment] 2017-07-27 00:19
Duplicate of #2365.

**Closed by krader1961** 2017-07-27 00:19 UTC
Labels: duplicate
