### ISSUE TITLE
unicode \u23CE ⏎ character preceding every prompt in ConEmu

### ISSUE THREAD

**Issue by samvasko** [fish-shell/fish-shell#789] opened 2013-05-20 19:09 UTC
Everytime I run fish using ssh from cmd on windows. I get this character at the end.
⏎
In cmd it just looks like crossed box. Not sure if that is bug on your side, but can you help with some workaround?

**Comment by Maximus5** [comment] 2016-03-16 22:14
When I'm trying to run fish, it shows the `?` even **before first prompt**. And before each next prompt of course... It's unclear to me, why fish shows it, what "output from a command" do you mean?

![2016-03-16_18-35-28](https://cloud.githubusercontent.com/assets/1222388/13830343/1850cbe8-ebdd-11e5-88b3-7765eeaaae6f.png)

**Comment by krader1961** [comment] 2016-03-16 22:51
What OS are you running fish on? How are you connecting to that fish shell?

"Output from command" means just that, the output from the most recent command that was run. For example, consider the difference between `echo hello` and `echo -n hello`. The latter will cause fish to include the down-left-arrow (aka carriage-return) symbol to the output while the former will not.

As for why you're seeing that before the first prompt I can only guess. A likely explanation is something in your config.fish is writing to the terminal without terminating the output with a newline.

**Comment by Maximus5** [comment] 2016-03-16 23:07
Where the `config.fish` may be located? There is no such file in my cygwin's /home. Also, I did not configure anything special for fish, just "installed" via cygwin setup.

OS: Windows 8, Windows 8.1 x64.
Fish.exe from latest cygwin x86.

I run `t:\cygwin\bin\fish.exe -l -i` directly from `Win+R`.
Also, the screenshot was created when almost the same command was started inside ConEmu.
If you are interested about strange `/fish_shmem_1049690: Permission denied` - that happens every time few hours before, but is not reproduced ATM.

**Comment by Maximus5** [comment] 2016-03-16 23:14
OK, just found two `config.fish` files and append simple echo to the end of each. Get the following:

![2016-03-17_02-12-29](https://cloud.githubusercontent.com/assets/1222388/13831587/d6dce760-ebe5-11e5-9358-9577b8e8ae8d.png)

So, I suppose the problem is inside fish's prompt setting. How it is configured?

**Comment by krader1961** [comment] 2016-03-16 23:29
The easiest way to configure things like the prompt is to run the `fish_config` command. Once you have more experience you can create a **fish_prompt** function to have total control over the prompt.

Also, you're last screen capture appears to have a simple question-mark whereas your earlier one had the glyph that is typically displayed for characters (technically "code points") that aren't valid for the font you're using. That may or may not be due to fish emitting the carriage-return code point. Which means what you're seeing may or may not be the same thing as was originally reported in this issue.

**Comment by Maximus5** [comment] 2016-03-17 00:06
Previous screenshot was taken from ConEmu, which utilizes TrueType font. Last one - is bare Windows console with non-unicode raster font. That is the reason of the difference.

**Comment by eugenesvk** [comment] 2016-03-17 00:19
I have the same issue with a blank prompt (i.e. a **fish_prompt** function that outputs one symbol with `echo "symbol"` (see screenshot https://github.com/Maximus5/ConEmu/issues/586#issuecomment-197388965)).
It would be nice to have an option to turn that extra carriage return off. I understand I might have an "ugly prompt" starting from the same line as the output of the last command if that command doesn't have a return symbol on its own, but I'm totally fine with it, it's much better than constantly having an extra symbol on each prompt drawing.
Fish is my favorite shell and would be nice if I could also use it on Windows Msys2 without this visual artifact.

**Comment by Maximus5** [comment] 2016-03-17 08:58
Some more info. Fish prints a lot of "hidden" data to console. Here is [raw log file](https://gist.github.com/Maximus5/bca0f294262a084e7720) and actual screenshot:

![2016-03-17_11-47-00](https://cloud.githubusercontent.com/assets/1222388/13840968/193b5d8e-ec37-11e5-8e42-f8597600ebd7.png)

So, after executing the command typed in prompt (`echo "***"`) fish prints the following (ESC symbols - `\e`)

~~~
\e]0;fish  /home/Max\e[30m\e(B\e[m\e[38;5;245m⏎\e[0m                                                                                                                                                                                           
 
\e[32m~\e[30m\e(B\e[m $ \e[30m\e(B\e[m\e[K
~~~

WTF?

**Comment by krader1961** [comment] 2016-03-17 18:55
@Maximus5: Those are [ANSI X3.64](https://en.wikipedia.org/wiki/ANSI_escape_code) escape sequences to do things like set the foreground and background colors of the characters in the fish prompt. Nothing at all unusual about that. That's been the standard way of doing such things for several decades.

**Comment by Maximus5** [comment] 2016-03-17 19:30
@krader1961 

1) These are not ANSI escape sequences. These are a character U+23CE (`⏎`).

![2016-03-17_22-19-04](https://cloud.githubusercontent.com/assets/1222388/13858207/ab7048fc-ec8e-11e5-9d6c-d8db3e789835.png)

2) That's rather strange to print **invisible** text for several decades, do you really need this overhead? However that is not the mentioned problem of course.

![2016-03-17_22-28-53](https://cloud.githubusercontent.com/assets/1222388/13858469/de396c7c-ec8f-11e5-8eb4-8f2fd9f99105.png)

**Comment by krader1961** [comment] 2016-03-17 19:46
The \u23CE character is the unicode carriage-return mentioned earlier. It's defined in *src/common.cpp*:

```
omitted_newline_char = (wcwidth(L'\x23CE') > 0) ? L'\x23CE' : L'~';
```

It's what fish prints (along with a newline char) just before a prompt. Unfortunately, it always does so using a complex sequence of escape sequences that should leave it only visible if the last char previously output was not a newline. That mechanism is obviously not compatible with whatever ConEmu is doing with those escape sequences.

A bit of searching shows this has been reported at least two more times in issue #1071 and issue #2092. I'll review all three and keep the one with the clearest description of the issue open and close the other two as duplicates.

**Comment by ridiculousfish** [comment] 2016-03-17 19:51
We should check to see if zsh has the same issue on ConEmu. If not, figure out why not.

**Comment by eugenesvk** [comment] 2016-03-17 20:06
@ridiculousfish 
zsh has a similar issue — see my link above, although it displays a `%` percent sign instead of a carriage return.

**Comment by Maximus5** [comment] 2016-03-17 20:37
\u23CE is **not** a carriage return

> 23CE ⏎ [RETURN SYMBOL](http://www.unicode.org/charts/PDF/U2300.pdf)
>  • may be **shown** with either hollow or filled glyph

So, it is **visible** glyph corresponding to control character. And it is improperly to use this **glyph** instead of **control character**. Or, do you mean that fish want to show this **glyph** instead of do `carriage return`?

**Comment by ridiculousfish** [comment] 2016-03-17 20:45
@Maximus5 fish outputs both a ⏎ and a carriage return. It does it in a way that the ⏎ is only visible if there are trailing characters on the last line of output of the previous command. This is not something it can check directly, so it uses a trick (borrowed from zsh). The issue is that ConEmu is incompatible with the trick; I don't understand why yet.

**Comment by Maximus5** [comment] 2016-03-17 20:55
Trying to build fish from sources. Failed to configure

~~~
/c/src/fish-shell $ autoconf                                                  
cut: FISH-BUILD-VERSION-FILE: No such file or directory     
                                                            
/c/src/fish-shell $ ./configure                                               
configure: error: cannot find sources (fish) in . or ..     
~~~

What is going wrong?

**Comment by eugenesvk** [comment] 2016-03-17 21:07
@Maximus5
Not sure about Cygwin if that's what you're using, but you can relatively easily build it in MSys2 with a simple patch at https://github.com/Alexpux/MSYS2-packages/tree/master/fish. You'd have to 
1. slightly modify the `PKGBUILD` to use a manually downloaded source instead of the hard-coded links
2. change one mistake in variable declaration 
(note this issue https://github.com/Alexpux/MSYS2-packages/issues/204 and https://github.com/fish-shell/fish-shell/issues/2821#issuecomment-198064421)
3. maybe install a couple of additional packages if you get a "missing" error during build (don't remember if I got any)
**NB** don't forget to `pacman -S base-devel` in MSys2 before you try to build.

**Comment by krader1961** [comment] 2016-03-17 21:29
> \u23CE is not a carriage return... it is visible glyph

Yes, @Maximus5, I am well aware of that :-) I apologize that my previous comments where I say things like "down-left-arrow (aka carriage-return) symbol" weren't sufficiently clear on that point. But since we're being pedantic \u23CE is not a glyph. It is a code point. The specific glyph displayed is a function of the font.

Others have reported this also occurs with the MS-Windows Console2 and ConsoleZ terminal emulators.

**Comment by krader1961** [comment] 2016-04-07 19:17
FWIW, I have a hunch this symptom has the same root cause as the symptom described in issues #2859 and #2003.

**Comment by krader1961** [comment] 2016-04-07 20:09
I propose an experiment: build fish without the code that writes the char sequence that attempts to ensure the prompt never overwrites output that does not end with a newline. I'm happy to write a patch but someone else will have to compile and test it since I don't have a MS Windows machine setup for development.

Obviously that isn't the ideal long term solution but it would bring relief for Windows users.

**Comment by eugenesvk** [comment] 2016-04-07 20:57
@krader1961
I'd be happy to test the patch. I'd even accept it as the permanent solution since I don't really mind very rare cases when prompt doesn't get to a new line — it beats the current situation when fish is unusable outside of Mintty. The tradeoff is pretty obvious.

**Comment by krader1961** [comment] 2016-04-10 02:23
FWIW, my most recent comment was really targeted at issue #2859 and should have been reworded when I pasted it into this issue. My proposed change would obviously resolve this symptom. My hope was that removing the code that causes this symptom would also resolve issue #2859. Initial testing by @barksdml suggests that is not the case.

The only `$TERM` value I can find documented in the issues that document this problem has been `cygwin`. Perhaps we should simply special-case that value to inhibit the magic emitting of the \u23CE character.

**Comment by eugenesvk** [comment] 2016-10-25 22:53
@krader1961 just wanted to check if there is any news on the patch or another fix for this?
I'd also add that whenever I have a right prompt showing up (even if it's something as simple as `echo "1"` ) I get this issue https://github.com/fish-shell/fish-shell/issues/2859. When right prompt is not showing anything, then I only get the extra carriage return. Not sure if the right prompt is connected to this or a separate issue, though

**Comment by MicahZoltu** [comment] 2016-11-13 20:36
Is there a workaround for this for regular users?  I'm running `fish` on `cygwin` on `ConEMU` and getting this behavior.  I'm no expert in all of this stuff, so compiling my own anything probably isn't a realistic option.  I'm hoping for some setting I can set somewhere, or a config file I can edit?

**Comment by skrysmanski** [comment] 2016-11-28 10:39
So, I'm running into the same problem but in my case I'm running fish on a Ubuntu machine (not in cygwin) and accessing it via ssh (through the ssh executable that comes with Git for Windows). It then doesn't matter whether I use ConEmu or the regular Windows console - I'm always getting this symbol.

**Comment by Maximus5** [comment] 2016-11-28 14:02
Exactly what I'm takin about: it's a **question for fish author** why fish constantly prints unexpected character before prompt.

**Comment by krader1961** [comment] 2016-11-29 03:06
The problem, @skrysmanski and @Maximus5, is that the MS Windows terminal emulators don't behave like every other terminal emulator. Even if we replaced the U+23CE character with a regular ASCII character (e.g., `%`) it would still be displayed. Also, I am not seeing this problem when I run fish inside a Cygwin ConEmu terminal. What needs to be determined is why only some people are seeing this behavior and what, if anything, fish can do to workaround the quirk short of special-casing TERM=cygwin to disable the mechanism for indicating the output of the previous command did not end with a newline.

I don't use MS Windows except when investigating problems like this. So I personally don't have any interest in spending lots of time on this issue. I've already spent on the order of 20 hours working on Windows specific problems in the past year. Someone who is affected by this will need to help.

**Comment by Maximus5** [comment] 2016-11-29 13:58
@krader1961 The question is why fish needs to output the character? It doesn't matter what exactly - U+23CE or %. I don't believe that other terminals don't display it, it's more probably that fish doesn't print it in other terminals.

**Comment by doxxx** [comment] 2016-11-29 15:36
Here's another interesting tidbit of information: Running fish in the Windows Subsystem for Linux in Windows 10 (aka `bash.exe`) _doesn't_ display this extra character. Like ConEmu and cmd.exe but unlike mintty, this is an actual console -- it has a conhost.exe child process. My suspicion is that Microsoft has done extra work to ensure that ANSI sequences work correctly in this console like they would in a Linux terminal. Judging from [this SuperUser answer](http://superuser.com/a/1050078/78821), it's something new in Windows 10 that has to be explicitly enabled for console applications with Windows API calls.

**Comment by Maximus5** [comment] 2016-11-29 16:01
WSL works absolutely differently in comparison with native Windows console binaries. It's not fair to compare with it, WSL doesn't use Windows API and conhost.exe works in some weird, unusual and obfuscated way.

**Comment by faho** [comment] 2016-11-29 16:18
>The question is why fish needs to output the character?

Fish outputs that character to show you that the previous output did not end with a newline.

>I don't believe that other terminals don't display it, it's more probably that fish doesn't print it in other terminals.

It does. Feel free to confirm this yourself.

**Comment by doxxx** [comment] 2016-11-29 16:50
@Maximus5 Does ConEmu enable virtual terminal processing in its console as described [here](https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx)?

**Comment by doxxx** [comment] 2016-11-29 16:55
This is an interesting comment regarding cmd.exe's handling of ANSI in Windows 10 Anniversary Update: https://github.com/Microsoft/BashOnWindows/issues/1173#issuecomment-254250445

**Comment by Maximus5** [comment] 2016-11-29 17:32
ConEmu does not disable the feature. Moreover, ANSI is not received by ConEmu as noted I several issues already. They are processes internally by Windows and Ubuntu cores.

**Comment by doxxx** [comment] 2016-11-29 18:10
The way I read those issues and the documentation, the VT feature has to be explicitly enabled by a console application. It's not enabled by default. The Windows 10 cmd.exe normally has the feature enabled (so builtin echo commands with escape sequences work as expected) but disables it before launching a child process, for vague compatibility reasons. Thus cygwin fish in both ConEmu and cmd.exe can display color but cannot use more advanced ANSI VT sequences.

**Comment by krader1961** [comment] 2016-12-04 03:27
Silly me. I just assumed I was using ConEmu. I didn't realize that stock Cygwin uses Mintty. That's why I didn't see the problem. I installed ConEmu from [here](https://www.fosshub.com/ConEmu.html) and immediately saw the problem. Note that Mintty exports TERM=xterm while ConEmu exports TERM=cygwin.

@ridiculousfish, @faho, @zanchey, @floam: How do you feel about simply disabling this feature if TERM=cygwin? It's not clear that a) we'll ever get root cause or b) that even if we do we'll be able to workaround the problem. It looks to me like a shortcoming of ConEmu. Do we want to special-case that environment? Doing so sets a precedent that can be expanded in scope if people using other incompatible terminal emulators complain.

**Comment by krader1961** [comment] 2016-12-17 05:11
So the question still remains whether we should special-case TERM=cygwin; i.e., the ConEmu terminal used by some people with Cygwin on MS Windows. I am ambivalent. This issue has been open 3.5 years and ConEmu still does not correctly handle what fish does while Mintty, the stock terminal for Cygwin, does. I vote we close this "will-not-fix" in two weeks unless someone makes a convincing argument for why we should work around this ConEmu quirk.

**Comment by Maximus5** [comment] 2016-12-17 10:39
It's not correct to say "ConEmu quirk".

* You are writing console application, which is expected to be working in the standard console on the selected OS. Well, you do not use Windows, but a lot of people do.
* Next, cygwin provides a translation layer which allows to almost seamlessly recompile "native unix" applications to run them in Windows.
* So they are expected to run properly in Windows.

When people say "it works in mintty" that sounds like

> - The "Prince of Persia" (1989 video game) does not work on my PC!
> - It's working, just run it in DosBox.

Yeah, but it would not be Windows application after that.
Well, another example

> - [RPP](http://www.raw-photo-processor.com/RPP/Overview.html) does not work on my PC!
> - It's working, just install MacOS.

Bottom line. I believe that applications, compiled for Windows, must work in Windows without third party emulators of anything. mintty is the emulator. But ConEmu is biult on real Windows console, and when something is not working in ConEmu, **it is not working in native Windows console too**: https://github.com/fish-shell/fish-shell/issues/789#issuecomment-197598281

-----

As for your suggestion about `TERM=cygwin`, it's bad approach. [Previous examples](https://github.com/fish-shell/fish-shell/issues/789#issuecomment-198047270) were obtained when `TERM=xterm` or `TERM=xterm-256color` using [cygwin connector](https://conemu.github.io/en/CygwinMsysConnector.html). As you can see, the character `⏎` is printer even **before** any command executed from prompt, just after fish startup.

Still not enough arguments?

**Comment by skrysmanski** [comment] 2016-12-17 10:47
Why not just make this behavior configurable in fish? In my opinion, this would be the only clean solution - because Linux and Windows terminals are apparently incompatible in this case (and thus it's neither the "fault" of fish nor of ConEmu/Windows).

**Comment by faho** [comment] 2016-12-17 11:24
>when something is not working in ConEmu, it is not working in native Windows console too:

That's kinda irrelevant for fish, since fish (AFAIK) isn't a windows application, it needs cygwin (or WSL) to run in windows. So the standard cygwin console is the standard there.

>It's not correct to say "ConEmu quirk".

It doesn't matter what we call it. What matters is what we do.

Anyway, let me try to summarize:

When you use certain terminals, you'll get an annoying character every command because they behave differently than what we expect.

This set of terminals is rather limited - most terminals don't show the character.

So, we should either change those terminals to behave like others, or we should detect them and disable that behavior on our end.

This leaves these questions:

- Which terminals are we talking about? Is it really just ConEmu?

- Can we change those terminals?

- If we cannot, how do we detect them?

@Maximus5: You're the ConEmu maintainer, right? Would you be willing to bring ConEmu's behavior in line with what seems like the majority of terminals? It's an issue with at least fish and zsh.

If you can't or won't, how do you suggest we detect that we are running in ConEmu? So far it seemed like it's the only terminal that sets TERM=cygwin, but you suggest that it might also be running with TERM=xterm. Do you set a variable $CONEMU_VERSION or something?

Or do you have another suggestion for what we should do? Note that we don't want to abolish the behavior entirely.

>Why not just make this behavior configurable in fish?

That would be nigh-indiscoverable. Say we added a variable "$fish_print_return". The only way you'd know it existed is if you trawled through the documentation and found e.g. an FAQ entry that said "if you're having problems, set this thing to 0". In which case, why don't we just set it?

We try not to add configuration if we can just do the right thing, so this should be a very last resort.

**Comment by skrysmanski** [comment] 2016-12-17 11:30
@faho 

> That's kinda irrelevant for fish, since fish (AFAIK) isn't a windows application, it needs cygwin (or WSL) to run in windows. 

That's not true. You can ssh into a Linux box from the Windows command line (window) and still get this weird output.

The problem is that fish is expecting some behavior from the terminal that the Windows Console Host (and thus ConEmu) doesn't support.

**Comment by faho** [comment] 2016-12-17 11:40
@skrysmanski: Thanks for the clarification! Anyway, that means it's at least two terminals, and it's also when fish wasn't compiled for windows.

The ssh-case is also another argument against configuration, since your ssh-host might also be connected to with other operating systems and terminals. So if we did this via a variable you would need to export it on the client and accept it on the host (ssh only accepts a configurable set of environment variables from the client).

So, how do we detect both of those terminals? It's unlikely that Microsoft is gonna fix the Windows Console Host (I don't think they've worked on that for a couple of years, and even if they did it would only be released for Windows 10).

**Comment by Maximus5** [comment] 2016-12-17 13:54
Sure, I'm the ConEmu maintainer. But unfortunately I still don't understand what "wrong behavior" you are talking about.
When this becomes clear to me, I'll either implement a fix for ConEmu or suggest a workaround for fish.

**Comment by faho** [comment] 2016-12-17 14:34
The trick is in https://github.com/fish-shell/fish-shell/blob/master/src/screen.cpp#L1189-L1236, and it works like this:

After a command has finished, before printing the prompt or anything else, we print a newline symbol (\u23CE, unless that can't be encoded), and then (screenwidth - width of the newline symbol) spaces. If there was anything in the line, this should leave us wrapped in the next line. If there wasn't (because the last thing printed was a newline), this should leave us right at the end of it.

Then we print \r and enough spaces to overwrite the newline symbol, another \r and the \x1b[2K sequence to clear the line (dunno why that latter one is necessary).

There's a couple of things that can go wrong here - character (or glyph or whatever) width might be off, the screen width we get might be, or (most likely) printing more than screen width doesn't wrap to the next line.

Is that enough to go on?

**Comment by Maximus5** [comment] 2016-12-17 15:43
Yes, now I understand the fish behavior and most probably fix the issue with connector.
But when users do not use connector+ConEmu and run fish/ssh in native Windows console, the issue would remain.

To clarify the difference

> If there wasn't (because the last thing printed was a newline), this should leave us right at the end of it.

In Windows console, for example 80 cells wide, the cursor can't be placed at position 80 (0-based), it immediately goes to the next line.
In Unix consoles (mintty mimics this behavior) the cursor goes next line only when next character is printed.

ConEmu tries to emulate Unix behavior under certain conditions, and after some tuning it might be working as expected.

**Comment by krader1961** [comment] 2016-12-17 17:01
> You can ssh into a Linux box from the Windows command line (window) and still get this weird output.

@samvasko: Are you referring to the native MS Windows cmd.exe terminal? I was under the impression that Windows users who don't use Cygwin use PuTTY as their ssh client. What console program does it use and does it have this display quirk? I though PuTTY claims to emulate xterm and thus sets TERM=xterm. 

If someone is using ssh from ConEmu we would still detect this via TERM=cygwin and disable the feature (assuming @Maximus5 doesn't alter ConEmu to work like most UNIX terminals).

**Comment by doxxx** [comment] 2016-12-17 21:44
PuTTY does not use the Windows console system. It emulates xterm itself. When I SSH to a Linux box using PuTTY and use fish, I don't see the problem described in this issue.

**Comment by krader1961** [comment] 2016-12-17 22:42
@Maximus5: How exactly would a user "run fish/ssh in native Windows console"? Fish is not a native windows app. It requires Cygwin (or WSL which does not exhibit this problem). Can you even run Cygwin based programs inside the native Windows console? Even if you can does anyone do so? As far as I can tell people are either using Mintty (which doesn't exhibit the problem) or ConEmu.

Also, when I said "ConEmu quirk" I did not mean that in a pejorative way. Only that ConEmu behaves different from the other DEC VTxxx and ANSI x3.64 based terminals that are by far the most commonly used for interacting with UNIX console apps. The current ConEmu behavior may make perfect sense for MS Windows apps. But it seems to me that when running the Cygwin environment its behavior should match that of all the other terminals used in the UNIX world. If that isn't feasible we can special-case it within fish to avoid the non-standard behavior. It looks to me like testing whether TERM=cygwin is the simplest way to do that. If there is a better way to detect that we're running inside ConEmu just tell us what that is.

**Comment by Maximus5** [comment] 2016-12-18 08:41
@krader1961 Do you know what is Windows executable? PE format? `.exe` files?

fish/bash/ssh and dozens of other utilities provided by cygwin certainly can by executed in native Windows console. Why do you think they can't?

Yes, they requires Cygwin, but you give wrong meaning to these words!
Cygwin is not a mintty! Cygwin is a "translation layer" which is cygwin.dll and a large set of Windows executables.

Easiest way to check: `Win+R`, type full path to `fish.exe`, press `Enter`.

**Comment by Maximus5** [comment] 2016-12-18 08:43
Obviously, if cygwin/bin is appended to the PATH, user may run all cygwin's utilities (and fish) even from `cmd.exe` or `PowerShell.exe`.

**Comment by floam** [comment] 2016-12-18 16:40
@Maximus5 So, what's the right way for us to detect we're running in a cmd.exe thing that will not be able to accomodate our trick?

Have you figured out how to make ConEmu compatible?

**Comment by floam** [comment] 2016-12-18 16:41
Also, Microsoft, I believe, massively improved their command prompt post-WSL. It handles all kinds of ANSI escapes now. Does this issue still exist there?

**Comment by doxxx** [comment] 2016-12-18 18:01
As I mentioned earlier, the improved ANSI support in a Windows console
application needs to be explicitly enabled with a Windows API call. `cmd`
enables it by default _but_ disables it before launching subprocesses for
backwards compatibility.

**Comment by floam** [comment] 2016-12-18 18:09
Sorry, I had read past that.

**Comment by krader1961** [comment] 2016-12-19 04:18
@Maximus5 you said

> Easiest way to check: Win+R, type full path to fish.exe, press Enter.

I do not understand how the fish shell would do that to detect it is running inside a MS Windows console. Especially if someone executes a command like `ssh $hostname` within that shell. How would the fish shell running on `$hostname` know that the terminal does not behave like most terminals used by fish users? The usual manner is environment variables like `$TERM`.

**Comment by floam** [comment] 2016-12-19 05:09
> I  do not understand how the fish shell would do that to detect it is running inside a MS Windows console.

What he meant is that this is how you personally can witness fish on a native console on Windows, by manually running it inside a native console with those instructions.

**Comment by Maximus5** [comment] 2016-12-19 10:29
I agree, checking `$TERM` for `cygwin` value seems like the only possible way.

**Comment by krader1961** [comment] 2016-12-22 23:05
To avoid hardcoding things like `$TERM` values in the C++ code and maximize flexibility I propose introducing a new function. This function would be evaluated before the first prompt is displayed and whenever the `TERM` var changes. If it returns success we use the current mechanism to highlight that the prior command output did not end in a newline. If it returns failure (any non-zero return status) we bypass that mechanism. Fish would include a version of the function that simply checks for `$TERM == cygwin`. Individuals or distros would be free to create a version of the function that performs other checks or even just does `return 1` without regard to the term type.

Anyone have a good name for this function? Obviously it should begin with `fish_`.

**Comment by ridiculousfish** [comment] 2016-12-23 01:28
I'm not thrilled about introducing a function here. What does zsh do? Does it suffer from this same bug or has it found a workaround?

**Comment by krader1961** [comment] 2016-12-23 03:53
Somebody owes me a bottle of scotch. Before reading further note that the original zsh implementation of this feature in July 2005 was radically different than it is today and can be found [here](https://www.zsh.org/mla/workers/2005/msg00819.html) and probably would not produce the desired result in ConEmu. Nonetheless, the current zsh code appears to do the right thing. After pondering the zsh and fish code for a while I think I've found the critical difference. In zsh it does this in *Src/util.c*:

```
        str = promptexpand(eolmark, 1, NULL, NULL, NULL);
        countprompt(str, &w, 0, -1);
        opts[PROMPTPERCENT] = percents;
        zputs(str, shout);
        fprintf(shout, "%*s\r%*s\r", (int)zterm_columns - w - !hasxn,
                "", w, "");
```

The `w` variable will be equal to one at that point. The equivalent part of the fish code is

```
abandon_line_string.push_back(omitted_newline_char);
abandon_line_string.append(screen_width - non_space_width, L' ');
abandon_line_string.push_back(L'\r');
abandon_line_string.append(non_space_width, L' ');
abandon_line_string.push_back(L'\r');
abandon_line_string.append(L"\x1b[2K");
```

Where our `non_space_width` is the analog of zsh's `w` and is also one.

There are three significant differences in the two approaches. The most important is the inclusion of `!hasxn` in the calculation of how many spaces to write before the first `\r` by zsh. Because neither the xterm nor cygwin terminfo definitions have that attribute (known as "eat_newline_glitch") zsh outputs one fewer spaces than fish. If I modify the fish code to subtract one from the first whitespace append it fixes the problem.

Obviously the second difference is that zsh outputs the clear-to-end-of-line escape sequence while zsh does not. However, leaving that in the code doesn't cause any problems on ConEmu or Mintty.

The third difference is that zsh writes what fish calls the `omitted_newline_char` twice (zsh just uses a literal `%` character). Modifying fish to do the same thing also works in ConEmu and Mintty.

To be determined is whether the changes that make this work in ConEmu cause problems for the UNIX terminal emulators which we also need to support.

**Comment by krader1961** [comment] 2016-12-23 04:03
In case it wasn't clear from my previous comment the issue is due to the fact fish expects to be able to write a space at the 80'th column position (or whatever is the width of the terminal) without inducing a line wrap and ConEmu (and the native MS Windows console) violates that assumption per @Maximus5's earlier [comment](https://github.com/fish-shell/fish-shell/issues/789#issuecomment-267769436). The zsh heuristic avoids that difference in behavior. I'm pretty confident the zsh heuristic is valid for both types of terminals but much testing will be required before we change this since we don't want to fix this for a small subset of fish users while simultaneously pissing of a much larger community.

**Comment by floam** [comment] 2016-12-23 06:50
I'm surprised we aren't checking `has_newline_glitch`.

**Closed** 2016-12-24 20:18 UTC
Labels: enhancement, RFC, windows

**Comment by ArianeLu** [comment] 2018-02-24 09:30
Same issue here, i am using font "Sarasa Gothic" by @be5invis, this symbol and the newline will disappear after change to other font like "Inziu Iosevka"

**Comment by mqudsi** [comment] 2018-03-02 23:27
What @krader1961 and @Maximus5 mention is well-documented [in the wrapping section](https://www.gnu.org/software/termutils/manual/termcap-1.3/html_node/termcap_27.html) of the GNU `termutils` manual:

> Wrapping means moving the cursor from the right margin to the left margin of the following line. Some terminals wrap automatically when a graphic character is output in the last column, while others do not. Most application programs that use termcap need to know whether the terminal wraps. There are two special flag capabilities to describe what the terminal does when a graphic character is output in the last column.
> 
> `am'
> Flag whose presence means that writing a character in the last column causes the cursor to wrap to the beginning of the next line. If `am' is not present, writing in the last column leaves the cursor at the place where the character was written. Writing in the last column of the last line should be avoided on terminals with `am', as it may or may not cause scrolling to occur (see section Scrolling). Scrolling is surely not what you would intend. If your program needs to check the `am' flag, then it also needs to check the `xn' flag which indicates that wrapping happens in a strange way. Many common terminals have the `xn' flag.
> `xn'
> Flag whose presence means that the cursor wraps in a strange way. At least two distinct kinds of strange behavior are known; the termcap data base does not contain anything to distinguish the two. On Concept-100 terminals, output in the last column wraps the cursor almost like an ordinary `am' terminal. But if the next thing output is a newline, it is ignored. DEC VT-100 terminals (when the wrap switch is on) do a different strange thing: the cursor wraps only if the next thing output is another graphic character. In fact, the wrap occurs when the following graphic character is received by the terminal, before the character is placed on the screen. On both of these terminals, after writing in the last column a following graphic character will be displayed in the first column of the following line. But the effect of relative cursor motion characters such as newline or backspace at such a time depends on the terminal. The effect of erase or scrolling commands also depends on the terminal. You can't assume anything about what they will do on a terminal that has `xn'. So, to be safe, you should never do these things at such a time on such a terminal. To be sure of reliable results on a terminal which has the `xn' flag, output a `cm' absolute positioning command after writing in the last column. Another safe thing to do is to output carriage-return newline, which will leave the cursor at the beginning of the following line.
> `LP'
> Flag whose presence means that it is safe to write in the last column of the last line without worrying about undesired scrolling. `LP' indicates the DEC flavor of `xn' strangeness.
>

**Comment by Pysis868** [comment] 2019-07-13 20:54
I was having this problem for a while, had already tried correct fonts, environment variables and settings like I had practiced before.

All was as I needed, although using an alternative font as Unifont instead of Lucida Sans Unicode or any other seemed to give the best \u23CE character with that upward arch in addition to the horizontal length.

Then I realized I hadn't updated my machine in a while (Win 10 Pro x86_64, ConEmu 190310 [64], Cygwin NT 10.0 x86_64 3.0.7(0.338/5/3), fish 2.4.0) using the cygwin setup installer/wizard / apt-cyg / sage.

I decided to check some details and found fish was up to 3.0.2!
https://cygwin.com/cgi-bin2/package-grep.cgi?grep=fish&arch=x86_64

Was eventually able to update after some slight bugs and restarting that process 1 or 2 more times, made a new console tab, realized I had fish 2.7.0, 3.0.2 was in the test phase, and upon launching it no longer had the character erroneously anymore!

I had done my tests using `echo`, `echo -n`, and `echo -e '\n', just to try some combinations based on the commentary I had found here, and it seems to be fixed now.

It was very cool to see everyone in this thread working on it.  I am happy with ridiculousfish's and Maximus5's products, thanks!!
