### ISSUE TITLE
Weird output (bug?) of --no-execute on working script

### ISSUE THREAD

**Issue by ulidtko** [fish-shell/fish-shell#6484] opened 2020-01-08 11:43 UTC
Hi! I know, my fish 2.7.1 is pretty darn old, but hear me out.

There's this excellent [vim plugin][] from sir @dag for fish. In includes a syntax checking integration which utilizes `fish --no-execute`.

The problem is, I get weird output from `fish --no-execute` called on a perfectly valid and working script. I suspect it's a bug.

Minimal repro:
```
~> echo 'type -q foobar; and echo "oh foobar is a thing?.."' > test.fish
~> fish test.fish
~> fish --no-execute test.fish
test.fish (line 1): 
type -q foobar; and echo "oh foobar is a thing?.."
^
~> fish --version
fish, version 2.7.1
```

Is a bug? Is fixed in 3.0 series?..

[vim plugin]: https://github.com/dag/vim-fish

**Comment by zanchey** [comment] 2020-01-08 12:13
This is because of #977 - `type` is a function, and `--no-execute` doesn't understand how to load function files.

**Comment by krobelus** [comment] 2020-01-08 12:25
I think we should just treat every command as valid as stated in https://github.com/fish-shell/fish-shell/issues/977#issuecomment-54929637. We also support and use variables as commands.

**Comment by faho** [comment] 2020-01-08 19:00
Duplicate of #977

**Closed by faho** 2020-01-08 19:00 UTC

**Comment by ulidtko** [comment] 2020-01-09 11:33
@faho well, 1) not duplicate, merely related; 2) #977 is explicitly relabeled **`Enhancement`  not a Bug**.

I am reporting strictly *a bug*, not an "enhancement duplicate".

Not duplicate — because I don't even get `Unknown command` in the error output, see?

The output is barely legible; just points to a [working!] source line, saying nothing on what's wrong.

This becomes much worse when you have multiple "errors".

----
P.S: I see that the whole `--no-execute` feature stagnates since at least 2013. Which of course is a pity; but still not a justification to centralize all discussion of it in the single #977 — which stagnates, too, and is not even considered a bug. I've no problem to move there; but I think you're jumping the gun with closing as duplicate.

**Comment by ulidtko** [comment] 2020-01-09 11:38
P.P.S: those developers will shout on you if you *necropost* in old threads, asking to open a new issue instead. Those same developers will shut down your issue "as a duplicate" of a stagnating not-a-bug of inferior quality.

What a great way to exclude any sort of manual QA from volunteers.

![photo_2020-01-07_00-46-01](https://user-images.githubusercontent.com/365338/72064548-c78c1480-32e4-11ea-8129-1ce66047017b.jpg)

**Comment by faho** [comment] 2020-01-09 11:39
No, it is indeed a duplicate. The error you're getting is command-not-found, only the handler isn't defined. The way to fix it is to disable checking for commands in no-execute, as mentionednin 977.

**Comment by ulidtko** [comment] 2020-01-09 11:40
@faho can you put back the "Bug" label on #977 then?

**Comment by faho** [comment] 2020-01-09 11:41
Yes, I can do that.
