### ISSUE TITLE
[Support] ls command print garbage on screen

### ISSUE THREAD

**Issue by fabiang** [fish-shell/fish-shell#6737] opened 2020-03-11 18:34 UTC
Hello,

I've a problem since two or three years with my fish (currently running 3.0.2): when I'm running the `ls` command I see some garbage in the output:

```
~ $ ls -l /


struct


uname
     hellouidmap




slice	

测试	uint
uint64int   uintint8 
                     int16
                          int32
                               int64float32?��float64>������pointer	null	none	fucktotal 6444
lrwxrwxrwx.   1 root root       7 Jul 25  2019  bin -> usr/bin/
...
```

**Note** the word "fuck".

I don't have this problem when executing `/usr/bin/ls` directly, `ls` under `bash` or when using `env FOO=bar ls -l`

While I'm living with this issue for years now, a co-worker just asked me why my terminal says "fuck".

What I've tried:
- removing my fish functions and emptying the `conf.d` folder
- remove `~/.config/fish` completely
- `sh -c 'env HOME=$(mktemp -d) fish'` then `ls`: still same problem

What I have:
- `uname -a`: Linux $HOSTNAME 5.5.7-200.fc31.x86_64 #1 SMP Fri Feb 28 17:18:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- `fish --version`: fish, version 3.0.2
- `echo $TERM`: xterm-256color
- `cat /etc/os-release`:
```
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
```

Is this upstream? Any advice how I can catch this fish error?

Thank you.

**Comment by faho** [comment] 2020-03-11 18:35
Well, what does `type ls` say?

What do your environment variables say - `env`?

**Comment by fabiang** [comment] 2020-03-11 18:56
I've just compiled from source against version 3.1.0 and the error is gone and when I switch over to tag 3.0.2 the error is still present. So it seems 3.1.0 fixed the issue.

I assume the error was fixed. Strange that no one else noticed this over the past few years.

At least someone having this issue can now find a solution. Closing this.

For sake of completeness:
```
~ $ type ls
ls is a function with definition


struct


uname
     hellouidmap




slice	

测试	uint
uint64int   uintint8 
                     int16
                          int32
                               int64float32?��float64>������pointer	null	none	fuck# Defined in /home/user/fish-shell/share/functions/ls.fish @ line 6
function ls --description 'List contents of directory'
    set -l param --color=auto
    if isatty 1
        set -a param --indicator-style=classify
    end
    command ls $param $argv
end
```

```
CINNAMON_VERSION=4.4.8
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/userid/bus
DESKTOP_SESSION=cinnamon
DISPLAY=:0
GDMSESSION=cinnamon
GDM_LANG=de_DE.UTF-8
GJS_DEBUG_OUTPUT=stderr
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/92d536b1_149a_47ea_991b_d28a3ad58506
GNOME_TERMINAL_SERVICE=:1.866
GOPATH=/home/user/goprojects
GTK_OVERLAY_SCROLLING=0
HOME=/home/user
IMSETTINGS_INTEGRATE_DESKTOP=yes
IMSETTINGS_MODULE=none
KRB5CCNAME=KCM:
LANG=en_US
LOGNAME=user
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/home/user/goprojects/bin:/home/user/goprojects/bin:/home/user/goprojects/bin:/home/user/goprojects/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
PWD=/home/user
QT_IM_MODULE=xim
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/4827,unix/unix:/tmp/.ICE-unix/4827
SHELL=/bin/fish
SHLVL=4
SSH_AGENT_PID=4824
SSH_AUTH_SOCK=/run/user/userid/keyring/ssh
TERM=xterm-256color
USER=user
USERNAME=user
VTE_VERSION=5803
WINDOWPATH=2
XAUTHORITY=/run/user/userid/gdm/Xauthority
XDG_CURRENT_DESKTOP=X-Cinnamon
XDG_DATA_DIRS=/home/user/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
XDG_RUNTIME_DIR=/run/user/414801643
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=cinnamon
XDG_SESSION_ID=2
XDG_SESSION_TYPE=x11
XDG_VTNR=2
XMODIFIERS=@im=none
```

**Comment by faho** [comment] 2020-03-11 18:59
`type test`?

**Comment by fabiang** [comment] 2020-03-11 18:59
```
~ $ type test
test is a builtin
```

**Comment by faho** [comment] 2020-03-11 19:00
Sorry, `type -a test`.

**Comment by fabiang** [comment] 2020-03-11 19:01
```
~ $ type -a test
test is a builtin
test is /home/user/goprojects/bin/test
test is /home/user/goprojects/bin/test
test is /usr/bin/test
```
Oh, is it go?

**Comment by faho** [comment] 2020-03-11 19:02
Yup, it is.

And no, this is not the first time - that awful awful awful command name has tripped us up a few times. Most recently in #5665, which is when we decided to work around it.

**Comment by fabiang** [comment] 2020-03-11 19:02
Remove the `test` binary and the error is gone. Thank you very much.

**Comment by faho** [comment] 2020-03-11 19:02
Duplicate of #5665

**Closed by faho** 2020-03-11 19:02 UTC
Labels: duplicate

**Comment by exploide** [comment] 2020-03-11 19:12
> I've just compiled from source against version 3.1.0 

I read you use Fedora 31 along with fish 3.0.2. This indicates to me that you are hit by the current Fedora modularity annoyance. Fedora currently contains packages in both, the modularity repository, as well as in the regular repositories. This happened without the consensus from all affected maintainers, hence certain modularity packages are not brought up to date in contrast to the regular packages. But for some packages, modularity repository takes precedence.

fish is one of the affected packages. Thus you have version 3.0.2. If you want to get the latest and greatest fish, you can do the following:

```
sudo dnf module disable fish
sudo dnf distro-sync
```

You should then get fish 3.1.0 from the regular repositories.
