### ISSUE TITLE
fish_config interface not loading

### ISSUE THREAD

**Issue by muffledcry** [fish-shell/fish-shell#8690] opened 2022-02-01 18:58 UTC
fish, version 3.1.2
ChromeOS/Crostini
Linux penguin 5.4.157-17191-g6575d22de694 
xterm-256color

When attempting to use fish_config, I get the following result instead of the normal interface for styling:

![image](https://user-images.githubusercontent.com/59100054/152032754-9abeda07-616b-47b8-9bf0-646385121689.png)
![image](https://user-images.githubusercontent.com/59100054/152032919-d081a1a1-d683-46ea-b2f3-d941d3b6f709.png)

**Comment by faho** [comment] 2022-02-01 19:26
Duplicate of #7789

**Comment by faho** [comment] 2022-02-01 19:27
The solution is to upgrade fish. Version 3.1.2 lacks 20% of all commits ever made to fish.

**Closed by faho** 2022-02-01 19:26 UTC
