### ISSUE TITLE
Since fish version 3.6.0 I can't set abbreviations via the fish_config web gui anymore

### ISSUE THREAD

**Issue by moritz1000** [fish-shell/fish-shell#9489] opened 2023-01-18 17:33 UTC
**Fish version:**
fish, version **3.6.0**

**Operating system:**
Linux endeavour 6.1.6-arch1-3, xterm-256color, KDE Konsole

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting: `sh -c 'env HOME=$(mktemp -d) fish'`
Yes, I tried this. It did not change anything.

**TL;DR**

**When I try to create a new abbreviations via the fish_config web gui and save it, nothing happens**.

Steps to reproduce:
1) I open the web config via `fish_config`
2) I navigate to "abbreviations" and enter `test` in the left field and `test2` in the right field
3) Then I click on save
4) I go back to the console and see the following output:
```
fish_config 
Web config started at file:///tmp/web_config0a412935.html
If that doesn't work, try opening http://localhost:8000/c6c542f9cfa2f9491016600baf7bb647/
Hit ENTER to stop.
$ set -L
$ abbr --show
$ abbr --add 'test' 'test2'
```
5) I press ENTER to stop.
6) I check via `abbr --show ` if the abbreviations 'test' 'test2' exists: **no, it does not.**
7) I try to use the abbreviations test -> test2: it does not work.

So according to the console output the abbreviations gets successfully but in reality it does not.
I can't use it and when I go back to the `fish_config` web gui > abbreviations tab, there is nothing new.
___

**When I try to set a new abbreviations via console only by typing** e.g.: `abbr --add test2 test3`, **it works.**
I see the abbreviations via `abbr --show` > `abbr -a -- test2 test3` and I can use it.

**The abbreviations test2 test3 does not appear in he fish_config web gui abbreviations tab!**
___

All my abbreviations that I set on older fish shell versions (<3.6.0) do still work.
![image](https://user-images.githubusercontent.com/35174351/213247896-5d7d504c-0d41-4d5e-96bc-2aa50075a534.png)

**If I try to downgrade to an older fish version (**3.5.1**) via `sudo downgrade fish` I can successfully set abbreviations via the fish_config web gui again!**

I can also still use the fish_config web gui to change e.g. my colors.

**Comment by faho** [comment] 2023-01-18 17:37
Duplicate of #9460

**Comment by faho** [comment] 2023-01-18 17:38
This is correct, abbreviations can no longer be stored in universal variables so the tab is ineffective.

We forgot that it existed and have removed it for 3.6.1.

You need to set your abbreviations in config.fish or conf.d files.

**Closed by faho** 2023-01-18 17:37 UTC

**Comment by moritz1000** [comment] 2023-01-18 17:42
> This is correct, abbreviations can no longer be stored in universal variables so the tab is ineffective.
> 
> We forgot that it existed and have removed it for 3.6.1.
> 
> You need to set your abbreviations in config.fish or conf.d files.

Thanks for the reply.
In which file are my current abbreviations stored which I previously created via the web gui?
I can't find them in config.fish or conf.d files.
I see them listed via 
```
abbr --show
abbr -a -U -- cheat cht.sh
abbr -a -U -- yeet 'yay -Rns'
abbr -a -U -- gib 'yay -S'
abbr -a -U -- unlockdb 'sudo rm /var/lib/pacman/db.lck'
abbr -a -U -- plasma_r 'kquitapp5 plasmashell && kstart5 plasmashell'
```

**Comment by faho** [comment] 2023-01-18 17:47
The `-U` is the hint here - they are imported from the old universal variables, stored in ~/.config/fish/fish_variables. This is like `set -U`, which sets universal variables.

If you want to set them from config.fish, copy those calls into there and remove the `-U`, then go to the web interface and delete them.

Or wait for 3.6.1 and run `abbr --erase (abbr --list)`.

**Comment by antoooooooooooonie** [comment] 2023-08-08 12:04
@faho What was the rationale behind no longer allowing abbreviations to be stored as a universal variable? 

As far as I can tell abbreviations are still universally accessible across all of my shells anyways, except now I can no longer edit them in the UI?

**Comment by faho** [comment] 2023-08-08 12:13
>What was the rationale behind no longer allowing abbreviations to be stored as a universal variable?

Abbreviations were made much more powerful in fish 3.6.0, which means the old variables could no longer hold them.

You can now have abbreviations trigger on regexes, everywhere in the commandline, and run a function to get the replacement, and set the cursor in the replacement.

>As far as I can tell abbreviations are still universally accessible across all of my shells anyways, except now I can no longer edit them in the UI?

The old abbreviation variables still exist and will still be loaded for the time being (this works because they only have the old limited feature set), but `abbr` will no longer create new ones.

**Comment by antoooooooooooonie** [comment] 2023-08-08 12:40
@faho Those new functionalities sound awesome! 

Thanks for taking the time to explain - and also just for making Fish awesome.
