### ISSUE TITLE
source: Error encountered while sourcing file

### ISSUE THREAD

**Issue by ua17** [fish-shell/fish-shell#6938] opened 2020-04-23 18:50 UTC
Hey, everybody.
When I open the terminal, I see this message.
```
source: Error encountered while sourcing file “/tmp/.psub.jzkAA3h7Nu”:
source: No such file or directory
source: Error encountered while sourcing file “/tmp/.psub.5ubpc6wghe”:
source: No such file or directory
Welcome to fish, the friendly interactive shell
```
How do I fix it?
```
➜  ~ fish --version 
fish, version 3.1.0
➜  ~ echo $version
3.1.0
➜  ~ uname -a
Linux 73 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ echo $TERM
xterm-256color
```
Thank you very much.

**Comment by faho** [comment] 2020-04-23 19:56
Duplicate of #6613.

It's a bug in fish 3.1.0 that'll be fixed in the next release.

The workaround is easy: Don't do `source (... | psub)`, which is superfluous anyway - just use `... | source`.

**Closed by faho** 2020-04-23 19:56 UTC

**Comment by ua17** [comment] 2020-04-23 21:04
Thank you @faho
