### ISSUE TITLE
Command Substitution Problem with WP-CLI in Fish

### ISSUE THREAD

**Issue by timkite** [fish-shell/fish-shell#1341] opened 2014-03-12 20:39 UTC
I discovered an odd behavior when using the latest stable fish shell (2.1.0) with the latest release of wp-cli (0.14.1). When the "wp" command is used within a command substitution in, say, a for loop, the sub-shell is launched and then never returns. The for loop completes, returning nothing, but the sub-shell is left running. The equivalent loop works in bash. An example:

The command "wp user list --field=user_login" will produce a newline separated list of WordPress usernames found on the site referenced by the wp-config.php found within the present working directory, written to stdout. The command "wp user update $u --user_pass='newpass' would update that user's password with the one specified. It could be replaced with something as simple as "echo $u" and the same issue is exhibited in fish.

```
# bash (works as expected)
for u in $(wp user list --field=user_login); do
    wp user update $u --user_pass='newpass'
done

# fish (sub-shell never returns, command fails with nothing returned)
for u in (wp user list --field=user_login)
    wp user update $u --user_pass='newpass'
end
```

**Comment by faho** [comment] 2015-10-04 17:29
@timkite: Is this still an issue?

**Comment by timkite** [comment] 2015-10-05 13:32
Yes, with Fish 2.2.0 (latest for RHEL6), wp-cli 0.20.1 (latest), and PHP 5.3.3 (latest for RHEL6).
-- 
Tim

**Comment by faho** [comment] 2015-10-05 14:19
This seems similar to #1949.

**Comment by timkite** [comment] 2015-10-05 15:48
Yes, actually it looks like the same issue precisely, and it makes sense why fish is behaving as it does (thinking that the command in parentheses is an interactive shell, and thus never returning). I hope there's a fix coming, though until there is I can always switch to bash when I need a "normally" behaving sub-shell.
-- 
Tim

**Comment by faho** [comment] 2015-10-05 17:17
@timkite: If you want to confirm that it's exactly that, redirect stdin from /dev/null:

```fish
for u in (wp user list --field=user_login </dev/null)
    wp user update $u --user_pass='newpass'
end
```

**Comment by timkite** [comment] 2015-10-05 18:46
That works! I wouldn't have thought to do that, and that's not a bad workaround.
-- 
Tim

**Comment by zanchey** [comment] 2015-10-15 05:42
In that case, I'll close this as a duplicate of #1949.

**Closed by zanchey** 2015-10-15 05:42 UTC
Labels: duplicate
