### ISSUE TITLE
Tab-completing ".." (upper directory) does not work in 3.6.0

### ISSUE THREAD

**Issue by melefabrizio** [fish-shell/fish-shell#9485] opened 2023-01-17 22:16 UTC
fish: 3.6.0

I recently switched to a new macbook. During the migration I brought over the entire `.config` directory, to keep all my fish/fisher plugins and configurations.

But, when I try to tab-complete the upper directory (eg, type `cd ..` then `<tab>` to view the parent directories's dirs) nothing happens. I think that the problem is that `..` is a function in fish 3.6.

On the other laptop, which was using fish 3.5.1, typing `cd ..` then `<tab>` showed the usual autocomplete "dropdown" with the contents of the parent directory.

I'm sure this is a problem of something `> 3.5.1` because after upgrading on the "other" laptop it stopped working with the same behaviour.

In both versions typing `..` results in a `cd ..`.  Asciinema of the bug [here](https://asciinema.org/a/8CsVz0Nq2plrTueZ70oxcROE1)

(I tried using the `sh -c 'env HOME=$(mktemp -d) fish'` to check whether it was something on my side, but same behaviour)

**Comment by faho** [comment] 2023-01-17 22:17
Duplicate of #9477

**Closed by faho** 2023-01-17 22:17 UTC
