### ISSUE TITLE
Disable showing prefix of tab list

### ISSUE THREAD

**Issue by xiebruce** [fish-shell/fish-shell#9649] opened 2023-03-09 19:28 UTC
**YOUR TEXT HERE**
`file --version`
> fish, version 3.6.0

`uname -a`
> Darwin Bruce's MBP 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

`echo $TERM`
> xterm-256color

**YOUR TEXT HERE**

Type `cd /usr/local/`, press `Tab`, then the files under `/usr/local/` will list out as follow
<img width="766" alt="image" src="https://user-images.githubusercontent.com/13575500/224131021-b7755bcb-b4ad-425b-9059-20f3d6679f92.png">

My question: how can I disable showing the prefix in the `Tab` file list? Because it's clear to me that I'm checking file list under `/usr/local/`(I type the command), I don't need fish to tell me that those files are under `…sr/local/`, I just need to know what exact files are under `/usr/local/`, just like what zsh do(see the screenshot bellow)

<img width="739" alt="image" src="https://user-images.githubusercontent.com/13575500/224132865-9716f982-33ed-4cb4-82df-34405ea24e61.png">

If it is possible, it's better to show files and folders in different color, it's there a "switch" to turn it on?

**Comment by faho** [comment] 2023-03-09 19:37
Duplicate of #8618

**Closed by faho** 2023-03-09 19:37 UTC
