### ISSUE TITLE
Piped chain of commands inside command substitution

### ISSUE THREAD

**Issue by gnapse** [fish-shell/fish-shell#1977] opened 2015-03-10 16:09 UTC
In traditional shells something like this can be done:

    cd $(find . -type d | pick)

If I try to do the same thing on fish, dropping the `$` sign in front of the command substitution notation, I get this:

    cd (find . -type d | pick)

However, this does not work. So what's the correct notation to achieve something like this in fish?

Note: in the above examples, the `pick` command refers to [thoughtbot/pick](https://github.com/thoughtbot/pick), a command line tool to select a single item out of a list by fuzzy-filtering. Its power often comes by using it precisely in this manner shown above, piping in the output of another command within a command substitution expression.

**Comment by zanchey** [comment] 2015-03-11 04:40
I'm reasonably sure that by "doesn't work" you mean it returns immediately but you can see a stopped job in `jobs`. Unfortunately this is a known issue - command substitutions run in their own process group (see #1362) and thus don't get access to the terminal.

I will close this as a duplicate of that report for now as the discussion is pretty extensive there.

**Closed by zanchey** 2015-03-11 04:40 UTC
