### ISSUE TITLE
Generate appropriate completions for subcommand man pages

### ISSUE THREAD

**Issue by NotAFile** [fish-shell/fish-shell#7257] opened 2020-08-11 18:07 UTC
```
echo $version
3.1.2
```
### Summary

Many newer projects split the documenation into one man page per subcommand. Fish can't detect that. It probably could.

### Details

I found a few commands where fish does not generate full completions because it can not combine completions split over multiple man pages. For example for the `libinput` command:

```
NAME
       libinput - tool to interface with libinput

SYNOPSIS
       libinput [--help|--version] <command> [<args>]
[...]
COMMANDS
       libinput-debug-events(1)
               Print all events as seen by libinput

       libinput-debug-gui(1)
               Show a GUI to visualize libinput's events
[...]
```

Where the `libinput-debug-events(1)` is:

```
NAME
       libinput-debug-events - debug helper for libinput

SYNOPSIS
       libinput debug-events [options]

       libinput debug-events [options] --udev <seat>

       libinput debug-events [options] [--device] /dev/input/event0 [/dev/input/event1...]
```

It generates proper completions for these manpages of course:

```fish
# libinput-debug-events
# Autogenerated from man page /usr/share/man/man1/libinput-debug-events.1.gz
complete -c libinput-debug-events -l device --description 'Use the given device(s) with the path backend.'
complete -c libinput-debug-events -l grab --description 'Exclusively grab all opened devices.'
[...]
```

However, `libinput-debug-events` is not a real command, so this is in vain.

Here's another example from podman:

```
NAME
       podman - Simple management tool for pods, containers and images

SYNOPSIS
       podman [options] command
[...]
COMMANDS
       ┌──────────────────────┬──────────────────────────────────────────────┐
       │Command               │ Description                                  │
       ├──────────────────────┼──────────────────────────────────────────────┤
       │podman-attach(1)      │ Attach to a running container.               │
       ├──────────────────────┼──────────────────────────────────────────────┤
```

```
NAME
       podman-attach - Attach to a running container

SYNOPSIS
       podman attach [options] container

       podman container attach [options] container
```

### Solutions

The first solution that came to mind is detecting a `COMMANDS` section and looking for references to other man pages. However, since fish parses all man pages anyway, we can be smarter.

My proposal here would be to look at how the program calls itself on it's own manpage in the `SYNOPSIS` section. If it passes some sanity checks such as matching the name of the man page, we can assume that this is a subcommand and output the appropriate completions.

**Comment by faho** [comment] 2020-08-11 18:19
Sorry, subcommands aren't written in a standardized enough way that this is feasible to make useful, and your examples actually show why.

E.g. even if you managed to get "attach" and "container attach" out of it, what do you do with the "[options]" and "container" strings? Is that first "container" the literal string "container" and that second one "a container"?

Or if you see

```
       libinput debug-events [options] [--device] /dev/input/event0 [/dev/input/event1...]
```

how do you parse this in a way that it'll offer "/dev/input/event0" *or* "/dev/input/event1" - which I'm assuming this is supposed to signify.

And even *just* the subcommands themselves are given in such a variety of styles that putting more effort into this isn't useful.

I'm filing this as a duplicate of #7107, because the intent behind it is to make completing subcommands easier, and that tracks doing that.

**Closed by faho** 2020-08-11 18:19 UTC

**Comment by NotAFile** [comment] 2020-08-11 18:55
I saw that issue (and contrasted it to this one in an earlier draft). This is a completely different thing. #7107 relates to how subcommands are described to fish. This is adding functionality to `create_manpage_completions.py`

Fish already generates completions for these subcommand manpages. I'm not proposing any changes to that. My proposal is merely to amend the completion generator to allow it to detect that the `programname-subcommand` man page relates to `programname` and emit the appropriate completions.

**Comment by faho** [comment] 2020-08-11 19:03
>This is adding functionality to create_manpage_completions.py

I understand and I am saying that that's unlikely to yield acceptable results, hence I'm deferring to other ideas to make completing subcommands nicer.

Create_manpage_completions.py is really not all that useful, tbh, and it's because the problem is basically impossible, because manpages aren't written in a manner to facilitate this.

Effort put into it is, for the most part, better spent either writing completion scripts or making writing completion scripts easier.
