### ISSUE TITLE
"fish -n" throws error when invoking command substitution

### ISSUE THREAD

**Issue by Datamance** [fish-shell/fish-shell#6885] opened 2020-04-11 00:17 UTC
Fish version is 3.1.0.

Here's the relevant line of `config.fish`:
```fish
source (pyenv init - | psub)
```

and here's the output when I run `fish -n config.fish`:
```
 ricorodriguez  ~/.c/fish  fish -n config.fish                                     217ms  Fri Apr 10 20:03:15 2020
config.fish (line 1):
pyenv init - | psub
               ^
in command substitution
	called on line 20 of file config.fish
config.fish: Unknown error while evaluating command substitution
```

The file runs perfectly fine without the -n flag.

This is causes an error with the [Ale Syntax checker](https://github.com/dense-analysis/ale), which is why I'm filing the bug.

**Comment by zanchey** [comment] 2020-04-11 02:16
Duplicate of #977 (fixed in master) - thanks anyway!

**Closed by zanchey** 2020-04-11 02:16 UTC
