### ISSUE TITLE
Fish shell seems cache streaming between customized functions

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#8474] opened 2021-11-23 02:59 UTC
## Fish Version
``` fish
$ fish --version
fish, version 3.3.1
```

## Operating System
``` fish
$ uname -a
Linux caizheng-nuc10i7fnk 5.10.70-1-MANJARO #1 SMP PREEMPT Thu Sep 30 15:29:01 UTC 2021 x86_64 GNU/Linux
```

## Reproduction Steps
``` fish
# Create two simple wrapper functions around `find` and `cat`
function find_inside_function
  find /
end

function cat_inside_function
  cat
end

# Case #1 - a command pipes to a command
find / | cat

# Case #2 - a command pipes to a fish function
find / | cat_inside_function

# Case #3 - a fish function pipes to a command
find_inside_function | cat

# Case #4 - a fish function pipes to another fish function
find_inside_function | cat_inside_function
```

## Expectation
The case `#4` behaves the same as other cases.

## Actual Result
Cases `#1`, `#2`, `#3` printed output to console immediately while case `#4` hung up for a while before output shown up.

Seems case `#4` tried to cache the stream between functions.

**Comment by faho** [comment] 2021-11-23 07:11
Duplicate of #1396

**Closed by faho** 2021-11-23 07:11 UTC
