### ISSUE TITLE
fish_color_* variables default values

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#6223] opened 2019-10-18 10:08 UTC
I feel like this should be answered somewhere already, but I wasn't able to find it.  Sorry if this is a duplicate.

I (accidentally, more or less) deleted my fishd.* and fish_variables files.  As a result, the syntax colouring now looks very weird.  I don't remember doing it but it could be that I set up syntax colouring by hand a long time ago.  Anyway, I was very surprised to see that a lot of the fish_color_* variables have explicit RGB hex codes as their values.  I have all my colours set up in my terminal's config file and I would think that that's true for most users.  So wouldn't it make more sense to use the colour names as they are used by set_colour as defaults for the colour variables?  That way fish would use the terminal's colours by default.

**Comment by faho** [comment] 2019-10-18 10:37
Duplicate of #3443

**Closed by faho** 2019-10-18 10:37 UTC
