### ISSUE TITLE
Alt-backspace is no longer able to delete a word backwards

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4975] opened 2018-05-12 11:15 UTC
fish, version 2.7.1
openSUSE Tumbleweed
Linux 4.16.6-1-default x86_64

`Alt-backspace` is not able to delete a word in prompt backwards, it just delete one character.

I also tested fish in:

    sh -c 'env HOME=$(mktemp -d) fish'

it doesn't work either. But if I'm in bash session, `Alt-backspace` works fine.

I also try to remove all my fish shell configuration, change terminal, run fish without tmux, try to reboot my computer, in all the situations, `Alt-backspace` doesn't work as old times in fish-shell, but it works fine in bash shell.

**Comment by faho** [comment] 2018-05-12 11:34
Duplicate of #4955.

**Closed by faho** 2018-05-12 11:34 UTC
