### ISSUE TITLE
Command substitution

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#4362] opened 2017-08-29 11:59 UTC
What's the equivalent for <code>"$(command)"</code> in fish ?

It pass the result of the command in only one argument without spliting

**Comment by ridiculousfish** [comment] 2017-08-30 06:47
Unfortunately nothing so convenient - it's a known and acknowledged hole.

Often though it's unnecessary, since fish splits on newlines and not arbitrary whitespace. What's your use case?

**Comment by hamon-e** [comment] 2017-08-30 19:49
Nothing atm but I was asking cause i had to do this in the past

**Comment by zanchey** [comment] 2017-08-31 15:29
I think this is a duplicate of #159 (!)

**Closed by zanchey** 2017-08-31 15:29 UTC
Labels: duplicate
