### ISSUE TITLE
pushd -1 doesn't works

### ISSUE THREAD

**Issue by componhead** [fish-shell/fish-shell#4722] opened 2018-02-10 23:12 UTC
`pushd +1` works well but `pushd -1` doesn't.

https://asciinema.org/a/vQaltyh6Wb9cTYr58pC7eYuou

**Comment by faho** [comment] 2018-02-10 23:25
Duplicate of #4398, which contrary to what it says didn't make it into 2.7.0, but is in master and will be in 3.0.

Sorry for the inconvenience!

**Closed by faho** 2018-02-10 23:25 UTC
