### ISSUE TITLE
How can I configure errors to use curly underlines?

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10957] opened 2024-12-28 03:06 UTC
According to [this answer](https://askubuntu.com/a/985386), there are various escape sequences available to output fancy styling, like curly underlines.

I want to configure `fish_color_error` to red, bold, with curly underlines rather than the normal straight underlines.

My current config is:

```
set -U fish_color_error --bold --italics --underline ff0000
```

Is there some way to configure curly underlines using the appropriate escape sequence from the linked answer?

**Comment by faho** [comment] 2024-12-28 06:46
Duplicate of #7619

**Closed by faho** 2024-12-28 06:46 UTC

**Comment by faho** [comment] 2024-12-28 06:47
There is currently simply no support for thr various underline styles in fish.

**Comment by krobelus** [comment] 2024-12-28 09:58
it's documented here: https://wezfurlong.org/wezterm/faq.html#how-do-i-enable-undercurl-curly-underlines,
supported by at least WezTerm and foot
