### ISSUE TITLE
Cannot figure out where abbreviation is being set

### ISSUE THREAD

**Issue by jrop** [fish-shell/fish-shell#9532] opened 2023-02-02 17:39 UTC
```sh
 I  ~ ❱ fish --version
fish, version 3.6.0
 I  ~ ❱ abbr --show | grep nix
abbr -a -U -- nst nix-store
abbr -a -U -- np nix-prefetch-url
abbr -a -U -- ngc nix-collect-garbage
abbr -a -U -- nd nix-daemon
abbr -a -U -- ncc nix-copy-closure
abbr -a -U -- nb nix-build
abbr -a -U -- nc nix-channel
abbr -a -U -- nsh nix-shell
abbr -a -U -- nh nix-hash
abbr -a -U -- ni nix-instantiate
abbr -a -U -- ne nix-env
 I  ~ ❱ abbr -e -U nst ... # one for each of the above
```

However, upon restarting my shell, the abbreviations are back, and for the life of me, I cannot find which config file they are in. Is there a suggested method for discovering where abbreviations are set?

**Comment by jrop** [comment] 2023-02-02 17:50
I just tried:

```sh
I  ~ 3.2s ❱ fish -d abbrs,char-encoding,config,debug,env-dispatch,env-export,env-locale,error,event,exec,exec-fork,exec-job-exec,exec-job-status,fd-monitor,iothread,output-invalid,path,proc-internal-proc,proc-job-run,proc-pgroup,proc-reap-external,proc-reap-internal,proc-termowner,profile-history,reader,reader-render,screen,term-support,topic-monitor,uvar-file,uvar-notifier,warning,warning-path -o fish-debug.txt
Debug enabled for category: abbrs
Debug enabled for category: char-encoding
Debug enabled for category: config
Debug enabled for category: debug
Debug enabled for category: env-dispatch
Debug enabled for category: env-export
Debug enabled for category: env-locale
Debug enabled for category: error
Debug enabled for category: event
Debug enabled for category: exec
Debug enabled for category: exec-fork
Debug enabled for category: exec-job-exec
Debug enabled for category: exec-job-status
Debug enabled for category: fd-monitor
Debug enabled for category: iothread
Debug enabled for category: output-invalid
Debug enabled for category: path
Debug enabled for category: proc-internal-proc
Debug enabled for category: proc-job-run
Debug enabled for category: proc-pgroup
Debug enabled for category: proc-reap-external
Debug enabled for category: proc-reap-internal
Debug enabled for category: proc-termowner
Debug enabled for category: profile-history
Debug enabled for category: reader
Debug enabled for category: reader-render
Debug enabled for category: screen
Debug enabled for category: term-support
Debug enabled for category: topic-monitor
Debug enabled for category: uvar-file
Debug enabled for category: uvar-notifier
Debug enabled for category: warning
Debug enabled for category: warning-path
 I  ~ ❱ exit
 I  ~ 2.1s ❱ nvim fish-debug.txt # no references to the abbreviation is found in this file
```

**Comment by faho** [comment] 2023-02-02 17:55
These are old abbreviations imported from universal variables. Unfortunately our messaging around these wasn't ideal and will be improved in the 3.6.1 release.

To erase them you will currently have to do:

```fish
set -e (set -Un | string match -re '^_fish_abbr_')
```

we're fixing that so you can just do

```fish
abbr -e (abbr --list)
```

I'm closing this as a duplicate of #9468 and #9490 because those should clarify what is happening.

**Closed by faho** 2023-02-02 17:55 UTC
