### ISSUE TITLE
Selectively disabling wildcard expansion

### ISSUE THREAD

**Issue by bovid-19** [fish-shell/fish-shell#8926] opened 2022-05-01 11:13 UTC
I would appreciate it if you'd consider adding a way to disable wildcard expansion for specific commands.

While customizing this behaviour like [completions](https://fishshell.com/docs/current/completions.html) is [probably out of the question](https://github.com/fish-shell/fish-shell/issues/1602#issuecomment-244636555), I think that at least for commands that take URLs as their input, some way of achieving this would be useful.

How do you feel about adding a special function that would loop over and quote all of its arguments instead of expanding them, allowing users to wrap commands like this:
```
function links
    links (autoquote $argv)
end
```
?

[Removing the expansion of `?`](https://github.com/fish-shell/fish-shell/commit/dc8d603f988218b6e4fe9dba77f3b62323883182) may be enough in many cases, but [useful addresses that contain `*`](https://web.archive.org/web/*/https://fishshell.com/) exist as well.

**Comment by faho** [comment] 2022-05-01 18:11
Quite frankly: No. Quote your expansions.

**Comment by faho** [comment] 2022-05-01 18:12
Duplicate of #3504

**Closed by faho** 2022-05-01 18:11 UTC

**Comment by faho** [comment] 2022-05-02 09:28
In practice, what you want to do is type

```fish
links '
```

and paste your URL either via ctrl-v (which goes via something like xsel to directly get the clipboard) or the terminal's paste function (which requires it to support bracketed paste, which is the case in almost all modern terminals). Then type the closing single-quote.

When you paste inside single-quotes, fish takes care to escape the pasted text so it can't close the single-quote (i.e. it turns all `\` into `\\` and all `'` into `\'`), and so you're guaranteed that it fits inside them and is interpreted as the literal pasted text.

This has the advantage that it's not a *syntactical* difference - you can still type `links *.html` to open all html files. It's only a key-binding thing and applies to all commands, everywhere.

**Comment by diaper00** [comment] 2024-01-19 23:46
I beg to differ. How can one pass * to a program like "find" without quotes? For example:
f Peligrosa*
where f is a function that contains
find -name $argv

This is not possible without using quotes.

This may seem like laziness on my part that I don't want to use quotes. But I search for files that I partially remember all the time.

It means a special case, I have to remember the context of wildcards in fish and how to get them to the wrapped program. And most of the time I will type this in wrong at 2am and then type it in again with 'Peligrosa*'

I'd like to put functions around most all common tasks I do to insulate from the obscure 50 year design of command line functions. It's more than shortcuts, its about creating consistency. Being able to turn off fish preprocessing and wildcards and ** tree search would be very helpful.

I don't live and breathe this stuff. I will get this environment designed and will go do completely different non computer related projects for 6 months or a year. The arcane things I will forget.

Yes you are right, it is only another two keystrokes. But part of this is being able to design an environment that is fun for me to use. And control and consistency for the user seems to be a fish design goal.

**Comment by krobelus** [comment] 2024-01-20 06:38
> How can one pass * to a program like "find" without quotes?

I agree that this can be really annoying, especially given that it works fine in other shells in 99% of the cases.
Of course it's difficult to find a general improvement that doesn't add too much confusion, I remember being very confused when I noticed that Bash passes through globs to `apt`.
I personally hit this most often with `git` and `rg`.

We already have special cases for select commands; the docs say:

> There are exceptions, namely set and path, overriding variables in overrides,
> count and for. Their globs will instead expand to zero arguments (so the
> command won’t see them at all), like with shopt -s nullglob in bash.

Perhaps we should have similar exceptions for commands: that interpret `*` themselves, don't use `failglob` behavior but pass through globs like bash does by default.
That's a scary language change with potential for confusion but if it's only for a select few commands, it could be fine.

We can also try to solve it on the input side.
You can use this binding to automatically escape `*` for certain commands:

```fish
function insert-asterisk
    set -l quote_state (__fish_tokenizer_state -- (commandline -ct | string collect))
    set -l command (commandline -opc)[1]
    if
        # Not already quoted.
        test $quote_state = normal &&
        # Command that interprets * in its own way.
        contains $command -- apt apt-get dpkg find git grep rg sed string
        commandline --insert '\*'
    else
        commandline --insert '*'
    end
end
bind \* insert-asterisk
```

**Comment by faho** [comment] 2024-01-20 07:16
> Perhaps we should have similar exceptions for commands: that interpret * themselves, don't use failglob behavior but pass through globs like bash does by default.

To be clear: What bash does is pass through globs *if they don't match*.

That means now your command suddenly does something different *if* you don't have a matching file.

I've always felt that's the worst possible behavior.

Quoting is simple and consistent, I do not believe it's a failing to go "if you quote it's not a glob, if you don't it is" everywhere.

Even for the special cases you mention it is still a glob, it's just that if it matches nothing it still turns into what it matches - nothing.
