### ISSUE TITLE
`alias` does not handle backslash properly

### ISSUE THREAD

**Issue by harshavb** [fish-shell/fish-shell#9846] opened 2023-06-16 23:55 UTC
Fish version: 3.6.1
Operating System: Linux nyarch 6.3.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 x86_64 GNU/Linux
Terminal: xterm-kitty
Tried fish without third-party customizations, still broken
To reproduce: simply include a backslash in your alias

The problem I have is that i have a folder named "Program Files" that i need in a path for my alias. but when I try to do Program\ Files, 
it just totally breaks.

![image](https://github.com/fish-shell/fish-shell/assets/48032800/e9a93d7b-8ed5-4720-8416-857d2d7cdc39)

**Comment by faho** [comment] 2023-06-17 05:30
Duplicate of #8720 

The *definition* is correct, the display is broken, and a quick comparison of `type test-alias` will show that.

In any case, all problems with alias magically go away if you just define a function directly:

```fish
function test-alias
    proton ~/local/Program\ Files $argv
end
```

**Closed by faho** 2023-06-17 05:30 UTC
