### ISSUE TITLE
Fail on error (“set -e”)

### ISSUE THREAD

**Issue by xebtl** [fish-shell/fish-shell#2389] opened 2015-09-15 14:07 UTC
A while ago, there was some [discussion](http://sourceforge.net/p/fish/mailman/message/31618463/) on the mailing list about a “fail on error” feature for fish, i.e. to have the shell exit if a command fails, similarly to bash's `set -e`.  However, it seems that this idea died.

I think such a feature would be very good to have for scripting in fish.  For instance, I often write small scripts to drive a computation of some sort, which can run for quite a while.  In what is basically a throw-away script, I do not want to handle every potential error explicitly.  On the other hand, an uncaught error can invalidate the rest of the calculation, which might run on for hours producing, essentially, garbage.  Much better to have the script crash and thereby notify me.  `set -e` is by no means perfect, but can be very helpful in such a situation.

On the mailing list, it was suggested to make this the default behaviour.  My own feeling is that this would be too restrictive for a shell.  Better to activate it on demand.

**Comment by faho** [comment] 2015-09-15 14:23
Duplicate of #805. Thanks for reminding us.

**Closed by faho** 2015-09-15 14:23 UTC

**Comment by xebtl** [comment] 2015-09-15 14:37
Oops, I did not find that issue in my search.  Good to know the idea did not die after all, and some interesting points in the discussion over there.

Sorry for the dupe.
