### ISSUE TITLE
Piping to function blocks output

### ISSUE THREAD

**Issue by acidnik** [fish-shell/fish-shell#7383] opened 2020-10-06 09:17 UTC
fish --version
echo $version
fish, version 3.1.2
3.1.2
uname -a 
Darwin sbn-mac-259.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
echo $TERM
screen-256color

sh -c 'env HOME=$(mktemp -d) fish'

A minimal code to reproduce:
```
function t
      cat $argv
end

# this works ok, outputting numbers with delay
for i in (seq 100)
       sleep 0.1
       echo $i
end

# this blocks output until the end of the loop
for i in (seq 100)
       sleep 0.1
       echo $i
end | t
```

Expected result: piping to a function should not block the output

**Comment by faho** [comment] 2020-10-06 09:33
Duplicate of #206

**Closed by faho** 2020-10-06 09:33 UTC

**Comment by faho** [comment] 2020-10-06 09:36
Sorry, that's #1396
