### ISSUE TITLE
bug: cgi.escape from /usr/share/fish/tools/web_config/webconfig.py deprecated -> freeze in fish_config; replace with html.escape for fix

### ISSUE THREAD

**Issue by LeonardSchuler** [fish-shell/fish-shell#7399] opened 2020-10-14 15:53 UTC
fish, version 2.7.1
4.15.0-118-generic #119-Ubuntu, x86_64, GNU/Linux
xterm-256color

Had some trouble with fish_config not responding when switching to the Prompt tab. In the command line I get a deprecation warning from /usr/share/fish/tools/web_config/webconfig.py

After changing cgi.escape to html.escape (first importing html) in the code below, everything works again.

It was a clean install using apt install fish and no modifications.

`
    # We have to HTML escape the text and convert ANSI escapes into HTML
    # Collect it all into this array

    result = []

    span_open = False

    # Text is at even indexes, escape sequences at odd indexes
    for i in range(len(separated)):
        component = separated[i]
        if i % 2 == 0:
            # It's text, possibly empty
            # Clean up other ANSI junk
            result.append(cgi.escape(strip_ansi(component)))
        else:
            # It's an escape sequence. Close the previous escape.
            span_open = append_html_for_ansi_escape(component, result,
                                                    span_open)

`

**Comment by krobelus** [comment] 2020-10-14 16:11
duplicate of #5125

2.7.1 is quite old, [debian stable is already on 3.0.2](https://packages.debian.org/search?keywords=fish)

**Closed by krobelus** 2020-10-14 16:11 UTC
