### ISSUE TITLE
Completions for misspelled variables show escape characters

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4272] opened 2017-07-31 00:43 UTC
Under `fish, version 2.6.0-304-g1169b8e`, completions for misspelled variables show escape characters, while normally they wouldn't.

To illustrate with an example:

```fish
mqudsi@Blitzkrieg /m/c/U/Mahmoud> echo $fish_<TAB>
$fish_bind_mode                                                                                                     (Variable: default)
$fish_color_autosuggestion                                                                                   (Variable: '555' 'yellow')
$fish_color_command                                                                                       (Variable: '005fd7' 'purple')
$fish_color_comment                                                                                                     (Variable: red)
…and 26 more rows
```

Whereas:

```fish
mqudsi@Blitzkrieg /m/c/U/Mahmoud> echo $bin<TAB>
\$__fish_active_key_bindings  (Variable: fish_default_key_bindings)  \$fish_bind_mode                       (Variable: default)
\$__fish_bin_dir                         (Variable: /usr/local/bin)  \$fish_key_bindings  (Variable: fish_default_key_bindings)
```

The second time around all the `$` completions are prefixed with an escape.

**Comment by krader1961** [comment] 2017-07-31 03:04
I can reproduce this. Looks like a harmless cosmetic bug to me in as much as the proffered fuzzy matches can still be selected and are inserted in the command line without the escape.

**Comment by e-beach** [comment] 2017-08-07 23:22
For what it's worth I was able to reproduce this on fish 2.6.0

**Comment by faho** [comment] 2019-05-30 17:32
Can't reproduce, assuming fixed, closing.

**Closed by faho** 2019-05-30 17:32 UTC
Labels: bug, completions

**Comment by zanchey** [comment] 2019-06-01 13:24
This was present in 2.7.1 but not 3.0.0.
