### ISSUE TITLE
Unexpected `alt-l` behaviour

### ISSUE THREAD

**Issue by jjh2811** [fish-shell/fish-shell#10077] opened 2023-10-28 09:20 UTC
Hi
I'm using `fish, version 3.6.1` on `Linux Ubuntu`.

`__fish_list_current_token` function triggered by hitting `alt-l` does not work as expected when the token is a tilde-based path.

![ezgif-5-ddf9ab446b](https://github.com/fish-shell/fish-shell/assets/20239681/d5a4fd96-96b7-44d0-abd9-c83b71326fd0)

The behaviour when token is `~/test/subdir/` is not the same as when it is `/home/ubuntu/test/subdir/`.
It only lists contents of _**current**_ directory

**Comment by faho** [comment] 2023-10-28 09:24
Duplicate of #9954

**Closed by faho** 2023-10-28 09:24 UTC
