### ISSUE TITLE
bind changes behavior of bound command

### ISSUE THREAD

**Issue by TymekDev** [fish-shell/fish-shell#8859] opened 2022-04-05 06:32 UTC
Hi, I have encountered some problems when using bindings created with `bind`. Behavior differs between running a command via binding and running it on its own. By the looks of it input is somehow not relayed (Control-C works though) for the former.

Please see this example with `bash` and `read`:
[![asciicast](https://asciinema.org/a/t5CfIlBvCrDRkQ0GfVk7HOmwS.svg)](https://asciinema.org/a/t5CfIlBvCrDRkQ0GfVk7HOmwS)

The bash & read example is less obscure, but I have also encountered the problem when running fugitive with `nvim :Git` and using its patch functionalities. It is just my wild guess, but perhaps it has something to do with spawning other shells by the bound command?

### Reproduction
```
bash -c 'read -p "Foo: " foo && echo $foo'
bind \ca 'bash -c \'read -p "Foo: " foo && echo $foo\''
# Control-A to run the binding
```

### Diagnostics
I have replicated this behavior on two similar distinct machines.
```
$ fish --version
fish, version 3.4.0

$ uname -a
Linux ThinkPad-T14-Gen-1 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64

$ echo $TERM
xterm-kitty
```

```
$ fish --version
fish, version 3.4.1

$ uname -a
Linux sffpc 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM
xterm-kitty
```

**Comment by faho** [comment] 2022-04-05 07:18
Duplicate of #4772

**Closed by faho** 2022-04-05 07:18 UTC
