### ISSUE TITLE
Some characters cause glitches

### ISSUE THREAD

**Issue by nagisa** [fish-shell/fish-shell#750] opened 2013-05-15 13:21 UTC
Trying entering some characters, for example `U+1F603`, `U+1F60A` or `U+1F612` either by keyboard (compose sequences) or copy-paste does not show the character (entering one between quotes does work though, still with some glitches).

![A screenshot](https://f.cloud.github.com/assets/679122/506871/68b7391c-bd61-11e2-85f9-4413086686d8.png)

Some breakdown. First of all, for first and second examples some trailing white space was entered. For every character entered after the smile, quote before the smile is duplicated, but interestingly enough – echo is not. In the last example, smile does not appear at all (but was inserted at the beginning). Entering text after it is possible, but deleting does not respond with expected feedback (characters from internal buffer are cleared as far as I observed).

sh and bash obviously work fine in same terminal emulator.

I suspect the unicode library fish uses (does fish use one?) – it might not support any unicode characters outside BMP and SMP planes.

**Comment by 1player** [comment] 2015-05-07 13:52
@ridiculousfish does also happen on KDE's Konsole terminal, which is not based on VTE.

I've been trying to write `echo 🍅` and the tomato character does not show up, even though running the command gives the expected output. Also, next time I write 'echo' and I'm autosuggested the above command, the whole line gets garbled until I remove it from the history.

Tested on VTE-based Terminator and non-VTE Konsole terminal emulators. Bash is not affected.

**Comment by Ninja3047** [comment] 2015-07-20 01:49
+1 for this issue, I have tried on both st and urxvt so it's definitely a fish issue.

**Comment by zanchey** [comment] 2015-07-20 05:05
This might be better since #2217 got merged; have you had a chance to try on a version newer than 2.2.0-65-ge7273e1 (i.e. built from master)?

**Comment by faho** [comment] 2015-07-20 08:18
I tested with 2.2.0.r55.g97edc96 (i.e. before 2217) and 2.2.0.r70.gdd4639e (after 2217), and I don't get a meaningful change. (Unfortunately I can't create a screenshot because of a bug in my screenshotting utility, will try to track that down)

**Comment by zanchey** [comment] 2015-09-29 08:12
http://eev.ee/blog/2015/09/12/dark-corners-of-unicode/ is good reading. `wcwidth` may be to blame here.

**Comment by krader1961** [comment] 2016-06-19 02:43
I cannot reproduce this using a fish built from git head as of this comment.  There have been a ton of changes related to how locales and unicode are handled since this issue was opened. Or even since the last update 11 months ago. It seems reasonable to conclude it has been fixed so I'm closing it. If someone can still reproduce using a fish built from current source feel free to reopen.

**Comment by z3ntu** [comment] 2016-07-20 08:52
@krader1961 I don't know if this is the exact same problem, but the newest git version still doesn't work with the characters üöä as expected. Video demonstration is here: https://youtu.be/vxAy0isw9Qc
I am using Konsole with the `fish-git` AUR (Arch Linux) package which I just compiled.

**Comment by faho** [comment] 2016-07-20 13:34
@z3ntu: This works for me, also with Konsole, also on Arch. What's your locale? Does this happen without history (try `sh -c 'env HOME=$(mktemp -d) fish'`)?

**Comment by z3ntu** [comment] 2016-07-20 15:05
Yes, same behaviour.
```
$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_DE.UTF-8
LC_TIME=en_DE.UTF-8
LC_COLLATE=C
LC_MONETARY=en_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Yes, I know, that en_DE.UTF-8 is neither a valid X11 locale nor does it actually exist somehow on my system. But I want to have my system on English and  my formats in German and that's why KDE sets my locale to this weird frankenstein monster of a locale.

**Comment by faho** [comment] 2016-07-20 15:18
>Yes, I know, that en_DE.UTF-8 is neither a valid X11 locale nor does it actually exist somehow on my system. But I want to have my system on English and my formats in German and that's why KDE sets my locale to this weird frankenstein monster of a locale.


That's the issue. When I set any locale variable to "en_DE.UTF-8", it starts failing. I'm guessing fish's setup here fails without an error. @krader1961: Can you confirm?

While I can only suggest, @z3ntu, that you set your locale variables to something sensible, as far as I can see we should still be able to read and echo characters properly as long as LC_CTYPE (or if that is unset LANG or LC_ALL) is set properly.

**Comment by z3ntu** [comment] 2016-07-20 17:14
```
LC_CTYPE="en_US.UTF-8"
```
Isn't it set correctly? Btw do you know how you can fix these en_DE things but retain the german formats in KDE?

**Comment by krader1961** [comment] 2016-07-20 23:14
You cannot set any of the locale env vars to  invalid values. Doing so causes the libc locale subsystem to fallback to a single-byte locale. That in turn causes fish to incorrectly calculate how many columns (cells) are taken up on the terminal by those wide characters. Since your terminal is still decoding the UTF-8 sequences into wide characters but fish is no longer doing so you see the behavior you observed.

This is really obvious on BSD systems. I cut and pasted your locale vars into a script, exported them, then started a new fish instance. Within that instance I ran the locale command. Here is what it output:

```
LANG="en_US.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

On Ubuntu (and presumably all GNU Linux systems) the output of `locale` obscures the problem:

```
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_DE.UTF-8
LC_TIME=en_DE.UTF-8
LC_COLLATE=C
LC_MONETARY=en_DE.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_DE.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

However, notice the first line of output. That's essentially telling you that you can't expect sane behavior given your combination of locale vars. On both systems fish treats each byte of those multibyte UTF-8 sequences as an individual character because that's what the libc locale subsystem is doing.

I can't explain why KDE isn't exhibiting weird behavior. Perhaps it's using a different locale API than the one in libc.

P.S., In the future please use asciinema rather than youtube videos.

**Closed by krader1961** 2016-07-20 23:14 UTC
Labels: bug

**Comment by z3ntu** [comment] 2016-07-21 07:03
![image](https://cloud.githubusercontent.com/assets/3768500/17013938/cb216e10-4f21-11e6-8d0b-062263c3909e.png)
This is how my KDE "Formats" settings window looks... I really don't know why it does this weird stuff...
