### ISSUE TITLE
Fish crashes on cd ""

### ISSUE THREAD

**Issue by AngryBeeSec** [fish-shell/fish-shell#8290] opened 2021-09-13 10:43 UTC
I am running 
Fish:
3.3.1
OS:
Linux 5.14.2-zen1-2-zen #1 ZEN SMP PREEMPT x86_64 GNU/Linux
Term:
xterm-256color

I have confirmed that this bug affects fish even without any third party extensions.

When I run the following command.
 cd ""
 
I am presented with this message.

terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)

Warning: Program '/usr/bin/fish' crashed.

**Comment by faho** [comment] 2021-09-13 11:14
Duplicate of #8147

**Closed by faho** 2021-09-13 11:14 UTC
