### ISSUE TITLE
(subcommand) doesn't work when first 

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2669] opened 2016-01-09 01:22 UTC
I had a command I used to run a lot on bash:

```
`drush sql-connect` < database.sql
```

In fish I know I can use subcommands but this particular command doesn't work when it is listed first:

`(drush sql-connect) < database.sql`

Is this a bug or works as intended and I should just figure out a different way of doing that?

**Comment by krader1961** [comment] 2016-01-09 03:27
Put the redirect inside the subcommand:

```
(drush sql-connect < database.sql)
```

Also, what you wrote doesn't work under bash if I simply replace your drush command with cat. So I suspect you're leaving out some details. I think this is working as intended.

**Comment by ElijahLynn** [comment] 2016-01-09 03:44
Thanks for the reply.

(drush sql-connect < database.sql) does not work either, the command doesn't produce an error and $status = 0. But the command does not execute and turns red.

The command works as specified in bash. And is also in the drush documentation as such, see example here http://drushcommands.com/drush-8x/sql/sql-connect/.

The command `drush sql-connect` returns a valid database connection string. So it should output ` mysql --database=sandbox_database --host=localhost --user=root --password=pass`.

**Comment by ElijahLynn** [comment] 2016-01-09 03:51
If I do a `drush sql-connect < database.sql` in Fish, it makes it as far as printing the database connection string on the return but does not seem to execute the string to get the redirect.

**Comment by ridiculousfish** [comment] 2016-01-09 05:42
In bash, ``` `drush sql-connect` < database.sql``` should run the command `drush sql-connect`, take its output, and run that again as a string. You have to be explicit about that in fish. Try:

    eval (drush sql-connect) "< database.sql"

**Comment by krader1961** [comment] 2016-01-09 05:56
> In bash, `drush sql-connect` < database.sql runs the command drush sql-connect, captures its output, and runs that output again as a string. This is a pretty weird thing to want to do,...

Aha! I see I misunderstood what the original poster was trying to do precisely because it is a pretty weird thing to do. In my 30+ years using UNIX like operating systems I do not recall having ever come across something like that let alone wanted to do something like it. This is yet another excellent example for why fish should not emulate bash/ksh/zsh.

**Comment by ridiculousfish** [comment] 2016-01-09 06:20
Yup :+1:

**Comment by faho** [comment] 2016-01-09 13:59
This is a duplicate of #2427. Let's try to keep the discussion there.

Regarding the `(something) < somefile`, see also #1786.

**Closed by faho** 2016-01-09 13:59 UTC

**Comment by ElijahLynn** [comment] 2016-01-14 01:33
`eval (drush sql-connect) < database.sql` works nicely, no quotes were needed.
