### ISSUE TITLE
Pipe non-existent file to stdin freezes fish

### ISSUE THREAD

**Issue by hayabusa2yk** [fish-shell/fish-shell#7331] opened 2020-09-13 15:49 UTC
```sh
cat | echo < a
```
This freezes the fish shell and CPU usage goes to 100%.
If I use a terminal emulator(Alacritty), simply it exits.
On the bash shell, Behavior is the same as `cat | echo`.
OS: Arch Linux(Fish installed using Pacman, no other shell customization)

`fish --version`:
```
fish, version 3.1.2
```

`echo $version`:
```
3.1.2
```

`uname -a`:
```
Linux Kuro 5.8.8-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 09 Sep 2020 19:01:48 +0000 x86_64 GNU/Linux
```

`echo $TERM`:
```
alacritty
```

> Please tell us if you tried fish without third-party customizations
Yes

**Comment by faho** [comment] 2020-09-13 16:06
Duplicate of #7038

**Closed by faho** 2020-09-13 16:06 UTC
