### ISSUE TITLE
Incorrect path when launched from Visual Code

### ISSUE THREAD

**Issue by rikvanderkemp** [fish-shell/fish-shell#5731] opened 2019-03-09 16:36 UTC
fish, version 3.0.1
Linux  4.19.24-1-MANJARO #1 SMP PREEMPT Wed Feb 20 22:59:23 UTC 2019 x86_64 GNU/Linux

This is a bit of an oddball. You can launch an integrated terminal from Visual Code. 
It should navigate to the current working directory of your current project.
This worked fined until release 3.0.1. However, I though it might have been an issue with Visual Code as I read that there is someone else experiencing similar issues with other shells (https://github.com/Microsoft/vscode/issues/69954).

However, when I downgraded to version 3.0.0 the integrated terminal behaved correctly again.

**Correct behavior 3.0.0**
![3 0 0](https://user-images.githubusercontent.com/347308/54074351-ba9c3000-4291-11e9-9089-7bff0948c8cf.gif)

**3.0.1**

![3 0 1](https://user-images.githubusercontent.com/347308/54074338-92accc80-4291-11e9-8a13-e8d3d201a45b.gif)

**Comment by faho** [comment] 2019-03-09 16:39
Upgrade to 3.0.2.

This is a duplicate of #5647.

**Closed by faho** 2019-03-09 16:39 UTC
