### ISSUE TITLE
`fish_config` Does Not Save Abbreviations

### ISSUE THREAD

**Issue by zedseven** [fish-shell/fish-shell#9680] opened 2023-03-23 06:25 UTC
Fish version: 3.6.0
OS: Arch Linux x86_64 GNU/Linux

Recently, I haven't been able to save new abbreviations using `fish_config`. I'm not sure when this became a problem exactly, since I don't regularly edit my abbreviations, but I saw @dunstorm also recently reported the same issue in the same version, on the closed issue #4357.

I am able to change my Fish theme using `fish_config`, so it seems like it may be specific to the abbreviations.

When setting abbreviations, `fish_config` doesn't output any errors and the output looks normal:
```
$ fish_config
Web config started at file:///tmp/web_configrxnutz20.html
If that doesn't work, try opening http://localhost:8000/20efbe1262cae6527cf0222a4a3e6a83/
Hit ENTER to stop.
$ set -L
$ abbr --show
$ abbr --add 'skim' 'sk'
$ abbr --add 'fzf' 'sk'

Shutting down.
```

**Comment by zedseven** [comment] 2023-03-23 06:27
When running the command `abbr --add 'skim' 'sk'` manually, the abbreviation was added successfully.

This seems to be an issue specifically with `fish_config`.

**Comment by faho** [comment] 2023-03-23 07:06
Duplicate of #9460

**Comment by faho** [comment] 2023-03-23 07:07
Please see the [CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst#deprecations-and-removed-features-1):

    Abbreviations are no longer stored in universal variables. Existing universal abbreviations are still imported, but new abbreviations should be added to config.fish.

This renders the fish_config abbreviations tab non-functional, we unfortunately forgot to remove it.

**Closed by faho** 2023-03-23 07:06 UTC

**Comment by zanchey** [comment] 2023-03-23 08:16
Sorry, I was hoping to have 3.6.1 out by now
