### ISSUE TITLE
Nondeterministic "Array index out of bounds" error if you open multiple `fish` shells at once.

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#2820] opened 2016-03-14 22:30 UTC
If your config file contains a lot of abbreviations, launching a bunch of `fish` shells in quicks succession can trigger a race condition that causes an `Array index out of bounds` error.

### Reproduction Steps:

- 1. Change `config.fish` to contain the following:

`config.fish`:

    abbr -a "carrots1" "ls"
    abbr -a "carrots2" "ls"
    abbr -a "carrots3" "ls"
    abbr -a "carrots4" "ls"
    abbr -a "carrots5" "ls"
    abbr -a "carrots6" "ls"
    abbr -a "carrots7" "ls"
    abbr -a "carrots8" "ls"
    abbr -a "carrots9" "ls"
    abbr -a "carrots10" "ls"
    abbr -a "carrots11" "ls"
    abbr -a "carrots12" "ls"
    abbr -a "carrots13" "ls"
    abbr -a "carrots14" "ls"
    abbr -a "carrots15" "ls"
    abbr -a "carrots16" "ls"
    abbr -a "carrots17" "ls"
    abbr -a "carrots18" "ls"
    abbr -a "carrots19" "ls"
    abbr -a "carrots20" "ls"
    abbr -a "carrots21" "ls"
    abbr -a "carrots22" "ls"

- 2. Launch a whole bunch of two `fish` shells in quick succession.

### Expected behavior:

The shell always initializes without problem.

### Observed behavior:

*Some* of the new shells *sometimes* run into this error:

> Array index out of bounds
> /usr/local/Cellar/fish/2.2.0/share/fish/functions/abbr.fish (line 12):    __fish_abbr_parse_entry $fish_user_abbreviations[$i] key_i
>                                                                                                                             ^
> in function '__fish_abbr_get_by_key'
>   called on line 2 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/abbr.fish
>   with parameter list 'carrots2'
> 
> in command substitution
>   called on line 0 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/abbr.fish
> 
> in function 'abbr'
>   called on line 2 of file ~/.config/fish/config.fish
>   with parameter list '-a carrots2 ls'
> 
> from sourcing file ~/.config/fish/config.fish
>   called during startup
> 
> Array index out of bounds
> /usr/local/Cellar/fish/2.2.0/share/fish/functions/abbr.fish (line 12):    __fish_abbr_parse_entry $fish_user_abbreviations[$i] key_i
>                                                                                                                             ^
> in function '__fish_abbr_get_by_key'
>   called on line 2 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/abbr.fish
>   with parameter list 'carrots2'
> 
> in command substitution
>   called on line 0 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/abbr.fish
> 
> in function 'abbr'
>   called on line 2 of file ~/.config/fish/config.fish
>   with parameter list '-a carrots2 ls'
> 
> from sourcing file ~/.config/fish/config.fish
>   called during startup
> 
> Welcome to fish, the friendly interactive shell
> Type help for instructions on how to use fish
> lgarron@lgarron-macbookpro ~>
> 

<img width="1194" alt="screen shot 2016-03-14 at 15 25 27" src="https://cloud.githubusercontent.com/assets/248078/13761991/4b545bf8-e9f9-11e5-811f-2bf65f8ed436.png">

The error is not always for the same abbreviation(s).

---
Operating system: `OSX 10.11.3`, installed `fish` using Homebrew

Terminal or terminal emulator: `iTerm2` (`Build 2.9.20160313`)

**Comment by lgarron** [comment] 2016-03-14 22:33
In case it helps to know a "real-world" example, I run into this with the abbreviations in my [`chrome.fish`](https://github.com/lgarron/dotfiles/blob/master/dotfiles/chrome/.config/fish/chrome.fish) dotfile.

**Comment by faho** [comment] 2016-03-14 22:39
This is a duplicate of #2664, I think, which should be fixed in the next fish release.

The issue was we were re-writing abbreviations on startup, which we don't do any longer (also because that was slow).

**Closed by faho** 2016-03-14 22:39 UTC

**Comment by faho** [comment] 2016-03-14 22:40
Thanks for the elaborate information, though. This is a quality bug report!

**Comment by lgarron** [comment] 2016-03-14 23:39
Interesting, I couldn't find #2664 by searching for "Array index out of bounds" in issues.
Great to know it's addressed; thanks!
