### ISSUE TITLE
Incorrect coloring for autosuggestion in emacs ansi-term

### ISSUE THREAD

**Issue by sandric** [fish-shell/fish-shell#3310] opened 2016-08-18 16:21 UTC
**fish version installed** _fish, version 2.3.1_

**terminal version** _GNU Emacs 25.1.50.1 ansi-term_
## Reproduction steps

If I use fish shell in iterm2 (build 3.0.8) - everything is great, I use default fish theme and coloring is working as needed - first entered characters if autosuggestion exists are blue and suggestion in gray. If there is no any suggestion for entered characters - its color is red. 

But when I try the same in emacs in `ansi-term`, with raw emacs that started with `emacs -Q`, the coloring is not working for autosuggestion - no matter if suggestion exist or not, its always black color, not blue or red. The strange thing is that if I press tab to show autocompletion list, its list is displayed with proper coloring. Here's the screenshot.

![Image of ansi-term](https://i.imgur.com/UUSf7AE.png)
![Image of ansi-term](https://i.imgur.com/cKB2lDi.png)

Mine terminal env variables inside ansi-term are those:

```
sandric@sandric-mac ~> env | grep TERM
ITERM_PROFILE=sandric
ITERM_SESSION_ID=w0t0p1:1F0EBADA-D06D-44C4-A237-9CE9B919569E
TERM=eterm-color
TERMCAP=eterm-color:li#33:co#80:cl=\E[H\E[J:cd=\E[J:bs:am:xn:cm=\E[%i%d;%dH:nd=\
E[C:up=\E[A:ce=\E[K:ho=\E[H:pt:al=\E[L:dl=\E[M:DL=\E[%dM:AL=\E[%dL:cs=\E[%i%d;%d
r:sf=^J:dc=\E[P:DC=\E[%dP:IC=\E[%d@:im=\E[4h:ei=\E[4l:mi::so=\E[7m:se=\E[m:us=\E
[4m:ue=\E[m:md=\E[1m:mr=\E[7m:me=\E[m:UP=\E[%dA:DO=\E[%dB:LE=\E[%dD:RI=\E[%dC:kl
=\EOD:kd=\EOB:kr=\EOC:ku=\EOA:kN=\E[6~:kP=\E[5~:@7=\E[4~:kh=\E[1~:mk=\E[8m:cb=\E
[1K:op=\E[39;49m:Co#8:pa#64:AB=\E[4%dm:AF=\E[3%dm:cr=^M:bl=^G:do=^J:le=^H:ta=^I:
se=\E[27m:ue=\E[24m:kb=^?:kD=^[[3~:sc=\E7:rc=\E8:r1=\Ec:                       
TERMINFO=/usr/local/Cellar/emacs/HEAD/share/emacs/25.1.50/etc/
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.0.8
TERM_SESSION_ID=w0t0p1:1F0EBADA-D06D-44C4-A237-9CE9B919569E
```

`tput colors` gives 8.
## Expected results

I know that ansi-term is not 24 bit coloring and have only 8 colors but when I try to test echoing ansi color sequences for blue and red on first screenshot colors displayed right. And as I understood fish will degrade to your terminal coloring system, which it does on enabling autocomplete list hitting `<tab>` on second screenshot, but somehow failing to do the same for blue and red in in-line autosuggestion. 

So I guess its a bug and fish should display colors properly?

**Comment by krader1961** [comment] 2016-08-18 17:16
See issues #2441, #2983, and #3282. Pretty confident this is a duplicate of those issues and there isn't a bug in fish as we've covered this ground several times.

**Comment by floam** [comment] 2016-08-18 17:59
If you want to try out #3260 and let me know what effect (positive or negative) it has, that'd be useful @sandric.

**Comment by sandric** [comment] 2016-08-18 18:18
@krader1961 Just to clear about setting up terminfo - I tried it right away and it didn't helped. I saw those issues, but I thought that its an issue with `4m` characters and not my coloring problems since I have no such behavior and looks like it helped to fix those `4m` issues to other people.

@floam, Yes, sure! Do I need to do anything to setup or just build pr locally and try to run in ansi-term?

**Comment by floam** [comment] 2016-08-18 19:09
That should be it. Compile it, load it up, and let me know if the behavior changes with color output.

**Comment by sandric** [comment] 2016-08-18 21:56
Hm, looks like nothing changed.. Mb I did smth wrong, so here's steps I made:
* clone fish repo
* run `git fetch origin pull/3260/head:coloring-test`
* run `xcodebuild build`
* start emacs
* run `ansi-term` in emacs
* in command to run enter `~/fish-shell/build/Release/fish`

And there's no changes at all - the same no color differentiating in inline autosuggestion.
I also tried to tried to delete `.terminfo` directory, and regenerate one - all the same.

**Comment by floam** [comment] 2016-08-18 22:05
> git fetch origin pull/3260/head:coloring-test 

This didn't change the code in the working directory. You'd can do a `git merge coloring-test` after to merge it into master. If you run into issues with it doing the merge (should just work) you can just do `git checkout coloring-test`.

**Comment by sandric** [comment] 2016-08-18 22:08
Oh, no I ment I checked out after I pulled pr, of course, I just forgot to place it into list above. Yeah, it would be dumb to compile head). No, I compiled code with your last three commits from pr.

**Comment by sandric** [comment] 2016-08-19 15:16
As a quick fix for such coloring bug in emacs ansi-term, here's what I add to my `config.fish`:
```fish
if test $TERM = "eterm-color"
        set -g fish_color_normal normal
        set -g fish_color_command blue
        set -g fish_color_quote blue
        set -g fish_color_redirection normal
        set -g fish_color_end yellow
        set -g fish_color_error red
        set -g fish_color_param cyan
        set -g fish_color_comment red
        set -g fish_color_match cyan
        set -g fish_color_operator cyan
        set -g fish_color_escape cyan
        set -g fish_color_cwd green
        set -g fish_color_autosuggestion cyan
        set -g fish_color_user green
        set -g fish_color_host normal
        set -g fish_color_history_current cyan
        set -g fish_color_selection blue
        set -g fish_color_status magenta
        set -g fish_pager_color_prefix cyan
        set -g fish_pager_color_completion magenta
        set -g fish_pager_color_description normal
        set -g fish_pager_color_progress green
end
```
I took it from [here](https://github.com/fish-shell/fish-shell/blob/790968120d280443be17737c73ff13928a633a37/share/functions/__fish_config_interactive.fish#L273), which is as I get simple workaround for 8 colors terminals in pure linux tty. The only thing that I did not figured out how to change is background color for pager's selected item or match in history - the same magenta background, but I haven't figured it out how to change it even  in normal iterm2, looks like there was an issue #2878 but I don't saw the solution there. But it works for me, basically, will wait for @floam #3260 merged and try it out.

**Comment by faho** [comment] 2016-08-19 16:04
@sandric: What's your value for $fish_term24bit? See d68320a3c670d1da30bee532ef5c6c72aa9ac477.

Does it work if you `set -e fish_term24bit`?

We might want to explicitly unset it if we're in known-broken term-in-terms (seemingly everything but tmux).

**Comment by faho** [comment] 2016-08-19 16:21
Okay, that's _probably_ not it - we don't export that variable, so it shouldn't be inherited anyway. The issue that caused d68320a was that we set it depending on some exported variables.

It's most likely something much simpler - the color you are using is probably rounded to black. Can you confirm that `set_color $fish_color_autosuggestion | od -t x1z` in emacs prints ">.[30m<" (where the "." stands in for an escape character)? What is $fish_color_autosuggestion set to?

This would then be fixed with #3260. I just confirmed that a color of "006363" will currently come out black, but with that PR will come out cyan (\\e\\[36m).

**Comment by floam** [comment] 2016-08-19 16:42
> This would then be fixed with #3260. I just confirmed that a color of "006363" will currently come out black, but with that PR will come out cyan (\e\[36m).

Where does it appear black?

**Comment by faho** [comment] 2016-08-19 16:43
In ansi-term, a `set_color 006363` will currently print \\e\\[30m, i.e. black.

**Comment by sandric** [comment] 2016-08-19 16:45
@faho Ok, I checked, my `echo $fish_color_autosuggestion` is `555` but `set_color $fish_color_autosuggestion | od -t x1z` gives me an error:
```
sandric@sandric-mac ~> set_color $fish_color_autosuggestion | od -t x1z
od: z: unrecognised format character
sandric@sandric-mac ~> set_color $fish_color_autosuggestion | od -t x1
0000000    1b  5b  33  38  3b  32  3b  38  35  3b  38  35  3b  38  35  6d
0000020
```

**Comment by floam** [comment] 2016-08-19 16:52
Hey, you're right. My branch is doing better with TERM=ansi, I can see, for a variety of RGB colors. Didn't notice that prior, great. `(set_color 550000;echo foo) | xxd` is also going to 31, red, while master is.. also black.

**Comment by faho** [comment] 2016-08-19 17:26
> 1b  5b  33  38  3b  32  3b  38  35  3b  38  35  3b  38  35  6d

@sandric: Uhm, that is "\e[38;2;85;85;85m" - i.e. the full-fledged truecolor sequence. Did you run that in iTerm? Please run it again in ansi-term.

**Comment by floam** [comment] 2016-08-19 17:31
That's the escape you'd expect to see if 24bit mode is forced on, even if he's in `ansi-term` - really, I think it was a bad idea to make the only way to use it be a force-on-everywhere (except the exceptions we've been adding) setting, given how it tends to mess stuff up and how universal variables work.

**Comment by faho** [comment] 2016-08-19 17:34
>how universal variables work.

It's not universal by default, and you can disable it by setting it to "0".

Really, it's annoying that ncurses doesn't just add this so we can rely on that.

I mean I'd agree to a change that ignored fish_term24bit = 1 if the terminal supports less than 256 colors, but I can't really see how to support it perfectly.

**Comment by sandric** [comment] 2016-08-19 17:37
@faho No, I ran it on ansi-term, as @floam suggested, I ran just ran it without resetting fish colors I described above, here's commands output if I fix colors with that color variables setting in config.fish, its truly sets full sequences if not reset them:
```
sandric@sandric-mac ~> echo $fish_color_autosuggestion
cyan
sandric@sandric-mac ~> set_color $fish_color_autosuggestion | od -t x1z
od: z: unrecognised format character
sandric@sandric-mac ~> set_color $fish_color_autosuggestion | od -t x1
0000000    1b  5b  33  36  6d                                            
0000005
sandric@sandric-mac ~> env | grep term
INSIDE_EMACS=25.1.50.1,term:0.96
TERM=eterm-color
TERMCAP=eterm-color:li#60:co#96:cl=\E[H\E[J:cd=\E[J:bs:am:xn:cm=\E[%i%d;%dH:nd=\E[C:up=\E[A:ce=\E[K
:ho=\E[H:pt:al=\E[L:dl=\E[M:DL=\E[%dM:AL=\E[%dL:cs=\E[%i%d;%dr:sf=^J:dc=\E[P:DC=\E[%dP:IC=\E[%d@:im
=\E[4h:ei=\E[4l:mi::so=\E[7m:se=\E[m:us=\E[4m:ue=\E[m:md=\E[1m:mr=\E[7m:me=\E[m:UP=\E[%dA:DO=\E[%dB
:LE=\E[%dD:RI=\E[%dC:kl=\EOD:kd=\EOB:kr=\EOC:ku=\EOA:kN=\E[6~:kP=\E[5~:@7=\E[4~:kh=\E[1~:mk=\E[8m:c
b=\E[1K:op=\E[39;49m:Co#8:pa#64:AB=\E[4%dm:AF=\E[3%dm:cr=^M:bl=^G:do=^J:le=^H:ta=^I:se=\E[27m:ue=\E
[24m:kb=^?:kD=^[[3~:sc=\E7:rc=\E8:r1=\Ec:                                                         
```

**Comment by floam** [comment] 2016-08-19 17:40
You need to unset the option that forces 24-bit colors - `set -e fish_term24bit`

**Comment by floam** [comment] 2016-08-19 17:43
> It's not universal by default, and you can disable it by setting it to "0".

Sure - but if you want a to make something persistent in fish - you set it it with -U.

I kind of like the idea of having a function that enables it more - what it could do is record what their $TERM is and just whitelist that one for them.

**Comment by sandric** [comment] 2016-08-19 17:55
@floam Oh, yes, you are right, I just tried to run `set -e fish_term24bit` and looks like it displays colors correctly without tweaking config.fish. I'm little bit confused though about that var, so I should set it and its how its suppose to work?

**Comment by floam** [comment] 2016-08-19 18:03
> I'm little bit confused though about that var, so I should set it and its how its suppose to work?

What you just did with -e is erase it - it looks like it was set in the past. What it does is forces "millions of colors" mode for very advanced terminals. You likely encountered it in the documentation here: https://fishshell.com/docs/current/commands.html#set_color-detection or followed advice from someone on the mailing list or some such: http://fish-users.narkive.com/cqYaOVNY/terminal-emulator#post6

I'd just leave it off.

**Comment by krader1961** [comment] 2016-12-29 03:08
Since there haven't been any updates in four months I'm going to assume this is resolved. If that isn't the case, @sandric, please feel free to reopen.

**Closed by krader1961** 2016-12-29 03:08 UTC
Labels: question
