### ISSUE TITLE
git --work-tree=$HOME hangs on autocomplete

### ISSUE THREAD

**Issue by chamini2** [fish-shell/fish-shell#9246] opened 2022-09-29 15:30 UTC
```
3.5.1

Darwin MattBookAir.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:07 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8110 arm64
xterm-256color
```

*****

I have an alias for handling my dotfiles

```
alias config 'git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
````

which is used like

```
config add ~/.config/fish/custom/my_function.fish
config commit -m "added my_function function"
config push
```

from any working directory and it works.

To avoid config showing ALL of my home when I do `config status`, I also did

```
config config --local status.showUntrackedFiles no
```

So... when I am wanting to add a new file to my config repo:

```
config add ~/.config/fish/custom/<TAB>
```

it get's stuck forever, instead of giving me options or at least giving me back control of the prompt.

[asciinema recording](https://asciinema.org/a/b3IUkMODf70OUM77o36yBDrVM)

*****

I just checked and the same happens with `git --git-dir=$HOME/.cfg/ --work-tree=$HOME` directly, and the problem seems to be `--work-tree=$HOME`. Any ideas?

**Comment by faho** [comment] 2022-09-29 15:48
Duplicate of #8207

You're asking git to scan gigabytes of data. That's slow, because it's a big task.

No, I do not believe there is anything we can do here.

**Closed by faho** 2022-09-29 15:48 UTC
