### ISSUE TITLE
Conda manager stopped working in fish shell (hangs forever).

### ISSUE THREAD

**Issue by tastyminerals** [fish-shell/fish-shell#6971] opened 2020-05-06 08:10 UTC
### current system 
**fish version** `3.1.1`

 **uname -a** `Linux pavel-p6567hshp 5.5.19-1-MANJARO #1 SMP PREEMPT Tue Apr 21 08:12:19 UTC 2020 x86_64 GNU/Linux`

**echo $TERM** `xterm-256color`

No third-party tools.

### problem
Issuing any of the below hangs forever.
```
conda create -n myenv python=3.8
conda update --all
conda remove --all
```
`Ctrl+C` reveals that there was some output:

```
^CCollecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/pavel/miniconda3/envs/torch

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    certifi-2020.4.5.1         |           py38_0         156 KB
    ncurses-6.2                |       he6710b0_1         817 KB
    openssl-1.1.1g             |       h7b6447c_0         2.5 MB
    pip-20.0.2                 |           py38_1         1.7 MB
    python-3.8.2               |       hcf32534_0        49.6 MB
    setuptools-46.1.3          |           py38_0         523 KB
    sqlite-3.31.1              |       h62c20be_1         2.0 MB
    wheel-0.34.2               |           py38_0          51 KB
    ------------------------------------------------------------
                                           Total:        57.3 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py38_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.0.2-py38_1
  python             pkgs/main/linux-64::python-3.8.2-hcf32534_0
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-46.1.3-py38_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)?
CondaSystemExit:
Operation aborted.  Exiting.
```

The same operations work without problem in `zsh` if I switch to it.

Strange thing is that `conda` was working before. I played with **omf** a little by simply installing it and adding a theme. Then when I couldn't run conda anymore, I uninstalled omf and fish one by one. Installed fish back by nothing changed :( Could it be connected with omf?

**Comment by faho** [comment] 2020-05-06 11:50
Please upgrade to 3.1.2, this smells like a duplicate of #6955.

Closing for now, if you can reproduce with 3.1.2 we'll reopen.

**Closed by faho** 2020-05-06 11:50 UTC
