### ISSUE TITLE
Task cannot be backgrounded

### ISSUE THREAD

**Issue by ZeusThundr** [fish-shell/fish-shell#10019] opened 2023-09-14 16:55 UTC
fish version: [fish-git](https://aur.archlinux.org/packages/fish-git) 3.6.1-864-g778f4e673 I have also tried release 3.6.1
terminfo: xterm-256color
kernel: Linux 6.4.10-tkg-pds
I have tried fish without third-party customizations
asciinema: [recording](https://asciinema.org/a/kXecBOrwrmvKAWDYKkB3tiM8M)
 
On **Line 18** the fish will not background the task and the rest of the code will not execute until I SIGINT twice
It seem like it is waiting for input not sure though I'm new to scripting this script is ported over from [lfimg](https://github.com/thimc/lfimg/blob/master/lfrun)
even if It did work exec on **line 20** will not take file descriptors [3948](https://github.com/fish-shell/fish-shell/issues/3948)

A bit unrelated but I didn't want to make multiple issues why does in fish `cat (ping -c 4 google.com | psub)` wait for the ping command to finish before catting the output; While in bash `cat <(ping -c 4 google.com)` outputs as the contents of ping immediately as they are received.

You need [ueberzug](https://github.com/ueber-devel/ueberzug) and [lf- file manager](https://github.com/gokcehan/lf) to test this script. If you would like full functionality you will also need to install [lfimg](https://github.com/thimc/lfimg)
```fish
   1   │ #!/usr/bin/env fish
   2   │
   3   │ function cleanup --on-signal SIGINT
   4   │     exec 3>&-
   5   │     rm $FIFO_UEBERZUG
   6   │ end
   7   │
   8   │ function lfimg
   9   │     set -f CACHE $HOME/.cache/lf
  10   │     if test $SSH_CLIENT || test $SSH_TTY
  11   │         command lf $argv
  12   │     else
  13   │       if not test -d $CACHE
  14   │         mkdir --parents $CACHE
  15   │       end
  16   │       set -gx FIFO_UEBERZUG $CACHE/ueberzug-$fish_pid
  17   │       mkfifo $FIFO_UEBERZUG
  18   │       ueberzug layer -s < $FIFO_UEBERZUG -p json & # Function stops here and will not background task
  19   │       # ueberzug layer -s < (mkfifo $FIFO_UEBERZUG | psub -F) -p json &
  20   │       exec 3> $FIFO_UEBERZUG
  21   │       # trap cleanup EXIT SIGINT
  22   │       command lf $argv 3>&-
  23   │   end
  24   │ end
  25   │
  26   │ lfimg
```

**Comment by faho** [comment] 2023-09-14 18:00
What does `type ueberzug` say? If it is a function: Fish currently cannot background anything other than simple commands.

If it is not that I would quite like to ask you to try to reduce the problem so it is easier to reproduce.

**Comment by ZeusThundr** [comment] 2023-09-15 09:39
`type ueberzug` outputs `ueberzug is /usr/bin/ueberzug`
I have to admit my understanding is quite limited, since I simply did my best effort to port the script over to fish and did not create it. it might be related to the behavior I noted with `cat (ping -c 4 google.com | psub)` in the first comment. Thank you for your timely response.
the issue is reproducible with the following script
```fish
#!/usr/bin/env fish
mkfifo file
ls > file &
cat < file
```

**Comment by faho** [comment] 2023-09-15 10:11
Duplicate of #7422

**Closed by faho** 2023-09-15 10:11 UTC
Labels: needs more info
