### ISSUE TITLE
First letter shifted when copy pasting from the mouse

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5373] opened 2018-11-28 18:57 UTC
fish, version 2.7.1-1748-g5615351f  (on server) and 2.7.1 (in local)
linux ubuntu 14.04 on local with gnome-terminal
linux debian 9 on remote SSH

When I press the middle button to copy from local to remote server (or when I right click + "paste"), it does this:

http://image.noelshack.com/fichiers/2018/48/3/1543431247-bug-fish.jpg
([other link](http://www.noelshack.com/2018-48-3-1543431247-bug-fish.jpg))

it shifts the first letter on the left, like a shadow of the first letter

I don't have this in local (using same theme) and it happens on nightly build but also official 2.7.1.

**Comment by faho** [comment] 2018-11-29 09:32
Duplicate of #5059, #4539, #4609 and numerous other issues, including your very own #5221.

The issue is that your host fish (the one on the server) is still 2.7.1, which has the bad wcwidth. The client fish is irrelevant here, because that's not currently running.

**Comment by BarbzYHOOL** [comment] 2018-11-29 17:53
omg i'm sorry i wrote the wrong thing!!!

it's fish, version 2.7.1-1748-g5615351f (on server)

**Comment by faho** [comment] 2018-11-29 18:11
>seems like it's a different issue

Probably not. What we need to figure out then is if this is specific to any character. If you temporarily replace your prompt with just a simple "$", via `function fish_prompt; echo '$'; end`, and you then just paste "abc", does this still reproduce?

From there, you'll have to add more characters to try to reproduce it.

My guess is that it's still the same underlying issue. Fish and the terminal need to agree on character width. The terminal here is old, built on an old glibc. In particular Ubuntu 14.04 is from before glibc 2.26, which means it doesn't support Unicode 9. That means any of the newer emoji are right out.

There really isn't a good fix there. If you've built fish with the included wcwidth (which is the default), then you can set $fish_emoji_width and $fish_ambiguous_width to 1 or 2, respectively. That could potentially work but will still break if the terminal is just plain wrong (and I've seen e.g. some terminals printing a zero-width space with a non-zero width).

As long as the terminal is on the same system, this can be worked around by using the system's wcwidth, but that won't work if you're on two systems via something like ssh.

So, to a certain extent, the answer here needs to be that terminals need to be fixed.

**Comment by BarbzYHOOL** [comment] 2018-11-29 18:48
`function fish_prompt; echo '$'; end` ==> no bug

`set fish_emoji_width 1` etc... don't change anything


So I could try with another terminal? (btw it's surprising to me that terminals still have big bugs like this in 2014-2018)

**Comment by faho** [comment] 2018-11-29 18:50
>function fish_prompt; echo '$'; end ==> no bug

That means there is _some_ character there that causes issues.

>btw it's surprising to me that terminals still have big bugs like this in 2014-2018

Unicode 9 is from 2016.

**Comment by BarbzYHOOL** [comment] 2018-11-29 19:54
> That means there is some character there that causes issues.

How can I identify it? prob one of the icon here (I found them in my "caracters table" on ubuntu)? http://image.noelshack.com/fichiers/2018/48/4/1543521187-myfish.png

**Comment by faho** [comment] 2018-11-29 20:38
>prob one of the icon here

Probably.

Try removing all of them. Does the problem occur? If not, then one or more of them causes it. Try them one at a time and see which of them does. Replace the offenders with something else as a workaround.

**Comment by BarbzYHOOL** [comment] 2018-11-29 20:56
> Replace the offenders with something else as a workaround.

nooooooooooooooooooooooo :'(
another method? like maybe add the fonts to the remote server ? if the icons are from fontawesome as I suspect it (kinda makes no sense I guess)

I replaced ALL my icons cause I had many and now it's not buggy anymore but it looks awful now (replaced with letters). I suppose I would have the same issue with bobthefish theme?

**Comment by faho** [comment] 2018-11-29 21:18
>like maybe add the fonts to the remote server ?

The fonts used are the local ones.

>I suppose I would have the same issue with bobthefish theme?

You would have the same issue with every character that the Ubuntu 14.04 glibc does not correctly handle.

>another method?

Upgrade your local OS. Not a bad idea anyway, considering that Ubuntu 14.04 is almost EOL.

However, you'd have to upgrade to 18.04 - 16.04 is _not_ enough.

Alternatively, considering that the server _and_ the local OS are pre-Unicode 9, try building fish against the system wcwidth - `cmake -DINTERNAL_WCWIDTH=OFF`. It's possible that that's wrong equally on both machines, so while things aren't right, they're at least consistent.

**Comment by BarbzYHOOL** [comment] 2018-11-29 21:37
Ok i need to update ubuntu I know :P

I tested 4 different terminals and they all have the same exact bug. So it's more related to that glibc rather than the terminal itself?

And I use the nightly build for fish, so I'm not compiling it myself.

**Comment by faho** [comment] 2018-11-30 19:46
>So it's more related to that glibc rather than the terminal itself?

Yes.

>And I use the nightly build for fish, so I'm not compiling it myself.

If you did compile yourself, you could try using the system's (i.e. glibc's) wcwidth. Like I said, that has a chance of succeeding (by failing on both ends the same way).

**Comment by ridiculousfish** [comment] 2018-12-01 21:34
If we can figure out what character this is that would be very helpful.

**Comment by BarbzYHOOL** [comment] 2018-12-01 23:42
I just noticed that if I connect with ssh -X and I copy paste with ctrl+v it works fine
But if I paste with the middle mouse button aka right click "paste", then it shifts the letter

**Comment by ridiculousfish** [comment] 2018-12-03 00:49
Paste what?

**Comment by BarbzYHOOL** [comment] 2018-12-03 17:14
Anything

**Comment by faho** [comment] 2018-12-08 15:08
Uhm... do you see the second to fourth of these on your system?

Because I see those replacement boxes that display the character codes.

They are  U+F24D, U+E3AA and U+F24A, all of which are "private use" characters. Because they have no definition, they don't have a defined width.

Fish's own wcwidth classifies them as "ambiguous", which means in fish 3.0 (and the nightly builds) with the included wcwidth you can set `fish_ambiguous_width` to e.g. 1 or 2, depending on how wide these display.

**Comment by faho** [comment] 2018-12-08 18:32
>So it's only these 3 characters?

The other characters could still cause issues with your old wcwidth.

>I tried to set -l fish_ambiguous_width 1 and 2 and it still bugs

To be clear: That was with the nightly fish from the PPA?

If you do

```fish
printf '%s\n' aaa ✘    ➗ ⎇ ╰ ─ ╭
```

how many "a" wide are those characters?

**Comment by BarbzYHOOL** [comment] 2018-12-08 19:14
fish, version 2.7.1-1785-g88f7d506

They are 2 a wide, I can select them in half (approximatively) while the ✘ is only one char long

Need a screenshot?

**Comment by faho** [comment] 2018-12-08 19:55
>Need a screenshot?

It would be useful, yeah.

>fish, version 2.7.1-1785-g88f7d506

And that's directly from the PPA?

>They are 2 a wide, I can select them in half (approximatively) while the ✘ is only one char long

The "✘" is probably okay. The others need fish_ambiguous_width of 2, then.

This is still extremely easy to break - if you have any more private use characters with a different width, it'll break then. The best idea is to not use them. So I'd definitely suggest throwing those three characters out.

**Comment by BarbzYHOOL** [comment] 2018-12-08 21:09
> And that's directly from the PPA?
yes

Screenshot http://image.noelshack.com/fichiers/2018/49/6/1544303266-bug.jpg

**Closed** 2019-01-26 20:48 UTC
Labels: needs more info

**Comment by BarbzYHOOL** [comment] 2019-01-31 18:02
I sent the screenshot though :'(

**Comment by faho** [comment] 2019-01-31 19:11
Sorry, I meant to send a comment!

The problem here is that the directory symbols are private use characters, so they have ambiguous width, but the ╰ ─ ╭ also have ambiguous width.

Only on your system the former are two wide and the latter one.

So unfortunately this is unsupportable. Sorry!

**Comment by BarbzYHOOL** [comment] 2019-01-31 20:31
1) "Only on your system the former are two wide and the latter one."

I don't understand

2) and what about the theme "bobthefish" (famous fish theme) which uses tons of different fonts from "geekfont" or "nerdfont" (notably for Git notifications)?


3) And in last resort, you mean that I can have either the box characters OR the directory characters, but not mix them?

**Comment by faho** [comment] 2019-01-31 20:35
>And in last resort, you mean that I can have either the box characters OR the directory characters, but not mix them?

Yes.

The problem is that all of these are "ambiguous" width, and that needs to be the same (because setting width per-character doesn't really work).

Which also explains:

>and what about the theme "bobthefish" (famous fish theme) which uses tons of different fonts from "geekfont" or "nerdfont" (notably for Git notifications)?

If these characters are classified as ambiguous (or private-use, which means they don't actually really exist as characters), they need to have the same width as $fish_ambiguous_width.

**Comment by BarbzYHOOL** [comment] 2019-02-02 19:36
ok :'(

**Comment by BarbzYHOOL** [comment] 2019-02-02 20:02
I just realized on one of my ssh window, with the same fish version it's not bugging out (and same theme). This happens on the physical machine but not on my containers machines (virtual machines)

I'm completely lost.

**Comment by BarbzYHOOL** [comment] 2019-02-02 20:46
I noticed that on the container (defunct) version, I have an extra space before the typing (blinking) cursor.

Ok, I identified that only this character causes an issue `╰`, still  looks like a different issue than what you told me because I had removed all the other chars. If I do this `function fish_prompt; echo '╰$'; end  ` then it bugs out

**Comment by BarbzYHOOL** [comment] 2019-02-02 21:32
@faho I verified, many themes use this character too (like theme "bira" for fish or for zsh)

So I looked up other themes and found this one https://github.com/oh-my-fish/theme-fox/blob/master/fish_prompt.fish

It has a pretty similar character that works fine (but it's angular instead of rounded).

This is still kind of weird, the bug only happens in my container. I probably have a setting in the LXC container that causes this but really no idea what
