### ISSUE TITLE
bind should not allow binding ""

### ISSUE THREAD

**Issue by PatrickF1** [fish-shell/fish-shell#8044] opened 2021-06-03 16:57 UTC
On fish 3.2.2, if I execute `bind "" ls`, the result is `ls` being executed on an infinite loop. I find it doubtful any user would ever intentionally want a command executed on infinite loop when using bind. Shouldn't bind error instead?

This is relevant to me as a fish plugin developer when I dynamically execute binds. Sometimes, when there is no user input or the user intentionally leaves a key bind sequence blank, I want `bind` to fail instead of this behavior. Yes, I know I can just check for an empty string but that results in a lot more code. Thanks!

**Comment by faho** [comment] 2021-06-03 17:05
No, it should. That's the "generic" binding that's executed when nothing else matches.

Anyway:

Duplicate of #5595

**Closed by faho** 2021-06-03 17:05 UTC
