### ISSUE TITLE
Arrow keys through mosh for Chrome become literal [A/[B/[C/[D sequences in fish

### ISSUE THREAD

**Issue by badp** [fish-shell/fish-shell#1276] opened 2014-01-31 21:55 UTC
When I use arrow keys through [the NaCl implementation of mosh](https://chrome.google.com/webstore/detail/mosh/ooiklbnjmhbcgemelgfhaeaocllobloj), fish interpretes the input as literal `[A`/`[B`/`[C`/`[D` sequences (literally: left brace followed by uppercase character), rather than arrows. That is, I get the same result from typing:

    echo (press left arrow on keyboard) | hexdump

and issuing this command:

    echo [D | hexdump

**Comment by faho** [comment] 2015-09-15 20:27
Is this still an issue in current master? I'm thinking a66d44054c4aae44c307b10bb10469b4565e5027 might have fixed it.

**Comment by zanchey** [comment] 2015-11-13 02:29
I backed that out, so probably not.

Mosh in Chrome is rad, but I can't reproduce the problem with v0.3.0.258 of @rpwoodbu/mosh-chrome and fish 2.1.1 or 2.2.0.

I see an entry in the mosh-chrome changelog that says:

>  Mosh for Chrome v0.2.2.22
> @rpwoodbu released this on 24 Feb 2014
> **Faster pasting / better escape sequence handling** - If you've ever noticed that pasting into the window was sluggish, you'll now notice it isn't anymore. The sluggishness may have also caused problems with interpretation escape sequences on janky connections (e.g., arrow keys).

I'm going to close this for now as I suspect it has been fixed by the above, but if anyone can reproduce it sing out!

**Closed by zanchey** 2015-11-13 02:29 UTC
