### ISSUE TITLE
Fish hangs on FreeBSD 10.1

### ISSUE THREAD

**Issue by liquid** [fish-shell/fish-shell#1922] opened 2015-01-29 20:53 UTC
Hi,

I'm not so sure where to post this (here or onto the FreeBSD bugzilla) but i'll give it a try. I've installed Fish and set it to my newly created user on a VM I had created using FreeBSD 10.1.

Fish is my login shell and I've chosen it as part of `adduser` when I created the user itself. Upon logging in via SSH, my shell hangs and it is non-responsive.

```
FreeBSD 10.1-RELEASE (GENERIC) #0 r274401: Tue Nov 11 21:02:49 UTC 2014

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
fish: 
^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

Fish was installed using the `pkg` system `fish-2.1.1_2`:

```
pkg info fish
fish-2.1.1_2
Name           : fish
Version        : 2.1.1_2
Installed on   : Thu Jan 29 20:40:35 UTC 2015
Origin         : shells/fish
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : shells
Licenses       : GPLv2
Maintainer     : freebsd.users@gmail.com
WWW            : http://fishshell.com/
Comment        : User friendly command line shell
Options        :
	DOCS           : on
	NLS            : on
Shared Libs required:
	libintl.so.8
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 3.52MiB
Description    :
fish is a user friendly commandline shell intended mostly for
interactive use.

WWW: http://fishshell.com/
```

Any help would be appreciated. I don't want to lose my fave shell but it looks like I might need to move onto FreeBSD after all. Again, if this is the wrong place to ask, I'm sorry.

Any help is appreciated, thank you.

**Comment by liquid** [comment] 2015-01-29 23:55
I've done some research and compiled fish from source (current master) and it seems to be working as expected:

``
fish, version 2.1.1-1191-g1ff9aba
``

Unless you guys actively contribute to the FreeBSD port collection I guess this issue could be closed,

**Comment by zanchey** [comment] 2015-01-30 00:05
I sent the FreeBSD maintainer a patch a while back but it hasn't been integrated yet - see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196661 or #1741.

I'm going to close as a duplicate of #1741 for now, but thanks for reporting this. We are interested in FreeBSD as a platform and glad to hear the new version is working well.

**Closed by zanchey** 2015-01-30 00:05 UTC
