### ISSUE TITLE
Wildcard exclude

### ISSUE THREAD

**Issue by jonhoo** [fish-shell/fish-shell#1444] opened 2014-05-01 12:32 UTC
A feature I often find myself missing from both bash and fish is the ability to specify wildcards with exclusions. For example, say I have a set of files:

```
$ ls
results-thisconfig
results-thatconfig
results-configuration3
results-README
```

And I want to `cat` the contents of all files except `results-README`. I can't use the wildcard `results-*`, as it will also match the last file. While it is trivial to enumerate all the files in this example, imagine a directory with many such files where that would be very inconvenient. Having a more verbose wildcard syntax that let me specify an exception rule would be extremely useful in a situation like this.

One way this might be doable is by creating a "wildcard set" syntax along the lines of `{wildcard:exception:exception...}` where each exception is also a wildcard. This would let me do something like:

```
$ ls {results-*:results-README}
```

Or if I wanted to exclude `results-thisconfig` and `results-thatconfig` too:

```
$ ls {results-*:results-README:results-*config}
```

**Comment by faho** [comment] 2015-07-16 12:32
Duplicate of #1336.

**Comment by Undeterminant** [comment] 2015-07-17 05:55
@faho: already mentioned, not quite a duplicate because we have disc

**Comment by faho** [comment] 2015-07-17 09:43
It's still a duplicate, it just means the _other one_ should be closed.

**Comment by raphael-costa** [comment] 2016-06-30 02:35
@ridiculousfish 
You say ! sometimes shows up in urls but you'd still to escape urls either way. ! would be a great adition

**Comment by ridiculousfish** [comment] 2016-06-30 02:36
@raphael-costa what would you like ! to do?

**Comment by ridiculousfish** [comment] 2016-06-30 02:37
Sorry, I got this confused with the history substitution request for !. Heh.

**Comment by raphael-costa** [comment] 2016-06-30 02:37
Ignore patterns.

**Comment by krader1961** [comment] 2016-10-15 05:05
> Other shells, bash, zsh, maybe others, have this feature, so why shouldn't fish have this?

Because it is an obscure feature that has very little utility for at least 98% of fish users. Because it leads to monstrosities like I documented in [my blog post](http://www.skepticism.us/2015/10/its-time-to-replace-zsh-with-a-saner-shell-because-unsetopt-multifuncdef-breaks-tab-completion/) about why I abandoned zsh. Because it can be more cleanly handled via appropriate options to the `find` command or a fish function that filters the output of `find` or fishes `**` glob syntax.

How often does anyone use the proposed enhancement interactively? I'm quite confident it is so infrequent we can treat it as zero. Anyone using it in a script can easily use a fish function or other mechanism to remove the unwanted matches.

**Comment by muflax** [comment] 2016-10-19 03:33
As a zsh user: I use wildcards with exclusions (and filters for file types, like `*(@)` for "only symlinks") regularly. My history is unfortunately deduplicating, so it misses repeated uses of the same command, but even so, over the last two years, I wrote ~150 different commands with exclusions, plus (eyeballing) ~20 commands I re-use regularly via history search (I'd guess at a rate of ~1/week). 

Typical uses are `rm *~*.gz`, `mpv *.mkv~*.watched.*`, and `wc -l *~*_(rhyming|sorted).txt`.

It's not a super important feature, but I use it regularly and I don't know any alternative that's at least as usable and ergonomic. `find`is bad and doesn't integrate well.

Something like`fzf` with multiple selection would probably be preferable for the ad-hoc use cases, but #1362 blocks that for now.

**Comment by krader1961** [comment] 2016-10-19 04:10
> Something likefzf with multiple selection would probably be preferable for the ad-hoc use cases, but #1362 blocks that for now.

It would be better to fix issue #1362 than implement the horrible mess that is zsh globbing. And I say that as someone who used zsh, including it's advanced glob syntax, for many years. There was a lengthy discussion a year ago about adding some of the zsh like glob features. Such a selecting regular files. As a recent convert from zsh to fish I initially argued for making those enhancements. I changed my mind. For example, I now have a `ff` function that I invoke as `(ff)` when I want a list of the regular files in or below my cwd.

**Comment by krader1961** [comment] 2016-12-24 04:09
I am closing this issue because we definitely do not want to add to fish the horrible mess that are zsh globs. Anyone wanting that is free to use Perl which has been likened to "RS232 line noise" (google it). We should, instead, fix issues like #1362 so that it is easy and safe to use subcommands for use cases like this.

I took ownership of this issue because I used zsh for many years before abandoning it for fish. I was initially sad that fish did not have such a rich glob syntax. However, after using fish for a more than a year, and contributing numerous changes to its behavior, I have concluded that adding support for more complex globs, including ways to exclude matches, is not in the best interest of the fish community.

**Closed by krader1961** 2016-12-24 04:09 UTC
Labels: enhancement, RFC

**Comment by ulidtko** [comment] 2016-12-25 21:26
> an obscure feature that has very little utility for at least 98% of fish users

@krader1961 do you have any data that supports these bold claims of yours?..

The comment of @muflax and the quite popular [stackoverflow question][•] clearly show that you underestimate the utility of this feature. And in general, one can never know *all* the uses that users can put you tool into.

So to me (a quite happy `zsh` user), the **will-not-implement** decision looks way too hastily taken. That's just to be clear.

But who am I to complain, right? Looks like you're the one in charge here.

[•]: http://stackoverflow.com/questions/4585929/how-to-use-cp-command-to-exclude-a-specific-directory

**Comment by ridiculousfish** [comment] 2016-12-27 00:47
@ulidtko thanks for sharing your thoughts. krader is right that adding zsh-style globs is a non-starter. Other shells are less inspiration, and more cautionary example, with their divergent syntax and configuration (EXTENDED_GLOB/GLOB_DOTS/NULL_GLOB etc).

In short, glob excludes is something we'd like to have, but not via growing the current glob syntax.

One approach that would be acceptable is a `glob` command, alluded to in #354. This fits with fish's preference for new commands instead of syntax. @ulidtko if you'd like to take the lead on that, you're more than welcome to. (Or maybe you have other ideas for how to introduce this feature without growing the glob syntax.) Thanks either way!

**Comment by ulidtko** [comment] 2016-12-27 12:20
@ridiculousfish I'm here merely to improve the SO question on exclude patterns by adding a `fish` solution to it ☺

Hopefully, that addition will be more usable and intuitive than the ones that bash and zsh offer — which are, admittedly, arcane and limited. I, for one, can't usually remember the right syntax when I need it (which is why it's noted down for later reference, in a searchable way). A `glob` subcommand looks promising!

And yet, as of now, I don't quite see the fish solution. Which is not a big problem by itself (we all know what hasted design leads to) — but the *canonical thread to track its appearance* is being shot down. Guess which issue pops up top on google "fish exclude patterns" ?..

Alright, so let's be constructive and move forward. I'll make a new issue. Everyone interested is invited to follow below.
