### ISSUE TITLE
Fish Shell breaks Kitty image previews with ranger

### ISSUE THREAD

**Issue by purxiz** [fish-shell/fish-shell#6994] opened 2020-05-11 21:48 UTC
Please tell us which fish version you are using by executing the following:
fish, version 3.1.1

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Ubuntu 20.04 with Kitty Terminal

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

Occurs on a fresh install of fish in a VM, with the only 3rd party program being ranger's rc.conf to enable image previews. This bug is documented on the ranger page here, but I believe it to be an error(?) in fish shell, rather than with ranger:

https://github.com/ranger/ranger/issues/1919

Steps to reproduce are install ranger, enable image previews and set image_preview_method=kitty.

Image previews work properly in BASH, but in FISH, only a portion of the image is shown. The image is not resized to fit the pane, and the ranger panes are no longer drawn while the portion of the image is being previewed.
I have tried downgrading to 3.1.0-1.2 (the only other version available in apt for Ubuntu 20.04), and the issue persists, though slightly differently. The picture is still rendered incorrectly, with only a portion of it being drawn, but only the text in the ranger panes disappear. The outlines remain.

I also tried with version 3.1.2, issue still persists.

Here is a picture of the issue:
![image](https://user-images.githubusercontent.com/1489052/81940274-6becd300-95c5-11ea-83ef-471ef73f8f3c.png)

The expected behavior is that I can still see the bounding boxes on ranger, as well as the contents, and the image is resized to fit into the right pane. Here is an image just before the image preview finishes loading. Once it is displayed, the terminal looks like above.
![image](https://user-images.githubusercontent.com/1489052/81940347-8161fd00-95c5-11ea-9f6f-daab53a8e489.png)

These images were produced on fish 3.1.2. 

Here is the expected behavior:
![image](https://user-images.githubusercontent.com/1489052/81940536-b2dac880-95c5-11ea-9cba-e4f81da93b0b.png)

**Comment by ammgws** [comment] 2020-05-11 23:34
I get this from time to time as well, didn't think it might be due to fish.

**Comment by purxiz** [comment] 2020-05-12 00:56
@ammgws for me it's working with bash, if you get a chance, it would be useful to test on fish 3.0.2, as the other thread claims that it's not broken in that version.

**Comment by zanchey** [comment] 2020-05-14 12:51
Marking this as a bug though I think it needs more characterisation; I can't get kitty to run on my machine for whatever reason.

**Comment by purxiz** [comment] 2020-05-14 13:32
@zanchey I'm happy to provide whatever test output or additional info is relevant/needed. I updated the post with some images to describe the problem, but I really don't know much if anything about how shell programming works, so I'm not sure about a solution at all.

**Comment by faho** [comment] 2020-05-14 14:48
I've managed to get the previews to work, but I can't see a difference between fish and bash here. Both resize the image in what seems to be an aspect-ratio preserving manner?

The obvious thing to check are the environment variables (e.g. is there a difference in $PATH, so that this executes a different thing in the background). It is also possible fish turns something on in kitty or prints something at some point.

**Comment by purxiz** [comment] 2020-05-14 15:08
@faho Did you set preview_images_method = kitty in your ranger.conf? For me, w3m (the default) works with both, but kitty does not work with fish while bash does, path's identical, empty kitty.conf and empty fish config.

**Comment by ammgws** [comment] 2020-05-14 15:27
I'm getting the same behaviour in bash as well, however I'm running bash from fish so it might be due to something in my environment.

**Comment by callahad** [comment] 2020-05-22 22:24
I can confirm that Fish 3.0.2 works as expected, and 3.1.0 fails.

There were only 2,210 commits between the two releases, so we should be able to bisect the regression in about a dozen builds.

...not that I'm volunteering. But not that I'm _not_ volunteering, either.

**Comment by callahad** [comment] 2020-05-22 22:58
Git bisect reports that 8031fa3bdb8a856ff1f90996386f285099f743c1 is the first bad commit.

I manually re-verified that its parent 3d25ce1fd4c5fc30e4c3a554e39d1fab796bd8b8 works as expected.

**Comment by callahad** [comment] 2020-05-23 08:57
(I do not have the experience or time to effectively pursue this further, but hopefully the bisect is helpful. I'm more than happy to test patches.)

**Comment by ammgws** [comment] 2020-05-23 09:14
Probably not a coincidence that the code changed in that commit had to do with termsize.

**Comment by callahad** [comment] 2020-05-23 16:09
Looks like an easier way to reproduce this is by passing a large image to Kitty's built-in `icat`.

Example invocations and screenshots over at https://github.com/ranger/ranger/issues/1919#issuecomment-633081001, but generally speaking, it's `kitty +kitten path/to/image.jpg`.

If I run `kitty bash`, then `icat` works.
If I run `fish` from inside of `kitty bash`, then `icat` _does not_ work.

If I run `kitty fish`, then `icat` _does not_ work.
If I run `bash` from inside of `kitty fish`, then `icat` _does not_ work unless I first resize the window.

So it seems like starting up Fish at all somehow breaks Kitty's sense of the window size, and that breakage persists into Bash subshells, but is temporarily fixed if the window is resized while the Bash subshell is active. Exiting Bash and returning to Fish re-breaks things.

**Comment by callahad** [comment] 2020-05-24 21:29
For a temporary workaround, calling `git revert` on 277db648049845f19847e62c2a128b970913bbc6 and 8031fa3bdb8a856ff1f90996386f285099f743c1 yields the following patch against Fish 3.1.2, which I'm happily using locally.

<details>
<summary>(Click to show patch)</summary>

```patch
diff --git a/src/common.cpp b/src/common.cpp
index f76445fc0..57d66695a 100644
--- a/src/common.cpp
+++ b/src/common.cpp
@@ -103,7 +103,7 @@ static relaxed_atomic_t<pid_t> initial_fg_process_group{-1};
 /// This struct maintains the current state of the terminal size. It is updated on demand after
 /// receiving a SIGWINCH. Use common_get_width()/common_get_height() to read it lazily.
 static constexpr struct winsize k_invalid_termsize = {USHRT_MAX, USHRT_MAX, USHRT_MAX, USHRT_MAX};
-static owning_lock<struct winsize> s_termsize{k_invalid_termsize};
+static relaxed_atomic_t<struct winsize> s_termsize(k_invalid_termsize);
 
 static relaxed_atomic_bool_t s_termsize_valid{false};
 
@@ -1749,8 +1749,9 @@ bool unescape_string(const wcstring &input, wcstring *output, unescape_flags_t e
 void invalidate_termsize(bool invalidate_vars) {
     s_termsize_valid = false;
     if (invalidate_vars) {
-        auto termsize = s_termsize.acquire();
-        termsize->ws_col = termsize->ws_row = USHRT_MAX;
+        struct winsize termsize = s_termsize;
+        termsize.ws_col = termsize.ws_row = USHRT_MAX;
+        termsize = s_termsize;
     }
 }
 
@@ -1818,42 +1819,27 @@ static void export_new_termsize(struct winsize *new_termsize, env_stack_t &vars)
 #endif
 }
 
-/// Get the current termsize, lazily computing it. Return by reference if it changed.
-static struct winsize get_current_winsize_prim(bool *changed, const environment_t &vars) {
-    auto termsize = s_termsize.acquire();
-    if (s_termsize_valid) return *termsize;
+/// Updates termsize as needed, and returns a copy of the winsize.
+struct winsize get_current_winsize() {
+    struct winsize termsize = s_termsize;
+    if (s_termsize_valid) return termsize;
 
     struct winsize new_termsize = {0, 0, 0, 0};
 #ifdef HAVE_WINSIZE
     errno = 0;
     if (ioctl(STDOUT_FILENO, TIOCGWINSZ, &new_termsize) != -1 &&
-        new_termsize.ws_col == termsize->ws_col && new_termsize.ws_row == termsize->ws_row) {
+        new_termsize.ws_col == termsize.ws_col && new_termsize.ws_row == termsize.ws_row) {
         s_termsize_valid = true;
-        return *termsize;
+        return termsize;
     }
 #endif
+    auto &vars = env_stack_t::globals();
     validate_new_termsize(&new_termsize, vars);
-    termsize->ws_col = new_termsize.ws_col;
-    termsize->ws_row = new_termsize.ws_row;
-    *changed = true;
+    export_new_termsize(&new_termsize, vars);
+    termsize.ws_col = new_termsize.ws_col;
+    termsize.ws_row = new_termsize.ws_row;
+    s_termsize = termsize;
     s_termsize_valid = true;
-    return *termsize;
-}
-
-/// Updates termsize as needed, and returns a copy of the winsize.
-struct winsize get_current_winsize() {
-    bool changed = false;
-    auto &vars = env_stack_t::globals();
-    struct winsize termsize = get_current_winsize_prim(&changed, vars);
-    if (changed) {
-        // TODO: this may call us reentrantly through the environment dispatch mechanism. We need to
-        // rationalize this.
-        export_new_termsize(&termsize, vars);
-        // Hack: due to the dispatch the termsize may have just become invalid. Stomp it back to
-        // valid. What a mess.
-        *s_termsize.acquire() = termsize;
-        s_termsize_valid = true;
-    }
     return termsize;
 }
 
diff --git a/src/common.h b/src/common.h
index d453e4b1d..a83a3de15 100644
--- a/src/common.h
+++ b/src/common.h
@@ -494,7 +494,6 @@ class owning_lock {
 
    public:
     owning_lock(Data &&d) : data(std::move(d)) {}
-    owning_lock(const Data &d) : data(d) {}
     owning_lock() : data() {}
 
     acquired_lock<Data> acquire() { return {lock, &data}; }
```

</details>

**Comment by dsanson** [comment] 2020-05-25 02:19
Good to see that it isn't just me. An easy way to check for the problem is running:

    kitty icat --print-window-size

when things are working properly, you get a reasonable response. But when things are broken, you get:

    65535x65535

For an old report of a similar problem, see https://github.com/kovidgoyal/kitty/issues/2026

**Comment by dsanson** [comment] 2020-05-25 03:28
The problem is not specific to kitty. The same problem affects my super simple C snippet for querying terminal dimensions, terminal_dimensions. This snippet of C will also demonstrate the problem:

```
#include <sys/ioctl.h>
#include <stdio.h>
int main(int argc, char **argv)
{
  struct winsize sz;

  ioctl(0, TIOCGWINSZ, &sz);
  printf("%i %i\n", sz.ws_xpixel, sz.ws_ypixel);
  return 0;
}
```

https://github.com/dsanson/terminal_dimensions

**Comment by mqudsi** [comment] 2020-05-26 20:14
I thought I'd tackle this but I can't get it to reproduce. I first tried whatever ranger I had installed via debian packages then switched to the latest ranger from pip3 (1.9.3). I'm running kitty 0.12.3 and fish 3.1.2-630-gad020e84d-dirty


![image](https://user-images.githubusercontent.com/606923/82945944-20420e00-9f63-11ea-8b7b-5070e20b021a.png)

![image](https://user-images.githubusercontent.com/606923/82945969-2c2dd000-9f63-11ea-829c-3fa54df5bc08.png)

![image](https://user-images.githubusercontent.com/606923/82946005-38199200-9f63-11ea-855f-30fb87415b94.png)

![image](https://user-images.githubusercontent.com/606923/82946014-3cde4600-9f63-11ea-9ce0-fa6bd2a87aeb.png)

Note that I had to set TERM to `xterm-kitty` for image preview to show as non-textual in ranger.

**Comment by krobelus** [comment] 2020-05-26 20:57
@mqudsi maybe try with a newer version of kitty, With `0.17.4` I get `65535x65535` when running `kitty icat --print-window-size` inside kitty. TERM is already set to xterm-kitty by default for me.

**Comment by ammgws** [comment] 2020-05-26 23:02
@mqudsi perhaps try some higher resolution photos?

**Comment by mqudsi** [comment] 2020-05-27 21:38
@krobelus same with 0.17.4 (kitty git master), which did indeed set `xterm-kitty` on its own:

![image](https://user-images.githubusercontent.com/606923/83074781-58675080-a038-11ea-8f4e-f4cdb2122050.png)

@ammgws that was a high resolution image, but more importantly, the underlying cause is not reproducing for me.

**Comment by mqudsi** [comment] 2020-05-31 05:03
I have no real reason to think it matters, but are you guys maybe running under wayland?

**Comment by ammgws** [comment] 2020-05-31 05:06
Yes, using sway

**Comment by krobelus** [comment] 2020-05-31 06:29
Xorg here.

**Comment by dsanson** [comment] 2020-05-31 14:14
Mac OS X.

**Comment by mqudsi** [comment] 2020-06-08 04:00
@ridiculousfish just pushed a lot of changes to term size; perhaps give it another try?

**Comment by ridiculousfish** [comment] 2020-06-08 04:19
My changes were hopefully just cleanup. I'll take a look at this issue though.

**Comment by ridiculousfish** [comment] 2020-06-08 04:29
I'll give it a try too

**Comment by ammgws** [comment] 2020-06-08 15:15
Seems to be fixed for me. Top is before updating fish.
![image](https://user-images.githubusercontent.com/20397027/84047403-31206400-a9e6-11ea-861a-c5484fd2683e.png)

**Comment by faho** [comment] 2020-06-08 15:50
Yeah, seems to be working, pretty sure it's d5a239e59ec0e84a47d499270f618e432abd747f that fixed it.

I think we were stomping on Kitty's stuff and it broke by forgetting the window size, which would also explain why it remains broken after quitting fish.

If someone cares enough, that's a thing kitty could be more resilient against.

**Comment by callahad** [comment] 2020-06-08 15:50
I bisected and can confirm that d5a239e59ec0e84a47d499270f618e432abd747f resolved this.

**Closed by faho** 2020-06-08 15:50 UTC
Labels: bug, needs more info
