### ISSUE TITLE
Case-insensitive completion of command arguments

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4948] opened 2018-04-27 08:39 UTC
_(...on case-insensitive filesystems.)_

Use-case: I have a case-insensitive filesystem and, rather than typing `command git` to skip my `git` alias, I often just uppercase the first letter (`Git`, similar to `\git` in bash) as it's far easier than typing out `command`, which in turn breaks fish's tab completion.

**Comment by zx8** [comment] 2018-04-27 08:41
Oops, dupe: https://github.com/fish-shell/fish-shell/issues/3978

**Comment by faho** [comment] 2018-04-28 13:42
Dupe of #2538, no?

**Closed by faho** 2018-04-28 13:42 UTC
