### ISSUE TITLE
Control sequence escapes "\cx" are neither highlighted nor expanded correctly

### ISSUE THREAD

**Issue by Phidica** [fish-shell/fish-shell#3800] opened 2017-02-01 02:22 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

tl;dr - Bugs are in bold

The [documentation](https://fishshell.com/docs/current/index.html#escapes) says that "\\c*x*" where *x* is "a letter of the alphabet" is an escape that will produce a control sequence. This is not the behaviour that `fish` actually has, though; rather, `fish` behaves much closer to what one should expect as a means to produce control sequences. That's good, but it means that first of all **the documentation needs updating to explain that other characters besides alphabetic ones are accepted**

Control sequences 101
=====================

A brief overview of how control sequences work to save everyone else some time: they are a way to use printing characters from the second half of the standard ASCII table to type nonprinting characters from the first half of the standard ASCII table. With reference to [a handy visual](http://www.asciitable.com/index/asciifull.gif), pressing control and a character from decimal 63 ('?') to decimal 96 ('`') will create a character from decimal 127 ('DEL') to decimal 32 (' ') wrapping around through decimal 0 ('NUL'). The characters from decimal 97 ('a') to decimal 126 ('~') are a secondary way to create the characters from decimal 1 to decimal 30. There is no such thing as control sequences for the characters from decimal 33 to decimal 62; they cannot be used in control sequences, nor acquired via the use of other control sequences

Current behaviour
=================

`fish` version: 2.4.0

1. "\\c" followed by any character from decimal 64 ('A') to decimal 126 ('~') is expanded as an escape, but under no circumstances does *highlighting* extend past the "\\c". This leads to trouble when one tries to run, for instance, `echo \c[`, which is meant to be a valid control sequence escape but the highlighter picks up the open square bracket and refuses to let the command execute. Tricking `fish` by running `echo \c[.]` reveals that "\\c[" *was* turned into a control sequence (rendered with a Unicode square, for me), as it should have been! So, **control sequence highlighting is not working as required**

2. The '?' and '@' characters cannot be used in control sequence escapes. "\\c?" should produce 'DEL' and "\\c@" should produce 'NUL', but `fish` rejects both of these as invalid tokens. So **control sequence expansion is not working as required**

3. If one tries to create a control sequence escape using any of the invalid characters from decimal 33 to decimal 62, such as '!', `fish` rejects it as an invalid token. That's good

Expected behaviour
==================

1. Highlighting should extend to the next character after the "\\c" only if that character is valid for making escapes. If the next character is invalid, then either:

    - In line with the behaviour of a pointless escape like "\\d", the "\\c" should be highlighted as a literal '\\' followed by a literal 'c' and a literal version of the invalid character, or
    - In line with the behaviour of multicharacter escape codes when faced with invalid input (eg, `echo \uG`), the invalid character should be consumed but no escape created and no error issued.

2. '?' and '@' should be parsed as valid in control sequence escapes

Other relevant issues
=====================

#3162: A fix here would explicitly forbid the ability to make control sequence escapes out of control sequences. As it currently stands, "\\c\\" is actually a control sequence (because '\\' is decimal 92), so the highlighting of something like "\\c\\n" will clearly indicate that the "\\n" is not interpreted as a character escape

#3189: Binding "\\c@" should be possible, and if the parser accepted it then running `bind \c@` would result in the desired behaviour of control-space executing the bind. Ah, I don't quite understand what the discussion in that issue and its associated pulls is about, but I think it's saying that 'NUL' has no valid internal representation because it would simply be an empty string, which already has a meaning. But if that's the case then I don't understand why `bind \x00` *does* work, up to a point, when "\\x00" is another way to make a 'NUL'. Anyway, I note that [this comment](https://github.com/fish-shell/fish-shell/pull/3250#discussion-diff-71965131) pertains to a relevant section of the parser which deals with allowing '@' in a control sequence escape

#3381: Not totally sure, but this issue may be affected. The fact that the issue is with "\\\\c" specifically might mean something

**Comment by pranav-prakash** [comment] 2017-02-01 04:27
For #3189 I believe the issue was that null is already used in the source code as the "if nothing else matches" binding to tell fish to type the character. Remapping this to a new action thus prevents you from actually entering any input to the console.

**Comment by krader1961** [comment] 2017-03-23 05:09
I don't like to be pedantic but this statement in the original problem statement is not true:

> they are a way to use printing characters from the second half of the standard ASCII table to type nonprinting characters from the first half of the standard ASCII table

There is at least one other statement that is similarly wrong. A control character is simply one that has all of the high three bits set to zero. Which is equivalent to saying that control characters are in the range 0x00 thru 0x1F. Applying the "control" modifier key in a terminal can simply strip the three high bits of the modified character or limit such behavior to a subset of all byte values. This has never been well defined and seems to be irrelevant to the issue.

Despite what I wrote above fish is definitely inconsistent and schizophrenic regarding control characters and their representation. As evidenced by the issues linked to in the original comment. So there are improvements to be made in this area.

The problem with this issue is that I can't tell what the O.P. expects to be changed. An issue should be focused on a single problem. I can't tell from the original problem description what the problem is or even if it is trying to document multiple problems that need to be fixed.

**Comment by Phidica** [comment] 2017-03-23 10:24
Okay, fair points. I was going off what I'd learnt on Wikipedia and some other sites after an evening of research. Perhaps I was presumptuous to present my understanding as fact, though I was confident I had it right at the time. Apologies if I've confused this matter further with the extraneous information

I understand that I wrote a very lengthy issue and I was concerned that my key points were being lost. To summarise in the simplest terms, I believe there are _two bugs_ here:

1. Highlighting does not work properly for control sequence escapes. If you write "\cA" then all three characters should be highlighted as an escape sequence, but only the "\c" is. This causes problems when the third character in the sequence is something more exotic than an alphanumeric
1. Some control sequences cannot be sent using control sequence escapes. 'DEL' and 'NUL' should be capable of being sent with "\c?" and "\c@" but `fish` rejects both

**Comment by krader1961** [comment] 2017-03-24 03:37
No worries, @Phidica. You can bind DEL by doing `bind \x7F 'echo del seen'`. The DEL character is not a normal control character in that, obviously, it is not formed by masking just the bottom five bits of the code sent by some other character. So it doesn't make sense to use the `\c` prefix. The inability to bind the NUL character is tracked in issue #3189.

Can you show a screenshot or asciinema recording of the highlighting problem? I'm still fuzzy on how to reproduce that aspect of the problem.

**Comment by krader1961** [comment] 2017-03-24 03:44
Also, just to be crystal clear, doing something like `\c?` (which is currently illegal due to `?` being a glob character) would result in the "US" control character (0x1F) not the "DEL" character (0x7F) by definition given the semantics of the control modifier.

**Comment by faho** [comment] 2020-10-03 09:55
Okay, closing this.

>So, control sequence highlighting is not working as required

Control sequence highlighting works, matching brackets doesn't - #2485 .

>"\c?" should produce 'DEL' and "\c@" should produce 'NUL'

Rejecting NUL is *correct*, because NUL can't be passed as argument, because arguments are NUL-terminated strings.

I don't think anyone cares about DEL here, if you have to use it, use \x7f.

**Closed by faho** 2020-10-03 09:55 UTC
Labels: RFC, enhancement, needs more info
