### ISSUE TITLE
SSH completion does not work with 2 or more aliases of a host.

### ISSUE THREAD

**Issue by Mazorius** [fish-shell/fish-shell#4290] opened 2017-08-07 11:56 UTC
* fish, version 2.6.0
* Darwin AMBPROG 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin
* xterm-256color
* without third-party does not change anything

Only the first alias is shown if I use __fish_print_hostnames and if I use ssh with completion as well.

**Comment by krader1961** [comment] 2017-08-08 01:41
I can't reproduce -- works for me. Are you using the `Include` directive? If yes then this was recently fixed and may be a duplicate of #4253. If no, please show us your *~/.ssh/config* (sanitized of any sensitive info).

**Comment by Mazorius** [comment] 2017-08-17 15:17
Hi @krader1961 ,

sorry for my late answer.

I have something like that inside my ssh configuration:
`Host alias1 alias2 alias3 alias4 alias5`

ssh only completes for alias1 but does not complete alias2-alias5.

Does this make it more clear?

 kind regards

**Comment by ThomasAH** [comment] 2017-09-04 13:57
For me it seems to completely ignore entries in ~/.ssh/config, but only uses (unhashed) known_hosts.
(fish 2.6.0 from your OBS on Debian jessie)

@Mazorius maybe that is why it works for your first entry, but not for the aliases?

**Comment by faho** [comment] 2017-09-04 14:01
>fish 2.6.0 from your OBS on Debian jessie

@ThomasAH: This was changed _after_ 2.6.0. It should be fixed in 2.7.0, which should go into beta any minute.

**Comment by ThomasAH** [comment] 2017-09-04 14:13
@faho, ah thanks!
I have an additional problem with parsing known_hosts entries with multiple host names, but I will create a separate ticket for it.

**Comment by faho** [comment] 2018-01-04 11:12
Works in master.

**Closed by faho** 2018-01-04 11:12 UTC
Labels: needs more info
