### ISSUE TITLE
Shift-tab is broken sometimes

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#922] opened 2013-07-21 17:23 UTC
Example: let's say that I accidentally tab-complete "e," which somehow expands to fish-shell because of fuzzy-completion. This lets you undo the tab completion so that it's back to e. Another possibility is that when cycling through completions, going back one is less cumbersome than cycling through all of them.

Edited title because the feature has been long added, but is broken in some cases.

**Comment by doughsay** [comment] 2015-01-25 19:36
Still happening with the latest version from homebrew... :(

**Comment by tonytonyjan** [comment] 2015-05-12 04:56
+1

**Comment by river-jade** [comment] 2015-07-22 07:53
I had the same problem. Switching terminal emulation from xterm-color to xterm did the trick!

**Comment by zanchey** [comment] 2015-07-23 06:46
@river-jade, what terminal emulator and what version of fish are you using?

**Comment by river-jade** [comment] 2015-07-23 08:09
Mac Terminal: Version 2.5.3 (343.7)
fish, version 2.2.0-71-g08911e2

**Comment by zanchey** [comment] 2015-07-23 09:04
Thanks - and when you say "switching terminal emulation", do you mean in Preferences - Profiles - Advanced? I don't have `xterm-color` there, just `xterm-256color`, which appears to work ok with shift tab.

**Comment by river-jade** [comment] 2015-07-24 11:19
Yes. I don't see xterm-color in there now either. I wonder if it was a
hangover from an earlier version of terminal?

**Comment by faho** [comment] 2015-10-23 20:58
Seems to be an issue with a weird TERM value. Closing - if anyone can still reproduce, please yell!

**Comment by beloglazov** [comment] 2015-10-29 02:00
I still have this issue, my TERM value is `rxvt-unicode-256color`.

**Comment by faho** [comment] 2015-10-29 12:12
@beloglazov: What does `infocmp $TERM` say for "kcbt"? What does `bash` say when you press CTRL+v and then shift-tab?

**Comment by beloglazov** [comment] 2015-10-31 02:08
@faho `kcbt=\E[Z`, CTRL+v and then shift-tab in bash results in `^[[Z`. I also have `vi-mode` oh-my-fish plugin enabled, I noticed that when this plugin is enabled pressing shift-tab works as escape -- quits the insert mode. I've also tried completely disabling my fish config, in that case pressing shift-tab in fish prints `[Z`. 

It's definitely possible that this problem is caused by interference with some of my other configuration, I just don't know what exactly causes it.

**Comment by krader1961** [comment] 2016-04-28 19:18
@beloglazov The behavior you're observing is because fish is waiting just 10 ms after seeing an escape character to see if it is followed by additional characters that would match a longer bind sequence. In emacs mode that isn't a problem because a bare escape isn't bound to anything. But in vi mode a bare escape is bound. If you're running fish inside `screen` or `tmux` or over a high-latency connection (e.g., ssh to a server a long way away) enough delay can added after the escape is sent to fish to cause erratic behavior.

The fish 2.3.0 release (currently in beta testing) includes I change I made three months ago to increase the timeout from 10 to 300 ms and make it configurable. I'm so confident that this is fixed I'm going to go ahead and close this issue.

**Closed by krader1961** 2016-04-28 19:18 UTC

**Comment by beloglazov** [comment] 2016-04-29 00:52
@krader1961 Thank you! I realized I don't experience this problem right now on 2.2.0. I'm glad it's fixed!
