### ISSUE TITLE
pipe is masking a sudo password prompt

### ISSUE THREAD

**Issue by sbanacho** [fish-shell/fish-shell#5037] opened 2018-06-09 00:57 UTC
Hi,
when I run a command like 'sudo yum list | grep foo' 

With bash, I get the sudo prompt, and after entering password the command proceeds.

With fish, it just pauses indefinitely.  There is no password prompt (and attempting to enter password does not work).

Without pipe, it works as expected (prompts for password).

It appears the pipe is blocking sudo's ability to request a password.

Versions of fish:  observed on both Linux, version 2.3.1 and MacOs, version 2.7.1

**Comment by faho** [comment] 2018-06-09 08:49
Duplicate of #3952.

**Closed by faho** 2018-06-09 08:49 UTC
