### ISSUE TITLE
tab completion on apt / apt-get does not offer option to choose

### ISSUE THREAD

**Issue by RafalSkolasinski** [fish-shell/fish-shell#7521] opened 2020-12-01 11:13 UTC
Hey, a strange issue here. Just installed KDE Neon and fish with apt-get here does not offer completion on different packages to choose from but rather selects one option only.

Similar to https://github.com/fish-shell/fish-shell/issues/3011 but only limited to `apt` and `apt-get`.

## Step to reproduce:
1. On KDE Neon install fish
2. type `sudo apt-get install pyt<tab>`

## What happens:
It autocompletes to `sudo apt-get install python3-alembic`

## What is expected:
Fish offers option to choose from different packages that follows the pattern.

Happy to provide more info as required.

---
## System details

Installed 3.1.2 from your PPA but system one was 3.1.0 and behaved int the same way.

```
$ fish --version
fish, version 3.1.2
```

```bash
$uname -a
Linux machine42 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ echo $XTERM
xterm-256color
```
Tried with following and still observed the issue
```bash
$  sh -c 'env HOME=$(mktemp -d) fish'
```

```bash
$ bind \t
bind --preset \t complete
```

**Comment by faho** [comment] 2020-12-01 14:28
This works for me on 3.1.2 on debian.

What does `__fish_print_packages` say? If that doesn't work either, what does

```fish
apt-cache --no-generate show '.*'pyt'.*' | sed -r '/^(Package|Description-[a-z]{2}):/!d;s/Package: (.*)/\1\t/g;s/Description-.*: (.*)/\1\x\
    ee\x80\x80\x0a/g'
```

say? That's what the apt completions end up running in 3.1.2.

**Comment by RafalSkolasinski** [comment] 2020-12-01 14:37
The `__fish_print_packages` prints packages but they seem to be `tab` (or couple spaces) separated and dumped into a single line of output. 

On another machine that works fine the output of same function is two-column with  first being name of package and second being the description. 

Wonder what could be broken here. 
The second command prints one column with package names.


Could it be possible that `__fish_print_packages` definitions differs between these two systems?
But what could impact it...

**Comment by faho** [comment] 2020-12-01 14:40
>Could it be possible that __fish_print_packages definitions differs between these two systems?

Well, that's easy enough to check - `sha256sum (functions --details __fish_print_packages)`. In my case that prints

```
bbe53f3f8ac6597c8649e771739a26280f6e6b03d3fe8cc4283127b33d0465eb  /usr/share/fish/functions/__fish_print_packages.fish
```

**Comment by RafalSkolasinski** [comment] 2020-12-01 14:45
Hmm... I got the same as you on both systems
```
bbe53f3f8ac6597c8649e771739a26280f6e6b03d3fe8cc4283127b33d0465eb  /usr/share/fish/functions/__fish_print_packages.fish
```

The difference is that system that works is
```
❯❯❯ cat /etc/lsb-release                                                                                                      (⎈ n/a|default)
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
```

And the one that doesn't is
```
╰─λ cat /etc/lsb-release                     
DISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User Edition 5.20"
```



fish configs are slightly different but I tried on faulty machine with both
- using ` sh -c 'env HOME=$(mktemp -d) fish'`
- removing `~/.config/fish`


this is strange

**Comment by faho** [comment] 2020-12-01 15:05
Ah, okay. So the function isn't different, but the output is different. Well, surely that's because `apt`s output is different!

What does

```fish
apt-cache --no-generate show python3-alembic
```

say on both?

**Comment by RafalSkolasinski** [comment] 2020-12-01 15:17
Broken system:
```
Package: python3-alembic
Architecture: all
Version: 1.1.0-1ubuntu1
Priority: optional
Section: python
Source: alembic
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 586
Depends: python3-pkg-resources, python3-dateutil, python3-mako, python3-sqlalchemy (>= 1.1.0), python3:any
Suggests: python3-editor
Breaks: alembic (<< 0.8.8-3)
Filename: pool/main/a/alembic/python3-alembic_1.1.0-1ubuntu1_all.deb
Size: 98684
MD5sum: 1799d4246ae042c5a7c3fff341df4a17
SHA1: 04980f17a931b6bc16e7dd4969db6343bd7aed13
SHA256: fe1c51f66351d31f0aa06fd1a4288b21e265a89c2f591a93b18db238dc4c4312
Homepage: https://bitbucket.org/zzzeek/alembic
Description: lightweight database migration tool for SQLAlchemy - Python module
Description-md5: 98ec47f7a2dda1713520d880822f9cad
```

Good system:
```
Package: python3-alembic
Architecture: all
Version: 1.1.0-1ubuntu1
Priority: optional
Section: python
Source: alembic
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 586
Depends: python3-pkg-resources, python3-dateutil, python3-mako, python3-sqlalchemy (>= 1.1.0), python3:any
Suggests: python3-editor
Breaks: alembic (<< 0.8.8-3)
Filename: pool/main/a/alembic/python3-alembic_1.1.0-1ubuntu1_all.deb
Size: 98684
MD5sum: 1799d4246ae042c5a7c3fff341df4a17
SHA1: 04980f17a931b6bc16e7dd4969db6343bd7aed13
SHA256: fe1c51f66351d31f0aa06fd1a4288b21e265a89c2f591a93b18db238dc4c4312
Homepage: https://bitbucket.org/zzzeek/alembic
Description-en_GB: lightweight database migration tool for SQLAlchemy - Python module
 Alembic is a new database migration tool, written by the author of
 SQLAlchemy. A migration tool offers the following functionality:
 .
  * Can emit ALTER statements to a database in order to change the
    structure of tables and other constructs
  * Provides a system whereby "migration scripts" may be constructed;
    each script indicates a particular series of steps that can
    "upgrade" a target database to a new version, and optionally a
    series of steps that can "downgrade" similarly, doing the same
    steps in reverse.
  * Allows the scripts to execute in some sequential manner.
Description-md5: 98ec47f7a2dda1713520d880822f9cad
```

**Comment by faho** [comment] 2020-12-01 16:13
Okay, that's basically the same thing, except for the description being slightly different - in particular one says "Description", the other says "Description-en_GB".

Since this `sed` does weirdness with `\x80` and such (which is above ASCII), what's the `locale` on both?

**Comment by RafalSkolasinski** [comment] 2020-12-01 16:39
Good system
```
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```


Bad system
```
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

The language one is empty, would this be the root of the problem?

**Comment by RafalSkolasinski** [comment] 2020-12-01 17:18
Hmm... did
```
sudo update-locale LANGUAGE=en_GB:en
```
and logged out and in again, now `locale` shows `LANGUAGE` but the `__fish_print_packages` command still misbehaves.

**Comment by faho** [comment] 2020-12-04 15:37
Okay, taking another look at this, the problem is indeed the missing "-en_GB". That `sed` invocation is super naive and absolutely requires the locale indicator. It's been fixed in a4a4a2e1b6cd59dbfe150f67fc665ba226656b1c.

Unfortunately I have no idea how to get the -en_GB on your system, so you'll have to wait until the next release or it might work to download [the fixed __fish_print_packages.fish](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_packages.fish) to ~/.config/fish/functions/ - I don't think we're using any new features there.

**Comment by faho** [comment] 2020-12-04 15:39
Nope, sorry, it's broken the other way around, the regex needs to be loosened some more.

**Closed** 2020-12-04 15:47 UTC
Labels: question

**Comment by RafalSkolasinski** [comment] 2020-12-06 23:59
Thank you @faho, just tested it and it works fine :+1:
