### ISSUE TITLE
/usr/share/fish/completions/git.fish (line 618): The expanded command was empty

### ISSUE THREAD

**Issue by remyabel2** [fish-shell/fish-shell#9201] opened 2022-09-11 05:52 UTC
**Fish version**: 3.5.0
**Operating system**: Fedora 36 Linux 5.19.8-200.fc36.x86_64
**Term**: xterm-kitty, but also tested in gnome-terminal and alacritty

If I begin typing `git -C ~/test/` then press tab to autocomplete, I get the following diagnostic:

```
git -C ~/test//usr/share/fish/completions/git.fish (line 618): The expanded command was empty.
    $__fish_git_needs_command
    ^
in function '__fish_git_needs_command'
in command substitution
git -C ~/test/       git -C ~/test/
```
Any key I press then causes the current shell to exit. I do not have this issue when autocompleting other git commands (or in general). `git -C some_path` seems to consistently trigger this error.

**Comment by faho** [comment] 2022-09-11 06:10
Duplicate of #9053

Upgrade to fish 3.5.1

**Closed by faho** 2022-09-11 06:10 UTC
