### ISSUE TITLE
[Feature request] Escape sequence processing for "set" and "read"

### ISSUE THREAD

**Issue by osamuaoki** [fish-shell/fish-shell#6285] opened 2019-11-04 17:00 UTC
```
> fish --version
>  echo $version
3.0.2
> uname -a
Linux goofy 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
```
Problem: Lack of method to pass string variables from function to outside cleanly 

For simple string passing we can write:
```
function foo
set out a b c
echo $out
end
foo|read -a aa
echo /$aa[1]/;echo /$aa[2]/; echo /$aa[3]/
```
This results in
```
/a/
/b/
/c/
```

But this kind of variable passing from inside function to outside has some limitations such as each variable shall not be null string '' nor contain new line in it, ...

This limitation can be avoided by coding using `string escape`, e.g.:
```
function foo
set out a '' 'c
d'
echo (string escape $out)
end
foo|read -a aa
echo -e /$aa[1]/;echo -e /$aa[2]/; echo -e /$aa[3]/
```
 In this example, we can regain original values using `-e` option offered by `echo`.  But for more complicated script in which `$aa` is used as `for x in $aa;` with some post processing, you may want to hold unescaped values in `$aa[1]` `$aa[2]` `$aa[3]` to make code more readbale.  This is not easy now.

So I request to add `-e` option to `read` which can be used with `-L` option` and `-a` option. 

This `-e` option should work like one for `echo` to unescape string.

Also, it will be nice to have `-e` option for `set` too.  Then we don't need to have odd multi-line set command.

The odd `echo` in `echo (string escape ...)`  line can be avoided if some option exists for `read` which works as if `-L -a` was expected to work by 0ion9  in https://github.com/fish-shell/fish-shell/issues/5820.  Alternatively, if some option exists to emit space instead of newline as the separator by the `string escape` command, we can have cleaner and easily readable code.

I think this is missing piece for the consistent string handling. 

FYI: I got bitten by null string case ... then realize more problems.

**Comment by krobelus** [comment] 2019-11-04 17:39
You can split on null bytes, and use string split0 which disables the default behavior of splitting on newlines.
```
$ function foo
set out a '' 'c
d'
printf '%s\0' $out
end
$ set aa (foo | string split0)
$ set -S aa
$aa: not set in local scope
$aa: set in global scope, unexported, with 3 elements
$aa[1]: length=1 value=|a|
$aa[2]: length=0 value=||
$aa[3]: length=3 value=|c\nd|
$aa: not set in universal scope
```
`read` also has a `-d` option to set a delimiter and `-z`/`--null` but I haven't got that working

**Comment by osamuaoki** [comment] 2019-11-05 14:56
I see for `set` and `split0`.  This needs to be elaborated in documentation more explicitly.  (I now see this is 3.0 feature after reading https://github.com/fish-shell/fish-shell/issues/3164 .  `( ... )` seems to produce array data instead of string.  Interesting.   This is not so obvious for new fish user.

I am not quite sure about your comment " haven't got that working" ... Do you mean `-z` eoesn't work as expected for `read`?  That doesn't work for me, either.  Is this bug in `-z` option or not?

I still think that `read` has advantage since it is not limited by the command line length limitation (if it exists in fish.)  So I looked for more POSIX-like scripting approach to read passed values.   Actually, it was not so difficult if we are worried about newline and null string:
```
osamu@goofy ~> function foo
                   set out a '' 'c
                   d'
                   echo (string escape $out)
               end
               foo|read -a aa
               eval set bb $aa
osamu@goofy ~> set -S bb
$bb: not set in local scope
$bb: set in global scope, unexported, with 3 elements
$bb[1]: length=1 value=|a|
$bb[2]: length=0 value=||
$bb[3]: length=3 value=|c\nd|
$bb: not set in universal scope

osamu@goofy ~> eval set cc (foo)
osamu@goofy ~> set -S cc
$cc: set in local scope, unexported, with 3 elements
$cc[1]: length=1 value=|a|
$cc[2]: length=0 value=||
$cc[3]: length=3 value=|c\nd|
$cc: not set in global scope
$cc: not set in universal scope

```
 So use of `eval` together with `string escape` can also solve parameter passing problem for this limited scope.   (I think there is price to pay for the use of `eval` though.  Just think you have `$` in original string ...)

That is why we need special option for `set` to unescape and  __`read` with functioning `-z` option or `--eval` option are nice to have__.  Also for readability, syntax like `string escape --style=array ...` to avoid use of `echo` is nice to have. 

The current behavior of `string escape/unescape` is a bit intriguing for me.
```
osamu@goofy ~> set -l xx 'a
               b c' '' d

osamu@goofy ~> set -S xx
$xx: set in local scope, unexported, with 3 elements
$xx[1]: length=5 value=|a\nb c|
$xx[2]: length=0 value=||
$xx[3]: length=1 value=|d|
$xx: not set in global scope
$xx: not set in universal scope

osamu@goofy ~> set yy (string unescape (string escape $xx))
osamu@goofy ~> set -S yy
$yy: not set in local scope
$yy: set in global scope, unexported, with 4 elements
$yy[1]: length=1 value=|a|
$yy[2]: length=3 value=|b c|
$yy[3]: length=0 value=||
$yy[4]: length=1 value=|d|
$yy: not set in universal scope

osamu@goofy ~> eval set zz (string escape $xx)
osamu@goofy ~> set -S zz
$zz: not set in local scope
$zz: set in global scope, unexported, with 3 elements
$zz[1]: length=5 value=|a\nb c|
$zz[2]: length=0 value=||
$zz[3]: length=1 value=|d|
$zz: not set in universal scope

```
`unescape` didn't work as expected by the name but simple eval seems to work.  I think `eval` creates problem if a string contains `$` and other special characters.

I agree fish has cleaner command line substitution syntax but it has its own share of complication too.

**Comment by krobelus** [comment] 2019-11-05 19:09
> I see for `set` and `split0`. This needs to be elaborated in documentation more explicitly. (I now see this is 3.0 feature after reading #3164 . `( ... )` seems to produce array data instead of string. Interesting. This is not so obvious for new fish user.
OK, we should improve that.
> 
> I am not quite sure about your comment " haven't got that working" ... Do you mean `-z` eoesn't work as expected for `read`? That doesn't work for me, either. Is this bug in `-z` option or not?

I just meant that I personally don't really know `read`, I haven't used it much.
I found out how it works now, see below.

> 
> I still think that `read` has advantage since it is not limited by the command line length limitation (if it exists in fish.) So I looked for more POSIX-like scripting approach to read passed values. Actually, it was not so difficult if we are worried about newline and null string:

Both `set` and `read` are limited to 10MB of data by default (can be changed by setting `fish_read_limit`). I think the operating system's command line length limit does not apply for builtins.

> 
> 
> So use of `eval` together with `string escape` can also solve parameter passing problem for this limited scope. (I think there is price to pay for the use of `eval` though. Just think you have `$` in original string ...)

Yes, that works fine - eval inverses the escaping. Unlike in POSIX-compatible shells, no extra expansion is performed, so this will even work if your variable contains `'$'` (which will be `'\$'` after `string escape`)

> 
> That is why we need special option for `set` to unescape and **`read` with functioning `-z` option or `--eval` option are nice to have**. Also for readability, syntax like `string escape --style=array ...` to avoid use of `echo` is nice to have.

I think `eval set` already works just fine (albeit not all too discoverable).

`read -a` reads an array from a single line, but fish separates records/list items by newlines.
That's why the echo is needed here. I think `read` is the only function that works like this, everything else in fish I can think of splits on newlines, so `--style=array` wouldn't` make much sense.

Since you already escaped the newlnes in the function's output you can use newlines as record separator alright: similar to most fish functions, string escape prints each of its outputs on a newline:

```fish
function foo
    set out a '$HOME' 'c
    d'
    string escape -- $out
end
eval set aa (foo)
# we can make read read one element per line with -d \n
# additionally we need to add -z to prevent stopping after the first line
read -z -d \n -a bb
# $aa is the same as $bb
```

> `unescape` didn't work as expected by the name but simple eval seems to work. I think `eval` creates problem if a string contains `$` and other special characters.

Yes so this is the unfortunate case of strings containing `\n`. Each element is printed on a new line, and also the escaped newlines (`'\n'`) are turned into newline characters by string unescape. It should, however, work for strings not containing newlines.
In my experience it's rare in fish to have variables with newlines - instead you usually have an array variable with one element per line.

I'm pretty sure it works fine with eval, as stated above.

> 
> I agree fish has cleaner command line substitution syntax but it has its own share of complication too.

Yeah, some cases with newlines in strings are tricky but `string escape` + `eval` works, or `printf '\0'` + `split0`, too.

**Comment by faho** [comment] 2019-11-30 09:48
#6366 would add a `--tokenize` option to `read` that would basically do this.

However in the typical case I'd recommend passing output with NUL and reading it with `read -z` or `string split0`, or simply setting a global variable.

Closing as duplicate of #3823, because that's the only thing remaining to be done.

**Closed by faho** 2019-11-30 09:48 UTC
