### ISSUE TITLE
prevent automatic execution of pasted commands

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3786] opened 2017-01-27 03:02 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: macOS 10.12.2 iTerm 3.0.13

See https://lifepluslinux.blogspot.ca/2017/01/look-before-you-paste-from-website-to.html

Fish currently executes the command automatically instead of waiting for a manual enter. It should wait for a manual enter before executing any pasted commands.

Fish can check if a command is pasted with [bracketed-paste](https://cirw.in/blog/bracketed-paste) mode.

**Comment by krader1961** [comment] 2017-01-27 03:22
Duplicate of #967 (and #2251, and #2188)

**Closed by krader1961** 2017-01-27 03:22 UTC
