### ISSUE TITLE
SIGINT during prompt output cuts it off

### ISSUE THREAD

**Issue by rafzi** [fish-shell/fish-shell#6313] opened 2019-11-11 13:29 UTC
Sometimes, when pressing Ctrl+C during the printing of the prompt, it gets cut off. If there was a color change, it stays for the rest of the next input. Occasionally this happens during normal use when pressing Ctrl+C multiple times fast.

Not sure how to solve this. Maybe buffer the prompt and flush it atomically? Would it make sense to mask SIGINT during prompt printing? Or mask it for a limited time?

fish 3.0.1
Ubuntu 18.04
xterm
This is very easy to reproduce with OMF "agnoster" by spamming Enter and Ctrl+C, but I could not reproduce it without customizations (maybe just difficult to time)

[![asciicast](https://asciinema.org/a/sX6y2MEJfBcXOYqGKa47aR801.svg)](https://asciinema.org/a/sX6y2MEJfBcXOYqGKa47aR801)

**Comment by zanchey** [comment] 2019-11-11 13:35
> when pressing Ctrl+C during the printing of the prompt

I am not sure why you are doing this?

Probably it only happens with this prompt because it calls an external command.

**Comment by faho** [comment] 2019-11-13 07:48
It seems to me like the color is really the only annoyance. So maybe we should just reset color after the prompt?

**Comment by faho** [comment] 2021-03-12 10:57
Duplicate of #6563

**Closed by faho** 2021-03-12 10:57 UTC
Labels: enhancement
