### ISSUE TITLE
fish_config error on ArchLinux

### ISSUE THREAD

**Issue by berceanu** [fish-shell/fish-shell#1754] opened 2014-10-13 15:43 UTC
```
Web config started at 'file:///home/berceanu/.cache/fish/web_config-6QXK2T.html'. Hit enter to stop.
Traceback (most recent call last):
  File "/usr/share/fish/tools/web_config/webconfig.py", line 723, in <module>
    ready_read = select.select([sys.stdin.fileno(), httpd.fileno()], [], [])
NameError: name 'httpd' is not defined
```

**Comment by drbig** [comment] 2015-01-03 17:21
Honestly, a localhost web config thingy that's effectively IPv6-only because 'IPv6 is a thing' seems weird to say the least (and to stay polite). Especially so when you support Python 2 (as passé as IPv4). The only good thing here is that `fish_config` is not necessary for anything.

**Comment by zanchey** [comment] 2015-01-05 00:12
Of systems configured as {IPv4-only, IPv4+IPv6, IPv6-only}, the current code runs fine on the latter two. Note that you don't need actual transit to anything - just a loopback interface with protocol support. Patches to make the first case work are welcome but care needs to be taken as it is easy to break the last case. My comment regarding IPv6 being a thing nowadays is driven by every major OS and distribution shipping with IPv6 configured. Whether that is a reasonable expectation for optional components of fish shell is, of course, a matter of perspective.

**Comment by xfix** [comment] 2015-03-29 10:43
```
xfix@localhost ~> fish_config
Web config started at 'file:///home/xfix/.cache/fish/web_config-V31TQX.html'. Hit enter to stop.
Traceback (most recent call last):
  File "/usr/share/fish/tools/web_config/webconfig.py", line 723, in <module>
    ready_read = select.select([sys.stdin.fileno(), httpd.fileno()], [], [])
NameError: name 'httpd' is not defined
xfix@localhost ~> uname -a
Linux localhost 2.6.35.7 #1 PREEMPT Sat Dec 27 04:09:19 CET 2014 armv6l GNU/Linux
```

Occurs on my phone as well with kernel that has disabled IPv6 support, and I cannot enable it because I don't have a source code for it. Will look into that issue soon.

**Comment by ridiculousfish** [comment] 2015-05-18 02:18
Ought to be fixed in 386d6a7. Thanks for reporting this!

**Closed** 2015-05-18 02:18 UTC

**Comment by ridiculousfish** [comment] 2015-05-18 02:31
Merged to master as 386d6a77f2885373356bb4be4808899658d0549a

**Comment by zanchey** [comment] 2015-05-20 16:12
I wonder if we could ask @g-nix, who IIRC runs without IPv4, to check that that still works.

**Comment by ridiculousfish** [comment] 2015-05-20 18:21
It would definitely be good for g-nix to confirm, but I was able to reproduce the issue with a Ubuntu VM and verify the fix, so I feel confident in it.

**Comment by pickfire** [comment] 2015-05-29 06:03
I get an error when using `fish_config` in Arch Linux too. I use a proxy and use ipv4. When I run `fish_config`:

![2015-05-29-140151_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/7877289/649e86a6-060b-11e5-9640-439b6556905d.png)

**Comment by ridiculousfish** [comment] 2015-05-29 06:05
I don't know anything about SOCKS. Any idea what's going on here?

**Comment by pickfire** [comment] 2015-05-29 07:37
I am using [`tor`][1] with [`polipo`][2]. [`Tor`][1] is **The Second Generation Onion Router** which uses the [socks5 protocol][3] and [`polipo`][2] is a **lightweight web caching server**.

[1]: torproject.org "The Onion Router"
[2]: https://en.wikipedia.org/wiki/Polipo
[3]: https://en.wikipedia.org/wiki/SOCKS

**Comment by ridiculousfish** [comment] 2015-05-29 07:46
Thanks for those details. fish isn't trying to be fancy here - just connecting to a port on localhost. Is there something we ought to be doing to handle this case?

**Comment by zanchey** [comment] 2015-05-29 08:05
My guess is that one of those two intermediate processes doesn't have an exception for local interfaces set.

**Comment by pickfire** [comment] 2015-05-29 08:52
I change the proxy in the browser then reload the page and it seems that it can't reload. The only way to get past this is to use firefox as firefox can define the exception for proxy. What I wanted is to reload the page and it doesn't work anymore.
