### ISSUE TITLE
Lot of errors logging from fish shell inside IntelliJ provided by Ubuntu snap

### ISSUE THREAD

**Issue by patope** [fish-shell/fish-shell#5623] opened 2019-02-06 13:00 UTC
fish, version 3.0.0
Linux robot 4.18.0-14-generic #15-Ubuntu SMP Mon Jan 14 09:01:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color

steps to reproduce:
1. Install IntelliJ snap `sudo snap install intellij-idea-community --classic`
2. Open IntelliJ and project.
3. Open terminal
terminal dumps lot of error message
```
<E> fish: Unable to open universal variable file '/snap/intellij-idea-community/118/plugins/terminal/fish/fish_variables': Read-only file system
```

Snap mounts intellij snap image file as read-only filesystem. Requested file do not exists on image.
Here
https://github.com/fish-shell/fish-shell/blob/fe67cc4f6e6174db91b7893c3726dd5e03613967/src/env_universal_common.cpp#L573
fish tries to open and lock file, but guess locking file on read-only files system is no possible.

**Comment by faho** [comment] 2019-02-06 13:29
Duplicate of #3988 - intellij stuff does weird things to inject their own config. This is tracked upstream at https://youtrack.jetbrains.com/issue/IDEA-169111.

**Closed by faho** 2019-02-06 13:29 UTC
