### ISSUE TITLE
Do not stop on spaces when using backward-kill-path-component

### ISSUE THREAD

**Issue by gokulsoumya** [fish-shell/fish-shell#7175] opened 2020-07-04 06:48 UTC
The current behaviour of `backward-kill-path-component` (`Ctrl-W` by default), taken from the man page:

> `backward-kill-path-component`, move one path component to the left of the cursor to the killring. A path component is everything likely to belong to a path component, i.e. not any of the following: `/={,}'":@ |;<>&`, plus newlines and tabs.

It'd be nice if a backslash escaped space was also considered as part of the path component so that it behaves more predictably when used on paths with spaces in them.

**Comment by faho** [comment] 2020-07-04 06:58
Duplicate of #2016

**Closed by faho** 2020-07-04 06:58 UTC
