### ISSUE TITLE
git change-directory completion broken

### ISSUE THREAD

**Issue by zeptoShank** [fish-shell/fish-shell#9075] opened 2022-07-16 05:13 UTC
Fish 3.5.0 installed with `brew`; using Terminal.app on macOS 12.4. I tried with and without my configurations, using the provided instructions. Happens every time. Never happened before 3.5.0.

  * `git --cd <space><tab><tab>` crashes fish, closing the tab. (Terminal.app itself does not quit, which may or may not be relevant.)
  * `git -C <space><tab><tab>` does the same.

**Comment by faho** [comment] 2022-07-16 06:14
Duplicate of #9053

**Closed by faho** 2022-07-16 06:14 UTC
