### ISSUE TITLE
username encoding with ssh

### ISSUE THREAD

**Issue by Estirp** [fish-shell/fish-shell#9472] opened 2023-01-14 06:03 UTC
**YOUR TEXT HERE**
fish, version 3.5.1
Linux paralllpipde 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux
alacritty

When I connect through ssh to an accented account with bash in remote, my accent is right. But with fish, it is wrong.
remotely :
`usermod -s /bin/bash mnémosyne`

locally :
```
ssh -v mnémosyne@svg
...
[mnémosyne@paralllpipde ~]$ env | grep syne
PWD=/home/mnémosyne/
LOGNAME=mnémosyne
HOME=/home/mnémosyne/
USER=mnémosyne
MAIL=/var/spool/mail/mnémosyne
```

remotely :
`usermod -s /bin/fish mnémosyne`

locally (partially translated) :
```
...
debug1: Remote: /home/mn\303\251mosyne//.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /home/mn\303\251mosyne//.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
...
error: Unable to open universal variable file '/': No such file or directory
mkdir: impossible to create directory « /home/mnÃ©mosyne »: Permission denied
...
mnÃ©mosyne@paralllpipde ~> env | grep syne
PWD=/home/mnÃ©mosyne
LOGNAME=mnÃ©mosyne
USER=mnÃ©mosyne
MAIL=/var/spool/mail/mnÃ©mosyne
HOME=/home/mnÃ©mosyne/
```

Once logged, my accent appears right, except username : 
`mnÃ©mosyne@paralllpipde ~> ééê`

**Comment by faho** [comment] 2023-01-14 06:30
What is the output of `locale` on both systems?

**Comment by faho** [comment] 2023-01-14 07:38
This is either a duplicate of #2613 (fish won't re-encode environment variables when the locale changes), or #2613 is going to make working around issues with your configuration awkward.

At which point tbh let's split the difference and call it a

duplicate of #2613

**Closed by faho** 2023-01-14 07:38 UTC
Labels: needs more info

**Comment by Estirp** [comment] 2023-01-14 08:53
locally : 
```
~> locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

remotely :
```
~> locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by faho** [comment] 2023-01-14 09:05
Yeah, that's gonna import $USER, then change the locale, in some manner. We have a hack that reads /etc/locale.conf (added specifically because arch unsets $LANG for getty), and that would happen too late.

See if you can set AcceptEnv (for sshd) and SendEnv for ssh to include $LANG and friends: https://stackoverflow.com/a/29609673/3150338

In short: Add `SendEnv LANG LC_*` to your ssh_config (the client part) and `AcceptEnv LANG LC_*` to your sshd_config (the server part).

**Comment by Estirp** [comment] 2023-01-14 14:20
It work !
Thank you very much.
