### ISSUE TITLE
Autosuggestion disappear on backspace

### ISSUE THREAD

**Issue by Ddystopia** [fish-shell/fish-shell#9598] opened 2023-02-20 12:58 UTC
## Autosuggestion disappear on backspace
  `fish --version`
fish, version 3.6.0
  `echo $version`
3.6.0

`$ uname -a`
Linux ddps76 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux
`$ echo $TERM`
alacritty
```fish
$ echo "To History"
$ ech# start typing `ech...`
````

Then the autosuggestion appears, I keep typing a few characters.
I type backspace, the autosuggestion disappears. If I delete another character and type it again, the autosuggestion appears.

## Expected behaviour:
Autosuggestion be present even after backspace

**Comment by faho** [comment] 2023-02-20 13:08
Duplicate of #3549

**Closed by faho** 2023-02-20 13:08 UTC
