### ISSUE TITLE
Perl autocomplete broken

### ISSUE THREAD

**Issue by yshui** [fish-shell/fish-shell#3929] opened 2017-03-31 21:57 UTC
fish version: 2.5.0

When trying to autocomplete perl command, this is shown:

```
$, is not a valid variable in fish.
/usr/share/fish/completions/perl.fish (line 5):                         | sed -e 's,/,::,g; s,\.pm$,,' | sort -u)"
                                                                                                 ^
from sourcing file /usr/share/fish/completions/perl.fish
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “/usr/share/fish/completions/perl.fish”
```

**Comment by faho** [comment] 2017-03-31 21:59
This is a duplicate of #3856, which is, you'll be happy to know, already fixed and will be in the next release.

**Closed by faho** 2017-03-31 21:59 UTC
