### ISSUE TITLE
commandline cannot append/prepend/replace buffer after upgrading from 3.3.1 to 3.4.1

### ISSUE THREAD

**Issue by speed2exe** [fish-shell/fish-shell#8852] opened 2022-04-03 17:16 UTC
term:
```
zx@arch /h/zx> echo $TERM
xterm-256color
```
uname:
```
zx@arch /h/zx> uname -a
Linux arch 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux
```

Tried with `sh -c 'env HOME=$(mktemp -d) fish'`

fish 3.3.1
```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
zx@arch /h/zx> commandline "some_text"
zx@arch /h/zx> some_text
```

fish 3.4.1
```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
zx@arch /h/zx> commandline "some_text"
zx@arch /h/zx> 
```

commandline does not work as expected based on `commandline -h`:
"With CMD specified, the command line buffer is erased and replaced with the contents of CMD."

**Comment by ridiculousfish** [comment] 2022-04-03 17:42
Duplicate of #8807

**Closed by ridiculousfish** 2022-04-03 17:42 UTC
