### ISSUE TITLE
zcat autocompletion with substring match changes `~` to `\~` for some reason

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#8143] opened 2021-07-14 19:56 UTC
This happens without any customizations, using fish from master (900e4a232e2949367a196c09777a7153c1e315d4) or 3.3.1.

I have a directory structure like: `/home/ericonr/void/void-packages/`, inside of which lies some file I want to decompress to stdout. So I type `zcat ~/void/pack` then press TAB, expecting autocomplete to do its job, but instead my prompt becomes `zcat \~/void/void-packages/`, which is not only wrong but it also breaks any further completion.

It seems to be caused by `__fish_complete_suffix`, because if I remove 

```
complete -c zcat -k -x -a "(
	__fish_complete_suffix .gz
	__fish_complete_suffix .tgz
)
"
```

from `share/completions/zcat.fish`, things are back to completing correctly.

**Comment by faho** [comment] 2021-07-14 20:03
Duplicate of #4570.

**Closed by faho** 2021-07-14 20:03 UTC
