### ISSUE TITLE
2-line prompt breaks tab completion err

### ISSUE THREAD

**Issue by teppay** [fish-shell/fish-shell#4949] opened 2018-04-27 09:29 UTC
In following two examples, I inputted only 'qwerty' + tab.
And any command which named qwerty* are not exist

When I use 1-line prompt,
![qwerty](https://user-images.githubusercontent.com/29748556/39355058-1f66e776-4a47-11e8-8c5a-b6e532bf18bd.gif)

But, when I use 2-line prompt,
![qwerty2](https://user-images.githubusercontent.com/29748556/39355353-f5ec6c94-4a47-11e8-9c88-f2611151023c.gif)

In fish, when the tab completion fail, it change the background color for an instant
I guess the function is related this problem

Sorry if it's wrong.

The following is my fish_prompt.fish when 1-line prompt
```fish
function fish_prompt --description 'Write out the prompt'
	set -l home_escaped (echo -n $HOME | sed 's/\//\\\\\//g')
    set -l pwd (echo -n $PWD | sed "s/^$home_escaped/~/" | sed 's/ /%20/g')
    set -l prompt_symbol ''
    set -x fish_color_cwd red
    set -x fish_color_param green
    switch "$USER"
        case root toor
            set prompt_symbol '#'
        case '*'
            set prompt_symbol '$'
    end

    echo -ns "[$USER" @ (prompt_hostname) ' ' (set_color $fish_color_cwd) $pwd (set_color normal) ']'
    echo -n "$prompt_symbol > "
end
```

The following is my fish_prompt.fish when 2-line prompt
```fish
function fish_prompt --description 'Write out the prompt'
	set -l home_escaped (echo -n $HOME | sed 's/\//\\\\\//g')
    set -l pwd (echo -n $PWD | sed "s/^$home_escaped/~/" | sed 's/ /%20/g')
    set -l prompt_symbol ''
    set -x fish_color_cwd red
    set -x fish_color_param green
    switch "$USER"
        case root toor
            set prompt_symbol '#'
        case '*'
            set prompt_symbol '$'
    end

    echo -s "[$USER" @ (prompt_hostname) ' ' (set_color $fish_color_cwd) $pwd (set_color normal) ']'
    echo -n "$prompt_symbol > "
end
```

The following is the information of my environment.
```fish
$ echo $version
2.7.1

$ uname -a
Darwin TSMBP.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

$echo $TERM
xterm-256color
```

**Comment by faho** [comment] 2018-04-27 09:45
This looks like a duplicate of #3093 to me.

**Closed by faho** 2018-04-27 09:45 UTC
