### ISSUE TITLE
Completions of commands from local directory is sometimes slow

### ISSUE THREAD

**Issue by grossjohann** [fish-shell/fish-shell#6327] opened 2019-11-15 16:06 UTC
I'm running fish version 3.0.2, on macOS Catalina 10.15.1; fish was installed via Homebrew.

I have a directory with 26 files, 6 of which are `*.sh` files that are executable.  (There are no subdirectories in this directory.)  Because `.` is not in my path, I execute these scripts by their local names, e.g. `./swap-example-data.sh`.  This script is the only file among the 26 files that begins with "sw".  So I expect that typing `./sw` and then hitting the tab key will complete the command.  It does that, but there is a perceptible delay.  But if I type, say `vim ./sw` and then hit the tab key, then filename completion is instantaneous.

I've tried this using my normal shell setup, and then I've tried it using the clean setup using `sh -c 'env HOME=$(mktemp -d) fish'`, as instructed in the guidelines for submitting issues.  I find that the clean setup is faster, but there is still a perceptible delay.

Let me try to give a broad summary:

`vim ./sw` completes instantly in a clean profile, as well as in my own profile.  (It's not specific to the command, `ls ./sw` is instantaneous, too.)

`./sw` in a clean profile completes with a perceptible delay, say X milliseconds.

`./sw` in my own profile completes with a larger perceptible delay, say 2*X milliseconds.

I have no clue where to start profiling, or even how to measure it accurately.  Is there a command that I could run that would tell fish to generate all completions of `./sw` when typed in the command position, versus `./sw` when typed at the argument position?  Then I could time those commands.

**Comment by faho** [comment] 2019-11-15 16:11
Duplicate of #6270 - we try to get a command description by executing `apropos` even for relative paths, and that takes ages because Apple screwed it up in Catalina.

**Closed by faho** 2019-11-15 16:11 UTC
