### ISSUE TITLE
Fish hangs when piping ffmpeg's stderr 

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#3389] opened 2016-09-18 12:48 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: arch inux, termite

Hi,
Running the following command
```
for i in **flac
    if ffmpeg -i $i ^| grep s32
        echo $i
    end
end
```
behaves strangely and hangs after some time, leaving two dead child processes (ffmpeg and grep).
It hangs on a different file every time I execute the command, though.

I think it's the `ffmpeg -i $i ^| grep s32` that is the cause of the problem but I'm not sure why. I can't reproduce it using different programs (like cat instead of ffmpeg).

I believe it is fish related, because running 
```
shopt -s globstar
for i in **/*flac; do if ffmpeg -i "$i" 2>&1 | grep s32; then echo $i; fi; done
```
in bash terminates normally.

**Comment by faho** [comment] 2016-09-18 13:11
This is most likely #1396.

The `grep` here is a wrapper function, and as such will (annoyingly) buffer its stdin.

The workaround is to use `command grep` (or `string match`).

**Comment by occivink** [comment] 2016-09-18 13:18
Actually I was using `ag` initially and the same problem occured, so I don't think that's it. `command grep` doesn't work either.

**Comment by faho** [comment] 2016-09-18 15:04
> command grep or string match don't work either.

That's weird. I just tested it on arch's fish 2.3.1 and it works. What I used was

```fish
for i in **flac
    if ffmpeg -i $i ^| command grep s32
           echo $i
    end
end
```

What do `type ffmpeg` and `type grep` say?

**Comment by occivink** [comment] 2016-09-18 15:09
Ah yeah I have a function ffmpeg defined as 
```
function ffmpeg
    command ffmpeg -hide_banner $argv
end
```
You're correct that if I use `command ffmpeg` it does work.

**Comment by faho** [comment] 2016-09-18 15:15
Closing this as a duplicate of #1396. Sorry for the inconvenience.

**Closed by faho** 2016-09-18 15:15 UTC

**Comment by occivink** [comment] 2016-09-18 15:17
Thanks for your help.
