### ISSUE TITLE
Read-only variables are silently ignored when setting using `SHLVL=3 command` syntax

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8178] opened 2021-07-28 00:20 UTC
fish 3.3.1

`SHLVL` is a global exported variable. It's also read-only. `set SHLVL 5` fails as expected. But surprisingly, trying to set it as part of command invocation silently ignores this, even though there's no reason to do so.

For example:

```
> SHLVL=5 env | grep SHLVL
SHLVL=1
```

I expect this is because `begin; set -lx SHLVL 5; cmd; end` fails (`set: Tried to modify the special variable 'SHLVL' with the wrong scope`). I don't know why this restriction exists. At first glance this seems unrelated to me writing `SHLVL=5 cmd`, but if `cmd` is a fish function then it becomes equivalent to the `set -lx` version.

This could be partially fixed by saying "if `cmd` is an external command, allow any variable to be set, including read-only ones; if `cmd` is a fish function then prohibit this". But this would be a source of confusion, especially since it means `alias cmd other_cmd` would cause a previously-working `SHLVL=5 cmd` to start failing.

I think the real fix is to simply allow special variables to be overridden in local scope.

In the meantime, `SHLVL=5 cmd` really should be printing a warning about how `SHLVL` is a special variable and cannot be overridden this way.

Note: This isn't just `SHLVL`, I can reproduce it with `PWD` too. I'm not sure offhand what other special variables exist that are both read-only and exported.

**Comment by faho** [comment] 2021-07-28 05:57
>I think the real fix is to simply allow special variables to be overridden in local scope.

I don't agree. That means e.g. `set -l history` or `set -l status` should work, and they very much shouldn't.

Instead this should error the same.

**Comment by faho** [comment] 2021-07-28 05:58
Duplicate of #7790

**Closed by faho** 2021-07-28 05:58 UTC
