### ISSUE TITLE
Possibly unintentional inconsistency in tilde (~) expansion?

### ISSUE THREAD

**Issue by cstyles** [fish-shell/fish-shell#7405] opened 2020-10-17 21:55 UTC
I've noticed that since the introduction of the `$ FOO=bar command` syntax to fish in #6287, different tilde expansion rules are used when setting an environment variable for a specific command:

```fish
$ env foo=~ fish -c 'echo $foo'
~
$ foo=~ fish -c 'echo $foo'
/home/cstyles
```

Is this intentional? In [this comment](https://github.com/fish-shell/fish-shell/issues/6048#issuecomment-524440474) under list item 2, it was proposed that...

>`FOO=bar` should produce the exact same variable that `set -lx FOO bar` does

...in which case the above behavior would be expected. But it's not clear to me from the thread if that suggestion ended up being adopted.

Assuming that the new syntax was added to make fish easier to transition to for people accustomed to bash/zsh/etc., it might make sense to emulate bash's expansion rules but it does deviate from the (as far as I know) otherwise universal rule of "tildes are only expanded at the beginning of a word".

Fish version: 3.1.2
OS: Both Linux and macOS

**Comment by krobelus** [comment] 2020-10-18 17:52
Good point. It looks like Bash special-cases tokens that look like variable assignments, it expands the tilde in `a=~` but not in `a:~`. I guess we could follow.

> FOO=bar should produce the exact same variable that set -lx FOO bar does

Yeah, that should be the current behavior.

**Comment by faho** [comment] 2021-05-03 14:12
Duplicate of #1410

**Closed by faho** 2021-05-03 14:12 UTC
Labels: enhancement
