### ISSUE TITLE
Web pages opened with the fish_config command do not have abbreviations

### ISSUE THREAD

**Issue by ZhangWeinian** [fish-shell/fish-shell#10733] opened 2024-09-19 14:31 UTC
fish: version 3.7.0
os: win11 & wsl2 with ubuntu 24.04 lts

Everything worked fine when using Ubuntu 22 before.
Just now, I used commands related to WSL to download and use Ubuntu 24 on the terminal. Following the configuration of Ubuntu 22, I made some configurations for the new Ubuntu 24. However, when I opened FishConfig, there was no option to set custom aliases.
I'm not sure what caused this, I hope someone can help me!

The appearance of the webpage when opened
![image](https://github.com/user-attachments/assets/7c1c5f1e-c8dd-4d05-9f80-e5fc6a22497e)

wsl
![image](https://github.com/user-attachments/assets/3683a0bf-d3c7-48db-a495-443e597c6d6f)

ubuntu
![image](https://github.com/user-attachments/assets/ab80afe3-2b3a-428e-bf2b-1ba7ca5d8e27)

**Comment by faho** [comment] 2024-09-19 14:35
Duplicate of #9460

**Closed by faho** 2024-09-19 14:35 UTC
