### ISSUE TITLE
Man pages and --help option problems.

### ISSUE THREAD

**Issue by smootharc** [fish-shell/fish-shell#8047] opened 2021-06-05 10:54 UTC
Hello,

~/.c/fish> fish -v                                                                                                                                                                               
fish, version 3.2.2

~/.c/fish> uname -a                                                                                                                                                                              
Linux ds 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux

sh -c 'env HOME=$(mktemp -d) fish' did not help the problem.

Some examples of the problem:

~/.c/fish> man fish                                                                                                                                                                              
No manual entry for fish

~/.c/fish [16]> functions --help                                                                                                                                                                 
fish: Missing man page for 'functions'. Did you install the documentation?

~/.c/fish> man abbr                                                                                                                                                                              
No manual entry for abbr

abbr --help returns nothing and the errorlevel is 0.

~/.c/fish [1]> man -w                                                                                                                                                                            
/usr/share/fish/man:/usr/local/man:/usr/local/share/man:/usr/share/man

The man pages are in /usr/share/fish/man as they should be but they seem to be ignored.

The help command works fine by the way.

I created a new user account and logged in to that account.  The directory ~/.config/fish for that account contains only the file fish_variables.  The man problems are exactly as shown above.

**Comment by faho** [comment] 2021-06-05 11:00
>The man pages are in /usr/share/fish/man as they should be but they seem to be ignored.

This looks like #7996, so please confirm you have files at e.g. /usr/share/fish/man/man1/type.1, and not /usr/share/fish/man/man1/1/type.1 (see the extra "/1").

Arch patched this out and Sphinx fixed it in 4.0.2, but it's possible Manjaro didn't get the fix or hasn't rebuilt fish after.

**Comment by faho** [comment] 2021-06-05 11:07
Alright, it appears Manjaro just imports Arch's packaging here (no pkgbuild at https://gitlab.manjaro.org/packages/community). The newest version of the package I can find on a Manjaro mirror is fish 3.2.2-1, while Arch fixed it in 3.2.2-2.

Also the package I downloaded doesn't appear to have man pages at all which would confirm it was built with a broken sphinx.

So this is a Manjaro issue, open a bug with them. They simply need to import Arch's fix or rebuild the package with the fixed sphinx I believe they already have.

**Comment by smootharc** [comment] 2021-06-05 11:33
Fabian,

Wow, that was fast!  The man pages do have an extra 1.  I thought it might
be a packaging problem!  Just after I posted this problem to git I
installed Manjaro to a single formatted disk on another machine
then, updated and and installed fish.  All the problems were exactly the
same!  This started some months ago, but I never got around to 'fixing' the
problem.  Is it possible to get the package manager to fix this?  Could
someone send him an email?  I'll do it if it is possible.

Thanks

**Comment by faho** [comment] 2021-06-05 12:04
According to https://manjaro.org/branch-compare/, 3.2.2-2 is in Manjaro's "testing" repository, so really you'll just have to wait.

As a workaround, just use `help thing` instead of `thing --help` - that will open up the help in your browser, and use the online version at https://fishshell.com/docs/current/index.html if the files aren't available locally.

Since there's nothing really to do here, I'm closing this as a duplicate of #7996.

**Closed by faho** 2021-06-05 12:04 UTC

**Comment by smootharc** [comment] 2021-06-05 12:11
Thanks!
