### ISSUE TITLE
fish shell can't be used to configure cgroups

### ISSUE THREAD

**Issue by hao-lee** [fish-shell/fish-shell#7919] opened 2021-04-10 15:50 UTC
```
# fish --version
fish, version 3.2.1
# uname -a
Linux localhost.localdomain 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
>
> sh -c 'env HOME=$(mktemp -d) fish'

No.

### Reproduce:

```
# cd /sys/fs/cgroup
# mkdir test && cd test
# echo +memory > cgroup.subtree_control
write: Invalid argument
```

However, the following command can run successfully so I think it's a bug of fish shell

```
# bash -c 'echo +memory > cgroup.subtree_control'
```

**Comment by faho** [comment] 2021-04-10 16:09
Duplicate of #7836

**Comment by faho** [comment] 2021-04-10 16:09
Fixed in the next release, use `command echo` as a workaround.

**Closed by faho** 2021-04-10 16:09 UTC

**Comment by hao-lee** [comment] 2021-04-11 03:46
Thanks!
