### ISSUE TITLE
Auto complete with aura prints errors

### ISSUE THREAD

**Issue by valters-tomsons** [fish-shell/fish-shell#7951] opened 2021-04-24 10:30 UTC
**Fish version:** 3.2.1
**Operating system:** Arch Linux (kernel 5.11.14)

Using autocomplete with [aura package manager](https://github.com/fosskers/aura) prints a bunch of errors. This happens whenever I press SPACE or TAB after.

[![asciicast](https://asciinema.org/a/pUENHmW1qVc30Xt69vT9YPqrr.svg)](https://asciinema.org/a/pUENHmW1qVc30Xt69vT9YPqrr)

**Comment by faho** [comment] 2021-04-24 11:27
Duplicate of #7865

**Comment by faho** [comment] 2021-04-24 11:28
Yeah, Arch still hasn't managed to upgrade to 3.2.2.

**Closed by faho** 2021-04-24 11:27 UTC
