### ISSUE TITLE
No easy way to start fish shell without user config

### ISSUE THREAD

**Issue by mohd-akram** [fish-shell/fish-shell#3288] opened 2016-08-04 09:12 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_: 2.3.1

**OS/terminal used**: OS X 10.11.6

Bash has `--noprofile` and `--norc` to start it without any user config, but there doesn't seem to be an easy way to do this with fish shell.

**Comment by zanchey** [comment] 2016-08-04 09:26
Usually I do this with `env HOME=/tmp/foo fish`, or you can point `XDG_CONFIG_HOME` and `XDG_DATA_HOME` to a nonexistent location.

**Comment by mohd-akram** [comment] 2016-08-04 09:28
The problem with that is that other applications might depend on these variables.

**Comment by faho** [comment] 2016-08-04 11:33
The question is: What do you want this for?

We usually want to disable configuration to see whether that caused an issue in fish. For that, the `env` thing works nicely because you don't really need to use other applications then.

If you are unhappy with your configuration, you can change it, and if you'd like to temporarily have a variable have a different value, you can do that interactively. I can't come up with anything where this option might be useful - though that may just be my lacking imagination.

**Comment by mohd-akram** [comment] 2016-08-04 21:01
Well, actually a plugin I was using was behaving strangely as it started a child fish shell using `fish -c "command goes here"`, but the reevaluation of the config.fish file was causing some conflicts. I can see this being useful for running jobs/child shells which can avoid the unnecessary overhead of loading a user's config and can behave more predictably. Furthermore, even in the use case you mentioned, changing `env` feels a bit hacky. I'm still new to fish shell so excuse any ignorance on my part :)

**Comment by krader1961** [comment] 2016-08-04 23:38
@mohd-akram, How exactly would a `--noprofile` option help in the scenario you cited? If a script is explicitly starting a sub-shell via something like `fish -c "some_command"` it would not be affected by the use of `--noprofile` in the parent shell and would still source your config. On the other hand, explicitly changing the relevant env vars as mentioned by others would affect the child shell and keep it from using your customized config.

Altering env vars can, obviously, affect other programs launched by fish so it's not ideal. The only way I can see to avoid that and still affect subshells would be to define a new env var that fish looks at for startup options. Similar to how the less(1) command uses the `LESS` env var.

**Comment by mohd-akram** [comment] 2016-08-05 00:07
I'm not sure what you mean. I just tried now with bash and it doesn't read the .bashrc or .bash_profile at all when invoked with `-c` (which I think is an appropriate behavior), though it does inherit the parent shell variables like any other process. I tested this by putting an `echo` statement in both of them.

Fish on the other hand loads the config for any child shell and not just interactive shells. Perhaps if this behavior is changed there would be no real need for a new flag.

**Comment by krader1961** [comment] 2016-08-05 00:20
> I'm not sure what you mean. 

When you run `bash --norc` that only affects the interactive shell you started with that flag. If you then spawn another interactive shell without that flag it will read your *~/.bashrc*. Similarly for the `--noprofile` flag. Neither of those will affect a non-interactive shell which is what you get when running `bash -c "some_command"`. In other words, not even are those flags not passed to the sub-shell doing so would make any difference because that sub-shell is not interactive.

> bash and it doesn't read the .bashrc or .bash_profile at all when invoked with -c

True, but that's because bash has multiple config files and which ones are read depend on how the shell was started. Fish employs a different approach. It has a single user config file that is always source whether the shell is interactive or not. You're expected to use statements like `if status --is-interactive` or `if status --is-login` to limit which portions of the config are to be excluded from non-interactive sub-shells.

**Comment by mohd-akram** [comment] 2016-08-05 00:56
> If you then spawn another interactive shell without that flag it will read your ~/.bashrc. Similarly for the --noprofile flag.

I don't think this is really an issue, most likely a user will be spawning an interactive shell and they can pass these options again if they choose to.

>  You're expected to use statements like if status --is-interactive or if status --is-login to limit which portions of the config are to be excluded from non-interactive sub-shells.

Ah, that would be helpful in my case, although a bit of a burden on the user.

**Comment by krader1961** [comment] 2016-08-05 01:02
> ... although a bit of a burden on the user.

No more of a burden that putting some of your configuration in a hypothetical *~/.fish_profile*, some in *~/.fishrc*, etc.

**Comment by faho** [comment] 2016-08-24 21:39
@mohd-akram: Can you recall what exactly was causing your issue? Which plugin, what variable did you set?

Maybe there's an issue we can handle there, or maybe there's an actual case for a switch to disable configuration there. Currently it still feels like a cop-out.

**Comment by mohd-akram** [comment] 2016-08-26 13:31
The issue was vkovtash/pure#3.

**Comment by faho** [comment] 2016-08-26 15:13
@mohd-akram: That issue is caused by pure using a hack. The real solution would be solving #238, so that the pure prompt could then use proper background tasks, abandoning that hack.

**Comment by mohd-akram** [comment] 2016-08-26 15:54
Indeed, the developer of pure mentioned that in the issue. I figured allowing lightweight child shells could be an easier solution in the mean time.

**Comment by krader1961** [comment] 2016-11-16 04:06
Is there any reason this should not be closed? The proposed change would not solve the problem reported by the O.P. AFAICT. As @faho pointed out the real issue here is the inability to background a fish function.

**Comment by faho** [comment] 2016-11-17 21:51
Yes, let's close this. If anyone can make a case for why this is useful, feel free to do so and we might rethink it!

**Closed by faho** 2016-11-17 21:51 UTC
Labels: enhancement, RFC

**Comment by ridiculousfish** [comment] 2016-11-19 23:20
[bash's startup file rules](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html) are mind bending. fish's simple and consistent rules are a huge win. We shouldn't budge on which files are read at startup.

**Comment by legolord208** [comment] 2017-06-04 10:39
I only see the use of this for testing. For example, I had overriden the fish_greeting function. I realized I could just empty the fish_greeting variable. Now, the `env` trick worked, but having to google to find this issue and find a dirty hack was kind of disappointing. I think some quick way to disable it would fit nicely, if it's not too much trouble. Thanks.

**Comment by aabs** [comment] 2020-04-05 23:50
FWIW, I would have liked this feature so I can directly invoke an install script that modifies the config files themselves, without invoking the pre-existing config files first.  Something like this would be handy:

```shell
curl -skLq bit.ly/fishdots_install | fish --noconfig
```

As far as I am aware, no such flag exists; so things instead could get confusing and unpredictable during the install process of my little dotfiles framework.
