### ISSUE TITLE
Cygwin: Fish doesn't accept paths with colons in them for implicit CD

### ISSUE THREAD

**Issue by cbuschardt** [fish-shell/fish-shell#2961] opened 2016-04-21 04:03 UTC
Fish is overly restrictive on characters that may appear in paths.
### Reproduction Steps:

Type "c:/" or "cd c:/" without the quotes and press enter.
path_get_cdpath apparently doesn't allow for the path to contain a colon.  
### Expected behavior:

Command should succeed and switch directories.
### Observed behavior:

Command fails
### Additional information:

"ls c:/" works and even autocompletes directories. 

Fish version: 2.2.0 as part of Cygwin

**Comment by krader1961** [comment] 2016-04-21 04:33
That code has undergone substantial revisions since the 2.2.0 release. I don't have fish running on a MS Windows system. However, I executed the following on my OS X server using the current git head version and it works for me:

```
$ mkdir c:
$ mkdir c:/abc
$ touch c:/abc/def
$ c:/
```

Tab completion of those paths also works. We just entered a beta test period for fish 2.3.0. See the announcement at https://lists.sourceforge.net/lists/listinfo/fish-users. If you can test that I think you'll find fish now works as you expect.

**Comment by zanchey** [comment] 2016-04-21 13:48
I can reproduce this on Cygwin with 2.3b1.

The problem is not that fish bans colons in paths, but that it tries to stat "`./c:` before changing directory. Cygwin is smart enough to translate `c:` but not `./c:`.

**Comment by zanchey** [comment] 2016-04-21 14:25
Currently, `path_get_cdpath` in `src/path.cpp` is what tries to validate the path for `cd`, so this probably needs enhancing to try the raw path instead of `./somepath`.

**Comment by krader1961** [comment] 2017-03-20 04:04
In addition to not supporting drive letters fish doesn't let you use backslashes for the path separator.

**Comment by dragonejt** [comment] 2021-05-28 03:54
Are there any updates to this issue? I'm running v3.2.2 on cygwin and this error still persists

**Comment by andrew-schulman** [comment] 2021-06-14 12:16
On Thu, May 27, 2021 at 11:54 PM Evan Tung ***@***.***> wrote:

> Are there any updates to this issue? I'm running v3.2.2 on cygwin and this
> error still persists
>
Confirmed that the error is still there in fish 3.2.2 in Cygwin.

Note that it would be an enhancement to fix this, because the supported way
to do this in fish is to run `cd /cygdrive/c`. Granted that /cygdrive/c is
longer to type than c:/. Speaking for myself, I changed the drive prefix in
Cygwin from /cygdrive (annoyingly long) to /win, so the most I have to type
is `cd /win/c`, which is more Unixy and hardly any longer than `cd c:/`.

**Comment by ajeetdsouza** [comment] 2022-04-21 09:42
Related: https://github.com/fish-shell/fish-shell/issues/8883

**Comment by faho** [comment] 2022-04-21 09:57
Okay, I'm closing this one like #8883. The reason is that fish wants an absolute $PWD (because otherwise what even is $PWD?), and with things like `c:\` that's now a system-dependent thing. So it's not enough to make the cdpath code try "the raw path", we also need to figure that *this* path already counts as absolute.

It basically means making all our path-logic aware that sometimes windows paths exist. And sometimes they aren't `c:/something` but `c:\something`, so now it needs to handle backslashes as well.

It's also been open for five years with no progress, and as far as I'm aware there's always the possiblity of using a nice linuxy path.

Sorry!

**Closed by faho** 2022-04-21 09:57 UTC
Labels: enhancement, cygwin
