### ISSUE TITLE
Formatting issues in emacs

### ISSUE THREAD

**Issue by Nolski** [fish-shell/fish-shell#2983] opened 2016-04-28 22:16 UTC
So I'm a user of [spacemacs](https://github.com/syl20bnr/spacemacs) and when I enter ansi-term (or shell mode) the formatting of the command line seems to be fairly messed up when auto completion happens. Also the colors do not appear correctly.
### Reproduction Steps:

1. Install spacemacs or emacs
2. Open [shell mode](https://www.emacswiki.org/emacs/ShellMode) or [ansi-term](https://www.emacswiki.org/emacs/AnsiTerm)
3. just go about your normal fish usage. 

### Expected behavior:
fish completion and colors act as normal (example below)
https://asciinema.org/a/3a370guz2ss48nzqza4e0j5m4

### Observed behavior:
fish completion causes artifacts and colors are not correct (example below)
https://asciinema.org/a/8r9cllsfbyac7eizu5u16bgw9

### Additional information:
none
  

---
Fish version: [from the output of fish --version]
fish, version 2.2.0

Operating system: [your operating system and how you installed fish e.g. Homebrew, Ubuntu PPA, distribution package]
OSX (homebrew)

Terminal or terminal emulator: [e.g. PuTTy, iTerm2, GNOME Terminal, VT220]
iterm2

**Comment by faho** [comment] 2016-04-28 22:32
This is a duplicate of #2441.

Emacs ships its terminfo files in a weird location, so you need to execute `tic -o ~/.terminfo $TERMINFO/e/eterm-color.ti`.

Beyond that, though, all emacs term modes are pretty barren when it comes to features.

**Closed by faho** 2016-04-28 22:32 UTC
