### ISSUE TITLE
cd with wildcards behaves differently in 3.7.0 than in 3.6.4

### ISSUE THREAD

**Issue by OriginCode** [fish-shell/fish-shell#10211] opened 2024-01-14 12:08 UTC
- Fish Version: 3.7.0
- Operating System: AOSC OS 11.1.0 (GNU/Linux x86_64)
- `uname -a`: `Linux mashiro 6.6.8-aosc-main #1 SMP PREEMPT_DYNAMIC Thu Jan  4 07:06:24 UTC 2024 x86_64 GNU/Linux`
- `echo $TERM`: screen-256color

In Fish 3.6.4, for the following directory structure:

```
dir
├── subdir1
│   └── anotherdir
└── subdir2
```

While the current directory is `dir`, `cd */anotherdir` will change the directory to `./subdir1/anotherdir`. This behaves the same on Bash too.

However, in Fish 3.7.0, the above `cd` command will return `Too many args for cd command`. Tested on the default configuration.

**Comment by faho** [comment] 2024-01-14 12:21
Duplicate of #10205

**Closed by faho** 2024-01-14 12:21 UTC
