### ISSUE TITLE
Long commands cause whitespace to be input

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8561] opened 2021-12-20 06:49 UTC
This is most frequently noticed when pasting stuff like super long clang commands. I think it depends on the command taking up more lines than LINES.

A ton of spaces that I cannot account for end up in the command line. Here is an example. I stick a long space-separated string into my clipboard and paste it into Terminal.app.

https://user-images.githubusercontent.com/291142/146757800-2f112290-5051-4d64-8d4c-3458a4228421.mov

**Comment by floam** [comment] 2021-12-20 06:51
(Also encountered all the time if I make the mistake of pasting the contents of a .fish script into a terminal window, a common thing.)

**Comment by floam** [comment] 2021-12-21 00:38
Easier way to trigger it: make your terminal like 3 or 4 lines tall, and just type junk until you fill up a screen.

**Comment by krobelus** [comment] 2021-12-21 07:26
Duplicate of #7296

**Closed by krobelus** 2021-12-21 07:26 UTC
Labels: bug
