### ISSUE TITLE
up-arrow history search doesn't work correctly

### ISSUE THREAD

**Issue by JanKanis** [fish-shell/fish-shell#483] opened 2012-12-29 22:12 UTC
If I execute the following commands
```
echo foo
echo bar
echo baz
```
and then enter `echo` and press the up arrow repeatedly, fish completes from history but skips the `echo baz` (i.e. the most recent) command. If I don't type `echo` but `cho` (or anything not matching the most recent history item from its start) the most recent history item is found correctly. 

Second, fish used to highlight the matching part in a different color, but does not do that any more.  Changing $fish_color_search_match and $fish_color_match does not work.

**Comment by faho** [comment] 2015-07-16 11:34
Is this not a duplicate of #405?

**Comment by ridiculousfish** [comment] 2015-07-16 21:53
Yes it is, nice catch.

**Closed by ridiculousfish** 2015-07-16 21:53 UTC
