### ISSUE TITLE
Issue with the commands read and cat in a script

### ISSUE THREAD

**Issue by VosaXalo** [fish-shell/fish-shell#1769] opened 2014-10-21 20:12 UTC
Hi,

I have found a "strange" issue when I use the commands **read** and **cat** together in a script. This issue is instead not present when I use the same commands in interactive mode.

If I open a terminal and I use these commands interactively:
**read;cat > testo.txt**
all is ok. I press Enter to the "read" prompt, then I can write some text, and with CTRL+D I finish the editing.

If I save the same two commands in a file, and then I run the file as a fish script, I have a problem.
I press Enter to the "read" prompt, then I can't see nothing. No characters when I use the keyboard,  CTRL+D doesn't work. Only CTRL+C can interrupt the command "cat".

**Comment by mqudsi** [comment] 2018-09-30 20:31
This is basically a duplicate of some combination of #4178 and #3805.

**Closed by mqudsi** 2018-09-30 20:31 UTC
Labels: bug
