### ISSUE TITLE
abbr fails to update universal variables, not retaining new abbreviations between shells

### ISSUE THREAD

**Issue by mzagaja** [fish-shell/fish-shell#9623] opened 2023-02-28 15:54 UTC
```sh
fish, version 3.6.0
Darwin Matthews-MacBook-Pro-88.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
```
✅ `sh -c 'env HOME=$(mktemp -d) fish'`

I am trying to create a fish abbreviation in fish 3.6.0 and it is not being saved as a universal variable.

```sh
abbr -a dce docker compose exec
```
Works fine in my existing shell session.

As soon as I switch to a new shell session, it's not available.

`abbr` does not appear to be updating `~/.config/fish/variables` as evidenced by:

```sh
╰─ abbr -U -a dce docker compose exec
╰─ cat ~/.config/fish/fish_variables | grep abbr
SETUVAR _fish_abbr_awm:aws\x20\x2d\x2dendpoint\x2durl\x20http\x3a//localhost\x3a9010\x20\x2d\x2dprofile\x20minio
SETUVAR _fish_abbr_be:bundle\x20exec
SETUVAR _fish_abbr_cdr:cd\x20\x28git\x20rev\x2dparse\x20\x2d\x2dshow\x2dtoplevel\x29
SETUVAR _fish_abbr_dcc:docker\x20compose\x20run\x20\x2d\x2drm\x20consus
SETUVAR _fish_abbr_srvprod:cat\x20config/deploy/production\x2erb
```

**Comment by faho** [comment] 2023-02-28 16:25
Duplicate of #9523

**Comment by faho** [comment] 2023-02-28 16:25
Please see the [CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst#deprecations-and-removed-features-1):

    Abbreviations are no longer stored in universal variables. Existing universal abbreviations are still imported, but new abbreviations should be added to config.fish.

**Closed by faho** 2023-02-28 16:25 UTC

**Comment by mzagaja** [comment] 2023-02-28 19:26
@faho Thanks for the redirect here. I did not notice this in the changelog.
