### ISSUE TITLE
"PuTTY X11 proxy"

### ISSUE THREAD

**Issue by paul-alkhimov** [fish-shell/fish-shell#3147] opened 2016-06-15 16:19 UTC
### Reproduction Steps:

1. I am connecting via SSH using PuTTY to the headless Ubuntu (3.13.0-86-generic) without X server.
2. Everything works fine unless I use Ctrl-K or Alt-Backspace. In that case the terminal hangs for two seconds and spits the following (overwriting starting from the cursor position):  

```
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
xsel: Can't open display: (null)
```

In case I use bash, everything is fine, thus I assume that PuTTY is not to blame.

---
Fish version: 2.0.0

Operating system: Ubuntu.

Terminal or terminal emulator: PuTTy

**Comment by faho** [comment] 2016-06-15 18:16
>Fish version: 2.0.0

You'll want to upgrade to 2.3.0.

>xsel: Can't open display: (null)

This looks like it tries to add something to the X11 clipboard - functionality which we have removed now in favor of functions to explicitly copy.

My guess is that fish 2.0.0 doesn't handle this situation correctly, but since so much has changed since then, I'm going to close this for now. If you can reproduce with fish 2.3.0, please say so.

**Closed by faho** 2016-06-15 18:16 UTC

**Comment by paul-alkhimov** [comment] 2016-06-15 20:52
I installed 2.2.0 (the version which comes was delivered by apt-get). This problem is gone.
