### ISSUE TITLE
fish_vi_cursor stuck on block when entering insert mode

### ISSUE THREAD

**Issue by resign** [fish-shell/fish-shell#6848] opened 2020-04-01 12:15 UTC
```shell
$ fish -v
fish, version 3.1.0
$ echo $TERM
st-256color
$ uname -a
Linux life 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
```

I am using `fish_vi_key_bindings` and `fish_vi_cursor`. I have set my cursors as follows:
```fish
set -g fish_cursor_insert line
set -g fish_cursor_default block
set -g fish_cursor_visual underscore
```
When I enter a terminal the cursor is a line as it should. If I hit escape to exit insert mode my cursor becomes a block as expected. But if I re-enter insert mode my cursor stays as a block and does not become a line as it should.

**Comment by faho** [comment] 2020-04-01 14:37
Duplicate of #6653

**Closed by faho** 2020-04-01 14:37 UTC
