### ISSUE TITLE
Expansion of command substitution during completion

### ISSUE THREAD

**Issue by numist** [fish-shell/fish-shell#2323] opened 2015-08-20 18:37 UTC
I have a few scripts in `~/bin` that print paths. A simplified example would be `derived_data` that prints `~/Library/Developer/Xcode/DerivedData/`.

Armed with this script, I often find myself at the shell typing:

```
$ rm -rf (derived_data)/ProjNa⇥
```

and expecting tab completion to work.

I understand that not all subshell executions can be expected to be pure (though they ought to be!), but way back when I was a bash user I had the shell configured to work around this by replacing the subshell invocation with its output in the command line when I attempted completion that required its value.

**Comment by faho** [comment] 2015-08-20 19:17
The best I can come up with is something like

```fish
function eval_and_complete
	set -l cmd (commandline -ct)
	set -l out (eval echo $cmd)
	commandline -tr "$out"
	commandline -f complete
end
```

Bind that to a key and it will `eval` the current token (I'm sure I don't have to tell you that command could do harm) and then complete it. Unfortunately it doesn't cycle through the menu.

**Comment by GReagle** [comment] 2015-09-24 18:44
By the way, fish doesn't do subshells.  You are referring to command substitution.

These don't directly do what you want, but here are some work-around ideas that might work, or might be crap ...

    rm -rf ~/L<tab>/D<tab>/X<tab>/D<tab>/ProjNa<tab>
or

    ln -s ~/Library/Developer/Xcode/DerivedData ~/derived_data
    rm -rf ~/derived_data/ProjNa<tab>

**Comment by faho** [comment] 2015-09-24 18:58
Ummmh.... I just noticed something.

>I have a few scripts in ~/bin that print paths.

@numist: Why functions? Why not variables? Those complete properly, and completing command substitutions by their very nature requires executing these commands, which... isn't great.

**Comment by numist** [comment] 2015-09-30 04:12
Variables aren't really appropriate because the values produced by the functions aren't constant—or even necessarily pure.

For example, a script called `build_dir`, which understands a number of different kinds of projects, that prints the deliverables directory based on the `PWD` and the configuration of the project at that location.

**Comment by zanchey** [comment] 2015-11-18 07:11
I think this would be useful, but I don't think we can turn on expansion of command substitutions in completion across the board, as they may have side effects that are only wanted once. One possibility could a flag to `function` like `--always-expand`, although that would interact poorly with the autoloading machinery at present.

**Comment by krader1961** [comment] 2017-03-18 00:22
Note that having the completion logic expand subcommands means it would be run at least twice: first when pressing [tab] then again when the statement is run. I'm unconvinced this is useful enough to warrant the added complexity. Not to mention the dangers already discussed in doing this. I think it would be better to use a combination of `function --on-variable PWD` type functions to dynamically update global variables which can then be used in the statement.

**Comment by krader1961** [comment] 2017-07-05 04:03
Closing as a duplicate of #751. We can't safely auto-expand subcommands. But we can provide an easy way for the user to explicitly ask that they be expanded. That's what solving issue #751 allows.

**Closed by krader1961** 2017-07-05 04:03 UTC
Labels: enhancement, RFC
