### ISSUE TITLE
Tab completion with normalized filename (HFS+)

### ISSUE THREAD

**Issue by Arbitrageur** [fish-shell/fish-shell#1473] opened 2014-05-21 14:25 UTC
I know there were some issues with tab completion of Chinese filenames. 
But this is somewhat different.

Assuming there is a file, '가나다'.

```
> ls
가나다
```

When I tried tab completion, it failed.

```
> ls 가<tab>
```

Still, I can do 'ls 가나다'

```
> ls 가나다
가나다
```

My system is Mac OS X Mavericks 10.9.3 and fish 2.1.0, installed from homebrew.

```
> uname -a 
Darwin Yeolhyuns-MacBook-Pro.local 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64
> fish --version
fish, version 2.1.0
```

**Comment by faho** [comment] 2017-01-07 16:23
Closing as duplicate of #474.

**Closed by faho** 2017-01-07 16:23 UTC
Labels: duplicate
