### ISSUE TITLE
Publish static builds?

### ISSUE THREAD

**Issue by coolaj86** [fish-shell/fish-shell#7347] opened 2020-09-24 17:39 UTC
Would you be willing to publish static, standalone builds for Linux, like you do for Mac?

I'm the one of the core devs on https://webinstall.dev/ and we're putting up common installers for tools that we use and share with others based on a few core values:
- 1st party builds, straight from the official release API
- no `sudo`
- no dependencies
- ~2.5k installers rather than ~400mb package managers (looking at you, brew)

I was able to hack together an [installer for Mac](https://github.com/webinstall/webi-installers/blob/master/fish/install.sh) as the `.app` unpacks nicely and has a statically-built `usr/local` structure inside that works perfectly when run from `~/.local/opt/fish` and put in the `PATH`.

I'm hoping to be able to do the same thing for Linux, but I don't see anything I can use as a static build in the [releases](https://github.com/fish-shell/fish-shell/releases).

Also, I thought I had opened a similar issue a while back (before I found out there was a static build inside the `.app` for Mac) but I couldn't find it again in the search - so sorry if I did.

**Comment by faho** [comment] 2020-09-24 17:43
The plan is to publish an appimage.

See #6475.

**Comment by faho** [comment] 2020-09-24 17:43
Duplicate of #6475

**Closed by faho** 2020-09-24 17:43 UTC

**Comment by zanchey** [comment] 2020-09-25 12:45
And #7190!
