### ISSUE TITLE
Fish tab-completion doesn't find matches in the middle of a string when using variables.

### ISSUE THREAD

**Issue by AaronBPaden** [fish-shell/fish-shell#8674] opened 2022-01-28 23:30 UTC
fish, version 3.3.1
OS: Arch Linux

Sorry for the imprecise language, not sure what the feature is called. But for example, if you have a directory $one/two-three you can type

```
$ cd $one
cd three<tab>
```
that will expand to two-three. But this won't work:

```
$ cd $one/three<tab>
```

This is a minor issue but I run into it pretty often. For example, you may have a root directory with many subdirectories containing the same long prefix — like the name of a larger project — that you would rather skip typing out.

This may be the same as #4205 under the hood, but I wasn't sure.

**Comment by faho** [comment] 2022-01-29 07:19
Duplicate of #4205

**Closed by faho** 2022-01-29 07:19 UTC
