### ISSUE TITLE
make a function return when pipe is broken

### ISSUE THREAD

**Issue by guillonb** [fish-shell/fish-shell#7513] opened 2020-11-27 09:41 UTC
I have a function with infinite output. When piping it to a command expecting a finite number of lines only (say 1), the process never stops. Here is a minimal example:
```fish
$ function myyes; yes; end
$ myyes | read
```

The BASH equivalent works perfectly fine:
```bash
$ function myyes { yes; }
$ myyes | { read line; echo $line; }
```

How can I have my function to stop when the pipe is broken? I unsuccessfully tried things such as `trap return SIGPIPE`…

My setting:
```fish
$ fish --version
fish, version 3.1.2
$ echo $version
3.1.2
$ uname -a
Linux Gacrux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
$ echo $TERM
xterm
```

**Comment by faho** [comment] 2020-11-27 14:34
The underlying issue here is that fish buffers the output in this case (function/block to builtin), so the pipe never breaks because the `read` never runs.

**Comment by faho** [comment] 2020-11-27 14:34
Duplicate of #1396

**Closed by faho** 2020-11-27 14:34 UTC

**Comment by zanchey** [comment] 2020-11-29 12:02
I don't even think there's a good workaround here; `myyes | head -n 1 | read` doesn't work either.
