### ISSUE TITLE
Kill Syntax Highlighting

### ISSUE THREAD

**Issue by dark-yux** [fish-shell/fish-shell#2072] opened 2015-05-19 07:14 UTC
Please allow option to kill syntax highlighting.

**Comment by ridiculousfish** [comment] 2015-05-19 07:18
Can I ask why? Do you simply not like syntax highlighting, or are you worried about the performance impact, or is there another reason?

**Comment by dark-yux** [comment] 2015-05-19 07:31
I personally don't like the syntax highlighting because of the web interface i have to use to change the color which is broken in the current fish in the default Ubuntu Repositories. Using it in a previously unbroken version i didn't like it. I wanted the terminal's color settings system to handle it so I could have a simple white on black terminal, without changing the color of applications that set it's own terminal safe colors, but fish sets it's own colors! Leaving me with the option of setting all of these variables to one color, when instead all I would have to do is turn off the syntax highlighting. Therefore one color.

**Comment by Lucretiel** [comment] 2015-06-04 22:07
You don't have to use the web interface; that's just a convenience. It's all actually just set in a bunch of fish variables, documented here http://fishshell.com/docs/current/index.html#variables-color.

I'm curious why you want to turn them off? The syntax highlighting is easily one of the best features over other shells in interactive use.

**Comment by zanchey** [comment] 2015-06-26 08:51
You can lie to fish and tell it your terminal does not support colors by setting your terminal emulator variable (TERM) to `xterm-mono` or similar, if that's supported on your system.

**Comment by yegortimoshenko** [comment] 2015-10-29 23:55
I use this configuration to turn off most of syntax highlighting (except red color for errors):

```
# Turn off syntax highlighting
for color in fish_color_command fish_color_comment fish_color_end \
             fish_color_escape fish_color_match fish_color_operator \
	     fish_color_param fish_color_search_match fish_color_quote \
	     fish_pager_color_description fish_pager_color_prefix
	set $color normal
end

set fish_color_autosuggestion white
set fish_color_error red

set fish_pager_color_progress white
```

By the way, it would be cool if there was an option to achieve this in a less verbose way.

**Comment by Lucretiel** [comment] 2015-10-30 04:45
Here's an easy way to set every fish color to normal:

```fish
for color in (set | grep -Eio 'fish_color_[a-z0-9_]+')
    # optional: save the color to be restored later
    #set -g old_$color $$color
    set $color normal
end
```

**Comment by faho** [comment] 2017-01-07 16:29
Duplicate of #2001.

**Closed by faho** 2017-01-07 16:29 UTC
