### ISSUE TITLE
Perl completion file error

### ISSUE THREAD

**Issue by Frankie013** [fish-shell/fish-shell#3917] opened 2017-03-26 17:11 UTC
Fish version: 2.5.0
OS: Debian Stable, tried on FreeBSD also.

When typing 'perl (flags)' into terminal, an error is pushed before pushing enter to submit the command.
Completion file for Perl program produces error:
```
~ ❯❯❯ perl -v $, is not a valid variable in fish.
/usr/share/fish/completions/perl.fish (line 5):                         | sed -e 's,/,::,g; s,\.pm$,,' | sort -u)"
                                                                                                 ^
from sourcing file /usr/share/fish/completions/perl.fish
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “/usr/share/fish/completions/perl.fish”
```

I know nothing of how to sort it or what the issue is, completely new when it comes to these things I'm afraid.

**Comment by faho** [comment] 2017-03-26 17:39
This is a duplicate of #3856, which is, you'll be happy to know, already fixed and will be in the next release.

**Closed by faho** 2017-03-26 17:39 UTC
