### ISSUE TITLE
linker command failed

### ISSUE THREAD

**Issue by h0d** [fish-shell/fish-shell#4550] opened 2017-11-26 14:09 UTC
I'm on macOS Sierra 10.12.6, using iTerm2 3.1.5b2.

```
$ fish --version
fish, version 2.7.0
$ echo $version
2.7.0
$ uname -a
Darwin me@computer 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
$ echo $TERM
xterm-256color
```

I tried to disable third-party customizations, it did not change anything.

When compiling a program with SDL2 (i.e. `sdl2-config --cflags --libs`) within fish it will fail, showing an error from `ld`:
```
# ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1
```

On bash everything works as expected.

**Comment by zanchey** [comment] 2017-11-26 15:22
This is a duplicate of #982, which we haven't come up with a great solution for (or added to the FAQ).

The easiest is adding `| string split " "` to the `sdl2-config` invocation, like this:

```
sdl2-config --cflags --libs | string split " "
```

I'll close this as a duplicate for now, but if that workaround doesn't help then please let us know.

**Closed** 2017-11-26 15:22 UTC
Labels: duplicate
