### ISSUE TITLE
Read in startup script not working

### ISSUE THREAD

**Issue by IsaacOscar** [fish-shell/fish-shell#4787] opened 2018-03-07 06:13 UTC
I am trying to create a fish script that asks for a prompt whenever a user logs in (they may be using multiple shells, including fish).
Initially I made my script (`/script.fish`) look like this:

```
#!/usr/bin/fish
echo -n "Type something: "
read -p '' val
echo "You typed: $val"
```

I added `/script.fish` to the first line of `/etc/profile`, and `if status --is-login; /script.fish; end` to `/etc/fish/config.fish`.

I tested it by logging in via ssh, and typing `hello` followed by enter, here are my results:
* With my login shell set to bash:
    ```
    Type something: hello

    ```
    At which point I can't escape this prompt (not even with `^C`, `^D` or `^z`, and pressing enter just makes new lines), so I had to run `pkill -9 fish`.
* With my login shell set to fish:
    ```
    Type something: Welcome to fish, the friendly interactive shell
    isaacg@chipmunk ~> hello
    The program 'hello' can be found in the following packages:
     * hello
     * hello-traditional
    Ask your administrator to install one of them
    isaacg@chipmunk ~>
    ``` 
    It seems to be spawning a new shell, as I had to type exit twice to close my ssh connection.

So naturally, I tried a workarround, by changing the `read` line above to:
```
set val (head -1 /dev/stdin)
```

And it works! But only on bash :(
* Bash: 
    ```
    Type something: hello
    You typed: hello
    000:[~]$
    ```
* Fish:
    On fish, this produces the prompt
    ```
    Type something:
    ```
    Nothing I type shows up on the prompt, pressing '^c' however get's me into a fish shell (unlike before, it is not nested inside another one).

System Details:
* Fish Version: 2.7.1
* OS: Ubuntu 16.04.2 LTS
* Uname: `Linux chipmunk 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Terminal: Putty & Konsole (both claiming to be `xterm-256color`)

I'm not using any customised fish startup files (my `~/.config/fish/config.fish` file was blank).

**Comment by faho** [comment] 2018-03-07 14:42
This looks to me like a duplicate of #3805, which is fixed in git master (and will be part of the next release).

**Closed by faho** 2018-03-07 14:42 UTC
