### ISSUE TITLE
`argparse b/arg` will still accept `-a`

### ISSUE THREAD

**Issue by giorgiga** [fish-shell/fish-shell#10802] opened 2024-10-20 14:30 UTC
From the [argparse documentation](https://fishshell.com/docs/3.7/cmds/argparse) it would seem otherwise but the initial letters of the long form of arguments seem to be always accepted and considered equivalent to the full long form.

Consider the following (using fish 3.7.1):

```fish
❱ fish -c 'argparse long -- -l ; echo $_flag_long' # note it's only "long" and not "l/long"
--long
❱ fish -c 'argparse long -- --l ; echo $_flag_long' # note the double dash --l instead of -l
--long
❱ fish -c 'argparse o/long -- -l ; echo $_flag_long' # the short form is -o, -l still accepted
--long
❱ fish -c 'argparse long -- -lo ; echo $_flag_long' # note the single dash, I would expect this to be two short arguments (ie. same as -l -o) not a shortened long one
--long
❱ fish -c 'argparse long -- -lon ; echo $_flag_long' # same with 3 letters
--long
```

The value of the variables (not that anyone checks it, probably) is also surprising:

```fish
❱ fish -c 'argparse o/long -- -o ; echo $_flag_o' # expected
-o
❱ fish -c 'argparse o/long -- -l ; echo $_flag_o' # surprising!
--long
```

The options seem to be accepted only as long as there is no ambiguity (in a sense), but the overall behavior is IMHO still very complicated and unintuitive (imagine describing it in the docs):

```fish
❱ fish -c 'argparse l/other o/long -- -lo ; echo "_flag_l: $_flag_l, _flag_o: $_flag_o"' # -lo
_flag_l: -l,  _flag_o: -o
❱ fish -c 'argparse l/other o/long -- --lo ; echo "_flag_l: $_flag_l, _flag_o: $_flag_o"' # --lo
_flag_l: ,  _flag_o: --long
❱ fish -c 'argparse l/other o/long -- -lon ; echo "_flag_l: $_flag_l,  _flag_o: $_flag_o"' # -lon
argparse: -lon: unknown option
_flag_l: ,  _flag_o: 
❱ fish -c 'argparse l/other o/long -- --lon ; echo "_flag_l: $_flag_l, _flag_o: $_flag_o"' # --lon
_flag_l: ,  _flag_o: --long
```

Is this a bug in the code or should the documentation be edited?

**Comment by henrikhorluck** [comment] 2024-10-26 21:06
Good observation! `argparse` uses the same option-parsing logic as other builtins, which all allow using unambigious prefixes, _including_ as shortopts. I do agree this is somewhat surprising, and it might be removed in the future.

Duplicate of  https://github.com/fish-shell/fish-shell/issues/7341 (also: https://github.com/fish-shell/fish-shell/issues/9421)

**Closed by henrikhorluck** 2024-10-26 21:06 UTC
