### ISSUE TITLE
fish_indent: Improve indentation of boolean conditions

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#2646] opened 2015-12-31 20:45 UTC
From #1428, we currently have:

```
> if false
       or true
       echo alpha
  end
```

One possible improvement:

```
> if false
  or true
       echo beta
  end
```

Another one, a little trickier:

```
> if false
     or true
       echo gamma
  end
```

**Comment by pickfire** [comment] 2016-01-03 06:54
What about:
```
> if false or true
      echo delta
  end
```

**Comment by derekstavis** [comment] 2016-01-03 15:18
I would prefer not breaking lines, as it looks more natural:

```fish
if false; or true
    echo yaay
end
```

But as you mentioned in other issues, `fish_indent` prevents joining lines.

**Comment by krader1961** [comment] 2016-12-06 01:55
I'm going to work on this issue over the next few days. I strongly disagree with the proposal to not break lines. You wouldn't write the following in C++ (I hope):

```
int x = 1; float y = 2.3;
```

Or this in Python:

```
print('yes'); print('no')
```

The problem with allowing `if false; or true` is that it makes more complicated expressions harder to read, not easier, and will greatly complicate line folding (another item on my TODO list). Of the various alternatives I think @ridiculousfish's second proposal is the easiest to read and most amenable to automated line folding:

```
if false
or true
    echo yes
end
```

However, that leads to potentially confusing formatting when `begin` blocks are present:

```
if false
or begin
    true
    or false
end
    echo yes
end
```

However, such constructs are very rare and should be short enough to allow easy visual matching of the `end` statements with their antecedent. If not then the code should be refactored.

**Comment by krader1961** [comment] 2016-12-07 06:05
I feel compelled to expand on my antipathy to the `if false; or true` formatting. The main problem is that `or` is not equivalent to `||` in C/C++ or the `or` keyword in Python. In fish it is itself a command. Albeit a special one. And commands should always be placed on a new line.

Would you think `if false; echo yes; end` is acceptable style? The `echo` in that sequence is fundamentally no different from the `or` (or `and`) command in fish scripts. I think much of the desire to make `if false; or true` the preferred formatting stems from a misunderstanding of the fish language and the desire to treat it like the syntax of other shell scripting languages people are familiar with.

**Comment by floam** [comment] 2016-12-07 19:02
`if false; or true` just seems like a logical way to format it and group the commands to me.

`if false; echo yes; end` is different, the builtin `echo` isn't used like `and` and `or`.

**Comment by krader1961** [comment] 2016-12-09 03:51
It "just seems like a logical way to format it" because you, and too many other fish users, insist on thinking of `; and` as identical to to the POSIX 1003.1 shells `&&` and `; or` as identical to `||`. They serve a similar purpose but are not the same thing by design.

In other scripted languages like Python you can use a semicolon as an alternative to a newline (plus the requisite whitespace in the case of Python). Nonetheless no style guide I respect says that using a semicolon to separate statements is acceptable style. Even in C/C++ where the semicolon is required no sane style guide recommends putting multiple statements on a single line.

These types of discussions boil down to "language X that I'm used to using does it differently than language Y and I want language Y to resemble language X". Where "X" in this case is bash (more generally Bourne shell descendants) and "Y" is fish. Sorry, but that is not a compelling argument.

As a grey beard who has been earning a living as a programmer since 1978 I have been proficient, even expert, in more languages (e.g., FORTRAN and COBOL) than I now claim to have even passing familiarity with. So I am accustomed to adapting my habits to new languages and the idioms appropriate for them. Something I advise people adopting fish to likewise do.

**Comment by krader1961** [comment] 2016-12-09 03:54
P.S., The only reason I haven't already merged a fix for this is that getting the correct indentation for comments in `if` and `while` constructs is tricky. Doing the right thing for the subsequence `and` and `or` statements turned out to be trivial.

**Comment by aristidesfl** [comment] 2017-05-20 14:00
Is this syntax currently supported? Since which version?

```
 if false
 or true
    echo 1
 end
```

**Comment by faho** [comment] 2017-05-20 14:31
@aristidesfl: If by "supported" you mean fish handles it like `if begin false; or true; end`, then since 2.3.0.

**Comment by aristidesfl** [comment] 2017-05-21 12:24
Since parenthesis are not used for grouping in fish, Is there a way to group logical expressions? 

For example the following condition prints `true`
```fish
if false
and false
or true
  echo 'true'
end
```

But if one would group the `or` it wouldn't print anything:
```fish
# invalid syntax
if false
and (false or true)
  echo 'true'
end
```

**Comment by faho** [comment] 2017-05-21 12:29
@aristidesfl: See my previous comment: `begin` and `end`.

```fish
if false
  and begin
      false
      or true
  end
    echo true
end
```

If you have any more questions I suggest you open a new issue.

**Comment by aristidesfl** [comment] 2017-05-21 14:49
@faho but then we have the problem with the indentation which makes the code less readable. Is there any documentation on the reasoning behind the choice of using the keywords `begin` and `end` for grouping boolean conditions, instead of using some combination of braces / brackets?

**Comment by zanchey** [comment] 2017-05-22 12:26
The `begin`/`end` syntax was introduced in 2005-09-05 according to the changelog in the initial version control commit.

It is very unlikely that we would add two syntaxes to do the same thing, nor to extend one syntax to mean two things.

**Comment by faho** [comment] 2019-05-05 11:24
Okay, in 15c50703c I made it so `fish_indent` keeps semicolons on the same line for `; and` and `; or`.

So 

```fish
if false; or true
    echo yes
end
```

would stay as it is (and would also be the result of formatting `if false; or true; echo yes; end`).

It doesn't change from newline-style to semicolon-style, it just allows both if it finds them.

**Comment by faho** [comment] 2023-05-11 11:45
Okay we now have a style we can live with, so I don't think this needs to stay open.

**Closed by faho** 2023-05-11 11:45 UTC
Labels: enhancement
