### ISSUE TITLE
`kubectl logs xxx --tail=100 -f | grep aaa` not working

### ISSUE THREAD

**Issue by thuzhf** [fish-shell/fish-shell#9107] opened 2022-08-03 13:48 UTC
```
fish --version: 3.3.1
uname -a: Linux xxx 4.18.0-147.5.1.el8_1.x86_64
echo $TERM: screen
```

How to reproduce: execute: `kubectl logs xxx --tail=100 -f | grep aaa`
In `bash`, this cmd can dynamically show results. But in `fish`, it just hangs.
If you remove `-f`, it works fine.

**Comment by thuzhf** [comment] 2022-08-03 13:52
I changed to use `kubectl logs xxx --tail=100 -f | /usr/bin/grep aaa`, and it works now. But why?

**Comment by faho** [comment] 2022-08-03 14:23
Duplicate of #1396

**Closed by faho** 2022-08-03 14:23 UTC

**Comment by faho** [comment] 2022-08-03 14:27
Fish, in some cases, buffers output to functions. Bash instead often forks off a separate process ("subshell").

The obvious victim of that are commands that don't end, like `tail -f` (which seems to be the inspiration for this kubectl feature). And since `grep` is a function by default in fish (to add `--color=auto`), that hits it.

We have, over time, removed this in some cases where we can tell it's not necessary and just pass the pipe through. I can't see any changes to that since 3.3.1 (which is two minor releases and about 10% of all commits ever made to fish behind), but I am unable to reproduce this with a normal `tail -f`.

However, the underlying issue, #1396, is still open because we would like to remove this restriction as much as possible, hopefully entirely.
