### ISSUE TITLE
Config not saving / persistent among sessions

### ISSUE THREAD

**Issue by dunstorm** [fish-shell/fish-shell#9660] opened 2023-03-14 15:55 UTC
```
dunstorm@code ~> fish --version
fish, version 3.6.0
```

```
dunstorm@code ~> uname -a
Darwin code 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
```

I am encountering an issue since I upgraded to fish 3.6.0 i.e. config file is not saving / persistent among session. 

```
1 session
abbr --show
abbr --erase aws
abbr --show (doesn't display aws)
```

```
2nd session
abbr --show (shows aws)
```

I did try to debug, the logs are not enough and doesn't throw any error

```
history: Loaded 8991 old items
profile-history: populate_from_file_contents: 3 ms
profile-history: load_old: 4 ms
history: Saving 1 items via appending
profile-history: save no vacuum: 1 ms
-> source /opt/homebrew/Cellar/fish/3.6.0/share/fish/functions/abbr.fish
> abbr --show
history: Saving 1 items via appending
profile-history: save no vacuum: 1 ms
> abbr --erase aws
history: Loaded 8991 old items
profile-history: populate_from_file_contents: 2 ms
profile-history: load_old: 4 ms
history: Saving 1 items via appending
profile-history: save no vacuum: 0 ms
> abbr --show
history: Saving 1 items via appending
profile-history: save no vacuum: 1 ms
> clear
history: Loaded 8991 old items
profile-history: populate_from_file_contents: 3 ms
profile-history: load_old: 5 ms
history: Saving 1 items via appending
profile-history: save no vacuum: 0 ms
> exit
```

I also tried deleting my history file but it was of no help.

**Comment by faho** [comment] 2023-03-14 16:21
Duplicate of #9523

**Comment by faho** [comment] 2023-03-14 16:21
> Please see the [CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst#deprecations-and-removed-features-1):

>> Abbreviations are no longer stored in universal variables. Existing universal abbreviations are still imported, but new abbreviations should be added to config.fish.

**Closed by faho** 2023-03-14 16:21 UTC

**Comment by dunstorm** [comment] 2023-03-14 16:58
Hello @faho 

Thanks for the reply! I missed that. So, shouldn't `fish_config` use alias instead to change universal variables? Why is it still using `abbr`? 

I was a frequent user of `fish_config` this really hurts. Is there something else that can be used to change universal variables?

**Comment by faho** [comment] 2023-03-14 17:04
The *other* things are still using universal variables, and work fine.

The one thing that doesn't work is `abbr`, which is that thing that changes e.g. "sc" to "sudo systemctl" when you're typing. We changed abbr, but forgot to remove the abbreviation tab in fish_config. That's the only thing that's no longer working.

(and no, `alias` has nothing to do with any of this)

**Comment by dunstorm** [comment] 2023-03-14 19:33
> The _other_ things are still using universal variables, and work fine.
> 
> The one thing that doesn't work is `abbr`, which is that thing that changes e.g. "sc" to "sudo systemctl" when you're typing. We changed abbr, but forgot to remove the abbreviation tab in fish_config. That's the only thing that's no longer working.
> 
> So the upcoming 3.6.1 release will have the abbreviations tab removed so you don't accidentally use it.
> 
> (and no, `alias` has nothing to do with any of this)

@faho Thanks for the follow up, I would highly suggest to remove "abbreviations" and add "aliases" in `fish_config`. It will be for someone like me who is using universal "abbreviations"/variables and editing them via `fish_config`.
