### ISSUE TITLE
Error on fish_title.fish after upgrading to fish 3.4

### ISSUE THREAD

**Issue by 0trenixjetix** [fish-shell/fish-shell#8782] opened 2022-03-13 18:14 UTC
I am using fish 3.4

The output of uname -a and $TERM
`Linux debian 5.16.0-3-amd64 #1 SMP PREEMPT Debian 5.16.11-1 (2022-02-25) x86_64 GNU/Linux`
`xterm-256color`

The error is when fish_title is sourced.
```
The 
/usr/share/fish/functions/fish_title.fish (line 7): $(...) is not supported. In fish, please use '(prompt_hostname)'.
        and set ssh "[$(prompt_hostname | string sub -l 10)]"
                      ^
from sourcing file /usr/share/fish/functions/fish_title.fish
in command substitution
source: Error while reading file '/usr/share/fish/functions/fish_title.fish
```
fish_title.fish right now is 
```
function fish_title
    # emacs' "term" is basically the only term that can't handle it.
    if not set -q INSIDE_EMACS; or string match -vq '*,term:*' -- $INSIDE_EMACS
        # If we're connected via ssh, we print the hostname.
        set -l ssh
        set -q SSH_TTY
        and set ssh "[$(prompt_hostname | string sub -l 10)]"
        # An override for the current command is passed as the first parameter.
        # This is used by `fg` to show the true process name, among others.
        if set -q argv[1]
            echo -- $ssh (string sub -l 20 -- $argv[1]) (prompt_pwd -d 1 -D 1)
        else
            # Don't print "fish" because it's redundant
            set -l command (status current-command)
            if test "$command" = fish
                set command
            end
            echo -- $ssh (string sub -l 20 -- $command) (prompt_pwd -d 1 -D 1)
        end
    end
end
```
This is me trying to reproduce the issue.
![imagen](https://user-images.githubusercontent.com/8699204/158073242-57461d90-6ca5-4b8d-b450-5acacc201434.png)

'**

**Comment by faho** [comment] 2022-03-13 18:23
Duplicate of #8778

**Comment by faho** [comment] 2022-03-13 18:24
This is your old fish picking up the new fish's function. You'll have to restart fish after upgrading.

**Closed by faho** 2022-03-13 18:23 UTC
