### ISSUE TITLE
CTRL + R alternative for fish

### ISSUE THREAD

**Issue by 0x0elliot** [fish-shell/fish-shell#9191] opened 2022-09-08 20:28 UTC
Please tell us which fish version you are using by executing the following:

  fish --version: fish, version 3.4.1

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Linux elot 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux

you know how CTRL + R leads to a reverse search in bash? acknowledging how powerful fish's "opinions" on your commands are, I would like to point out that bash's CTRL + R just provides a simple interface to reverse search at. It would be cool if could do the same.

**Comment by faho** [comment] 2022-09-08 20:32
Duplicate of #602

**Comment by faho** [comment] 2022-09-08 20:33
Fixed in the next release, see #9089.

It looks like
![ninja4](https://user-images.githubusercontent.com/5185367/189220369-a89248a6-2103-47ef-b848-76a6ea0bd1b1.gif)

**Closed by faho** 2022-09-08 20:32 UTC
