### ISSUE TITLE
Ability to read multiline content into variable

### ISSUE THREAD

**Issue by szpak** [fish-shell/fish-shell#1147] opened 2013-11-28 16:58 UTC
It would be [useful](http://thread.gmane.org/gmane.comp.shells.fish.user/4028) to be able to read multiline input into variable for further usages. For example:

```cat myfile | myscript```

where in myscript a content of the file is read and passed (for example) to 
a clipboard.

In Bash a weird construction like "input="$(< /dev/stdin)" can be used.

**Comment by alphapapa** [comment] 2015-08-27 04:00
I'm really missing something like Bash's `readarray` builtin.  I'm trying to convert a Bash script to a Fish script, but this is making it nearly impossible.  In Bash I would do something like:
```
readarray -t arrayName <<<"$(grep word file)"
```
And the result would be an array with each line from `grep` in an element.  Then I could process it like:
```
for line in "${arrayName[@]}"
do
    echo "Something: $line"
done
```
Maybe I'm missing something, but I can't find any way to emulate this in Fish, so this is a showstopper.  :(

**Comment by ridiculousfish** [comment] 2015-08-27 04:08
@alphapapa Perhaps I'm misunderstanding, but this should just work?

    set arrayName (grep word file)
    for line in $arrayName
        echo "Something: $line"
    end

**Comment by alphapapa** [comment] 2015-08-28 21:16
I'm sorry, I guess it had been a while since I tried using Fish to write a script, and I got confused.  I think what confused me was that doing something like this:
```
set arrayName (grep word file)
echo $arrayname
```
...removes all of the line breaks, making it appear that it's a single-element variable instead of an array with one line per element.

Is that intended behavior?

Thanks for your patient answer when I probably deserved a "RTM".  :)

**Comment by faho** [comment] 2015-08-29 16:40
@alphapapa: See #159 - and actually this issue as well.

**Comment by szpak** [comment] 2015-08-30 08:06
As the topic was already dragged out from the shadow I have a related question. Proposed workaround to put a multiline content from a pipe to a variable:
```
while read i; set var "$var""$i"\n; end
echo -n $var > /tmp/output
```
adds unnecessary `\n` in the situation where the was no empty line at the end on the source content. How can I easily remove only that last character (to simplify the thing it is ok to remove the last `\n` even if it was in the source content)? I cannot use `set` as all line delimiters would be lost.

**Comment by zanchey** [comment] 2015-11-18 07:42
If you can put the pipe inside a command substitution, you can disable IFS and use this to your advantage:

```fish
> set IFS ''; set var (printf 'foo\nbar\n')
> echo $var
foo
bar
> count $var
1
```

**Comment by zanchey** [comment] 2015-11-18 07:48
Looking back, I don't think there's anything else to do here.

You can use read in a pipeline with the `-z` flag to disable splitting on newlines (added in 2.2.0). Alternatively you can use set with command substitutions with IFS set to `''`.

So I'm going to close this for now! If you think I've missed something, speak up.

**Closed by zanchey** 2015-11-18 07:48 UTC

**Comment by doapp-ryanp** [comment] 2016-04-12 15:06
For others that run across this, here is a concrete example of what @zanchey is talking about:

`cat ./swagger.json | read -z json`

**Comment by zanchey** [comment] 2016-04-13 03:48
You can even do `read -z json < swagger.json`!

**Comment by ElijahLynn** [comment] 2018-02-10 06:45
Leaving another example here that is very similar to https://github.com/fish-shell/fish-shell/issues/1147#issuecomment-135285483 but may not be obvious to others. It cats out the file into a list/array. 
                 
`set arrayName (cat /path/to/file)`

e.g.
```
function curl_codes
  set --local urls (cat $argv)
  for url in $urls
    curl --output /dev/null --silent --head --write-out "%{http_code}\n" $url
    echo " $url"
  end
end
```
