### ISSUE TITLE
Support Native Version for Windows

### ISSUE THREAD

**Issue by CoolPlayLin** [fish-shell/fish-shell#10155] opened 2023-12-16 06:19 UTC
Hey bro,
  Although it looks crazy, I still want fish shell to provide native version for windows platform instead of installing [Cygwin](https://cygwin.com/) before installing fish shell. It would bring EVEN better experiences for windows users

**Comment by zanchey** [comment] 2023-12-16 08:43
Duplicate of #4212

**Closed by zanchey** 2023-12-16 08:43 UTC

**Comment by zanchey** [comment] 2023-12-16 08:46
This gets asked for occasionally (#4212, #7488) but essentially fish requires a POSIX-compatible environment, which Windows does not provide without additional support. WSL, Cygwin and (I believe) msys2 all provide options for running fish on Windows.

**Comment by 3052** [comment] 2024-12-19 14:32
just know that you are excluding a huge base of windows users with this decision - I thought for sure with the Rust rewrite that we would have a native windows version, but nope - WSL and Cygwin are really awful in my opinion because they are essentially Linux emulators which incur a huge performance hit
