### ISSUE TITLE
Feature request: add path subcommand for string utility (`string path`)

### ISSUE THREAD

**Issue by mattmc3** [fish-shell/fish-shell#7658] opened 2021-01-25 19:25 UTC
Coming from Zsh, there are a lot of built-in helpers for dealing with path strings. Being a shell and all, this makes sense since path strings are a really common thing to interact with. The typical way to handle these in Zsh is with [variable expansion modifiers](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Modifiers)

I appreciate the simplicity and power of Fish and don't think these kind of magic modifiers are a good fit for fish, but I do think fish suffers from a lack of a great builtin path management utility. I started down the road of creating a `pathmod` plugin, and maybe that is good enough, but as I was developing it I realized the only reason for this to exist is because fish could use it as a builtin, and it would be worth asking the dev team to consider adding this functionality. Perhaps as a new `string path` subcommand of the `string` utility.

Here's how it could work. First off, the canonical Zsh examples:

```zsh
$ # Zsh path manipulation
$ somepath="./README.md" 

$ # get the absolute path
$ echo ${somepath:a}
/Users/mattmc3/code/fish-shell/fish-shell/README.md

$ # get the file extension
$ echo ${somepath:e}
md

$ # get the file name
$ echo ${somepath:t}
README.md

$ # get the file directory
$ echo ${somepath:a:h}
/Users/mattmc3/code/fish-shell/fish-shell

$ # get the file root name
$ echo ${somepath:a:r}
/Users/mattmc3/code/fish-shell/fish-shell/README

$ # chaining works to go up directories
$ echo ${somepath:a:h:h:h}
/Users/mattmc3/code

$ # chaining also works to strip a double extension
$ somepath="./README.md.bak"
$ echo ${somepath:a:r:r}
/Users/mattmc3/code/fish-shell/fish-shell/README
```

In fish currently, it can cumbersome to do some of these simple path string manipulations:

```fish
$ # Fish path manipulation
$ set somepath "./README.md" 

$ # get the absolute path
$ realpath $somepath
/Users/mattmc3/code/fish-shell/fish-shell/README.md

$ # get the file extension (not all paths have one, so we need to account for extension-less paths)
$ echo (string split "." --max 1 --right $somepath)[-1]
md

$ # get the file name
$ basename $somepath
README.md

$ # get the file directory
$ dirname (realpath $somepath)
/Users/mattmc3/code/fish-shell/fish-shell

$ # get the file root name
$ echo (string split "." --max 1 --right $somepath)[1]
/Users/mattmc3/code/fish-shell/fish-shell/README

$ # chaining sub shells is required to go up directories
$ dirname (dirname (dirname (realpath $somepath)))
/Users/mattmc3/code

$ # striping double extensions in fish can be tricky because of dots in directory names
$ set somepath "/Users/mattmc3/.config/fish/README.md.bak"
$ string replace -r '(\.[^\.]*){2}$' '' $somepath
/Users/mattmc3/code/fish-shell/fish-shell/README
```

And here is the same code with a proposed `string path` subcommand:

```fish
$ set somepath "./README.md" 

$ # -a/--absolute for realpath
$ string path --absolute $somepath
/Users/mattmc3/code/fish-shell/fish-shell/README.md

$ # -e/--extension to get the file extension
$ string path --extension $somepath
md

$ # -n/--name to get the file/directory name
$ string path --name $somepath
README.md

$ # -p/--parent get the file parent directory
$ string path --absolute --parent $somepath
/Users/mattmc3/code/fish-shell/fish-shell

$ # -r/--rootname to get the file root name
$ string path --absolute --rootname $somepath
/Users/mattmc3/code/fish-shell/fish-shell/README

$ # strip double extensions
$ set somepath "/Users/mattmc3/.config/fish/README.md.bak"
$ string path --absolute --rootname=2 $somepath
/Users/mattmc3/code/fish-shell/fish-shell/README

$ # move up a few directories
$ string path --parent=3 $somepath
/Users/mattmc3/code
```

I'm not tied to this specific implementation, it just seems to be one that fits well with the fish way of doing things. Thanks for considering adding more robust support for path string manipulation to fish.

**Comment by mattmc3** [comment] 2021-01-25 21:04
Hey @faho ! Thanks for the thoughtful reply. Let me see if I can address some of your points:

> I don't think going from "zsh has this" helps.
> I think this needs some more thought on what you want to achieve

I hesitated to even mention Zsh because I worried this would be the interpretation of my request. I want to make it clear that this isn't a "Zsh has this, why not fish?" thing. This feature request has its genesis in one simple idea:

_Working with path strings is a core concept in a shell, and fish lacks a single unified abstraction for dealing with them well._

My purpose in citing Zsh was only to show one example implementation of a unified abstraction for working with path strings.

Sure, fish has a way to do all this stuff with separate utilities, but it feels disjointed.

>   string path --absolute $somepath
> is any better than
>   realpath $somepath

You make a good point here - this would definitely be redundant, other than the fact that you could _unify_ dealing with path strings in one utility with this proposal. But `realpath` is fine and it works and wouldn't need to go away. It's just that we have 4 utilities for dealing with paths (basedir, dirname, realpath, string) and that feels really messy and like a missed opportunity to unify path string handling into one valuable abstraction.

> so the worst is realpath (dirname $somepath)/..

I agree that the worst thing when dealing with paths is bouncing to parent directories. And the `realpath` utility has a couple core issues. The first is that it assumes you want to resolve symlinks when maybe you don't. The second, and more problematic, is that you can't work with paths as simply strings. They have to be existing files. See this example:

```
$ cd ~/.config/fish/functions
$ set missingfile ./fake.fish
$ realpath $missingfile
/Users/mattmc3/.config/fish/functions/fake.fish
$ realpath $missingfile/../conf.d
builtin realpath: fake.fish/../conf.d: No such file or directory
```

> or an entirely separate command - files is surprisingly available going by Arch's repos

I'm unfamiliar with this, but it seems like that would be helpful. Got a link that I could read up on?

If I'm honest, we could probably get 80% of the utility I'm after with a few tweaks to realpath. We'd not get a unified path utility, but it'd be one step closer to making working with path strings less clunky.

**Comment by faho** [comment] 2021-01-25 21:23
>I'm unfamiliar with this, but it seems like that would be helpful. Got a link that I could read up on?

What I meant was that the name `files` is *not* taken - we could make a builtin called `files` instead of repurposing `string`, without (from a super quick check) stepping on anyone's toes.

**Comment by zanchey** [comment] 2021-02-07 13:46
https://packages.debian.org/search?searchon=contents&keywords=bin%2Ffiles&mode=path&suite=unstable&arch=any shows only an internal Phabricator command, which is not likely to be on anyone's `PATH`.

**Comment by mqudsi** [comment] 2021-02-07 16:40
I imagine it depends on what the other subcommands are. If it's strictly to do with the names/paths to files, then probably something `path`-related is better than something `file`-related. But if it involves opening files at some point, then the latter makes more sense?

**Comment by mattmc3** [comment] 2021-02-07 16:50
What about a `paths` command? Obviously `path` (singular) is a non-starter. Or `filepath`?

Also, the naming feels a little like bikeshedding at the moment since I’m not sure there’s agreement yet that this is a feature Fish needs (obviously I think so, but that’s not clearly decided).

**Comment by IlanCosman** [comment] 2021-02-07 21:08
Personally, I'd love for `basename` and `dirname` to be integrated into fish, perhaps as flags to a `files` or `paths` command. They are super useful, and without them we end up doing it clunkily through `string`:

https://github.com/fish-shell/fish-shell/blob/943cf03d8ec93de8879b81cfde83cc70f0586f53/share/config.fish#L246

`dirname` is way harder to do through `string`.

**Comment by faho** [comment] 2021-08-29 11:03
Okay, I've played around with writing a builtin called `path`.

Currently, it has the following subcommands:

- `base` and `dir` to do "basename" and "dirname" on all the given paths
- `extension` to give the extension for a given file. It correctly handles paths like "~/.config/fish/conf.d/foo" (no extension) and `~/.config` (no extension). A command to remove the extension would be simple enough, I'm just not sure what it should be called.
- `path normalize` to do the rote string-transformation stuff to normalize a path - collapse successive `//` into one `/` and such, and `path real` to do actual `realpath`, resolving symlinks and everything. These are the same as `builtin realpath --no-symlinks` and `builtin realpath`, respectively.

and the most complicated:

- `path match` to run globs via `glob(3)`. This includes `[0-9]` ranges and `?` single character wildcards.

And one I plan to add:

- `path filter` to only pass through the paths that pass certain conditions, like type (file, symlink, directory?) or permission (executable, readable, writable), possibly size, owner, c/m/atime? These filters might also be accessible to `path match` directly, but `path filter` would not run the glob.

So, to find just the basenames of files called `fish0` to `fish9` in `/tmp/`, you could do

```fish
path base -- (path filter --type=file -- (path match '/tmp/fish[0-9]'))
```

(note: These are all explicitly split, so newlines in filenames are indeed handled as long as you use command substitutions)

**Comment by krobelus** [comment] 2021-08-29 12:50
Sounds reasonable. The `filter` option being available to other subcommands makes it more concise, which is good. Maybe even `path --filter=file match '*'`.

> path match to run globs via glob(3). This includes [0-9] ranges and ?

Hmm that's pretty similar to fish's standard globbing. Maybe we should break our convention and make this one do regex matching by default.

**Comment by faho** [comment] 2021-08-29 12:52
>Maybe we should break our convention and make this one do regex matching by default.

Unfortunately, `glob(3)` doesn't do regex matching.

So any regex-matching we would have to do ourselves, and doing that in a performant manner is a bunch of work. Plus `string` does globs by default (well, fish's simple `*` globs).

**Comment by zanchey** [comment] 2021-08-29 13:18
`glob(3)` is in POSIX, so it's at least theoretically portable. (For a wild ride, see [`wordexp(3)`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/wordexp.html).)

**Comment by faho** [comment] 2021-08-29 19:27
Oh, right, annoying issue I forgot: `glob(3)` doesn't do `**` recursive globs either.

At the moment I have `path match` error out with an unescaped `**`.

**Comment by faho** [comment] 2021-08-30 19:15
Hehe:


```fish
> path match '*' -Z | path filter -z --perm=exec --type=file -Z | path real -z
/home/alfa/ownCloud/dev/fish-shell/build/fish
/home/alfa/ownCloud/dev/fish-shell/build/fish_indent
/home/alfa/ownCloud/dev/fish-shell/build/fish_key_reader
/home/alfa/ownCloud/dev/fish-shell/build/fish_test_helper
/home/alfa/ownCloud/dev/fish-shell/build/fish_tests
/home/alfa/ownCloud/dev/fish-shell/build/littlecheck.py
```

This isn't just theory:

![Screenshot_20210830_211238](https://user-images.githubusercontent.com/5185367/131392383-d38ad80f-247f-4586-98b9-dce65e8c8048.png)


(`-z` here is "--null-in", i.e. stdin is null-separated, `-Z` is "--null-out", i.e. output should be printed null-separated. all of this can also be done in command substitutions and is explicitly split, the `filter` here could also be done as options to `match`, but `filter` is useful regardless because it means you don't re-match globs)

**Comment by mattmc3** [comment] 2021-08-30 19:40
@faho

This is awesome! Well done. I'm super excited for this functionality.

> A command to remove the extension would be simple enough, I'm just not sure what it should be called.

As a Pythonista, I may be biased, but might I suggest borrowing some of its nomenclature and using ["stem"]((https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem) for removing an extension?

**Comment by faho** [comment] 2021-08-30 19:45
>As a Pythonista, I may be biased, but might I suggest borrowing some of its nomenclature and using "stem" for removing an extension?

I have literally never heard the term "stem" for this, and I'd rather not restrict it to the final path component.
I.e. performing this operation on a path like "./pictures/my_dog.jpg" should give you "./pictures/my_dog". If you want to remove the rest of the path, you can pass that to "basename" to turn it into "my_dog". That composes a lot better than also removing everything but the final component in this operation.

In lieu of a common term (and I think "root" is too confusing here), I'd rather do something overly long but crystal clear like "strip-extension", or possibly `path extension --strip` (because it's basically the inverse of `path extension`).

**Comment by mattmc3** [comment] 2021-08-30 19:48
Valid point. Could we add an optional number to strip like `path extension --strip 2` so that `myfile.tar.gz` becomes `myfile`?

**Comment by faho** [comment] 2021-08-30 19:58
Pass it to it twice - `path extension --strip -z | path extension --strip -Z`. I do not believe this is a common enough thing, and it's also not really unambiguous?

E.g. if you had the game F.E.A.R installed, you might conceivably have a "F.E.A.R.exe". Is "R.exe" really a double extension?

**Comment by mattmc3** [comment] 2021-08-30 20:05
You can do that - it just gets tedious to strip via piping when you have files like `myfile.log.20210830.tar.gz.bak`.

**Comment by faho** [comment] 2021-08-30 20:14
See, the problem there is *how many layers do you want stripped*?

If you know that filename, and you know it's gonna be "tar.gz.bak", you can run `path extension --strip` multiple times, or maybe `string replace`. But if you don't, how are you gonna explain where the extensions end?

If one of the files was "myfile.log.20210930.tar.gz" (not a backup) or "myfile.log.20211030.gz.bak" (only one file, so tarring was skipped), if you run a hypothetical `path extension --strip=3` it'll end with "myfile.log" in both, and that's now gibberish.

So I'm really struggling to figure out where this is useful.

**Comment by faho** [comment] 2021-08-30 20:18
Maybe more of a "strip *this* extension" option? Instead of telling it to strip three layers, tell it to strip ".tar.gz.bak"? (or any of them)? Similar to GNU basename's `--suffix` option.

**Comment by mattmc3** [comment] 2022-04-05 20:17
Over a year has gone by on this, but I wanted to share my (heavily Zsh biased) version of an extended path utility: https://github.com/mattmc3/pathx.fish

Still waiting on this to get integrated into Fish.

**Comment by faho** [comment] 2022-04-06 08:07
@mattmc3 I'm assuming you have missed #8265, which I feel has a nicer interface and a bunch more bells and whistles.

**Comment by mattmc3** [comment] 2022-04-06 13:23
@faho - I actually didn't miss #8265 and have been really excited to see it get out the door. It's a really great implementation and I support it fully! I've just been asked a bunch about this one and I keep telling folks to hold off, the `path` utility is coming. But when it wasn't included in 3.4 I decided to polish up and publish what I've been using for years as a stop-gap. I can appreciate that including this within Fish itself will require more rigor to ensure that we don't paint ourselves into a corner with an implementation that isn't broadly usable.

Is there anything else you need from the community to help get this one fully baked, or at least scheduled for a specific release rather than just marked ambiguously as *fish-future*?

**Comment by faho** [comment] 2022-04-06 19:18
>Is there anything else you need from the community to help get this one fully baked

The main thing we need is *use cases*. What issues do you currently face with paths, and how could we make that easier?

Note this isn't the same as simply asking for features from zsh.

E.g. one of the things this can currently support is "find the command from $PATH":

```fish
set -l cmd (path filter -fx $PATH/$commandname)[1]
```

which is a common pattern (it happens for commands, function files, config files, ...).

Or "get just the files, not the directories in $PWD":

```fish
path filter -f *
```

(just the dirs is "*/")

Another is "change this extension to .mp4":

```fish
path change-extension .mp4 $massive_list_of_files
```

>at least scheduled for a specific release rather than just marked ambiguously as fish-future?

No. I'm *trying* to get it into 3.5, but if that doesn't work out that doesn't work out. I would rather delay this to 3.69 than add it and it's awful.

One thing I've done to make it easier to merge is to remove all the globbing features that I added to it, because I don't think they, in their implemented form, actually helped all that much. So because they'd have to be supported in that form, I chose to remove them instead so we can add them later.

**Comment by mattmc3** [comment] 2022-04-06 21:12
One use case I do fairly often, especially when I'm writing a fish plugin, is start navigating project files from `(status filename)`, so there's a lot of `set prjdir (realpath (dirname (status filename)/../..)` kinds of things. Another common thing I do is get counts of all file extensions in a directory structure, which is an approximation for GitHub's "Languages" feature that shows what the distribution of files is within a project. A couple things that would be helpful to know:

* How does the new path utility deal with finding/manipulating/navigating extension-less files? Globbing is notoriously bad at finding/filtering these. It's only slightly better at dotfiles (ie: .vimrc), as those files can look like their name is empty and their extension is ".vimrc".
* How does the the path utility deal with `../../..` parent directory syntax?

**Comment by faho** [comment] 2022-04-07 06:24
>How does the the path utility deal with ../../.. parent directory syntax?

There are two commands that would handle this:

- `path normalize` will do this as a string operation. It will remove double `/`, `/./` components and cancel out `../` components with earlier ones. So in effect you will get the *logical* parent directory - like with `cd ..`. (there could be a flag to skip cancelling out, so you'd just get the path beautified)
- `path resolve` will basically do `realpath`. It will give you the path with symlinks resolved, so you should get something related to the *physical* path, like `cd -P ..`.


Also:

> set prjdir (realpath (dirname (status filename)/../..)

We now have a `status dirname` shorthand for the dirname of the current file.

>How does the new path utility deal with finding/manipulating/navigating extension-less files? Globbing is notoriously bad at finding/filtering these. 

Globbing or any other form of matching by name is currently not included.

> as those files can look like their name is empty and their extension is ".vimrc".

The extension-handling in `path` would tell you their name is `.vimrc` and the extension is empty. It ignores a leading dot for the purposes of determining the extension.

>nother common thing I do is get counts of all file extensions in a directory structure, which is an approximation for GitHub's "Languages" feature that shows what the distribution of files is within a project

```fish
path filter -f ** | path extension | sort | uniq -c | sort -n
```

in my fish-shell repo says something like

```
     77 .py
    102 .o
    104 .txt
    105 .cpp
    111 .h
    131 .rst
    414 .html
    458 .1
    568 .cmake
    576 .make
   3727 .fish
```

**Comment by mqudsi** [comment] 2022-04-08 20:03
I'm with faho that the ergonomics have to be nailed down exactly right before such a thing ships. My primary case is transforming paths, and it's a misleadingly difficult thing to do if you want to support all the cases - e.g. see below just to get a path to a file w/out the extension

```fish
    # I believe this is the minimal regex for extracting a filename without its extension
    # that works with pathed files (dropping the directory prefix) and with files without
    # extensions (in which case the entire name is returned).
    set basename (string replace -r '(?:^.*\/)?([^\/]+?)(?:\.[^\/.]+)?$' '$1' $path)
```

But part of the problem is that it needs to be concise enough to then be nested for interpolation, e.g. `mv $file (path dir $file)/(path fname_no_ext $file).new_ext` to rename a file to a different extension that handles cases where the file is in a subdirectory, a relative ../ directory, the same directory, an absolute path, has an extension, has no extension, etc, etc - so it's not sufficient to just provide each of the values but also to make them composable. The syntax above (unixy with separate commands each doing a single thing) is an alternative to some of the voodoo used by zsh and some GNU tools as faho illustrated in the initial post where you could achieve the same same-path-but-different-extension behavior with a single (maybe opaque and impossible-to-remember) expression, but with maybe more expressive syntax/names (say `path {:dir}/{:basename}.new_ext` $file).

If we had support for dictionaries/named associated variables/whatever we could use something like how `read` or `string match -r` can wish variables directly into existence in the current scope, e.g. `path explode path/to/file -v foo` and thereafter use `$foo[fname]`, `$foo[ext]`, `$foo[dir]`, etc which is understandable, more imperative, and easier to read, but within the scope of our current abilities I don't think creating separate variables $foo_fname, $foo_ext, $foo_dir, etc. is sufficiently equally elegant to be an option (and numbered array subscripts are absolutely not an option).

**Comment by faho** [comment] 2022-05-03 07:00
For posterity:

>    set basename (string replace -r '(?:^.*\/)?([^\/]+?)(?:\.[^\/.]+)?$' '$1' $path)

That's

```fish
set basename (path basename $path | path change-extension '')
```

as it stands right now.

>But part of the problem is that it needs to be concise enough to then be nested for interpolation, e.g. mv $file (path dir $file)/(path fname_no_ext $file).new_ext to rename a file to a different extension that handles cases where the file is in a subdirectory, a relative ../ directory, the same directory, an absolute path, has an extension, has no extension

```fish
mv $file (path change-extension .new_ext $file)
```

If $file has an extension, this will change it to ".new_ext". If it doesn't, this will add a new ".new_ext". So e.g. `path change-extension .md README text.rst` will print "README.md" and "text.md".

The definition of "extension" we use here is the part after and including the last "." of the basename, unless it's directly at the start, or the basename is "..". This sounds complicated but isn't too bad, really - it just means that a leading "." that marks a dotfile doesn't start an extension, and that the ".." file doesn't have an extension.

So I don't believe you need to get the dirname here at all.

**Closed** 2022-05-29 18:26 UTC
Labels: enhancement, RFC
