### ISSUE TITLE
command `string` inside a block fails to read stdin 

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#5457] opened 2019-01-01 05:03 UTC
> fish, version 3.0.0

It works fine when I invoke the `string` command on the command line.

> echo "something" | string escape

try:

> echo "something" | begin; string escape; end

Unfortunately it outputs nothing.

**Comment by mqudsi** [comment] 2019-01-01 06:20
Is this behavior different from 2.7.1?

**Comment by faho** [comment] 2019-01-01 11:07
Also happens in 2.7.1.

I'd assume we're checking for a "direct redirection", which, as a concept, isn't really all that useful.

**Comment by ridiculousfish** [comment] 2019-01-12 22:08
This is not a bug, it is by design. The point of the 'direct redirection' is to reliably determine when you want to read from stdin. If `string escape` were to unconditionally read from stdin, then uses like `string escape $somevar` where $somevar happens to be empty, would do the wrong thing by reading from stdin.

Closing, thanks for filing!

**Closed by ridiculousfish** 2019-01-12 22:08 UTC
Labels: bug

**Comment by mqudsi** [comment] 2019-03-01 19:41
> where $somevar happens to be empty, would do the wrong thing by reading from stdin.

Which is why we need to implement the variable overhaul discussed many times in the comments (formally filed at https://github.com/fish-shell/fish-shell/issues/4961) so this kind of inconsistency can be worked around. (I was just bit by expecting `string` in a function to read from stdin)

**Comment by imcaizheng** [comment] 2019-11-29 16:41
@ridiculousfish how about introduce a new flag like `--from-stdin` for the string command to instruct it to explicitly read from stdin rather than command line?

**Comment by imcaizheng** [comment] 2019-11-29 16:44
@ridiculousfish `echo 'hello fish' | eval string escape` does not output anything and `$status` is set to 1. Is it a desired behavior too?

**Comment by ridiculousfish** [comment] 2019-11-30 08:32
`echo 'hello fish' | eval 'string escape'` doesn't work for the same reason as above. `string` only looks at its own redirections to decide what to do, not those inherited from the environment.

IMO it's not worth introducing a new flag here. If there's a particular function which is tricky to write we can help figure out how to write it.

**Comment by imcaizheng** [comment] 2019-12-02 18:56
@ridiculousfish If you mean that the pipe symbol must be present before the string command to force it to read from stdin then there's a more elegant workaround here `echo 'hello fish' | eval 'tee | string escape'`

**Comment by ridiculousfish** [comment] 2019-12-04 18:45
Good idea! I think `cat` would be even simpler than `tee`
