### ISSUE TITLE
stty keybind commands don't work in fish

### ISSUE THREAD

**Issue by ericjs** [fish-shell/fish-shell#6222] opened 2019-10-17 20:44 UTC
If I run

`stty intr \^k`

or

`stty intr ^-`

or 

`stty intr undef`

and then run

`stty -a`

It continues to show intr = ^C; and Ctrl-C continues to work to send an interrupt signal.
In a bash shell, stty works as expected.
This is using the terminal Konsole. 

---
fish, version 3.0.0
Chakra Linux:
Linux BLACKBROOK-7510 5.2.11-3-CHAKRA #1 SMP PREEMPT Tue Sep 10 20:12:36 CEST 2019 x86_64 GNU/Linux
xterm-256color
Same behavior using   `sh -c 'env HOME=$(mktemp -d) fish'`

**Comment by ericjs** [comment] 2019-10-17 20:47
I don't know why I have the huge bold text in my description...I was able to reduce it but not eliminate it and I don't see any markup in my text to cause it...

**Comment by krobelus** [comment] 2019-10-17 20:53
Can confirm.

> I don't know why I have the huge bold text in my description...I was able to reduce it but not eliminate it and I don't see any markup in my text to cause it...

Some dashes at the beginning of a line cause the line above to be interpreted as headline I added a linebreak

**Comment by zanchey** [comment] 2019-10-18 07:51
This is a duplicate of #2315 / #1041.

**Closed by zanchey** 2019-10-18 07:51 UTC
Labels: duplicate
