### ISSUE TITLE
Pasting long text makes the terminal go completely blank.

### ISSUE THREAD

**Issue by esn89** [fish-shell/fish-shell#10567] opened 2024-06-14 00:28 UTC
```
fish, version 3.7.1
3.7.1
```

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

```
Darwin M-J6HX003X0L 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64 arm Darwin
```

```
xterm-kitty
```

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'

**Yes, I have tried this, and the problem still happens.**

Pasting a lot of of text makes nothing show up and the terminal hang.

I first discovered this while copy and pasting some certs with chains in them at work.  Obviously, I can't put this on asciinema, so I tried it with a large wall of text that I just copied from here: https://www.ocf.berkeley.edu/~jonc/

Copying from the beginning of the blog "I tend to be overly...." to the end of the blog on July 15th 2020, then pasting its contents like so:

```
echo "<HIT PASTE KEY> ....
```

 makes the terminal go blank:
https://asciinema.org/a/Jb3YJm1Qgc2WYX6B5g9VDkwAl

**Comment by faho** [comment] 2024-06-14 05:04
Duplicate of #7296

**Closed by faho** 2024-06-14 05:04 UTC

**Comment by esn89** [comment] 2024-06-14 05:09
@faho 

It's a duplicate, great.  Is it fixed?  Is there a workaround?
