### ISSUE TITLE
youtube-dl command does not work in fish shell

### ISSUE THREAD

**Issue by timthelion** [fish-shell/fish-shell#3907] opened 2017-03-23 11:33 UTC
````
timothy@yoga ~/Videos> fish -v
fish, version 2.2.0
````
````
timothy@yoga ~/Videos> youtube-dl https://www.youtube.com/watch?v=dHI22pH9CZg
No matches for wildcard “https://www.youtube.com/watch?v=dHI22pH9CZg”.
fish: youtube-dl https://www.youtube.com/watch?v=dHI22pH9CZg
                 ^
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
timothy@yoga ~/Videos> bash
timothy@yoga:~/Videos$ youtube-dl https://www.youtube.com/watch?v=dHI22pH9CZg
[youtube] dHI22pH9CZg: Downloading webpage
[youtube] dHI22pH9CZg: Downloading video info webpage
[youtube] dHI22pH9CZg: Extracting video information
[youtube] dHI22pH9CZg: Downloading js player en_US-vflTlQxIb
[youtube] dHI22pH9CZg: Downloading MPD manifest
.....................................
````

````
timothy@yoga ~/Videos> uname -a
Linux yoga 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
timothy@yoga ~/Videos> echo $TERM
xterm
````

**Comment by geoffmacintosh** [comment] 2017-03-23 14:29
If you put the URL in quotes, it should work. At least it does for me!

    youtube-dl "https://www.youtube.com/watch?v=dHI22pH9CZg"

**Comment by timthelion** [comment] 2017-03-23 15:45
AHA. Please don't close this bug report yet though. I don't think this 
is exactly "friendly" behavior ;)

**Comment by faho** [comment] 2017-03-23 15:55
This has _nothing_ to do with `youtube-dl` specifically, it's a general issue. The "?" character is a single-character glob - "https://www.youtube.com/watch?v=dHI22pH9CZg" tries to match a file named "https://www.youtube.com/watch", then one character and then "v=dHI22pH9CZg". That's also the reason why quoting it fixes the issue - globs aren't expanded in quotes.

There have been numerous changes that affect this in the time since 2.2.0 (if you would like these, you should upgrade!):

- Fish no longer executes commands if a glob fails - that means `youtube-dl` would not be launched here

- Fish now offers a binding to paste from the clipboard (and in the upcoming 2.6.0 also bracketed paste if you just paste into the terminal)

- In 2.6.0, if you enter `'` and paste (via either method), the pasted text will be escaped so you can simply close the single-quote

So short of removing the `?` glob, there's nothing more we can do here. That is something we've debated (especially since that glob seems to be completely unused), but we have to do it carefully, in a major release.

Anyway, it's always a good idea to quote anything you paste into a terminal (or to write it by hand since pasting isn't safe if you do it via the terminal and it doesn't properly support bracketed paste).

**Comment by faho** [comment] 2017-03-23 16:01
This is a duplicate of #3649.

**Closed by faho** 2017-03-23 16:01 UTC

**Comment by geoffmacintosh** [comment] 2017-03-23 16:05
I think that the [bracketed paste feature](https://github.com/fish-shell/fish-shell/pull/3871) that was recently added should make this a non-issue in the next version of fish.

**Comment by Memphizzz** [comment] 2018-04-19 15:58
Would it be possible with "bracketed paste" to have a set of regex's which define wether or not to paste the data surrounded by brackets?

**Comment by faho** [comment] 2018-04-19 16:29
>Would it be possible with "bracketed paste" to have a set of regex's which define wether or not to paste the data surrounded by brackets?

@Memphizzz: I'm afraid I don't understand. "Bracketed paste" means that _the terminal_ marks pasted data, so that the application running inside it (e.g. fish) can determine that it was pasted and not entered manually.

The "brackets" here are escape sequences - `\e[200~` opens, `\e[201~` closes. Fish gets them no matter what the pasted data looks like, as long as it has signalled that it supports BP.

**Comment by Memphizzz** [comment] 2018-04-19 16:37
I see, i thought that bracketed paste would actually add brackets on paste automatically. I came here because of the same youtube-dl problem the OP has. I would like to avoid having to type the brackets at all. I'm running fish 2.7.0 on windows using cygwin, but I can't seem to just paste a youtube url. Do I need to setup a special bind key for this to work? I currently just use shift+insert.

**Comment by faho** [comment] 2018-04-19 16:59
>Do I need to setup a special bind key for this to work?

No. It should be done automatically, but it requires terminal support.

Enter:

```fish
youtube-dl '
```

then press shift+insert. Then enter the closing `'`.

That should enter the URL without any danger of executing code (that's why bracketed paste was invented), and it should pass it through to `youtube-dl` unchanged.
