### ISSUE TITLE
SIGABRT for file completion

### ISSUE THREAD

**Issue by antoyo** [fish-shell/fish-shell#4110] opened 2017-06-08 13:29 UTC
```
$ fish --version
fish, version 2.5.0
```

I use ArchLinux and the terminal is `termite`.

```
$ uname -a
Linux hostname 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
```
```
$ echo $TERM
xterm-termite
```

When trying without customizations, I see the following error:
```
fish: src/pager.cpp :161 : line_t pager_t::completion_print_item(const wcstring&, const pager_t::comp_t*, size_t, size_t, size_t, bool, bool, page_rendering_t*) const:  l'assertion « desc_remaining >= 2 » a échoué.ta/\ E\cb\ca.pstate      …est/data/\ \Xc5X\cb.pstate        
fish: 'sh -c 'env HOME=$(mktemp -d) fi…' terminated by signal SIGABRT (Abandon)
```

** How to reproduce this issue: **

I type `rm -Rf directory/<Tab><Tab>` and this directory contains files with invalid characters.

Unrelated, but fish is also unable to do proper `*` expansion for some of these files:
running `rm -f *` in this directory didn't delete all the files while in `bash`, it did.

**Comment by zanchey** [comment] 2017-06-08 13:33
I think this is a duplicate of #3989.

**Closed** 2017-06-08 13:36 UTC
