### ISSUE TITLE
Allow interruption of completion

### ISSUE THREAD

**Issue by mdamien** [fish-shell/fish-shell#3020] opened 2016-05-10 20:03 UTC
When tabbing, it can take a long time to complete the list (apt-get, directory with lots of files,...) but fish stay stuck even when doing `Ctrl-C`.

### Reproduction Steps:

1. Type `sudo apt-get install `
2. Hit `tab`, you can't type anymore while it's loading
3. Hit `Ctrl-C`

### Expected behavior:

Completion is stopped and you're returned to the shell

### Observed behavior:

Process isn't getting interrupted.

---
Fish version: 2.2.0 
Operating system: Ubuntu 
Terminal or terminal emulator: Terminator

**Comment by zanchey** [comment] 2016-05-10 22:01
This is a duplicate of one of our oldest issues: #23! I'll close in its favour.

**Closed by zanchey** 2016-05-10 22:01 UTC
Labels: duplicate
