### ISSUE TITLE
fish doesn't understand the color white

### ISSUE THREAD

**Issue by mikez302** [fish-shell/fish-shell#3176] opened 2016-06-28 00:03 UTC
I would like the current directory in my fish prompt to be light gray, as it was in bash before I started using fish. I tried running `set -U fish_color_cwd white` (since white is the closest color to light gray that is listed in the [`set_color` documentation](https://fishshell.com/docs/current/commands.html#set_color)) and it didn't do anything. The text was green after, just like it was before.

I then tried `set -U fish_color_cwd red` to see what happened and the text turned red, like I expected. Then I tried `set -U fish_color_cwd white --bold` and it became bold, but green again. It seems like it understands all of the colors I tried, but not white.

I am using fish 2.3.0 on OS X 10.11.5 and the built-in Terminal. Here is a screenshot demonstrating what is happening:
![white not working in fish shell](https://cloud.githubusercontent.com/assets/510781/16399572/9674a980-3c88-11e6-9b11-76d5379e1450.png)

**Comment by floam** [comment] 2016-06-28 00:49
You have customize the text color in your Terminal.app profile configuration. One of the whites or text/bold text colors in here is going to show that it's been set to bright green (other than the standard ANSI green/bright green):
<img width="676" alt="screenshot 2016-06-27 at 5 47 56 pm" src="https://cloud.githubusercontent.com/assets/291142/16400370/873b142a-3c8f-11e6-83de-7827528ad955.png">

**Comment by floam** [comment] 2016-06-28 00:52
(Or, you are using Apple's "Homebrew" profile which has green for the unstyled text already)

**Comment by faho** [comment] 2016-06-28 01:02
@mikez302: To test if floam is right, try `echo (set_color white) banana`.

Also, you can pass RGB values to set_color and the color variables and fish will do the right thing (or try to).

**Comment by floam** [comment] 2016-06-28 01:15
I'm not right. Of course the "Last login" output there is not colored with ASCII escapes. He's probably using the included Homebrew profile which has both Text and Bold Text as green, like I first guessed... 😒

**Comment by krader1961** [comment] 2016-06-28 02:00
The important thing to keep in mind is that color names like "white" are simply mapped to the corresponding [ANSI X3.64 SGR sequence](https://en.wikipedia.org/wiki/ANSI_escape_code). Those sequences map each color name to a number. The terminal is free to map the number to whatever color it likes and different terminals use different default colors. However, in your case I strongly suspect that @floam is correct and you've reconfigured your terminal so that "white" appears as bright green.

On my terminal (iTerm2 with the default color palette) I get the expected result:

![image](https://cloud.githubusercontent.com/assets/7545917/16401380/e3fcf38c-3c98-11e6-9155-9128f45fbdd5.png)

**Comment by mikez302** [comment] 2016-07-02 18:26
This screenshot shows what my Terminal color settings look like:
![terminal color settings](https://cloud.githubusercontent.com/assets/510781/16541864/6bf9806a-4046-11e6-8139-c45b2edc407b.jpg)

I am using the Homebrew profile. The "Text" and "Bold Text" colors are green. Everything else looks mostly like it does in @floam's screenshot.

I tried running `echo (set_color white) banana` and saw the word `banana` in green.

What should I do about this? It seems strange to me that fish would be unable to show white or light gray text in my terminal, if bash can do it.

**Comment by floam** [comment] 2016-07-02 18:52
Is $fish_term24bit set to 1 somehow?

**Comment by floam** [comment] 2016-07-02 18:57
(Terminal.app, with a greenish color set for text, getting 24bit color thrown at it it can't handle, will be greenish when `set_color` tries to do #FFFFFF. Longshot...)

<img width="413" alt="screenshot 2016-07-02 at 11 57 14 am" src="https://cloud.githubusercontent.com/assets/291142/16542027/268765d2-404c-11e6-9b47-ddbc8a171967.png">

**Comment by krader1961** [comment] 2016-07-02 19:42
I can't reproduce with or without setting fish_term24bit. The following screen shot is after I moved my custom *fish_prompt.fish* script out of the way so that I'm using the default prompt. What does `echo $TERM` report? I'm betting it's `xterm`. Why because if I set TERM to that value I can reproduce your problem. Note that xterm only supports the first 8 named colors and `white` isn't in that set but `grey` is.

![image](https://cloud.githubusercontent.com/assets/7545917/16542146/3157bf52-4051-11e6-8d4d-95d65e6591f7.png)

**Comment by krader1961** [comment] 2016-07-02 19:43
BTW, you should configure the terminal to identify itself as `xterm-256color`.

**Comment by floam** [comment] 2016-07-02 19:48
"xterm" with Terminal.app I thought goes through the code path that gives in 256 colors anyhow.

**Comment by floam** [comment] 2016-07-02 19:56
OK, I had that backwards. Everywhere except for Apple_Terminal we do this. The comment in `input.cpp` says it is for Snow Leopard. I guess we can remove that someday (or check `TERM_PROGRAM_VERSION` - this was added in Lion.)

**Comment by floam** [comment] 2016-07-06 11:47
>  Note that xterm only supports the first 8 named colors and white isn't in that set but grey is.

If you have 8 colors, these are what they are:

 - `0 black`
 - `1 red`
 - `2 green`
 - `3 yellow`
 - `4 blue`
 - `5 magenta`
 - `6 cyan`
 - `7 white`
... and  9..16 render the same as 7 does.
with 16 colors 9..16 are bright variants of each. 16 should be `bright white`.

See https://github.com/fish-shell/fish-shell/blob/master/src/color.cpp#L226-L239

However scroll down just a bit to `static const named_color_t`. This does not agree with rgb_color_t::white().

Broken by this commit: https://github.com/fish-shell/fish-shell/commit/0a0acc8a2e0b8c2ca0c0500123d586d629f99b16

When adding bright color support you can see normal-brightness `white` is now called `grey`. We made it so that what should be called bright white and prepended with a `br` like we do the other brights is simply `white`, and instead of being color 7,  white is color 15 now. 

There are a handful of things we could have done to make this work if we were going to get cute with the color names like this:

For some reason we do not try to find the closest matching supported color for term8 or term16? And for term8 we are not willing to give them color 15 even though it will render as white. Fish doesn't appear to be taking advantage of the the RGB values we have along with each of those named colors in that struct on term256. If we wanted to we could ensure they get good colors. Instead they get the same exact thing for purple and magenta and for yellow and orange.

**Comment by krader1961** [comment] 2016-07-06 23:08
See also issue #2951. Also, it's debatable that this is a bug. It's working as documented and this is the first complaint in the seven months since that change was merged.

**Comment by floam** [comment] 2016-07-21 15:02
Actually, this is worse than what I assumed, the change didn't cause `set_color white` not to do anything. Actually, it's sending out bogus escapes:

```
env TERM=xterm fish -c 'builtin set_color white | xxd'
00000000: 1b5b 3331 356d                           .[315m
```

> this is the first complaint in the seven months since that change was merged.
We can't really use a lack of squeaky wheels as validation of what is or isn't a bug. Consider that this whole time [we've also been locking out `grey`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_config_interactive.fish#L305) for Linux VTs in this situation, while the unblocked `white` option causes the output above. That's obviously a confounding of factors that represents a bug that should cause someone some kind of issue but we haven't heard a pip.

**Comment by davinkevin** [comment] 2016-08-01 08:30
I've just updated fish and I've got the same problem...

I've switch to grey, but for me it's a regression.

**Comment by floam** [comment] 2016-08-01 08:49
Wow, sorry about those mentions above the prior comment spamming this thread. Moral of the story: don't add the "Fixes: " line until right before you push to master.

**Comment by mikez302** [comment] 2016-08-07 19:18
I finally got a chance to try these things. This is what I have found:

- I ran `echo $fish_term24bit` and got an empty string in response.
- I ran `echo (set_color grey) foo` and it showed in light grey.
- I ran `echo (set_color white) foo` and it showed in green.
- I ran `echo (set_color ffffff) foo` and it showed in the same shade of light grey.
- I ran `echo $TERM` and it said "xterm".

I then went into my advanced settings and changed the "Declare terminal as" setting to "xterm-256color". Now, `echo (set_color white) foo` shows me "foo" in white.

Out of curiosity, why isn't the terminal declared as "xterm-256color" by default? Will changing this setting cause any problems?

**Comment by floam** [comment] 2016-08-07 23:00
On OS X it has defaulted to `xterm-256color` ever since `xterm-256color` was added to the list AFAIK.

Is it possible you have migrated some old settings over? You could test by reverting one of the profiles/"themes" in Terminal.app to default with the button it has and see what setting it gets.

**Comment by mikez302** [comment] 2016-08-08 02:23
@floam, to be honest, I don't care enough to spend my time trying to figure out why that happened. Maybe you are right about the default. I changed the setting to `xterm-256color` and it is working fine now. Feel free to close this issue if you don't think it should be open any more.

**Comment by floam** [comment] 2016-08-08 19:18
No problem,  just a suggestion if you were curious :smile:

This should be left open - the problem you encountered is a bug in fish that I'm working on fixing in #3260. Your changing that there should get you 256 colors - but this is a that shouldn't occur even only with 8 - 16 colors supported. `set_color white` should basically always work.

**Closed** 2016-09-11 10:14 UTC
Labels: bug, regression
