### ISSUE TITLE
Emoji issues in Fish 3.0

### ISSUE THREAD

**Issue by jerr0328** [fish-shell/fish-shell#5583] opened 2019-01-24 17:27 UTC
Fish version: 3.0.0
macOS Mojave: 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
iTerm2 Build 3.2.7, "Use Unicode 9 widths" unchecked
Ran without customizations (`sh -c 'env HOME=$(mktemp -d) fish'`)
Asciinema: https://asciinema.org/a/O8w4MnrYyj95MHQlXrtbdZatm

Emojis are still causing issues. #2652 claims this issue is fixed, but different combinations of `fish_emoji_width` (none, 1, 2) seem to affect the behavior without really fixing the problem. In Fish 2.7 I seemed to have avoided the problem with the iTerm workaround, but after updating to Fish 3.0, it started breaking. I can set the emoji width to 1 or 2, but it only works on some emojis (e.g. with 🛠and 🐛, one breaks and the other is ok when setting the value to 1, and the breakage swaps when I change the value). Using a newer emoji (e.g. 🥳) also causes a lot of issues. I have tried as well the ambiguous width values, but it also seems to cause the same random issue.

I installed Fish via brew.

**Comment by faho** [comment] 2019-01-24 17:36
>"Use Unicode 9 widths" unchecked

Check that, set $fish_emoji_width to 2, set $fish_ambiguous_width to whatever your terminal says - 2 for wide, 1 for narrow.

**Comment by faho** [comment] 2019-01-24 20:47
Soo.. I'm not sure if you noticed or it its the same for you, but your :hammer_and_wrench: "character" doesn't show as a character here. It shows as an image. So I can't copy it to figure out which character it is. Googling "hammer and wrench emoji" sends me to https://emojipedia.org/hammer-and-wrench/, which explains that it is:

>Codepoints
    🛠 U+1F6E0
    ️ U+FE0F

and indeed, copying that one gets me _2_ codepoints in the terminal (as confirmed by `od -t x1z` or `string length`). The latter is a variation selector. Which applies to another codepoint to change it somehow.

Which we already mention in our code:

```c++
    // Check for VS16 which selects emoji presentation. This "promotes" a character like U+2764
    // (width 1) to an emoji (probably width 2). So treat it as width 1 so the sums work. See #2652.
    const int variation_selector_16 = 0xFE0F;
    if (wc == variation_selector_16) return 1;
```

So together with U+2764, a U+FE0F variation selector "upgrades" it to an emoji. So both together have a width of 2. The former separately has a width of 1, so we give U+FE0F a width of 1 as well.

Now this hammer_and_wrench thingy (🛠) together with U+FE0F forms 🛠️. Which on my system looks absolutely identical. Not just the same width, the same actual symbol.

So there's no change in width. So the U+FE0F would in this case have to have a width of 0.

----

So, the easiest thing for you to do is to just use a different character. Maybe `echo \U1F6E0 | pbcopy` gives you a hammer_and_wrench without the variation selector that just works.

What we should do, I have no clue. That bit above was from our version of a function called `wcwidth` that has this quaint notion that characters are independent and have a certain width. So it's called with just one character (well, "codepoint" would probably be the correct term here), without any context.

**Comment by floam** [comment] 2019-01-24 22:01
I was able to copy and paste 🛠 just fine from his comment.

**Comment by jerr0328** [comment] 2019-01-24 22:03
Interesting, that shows as a perfectly normal character to me here in Chrome, I don't know if the browser or Github is trying to render as an image, I see the character itself both in my comment and in yours.

Running the `printf \U1F6E0 | pbcopy` (`printf` to avoid the newline thrown in by `echo`) doesn't help too much, I get the character but there's still some weirdness (like going up in the history and editing the command). I can work around this character, knowing that the codepoint is problem. For both, though `string length 🛠` shows a length of 1. Here's the output of `printf \U1F6E0 | god -t x1z` (prefix of g for gnu version, macOS otherwise has the BSD version which doesn't have `z` type):
```
0000000 f0 9f 9b a0                                      >�..�<
0000004
```
I'm not really sure if this means anything...

**Comment by faho** [comment] 2019-01-25 17:01
>I was able to copy and paste hammer_and_wrench just fine from his comment, it's not an image.

It is for me, but that's probably due to me using firefox and/or linux. It's not all that important.

>It does mess up fish's rendering with correctly-configured emoji widths.

How wide is it?

If you do `printf '%s\n' aa \U1F6E0`, is it as wide as one or two a?

Because our wcwidth says it's one of those that changed in Unicode 9, so if you're using Unicode 9 widths, it should be as wide as 2 a.

(And it's probably good news that it wasn't the variation selector)

**Comment by floam** [comment] 2019-01-25 17:13
It's displayed 2 columns wide.

**Comment by jerr0328** [comment] 2019-01-25 17:20
I see it as two, as well.
`printf '%sx\n' aa \U1F6E0` shows that it's being treated as 1 wide, with the x on the second line in the second line (first line it's on the third, following the two `x` characters).
<img width="25" alt="screenshot 2019-01-25 at 18 19 52" src="https://user-images.githubusercontent.com/1524722/51761618-de365d00-20cd-11e9-96f3-5c69a32298d2.png">

**Comment by faho** [comment] 2019-01-25 17:21
So... I'm afraid your terminal is wrong.

**Comment by jerr0328** [comment] 2019-01-25 17:31
I saw the same behavior in the standard macOS Terminal as well, with different fonts as well. It could be a system-wide issue. I'm not sure how Vim handles it because I see it rendered correctly there

**Comment by floam** [comment] 2019-01-25 17:34
Yes, I should have said that I'm on macOS 10.14, Terminal.app and iTerm. If we can figure out the range of emojis rendering like this we should be able to add a special case to our wcwidth.

**Comment by floam** [comment] 2019-01-25 17:43
And no, it's not the case that the libc wcwidth does any better:
<img width="379" alt="wcwidth" src="https://user-images.githubusercontent.com/291142/51762812-a1467800-2085-11e9-8746-3bd77ded3d48.png">

**Comment by ridiculousfish** [comment] 2019-01-25 20:50
Bug is U+1F41B, Hammer and Wrench is U+1F6E0. These both fall in the "widened in Unicode 9" category (so should respect "Use Unicode 9 widths" and `$fish_emoji_width`, which should agree).

The bug appears to be that iTerm2 is treating 'Hammer and Wrench'  (U+1F6E0 ) as width 1, even if "use Unicode 9 widths" is set. @gnachman does that seem right to you?

**Comment by faho** [comment] 2019-01-25 20:56
>The bug appears to be that iTerm2 is treating 'Hammer and Wrench' (U+1F6E0 ) as width 1, even if "use Unicode 9 widths" is set. @gnachman does that seem right to you?

Moreover the rendering is buggy - a character following hammer and wrench overlaps it, as can be seen in https://github.com/fish-shell/fish-shell/issues/5583#issuecomment-457647885:

![image](https://user-images.githubusercontent.com/1524722/51761618-de365d00-20cd-11e9-96f3-5c69a32298d2.png)

**Comment by floam** [comment] 2019-01-25 21:05
Ah, I didn't notice that. Yeah, the terminal's not working right.

**Comment by gnachman** [comment] 2019-01-26 00:52
@ridiculousfish Doesn't look full width to me. From https://www.unicode.org/Public/11.0.0/ucd/EastAsianWidth.txt

```
1F6E0..1F6EA;N   # So    [11] HAMMER AND WRENCH..NORTHEAST-POINTING AIRPLANE
```

**Comment by faho** [comment] 2019-01-26 20:40
>Doesn't look full width to me

@gnachman: Our wcwidth (https://github.com/ridiculousfish/widecharwidth) assumes that everything in emoji-data.txt that was introduced prior to Unicode 9 was widened in Unicode 9 (no matter what EastAsianWidth.txt says).

The rendering seems to agree - it's drawn at full width.

**Comment by ridiculousfish** [comment] 2019-01-27 05:39
Ugh I think I made a mistake - I believed that all emoji became width 2 in Unicode 9 but apparently that's not true.

**Comment by jerr0328** [comment] 2019-01-27 12:04
I did find an open issue regarding the rendering of these emoji with VS.
https://gitlab.com/gnachman/iterm2/issues/7239

Interesting to read in the issue: 
>  I think bash/readline is treating the heart symbol and the emoji variant selector as two separate typed/deletable characters, which is a little surprising.

I wonder if this also relates to the fact that the quote closing change goes a bit haywire with this.

Also, I looked again at the asciinema video on a different computer (running Windows) and the different rendering of emoji causes differences. In this case I think I really need to record the screen as a video to properly capture the issue,

**Comment by faho** [comment] 2019-01-27 12:13
>So Hammer and Wrench should be width 2 by default, and width 1 with Text VS. (But please don't do that second thing, there's no way fish could support that!)

(Dumb idea: Assume that the Text VS is used "correctly" and assign width "-1" to it iff emoji-width is 2? Just like we assign width 1 to emoji VS?)

**Comment by mqudsi** [comment] 2019-01-27 22:12
What if the user is on an OS that does not support Unicode 9.0 (or higher)? e.g. I believe while `U+1F469` (woman) and `U+1F3EB` (school) are both in Unicode 6.0, `U+1F569,U+200D,U+1F3EB` (female teacher) is only in Unicode 9.0. If fish "always" deduces that the combination is 1 wide, it'll be wrong when running under an older OS (even with the same terminal emulator and version *and* font), no?

----

*Also, I know the asciicinema stream depends on your OS and browser, but fwiw the following did not display correctly in the asciicinema for me but locally works out-of-the-box in both iTerm2 and Terminal.app on macOS Yosemite 10.10:*

![sparkles emoji + text](https://i.imgur.com/3cjsnIx.png)

**Comment by faho** [comment] 2019-01-27 22:15
>If fish "always" deduces that the combination is 1 wide

That's what $fish_emoji_width is for. You set it to 1 if you don't have Unicode 9, and 2 if you do.

**Comment by mqudsi** [comment] 2019-01-27 22:54
> That's what $fish_emoji_width is for. You set it to 1 if you don't have Unicode 9, and 2 if you do.

Maybe I'm missing something, but each release (and we're now on Unicode version 11) brings new combinations. What if your OS release supports Unicode 9 but you're trying to use a new combination from Unicode 11?

**Comment by faho** [comment] 2019-01-27 23:02
Then your terminal will probably get it wrong.

Am So., 27. Jan. 2019, 23:54 hat Mahmoud Al-Qudsi <notifications@github.com>
geschrieben:

**Comment by mqudsi** [comment] 2019-01-27 23:09
Not if `fish_emoji_width` were replaced with a `fish_unicode_version` and its value were quizzed to determine supported combinations. Personally, I don't use emoji in the terminal, but my personal feelings about that don't seem to have dampened the demand for emoji support in the terminal.

(Also, to share a tangentially related issue that I found enlightening some months back: https://github.com/kovidgoyal/kitty/issues/461)

**Comment by faho** [comment] 2019-01-27 23:13
No, because your terminal needs to get the same width.

We can't query width for every single codepoint, and the one large change
is unicode 9.

Am Mo., 28. Jan. 2019, 00:09 hat Mahmoud Al-Qudsi <notifications@github.com>
geschrieben:

**Comment by floam** [comment] 2019-02-19 12:19
Given that we've encountered VS 15 in the wild in #5668, I'm going to commit a change to have our function return 0 for that case. It's only right some of the time - sometimes it probably needs to subtract 1 depending on the previous character, perhaps possible in our `wcswidth` implementation - but returning 1 which would increase the sum is always wrong.

**Comment by floam** [comment] 2019-03-13 11:39
It really seems like we do need something more clever that takes entire strings into account. It seems to me that `wcswidth` could theoretically do this but implementations do not. I assume ICU can figure it out? What's there short of that?

**Comment by floam** [comment] 2019-03-13 11:41
This is leaving aside that it seems like you actually need insight into the fonts available to figure out some things. But one could get much closer with a function given an entire string.

**Comment by faho** [comment] 2019-03-13 11:48
>This is leaving aside that it seems like you actually need insight into the fonts available to figure out some things. 

Sorry, if the font changes things there's nothing we can do. E.g. non-monospace fonts are broken here.

**Comment by floam** [comment] 2019-03-13 11:50
Of course. Or if you don't have a graphical representation available for the slightly smiling emoji. Point is, a wcswidth taking into account which sequences come after other sequences, it seems like we could get closer to the right answer *more* of the time.

**Comment by ridiculousfish** [comment] 2019-03-24 02:12
We're completely at the mercy of the terminal's rendering here. bash doesn't have these issues because bash doesn't care: it doesn't need to worry about character widths because it doesn't attempt to do layout. The price of this is that it can't support e.g. a right prompt. However I wonder if we can move fish towards caring less; if fish required the character width less often, it would help reduce this sort of issue.

**Comment by gnachman** [comment] 2019-03-25 16:38
Bash has lots of problems with character width because it likes to redraw the prompt under various circumstances, such as when you control-R or the window resizes. It's a fairly frequent source of bug reports for iTerm2.

**Comment by mqudsi** [comment] 2019-03-28 08:37
Lol. I can sympathize. It feels like I spend most of my free time filing bug reports related to various resizing and and repainting issues in neovim where one patch fixes things for a terminal only to break it for ten others.

What we need is a unified API in the opposite direction where a program can ask the terminal "tell me about the currently visible layout" and get meaningful results back. There are too many variables beyond our control in 2019 that were simply not an issue in the 80s (let alone earlier). It's not just the number of bytes not correlating to the number of glyphs or the width of a glyph not being a single cell, even accounting for the same combination of terminal and shell. The font in use, the operating systems rendering features, accessibility options at play.. there has to be a better option than throwing it all away and bundling a web browser in a gtk toolkit and calling it a terminal that solves these problems.

**Comment by floam** [comment] 2019-04-05 21:14
The primary thing that would be nice to make better is the way the computed cursor position being off really makes things go to hell interactively in fish, it can make it hard to even enter commands because the user has to guess where fish is going to insert a character when they type, and guess what character will go away when they hit backspace. The stair stepping, text getting entered wrong, and way you start typing over the printed prompt is bonkers for a user to figure out.  Could we do anything to cause fish not to care about the computed cursor position quite so much or limit the damage?

A right prompt being misaligned is annoying but what's really maddening is an emoji appearing in your current command-line or being flashed from an autosuggestion and totally corrupting the experience. Could cursor position save/restores or querying the cursor position on capable terminals help?

**Comment by floam** [comment] 2019-04-06 01:55
I wrote this function to determine the rendered widths of given strings:

```
function realwidth
    tput smcup
    printf "%s%s" $argv[1] \e\[6n\;
    read -l out -n5
    tput rmcup
    set -l width (math (string match -r '\[\d;(\d+)R' $out)[2] - 1) # cursor is in the column after the thing was rendered
    printf "%d\n" $width
end
```
It uses the alternate screen only because I couldn't figure out how to make `read -s` not echo any characters like bash's can, and `stty -echo` didn't work in fish. 

It seems like we could do a couple one-off checks perhaps on first launch like how we generate manpage completions, and guess emoji width and ambiguous width characters from that on capable terminals.

**Comment by floam** [comment] 2019-04-06 02:09
Or maybe it could be triggered by `fish_config`.

**Comment by faho** [comment] 2019-05-28 19:59
I think the current situation is the best we can do with changes just in fish, so I'll close this.

It's also not that bad anymore - use an up-to-date terminal on an up-to-date system and it should mostly "just work".

**Closed by faho** 2019-05-28 19:59 UTC
Labels: bug
