### ISSUE TITLE
Error when a function's def has an empty line at the end of the file; is this harsh or best practice?

### ISSUE THREAD

**Issue by EdmundsEcho** [fish-shell/fish-shell#7182] opened 2020-07-07 14:51 UTC
This is more of an "FYI" and question.

The FYI is that when defining a function, in the event there is a trailing new line at the end of the file, fish returns the following error: 

```
338:339: syntax error: Expected end of line but found unknown token. (-2741) 
```

It was easy to fix once I took the time to open the function definition.  I just want to bring it up in context of "is this best practice"? or is it easier to have fish ignore such an issue?

\- E

**Comment by faho** [comment] 2020-07-07 16:04
@EdmundsEcho Can you clarify what the function looks like?

Is this in a function file? Does

```fish
printf '%s\n' "function foo" "echo foo" "end" "" "" | source
```

reproduce the issue? Or if you output that bit into a function file?

I kinda doubt it's just a newline, and that's absolutely not supposed to happen - empty lines are supposed to be entirely transparent, and going by Unix's actual definition something is only a text file if it has a trailing newline.

**Comment by faho** [comment] 2020-07-07 16:04
Also this does not look like any fish error I've ever seen - which fish version are you running?

**Comment by faho** [comment] 2020-07-07 16:48
Okay, this appears to be an *AppleScript* error. In which case fish has nothing to do with interpreting it, so there is nothing we can do.

**Comment by EdmundsEcho** [comment] 2020-07-07 21:29
The code you provided did not generate the error.  The function was defined in a file in the fish/function directory. The version of fish is 3.1.2 (I provided it in the commented template code; I was never sure if you all could see the input we provide there).  So fish engages applescript?

**Comment by zanchey** [comment] 2020-07-08 03:46
Can you provide the source of the function file? When do you see this error?

**Comment by EdmundsEcho** [comment] 2020-07-08 14:56
Here is the source:
```
function grep
  ggrep --color=auto
end
```

Add a line after `end` to generate the error. 

I'm also seeing the error when I <crl-x> out of an active process.  Here is the screenshot.

![Screen Shot 2020-07-08 at 10 52 05 AM](https://user-images.githubusercontent.com/11245417/86934287-89dc3d00-c109-11ea-9305-34aa4e10bee2.png)

**Comment by faho** [comment] 2020-07-08 15:06
@EdmundsEcho What is `ggrep`? `type ggrep` should tell you.

**Comment by mqudsi** [comment] 2020-07-08 16:07
(I'm guessing gnu grep)

**Comment by mqudsi** [comment] 2020-07-08 16:08
Is the error being generated by your prompt?

**Comment by faho** [comment] 2020-07-08 16:15
>(I'm guessing gnu grep)

I'm guessing that's what it is *supposed* to be, but since we get an applescript error it might not.

**Comment by ridiculousfish** [comment] 2020-07-11 20:58
This is indeed an AppleScript error probably due to Windows line endings (\r)

**Comment by EdmundsEcho** [comment] 2020-07-14 19:45
@faho  others had it right: gnu grep.  When I was building a find/replace capacity, using the gnu version of the unix utility was more efficient; and in general from what I could gather.  

@ridiculousfish -- If you are correct, I should be able to add the extra line to my function, and *not* see the error.  That is indeed what happens.  Nice catch!  

I've been on a mac os for years now.  So, how did this "non-compliant" version of line break get into the function? I believe fishshell converts my `alias` entries to a function. So, to be clear, I did not write this function; it's an automated wrapper generated by fishshell. 

Is it possible that the fishshell conversion `:: alias -> function` includes a superfluous line at the end of the file AND can sometimes do so using `\r` instead of `\n`?  Is Mac OS starting to drop support for `\r`? (where before they supported both `\r` (DOS) and `\n` but not `\r\n` (windows))

I suspect there was a point when this was the case.  I can't see the function wrappers for all of my aliases... And further, my `ls` alias.  `tmux.fish` has an extra line but has a `unix` fileformat... So a bit of a mystery but likely something to keep an eye one?

([see this article from O'Reilly](https://www.oreilly.com/library/view/mac-os-x/0596004605/ch01s06.html) for the historical encoding of linebreak on Mac, Windows and Unix).

\- E

**Comment by faho** [comment] 2020-07-14 20:04
>Is it possible that the fishshell conversion :: alias -> function includes a superfluous line at the end of the file AND can sometimes do so using \r instead of \n? 

No.

It is possible that you opened it with `funced`, with an editor set to use `\r`, or that you opened the file in an editor otherwise.

Anyway, we figured out what the problem was, and I'm fairly confident that fish won't randomly insert \r anywhere, so I'm closing this.

**Closed by faho** 2020-07-14 20:04 UTC
Labels: needs more info

**Comment by EdmundsEcho** [comment] 2020-07-20 19:29
Your course of action makes sense.  My only closing comment is that I don't use anything other than nvim on a mac os.  It does not altogether eliminate the possibility of what you are describing, but is likely a useful fyi nonetheless.  Thank you all-round. \- E
