### ISSUE TITLE
pipe buffers too much causing grep's to not show data

### ISSUE THREAD

**Issue by yalon** [fish-shell/fish-shell#9445] opened 2023-01-03 08:33 UTC
Hi,

I'm running on LinuxBrew-built fish 3.5.1 on Amazon Linux 2 (5.10.130-118.517.amzn2.x86_64 #1 SMP Wed Jul 13 16:51:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux).

Seems like fish adds buffering when piping processes, which makes grep'ing over large (or infinite) amounts of data impossible. 

Why is this so painful? For example, if you're troubleshooting a running service (e.g. `docker logs -f xxx`) and pipe it through some greps to catch a specific log line out of a huge number of lines, with fish it won't work but with bash it will.

Here's a fairly easy way to reproduce - this is CPU bound so you may want to tweak the numbers:

First, a primitive data generator:

```shell
time python -c 'for i in range(100000000): print(i)' > /dev/null

real	0m34.518s
user	0m34.478s
sys	0m0.017s
```

Now, when running the following in bash:
```shell
python -c 'for i in range(100000000): print(i)' | grep 35 | grep 989
```

You start receiving results to the console immediately, since 35989 for example fits the grep conditions but in fish I see the output only when the Python process exits.

Here's a way to show the buffering issue without pasting a video:

```shell
# run this from bash so the "last" pipe and head will run from bash:
bash -c "python -c 'for i in range(100000000): print(i)' | grep 35 | grep 989" | (time head -1)
35989

real	0m2.183s
user	0m0.001s
sys	0m0.000s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
BrokenPipeError: [Errno 32] Broken pipe
```

This shows that the "35989" line was outputted after 2 seconds.

Now, running the same with fish will only output the filtered lines when the Python process exits. Using the same method to measure when the first line gets output:

```shell
# run this from bash so the "last" pipe and head will run from bash:
fish -c "python -c 'for i in range(100000000): print(i)' | grep 35 | grep 989" | (time head -1)
35989

real	0m36.057s
user	0m0.000s
sys	0m0.001s
```

This shows that the "35989" was outputted after 36 seconds (or basically, once the Python process exitted).

I tried to find any fish setting that will make it not buffer but couldn't, so opening this ticket.

Thanks!

**Comment by faho** [comment] 2023-01-03 08:36
Duplicate of #1396

**Comment by faho** [comment] 2023-01-03 08:37
`grep` is a function by default, and functions and blocks buffer output to solve a variety of issues.

Use `command grep` to avoid it in this case.

**Closed by faho** 2023-01-03 08:36 UTC

**Comment by yalon** [comment] 2023-01-03 09:05
Thanks @faho for the quick reply and the help! 

I was actually unaware of grep being a function (kinda sneaky since when I run grep --help it looks like a regular GNU grep), so running `type` I see that the reason grep is a function is to add `--color=auto`, similar to bash's grep alias.

Unfortunately, from what I can see with the bug you linked, since fish implements aliasing as a function as well, there's no way to work around this except explicitly writing `/usr/bin/grep --color=auto` every time, implementing a shim, or risk forgetting the buffering issue and keep the existing function/alias.

I do humbly suggest that until #1396 is resolved, adding a shim for grep or simply not adding the "grep" function in a default installation, since I think it's a common use case to pipe some greps together.

Thanks again.

**Comment by ridiculousfish** [comment] 2023-01-03 23:21
Note the buffering only occurs if you have multiple `grep`s (or other fish functions) in the same pipeline. For the common case of a single `grep` you will not encounter buffering.
