### ISSUE TITLE
posix_spawn busted on OpenBSD

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#1064] opened 2013-10-27 22:28 UTC
fish 2.1.0 can't seem to execute any commands correctly on OpenBSD 5.3 when `fish_use_posix_spawn` is 1 (which it is by default). Tested using the Vagrant box from http://www.vagrantbox.es

**Comment by dongcarl** [comment] 2015-02-13 09:11
@ridiculousfish why is that the case? it looks like OpenBSD has posix_spawn: http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-5.6/man3/posix_spawn.3?query=posix_spawn&sec=3&manpath=OpenBSD-5%2e6

**Comment by ridiculousfish** [comment] 2015-02-13 09:16
Yes, it has it, so fish uses it. As to why it doesn't work - I dunno! It just breaks horribly. I haven't investigated yet!

**Comment by dongcarl** [comment] 2015-02-13 09:19
would you think that it's appropriate to ask the OpenBSD devs?

**Comment by ridiculousfish** [comment] 2015-02-13 09:23
Not without some evidence that the problem is with OpenBSD, e.g. a reduced test case.

**Comment by dongcarl** [comment] 2015-02-13 09:36
I'm just a noob but I know you guys probably wouldn't have the time to do this... What are some resources that might help get me started on fixing this?

**Comment by ridiculousfish** [comment] 2015-02-13 09:39
Are you an OpenBSD user? If so you could start by seeing if this still happens. Install fish HEAD and see if it works :)

**Comment by dongcarl** [comment] 2015-02-13 09:42
Yeah I simply cloned the github repo and went through the building process... I'll try it with HEAD

**Comment by dongcarl** [comment] 2015-02-13 09:44
Setting `fish_use_posix_spawn` to 0 makes everything all good though

**Comment by bonds** [comment] 2017-02-22 11:33
I'm running Fish 2.3.1 built from source, on OpenBSD 6.0-stable on x86_64, and Fish works fine out of the box, I did not need to set fish_use_posix_spawn.

**Comment by krader1961** [comment] 2017-03-29 03:08
Closing since this was reported 3.5 years ago and someone reported just one month ago that the bug is no longer present. Feel free to reopen if you can reproduce this using fish 2.5.0 or newer on OpenBSD.

**Closed by krader1961** 2017-03-29 03:08 UTC
Labels: bug
