### ISSUE TITLE
Prompt issue after upgrade from 2.3 to 2.4

### ISSUE THREAD

**Issue by hawkeyej** [fish-shell/fish-shell#3535] opened 2016-11-08 20:05 UTC
Since upgrading from 2.3 to 2.4, I'm getting some extra output right before my budspencer prompt.

`
[1 q[1 q⏎
`

I have no idea where it's coming from. It was not there for 2.3

**Comment by floam** [comment] 2016-11-08 20:23
What terminal are you using and what is `TERM` set to?

**Comment by floam** [comment] 2016-11-08 20:24
(This is going to be perhaps another manifestation of #3499).

**Comment by hawkeyej** [comment] 2016-11-08 20:51
gnome-terminal and TERM=xterm
Linux Mint 17.3 Cinnamon

Does look like the same symptom.

**Comment by faho** [comment] 2016-11-08 21:41
@hawkeyej: What is $VTE_VERSION?

**Comment by hawkeyej** [comment] 2016-11-08 21:59
No such thing.

**Comment by faho** [comment] 2016-11-08 22:22
$@~@~¼@²¸14""$"$!!! (colorful swearing)

I can reproduce this with the gtk2 version of lxterminal. It seems there were some versions of it without $VTE_VERSION, so our detection is failing on those. Even worse, it seems those versions are still in the wild.

For now, you can put `function fish_vi_cursor; end` into your config.fish to disable the cursor stuff.

**Comment by hawkeyej** [comment] 2016-11-08 22:28
@faho Thanks for the workaround

**Comment by c22** [comment] 2016-11-09 04:45
Not sure if it's specifically related, maybe slightly related to #3535 or maybe this should be a separate issue entirely, but Ctrl+C shows output in terminal now whereas prior to 2.4 it did not.

eg.

`asd [ctrl+c]` results in
`asd^C`

Using iTerm2 (3.0.10) on OSX 10.11.6

Is this intended behaviour? Can it be turned off?

I've also noticed some command completions ending prematurely under certain circumstances, but haven't worked out how to reproduce them just yet.

**Comment by krader1961** [comment] 2016-11-09 04:59
@c22, Why do you think the [ctrl-C] behavior is related to the problem reported by @hawkeyej?  You should have seen that behavior with fish 2.3 albeit with some problems. See commit 1cd4731c, included in fish 2.3, and subsequent commits included in fish 2.4 (e.g., 5f849d02, a897ef00, and 8ca3adaa). 

> Is this intended behaviour? Can it be turned off?

Yes it is intended, and no it cannot be turned off.

**Comment by faho** [comment] 2016-11-09 13:37
>Yes it is intended, and no it cannot be turned off.

Well, this is achieved via binding ctrl-c, so you can restore the old binding - `bind \cc 'commandline ""'`.

Okay, back to the problem at hand.

What happens here is that this terminal identifies as "xterm", and the terminfo definition says that things identifying as "xterm" can change cursor. None of our other checks fail (because we only blacklist things inside of emacs or with a too old but still defined VTE_VERSION).

I have now figured out how to detect that case - $TERM is xterm* but it's neither konsole nor iterm nor a new enough vte nor a new enough xterm - and now I'd like to check if the logic can be simplified.

@zanchey: If we do a 2.4.1, this should be included.

**Comment by ridiculousfish** [comment] 2016-11-09 21:59
@c22 I disable the new ^C behavior via:

```function __fish_cancel_commandline
    commandline ""
    commandline -f repaint
end
```

**Comment by aureooms** [comment] 2016-11-18 17:42
Screenshot, minimal reproducing step is to set fish_key_bindings fish_vi_key_bindings

![screenshot](http://i.imgur.com/6W45gc4.png)

**Comment by faho** [comment] 2016-11-18 18:38
This is actually a duplicate of #3499, which I've just closed via acc2353.

If all those affected could confirm that this removes the weird sequences, that'd be great.

**Comment by fabianhjr** [comment] 2016-11-20 19:19
Had the issue with `fish 2.4.0`, was using the temp fix described [here](https://github.com/fish-shell/fish-shell/issues/3535#issuecomment-259278388). The following is my system information.
```
Linux 4.8.8-2-ARCH x86_64
terminator 0.98
```
After upgrading to `fish 2.4.0-136-gb86b84e` the problem was solved.

**Comment by faho** [comment] 2016-11-20 22:01
>I don't know if the following is related to this issue, but is something I experienced after upgrading. Using alt + backspace should be deleting word by word but instead it glitches a backspace.

It's not - the vi-bindings were changed. Specifically, in 2.3 I changed it so they just inherited all of the emacs bindings. That turned out to be somewhat messy, so we decided to only pick some bindings that aren't related to editing text and share those.

Anyway, nice that it's working. I'll close this issue then.

**Closed by faho** 2016-11-20 22:01 UTC
Labels: bug, regression

**Comment by fabianhjr** [comment] 2016-11-21 02:34
Great, thanks for the info. ^-^
