### ISSUE TITLE
Core dump on latest cygwin version on windows 8

### ISSUE THREAD

**Issue by mcormier** [fish-shell/fish-shell#1146] opened 2013-11-28 00:04 UTC
Starting using fish on a windows 8/cygwin setup and the following occurred.

fish ) fassertion "thread->thread != 0" failed: file "iothread.cpp", line 202, function: void iothread_service_completion()
Aborted (core dumped)

Don't know what caused it, don't have a set of steps to reproduce.

The latest Cygwin version is 2.1.0

**Comment by oysteinkrog** [comment] 2015-05-22 11:31
Also getting this.

**Comment by nekulturny** [comment] 2015-08-02 15:53
I've had these core dumps also using fish on both Windows 7 and Windows 8.

I was looking at the fish source code and I saw that fish uses posix_spawn on OSX because it's more efficient than fork on that platform.  I also found this project here on github that purports to be an efficient posix_spawn implementation for Cygwin:  https://github.com/dcolascione/cygspawn

I'm a Java developer and this is all pretty much Greek to me but maybe there's a solution in there somewhere.

**Comment by zanchey** [comment] 2015-08-06 05:16
There's some pretty scary stuff in that link.

**Comment by nekulturny** [comment] 2015-08-08 21:50
That ... is entirely believable to me.  I did some more research after posting it and I realized it almost certainly would not help.  I don't know enough to be of any practical use.

However as a side note, I am now running fish 2.2.0 that I compiled from source on cygwin and the core dumps seem to have stopped.  This is on Windows 8.

**Comment by zanchey** [comment] 2015-11-04 05:40
Both 2.2.0 and git master seem to work fine on Cygwin without dumping core, so I'm closing this for now. If anyone can reproduce it please speak up!

**Closed by zanchey** 2015-11-04 05:40 UTC
Labels: windows
