### ISSUE TITLE
False positive by `fish -n`

### ISSUE THREAD

**Issue by refaelsh** [fish-shell/fish-shell#7618] opened 2021-01-10 21:20 UTC
❯ fish --version
fish, version 3.1.2

❯ echo $version
3.1.2

❯ uname -a
Linux arch 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 GNU/Linux

❯ echo $TERM
alacritty

I've tried running `fish -n` on the following simple file:
```
❯ cat .config/fish/config.fish
#!/usr/bin/fish
alias ls="ls --color=auto"

starship init fish | source

❯
```

And got a strange result:
```
❯ fish -n .config/fish/config.fish
.config/fish/config.fish (line 2):
alias ls="ls --color=auto"
^

❯
```

As if there is somekind of a problem on line 2.

Please advice.

**Comment by faho** [comment] 2021-01-10 21:54
Duplicate of #977

**Closed by faho** 2021-01-10 21:54 UTC

**Comment by faho** [comment] 2021-01-10 21:55
Yes, the issue here is that `fish --no-execute` used to still complain about commands it can't find, and since it won't actually `source` any functions it'll complain about every function (unless there's a command of the same name in the default $PATH).

This makes `fish --no-execute` basically useless.

Good news is it's fixed in the next release.
