### ISSUE TITLE
Unable to use function end-selection with binding

### ISSUE THREAD

**Issue by haoadoreorange** [fish-shell/fish-shell#9369] opened 2022-11-22 04:10 UTC
Please tell us which fish version you are using by executing the following:

  3.5.1

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

6.0.8-arch1-1
xterm-256color

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

Yes

**YOUR TEXT HERE**
I bind ctrl+x to copy and end the selection in fish
```
bind \cx 'fish_clipboard_copy; end-selection'
```
But the `end-selection` gives an error "Unknown command". I have to write
```
bind \cx 'fish_clipboard_copy; commandline -f end-selection'
```
Is this the intended behavior ?

**Comment by faho** [comment] 2022-11-22 05:56
> Is this the intended behavior ?

Yes. "end-selection" is not a normal function or a proper command. It's a thing to do in a binding.

Closing since it's working as intended.

**Closed by faho** 2022-11-22 05:56 UTC
