### ISSUE TITLE
`cd ~/Documents` fails with `Permission denied` error when using Fish over SSH on macOS

### ISSUE THREAD

**Issue by Tyrubias** [fish-shell/fish-shell#9079] opened 2022-07-20 05:46 UTC
**Environment**

```fish
$ fish --version
fish, version 3.5.0
$ echo $version
3.5.0
$ uname -a
Darwin Victors-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
$ echo $TERM
xterm-kitty
```

I use `fish` (installed using Homebrew) as my login shell on both macOS and Linux. When I `ssh` into my macOS system from my Linux system, I am unable to `cd` to `~/Documents`, `~/Downloads`, or `~/Desktop`. I receive a generic `Permission denied` error when I attempt to do so.

I have replicated this behavior using other terminal emulators such as iTerm2 and the built-in Terminal application. I can also replicate this behavior when I disable third-party customization using ` sh -c 'env HOME=$(mktemp -d) fish'`. Furthermore, I can replicate this behavior without the use of a second machine simply by executing `ssh localhost` on my macOS system.

I don't see this error if I attempt to `cd` to other built-in macOS directories such as `~/Library` or `~/Pictures`. I also don't see this error if I launch `zsh` from `fish` after I `ssh` into my macOS system. However, when using `zsh` launched from `fish` over `ssh`, I cannot list the contents of the `~/Documents`, `~/Downloads`, or `~/Desktop` directories after I `cd` to them.

**Here is a quick `asciinema` of this behavior**

[![asciicast](https://asciinema.org/a/LVTZTQUAEuFW1qVHLbUD9NRoT.svg)](https://asciinema.org/a/LVTZTQUAEuFW1qVHLbUD9NRoT)

If I can provide any other logs or take any other steps to help debug this, I'd be more than happy to! Please let me know how I can help.

**Comment by krobelus** [comment] 2022-07-20 05:51
try https://stackoverflow.com/questions/69018553/getting-an-error-cd-users-x-downloads-is-a-rotten-symlink-in-fish-shell/69023975#69023975

**Comment by Tyrubias** [comment] 2022-07-20 05:56
@krobelus Thank you for the suggestion. To clarified, I've already tried this (including giving all three of the terminal emulators I've tried this on Full Disk Access) and I get the same error.

**Comment by Tyrubias** [comment] 2022-07-20 05:58
For further clarification, this doesn't happen when I just open `fish` on my local machine; this only occurs when I connect to my macOS system over SSH with `fish` as the login shell.

**Comment by floam** [comment] 2022-07-20 06:34
Considering even in zsh, you still do not see the contents of these directories. I'll ask if you might consult https://derflounder.wordpress.com/2021/09/29/enabling-full-disk-access-for-ssh-on-macos-big-sur-using-a-management-profile/

**Comment by Tyrubias** [comment] 2022-07-20 18:48
Thank you so much for the help. Enabling full disk access for remote users does fix this, but this is not an issue I had when my login shell is set to `zsh`. Is there anything further I can do to help investigate this? I understand that there are [security concerns with `ssh-keygen-wrapper`](https://www.sentinelone.com/blog/mojaves-security-hardening-user-protections-bypassed/).

**Comment by floam** [comment] 2022-07-21 05:32
It would be a matter of trying to break down exactly what that option does any by which mechanism you're receiving the permission denied errors. It could be sandboxing, or a way in which rights are inherited in the case of sshd. You'd need to watch `log stream` activity like a hawk with debug information enabled in the two different cases, maybe compare syscalls made.

**Comment by floam** [comment] 2022-07-21 05:44
I'd suggest trying a /usr/local/bin/fish that is fully signed so you are comparing apples to apples - use the .pkg installer.

**Comment by faho** [comment] 2022-08-03 10:54
Okay I think we've explained what the issue is - fish isn't entitled enough to macOS' sandboxing, while the zsh as the default shell obviously is.

I don't think we can give you any more clues and there hasn't been any movement here in two weeks, so I'm closing this. If you have any follow-up questions, do of course feel free to ask.

**Closed by faho** 2022-08-03 10:54 UTC
Labels: question
