### ISSUE TITLE
`test` mis-parse with compound expression involving string comparison where LHS is a flag known to test

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#5947] opened 2019-06-19 22:50 UTC
`test` takes a number of flags, such as `test -g filename`, but it prioritizes binary operators over interpreting an argument as a flag, e.g. `test -g = -g` is parsed as a string comparison. This is useful when the first arg is actually a variable, e.g. `test "$flag" = -g`.

Unfortunately, this fails once a compound expression is involved. `test -g = -g -o -g = --graph` (which comes from `test "$flag" = -g -o "$flag" = --graph`). In this case it instead parses the `-g` as the unary operator and emits the error

> test: Expected a combining operator like '-a' at index 2

This is true even when using parentheses to group, e.g. `test \( -g = -g \) -o \( -g = --graph \)`.

Reproduced with recent `master` (`fish, version 3.0.2-1297-gb41e5cbbb-dirty`) as well as version `3.0.2`.

**Comment by lilyball** [comment] 2019-06-19 22:52
Looks like this has been filed before as #5186, but that issue was closed saying this is just an edge case. Closing that was wrong; bash is able to parse this correctly.

**Comment by faho** [comment] 2019-06-21 10:31
Note that this isn't actually even a violation of POSIX, because:

     >4 arguments:
        The results are unspecified. 

To be perfectly frank, test sucks, and should be replaced. And the replacement should not have combining operators, and most of all should not include a one argument mode.

If anyone cares enough to write a patch for this, we'll merge it.

**Comment by faho** [comment] 2019-07-02 21:24
Okay, I'm gonna close this as a duplicate of #1337. @lilyball even commented essentially the same example.

**Closed by faho** 2019-07-02 21:24 UTC
Labels: bug
