### ISSUE TITLE
complete no-files option not working

### ISSUE THREAD

**Issue by lordlycastle** [fish-shell/fish-shell#2587] opened 2015-12-08 23:16 UTC
I just tried to write an option completion in which the option shouldn't be followed by file, and should have an argument provided, so from docs I should use `-x` option in complete. But for some reason when I try auto-complete after that option the files are listed. [Video](http://zippy.gfycat.com/NaturalAcrobaticAcornbarnacle.mp4). The `-r` option is working correctly as it doesn't suggest other options; it's just the `-f` option that's acting odd.

**Comment by faho** [comment] 2015-12-09 08:40
It's not _quite_ not working, you just need to supply it to every single completion - i.e. if there's one applicable completion that allows files, you'll get files.

Anyway, this is a duplicate of #112.

**Closed by faho** 2015-12-09 08:40 UTC

**Comment by lordlycastle** [comment] 2015-12-09 14:06
Thanks for clearing that up. I wanted to write completions of `open` command on OS X, I wanted your input in determining if the system was OS X; would `[ (uname -s) = 'Darwin' ]` be a good enough check for that?

**Comment by faho** [comment] 2015-12-09 14:11
> I wanted your input in determining if the system was OS X; would [ (uname -s) = 'Darwin' ] be a good enough check for that?

That's what we do in e.g. functions/help.fish or functions/open.fish (minus the "-s", which is redundant at least according to my man page).

**Comment by ridiculousfish** [comment] 2015-12-09 19:49
open completions on OS X would be great to have. `test (uname) = Darwin` is what it does today.

**Comment by lordlycastle** [comment] 2015-12-10 13:42
I was also looking into completions for `killall`, they're different too... I noticed that global variable [`__kill_signals`](https://github.com/fish-shell/fish-shell/blob/b85a8bb/share/functions/__fish_make_completion_signals.fish#l14) isn't set properly. Only signal 31 is available in completions. I'm guessing that is because it's over-written by every iteration of the following for-loop. Any specific reason why it's done this way?
```
for i in (seq 31)
    set -g __kill_signals $signals $i" "(kill -l $i) # Also I couldn't find a declaration of $signals
end
```

**Comment by faho** [comment] 2015-12-10 13:56
@lordlycastle: Yeah, that'll be what we around these parts call one of them there "bugs". It's fetchin' fer a fixin'. Yeehaw!

Also __fish_make_completion_signals has a few other issues - it doesn't add the -l option on my system, which my kill (from util-linux 2.27.1) also supports, and it adds completions for `kill` even though it might be invoked for `killall`. I'd rather have a function that just echoes out `$signalnumber\t$signalname\n` (so the name is used as a description) and `$signalname\n`.

**Comment by lordlycastle** [comment] 2015-12-10 20:07
@faho I don't think it's bug, just a typo, replacing `signals` in the line above with `__kill_signals` seems to get all the signals. As for the completions, I can add/fix the OS X; if you have URL to Linux manual page, I can improve those too, if you wish.

![screen shot 2015-12-10 at 20 04 58](https://cloud.githubusercontent.com/assets/11729541/11727017/4f3cc09a-9f79-11e5-9203-2145103b93d9.png)

**Comment by faho** [comment] 2015-12-10 20:30
> I don't think it's bug, just a typo

A typo can cause a bug.

>if you have URL to Linux manual page

My kill supports "-L", so the other codepath will be used. This means the signals are all listed.

As for the other options, I can't find the correct man page online, so I'll just paste it here:


```
-s, --signal signal
              The signal to send.  It may be given as a name or a number.

       -l, --list [number]
              Print a list of signal names, or convert the given signal number to a name.  The signals can be found in /usr/include/linux/signal.h

       -L, --table
              Similar to -l, but it will print signal names and their corresponding numbers.

       -a, --all
              Do not restrict the commandname-to-pid conversion to processes with the same uid as the present process.

       -p, --pid
              Only print the process id (pid) of the named processes, do not send any signals.

              The --pid option is automatically enabled when the kill command is invoked with the name of pid.  This functionality is deprecated, and will be removed in March 2016.

       --verbose
              Print pid(s) that will be signaled with kill along with the signal.

       -q, --queue value
              Use sigqueue(2) rather than kill(2).  The value argument is an integer that is sent along with the signal.  If the receiving process has installed a handler for this  signal
              using the SA_SIGINFO flag to sigaction(2), then it can obtain this data via the si_sigval field of the siginfo_t structure.
```

Thanks!

**Comment by lordlycastle** [comment] 2015-12-17 02:45
@faho I know you wanted to have a different `__fish_make_completions_signals`, but I kinda fixed it so all signal names and numbers are completed along with proper descriptions. Have a [gander](https://github.com/fish-shell/fish-shell/compare/master...lordlycastle:base).

**Comment by faho** [comment] 2015-12-17 10:18
@lordlycastle: Do you think the descriptions are really all that useful? It'll just print stuff like "KILL    Send KILL signal". What I'd like more is completing names without descriptions, and numbers with the names as descriptions (like "9" described as "KILL").

Also, instead of the uname check you'll probably want to check if "killall --version" fails (unless that then kills everything named "--version", which I doubt). That would then cause the same path to be used on the BSDs, which are quite similar to OSX when it comes to these kinds of commandline tools. In general it's nicer to attempt to test functionality, not names.

As for_make_completion_signals.... well, this'd at least fix the glaringest bug. We can still improve it later.

**Comment by lordlycastle** [comment] 2015-12-17 19:10
@faho That's works, I'll fix the signals completions. I didn't use `killall --version` before it wasn't already included in the completions, so wasn't sure if it existed. 

I also wanted to write completions for `killall -u` where username or UID follow the option. Just want to make sure it'll work at you side too.  What I have is as follows, unless there's better way:
```
function __make_users_completions
	set -l users (dscl . list /Users | grep -v '^_.*')
	for user in $users
		set uid (id -u $user)
		complete -c killall -s u -x -a "$user $uid" -d "Match only processes belonging to $user"
	end
end
```
Secondly, there is also `-t` option with definition:
```
-t tty      Limit potentially matching processes to those running on the specified tty.
```
Do you know of a better way for completing all running ttys other than using `ls /dev/tty*` and `grep`?

**Comment by faho** [comment] 2015-12-17 19:31
>I also wanted to write completions for killall -u where username or UID follow the option. Just want to make sure it'll work at you side too.

Doesn't use UIDs for my killall (from psmisc), only usernames:

```fish
> killall -u 0
Cannot find user 0
> killall -u root
# Tons of "operation not permitted" messages scrolling by since I wasn't dumb enough to execute that as root
```

>Secondly, there is also -t option with definition:

Not a thing for my killall either.

>Do you know of a better way for completing all running ttys

`ps` can print ttys - `ps a -o tty` or similar might work (though I've always found ps to be weirdly complicated).

**Comment by zanchey** [comment] 2015-12-17 23:53
The Solaris killall completion should just be "DON'T DO THIS". Freakin' SysV.

**Comment by faho** [comment] 2015-12-18 00:19
@zanchey: Yeah, I've read about that. I thought I'd leave it as a joke. No, sorry, just kidding! How would we detect Solaris killall? I'd rather not do `uname`, but more of a feature-ish test.

**Comment by zanchey** [comment] 2015-12-19 02:51
There's no way to run `killall` safely, so `uname` might be your best bet.
