### ISSUE TITLE
fish doesn't recognize url as parameter of youtube dl

### ISSUE THREAD

**Issue by JosephEdselBonilla** [fish-shell/fish-shell#2750] opened 2016-02-21 13:11 UTC
http://imgur.com/zxgFpHO

**Comment by faho** [comment] 2016-02-21 13:14
This is a duplicate of #967.

The issue is that "?" is a single-character glob, so fish tries to match files in the local directory. The workaround is to quote the parameter - I always do `youtube-dl "` then press Ctrl-v, enter the second quote and then execute it.

**Closed by faho** 2016-02-21 13:14 UTC

**Comment by pickfire** [comment] 2016-02-21 13:31
@JosephEdselBonilla remember to quote things that have `?` with either `'` or `"`.

**Comment by Librebowski** [comment] 2020-01-12 23:10
Put the url in " "s like the other guys said. works great.
