### ISSUE TITLE
Very long command

### ISSUE THREAD

**Issue by adeftu** [fish-shell/fish-shell#9427] opened 2022-12-23 16:47 UTC
> Please tell us which fish version you are using by executing the following:

```shell
$ fish --version
fish, version 3.5.1
```

> Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

macOS 12.6.1

```shell
$ uname -a
Darwin QJXT4YRW6D 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64

$ echo $TERM
xterm-256color
```

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior > you are reporting:
>
>  sh -c 'env HOME=$(mktemp -d) fish'

Yes, same issue.

> Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

Pasting a very long string messes up the terminal and renders it unusable, but works fine in zsh. See video below:

https://user-images.githubusercontent.com/13695993/209370899-b3f432c8-7c4c-4a0a-8bb7-356a3b239d79.mp4

**Comment by faho** [comment] 2022-12-23 17:11
Duplicate of #7296

**Closed by faho** 2022-12-23 17:11 UTC
