### ISSUE TITLE
A key or a keyboard shortcut to expand variables

### ISSUE THREAD

**Issue by jsx97** [fish-shell/fish-shell#10658] opened 2024-08-09 20:10 UTC
fish 3.7.1, macOS Sonoma 14.5 (Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64).

In Zsh, I can expand variables using the Tab key. That is, I can type `cd $PWD`, press Tab, the variable will be expanded to something like `/Users/john/foo/bar`, and then I can edit it to something like, e.g., `/Users/john/fooz/booz`.

I don't see this works in fish. Neither the Tab nor the Right Arrow keys expand variables. I asked on Reddit and on Unix & Linux Stack Exchange, and there is silence, hence I have supposed there is no such a feature in fish. I would be happy it will be added.

**Comment by faho** [comment] 2024-08-09 20:25
Duplicate of #751

**Closed by faho** 2024-08-09 20:25 UTC

**Comment by mattmc3** [comment] 2024-08-09 20:40
See https://stackoverflow.com/questions/50279388/how-to-expand-environment-variables-using-keyboard-shortcut-in-fish
