### ISSUE TITLE
Fish should expand abbreviations after an `env` command

### ISSUE THREAD

**Issue by zubin** [fish-shell/fish-shell#10469] opened 2024-04-29 19:13 UTC
```sh
$ fish --version
fish, version 3.7.0

$ uname -a # macos
Darwin z2z.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64
```

When prefixing a command with `env` (eg `env foo=bar`), abbreviations should still expand. 

Example:

```sh
abbr foo foobar
foo<space> # expands to foobar
env foo=bar foo<space> # should expand but doesn't

abbr --erase foo # remove test abbr
```

There is a workaround – type the command first before inserting `env ...` – but it'd be better not to have to do that.

**Comment by faho** [comment] 2024-04-29 19:47
It shouldn't - `env` isn't syntactically special, and that's a good property to have. That's because `env` is just a binary on your system and it may or may not do what you want. Fish has no control over it.

Good news is you can, in the upcoming release, make abbreviations for `env` and in command position:

```fish
abbr --command={env,} foo foobar
```

So I'll be closing this as a duplicate of #9411

**Closed by faho** 2024-04-29 19:47 UTC

**Comment by krobelus** [comment] 2024-04-29 20:56
I think `env foo<space>` should expand an abbrevation. I don't think "is in command position" is the ideal criteria but rather "is this supposed to be a shell command".
Of course this is a never-ending effort but in this case we have the information (abbrevations are suggested as completions)

**Comment by zubin** [comment] 2024-04-29 22:46
> I think `env foo<space>` should expand an abbrevation. I don't think "is in command position" is the ideal criteria but rather "is this supposed to be a shell command". Of course this is a never-ending effort but in this case we have the information (abbrevations are suggested as completions)

I'm inclined to agree: while the `abbr --command={env,} foo foobar` approach will work, it feels wrong to classify a regular command as a subcommand to `env` to make abbreviations work. Also it will be somewhat awkward to use that syntax when defining _every_ abbreviation.

**Comment by tmccombs** [comment] 2025-01-04 07:19
I think this is slightly different than #9411.  #9411 is "I want to have abbreviations that only expand as part of some command", which is cool, and I'm happy that is happening. But this is more "for some commands, I want to specify that there is an additional 'command position' for certain commands". 

This has been discussed before in https://github.com/fish-shell/fish-shell/pull/6891 and https://github.com/fish-shell/fish-shell/issues/5003. 

I think that the bash/zsh solution of an alias with a trailing space means that the next token can also be expanded is hacky and brittle. 

But I also think it would be nice to be able to use all of my abbreviations with things like sudo/runas/pkexec/run0, systemd-run, `mise exec`, `uv run`, etc. 

It would *also* be nice if it could work for things like ssh, and `docker exec`, which the bash/zsh solution can't handle, because the alias/abbr would need to be expanded after other non-command arguments. 

One possibility is to tie it in to the completion system somehow, but that feels kind of icky to me too. 

A straightforward solution could be some command that allows you to specify that if the current command starts with a certain token, or matches a certain regex, then command abbreviations should be treated as global. But I'm still not sure that's the best solution.

Or a variant of that could be a special variable that is a list of commands, and `abbr [--postion=command] foo foobar` is equivalent to `abbr --command=$fish_abbr_expanding_commands --command= foo foobar`, maybe with some way to opt out of that. I suppose that could even be done with a fish function...

At the end of the day, I'm not sure what the best design for this would be, and I'm not even sure it would be worth the complexity to add it, but wanted to say that I think a better design for this than exists in bash/zsh probably is possible.

Thanks for fish.

**Comment by zubin** [comment] 2025-01-07 01:42
@tmccombs Thanks for the context and for your considered response. Apologies in advance if my naive suggestion doesn't make sense! 

I'm not sure if this is one of the ideas you were suggesting but maybe it could be configurable something like this:

```fish
# $fish_global_command_prefixes may contain some sensible defaults, or be empty
# user can add their own
set -a fish_global_command_prefixes \
  "bundle exec" \
  "aws-vault exec"
```

When preceding args match that variable, the abbreviation expander would reset command depth to zero in order for abbreviations to be triggered. 

Not sure how the original `env [...]` use case would work though, since there can be any number of arguments to `env` before a command abbreviation.
