### ISSUE TITLE
`set --path` / `--unpath` are undocumented

### ISSUE THREAD

**Issue by lexi-lambda** [fish-shell/fish-shell#6169] opened 2019-10-05 08:34 UTC
The `--path` and `--unpath` options added to `set` in #5245 are very useful, but they have not made their way into the documentation for `set`.

Also, the behavior that all variables ending in `PATH` are automatically made “PATH-like” explicitly conflicts with the following paragraph in the tutorial:

> Note that there are three environment variables that are automatically split on colons to become lists when fish starts running: `PATH`, `CDPATH`, `MANPATH`. Conversely, they are joined on colons when exported to subcommands. All other environment variables (e.g., `LD_LIBRARY_PATH`) which have similar semantics are treated as simple strings.

**Comment by faho** [comment] 2019-10-06 13:35
Duplicate of #5741

**Closed by faho** 2019-10-06 13:35 UTC

**Comment by lexi-lambda** [comment] 2019-10-06 13:36
Thanks! Somehow I missed both that issue and didn’t see the updated docs in the current code. Sorry for the noise.
