### ISSUE TITLE
echo >file writes one character at a time

### ISSUE THREAD

**Issue by yump** [fish-shell/fish-shell#7979] opened 2021-05-07 04:20 UTC
Fish version: 3.2.1
OS: Linux, Fedora 33

# How to reproduce: 

```
sh -c 'env HOME=$(mktemp -d) strace -ewrite fish -c "echo 123 >/tmp/file"'
```

What I expected:

```
write(4, "123\n", 4)                    = 4
```

What happens:

```
write(4, "1", 1)                        = 1
write(4, "2", 1)                        = 1
write(4, "3", 1)                        = 1
write(4, "\n", 1)                       = 1
```

# Why is this a problem?

Various linux kernel `/sys` interfaces (`/sys/class/hwmon/*/pwm*`, `/sys/block/sd*/queue/scheduler`, `/proc/sys/vm/*`, etc.) require that parameters be written in a single syscall.  Otherwise funny things happen.  For example:

```
# echo 123 >/proc/sys/vm/swappiness
# cat /proc/sys/vm/swappiness 
1
```

Less importantly, there are likely performance implications of using more syscalls than necessary, especially with spectre mitigations active.

**Comment by faho** [comment] 2021-05-07 04:23
Duplicate of #7836

**Closed by faho** 2021-05-07 04:23 UTC

**Comment by faho** [comment] 2021-05-07 04:25
Just like #7978. Please check the closed issues next time.
