### ISSUE TITLE
No autocompletion while changing to the parent directory

### ISSUE THREAD

**Issue by ktklin** [fish-shell/fish-shell#9510] opened 2023-01-26 21:46 UTC
After upgrading to version 3.6.0 on MacOS 13.1 i experienced that the autocompletion for changing to the parent directory via
`cd ..` does not work anymore. 

Downgrading to version 3.5.1 i could verify that it works fine there.

Is that intended behaviour?

**Comment by faho** [comment] 2023-01-26 21:50
Duplicate of #9477

**Closed by faho** 2023-01-26 21:50 UTC
