### ISSUE TITLE
Make fish compatible with Tor as default browser

### ISSUE THREAD

**Issue by jkabrg** [fish-shell/fish-shell#2814] opened 2016-03-11 23:13 UTC
Is it possible to add an override_browser option into the config so you can explicitly say to use chrome?

**Comment by krader1961** [comment] 2016-03-11 23:25
Fish uses the python [webbrowser](https://docs.python.org/2/library/webbrowser.html) class to interface with your browser. You should be able to set the **BROWSER** environment var to override the default browser. Does that do what you want?

**Comment by krader1961** [comment] 2016-03-11 23:26
Also, you'll find this documented in `man fish_config` although I admit an example would be helpful.

**Comment by floam** [comment] 2016-03-11 23:33
Look at webbrowser.py at how it's implemented. At least on a Mac with Apple-included built-in python2.7, good luck. I think Python3.3 or greater may work with a BROWSER path.

**Comment by floam** [comment] 2016-03-11 23:48
It should use your default browser set in OS X though. I can't try any of this on account of having left my Mac at home and being surrounded by PCs at the moment.

**Comment by jkabrg** [comment] 2016-03-12 00:08
The aim is *not* to use the default browser.

**Comment by jkabrg** [comment] 2016-03-12 00:09
The aim is to override the default browser because it's Tor browser and Tor
browser doesn't do localhost.

**Comment by floam** [comment] 2016-03-12 00:22
Firefox may work. It's the only thing they let slow. Install firefox and make sure it's been launched once so it's in the LaunchServices cache, (so ie. "open firefox" at the terminal would work), and it looks like it will try some some applescript through the python bindings.

set -xg BROWSER "/Applications/Firefox.app/Contents/MacOS/firefox %s"; fish_config

**Comment by floam** [comment] 2016-03-13 05:12
```
floam@AaronBook ~> set -xg BROWSER "/Applications/Firefox.app/Contents/MacOS/firefox"; fish_config
Traceback (most recent call last):
  File "/usr/local/Cellar/fish/HEAD/share/fish/tools/web_config/webconfig.py", line 32, in <module>
    import webbrowser
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 669, in <module>
    cmd = _synthesize(cmdline, -1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 94, in _synthesize
    if controller and name.lower() == controller.basename:
AttributeError: 'MacOSXOSAScript' object has no attribute 'basename'
```
Doesn't work, the feature [is broken](https://bugs.python.org/issue24955).

**Comment by pickfire** [comment] 2016-03-13 14:05
I would like to use another browser when using `fish_config`:
```fish
env BROWSER='firefox' fish_config
```
It doesn't work. Instead everytime I need to copy the url from `surf` browser to `firefox`.

I really hope that fish can play nice with tor browser, I use tor but I don't use tor browser, I use it with firefox. (rpi limit)

**Comment by faho** [comment] 2016-03-13 14:19
@pickfire: `fish_config` is a function that executes webconfig.py, which is not in PATH. So calling the external `env` won't work. Do `set -gx BROWSER firefox; fish_config`. If you want, you can `funced fish_config` and add it there.

**Comment by faho** [comment] 2016-03-13 14:33
Note that the "-gx" is both necessary (because functions don't receive local-but-exported variables) and annoying (because it will change the value outside).

**Comment by bucaran** [comment] 2016-03-13 14:42
@faho 

> Though you could replace the eval in fish_config with env BROWSER=firefox.

Does not work for me?

**Comment by faho** [comment] 2016-03-13 14:44
@bucaran: Works for me. It's possible your `env` behaves differently from mine.

To be clear, this is the fish_config I'm testing:

```fish
function fish_config --description Launch\ fish\'s\ web\ based\ configuration
	# Support passing an initial tab like "colors" or "functions"
	set -l initial_tab
	if count $argv >/dev/null
		set initial_tab $argv[1]
	end
	env BROWSER=firefox $__fish_datadir/tools/web_config/webconfig.py $initial_tab
end
```

And then `set -gx BROWSER w3m; fish_config` will still launch firefox.

**Comment by floam** [comment] 2016-03-13 14:46
Won't work if he's on Mac and using python 2.7. I don't know what he has. But the webbrowser module is both super inflexible and also super broke as far as the support for setting the browser from the environment goes.

**Comment by bucaran** [comment] 2016-03-13 14:46
Thanks @floam

Is there anything that will just make it work?

**Comment by faho** [comment] 2016-03-13 14:49
@bucaran: I presume changing the shebang to python3 in $__fish_datadir/tools/web_config/webconfig.py might work.

**Comment by faho** [comment] 2016-03-13 14:50
See also #2655 - would it be okay to default to python3 on OSX to work around this?

**Comment by floam** [comment] 2016-03-13 14:50
You can edit the webapp python directly and have it just use webbrowser.Chrome or webbrowser.firefox instead of webbrowser.

**Comment by pickfire** [comment] 2016-03-13 14:50
@faho, but it might be bad if someone doesn't have firefox installed. Probably it can get the `ENV` we just gave it.

**Comment by floam** [comment] 2016-03-13 14:50
>See also #2655 - would it be okay to default to python3 on OSX to work around this?

Sure when Apple starts shipping Python 3 with OS X. :(

**Comment by floam** [comment] 2016-03-13 14:51
But if the fish function could check for python3 and use it if it exists that would be very nice.

**Comment by floam** [comment] 2016-03-13 14:56
(Also [https://bugs.python.org/issue24955](the bug I linked to) - I just noticed that it was reported on 3.3 and 3.5 also. And I guess that bug is still not fixed. So even that won't fix it I guess. Guh.

**Comment by faho** [comment] 2016-03-13 14:57
@pickfire: The idea was that that's your local customization, so just pick a browser there that's nice for you. I'd like that better than adding another weird variable.

>I just noticed that it was reported on 3.3 and 3.5 also. And I guess that bug is still not fixed. So even that won't fix it I guess. Guh.

Urgh. So in other words: On OSX, the issue is upstream. On other systems, use $BROWSER.

**Comment by pickfire** [comment] 2016-03-14 13:59
@faho, I use a nice browser, I just don't like firefox, it is too slow. But my browser can't open that `fish_config` page.

I really hope that fish can be more flexible.

**Comment by krader1961** [comment] 2016-03-24 23:11
Sorry, @jkabrg, but I can't get the **BROWSER** var to work on OS X. This isn't, technically, a fish bug. It's a bug in a python module we depend on to work as advertised. The only way I could get this to work was launch Safari or Chrome and make one of them the default browser for as long as I need to run `fish_config`. If that isn't an acceptable workaround you'll need to lobby to have the python module fixed. Many of us would be happy to add a "me too" if you do open an issue with that project.

**Closed by krader1961** 2016-03-24 23:11 UTC
Labels: question

**Comment by floam** [comment] 2016-03-24 23:15
Fish can grab the BROWSER variable in the fish_config script and pass it as an argument on to the actual python webapp, which can check for/fix the bug or pick a browser in the python script through another means. 

Otherwise the feature may remain broken for years for folks.

**Comment by krader1961** [comment] 2016-03-24 23:24
I'm not grokking your proposed fix, @floam, but if you've got an idea of how to make this work I'd be happy to review and test a pull-request. Even monkey-patching the webbrowser.py module after it's imported might be acceptable if it can be done in a manner guaranteed not to break any existing, correct, behavior.

**Comment by floam** [comment] 2016-03-24 23:36
My suggestion was basically monkey patch it (or something) plus I prescribed that interpreting BROWSER and picking a browser should take place in fish code before the webapp is called. I think it ought to just unset BROWSER after it's made a choice. This is so that we can actually tell the users what they should set BROWSER to in order to have that browser opened. As it is there's a mishmash of conventions supported on different platforms by webbrowser that I don't think are very intuitive or reasonable, and fish right now is also nullifying certain choices if you had picked a text browser. It'd be nice if we could do something pleasant, documented, unsurprising, and also if easily altered with funced.
