### ISSUE TITLE
Fish 2.3 string function error

### ISSUE THREAD

**Issue by darakian** [fish-shell/fish-shell#3141] opened 2016-06-14 02:11 UTC
Hey all. I've got a mostly standard fedora 23 install. After updating to Fish 2.3 I'm getting the following after every use of the command line. ex. doing the command uname -a gives

jon@localhost > uname -a
Linux localhost.localdomain 4.4.8-300.fc23.x86_64 #1 SMP Wed Apr 20 16:59:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
fish: string: command not found...
/usr/share/fish/functions/prompt_pwd.fish (line 1): string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
                                                    ^
in command substitution
	called on line 0 of file /usr/share/fish/functions/prompt_pwd.fish

in function “prompt_pwd”
	called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

fish: string: command not found...
/usr/share/fish/functions/prompt_pwd.fish (line 18): 		string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' $tmp
                                                     		^
in function “prompt_pwd”
	called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

jon@localhost >

**Comment by floam** [comment] 2016-06-14 02:14
It looks like you have fish 2.3 only partially installed. What does 'fish --version' output? 'type -a fish's?

On Mon, Jun 13, 2016 at 7:11 PM Jon Moroney

<
mailto:Jon Moroney <notifications@github.com>
> wrote:

Hey all. I've got a mostly standard fedora 23 install. After updating to Fish 2.3 I'm getting the following after every use of the command line. ex. doing the command uname -a gives

jon@localhost > uname -a

Linux localhost.localdomain 4.4.8-300.fc23.x86_64
https://github.com/fish-shell/fish-shell/issues/1
SMP Wed Apr 20 16:59:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

fish: string: command not found...

/usr/share/fish/functions/prompt_pwd.fish (line 1): string replace -r '^'"$realhome"'($|/)' '~$1' $PWD

^

in command substitution

called on line 0 of file /usr/share/fish/functions/prompt_pwd.fish

in function “prompt_pwd”

called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution

called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”

called on standard input

in command substitution

called on standard input

fish: string: command not found...

/usr/share/fish/functions/prompt_pwd.fish (line 18): string replace -ar '(.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' $tmp

^

in function “prompt_pwd”

called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution

called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”

called on standard input

in command substitution

called on standard input

jon@localhost >

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/fish-shell/fish-shell/issues/3141
, or
https://github.com/notifications/unsubscribe/AARxRg6KWiD67ARLDlxCFjsa9TZqLtnjks5qLg3LgaJpZM4I05iK
.

https://github.com/fish-shell/fish-shell/issues/3141

**Comment by darakian** [comment] 2016-06-14 02:19
jon@localhost > fish --version
fish, version 2.3.0
fish: string: command not found...
/usr/share/fish/functions/prompt_pwd.fish (line 1): string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
                                                    ^
in command substitution
	called on line 0 of file /usr/share/fish/functions/prompt_pwd.fish

in function “prompt_pwd”
	called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

fish: string: command not found...
/usr/share/fish/functions/prompt_pwd.fish (line 18): 		string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' $tmp
                                                     		^
in function “prompt_pwd”
	called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

jon@localhost > 

----------------------------------------------------------------------------------------------------------------
and 
----------------------------------------------------------------------------------------------------------------
jon@localhost > type -a fish
fish is /usr/bin/fish
fish: string: command not found...
/usr/share/fish/functions/prompt_pwd.fish (line 1): string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
                                                    ^
in command substitution
	called on line 0 of file /usr/share/fish/functions/prompt_pwd.fish

in function “prompt_pwd”
	called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

fish: string: command not found...
/usr/share/fish/functions/prompt_pwd.fish (line 18): 		string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' $tmp
                                                     		^
in function “prompt_pwd”
	called on line 6 of file /usr/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/share/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

jon@localhost >

**Comment by darakian** [comment] 2016-06-14 02:19
I've also done a reinstall through the package manager and still have the same issue.

**Comment by krader1961** [comment] 2016-06-14 02:26
The shell instance you're running is pre 2.3.0. You need to `exec fish` or close your terminal and open a new one.

**Comment by floam** [comment] 2016-06-14 02:27
echo $FISH_VERSION

**Comment by krader1961** [comment] 2016-06-14 02:28
The problem is that fish notices the fish script file has changed and reloads it. Since you've installed new fish scripts that use the new `string` builtin your current shell (probably version 2.2.x) tries to find that command and can't.

**Comment by floam** [comment] 2016-06-14 02:34
I wonder if the new scripts should include a simple check for a pre-string fish executing them, and have them bail or alert the user.

**Comment by krader1961** [comment] 2016-06-14 02:41
> I wonder if the new scripts should include a simple check for an older fish running them...

It would be better to just add the check to the global *config.fish* script. Not saying that is a good idea but it's preferable to doing the check in every single script that uses the new `string` builtin. The challenge is doing something useful that isn't easily ignored or more of an annoyance than the problem we're trying to solve.

**Comment by floam** [comment] 2016-06-14 02:47
I am perhaps just partial to having `prompt_pwd` fallback to outputting an unprettified path and the default prompt falling back to some dumb (but not broken) prompt on any error.

**Comment by floam** [comment] 2016-06-14 02:52
(I don't consider checking exit codes and handling surprises gracefully that much of an annoyance - it seems probable doing such things in our core scripts can avoid untold other mystery issues at some point down the road.)

**Comment by krader1961** [comment] 2016-06-14 03:49
I agree that checking for failures (whether it's checking the exit code or something else) is a best practice where such failures are not improbable. I disagree that checking whether the string builtin exists in every script it is used is a good idea. Why not add checks for any other builtin that hasn't existed since the first public release just in case some user is upgrading from a really old version? That doesn't scale and leads to scripts that are needlessly complicated, expensive to run, and hard to read.

Upon reflection I see that my idea to add the check for a missing builtin to the global *config.fish* does not help in this situation as that file won't be read again by an old shell instance. Too, adding such a check to the default fish_prompt function doesn't help users who have a custom, private, version of that function. I don't see any good solutions to this issue.

Note that other shells are also susceptible to this failure mode. Consider installing a new version of bash or zsh that adds a feature used by a script installed by the upgrade. And you haven't already run that script so it isn't cached. When you run that script in the older version of the shell you'll see similar failures. The only reason fish users are more likely to see this is because of its aggressive reloading of scripts when the underlying file has changed. But the core problem is not unique to fish.

**Comment by floam** [comment] 2016-06-14 03:52
Above commit fixes both 2.2.0 running when the scripts change, and also launching a 2.2.0 instance with 2.3.0 scripts. At least, no annoying errors are caused upon prompt print and cd'ign around.

**Comment by faho** [comment] 2016-06-14 09:47
This same question has already been asked in #3125 and #3057, so strictly speaking this would be a duplicate.

It's probably stumped enough people that we'd want to do something about it, though.

**Comment by krader1961** [comment] 2016-06-15 05:08
Closing this in favor of continuing the discussion, and committing a fix, in issue #3057.

**Closed by krader1961** 2016-06-15 05:08 UTC
Labels: question
