### ISSUE TITLE
Followup to #6270: Tab completions slow again on Big Sur

### ISSUE THREAD

**Issue by jspiro** [fish-shell/fish-shell#7524] opened 2020-12-02 01:15 UTC
I've found for a while that some commands are randomly slow to auto-complete. `ter<tab>` in particular, for terraform, on my machine. It takes two full seconds, so long that I can see it's stuck on `makewhatis` when I watch processes. That led me to #6270, which is now locked, hence new issue :-(

This issue became particularly bad after I installed `asdf` using brew, and installed it in `fish`. I found the workaround in that other issue (`funced __fish_describe_command`) instantly fixes this for me–I've never seen tab completions run so fast, and I want to keep the workaround as a result.

What am I giving up if I keep it–just the descriptions of the utilities? Seems a small price to pay for getting 2 seconds back every time I use a tab completion.

```
fish, version 3.1.2
Darwin OSX-0640.localdomain 20.2.0 Darwin Kernel Version 20.2.0: Tue Nov 10 21:14:14 PST 2020; root:xnu-7195.60.70.111.1~1/RELEASE_X86_64 x86_64
xterm-256color
```

Using iTerm's latest beta, and Big Sur 11.1 Beta (20C5048k). I've tested it with plugins disabled, same issue.

Maybe it's something on my machine, maybe not. I thought I'd reopen this in case others encounter the issue. It seems like perhaps the underlying system for grabbing descriptions should be revisited. Could they stream in after the tab completion list is produced?

**Comment by faho** [comment] 2020-12-02 04:58
Duplicate of #7511

**Comment by faho** [comment] 2020-12-02 04:59
(fixed by #7365)

**Closed by faho** 2020-12-02 04:58 UTC

**Comment by faho** [comment] 2020-12-02 06:10
> What am I giving up if I keep it–just the descriptions of the utilities?

Correct. Previously we did that automatically, then we disabled that because it seemed fixed, now it seems it has regressed. #7365 adds some caching there and doesn't have a version check so it'll presumably just be used on macOS permanently.

**Comment by jspiro** [comment] 2020-12-02 06:31
@faho You're a rockstar, good idea re caching. I swear I searched for both the function name, and separately for the word "slow" and didn't find either that PR or other issue. Doh!

I'm looking forward to the next release!
