### ISSUE TITLE
Arrow Keys Are Completely Broken

### ISSUE THREAD

**Issue by flip4bytes** [fish-shell/fish-shell#2035] opened 2015-04-21 02:54 UTC
For some reason, when I do arrow keys, fish shell interprets it as `newline + "[A"` / `newline "[B"` / `newline "[C"` / `newline "[D"`:

![](http://i.imgur.com/ENGzkiA.jpg)

It makes command line completely unusable for keyboards that have the arrow keys and delete key mapped as a function key.

**Comment by zanchey** [comment] 2015-04-21 03:45
It would be useful to know what terminal you are running (e.g. Xterm) and which version of fish you are using. Fish takes pains to ensure that the escape characters you are seeing work, so I suspect the problem is that the terminal is sending something different than expected.

You could try running something like `xxd` or `cat`, then typing the arrow keys, to get a sense for what the raw output is. Pasting that information here might allow us to help further.

**Comment by flip4bytes** [comment] 2015-04-21 03:50
@zanchey I am using cygwin (within ConEmu) and managed to find this issue thread which shows the exact same problem as I'm describing:

https://github.com/fish-shell/fish-shell/issues/1160

**Comment by zanchey** [comment] 2015-04-21 04:00
Ah, ConEmu is a whole new ball game.

I will close this as a duplicate of #1160 and we can track there.

**Closed by zanchey** 2015-04-21 04:00 UTC
Labels: duplicate

**Comment by flip4bytes** [comment] 2015-04-21 04:02
@zanchey Appreciate it, and yeah, sorry about that. I was searching for solutions for like 3 hours and I have about 50 tabs open and and then literally 3 minutes after you replied, I managed to find the #1160 thread right before I completely gave up.
