### ISSUE TITLE
sudo: !!: command not found in Fish

### ISSUE THREAD

**Issue by vipulgupta2048** [fish-shell/fish-shell#4983] opened 2018-05-14 10:34 UTC
Outputs that were needed for more information:
fish --version: fish, version 2.7.1
uname -a: Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux [Actually its Xubuntu 16.04]
$TERM: xterm

Hi, I was trying out a tweet I read. 
_If you forget to write `sudo` with the command you just wrote, type `sudo !!` in the terminal and save time typing the command again._

I tried it out in Fish, but the out was
`sudo: !!: command not found`
I tried adding the same through a hacky method in config.fish but it isn't working. Any ideas that you might have? and Why such a heavenly command is not there in Fish from the get-go.

**Comment by faho** [comment] 2018-05-14 11:03
Duplicate of #288.

See https://github.com/fish-shell/fish-shell/wiki/Bash-Style-Command-Substitution-and-Chaining-(!!-!$-&&-%7C%7C) for a way to add it.

**Closed by faho** 2018-05-14 11:03 UTC
