### ISSUE TITLE
`commandline -f` ops reordered with respect to other commandline operations

### ISSUE THREAD

**Issue by laughedelic** [fish-shell/fish-shell#3031] opened 2016-05-15 23:27 UTC
I observe strange behaviour regarding the execution order of `commandline` calls _with_ `-f` option and _without_.

Example: I define the following function and bind it to a <kbd>ctrl</kbd><kbd>s</kbd>:

``` fish
function __surround
    commandline -f backward-kill-path-component
    commandline -i '"'
    commandline -f yank
    commandline -a '"'
end

bind \cs '__surround'
```

(in my `fish_user_key_bindings.fish`)

What happens instead:
- cut + paste (those with `-f`)
- insert + append

Here is a demo: [asciicast](https://asciinema.org/a/45721)

This is just a simplified example, I have encountered this behaviour in more situations and if this is not enough, I can provide more examples. 

---
- Fish version: `fish, version 2.3b2` (`homebrew install --devel fish`)
- Operating system: OS X El Capitan
- Terminal emulator: iTerm2

**Comment by krader1961** [comment] 2016-05-16 01:06
That's because `commandline -f` pushes the function into the reader input queue. Those functions aren't actually executed until your function returns and the input reader runs again. The `commandline -i` and `commandline -a` on the other hand immediately modify the buffer. This causes the operations to be reordered as you noticed. This is not intuitive and quite annoying. I could have sworn there was an open issue discussing this but I can't find it.

This behavior is technically not a bug since fish is working as intended. Nonetheless, I think the behavior should be changed. Relabeling this an enhancement since I can't find the issue I thought was already open to change this behavior.

**Comment by laughedelic** [comment] 2016-05-16 23:14
@krader1961 thanks for the explanation. Now I see, that `-i`/`-a` commands get actually executed first. Is there any way to overcome this? Or better just not to mix `-f` options with other ones?

Probably this closed issue is related: https://github.com/fish-shell/fish-shell/issues/1567

**Comment by krader1961** [comment] 2016-05-17 01:01
> Is there any way to overcome this?

Not that I'm aware of without changing the core code. It's not a general solution but for the example you gave in the original problem statement simply fetch the command line (`commandline`), mutate it however you want, then replace the command line with your mutated version (`commandline -r`).

**Comment by laughedelic** [comment] 2016-05-17 22:08
> fetch the command line (commandline), mutate it however you want, then replace

That's what I was doing so far. I just thought that it might be not effective.

**Comment by zanchey** [comment] 2016-05-20 21:07
See #1567.

**Comment by laughedelic** [comment] 2016-05-20 22:32
@zanchey do you mean something in particular? I referenced this issue in another comment, but it doesn't help much.

**Comment by faho** [comment] 2016-05-20 22:43
@laughedelic: That changed it from a stack (which would mean all your stuff is interpreted in reverse) to a queue.

That was another notable time this behavior was touched, so it's important for any further changes (so as not to regress, etc). The comment wasn't for you in particular.

**Comment by zx8** [comment] 2019-07-08 19:26
Sorry to dig up an ancient issue, but I've just been hit by this again in https://github.com/fish-shell/fish-shell/issues/5979#issuecomment-509190747 and was wondering if any of the recent work @ridiculousfish is doing around parsers/threading will affect this at all, or perhaps make it easier to implement in future?

I'm sure there's a good reason `commandline -f` is currently the way it is, but the current behaviour is very unintuitive and often stills surprises me when writing scripts (and I consider myself a _relatively_ seasoned fish user).

As programmers, unless some sort of special syntax is involved, we're used to things being executed sequentially in scripting languages, and often taking effect immediately, which makes this particular nuance all the more surprising.

Is it safe to assume that since this issue is still open that there's intent to change (/fix) this one day?

**Comment by ridiculousfish** [comment] 2019-07-16 01:57
No this won't be affected by any threading changes.

We're certainly open to a fix for this.

**Comment by krobelus** [comment] 2024-11-14 11:31
this is fixed

**Closed by krobelus** 2024-11-14 11:31 UTC
Labels: enhancement
