### ISSUE TITLE
Newlines added when input is more than 74 lines

### ISSUE THREAD

**Issue by laserscout** [fish-shell/fish-shell#9860] opened 2023-06-23 08:46 UTC
fish, version 3.6.1
macOS 13.4, Darwin Kernel Version 22.5.0, xterm-256color

Running a shell with: `sh -c 'env HOME=$(mktemp -d) fish'`

I have been having this issue for quite some time but didn't try to investigate it since it only affects me when pasting long text. But I have boiled it down to the following:

When interactively more than 74 lines are input the shell, they are displayed in a mangled way with newlines and white characters added.
[![proof](https://asciinema.org/a/592854.svg)](https://asciinema.org/a/592854)

The same happens with other multi-line input like
```
echo 'foo' \|
head \|
head \|
...
```

This behavior is not present on `bash` or `zsh` using the same terminal emulator `terminal` and the same behavior _is_ present when running `fish` in another terminal emulator like `iTerm`

And... now that I checked, the same happens in a fresh `fish` installation in `fish, version 3.3.1` `Linux 5.15.0-1028-raspi #30-Ubuntu SMP PREEMPT Thu Apr 20 01:21:34 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by laserscout** [comment] 2023-06-23 08:57
update:
Why **74**?
Because my terminal emulator window is **272x74**

**Comment by faho** [comment] 2023-06-23 09:02
Duplicate of #7296

**Closed by faho** 2023-06-23 09:02 UTC
