### ISSUE TITLE
Vim Problem

### ISSUE THREAD

**Issue by OmidHdr** [fish-shell/fish-shell#10821] opened 2024-10-30 04:16 UTC
fish, version 3.7.0
I use Fedora and kitty terminal 

uname -a 
Linux fedora 6.10.12-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 30 21:38:25 UTC 2024 x86_64 GNU/Linux

echo $TERM
tmux-256color

I add this into my fish config to use vim keys

fish_vi_key_bindings

I can use only (i,I,a,A,b,e,w) but the problem is number dosen't working in this case
for example (5b , 6e, 3w)

**Comment by faho** [comment] 2024-10-30 06:10
Duplicate of #2192

**Closed by faho** 2024-10-30 06:10 UTC
