### ISSUE TITLE
"cd ." does not work on deleted and recreated directories (as in other shells like bash)

### ISSUE THREAD

**Issue by kwarnke70** [fish-shell/fish-shell#5355] opened 2018-11-19 16:26 UTC
$ fish --version                                                                                                                                                                                
fish, version 2.7.1

While developing and building sometimes a whole directory tree is deleted and rebuild.
If I stay with fish in this directory I have to explicit cd into again with full path.
Other shells, like bash, allow just use "cd ." to be here again.

Working example with wanted behavior with bash:
root@ub18:/tmp# mkdir del.me
root@ub18:/tmp# cd del.me/
root@ub18:/tmp/del.me# rmdir /tmp/del.me 
root@ub18:/tmp/del.me# mkdir /tmp/del.me                                                                                                                                                        
root@ub18:/tmp/del.me# cd .
root@ub18:/tmp/del.me# pwd
/tmp/del.me

Error message:
root@ub18:~/NetBeansProjects/awplug/karaf/target/assembly · (master~)
$ cd .                                                                                                                                                                                          
<E> fish: getcwd() schlug mit errno 2/No such file or directory fehl
<E> fish: Could not determine current working directory. Is your locale set correctly?
cd: Konnte PWD-Variable nicht setzen
<E> fish: getcwd() schlug mit errno 2/No such file or directory fehl

**Comment by faho** [comment] 2018-11-19 16:32
Duplicate of #4543

**Closed by faho** 2018-11-19 16:32 UTC
