### ISSUE TITLE
Child fish instances conflate `PATH`, global `fish_user_paths`, and universal `fish_user_paths`

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5488] opened 2019-01-05 22:51 UTC
The root cause behind #5456 is that child `fish` instances are started up with an exported `PATH` that is calculated via the original `PATH`, the current `fish_user_paths` if shadowed in the global scope, and the saved `fish_user_paths` universal value.

This leads to incorrect results when launching child fish instances. Here is one such example:

```fish
mqudsi@ZBOOK /m/c/U/mqudsi> env PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin HOME=(mktemp -d) fish
Welcome to fish, the friendly interactive shell
mqudsi@ZBOOK /m/c/U/mqudsi> set -U fish_user_paths /foo1 /foo2
mqudsi@ZBOOK /m/c/U/mqudsi> echo $PATH | string replace -a ' /' \n/
/foo1
/foo2
/usr/local/bin
/usr/bin
/bin
mqudsi@ZBOOK /m/c/U/mqudsi> set -g fish_user_paths /foo0 $fish_user_paths
mqudsi@ZBOOK /m/c/U/mqudsi> echo $PATH | string replace -a ' /' \n/
/foo0
/foo1
/foo2
/usr/local/bin
/usr/bin
/bin

mqudsi@ZBOOK /m/c/U/mqudsi> fish
Welcome to fish, the friendly interactive shell
mqudsi@ZBOOK /m/c/U/mqudsi> echo $PATH | string replace -a ' /' \n/
/foo1
/foo2
/foo0
/usr/local/bin
/usr/bin
/bin
/sbin
/usr/sbin
```

In the parent instance, the explicit shadowing of `fish_user_paths` in the global scope took precedence over the universal `fish_user_paths` value (as it should). But when a new child instance was started, it was oblivious to the fact that the current `PATH` was comprised of a global `fish_user_paths` combined with the real `PATH`, and it treated the entire value as `PATH`. Then it applied `fish_user_paths` (from the shared universal scope) with deduplication to result in the universal `fish_user_paths` taking precedence over the global value.

This same behavior is observed if changes to `PATH` are made directly rather than via a global `fish_user_paths`, which is the behavior observed in #5456.

I'm not sure what the correct behavior here is. I am reminded of #5258, but this is a tad easier since it involves a single, well-defined variable. Perhaps there can be some means by which the parent shell instance can inform a child fish instance of the internal `PATH` state so that this does not happen (it would be sufficient to communicate the value of `fish_user_paths` at the point that `fish` was executed, respecting rules of scope).

**Comment by zanchey** [comment] 2019-01-11 14:39
Some options:
- warn on startup when there are global and universal variables with the same name (yuck)
- remove the `fish_user_paths` elements from `PATH` when starting a subprocess called fish (fragile)

This is very much a corner case though.

**Comment by mqudsi** [comment] 2019-01-12 02:06
@faho had a better solution, which was to individually skip each element in `fish_user_paths` that is already present in `PATH` when calculating `PATH` on startup, although perhaps that should be done only if `not status is-login-shell` so entries can be explicitly added to `fish_user_paths` even if they are already in `PATH` to give the priority.

**Comment by faho** [comment] 2019-03-26 11:32
Duplicate of #5488

**Closed by faho** 2019-03-26 11:32 UTC
Labels: enhancement
