### ISSUE TITLE
getopt doesn't support long options on OS X

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#514] opened 2013-01-12 22:15 UTC
/usr/bin/getopt doesn't support long options on OS X. Documented parameters like `type --no-functions` will fail.

**Comment by krader1961** [comment] 2016-09-24 03:57
This is, more or less, a duplicate of issue #478. More generally, if we don't implement a docopt style parsing facility we should at least implement a fish getopt command usable by fish functions.

**Closed by krader1961** 2016-09-24 03:57 UTC
Labels: enhancement
