### ISSUE TITLE
fish 2.3.0, failled to set locales when fish is the default login shell.

### ISSUE THREAD

**Issue by Hacksign** [fish-shell/fish-shell#3144] opened 2016-06-14 11:03 UTC
Archlinux distribution.
1. change shell to bash with `chsh` command
2. logoff, then re-login again
3. execute `locale` command. All locales are properlly set.
4. run `/usr/bin/fish`, then run `locale`, All locales are still properlly set.
5. change shell to /usr/bin/fish with `chsh` command
6. logoff, then re-login again
7. execute `locale` command, this time all locale variables is 'POSIX'

Don't know how this happend.
I just updated my system today, then this happened.
It is normal before I update my system .

**Comment by faho** [comment] 2016-06-14 12:56
This is a duplicate of #3092 (if it doesn't seem to apply, please yell).

The issue is that systemd is supposed to set locale for all services (and hence their child processes as well), but explicitly unsets locale for getty (because some locales display wrong in Linux VTs).

I've been working on a change where we'd read /etc/locale.conf (and a few other files) if we are launched with an empty locale, but I'm not completely convinced that's the right thing to do.

For now, you'll probably want to set locale in ~/.pam_environment.

**Closed by faho** 2016-06-14 12:56 UTC
