### ISSUE TITLE
Don't trust $USER

### ISSUE THREAD

**Issue by happyeggchen** [fish-shell/fish-shell#8583] opened 2021-12-25 13:05 UTC
fish, version 3.3.1 in chroot

I login with user safety(though it's unsafe at all),why fish shell think im a root user,ash and bash think im not root user

![2021-12-25 21-02-23 的螢幕擷圖](https://user-images.githubusercontent.com/38799701/147385486-3faedcf8-e250-46f3-b02c-ddf61749c22c.png)

![2021-12-25 21-04-01 的螢幕擷圖](https://user-images.githubusercontent.com/38799701/147385502-9613277f-91a5-4c99-8913-3c9e77b4b67c.png)

**Comment by faho** [comment] 2021-12-25 18:36
Fish thinks you are the root user because your uid is 0. You *are* root inside the container.

Bash simply trusts the $USER environment variable and reflects that, fish doesn't if the uid is 0.

**Comment by happyeggchen** [comment] 2021-12-27 04:42
But the user safety in container is always 1000,not 0,it was created when init a new container

**Comment by happyeggchen** [comment] 2021-12-27 04:44
When i do su safety,fish think im not root,but  if i do chroot --userspec safety:safety,fish think I'm root

**Comment by ridiculousfish** [comment] 2021-12-27 05:46
What does `whoami` and `echo $USER` print?

**Comment by faho** [comment] 2021-12-27 12:01
What happens here is that, at some point, fish runs `getuid`, and that returns 0, and then it runs `getpasswd` for that, and it tells it the name belonging to UID 0 is "root".

Even a diverging effective user id ("euid") won't help, because you can always set your effective uid to your real uid (even without special permissions).

I have no real idea what is happening here, and what exactly `chroot` is changing here. All I know is that fish asks the system which user it is, and the system insists it is root with a UID of 0.

Note that this is also broken inside bash - you can see the chosen $USER in the prompt (if you use the `\u` PS1 escape), but try to `cd ~` and it will try to `cd /root`!

>What does whoami and echo $USER print?

@ridiculousfish In both bash and fish: `whoami` will print the chosen user, $USER will be set to root.

**Comment by faho** [comment] 2021-12-27 18:24
Aaah, okay. I think I know what's happening here. I had the failure mode entirely the wrong way around!

Bash won't actually use $USER, ever, while fish will trust it when the uid isn't 0.

We do getuid(), it says some uid that's not 0, and fish then trusts $USER - because this was introduced to work around `su`s awkwardness of keeping $USER set. If it did give us 0, we would update $USER from passwd, and probably end up with "root".

One possibility here is to update $USER, always, instead of ever trusting it. We want to have $USER be meaningful, because we don't have another way of reading it (like bash's `\u` expansion in $PS1, which does *not* use $USER, apparently), and that's what your prompt is reading.

**Comment by happyeggchen** [comment] 2021-12-31 17:06
I solved that
Set user=safety
Now my script[ctcontainer](https://github.com/teahouse/ctcontainer) is good to go thx

**Comment by faho** [comment] 2022-01-01 08:24
This is *not* fixed, there is merely a workaround. The issue is that we can still inherit a wrong $USER.

I think the best thing we can do is fix $USER always instead of just when the uid is 0.

**Comment by septatrix** [comment] 2022-04-08 19:20
I think fixing USER is the wrong way because when it is changed there are usually reasons that it is that way. Also I am not sure which `su` behaviour you are referencing.

**Comment by faho** [comment] 2022-04-08 19:28
>I think fixing USER is the wrong way because when it is changed there are usually reasons that it is that way

The problem is this:

1. The reasons aren't actually any good (mostly it's "oh you can see your *original user*" which you quite possibly already knew and which is much less important than your actual current user)
2. We don't have a special "this is the user value *but for the prompt*" (because we don't do that $PS1 formatting stuff) and a separate "this is the user value for internal use to find our config file". The way to print the user in your prompt is to use $USER.

So we should, indeed, simply get the value of $USER to line up with what the user actually *is*.

>Also I am not sure which su behaviour you are referencing.

#3916 - *some* su implementations leave $USER intact in *some* cases (but not in others, like with `su -l`). It's a big hairy mess.

**Comment by septatrix** [comment] 2022-04-08 19:34
Still I think that silently manipulating the users environment can cause more confusion that it is worth. The less interfering option would be to use `id -un` in the prompt instead (though this would always require a subprocess which might not be too desirable)

**Comment by faho** [comment] 2022-04-08 19:35
If you want to do that you can do that, I'm not going to stop you.

The *default* here should be that $USER isn't entirely unrelated the the user you currently are, which nicely fixes *already existing uses*.

**Comment by septatrix** [comment] 2022-04-15 13:13
Introducing that change would be a dumpster fire on multi-user nodes where UIDs are shared due to limitations of running out (think universities and other shared clusters). This is already the case on BSD where logging in as `toor` user shows `root` as they share UID 0.

Furthermore should a shell not touch environment variables besides the obvious `SHELL`. This could have disastrous effects in programs and script when using e.g. `HOME` or `LOGNAME` (which is btw the more canonical source for the display name as opposed to `USER`). And please to not start to also set e.g. `HOME` to keep them in sync. That is simply outside of the shells responsibility.

We are trying to fix other programs legacy/compatibility behavior. There is no reason to use with `su` without `--login/-l/-` due to a plethora of other reasons apart from not setting `USER`/`LOGNAME`. Same goes for chroot which is a light wrapper around the system call and pushes this responsibility rightful to a *login manager* (the likes of `su --login`, `getty` and `sulogin` and not a shell).

The default here should be to leave the users environment as is. In my eyes the only reason against using `id -un` would be that it is not a built-in. Therefore iff you really really really want to change the behaviour to always use the user's name from `/etc/passwd` I would propose to add a new read-only fish variable `fish_logname` which could then simply call the required functions from `pwd.h`. This way the environment can stay as is and if cache is not required it would even update if the entry in the password file changes.
Though given the (in my eyes substantial) drawbacks I would advise against this.

**Comment by faho** [comment] 2022-04-15 13:31
$USER is what people *will use*, so it is the thing that should be fixed.

For advanced people, they can already use `id -un` *today*. They can also keep on using $LOGNAME - I've not seen many people bother with that.

>Furthermore should a shell not touch environment variables besides the obvious SHELL. This could have disastrous effects in programs and script when using e.g. HOME or LOGNAME (which is btw the more canonical source for the display name as opposed to USER). And please to not start to also set e.g. HOME to keep them in sync. 

We already *do* "touch" environment variables in a bunch of cases.

For instance we already *do* set $HOME to find the correct place for our config files, because keeping it and changing the user is *broken*, especially once we start writing universal variables.

This is a simple UX matter - if you can make the thing people reach for first work, then you don't have a need for a second thing.

**Comment by faho** [comment] 2022-04-15 13:45
Also:

>Introducing that change would be a dumpster fire on multi-user nodes where UID
> [...]
> This could have disastrous effects

That's overly dramatic, and I would appreciate if you took a few steps back.

Realistically, currently $USER is outdated if the euid was changed via e.g. `su`. It doesn't match with what rights you currently have, the value is at most good as a "this is what user you originally logged in as". That's essentially useless.

If we update $USER, the value will be one of the names for the current (e)uid. On systems I'm familiar with, the UID determines the actual access rights, so that $USER value now reflects your permissions. Whether it's "root" or "toor" is then a minor cosmetic difference.

>We are trying to fix other programs legacy/compatibility behavior.

Yes, in some cases we will try to work around other program's misbehaviors, to improve the overall experience.

**Comment by septatrix** [comment] 2022-04-15 14:24
> > Introducing that change would be a dumpster fire on multi-user nodes where UID
> > [...]
> > This could have disastrous effects
> 
> That's overly dramatic, and I would appreciate if you took a few steps back.

I apologize if I sounded lurid and did not want to be rude. Still I stand firm in my point that always changing these variables can have unintended consequences.

If I log in to my universities cluster (which is managed using kerberos IIRC) I share a UID with a few thousand other students. We all have different network mounted home directories inside some sort of chroot/container such that we cannot access other users data. If fish now changes the $USER also for UID!=0 I would always have a wrong prompt. Even worse if - as you said fish already also changes the $HOME for them to remain in sync I would be practically locked out of my system because it now refers to another users home which I am unable to access. I would not be surprised if the result inside a chroot as above would be the same.

**Comment by faho** [comment] 2022-04-15 14:50
One idea here is to get the passwd entry for the name (if any) via `getpwnam(3)` and if the uid matches continue.

If not, update the user data - name and home.

**Comment by septatrix** [comment] 2022-04-15 16:07
> One idea here is to get the passwd entry for the name (if any) via `getpwnam(3)` and if the uid matches continue.
> 
> If not, update the user data - name and home.

Nice, that seems like a nifty way to do it.

**Closed** 2022-05-02 15:15 UTC
Labels: enhancement
