### ISSUE TITLE
Auto-completion works with 🤞but doesn't with  💰

### ISSUE THREAD

**Issue by canassa** [fish-shell/fish-shell#5382] opened 2018-12-03 12:41 UTC
First of all, sorry for the weird issue report! 😀 

I noticed a few weeks ago a weird behavior with my auto-completion. When I hit 'tab' to select an auto-completion the cursor seems to return one position, I recorded a screencast of the issue happening in here:

![not-working](https://user-images.githubusercontent.com/288227/49373872-de366400-f6ff-11e8-9041-74610d7f3e08.gif)

Notice and lack of space in-between the `cd` and the directories.

After some debugging, I managed to pin down the issue to the 💰emoji in my prompt. I basically have a `printf '💰'` call in my fish_prompt function that does that.

Now, the funny thing is that it doesn't happen for all emojis, it works just fine with the 🤞emoji and several others.

![works](https://user-images.githubusercontent.com/288227/49373791-96afd800-f6ff-11e8-90f1-3a2c559b9b54.gif)

The issue happens with both iTerm and the Terminal app

`fish, version 2.7.1`

Thanks!

**Comment by zanchey** [comment] 2018-12-03 14:09
I think this is a duplicate of #5272, and to quote:

Duplicate of #5059, #4539, #4609 and numerous other issues.

The summary is that the terminal and fish need to agree on how wide characters are or our cursor movement for doing suggestions goes to wrong places, but this sometimes goes wrong because unicode is hard. Fish 3.0 will have numerous improvements.

**Closed** 2018-12-03 14:15 UTC
