### ISSUE TITLE
Lift the restriction on using variable as the first word (the command word)

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#564] opened 2013-02-07 12:51 UTC
Currently it's prohibited to use variables as the first word of a command. However this can be useful at times, esp. when implementing functions that take "callbacks". Consider this:

    function map
        set -l predicate $argv[1]
        set -e argv[1]
        for a in $argv
            $predicate $a
        end
    end

Several considerations when `$predicate`

1. Expands to no word. Using the next word as command is almost always wrong. Better complain and skip this command.

1. Expands to a list, the head of which is one of `builtin` or `command`. Should `builtin` and `command` be interpreted?

**Comment by krader1961** [comment] 2016-04-08 22:45
This is fundamentally a duplicate of issue #154.

**Closed by krader1961** 2016-04-08 22:45 UTC
Labels: duplicate
