### ISSUE TITLE
tab completion broken on 3.0.1

### ISSUE THREAD

**Issue by a7hybnj2** [fish-shell/fish-shell#5668] opened 2019-02-18 17:05 UTC
fish, version 3.0.1
macOS Mojave 10.14.3
Terminal 2.9.1

I recently upgraded to fish 3.0.1 using `brew upgrade fish` and now my tab completion is broken.

for instance when trying to tab complete mvim I hit m {tab} and `mvi` populates the cli so I hit m to complete the command but the 'm's are a different color than the 'vi' part. When I hit enter it reads `fish: Unknown command mm`

<img width="248" alt="screen shot 2019-02-18 at 12 02 06" src="https://user-images.githubusercontent.com/36831279/52966353-0cc5f180-3375-11e9-9d20-ac17a2544c42.png">
<img width="221" alt="screen shot 2019-02-18 at 12 01 20" src="https://user-images.githubusercontent.com/36831279/52966354-0cc5f180-3375-11e9-81bb-fabdbc6ce586.png">

this is a new bug, this functionality worked perfectly on previous versions. I failed to look at what version I was running before I brew upgraded...

**Comment by faho** [comment] 2019-02-18 17:15
>for instance when trying to tab complete mvim I hit m {tab} and `mvi` populates the cli

Ummmh... what about e.g. `mv`?

How many times are you hitting tab?

What should happen is you enter `m<TAB>`, and fish half-opens the pager, with among other things at the very least "mvim" and "mv", but also quite possibly e.g. "make" and a whole bunch of other commands. If you press TAB again, it'll open the pager fully, and allow you to move around in it. Versions before 3.0.0 also immediately searched the pager, whereas 3.0.0 cancels paging instead, and requires you to press ctrl-s to start searching.

It will _also_ show the suggestion directly in the commandline, but you don't need to press TAB to see it, and you press right-arrow to accept it.

So I'm a bit fuzzy on which of those you attempted.

**Comment by a7hybnj2** [comment] 2019-02-18 17:17
probably related

If I type `mvi {tab}`
<img width="640" alt="screen shot 2019-02-18 at 12 14 21" src="https://user-images.githubusercontent.com/36831279/52967057-ddb07f80-3376-11e9-960a-026f59e71416.png">
then I `{backspace}`
<img width="215" alt="screen shot 2019-02-18 at 12 14 35" src="https://user-images.githubusercontent.com/36831279/52967056-ddb07f80-3376-11e9-950a-59bc20bd6ffc.png">
all the way I am left with `mv` and cannot delete it
<img width="153" alt="screen shot 2019-02-18 at 12 14 40" src="https://user-images.githubusercontent.com/36831279/52967055-ddb07f80-3376-11e9-9db3-da5f195dccdf.png">
but if I hit enter it makes no mention of having mv populated as if it were invisible
<img width="110" alt="screen shot 2019-02-18 at 12 14 45" src="https://user-images.githubusercontent.com/36831279/52967054-ddb07f80-3376-11e9-9b11-a75f462a83a6.png">

**Comment by faho** [comment] 2019-02-18 17:27
Ah, okay.

What's happening here is that you have a character in your prompt that fish and your terminal disagree on the width on. This happens because fish 3 got an update and now recognizes more characters, and recognizes more characters as wide that it previously thought were narrow (because unicode9 changed the widths!), while terminals are frequently set to older settings.

Most likely what you need to do is turn on "treat ambiguous width characters as double-width" in your terminal's settings.

**Comment by a7hybnj2** [comment] 2019-02-18 17:30
@faho I included more screen shots which I hope would clarify the functionality.

To explain the first screen shots more clearly: In the first image I type `m {tab} m' which populates `mvim` but when I hit enter I get the error illustrated.

I am not using {right arrow}

Here I am typing `mv {tab}'

<img width="291" alt="screen shot 2019-02-18 at 12 27 24" src="https://user-images.githubusercontent.com/36831279/52967615-9cb96a80-3378-11e9-8811-68e295df50e8.png">
then I arrow down to highlight `mvim`
<img width="292" alt="screen shot 2019-02-18 at 12 27 33" src="https://user-images.githubusercontent.com/36831279/52967613-9cb96a80-3378-11e9-8864-2e5e5208985b.png">
then I hit enter and mvim opens! but look at the command `mvimim` what is that?
<img width="220" alt="screen shot 2019-02-18 at 12 27 41" src="https://user-images.githubusercontent.com/36831279/52967611-9c20d400-3378-11e9-9d58-8c8aad51af4e.png">

**Comment by a7hybnj2** [comment] 2019-02-18 17:31
> Ah, okay.
> 
> What's happening here is that you have a character in your prompt that fish and your terminal disagree on the width on. This happens because fish 3 got an update and now recognizes more characters, and recognizes more characters as wide that it previously thought were narrow (because unicode9 changed the widths!), while terminals are frequently set to older settings.
> 
> Most likely what you need to do is turn on "treat ambiguous width characters as double-width" in your terminal's settings.

Whoops, didn't see this until I replied already. Let me try out your solution.

**Comment by a7hybnj2** [comment] 2019-02-18 17:39
@faho I cannot find anything resembling "tread ambiguous width characters as double-width" in the terminals settings.

**Comment by faho** [comment] 2019-02-18 17:46
@a7hybnj2: Please see https://apple.stackexchange.com/a/213483.

**Comment by a7hybnj2** [comment] 2019-02-18 17:52
`Profiles - Text` doesn't seem to contain that option
<img width="663" alt="screen shot 2019-02-18 at 12 49 22" src="https://user-images.githubusercontent.com/36831279/52968594-b27c5f00-337b-11e9-8893-5df68559d452.png">
nor does `Profiles - Advanced`
<img width="668" alt="screen shot 2019-02-18 at 12 49 37" src="https://user-images.githubusercontent.com/36831279/52968593-b27c5f00-337b-11e9-8a3a-1d409c7ee71c.png">
The only mention of "Ambiguous characters" is at the very bottom of `Advanced` "Unicode East Asian Ambiguous characters are wide" and when I checked it as an option it did not fix the problem.

**Comment by a7hybnj2** [comment] 2019-02-18 17:54
Can I just change fish back to the previous unicode version?

**Comment by faho** [comment] 2019-02-18 18:05
>Can I just change fish back to the previous unicode version?

Not quite. What you can do is set "fish_emoji_width" and "fish_ambiguous_width" to 1, e.g.

```fish
set -g fish_emoji_width 1
set -g fish_ambiguous_width 1
```

This won't "change it back" for characters that are _new_ to unicode 9, but it'll turn back handling of those that were changed.

**Comment by a7hybnj2** [comment] 2019-02-18 18:19
I was hoping that would work...

Here is my .config/fish/config.fish not that it will help.
```
set -gx EDITOR 'mvim'
set -gx GPG_TTY (tty)
set -g fish_emoji_width 1
set -g fish_ambiguous_width 1
```

Anything else I should try before I attempt to install an older version?

**Comment by faho** [comment] 2019-02-18 18:24
@a7hybnj2: What's your `fish_prompt` and `fish_right_prompt`?

**Comment by a7hybnj2** [comment] 2019-02-18 18:34
The previous version I was running was 2.7.1

I am using omf theme [mars](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#mars)
The only thing I have set beyond that is:
```
fish_greeting.fish
function fish_greeting
	neofetch
end
```

**Comment by a7hybnj2** [comment] 2019-02-18 18:40
I just did a `brew switch fish 2.7.1` and everything works like I expect it too.

**Comment by floam** [comment] 2019-02-18 22:06
It shouldn't be necessary to set those variables, we actually pretty carefully deduce the emoji behavior on Terminal.app in 3.0.0. Seems something is going wrong though.

**Comment by a7hybnj2** [comment] 2019-02-18 22:08
@floam I would like to give 3.0.0 a try but couldn't find a brew formula. Rolling back to 2.7.1 defiantly removed the issue. If you want me to test anything or provide more data just let me know.

**Comment by floam** [comment] 2019-02-18 23:33
3.0.0 and 3.0.1 should have functionally the same behavior here AFAICT. What I was suggesting was that whatever the problem is, it's probably not going to be fixed by adjusting `fish_emoji_width` for you because we should be correctly figuring out the value internally in fish.

In fact I think setting it to `1` should make it worse. Terminal.app in High Sierra and newer renders emojis with a width of 2 (at least, that's what we assert in env.cpp).

**Comment by floam** [comment] 2019-02-18 23:35
Does it happen for you with the default prompt?

**Comment by floam** [comment] 2019-02-18 23:42
Okay, I can pretty easily reproduce this by sticking the triangle the mars theme uses into the prompt:

```
function fish_prompt
    echo ▶︎︎
end
```

**Comment by floam** [comment] 2019-02-19 00:04
Which is:
```
printf ▶︎︎|god -t x1z
0000000 e2 96 b6 ef b8 8e ef b8 8e                       >?.??.?.<
0000011
```

**Comment by floam** [comment] 2019-02-19 00:12
That's a triangle plus variation selector 15, which selects for a text presentation as opposed to the colorful emoji presentation (variation selector 16).

**Comment by floam** [comment] 2019-02-19 00:23
Fish is giving it a total width of 3, when it's really 1-wide. I think we want our wcwidth to return 0 for VS 15. @ridiculousfish? @faho?

**Comment by floam** [comment] 2019-02-19 00:42
I'd commit this but I'm not super confident there will not be some surprise yet:
```diff
diff --git a/src/fallback.cpp b/src/fallback.cpp
index 3f291255..8b785367 100644
--- a/src/fallback.cpp
+++ b/src/fallback.cpp
@@ -282,8 +282,9 @@ int fish_wcswidth(const wchar_t *str, size_t n) { return wcswidth(str, n); }
 int fish_wcwidth(wchar_t wc) {
     // Check for VS16 which selects emoji presentation. This "promotes" a character like U+2764
     // (width 1) to an emoji (probably width 2). So treat it as width 1 so the sums work. See #2652.
-    const int variation_selector_16 = 0xFE0F;
+    const int variation_selector_16 = 0xFE0F, variation_selector_15 = 0xFE0E;
     if (wc == variation_selector_16) return 1;
+    else if (wc == variation_selector_15) return 0;
 
     int width = widechar_wcwidth(wc);
     switch (width) {
```

**Comment by a7hybnj2** [comment] 2019-02-19 00:42
@floam wow, thanks for tracking that down. I have removed any width settings from my config.fish file.

I will continue watching for updates.

**Comment by floam** [comment] 2019-02-19 01:08
Is VS15 supposed to be able to demote an emoji? Like maybe be `-1` width depending on context? Because that would suck.

**Comment by floam** [comment] 2019-02-19 04:35
We'd really need to know the previous character to handle these variation selectors properly. `fish_wcswidth` could do it I guess.

**Closed** 2019-02-19 07:18 UTC
Labels: bug

**Comment by floam** [comment] 2019-02-19 12:24
@a7hybnj2 You might find `brew install --HEAD fish` works OK.

**Comment by a7hybnj2** [comment] 2019-02-19 16:57
@floam 
```
brew uninstall fish
brew install --head fish
fish --version `3.0.2`
```
still has the errors illustrated above in the screenshots...

**Comment by floam** [comment] 2019-02-19 16:59
`--HEAD`, not `--head`.

**Comment by a7hybnj2** [comment] 2019-02-19 17:04
@floam haha whoops! Thanks for the help in diagnosing, tracking, and implementing a quick fix! It appears to be working for my test cases!

**Comment by a7hybnj2** [comment] 2020-01-09 15:57
Hi, I just wanted to check on this. I just brew install fish and the version I received still had the character issue. If you look at previous comments there was a fix in --HEAD so I again brew uninstall fish; brew install --HEAD fish and that fixed my problems.

I think I was lead to believe, maybe since the previous issue was closed, that it was fixed. Can anyone provide insight on this?

I am happy to run HEAD for now but just thought I would check.

**Comment by zanchey** [comment] 2020-01-10 02:39
It is fixed in the git master branch (what you get installing with `--HEAD`, but not in a released version yet (though new version coming soon).

**Comment by a7hybnj2** [comment] 2020-01-10 02:45
@zanchey Oh, wow. I thought a new version would have come out since this issue was opened almost a year ago. I have been running --HEAD since I realized it was a fix to my issue and it has been working well. Never had any other issues with it. Do you know when 'soon' will be(1 month, 5, 10)?

**Comment by zanchey** [comment] 2020-01-10 03:10
I will not disappoint you with an inevitably-inaccurate answer.

**Comment by floam** [comment] 2020-02-18 16:39
@a7hybnj2 3.1.0 was released, in case you missed it.

**Comment by a7hybnj2** [comment] 2020-02-18 17:53
@floam thanks for the headsup. I just updated. So far things look good.
