### ISSUE TITLE
fish-shell ignores the argv like there is no such argv if it is the string "hostname"

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#8659] opened 2022-01-21 18:44 UTC
```
- fish, version 3.3.1
- Linux archlinux 5.16.2-zen1-1-zen
```
**YOUR TEXT HERE**
I wrote a function, when I pass the hostname as the argv to the function, the behavior is wrong, then after analyze the function line by line, I accidentally found a very weird bug of fish-shell: fish-shell ignores the argv like there is no such argv if it is the string "hostname", I'm not sure if there are other strings like this that fish shell will ignore.

Running under `sh -c 'env HOME=$(mktemp -d) fish'`:
```
> function abc
      set -q $argv[1]; and set ARGV .; or set ARGV $argv[1]
      echo ARGV: $ARGV
  end
> abc def
ARGV: def
> abc host
ARGV: host
> abc hostnameaaaa
ARGV: hostnameaaaa
> abc hostname
ARGV: .
```

**Comment by faho** [comment] 2022-01-21 19:38
Duplicate of #8214

**Closed by faho** 2022-01-21 19:38 UTC

**Comment by faho** [comment] 2022-01-21 19:40
You're checking the wrong thing.

`set -q $argv[1]` checks if the variable named by *the contents of the first element of argv* are set.

You want just `set -q argv[1]` without the `$`.

Also this would act weirdly because of #8214.

**Comment by c02y** [comment] 2022-01-21 20:14
Jesus, didn't know that, I got a lot of checks for whether argv is passed in my config.fish, they never went wrong.

And I also notice that `set -q argv` is different from `set -q argv[1]`, I should use `set -q argv[1]` to check whether any argv is passed to a function since `set -q argv` doesn't handle `else/or` part.
