### ISSUE TITLE
inline help message is not formatted correctly

### ISSUE THREAD

**Issue by qinfeng** [fish-shell/fish-shell#4708] opened 2018-02-05 06:28 UTC
I found most of the built-in command's inline help message is not well formatted and all double-quote are converted to single quote which leads the example in the help message not working at all, such as below case:
```
$ read --help
       readread - read line of input into variables
        -

   Synopsis
       read [OPTIONS] [VARIABLES...]

   Example
       The following code stores the value 'hello' in the shell variable $foo.

       echo hello|read foo

         This is a neat way to handle command output by-line:
       printf '%s\n' line1 line2 line3 line4 | while read -l foo
                         echo 'This is another line: $foo'
                     end
```
The first line always doubles the command name.
The example does not work since it should be 
```
echo "This is another line: $foo"
```

My env info:
```
fish version: fish, version 2.7.1
uname -a
Darwin iMac 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
term:  xterm-256color
```

**Comment by zanchey** [comment] 2018-02-05 08:04
Yep, this is a problem with the documentation generation workflow, which has been fixed in the development version.

I'm close this as a duplicate of #4534.

**Closed by zanchey** 2018-02-05 08:04 UTC
