### ISSUE TITLE
Cannot get breakpoint to work

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2157] opened 2015-06-29 00:56 UTC
I have been trying to get `breakpoint` to work by putting it in the function on line 1, then calling the function. I do not get a prompt while running the function. Should I?

**Comment by ridiculousfish** [comment] 2015-06-29 01:46
What version of fish are you using? This works for me on master:

    > function do_breakpoint ; echo before ; breakpoint ; echo after ; end
    > do_breakpoint
    before
    >

Control-D to continue with the function.

**Comment by ElijahLynn** [comment] 2015-06-29 13:56
Thanks for that example, okay it was working. Your example taught me how it works. I think I was expecting some more visual indicator of what breakpoint line number I was on. That would be a good example for the docs.

**Comment by ridiculousfish** [comment] 2015-06-29 17:45
It would be nice to display some sort of indicator.

**Comment by zanchey** [comment] 2015-07-21 23:46
I'm going to mark this as a duplicate of #1310 for now, and we can track there.

**Closed by zanchey** 2015-07-21 23:46 UTC
Labels: duplicate
