### ISSUE TITLE
vi mode: Better differentiate between `aw`, `iw` and `w`, `e` text-objects

### ISSUE THREAD

**Issue by primeapple** [fish-shell/fish-shell#10617] opened 2024-07-16 12:32 UTC
Some vi text objects don't behave as they would in vi:

- `iw` and `aw` mostly behave the same right now, which is not correct. In vi `diw` deletes the current word, while but `daw` deletes the current word and all following whitespace. In fish both behave as of `diw` in vi. Same with `ciw` and `caw` (and I think all other commands that use `iw`/`aw`
- `w` and `e` behave correctly as movements, but not as text objects. In vi `dw` deletes all characters until whitespace occurs. It will also delete this whitespace until a new character occurs. `de` deletes all characters until whitespace occurs, but keeps the whitespace. In Fish both behave as `de` in vi. Same for `cw` and `ce` and I believe all characters that use `w` and `e` textobjects.

**Comment by faho** [comment] 2024-08-13 15:41
Duplicate of #1842

**Closed by faho** 2024-08-13 15:41 UTC

**Comment by faho** [comment] 2024-08-13 15:42
fish does not, currently, *have* text objects. It has some hacked-together key bindings that do some things that look like it.

Frankly: The vi bindings are in need of a real champion to bring them up to snuff.
