### ISSUE TITLE
`<command> --help` & `help <command>` no longer work on macOS

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4805] opened 2018-03-12 09:24 UTC
```
$ fish --version
fish, version 2.7.1-948-gd367d57a
```

Example using `string`, but is the same for all commands:
```
$ help string
# opens default browser to https://fishshell.com/docs/2.7/index.html
# rather than anchored link to https://fishshell.com/docs/2.7/commands.html#string
```

```
$ string --help
# returns nothing
```

**Comment by mqudsi** [comment] 2018-03-12 12:09
macOS?

**Comment by mqudsi** [comment] 2018-03-12 13:20
Duplicate of #4480, fixed for 3.0 in `42fa8415736d8a7108f59e791085f99831402b1a` but unfortunately not included in 2.7.x:

```fish
mqudsi@ZBook ~/r/fish-shell> git branch --contains 42fa8415736d8a7108f59e791085f99831402b1a                                                                                                                                                                   conservative_autosuggestions                                                                                                                                                                                                                                coverity_scan_master                                                                                                                                                                                                                                        direct_io                                                                                                                                                                                                                                                   exec_wrapper                                                                                                                                                                                                                                                fignore                                                                                                                                                                                                                                                     fix_brace_parsing                                                                                                                                                                                                                                           git-status-v1                                                                                                                                                                                                                                               hostname                                                                                                                                                                                                                                                    issue-4715                                                                                                                                                                                                                                                  issue_4490                                                                                                                                                                                                                                                * master                                                                                                                                                                                                                                                      no_percent                                                                                                                                                                                                                                                  no_underscore                                                                                                                                                                                                                                               readme_updates                                                                                                                                                                                                                                              safe_completions                                                                                                                                                                                                                                            string_split_keep_empty                                                                                                                                                                                                                                     test_wait_pid   
````

@zanchey thoughts here?

**Comment by zx8** [comment] 2018-03-12 19:29
I thought I was using 3.0 built from `master` / `brew install fish --HEAD`?

Note the portion after `fish, version 2.7.1-948-g[...]` refers to commit [`d367d57a`](https://github.com/fish-shell/fish-shell/commit/d367d57ae9527753e3564a77b757c8ccdbb12f02)

**Comment by mqudsi** [comment] 2018-03-12 22:25
We can track it there. Thanks!

**Closed by mqudsi** 2018-03-12 22:25 UTC
