### ISSUE TITLE
commandline special input functions are not executed in order

### ISSUE THREAD

**Issue by e-beach** [fish-shell/fish-shell#4363] opened 2017-08-29 12:18 UTC
$ fish --version                                                                         
fish, version 2.6.0

Repro:

1. `bind \; 'commandline -f end-of-line; commandline -C 3'`
2.  type 'hello world'
3.  type `;`

Expected behavior: the cursor moves to the third character, `l`.
Actual behavior: the cursor stays at the end of the line.

This is likely a known issue, but it is confusing to someone who does not know how the code is implemented, and contradicts the docs, which states that commands are run in the order they are specified.

**Comment by krader1961** [comment] 2017-08-30 05:03
This is a duplicate of issue #3031.

**Closed** 2017-08-30 14:31 UTC
