### ISSUE TITLE
switch: Expected exactly one argument, got 0

### ISSUE THREAD

**Issue by Martinfx** [fish-shell/fish-shell#6458] opened 2019-12-28 14:58 UTC
Hi,
i use fish shell but on FreeBSD have issue with command

```
fish, version 3.0.2
echo $version 3.0.2

uname -a 
FreeBSD  12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 GENERIC  amd64

echo $TERM 
xterm-256color
```

```
 sudo mount -o loop FreeBSD-12.1-RELEASE-arm-armv6q-RPI-B.img
mount: FreeBSD-12.1-RELEASE-arm-armv6q-RPI-B.img: unknown special file or file system
maxfx@ ~/Downloads> sudo mount -o /usr/local/share/fish/functions/__fish_complete_mount_opts.fish (line 146): switch: Expected exactly one argument, got 0

    switch (string replace -r '=.*' '=' -- $last_arg)
           ^
in function “__fish_complete_mount_opts”
	called on line 35 of file /usr/local/share/fish/completions/sudo.fish

in command substitution
	called on line 70 of file /usr/local/share/fish/completions/sudo.fish

in function “__fish_complete_sudo_subcommand”
	called on standard input

in command substitution
	called on standard input


```

**Comment by faho** [comment] 2019-12-28 15:13
Duplicate of #5750

Fixed in master by f56bce3f977182710762a1501ec52de3ddaa29d2.

**Closed by faho** 2019-12-28 15:13 UTC
