### ISSUE TITLE
Request to add support for piping into `fish -c 'builtin'` for built-ins

### ISSUE THREAD

**Issue by mattmc3** [fish-shell/fish-shell#10421] opened 2024-04-05 20:02 UTC
I'm on Fish 3.7.1.

I'd like to request support for properly piping data into a call to `fish -c`. The reason for this would be to allow Fish one-liners to be used from another shell like Bash/Zsh, or for [commands that run as background jobs](https://github.com/fish-shell/fish-shell/issues/238) with `&`.

Fish built-ins (eg: `string`, `count`, `math`) fail to handle piped input when called via `fish -c`. However, external commands (eg: `grep`, `cat`) handle piping just fine.

Example of Fish built-ins failing to accept piped data:

```fish
$ echo "1 + 1" | math  # correct
2
$ echo "1 + 1" | fish -N -c 'math'  # error!
math: expected >= 1 arguments; got 0
$ printf '%s\n' a b c | count  # correct
3
$ printf '%s\n' a b c | fish -N -c "count"  # wrong!
0
$ printf '%s\n' abc xyz abba zzz | string match "*b*"  # correct
abc
abba
$ printf '%s\n' abc xyz abba zzz | fish -N -c 'string match "*b*"'
# incorrect! empty results
```

Example of commands accepting piped data just fine:

```fish
$ printf '%s\n' a b c | cat
a
b
c
$ printf '%s\n' a b c | fish -N -c "cat"
a
b
c
$ printf '%s\n' abc xyz abba zzz | grep b
abc
abba
$ printf '%s\n' abc xyz abba zzz | fish -N -c "grep b"
abc
abba
```

If I'm not properly understanding what the behavior should be here, let me know. It doesn't seem like this should behave as I've demonstrated, but happy to be educated if I'm incorrect. I think it would be immensely useful to pipe data into `string`, for example, when you need to work in another shell and don't want to use `sed`.

**Comment by faho** [comment] 2024-04-05 21:36
Duplicate of #5714

**Closed by faho** 2024-04-05 21:36 UTC

**Comment by faho** [comment] 2024-04-05 21:38
The reason these won't read from stdin in that case is because they only do when "directly redirected", to avoid confusion with being called with 0 arguments given on the commandline (e.g. `string match foo $bar` when $bar is empty).

So this will have to be a flag (tho there probably won't be for `count` because that currently has none, use `wc` instead).

**Comment by mattmc3** [comment] 2024-04-05 22:39
Thanks faho. In the mean time, for anyone also having this issue, a [not-so-UUOC](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat) will get you there:

```
$ echo "1 + 2" | fish -N -c "cat | math"
3
$ printf '%s\n' abc xyz abba zzz | fish -N -c "cat | string match '*b*'"
abc
abba
```
