### ISSUE TITLE
Autocomplete text uses default text color

### ISSUE THREAD

**Issue by dstaley** [fish-shell/fish-shell#2940] opened 2016-04-15 01:19 UTC
When using Ubuntu for Windows to run fish, the default color for autocomplete from history is the same color as default text.

![](https://zippy.gfycat.com/ThirdRepulsiveArachnid.gif)

### Reproduction Steps:

1. Using fish on Ubuntu for Windows, begin typing a command from your history

### Expected behavior:

The autocomplete text should be displayed in a color other than the default text color so as to distinguish it from the text you've already typed.

### Observed behavior:

The autocomplete text is displayed in the same color as the text you've typed, making it difficult to realize what you've typed and what is being autocompleted.

---
Fish version: 2.2.0

Operating system: Ubuntu on Windows

Terminal or terminal emulator: Windows Console

**Comment by krader1961** [comment] 2016-04-15 01:52
This is effectively a duplicate of issue #2910.

**Closed by krader1961** 2016-04-15 01:52 UTC
Labels: duplicate

**Comment by floam** [comment] 2016-04-15 03:35
This bug perhaps is a little embarrassing in that it is the most immediately user-visible one, and while their console lies about being "xterm", it did  only had 16 colors for a reason, and fish - on purpose - tries to bast 256 colors at this terminal we know should only have 16 - we break the rules because it often would work and we want the extra colors.

**Comment by ridiculousfish** [comment] 2016-04-15 20:48
Have you found a reliable way to detect if we're running on Windows? I guess it has to be dynamic (not at build time) because unmodified Linux binaries are being run on Windows.

**Comment by floam** [comment] 2016-04-16 00:38
Yeah, check '/proc/version'.

On Fri, Apr 15, 2016 at 1:48 PM ridiculousfish <notifications@github.com>
wrote:

> Have you found a reliable way to detect if we're running on Windows? I
> guess it has to be dynamic (not at build time) because unmodified Linux
> binaries are being run on Windows.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/fish-shell/fish-shell/issues/2940#issuecomment-210641019>
>
-- 
Aaron

**Comment by krader1961** [comment] 2016-04-16 01:25
> Yeah, check /proc/version

Is the information we need in `uname -a` (or one of its more restrictive formats)? That would be preferable to checking */proc/version* which doesn't exist on OS X.

**Comment by floam** [comment] 2016-04-16 01:32
Running Ubuntu's `/bin/uname`  look a lot closer to normal Linux vs. checking the `/proc/` mount. `/proc/version` not existing means we can just check if it exists before wasting a fork.

<img width="667" alt="screenshot 2016-04-15 at 6 28 37 pm" src="https://cloud.githubusercontent.com/assets/291142/14578271/3a72358c-0338-11e6-9dca-da2e324ec21c.png">

**Comment by krader1961** [comment] 2016-04-16 01:38
Okay, the next question is can we depend on /proc/version to continue to contain the string "Microsoft" for the foreseeable future (at least a full year from today)? We'll be really annoyed if, when it goes from Beta to GA, they change those strings thus invalidating our assumption about its stability.

**Comment by floam** [comment] 2016-04-16 01:43
This is Microsoft - I'd say they are cognizant of how people do version checks and are aware that -Microsoft" as the version suffix here is about the only way to identify this guy. 

If they remove that suffix I guess their customers will be annoyed too. 

Consider that they skipped Windows 9 to not break software checking if the version strings start with "Windows 9" for Win 95/98 checks.

**Comment by floam** [comment] 2016-04-16 01:49
(I'd suspect we can depend on that being there until it will not cause a problem for it not to be there. Having fiddled with this thing it appears to not be there by chance.)

**Comment by krader1961** [comment] 2016-04-16 02:03
> I'd say they are cognizant of how people do version checks...

Consider their penchant for changing the MS Office file formats across new releases of that software in ways that rendered the files to be unable to be opened by the previous version. Not just opened with some features missing -- completely unable to be opened. So, no, I'm not going to make any assumptions regarding */proc/version*. Absent any public statement to the effect "Microsoft" will continue to be part of the info reported by */proc/version* it's safer to assume we can't trust it.

**Comment by floam** [comment] 2016-04-16 02:04
If we're talking about trusting it... to reduce the color support from 256 to 16, what's the harm?

**Comment by krader1961** [comment] 2016-04-16 02:16
The harm is that people are surprised, and blame us, when Microsoft changes the output of */proc/version* causing their prompt colors to change even though they haven't upgraded fish or changed their fish configuration. I can also see us adapting other behaviors of fish based on that information. Which means if MS changes it things beside the prompt colors are affected.

Sure, any distro might change things in a manner that breaks fish; e.g., by installing an updated `seq` command that has subtly different behavior. But we know from history that is very unlikely. I'm not willing today (maybe tomorrow) to make that same assumption about the Win10 linux subsystem.

**Comment by floam** [comment] 2016-04-16 02:21
How do we make it do the right thing today then?

**Comment by floam** [comment] 2016-04-16 02:23
(today, someone new to Linux on Windows trying the various shells, will find that fish is the one with the broken colors. Keep in mind, you get fish on Ubuntu on Windows (which is on Ubuntu 14.04, only with a PPA which is nightly built master.)

**Comment by krader1961** [comment] 2016-04-16 02:51
> How do we make it do the right thing today then?

I don't know. The answer might be relying on "Microsoft" appearing in the output of */proc/version*. But absent some reason (e.g., public documentation) to believe that won't change in the immediate future it seems like an unsafe assumption (especially given Microsoft's history). I would prefer to revert our existing xterm to xterm-256color hack and deal with the fallout of that change.

**Comment by dstaley** [comment] 2016-04-16 03:13
Rich Turner, the PM for Ubuntu on Windows, says checking `/proc/version` is ["likely to be one of the most stable ways of checking"](https://twitter.com/richturn_ms/status/721172947302350848?s=09) if you're running on Ubuntu for Windows.

**Comment by krader1961** [comment] 2016-04-16 03:32
Thank you, @dstaley. We appreciate the confirmation. I'd prefer something more official than a tweet but I think that is sufficient for our needs. I've updated issue #2910 with that info.

**Comment by bitcrazed** [comment] 2016-06-26 20:13
Thanks @dstaley. Now I understand the context more fully (thanks for looping me into the conversation), let me see if there's a better way to feature-check color support than name-checking a text string.

Know that we are keen to improve the Windows Console's color support in a future release; bear with us while we wrangle this thing into better shape.
