### ISSUE TITLE
~/.local/share/fish_history is not valid YAML

### ISSUE THREAD

**Issue by halostatue** [fish-shell/fish-shell#5936] opened 2019-06-12 20:04 UTC
Fish version 3.0.2.

When trying to parse `fish_history` with Psych (the Ruby YAML parser), it is almost, but not quite, valid YAML.

```
Psych::SyntaxError: (/Users/austin/.local/share/fish/fish_history): mapping values are not allowed in this context at line 2045 column 30
from /Users/austin/.rubies/ruby-2.3.8/lib/ruby/2.3.0/psych.rb:379:in `parse'
```

The line in question contains a colon:
```yaml
- cmd: git commit -am "v1.0.3: Fix an issue with a regex" && git tag v1.0.3 && git push-head
  when: 1559876301
```

The correct way that this should be written is:
```yaml
- cmd: 'git commit -am "v1.0.3: Fix an issue with a regex" && git tag v1.0.3 && git push-head'
  when: 1559876301
```

Alternatively, it may be written:
```yaml
- cmd: |
    git commit -am "v1.0.3: Fix an issue with a regex" && git tag v1.0.3 && git push-head
  when: 1559876301
```

This latter (a) ensures that any wrapped text appears only on one line and (b) ensures that there’s no conflict between the YAML quotes and the command-line.

**Comment by faho** [comment] 2019-06-12 20:08
Duplicate of #3341 - we know it's not valid YAML, and we want to switch to something better than the current setup.

**Closed by faho** 2019-06-12 20:08 UTC
