### ISSUE TITLE
RFC: Automatic expansion of non-words

### ISSUE THREAD

**Issue by danzimm** [fish-shell/fish-shell#7049] opened 2020-05-27 16:04 UTC
Hey folks, I was wondering if I could get some feedback, and potentially some implementation advice, about an idea to implicitly (and conditionally) expand non-word tokens.

## Feature
Let me unwrap what I mean by "implicitly (and conditionally) expand non-word tokens".

My overall goal is to enable typing `vim //subpath/to/file.txt` and have fish automatically replace `//` with `(get_project_root)`. There is one caveat: there are certain commands that I want to avoid implicitly expanding from (because e.g. the command already does the expansion itself).

These features would enable a better CLI workflow when interacting with various build systems like buck. One day I would to be able to run the following commands and it do the *right* thing:
```
> vim //lib/foo.txt
> vim //config/
> buck build //lib:foo
> cat //buck-out/gen/lib/foo.txt.processed
```
If the support is abstract enough that last command might even be able to be replaced with:
```
> cat ///lib/foo.txt.processed
```
where `///` was expanded to `(get_project_root)/buck-out/gen`.

## What I've tried to satisfy this feature in the past

In the past year or two I made this work by implementing my own function to compute the current project root and manually typing `(get_project_root)` (well I shortened the function name) every-time I needed the root expanded. I found that this was tiresome (and slow), and I eventually opted to c/p the paths as opposed to using this "shortcut".

I attempted to use `abbr`s, but those will only expand after the user types a space following the word they want expanded. So, with `abbr`s I would have to type `vim //<space><backspace>path/to/file.txt`. This is better than the function, but was still not the most ergonomically pleasing.

## My own thoughts on enabling this feature

From my perspective this feature can be thought of as the composition of two features:
1) Enable certain `abbr`s to be expanded mid-word
  - This is kind of scary, though, from a performance perspective. Maybe we add a restriction that an `abbr` always has to start after a space, but can end mid-word.
2) Enable `abbr`s to avoid expansion conditionally based off previous tokens in the current statement (I might have the terminology wrong here... let me know if I need to clarify what I mean here though)

## Would this be accepted?

What do the maintainers think about the feature listed above? What about the potential implementation I described? I would love to hear other perspectives on this feature (both the validity of the feature and ideas about how to implement it if you think it's a reasonable idea!). If this would be accepted I am very interested in implementing this myself and creating PRs.

**Comment by faho** [comment] 2020-05-27 16:16
Duplicate of #5003

**Comment by faho** [comment] 2020-05-27 16:16
Yeah, global abbreviations are on the agenda.

**Closed by faho** 2020-05-27 16:16 UTC

**Comment by danzimm** [comment] 2020-05-27 16:35
Thanks for the quick response! I just read through the thread you linked- I can't quite determine whether global abbreviations will require spaces (i.e. if global abbreviations would work on words only, or partial words too). Could you help clarify what global abbreviations are specifically? Additionally do you know if anyone is working on this already? If not I might be interested in helping out :D

**Comment by faho** [comment] 2020-05-27 16:55
>Could you help clarify what global abbreviations are specifically? 

That's for #5003 to clarify.

>Additionally do you know if anyone is working on this already?

Not to my knowledge.
