### ISSUE TITLE
resourcing config file doesn't work as function. why?

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#1908] opened 2015-01-20 20:57 UTC
``` bash
$ type resource
resource is a function with definition
function resource
        source ~/.config/fish/config.fish
end
```

why doesn't this actually work to re-source the file again?

I edit the config.fish file, and add a `set -x BLAH foo` for instance, but running `resource` will not honor it, and I have to run `source ~/.config/fish/config.fish` manually

**Comment by geoff-codes** [comment] 2015-01-21 06:40
You need to use globally-scoped variables.
`man set`:
` -g or --global causes the specified shell variable to be given a global scope. Non-global variables disappear when the block they belong to ends`

That is, anything you have `set -x` will be deallocated at the end of the block — that is, when the function completes. Use `set -gx` in your `config.fishand you should get what

**Comment by danielb2** [comment] 2015-01-21 06:59
ok, thanks much

**Comment by danielb2** [comment] 2015-01-21 07:00
Wouldn't it be useful to just tell the function itself that it should behave as the outer scope?

**Comment by geoff-codes** [comment] 2015-01-21 07:15
Well, by definition, a function has its own scope. While in theory a function could be told to make all locally scoped variables global, this isn't usually a good practice, since one might end up with many more variables than necessary in memory. In any case, I don't believe fish has any such functionality. Once you get used to scoped variables, its really not that bad, I promise :wink:.

**Comment by danielb2** [comment] 2015-01-21 07:17
my concern was just that with `resource` in particular the desired outcome was to have it behave as a different scope. But I suppose it can be argued that `set -gx` is simply the appropriate way of setting those variables anyway.

**Comment by geoff-codes** [comment] 2015-01-21 07:19
> But I suppose it can be argued that set -gx is simply the appropriate way of setting those variables anyway.

Yep. :100:

**Comment by zanchey** [comment] 2015-01-21 07:39
I think there's been a change to the default scoping in this situation. The behaviour here appears to differ between 2.1.1 and 2.1.1-1188-gf920be5 (f920be5).

**Comment by ridiculousfish** [comment] 2015-01-21 21:15
Let's nail down what changed. My guess is 7b12fd26f3d0ec2fe655cd537fda21f760e92d11

**Comment by geoff-codes** [comment] 2015-01-22 03:22
But is this indeed not the desired behavior?

The language from `set --help` since at least 737972be:

> The scoping rules when creating or updating a variable are:

> 1.  If a variable is explicitly set to either universal, global or local, that setting will be honored. If a variable of the same name exists in a different scope, that variable will not be changed.

> 2.  If a variable is not explicitly set to be either universal, global or local, but has been previously defined, the previous variable scope is used.

> 3.  **If a variable is not explicitly set to be either universal, global or local and has never before been defined, the variable will be local to the currently executing function.** Note that this is different from using the -l or --local flag. If one of those flags is used, the variable will be local to the most inner currently executing block, while without these the variable will be local to the function. If no function is executing, the variable will be global.

So, as I see it, a function which sources `~/.config/fish/config.fish` should have any non-explicitly scoped variables declared therein local to that function. Maybe it seems a seem a bit off since we're talking about the `config.fish` file, where (on shell initialization) unscoped variables are initialized into the top-level local scope. But _after_ shell initialization, `~/.config/fish/config.fish` has no special importance; sourcing it is just like sourcing any other file.

**Comment by zanchey** [comment] 2015-01-23 00:53
If nothing else, the change in behaviour should be noted in the release notes.

**Comment by ridiculousfish** [comment] 2015-05-03 03:46
Ok, so the is the current behavior:

1. When config.fish is sourced during startup, there's no local scope. All variables created within fish.config are therefore global.
2. If config.fish is re-sourced, and it modifies a variable that was defined in step 1, that variable is global so the modifications will be visible.
3. However, if you modify config.fish to add a new variable, that will use the default scoping rules.

The key change is that `set -l` will do something sensible when run at the command line. That is, before:

    function show ; echo $var ; end ; set -l var local_value ; show

will output `local_value`: the local variable is visible to called functions (which it ought not to be). After the change it won't be visible to callees. I don't think the behavior of `resource` should have changed.

I think there's nothing remaining to do here, except update the relnotes as zanchey says. @danielb2 Are you OK closing? Does all this make sense?

**Comment by geoff-codes** [comment] 2015-05-03 08:33
That makes sense to me. While (above) I called the scope of the variables initialized in `config.fish` at startup the "top-level local scope", the fact that this is identical to the global scope makes sense to me (and I'm not sure I ever meant anything otherwise). I'm still not sure what the change in behavior is/was, but in my usage I almost never use `set -l`, so if it's behavior is different than in the past, I really wouldn't know. But as you say, the behavior in question that initiated this issue has nothing to do with that anyway, so no, for my part at least, I don't think there's anything to do for _this_ issue, per se. However, that doesn't mean that fish's variable scoping system isn't insanely complicated.

**Comment by zanchey** [comment] 2015-05-05 06:41
The text I have gone with so far is:

> A new "top-level" local scope has been added. The implications are subtle (#1908), but one important manifestation is that variables declared without `set -g` in `config.fish` may not behave as expected.

Any suggestions for improvement? Committers can edit the draft at https://github.com/fish-shell/fish-shell/releases/ directly.

**Comment by geoff-codes** [comment] 2015-05-05 10:28
So I've looked at the change more closely, and I'm not sure that's 100% it.

As I understand it, a "top-level local scope" *could* exist prior to this change, but only when explicitly declared as locally scoped, and therefore subject to block-level scoping rules, and somewhat transient in nature. Now, the top level local scope persists throughout the session, and this is the  scope of unscoped variable declarations, if they're not within a block or function.

Correct me if I'm wrong, but I think `man set` **does** need to be changed, in addition to the release notes (emphasis mine):

 > 3.  If a variable is not explicitly set to be either universal, global or local and has never before
         been defined, the variable will be local to the currently executing function. Note that this is
         different from using the -l or --local flag. If one of those flags is used, the variable will be
         local to the most inner currently executing block, while without these the variable will be local 
         to  the function. **_If no function is executing, the variable will be global._**

That is now incorrect. Now, the wording should be something lke "_If no function is executing, the variable will be local to top level of the session. Note that this is different from using the -g or --global flag, as these variables will not be accessible to functions._"

@ridiculousfish
> 1. When config.fish is sourced during startup, there's no local scope. All variables created within fish.config are therefore global.

This statement isn't _100%_ true: that is, one can `set -l` variables within `config.fish`, even if outside a function or block, and these variables do not persist into the environment (a feature I use quite a bit actually, like when constructing my $PATH variable). So I believe what you mean is "All _unscoped_ variables created within fish.config[sic] are therefore global." Correct?

I have to wonder if is really a desirable behavior in the long run (I know there might be some growing pains were this to be changed). But particularly as https://github.com/fish-shell/fish-shell/commit/7b12fd26f3d0ec2fe655cd537fda21f760e92d11 has fixed the "pollution of the global scope" from the command line issue, it seems like `config.fish` is **really** being treated as a special case. I would argue that *this* is the cause of confusion that initiated this issue originally (the "resource" function problem). Since unscoped variables are put into the global namespace when `config.fish` is first sourced, its not unreasonable to think that this is a property of the `config.fish` file, and that _whenever_ it is sourced, this aught to occur.

So I would argue that it would make a lot more sense to create the "top level local scope" _before_ `config.fish` is sourced on startup. This would make it pretty simple - the only variables ever in the global scope would those initialized or reinitialized with `-g`. And, unscoped variable declarations would _always_ initialize local variables, if the variable hasn't already been declared in another scope.

So @zanchey at present, I'll give a shot at the release notes, as I understand it:

> A top level local scope is now always initialized at startup, immediately after `config.fish` is read.
> The implications of this change are:
  - Variables declared with `set -l`, outside any function or block, no longer erroneously end up with global scope.
  - As in any other local scopes, _unscoped_ variable declarations, outside any function or block, **except any declared in `config.fish` on initialization**, are "local" to the top level, and therefore are inaccessible to functions, etc.

**Comment by ridiculousfish** [comment] 2015-05-05 19:03
@geoff-codes Thanks for your considered write-up. I realized what I wrote up before is incorrect.

Let me respond:

> As I understand it, a "top-level local scope" could exist prior to this change, but only when explicitly declared as locally scoped

Right. If you ran `set -l var val` at top level, a local scope would be created for the extent of that command, and destroyed at the end. So you had this:

    > set -l abc 1 2 3
    > count $abc
    0

which is sort of silly.

> Now, the top level local scope persists throughout the session, and this is the scope of unscoped variable declarations, if they're not within a block or function

No, this is not the new behavior. The new top level scope is like the scope established by begin/end, not like a function. The behavior of unscoped variables at the top level is the same as before: they become globals.

The change is that, in my example above, `abc` would go into the new perma-local scope, so it would be visible to other commands run at the same scope, like the following `count`. But it would not be visible to called functions (nor was it previously).

> If no function is executing, the variable will be local to top level of the session. Note that this is different from using the -g or --global flag, as these variables will not be accessible to functions (as global variables are)

No, unscoped variables at the top level really do become globals, as before.

> So I would argue that it would make a lot more sense to create the "top level local scope" before config.fish is sourced on startup

Agreed, and in fact this is what it does; I just got it wrong.

Let me go correct my comment above and then I'll take a whack at the relnote description.

**Comment by geoff-codes** [comment] 2015-05-05 19:24
> No, unscoped variables at the top level really do become globals, as before.

Oh geez. Well, that's what I get for doing that write-up at 3:30AM . I could have sworn I had tested it and saw what I described above. But lo and behold...

**Comment by ridiculousfish** [comment] 2015-05-18 00:17
My relnote text is:

    A new "top-level" local scope has been added, allowing local variables declared on the commandline to be visible to subsequent commands.

Speak up if you think it's wrong / insufficient. Thanks!

**Closed by ridiculousfish** 2015-05-18 00:17 UTC
