### ISSUE TITLE
Enable noclobber globally

### ISSUE THREAD

**Issue by dancojocaru2000** [fish-shell/fish-shell#7072] opened 2020-06-01 15:26 UTC
How can I enable noclobber globally in fish?

I just destroyed a script file by accidentally using `>` instead of `|` and now I want to disable `>` overwriting existing files. How can I do that?

And also, because I really need to vent this out, **fuck**, here goes a day of work down the drain.

**Comment by faho** [comment] 2020-06-01 15:42
You don't.

This isn't the kind of setting we offer - it creates global differences in dialect that are hard to reason about.

I'm terribly sorry but really, all I can suggest is keeping copies of your work. E.g. use `git` and commit early and often.

**Comment by dancojocaru2000** [comment] 2020-06-01 15:45
What is hard to reason about?

Also, I was using git. However, it makes zero sense to make a commit saying "changed line 13" then another commit saying "changed line 14".

I was testing the script before making the damn commit and disaster happened.

**Comment by dancojocaru2000** [comment] 2020-06-01 15:49
And also, I'm sorry if I come mean (although I probably am considering my mood is gone), but suggesting keeping copies is a step below suggesting to not type `>` next time.

**Comment by faho** [comment] 2020-06-01 15:57
What I mean is that it is like e.g. "failglob" in that it is an option that you can enable *SOMEWHERE* and it will change the meaning of a line:

```fish
echo foo > bar
```

will this overwrite bar or not? Without a global noclobber option, that's easy: Yes. But if you introduce it, you need to suddenly check if it's on or not.

And e.g. if you copied a script from someone else, you'd have to hope they didn't plan on it working the other way around.

That's why we, as a general rule, don't *do* options like that.

**Comment by dancojocaru2000** [comment] 2020-06-01 15:58
**OH FUCK OH FUCK YEAH THANK GOD!**

I had my text editor open and it didn't clear the undo buffer!!! PFEW!

---

That aside, I still think this needs to be a feature in order to prevent accidents in the future.

I see no cases where this would be a problem.

Script assuming `>` is override?

- interactively ask the user what to do
- stop the script and ask the user to `rm` the file

On top of that, I would rather have scripts I have to edit by adding a `rm` than losing my work.

---

Another idea would be for fish to keep backups of it's own of files overwritten by `>`, but I'm pretty sure that'll be a deadend considering many people will probably dislike the idea.

**Comment by faho** [comment] 2020-06-01 16:03
>I see no cases where this would be a problem.

You lack imagination.

There are a ton of cases where you want to override a file, and changing the behavior of `>` breaks all of them.

>I am extremely willing to sacrifice scripts not working for not losing work.

Okay, we're not. Mainly because scripts, you know, do work.

> interactively ask the user what to do
  stop the script and ask the user to rm the file

That assumes the script was written with that in mind - in which case it could also just turn the knob the way it wants. The problem is that it's hard to remember and another chore to do when writing a script.

>Also, perhaps a command could be added to temporarily run scripts without the noclobbing enabled?

You didn't remember to run it with noclobber now, why would you remember to run it with then?

-----

Glad you could recover your work. Closing!

**Closed by faho** 2020-06-01 16:03 UTC
Labels: question

**Comment by dancojocaru2000** [comment] 2020-06-01 16:09
The suggestion about interactively asking the user what to do would be about fish itself pausing the script execution when overriding behaviour is met and asking the user what to do, not the script.

Basically not being JavaScript and skipping errors in a script, but erroring out.

> You didn't remember to run it with noclobber now, why would you remember to run it with then?

And I don't need to remember. That's like not remembering to run a command with `sudo`. No big deal, I see the error, I run with `sudo` again.

> Okay, we're not.

But why do you have to be? The option existing and not being enabled by default makes no changes to default assumptions. If I enable the option, it would be my responsibility to deal with what happens. And, once again, reiterating my `sudo` point, there is close to no effort just running a script again with that command when an error pops up.

**Comment by ridiculousfish** [comment] 2020-06-01 18:31
I'm sure this was a frustrating experience, I too have lost data in similar ways. Unfortunately there are so many such foot-guns in Linux.

As faho says, fish is philosophically opposed to supporting configuration options like these. I think the right approach here would be global abbreviations (see #5003); this would allow you to perform syntactic changes to what you enter interactively.

**Comment by rrthomas** [comment] 2026-08-31 21:02
As someone who used the `noclobber` bash option for some years before switching to fish, I'm sad this is not considered "fishy". I found it invaluable. I guess I'll have to get used to typing `>?`, but I find the lack of a global "noclobber" more of a footgun (which is why I enabled it in bash in the first place).
