### ISSUE TITLE
fish shell will cause a problem when using tmux

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4468] opened 2017-10-11 09:26 UTC
- fish, version 2.6.0
- Linux chz 2.6.32-431.el6.i686 #1 SMP Fri Nov 22 00:26:36 UTC 2013 i686 i686 i386 GNU/Linux
- $TERM: xterm or xterm-256color

It is the same result in following situations:
1. I use my configuration in ~/.config/fish
2. Delete that ~/.config/fish and use default configuration provided by fishshell
3. sh -c 'env HOME=$(mktemp -d) fish'

Check the details: https://github.com/tmux/tmux/issues/1109

**Comment by zanchey** [comment] 2017-10-11 13:57
What's the output of `locale -a`? I suspect that may be part of the problem.

**Comment by zanchey** [comment] 2017-10-11 14:03
I can't reproduce this locally on OS X with iTerm, but I can over SSH or Mosh to Linux.

**Comment by c02y** [comment] 2017-10-12 01:11
> What's the output of locale? I suspect that may be part of the problem.

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by zanchey** [comment] 2017-10-13 14:43
Bisects to 616d301083b925632cd39ff719caad0d973c29a5 - regression between 2.5.0 and 2.6.0.

**Comment by ridiculousfish** [comment] 2017-10-13 16:52
@zanchey can you please post the steps you used to reproduce?

**Comment by zanchey** [comment] 2017-10-13 23:15
Sure - I use iTerm 2 on OS X, but SSH (or mosh) to a Debian Linux 8 machine.

Create a directory (`mkdir abc漢字`) and change into it (`cd abc漢字`); observe the terminal title.

**Comment by c02y** [comment] 2017-11-03 08:26
I can get around this issue by modifying the .tmux.conf  file:
from 

    set -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] ""\"#(echo #{pane_title} | sed \"s#$HOME#~#g\")\""

to 

     set -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] ""\"#(echo #{pane_current_path} | sed \"s#$HOME#~#g\")\""

i.e., change `pane_title` to `pane_current_path`.

**Comment by mqudsi** [comment] 2018-03-09 20:21
I can't reproduce this locally or over ssh with fish 3.0 and tmux 9b1f620aa017bb3634b3806e959580cde75ec655

@c02y @zanchey does this still reproduce?

**Comment by zanchey** [comment] 2018-05-29 06:39
Not any more with fish 2.7.1 or 2.7.1-1223-g23eb63eb, so I think we can close as resolved in 2.6.0.

**Closed by zanchey** 2018-05-29 06:39 UTC
Labels: bug, regression
