### ISSUE TITLE
fish 3.0 in ssh session has some git bugs.

### ISSUE THREAD

**Issue by latiaoxia** [fish-shell/fish-shell#5578] opened 2019-01-24 03:11 UTC
fish, version 3.0.0
server OS: 4.8.0-36-generic #36~16.04.1-Ubuntu SMP

When I ssh login ubuntu server to fish, in the git repo, typing `git add .<tab>` will cause some wrong matches:
```
~> git add .<tab>
../../../.cache/  (Untracked file)  ../../../.config/  (Untracked file)  :/.cmake/   (Untracked file)
../../../.cmake/  (Untracked file)  :/.cache/          (Untracked file)  :/.config/  (Untracked file)
```
`../../../*` are the wrong matches.

And fish in local linux os does not have such issue, only in remote ssh login session.

**Comment by faho** [comment] 2019-01-24 07:58
The issue is that your remote git is old and doesn't support `status --porcelain=2`, so we fall back to the v1 format, which doesn't give us relative paths, so we have to compute them ourselves (which is a right PITA).

The code that did that had a bug if you're in the git root (where it should have done nothing).

I've fixed this, incidentally, in 4af2a681b8fa69a12da9ab8015474841d15e26a9. Which will be in the upcoming 3.0.1 release.

**Closed by faho** 2019-01-24 07:58 UTC
