### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by maxnordlund** [fish-shell/fish-shell#2760] opened 2016-02-25 01:33 UTC
I realized today that the current stable fish is [~600 commits][1] and [~7 months][2] behind master.

I think it might be time to cut a new release. While I'm in the release early, release often camp, I do think it's about time in this particular case.

[1]: https://github.com/fish-shell/fish-shell/compare/2.2.0...master
[2]: https://github.com/fish-shell/fish-shell/releases/tag/2.2.0

**Comment by zanchey** [comment] 2016-02-25 03:07
We can use this as a tracking bug, I guess?

Looking through the issues in https://github.com/fish-shell/fish-shell/milestones/next-2.x:

 [ ] I definitely want to get #2113 sorted out before another release (#1956 / #2498 is related and will need further work extending it).

Other issues I am less attached to.

@krader1961 has been doing awesome work on pull requests and it would be nice to have a decision on all of those before the next release.

**Comment by jrobeson** [comment] 2016-02-25 03:15
Are there any issues that should be labeled as regressions ? If so, those should make the docket too

**Comment by zanchey** [comment] 2016-02-25 03:29
@jrobeson I did have a look through and there aren't any outstanding that I can see.

**Comment by krader1961** [comment] 2016-02-25 05:10
My primary project at $dayjob does a release every week excluding weeks with holidays. Obviously that isn't practical for an open source project like fish that relies on volunteers but I do think we should be issuing minor releases at least twice a year and preferably four, or more, times a year. If the problem is that there's a lot of manual labor involved I'd ask how much of that effort could we eliminate through a one time investment in creating some automation.

As for outstanding pull requests the only one I'd like to see merged before a build is https://github.com/fish-shell/fish-shell/pull/2713 to reduce the range of Unicode private-use chars that fish reserves. Even without part two of that change to ensure such chars can't pass through the parser just reducing and moving the range of reserved chars will make a few people who have been bit by them happier. No one has given any feedback on the change so I'm tempted to just merge it.

All of the other changes either don't need to be in a point release (e.g., my hermetic test change) or are controversial and/or have other problems (e.g., the /etc/locale.conf support PR). The one exception would be https://github.com/fish-shell/fish-shell/pull/1675 to update the Brazilian Portuguese language support.

**Comment by krader1961** [comment] 2016-02-25 06:37
Regarding the **next-2.x** milestone issues shown by https://github.com/fish-shell/fish-shell/milestones/next-2.x at least one, https://github.com/fish-shell/fish-shell/issues/2664, should be fixed before the next minor release. Yes, I understand the user could avoid the race condition. The point is they shouldn't have to. Another one, https://github.com/fish-shell/fish-shell/issues/2090, should be relabeled to **next-major** because it will almost certainly involve backward incompatible changes.

**Comment by faho** [comment] 2016-02-25 13:40
I've just closed #2664 since, to the best of my knowledge, that issue has been fixed. There might be more like it but I can't find any. Also marked it in zanchey's comment.

**Comment by jrobeson** [comment] 2016-02-25 23:11
what's left for #2498 ?

**Comment by faho** [comment] 2016-02-26 00:57
@jrobeson: For someone to merge it. I'll try to get to it tomorrow.

**Comment by faho** [comment] 2016-02-26 00:59
Unless it can be easily adapted to fix #2113 as well.

**Comment by pickfire** [comment] 2016-02-26 06:01
Why so fast? Do it slowly, if would be troublesome if there is a major bug found after releasing fish.

**Comment by faho** [comment] 2016-02-26 11:16
2498 is merged now.

**Comment by faho** [comment] 2016-02-29 10:18
Marked #2713.

**Comment by jrobeson** [comment] 2016-03-05 06:27
looks like #1675 should be removed from the list, since the PR was closed without being merged

**Comment by krader1961** [comment] 2016-03-05 18:25
> looks like #1675 should be removed from the list

Correct. It appears most, if not all, of those changes were made on 2015-10-11 with https://github.com/fish-shell/fish-shell/commit/6e3ea5b2eab26ce2006d59c3a5829e87d05d4bc4 so simply building from head will implicitly include the improvements that were part of #1675.

**Comment by maxnordlund** [comment] 2016-03-05 22:13
OK, so looks like it's just the Homebrew vendor issue left. If it isn't something that can be easily implemented, maybe it should be left for this release?

And instead try to follow up with another one slightly quicker this time :wink:

**Comment by ridiculousfish** [comment] 2016-03-05 22:32
#2784 definitely needs to go in. I'm working on that.

**Comment by maxnordlund** [comment] 2016-03-05 22:54
Sweet, thanks for letting us know :bow:

**Comment by zanchey** [comment] 2016-03-06 13:36
I've renamed the next-2.x milestone to 2.3.0 and created a new next-2.x milestone, so it's time to start pushing issues out of the 2.3.0 milestone.

I'd like to ask @fish-shell/contributors to look through the list at https://github.com/fish-shell/fish-shell/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3.0 and either assign yourself, tag someone to have a look or change the milestone. Of course, if you're not sure then feel free to start the discussion about whether it's realistic.

I'd like to aim for a beta in the next few weeks, with a full release a fortnight after that - depending on @ridiculousfish's schedule.

**Comment by faho** [comment] 2016-03-06 14:10
10 issues left - #2215 in particular still requires some looking into because it was supposed to be fixed but seems like it isn't on at least one machine.

**Comment by krader1961** [comment] 2016-03-22 03:47
I've pruned a few issues from this release milestone that do not appear to be critical. The only one without a clear path forward is issue #952. In particular it doesn't have an owner. I've started doing some debugging but as a new contributor it's going to take me a lot of time to diagnose and fix this. Should #952 block the 2.3.0 release? If so is anyone willing to take ownership of that issue?

**Comment by Starefossen** [comment] 2016-03-24 20:53
1+ for pruning issues from the milestone in order to get a new release out as soon as possible.

**Comment by zanchey** [comment] 2016-04-08 02:41
We have a fix for #952 in #2912, and I'm merging #2770 now.

**Comment by webwurst** [comment] 2016-04-14 10:52
This feels soo close! Can someone give it a push? :stuck_out_tongue_winking_eye:

**Comment by floam** [comment] 2016-04-14 10:54
https://github.com/fish-shell/fish-shell/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3.0

**Comment by faho** [comment] 2016-04-14 10:59
Or rather just #2453 - the other two are going to be fixed by releasing.

@ridiculousfish: Are you still working on that one?

**Comment by krader1961** [comment] 2016-04-29 03:58
My apologies, @zanchey, I just noticed that the `fish_escape_delay_ms` default for Vi mode is wrong. It should be 100 ms rather than 10 ms. Please cherry-pick commit 3e24ae80b3739ded7d4066349fc87d13f2b70727.

**Comment by krader1961** [comment] 2016-04-29 04:19
And if the release depends on the unit tests passing you'll need commit 5092904ea3a95c6ba78350c3b3761511f613fde8 as well to fix the bind unit test I broke with my previous commit.

**Comment by ridiculousfish** [comment] 2016-04-29 22:55
I cherry-picked those two commits. Thanks!

**Closed** 2016-05-20 23:32 UTC
