### ISSUE TITLE
Strange paste result 

### ISSUE THREAD

**Issue by wd** [fish-shell/fish-shell#7779] opened 2021-03-05 13:11 UTC
Version: 3.2.0
Darwin Dongs-Mac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

In Terminal.app: xterm-256color
In Kitty+tmux: screen-256color

# Test results

Copy codes below, and press `cmd+v` many times in the terminal. May be related with https://github.com/fish-shell/fish-shell/pull/7662
```
echo '
    indented
```

##  Terminal.app

![image](https://user-images.githubusercontent.com/58177/110119557-f291cb80-7df6-11eb-999f-1c879e346ce4.png)

##  Kitty + tmux

With my custom setup

![image](https://user-images.githubusercontent.com/58177/110119685-1d7c1f80-7df7-11eb-9f7f-7771ea730923.png)

**Comment by wd** [comment] 2021-03-05 13:14
This is what I got in fish 3.1.2

![image](https://user-images.githubusercontent.com/58177/110120222-bad75380-7df7-11eb-8af5-caddcb7e40cb.png)

**Comment by faho** [comment] 2021-03-05 13:16
Duplicate of #7770

**Closed by faho** 2021-03-05 13:16 UTC
