### ISSUE TITLE
Text formatting broken with multiline command (begin/end block) larger than terminal dimensions

### ISSUE THREAD

**Issue by andmis** [fish-shell/fish-shell#8693] opened 2022-02-04 12:13 UTC
![Feb-04-2022 07-08-16](https://user-images.githubusercontent.com/5308024/152526841-c1b2371e-59b6-4efd-84e7-59d2c2588c38.gif)

This is on macOS 12.1. That recording is in the latest iTerm2, but I get the same behavior in Terminal.app. The recording was with `fish, version 3.3.1-828-gec4eccce3`, but I get the same behavior with a fish built from source from a recent checkout.

**Edit:** I get the same behavior with `fish -N`.

**Comment by krobelus** [comment] 2022-02-04 13:45
Duplicate of #7296

**Closed by krobelus** 2022-02-04 13:45 UTC
