### ISSUE TITLE
rmdir doesn't correctly complete directory names with a newline

### ISSUE THREAD

**Issue by gregorias** [fish-shell/fish-shell#9693] opened 2023-03-28 11:54 UTC
`rmdir` doesn't correctly complete directory names with a newline

## Reproduction steps

1. Run the following script with source

```fish
cd (mktemp -d)
mkdir 'foo
bar'
```

2. Type `rmdir ` and press Tab.

Fish will suggest `bar`

## Expected Output

Fish suggests:

```
foo
bar
```

## Environment

* Fish: 3.6.1
* OS: macOS
* `uname -a`: Darwin Grzegorzs-MBP 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
* Terminal: Kitty

## Additional details

`rm -rf` works correctly and completes to `foo\nbar`.

**Comment by faho** [comment] 2023-03-28 12:12
Yup, scripted completions like rmdir split their results on newlines. Specifically in this case `__fish_complete_directories` invokes `complete --do-complete`, which already loses them.

I would recommend against filenames with newline as it stands (and tbh I'd love to have them forbidden by the system entirely, there have been proposals).

I'm closing this as a duplicate of #751 because that's what would be needed to replace the `complete --do-complete` here - `__fish_complete_directories` was already mentioned there.

**Closed by faho** 2023-03-28 12:12 UTC
