### ISSUE TITLE
fish_add_path log at start

### ISSUE THREAD

**Issue by vorticalbox** [fish-shell/fish-shell#8726] opened 2022-02-14 08:15 UTC
Please tell us which fish version you are using by executing the following:

version: 3.1.2
OS: Linux pop-os 5.15.15-76051515-generic

I recently updated fish and it is no logging this every time I start my terminal 

```
/usr/share/fish/vendor_conf.d/snapd.fish (line 3): 
fish_add_path -aP $snap_bin_path
^
from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish
	called on line 294 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup
```

**Comment by faho** [comment] 2022-02-14 09:03
Duplicate of #8713

**Closed by faho** 2022-02-14 09:03 UTC
