### ISSUE TITLE
fish in emacs ansi-term prints an extra "⏎"

### ISSUE THREAD

**Issue by brabalan** [fish-shell/fish-shell#1411] opened 2014-04-14 20:32 UTC
I use fish in an ansi-term in emacs. After each command, I get an extra "⏎" character printed. As can be seen in the copy and paste below, it seems that a newline is not created (or the line is not moved back to the beginning).

```
schmitta@top ~> echo foo
foo
⏎                                                                                                 schmitta@top ~> 
```

In my emacs window, the last prompt is on the left of the window, and there is a small indicator in the fringe that the line wrapped.

I'm using GNU Emacs 24.3.1 (x86_64-apple-darwin13.0.0, Carbon Version 1.6.0 AppKit 1265) and fish version 2.1.0. I moved away my ~/.config/fish directory before testing, so (unless there are configuration variables I don't know about) this should work on a fresh installation.

**Comment by faho** [comment] 2017-01-07 15:51
This works for me with emacs 25.1.1 and fish >= 2.4.0.

I'm closing unless someone else can reproduce it still.

**Closed by faho** 2017-01-07 15:51 UTC
Labels: bug

**Comment by warsaw** [comment] 2019-02-28 01:19
As I'm just starting to play with fish in Emacs 26.1, I landed on this issue.  `toggle-truncate-lines` definitely helps with weirdness I'm seeing in `ansi-term` (extra newlines), it's not a perfect solution.   Each time I hit `RET` at a fish prompt, I can see the `*ansi-term*` buffer gets a little longer at the end of the buffer.  It's like the newlines are getting added there.  

I'm using fish 3.0.2 from Homebrew on macOS with Emacs 26.1
