### ISSUE TITLE
macOS 11.1: slow command autocompletion

### ISSUE THREAD

**Issue by caarlos0** [fish-shell/fish-shell#7641] opened 2021-01-20 14:42 UTC
Fish:
```
fish, version 3.1.2
```

OS:
```
Darwin Carloss-MacBook-Pro-21983.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

TERM:
```
xterm-256color
```

Bug also reproducible with `sh -c 'env HOME=$(mktemp -d) fish'`.

Its pretty much the same thing as https://github.com/fish-shell/fish-shell/issues/6270, but on newer macOS.

---

```
sh -c 'env HOME=$(mktemp -d) fish --profile /tmp/kube -c \'__fish_describe_command kube\''
```

and then, using `sort -nk 2 /tmp/kube`, we see the offender is:

```
# skipped some lines for brevity
2126	2126	----> uname
122	2248	---> test (uname) = Darwin
15	4008	--> if test (uname) = Darwin
171	4191	-> source /usr/local/Cellar/fish/3.1.2/share/fish/functions/__fish_describe_command.fish
1341	5018	> builtin source /usr/local/Cellar/fish/3.1.2/share/fish/config.fish
1158266	1158266	-> apropos $argv 2>/dev/null | awk -v FS=" +- +" '{
159	1164507	> __fish_describe_command kube
```

**Comment by faho** [comment] 2021-01-20 14:45
Duplicate of #7511

**Closed by faho** 2021-01-20 14:45 UTC
