### ISSUE TITLE
No way to configure system PATH with higher priority than vendor PATH

### ISSUE THREAD

**Issue by anka-213** [fish-shell/fish-shell#7142] opened 2020-06-21 15:26 UTC
This is a duplicate of #5641, which was (incorrectly?) closed and locked as a duplicate. That issue is not fixed, but the issue it was marked as a duplicate of (#5456) is fixed, closed and locked.

One possible way to resolve this, hopefully without breaking other stuff (e.g. #5956), would be to check if all paths it would add are already present int PATH and then do no reordering, but do the normal reordering if it would add anything. I'm not sure if this is a resonable solution though.

My use-case is mostly the same as #5641.  I want to be able to use fish with [nix-darwin](/LnL7/nix-darwin) without having a broken `PATH` (broken in the sense that the system packages has a higher priority than those that I manually installed with nix).

Currently, my only workaround is to override the nix config to set the path both before and after loading `share/fish/config.fish`, which feels like a very ugly hack, and might not work in all cases (see the [motivation mentioned in the nix package for fish](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/fish/default.nix#L58-L61)). That is, I want some solution to https://github.com/LnL7/nix-darwin/issues/122.

**Comment by faho** [comment] 2020-06-21 16:37
#5641 was marked as a duplicate under the assumption that the underlying problem was fish's /etc/paths.d handling reordering $PATH, which was fixed in #5456.

Now, since fish 3.1, it should no longer be doing any reordering for that.

What I would really like to know is what exactly is insufficient for you here?

You can set $PATH via /etc/paths, you can set it via $fish_user_paths, you can set it directly. Where is the problem? Where is nix-darwin setting the path?

**Comment by anka-213** [comment] 2020-06-21 17:41
Which commit was it that fixed #5456? That is a bit unclear with all the reverting and stuff that happened. Anyways, the problem is specifically for login shells, which was not addressed in that issue.

Nixos and nix-darwin sets `PATH` by importing a shell-agnostic environment variable script from in `/etc/fish/nixos-env-preinit.fish`([darwin-nix](https://github.com/LnL7/nix-darwin/blob/2412c7f9f98377680418625a3aa7b685b2403107/modules/programs/fish.nix#L113), [nixos](https://github.com/NixOS/nixpkgs/blob/4a8a2145d782e2c7b1f1687f5c1e3a394d542b2e/nixos/modules/programs/fish.nix#L116)) which is called by `/nix/store/some-hash-fish-3.1.2/share/fish/__fish_build_paths.fish` ([here](https://github.com/NixOS/nixpkgs/blob/838822a2e52d8b217711b7e573c5e347139f02e7/pkgs/shells/fish/default.nix#L192) and [here](https://github.com/NixOS/nixpkgs/blob/838822a2e52d8b217711b7e573c5e347139f02e7/pkgs/shells/fish/default.nix#L65)) before `/nix/store/some-hash-fish-3.1.2/share/fish/config.fish` is called. I think this is needed in order to make sure that ["config snippets can find the commands they use on the PATH"](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/fish/default.nix#L61). I think the config snippets are included from there according to the comments https://github.com/fish-shell/fish-shell/issues/2950.

**Comment by faho** [comment] 2020-06-21 18:48
Ah, okay. I think I see what happens here.

This uses `__fish_build_paths`, which is ordinarily meant for $fish_function_path and $fish_complete_path, so they can be set at compile-time.

It is sourced *super early*, before any other changes to $PATH.

So this changes $PATH. Presumably it would put the paths at the correct place (what does it look like on your end?), but then later /etc/paths comes in and the paths there take precedence. Any *new* paths are added before any old paths (things in /etc/paths that are already included should not be reordered).

Then $fish_user_paths is evaluated and comes before *that* (and any paths in $fish_user_paths are moved to the front), so the __fish_build_paths paths are pushed back after all those.

This generally makes sense - it's user > admin > system, i.e. $HOME > /etc > /usr.

But if any paths that shouldn't take precedence over __fish_build_paths are in /etc/paths or $fish_user_paths, they are of course put before them and cause trouble.

I would assume that's the case.

So there's a few solutions here:

- Remove the offending paths from /etc/paths or $fish_user_paths - this is probably not viable for nix
- Add the nix paths to /etc/paths - this might be viable for nix-darwin
- Use a configuration snippet. Call it "00-nix.fish", put the path manipulation there. This is clean, simple and does what you want. It can be kept out of sight of users by putting it in the system conf.d
- Use $fish_user_paths - this is more visible to the user and can cause issues should they erase the variable
- Use /etc/fish/config.fish - this is semi-visible to the user, and only works *after* the snippets, so it's probably not viable
- Patch share/config.fish to add in $PATH changes later - note that we don't want __fish_build_paths later because that's needed to find our *functions*, of which we execute a few in share/config.fish

I don't think this needs any changes in fish proper.

**Comment by anka-213** [comment] 2020-06-21 19:45
@faho 
> Any _new_ paths are added before any old paths (things in /etc/paths that are already included should not be reordered).

If I understand you correctly, this does not seem to be true. The `PATH` that nix-darwin provides to to fish in `/etc/fish/nixos-env-preinit.fish` already contains all the paths in /etc/paths, but they are still reordered to go into the front for me.

This path is given by nix
```
/Users/anka/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /usr/sbin /bin /sbin
```
which is reordered by fish to this
```
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Users/anka/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin
```
`/etc/paths` contains this:
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by faho** [comment] 2020-06-21 20:06
>If I understand you correctly, this does not seem to be true.

Which fish version?

**Comment by anka-213** [comment] 2020-06-21 20:10
> Which fish version?
3.1.2

**Comment by faho** [comment] 2020-06-21 20:11
Ah, okay, no. I was wrong - if a thing is in /etc/paths it *will* be moved to the front. This matches what apple's path helper does so it is correct.

The problem is then that the nix path is set *before* that, so the solution stays the same.

**Comment by zanchey** [comment] 2020-06-23 13:36
Is there something fish should do differently here, then?

**Comment by faho** [comment] 2020-06-23 17:53
I would imagine the nix folks would like an additional file that is read just before the snippets but after /etc/paths.

But tbh it's a super easy patch and not of use for anyone else, and we don't really want to add fifty customization points here, so I'm not sold on carrying that "fish_build_paths_2" here.

(
The snippet solution also won't really work as it is because the user snippets are read *first*. That might be a different issue.
)

**Comment by zanchey** [comment] 2020-08-07 13:43
Sounds like there's not a general solution here that needs implementing then.

**Closed by zanchey** 2020-08-07 13:43 UTC
Labels: needs more info

**Comment by lilyball** [comment] 2021-11-17 22:09
@faho There unfortunately isn't a good solution that doesn't require modifying Fish. `/etc/paths.d` doesn't work because anything in there is lower priority than the `/etc/paths` file, so nix-darwin still gets the wrong path order. A configuration snippet is also bad because it'll run _after_ any user config files but we need the environment set up before any user config runs. `$fish_user_paths` actually works (it's what I'm doing locally) but it means modifying a variable that's supposed to belong to the user, and this will break if a user unconditionally overwrites it.

I understand the resistance to adding a lot of customization points. The problem is that there is _no_ customization point after Fish modifies the PATH and before the user's config starts running. For Bash, the `path_helper` stuff comes first before anything else, and any code added to `/etc/profile` or `/etc/bashrc` will run in between that and the user config. But there's simply no equivalent in Fish.

My personal preference here is to add a simple hook after the `path_helper` logic but before calling `__fish_reconstruct_path`. This could just be an event that it emits, `emit __fish_config_path_helper_post`.

Alternatively, it could check if `__fish_macos_set_env` already exists before defining it, such that we can define our own version and it will be invoked instead. I don't like this as it requires reimplementing the `path_helper` logic though, but it would certainly work.

Without a change like this done to Fish proper, the only real solution that nix-darwin can do is patch `share/config.fish`, which not only means keeping a patch up-to-date, but also means forcing nix-darwin users to compile Fish from source unless the patch can be upstreamed into nixpkgs proper.

**Comment by faho** [comment] 2021-11-17 22:28
Please keep it as a distro patch, this is not a customization point we want to have.
