### ISSUE TITLE
snapd.fish (line 3) when I open terminal

### ISSUE THREAD

**Issue by terthesz** [fish-shell/fish-shell#8721] opened 2022-02-12 13:58 UTC
fish --version: fish, version 3.1.0
echo $version: 3.1.0

uname -a: Linux ubuntu-pc 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux <br/>
echo $TERM: xterm-256color

Every time I open a new terminal window this error shows up: <br/>
`/usr/share/fish/vendor_conf.d/snapd.fish (line 3): 
fish_add_path -aP $snap_bin_path
^
from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish
	called on line 294 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup`

the same thing happens when I use gish without third-party customizations

**Comment by zanchey** [comment] 2022-02-12 14:04
Duplicate of #8713

**Closed by zanchey** 2022-02-12 14:04 UTC
Labels: duplicate
