### ISSUE TITLE
File completion not working for git status

### ISSUE THREAD

**Issue by pikeas** [fish-shell/fish-shell#9071] opened 2022-07-13 17:04 UTC
Fish version: 3.5.0
OS: MacOS 12.3.1
TERM: xterm-256color

Reproduction: `git status <tab>`

File completion works for other git commands, for example `git add`. Completion for `git status` works in Bash, so the issue seems scoped to Fish + `git status` only.

**Comment by faho** [comment] 2022-07-13 17:12
Duplicate of #9053

**Closed by faho** 2022-07-13 17:12 UTC
