### ISSUE TITLE
Fish won't let Tmux set the terminal title to the current path correctly in some cases

### ISSUE THREAD

**Issue by psychoslave** [fish-shell/fish-shell#7017] opened 2020-05-19 07:10 UTC
# Aim and snag

What I'm trying to achieve:
- on the narrow scope, having the the terminal window (GNOME-terminal in my case) to display the current path for the current Tmux pane of my Byobu session
- on a broader scope, deport as much as I can out of my prompt

So here is how I configured Tmux through `~/.config/byobu/profile.tmux`

```
source $BYOBU_PREFIX/share/byobu/profiles/tmux
set -g status-right '#(gitmux -cfg ~/.config/byobu/gitmux.conf) #{pane_current_path}'
set-option -g status-interval 1
set-option -g set-titles on
set-option -g set-titles-string '#{?#{==:#{host},localhost},#{host_short} -:,}#{pane_current_path}#{pane_current_path}'
set allow-rename off
set-option -g allow-rename off
```

- the expected behaviour: when running `cd /some/path`, the terminal title become "/some/path"
- the actual result: the terminal title *seems* stuck to "/home/psychoslave", but actually:
  - sometime, probably due to some execution lag, the right path briefly appears in the terminal title
  - running some persisting commands, such as `yes` or `vim` will let the terminal title be set properly, but this is not the case when running `read test` for example
  - actually, manually call `fish` will make the behaviour meet the expected one.

That is, as I have `chsh`ed to Fish, when I launch Byobu, Tmux will spawn fish sessions as I ask for more panes to be created. These sessions won't let the terminal title be set as expected. But if I run `fish` within one of them, then the terminal title is properly set as expected.

Note: even in such a case of an intertwined shell, my current configuration won't set the terminal title as I would like when I ssh to some remote server. This is *not* a part of this bug, as Tmux is not informed of this context change. However if you have some hint on how to pass to Tmux the user name, host name and distant path of an ssh session without adding them to the prompt, I would be delighted to read it.

# System information
```
fish --version && cat /etc/fedora-release && uname -a && echo $TERM && 
gnome-terminal --version && byobu --version
fish, version 3.0.2
Fedora release 31 (Thirty One)
Linux localhost.localdomain 5.6.11-200.fc31.x86_64 #1 SMP Wed May 6 19:10:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
screen-256color
# GNOME Terminal 3.34.2 using VTE 0.58.3 +BIDI +GNU
byobu version 5.133
tmux 2.9a
```

Note: I didn't included an asciinema. I guess it wouldn't capture the terminal title erroneous behaviour, or would it?

**Comment by faho** [comment] 2020-05-19 07:14
Duplicate of #5699

**Comment by faho** [comment] 2020-05-19 07:15
Yeah, tmux does *awful things* to get the current path. It should just support OSC7

**Closed by faho** 2020-05-19 07:14 UTC

**Comment by psychoslave** [comment] 2020-05-19 19:18
@faho: what is OSC7 in this context, please. :pray

**Comment by faho** [comment] 2020-05-19 19:34
It is an escape sequence that an application can send to the terminal to indicate its current working directory.

It is named this because it starts with the sequence known as "OSC" (short for "Operating System Command") - `\e]`, and then followed by a 7.

The idea being that the application simply writes that sequence to the terminal, which intercepts it and then knows the CWD.

Many terminals support it, including VTE (the backend of gnome terminal and plenty others) and iTerm.

[The changelog](https://github.com/tmux/tmux/blob/master/CHANGES#L343) says tmux has "simple support for OSC 7 (result is available in the pane_path format)", but I've not been able to confirm that.

Instead tmux opts for a hacky solution in which it reads /proc/$pid/cwd of the controlling process, and fish confuses it.
