### ISSUE TITLE
commandline regression starting from version 3.4

### ISSUE THREAD

**Issue by adrian-gierakowski** [fish-shell/fish-shell#8999] opened 2022-06-06 10:55 UTC
Following commands where ran from a docker container started with:
```sh
docker run --rm -it debian:unstable
```

```sh
> apt-get update && apt-get -y install fish lsb-release && fish
> fish --version && echo $version
fish, version 3.4.1
3.4.1
> uname -a
Linux 2e58a8ba6ff3 5.17.7 #1-NixOS SMP PREEMPT Thu May 12 10:32:48 UTC 2022 x86_64 GNU/Linux
> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	unstable
Codename:	sid
> echo $TERM
xterm
```

for example, in 3.3.x, running the following:
```sh
> commandline -r "echo hi > out && cat out"; commandline -f execute
```

would result in following:
```sh
> echo hi > out && cat out
hi
```

and the `out` file being created

however in 3.4.x I get an empty prompt and no file being created

While the above commands where tested in a debian based docker container, I get the same results running 3.4.0 and 3.4.1 on NixOS

**Comment by krobelus** [comment] 2022-06-06 11:19
Duplicate of #8807

**Closed by krobelus** 2022-06-06 11:19 UTC
