### ISSUE TITLE
Wrong Display Conflicting with TMUX

### ISSUE THREAD

**Issue by haodong** [fish-shell/fish-shell#5231] opened 2018-10-06 17:04 UTC
```
fish, version 2.7.1
MacOS 10.13.6
```
Problem: When splitting a pane into two vertically by tmux, those fish lines would display in wrong format. Just like the screenshot below.

![screen shot 2018-10-07 at 1 01 19 am](https://user-images.githubusercontent.com/8103074/46573785-9e3b5500-c9cc-11e8-8d36-4f061f5dfa2e.png)
![screen shot 2018-10-07 at 1 01 28 am](https://user-images.githubusercontent.com/8103074/46573787-a09daf00-c9cc-11e8-965d-911201374532.png)

The reason I'm suspecting the problem of fish is based on [this solution](https://superuser.com/a/1266581/407472). I tested on my machine and confirmed that bash (v3.2) is OK for this issue.

**Comment by faho** [comment] 2018-10-06 18:28
This looks like a duplicate of #1086.

**Closed by faho** 2018-10-06 18:28 UTC
