### ISSUE TITLE
History disappearing 

### ISSUE THREAD

**Issue by EvanTheB** [fish-shell/fish-shell#4931] opened 2018-04-20 05:49 UTC
fish, version 2.7.1

Linux dice01.local 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

xterm-256color

Hello,
I am experience history loss. I am logging in to a shared hpc system via SSH, it uses a 'panfs' mount for the user directory. The actual machine I am on is also a VM. 

panfs://10.0.0.100/ClusterHome/evaben on /home/evaben type panfs (rw,noauto,panauto,rmlist=(10.0.0.100;10.0.0.217;10.0.0.243),iscsi-sock-rsize=131072,callback-network-allow=10.0.0.0/255.255.0.0)

I am logged in with multiple SSH terminal windows, and a bit of tmux. The symptom I see is that approximately once per week, all my history disappears.

```
ll ~/.local/share/fish/
-rw-r--r-- 1 evaben g_dsg_clinical_genomics 1.4K Apr 20 15:46 fish_history
-rw------- 1 evaben g_dsg_clinical_genomics    0 Apr 20 15:24 fish_history.NB2ClH
-rw-r--r-- 1 evaben g_dsg_clinical_genomics  31K Mar 28 13:34 fish_history.QbM6S3
-rw-r--r-- 1 evaben g_dsg_clinical_genomics 7.2K Apr 17 17:54 fish_read_history
drwxr-xr-x 2 evaben g_dsg_clinical_genomics 4.0K Mar 26 14:56 generated_completions/
```

I had many lines of history, then everything is gone. There is also this older file 'fish_history.QbM6S3'. I don't know what is going on there.

Thanks

**Comment by EvanTheB** [comment] 2018-04-20 06:29
I am suspecting more that this issue may be more to do with panfs than fish. There are panfs files in this directory also, with the history contents I expect. So my history is recovered (hooray).

**Comment by mqudsi** [comment] 2018-04-20 15:01
@EvanTheB do you mean you found the contents of `fish_history` in a different file?

**Comment by ridiculousfish** [comment] 2018-04-24 17:31
Yes, most commands open the history file, write to it, and then close it.

Occasionally a command will trigger a "vacuum" (dedup + enforcing size limitation). The files like `fish_history.QbM6S3` are temporary files used during the dedup. The basic operation is to create the temporary file, write out the new contents, `rename()` it into place, and then `unlink()` the temporary file path for good measure. I think it's unlikely that a fish bug would leave these files around, though it's possible if fish were to crash or be killed during this operation.

**Comment by EvanTheB** [comment] 2018-04-26 01:30
Can anyone provide advice on enabling some logging around that process? I haven't used fish in any debug kind of mode before. Please point me to the source involved in the above and any debug mode compilation advice.

Thanks

**Comment by ridiculousfish** [comment] 2018-04-26 03:55
The relevant sources are in [history.cpp](https://github.com/fish-shell/fish-shell/blob/master/src/history.cpp)

You can enable some logging by invoking fish via `fish -d 2`. In particular that will report history errors that would otherwise be squelched. My suggestion is:

1. Run `fish -d 2`
2. Run 20 distinct commands (they have to be distinct), e.g. `echo 1` through `echo 20`. For most commands fish should report `save_internal no vacuum` which is the fast path, but eventually it will report `save_internal vacuum` which is the rewrite-the-file path. Are there any errors reported there?

That will be a good start for diagnosing this.

**Comment by faho** [comment] 2018-05-08 12:43
I'm assuming the question has been answered.

**Closed by faho** 2018-05-08 12:43 UTC
Labels: question

**Comment by EvanTheB** [comment] 2018-05-10 06:57
I am not seeing anything fishy with some limited testing as suggested by @ridiculousfish . I tried
    cat many_commands | fish -d 2
But this only produced 1 
    <2> fish: save_internal no vacuum: 2 ms
line. many_commands was just "echo 1\necho2..." in a file Is there an easy way for me to automate the entering of many commands?

**Comment by faho** [comment] 2018-05-11 12:34
>Is there an easy way for me to automate the entering of many commands?

We use [expect](http://www.nist.gov/el/msid/expect.cfm) for our test suite.

Alternatively, a low-tech solution is to copy-paste the commands.

E.g.

```fish
for i in (seq 0 1000)
    echo "echo $i"
end | xsel --clipboard
```

then paste it via your terminal. Though you have to turn off bracketed paste for this, otherwise fish won't _execute_ those commands, but build one massive commandline with all of them. So either do `functions -e __fish_enable_bracketed_paste` or start fish with `$FISH_UNIT_TESTS_RUNNING` enabled.

**Comment by EvanTheB** [comment] 2018-05-15 07:46
Thanks faho,
Perhaps related; fish is crashing a few times per day with message 'Bus Error'
I am trying to run with fish -d 2 to catch this error in the act, but no luck yet. The crash drops me back into bash. (I am ssh -> bash -> fish).

**Comment by faho** [comment] 2018-05-16 22:42
>Perhaps related; fish is crashing a few times per day with message 'Bus Error'

Should be, yeah. A SIGBUS can be caused by an `mmap()` that reads past the end of the file. We mmap the history file, so if your FS loses data, that'll cause it.

**Comment by ridiculousfish** [comment] 2018-05-22 02:37
Well if you `mmap()` a file and then the file later gets truncated, the past-the-end mappings give you zeros, not a crash. A bus error sounds like a real crash and if you can catch it in a debugger and provide a backtrace, that would be awesome!

**Comment by EvanTheB** [comment] 2018-05-28 01:39
Is it possible to direct -d output to a file? I would have it on all the time and catch this error if it weren't interrupting my autocompletes and program outputs

**Comment by ridiculousfish** [comment] 2018-05-28 03:12
That's a cool idea but I don't think it's possible yet. The whole debug output thing needs an overhaul.

**Comment by mqudsi** [comment] 2018-06-02 04:00
> That's a cool idea but I don't think it's possible yet. The whole debug output thing needs an overhaul.

See also #4818
