### ISSUE TITLE
`builtin realpath --no-symlinks` handles leading slashes incorrectly

### ISSUE THREAD

**Issue by mingcenwei** [fish-shell/fish-shell#8740] opened 2022-02-20 11:36 UTC
`builtin realpath --no-symlinks` doesn't collapse leading slashes. (see `tests/checks/realpath.fish`)
```shell
$ sh -c 'env --unset=XDG_CONFIG_HOME HOME=$(mktemp -d) fish'

$ builtin realpath -s ///bin # Expected: `/bin`
///bin

$ builtin realpath -s //bin # Expected: `/bin`
//bin
```
Environment
```shell
$ fish --version
fish, version 3.3.1

$ echo $version
3.3.1

$ uname -a
Linux HOSTNAME 5.16.8-arch1-1 #1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 GNU/Linux

$ echo $TERM
xterm-256color
```
Relevant files: `src/builtins/realpath.cpp`, `src/wutil.cpp`

**Comment by faho** [comment] 2022-02-20 19:23
Duplicate of #8281

**Closed by faho** 2022-02-20 19:23 UTC
