### ISSUE TITLE
Can't press enter after command launched with bind

### ISSUE THREAD

**Issue by TheHardew** [fish-shell/fish-shell#9858] opened 2023-06-21 20:30 UTC
fish, version 3.6.1
Linux pc 6.3.8-zen1-1.1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 15 Jun 2023 14:16:32 +0000 x86_64 GNU/Linux
xterm-256color
alacritty 0.12.1 (5fdfd47f) (also happens in foot version: 1.14.0 +pgo +ime +graphemes -assertions)

I have tried fish without customizations

I have ranger bound to \co

`bind \co ranger`

After bulkrename in ranger, I can not press the enter key.
To reproduce
```
bind \co ranger
cd (mktemp -d)
touch a b c

launch ranger with the key bind
press v to select all files
:bulkrename
change some text
save and close the file
save and close the file, again, this time it's a script that will be executed

files have been renamed, a message is displayed "Press ENTER to continue"
Enter does nothing
```

I have to close the whole terminal window
No asciinema since I can't save the recording.

**Comment by faho** [comment] 2023-06-21 20:38
Duplicate of #4772

**Closed by faho** 2023-06-21 20:38 UTC
