### ISSUE TITLE
fish syntax checker complains about abbr

### ISSUE THREAD

**Issue by markrian** [fish-shell/fish-shell#7452] opened 2020-11-05 12:03 UTC
If you run `fish -n` against a file that contains `abbr` calls, it complains about them.

For instance:

```fish
$ cat example.fish 
abbr --add foo "echo bar"

$ fish -n example.fish 
example.fish (line 1): 
abbr --add foo "echo bar"
^
```

Here's my version info:

```fish
$ fish --version
fish, version 3.1.0
$ echo $version
3.1.0
$ uname -a
Linux mfx1 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Note that sourcing the file works as expected:

```fish
$ source example.fish
$ foo # this gets transformed to echo bar on hitting enter
bar
```

**Comment by faho** [comment] 2020-11-05 12:06
Duplicate of #977

**Closed by faho** 2020-11-05 12:06 UTC
