### ISSUE TITLE
Issues rendering `\t` at the prompt

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#9323] opened 2022-11-01 01:12 UTC
* Pasting a literal tab to the prompt results in the tab being "physically" present but with 0 cells allocated to its width (try with `printf \t | fish_clipboard_copy` then ctrl+v)
* Afterwards pressing the up arrow or choosing the entry with the expanded tab in it from history gives a prompt where the tab *is* shown but fish thinks it has a width of 1 cell instead of 4 (or 2 or 8), throwing all calculations and cursor positioning thereafter.

Recording: https://asciinema.org/a/QEYLDJI6MIxo6SOKZaYYtje3l 
(`3` is typed then a tab is pasted for the first two prompts, then the up arrow is pressed once to retrieve the entry with the expanded tab from history and the right arrow key is repeatedly pressed until fish thinks the end of line is reached).

**Comment by faho** [comment] 2022-11-01 05:40
The problem here is that tab doesn't have one width.

It has the concept of "tab stops". A tab will expand up to the next tab stop, however far away this is. And tab stops can be configured.

Try this:

```fish
printf '%s\n' \tb a\tb aa\tb aaa\tb aaaa\tb aaaaa\tb aaaaaa\tb aaaaaaa\tb aaaaaaaa\tb
```

I'm afraid the best answer here is "don't use tabs".

**Comment by krobelus** [comment] 2022-11-01 06:23
Duplicate of https://github.com/fish-shell/fish-shell/issues/5274 I guess.
This is not an inherent problem of tab characters, fish just doesn't implement them.
We should fix this and handle tabs like a text editor would. In particular, a tab in a text editor always has at least width 1, never zero. Of course it's not completely trivial and the workaround of not using tabs is easy.
I sometimes paste commands with leading tabs, we even have a workaround for that in fish_clipboard_paste.

**Comment by faho** [comment] 2022-11-01 21:52
Closing in favor of 5274 then.

**Closed by faho** 2022-11-01 21:52 UTC
