### ISSUE TITLE
`echo a | pv | grep a` sometimes takes forever

### ISSUE THREAD

**Issue by Mizuchi** [fish-shell/fish-shell#4643] opened 2018-01-05 05:06 UTC
Steps to reproduce: 

just run `echo a | pv | grep a` multiple times. I don't have this issue with bash. for example:

```
[ytj@archlinux ~]$ echo a | pv | grep a  # this is bash
2.00 B 0:00:00 [63.0KiB/s] [<=>                                 ]
a
[ytj@archlinux ~]$ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
ytj@archlinux /h/ytj> echo a | pv
a
2.00 B 0:00:00 [ 150KiB/s] [<=>                                 ]
ytj@archlinux /h/ytj> echo a | grep a
a
ytj@archlinux /h/ytj> echo a | pv | grep a
2.00 B 0:00:00 [50.1KiB/s] [<=>                                 ]
a
ytj@archlinux /h/ytj> echo a | pv | grep a
2.00 B 0:00:00 [48.8KiB/s] [<=>                                 ]
a
ytj@archlinux /h/ytj> echo a | pv | grep a
2.00 B 0:00:00 [39.9KiB/s] [<=>                                 ]
a
ytj@archlinux /h/ytj> echo a | pv | grep a
```

environments:

```
[ytj@archlinux ~]$ fish --version
fish, version 2.7.0
[ytj@archlinux ~]$ uname -a
Linux archlinux 4.14.9-1-ARCH #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017 x86_64 GNU/Linux
[ytj@archlinux ~]$ echo $TERM
xterm-256color
```

strace:

```
ytj@archlinux /h/ytj> echo a | strace pv | grep a
execve("/usr/bin/pv", ["pv"], 0x7ffcda569490 /* 30 vars */) = 0
brk(NULL)                               = 0xe05000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=102299, ...}) = 0
mmap(NULL, 102299, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2f2228a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\20\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2069912, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2f22288000
mmap(NULL, 3897584, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2f21cc7000
mprotect(0x7f2f21e75000, 2097152, PROT_NONE) = 0
mmap(0x7f2f22075000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ae000) = 0x7f2f22075000
mmap(0x7f2f2207b000, 14576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f2f2207b000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f2f22289540) = 0
mprotect(0x7f2f22075000, 16384, PROT_READ) = 0
mprotect(0x60d000, 4096, PROT_READ)     = 0
mprotect(0x7f2f222a3000, 4096, PROT_READ) = 0
munmap(0x7f2f2228a000, 102299)          = 0
brk(NULL)                               = 0xe05000
brk(0xe26000)                           = 0xe26000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1682192, ...}) = 0
mmap(NULL, 1682192, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2f220ed000
close(3)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2997, ...}) = 0
read(3, "# Locale name alias data base.\n#"..., 4096) = 2997
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/pv.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/pv.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/pv.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/pv.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/pv.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/pv.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
fstat(0, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TIOCGWINSZ, {ws_row=63, ws_col=239, ws_xpixel=1918, ws_ypixel=1077}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
--- stopped by SIGTTOU ---
```

**Comment by Mizuchi** [comment] 2018-01-05 05:43
1. I have also tested in CentOS7, same issue. so this problem is unlikely related to echo/pv/grep or linux kernel.
2. I have also tested in tty whose $TERM == "linux", same issue. So this problem is unlikely related to xterm.

**Comment by faho** [comment] 2018-01-05 11:07
Duplicate of #3952.

The issue seems to be that `pv` is writing to the terminal, but it's not guaranteed to be in the correct pgroup for it.

**Closed by faho** 2018-01-05 11:07 UTC

**Comment by faho** [comment] 2018-01-05 11:24
Duplicate of #3952.

The issue seems to be that `pv` is writing to the terminal, but it's not guaranteed to be in the right pgroup for it, because `grep` is a function, and so the `command grep` is seen as its own job.

As a workaround, use `command grep`.
