### ISSUE TITLE
Issue --web not loading (fish_config)

### ISSUE THREAD

**Issue by Furiousfox-01** [fish-shell/fish-shell#9297] opened 2022-10-23 04:38 UTC
**I  am using fish  ---> 3.5.1  in ubuntu 22.10**
fish_config is ### not working for me--- shows

![Screenshot from 2022-10-23 **10-03-24](https://user-images.githubusercontent.com/86916986/197374059-26f8f71e-c89a-465e-9892-078666d169c0.png)**

**Comment by faho** [comment] 2022-10-23 06:18
Duplicate of #9014

**Comment by faho** [comment] 2022-10-23 06:18
It's an Ubuntu issue - they've snapped all their browsers now, which means they can't open files in /tmp anymore.

Unfortunately there is no good replacement path we could use.

**Closed by faho** 2022-10-23 06:18 UTC

**Comment by Furiousfox-01** [comment] 2022-10-26 03:35
Thanks it working...👍🏻👍🏻
