### ISSUE TITLE
⏎ character preceding every prompt

### ISSUE THREAD

**Issue by ProfessionalNihilist** [fish-shell/fish-shell#1071] opened 2013-10-29 09:28 UTC
Debian Saucy, added the PPA and installed, set title function as per http://fishshell.com/docs/current/faq.html#faq-titlebar but the issue is not resolved.

Using fish on a headless server over ssh.

    anathema@inez ~> ls
    irclogs/
    ⏎
    anathema@inez ~>

**Comment by gordontyler** [comment] 2016-02-04 15:14
I get the same problem running fish (built using cygwin) on Windows using ConEmu (and Console2/ConsoleZ as well).

**Comment by krader1961** [comment] 2016-03-17 21:22
Duplicate of issue #789.

**Closed** 2016-03-17 21:39 UTC
Labels: duplicate, windows
