### ISSUE TITLE
fish_config doesn't work, because nothing found in `~/.cache/fish`

### ISSUE THREAD

**Issue by hedy06** [fish-shell/fish-shell#6941] opened 2020-04-24 12:57 UTC
### Fish version
`fish, version 2.7.1`

### `uname -a`
```
Linux DESKTOP-PK3E38B 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Note that I use Windows Subsytem for Linux with Ubuntu.

---

What I tried to do was starting `fish_config`, but it didn't work: 
![image](https://user-images.githubusercontent.com/50042066/80214598-b685ca00-866d-11ea-80ce-4d2986a5f00a.png)
It's Chinese because my system is Chinese. The Chinese you see isn't actually Chinese either, it's doesn't make sense. The English seems to be saying that ':' was an invalid operator.

Then I tried to `cd` into `~/.cache/fish`, and saw that there were nothing in there:
![image](https://user-images.githubusercontent.com/50042066/80214790-019fdd00-866e-11ea-8dd4-a17857688d09.png)

can anyone help with my problem? I installed fish using
```
sudo apt install fish
```
and have set fish to default shell. 

**EDIT: I noticed my fish version is very behind, maybe it's an `apt` problem? Should I try installing fish using LinuxBrew, or run `apt-add-repository` first, before using `apt`? Because in the fish shell website installation steps, under windows - windows subsystem for Linux - it just told me to do `sudo apt install fish`.** 

thanks!

**Comment by zanchey** [comment] 2020-04-25 01:42
This is a duplicate of #6338, which was fixed in fish 3.1.0. You could try using the Ubuntu PPA from https://launchpad.net/~fish-shell/+archive/ubuntu/release-3 to get a newer version.

**Closed by zanchey** 2020-04-25 01:42 UTC
Labels: duplicate

**Comment by hedy06** [comment] 2020-04-25 07:17
Thanks, it worked. But I think the installation docs under Windows subsystem for Linux is a tiny bit misleading :)

**Comment by zanchey** [comment] 2020-05-21 14:53
Yes, agreed. I've updated the README in cbf53623b44.
