### ISSUE TITLE
Attempting to complete a specific nonexistent command locks up fish, given local fish_user_key_bindings definition

### ISSUE THREAD

**Issue by TieDyedDevil** [fish-shell/fish-shell#3488] opened 2016-10-24 19:19 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.3.1-670-g37d91d0
FWIW, this is my fork, but built from upstream/master.

**OS/terminal used**: Fedora 24/st

Talk about the the issue here. 

## Reproduction steps
1. Create the file `/.config/fish/conf.d/fish_user_key_bindings.fish` as noted below.
2. Save current work, just in case the runaway process gets out of hand.
3. Start a new fish shell.
4. At the fish prompt, type `bindi<tab>`.

## Results
CPU utilization spikes and memory gets eaten up very quickly. Be prepared to do `pkill -9 fish` before your system runs out of memory and starts swapping.

This is an interesting bug in that it seems specific to that one particular completion. Other command completions work as expected. Variations of this completion, e.g. binda<tab>, bindx<tab> do the right thing.

The issue does NOT occur if I run fish w/o third-party customizations.

In my installation (w/ third-party customizations) the issue is triggered by the presence of `~/.config/fish/conf.d/fish_user_key_bindings.fish`. The content of this file is:

```fish
function fish_user_key_bindings

	bind -M normal \e\[80\~ media-toggle-mute
	bind -M insert \e\[80\~ media-toggle-mute
	bind -M replace-one \e\[80\~ media-toggle-mute
	bind -M visual \e\[80\~ media-toggle-mute

	bind -M normal \e\[81\~ media-volume-down
	bind -M insert \e\[81\~ media-volume-down
	bind -M replace-one \e\[81\~ media-volume-down
	bind -M visual \e\[81\~ media-volume-down

	bind -M normal \e\[82\~ media-volume-up
	bind -M insert \e\[82\~ media-volume-up
	bind -M replace-one \e\[82\~ media-volume-up
	bind -M visual \e\[82\~ media-volume-up

	bind -M normal \e\[83\~ media-audio-next
	bind -M insert \e\[83\~ media-audio-next
	bind -M replace-one \e\[83\~ media-audio-next
	bind -M visual \e\[83\~ media-audio-next

	bind -M normal \e\[84\~ media-audio-play
	bind -M insert \e\[84\~ media-audio-play
	bind -M replace-one \e\[84\~ media-audio-play
	bind -M visual \e\[84\~ media-audio-play

	bind -M normal \e\[85\~ media-audio-prev
	bind -M insert \e\[85\~ media-audio-prev
	bind -M replace-one \e\[85\~ media-audio-prev
	bind -M visual \e\[85\~ media-audio-prev

	bind -M normal \e\[86\~ media-mic-mute
	bind -M insert \e\[86\~ media-mic-mute
	bind -M replace-one \e\[86\~ media-mic-mute
	bind -M visual \e\[86\~ media-mic-mute

end
```

The presence of this file does not cause the issue when running the fish 2.3.1 release from the Fedora 24 repo.

**Comment by floam** [comment] 2016-10-24 19:27
I can reproduce this.

**Comment by krader1961** [comment] 2016-10-24 19:37
Does it still happen if you build fish after `git checkout a8c9019a`?

**Comment by floam** [comment] 2016-10-24 19:40
That was my first thought as well, and I already checked. It does still occur so it's unrelated to the regression in #3483.

**Comment by floam** [comment] 2016-10-24 20:13
Bisected to 851e44934780f469927f19770d0fc65d82bed129 @krader1961

**Comment by floam** [comment] 2016-10-24 20:27
Thanks a lot for reporting this, @TieDyedDevil!

**Comment by floam** [comment] 2016-10-24 20:29
Let's fix this one way or the other before releasing 2.4.0.

**Comment by krader1961** [comment] 2016-10-25 03:33
The problem is somewhere in the *src/pager.&ast;* code. A review of that portion of the implicated commit does not reveal any obvious bugs to me. Which suggests that one of the vars that supposedly contains only positive values can be set to a negative value. Which is itself a good reason to pay attention to warnings about comparisons between signed and unsigned values.

**Comment by floam** [comment] 2016-10-25 04:47
Do you know how to fix it? I'd be inclined to otherwise back out those changes.

**Comment by krader1961** [comment] 2016-10-26 02:25
Yes, the fix is simple and involves, as I suspected, a single expression. Specifically, an expression that subtracted of two values, one unsigned, that results in negative value in certain circumstances. The problem is due to the stupid C rule that when an unsigned int is in an expression signed ints are implicitly converted to unsigned. Which is why we had a bazillion warnings about such combinations. They're dangerous. I'm pondering whether to revert the entire change or fix the one known problem. I'll make a decision before I go to bed and have a fix committed either later tonight or tomorrow morning.

FWIW, I'm strongly leaning towards following the [Google style guide](https://google.github.io/styleguide/cppguide.html#Integer_Types) on this matter and eliminating every use of `size_t` in our code. This bug is a good example of why that type is dangerous and should be avoided. Yes, I know there are people who disagree. I read two blog posts this afternoon by programmers who argued for using unsigned ints more, not less. I found their arguments unpersuasive.

**Closed** 2016-10-26 04:07 UTC
Labels: bug, regression
