### ISSUE TITLE
Cannot change default vi mode

### ISSUE THREAD

**Issue by fightingdreamer** [fish-shell/fish-shell#10140] opened 2023-12-07 12:30 UTC
fish: 3.6.1

MacOS: 12.6.5
iTerm2: Build 3.4.22

Looks like vi mode keeps resetting to insert mode after every command, I cannot find a way to change it to normal mode.

Example:
```fish
# enter vi mode
fish_vi_key_bindings<enter>
# change to normal node
<esc><enter>
# fish changed to insert mode
```

Tried on clean profile with the same result:
```sh
sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
```

**Comment by faho** [comment] 2023-12-07 12:44
Duplicate of #6046

**Closed by faho** 2023-12-07 12:44 UTC
