### ISSUE TITLE
Can't install Fish on AWS Linux

### ISSUE THREAD

**Issue by Devin82m** [fish-shell/fish-shell#3908] opened 2017-03-23 19:54 UTC
Hello, I have yet to install Fish on AWS linux, so I have no version information other than I tried both CentOS 6 and 7 repositories (deleting the other before trying each). 

Linux ip-172-31-20-125 4.4.11-23.53.amzn1.x86_64 #1 SMP Wed Jun 1 22:22:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

xterm

I tried asciinema, I'm having a time trying to get it installed, even trying Pip. Oh well, here is the entire output of me trying to install Fish. Yes, I have Nettools installed and the hostname command does work. 

```
[root@ip-172-31-20-125 ec2-user]# yum install fish
Loaded plugins: priorities, update-motd, upgrade-helper
Repository shells_fish_release_2 is listed more than once in the configuration
amzn-main/latest                                                                                                                                                                        | 2.1 kB     00:00
amzn-updates/latest                                                                                                                                                                     | 2.3 kB     00:00
Resolving Dependencies
--> Running transaction check
---> Package fish.x86_64 0:2.5.0-1.2 will be installed
--> Processing Dependency: hostname for package: fish-2.5.0-1.2.x86_64
--> Finished Dependency Resolution
Error: Package: fish-2.5.0-1.2.x86_64 (shells_fish_release_2)
           Requires: hostname
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@ip-172-31-20-125 ec2-user]#
```

**Comment by krader1961** [comment] 2017-03-23 21:07
On RHEL/CentOS the hostname command is in the hostname package. Thus it's a requirement. On other platforms we require the net-tools package. See our [build spec](https://build.opensuse.org/package/view_file/shells:fish:nightly:master/fish/fish.spec?expand=1). I can't find any issues or recall anyone asking about installing fish on AWS before. Are you sure you should be using a package meant for RHEL rather than one for other Linux distros?

**Comment by Devin82m** [comment] 2017-03-23 22:22
Well, the hostname command works, so I would assume there is nothing to do there. As for the version of Linux, my understanding is that AWS Linux is based on CentOS.

**Comment by zanchey** [comment] 2017-03-23 22:25
My suspicion is that the macros we use to decide whether to depend on hostname or net-tools are different on Amazon Linux.

Could you attach the output of `rpm --eval %dump` (with any sensitive data redacted)?

**Comment by krader1961** [comment] 2017-03-23 22:42
https://forums.aws.amazon.com/thread.jspa?threadID=51647 says that AWS Linux was originally based on RHEL5. So, close enough :smile: As zanchey noted apparently they've deviated a bit from those origins. If you can provide answers to his questions we might find a way to provide a package for AWS that won't result in that error.

**Comment by Devin82m** [comment] 2017-03-23 22:53
Here you go.
[rpmdump.txt](https://github.com/fish-shell/fish-shell/files/866397/rpmdump.txt)

**Comment by zanchey** [comment] 2017-03-23 23:36
OK, I can't work that out at all. What about

```
rpm --eval '0%{?rhel_version} >= 700 || 0%{?centos_version} >= 700 || 0%{?fedora} || 0%{?is_opensuse}'
```

**Comment by faho** [comment] 2017-04-07 12:34
@Devin82m: Ping?

**Comment by faho** [comment] 2017-04-16 17:37
Closing since we don't have the required info. @Devin82m: If you still care about this, please reply with the answer to @zanchey's question.

**Closed by faho** 2017-04-16 17:37 UTC
Labels: needs-more-info, question

**Comment by gglanzani** [comment] 2017-04-26 14:27
@zanchey I can  help you: 

```
 rpm --eval '0%{?rhel_version} >= 700 || 0%{?centos_version} >= 700 || 0%{?fedora} || 0%{?is_opensuse}'
0 >= 700 || 0 >= 700 || 0 || 0
```

**Comment by zanchey** [comment] 2017-04-29 12:51
@gglanzani, have you tried install fish on AWS Linux?

I found @Devin82m's [StackOverflow question](https://stackoverflow.com/questions/42849248/how-do-i-install-fish-shell-on-aws-linux), which makes it clear that there is a problem with yum selecting the wrong package for install.

I could reproduce this (on CentOS 6) by running:

```
cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo
yum install fish # fails due to lack of hostname package
rm shells:fish:release:2.repo
wget http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_6/shells:fish:release:2.repo
yum install fish # still fails
```

and fix with (after the above)

```
yum clean all
yum install fish.i686 # only 32-bit builds available for older versions of CentOS
```

**Comment by RReverser** [comment] 2018-03-04 20:16
@zanchey Looks like `fish.i686` doesn't exist (not anymore?) in CentOS 6 repo.

**Comment by RReverser** [comment] 2018-03-04 20:22
Ok managed to install fish on AWS ignoring dependencies with

```bash
rpm -Uvh --nodeps $(repoquery --location fish)
```

from this answer to a similar question https://serverfault.com/a/681848.
