### ISSUE TITLE
Native Windows Terminal build?

### ISSUE THREAD

**Issue by Zopolis4** [fish-shell/fish-shell#9305] opened 2022-10-26 10:19 UTC
Ncurses 6.3 offers experimental native support for the new Windows Terminal, if I understand correctly.

Thus, would it (in theory) be possible to create a native build of fish that runs under windows without the need for a Linux subsystem? (Assuming all the posix tools are installed, etc).

**Comment by faho** [comment] 2022-10-26 10:40
Duplicate of #7488

**Closed by faho** 2022-10-26 10:40 UTC

**Comment by faho** [comment] 2022-10-26 10:41
Ncurses isn't a big problem.

The posix tools are one, posix *semantics* are another - how does signal delivery work, what about executing processes, opening files, what does `stat` do, is O_CLOEXEC supported?

A unix shell is something that's fairly tied to unix as an operating system, to its internals. And so adjusting that to work with windows instead is a non-trivial task.

And it's one that we aren't interested in because things like WSL exist that you could just use.

**Comment by Zopolis4** [comment] 2022-12-19 23:56
(I understand that its a non-trivial task, just explaining my reasoning)

The main reason I would be interested this is for cases when I can't use WSL or cygwin or msys2, where I need a Windows environment with a Windows shell, but want to use fish for the command completion and highlighting and etc.
