### ISSUE TITLE
Default colours don't work well on light-coloured terminals

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3893] opened 2017-03-14 01:46 UTC
[On the mailing list, Tassilo reports](https://sourceforge.net/p/fish/mailman/message/35720627/):

> After a bit of fiddeling, I found out that the common completion prefix
> is printed visibly (underlined) when I change my terminal from black
> foreground on white background to white foreground on black background,
> but I don't want to do that.

The problem is that a lot of the default colours set in `__fish_config_interactive` are:
- suitable for dark terminals
- not suitable for light terminals
- not exposed in the Web config

We should fixe at least the suitability on light terminals.

**Comment by faho** [comment] 2021-05-01 18:20
Duplicate of #3412

**Closed** 2021-05-01 18:20 UTC
Labels: enhancement
