### ISSUE TITLE
Wine error

### ISSUE THREAD

**Issue by heysama** [fish-shell/fish-shell#8685] opened 2022-02-01 13:50 UTC
yigit@handel ~> fish --version
fish, version 3.3.1
yigit@handel ~> echo $TERM
xterm-256color
yigit@handel ~> uname -a
Linux handel 5.15.16-1-MANJARO #1 SMP PREEMPT Thu Jan 20 13:58:19 UTC 2022 x86_64 GNU/Linux
yigit@handel ~> 

I used the "Help" command and got an error related to "Wine". I don't know what's the matter.

yigit@handel ~> help
env: `wine': Böyle bir dosya ya da dizin yok
yigit@handel ~>

**Comment by faho** [comment] 2022-02-01 13:58
Your default browser has been set to Wine's internet exploder, but your $PATH doesn't contain wine anywhere. 

You need to fix your desktop's settings, or set $BROWSER to a usable browser. Fish can't really do anything about this.

**Comment by faho** [comment] 2022-02-01 13:58
Duplicate of #8590

**Closed by faho** 2022-02-01 13:58 UTC
