### ISSUE TITLE
Parentheses conflict with tabcompletion

### ISSUE THREAD

**Issue by wilhelmy** [fish-shell/fish-shell#2886] opened 2016-04-02 22:46 UTC
I'm seeing this issue with fish 2.2.0:
```
> mkdir './()'
> cd ./\([Tab pressed]Unexpected end of string, parenthesis do not match
- (line 1): begin; printf \%s\n ./(*/ 
 ;end <&3 3<&-
                                ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 24 of file /usr/share/fish/functions/__fish_complete_cd.fish

in function “__fish_complete_cd”
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “-”
\)/
```
In the end, the tab completion works (the last line is the successful tab completion) but the error message is very irritating

**Comment by krader1961** [comment] 2016-04-02 22:54
Known issue. Duplicate of #952.

**Closed by krader1961** 2016-04-02 22:54 UTC
Labels: duplicate

**Comment by faho** [comment] 2016-04-02 23:18
@krader1961: No - this is the part that's fixed in the next release (`eval` in the cd completions). Anyway, nothing more to do here.
