### ISSUE TITLE
Some builtin commands crash the shell when called with an empty string

### ISSUE THREAD

**Issue by mpfaff** [fish-shell/fish-shell#8436] opened 2021-11-11 16:40 UTC
**Version**: 3.3.1
**OS**: Linux 5.14.10-1-MANJARO
**Terminal**: alacritty

I have confirmed that this issue occurs without any customizations.

# Steps to reproduce

- Start the fish shell
- Run any of these commands:
  - `cd ''`
  - `cd ""`
  - `pushd ''`
  - `pushd ""`
- The shell process exits with SIGABRT after printing this error message:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)
```

**Comment by faho** [comment] 2021-11-11 17:05
Duplicate of #8147

**Closed by faho** 2021-11-11 17:05 UTC
