### ISSUE TITLE
cd autocompletes to non-existant directory

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#2334] opened 2015-08-26 16:48 UTC
In this simple example:
```
> ls -a
./ ../
> mkdir "A 1" "A 2"
> cd 
```
at this point pressing tab once will autocomplete to `cd A\ `, and pressing it a second time will autocomplete to `cd A\ A` even though it matches no directory.
Note that this doesn't happen with files instead of directories.

Using fish 2.2.0.

**Comment by faho** [comment] 2015-08-26 19:33
This is a duplicate of #2300 - as with that, please try #2289.

**Closed by faho** 2015-08-26 19:33 UTC

**Comment by occivink** [comment] 2015-08-26 20:03
Right, sorry about the duplicate. I built the git version, but when I run it I get the following error every time I enter a command:
```
fish: echo $_ " "; __fish_pwd
                   ^
in command substitution
	called on standard input

fish: __fish_pwd
      ^
in command substitution
	called on standard input

in command substitution
	called on standard input

fish: echo $_ " "; __fish_pwd
                   ^
in command substitution
	called on standard input
```
even with an empty config dir. Most keybindings don't seem to work either. Any ideas what could cause this?

**Comment by faho** [comment] 2015-08-27 18:39
Any custom config? Particularly, did you override __fish_pwd?

**Comment by zanchey** [comment] 2015-08-27 22:54
That's usually caused by building the source and trying to run fish directly before doing `make install`.
