### ISSUE TITLE
Shell Input Redirect Fails

### ISSUE THREAD

**Issue by forsakensingularity** [fish-shell/fish-shell#10557] opened 2024-06-08 06:24 UTC
This syntax fails:

2>&1 echo "yes" | sudo -u ccnadm ./control.sh stop server

even trying -n for echo doesn't fix it...

RE: 

 ╭─jangela@jangela in ~ as 🧙 took 3s
 ╰─λ 2>&1 echo -n "yes" | sudo -u ccnadm ./control.sh stop server
fish: Expected a string, but found a redirection

 ╭─jangela@jangela in ~ took 3s
 ╰─λ echo $version
3.7.1

 ╭─jangela@jangela in ~ 
 ╰─λ sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
jangela@jangela-hplapppy17Garuda /h/jangela> 2>&1 echo "yes" | sudo -u ccnadm ./control.sh stop server

fish: Expected a string, but found a redirection

I did run this redirect on AIX version 7 but  I sortof expect Linux, maybe not fish, to support such syntax...

Thx/Bill

**Comment by forsakensingularity** [comment] 2024-06-08 06:27
Also tried:

2>&1 echo -e "all\nyes\nyes" | sudo su -

Am I crazy and missing it?

**Comment by faho** [comment] 2024-06-08 06:27
Duplicate of #2122

**Comment by faho** [comment] 2024-06-08 06:27
Fish does not support prefix notation for redirection.

Use `foo 2>&1`, not `2>&1 foo`

**Closed by faho** 2024-06-08 06:27 UTC

**Comment by forsakensingularity** [comment] 2024-06-08 06:51
OK, I think I understand (but maybe not) at any rate this syntax works (IE, it gives the proper response)

[jangela@jangela-hplapppy17Garuda ~]$ yes | sudo -u ccnadm ./control.sh stop server
sudo: unknown user ccnadm
sudo: error initializing audit plugin sudoers_audit


Thx/Bill

**Comment by faho** [comment] 2024-06-08 06:59
Here's the exact translation of your exact command:

```fish
echo "yes" 2>&1 | sudo -u ccnadm ./control.sh stop server
```

Just put the redirection *after* the command it redirects. First `echo`, *then* `2>&1`. This otherwise behaves exactly like the prefix-notation would work in shells that support it.

Now: This particular redirection for this particular command is basically useless. What it does is send `echo`'s stderr to its stdout. In this case it means that error output goes through the pipe as well, ending up in `sudo`'s stdin. But `echo` typically does not print an error, and if it *did* print an error you would not want `sudo` to read it as input.

You can also use `yes` instead, but that's something different from `echo yes` - the latter will print one line "yes", but `yes` will print a never-ending stream of "y" (until it gets cut off by the pipe being closed). *And* it has nothing to do with your redirection question.
