### ISSUE TITLE
'commandline' does nothing on 3.4.0 

### ISSUE THREAD

**Issue by EvanTheB** [fish-shell/fish-shell#8824] opened 2022-03-22 03:34 UTC
fish, version 3.4.0

xterm-256color (gnome-terminal)

Linux evanbenn 5.15.15-1rodete2-amd64 #1 SMP Debian 5.15.15-1rodete2 (2022-02-23) x86_64 GNU/Linux

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

Yes still present.

run `commandline test`

expected: prompt has `test`

actual: prompt has nothing

This is working again when I downgrade to 3.3.1.

**Comment by faho** [comment] 2022-03-22 06:24
You mean you run `commandline test` interactively?

Yeah, that's not supposed to work. It only did so by accident.

**Comment by faho** [comment] 2022-03-22 06:24
Duplicate of #8807

**Closed by faho** 2022-03-22 06:24 UTC

**Comment by EvanTheB** [comment] 2022-03-23 04:55
This also fails when i run 'commandline' in a function, for example: 

```
function fh
    commandline (history | fzf --height 40%)
end
```

I'm not sure what not-interactively would mean, triggered by a hotkey?

**Comment by krobelus** [comment] 2022-03-23 07:05
> I'm not sure what not-interactively would mean, triggered by a hotkey?

yes, try: bind \cr fh
it might also work in event handlers
