### ISSUE TITLE
Script command (term logging) interactive input disappear

### ISSUE THREAD

**Issue by Selora** [fish-shell/fish-shell#6088] opened 2019-09-03 16:09 UTC
Fish version: `3.0.2`
Linux version: `5.2.11`
Terminal program reproduced on: termite, xterm, TTY

Allright, so this is probably a bug that will be hard to attribute. I'm trying to setup automatic logging to a script/typescript file for every fish instance I'm launching. While starting the `script` command from an already existing terminal works perfectly, characters disappear and are not logged to the typescript file when in interactive mode (ex. python console, prompts, etc).

I'm not knowledgeable enough to pinpoint where this problem is coming, I'm fairly sure it's not really a fish issue, and more something to do with buffered IO, but I've been able to reproduce on termite and xterm in an Xorg session and a plain TTY.

Steps to reproduce (from a fish shell): 
1. Start fish with `fish -C "script [-f] asdf"`
2. Run python
3. Notice that character inputs are not there. However, the command is properly registered. Upon pressing "enter", you get output corresponding to what you typed.

Note: Bash does not seem to exhibit these behaviors
1. From /bin/bash, bash -c "script -f -c '/bin/bash'"
2. Notice inputs are there in a python shell

Note: Starting another fish session or another script/typescript from a "broken" session does not fix the problem either, e.g. input characters are still missing

**Comment by krobelus** [comment] 2019-09-04 12:52
I can reproduce this with `fish -C python` or `fish -C bc`.
Looks like it can be fixed fairly easily in fish, see the referenced commit for a quick-and-dirty fix.

**Comment by faho** [comment] 2019-09-06 11:15
Pretty sure this is a duplicate of #5663, which was closed in master.

**Closed by faho** 2019-09-06 11:15 UTC
