### ISSUE TITLE
Lack of support of lambda / closure in fish functions

### ISSUE THREAD

**Issue by adamcavendish** [fish-shell/fish-shell#2610] opened 2015-12-14 08:48 UTC
A clusure might be required to generate functions inside functions. There might be two ways of doing it.

1. Allow local and global function definition (not so elegant)
2. Allow closure, lambda functions and returning functions (hard to design and implement) 

```
function mytest
  function inner_test
  end
end

mytest

not test (functions -q inner_test); and echo "Not exist!"
```

This is not possible now in fish-shell

**Comment by faho** [comment] 2015-12-14 09:58
I believe this is a duplicate of #1799. Thanks!

**Closed by faho** 2015-12-14 09:58 UTC
Labels: duplicate

**Comment by krader1961** [comment] 2015-12-15 03:31
This isn't strictly speaking a duplicate of #1799 but I am opposed to adding support for closures or lambda functions. There is no way in fish or any traditional UNIX shell to pass a reference to a function and no such mechanism should be added (ignoring passing the literal name of the function and using "eval"). Fish is not Python, Scala, etc. It's a simple scripting language with a focus on providing a highly satisfying interactive shell experience. If you're tackling a problem whose solution would benefit from a feature like function closures you should be using a different language.

**Comment by adamcavendish** [comment] 2015-12-15 05:48
@krader1961 Thx. I'm thinking about it. Fish is also a string-based shell language so it might be hard to do it.

**Comment by krader1961** [comment] 2015-12-17 06:09
By all means think about it and put forward a proposal, @adamcavendish. But you should think very carefully about the fact that a shells like bash, ksh, and fish are effectively DSLs (domain specific languages) such as those implemented by tools like awk. DSLs are not meant to be general purpose languages suitable for writing entire applications (e.g., a web server). Adding features like closures to make them comparable to a GPL is almost always a bad idea.

**Comment by adamcavendish** [comment] 2015-12-19 03:09
@krader1961 I understand that shell is a DSL, however, it shoud be a DSL specified for job execution. (Not back to the days when sh is born. At that time shell means executing a job.) So job execution system should be good at managing the jobs, especially parallelism and async management, which is the reason I was trying to implement lambda myself.

**Comment by krader1961** [comment] 2015-12-19 03:22
I definitely agree that nearly all (if not all) extant shells are horrible at managing parallel async jobs. This includes fish. Whether or not improving that situation requires closures is TBD. Note that the [Go](https://golang.org/) language addresses that issue in a unique fashion that does not require closures per-se. I think your proposal to add support for closures is premature and impractical given the design of fish and similar languages. What you are proposing is a major research effort that is not appropriate for an open issue against an existing command shell language. Write a [white paper](https://en.wikipedia.org/wiki/White_paper) on the topic then come back with a concrete proposal.

**Comment by adamcavendish** [comment] 2015-12-19 03:28
@krader1961 go is using closures as well in go-routine.

```go
go func(msg string) {
    fmt.Println(msg)
}("Hello World")
```

I'm considering to write a paper about these stuffs, but I think it would be impossible to implement it in any posix shell and I found the only non-posix shell that is quite popular is fish-shell.

**Comment by krader1961** [comment] 2015-12-19 03:37
Yes, Go has closures. They're not central to its async IO mechanism (go-routines). Fish is a "posix shell". The difference when compared to other shells like bash and zsh is that it has a much simpler core set of features and relies more heavily on external commands. Which is very much in keeping with the grandaddy of all these shells: the original [Bourne shell](https://en.wikipedia.org/wiki/Bourne_shell).

I would love to see a major step forward in shell design with respect to management of background (aka async) jobs. Let us know when you've published a white paper on the topic.

**Comment by tfga** [comment] 2019-07-16 07:45
@krader1961 There are compelling reasons for having lambdas in a shell. Both as a language and as a repl.

Suppose you want to add a suffix to all the filenames in a directory. How would you do it?

Using a `for` loop:

```fish
for name in *; mv $name $name.old; end
```

Using `map` and lambdas:

```fish
dir -1 | map { mv $ $.old }
```

Which one is simpler? Which would you rather type in an interactive shell?

More motivation / inspiration / examples:
https://github.com/ssledz/bash-fun
