### ISSUE TITLE
fish crashes node debugging process

### ISSUE THREAD

**Issue by 1ak31sha** [fish-shell/fish-shell#5680] opened 2019-02-20 16:01 UTC
fish, version 3.0.2

Darwin u6064854-tpm-a.ten.thomsonreuters.com 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

 sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
(no output from this command)

**How to reproduce the problem:**
1.cd into folder with jest tests
2.node --inspect-brk ~/path/to/jest/.bin/jest --runInBand
3. attach by going to chrome://inspect, then hit f8
4. set a breakpoint and try to use the console. notice that the process in terminal should have crashed.

Thanks so much!
As a work around for now i am using bash when running tests

[I] ~/w/e/p/c/__tests__ (temp-filtered-list↑2|✚4) $
node --inspect-brk ~/workspace/emcm-ui/node_modules/.bin/jest --runInBand
Debugger listening on ws://127.0.0.1:9229/536e648e-e6bb-4524-ba16-d8dfa27ce9d4
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

 RUNS  ./tests.js
 1: 0x10003818c node::Abort() [/usr/local/bin/node]
 2: 0x100093973 node::BackgroundTaskRunner::PostDelayedTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >, double) [/usr/local/bin/node]
 3: 0x100173b9a v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(double) [/usr/local/bin/node]
 4: 0x100167d73 v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(v8_inspector::String16 const&, v8_inspector::String16 const&, v8_inspector::protocol::Maybe<v8_inspector::String16>, v8_inspector::protocol::Maybe<bool>, v8_inspector::protocol::Maybe<bool>, v8_inspector::protocol::Maybe<bool>, v8_inspector::protocol::Maybe<bool>, v8_inspector::protocol::Maybe<bool>, v8_inspector::protocol::Maybe<double>, std::__1::unique_ptr<v8_inspector::protocol::Runtime::RemoteObject, std::__1::default_delete<v8_inspector::protocol::Runtime::RemoteObject> >*, v8_inspector::protocol::Maybe<v8_inspector::protocol::Runtime::ExceptionDetails>*) [/usr/local/bin/node]
 5: 0x100125415 v8_inspector::protocol::Debugger::DispatcherImpl::evaluateOnCallFrame(int, std::__1::unique_ptr<v8_inspector::protocol::DictionaryValue, std::__1::default_delete<v8_inspector::protocol::DictionaryValue> >, v8_inspector::protocol::ErrorSupport*) [/usr/local/bin/node]
 6: 0x100124825 v8_inspector::protocol::Debugger::DispatcherImpl::dispatch(int, v8_inspector::String16 const&, std::__1::unique_ptr<v8_inspector::protocol::DictionaryValue, std::__1::default_delete<v8_inspector::protocol::DictionaryValue> >) [/usr/local/bin/node]
 7: 0x100118bd4 v8_inspector::protocol::UberDispatcher::dispatch(std::__1::unique_ptr<v8_inspector::protocol::Value, std::__1::default_delete<v8_inspector::protocol::Value> >, int*, v8_inspector::String16*) [/usr/local/bin/node]
 8: 0x100176b0f v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(v8_inspector::StringView const&) [/usr/local/bin/node]
 9: 0x1000e0bc1 node::inspector::NodeInspectorClient::dispatchMessageFromFrontend(int, v8_inspector::StringView const&) [/usr/local/bin/node]
10: 0x1000e0932 node::inspector::(anonymous namespace)::SameThreadInspectorSession::Dispatch(v8_inspector::StringView const&) [/usr/local/bin/node]
11: 0x1000ecab0 void node::inspector::(anonymous namespace)::AnotherThreadObjectReference<node::inspector::(anonymous namespace)::MainThreadSessionState>::Apply<std::__1::unique_ptr<v8_inspector::StringBuffer, std::__1::default_delete<v8_inspector::StringBuffer> > >(node::inspector::(anonymous namespace)::MainThreadSessionState*, void (node::inspector::(anonymous namespace)::MainThreadSessionState::*)(std::__1::unique_ptr<v8_inspector::StringBuffer, std::__1::default_delete<v8_inspector::StringBuffer> >), std::__1::unique_ptr<v8_inspector::StringBuffer, std::__1::default_delete<v8_inspector::StringBuffer> >&) [/usr/local/bin/node]
12: 0x1000eb830 node::inspector::MainThreadInterface::DispatchMessages() [/usr/local/bin/node]
13: 0x1000947f7 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/usr/local/bin/node]
14: 0x100093e0f node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/local/bin/node]
15: 0x100094cbf node::NodePlatform::FlushForegroundTasks(v8::Isolate*) [/usr/local/bin/node]
16: 0x1000e015b node::inspector::NodeInspectorClient::runMessageLoop() [/usr/local/bin/node]
17: 0x10015abb1 v8_inspector::V8Debugger::handleProgramBreak(v8::Local<v8::Context>, v8::Local<v8::Value>, std::__1::vector<int, std::__1::allocator<int> > const&, bool, bool) [/usr/local/bin/node]
18: 0x1003d92ea v8::internal::Debug::OnDebugBreak(v8::internal::Handle<v8::internal::FixedArray>) [/usr/local/bin/node]
19: 0x1003de824 v8::internal::Debug::HandleDebugBreak(v8::internal::IgnoreBreakMode) [/usr/local/bin/node]
20: 0x100613133 v8::internal::Runtime_HandleDebuggerStatement(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
21: 0x1a239985c01d
fish: 'node --inspect-brk ~/workspace/…' terminated by signal SIGABRT (Abort)

**Comment by faho** [comment] 2019-02-20 16:18
It seems kind of unlikely that this is caused by fish itself.

It's possible it's caused by differences in configuration, which cause environment variables being different - compare the output of `env` in fish and bash. (In that case it would most likely be a bug in node)

I can't reproduce it with these steps (though I'm not a js dev, so I basically just set up a skeleton project like https://flaviocopes.com/jest/ said).

**Comment by 1ak31sha** [comment] 2019-02-23 04:17
ok, will give it a try tomorrow thanks! <3

**Comment by faho** [comment] 2019-03-05 20:06
Okay, I'm closing this for a lack of information, and because a crash in another application is, by definition, that application's fault (unless fish is doing something very weird, which it probably isn't).

If anyone can provide some more information so we can reproduce it we'll reopen.

**Closed by faho** 2019-03-05 20:06 UTC
Labels: needs more info
