### ISSUE TITLE
Odd expansion of curly brackets {,,,}

### ISSUE THREAD

**Issue by dimaqq** [fish-shell/fish-shell#4598] opened 2017-12-14 06:00 UTC
fish, version 2.6.0
yes I've tried fish with no extensions.

```
dimaqq@voi ~> echo x{,,,}
x x, x
dimaqq@voi ~> echo x{,,,,,,}
x x, x, x,
dimaqq@voi ~> echo x{,,,,,,,}
x x, x, x, x
```

Somehow, first and last commas are interpreted correctly, but if there's nothing between the commas, the other, inner commas are treated literally.

Simple invocations `mv foo{,.old}` are expanded correctly.

**Comment by dimaqq** [comment] 2017-12-14 06:03
If anyone is stuck, there are following work-arounds: `{,{,{,}}}` and `{{,}{,}}`

**Comment by faho** [comment] 2017-12-14 21:13
This is a duplicate of #3002. Sorry for the inconvenience!

**Closed by faho** 2017-12-14 21:13 UTC
