### ISSUE TITLE
Can't use a U+F005 (\uF005) character in fish

### ISSUE THREAD

**Issue by eugenesvk** [fish-shell/fish-shell#2684] opened 2016-01-18 22:48 UTC
When using `echo \UF005` I get `Mismatched brackets` error even though this is not a bracket symbol. Also, I can't insert this symbol manually either, so it seems like a forbidden symbol in `fish` or something (works fine in other shells).
Is there a way around it? I'm using a customized font that has some of git icons in that range (can't paste here since GitHub doesn't have this font).
PS.
Sorry, should've mentioned that it's on `OS X 10.11.2`, `fish 2.2.0`

**Comment by krader1961** [comment] 2016-01-18 22:59
I can reproduce this on Mac OS X using a fish built from github head. Note that U+F005 is a "private use character". See https://codepoints.net/U+F005?lang=en. And I don't see how it could be confused with either bracket character (\x5B and \x5D).

P.S., It's generally a good idea to include your fish version and OS when reporting problems, @eugenesvk,  because some problems are OS specific and/or may have already been fixed by a newer version of fish.

**Comment by eugenesvk** [comment] 2016-01-18 23:19
@krader1961 Sorry, updated with the OS and `fish` versions.
Thanks for pointing out that these are private area glyphs — that's exactly correct, the fonts were patched in that area with additional symbols to avoid a conflict with default glyphs. Also no clue how it's confused with a bracket since it's not a bracket neither by UTF code nor by appearance ;)
However, I've encountered a few mentions that `fish` uses private glyphs e.g. in https://github.com/fish-shell/fish-shell/issues/436, so maybe it's one of those, but it doesn't seem to be documented. And anyway I wish `fish` implemented those functions without interfering with the users' private area glyphs.

**Comment by krader1961** [comment] 2016-01-18 23:28
The \x1e character mentioned in #436 is not a unicode private area codepoint; it's an ASCII control character. So that shouldn't be relevant to this issue. I see nothing in the source code to suggest that fish is using private area codepoints. This is most likely a problem with the code that characterizes unicode codepoints. The question is whether it's fish code or a library that fish depends on.

I'll test this when I get home and can start my Ubuntu VM to see if this is specific to OS X.

**Comment by eugenesvk** [comment] 2016-01-19 00:00
@krader1961 thanks for helping!
I know  `\x1e` is not a private area codepoint, I was rather referring to __JanKanis__'s comment
>How about using a private use area character as separator? Fish already uses some of those in some cases.

(that thread popped up when I was researching another issue).

**Comment by ridiculousfish** [comment] 2016-01-19 01:31
fish uses the range U+F000 through U+F00F to represent various "command" type characters, like home directory or brackets. 

Try `printf "\uF005"`. Does that work?

**Comment by krader1961** [comment] 2016-01-19 02:01
Yes, the printf formulation works. My grep-fu earlier today was weak :-) I now see the __EXPAND_RESERVED__ and __EXPAND_RESERVED_END__ definitions in __expand.h__ and their use in the following enum. This seems like a questionable design decision as it means that someone, like @eugenesvk, can insert reserved tokens into the parser that are otherwise not documented as reserved tokens (like the regular ASCII bracket chars).

I recommend switching to Unicode "noncharacters" from the range U+FDD0 to U+FDEF: http://www.unicode.org/faq/private_use.html. That would allow us to leave the existing implementation as is while avoiding the type of conflict @eugenesvk noted. Yes, someone could still try to run a command like `echo \uFDD5` but that would be a perverse thing to do and would be the equivalent of executing the CPU halt-and-catch-fire opcode.

**Comment by krader1961** [comment] 2016-01-19 04:27
Please assign this to me. I've already coded a change that shows switching to the "noncharacters" range works. I'm now working on figuring out how to have fish reject any characters from that range when it is parsing its input.

**Comment by pickfire** [comment] 2016-01-19 14:48
It works, but weird character is displayed.
```
~> printf "\uF005"

```

**Comment by krader1961** [comment] 2016-01-19 15:34
> It works, but weird character is displayed.

That's expected. That codepoint is a private-use character whose glyph is not defined by the Unicode standard. See http://www.unicode.org/faq/private_use.html.

**Comment by eugenesvk** [comment] 2016-01-19 16:58
@ridiculousfish it kind of works as a standalone command, but I can't use it to assign a variable
e.g. if I'm using `set VAR (printf "\UF005"); echo $VAR` then I get the same error.

Also, when using `printf "\UF005"` on a standalone basis, I also get a visual return symbol in addition to the proper char (which looks like `\UF23CE`). The return symbol disappears if I echo another character after the `printf "\UF005"`, but I didn't want it in the first place even when there are no chars being output after it.

I would second @krader1961's suggestion to please NOT use any Unicode chars users can use.

**Comment by faho** [comment] 2016-01-20 17:34
> I also get a visual return symbol in addition to the proper char (which looks like \UF23CE). 

`⏎`? That's inserted by fish if the command doesn't end with a newline. It's only done when the output is going to the terminal to prevent output bleeding over into the prompt line.

**Comment by eugenesvk** [comment] 2016-01-20 18:02
@faho yes, that's the one: ⏎, though it turns to a shallower `⏎` in code-quotes :)
Thanks for clarification. Indeed, in my `bash` it just bleeds over into the prompt line, while `zsh` and `fish` handle it differently.

**Comment by krader1961** [comment] 2016-01-21 06:27
This is a progress report on my attempt to fix this issue. There are at least three uses of Unicode private-use codepoint ranges. That itself isn't a problem. What is a problem are the locations, like function __wchar_private()__ that use hardcoded hex values rather than symbols common to the other places that use the same ranges of values.

Those issues seemed simple to fix. However doing so results in the unit tests failing. That appears to be due to the semi-mysterious __ENCODE_DIRECT_BASE__ symbol defined in __common.h__ that defines a base value for chars that are considered private by __wchar_private()__ but which are not otherwise explicitly defined elsewhere (e.g., via enums). This part of the code is an awful mess from a maintenance perspective.

**Comment by ridiculousfish** [comment] 2016-01-21 07:03
Yes, this is not simple to fix. fish stores unescaped strings using in-band representations of things like brackets and ~. A band-aid would be to switch to wchar_t values outside of the Unicode code-point range, but this wouldn't work on Windows. A proper fix would be to switch to a fancier storage for an unescaped string, that doesn't try to cram expansions into characters. This would be a big change, without a lot of benefit.

**Comment by krader1961** [comment] 2016-01-21 16:00
The problem isn't the in-band representation for things like brackets and ~ (home directory). Those uses only consume 14 characters and easily fit into the 32 codepoints reserved as "noncharacters" (really private-use) in the Unicode BMP. It was trivial to move those into the really private-use range (aka "noncharacters").

The problem are the 256 private-use characters used in this manner:

```
#define ENCODE_DIRECT_BASE 0xF100u

/* Here consumed must have been set to something. The narrow_val is a literal byte that we want to output (#1894) */
wc = ENCODE_DIRECT_BASE + narrow_val % 256;
```

I'm going to ponder that code to see if there is a straightforward way to handle that case without consuming 256 Unicode codepoints that fish has no business appropriating. But if there isn't I'll relocate it closer to the end of the private-use range in the BMP as that should minimize potential conflicts on the assumption that most people are likely to choose codepoints from the start of the range for their "private use". Note that I said "closer to the end" because we already know the "Apple" symbol (0xF8FF) uses the last private-use codepoint in the BMP.

**Comment by ridiculousfish** [comment] 2016-01-21 18:22
The largest Unicode code point is 0x10FFFF. On systems with 32 bit wchar_t, we can use values larger than that. That's my "band-aid" idea.

**Comment by krader1961** [comment] 2016-01-21 18:32
If we assume a 32 bit wchar_t we can use the noncharacter regions in planes 15 and 16. I thought the problem was that we have to assume wchar_t is only 16 bits wide to accommodate MS Windows. If that isn't true then the solution is straightforward.

**Comment by ridiculousfish** [comment] 2016-01-21 18:37
Yeah, I don't think Windows has an easy band-aid, but this is already an edge case.

**Comment by krader1961** [comment] 2016-01-22 04:47
FWIW, I've concluded there isn't any simple way to alter the code to totally eliminate the use of Unicode private-use characters. I have, however, modified the code to reduce fish's use of such characters from 6399 to 320. And in the process cleaned up the code to make the use of such characters much clearer. I still need to modify the code to replace reserved chars with the Unicode "replacement char" for anything that fish reads into its parser. In the meantime I'll open a pull-request with the first, and most important, change in addressing this issue.

**Comment by krader1961** [comment] 2016-02-11 01:40
I just noticed issue #51 (opened more than three years ago) is the same issue. I don't think we're going to completely fix this anytime soon but with the changes I have in the pipeline the reserved char range will be greatly reduced and it will be impossible to confuse fish by feeding it the private-use chars it does use internally.

**Comment by eugenesvk** [comment] 2016-02-11 13:16
@krader1961 that would be a welcome fix for my powerline-patched fonts ;)

**Comment by floam** [comment] 2019-03-13 23:24
\uF005 works here in fish, in 2019. Are we tracking anything else with this one?

**Comment by faho** [comment] 2019-03-14 09:21
The larger point is that fish is using some chars internally that can cause problems when used in a command.

However, that usage has been reduced significantly, there's not been any reports of problems since then (AFAIK) and the chars we do use are all private-use, so there's no expectation that they'll work anyway.

So let's just close this.

**Closed by faho** 2019-03-14 09:21 UTC
Labels: enhancement
