### ISSUE TITLE
test command always returns 0 when called with a flag and no arguments

### ISSUE THREAD

**Issue by bnwa** [fish-shell/fish-shell#10831] opened 2024-11-04 17:44 UTC
Fish: fish, version 3.7.1
OS: Darwin [REDACTED] 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 arm64
TERM: xterm-256color
Third Party Customizations: None

Testing for executables on PATH in `config.fish` demonstrates unexpected behavior: `test -x (which foo)` (where `foo` does not exist on $PATH of course) returns a `0` status, and therefore, in any conditional branching, always executes the case even when invalid.

As I understand from the docs, command substitution should evaluate to the output of the enclosed command; in this case, nothing. As it turns out, `test -x; echo $status` also prints `0`. I suspect calling `test` with any flag produces this behavior as `echo -d; echo $status` also returns `0`. However, as expected, `test; $echo status` returns an error status.

I discovered this behavior have a series of branches in my `config.fish` to setup alias functions based on the presence of executables on the $PATH. The $PATH is correctly configured at this point as an `echo $PATH` at the top of `config.fish` proved.

Am I misunderstanding the behavior of `test`?

**Comment by faho** [comment] 2024-11-04 17:48
Duplicate of #2037

**Closed by faho** 2024-11-04 17:48 UTC

**Comment by faho** [comment] 2024-11-04 17:49
Unfortunately this is a POSIX requirement, and `test` is one of the few parts of fish to follow POSIX. This behavior is so you can do `test "$foo"` as a shortcut for `test -n "$foo"`.

Good news is we're phasing it out
