### ISSUE TITLE
Enhanchement Remove path from $PATH

### ISSUE THREAD

**Issue by ShalokShalom** [fish-shell/fish-shell#9147] opened 2022-08-18 17:39 UTC
I suggest `fish_remove_path` or something similar.

Currently, there is no way (in the documentation) to remove strings from the PATH. 

https://fishshell.com/docs/current/tutorial.html#path
https://fishshell.com/docs/current/cmds/fish_add_path.html#cmd-fish-add-path

**Comment by faho** [comment] 2022-08-18 17:57
Duplicate of #8604

**Closed by faho** 2022-08-18 17:57 UTC

**Comment by faho** [comment] 2022-08-18 17:59
Short answer is it's impossible to permanently remove a path from $PATH outside of the place where it's added, and so fish_remove_path would have a gaping hole that can't be plugged, so it's better to not pretend to have it.
