### ISSUE TITLE
Exported lists being converted into strings

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7499] opened 2020-11-23 22:36 UTC
fish, version 3.1.2

```console
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
ilan@arch ~> set -lx blah 1 0
ilan@arch ~> echo $blah's'
1s 0s
ilan@arch ~> # The list is an actual list
ilan@arch ~> fish
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
ilan@arch ~> echo $blah's'
1 0s
ilan@arch ~> # The list has been converted into a string
```

This was very unexpected, and I think it's clearly the wrong behavior.

**Comment by faho** [comment] 2020-11-24 04:09
Duplicate of #5348

**Closed by faho** 2020-11-24 04:09 UTC
