### ISSUE TITLE
Shell hangs when executing command on startup from config.fish

### ISSUE THREAD

**Issue by gibsjose** [fish-shell/fish-shell#5768] opened 2019-03-26 15:28 UTC
## Configuration
```
fish --version
fish, version 3.0.2
```

```
uname -a
Linux blizzard 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
echo $TERM
xterm-256color
```

## Issue
The fish shell hangs indefinitely when executing a function (which is just an alias for running a C program with an argument).  If I comment out the line in the `config.fish` script and save while it is hanging, it finishes executing and it appears that the program was executed.

The line in `config.fish` is simply:

```
wrenv
```

Which is an alias defined as:

```
# VxWorks Environment Setup
function wrenv
    /opt/vxworks-6.9/WindRiver/wrenv.linux -p vxworks-6.9
end
```

This `wrenv.linux` script is a C program that configures some environmental variables for VxWorks, an embedded real time operating system.

Simply calling `wrenv` or calling the `wrenv.linux` script directly from within fish does **not** cause it to hang. Instead it executes successfully and returns. Putting the same line in my `.bashrc` and starting a new bash shell likewise succeeds. This leads me to believe that the issue is somehow related to how fish sources the config file on startup.

## Steps to Reproduce
1. Add line `wrenv` to end of `config.fish`
2. Source `config.fish` or open a new terminal
3. Terminal hangs indefinitely
4. Commenting line out in `config.fish` while shell hangs causes the prompt to come back and the program to finish executing (I can tell because it sets some environmental variables).

## Output of last part of `strace fish` when line is in `config.fish`
```
stat("/home/hfcs/.config/fish/functions/set_color.fish", 0x7ffc51ec5700) = -1 ENOENT (No such file or directory)
stat("/etc/fish/functions/set_color.fish", 0x7ffc51ec5700) = -1 ENOENT (No such file or directory)
stat("/usr/share/fish/vendor_functions.d/set_color.fish", 0x7ffc51ec5700) = -1 ENOENT (No such file or directory)
stat("/usr/share/fish/functions/set_color.fish", 0x7ffc51ec5700) = -1 ENOENT (No such file or directory)
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
read(3, 0x7ffc51ec47d0, 4096)           = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
stat("/home/hfcs/.config/fish/fish_variables", {st_mode=S_IFREG|0644, st_size=1299, ...}) = 0
pipe([3, 4])                            = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
read(3, 0x7ffc51ec47d0, 4096)           = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
pipe([3, 4])                            = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
read(3, 0x7ffc51ec47d0, 4096)           = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
pipe([3, 4])                            = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
read(3, 0x7ffc51ec47d0, 4096)           = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
pipe([3, 4])                            = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
read(3, 0x7ffc51ec47d0, 4096)           = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
pipe([3, 4])                            = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
read(3, 0x7ffc51ec47d0, 4096)           = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
getpgrp()                               = 16533
ioctl(0, TIOCGPGRP, [16533])            = 0
getpid()                                = 16535
openat(AT_FDCWD, "/home/hfcs/.config/fish/functions/utilities.fish", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=1355, ...}) = 0
fcntl(3, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fstat(3, {st_mode=S_IFREG|0664, st_size=1355, ...}) = 0
read(3, "# Reload fish configuration\nfunc"..., 4096) = 1355
read(3, "", 4096)                       = 0
close(3)                                = 0
stat("/home/hfcs/.config/fish/functions//opt/vxworks-6.9/WindRiver/wrenv.linux.fish", 0x7ffc51ec7b70) = -1 ENOENT (No such file or directory)
stat("/etc/fish/functions//opt/vxworks-6.9/WindRiver/wrenv.linux.fish", 0x7ffc51ec7b70) = -1 ENOENT (No such file or directory)
stat("/usr/share/fish/vendor_functions.d//opt/vxworks-6.9/WindRiver/wrenv.linux.fish", 0x7ffc51ec7b70) = -1 ENOENT (No such file or directory)
stat("/usr/share/fish/functions//opt/vxworks-6.9/WindRiver/wrenv.linux.fish", 0x7ffc51ec7b70) = -1 ENOENT (No such file or directory)
access("/opt/vxworks-6.9/WindRiver/wrenv.linux", X_OK) = 0
stat("/opt/vxworks-6.9/WindRiver/wrenv.linux", {st_mode=S_IFREG|0775, st_size=59023, ...}) = 0
getpid()                                = 16535
fcntl(0, F_GETFL)                       = 0x2 (flags O_RDWR)
getpid()                                = 16535
rt_sigaction(SIGHUP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=0x55f38b72d5a0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7ff814e0b890}, 8) = 0
rt_sigaction(SIGQUIT, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7ff814e0b890}, 8) = 0
rt_sigaction(SIGILL, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTRAP, NULL, {sa_handler=0x55f38b72d4f0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7ff814e0b890}, 8) = 0
rt_sigaction(SIGABRT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGBUS, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGFPE, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGKILL, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGUSR1, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGUSR2, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSEGV, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7ff814e0b890}, 8) = 0
rt_sigaction(SIGALRM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=0x55f38b72d510, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7ff814e0b890}, 8) = 0
rt_sigaction(SIGCONT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSTOP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTIN, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTOU, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGURG, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGXCPU, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGXFSZ, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGVTALRM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGPROF, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGWINCH, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGIO, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGPWR, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSYS, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSTKFLT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGABRT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7ff815d84000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7ff815d8cff0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 16538
munmap(0x7ff815d84000, 36864)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
getpgrp()                               = 16533
wait4(16538, 0x7ffc51ec7bdc, WNOHANG|WSTOPPED, NULL) = 0
wait4(16538,
```

## Output of `fish -d3` when line is in `config.fish`
```
<3> fish: Created job 4 from command 'set __fish_git_prompt_showcolorhints 'yes'' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_showdirtystate 'yes'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_showstashstate 'yes'' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_showuntrackedfiles 'yes'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_color_branch normal' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_color_upstream_ahead green' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_color_upstream_behind red' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_showupstream 'informative'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_char_cleanstate '✔'' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_char_dirtystate '✖'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_char_stateseparator ' '' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_char_stagedstate '*'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_char_untrackedfiles '…'' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_char_stashstate '↩'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_char_upstream_prefix ' '' with pgrp -2
<3> fish: Created job 5 from command 'set __fish_git_prompt_char_upstream_ahead '+'' with pgrp -2
<3> fish: Created job 4 from command 'set __fish_git_prompt_char_upstream_behind '-'' with pgrp -2
<3> fish: Created job 2 from command 'source $f' with pgrp -2
<3> fish: Created job 4 from command 'source $f' with pgrp -2
<3> fish: unregister: EVENT_ANY: "fish_prompt"
<3> fish: Created job 3 from command '/opt/vxworks-6.9/WindRiver/wrenv.linux -p vxworks-6.9' with pgrp 17098
```

**Comment by faho** [comment] 2019-03-26 15:42
Duplicate of #2980

**Closed by faho** 2019-03-26 15:42 UTC

**Comment by gibsjose** [comment] 2019-03-26 15:50
I'm not sure it's a duplicate. Adding the suggested `stty icrnl icanon iexten echo` to the top of my `config.fish` did not solve the problem.

**Comment by gibsjose** [comment] 2019-03-26 15:51
Additionally, the script in question is **not** interactive. It simply sets some environmental variables and exits. I am also not running `screen`, as mentioned in the other issue.

**Comment by gibsjose** [comment] 2019-03-27 14:45
@faho Could your provide more info on why this is a duplicate?

**Comment by faho** [comment] 2019-03-27 14:54
What happens is that fish executes that process, which somehow accesses the terminal. And that doesn't succeed because of #2980, so the process is stopped and fish waits for it to end, which it doesn't.

It doesn't have to use screen or cygwin or anything.

My theory:

>(I can tell because it sets some environmental variables)

It's an external program. It doesn't have any access to fish's variables, and you're not running `source` or otherwise reading any _output_ to set the variables inside fish. Which means it is most likely executing another fish. Which then tries to access the terminal, which won't work because #2980.
