### ISSUE TITLE
Escape and complete -C (for fzf completion widget)

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#3469] opened 2016-10-17 07:30 UTC
fish 2.3.1, Arch Linux, urxvt 9.22

I am trying to write a widget to replace fish completion menu with fzf. (Awesome, right? ;) )

The idea is simple:

``` fish
## Boilerplate...
complete -C | fzf... | read result
## Some code to replace the token with $result.
```

Problem is, `complete -C` unescapes the tokens a bit too much, which makes variables indistinguishable from escaped dollars.

Example:

``` fish
set HFOO 42
echo \$HOME-$H<binding>
```

Replace `<binding>` with a binding to a function that prints out `complete -C`. Result:

```
$HOME-$HOME
$HOME-$HFOO
```

The result is unusable since there is no way for the calling function to know what should be escaped.

The normal completion does preserve the escaped token though:

```
\$HOME-$HOME
\$HOME-$HFOO
```

I think `complete -C` should do the same.

This might be related to https://github.com/fish-shell/fish-shell/issues/1127.

**Comment by faho** [comment] 2016-10-19 16:19
Yes, can reproduce.

We have a bunch of issues with escaping (because it's really confusing), but I can't find this particular one.

**Comment by ViViDboarder** [comment] 2018-02-02 01:23
I've been working on something like this with fzf for certain completions.

I put together the following [function](https://github.com/ViViDboarder/shoestrap/blob/908d4f084d6796248344aab5880dd207a322cef8/assets/default/fish/functions/__fzf_complete.fish) to use, but I see issues as well.

Not every time, but sometimes it will clear the entire command line (including prompt) from the view. Other times it will call fzf multiple times and try to do multiple completions. So far I haven't figured the issues or why they are only sporadic.

Interested to see if you've had any more luck!

**Comment by Ambrevar** [comment] 2018-02-02 07:47
Correct me if I'm wrong, but I think you are referring to a different issue, namely process management and/or file descriptor management.  fish has had several issues in that area in the past.  You might want to keep looking in the issue tracker.

The issue from the original post related to the badly escaped output of the `complete -C` command.

**Comment by krobelus** [comment] 2019-10-03 07:58
For `complete -C''\$HOME-$H`, I can imagine two possible behaviors:

1. `\$HOME-/home/johndoe`

That is, expand the completed token. This may be worthwile assuming that completions are short-lived.

2. `\$HOME-$HOME`

I have an implementation of this one at [escape-complete-C](https://github.com/krobelus/fish-shell/commits/escape-complete-C).
This would break third party scripts using `complete -C` (mostrly for subcommand completion I guess).

**Comment by nzig** [comment] 2022-01-15 15:02
@krobelus Could this be fixed by taking the implementation in your branch, but gating it behind a `--unescaped` flag as suggested in https://github.com/fish-shell/fish-shell/issues/4570#issuecomment-718082497 and discussed in #8441? This would avoid the problem of breaking scripts using `complete -C`, but allow the use case in this issue.

I will open a PR for this.

**Closed** 2022-02-09 07:34 UTC
Labels: bug
