### ISSUE TITLE
starting an interactive bash

### ISSUE THREAD

**Issue by homelessgamer** [fish-shell/fish-shell#6033] opened 2019-08-07 19:25 UTC
My system: 
`fish, version 3.0.2`
`Linux aenderarch 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux`

Command inducing the problem (`--interactive`):
`fish -ic 'sh'`

Problem: Keyboard input given to `sh` is not beeing displayed. Thus after typing `sh --version\n\n\n` the output looks like: 
```
user@host> sh -c 'env HOME=$(mktemp -d) fish -ic 'sh' '
sh-5.0$ fish, version 3.0.2
sh-5.0$ sh-5.0$ sh-5.0$
```
A workaround i found is using `reset` which successfully resets sh. 

Similar sounding issue: #4929

**Comment by faho** [comment] 2019-08-07 19:52
Duplicate of #2980

**Closed by faho** 2019-08-07 19:52 UTC
