### ISSUE TITLE
eval doesn't handle terminal escape sequences correctly

### ISSUE THREAD

**Issue by simotek** [fish-shell/fish-shell#5568] opened 2019-01-22 03:25 UTC
Version: 3.0.0
I am trying to call eval echo `"[green]blah [red]$foo[black]"` where [green] etc are terminal escape sequences. eval throws the following error.

![eval_issue](https://user-images.githubusercontent.com/3827011/51510524-4e827b80-1e4d-11e9-9c4d-12e270c7bff5.png)

**Comment by zanchey** [comment] 2019-01-22 11:01
What are you using to generate the escape sequences? The brackets need to be escaped. You could wrap the escape sequences in escaped quotes if needed, although always better to avoid `eval`.

**Comment by simotek** [comment] 2019-01-22 22:19
i'm using echo -e to generate the escape sequences as can be seen above, and it seems to work. For the reason I need eval for the reasons given in https://github.com/fish-shell/fish-shell/issues/5565

**Comment by zanchey** [comment] 2019-01-23 01:53
Sorry, I mean, are you using `set_color` or similar?

Anyway, piping the escape sequence through `string escape` seems to work for me:

```
set -l Z (echo -e (set_color red | string escape) "foo" (set_color green | string escape) "bar")
eval echo $Z
```

**Comment by faho** [comment] 2019-01-23 15:11
So, first of all:

"eval doesn't handle terminal escape sequences correctly". It does.

You're not quite clear on what `eval` _does_. eval takes all of its arguments together, and runs them as if they'd been given on the commandline just like eval was given them.

It's a small wrapper around `source` (that you don't actually need unless the command requires access to stdin - otherwise `echo $thing | source` is faster and better).

Now imagine I did:

```fish
set_color red > file
source file
```

What would you expect to happen? What would you expect to happen if you prepended `echo`?

What does happen is that fish sees the line `<escape>[31m` (where `<escape>` is an actual literal escape character, not `\e` but what happens when `\e` - a backslash and then an "e" - is expanded). It sees the escape and doesn't care, because escapes are just characters. Then it sees the bracket and tries to match it, because brackets are special to fish.

What you need to do, if you really actually want `eval` (you probably don't!), is to `string escape` the parts you don't want to be interpreted.

In your example here, $Z contains _nothing_ that you'd want to be expanded again, so you could also do `eval echo '$Z'` or just `echo $Z`.

In #5565 you said:

>I am trying to expand environment variables exactly once, so that I can read in something like $PATH /sbin /usr/sbin and expand it accordingly

Now, what you want to use here is double-variable-expansion - `$$var`.

If you have a function called `foo` that is called like `foo '$PATH' /sbin /usr/sbin`, you'll want something like:

```fish
function foo
    for arg in $argv
        # See if the argument starts with a "$" and remove it at the same time
        if set -l varname (string replace -rf '^\$' '' -- $arg)
            printf '%s\n' $$varname # this expands it first to "$PATH", and then expands _that_.
        else
            echo $arg
        end
    end
end
```

**Comment by simotek** [comment] 2019-01-23 23:08
> Sorry, I mean, are you using `set_color` or similar?
> 
> Anyway, piping the escape sequence through `string escape` seems to work for me:
> 
> ```
> set -l Z (echo -e (set_color red | string escape) "foo" (set_color green | string escape) "bar")
> eval echo $Z
> ```

I'm not using set_color rather i'm using the escape sequences directly, `(set_color red)` and `(echo -e "\e[0;31m")` the difference is the later will use the color "Red" that is specified by my terminal emulator, using `string escape` converts the string back to `\e\[0\;31m` which is then harder to convert back to a color then before.

**Comment by simotek** [comment] 2019-01-23 23:15
> So, first of all:
> 
> "eval doesn't handle terminal escape sequences correctly". It does.
> 
> You're not quite clear on what `eval` _does_. eval takes all of its arguments together, and runs them as if they'd been given on the commandline just like eval was given them.
> 
> It's a small wrapper around `source` (that you don't actually need unless the command requires access to stdin - otherwise `echo $thing | source` is faster and better).
> 
> Now imagine I did:
> 
> ```fish
> set_color red > file
> source file
> ```
> 
> What would you expect to happen? What would you expect to happen if you opened that file and prepended `echo`?
> 
> What does happen is that fish sees the line `<escape>[31m` (where `<escape>` is an actual literal escape character, not `\e` but what happens when `\e` - a backslash and then an "e" - is expanded). It sees the escape and doesn't care, because escapes are just characters. Then it sees the bracket and tries to match it, because brackets are special to fish.
> 
> What you need to do, if you really actually want `eval` (you probably don't!), is to `string escape` the parts you don't want to be interpreted.
> 
> In your example here, $Z contains _nothing_ that you'd want to be expanded again, so you could also do `eval echo '$Z'` or just `echo $Z`.
> 
> In #5565 you said:
> 
> > I am trying to expand environment variables exactly once, so that I can read in something like $PATH /sbin /usr/sbin and expand it accordingly
> 
> Now, what you want to use here is double-variable-expansion - `$$var`.
> 
> If you have a function called `foo` that is called like `foo '$PATH' /sbin /usr/sbin`, you'll want something like:
> 
> ```fish
> function foo
>     for arg in $argv
>         # See if the argument starts with a "$" and remove it at the same time
>         if set -l varname (string replace -rf '^\$' '' -- $arg)
>             printf '%s\n' $$varname # this expands it first to "$PATH", and then expands _that_, to leave the value of $PATH.
>         else
>             echo $arg
>         end
>     end
> end
> ```

At the moment i'm just trying to port some fish2 code to fish3, in fish2 I was using the

**Comment by simotek** [comment] 2019-01-23 23:34
> So, first of all:
> 
> "eval doesn't handle terminal escape sequences correctly". It does.
> 
> You're not quite clear on what `eval` _does_. eval takes all of its arguments together, and runs them as if they'd been given on the commandline just like eval was given them.
> 
> It's a small wrapper around `source` (that you don't actually need unless the command requires access to stdin - otherwise `echo $thing | source` is faster and better).
> 
> Now imagine I did:
> 
> ```fish
> set_color red > file
> source file
> ```
> 
> What would you expect to happen? What would you expect to happen if you opened that file and prepended `echo`?
> 
> What does happen is that fish sees the line `<escape>[31m` (where `<escape>` is an actual literal escape character, not `\e` but what happens when `\e` - a backslash and then an "e" - is expanded). It sees the escape and doesn't care, because escapes are just characters. Then it sees the bracket and tries to match it, because brackets are special to fish.
> 
> What you need to do, if you really actually want `eval` (you probably don't!), is to `string escape` the parts you don't want to be interpreted.
> 
> In your example here, $Z contains _nothing_ that you'd want to be expanded again, so you could also do `eval echo '$Z'` or just `echo $Z`.
> 
> In #5565 you said:
> 
> > I am trying to expand environment variables exactly once, so that I can read in something like $PATH /sbin /usr/sbin and expand it accordingly
> 
> Now, what you want to use here is double-variable-expansion - `$$var`.
> 
> If you have a function called `foo` that is called like `foo '$PATH' /sbin /usr/sbin`, you'll want something like:
> 
> ```fish
> function foo
>     for arg in $argv
>         # See if the argument starts with a "$" and remove it at the same time
>         if set -l varname (string replace -rf '^\$' '' -- $arg)
>             printf '%s\n' $$varname # this expands it first to "$PATH", and then expands _that_, to leave the value of $PATH.
>         else
>             echo $arg
>         end
>     end
> end
> ```

I'm mostly trying to port some code from fish2 to fish3, in fish2 the following code would take the contents of $split[2] and store it as $split[1] in some places $split[2] may contain terminal escape sequences or in other cases environment variables https://github.com/simotek/tackle/blob/simotek-theme/themes/simotek/simotek_theme_colors.en and https://github.com/simotek/tackle/blob/simotek-theme/default.env are examples.

```
set -l TMP "echo -e \"$split[2]\""
printf "%s" (eval $TMP) | read -gx $split[1]
```
for whatever reason fish2 could handle this but fish3 doesn't hence the bug questioning the change in behavior. Id rather not have to loop through and do this manually it seems like its the sort of thing that fish should have an internal way of doing this rather then having to loop through my string and do it manually.

**Comment by faho** [comment] 2019-01-24 08:16
```fish
set -l TMP "echo -e \"$split[2]\""
printf "%s" (eval $TMP) | read -gx $split[1]
```

@simotek: What is `$split[2]` here? Because if I set it to the literal `\e[0;30m# Black` from your env file and run that, it works for me? It's still got the comment attached, but I can't see how 2.7 would have stripped it?

I.e. where is `__tacklebox_load_env_file` defined?

**Comment by faho** [comment] 2019-02-10 18:46
@simotek: Ping? Could you point me towards `__tacklebox_load_env_file`?

**Comment by simotek** [comment] 2019-02-11 01:18
https://github.com/simotek/tacklebox/blob/feature-env-loader-theme/tacklebox.fish has the version that was working with fish2, 

https://github.com/simotek/tackle/blob/simotek-theme/themes/simotek/simotek_theme_colors.en is an example file that was being loaded.

Sometimes $split[2] might contain something like `$SHIRT` or `$PATH` and with fish2 I was using eval to expand those variables and the echo -e to convert the escape sequences.

**Comment by faho** [comment] 2019-02-11 15:57
@simotek: I don't know what to tell you, `__tacklebox_load_env_file simotek_theme_colors.en` works for me in 3.0.

Even if I change a line to

```fish
smtk_clr_red_h=$smtk_clr_white\e[0;90m# whiteblack
```

it still works. It expands the variable and everything.

Maybe you've reduced your test case wrong?

**Comment by faho** [comment] 2019-03-14 11:00
Closing because I can't reproduce.

**Closed by faho** 2019-03-14 11:00 UTC
Labels: question

**Comment by a7hybnj2** [comment] 2020-01-06 03:56
Hi, I just wanted to check on this. I just brew install fish and the version I received still had the character issue. If you look at previous comments there was a fix in --HEAD so I again `brew uninstall fish; brew install --HEAD fish` and that fixed my problems.

I think I was lead to believe, maybe since the previous issue was closed, that it was fixed. Can anyone provide insight on this?

I am happy to run HEAD for now but just thought I would check.
