### ISSUE TITLE
Aliases don't inherit completions from the aliased command

### ISSUE THREAD

**Issue by rgeorgiev583** [fish-shell/fish-shell#5843] opened 2019-04-25 08:49 UTC
Although the manpage describes that the `alias` command should generate a function entry which wraps the command being aliased, completions for that command don't work using the alias at all.  More specifically, there is no `--wraps` option in the function definition generated by the alias:
```
>alias dog=cat
>type dog
dog is a function with definition
# Defined in - @ line 1
function dog --description 'alias dog=cat'
    cat $argv

end
```

The issue is reproducible even after executing the `sh -c 'env HOME=$(mktemp -d) fish'` command.

Here's some information about the software I'm running:
* fish: `3.0.2`
* OS: `Linux hostname 5.0.8-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 17 14:56:15 UTC 2019 x86_64 GNU/Linux`
* terminal: `xterm-256color`

According to the changelog, this behavior is supposed to have been implemented in version 3.0b1 and there were no indications of it being removed in later releases.

**Comment by floam** [comment] 2019-04-25 22:56
Actually, `alias` does make functions with the `--wraps` flag. The problem is that `functions` doesn't reproduce that option.

For example:

```fish
$ function foo --wraps bar; echo this is a function; end
$ functions foo
function foo
	echo this is a function;
end
```

**Comment by floam** [comment] 2019-04-25 22:58
Duplicate of #1625

**Closed** 2019-04-26 13:03 UTC
Labels: duplicate
