### ISSUE TITLE
Feature request: Output math to base 16, 8, 2

### ISSUE THREAD

**Issue by tripathiu** [fish-shell/fish-shell#8102] opened 2021-07-02 00:42 UTC
It would be nice to output math expression in a different base. For example:

```
math -b16 6 + 4
0xa
```

or maybe,

```
math -b hex 6 + 4
0xa
```

----------

### Fish version
```
[~] > fish --version && echo $version
fish, version 3.1.0
3.1.0
```

### OS
```
[~] > uname -a
Linux spectre 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by faho** [comment] 2021-07-02 05:00
Duplicate of #7496

**Comment by faho** [comment] 2021-07-02 05:00
Good news! Upgrade, and you have it!

Well, hex and octal - binary isn't easily available.

**Closed by faho** 2021-07-02 05:00 UTC
