### ISSUE TITLE
Bug in autocomplete for cd

### ISSUE THREAD

**Issue by sephamorr** [fish-shell/fish-shell#2748] opened 2016-02-21 00:32 UTC
When using tab autocomplete after typing the following strings in prompt, fish gets angry in one specific case:
First what works:
`ls someletters[` (note the square bracket. Every other executable that I tested except cd works correctly)
What doesn't:
`cd someletters[` with error:
```
Unexpected end of string, square brackets do not match
- (line 1): begin; printf "%s\n" someletters[*/ 
 ;end <&3 3<&-
                                 ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 45 of file /usr/share/fish/functions/__fish_complete_cd.fish

in function “__fish_complete_cd”
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “-”
```

I'm using fish 2.2.0, on Ubuntu 15.10

**Comment by faho** [comment] 2016-02-21 00:43
This is a duplicate of #562. Also, the situation is much improved in current git since the cd completion has been rewritten to not use eval.

**Closed by faho** 2016-02-21 00:43 UTC

**Comment by sephamorr** [comment] 2016-02-21 00:51
Sorry to bother, I hadn't seen #562. Thanks.
