### ISSUE TITLE
Typing Danish letters now pastes the clipboard into the terminal

### ISSUE THREAD

**Issue by M0rtenB** [fish-shell/fish-shell#7660] opened 2021-01-26 12:48 UTC
I use a Danish keyboard. Been using Fish for years with no issue. I just discovered lately that pressing the æ, ø and å key while the Fish prompt is active no longer inserts the corresponding letters, but acts as if I pressed cmd-v and pastes the clipboard.

One more thing: If I place a sequence of letters containing these danish letters on the clipboard and try to paste them into the Fish prompt, only the non-Danish letters are inserted.

I don't know how long this behavior has been there, presumably since I updated to MacOS 11.1.

If I switch to bash, there is no longer any issue!

Fish version 3.1.2. MacOS 11.1. Standard Terminal.app.
Trying "sh -c 'env HOME=$(mktemp -d) fish" makes no difference to this behavior.

**Comment by faho** [comment] 2021-01-26 13:00
Duplicate of #6341

**Comment by faho** [comment] 2021-01-26 13:01
@M0rtenB: You've reported this previously, the issue is you turned on "Escape non-ASCII input with Control-V" in the terminal again.

Bash uses ctrl-v to insert the next character literally, fish uses ctrl-v to paste.

**Closed by faho** 2021-01-26 13:00 UTC

**Comment by M0rtenB** [comment] 2021-01-26 13:05
I'm sorry. I thought it seemed familiar. Thanks for pointing it out. 😞
