### ISSUE TITLE
Suggestion - option to refresh prompt every N seconds

### ISSUE THREAD

**Issue by suspiciousfellow** [fish-shell/fish-shell#7410] opened 2020-10-21 14:18 UTC
Like many others I expect, I have several terminal windows open with a prompt that, when inside a git repository, indicates the current branch at the time that the prompt is evaluated. With many windows open and many branches within my company's monorepo, it's quite likely that this isn't the same branch by the time I get around to typing something in the prompt.

It would be a pretty cool feature if you could set the prompt to be re-evaluated every few seconds or so. That way all my terminal windows would indicate the correct branch within a few seconds if I check another one out.

**Comment by mqudsi** [comment] 2020-10-24 02:47
This requires full async support in the prompt, which isn't yet something that fish exposes in a very ergonomic fashion.

You could adapt @acomagu's clever approach in https://github.com/acomagu/fish-async-prompt to background an external process (fish or sh) that sends a signal to fish, triggering a user-defined event handler to run and generate output consumed by the prompt.

**Comment by suspiciousfellow** [comment] 2020-11-16 20:51
Thanks - I'll give extending his approach into what I'm after a go and publish the results :)

**Comment by faho** [comment] 2020-11-27 14:48
Duplicate of #1942

**Closed by faho** 2020-11-27 14:48 UTC
