### ISSUE TITLE
No PATH in child processes of a login shell

### ISSUE THREAD

**Issue by limadm** [fish-shell/fish-shell#3024] opened 2016-05-11 17:46 UTC
I started using fish-shell recently, it is really fun to use, so I have set it as my login shell!
But I have spotted a very strange problem, it seems that the `$PATH` variable is not passed to child processes of the login shell. Note that reading other variables (e.g. `$USER`) works.

### Reproduction Steps:

1. Open a *login* terminal (e.g. in xterm type `fish -l`)
2. Type the commands:
```
which su
lua -e 'print(os.getenv("PATH"))'
lua -e 'print(os.getenv("USER"))'
python -c 'import os; print(os.getenv("PATH"))'
python -c 'import os; print(os.getenv("USER"))'
cd
which su
fish -c 'which su'
fish -l -c 'which su'
```

### Expected behavior:

`which` invocations should output `/usr/bin/su`, and the lua/python scripts should output the `$PATH` and `$USER` variables.

### Observed behavior:

Only the `fish -c 'which su'` command has a valid `$PATH`, as follows:

	dan@arch ~> which su
	which: no su in ((null))
	dan@arch ~> lua -e 'print(os.getenv("PATH"))'
	nil
	dan@arch ~> lua -e 'print(os.getenv("USER"))'
	dan
	dan@arch ~> python -c 'import os; print(os.getenv("PATH"))'
	None
	dan@arch ~> python -c 'import os; print(os.getenv("USER"))'
	dan
	dan@arch ~> cd
	dan@arch ~> which su
	/usr/bin/su
	dan@arch ~> fish -c 'which su'
	/usr/bin/su
	dan@arch ~> fish -l -c 'which su'
	which: no su in ((null))
	dan@arch ~>

### Additional information:

It happens all the time, tested with fresh install and configuration directory.

### Solution:

As a simple workaround, I am spawning a second fish process with `exec` at login (`~/.config/fish/config.fish`).

	if status --is-login
		set -x PATH ~/bin /usr/local/bin $PATH
		if test -z "$DISPLAY" -a "$XDG_VTNR" -eq 1
			exec startx -- -keeptty
		else
			exec fish
		end
	end

---
Fish version: 2.2.0

Operating system: Arch Linux

Terminal or terminal emulator: tested on urxvt / xterm / tmux.

**Comment by krader1961** [comment] 2016-05-11 18:22
Is that your entire *config.fish*? Have you verified that `$PATH` is sensible when fish starts running? If you put `env | grep PATH` at the top of your *config.fish* does it output a reasonable value for PATH. What does `set -x | grep PATH` output if you put it at the top of your *config.fish*?

**Comment by ridiculousfish** [comment] 2016-05-12 06:14
This is extremely weird. What do `set | grep PATH` and `set -x | grep PATH` show?

**Comment by limadm** [comment] 2016-05-14 01:22
Yes, just that. I have also confirmed the value of `$PATH` before, it was set to:
```
dan@arch ~> env | grep PATH
PATH=/home/dan/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
dan@arch ~> set -x | grep PATH
PATH '/home/dan/bin'  '/usr/local/bin'  '/usr/bin'  '/bin'  '/usr/sbin'  '/sbin'
dan@arch ~>
```
The child processes in the first examples couldn’t get the `$PATH`, but please note that `which su` works when invoked after `cd`, i.e. it reads the correct `$PATH`. I also have tested with other built-ins, e.g. `type su` works normally and prints `su is /usr/bin/su`, but does not fix the `$PATH` for subsequent processes as `cd` does.
By the way, sorry for the late reply... I was trying to find this bug by myself, but I couldn’t reproduce it, so I think it may be a packaging bug in Arch Linux.

**Comment by krader1961** [comment] 2016-05-14 02:16
Not sure what you mean by "Yes, just that." Also, I wanted the output of those commands when placed at the top of your *config.fish*, not when run interactively. It would probably be a good idea to add those two commands to your *config.fish* then enter the following sequence of lines literally:

```
script /tmp/fish.txt
fish -d5
echo hello
exit
exit
```

Then attach */tmp/fish.txt* to your next comment.

**Comment by krader1961** [comment] 2016-05-14 02:54
> I was trying to find this bug by myself, but I couldn’t reproduce it, ...

Are you no longer able to reproduce this problem? If true do you have any ideas as to what the cause and fix are?

**Comment by krader1961** [comment] 2016-05-17 03:10
Is this still an issue for you, @limadm?

**Comment by limadm** [comment] 2016-05-21 09:35
Sorry for the confusion. I meant to say just “Yes”, like:

> Yes.

I did what you suggested and it began to work when I added `which su` to the beginning of my `config.fish`. I didn't get why it just worked, so I checked what every line of my `config.fish` and `functions/*` did, and then I have found an interesting behavior.

I added a `check_system` function which translates `uname`'s MSYS and MINGW results to "Windows". Inside that function, I set the locals `PATH` and `osname`, which I thought not to conflict with the outer scope (I assumed that function definitions had an implicit block scope), but they did. The statement `set -l PATH ...` inside a function definition sets the `PATH` variable in the calling scope, which is the outer scope of the login shell. I still don't know why it don't happens in children shells. Nevertheless, I think this issue can be closed. In the end, it was my mistake from a pausible assumption.

Finally, could you check this behavior and document it in `help functions`, please?
Alternatively, functions could have an implicit block scope, which removes their power of changing the outer scope environment -- a seeming duplicate of `set -g` in some sense.

**Comment by faho** [comment] 2016-05-21 09:49
>The statement set -l PATH ... inside a function definition sets the PATH variable in the calling scope, which is the outer scope of the login shell.

I'm quite sure it doesn't. Not like you are thinking, at least.

```fish
set -gx var value
function t
    set -l var othervalue
    echo $var # will print othervalue
end
t
echo $var # will be value, not othervalue
```

The issue here is the export-bit. Which makes this a duplicate of #2611.

**Closed by faho** 2016-05-21 09:49 UTC
Labels: question
