### ISSUE TITLE
Pasting certain input can make subshell unresponsive

### ISSUE THREAD

**Issue by dnicolson** [fish-shell/fish-shell#9260] opened 2022-10-04 18:45 UTC
To reproduce, run the following command:
```
fish --login
```

And now paste the following:
```
cat '{\"x\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\"x\":\"x\",\"x\":x,\"s\":\"x\",\"x\":\"x\",\"x\":\"x\",\"x\":x}"}'
```

The input is very unique and slight modications can result in the issue not appearing, this was previously reduced from a large JSON object.

fish 3.5.1
Darwin Kernel Version 22.1.0: Tue Sep 20 10:43:35 PDT 2022; root:xnu-8792.40.108.191.2~2/RELEASE_ARM64_T6000 arm64
xterm-256color
iTerm 3.5.0beta6

**Comment by faho** [comment] 2022-10-04 18:47
Works for me.

Please confirm you are in fact running fish 3.5.1, and list the output of the following:

```fish
bind --user

sha256sum (functions --details fish_clipboard_paste)
```

Also please try without customization, like the issue template asks.

**Comment by dnicolson** [comment] 2022-10-04 18:57
Here is the output:
```
bind \cd delete-char
02828e059c6de32060be148f82d33a2c9c70f6c619337c5ff8c968a04b99934a  /opt/homebrew/Cellar/fish/3.5.1/share/fish/functions/fish_clipboard_paste.fish
```

I can reproduce it running `env HOME=$(mktemp -d) fish` and the `config.fish` file is empty except for needed Homebrew environment variables.

What if you paste the input a second time?

**Comment by faho** [comment] 2022-10-04 19:08
>What if you paste the input a second time?

I can paste it as much as I want, it's instantaneous.

Do you paste via ctrl-v, or via your terminal's paste function?

Can you confirm that this particular input triggers it? As in you haven't accidentally censored anything that's needed for it to reproduce the issue? Copy the input from the code field on github.

**Comment by dnicolson** [comment] 2022-10-04 19:23
I am pasting using Command-V.

The issue was 100% reproducible and also on an Intel Mac running macOS 12, but just now it took a few tries to reproduce this:

Uploading Screen Recording 2022-10-04 at 21.17.37.mov…

**Comment by faho** [comment] 2022-10-04 19:27
Have you tried just keeping typing?

This looks like it's just going beyond the screen, which has a few known issues, but nothing that actually hangs the shell.

**Comment by dnicolson** [comment] 2022-10-04 19:33
The problem is that the shell doesn't respond to Ctrl-D or Ctrl-Z. Typing random characters resulted in this behavior:

https://user-images.githubusercontent.com/2276355/193909205-d8391b1c-bf33-4570-9abb-071961610679.mov

**Comment by faho** [comment] 2022-10-04 19:39
This is a rendering issue. Your ctrl-d is bound to "delete-char", which would delete one char *forward*.

Try pressing ctrl-c.

**Comment by dnicolson** [comment] 2022-10-04 19:43
No luck, the only way out seems to be to quit the terminal.

**Comment by faho** [comment] 2022-10-04 19:45
Okay, do this:

```fish
commandline -i (cat share/functions/fish_git_prompt.fish)
```

*now* press ctrl-c.

**Comment by dnicolson** [comment] 2022-10-04 19:49
That worked in getting the prompt back:
![PixelSnap 2022-10-04 at 21 48 05@2x](https://user-images.githubusercontent.com/2276355/193912007-8ad8afb3-e6cb-42fd-9eb6-1d4c91425ada.png)

**Comment by faho** [comment] 2022-10-04 19:49
Duplicate of #7296

**Closed by faho** 2022-10-04 19:49 UTC
Labels: needs more info

**Comment by faho** [comment] 2022-10-04 19:52
That's the same as 7296 then. Your shell isn't *actually* unresponsive, it just looks that way because it's having a time rendering your stuff - it tries to fit X lines into Y rows, where Y < X.

This ends up... not good.
