### ISSUE TITLE
duplicate echo in fish prompt, with osx terminal.app

### ISSUE THREAD

**Issue by aeosynth** [fish-shell/fish-shell#742] opened 2013-05-12 23:34 UTC
fish_prompt.fish

```
function fish_prompt
  echo $PWD
  echo '> '
end
```

when i launch the osx (10.7.5) default terminal.app, with fish as my default shell, the pwd is echo'd twice. this happens only on new launches, not when opening new windows / tabs. [iterm2](https://code.google.com/p/iterm2/) beta does not show the duplicate echo

**Comment by krader1961** [comment] 2016-04-07 17:55
This is very old and I can't reproduce the problem so closing the issue.

**Closed by krader1961** 2016-04-07 17:55 UTC
Labels: will-not-fix
