### ISSUE TITLE
`eval (__fzfcmd)` sometimes fails

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#4135] opened 2017-06-17 10:53 UTC
Fish version: 2.6
Terminal: Urxvt 9.22
OS: Arch Linux
fzf:  0.16.8

Install [fzf](https://github.com/junegunn/fzf/) and add the following to your config:

```
function fzf-bcd-widget -d 'cd backwards'
	pwd | awk -v RS=/ '/\n/ {exit} {p=p $0 "/"; print p}' | tac | eval (__fzfcmd) +m --select-1 --exit-0 | read -l result
	[ "$result" ]; and cd $result
	commandline -f repaint
end
bind \e\cL fzf-bcd-widget
```

More than half the times this will fail to do anything and a terminated `fzf` process will be forked.
It works when `eval (__fzfcmd)` is replaced by `fzf`.

Note that other functions with a similar use of `eval (__fzfcmd)` work without an itch, e.g. the official
https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish#L43.

**Comment by faho** [comment] 2017-06-17 20:21
Duplicate of #3952. The issue is that we put the commands in the pipeline into different process groups, and which of those gets control of the terminal is up to timing.

Note that the `__fzfcmd` function is implemented in an unnecessarily roundabout way - right now it prints commands to be executed via `eval`, when it could just execute them directly. I've worked on this and related changes, but I've not found the time to upstream them to fzf.

**Closed by faho** 2017-06-17 20:21 UTC
