### ISSUE TITLE
How to make fish stop output "⏎" character?

### ISSUE THREAD

**Issue by HuJK** [fish-shell/fish-shell#4882] opened 2018-04-07 05:10 UTC
I know this issue:
https://github.com/fish-shell/fish-shell/issues/789

but bitvise ssh terminal can't handle it.
How to config fish to make it like bash, don't output  "⏎" character?
![image](https://user-images.githubusercontent.com/15907444/38451579-09307b3a-3a65-11e8-80f4-73a20795528d.png)

fish, version 2.6.0

**Comment by HuJK** [comment] 2018-04-07 05:46
zsh works well.
![image](https://user-images.githubusercontent.com/15907444/38451802-24a8353e-3a69-11e8-9f8e-f398651978f9.png)

I don't care  the % symbol appears some time.

But the ⏎ char appear in every line.

**Comment by faho** [comment] 2018-04-07 20:27
Let's close this one as a duplicate of #4717.

We need to figure out what zsh is doing differently here.

**Closed by faho** 2018-04-07 20:27 UTC

**Comment by HuJK** [comment] 2018-04-08 04:53
I think it is different. 

https://github.com/fish-shell/fish-shell/issues/4717 is talking about how to change the terminal emulator's behavior

But I am talking how to change the fish's behavior. 

Because not only bitvise ssh, jupiter lab has same issue:
![image](https://user-images.githubusercontent.com/15907444/38463366-c3ec0072-3b2b-11e8-82e9-879eb1d11bc1.png)



I don't want to configure every terminal emulator that can't handle it well.

**Comment by faho** [comment] 2018-04-08 11:42
>I think it is different.

It's not. The issue is about finding the solution to the problem, which is the same as here - sometimes a "⏎" shows up in your terminal where it shouldn't.
