### ISSUE TITLE
Ligatures not displaying correctly

### ISSUE THREAD

**Issue by slippuu** [fish-shell/fish-shell#10830] opened 2024-11-04 14:41 UTC
Result of `echo $version`:
`3.7.1`

Result of `uname -a`:
`Linux archlinux 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux`

Result of `echo $TERM`:
`xterm-kitty`

Issue still occurs after running `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'`

This has been attempted on both kitty (`xterm-kitty`) and qterminal (`xterm-256color`).

When attempting to use certain ligatures, they don't display correctly (as shown) whereas some others do.
![20241104_14h32m44s_grim](https://github.com/user-attachments/assets/98c6fe5d-fcea-4456-b301-a365d8582f46)
![20241104_14h33m00s_grim](https://github.com/user-attachments/assets/48ed2f82-75f3-4fd3-b2dd-f46b6a9e98f7)
![20241104_14h33m09s_grim](https://github.com/user-attachments/assets/1c32d357-5caf-4d49-996d-3b93e6e7d08e)
Even switching to bash from fish I'm then able to use the ligatures no problem
![20241104_14h33m25s_grim](https://github.com/user-attachments/assets/9320eb32-1afd-433c-9f5f-92ec407e8644)

At first I thought it was the terminal and colors, which is when I switched from kitty to qterminal but still suffered the same. I have tried with various ligature-supported fonts (`CaskaydiaCove Nerd Font` and `FiraCode Nerd Font`) and the experience is the same. I was also doubtful it was the terminals issue in displaying them correctly as the start of the prompt shows the ligature for `~>` correctly.

**Comment by faho** [comment] 2024-11-04 15:04
Fish will, in some cases, print color sequences between characters.

It appears that confuses your terminal into no longer selecting the ligature.

That would have to be fixed in the terminal.

**Closed by faho** 2024-11-04 15:04 UTC

**Comment by zanchey** [comment] 2024-11-06 14:06
I wouldn't have thought the first example makes sense as a ligature if it changes colour halfway through?

**Comment by tunix** [comment] 2025-01-16 20:13
Hi @faho , I experience the same issue. Tried different terminals: Ghostty, Wezterm, iTerm2

None of them were able to show `->` correctly. Just like @slippuu , I tried switching to bash or zsh and it shows the ligature as expected.

![Image](https://github.com/user-attachments/assets/30afe226-fceb-4cd4-8eca-e02cc9fbe3d4)

Any change you'd reconsider your opinion about this?

**Comment by faho** [comment] 2025-01-16 20:38
> Any change you'd reconsider your opinion about this?

Ghostty 1.0.1:

![Image](https://github.com/user-attachments/assets/8fa236ba-919f-4f92-8f5a-e91c17d2e483)

The issue is that `->` outside of quotes "the string '-' that starts an option followed by a redirection", and so fish will color the two parts separately (similar for "==>" - "the string '==' and a redirection"). That `<>` is an actual error and so the `>` will be red.

It will work in quotes or, for `->`, after a `>`:

![Image](https://github.com/user-attachments/assets/fc04c64b-429c-4e7c-b03f-8460d09e69b1)

There isn't really anything to reconsider - this is working. It's just syntax highlighting.
