### ISSUE TITLE
fish hangs on tab completion for vi when vi is aliased to vim using function

### ISSUE THREAD

**Issue by wlnirvana** [fish-shell/fish-shell#3677] opened 2016-12-24 14:52 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
`fish, version 2.4.0`

**OS/terminal used**: 
`Linux x260 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux`

Talk about the the issue here. 
With the following `~/.config/fish/config.fish`, when I type `vi ` and then press `<TAB>` to get autocompletion, fish just hangs.
```
function vi
	  vim
end
```
However, if aliased is used, like the following, everything works just fine.
```
alias vi vim
```

**Comment by faho** [comment] 2016-12-24 17:16
I can reproduce this. `strace` tells me fish is stuck doing

    select(7, [6], NULL, NULL, {tv_sec=0, tv_usec=10000}) = 0 (Timeout)

in a loop.

The vi completions are a tiny bit special, in that they automatically wrap the "vim" ones if `vi --version` returns 0:

```fish
if type -q vi
    # Check if vi is really vim
    if vi --version > /dev/null ^ /dev/null
        complete -c vi -w vim
    else
```

with your function, which is a tiny bit broken, it'll execute `vi --version`, which will execute `vim`, **without arguments** (this would be fixed by the alias, though that will also directly set up the vim completions as the ones to use).

That will then run without output (since stdout isn't connected), and without terminating (since, presumably, it's still theoretically a running vim). Fish will then wait for it to terminate.

I'm not sure if we can do anything about this other than fixing #23 in general. I'm keeping this issue open for another week or so to see if anyone has an idea, otherwise we should close this as a duplicate.

**Comment by faho** [comment] 2016-12-24 17:17
Also, you should basically always pass "$argv" in wrapper functions like this -

```fish
function vi
    vim $argv
end
```

**Comment by krader1961** [comment] 2016-12-24 20:38
@wlnirvana: To expand on @faho's answer if you run `type vi` after doing `alias vi vim` you'll see

```
vi is a function with definition
function vi --description 'alias vi vim'
    vim $argv
end
```

The inclusion of `$argv` is why it works and your function does not.

@faho: If you type `vim >/dev/null ^/dev/null` you'll see that vim is actually running and waiting for user input. If you press `:q[enter]` it will exit and return you to a shell prompt. If you install the OPs broken function definition and induce the apparent hang all you have to do is type `:q[enter]` to break the "hang". Simply modifying the test in the *vi.fish* completion script to

```
if vi --version < /dev/null > /dev/null ^ /dev/null
```

will keep the "hang" from happening. This isn't really a dup of issue #23 and I'm not convinced we should be trying to modify our scripts to deal with broken functions users may have installed.

**Comment by wlnirvana** [comment] 2016-12-25 07:26
Thanks @faho and @krader1961. Adding `$argv` does solve the issue.

**Closed** 2016-12-29 03:05 UTC
Labels: question

**Comment by OJFord** [comment] 2019-04-25 10:45
I was about to open a near duplicate issue of this, but the resolution doesn't quite apply - my `vi` is `/usr/local/bin/vi` which is a (Homebrew-installed) symlink to `vim`.

I've now aliased `vi vim` in fish, so hopefully that will work around it.
