### ISSUE TITLE
fish as login shell prevents NoMachine from running

### ISSUE THREAD

**Issue by dmd** [fish-shell/fish-shell#10280] opened 2024-02-02 12:22 UTC
(version 3.7.0)

When fish is set as my login shell, [NoMachine](https://www.nomachine.com/) cannot start a session.

NoMachine support writes;

> fish needs a TTY in order to work correctly. Our SSH connection has TTY disabled to work as a transparent tunnel, however we need to run the server instance once we are connected, in order to initiate the handshaking. Such command is just ignored when executed in a non-TTY fish instance.

**Comment by faho** [comment] 2024-02-02 12:26
Duplicate of #6967.

**Comment by faho** [comment] 2024-02-02 12:26
It appears NoMachine expects the shell to run commands line-by-line, as they are sent.

Fish expects to read all its input, parse it fully and only run it if there are no syntax errors.

**Closed by faho** 2024-02-02 12:26 UTC

**Comment by dmd** [comment] 2024-02-02 12:30
Is there a workaround from NoMachine's perspective? Seems like there isn't?

**Comment by faho** [comment] 2024-02-02 12:33
This is apparently a fundamental expectation on both sides, and neither can be tricked into not doing it.

So the recourse is to not make fish your login shell (you could start it interactively from your login shell), or to not use NoMachine.

**Comment by dmd** [comment] 2024-02-02 12:34
OK, thanks.

**Comment by dmd** [comment] 2024-02-02 12:40
[Convenient workaround](https://unix.stackexchange.com/questions/476107/how-to-use-fish-on-remote-servers-that-have-it-installed-without-changing-login?rq=1) for others' future reference: make an alias so that when connecting to the machine in question (which does not have fish as my login shell), connect as `ssh that-machine -t "sh -c 'exec fish -li'"`
