### ISSUE TITLE
Vim Bindings: Normal mode number prefix

### ISSUE THREAD

**Issue by AlexSWall** [fish-shell/fish-shell#10012] opened 2023-09-10 16:41 UTC
Fish shell doesn't currently support using numbers before operators/etc. in its vim mode normal mode. For example, `4W` would not go forward four words—only one.

I understand the long-term aim for fish shell is not to attempt to perfectly implement all of vim's features, and I'm hoping Neovim in the future offers Readline-like functionality.

However, I think this addition would be a big improvement in the meantime (at least for me) and cannot find any issue referencing this request. (The best I saw was one maintainer many years ago suggesting this would be hard to do.)

What would be required to add this? How feasible actually is it?

**Comment by faho** [comment] 2023-09-10 17:03
Duplicate of #4019

**Closed by faho** 2023-09-10 17:03 UTC

**Comment by faho** [comment] 2023-09-10 17:07
> What would be required to add this? How feasible actually is it?

What would be required is something that actually *understands* vi.

Currently, you would bind `dw` to `delete-word`. What would have to be done is binding `<operation><number><object>`.

And that's basically an overhaul of the entire vi-binding system. Which it is in dire need of anyway, but which isn't likely to happen because none of the core contributors use vi-mode.

Sorry!

**Comment by AlexSWall** [comment] 2023-09-11 22:01
@faho It's not clear to me that this is a duplication of that ticket? If anything, you can close for the 'master' fish vim bindings ticket, but I intended for this to not be 'just another bug' so much as something I'd be genuinely interested in fixing myself.
