### ISSUE TITLE
pwd output on deleted path is non-standard

### ISSUE THREAD

**Issue by pik** [fish-shell/fish-shell#2129] opened 2015-06-10 14:25 UTC
So the standard bash output if you are currently in a directory which has already been deleted on `pwd` is to print the directory nevertheless. In contrast to bash Fish does not print anything. This means for example that a `fish_title` or other function calling `pwd` will error when a directory has been deleted from under the current shell-path. 

Not sure if this might not be "working as intended" but it does introduce certain problems which `bash` does not otherwise have.

**Comment by ridiculousfish** [comment] 2015-06-10 17:33
I'm not sure what you're seeing. Can you please provide steps to reproduce?

**Comment by pik** [comment] 2015-06-11 06:07
Terminal 1: 
`cd /home/user; mkdir deleteme; cd deleteme;`
Terminal 2: 
`rmdir deleteme` 
Termin 1: 
`pwd` 

Expected output: 
`/home/usr/deleteme` 
Actual output: 
``

**Comment by ridiculousfish** [comment] 2015-06-11 06:12
Can't reproduce on OS X Yosemite; looks like this is Linux specific.

**Comment by pik** [comment] 2015-06-11 11:40
Are you sure I'm trying this on OS X 10.10.3 w/ what seems to be the same effect?

**Comment by ridiculousfish** [comment] 2015-06-11 18:53
What is your `$FISH_VERSION`?

It looks like early versions of fish had a `pwd.fish` function that wrapped `echo $PWD`. I happened to have that installed and it explained the behavior I was seeing on OS X.

On fish 2.1, `pwd` resolves to `/bin/pwd` which of course cannot know the name of the deleted directory. On fish 2.2, `pwd` is a builtin (like in bash) but it wraps `getcwd` instead of `$PWD`.

The big advantage of wrapping `getcwd` is that it correctly tracks renamed directories, something that bash doesn't do. We could consider falling back to `$PWD` if `getcwd` fails.

**Comment by pik** [comment] 2015-06-11 19:33
[2.1.2](https://www.archlinux.org/packages/community/x86_64/fish/) on linux, not sure about the OS X version. 

> The big advantage of wrapping getcwd is that it correctly tracks renamed directories, something that bash doesn't do. We could consider falling back to $PWD if getcwd fails.

I'm not sure the lack of output is even bad - but it would need to be accounted for (for example `switch(pwd)` will produce errors if the directory has been deleted - I wonder how numerous are the scripts or aliases which rely on the `bash` behaviour?

**Comment by nathansgreen** [comment] 2017-01-05 21:47
I think this issue is related to what I'm experiencing. I often have directories deleted and re-created out from underneath me. Bash handles the situation just fine, Fish does not. Example:

```bash
mkdir abc; cd abc; rmdir ../abc; mkdir ../abc; pwd
```
```diff
- <E> fish: getcwd() failed with errno 2/No such file or directory
```
It also doesn't work to do `cd .` once the current directory has been recreated, which intuitively seems like it should work. The only way to make it work is to know which parent directory was deleted and do a relative `cd` all the way back to its parent and then down to whatever the current directory was before. The simplistic `cd ../abc` works fine for a counter-example but is unworkable in most real-world scenarios I've run into and is more or less pathological.

**Comment by krader1961** [comment] 2017-01-05 22:11
> ..., which intuitively seems like it should work.

Unfortunately your intuition is wrong. Try this in bash:

```
mkdir abc; cd abc; rmdir ../abc; mkdir ../abc; touch ../abc/def; ls; cd ../abc; ls; rm -rf ../abc; touch ghi
```

Bash isn't doing anything special. Bash does not recognize that the new "abc" directory exists and does not implicitly cd to it after you recreate it. The pwd for bash, and fish, and zsh, is still the original "abc" directory. When you `rmdir ../abc` you're really just deleting the name. Since the shell holds a reference to the directory, by virtue of its cwd, the directory isn't actually deleted until that reference is released by doing another `cd` command.

**Comment by nathansgreen** [comment] 2017-01-05 22:54
In Bash, `cd .` works, in Fish it does not. That's not particularly special for Bash, it's just a very unfriendly behavior for Fish. The only Bash error in your command series is the last command, which obviously cannot succeed, so I don't see how it's particularly helpful.

**Comment by krader1961** [comment] 2017-01-06 03:47
> In Bash, cd . works, in Fish it does not.

It sort of works in bash. Try this:

```
mkdir abc; cd abc; rmdir ../abc; cd .
```

You should get this error:

```
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

And typing `pwd` at that point produces this weird output: `/Users/krader/tmp/abc/.`. Note the trailing `/.` which would not normally be present. As soon as you do `mkdir ../abc; cd .` that pwd output goes back to the expected `/Users/krader/tmp/abc` (without the weird trailing `/.`).

What bash appears to be doing after you recreate the directory is the equivalent of `cd $PWD` when you type `cd .`. Note that until you do the `cd .` **bash will not use the recreated directory**. Nor will any external commands run from that bash shell. That was the whole point of the example in my previous comment.

The UNIX model for directories, including the current working directory for processes, does not work the way you think it does. Bash kind of papers over the problem; that is, it imperfectly hides the problem. Fish will never implement that broken "fix" as long as I have a vote on the matter. It is one reason so many people, like yourself @nathansgreen, have an incorrect mental model for how this works.

Having said that I do think it is sensible for fish to output `$PWD` if the `getcwd()` syscall fails with ENOENT. Possibly by appending `/.` like bash does to provide a clue it isn't authoritative.

**Comment by krader1961** [comment] 2017-01-06 04:01
Also, note that fish does not update the `PWD` var after its cwd has been deleted and you try to `cd .`. So after recreating the directory (e.g., `mkdir ../abc`) you can successfully `cd $PWD` to switch to the new *abc* directory.

As I said before bash is apparently just converting `cd .` to `cd $PWD` in that situation. Which doesn't really address the problem that until that `cd .` is done the cwd is completely unusable either by bash or by any external command it runs. That mapping of `cd .` to `cd $PWD` is a hack that only obscures the problem and gives people the wrong idea about how the concept of a current working directory actual works.

**Comment by nathansgreen** [comment] 2017-01-06 04:38
I disagree. `cd .` doesn't "sort of work," in Bash, it works. If the path doesn't exist, it must return an error: no user finds that surprising. What is surprising is that Fish will happily display the entire path in the prompt and then utterly fail when I type `cd .` *when that path exists*. Users think in terms of paths. (It is a shell, after all.) If I can `cd` to the absolute path on my prompt, which displays repeatedly every time I get one of these errors, there's no reason why `cd .` should fail.

The inverse of this logic holds as well, by the way. If `cd .` cannot be reasonably expected to work (i.e. Bash is wrong) then `cd ..` should fail in just the same way. And yet, with a bit of fiddling, Fish can somehow manage this:
```bash
mkdir -p ~/tmp/abc/def; cd ~/tmp/abc/def; rmdir ../def; rmdir ../../abc; mkdir -p ~/tmp/abc/def; cd ../../abc/def; pwd
```

The current Fish behavior exposes the fact that its implementation is tied to low-level Unix filesystem semantics. Good interfaces do not expose implementation details. Users don't ordinarily think in terms of descriptors. Bash does the right thing because it doesn't force the user to act differently depending on the implementation details of the operating system.

It's not surprising to get an error if your current directory no longer exists. It's very much surprising to get an error that says your current directory doesn't exist when in fact it does, since the current directory is, to a user, defined by a path. Even more surprising when you've displayed a prompt that tells them their current directory and given them an error message saying that directory does not exist, and yet every other process on their machine will tell them that it does. I can open two terminal windows, put them side by side, and make one declare incessantly that its current directory does not exist, while the other, with the exact same path as its current directory, happily claims that it does. This is schizophrenic.

**Comment by krader1961** [comment] 2017-01-06 04:49
> This is schizophrenic.

Yes, it is. Sorry, but that's how UNIX behaves. We can paper over that behavior but it doesn't change the fact that doing so does not actually "fix" that behavior. Try this in bash:

```
mkdir abc
cd abc
rmdir ../abc
bash
```

Notice that the bash subshell reports 

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

Now type `exit` to leave that bash subshell and type

```
mkdir ../abc
bash
```

You'll still get the same error despite the fact you've recreated the "abc" directory.

And typing `cd ..` in that bash subshell reports

```
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

If there were a way to actually make this work beyond the trivial case of `cd .` in a given shell I'd be happy to implement it. But the bash behavior does not actually work around the "low-level Unix filesystem semantics" except in a very trivial, not particularly useful, fashion.

**Comment by ridiculousfish** [comment] 2017-01-07 23:27
@nathansgreen I think you have some reasonable points. What do you propose exactly? Is it just special-casing `cd .` or would you like to see a more fundamental change?

krader is right that bash doesn't acheive much here. For example, it's quite possible for `ls .` and `ls $PWD` to produce different output if your cwd is unlinked.

**Comment by nathansgreen** [comment] 2017-02-07 17:08
Honestly, I don't know what to propose. If you `cd` with an absolute path, everything should always make sense, unless the root filesystem was somehow swapped out from under you. (This might be possible, I'd rather not try to figure out how to do it.) So, my thought would be to attempt to re-acquire a reference to $PWD if an error occurs.

**Comment by krader1961** [comment] 2017-02-08 00:50
> If you cd with an absolute path, everything should always make sense, unless the root filesystem was somehow swapped out from under you.

It's not just the root filesystem. It's any mount point. Although having the underlying filesystem become invalid without killing your process is generally only possible if you're using a remote file system like NFS. But that's not really interesting or what is being discussed. The whole point of this issue is not how to deal with mount points becoming invalid. It's how do we deal with specific directories becoming invalid because they were unlinked (i.e., deleted).

> So, my thought would be to attempt to re-acquire a reference to $PWD if an error occurs.

So every single time fish is about to execute any command it should check if $PWD is still valid? And even if we do so we'll only be able to successfully `chdir()` to it if it was actually recreated. If it wasn't then what? It seems to me that solution is worse than the problem we're trying to solve.

Having said that I'd still be in favor of what I wrote earlier:

> Having said that I do think it is sensible for fish to output $PWD if the getcwd() syscall fails with ENOENT. Possibly by appending /. like bash does to provide a clue it isn't authoritative.

**Comment by faho** [comment] 2019-03-15 18:31
Can't reproduce anymore, closing.

**Closed by faho** 2019-03-15 18:31 UTC
Labels: RFC, enhancement
