### ISSUE TITLE
Unbound keys in default (command) vi-mode (bug?)

### ISSUE THREAD

**Issue by ferriff** [fish-shell/fish-shell#2832] opened 2016-03-20 11:24 UTC
Unbound keys in default (command) mode should rather have no effect than appear in the command line as if typed. This is very confusing, at least to me.

_Original submitted issue below: visual mode should instead be default (command) mode:_

> Unbound keys in visual mode should rather have no effect than appear in the command line as if typed. This is very confusing, at least to me.

**Comment by krader1961** [comment] 2016-03-20 19:18
I can't reproduce using fish built from git head. If you're able to reproduce using fish built from the latest sources please describe the sequence of characters you're typing.

**Comment by ferriff** [comment] 2016-03-20 20:22
I see it from the latest master: type something, then go to visual mode, and type any unbound letter (e.g. n, Z, N, M).

**Comment by krader1961** [comment] 2016-03-20 22:49
That's weird because that's exactly what I did. As far as I can see the unbound char is silently ignored. Is it possible that while working on your other binding improvements you introduced a change in behavior local to your machine?

**Comment by faho** [comment] 2016-03-21 00:14
I also cannot reproduce - archlinux, konsole, rxvt-unicode and xterm.

I type the characters and nothing happens.

@ferriff: One place to check is the fish_user_key_bindings function, if defined. Or any terminal customization you did and the value of your $TERM (for me it's konsole-256color and whatever the defaults for the other two are).

**Comment by ferriff** [comment] 2016-03-21 00:37
Sorry! I realize now I wrote visual mode instead of default (command) mode!!! In visual nothing happens even with my setup. I'll correct the title of the issue.

I add some information anyway:

@krader1961: I tried also on other machines (ssh-ing to them) with a freshly compiled fish started from scratch with the only config of `fish_vi_mode` and nothing else.

@faho: I don't have the `fish_user_key_bindings` function defined. $TERM is either xterm or rxvt-unicode-256color. I removed all the customizations of xterm and rxvt-unicode and still have the same issue.

**Comment by krader1961** [comment] 2016-03-21 00:46
Yep, that is another behavior that is extremely annoying that I'd love to see someone fix. It is undoubtedly because vi-mode is a recent enhancement and the pre-existing bind code implemented emacs like behavior.  If you're energized to fix these types of issues I'll be happy to review your changes and get them merged quickly :-)

**Comment by faho** [comment] 2016-03-21 00:50
This particular thing I actually know how to fix, but I'm not sure if a bigger fix should be done (up to a revert of c0e8ad6f1feff09474e957773a1508d9813d4bbb).

The issue of characters passing through can be solved by adding `bind -e ""` to fish_vi_key_bindings (after the calls to fish_default_key_bindings). This will remove the default "self-insert" that applies to anything not otherwise bound.

Since you two actually use vi-mode, what do you think?

**Comment by krader1961** [comment] 2016-03-21 01:03
Aha! I hadn't noticed that special binding before you pointed it out, @faho. The current behavior is unexpected in vi-mode and your proposed change would provide behavior less surprising to its users. But that leads me to point out a related bogosity: vi-mode inheriting emacs-mode bindings at all. I've been surprised more than once to find emacs-mode bindings working in vi-mode. I don't know that reverting the commit your referred to is the correct solution at this juncture. I'll need some time to review the issues referenced in that commit. But I do strongly believe that vi-mode should not include any emacs'isms. That is almost certainly best done by having vi-mode bindings start with a clean slate and explicitly duplicate the once in emacs-mode that make sense in vi-mode.

**Comment by ferriff** [comment] 2016-03-21 01:04
`bind -e ""` seems fine!
I don't see any immediate drawback from having it, but I let more experienced fish users comment :)

**Comment by krader1961** [comment] 2016-03-21 01:12
I vehemently disagree with the people commenting on issue #2255 (which commit c0e8ad6 references) that the default (emacs-mode) bindings should be retained in vi-mode unless explicitly remapped. I recognize that not inheriting the default bindings might require additional changes to the vi-mode bindings whenever a new default binding is introduced. Tough. Deal with it. It's a one time, small, cost.

**Comment by mqudsi** [comment] 2016-03-29 23:25
@krader1961 just one question: not having read through *all* the vi-mode issues, is it your proposal to a) ship fish "clean" without any emacs-mode bindings enabled in vi-mode, or b) with hand-picked emacs-mode bindings enabled? I think I was misunderstanding in the previous issue, because I thought the drama was about a, while b would be most-logical.

**Comment by krader1961** [comment] 2016-03-30 00:01
@mqudsi: My preference is (a) no emacs-mode bindings in vi-mode. A few such as \ca and \ce to move to the start/end of line are probably okay as they are unlikely to cause vi addicts to be surprised. However, I really don't see the point. If you want emacs bindings use emacs-mode. If you want a hybrid then add the bindings you want to your personal `fish_user_key_bindings` function.

**Comment by mqudsi** [comment] 2016-03-30 00:18
@krader1961 OK, so when I installed vi-mode for the first time, I was only momentarily surprised that my ^a and ^e did not work since every single text input on OS X natively supports them and they do not necessarily conflict with vim mode, I expected them to be enabled. 

I did not understand why meta+up did not do argument completions and personally considered that a bug - a shell has to have some consistency of its own, same as if up/down actually moved the cursor instead of scrolling through history. For the sake of completions, meta+left/right make life easier, but I expected to have to rebind them myself (hopefully without too much trouble). 

Default insert mode made sense (since that's the main purpose of a terminal, entering stuff) as well as returning to insert mode thereafter. Ctrl+C exiting insert mode was unexpected (and now fixed). The lack of `/` in normal mode (or `s///`) was surprising (though not a bug, just missing - in some ways, it makes my earlier `edit_cmd` binding more useful than vi-mode).

Seeing random non-bound characters entered at the terminal when in normal mode was definitely a "bug" moment as it was weird and unexpected - esp. since I was expecting ':' or '/' to do something other than actually type ':' when in normal mode.

Overall, I think hand-picking select non-conflicting emacs-mode keys that aren't so much "emacs mode" as they are "basic navigational components of fish" to be the "expected behavior", together with tested options (perhaps documented) that would enable certain additional emacs-like functionality for interested users.

**Comment by krader1961** [comment] 2016-03-30 00:28
> Overall, I think hand-picking select non-conflicting emacs-mode keys that aren't so much "emacs mode" as they are "basic navigational components of fish" to be the "expected behavior"

I agree with that. In fact, the problem (current situation) is due to conflating emacs bindings with fish specific bindings. Those should be teased apart. Then both emacs-mode and vi-mode can import the fish specific bindings without including unwanted bindings. The problem with enabling any emacs-mode bindings (e.g., \ca) in vi-mode is it will inevitably lead to people asking "well, why not include this other emacs binding?" That way lies madness and breaks the core fish principle of "least surprise".

**Comment by krader1961** [comment] 2016-03-30 00:33
Also, I recently came across another discussion about invoking an external editor to edit the command line. This is what I put in my `fish_user_key_bindings.fish` script:

```fish
function edit_cmd --description 'Input command in external editor'
    set -l f (mktemp /tmp/fish.cmd.XXXXXXXX)
    if test -n "$f"
        set -l p (commandline -C)
        commandline -b > $f
        vim -c 'set ft=fish' $f
        commandline -r (more $f)
        commandline -C $p
        command rm $f
    end
end

function fish_user_key_bindings
    bind \ev 'edit_cmd'
end
```

**Comment by mqudsi** [comment] 2016-03-30 00:48
@krader1961 my feelings exactly, and I concur about the difficulty in deciding what is emacs-mode and what is fish. 

I'm a cross-platform dev (FreeBSD, OS X, and Windows) but unix-ish tools on all three platforms generally support some subset of emacs-mode commands (from readline, I believe). I'd expect these - where they don't outright conflict with vi's shortcuts - to work in fish. I know it's a difficult call because they're not supported from within vim, but with a shell I feel like there is so much mental context-switching happening as the "time per line" spent in the shell is greatly less than in a full-blown vim editor, meaning muscle memory, instinct, etc. making it that much harder to mentally switch from exclusive vim-mode to "dumb mode".

Key bindings that are exclusive to emacs and are not supported in a standard readline config would certainly not fall into the category (IMHO) of features that should be active in an out-of-the-box vi-mode config.

---

Also, this is the `edit_cmd` script I was talking about earlier (in the other issue?) that I used prior to trying out vi-mode. I never could get it to work 100% correctly (though I didn't fight with `commandline` for too long) as it would always mangle new lines, single quotes, and double quotes, which is a shame since it is most useful when dealing with long and unwieldy command lines with many a quote and line break..

**Comment by faho** [comment] 2016-04-12 19:42
I've fixed the main issue at hand here, the inheritance stuff should be discussed in a dedicated issue.

**Closed** 2016-04-12 19:41 UTC
Labels: bug, regression, vi-mode

**Comment by faho** [comment] 2016-04-12 19:50
Okay, dedicated issue opened: #2930.
