### ISSUE TITLE
How to keep pipe/file open?

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#6934] opened 2020-04-22 15:14 UTC
In some cases it is very useful ability to keep pipe(fifo) open. In bash this looks like:

    exec 3<>/path/to/pipe

Is there similar functionality in Fish shell?

**Comment by faho** [comment] 2020-04-22 15:19
Duplicate of #3948

**Comment by faho** [comment] 2020-04-22 15:19
In other words: No, there currently is not.

**Closed by faho** 2020-04-22 15:19 UTC

**Comment by kuvaldini** [comment] 2020-04-23 08:58
@faho thank you for response.
