### ISSUE TITLE
`eval` works with strings, not lists

### ISSUE THREAD

**Issue by szhu** [fish-shell/fish-shell#2261] opened 2015-08-02 00:56 UTC
I want a kind of `eval` that, given an list, will treat the first list item as a command and the rest as the argv. Unfortunately, eval has to interpret an entire string, and so will join and split its argv, causing unexpected results.

```fish
# For reference:
$ test a = ''

# I expect the following to do the same thing, but it doesn't:
$ eval test a = ''
test: Missing argument at index 2

# This is because eval is converting its argv into a string, making it equivalent to:
$ eval 'test a = '
test: Missing argument at index 2

# Note that eval is officially recommended for this kind of purpose:
$ set mylist test a = ''
$ $mylist
Variables may not be used as commands. In fish, please define a function or use 'eval mylist'.
$ eval $mylist
test: Missing argument at index 2

# Fun examples to not try:
$ eval test a = ''
$ eval echo '~'
$ eval echo '$HOME'
$ eval rm 'a file with / -rf in it'
```

Also, note that "`eval mylist`" in the error message appears to be a typo and so I did `eval $mylist` in lieu of that.

**Comment by Profpatsch** [comment] 2015-10-01 14:26
This is a fairly big bug.

Another example I stumbled upon:

```
> set x "1 2"
> eval ls $x
ls: cannot access 1: No such file or directory
ls: cannot access 2: No such file or directory
> eval ls "$x"
ls: cannot access 1: No such file or directory
ls: cannot access 2: No such file or directory
> echo $x[1]
1 2
```

$x should definitely not be split.

**Comment by Profpatsch** [comment] 2015-10-01 16:37
@szhu I thought about that and it’s actually not a bug, but consistent behaviour.

eval takes a string of fish code and evaluates it. If the first argument of a list is treated differently from the rest, it gets highly inconsistent.

What you can do instead:
```fish
> set x ls folder1 "folder 3"
> eval x[1] \"x[2..-1]\"
<ls ouput>
```

or for your example:
```fish
> test a = ''
> eval test a = \"''\"
> eval test \"a = ''\"
```

**Comment by szhu** [comment] 2015-10-01 20:05
Sorry, I didn't mean that the first argument is treated differently from the rest. I just meant that the first one should be the program to run and the entire list should be the `argv`. In other words, I just meant that the list shouldn't be re-split by spaces. I think we're talking about the same thing, right?

**Comment by Profpatsch** [comment] 2015-10-01 21:17
> I just meant that the first one should be the program to run and the entire list should be the argv

Then the first argument would be treated differently, right? :)

eval is a very dumb function, which takes arbitrary fish code and evaluates it. If it is given a list, it does the dumbest thing it can to convert that to a string (the same thing most other programs do), separate it by spaces.

Another way to do it:

```fish
eval "test a = ''"
```

**Comment by szhu** [comment] 2015-10-01 21:50
Yes, the first argument would be treated differently. It's not farfetched though; all shells treat the first argument of each command line input differently in this way.  I'm not opposed to my proposed command being called something not eval, perhaps `call` or `system` since what it does is equivalent to the functions of those names in Python and Ruby.

**Comment by faho** [comment] 2015-10-01 22:19
>eval "test a = ''"

Yeah, that's the way to do it. Either that or, if you have more complicated needs, `string escape` (not in a release yet).

>I want a kind of eval that, given an list, will treat the first list item as a command and the rest as the argv

I'm afraid I don't quite understand - what's the point of treating the first argument differently? In what way exactly should it be treated differently?

What I see in your proposal is that eval should treat the input "as a list", that it should consider how the arguments have been split. This would, in a certain way, be more elegant. If I do `eval "/tmp/say my name" "cool dude"`, it should execute `/tmp/say my name` and hand it one argument "cool dude". There's nothing "special" about the splitting of the first element - that it is "the command" is a consequence of our syntax (and might not always be necessary - if we allow prefixed redirections like `<somefile grep something >someotherfile`), and it's not only the first argument that's a command - think of `eval "something; someotherthing" (or in the proposed syntax `eval "something" ";" "someotherthing"` - and yeah, that's a bit ugly).

And that's where we get into the counterargument: Not only can the proposal also yield ugly results, it would also break most uses of eval (my $EDITOR is "emacs -nw" - I'd have to split that up) and might require more manual splitting when you use it in a script (i.e. you get the argument as output from some commmand, now you need to split at spaces, but only if they aren't escaped - in other words it moves the annoying escaping logic further up).

I'm not convinced having another command that does the same thing but a bit differently is the right thing to do. If anything must be done I'd advocate for an option to eval "-l" or "--list" or so.

But first, I'd like to see more how `string escape` works out in practice - I haven't used it much yet.

@shzu: What exactly are you trying to do, btw? I don't really need eval all that much, to be honest, and I always feel dirty using it, like someone cutting a ribbon with a chainsaw - sure it's gonna work, but you better watch your legs.

**Comment by szhu** [comment] 2015-10-02 01:17
"First argument treated differently"… wait what? I'll try to clarify here.

When you type a command into bash or fish or any other shell, such as `echo a b c`, it gets tokenized and split into the following list: `echo`, `a`, `b`, `c`.

Then some magic happens that most people take for granted: The shell forks itself, and the child does something along the lines of `exec("/bin/echo", ["echo", "a", "b", "c"])`, where the first argument is the program to run and the rest is the `argv` to pass to it.

Note how `argv[0]` is used for the first argument. That's all I was talking about. I'm not proposing that `eval` should implement the whole fork-exec thing. That would be silly, since fish already has that implemented, otherwise it wouldn't be able to run any commands.

However, I'm pointing out the fish seems to lack a fish API for sending an already-parsed `argv` to an arbitrary program. This API is available in Python as [`subprocess.call`](https://docs.python.org/2/library/subprocess.html#subprocess.call) with `shell=False` and in Ruby as [`system`](http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-system). All I need is a way to do this in fish.

Putting this another way:

```fish
set files "my file 1" "my file 2"

# I can currently do this
rm $files

# But I want to do either this
set cmd "rm"
$cmd $files

# or this
set cmd_and_files "rm" $files
$cmd_and_files

# fish doesn't allow the first arg to be a variable,
# so I'm proposing the API be made available as
# a function called `call`, used as follows:
set cmd_and_files "rm" $files
call $cmd_and_files
```

Hope that makes things clearer. Feel free to ask me to explain it another way!

**Comment by Profpatsch** [comment] 2015-10-02 01:24
```fish
eval $cmd \"$files\"
```

?

**Comment by szhu** [comment] 2015-10-02 01:33
```
$ set files "my file 1" "my file 2"
$ echo $cmd \"$files\"
"my file 1" "my file 2"
```

Oh, I see… it's taking the Cartesian product of [`"`], [`my file 1`, `my file 2`], and [`"`].  That's a neat trick… perhaps this should be documented for a common use case as this one?

Also, while I'm fairly satisfied that this solution will not skip spaces, it still irks me that the only way to fix do the thing I want is to format the entire command such that spaces are not skipped. Is there no way to directly send the list to the program as its `argv`?

**Comment by Profpatsch** [comment] 2015-10-02 01:52
I’m still not sure what your remaining problem is.

There is no more direct way to call a program. This should directly map to `exec` or somesuch, with the program path as first argument and the rest as `char *confs argv[]`.

**Comment by szhu** [comment] 2015-10-02 01:56
Its behavior does directly map to exec. However, I'm not satisfied that the implementation will throw all the arguments into the same string and then parse them again. fish has first-class support for lists that don't involve storing them as a single string intermediately. This is even supported as long as argv[0] is not variable.  I expect the same support for lists here.

**Comment by faho** [comment] 2015-10-02 13:44
Ah, now I see what you mean! Basically, you want a way to do what bash does with `$EDITOR some\ file`.

If so, in current git this is quite easy since the `string` builtin landed:

```fish
function call
    set -l cmd $argv[1]
    set -e argv[1]
    eval $cmd (string escape -- $argv)
end
```

This explicitly does not escape the first argument to allow `call $EDITOR $files` to work with EDITOR set to "emacs -nw".

**Comment by szhu** [comment] 2015-10-02 18:09
My main point in this whole thread is that if I already have everything as a list, I don't want fish to parse a string as a list, even behind the scenes. The example you gave is a nice solution to that specific problem, but quoting and parsing it just reminds me of the bash works around its lack of good list support. I don't think these kind of workarounds should be necessary in fish.

Imagine this test case, in a world where `$EDITOR` isn't a single string in the first place, but is already a list:

```fish
set -x EDITOR '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' --wait
call $EDITOR file1 file2
```

I want this to work, and I don't want to change the first line.

**Comment by faho** [comment] 2015-10-02 18:19
>I want this to work, and I don't want to change the first line.

In this case, you'd want to escape all of it - `eval (string escape -- $EDITOR file1 file2)`.

The case for my `call` not escaping the first argument is because these kinds of variables usually aren't lists, and I don't think they _can_ be - try using an application that launches $EDITOR (e.g. `git commit`) with that $EDITOR. (Or it might also be that we export lists wrong, I'd need to check)

**Comment by szhu** [comment] 2015-10-02 18:55
1. I know I can do it with escaping. I don't want to do this, on principle. (1) It shouldn't be necessary in a language with such great list support and (2) if this is the official workaround, there better be no caveats, instead of "it looks like it works" or "we haven't found bugs with it yet".
2. I know $EDITOR doesn't work like this. I'm trying really hard to find an example to demonstrate. (Hence, "in a world where $EDITOR...").
3. If you want to know my real use case, it's basically that sometimes I want to store a command to run later, and I want to store it as a list.

**Comment by Profpatsch** [comment] 2015-10-02 23:07
So why not:
```fish
set invocation ls "-l" "-a" "$folder"
eval $invocation[1] \"$invocation[2..-1]\"
```

**Comment by szhu** [comment] 2015-10-03 05:32
Why not? Because this basically functionality needs to be a built-in function. Like, I see no inherent reason why it needs to even mention `invocation[1]` explicitly.

But behavior wise, I'm totally satisfied.

**Comment by faho** [comment] 2015-10-04 18:09
>I know $EDITOR doesn't work like this. I'm trying really hard to find an example to demonstrate. 

This, to me, is always a sign that you actually want something different.

>If you want to know my real use case, it's basically that sometimes I want to store a command to run later, and I want to store it as a list.

Is this interactive? In that case, why not replace your commandline with it?

```fish
bind \cr 'set -U last_command $last_command (commandline); commandline ""'
bind \er 'commandline "$last_command[-1]"; set -e last_command[-1]'
```

? (You could probably do a much more complicated solution with a ring buffer and such)

>Because this basically functionality needs to be a built-in function

How exactly does it help you that it's a built-in function? Other than the fuzzy feeling, I mean. We've got a ton of functionality we've implemented in fish-script. 

I'd be okay with taking that `call` function - it's been proposed in #564 already, only we didn't have `string escape` back then so it didn't work as well.

**Comment by Profpatsch** [comment] 2015-10-05 12:21
Implementing `call` as a function sounds sensible. It definitely doesn’t have to be a built-in, szhu probably meant “in the standard libary”.

**Comment by faho** [comment] 2015-10-05 13:07
>It definitely doesn’t have to be a built-in, szhu probably meant “in the standard libary”. 

Umm yeah, that's probably right. I also just noticed that my phrasing may have come across a little more hostile than I wanted - sorry, I'm a bit tone-deaf sometimes.

@szhu: Would it be satisfactory to you if we just took that `call` function? I'd like to not escape the first argument so the "$EDITOR" case works - putting the onus on the user if they want to do something I view as less common, though it's a bit magicky, we could then adjust the special "variables as commands are not allowed" error message to suggest `call`, not `eval`.

**Comment by szhu** [comment] 2015-10-06 05:57
Hey no worries! I know that you weren't trying to be hostile :)

I would like `call` to not break up any list component, because the really really nice thing about fish is the strings are NEVER split implicitly. Bash does this and look at the mess it causes.

Sure, I know that `$ENV` will not be a list. So I propose we either:

- Treat it specially, as we do `$PATH`, or
- Let the user break it up themselves -- I know how to do this actually, but there has to be a way, right? If not that's a big problem. I think `eval "set ENV_AS_LIST $ENV"` works but it doesn't seem like the safest option.

**Comment by faho** [comment] 2015-10-06 08:14
>Treat it specially, as we do $PATH, or

I'm not sure if it needs to be treated specially - I don't get the current exporting behavior for lists (that aren't PATH or CDPATH or MANPATH). What happens when you export a variable set like `set -gx EDITOR emacs -nw` is that it is exported as "emacs-nw" - i.e. all elements smushed together without any separator.

While it seems like [bash just punted on this](http://www.openwall.com/lists/oss-security/2014/09/30/1), I can't think of a case where no separator makes sense, and I'm having issues coming up with one where spaces don't (excepting of course colon-separated stuff like $PATH).

Treating $EDITOR special is also wrong, as you not only need $EDITOR, but also $VISUAL, $PAGER (I've seen it set to "less -s") and at least a few other variables.

>Let the user break it up themselves -- I know how to do this actually, but there has to be a way, right?

The old option is `(echo $var | tr ' ' '\n')`. The new option (and this `call` depends on `string` anyway) is `string split " " -- $var`.

**Comment by szhu** [comment] 2015-10-06 08:38
Perhaps the right way to solve this is by fixing how export works:

- Items should be separated by spaces.
- Items with spaces in them should be quoted.

Advantage of this: There are many traditional programs that don't deal with quotes well and also assume that no argument has a space inside it. Because only items with spaces should be quoted, these programs will not be affected.

**Comment by faho** [comment] 2015-10-06 09:36
It's actually a bit more complicated - lists are exported just as they are represented internally - as strings, with the elements separated by "\x1e" (a "private use" unicode character).

This means nested fish instances will just magically pick up lists from the environment, while everything else reads weird values. I'm not sure picking the solution that allows fish to work and everything else not to is correct.

Anyway, let's see the impact the decision of whether to escape the first element has on `call`, with `call_yes` doing escaping, and `call_no` not doing it, and `call_me_maybe` being a joke to meet my quota:

```fish
set EDITOR "emacs -nw"
call_yes $EDITOR /some/file # will fail because it tries to execute a command named "emacs -nw"
call_no $EDITOR /some/file # will work
call_yes (string split " " -- $EDITOR) /some/file # works
set EDITOR emacs -nw
call_yes $EDITOR /some/file # works
call_no $EDITOR /some/file # works
set EDITOR "/usr/bin/fried catfi.sh" # i.e. filename with a space in it
call_yes $EDITOR /some/file # will work
call_no $EDITOR /some/file # will try to call /usr/bin/fried and fail
call_no (string escape -- $EDITOR) /some/file # works
```

Yeah, `call_no` is a bit unfishy - you suddenly have to care about spaces in filenames again, and that's so 1989.

**Comment by ridiculousfish** [comment] 2015-10-06 17:55
Nitpick: `\x1e` is not private use - it's the "record separator" character and it's part of ASCII.

**Comment by szhu** [comment] 2015-10-06 17:59
```
$ touch hello\x1eworld

$ set files_to_remove hello*

$ echo $files_to_remove
hello world

$ rm $files_to_remove
rm: hello: No such file or directory
rm: world: No such file or directory
```

heh.

**Comment by faho** [comment] 2015-10-06 18:09
@szhu: #436.

>Nitpick: \x1e is not private use - it's the "record separator" character and it's part of ASCII.

Sorry, I was confused by the later discussion there.

**Comment by cben** [comment] 2016-02-12 04:51
The cartesian-product-with-quotes hack is unsafe in multiple ways.
Exhibit D:
```
~ $ set secret 'NO ONE SHOULD SEE THIS'
~ $ # ... History became legend, legend became myth...
~ $ set cmd echo
~ $ set args 'Benign' 'Peek at $secret!'
~ $ eval $cmd \"$args\"
Benign Peek at NO ONE SHOULD SEE THIS!
```
Exhibit Q:
~ $ set cmd ls
~ $ set args '" syntax error'
~ $ eval $cmd \"$args\"
Unexpected end of string, quotes are not balanced
- (line 1): begin; ls "" syntax error" 
 ;end <&3 3<&-
                                ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on standard input

source: Error while reading file “-”
~ $ set args '" drop table words "'
~ $ eval $cmd \"$args\"
ls: cannot access : No such file or directory
ls: cannot access drop: No such file or directory
ls: cannot access table: No such file or directory
ls: cannot access words: No such file or directory
ls: cannot access : No such file or directory
```

`string escape` can probably be safe.
I do share szhu's sentiment that a simple primitive feels inherently safer than any escape-then-eval dance.  But if fish can guarantee that `string escape` will always round-trip safely, that's probably ok.

Unix actually provides multiple "call" alikes, e.g.:
```
~ $ env -- $cmd $args  # safe without quotes!
ls: cannot access " drop table words ": No such file or directory
```
But this can't call fish functions (sometimes a bug, sometimes a feature).

The whole issue would be moot if fish dropped the rule against expansions in first word and allowed commands like `$cmd_array`, `$cmd_array $extra_args`, `"$cmd" $args`.  I can see how the rule tries to protect users but FWIW I personally would prefer it dropped. The rule reduces orthogonality, and if the suggested remedy it steers people towards is eval, that's not really "protecting".
BTW, I just tried executing `$cmd` and similar and they all fail **silently** (except for being red syntax-highlighting and status):
```
~ $ $cmd $args
~ $ echo $status
127
~ $ $nonexistant
~ $ echo $status
127
~ $ fish --version    # using fish-shell/release-2 ppa on ubuntu
fish, version 2.2.0-500-g3a249bb
```
Didn't it use to print an informative error message (advising something about eval IIRC)?

**Comment by krader1961** [comment] 2016-04-06 22:49
While multiple issues were raised the core issue is the same as #154 so I'm closing this as a dup.

**Closed by krader1961** 2016-04-06 22:49 UTC
Labels: duplicate
