### ISSUE TITLE
The peco interface is not displayed when called in a subcommand

### ISSUE THREAD

**Issue by paulcarey** [fish-shell/fish-shell#1889] opened 2015-01-14 09:48 UTC
The filtering tool, [peco](https://github.com/peco/peco), does not appear to work when run in a subcommand.

    bash $ echo pecoresult: $(printf "a\nb\nc\n" | peco) 
    #  The peco interface is displayed - select a line and hit return
    pecoresult: b

    fish $ echo pecoresult: (printf "a\nb\nc\n" | peco)
    # The peco interface is not displayed, the following is output immediately
    pecoresult: 

Obviously this is contrived - a practical example I'd like to be able to run in fish is

    $ vim (git ls-files | peco)

When not run in a subcommand, peco works as expected.

**Comment by zanchey** [comment] 2015-01-16 08:10
This is, I think, the same as #1362 - processes run in a command substitution get a new process group, get SIGTTIN and then stop. I'm going to close this issue as a duplicate of #1362 for now, and add some comments about possible workarounds. Sorry!

**Closed by zanchey** 2015-01-16 08:10 UTC
