### ISSUE TITLE
Alt-W (and possibly other functions) clobbered by multi-line prompt

### ISSUE THREAD

**Issue by tobia** [fish-shell/fish-shell#5615] opened 2019-02-04 16:22 UTC
This was addressed in old issues, but they were all closed 5+ years ago, while this bug is still persisting.

Tried on fish 2.7.1, as well as master, on XUbuntu Bionic and Urxvt.

```
$ sh -c 'env HOME=$(mktemp -d) ./fish'
Welcome to fish, the friendly interactive shell
tobia@yoga /h/t/s/f/build> echo $FISH_VERSION 
3.0.0-306-g9f469e57
tobia@yoga /h/t/s/f/build> git <Alt+w>
Git (3pm)            - Perl interface to the Git version control system
git (1)              - the stupid content tracker
tobia@yoga /h/t/s/f/build> function fish_prompt
                               echo ==FIRST LINE==
                               echo -n '$ '
                           end
==FIRST LINE==
$ git <Alt+w> 
Git (3pm)            - Perl interface to the Git version control system
==FIRST LINE==       - the stupid content tracker
$ git
```

As you can see, the first invocation (after the first `<Alt+w>`) prints correctly, while the second one (after the second `<Alt+w>`) is clobbered by the multi-line prompt.

Am I missing something in the multi-line prompt definition?

**Comment by tobia** [comment] 2019-02-04 16:31
Also, I just discovered that Alt-Left directory navigation does not rewrite the line correctly:

```
$ sh -c 'env HOME=$(mktemp -d) ./fish'
Welcome to fish, the friendly interactive shell
tobia@yoga /h/t/s/f/build> echo $FISH_VERSION 
3.0.0-306-g9f469e57
tobia@yoga /h/t/s/f/build> cd /
tobia@yoga /> cd home
tobia@yoga /home> cd tobia
tobia@yoga /h/tobia> cd src
tobia@yoga /h/t/src> cd fish-shell
tobia@yoga /h/t/s/fish-shell> cd build
tobia@yoga /> # <Alt-Left> a few times goes back to a clean root directory
tobia@yoga /> function fish_prompt
                  echo (prompt_pwd)
                  echo '$ '
              end
/
$ cd home
/home
$ cd tobia
/h/tobia
$ cd src
/h/t/src
$ cd fish-shell
/h/t/s/fish-shell
$ cd build
/homebiaish-shell
$ # <Alt-Left> a few times leaves the mess you can see above
```

I don't know if this is the same bug, but it seems related to me.

**Comment by faho** [comment] 2019-02-07 16:07
Duplicate of #5033

**Closed by faho** 2019-02-07 16:07 UTC
