### ISSUE TITLE
Ability to disable space adding after tab completion

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8460] opened 2021-11-19 05:10 UTC
Automatic space adding after suggested completion can be annoying when option value is joined with it not via `=`. For instance consider `mcs` compiler `--addmodule:MODULE1[,MODULE2]` option. I suggest add `-N`|`--no-space` option to complete to control adding space after completion. It would be useful in https://github.com/fish-shell/fish-shell/pull/8452. ;)

**Comment by faho** [comment] 2021-11-19 07:24
Duplicate of #7832

**Closed by faho** 2021-11-19 07:24 UTC
