### ISSUE TITLE
fish: tab auto-completing with tab key Error not sure it's related to fish or pyenv

### ISSUE THREAD

**Issue by kirankotari** [fish-shell/fish-shell#6125] opened 2019-09-19 09:57 UTC
I wanted to add requirements.txt file in git when I clicked on the tab key the error follows.
```
(master) λ git add repyenv: gettext: command not found                              
The `gettext' command exists in these Python versions:
  anaconda3-2019.03
pyenv: gettext: command not found
The `gettext' command exists in these Python versions:
  anaconda3-2019.03
pyenv: gettext: command not found
The `gettext' command exists in these Python versions:
  anaconda3-2019.03
pyenv: gettext: command not found
The `gettext' command exists in these Python versions:
  anaconda3-2019.03**
```
version: fish, version 3.0.2
OS: Darwin Mojave
TERM: xterm-256color

it say's **pyenv: gettext: command not found**

**Comment by faho** [comment] 2019-09-19 10:00
Install gettext. This should have been a dependency.

**Comment by faho** [comment] 2019-09-19 10:04
Although fish only ever uses gettext if it's available (via the `_` helper function), so you have something else that uses it, or a weird gettext wrapper or you've replaced the `_` function with something worse.

**Comment by kirankotari** [comment] 2019-09-19 10:20
oh my bad. can you paste the output of the following file
`~/.config/fish/config.fish`

**Comment by faho** [comment] 2019-09-19 10:46
>can you paste the output of the following file
~/.config/fish/config.fish

?

I have no idea what you mean here. That file contains your customisation. It can be entirely empty or non-existent. Mine contains a bunch of my customisation that's of no use to you.

Try moving it out of the way or commenting everything in it.

**Comment by zanchey** [comment] 2019-09-19 11:12
Looks like a duplicate of https://github.com/pyenv/pyenv/issues/747 (ie an anaconda problem)

**Comment by kirankotari** [comment] 2019-09-19 11:20
> > can you paste the output of the following file
> > ~/.config/fish/config.fish
> 
> ?
> 
> I have no idea what you mean here. That file contains your customisation. It can be entirely empty or non-existent. Mine contains a bunch of my customisation that's of no use to you.
> 
> Try moving it out of the way or commenting everything in it.

Recently I was facing issues with **conda**, then I ran `conda init fish` which modified the above file. I was assuming the defaults are overridden.

**Comment by faho** [comment] 2019-09-19 11:40
>I was assuming the defaults are overridden.

Ah, okay. The defaults are nothing.

The output of `type -a gettext` and `type -a _` would be good to know, as would the contents of config.fish.

Maybe we can untangle this mess and tell the conda people where the issue lies.

**Comment by kirankotari** [comment] 2019-09-24 06:16
I am facing this issue when my python was not pointing to anaconda. Please find the data in detail.
```
λ pyenv versions                                                                                            (~) 11:42:02
  system
  2.7.16
  3.5.6
  3.6.6
  3.6.9
  3.7.4
* anaconda3-2019.03 (set by /Users/XYZ/.python-version)
  anaconda3-2019.03/envs/kaggle_manipal_env
```
```
λ type -a _                                                                                                 (~) 11:41:23
_ is a function with definition
# Defined in /usr/local/Cellar/fish/3.0.2/share/fish/functions/_.fish @ line 5
function _ --description 'Alias for the gettext command'
    command gettext fish $argv
end
```
```
λ cd sym_doc/personal/github/env/pyenv-win/pyenv-win/libexec/                                               (~) 11:42:23
(master) λ pyenv versions                                                         (pyenv-win/pyenv-win/libexec) 11:42:41
  system
  2.7.16
* 3.5.6 (set by /Users/XYZ/personal/github/env/pyenv-win/.python-version)
  3.6.6
  3.6.9
  3.7.4
  anaconda3-2019.03
  anaconda3-2019.03/envs/kaggle_manipal_env
```
```
(master) λ type -a _                                                              (pyenv-win/pyenv-win/libexec) 11:42:44
pyenv: gettext: command not found

The `gettext' command exists in these Python versions:
  anaconda3-2019.03

_# Defined in /usr/local/Cellar/fish/3.0.2/share/fish/functions/_.fish @ line 5
function _ --description 'Alias for the gettext command'
    command gettext fish $argv
end
(master) λ                                                                        (pyenv-win/pyenv-win/libexec)
```

**Comment by kirankotari** [comment] 2019-09-24 06:19
> _.fish file
> 
> ```
> (master) λ cat /usr/local/Cellar/fish/3.0.2/share/fish/functions/_.fish           (pyenv-win/pyenv-win/libexec) 11:47:11
> #
> # Alias for gettext or a fallback if gettext isn't installed.
> #
> if command -sq gettext
>     function _ --description "Alias for the gettext command"
>         command gettext fish $argv
>     end
> else
>     function _ --description "Fallback alias for the gettext command"
>         echo -n $argv
>     end
> end
> ```

Let me know the defaults code for _.fish file

**Comment by faho** [comment] 2019-09-24 06:40
>Let me know the defaults code for _.fish file

https://github.com/fish-shell/fish-shell/blob/master/share/functions/_.fish

Also since it's in /usr/local/Cellar, it should already be unmodified. And it is.

>(master) λ type -a _
pyenv: gettext: command not found

WTF? Okay, this is pretty weird. `type` should not be executing any external commands like `pyenv`.

The only thing I can think off is that they're overriding `type` (because `command` is a reserved word and can't be overridden with a function). Which is a big red flag.

Anyway, we have figured out what is causing your problem, and it's conda/pyenv.

If you have any further issues with this, please direct your questions there because they're more likely to be able to help you.

**Closed by faho** 2019-09-24 06:40 UTC
Labels: question
