### ISSUE TITLE
read built-in's history doesn't have the last line

### ISSUE THREAD

**Issue by randomdude999** [fish-shell/fish-shell#7391] opened 2020-10-10 17:14 UTC
Running on fish 3.1.2, arch linux, alacritty 0.5.0. Tested in a shell with no config files.
```
user@host /> read test
read> first
user@host /> read test
read> second
user@host /> read test
read> <press up>
read> first
```
after pressing up on the 3rd `read`, the autocompleted value is "first", though I would expect it to be "second". In general, the last line that was read by `read` is not present in the history.

I'm not entirely sure if `read` is supposed to have history at all (the code comments and some merged pull requests seem to imply that it shouldn't), but either way, this is a bug. (also, if it turns out that read shouldn't have history, then it'd be neat to at least have an option that enables it.)

**Comment by faho** [comment] 2020-10-10 17:30
Duplicate of #6892

**Closed by faho** 2020-10-10 17:30 UTC
