### ISSUE TITLE
Shell becomes unresponsive after trying to tab complete "git add "

### ISSUE THREAD

**Issue by cpadilla** [fish-shell/fish-shell#5333] opened 2018-11-12 19:51 UTC
Version: fish, version 2.7.1
OS: Linux nzxt 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
Terminal: Termite v13

Pretty much the title, if I try to use tab to auto complete a directory as I'm typing `git add`, it doesn't show tab complete results and I can no longer input text into the shell. The terminal is still responsive as I can use other commands (like `Ctrl+Shift+Space` to enter selection mode in termite), but the shell is frozen. I can't input text, backspace or undo with `Ctr+U`. I end up having to restart the terminal.

So far I've only seen this happen when using tab complete for the `git add` command. Tab completion works for other commands such as `git mv` or `git diff`.

**Comment by faho** [comment] 2018-11-12 20:50
In 2.7, `git add`s completions did essentially

```fish
command git ls-files -mo --exclude-standard
```

which... can just take a while, since it shows untracked files, which means it needs to scan the entire repository.

In the upcoming 3.0 (now master) we use `git status --porcelain`, which does more in one call, but also needs to scan for untracked files. One advantage is that we only glob for files matching the current token, so if you enter some letters before pressing tab it can reduce the amount of work it needs to do.

**Comment by cpadilla** [comment] 2018-11-12 20:54
Ah I see, you are correct. It was just taking a long time. After waiting a bit, it did finish loading and showed all of the options available (over 500).

Guess I was just impatient. :)

**Comment by faho** [comment] 2018-11-12 20:57
In that case, let's close this as a duplicate of #4117.

**Closed by faho** 2018-11-12 20:57 UTC
