### ISSUE TITLE
Enable fish to call $EDITOR on command line

### ISSUE THREAD

**Issue by GReagle** [fish-shell/fish-shell#2027] opened 2015-04-16 14:29 UTC
This function was originally written by Sanne Wouda and modified by Greg Reagle.  This feature is available in Bash as edit-and-execute-command (C-x C-e), and in zsh as edit-command-line.

Can this function be a standard part of fish, and bound to a key such as Ctrl-x Ctrl-e?
```
# Use $EDITOR to edit the current command
function edit-command
    set -q EDITOR; or return 1
    set -l tmpfile (mktemp); or return 1
    commandline > $tmpfile
    eval $EDITOR $tmpfile
    commandline -r (cat $tmpfile)
    rm $tmpfile
end
```

**Comment by tannhuber** [comment] 2015-04-25 20:39
I suggest to replace the second `commandline` command:
```
commandline -r -- (cat $tmpfile)
```
Look here: https://github.com/fish-shell/fish-shell/issues/1964

**Comment by zanchey** [comment] 2015-04-27 14:20
This will require cleverness to bind as `^X ^C`.

**Comment by GReagle** [comment] 2015-04-28 15:29
@tannhuber  The "--" prevents errors and is an improvement.  Thank you.

@zanchey  Yea, I have no idea how to get a multi-key binding to actually work in fish.  It is not so important what the binding is, just that the feature is there.

**Comment by davidmh** [comment] 2015-05-03 08:56
@zanchey @GReagle this seems to work as expected:

`bind \cx\ce edit_commandline`

**Comment by tannhuber** [comment] 2015-06-07 20:57
The function `edit-command` removes outer single and double quotes. Why? Is there a workaround?

Example:
```
echo 'single quotes will be removed' "double quotes will be removed" 'double quotes "will be removed"'
```

**Comment by GReagle** [comment] 2015-08-04 16:31
@tannhuber Good catch on the loss of quotes.  Definitely a problem.  The commandline builtin is not outputting the quotes.  Perhaps a new issue should be opened for that problem.

**Comment by faho** [comment] 2016-01-13 14:49
This is actually a duplicate of #1215.

**Closed by faho** 2016-01-13 14:49 UTC

**Comment by hashier** [comment] 2018-09-19 09:42
To everyone who started to copy/paste the solution from here like me. This is not needed anymore. This got merged into fish and got even two shortcuts. Alt-e and Alt-v.

Documentation: https://fishshell.com/docs/current/ (search for "edit the current command line in an external editor")
PR: https://github.com/fish-shell/fish-shell/pull/3627

**Comment by haakym** [comment] 2019-07-22 14:40
This doesn't seem to work in MacOS I just get ´or √ instead - any ideas?

**Comment by faho** [comment] 2019-07-22 15:18
@haakym: You want to confirm that $EDITOR (or $VISUAL) is set correctly. In particular if you set it to a GUI editor you need to make sure that it *stays* until you're done, frequently they fork off and let the shell return. For e.g. sublime this means using `subl -w` instead of plain `subl`.

**Comment by mfilej** [comment] 2019-07-23 08:27
Hmm, to me it sounds like your terminal might be producing the `´` character (which you get by typing ⌥e depending on the keyboard). There must be a setting somewhere to toggle this, depending on the terminal app that you use.

Alternatively, try esc+e instead.

**Comment by haakym** [comment] 2019-07-23 09:24
@faho Thanks for your response. The initial issue was as @mfilej mentioned below, but you were right I didn't have the $EDITOR or $VISUAL var set correctly. I now have this working with Vim via `set -gx EDITOR vim`.

> In particular if you set it to a GUI editor you need to make sure that it stays until you're done, frequently they fork off and let the shell return. For e.g. sublime this means using subl -w instead of plain subl.

That's really handy to know as I was trying to get this working with VS Code and after exiting nothing ever happened. I've now got this working with `set -gx VISUAL code -w`

@mfilej Thank you - `esc+e`/`esc+v` works great. I'm using iTerm2 and found I can update the option key to function as `Esc+` as mentioned here: [How do I make the option/alt key act like Meta or send escape codes?](How do I make the option/alt key act like Meta or send escape codes?)

Thanks again for your help - really appreciate it! This is going to save my wrists some pain :)
