### ISSUE TITLE
Is there a way this could be packaged like a normal shell 

### ISSUE THREAD

**Issue by gitdrug** [fish-shell/fish-shell#8445] opened 2021-11-15 07:36 UTC
(i use fish on my linux but not my windows)
Is there a way this could be packaged like a normal shell without using mysys2 or 
other things like that so i could just do a "winget install fish.shell" or something
because mysys2 doesn't work how i want it to is there a way i could out it on chocolatey winget or scoops repos so i can use it on windows as a normal program
as a normal shell and not some werid fake linux envitnment verson 
(if i sound dumb its because i know almost nothing about making programs like this haha)

**Comment by gitdrug** [comment] 2021-11-15 07:38
i want to know if theres a way to package it so it works and can be put on one of theses package managers so it can be just a normal program
https://scoop.sh/
https://github.com/microsoft/winget-cli
https://chocolatey.org/

**Comment by gitdrug** [comment] 2021-11-15 07:40
or can it not be a normal program because of some werid dependency?

**Comment by zanchey** [comment] 2021-11-15 08:35
Unfortunately it's not straightforward. Fish depends on a bunch of Unix utilities (see the README) which make it hard to bundle up. Even an AppImage probably wouldn't work with Windows.

**Comment by faho** [comment] 2021-11-15 08:41
Fish *is* a unix shell. It's not windows-native and will probably never be. That's why you need these "fake linux environment versions". Because it's a linux program.

You have a variety of options - msys, cygwin, wsl, ..., but they all install it as a unixy program because it *is* a unixy program.

Closing this as a duplicate of #7488.

**Closed by faho** 2021-11-15 08:41 UTC
