### ISSUE TITLE
fish is slow to respond on unknown command

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#2374] opened 2015-09-10 19:00 UTC
In normal circumstances, fish takes a non-negligible amount of time to report an unknown command.
For example, I just took this measurement:
```
> a
fish: Unknown command 'a'
> echo $CMD_DURATION
201
```
Right after I start my system, it's much worse and can take up to 5 seconds.

**Comment by occivink** [comment] 2015-09-10 19:01
command

**Comment by faho** [comment] 2015-09-10 19:07
Which OS is this on? What does `type __fish_command_not_found_handler` print?

**Comment by faho** [comment] 2015-09-10 19:43
Do note that 201ms might not be something fish can do anything about (and I consider that to not be too bad) - on my archlinux system, `pkgfile --binaries --verbose` (what the cnf-handler there uses) alone takes between 140 and 150ms (hot cache), while the cnf-handler takes... between 140 and 150ms, so there doesn't seem to be any overhead for that particular one. The 5 seconds could also be completely due to cold cache. If you wish to define a different cnf-handler, you can do so with e.g.

```fish
function __fish_command_not_found_handler --on-event fish_command_not_found
    # Do something
end
```

If you leave out the "--on-event" part, it will disable cnf-handling.

**Comment by occivink** [comment] 2015-09-10 20:00
I'm using archlinux as well.
```
> type __fish_command_not_found_handler
type: Could not find “__fish_command_not_found_handler”
```
I don't consider 200ms to be terrible either, but considering that bash returns almost instantaneously, I figured there was room for improvement.
If you meant `pkgfile --binaries --verbose *`, it takes about 200ms as well.

**Comment by faho** [comment] 2015-09-10 20:04
>type: Could not find “__fish_command_not_found_handler”

Oh, the startup logic is a bit convoluted - execute one command that's not found in the shell and then try again.

>bash returns almost instantaneously

Well, do you have the pkgfile stuff set up for bash? If not, that's to be expected - it does less (in terms of features), so it is faster.

We could adjust the cnf-handler so that the user knows it tried an external helper to find a package, though. Something like "$command does not appear to be in any package".

**Comment by occivink** [comment] 2015-09-10 20:16
Ah, I see.
```
__fish_command_not_found_handler is a function with definition
function __fish_command_not_found_handler --on-event fish_command_not_found
	set -l __packages (pkgfile --binaries --verbose -- $argv[1] ^/dev/null)
				if test $status -eq 0
					printf "%s may be found in the following packages:\n" "$argv[1]"
					printf "  %s\n" $__packages
				else
					__fish_default_command_not_found_handler $argv[1]
				end
end
```
So basically the pkgfile stuff is there to resolve the command to an existing one (but not installed). Considering that I don't care much about this functionality, I can just define 
```
function __fish_command_not_found_handler --on-event fish_command_not_found
	__fish_default_command_not_found_handler $argv[1]
end
```
right?

I'm not sure how I feel about searching packages on every failed command though. If I'm running a command that I think is installed but is not, I'd rather manually search the packages.

At least for me, the ratio "mistyped command <> command that I thought was installed but is not" doesn't warrant having this additionnal functionality (considering the cost).

**Comment by faho** [comment] 2015-09-10 20:19
>Considering that I don't care much about this functionality, I can just define [...] right?

Yes.

>I'm not sure how I feel about searching packages on every failed command though. If I'm running a command that I think is installed but is not, I'd rather manually search the packages.

It's functionality that's fairly often used on both bash and zsh, fish just happens to turn it on by default, because that's what fish does - turn useful stuff on by default, so you don't need 200 lines of configuration until your shell becomes nice.

Since there doesn't seem to be a fish bug here, I'll close this one. I'll also try the documentation stuff. If you have any more questions, feel free to ask.

**Closed by faho** 2015-09-10 20:19 UTC

**Comment by occivink** [comment] 2015-09-10 20:31
>so you don't need 200 lines of configuration until your shell becomes nice.
That's fair, I generally like fish because of that. However, most other usability improvements come for free in terms of performance (at least it seems).

I feel that this is case where fish tries to be a little too clever by setting it as default, but I'd like to know what others think.

**Comment by occivink** [comment] 2015-09-11 22:33
How do I make it persistent? I've defined `~/.config/fish/__fish_command_not_found_handler.fish` as mentionned, but it doesn't carry over to new shells.

**Comment by faho** [comment] 2015-09-11 22:53
Put it in config.fish (which is what I mentioned) or manually source that file there. (Also, functions usually go into ~/.config/fish/**functions**/)

The issue is fish autoloads functions on execution, so it doesn't know the definition of that function until it's executed at least once or otherwise sourced. (Though in this special case, you can _disable_ the handling without defining it as an event handler so it should also work as a normal function file - it just won't be executed until you do it manually once)

**Comment by occivink** [comment] 2015-09-11 23:29
>Also, functions usually go into ~/.config/fish/functions/

Uh right, that was what I meant.

Sourcing the file (or definiting the function) in fish.config doesn't seem to work, it seems like it needs to be executed at least once before.

**Comment by faho** [comment] 2015-09-12 09:41
You're on fish 2.2.0, right? I pushed the change to allow this _after_ that, so it's not in any release yet.
