### ISSUE TITLE
midnight commander subshell does not display prompt when minimized

### ISSUE THREAD

**Issue by Korkman** [fish-shell/fish-shell#8091] opened 2021-06-29 12:38 UTC
![grafik](https://user-images.githubusercontent.com/3186931/123796458-6e071380-d8e5-11eb-9d94-8184b508238e.png)

This is a regression in 3.3.0, although I must say it was flakey before. Tried with all 3rd party config removed. Broken across the board, seen in Debian Stretch, Buster, macOS (up-to-date brew versions).

**Comment by olfway** [comment] 2021-06-30 10:39
Same issue on macos, it was working before fish upgrade

**Comment by faho** [comment] 2021-06-30 10:48
This works if you set TERM=dumb, so it's something about our output having changed - either we now send the wrong stuff, or mc's terminal misunderstands us.

One possibility is #8011 - we now send `\r` before drawing the prompt again to be more resilient against width issues. (if it's that we'd love a fix in mc)

**Comment by faho** [comment] 2021-06-30 11:02
Yup, it's #8011, looks like mc's terminal is confused by our cursor movement. I recommend reporting it to them.

**Comment by olfway** [comment] 2021-06-30 12:06
Reported it: https://midnight-commander.org/ticket/4258

**Comment by olfway** [comment] 2021-06-30 12:07
I wonder can fish use some other command instead of '\r' ?

**Comment by faho** [comment] 2021-06-30 12:08
>I wonder can fish use some other command instead of '\r' ?

Basically not. `\r` is *simple*, does *exactly what we want* and is supported *everywhere* (that's a non-dumb terminal).

Using anything else would break elsewhere.

**Comment by olfway** [comment] 2021-06-30 12:13
I didn't use right prompt and I guess that a problem caused by
```
// Also move the cursor to the beginning of the line here,
// in case we're wrong about the width anywhere.
s_move(scr, 0, 0);
```
Actually I would prefer to have issues sometimes if fish is wrong with width instead of having no prompt always

**Comment by faho** [comment] 2021-06-30 12:19
>I didn't use right prompt and I guess that a problem caused by

Yup, that ends up sending the `\r`.

>Actually I would prefer to have issues sometimes if fish is wrong with width instead of having no prompt always

Sure, but having no prompt seems to be caused by mc being overly naive. In a "real" terminal this works, and if there's a choice between re-breaking it for many people in real terminals and few people in mc, that's unfortunately easy.

What we do seems correct, so this looks like an mc bug that needs to be fixed in mc.

**Comment by Korkman** [comment] 2021-06-30 21:35
I agree. This doesn't seem to be a bug in fish, but an incompatibility caused by naive assumptions in the mc subshell parser. @olfway Thank you for submitting the bug report to mc.

I found a workaround patching the fish_prompt function created by mc.

Here's my current code for now three bugs present in mc packages in Debian Jessie, Stretch and Buster:
```fish
function fish_prompt -d \
	"shell-pack prompt"
	if [ (status function) = "fish_prompt_mc" ]
		# this function was copied and renamed by mc to fish_prompt_mc
		
		# it is likely mc spammed the history, so we erase it immediately
		# (Debian Jessie and Stretch affected, fixed in Buster)
		if ! set -q __mc_history_cleared
			set -g __mc_history_cleared yes
			echo "all" | history delete --prefix "if not functions -q fish_prompt_mc;" &> /dev/null
		end
		
		# some hotfixing for the mc prompt
		if ! set -q mc_prompt_fixed
			set -g mc_prompt_fixed yes
			set -g mc_true_term "$TERM"
			
			set -l mc_prompt (functions fish_prompt)
			# # Defined interactively
			# function fish_prompt
			# echo "$PWD">&7; fish_prompt_mc; kill -STOP %self;
			# end
			
			# ^ this is how we expect fish_prompt to look like when overwritten by mc
			# note that >&7 is a variable pipe number

			set -l filtered_mc_prompt
			for mc_line in $mc_prompt
				if string trim -- "$mc_line" | string match -q "#*"
					# comment lines must be filtered or eval will not work!
					continue
				end
				
				# terrible bug in Debian Stretch: an additional prompt line!
				# let's remove it
				set mc_line (string replace --regex 'echo \(whoami\)[^;]+;' '' -- "$mc_line")
				
				# fish 3.3.0 started sending \r in capable terminals, which mc does not expect.
				# setting TERM to "dumb" and reverting at tactical places
				
				# append 'set -g TERM dumb' after 'kill .*;'
				set mc_line (string replace --regex 'kill .*;' '$0 set -g TERM dumb' -- "$mc_line")
				
				# prepend 'set -g TERM $mc_true_term' before 'echo $PWD'
				set mc_line (string replace --regex 'echo "\$PWD' 'set -g TERM "$$mc_true_term"; $0' -- "$mc_line")
				
				# save to list of lines
				set -a filtered_mc_prompt "$mc_line;"
			end
			
			# redefine fish_prompt
			eval "$filtered_mc_prompt"
			
			# also hook preexec to swap TERM for saved value
			function term_not_dumb_on_exec --on-event fish_preexec -d \
				"Revert to saved TERM value pre-exec"
				set -g TERM "$mc_true_term"
			end
			
		end
	end
	
	# prompt display code here
	…

end
```
This has the drawback of disabling any syntax highlighting and completions when in maximized mc subshell.

**Comment by faho** [comment] 2021-07-07 10:40
Alright, mc has a patch: https://github.com/MidnightCommander/mc/commit/e819ed742118dd4b9fc7d37e82830118df366ca4

If y'all could test that and report back at https://midnight-commander.org/ticket/4258, that would be great.

Since there's nothing to do on our end, I'm closing this.

**Closed by faho** 2021-07-07 10:40 UTC
