### ISSUE TITLE
Automatic startx doesn't work

### ISSUE THREAD

**Issue by Shadowigor** [fish-shell/fish-shell#1772] opened 2014-10-23 13:31 UTC
I appended the following to my ~/.config/fish/config.fish as suggested here https://wiki.archlinux.org/index.php/Start_X_at_login:

```
# Start X at login
if status --is-login
  if test -z "$DISPLAY" -a $XDG_VTNR = 1
    exec startx
  end
end
```

Unfortunately, this doesn't work. It just hangs and after a while I get kicked out and see the login prompt again. If I omit the 'exec'. It also hangs and I get to a shell after a while. If I manually enter 'startx', everything works fine. Is there a fix for that? I already saw [Issue #1281](https://github.com/fish-shell/fish-shell/issues/1281) and that's not the problem. My '/usr/bin/startx' has the '#!/bin/sh' line as the very fist line.

**Comment by fargledaer** [comment] 2015-01-18 23:55
I installed fish (2.1.1) on my Arch system (3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux) today and ran into the same issue.

My ~/.config/fish/config.fish is identical to the one in the initial post. When I login on tty1, nothing happens, and eventually I fall back to a login prompt. If I comment out the `exec startx` line, login works, and so does `startx` when I run it manually from the fish prompt. Additionally, if I switch my login shell to bash and add `exec startx` to ~/.bash_profile, it works as expected.

I investigated a bit further by adding some debug echoes to /usr/bin/startx, and found that it was hanging on this command:
   `xinit /home/<username>/.xinitrc -- /etc/X11/xinit/xserverrc :0 vt1 -auth /tmp/serverauth.wgAjQEOgOx`

I tried switching window managers in my ~/.xinitrc (from i3 to openbox) to rule out any window-manager-specific interactions. Same behavior.
   
Here's what `journalctl --follow` shows during a login attempt (asterisks added by me):
```
   Jan 19 02:24:14 <hostname> systemd[1]: Started Getty on tty1.
   Jan 19 02:24:35 <hostname> login[5422]: pam_unix(login:session): session opened for user <username> by LOGIN(uid=0)
   Jan 19 02:24:35 <hostname> systemd[1]: Starting Session c36 of user <username>.
   Jan 19 02:24:35 <hostname> systemd-logind[264]: New session c36 of user <username>.
   Jan 19 02:24:35 <hostname> systemd[1]: Started Session c36 of user <username>.
   Jan 19 02:24:35 <hostname> login[5422]: LOGIN ON tty1 BY <username>
   ***Jan 19 02:24:35 <hostname> systemd-coredump[5500]: Process 5499 (Xorg.bin) of user 1000 dumped core.***
   Jan 19 02:24:55 <hostname> login[5422]: pam_unix(login:session): session closed for user <username>
   Jan 19 02:24:55 <hostname> systemd[1]: getty@tty1.service has no holdoff time, scheduling restart.
   Jan 19 02:24:55 <hostname> systemd-logind[264]: Removed session c36.
   Jan 19 02:24:55 <hostname> systemd[1]: Stopping Getty on tty1...
   Jan 19 02:24:55 <hostname> systemd[1]: Starting Getty on tty1...
   Jan 19 02:24:55 <hostname> systemd[1]: Started Getty on tty1.
```

I added `ulimit -c unlimited` to startx right before the xinit line, hoping that I would get a core file in my home directory, but I didn't.

I'm not sure how to debug any further. Please let me know if any additional information would be helpful.

**Comment by zanchey** [comment] 2015-01-19 09:46
It might be worth using something like `exec strace -f startx -o ~/startx.strace.log` instead of plain `exec startx` and then posting the log that it produces (`startx.strace.log`), although that will produce a LOT of output.

**Comment by 0X1A** [comment] 2015-02-17 15:49
Any update on what exactly is causing this? I'm still having this exact issue with 2.1.1

**Comment by ridiculousfish** [comment] 2015-02-17 17:53
Possibly related to #367?

**Comment by zanchey** [comment] 2015-02-22 14:57
Using `strace` may not work after all due to X being setuid :-(

**Comment by natedalliard** [comment] 2015-03-28 10:48
I have the same issue on my machine (oh-my-fish and arch linux).

**Comment by mrak** [comment] 2015-03-28 20:46
I seem to have found the issue. Newer versions of `xorg` in Arch Linux run with user privileges and redirection will break the session. The key for me was using the `-keeptty` flag with `startx`:

```fish
# Start X at login
if status --is-login
  if test -z "$DISPLAY" -a $XDG_VTNR = 1
    exec startx -- -keeptty >~/.xorg.log ^&1
  end
end
```

You can use whichever file you want for the log; it doesn't have to be `~/.xorg.log`. This leads me to think that `fish` somehow deals with output and tty handoff differently than other shells when `exec` is used?

**Comment by ridiculousfish** [comment] 2015-03-28 23:07
Nice work @ mrak. I don't know of any differences offhand but there may be one. What is the difference - is it the redirection?

**Comment by mrak** [comment] 2015-03-28 23:12
@ridiculousfish I just verified that only `-keeptty` is needed.

```fish
# Start X at login
if status --is-login
  if test -z "$DISPLAY" -a $XDG_VTNR = 1
    exec startx -- -keeptty
  end
end
```

**Comment by mrak** [comment] 2015-03-28 23:16
The forum thread I found that described this fix is in [Arch Linux Forums / xorg-server 1.16 issues](https://bbs.archlinux.org/viewtopic.php?pid=1446402#p1446401).

The main gist is that X seems to lose track of which tty it's on while using fish in this way unless `-keeptty` is used.

**Comment by sploutchy** [comment] 2015-03-30 10:50
Thanks @mrak :)

**Comment by faho** [comment] 2015-09-02 13:30
I can reproduce this, now the question is if this needs a change in fish, one in X or a workaround in documentation.

**Comment by badele** [comment] 2016-02-06 09:22
Thank @mrak Effectivelly, it works !

**Comment by floam** [comment] 2016-06-18 11:03
@faho Does this still occur? Did @krader1961's tty PR affect this one way or the other?

**Comment by faho** [comment] 2016-06-18 12:04
@floam: I can't reproduce this anymore with vanilla 2.3.0.

I'm closing this as fixed there. If anyone still has this problem, please yell at me!

**Closed by faho** 2016-06-18 12:04 UTC

**Comment by yash-bansod** [comment] 2019-08-26 19:03
For those who are using fish in interactive mode please use:
```
# Start X at login
if status --is-interactive
  if test -z "$DISPLAY" -a $XDG_VTNR = 1
    exec startx -- -keeptty
  end
end
```
