### ISSUE TITLE
SSH host completion produces `awk` error after 2.7.0 update.

### ISSUE THREAD

**Issue by PodioSpaz** [fish-shell/fish-shell#4577] opened 2017-12-04 21:25 UTC
SSH host completion produces the following error: `awk: read error (Is a directory)`.

Fish Version: 2.7.0
OS: `Linux bodhi4 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Terminal: xterm

**Comment by zanchey** [comment] 2017-12-05 04:39
Presumably this is produced by the `awk` command in `__fish_print_hostnames` - does running that command directly produce the same error?

**Comment by PodioSpaz** [comment] 2017-12-05 14:19
Yes, running `__fish_print_hostnames` produces the same error.

**Comment by faho** [comment] 2017-12-11 09:57
> /etc/ssh/ssh_known_hosts is a directory, when it should be a file. 

I don't think ssh will actually read that, so there's something wrong with your configuration.

I'm not sure if we should remove the error here or if it was working as intended? I mean it did show you there was something actually wrong, so it was useful. But on the other hand the way these errors are displayed isn't great.

Anyway, suppressing stderr of completions is #4312, so I'm closing this in favor of that.

**Closed by faho** 2017-12-11 09:57 UTC
Labels: bug, completions
