### ISSUE TITLE
Invalid path escaping in completion for remote shell commands

### ISSUE THREAD

**Issue by morozov** [fish-shell/fish-shell#6495] opened 2020-01-13 05:00 UTC
```sh
$ fish --version
fish, version 3.0.2

$ uname -a
Linux redacted 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM
xterm-256color

# make sure customizations are not loaded
$ sh -c 'env HOME=$(mktemp -d) fish'
```

One the remote host named `remote`, there’s a directory `a b c` in the `$HOME` directory:
```sh
$ ssh remote -C 'ls -l ~/'
drwxr-xr-x  2 redacted redacted    4096 Jan 12 20:45 a b c
...
```

If I use commands like `scp` or `rsync` locally and try to complete the directory name, it completes as following:
```sh
$ scp remote:a<tab><tab>
$ scp remote:a\ b\ c/ .
scp: a: No such file or directory
scp: b: No such file or directory
scp: c: No such file or directory

$ rsync remote:a<tab><tab>
$ rsync remote:a\ b\ c/ .
rsync: link_stat "/home/redacted/a" failed: No such file or directory (2)
rsync: link_stat "/home/redacted/b" failed: No such file or directory (2)
rsync: change_dir "/home/redacted//c" failed: No such file or directory (2)
```

The paths should be escaped twice: once for the local shell, once for the remote. E.g.:
```sh
$ scp -r remote:a\\\ b\\\ c/ .
$ echo $status
0

$ rsync remote:a\\\ b\\\ c/ .
skipping directory .
$ echo $status
0
```

**Comment by zanchey** [comment] 2020-01-13 05:58
Duplicate of #1872 I think?

**Comment by morozov** [comment] 2020-01-13 07:34
Looks so. Any chance to get it fixed?

**Comment by krobelus** [comment] 2020-01-13 09:33
Should be fixed now :)

**Closed by krobelus** 2020-01-13 09:33 UTC
Labels: duplicate

**Comment by morozov** [comment] 2020-01-13 15:58
Thank you @krobelus! Works fine in my case.
