### ISSUE TITLE
no xf86 keys works when binded in dwm (startx in TTY°

### ISSUE THREAD

**Issue by Piczel** [fish-shell/fish-shell#3520] opened 2016-11-03 10:28 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
Arch Linux 4.8.6
dwm (dynamic window manager) 6.1 (config : http://sprunge.us/JDPR?c)

**Issue**
When launching dwm from startx in TTY (with fish), my xf86 keys binded for dwm (in config.h) aren't recognized (even with xev)
Works well with zsh, never had any problem

## Reproduction steps
1. use same WM, with same config (adapted for sure)
2. get in tty (with fish)
3. startx
4. no xf86 keys binded in config.h are working

**Comment by krader1961** [comment] 2016-11-03 17:43
The most likely explanation is that /etc/profile (or one of the other shell config scripts) that sh/bash/zsh sources is setting an environment variable that's needed by `startx` or `dwm`. Fish uses a different set of config scripts. It has to because it isn't POSIX 1003.1 compatible by design. To prove or disprove this hypothesis login as usual and run `set -x >/tmp/fish.env`. Then start an interactive zsh, `zsh -l`, and at it's prompt run `export >/tmp/zsh.env`. Then compare the two files. I'm betting you find that */tmp/zsh.env* contains an env var not in */tmp/fish.env*.

**Comment by Piczel** [comment] 2016-11-03 17:51
Hi, just compared the two files, there is no major differences (only LANG, MOZ_PLUGIN (firefox), and the PATH).. looks weird.

**Comment by krader1961** [comment] 2016-11-03 18:01
If `$PATH` is different that might affect the behavior of the commands you run. And that `$LANG` is different is also weird. Not sure what you mean by `.. looks weird`. Do you get the expected behavior from `startx` if you manually set LANG and PATH to the values zsh showed in the fish shell?

**Comment by faho** [comment] 2016-11-03 19:19
@Piczel: I've just tested your config with one tiny adjustment - 

```fish
static const char *upVol[]      = { "amixer", "set", "Master", "2+", NULL };
static const char *downVol[]      = { "amixer", "set", "Master", "2-", NULL };
static const char *muteVol[]    = { "amixer", "-q", "set", "Master", "toggle", NULL };
```

This is necessary because I don't have an `stm` program. What is it precisely?

Also, is it possible that you are missing another piece of your configuration? For example, how do you set your keyboard layout? Note that like Kurtis has said, fish will _not_ run /etc/profile, so if you have any invocation there, it will _not_ take effect if no POSIX shell reads it (which is usually only when they are started as a login shell).

(This is also on arch. Note that reducing volume by "2" is a tiny amount, so you might need to run "amixer get Master" to see that it is indeed changing)

>To prove or disprove this hypothesis login as usual and run set -x >/tmp/fish.env. Then start an interactive zsh, zsh -l, and at it's prompt run export >/tmp/zsh.env.

@krader1961: Actually, I'd suggest running `env` in both cases since our format is a bit different. Because we only care about exported variables, `env` will work.

**Comment by Piczel** [comment] 2016-11-04 08:11
Hi guys,

@faho : stm is just a simple script i wrote to manage volume/backlight/bluetooth/..

The $PATH is relativy the same (/usr/bin, ~/bin)

I use an azerty keyboard (fr)

In $LANG, there is too a problem, fish doesn't load /etc/profile, but already saw it

I tried to set all the zsh's env in fish (via set -gx VAR VALUE), but still doesn't work.

Regards.

**Comment by faho** [comment] 2016-11-04 10:19
>I use an azerty keyboard (fr)

Yes, but how do you set that? There are possibly other things being done in POSIX scripts (like /etc/profile, but not limited to that). And fish won't read them, so these things won't be done. And among those things is setting keyboard layout. Of course /etc/vconsole.conf will do that for the vconsole, but it won't for X.

>In $LANG, there is too a problem, fish doesn't load /etc/profile, but already saw it

Note that in the upcoming 2.4, fish will read /etc/locale.conf - which is where you usually want to define the language, not /etc/profile.

>I tried to set all the zsh's env in fish (via set -gx VAR VALUE), but still doesn't work.

That too points to something else being done.

Can you please try the following:

- Log in as your user (with fish as the shell)

- Run `zsh -l`

- Inside that, start `fish`

- Inside that, do `startx`

- See if the keys work

- Try all of this again, but only do `zsh` instead of `zsh -l`

If it works with `zsh -l`, but not `zsh` in the mix, then there is something inside the files that zsh runs as a login shell that you need. This includes /etc/profile but also /etc/profile.d and ~/.profile. If it works also with a non-login zsh, then you either source the login-shell files from the non-login ones or there's something else happening - it might be a program that launches your user's shell to read POSIX scripts (which will fail with fish).

**Comment by faho** [comment] 2016-11-17 21:47
@Piczel: Ping? Since I cannot reproduce this, I'm going to need your help.

**Comment by faho** [comment] 2016-11-28 09:04
@Piczel: I'm closing this since I can't reproduce it. If you ever get around to it, we'll reopen.

**Closed by faho** 2016-11-28 09:04 UTC
Labels: needs-more-info, question
