### ISSUE TITLE
Sudo completion / highlighting broken.

### ISSUE THREAD

**Issue by sarahkittyy** [fish-shell/fish-shell#6271] opened 2019-10-31 16:36 UTC
Fish version: `3.0.2`
`uname -a`: `Linux sarahkitty 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux`
`echo $TERM`: rxvt-unicode-256color

https://asciinema.org/a/ndTDRNCJIKATw9jOwgQUyCb1q

When a normal command is run, path completion with tab and right-arrow works fine.
When the same command is run with `sudo`, tab completion works, right-arrow doesn't.
If you give this `sudo` command arguments, neither tab-completion nor right-arrow completion works.

**Comment by faho** [comment] 2019-10-31 17:23
You mean `sudo -E`, which makes this a duplicate of #5675.

Unless I'm misunderstanding, but in that asciinema plain `sudo` seems to be working?

**Closed by faho** 2019-10-31 17:23 UTC

**Comment by sarahkittyy** [comment] 2019-10-31 17:45
@faho

I just tested it a little more:

Here is normal behavior, no sudo:
![image](https://user-images.githubusercontent.com/31551546/67971810-d61ec700-fbe3-11e9-9529-b5095ea99f62.png)
Note the visual path completion, and I can hit the right arrow on my keyboard to fill in the text.

Here is the behavior with sudo:
![image](https://user-images.githubusercontent.com/31551546/67971873-f9497680-fbe3-11e9-9785-70e6d4b4f6bb.png)
There is no visual completion shown, and hitting the right arrow does nothing. Hitting [TAB] will complete the path, though.

Here is the behavior with sudo + arguments (besides -E):
![image](https://user-images.githubusercontent.com/31551546/67972027-41689900-fbe4-11e9-92c4-164d459e27e9.png)
This works the same as with just sudo, no visual completion but [TAB] works.

Here is the behavior with `sudo -E`:
![image](https://user-images.githubusercontent.com/31551546/67972180-8b517f00-fbe4-11e9-84ba-66749c62921b.png)
No visual completion, and hitting [TAB] does absolutely nothing. No potential matches, no auto complete, nothing.

Is this intended behavior? It's awfully inconvenient, and even normal bash can tab-complete after `sudo -E`

**Comment by faho** [comment] 2019-10-31 17:52
> Note the visual path completion, and I can hit the right arrow on my keyboard to fill in the text.

Yes, that's because the suggestion suggests different things for different inputs.

In particular, for `sudo` the normal path completion is inhibited (because `sudo` doesn't take normal files).

Fixing this would basically require a rewrite of the completion system to allow enabling "real" file completion here, and the difference would be the underline.

>Is this intended behavior? It's awfully inconvenient, and even normal bash can tab-complete after sudo -E

It's a bug. #5675, which is fixed in the next release.

**Comment by faho** [comment] 2019-10-31 17:54
The workaround for `sudo -E` is to either download the current version of `sudo -E` or to enable the `qmark-noglob` feature flag, which disables the use of `?` as a glob (and which will become the default and then only behavior in future versions) - `set -U fish_features qmark-noglob`.

**Comment by sarahkittyy** [comment] 2019-10-31 17:58
Ok, thanks for clarifying
