### ISSUE TITLE
[performance][tmux] When default-shell is fish, new command run from a fish subshell, not directly from tmux

### ISSUE THREAD

**Issue by sulivanShu** [fish-shell/fish-shell#9333] opened 2022-11-07 19:25 UTC
- `fish, version 3.5.1`
- `tmux 3.3a`
- `Linux manjaro 6.0.2-3-MANJARO-ARM #1 SMP PREEMPT Sun Oct 16 16:24:03 UTC 2022 aarch64 GNU/Linux`
- `st-256color/tmux-256color`

Hi,

When default-shell is fish in tmux, new command runs from a fish subshell, not directly from tmux.

```
$ tmux -f <(echo set-option -g default-shell /usr/bin/fish) new
$ tmux new-window htop
(...)
─ tmux -f /dev/fd/63/ new
  └─ fish
  └─ fish -c htop
     └─ htop
(...)
```
The problem does not appear when enter the tmux new-window command without any other arguments.

When default-shell is bash, new command run directly from tmux.

```
$ tmux -f <(echo set-option -g default-shell /bin/bash) new
$ tmux new-window htop
(...)
─ tmux -f /dev/fd/63/ new
  └─ htop
  └─ bash
(...)
```
When default-shell is fish, creating a new subshell with each new no-shell tmux window consumes resources seemingly unnecessarily.

--

https://github.com/tmux/tmux/issues/3379 (Tmux forum)
https://bugs.launchpad.net/byobu/+bug/1995865 (Byobu forum)

**Comment by krobelus** [comment] 2022-11-07 19:39
tmux runs `$SHELL -c htop` in both cases, where `$SHELL` is tmux' `default-shell` option.
What you are seeing is that POSIX shells implicitly prepend `exec` to the last command but fish doesn't, see also https://github.com/fish-shell/fish-shell/issues/6902

One workaround is to set only `default-command` to fish and leave `default-shell` as /bin/sh

**Comment by faho** [comment] 2022-11-07 19:47
I'm inclined to call this a duplicate of #6902 - this is an additional complication of dubious value that we've rejected before

**Comment by krobelus** [comment] 2022-11-07 20:26
yeah AFAICT this only shows up in pstree-style tools, making them show the truth seems fine, I don't see good reason to change this (unless there is a perceptible impact on performance)

**Closed by krobelus** 2022-11-07 20:26 UTC

**Comment by sulivanShu** [comment] 2023-11-11 18:16
Here I give some tips to avoid splitting shells on Byobu Tmux. They probably can be transpose to vanilla Tmux or Screen.

In your `$BYOBU_CONFIG_DIR/profile.tmux`, add the line:

```
set -g default-command "exec $SHELL"
```

If you use `$BYOBU_CONFIG_DIR/windows.tmux` to open windows, you can limit shell duplication by putting `sh -c` in front of your commands. For example:

```
new-session -n htop sh -c htop;
new-window -n fish sh -c $SHELL;
```

However:

```
new-window -n sudo sh -c sudo -s;
```

Doesn't work and:

```
new-window -n vi nvim -S session.vim;
```

doesn't need `sh -c` before for not duplicate the shell, I don't know why.

These tips allow you to avoid keeping unnecessary instances of fish, which is annoying if you run dozens of programs with fish.
