### ISSUE TITLE
from make file && and || not working in fish shell 

### ISSUE THREAD

**Issue by kirankotari** [fish-shell/fish-shell#4836] opened 2018-03-19 07:38 UTC
I am using `fish version 2.7.1` on `darwin` with `xterm-256color`. I am liking fish but the existing make file are not working as expected due to `&&` and `||` in it. I couldn't change them due to other people still using the system default shells. 
Are you guys planning to support `&& and ||` else I need to shift back to system defaults.

**Comment by InspectorMustache** [comment] 2018-03-19 13:53
https://github.com/fish-shell/fish-shell/issues/4620
But I don't understand the relation between this and Makefile syntax.

**Comment by faho** [comment] 2018-03-19 15:18
Yup, this is effectively a duplicate of #4620, which you'll be happy to know has been fixed.

>But I don't understand the relation between this and Makefile syntax.

@InspectorMustache: Make uses $SHELL for a whole bunch of stuff.

@kirankotari: This particular piece of syntax has been added, but I'd argue that you _really_ don't want to use "the shell" for anything. Users can set their shell to e.g. python, if they so desire, so there is absolutely no guarantee what syntax it supports. Instead, set SHELL in your Makefile to whatever you support - if it is POSIX-compatible use

```make
SHELL := /bin/sh
```

if you need bash, use /bin/bash (or possibly /usr/bin/env bash). If you need python, use that.

Fish will now work if the only missing thing was "&&"/"||", but other things like `$()` and `if command; then` still aren't supported and much of it won't be.

**Closed by faho** 2018-03-19 15:18 UTC
Labels: duplicate

**Comment by faho** [comment] 2018-03-31 10:59
>does aliasing then to true or eval work?

@mqudsi: No, because with `true`, that will error out with arguments - `true git log` will print an error instead of executing `git log`. With `eval`, it'll double-evaluate any arguments.  `eval git log $branch` will expand `$branch` _twice_.

What we might use for this is the proposed `call` builtin. But that won't solve the issue, because after that, there's `fi`. And aliasing that to `end` won't work because that's not a command per-se, it's a keyword that is part of the syntax.
