### ISSUE TITLE
prompt shows weird output after terminal emulator starts

### ISSUE THREAD

**Issue by crdpa** [fish-shell/fish-shell#8080] opened 2021-06-21 17:52 UTC
It is random and does not happen always, but when i spawn a terminal sometimes i get this:

![fish](https://user-images.githubusercontent.com/61637474/122805908-0d9e2380-d2a0-11eb-9c0c-6325a6e58586.png)

I'm using foot terminal. It does not happen with bash.

`function fish_title; end; funcsave fish_title` did not solve the issue.

Locale:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Using Fish 3.2.2

**Comment by faho** [comment] 2021-06-21 18:13
Duplicate of #7893

**Closed by faho** 2021-06-21 18:13 UTC
