### ISSUE TITLE
Error in `completions/git.fish` causes crash

### ISSUE THREAD

**Issue by giorgiga** [fish-shell/fish-shell#9236] opened 2022-09-25 14:58 UTC
If I type `git -C Pro` and then hit tab to complete "Projects" (~/Projects is where i put... yes, that) I get 

    ~ ❱ git -C Pro/usr/share/fish/completions/git.fish (line 618): The expanded command was empty.
        $__fish_git_needs_command
        ^
    in function '__fish_git_needs_command'
    in command substitution
    jects/

and then the shell crashes whenever I hit a key.

Got this with fish 3.5.0, on an up-to-date Fedora f36 system.

Starting fish with `sh -c 'env HOME=$(mktemp -d) fish'` gives the same results.

**Comment by faho** [comment] 2022-09-25 15:18
Duplicate of #9053

**Closed by faho** 2022-09-25 15:18 UTC

**Comment by faho** [comment] 2022-09-25 15:19
This is, in fact, fixed in fish 3.5.1, released over 2 months ago.
