### ISSUE TITLE
[Bug] commandline doesn't work inside of completion functions

### ISSUE THREAD

**Issue by ajeetdsouza** [fish-shell/fish-shell#8771] opened 2022-03-09 11:45 UTC
Reported by @NextAlone via https://github.com/ajeetdsouza/zoxide/issues/341

fish version 3.3.1-1093-g959e17fac

The `commandline` builtin doesn't work when called via a completion. Consider the following script:

```fish
function foo
end

function _foo_complete
  commandline --current-process "this is foo"
end

complete -c foo -e
complete -c foo -f -a '(_foo_complete)'
```

After defining this, `foo<space><tab>` should invoke the completion function, which would replace the current command with `this is foo`. However, while this works for me on macOS and WSL2, it does not seem to be working for @NextAlone, who is on Arch Linux.

**Comment by faho** [comment] 2022-03-09 12:13
Duplicate of #6637

**Comment by faho** [comment] 2022-03-09 12:14
To put it simply, this is not something we want to support.

**Closed by faho** 2022-03-09 12:13 UTC
