### ISSUE TITLE
feature request: history insert

### ISSUE THREAD

**Issue by lolbinarycat** [fish-shell/fish-shell#10750] opened 2024-09-27 21:18 UTC
a new `insert` subcommand for the `history` builtin that adds the given commandline to the history as soon as it was typed.

this would be helpful along with `history delete --previous` to add `git switch branch` to my history whenever i do a `git switch -c branch`.

**Comment by faho** [comment] 2024-09-28 04:43
Duplicate of #4506

**Closed by faho** 2024-09-28 04:43 UTC
