### ISSUE TITLE
WSL - Piping xxd output to cut results in "usetpgid: Operation not permitted" and unresponsive terminal

### ISSUE THREAD

**Issue by paramsen** [fish-shell/fish-shell#5031] opened 2018-06-07 08:43 UTC
`fish -v`:  
fish, version 2.7.1

`uname -a`:  
Linux NAME 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

`echo $TERM`:  
xterm-256color

Running ` sh -c 'env HOME=$(mktemp -d) fish'` does not solve it.

Steps to reproduce:

Run `xxd -l10 <some file> | cut -d ' ' -f1,1`

Output:

    Could not send process <2256W, '>cut ' in job f1i, 'sxxd -l100 file | cut -d ' ' -f1,1h' from group :2033  to group C2255o
    ulsetpgid: Operation not permitted
    d Could not send job n1o ('txxd -l100 file | cut -d ' ' -f1,1 ') to foregrounds
    etcsetpgrp: Operation not permitted
    nd job 1 ('xxd -l100 file | cut -d ' ' -f1,1') to foreground
    tcsetpgrp: Operation not permitted

**Comment by faho** [comment] 2018-06-07 10:12
This is either a duplicate of #4776, #4715 or #4884.

**Closed by faho** 2018-06-07 10:12 UTC
