### ISSUE TITLE
autocomplete last commands arguments

### ISSUE THREAD

**Issue by saikiranrgda** [fish-shell/fish-shell#1973] opened 2015-03-09 14:40 UTC
It would be nice to autocomplete last command's argument like bash does.

ex:
```
$ ls .config/fish/config.fish
$ vi <ESC>  . 
```
This should fill the .config/fish/config.fish (last command's argument). We could also use ` <ALT> .` to cycle through multiple last commands.

**Comment by mrak** [comment] 2015-03-09 15:04
You can make a user keybinding to do this, as I think it is mapped to At+up by default

**Comment by zanchey** [comment] 2015-03-11 08:18
Indeed, `Alt-Up` will do this from the default keybindings and can be added to your own for ESC+`.`. See #89, #1125. I will close this as a duplicate of those for now as I note that the ESC+`.` behaviour is default in the next release (soonish, I hope!)

**Closed by zanchey** 2015-03-11 08:18 UTC
