### ISSUE TITLE
Fish expanding path prepends backslash in front of tilde, sometimes

### ISSUE THREAD

**Issue by jagenheim** [fish-shell/fish-shell#8943] opened 2022-05-09 08:06 UTC
fish --version: 3.3.1
Running arch 5.15.10
TERM: tmux-256color (but it's alacritty)
Tried without third party customization and it was reproducible.

Reproduce:
$ mkdir ~/foobar
$ touch ~/foobar/foobar1.zip
$ touch ~/foobar/foobar2.zip
$ unzip ~/foobar/foozip [tab]
Selecting a entry here will produce
$ unzip \~/foobar/foobar1.zip
Making the unzip command unable to find the zip file

This does NOT happen for
'ls' as command, or if the path expanded is
$ unzip ~/foobar/foobar [tab]

It does not happen if the path does not have the tilde character in front either.

**Comment by faho** [comment] 2022-05-09 09:00
Duplicate of #4570

**Closed by faho** 2022-05-09 09:00 UTC
