### ISSUE TITLE
rename public interfaces to not begin with a double underscore

### ISSUE THREAD

**Issue by PenegalECI** [fish-shell/fish-shell#4191] opened 2017-07-06 14:48 UTC
Hello, there.

I'm using fish 2.4.0, and working on completions for `mdadm`, which pull I will eventually request. I'm puzzled with the builtins for options tests: there is `__fish_contains_opt`, to test if an option has already been selected, and `__fish_not_contain_opt`, to test if an option has not been already tested. What puzzles me here is the difference between these names: the first one has the 3rd-person 's', whereas the second one does not have it. Once you got it, you deal with it easily, but it looks like a useless idiosyncrasy; `__fish_not_contain_opt` should be renamed to `__fish_not_contains_opt`, or does the 's' disappeared with the implied 'does'?

Regards.

**Comment by krader1961** [comment] 2017-07-06 16:00
> ... or does the 's' disappeared with the implied 'does'?

Yes, and that is probably why the author used the singular. English is weird. And I say that as a native speaker of 56 years.

I don't think there is any point in just adding or removing the `s` (depending on which one we modify). But since we're going to do a major release this might be a good time to change something more significant that has bugged me from day one. Too many functions and vars begin with a double-underscore implying they are a private implementation detail that are in fact public and not subject to arbitrary change. Fish 3.0 would be an ideal time to fix this confusing pattern. And while doing so we could introduce better, or at least more consistent, names for things like the functions in the original comment of this issue. Obviously we'll want to retain the old names for the foreseeable future but they would be explicitly marked as deprecated with an explicit planned removal date.

If we do this what should the new naming pattern look like? My preference is either a single leading underscore or no leading underscore for anything with a stable interface that users are free to use (if its a function name) or set (if its a var). Such names would be documented. Any function or var name that begins with two or more leading underscores is an implementation detail that should be treated as a black box. Using a dunderscore function or var means your code can be broken in a minor release.

**Comment by faho** [comment] 2017-07-09 10:39
Note that `__fish_not_contain_opt` is equivalent to `not __fish_contains_opt` - `__fish_not_contain_opt` is true when none of the given options are present, `__fish_contains_opt` if any of the given options is. We should remove the former.

There's a few ways we can go about that:

- Just remove it and let it error.
- Change `__fish_not_contain_opt` to just call `not __fish_contains_opt`
- Do that and also add a warning
- Make the warning conditional - i.e. save in a global or universal variable that we've printed the warning so it isn't thrown constantly.

We could do something like

```fish
function fish_deprecate -a oldname -a newname
    if not set -q fish_deprecated_warnings
        set -U fish_deprecated_warnings
    end
    if not contains -- $oldname $fish_deprecated_warnings
        echo "Warning: Function '$oldname' will be removed." >&2
        echo "Please use '$newname' instead." >&2
        set fish_deprecated_warnings $fish_deprecated_warnings $oldname
    end
end

function __fish_not_contain_opt
     fish_deprecate (status function) "not __fish_contains_opt"
     not __fish_contains_opt $argv
end
```

It'd be nice if we could print the caller-of-the-caller in `fish_deprecate` (i.e. what called `__fish_not_contain_opt`, the deprecated function).

>If we do this what should the new naming pattern look like? My preference is either a single leading underscore or no leading underscore for anything with a stable interface that users are free to use (if its a function name) or set (if its a var).

Whatever the exact convention, I'd say that we want to downplay things that aren't useful from the commandline, so they don't appear in completions that much.

**Comment by krader1961** [comment] 2017-07-11 02:31
> Note that `__fish_not_contain_opt` is equivalent to `not __fish_contains_opt`... We should remove the former.

Agreed. My first reaction was to up vote your fourth suggestion. But the problem is that we can't really provide good context and the user seeing the message probably did not write the code using the now deprecated function and won't have a clue what to do about the warning.

Since I'm proposing renaming functions like these that aren't really private in fish 3.0 the simplest is to keep the current functions as is but document them as deprecated. Then only implement a public name for `__fish_contains_opt`. At some future date (fish 3.x where x > 2) we start removing the deprecated function names.

> Whatever the exact convention, I'd say that we want to downplay things that aren't useful from the commandline, so they don't appear in completions that much.

My current viewpoint is that functions and variables we would expect an average user to use should never have a leading underscore. This includes things like the `__fish_git_prompt_showstashstate` variable to alter how `__fish_git_prompt` behaves. Neither of those should have leading underscores. 

Functions and variables that we promise to have a stable interface and are documented, but meant for use by people doing advanced things like writing completions, will have a single leading underscore. A large number of "helper" functions like `__fish_contains_opt` fall into this category.

Anything truly private (e.g., vars holding private state for functions shipped with fish) will have two leading underscores. Anyone referencing such symbols can expect their code to be broken in any release -- even a point fix (i.e., critical bug fixes only) release.

**Comment by krader1961** [comment] 2017-08-05 01:26
Removing the RFC label because I think there is consensus that we want to rename a lot of public functions and variables so that they prefixed with the misleading double-underscore (at least if you're coming from other languages like Python) which implies they are private.

**Comment by zanchey** [comment] 2017-08-09 11:09
FWIW, the documentation is clear that the current double-underscore functions are subject to change at any time:

> `fish` ships with several functions that are very useful when writing command specific completions. Most of these functions name begins with the string '`__fish_`'. Such functions are internal to `fish` and their name and interface may change in future fish versions. Still, some of them may be very useful when writing completions. A few of these functions are described here. Be aware that they may be removed or changed in future versions of fish.

**Comment by faho** [comment] 2023-05-11 11:53
It's been five years, I don't think this is happening en masse - we have renamed some important things like `fish_git_prompt`, but the completion helper functions have stayed like that for ages and aren't changing a lot.

**Closed by faho** 2023-05-11 11:53 UTC
Labels: cleanup
