### ISSUE TITLE
regression: abbr no longer saves abbreviations across session (my favorite thing in fish)

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#9865] opened 2023-06-28 02:35 UTC
https://www.reddit.com/r/fishshell/comments/10a7lrx/abbreviations_are_not_being_saved/

I just setup a new computer with fish shell and kept adding abbreviations but then in a new session they are not being saved.

I see in `man abbr`:

> Changed in version 3.6.0: Previous versions of this allowed saving abbreviations in universal variables.  That's no longer possible. Existing variables will still be imported and abbr --erase will also
>        erase the variables.  We recommend adding abbreviations to config.fish by just adding the abbr --add command.  When you run abbr, you will see output like this
> 
>           > abbr
>           abbr -a -- foo bar # imported from a universal variable, see `help abbr`
> 
>        In that case you should take the part before the # comment and save it in config.fish, then you can run abbr --erase to remove the universal variable:
> 
>           > abbr >> ~/.config/fish/config.fish
>           > abbr --erase (abbr --list) 

I'm super confused by this and consider this a user experience regression as it makes my workflow less "flowly". Are there plans to add this back? This workaround is very cludgy and quite tedious.  Why would I want to erase it, I just added it? And if we do have to put them in a file, shouldn't we have them in an abbr.fish include, so we can just overwrite this and not have to keep apending?

This was one of my favorite features of fish and when I spoke to other developers and told them how much I loved fish, the first thing I spoke of was the abbreviations and how easy it was to create them on the fly. I felt sad discovering it was removed.

**Comment by faho** [comment] 2023-06-28 03:31
Duplicate of #9523

Yes, this was intentional, and no, it's not coming back. Unfortunately with the added power of abbrs on 3.6.0, storing them in the old universal variables no longer works, and so we decided against it. Sorry.

**Closed by faho** 2023-06-28 03:31 UTC

**Comment by ElijahLynn** [comment] 2023-06-29 17:26
Okay, thanks for confirming. 😢

**Comment by ElijahLynn** [comment] 2023-06-29 17:27
For others who come across this, I just found this:

>  Like fish's abbr, zsh-abbr supports interactive creation of persistent abbreviations which are immediately available in all terminal sessions. Abbreviations automatically sync to a file, ready for your dotfile management.

source: https://zsh-abbr.olets.dev/

**Comment by ElijahLynn** [comment] 2023-06-30 00:52
Gonna use this thread to rubber duck solutions:

So, I just learned that fish automatically reads ~/.config/fish/conf.d, so we can move all our abbreviations to ~/.config/fish/conf.d/abbreviations.fish. I think the man page should suggest that as a minor improvement too. 

Next up is to figure out how to be able to manage that file interactively like zsh does.
