### ISSUE TITLE
Portable fish shell

### ISSUE THREAD

**Issue by dxlr8r** [fish-shell/fish-shell#3095] opened 2016-05-31 14:38 UTC
Hello, I'm trying to create a "portable" version of fish. I have user access to several hosts and want to take my enviroment with me. All hosts are x86, no gcc/compiler nor fish.

I tried to compile on personal server I have, and it built and ran there. 

`./configure --prefix=$HOME/opt/ --disable-shared --enable-static`

Then i tgz-ed it, transfered to a new host, unpacked and tried to run, but got following error:

```
-bash-4.1$ /home/foo/opt/bin/fish
-bash: /home/foo/opt/bin/fish: No such file or directory
```

Some input would be great.

**Comment by faho** [comment] 2016-05-31 15:43
So the file "/home/foo/opt/bin/fish" is the fish binary? Is it marked as executable (`chmod +x`)?

Usually "No such file or directory" means that there's "no such file or directory", so that'd be the first thing you should check.

Is your username the same on all these hosts? If not, `$HOME` would be different. Did you also move our scripts and such or just the binary? The latter isn't likely to work as we rely on our scripts.

**Comment by dxlr8r** [comment] 2016-06-01 06:21
Yes, that's the binary. It is executable and it exists, ls will show it, so will cat, etc.

$HOME is changed though, not the same username. But it's compiles static, shouldn't it work anyway?

**Comment by zanchey** [comment] 2016-06-01 09:06
That's not what static compilation does; also, $HOME will be expanded on the command line, so `configure` receives the actual value.

fish already supports relocatable builds - if you supply a prefix to configure, and no other compiled paths, then you can move the prefix around as you wish.

What does `file /home/foo/opt/bin/fish` say? What about `uname -a`?

**Comment by dxlr8r** [comment] 2016-06-01 09:40
file:
`-bash-4.1$ file /home/foo/opt/bin/fish`
`/home/foo/opt/bin/fish: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically`
`linked (uses shared libs), for GNU/Linux 3.12.0, not stripped`

uname:
`-bash-4.1$ uname -a`
`Linux foo.net 2.6.18-409.el5 #1 SMP Fri Feb 12 06:37:28 EST 2016 x86_64 GNU/Linux`

**Comment by zanchey** [comment] 2016-06-01 09:53
I wonder if [this StackExchange question](http://unix.stackexchange.com/q/76490/78890) is the same problem.

What's the output of `ldd /home/foo/opt/bin/fish`? Does the file indicated by `objdump -j .interp -s /home/foo/opt/bin/fish` exist?

**Comment by dxlr8r** [comment] 2016-06-01 10:49
`-bash-4.1$ ldd /home/foo/opt/bin/fish`
`	not a dynamic executable`

**Comment by faho** [comment] 2016-06-01 12:03
Well, does "/lib/ld-linux-x86-64.so.2" exist?

**Comment by dxlr8r** [comment] 2016-06-01 12:17
No it doesn't.

Is there anyway of making this portable? I configure and make on a Crux Linux, I don't have access to a RHEL 5.11 which I can install -dev packages and gcc on.

**Comment by faho** [comment] 2016-06-01 13:07
>Is there anyway of making this portable?

The advice I've usually seen (for proprietary games, mostly) is to build on the oldest glibc you'll want to support. So install Debian 4 or something (dunno if RHEL updated glibc within the 5.X releases, Debian 4 was released the same year) in a vm and build there.

**Comment by dxlr8r** [comment] 2016-06-01 13:10
Installing CentOS 5.11 as we speak. Would be cool if fish had a portable version so people could always bring their own enviroment wherever they may go. 

Well keep you updated.

**Comment by zanchey** [comment] 2016-06-01 13:12
I can't convince my toolchain to build a static binary - how did you manage? LDFLAGS or something?

**Comment by dxlr8r** [comment] 2016-06-01 13:14
No, just the ./configure flags from the first post.

`./configure --prefix=$HOME/opt/ --disable-shared --enable-static`

**Comment by zanchey** [comment] 2016-06-01 13:17
Interesting.

FWIW, I don't think anyone's tested a statically-linked binary - it may behave in unexpected ways. The `string` function would be the most obvious thing to test.

**Comment by dxlr8r** [comment] 2016-06-01 13:54
I got it to work on my setup, but it isn't portable or anything. But binary from CentOS built to the same path as my homefolder on the RHEL machines. Just tarred the whole "opt" tree down (only residence is fish), scp, untarred and it works.

So what I wanted is solved in that sense, but would still be great to have it portable and self sustained.

**Comment by faho** [comment] 2016-06-01 16:05
>So what I wanted is solved in that sense, but would still be great to have it portable and self sustained.

You're not going to get fish as a single file - we rely on our scripts far too much for that to work. But apart from the linking issue (which I don't think is possible to solve), what more problems did you have?

**Comment by pickfire** [comment] 2016-06-02 06:23
Yeah, I don't think fish isn't very portable, I tried fish with sbase, seems like it just suddenly broke. And I am planning to migrate to alpine linux which uses busybox and I hope that I could still use fish there.

**Comment by dxlr8r** [comment] 2016-06-02 08:15
> You're not going to get fish as a single file

Never said I wanted it in a file, I wanted all contents in a folder that you could package/unpackage and use on all x86 Linuxes. 

I asked how to make it portable, but ended up building a version that is linked to a path and RHEL. So it works as in I wanted Fish on a RHEL computer I don't have root on.

**Comment by faho** [comment] 2016-06-02 10:52
>Yeah, I don't think fish isn't very portable, I tried fish with sbase, seems like it just suddenly broke. And I am planning to migrate to alpine linux which uses busybox and I hope that I could still use fish there.

This is about a different definition of "portable". Not "you can compile the thing on different systems", but "you can take the files that make up the thing and use it on another system".

>I asked how to make it portable, but ended up building a version that is linked to a path and RHEL.

There's still a few system libraries that we link dynamically - glibc (a few .so's from that), gcc-libs and ncurses. (It doesn't seem "--disable-shared --enable-static" is doing anything)

I'm not sure it's possible to link them dynamically. For ncurses, there is #1271.

This is why you get the error - the thing that is not found is _the linker_. Any C/C++ program will have that issue on linux. AFAIK the only way to not use the linker is to statically link _everything_.

But: Even if you had a completely statically linked fish binary, you'd still be dependent on parts of the system for scripts. I think we're not using too much - mostly coreutils-y stuff, and both GNU and OSX/BSD versions work - but it's still a dependency. The "weirdest" dependency we use is probably bc.

Because your direct problem is solved, I'm closing this.

**Closed by faho** 2016-06-02 10:52 UTC
Labels: question

**Comment by floam** [comment] 2016-06-05 09:13
The OS X .app bundle is relocatable and should meet the definition of a portable app. It's one logical blob but a lot of files.

**Comment by ridiculousfish** [comment] 2016-06-05 09:17
To be clear, fish is everywhere relocatable in the sense that it can find its configuration and functions based on its runtime path. You can tar up a  directory hierarchy containing fish, move it around, untar it somewhere else. But of course you are still subject to the dynamic linker and its machinery for locating dylibs.

**Comment by dxlr8r** [comment] 2020-03-04 16:15
@anki-code I don't use fish anymore because of lack of here docs. But perhaps this can help: http://statifier.sourceforge.net/

**Comment by anki-code** [comment] 2020-03-04 16:22
@dxlr8r thank you for your response!
Could you please tell what you're using now?
Have you ever tried [xonsh shell](https://xon.sh/)? If yes could you please share your thoughts?

**Comment by dxlr8r** [comment] 2020-03-05 09:30
@anki-code went back to sh/bash, as I needed my scripts to be portable, and I found it strange to use one syntax on cmd line and another in scripts. bash ain't that bad when you get used to it. 

Haven't tried xonsh, maybe I will. I have created something a like to it myself, for internal usage at my work.

**Comment by faho** [comment] 2020-03-05 09:38
Folks, can I ask you to move this discussion elsewhere?

It's nice you found a shell for you, but if it's not fish this isn't really the right place for it.

**Comment by joanbm** [comment] 2020-03-05 13:47
Now that the build is CMake-based I gave this a try. With this patch applied to the CMakeFiles.txt of 3.1.0 one can build a static fish executable:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7fdfe9e..e52b0df 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,6 +9,10 @@ ENDIF()
 
 PROJECT(fish)
 
+SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
+SET(BUILD_SHARED_LIBS OFF)
+SET(CMAKE_EXE_LINKER_FLAGS "-static")
+
 # We are C++11.
 SET(CMAKE_CXX_STANDARD 11)
 SET(DEFAULT_BUILD_TYPE "RelWithDebInfo")
@@ -172,7 +176,7 @@ ENDFUNCTION(FISH_LINK_DEPS)
 ADD_LIBRARY(fishlib STATIC ${FISH_SRCS})
 TARGET_SOURCES(fishlib PRIVATE ${FISH_HEADERS})
 TARGET_LINK_LIBRARIES(fishlib
-  ${CURSES_LIBRARY} ${CURSES_EXTRA_LIBRARY} Threads::Threads ${CMAKE_DL_LIBS}
+  ${CURSES_LIBRARY} termcap ${CURSES_EXTRA_LIBRARY} "-Wl,--whole-archive -lpthread -Wl,--no-whole-archive" ${CMAKE_DL_LIBS}
   ${PCRE2_LIB} ${Intl_LIBRARIES} ${ATOMIC_LIBRARY})
 
 # Define fish.
```

Sources:
* https://stackoverflow.com/a/24671474
* https://stackoverflow.com/a/31265512

After this I got an statically linked fish executable that runs on the container it was compiled on, however, it seems to crash on other machines I copy it to.

During the linking phase of the build a lot of warnings like this appear:

```warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking```

So perhaps one of those is the cause, or perhaps it's something entirely different...

**Comment by anki-code** [comment] 2020-03-05 16:12
@faho if there is a way to make fish portable I could port it to [xxh](/xxh/xxh)

@joanbm what version of linux you use in the container? The best way is to using older GLIBs and build the container in Ubuntu 16 or in manylinux2010 for example.

**Comment by faho** [comment] 2020-03-05 16:14
Unfortunately if you're gonna link statically glibc is basically a non-starter. Use e.g. musl instead.

**Comment by joanbm** [comment] 2020-03-05 17:23
@anki-code: I tried using ubuntu:18.04 to build it. If like @faho says musl is better, it would make sense to try to use alpine instead.

**Comment by joanbm** [comment] 2020-03-07 00:08
I was bored so I gave it a try and managed to build an static fish binary with an Alpine container. After this you can then copy it out of the container with `docker cp` and onto another system.

It starts correctly on both my real Arch Linux system and an Ubuntu 16.04 container. I haven't tested it much so don't complain if something is broken. You will need to copy it on the exact same install path on the target system (e.g. `/home/normaluser/.fish-portable` in this `Dockerfile`) otherwise it will start but throw a lot of errors because it expects the files there.

```
    FROM alpine:3.11
    
    RUN apk add doxygen ncurses-dev ncurses ncurses-static pcre2-dev cmake make gcc g++
    
    RUN addgroup -S normaluser && adduser -S normaluser -G normaluser
    USER normaluser
    WORKDIR /home/normaluser
    
    ARG FISH_VERSION=3.1.0
    ARG FISH_TAR_CHECKSUM=29f24e9b1344ec7048076a6081286f717c8b9a9119397db6e57d31949657d2f4
    
    RUN wget https://github.com/fish-shell/fish-shell/archive/$FISH_VERSION/fish-$FISH_VERSION.tar.gz \
     && echo "$FISH_TAR_CHECKSUM  fish-$FISH_VERSION.tar.gz" | sha256sum -c \
     && tar xf fish-$FISH_VERSION.tar.gz
    
    WORKDIR fish-shell-$FISH_VERSION
    
    RUN printf 'diff --git a/CMakeLists.txt b/CMakeLists.txt\n\
    index 7fdfe9e..0e1aaab 100644\n\
    --- a/CMakeLists.txt\n\
    +++ b/CMakeLists.txt\n\
    @@ -9,6 +9,10 @@ ENDIF()\n\
     \n\
     PROJECT(fish)\n\
     \n\
    +SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")\n\
    +SET(BUILD_SHARED_LIBS OFF)\n\
    +SET(CMAKE_EXE_LINKER_FLAGS "-static -no-pie")\n\
    +\n\
     \x23 We are C++11.\n\
     SET(CMAKE_CXX_STANDARD 11)\n\
     SET(DEFAULT_BUILD_TYPE "RelWithDebInfo")\n\
    @@ -166,6 +170,7 @@ INCLUDE(cmake/PCRE2.cmake)\n\
     \x23 Define a function to link dependencies.\n\
     FUNCTION(FISH_LINK_DEPS target)\n\
       TARGET_LINK_LIBRARIES(${target} fishlib)\n\
    +  SET_TARGET_PROPERTIES(${target} PROPERTIES LINK_SEARCH_END_STATIC 1)\n\
     ENDFUNCTION(FISH_LINK_DEPS)\n\
     \n\
     \x23 Define libfish.a.\n\
    ' | patch -Np1
    
    RUN echo $FISH_VERSION > version \
     && mkdir -p build \
     && cd build \
     && cmake -DCMAKE_INSTALL_PREFIX="$HOME/.fish-portable" -DCMAKE_INSTALL_SYSCONFDIR="$HOME/.fish-portable" -DCMAKE_BUILD_TYPE=Release .. \
     && make -j$(nproc) \
     && make install
    
    CMD '/home/normaluser/.fish-portable/bin/fish'
```

**Comment by zanchey** [comment] 2020-03-07 06:24
Publishing an AppImage is probably the way to go here, see #6475

**Comment by anki-code** [comment] 2020-03-07 08:04
@zanchey thank you for the link! It helped me to add entrypoint for fish appimage to [xxh](https://github.com/xxh/xxh) — [xxh-shell-fish-appimage](https://github.com/xxh/xxh-shell-fish-appimage).

 🐟  +  📦  +  🐌  =  🎉

**Comment by anki-code** [comment] 2020-03-25 17:47
@joanbm could you please review my simpler version - https://github.com/fish-shell/fish-shell/issues/6808 ? What I'm doing wrong?
