### ISSUE TITLE
Process substitution with fifo doesn't work as expected

### ISSUE THREAD

**Issue by rmccampbell** [fish-shell/fish-shell#7174] opened 2020-07-03 22:02 UTC
fish version: 3.1.2
OS: Windows 10 WSL, Ubuntu 18.04.2 (Also tried it on a real linux box via SSH)

When I try using the process substitution command `psub` with the `--fifo` option, I expect that it will not block and allow the main command to execute while the subprocess is still generating output. Instead it buffers the output and only executes the main command once the subprocess ends. Example:

```
function cmd
    sleep 1; echo a
    sleep 1; echo b
    sleep 1; echo c
end

cmd
cat (cmd | psub --fifo)
```
I expect that the command with process substitution should echo each line with a 1 second delay, as the raw function does. This is the behavior in bash with `cat <(cmd)`. Instead it waits 3 seconds and echoes all three lines at once.

**Comment by faho** [comment] 2020-07-04 05:28
Duplicate of #1040

**Closed by faho** 2020-07-04 05:28 UTC
