### ISSUE TITLE
BROWSER env var (for e.g. help) not working correctly on OSX

### ISSUE THREAD

**Issue by NinoFloris** [fish-shell/fish-shell#3213] opened 2016-07-08 21:21 UTC
**fish version installed**: fish, version 2.3.1
**OS/terminal used**: OSX 10.11

## Reproduction steps
1. Launch fish
2. export BROWSER="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
3. help

## Expected results
Fish should open chrome

## Actual results
Fish opens my default association for .html files, as specified for finder (how 'open file.html' works)

**Comment by krader1961** [comment] 2016-07-08 22:04
Issue #3076 is probably relevant. The short answer is setting the `BROWSER` var doesn't work on macOS and no one knows how to make it work. It's really an "upstream" problem with a python module we use.

**Comment by faho** [comment] 2016-07-09 07:28
The more relevant issue being #2814.

The problem is that we can't support $BROWSER on macOS because our underlying python module is broken in that regard with python 2 and apple still doesn't ship python 3.

So: Sorry, there doesn't appear to be anything to do for us here.

I'm marking this as a duplicate of #2814, if you have an idea how to fix it we'd welcome it.

**Closed by faho** 2016-07-09 07:28 UTC

**Comment by floam** [comment] 2016-07-09 07:37
I'll note that in #2814 something I corrected later in the thread was that python 2 and 3 at that time were pretty much equally annoying here. (and it wouldn't be impossible for us to work around it.)
