### ISSUE TITLE
Stray Characters in Alacritty 0.10.0

### ISSUE THREAD

**Issue by ryancerium** [fish-shell/fish-shell#8714] opened 2022-02-10 18:00 UTC
Fish version: 3.3.1
Terminal: Alacritty 0.10.0

WSL 1, running Ubuntu 18.04

```bash
$ uname -a
Linux LAPEX-RPHELPS 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM
xterm-256color
```

It looks like Fish is printing some (partial escape code?) characters around application output.  Specifically, a `l` character tends to come around the beginning of the output and a `h` character tends to come around the last line of output.  The problem does not occur in Bash.  This also occurs if I use the Lucida Sans Typewriter font, which is not a nerd font.

These examples are all in the `~/temp` directory that contains 3 files imaginatively named `1`, `2`, and `3`.  You can see the `l` as part of the `ls` command and the `h` as part of the file `1` name.

My problem:
![image](https://user-images.githubusercontent.com/1735570/153458873-45b9c6df-8dc2-40fa-b620-f03df87ec5d2.png)

Removing customizations, the `h` has moved to the `3` file this time.
![image](https://user-images.githubusercontent.com/1735570/153459586-74281e5f-8750-4015-a85e-20afe0b73b6a.png)

The *really* weird part is that horizontally resizing the Alacritty window redraws the lines correctly and removes the stray characters.  Any idea what Fish is sending that Alacritty is failing to render correctly?

This _might_ be related to this Alacritty issue: https://github.com/alacritty/alacritty/issues/5333

**Comment by faho** [comment] 2022-02-10 18:06
Duplicate of #8240

**Closed as completed by faho** 2022-02-10 18:06 UTC
Labels: duplicate

**Comment by ryancerium** [comment] 2022-02-10 20:47
You are a kind and generous soul @faho.  Thanks for the info!
