### ISSUE TITLE
Can't enter MFA code (aws) after a fish read

### ISSUE THREAD

**Issue by jlsjonas** [fish-shell/fish-shell#4261] opened 2017-07-28 09:16 UTC
$ fish --version
fish, version 2.5.0
$ uname -a
Darwin Jonass-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
$ echo $TERM
xterm-256color

I have a script that uses fish' internal read a few times, and executes several AWS(-cli) commands.
Since we recently enforced MFA we're now required to enter a code every x minutes to make the commands go through.

For some reason, entering the code doesn't work if there has been a read.

notes: the code is requested in a password-style prompt, likely (haven't verified) using bash' read function (causing the issue)?

**Comment by faho** [comment] 2017-08-11 11:47
@jlsjonas: I'm closing this because, with the current information, there is basically zero chance of us doing anything about it.

Even if you add enough info, chances are it's caused by #3805 or similar.

If you wish to help us figure that out, at a minimum we'd need to know how exactly this MFA prompt is started. Is it included in a fish script? Is it injected somehow from the outside? Is it something weird like bash executing fish with a background script that starts the prompt at certain intervals?

**Closed by faho** 2017-08-11 11:47 UTC
Labels: needs-more-info, question

**Comment by jlsjonas** [comment] 2017-08-11 11:50
Hi, sorry missed the previous reply.

the aws cli is responsible for this MFA prompt

**Comment by faho** [comment] 2017-08-11 12:03
>the aws cli is responsible for this MFA prompt

Being unfamiliar with the aws cli, that's unfortunately not specific enough.

We'd need to know _how it's implemented_. Do you know of any documentation on this?

**Comment by jlsjonas** [comment] 2017-08-11 12:25
Sorry, if I did I would’ve mentioned it instead; a quick google search also doesn’t show related info


Jonas De Kegel
Full-Stack Developer/DevOps, Starcoders
Mobile: +32 468 29 28 29
Website: www.starcoders.com

**Comment by faho** [comment] 2017-08-11 12:43
In that case, let's just assume it's #3805. When that's fixed and this isn't, we can reopen this one.
