### ISSUE TITLE
sudo -E not complete commands

### ISSUE THREAD

**Issue by celsolom** [fish-shell/fish-shell#5675] opened 2019-02-19 13:44 UTC
The completion of sudo commands not working when i use "sudo -E". In 2.7.1 version, its works perfectly.

FISH Version: **3.0.1**

LSB Version:	**:core-4.1-amd64:core-4.1-noarch**
Distributor ID:	**Fedora**
Description:	**Fedora release 29 (Twenty Nine)**
Release:	**29**
Codename:	**TwentyNine**
_Linux 4.20.8-200.fc29.x86_64 #1 SMP Wed Feb 13 13:08:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux_

**Comment by faho** [comment] 2019-02-19 14:26
This is a bug in fish's core completion code, which doesn't like completing commands if the token is empty. The `sudo` completions now rely on that.

You'll have to enter _something_ for it to trigger now.

**Comment by faho** [comment] 2019-02-19 14:37
Okay, this is effectively a duplicate of #5418.

**Comment by celsolom** [comment] 2019-02-19 15:03
https://asciinema.org/a/228455

**Comment by faho** [comment] 2019-02-19 15:20
Whatnow? That works for me.

**Comment by faho** [comment] 2019-02-19 15:22
So... let's check that the completion scripts are all correct. Please run the following:

```fish
for f in $fish_complete_path/{sudo,dnf,yum}.fish
    test -f $f; and sha256sum $f
end
```

and post the output.

**Comment by celsolom** [comment] 2019-02-19 15:28
f639cafc28700c1e36ccfbeb90c4d2d84375e419d3eb6fd33b7d42ff98ecc93b  /usr/share/fish/completions/sudo.fish
04103b67210081e783c67087f5a03d77f55d80b37b93b8e990cc25a6566eeb40  /usr/share/fish/completions/dnf.fish
e484082b5f7bf148e8af68379be744da93b05768324633e163c0cba7905544c5  /usr/share/fish/completions/yum.fish
84bacba41947f177f89a28a8ec2798861a1a7460c946503caa9e0d4352e73835  /home/celso/.local/share/fish/generated_completions/sudo.fish
dfa218f4f559251d01549396485e3cd271052b7a51b730296840aff5792b14f4  /home/celso/.local/share/fish/generated_completions/dnf.fish
cc0030f5b25522ec38d2050bbf646a2bbd1c2ad50e09648d17f7bec6e47a7a24  /home/celso/.local/share/fish/generated_completions/yum.fish

**Comment by faho** [comment] 2019-02-19 17:06
`type sudo dnf yum`?

**Comment by celsolom** [comment] 2019-02-19 17:08
sudo is /usr/bin/sudo
dnf is /usr/bin/dnf
yum is /usr/bin/yum

**Comment by faho** [comment] 2019-02-19 17:52
Can you trigger the same thing with e.g. `git` instead of `dnf`?

I don't actually have dnf installed, so it's _possible_ that I'm missing something there.

Also I'm assuming this is the package from [our repository](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish), as it seems that Fedora doesn't have 3.0.1 yet?

**Comment by celsolom** [comment] 2019-02-19 18:09
I made update to version 3.0.2 from your repository (https://download.opensuse.org/repositories/shells:/fish:/release:/3/Fedora_29/x86_64/fish-3.0.2-1.1.x86_64.rpm)
Same with `git`.
https://asciinema.org/a/228500

**Comment by faho** [comment] 2019-02-20 21:30
Okay, I figured out the issue: There's an unquoted `?` in the sudo completions, and that is still, by default, a one-character glob. So it tried to match `E/preserve-env=?` to a file, which of course failed so it expanded to nothing, removing the option from consideration.

Unless you've disabled `?` globs, as I've been doing on my system.

**Closed by faho** 2019-02-20 21:30 UTC
Labels: needs more info

**Comment by celsolom** [comment] 2019-02-21 15:16
Worked!
`set -l opts A/askpass b/background C/close-from= 'E/preserve-env=?'`
