### ISSUE TITLE
$version variable empty (fish install from Debian repos)

### ISSUE THREAD

**Issue by Le-Technologue** [fish-shell/fish-shell#8689] opened 2022-02-01 16:18 UTC
Installed fish today from the Debian testing repos and it has a few bugs.

For a start, its version variable is blank. Which hinders installation of oh-my-fish for instance.

Of course I could try to edit it for a quick and dirty fix, but it's a readonly variable (as it should be), so it's not very encouraging !

Thanks in advance for your attention to this bug !

![image](https://user-images.githubusercontent.com/73589177/152004613-2791505f-37d8-4364-9011-8cb2464db6cf.png)

**Comment by floam** [comment] 2022-02-01 16:19
Duplicate of #8689

**Closed by floam** 2022-02-01 16:19 UTC
