### ISSUE TITLE
Command prompt is repeating when resize window size for all two-line prompt!!!

### ISSUE THREAD

**Issue by V0idk** [fish-shell/fish-shell#4964] opened 2018-05-08 09:16 UTC
```bash
↪ fish --version
fish, version 2.7.1-1147-g21890cca
# I use of the newest fish : 
mkdir build; cd build
cmake ..
make
sudo make install
```

```bash
↪ uname -a
Linux asd 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
↪   sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
# Random choose a two-line prompt, i choose Simple Pythonista.
zhong@asd /h/zhong> fish_config 
Web config started at 'file:///tmp/tmp.YwerwFp8wp/.cache/fish/web_config-ITO5MV.html'. Hit enter to stop.
Shutting down.
zhong at asd in /h/zhong
```
now resize the window! and you can see that the prompt become:
```bash
zhong at asd in /h/zhong                            zhong at asd in /h/zhongggonzhong at asd in /h/zhong in /h/zhongongg in /h/zhozhong atzhong zhonzhong at asd in /h/zhong asd in /h/zzhong atzhong zhong zhong at asd in /h/zhongg at asd in /h/zzhong at asdzhong at asd in /h/zhonghong asd izhongzhong at asd in /h/zhongt azhong at asd in /h/zhongsd izhong at azhongzhozhozzhong at asdzhong at asd inzhong at asd in /h/zhongh/zhongh/zhongh/zhongh/zhzhong atzhong at asd in /h/zhong
↪ 
```

![image](https://user-images.githubusercontent.com/17514799/39748744-6ff43c80-52e3-11e8-83df-a319603986a2.png)

and the prompt function: 
```
zhong at asd in ~
↪ cat /usr/local/share/fish/tools/web_config/sample_prompts/pythonista.fish 
# name: Simple Pythonista
# author: davbo


function fish_prompt
    if not set -q VIRTUAL_ENV_DISABLE_PROMPT
        set -g VIRTUAL_ENV_DISABLE_PROMPT true
    end
    set_color yellow
    printf '%s' (whoami)
    set_color normal
    printf ' at '

    set_color magenta
    echo -n (prompt_hostname)
    set_color normal
    printf ' in '

    set_color $fish_color_cwd
    printf '%s' (prompt_pwd)
    set_color normal

    # Line 2
    echo
    if test $VIRTUAL_ENV
        printf "(%s) " (set_color blue)(basename $VIRTUAL_ENV)(set_color normal)
    end
    printf '↪ '
    set_color normal
end

```

what's wrong?

**Comment by faho** [comment] 2018-05-08 10:38
Duplicate of #2320.

**Closed by faho** 2018-05-08 10:38 UTC
