### ISSUE TITLE
Recursive glob only looks in subdirectories

### ISSUE THREAD

**Issue by anordal** [fish-shell/fish-shell#3014] opened 2016-05-09 15:39 UTC
fish:

    > ls -1 **/*.txt
    sub/b.txt
    >
    > ls -1 {,**/}*.txt
    a.txt
    sub/b.txt

bash:

    > shopt -s globstar
    > ls -1 **/*.txt
    a.txt
    sub/b.txt

Any reason for this difference? I find the bash behaviour more convenient (except the need for globstar of course).

The [online documentation](http://www.fishshell.com/docs/current/index.html#expand) seems to describe the bash behaviour with this sentence «** matches any files and directories in the current directory and all of its subdirectories».

**Comment by faho** [comment] 2016-05-09 16:36
Well, `**` does match any files and directories. `ls -1 **.txt` would match both "a.txt" and "sub/b.txt".

The issue here is that "**/*.txt" means that the relative path needs to contain a "/", and that's only the case in subdirectories (unless you'd match "./", and neither fish nor bash do that here). From that point of view it seems quite logical.

The documentation should be improved, and there may well be arguments against this (or other glob behavior), though.

**Comment by faho** [comment] 2016-05-09 16:53
Okay, this has already been discussed in #2680. In response to this @krader1961 already clarified the documentation (which hasn't hit the online copy yet).

**Comment by krader1961** [comment] 2016-05-09 18:09
See also issue #2414. Unless someone believes the documentation regarding this is still inadequate, or the behavior is broken, we can probably close this. The relevant text from issue #2680 was my final comment:

> The fact that **/pattern won't match files in the current folder is a bit baffling to me too.

It turns out this is by design, @oranja. In fish you simply omit the slash; e.g., `echo ***.fish` in fish is the same as `echo **/*.fish` in zsh. I mention that in the change I just committed to clarify the behavior.

**Comment by anordal** [comment] 2016-05-10 10:30
Now I get it `**` works on the textual level, rather than an abstract directory recursion level. That would be a better summary of how fish differs from bash/zsh than the title «Recursive glob only looks in subdirectories».
Okay then, `**/*.txt` was a bad example since it is easily translatable to `**.txt`. Suppose it's `**/a.txt` instead, excluding **/gorilla.txt:

bash/zsh:

    > ls -1 **/a.txt
    a.txt
    sub/a.txt

fish:

    > ls -1 **a.txt
    a.txt
    gorilla.txt
    sub/a.txt
    sub/gorilla.txt
    >
    > ls -1 **/a.txt
    sub/a.txt
    >
    > ls -1 {,**/}a.txt
    a.txt
    sub/a.txt

**Comment by krader1961** [comment] 2016-05-10 23:10
The way to get bash behavior is to use two globs `*.txt **/*.txt`; the first matches items in the pwd and the second matches items in subdirectories.

**Comment by anordal** [comment] 2016-05-11 19:34
Yeah, that's what I feared. Fortunately, it's possible to collapse the two globs into `{,**/}`, so the rest of the expression won't have to be repeated.

**Closed** 2016-05-11 19:44 UTC
Labels: posix-me-harder, question
