### ISSUE TITLE
zombies leak when disowning a background process in fish_prompt

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7581] opened 2020-12-27 16:39 UTC
```fish
function fish_prompt
    sleep 1 &
    disown (jobs --last --pid)
    echo $PWD
end
```

The number of `sleep <defunct>` processes grows with every prompt render. `fish 3.1.2`

**Comment by faho** [comment] 2020-12-27 16:55
Should be fixed by #7189, and I can't reproduce it in master (but can in 3.1.2)

**Closed by faho** 2020-12-27 16:55 UTC
