### ISSUE TITLE
Allow variable as a command with `exec`

### ISSUE THREAD

**Issue by hauleth** [fish-shell/fish-shell#708] opened 2013-05-03 06:41 UTC
I know that fish don't allow variables as commands, but it will be nice if `exec` will allow variable as command name. If someone run that (s)he probably knows what is (s)he doing.

**Comment by krader1961** [comment] 2016-12-14 04:19
Closing as a duplicate of issue #154.

**Closed by krader1961** 2016-12-14 04:19 UTC
Labels: duplicate
