### ISSUE TITLE
set_color: Unknown color 'ff80'

### ISSUE THREAD

**Issue by FRiMN** [fish-shell/fish-shell#10247] opened 2024-01-22 11:25 UTC
I using fish in xfce-terminal.  In **some directories** I get an error in `fish_prompt` function.

```fish
math: Error: Unknown function
'0.2126 x 0xff + 0.7152 x 0x80 + 0.0722 x'
                                        ^
test: Missing argument at index 3
-lt 120
        ^
~/.config/fish/functions/fish_prompt.fish (line 24): 
        while test (math 0.2126 x $col[1] + 0.7152 x $col[2] + 0.0722 x $col[3]) -lt 120
              ^
in function 'fish_prompt'
in command substitution
set_color: Unknown color 'ff80'
```

In that place in function the variables had the following values:
```fish
pwd: /media/frimn/archive3/ai/llama/privateGPT
col: 0xff 0x80
```

```fish
~►fish --version  
fish, version 3.6.1
~►uname -a  
Linux frimn-MS-7D75 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
~►echo $TERM 
xterm-256color
```

**Comment by faho** [comment] 2024-01-22 11:50
Duplicate of #9164

**Comment by faho** [comment] 2024-01-22 11:51
It appears you have an outdated version of the disco prompt.

Run `fish_config` and select it again.

**Closed by faho** 2024-01-22 11:50 UTC
