### ISSUE TITLE
History search breaks when an empty entry is written to the history file

### ISSUE THREAD

**Issue by kanemathers** [fish-shell/fish-shell#6881] opened 2020-04-10 08:50 UTC
### Debug Info

```
$ fish --version
fish, version 3.0.2
```

```
$ uname -a
Linux xps 5.5.15-200.fc31.x86_64 #1 SMP Thu Apr 2 19:16:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

Problem persists when running fish without third-party customizations.

### The Problem

I've noticed an issue where by I fat finger `alt+enter`, hit enter to submit the line and fish's history search stops working. You can't search the history with `up` and the default suggestions seems broken.

I've tracked this down to, what appears to be, an issue with parsing the history file:

```
$ tail ~/.local/share/fish/fish_history 
- cmd: clear
  when: 1586508223
- cmd: fish --version
  when: 1586508228
- cmd: uname -a
  when: 1586508249
- cmd: echo $TERM
  when: 1586508254
- cmd: 
  when: 1586508411
```

Notice the last entry is `- cmd: `. It's a blank entry. This appears to trip up the history search. If I manually remove this line and open a new terminal, history search resumes working.

**Comment by faho** [comment] 2020-04-10 09:28
Duplicate of #6032

**Closed by faho** 2020-04-10 09:28 UTC
