### ISSUE TITLE
Autocompletion with unicode double some characters

### ISSUE THREAD

**Issue by mart-e** [fish-shell/fish-shell#5059] opened 2018-06-19 15:36 UTC
- `fish --version`: 2.7.1
- `platform`: Archlinux
- `$TERM`: xterm-256color
- `Terminal`: terminator

Hi there,

When typing a command containing an unicode character (for instance `echo "😀"`), fish got confused and the auto-completion double some characters. 

As you can see in the asciinema below, after typing 😀, the  second `"` starts doing funny things and display `echo ""😀"`.

At the last line, I type, slowly `e`, `c`, `h`, and it displays `eccoohh`

https://asciinema.org/a/5vnA3DDMWgUAVNHsqaglQvEHD

**Comment by faho** [comment] 2018-06-19 16:30
Duplicate of #4539, #4609 and numerous other issues.

**Closed by faho** 2018-06-19 16:30 UTC
