### ISSUE TITLE
Build error/failed on aarch64 / arm64 ( autocxx v0.23.1 )

### ISSUE THREAD

**Issue by skygunner** [fish-shell/fish-shell#9695] opened 2023-03-31 08:21 UTC
from master source
seems its about autocxx v0.23.1
maybe use a known working version of autocxx and pin it?

```Shell
   Compiling autocxx v0.23.1 (https://github.com/fish-shell/autocxx?branch=fish#f9ed164f)
The following warnings were emitted during compilation:

warning: /home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx: In function ‘bool cxxbridge1$output_stream_t$append_formatv(output_stream_t&, const wchar_t*, std::array<long unsigned int, 4>*)’:
warning: /home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx:845:119: error: cannot convert ‘bool (output_stream_t::*)(const wchar_t*, va_list)’ to ‘bool (output_stream_t::*)(const wchar_t*, std::array<long unsigned int, 4>)’ in initialization
warning:   845 |   bool (::output_stream_t::*append_formatv$)(const wchar_t *, ::std::array<::std::uint64_t, 4>) = &::output_stream_t::append_formatv;
warning:       |                                                                                                                       ^~~~~~~~~~~~~~

error: failed to run custom build command for `fish-rust v0.1.0 (/home/user/git/fish-shell/fish-rust)`

Caused by:
  process didn't exit successfully: `/home/user/git/fish-shell/./cargo/build/release/build/fish-rust-7a09ef5edd57be40/build-script-build` (exit status: 1)
  --- stdout
  cargo:CXXBRIDGE_PREFIX=fish-rust
  cargo:CXXBRIDGE_DIR0=/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/include
  cargo:CXXBRIDGE_DIR1=/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/crate

...

  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/home/user/git/fish-shell/fish-rust/../src/" "-I" "/home/user/git/fish-shell" "-I" "/home/user/git/fish-shell/cargo/build/aarch64-unknown-linux-gnu/cxxbridge/rust/" "-I" "/home/user/git/fish-shell/fish-autocxx-gen/include" "-Wall" "-Wextra" "-Wno-comment" "-std=c++11" "-o" "/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/6a2ae13e8edef82d-gen0.o" "-c" "/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx"
  cargo:warning=/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx: In function ‘bool cxxbridge1$output_stream_t$append_formatv(output_stream_t&, const wchar_t*, std::array<long unsigned int, 4>*)’:
  cargo:warning=/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx:845:119: error: cannot convert ‘bool (output_stream_t::*)(const wchar_t*, va_list)’ to ‘bool (output_stream_t::*)(const wchar_t*, std::array<long unsigned int, 4>)’ in initialization
  cargo:warning=  845 |   bool (::output_stream_t::*append_formatv$)(const wchar_t *, ::std::array<::std::uint64_t, 4>) = &::output_stream_t::append_formatv;
  cargo:warning=      |                                                                                                                       ^~~~~~~~~~~~~~
  exit status: 1

  --- stderr

  CXX include path:
    /home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/include
    /home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/crate


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/home/user/git/fish-shell/fish-rust/../src/" "-I" "/home/user/git/fish-shell" "-I" "/home/user/git/fish-shell/cargo/build/aarch64-unknown-linux-gnu/cxxbridge/rust/" "-I" "/home/user/git/fish-shell/fish-autocxx-gen/include" "-Wall" "-Wextra" "-Wno-comment" "-std=c++11" "-o" "/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/6a2ae13e8edef82d-gen0.o" "-c" "/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx" with args "c++" did not execute successfully (status code exit status: 1).


make[3]: *** [CMakeFiles/_cargo-build_fish-rust.dir/build.make:70: CMakeFiles/_cargo-build_fish-rust] Error 101
make[2]: *** [CMakeFiles/Makefile2:400: CMakeFiles/_cargo-build_fish-rust.dir/all] Error 2
make[1]: *** [/home/user/git/fish-shell/Makefile:136: all] Error 2
make: *** [GNUmakefile:26: all] Error 2
[sudo] password for user:
[  0%] Built target cargo-prebuild_fish-rust
    Updating git repository `https://github.com/fish-shell/autocxx`

....

   Compiling autocxx v0.23.1 (https://github.com/fish-shell/autocxx?branch=fish#f9ed164f)
The following warnings were emitted during compilation:

warning: /home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx: In function ‘bool cxxbridge1$output_stream_t$append_formatv(output_stream_t&, const wchar_t*, std::array<long unsigned int, 4>*)’:
warning: /home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx:845:119: error: cannot convert ‘bool (output_stream_t::*)(const wchar_t*, va_list)’ to ‘bool (output_stream_t::*)(const wchar_t*, std::array<long unsigned int, 4>)’ in initialization
warning:   845 |   bool (::output_stream_t::*append_formatv$)(const wchar_t *, ::std::array<::std::uint64_t, 4>) = &::output_stream_t::append_formatv;
warning:       |                                                                                                                       ^~~~~~~~~~~~~~

error: failed to run custom build command for `fish-rust v0.1.0 (/home/user/git/fish-shell/fish-rust)`

Caused by:
  process didn't exit successfully: `/home/user/git/fish-shell/./cargo/build/release/build/fish-rust-7a09ef5edd57be40/build-script-build` (exit status: 1)
  --- stdout
  cargo:CXXBRIDGE_PREFIX=fish-rust
  cargo:CXXBRIDGE_DIR0=/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/include
  cargo:CXXBRIDGE_DIR1=/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/crate

...

  CARGO_CFG_TARGET_FEATURE = Some("neon")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/home/user/git/fish-shell/fish-rust/../src/" "-I" "/home/user/git/fish-shell" "-I" "/home/user/git/fish-shell/cargo/build/aarch64-unknown-linux-gnu/cxxbridge/rust/" "-I" "/home/user/git/fish-shell/fish-autocxx-gen/include" "-Wall" "-Wextra" "-Wno-comment" "-std=c++11" "-o" "/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/6a2ae13e8edef82d-gen0.o" "-c" "/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx"
  cargo:warning=/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx: In function ‘bool cxxbridge1$output_stream_t$append_formatv(output_stream_t&, const wchar_t*, std::array<long unsigned int, 4>*)’:
  cargo:warning=/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx:845:119: error: cannot convert ‘bool (output_stream_t::*)(const wchar_t*, va_list)’ to ‘bool (output_stream_t::*)(const wchar_t*, std::array<long unsigned int, 4>)’ in initialization
  cargo:warning=  845 |   bool (::output_stream_t::*append_formatv$)(const wchar_t *, ::std::array<::std::uint64_t, 4>) = &::output_stream_t::append_formatv;
  cargo:warning=      |                                                                                                                       ^~~~~~~~~~~~~~
  exit status: 1

  --- stderr

  CXX include path:
    /home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/include
    /home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/cxxbridge/crate


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/home/user/git/fish-shell/fish-rust/../src/" "-I" "/home/user/git/fish-shell" "-I" "/home/user/git/fish-shell/cargo/build/aarch64-unknown-linux-gnu/cxxbridge/rust/" "-I" "/home/user/git/fish-shell/fish-autocxx-gen/include" "-Wall" "-Wextra" "-Wno-comment" "-std=c++11" "-o" "/home/user/git/fish-shell/./cargo/build/aarch64-unknown-linux-gnu/release/build/fish-rust-c75493e8bb1f03ed/out/6a2ae13e8edef82d-gen0.o" "-c" "/home/user/git/fish-shell/fish-autocxx-gen/cxx/gen0.cxx" with args "c++" did not execute successfully (status code exit status: 1).


make[3]: *** [CMakeFiles/_cargo-build_fish-rust.dir/build.make:70: CMakeFiles/_cargo-build_fish-rust] Error 101
make[2]: *** [CMakeFiles/Makefile2:400: CMakeFiles/_cargo-build_fish-rust.dir/all] Error 2
make[1]: *** [/home/user/git/fish-shell/Makefile:136: all] Error 2
make: *** [GNUmakefile:28: install] Error 2
```

**Comment by faho** [comment] 2023-03-31 08:56
Duplicate of #9665

**Closed by faho** 2023-03-31 08:56 UTC
