### ISSUE TITLE
Subfolders for user defined functions

### ISSUE THREAD

**Issue by mustaqimM** [fish-shell/fish-shell#4947] opened 2018-04-27 05:12 UTC
fish, version `2.7.1`
OS - `Linux arch 4.16.3-1-ARCH`

I feel the functions folder is getting cluttered with user defined functions and linked functions from installed plugins with fisherman. It would be nice to have fish still find recursively, functions in arbitrary named folders.

**Comment by zanchey** [comment] 2018-04-27 05:30
See #1819 from 2014, where we decided against implementing this. I'll leave this open for now in case there are new arguments, but my feeling would be that the added complexity is not worth it.

**Comment by mqudsi** [comment] 2018-10-02 02:12
> just load the functions recursively from all folders (**I suppose it's not that hard?**)

See https://github.com/fish-shell/fish-shell/issues/1819#issuecomment-63683307

fisherman could just add to fish_function_paths and install its functions into another directory.

----

I'm closing this as a duplicate of #1819. Feel free to continue the discussion there, and we can reopen it if anyone's opinion on this has changed.

**Closed by mqudsi** 2018-10-02 02:12 UTC
Labels: RFC, enhancement
