### ISSUE TITLE
Ranger's shell -w receives no input when ranger is started from config.fish

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#3468] opened 2016-10-17 06:52 UTC
On Arch Linux, urxvt 9.22, fish 2.3.1.

If I start ranger (1.7.2) automatically from my config.fish

	 ranger

ranger's `shell -w` receives no input. The `-w` flags forces ranger to wait for the child process.
With `shell -w read foo`, I cannot type any character.

However, if I quit ranger, and then restart it, the issue is gone.

I tried specifying a different shell for ranger in config.fish:

	env SHELL=sh ranger

Same issue. Typing `shell -w echo $SHELL` will return `sh`, but the input will be blocked.

Neither bash nor zsh have this issue.

Not sure whether this is a ranger or fish issue, so I've also reported it at
https://github.com/ranger/ranger/issues/689.

**Comment by krader1961** [comment] 2016-10-17 23:54
This is almost certainly a duplicate of issue #2980. Is "ranger" reading from your terminal? If yes and pressing [ctlr-J] rather than [enter] causes it to recognize whatever you type then it is definitely the same issue.

**Comment by Ambrevar** [comment] 2016-10-18 02:20
Indeed!

**Closed** 2016-10-18 02:26 UTC
Labels: duplicate
