### ISSUE TITLE
[Feature request] Mass delete backwards when using Ctrl+Del

### ISSUE THREAD

**Issue by TheEvilSkeleton** [fish-shell/fish-shell#7501] opened 2020-11-24 01:30 UTC
> Please tell us which fish version you are using by executing the following:
> 
>   fish --version
>   echo $version

fish, version 3.1.2

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
> 
>   sh -c 'env HOME=$(mktemp -d) fish'

```
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```

> Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

`uname -a`: `Linux TheMainDesktop 5.9.8-200.fc33.x86_64 #1 SMP Tue Nov 10 21:58:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

`echo $TERM`: `xterm-256color`

## Feature request

I'd like to use `Ctrl`+`Del` keys to mass delete backwards, as shown below:

In the terminal, it is what it is currently; in VSCode, it is as I want it to be.

![fish](https://user-images.githubusercontent.com/50847364/100034435-2b6adf00-2dca-11eb-9f9a-a5bb38dba8bb.gif)

**Comment by krobelus** [comment] 2020-11-24 21:57
Yeah we should probably map this to `kill-word`, like <kbd>Alt</kbd>+<kbd>D</kbd>.

You can do that with a simple bind command, but first you need to find out which key codes are sent when you press Ctrl+Del.
For example:

```
> fish_key_reader
Press a key:
              hex:   1B  char: \c[  (or \e)
(  0.021 ms)  hex:   5B  char: [
(  0.009 ms)  hex:   33  char: 3
(  0.010 ms)  hex:   3B  char: ;
(  0.010 ms)  hex:   35  char: 5
(  0.021 ms)  hex:   7E  char: ~
bind \e\[3\;5~ 'do something'
> bind \e\[3\;5~ kill-word
>
```

Due to historical compatibilty options, the delete key can also send the char 8 (ASCII backspace / <kbd>Ctrl</kbd>+<kbd>H</kbd>) or 127 (ASCII delete)
I believe we can get the active mapping from tcgetattr but I'm not sure.

**Comment by TheEvilSkeleton** [comment] 2020-11-24 22:47
That seems to be working, thank you so much.

Should I keep the issue opened or should it be closed?

**Comment by krobelus** [comment] 2020-11-24 23:06
Duplicate of #4770

**Closed by krobelus** 2020-11-24 23:06 UTC

**Comment by krobelus** [comment] 2020-11-24 23:07
Realized there was already an issue. I'm not sure how difficult this is.
