### ISSUE TITLE
Suggestion: don't suggest selected items for autocompletion

### ISSUE THREAD

**Issue by kristof-mattei** [fish-shell/fish-shell#9505] opened 2023-01-22 20:39 UTC
```

fish, version 3.6.0
3.6.0
```

Ascii showing the issue:
[ASCII](https://asciinema.org/a/553511)

Description:

Situation:
1) Git repo with 3 branches, `main`, `bar` and `foo`
2) Being on `main`
3) Typing in `git branch -d bar ` 
4) Pressing the autocomplete key suggests `bar`, `foo` and `main`

Expected behavior:

`bar` is not suggested, as it is already typed in.

**Comment by faho** [comment] 2023-01-22 21:01
Duplicate of #231

**Closed by faho** 2023-01-22 21:01 UTC

**Comment by kristof-mattei** [comment] 2023-01-22 21:09
> Duplicate of #231

Thank you. I didn't find it with Google.
