### ISSUE TITLE
Arguments with command substitution breaks `fish --no-execute` for some commands

### ISSUE THREAD

**Issue by ntkme** [fish-shell/fish-shell#6018] opened 2019-07-31 06:54 UTC
```
$ fish --version
fish, version 3.0.2
```

Initially I found this issue on `switch`. I tried a few other fish commands, and found that it appears to be a generic issue.

In the case of `switch` we do get an error message, and in other cases we got an error without a message. Here are a few examples:

```
$ switch (uname); case Linux; echo penguin; case Darwin: echo mac; end

$ echo 'switch (uname); case Linux; echo penguin; case Darwin; echo mac; end' | fish --no-execute
fish: switch: Expected exactly one argument, got 0

switch (uname); case Linux; echo penguin; case Darwin; echo mac; end
       ^
```

```
$ pushd (echo $HOME)

$ echo 'pushd (echo $HOME)' | fish --no-execute
fish: 
pushd (echo $HOME)
^
```

```
$ type (echo echo)
echo is a builtin

$ echo 'type (echo echo)' | fish --no-execute
fish: 
type (echo echo)
^
```

```
$ eval (echo echo)

$ echo 'eval (echo echo)' | fish --no-execute
fish: 
eval (echo echo)
^
```

**Comment by faho** [comment] 2019-07-31 07:12
The latter bit is #977 - `type` and `eval` are functions, and no-execute doesn't load functions.

Which just leaves the switch case. Which I could have sworn we also have a bug open about, but github's search is letting me down here.

**Comment by ntkme** [comment] 2019-07-31 07:15
@faho #4943 looks very similar.

**Comment by faho** [comment] 2019-07-31 07:17
Duplicate of #4943

**Comment by faho** [comment] 2019-07-31 07:17
Yup, that's it. Thanks!

**Closed by faho** 2019-07-31 07:17 UTC
Labels: bug
