### ISSUE TITLE
Piping a command which prompts for input hangs indefinitely

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#2377] opened 2015-09-10 22:30 UTC
```
$ sudo ls | grep test
  # wait a few seconds
  # ctrl+z to background
'sudo ls | grep test' has stopped
$ fg
Send job 1, 'sudo ls | grep test' to foreground
Password:
```

So it appears that `stdin` is somehow being swallowed until I bg/fg the process.

Note I'm using the `HEAD` version on OS X 10.11 - not sure if it works on 2.2 stable.

**Comment by zanchey** [comment] 2015-09-11 01:35
It's broken on 2.2 as well, but works OK in 2.1.1, so I'm going to mark this as a regression.

**Comment by zanchey** [comment] 2015-09-11 01:41
Actually, I think this might be because of the `grep` function - see #206, #1273 etc.

`sudo ls | command grep test` works fine for me, so I'm going to close this as a duplicate of #206 for now.

**Closed by zanchey** 2015-09-11 01:41 UTC
Labels: duplicate
