### ISSUE TITLE
$version special variable is not documented

### ISSUE THREAD

**Issue by kopischke** [fish-shell/fish-shell#3072] opened 2016-05-26 12:30 UTC
Fish 2.3 publishes ist own version in the special variable `$version`, but finding this out is left as an exercise to the user.

### Reproduction Steps:

1. `echo $version` → 2.3
2. `set --local version 1.2` → “set: Tried to set the special variable 'version' with the wrong scope” 
3. `help`, go to “Special variables” section in the [Shell variables documentation](file:///usr/local/Cellar/fish/2.3.0/share/doc/fish/index.html#variables)

### Expected behavior:

`version` is listed among the special variables

### Observed behavior:

`version` is not mentioned anywhere

---
- Fish version: 2.3
- Operating system: OS X 10.11.4, Homebrew installed via `brew install fish --devel`
- Terminal or terminal emulator: Terminal.app

**Comment by faho** [comment] 2016-05-26 12:34
We also have `$FISH_VERSION`, which seems like the better variable.

I'd like it if we ditched one of them, preferring to keep $FISH_VERSION. That could then be documented.

**Comment by kopischke** [comment] 2016-05-26 13:24
I agree: `$version` is too generic to be useful.

**Comment by floam** [comment] 2016-08-26 03:55
> I agree: $version is too generic to be useful.

Like - there might be confusion as to what it's for? I think most people will assume it's he version of fish running with it being unprefixed global, and easily discoverable in ways `fish --version` or `fish $status` both are. 

I think we should add it back because $FISH_VERSION is something that was added more recently and doesn't work on all versions of fish. It was only removed here on git after the last release so we can still save it - if any one else cares!

We could perhaps make one of the specials put the work "fish" in the output before the version number.

**Comment by floam** [comment] 2016-08-26 03:59
We could perhaps make one of the specials put the word "fish" in the output before the version number. I'd have preferred to keep only `$version` and toss the other - but now it's bene around for years and documented -- at this point I think we should keep them both and try to let them "complement" each other.

**Comment by krader1961** [comment] 2016-08-26 04:30
Since `$version` was apparently not documented I'm not particularly worried about people who discovered its existence. You say it's "been around for years and even documented". Where did you find it documented?

Is there any reason to think there are scripts in widespread use that check `$version` which will be broken by the change in question? And if there is we definitely do not want to prefix the output with "fish".  So I'm confused why we need to retain the old name if you think we can safely change the output.

It's also a constant and therefore should have been in all uppercase to begin with. We also have a guideline that fish specific variables and functions should be prefixed with "fish_" (if public) and "__fish_" (if private but global) to avoid name conflicts.

**Comment by floam** [comment] 2016-08-26 04:52
> It's also a constant and therefore should have been in all uppercase

Nonsense. Internally, I think you're just as likely to see likely to see `kHungarianKonstants` internally in fish, is a fact. But here we're talking about the user interface to access something (the version number) that might be backed by a constant. This knowledge that there's a constant here does us no do good except for in moments of ad-hoc reasoning after the fact, or when changing arguments to be `fish --FISH_VERSION`.


>  Where did you find it documented?

I was referring to 'FISH_VERSION'  - it being the latecomer I'd be inclined to remove it - but it's been around since 2012, and has even bene documented. So I think it should stay as intended by @zanchey when he committed it in 2012 to "complement" $version.

**Comment by floam** [comment] 2016-08-26 04:54
> So I'm confused why we need to retain the old name if you think we can safely change the output.

This is going to be accessed by humans more than scripts, I think, and I like people more.

**Comment by krader1961** [comment] 2016-08-26 05:06
It doesn't matter that you "like people more" than scripts. The question, as you correctly pointed out with respect to the `function --shadow-builtin` flag, is whether this change will break scripts. You and I both seem to think the answer is "no". So why keep `$version`? How often does a human type `echo $version`? Essentially never unless asked to by someone who is helping them debug a problem. And I'm willing to bet that if we conducted a poll or did an experiment most users would type `fish -V` or `fish --version` rather than `echo $version`. But that's irrelevant.

> it being the latecomer I'd be inclined to remove it - but it's been around since 2012, and has even bene documented.

And yet you still argue for reinstating `$version`. Which leaves me scratching my head in confusion.

> or when changing arguments to be `fish --FISH_VERSION`

Please step away from your keyboard and think about what you're responding to before you write a comment. I did not propose we introduce ` --FISH_VERSION` flag. Nor could that be inferred from what I wrote. I was pointing out that the version variable is quite literally a constant as evidenced by the error the O.P. saw when they attempted to assign to it. The guideline, that we admittedly violate frequently, is that variables which are constants should be in all uppercase.

**Comment by floam** [comment] 2016-08-26 05:18
It might as well have been documented.  You can't miss it.

A global variable with a short name like "version", with our completions, and various utilities existing - has made it self-announcing - it's *right there*! Has been for a long time. 

It's an aspect of the the interactive personality of fish. 

I'm surprised anyone bothered to go search for it in the docs recently or was surprised enough by something about it such that it had to be "dealt with".

I've been using fish for well over 10 years - I guess I sent [my first stab at a patch in 9 years ago](https://sourceforge.net/p/fish/mailman/message/8336158/). I've experienced learning certain details about fish and then forgetting them, only to ... (over and over again) enough times that I feel like I've at least got a pretty good idea of what it feels like to use fish. 


Anyhow, my spidey sense tell me this change is surer obnoxious and was made in haste. I hope we can put it back; it wasn't really hurting anything.

**Comment by floam** [comment] 2016-08-26 05:22
It's not really a big deal here - but it breaks my workflow ![https://imgs.xkcd.com/comics/workflow.png](https://imgs.xkcd.com/comics/workflow.png)

**Comment by krader1961** [comment] 2016-08-26 05:29
> It's not really a big deal here - but it breaks my workflow

How so? Also, I just ran `man bash` and saw `BASH_VERSION` documented. And `echo $version` in bash gives me an empty line. So if anything @faho's change makes us more consistent with bash which is something that many users consider a "good thing".

**Comment by floam** [comment] 2016-08-26 09:06
Sure, but look at the rest of BASH_*:
<img width="481" alt="screenshot 2016-08-26 at 2 03 19 am" src="https://cloud.githubusercontent.com/assets/291142/18000114/601f90e8-6b31-11e6-924b-b899efbd189e.png">
Where we have any matching features exposed in fish I think you'll find the variable name we use follows line with `$argv, $argc, $status, $version.`

**Comment by floam** [comment] 2016-08-26 09:08
TCSH is a much better role model here:

```
[aaronbook:~] floam% set
_	set e

addsuffix	
anyerror	
argv	()
csubstnonl	
cwd	/Users/floam
dirstack	/Users/floam
e	
echo_style	bsd
edit	
euid	502
euser	floam
gid	20
group	staff
history	100
home	/Users/floam
killring	30
owd	
path	(/usr/local/bin /usr/local/sbin /usr/local/opt/fzf/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /usr/local/opt/ccache/libexec /Applications/Server.app/Contents/ServerRoot/usr/bin /Applications/Server.app/Contents/ServerRoot/usr/sbin /Users/floam/go/bin /usr/local/MacGPG2/bin /Library/TeX/texbin)
prompt	[%m:%c3] %n%# 
prompt2	%R? 
prompt3	CORRECT>%R (y|n|e|a)? 
promptchars	%#
shell	/bin/tcsh
shlvl	2
status	0
tcsh	6.18.01
term	nsterm
tty	ttys009
uid	502
user	floam
version	tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-apple-darwin) options wide,nls,dl,bye,al,kan,sm,rh,color,filec
[aaronbook:~] floam% 

```

**Comment by faho** [comment] 2016-08-26 09:37
@floam: I'm strongly opposed to reintroducing this.

The name is so generic that it _was actually used_ for something by a user on accident. Granted, that could also happen to $status or $argv, but those are much more important and likely to be noticed. What $version does can be had at least two other ways.

>I think we should add it back because $FISH_VERSION is something that was added more recently and doesn't work on all versions of fish.

Which version was it added? Anyway, I'm quite certain we no longer support versions without it and that a script is unlikely to work with both current fish and those old versions. Am I wrong?

If not, it would be purely for interactive use, and in that case you can adjust - type `echo $FISH_VERSION`, see that it doesn't work, use `fish --version` or `echo $version` and know the fish version. Using those old versions is only for archaeology anyway.

**Comment by floam** [comment] 2016-08-26 22:01
$FISH_VERSION was added in some 2.x.

> Anyway, I'm quite certain we no longer support versions without it and that a script is unlikely to work with both current fish and those old versions. Am I wrong?

Not really, but it's so broken that I can't be the only guy on the plane that relied on $version to keep things separated a bit. I can't load up my fish 1.23.0 any more without dead everything.

Basically, I just guarded stuff in my personal files such that ancient fish would pick different directories than modern fish. I used to have it working so that I could load up fish 1.x to try it out in ~ without any spewing errors or extreme brokenness, when wanting to compare behavior. 

Plenty of functions can work in either version of fish. I used to share this prompt that'd show me fish version in tab title.

```fish
function fish_prompt
	echo -n \e]1\;
	echo $_  $argv $version [$status]\a
	tput setaf 3
	echo -n $PWD
	tput sgr0
	echo -n ' > '
end
```

**Comment by floam** [comment] 2016-08-26 22:05
Anyhow, fine. I give in!

**Closed** 2016-08-26 22:12 UTC
Labels: easy-pick, enhancement, needs-docs, release-notes

**Comment by floam** [comment] 2016-09-09 03:10
It seems like we started down this path with CMD_DURATION. What was the thinking at the time when that got added in? Until then we pretty much were being csh-like with lower-cased special variables for fish, unless they need to be exported.

**Comment by zanchey** [comment] 2016-10-02 10:49
Indeed, the [message from Axel in 2006 suggests that fish was following the lower-cased variables idea](https://sourceforge.net/p/fish/mailman/message/6609480/).

I think what happened with `CMD_DURATION` is that it was originally exported (7a8b7201a1881) but then became unexported (b31305b9)

**Comment by floam** [comment] 2016-10-02 11:10
If I had a veto card, I'd put this back. What I did instead was initialize $version via the init scripts: https://github.com/fish-shell/fish-shell/blob/master/share/config.fish#L16

**Comment by floam** [comment] 2016-10-02 11:13
I see that didn't go in as a seperate commit like I planned. Whoops.

**Comment by krader1961** [comment] 2016-10-02 14:59
From the message thread @zanchey linked to above:

> Also, I noticed that csh uses the name $version, so to keep compatibility with at least one shell class, that might be a better choice.

Given how despised csh was for writing shell scripts (google "csh harmful") emulating it isn't a compelling argument. If being compatible with a "shell class" is useful it should be the Bourne shell from which bash, ash, zsh, etc. are all descended.

**Comment by floam** [comment] 2016-10-02 18:28
I've read the "csh considered harmful" document by the Perl developer. I'm not convinced by much here.

Fish takes a lot of cues from csh and (IMO) a lot of our design choices might be said to take place with a "bourne shell scripting considered harmful" perspective.

**Comment by floam** [comment] 2016-10-02 18:29
Here that is, by the way:

http://www.perl.com/doc/FMTEYEWTK/versus/csh.whynot
