### ISSUE TITLE
Alias causes unspecified syntax checking errors

### ISSUE THREAD

**Issue by xiamaz** [fish-shell/fish-shell#4945] opened 2018-04-26 10:14 UTC
I am using version 2.7.1.

Running `fish -n` on the following example will result in an unspecified error.

```
alias test 'echo'
```

**Comment by faho** [comment] 2018-05-13 19:36
Duplicate of #977 - `alias` is a function, and `fish -n` does not load functions.

**Closed by faho** 2018-05-13 19:36 UTC
Labels: bug
