### ISSUE TITLE
Completion creates stopped R jobs on Cygwin

### ISSUE THREAD

**Issue by majaha** [fish-shell/fish-shell#2281] opened 2015-08-08 08:14 UTC
When using fish's completion feature, I often get lots of stopped R (the statistics language) jobs which have to be SIGKILLed. This is on 64 bit Cygwin on Windows 7 with fish 2.1.1 from the cygwin installer. The following transcript is pretty self explanatory.
```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
Matt@Matts-Laptop ~> jobs
jobs: There are no jobs
Matt@Matts-Laptop ~> ec[*TAB*]
```
A not-insubstantial pause...
```
echo       (Print arguments)  ecosystem.core.dll     (Executable, 423kB)
echo.exe  (Executable, 26kB)  ecosystem.windows.dll  (Executable, 484kB)
Matt@Matts-Laptop ~> jobs
Job     Group   CPU     State   Command
4       9904    0%      stopped R
3       5100    0%      stopped R
2       5796    0%      stopped R
1       1392    0%      stopped R
Matt@Matts-Laptop ~> ps
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
S    5796    2480    5796       9588  pty0        1001 09:12:27 /usr/lib/R/bin/exec/R
S    5100    2480    5100       4716  pty0        1001 09:12:27 /usr/lib/R/bin/exec/R
S    9904    2480    9904       8320  pty0        1001 09:12:27 /usr/lib/R/bin/exec/R
S    1392    2480    1392       9736  pty0        1001 09:12:26 /usr/lib/R/bin/exec/R
     5212    2480    5212       9584  pty0        1001 09:12:33 /usr/bin/ps
     2480    1316    2480       4232  pty0        1001 09:12:20 /usr/bin/fish
     1316       1    1316       1316  ?           1001 09:12:20 /usr/bin/mintty
     4196       1    4196       4196  ?           1001 09:12:22 /usr/bin/fishd
Matt@Matts-Laptop ~>
```

**Comment by faho** [comment] 2015-08-08 13:32
Can you try with fish 2.2.0?

**Comment by majaha** [comment] 2015-08-08 13:40
There doesn't seem to be a 2.2.0 in the cygwin installer, should I be trying to build from source? And might there be cygwin-specific patches in the cygwin installer version that we should be aware of?

**Comment by faho** [comment] 2015-08-08 14:02
>should I be trying to build from source?

That'd be great.

>And might there be cygwin-specific patches in the cygwin installer version that we should be aware of?

Sorry, I'm not familiar with cygwin so I don't know where they keep their build scripts, so I can't check. Cursory googling has yielded [Cygwin Package Search](https://cygwin.com/cgi-bin2/package-grep.cgi?grep=fish&arch=x86), which _finds_ fish, but clicking it only gets you a list of files without an obvious way of getting them.

**Comment by majaha** [comment] 2015-08-08 16:24
I just built and tested the github 2.2.0 version, and after applying the work-around for #952, the problem still persists.

However, it occurred to me that this is is very closely related to part 6 of #1887, and indeed #952.
The problem seems to be caused by the paths:
```
/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL
/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT
/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL
/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT
```
which are all on the PATH.

It would appear this bug is in fact a sub-bug of #952, caused by paths with parenthesis in them not being properly escaped or something. It can be worked around in a similar way:

    function R
        echo "(R)"
    end

**Comment by faho** [comment] 2015-08-08 17:26
It's actually a duplicate of #952 - the bug is that fish tries to run part of a directories name as command substitution, only in your case it succeeds because you have R installed.

Thank you for your investigation.

(Also, I hate that (R) and (tm) stuff)

**Closed by faho** 2015-08-08 17:26 UTC

**Comment by majaha** [comment] 2015-08-08 18:20
Yeah, that's what I was trying to say :)
It would be great if that bug were fixed!

**Comment by andrex-e-schulman** [comment] 2015-08-11 19:50
For PATHs that include the strings '(x86)' or '(X86)', a workaround is already present in the Cygwin-specific /etc/fish/config.fish:

    # Work around an autocompletion bug, where fish tries to execute the x86
    # function if it sees a PATH component like '/cygdrive/c/Program Files (x86)'.
    # See https://github.com/fish-shell/fish-shell/issues/952#issuecomment-27499216 .

    function x86 --description "print '(x86)'"
        echo '(x86)'
    end
    function X86 --description "print '(X86)'"
        echo '(X86)'
    end

For fish 2.1.1, I'll add a similar definition for the R function and make a new point release.  That should fix this issue.  I'll also include it in fish 2.2 when that's ready in Cygwin.
