### ISSUE TITLE
"set_color: Expected an argument" appearing each time Fish loads

### ISSUE THREAD

**Issue by AndrewHynes** [fish-shell/fish-shell#1335] opened 2014-03-10 18:31 UTC
Hi, I've used Fish on my system since I installed it, but for some reason I keep getting an error message when Fish loads (via tty or from a terminal emulator within X).

"set_color: Expected an argument"
Appears, and the colours are different from what they used to be - e.g. the completions are white, rather than green, now.

I haven't changed anything in particular, and it was working last time my laptop was on, though the time before that, I updated Fish to the latest version available on my system, 2.1.

The version is the latest -
andrew@haru ~> fish --version
fish, version 2.1.0

You can see my config.fish here - I do not attempt to use set_color, and it hasn't been changed since when it /was/ working.

https://github.com/AndrewHynes/dotfiles/blob/master/config.fish

I run Arch Linux.

Thanks.

**Comment by CaioAlonso** [comment] 2015-01-24 12:06
I am having this issue with fish `2.1.1` on an Arch Linux system.

Re-running `fish_config` and choosing any prompt does not solve the problem. @cjxgm's hack did not work either.

Opening `functions/fish_prompt.fish` and commenting out the part that says:
```
if not set -q __fish_prompt_cwd
    set -g __fish_prompt_cwd (set_color $fish_color_cwd)
end
```
suppresses the error message, but probably some color definition will stay broken.

**Comment by pwr22** [comment] 2015-01-24 15:44
What was the exact error you got? It looks like you probably need to set
fish_color_cwd to something

Peter

**Comment by CaioAlonso** [comment] 2015-01-26 13:08
@pwr22 the exact error is:
```
set_color: Expected an argument
```
Yes, that was the case, my fish_color_cwd was unset and after setting it the problem was solved. The thing is, I hadn't messed with my fish config in months and I have no idea why this happened.

**Comment by JamesMcMahon** [comment] 2015-02-02 14:34
Having the same issue.

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
set_color: Expected an argument
set_color: Expected an argument
```

It happened for me when I did a clone from one Macbook to another, though that most likely is just coincidence.

**Comment by mirco** [comment] 2015-02-26 00:22
Same issue for me. It keeps reoccuring every other reboot or so. For no reason obvious to me fish_color_user and fish_color_host don't get set anymore and I have to reselect the 'Classic + Git' prompt to fix it.

**Comment by zanchey** [comment] 2015-02-27 08:49
My suspicion is that your MAC address or other system identifier is changing, leading `fishd` to create new universal variable stores. Do you have any other universal variables set? Do they persist across the reboots?

**Comment by mirco** [comment] 2015-02-28 16:00
No they do not persist (I did 'set -e -U fish_greeting' and now it is set to the default value again).

MAC address doesn't change on reboot. This is just a normal laptop with wifi and ethernet. What other mechanisms does fish use as system identifier?

**Comment by gdelugre** [comment] 2015-03-01 15:40
Same problem here.

My config is fish ``2.1.2`` on ArchLinux.
The strange thing is that it's not happening all the time, but pretty often across reboots.

**Comment by zanchey** [comment] 2015-03-05 00:35
Could you post the contents of `ls -l ~/.config/fish/` when this happens?

**Comment by mirco** [comment] 2015-03-15 23:13
```bash
$ ls -l .config/fish
total 564
-rw-r--r-- 1 mirco mirco 551972 Mar 16 00:02 fish_history
-rw-r--r-- 1 mirco mirco  18178 Mar 14 20:36 fish_read_history
-rw------- 1 mirco mirco   1157 Mar 16 00:01 fishd.frangipani
drwx------ 1 mirco mirco    288 Mar 14 20:31 functions
```
where frangipani is my hostname

By the way, why don't you use the content of /etc/machine-id if it exists (it does on most modern linux distributions)? It was created exactly for the purpose of uniquely identifying a machine and is stable for the lifetime of the installation unless manually changed and independent from hardware changes.
See http://www.freedesktop.org/software/systemd/man/machine-id.html for more info

**Comment by pwr22** [comment] 2015-03-19 19:08
Never heard of that before but I'm +1 for that too

**Comment by zanchey** [comment] 2015-03-20 05:58
OK, it doesn't look like your hostname is changing, so that's that idea out.

The reason fish doesn't use the machine-id, I suspect, is that it's relatively new. It would be good to use that on systems where it's available, although the migration path might be a bit interesting.

Has anyone been able to reproduce this with a recent HEAD/master build?

**Comment by pwr22** [comment] 2015-03-20 06:38
I used to have this issue back on the very old release in the ubuntu repos. Nothing like this since later versions though and for me the fishd files were all based on my MAC last I checked

**Comment by smokku** [comment] 2015-05-22 14:07
Here's how I just fixed it:

    $ function set_default; set -U -- $argv; end
    $ grep 'set_default' /usr/share/fish/functions/__fish_config_interactive.fish | grep -v function | source

**Comment by mirco** [comment] 2015-05-24 15:44
I've installed a git build now for a couple of months and the issue hasn't come up since, so it seems to be resolved in the next release. The release it occured on was 2.1.2.

**Comment by zanchey** [comment] 2015-05-28 09:15
> We can leave this open to track actually repairing cases of unset colors.

I think it would be a good idea to have a `fish_reset` function to reset e.g. colors, but as the proximate issue is solved I'm going to bump this out of the 2.2.0 milestone.

**Comment by dolohow** [comment] 2015-06-30 09:58
I have the same issue, after unexpected restart when something is going on in a console under fish I have
```shell
set_color: Expected an argument
```
and I need to manually chose prompt again in `fish_config`, because it's different.

**Comment by krader1961** [comment] 2015-12-31 03:27
@AndrewHynes I'd like to propose closing this issue and continuing the discussion in issue #1912. Normally I would propose the inverse (closing the newer issue as a duplicate of the older one) but in this case I think the newer issue more clearly captures the core problem.

**Comment by faho** [comment] 2016-03-06 13:59
Closing as duplicate.

**Closed by faho** 2016-03-06 13:59 UTC

**Comment by dolohow** [comment] 2016-03-06 16:06
For the record with new version of fish shell the issue no longer happens on my machines.
