### ISSUE TITLE
Git completions on bare repo hangs

### ISSUE THREAD

**Issue by Susensio** [fish-shell/fish-shell#8815] opened 2022-03-18 09:05 UTC
Environment

fish, version 3.4.0
Linux nuc 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
xterm-256color

When in a bare git repo, completions hangs and I have to control+c to regain access to fish shell.

[![asciicast](https://asciinema.org/a/477944.svg)](https://asciinema.org/a/477944)

**Comment by faho** [comment] 2022-03-18 09:12
Duplicate of #8592

**Closed by faho** 2022-03-18 09:12 UTC

**Comment by faho** [comment] 2022-03-18 09:13
There's nothing we can really do here. We try to complete your files, unfortunately the directory you have given us is YOUR ENTIRE HOME DIRECTORY.

Git doesn't give us a great way to handle this case, so the guidance we can give you is "don't do that" or "ignore most files".

**Comment by Susensio** [comment] 2022-03-18 13:36
@faho 
Maybe this issue could de rescued? #8040
I understand the arguments you provided back then. If git add works on ALL FILES relative to $HOME, then it makes sense that autocompletion suggest all possible working combinations.
But, given that showUntracked in that bare repo means that I only care about tracked files, and given that the current implementation takes so much time to compute (in some cases, such like this one) that virtually returns no suggestions at all... Wouldn't it be more useful that `git add` completes with only tracked files, instead of no completion at all for several minutes?
I understand that you regard this as an edge case, but I think a lot of users versioncontrol their dotfiles with a git bare repo working from home.

**Comment by faho** [comment] 2022-03-18 13:47
>Wouldn't it be more useful that git add completes with only tracked files, instead of no completion at all for several minutes?

No, it wouldn't, because this isn't the *prompt*.

We *can't* not offer untracked files here, because having new files is a normal thing. We don't have a way of detecting that this is a super gigantic repo with 99% untracked-on-purpose files.

It's like I said: We can't really do anything here. Git doesn't really give us any options here.

What you can do is like I said: Ignore most files/directories.

**Comment by Susensio** [comment] 2022-03-18 14:38
I have just tested this in an old laptop, running fish 3.1.2, and it is working better. It gives suggestions and not hangs.
