### ISSUE TITLE
Control "$PATH entry is not valid" warnings

### ISSUE THREAD

**Issue by rnhmjoj** [fish-shell/fish-shell#4197] opened 2017-07-07 11:33 UTC
On NixOS there is an initial systemd-wide environment containing nix-specific variables, user defined aliases and variables, etc. Among these the PATH variable is populated with many directories some of which may or may not exist depending on the specific user so fish ends up producing a lot of these warning that may confuse some. Like:
```
set: Warning: $PATH entry "/home/$USER/bin" is not valid (No such file or directory)
set: Warning: $PATH entry "/etc/per-user-pkgs/$USER/bin" is not valid (No such file or directory)
set: Warning: $PATH entry "/home/$USER/.nix-profile/bin" is not valid (No such file or directory)
set: Warning: $PATH entry "/nix/var/nix/profiles/default/bin" is not valid (No such file or directory)
```
Is there any way to silence the warnings?

---
fish version: 2.6.0

**Comment by faho** [comment] 2017-07-07 11:52
Currently, there is no way to silence these warnings, so you need to not trigger them:

```fish
test -d "$component"; and set PATH $PATH $component
```

This would presumably need to be done by the nix folks - @therealpxc?

Note: I'm assuming that you've censored your username here. If this actually says `$USER` in the output that's probably a bug.

I'm not sure if we should remove these warnings. Any arguments for or against?

**Comment by rnhmjoj** [comment] 2017-07-07 12:15
> Note: I'm assuming that you've censored your username here

Yes yes, I did. It was reported here by the way: https://github.com/NixOS/nixpkgs/issues/27195

**Comment by krader1961** [comment] 2017-07-07 13:48
Closing since the problem is with the nix distro and we don't want this to be configurable behavior.

**Closed by krader1961** 2017-07-07 13:48 UTC
Labels: question

**Comment by therealpxc** [comment] 2017-07-08 17:20
I'm not necessarily looking for this ticket to be reopened, but I'd like to provide some motivation to explain where this is coming from from the Nix side. We intentionally add non-existent directories to the PATH on NixOS and Nix because they are the paths our package manager will install binaries to (they only appear when they have contents) and we want them to be picked up on the PATH and usable as soon as installation takes place, not only when a new shell logs in.

Because other shells don't warn for this, fish output for certain scripts becomes noisier than on other shells. In particular, when using `set` inside of the fish-foreign-env plugin (which provides a `fenv` function which runs commands in `bash`, monitors environment changes, and then reproduces them in fish), we get much noisier output than one would just running the same scripts in, say, `bash`.

Since these warnings in particular don't indicate that fish has decided not to obey the directive set out for it by the `set` command invocation, they seem in principle harmless to suppress. The ability to do so cleanly would be nice for certain scripts, including those that attempt to interface with scripts written for POSIX shells like `fenv`, and especially nice when we want suppressing this warning to be *fast*, such as during shell initialization (which is where we use it in NixOS).

We've worked around it and shell initialization seems to have remained quick enough, so if you feel that the change is inappropriate for `fish` that's no problem for us. But this is the story of why one might want to add non-existent paths to the PATH.

**Comment by krader1961** [comment] 2017-07-08 17:36
Not sure what solution you came up with but why not just redirect stderr?

```
> set PATH $PATH /jkl
set: Warning: $PATH entry "/jkl" is not valid (No such file or directory)
> set PATH $PATH /jkl ^/dev/null
> echo $PATH
/Users/krader/symlinks /Users/krader/bin /Users/krader/sbin /usr/local/bin /usr/local/sbin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/findutils/bin /usr/local/go/bin /usr/bin /usr/sbin /bin /sbin /opt/X11/bin /jkl /jkl
```

**Comment by therealpxc** [comment] 2017-07-08 17:53
We ended up doing something like that, patching the foreign-env plugin to do it. I also wrote up a solution that filtered the stderr output of `fenv` using the `string` builtin for exactly the messages we wanted to suppress, which worked just as well.

There was some concern about potentially suppressing additional warnings, besides the ones we wanted. Our choices were essentially 'filter the final output of `fenv` for exactly the messages we knew we could ignore' and 'add conditionals inside the fish-foreign-env package to see if the variable being set is PATH and then redirect stderr to /dev/null'. We went with the latter, for now at least.

Part of the issue is that we only generate POSIX scripts for setting up the environment, including our PATH variable. If we were not trying to get those to be usable from fish but instead created some for fish, directly adding those redirects exactly where we needed them as you suggest would have been more natural.
