### ISSUE TITLE
Environment variables set on session start

### ISSUE THREAD

**Issue by squidink7** [fish-shell/fish-shell#7485] opened 2020-11-17 05:58 UTC
I'm using Manjaro KDE Plasma and all my flatpak applications have gone missing, when I try to launch them from the command line it gives this warning: 
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/squidink7/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

I made a bug report on KDE's bug tracker and they told me it was an issue with fish. I tried chshing to bash and sure enough the issue was fixed. It seems there is a problem with those variables being set when the session starts, is there a way to make sure these variables always get applied?

I'm running fish version 3.1.2

**Comment by faho** [comment] 2020-11-17 14:59
What happens here is this:

- Flatpak sets $XDG_DATA_DIRS in /etc/profile.d/flatpak.sh (and on arch also $PATH via flatpak-bindir.sh)
- KDE starts the session with $SHELL, which is the user's shell
- If $SHELL is fish, that won't read /etc/profile.d because those are POSIX shell scripts and fish is incompatible (on purpose).

So there's not much for fish to do and it's not a bug in flatpak or KDE, more of an awkward design.

Ideally a shell wouldn't have anything to do with setting system settings like these, or if it did it would be the shell the script was written for ($SHELL is rarely the right thing to use).

You have a few workarounds available, the least odious of which is probably just to stick these lines into config.fish and be done with it:

```fish
set -gx --path XDG_DATA_DIRS $XDG_DATA_HOME/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

for flatpakdir in ~/.local/share/flatpak/exports/bin /var/lib/flatpak/exports/bin
    if test -d $flatpakdir
        contains $flatpakdir $PATH; or set -a PATH $flatpakdir
    end
end
```

These paths are unlikely to change, so just hardcoding them here is probably okay, and everything else is more annoying.

**Comment by faho** [comment] 2020-11-27 14:39
Closing because the question has been answered. Unfortunately there's nothing really for us to do here.

**Closed** 2020-11-27 14:38 UTC
Labels: question

**Comment by RafalSkolasinski** [comment] 2020-12-06 21:31
Thank you @faho for the fix above, it saved my day!

**Comment by ThisNekoGuy** [comment] 2021-03-15 21:29
@faho 
For future reference, since I supposedly found the wrong issue [here](https://github.com/fish-shell/fish-shell/issues/7816#issuecomment-799385915), would using the example above be correct to apply to other profile.d scripts that are ignored at startup in `config.fish`?

```fish
## Export triple buffer v-sync to kwin to help avoid Nvidia screen-tearing
# Not sure if this is written correctly...
set -gx KWIN_TRIPLE_BUFFER 1
 
## For setting Flutter paths                
set -gx flutter_home $FLUTTER_HOME /opt/flutter
set -gx --path flutter_home[1]/bin  

## Setting CUDA paths                     
set -gx cuda_path $CUDA_PATH /opt/cuda
set -gx --path $cuda_path[1]/bin:$cuda_path[1]/integration/nsight-compute:$cuda_path[1]/integration/nsight-systems

## Set Mozilla-common path 
set -gx --path MOZ_PLUGIN_PATH /usr/lib/mozilla/plugins
```

**Comment by faho** [comment] 2021-03-19 13:47
@ThisNekoGuy That's not how "--path" works.

It tells fish that a variable is a "path variable", which means that it works like $PATH and similar - there are multiple elements with a ":" between them, so fish splits it up and adds the ":" back when exporting.

I'm not sure what this is supposed to do:

```fish
set -gx --path flutter_home[1]/bin  
```

I'm imaginining that maybe you want to add these things to $PATH, in which case you can either manipulate $PATH (`set PATH $flutter_home[1]/bin $PATH`) or use our `fish_add_path` helper function (added in fish 3.2.0) that will only add them if they aren't already included:

```fish
fish_add_path $flutter_home[1]/bin $cuda_path[1]/bin $cuda_path[1]/integration/nsight-compute $cuda_path[1]/integration/nsight-systems
```

**Comment by brunorafaelng** [comment] 2022-03-28 21:02
> O que acontece aqui é isso:
> 
>     * Flatpak define $XDG_DATA_DIRS em /etc/profile.d/flatpak.sh (e no arch também $PATH via flatpak-bindir.sh)
> 
>     * O KDE inicia a sessão com $SHELL, que é o shell do usuário
> 
>     * Se $SHELL for fish, isso não lerá /etc/profile.d porque esses são scripts de shell POSIX e fish é incompatível (de propósito).
> 
> 
> Portanto, não há muito para os peixes fazerem e não é um bug no flatpak ou no KDE, é mais um design estranho.
> 
> Idealmente, um shell não teria nada a ver com definir configurações do sistema como essas, ou se tivesse, seria o shell para o qual o script foi escrito ($SHELL raramente é a coisa certa a usar).
> 
> Você tem algumas soluções disponíveis, a menos odiosa das quais provavelmente é apenas colocar essas linhas no config.fish e terminar com isso:
> 
> ```fish
> set  -l xdg_data_home $XDG_DATA_HOME ~/.local/share 
>  set  -gx  --path XDG_DATA_DIRS $xdg_data_home [1]/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share 
> 
>  para flatpakdir em ~/.local/share/flatpak/exports/bin /var/lib/flatpak/exports/bin 
>      se  test  -d  $flatpakdir 
>         contém  $flatpakdir  $PATH ; ou  defina  -a PATH $ flatpakdir 
>     end 
> end 
> ```
> 
> É improvável que esses caminhos mudem, então apenas codificá-los aqui provavelmente está bem, e todo o resto é mais irritante.

Too top bro!! rocked it! Hahaha
