### ISSUE TITLE
echo redirect to procfs is not working

### ISSUE THREAD

**Issue by Enter-tainer** [fish-shell/fish-shell#7939] opened 2021-04-19 03:46 UTC
## version
```
fish, version 3.2.1
Linux mgt-arch 5.11.15-zen1-2-zen #1 ZEN SMP PREEMPT Sat, 17 Apr 2021 00:22:34 +0000 x86_64 GNU/Linux
```

## reproduction

```
root@mgt-arch /h/mgt# echo 512 > /proc/sys/vm/nr_hugepages
root@mgt-arch /h/mgt# cat /proc/sys/vm/nr_hugepages
5
```

expected behavior: `cat /proc/sys/vm/nr_hugepages` should output `512`, but instead, it gives me a single `5`. I've also tried to write 512 to a file, then `cat file > /proc/sys/vm/nr_hugepages`, and that works. So maybe this bug is related to echo

Running the same script on bash will give me the correct result. I'm not really familar with fish-specific feature. So if it is intended, can someone tell me how to do the same thing in fish shell?

**Comment by faho** [comment] 2021-04-19 05:02
Duplicate of #7836

**Closed by faho** 2021-04-19 05:02 UTC

**Comment by faho** [comment] 2021-04-19 06:18
Fixed in the next release, use `command echo` as a workaround.
