### ISSUE TITLE
fish_git_prompt performance

### ISSUE THREAD

**Issue by Rapiz1** [fish-shell/fish-shell#7705] opened 2021-02-10 09:14 UTC
I found it sometimes slow to display the prompt in a super large git repo, which is in my case, the Linux kernel. Then I simply turned off the fish_git_prompt. It became quick again. I wonder is there any plan to improve [fish_git_prompt](https://fishshell.com/docs/current/cmds/fish_git_prompt.html) performance? I don't know what I can do, but I'm glad to help.

**Comment by faho** [comment] 2021-02-10 09:36
This is basically always down to doing something that forces git to check all the files. The worst offender is the informative status, so set

$__fish_git_prompt_show_informative_status

to 0.

The rest is a duplicate of #6764.

**Closed by faho** 2021-02-10 09:36 UTC
