### ISSUE TITLE
Fish hangs after Ctrl-C

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#3645] opened 2016-12-13 20:59 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version unknown
it is 2.4.0 with Haiku specific patches, not in mainline yet.
Current recipe: https://github.com/haikuports/haikuports/pull/928
Patchset: https://github.com/miqlas/haikuports/blob/b34ed504a7925d53e4be384ecad3b235fbb9d0e4/app-shells/fish/patches/fish-2.4.0.patchset

**OS/terminal used**: 
Haiku hrev 50762 x86_64, Terminal

Talk about the the issue here. 
BTW, the problem can lie in Haiku or in the supporting libs too.

## Reproduction steps
1) write characters into your Terminal
2) press Ctrl-C
3) Repeat
....
5) Profit! Fish hangs after Ctrl-C and aren't accept any input anymore, so you need to kill it. I never had any problems like this with the 2.3.x releases. (if i remember correctly.)

![fish_debug_1](https://cloud.githubusercontent.com/assets/5569059/21158994/b824d1dc-c17f-11e6-871d-a60372921889.png)
![fish_debug_2](https://cloud.githubusercontent.com/assets/5569059/21159009/c0ba6abe-c17f-11e6-8b5f-17e45c10bdef.png)

You wanted to have it.... Hop it helps. Let me know if you need other info.

## Results
```console
~ $ math 2 + 2
4
```

**Comment by krader1961** [comment] 2016-12-13 23:23
Your systems `execve()` function is mallocing memory. Because that is being done on the child side of a `fork()` call it can hang. Although I can't recall the last time I've seen that happen as it's more of a theoretical than practical concern. Nonetheless, the backtrace you provided shows clearly that is what is happening. A starting point is figuring out what your systems  `__flatten_process_args()` function is doing and why it needs to malloc memory. Perhaps that can be avoided by using an alternative to `execve()`. Or possibly we can avoid the malloc deadlock by restructuring the fish code. We might gain more insight if you run it as `fish -d5` before executing the steps that result in the hang.

**Comment by krader1961** [comment] 2016-12-13 23:34
To clarify my previous comment vis-a-vis such deadlocks being more theoretical than practical the point is that in a process with a single thread it can't happen. And even in a process with two or more threads it's an improbable race with a different thread starting, but not completing, a `malloc()`, `free()` or related function when the `fork()` is executed.

Is this easy to reproduce, @miqlas? What percentage of the time does a [ctrl-c] produce a hang? Have you made any customizations that might be relevant? For example, using `trap` to change how [ctrl-C] is handled (run `trap -p`)? What does `bind \cC` report and if it isn't bound to `__fish_cancel_commandline` what does the function bound to that key do?

**Comment by ridiculousfish** [comment] 2016-12-14 04:59
Awesome bug report! Thanks!

krader is right that `execve` is allocating memory, and I would tentatively argue that this is a bug in Haiku. In particular POSIX requires that `execve` is async-signal safe, which means it may be called from a signal handler, and thus must not call malloc internally.

**Comment by miqlas** [comment] 2016-12-14 08:11
fish -d5 log : https://gist.github.com/miqlas/9d46cfd39c104c912efb85d5522fa325

**Comment by miqlas** [comment] 2016-12-14 08:12
trap -p returns nothing.

bind \cC returns : bind \cc __fish_cancel_commandline

**Comment by miqlas** [comment] 2016-12-15 06:10
Reply from bonefish: https://dev.haiku-os.org/ticket/13111#comment:3

> Our malloc() implementation is actually async signal safe, by way of ​deferring signal delivery. I suspect the issue in this case is rather that malloc() isn't fork() safe in an multi-threaded program. If one thread calls fork() while another is currently in malloc() (or free(),...) the child process will inherit a locked mutex.
> The solution is to register respective atfork() hooks for the memory allocator. They would acquire the mutex pre-fork() and release it post-fork(), thus ensuring that the child finds the memory allocator in a usable state.

**Comment by krader1961** [comment] 2016-12-15 06:26
The `atfork()` mechanism is inherently broken. It does not fix this issue.

The `execve()` function must not execute any `malloc()` calls since it must, by definition, be deadlock free after a `fork()` call. The person who provided that answer is wrong in their recommendation.

**Comment by miqlas** [comment] 2016-12-15 22:15
korli made 2 patches to get it fixed on Haiku side, sadly we wasn't able to test it with fish, but he wass kind enough to provide the patches, so i should try them and report back to get one of them merged into the mainline. I hope i can find time for the tests dureing the next week.

Will report back. Theoretically we can close this ticket already, because it isn't a fish bug.

**Comment by ridiculousfish** [comment] 2016-12-16 21:00
My understanding is that `atfork` ought to work. The idea is that you acquire the lock before forking, to ensure that no other threads are in the critical section. Then the parent releases the lock, and the child reinitializes it. This ensures that children never inherit that mutex in a locked state. Is there something I'm missing? @krader1961

**Comment by krader1961** [comment] 2016-12-17 00:40
Yes `pthread_atfork()` can work in very limited situations.  But the mechanism is inherently flawed. Having said that the architecture of libc on Haiku may make it a viable solution for this specific problem. I'm simply pointing out that in the general case it isn't sufficient. A bit of googling will turn up plenty of discussions of its shortcomings.

Also, FWIW, the person who said

> Our malloc() implementation is actually async signal safe, by way of ​deferring signal delivery.

does not understand what "async signal safe" means in this context. It does not mean you can safely invoke malloc() because you've blocked signal delivery. In the context of fork() it means you can't invoke any async signal **unsafe** functions on the child side of the fork(). And that includes malloc().

I'm going to close this since there does not appear to be anything fish can do about this. If new information comes to light, @miqlas, that implicates fish feel free to reopen.

**Closed by krader1961** 2016-12-17 00:40 UTC
Labels: needs-more-info

**Comment by ridiculousfish** [comment] 2016-12-17 03:11
Cool. I just want to say thanks to the Haiku developers, you are super-responsive and awesome!

**Comment by miqlas** [comment] 2016-12-17 23:59
korli just psuhed a fix for this bug, i already tested it, i cannot reproduce the hang anymore. Thank you guys!
Change: http://cgit.haiku-os.org/haiku/commit/?id=hrev50771

**Comment by krader1961** [comment] 2016-12-18 00:08
That's fantastic, @miqlas. Please keep opening issues as you run into problems. We definitely want fish to work well on a relatively new OS where we might see a lot of users choose to use it because they're not expecting a bash clone.
