### ISSUE TITLE
`disown` is broken

### ISSUE THREAD

**Issue by raichoo** [fish-shell/fish-shell#6011] opened 2019-07-29 08:49 UTC
I have just moved from 822b53c6 to a33f0eb6 and `disown` apparently broke again. Starting a job in the background spawns a job as expected and `disown` removes it from the list, also just as expected. However, when I close the shell all disowned processes get quit nevertheless.

**Comment by raichoo** [comment] 2019-07-29 14:20
@ridiculousfish Looking at a33f0eb this pretty much seems to be the culprit. Reverting it fixes the issue.

**Comment by ridiculousfish** [comment] 2019-07-30 06:50
Thanks, I'll take a look!

**Comment by ridiculousfish** [comment] 2019-07-30 07:10
@raichoo can you share steps to reproduce?

 I tried the following: in a new shell instance, I ran:

    > sleep 1000 &
    > disown

I closed the instance and then ran `ps`, and verified that `sleep` was still running.

**Comment by raichoo** [comment] 2019-07-30 09:10
I've tried it again, and your example seems to work just fine so I dug a bit deeper. This seems to be related to using `disown` in a script.

I have something like

```
function top
  if set -q DISPLAY
    sakura  -t top --name monitor -e /usr/bin/top -P -t -s 5&
    disown
  else
    /usr/local/bin/cmus
  end
end
```

When doing this the terminal running top quits once I quit the parent shell even though `disown` has been issued. This worked fine before.

**Comment by raichoo** [comment] 2019-07-30 09:16
Sorry for the deleted comment. My browser was having the hickups and didn't allow me to edit.

Your approach seems to work fine, apparently it has something to do with running `disown` in a script. When I'm doing this the terminal running top gets quit once I quit the parent shell even though it has been disowned before. This worked fine before.

Here is the script again that is causing the issue:

```
function top
  if set -q DISPLAY
    sakura  -t top --name monitor -e /usr/bin/top -P -t -s 5&
    disown
  else
    /usr/bin/top -P -t -s5
  end
end
```

**Comment by raichoo** [comment] 2019-07-30 09:18
Not even trying to edit this anymore: in the original script I was doing `disown $last_pid` the version pasted right now was one attempt if trying to figure out what's going on.

**Comment by faho** [comment] 2019-07-30 09:20
See also #5036.

@raichoo: Try `status job-control full` at the start of the script.

Though I wouldn't expect that to be a regression from 3.0? In fact it'd be surprising that it worked before.

**Comment by raichoo** [comment] 2019-07-30 09:28
I've tried what you recommended and it also doesn't work. In fact the outcome gets a bit more confusing. The job is not properly disowned and it's still listed when issuing `jobs` in the parent shell. However, once I issue `disown` it gets removed but still closes when the parent shell does.

**Comment by raichoo** [comment] 2019-07-30 09:34
Okay, the not being able to disown was probably related to `disown $last_pid`which certainly is not supposed to work. However the spawned process still gets terminated.

**Comment by faho** [comment] 2019-07-30 09:35
Okay, so let's simplify the reproducer:

```fish
function top
    sleep 1h &
    disown
end
```

executed in an interactive shell reproduces the issue? Sleep is started, when you kill fish it is also killed?

This is on FreeBSD?

**Comment by faho** [comment] 2019-07-30 09:41
Okay, I can reproduce with the above function (note that `jobs` doesn't show any remaining jobs, so you'll have to check `ps` et al for the process running).

I can also confirm that reverting a33f0eb fixes it.

**Comment by raichoo** [comment] 2019-07-30 11:08
Yep, it is on FreeBSD

**Comment by ridiculousfish** [comment] 2019-07-31 00:14
I still can't reproduce on FreeBSD 12. (Note that FreeBSD doesn't seem to support the `h` suffix for sleep)

<img width="591" alt="Screen Shot 2019-07-30 at 5 13 53 PM" src="https://user-images.githubusercontent.com/920838/62174083-6dc2ff80-b2ed-11e9-8ec3-771c25e9b24e.png">
 on

**Comment by faho** [comment] 2019-07-31 06:50
@ridiculousfish I also cannot reproduce in that case, I can however if I open a new terminal and use that fish (on linux, so I doubt it's bsd-specific). So I'd imagine we get a different pgroup.

**Comment by ridiculousfish** [comment] 2019-08-03 21:09
Ahh I figured out how to repro - we aren't sending SIGHUP to the job when fish itself gets HUP. I was running into the behavior where iTerm2 keeps a session alive for a bit after closing the window.

**Comment by ridiculousfish** [comment] 2019-08-03 21:43
I'm just going to put back some logic about not assigning a job to fish's pgrp.

**Comment by ridiculousfish** [comment] 2019-08-03 21:44
Thanks for filing!

**Closed** 2019-08-03 21:44 UTC
Labels: bug

**Comment by raichoo** [comment] 2019-08-05 07:43
Seems to work fine over here :) Thanks for digging and fixing it :D
