### ISSUE TITLE
rustc autocompletion causes stderr output automatically

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4227] opened 2017-07-19 04:25 UTC
`fish, version 2.6.0-208-gc577d01` with rustc `rustc 1.18.0 (03fc9d622 2017-06-06)` installed.

If you open a *new* fish session and type in `rustc / ` the following appears automatically at the cursor:
```
rustc /warning: the option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details
```

Should stderr output from autocompletion guesswork be shown to the user?

**Comment by krader1961** [comment] 2017-07-19 04:41
No, but this is a problem with how subshells used by completions work. Closing as a duplicate of #1035.

**Comment by mqudsi** [comment] 2017-07-19 04:42
Thanks.

**Closed by krader1961** 2017-07-19 04:41 UTC
Labels: duplicate
