### ISSUE TITLE
Launch $EDITOR with shell

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#6072] opened 2019-08-26 21:57 UTC
```
fish, version 3.0.2
3.0.2
```

```
Darwin ien.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

```
xterm-256color
```

Reproduction:

1. ` sh -c 'env HOME=$(mktemp -d) fish'`
2. `set -gx EDITOR 'bash -c vim'`
3. Press ALT+E
```
nhooyr@ien ~> fish: Unknown command 'sh -c nano'
/usr/local/Cellar/fish/3.0.2/share/fish/functions/edit_command_buffer.fish (line 25): 
        $EDITOR $f
        ^
in function 'edit_command_buffer'
	called on standard input
```

Fish should be running $EDITOR with a shell so that arguments and flags can be passed.

E.g. my editor is `subl -wn` but fish won't let me pass the `-wn` flags without creating a script, making that my editor and calling `subl -wn` from there.

**Comment by zanchey** [comment] 2019-08-27 05:33
This is behaviour that we have struggled with as it is effectively undefined (`$EDITOR` is passed straight to `execvp(3)` by lots of other programs). See #5348, which I will close this as a duplicate of.

**Closed by zanchey** 2019-08-27 05:33 UTC
