### ISSUE TITLE
trap INT EXIT function doesn't work in my script

### ISSUE THREAD

**Issue by yamatakau08** [fish-shell/fish-shell#6744] opened 2020-03-13 06:50 UTC
```
/c/T/tako> uname -a
MINGW64_NT-10.0-17763 JPC00183513 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
/c/T/tako> fish --version
fish, version 3.0.2
```
My function ascreenrecord uses "trap ... INT EXIT".

```
/c/T/tako> cat ~/.config/fish/functions/ascreenrecord.fish
function ascreenrecord
  switch (uname -s)
    case 'MINGW64_NT-*'
      set mp4f //sdcard/Download/screenrecord.mp4
    case '*'
      set mp4f  /sdcard/Download/screenrecord.mp4
    end

  # list android devices to use
  adb devices -l

  read -P "select transport_id: " tid

  echo "start screenrecord ..."

  trap "adb -t $tid pull $mp4f $argv[1]" INT EXIT

  adb -t $tid shell screenrecord $mp4f

  # trap "" INT
end
```

There is no file and traps before executing ascreenrecord function.

```
/c/T/tako> ls
total 44
drwxr-xr-x 1 yama Domain Users 0 Mar 13 15:25 ./
drwxr-xr-x 1 yama Domain Users 0 Mar 12 16:40 ../

/c/T/tako> trap
```

Execute ascreenrecord function.

```
/c/T/tako> ascreenrecord
List of devices attached
...
XXXXXXXXXX             device product:SOV32_jp_kdi model:SOV32 device:SOV32 transport_id:5
...

select transport_id: 5
start screenrecord ...
```

hit Ctrl+c.
There is no output and file pulled from android device.

```
/c/T/tako> ls
total 44
drwxr-xr-x 1 yama Domain Users 0 Mar 13 15:25 ./
drwxr-xr-x 1 yama Domain Users 0 Mar 12 16:40 ../
```

But trap functions for INT and EXIT are registered.

```
/c/T/tako> trap
# Defined in - @ line 1
function __trap_handler_EXIT --on-event fish_exit
        adb -t 5 pull //sdcard/Download/screenrecord.mp4 ;
end
# Defined in - @ line 1
function __trap_handler_INT --on-signal SIGINT
        adb -t 5 pull //sdcard/Download/screenrecord.mp4 ;
end
```

Executing "__trap_handler_INT" can pull the mp4 file.

```
/c/T/tako> __trap_handler_INT
//sdcard/Download/screenrecord.mp4: 1 file pulled. 15.8 MB/s (3064737 bytes in 0.185s)
```

What is wrong with my script use trap INT, EXIT?

on Mac,fish, version 3.1.0 has the same issue.

**Comment by zanchey** [comment] 2020-03-13 12:54
I think this is a duplicate of #6649.

**Closed** 2020-04-28 12:16 UTC
