### ISSUE TITLE
complete -c hello -f -a ""  with empty string fails

### ISSUE THREAD

**Issue by gutenye** [fish-shell/fish-shell#4013] opened 2017-05-05 00:32 UTC
fish, version 2.5.0

```
complete -c cd -f -a ""
```

Current result:

``` 
$ cd dira/<TAB>
dira/filea
dirb/fileb
...
```
Expect result:

```
$ cd dira/<TAB>
<nothing>
```

if `-a` returns an empty string, it still show a list of files on completion, even though I have `-f` option. Expected: it should show nothing on completion.

If it is not a bug, is there a solution to fix this?

**Comment by faho** [comment] 2017-05-05 00:45
This is a duplicate of #112. Currently, we don't have a workaround. Sorry!

**Closed by faho** 2017-05-05 00:45 UTC
