### ISSUE TITLE
python pip completions error when using venv

### ISSUE THREAD

**Issue by rectalogic** [fish-shell/fish-shell#9377] opened 2022-11-24 16:32 UTC
When running tools from inside a python venv, autocompletion errors:
```
aw@rage ~> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
aw@rage /U/aw> python3.10 -m venv /tmp/venv
aw@rage /U/aw> /tmp/venv/bin/pip ifish: Unknown command: pip
/opt/local/share/fish/completions/pip.fish (line 1):
pip completion --fish 2>/dev/null | source
^
from sourcing file /opt/local/share/fish/completions/pip.fish
```
See asciinema cast attached.
[pipfish.cast.zip](https://github.com/fish-shell/fish-shell/files/10086222/pipfish.cast.zip)
```
aw@rage ~> uname -a
Darwin rage.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64
aw@rage ~> echo $TERM
xterm-256color
aw@rage ~> fish --version
fish, version 3.5.1
aw@rage ~> echo $version
3.5.1
```

**Comment by faho** [comment] 2022-11-24 16:46
Duplicate of #3117

**Closed by faho** 2022-11-24 16:46 UTC

**Comment by faho** [comment] 2022-11-25 11:32
Duplicate of #9133
