### ISSUE TITLE
(Kubernetes) bash: ~/**/kubectl.sh: No such file or directory persistent error

### ISSUE THREAD

**Issue by jodriscoll** [fish-shell/fish-shell#4446] opened 2017-10-03 14:17 UTC
**Completing the Issue Requirements:**
- `fish, version 2.6.0`
- `16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
- `xterm-256color`
![env-output](https://user-images.githubusercontent.com/996636/31128248-35b5f0aa-a81f-11e7-8c35-7a3aedb42457.png)
- `Oh My Fish version 5`
---
**Issue Description:**
When bashing out of fish, receiving a (relative) path error for `kubectl.sh`; pertains to the usage of [Kubernetes](https://kubernetes.io/).

**Demonstration:**
![kubectl](https://user-images.githubusercontent.com/996636/31129852-cbaf0e08-a823-11e7-8d22-9c5e1ea272a2.gif)

**Summary:**
Placing a file within the path, will (obviously) address the error, regarding of the contents of the file. I would prefer to address it globally using some nifty CLI definitions (that's I'm too newb to figure out, apologies!).

**Comment by zanchey** [comment] 2017-10-03 14:37
Is there something calling `kubectl.sh` in your bash initialisation files? The problem is that there's so darn many of them... `bash -x` may help.

**Comment by jodriscoll** [comment] 2017-10-04 19:12
Thanks for taking the time to respond @zanchey – I've executed your recommendation and extracted the references for Kubernetes. 

```bash
+ alias 'kubectl=$(pwd)/kubectl.sh'
+ source /dev/fd/63
+ export NVM_DIR=/Users/**redacted**/.nvm
+ NVM_DIR=/Users/**redacted**/.nvm
+ '[' -s /Users/**redacted**/.nvm/nvm.sh ']'
+ . /Users/**redacted**/.nvm/nvm.sh
+++ pwd
++ /Users/**redacted**/kubectl.sh completion bash
bash: /Users/**redacted**/kubectl.sh: No such file or directory
```

Let me know if you require further information to troubleshoot the issue out of existence :)

**Comment by zanchey** [comment] 2017-10-07 01:10
The edited transcript is not that helpful, but something in your bash startup files is definitely trying to run that `kubectl` comand.

I'm not sure that this is a fish problem - does it happen if you launch bash directly from your terminal emulator (that is, set the command run by your terminal to `/bin/bash`)? If so, then I don't think I can help much as the problem is not with fish.

**Comment by faho** [comment] 2017-10-18 11:54
@jodriscoll: Ping?

As @zanchey said, this doesn't seem to be a problem with fish, but with your bash configuration.

**Comment by faho** [comment] 2017-12-11 09:53
No answer in a while, and this doesn't seem to actually be a fish issue. Closing.

**Closed by faho** 2017-12-11 09:53 UTC
Labels: question
