### ISSUE TITLE
Cannot save abbreviations

### ISSUE THREAD

**Issue by pescepalla** [fish-shell/fish-shell#9506] opened 2023-01-23 11:52 UTC
```
$ fish --version
fish, version 3.6.0
$ uname -a
Linux stellaris 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux
$ basename "/"(ps -o cmd -f -p (cat /proc/(echo %self)/stat | cut -d \  -f 4) | tail -1 | sed 's/ .*$//') 
xfce4-terminal
```

Hi, I am finding myself unable to modify my abbreviations either with the `abbr` command or with the webUI. WebUI changes are discarded immediately, while modifications with `abbr --add` or `abbr --erase` are not carried over to a new terminal window. The commands fail to change the `fish_variables` file.

**Comment by faho** [comment] 2023-01-23 11:56
Please see the CHANGELOG:

> Abbreviations are no longer stored in universal variables. Existing universal abbreviations are still imported, but new abbreviations should be added to config.fish.

I'm closing this as a duplicate of #9460 because we forgot to remove the abbreviations tab from the web ui.

**Closed by faho** 2023-01-23 11:56 UTC

**Comment by pescepalla** [comment] 2023-01-23 12:21
Thanks. Does this mean that the `abbr` command cannot be used any longer to add persistent abbreviations?

**Comment by faho** [comment] 2023-01-23 12:25
That is exactly what it means, yes.

`abbr` is now a builtin, which makes it *much* faster, and it can do a lot more. In exchange, it will no longer add universal variables. The reason for that is that the way the abbreviations were saved didn't allow for the additional options abbreviations can now have ("run this function to expand it", "match on this regex", "match as a command or anywhere").

So you'll have to just save your `abbr --add foo bar` in config.fish or a file in ~/.config/fish/conf.d/.

**Comment by faho** [comment] 2023-02-14 12:17
We have added some improvements after 3.6.0, please see [the git version](https://github.com/fish-shell/fish-shell/blob/master/doc_src/cmds/abbr.rst)

**Comment by AlexWayfer** [comment] 2023-02-14 13:18
> This says outright that universal variables are no longer used.

It's not clear what the deal between standard (old-fashioned) abbrevations and universal variables. It requires investigation instead of simple instructions. BTW, I meant the difference between "should be" (kind of "have to be") and "may be" (kind of "very optional unclear for what").



> Anyway, we have added some improvements after 3.6.0, please see [the git version](https://github.com/fish-shell/fish-shell/blob/master/doc_src/cmds/abbr.rst)

Thanks, these changes are good.
