### ISSUE TITLE
lynx bug causes `help` output to render as black on blue background 

### ISSUE THREAD

**Issue by fczuardi** [fish-shell/fish-shell#4170] opened 2017-06-30 20:18 UTC
fish 2.5.0
Linux alarm 3.8.11-4-ARCH #1 SMP Sat Oct 22 11:59:55 MDT 2016 armv7l GNU/Linux
xterm

I am pretty sure this might be a lynx bug, but I will report it here as well since it might have a possible workaround on the fish side as well...

Steps to reproduce:
- install fish on a system that uses lynx as the browser (for exemple, a raspberry pi running raspbian)
- enter fish
- type help
- scroll to the introduction paragraph (on lynx)

Expected behavior:
The text should be pretty readable, for example, white over black.

Actual behavior:
The paragraph is black over blue, which is pretty ugly, see the picture

![us3gyqe](https://user-images.githubusercontent.com/606923/30872930-43068d96-a2b1-11e7-93a7-1c60d77a5c3a.png)

-----

Here is a simplified html that causes this issue, the problem seems to be the "contents" class name...

```html
<html>
<body>

<div class="contents"> <p>foo</p> </div>

</body>
</html>
```

**Comment by fczuardi** [comment] 2017-06-30 20:30
The lynx maintainer consider this a feature :) http://lists.gnu.org/archive/html/lynx-dev/2015-12/msg00037.html

**Comment by fczuardi** [comment] 2017-06-30 20:33
a div with class "contents" will hash colision with the lss selector em.a and render with that color :(   see http://lists.gnu.org/archive/html/lynx-dev/2015-12/msg00039.html

**Comment by krader1961** [comment] 2017-06-30 20:54
Simply changing the class name from `contents` to something else would probably solve this specific problem. But it doesn't guarantee some other rendering anomaly won't occur. The problem is fundamentally with `lynx`. I'm hoping the author of `lynx` had his tongue planted firmly in cheek when they wrote "It's a feature...".

Since you use lynx do you have concrete advice on making the fish documentation render better given lynx's quirks? Have you considered simply using `man`? All of the commands we ship with fish have a man page. And the remaining documentation (e.g., `help variables`) can be read at fishshell.com. Which makes working around lynx bugs hard to justify. Still, if there is something we can do that is simple and doesn't obfuscate our HTML we'd probably be willing to do it.

**Comment by fczuardi** [comment] 2017-06-30 21:10
I am not a regular lynx user, and I am almost sure that lynx came as a dependency of fish on debian jesse package (raspbian). I really dont mind using man, but I see an usability issue for people installing and using fish for the first time on debian, since the welcome message is:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

And typing help leads to a pretty ugly and hard to read documentation :P

**Comment by krader1961** [comment] 2017-06-30 22:56
It would not surprise me if the Debian team made lynx a dependency on raspbian but it isn't a requirement of fish. I looked at the [lynx documentation](http://lynx.browser.org/lynx_help/Lynx_users_guide.html) and noticed it has a `--nocolor` flag. Can you type `funced help` and replace this

```
eval $fish_browser $page_url
```

with

```
eval $fish_browser --nocolor $page_url
```

and confirm that makes the text readable? If it does that is probably the simplest fix for this problem. Obviously we would only use that flag if `$fish_browser` equals `lynx`.

**Comment by krader1961** [comment] 2017-06-30 23:16
Okay, I installed lynx on my Ubuntu system did `set -x BROWSER lynx` and confirmed that `--nocolor` has the desired effect. However, I'm not seeing black on blue. I'm seeing green, yellow, magenta on a black background.

What does `echo $TERM` and `lynx --version` report, @fczuardi ? I'm using xterm-256color and lynx version 2.8.9dev.9.

**Comment by krader1961** [comment] 2017-07-11 02:34
Marking this as "needs-more-info" because I can't reproduce the problem.

@fczuardi, Can you answer the questions in my previous comment?

**Comment by krader1961** [comment] 2017-07-18 00:01
Ping?

**Comment by krader1961** [comment] 2017-07-28 04:55
Closing due to lack of response to previous questions. If this is still a problem for you, @fczuardi, or anyone else feel free to reopen it.

**Comment by TheJare** [comment] 2017-08-25 22:30
FWIW I just tried fish inside Windows Subsystem for Linux with Ubuntu 16.04 distro (using a fairly plain Mintty as terminal) and experience the exact same problem. Easiest place to see the black on blue text is to type "help", then select the first link "fish shell", and on that page down a bit, "Tutorial". The first paragraph after the "Why Fish?" subheader is already black-on-blue (the first word "fish" is not).

~> lynx --version
Lynx Version 2.8.9dev.8 (21 Dec 2015)
libwww-FM 2.14, SSL-MM 1.4.1, GNUTLS 3.4.9, ncurses 6.0.20160213(wide)

 ~> echo $TERM
xterm-256color

**Comment by zanchey** [comment] 2017-09-26 15:05
I'm almost certain that comes from the Doxygen template.

**Comment by mqudsi** [comment] 2017-09-26 16:58
So I used to have this problem but when I tried again after having fixed my terminal colors, lynx looks just fine.

Here's what I see with lynx 2.8.9dev.8 under WSL (conhost):

![image](https://user-images.githubusercontent.com/606923/30873112-c7b664a8-a2b1-11e7-9cfe-26c045e2358d.png)

I've been meaning to publish my conhost color configuration to help others out. But I'm not sure there's a bug here?

My colorscheme:

![image](https://user-images.githubusercontent.com/606923/30873141-dfe2bb62-a2b1-11e7-9af5-87424960ad69.png)

@TheJare can you please post a screenshot of the output of `colortest-16`?

**Closed** 2017-09-26 19:34 UTC
Labels: enhancement

**Comment by faho** [comment] 2019-03-22 11:50
I just tried the new sphinx-based documentation in lynx (2.8.9rel1) and it looks alright, so I'd like to remove this workaround, because it allows us to remove the $DISPLAY check for xdg-open, because that actually works in non-graphical environments.

**Comment by mqudsi** [comment] 2019-03-23 15:11
I'm not sure which workaround you're referring to because as I recall the real fix was this was launching lynx with a custom stylesheet?

**Comment by faho** [comment] 2019-03-23 15:19
The workaround is that _we_ add the stylesheet. Which necessitates that we
handle lynx differently from everything else.

Mahmoud Al-Qudsi <notifications@github.com> schrieb am Sa., 23. März 2019,
16:11:

**Comment by zanchey** [comment] 2019-03-24 03:33
The workaround is 2b425ad221831b7f149042.

**Comment by floam** [comment] 2023-01-02 03:31
> simply changing the class name from contents to something else would probably solve this specific problem. But it doesn't guarantee some other rendering anomaly won't occur. 

This was a very severe take. We don't need to guard against future hash collisions that might cause adverse styling in Lynx with this severe workaround.

I'm removing the Lynx stylesheet and special case since this has been effectively fixed since we switched to Sphinx. We don't have a <div class="contents"> any longer.
