### ISSUE TITLE
Completions for relative path are loaded even if the command isn't available in $PATH

### ISSUE THREAD

**Issue by Qix-** [fish-shell/fish-shell#9133] opened 2022-08-10 14:33 UTC
> fish, version 3.5.1
>
> Yes, this happens in a clean environment.

I manage my Github clones with a script called `gh`, which I invoke via `./gh foo/bar`.

Fish seems to think I'm trying to run the global `gh` command, which is not the case - I don't use Github's client but I suppose theirs is similarly named `gh`.

Whenever I write `./gh foo/bar`, I get the error message:

```
/opt/homebrew/Cellar/fish/3.5.1/share/fish/completions/gh.fish (line 1):
gh completion --shell fish 2>/dev/null | source
^
from sourcing file /opt/homebrew/Cellar/fish/3.5.1/share/fish/completions/gh.fish
```

Shouldn't it be seeing that I'm writing `./gh` and not `gh` and ignore it?

**Comment by faho** [comment] 2022-08-10 14:44
Quite simply put: It is impossible for us to tell that your command isn't the same "gh" that we know how to complete. It is also *correct* for us to interpret absolute or relative paths the same - imagine if you ran `./git`.

Sorry, there is nothing we can do here.

**Comment by faho** [comment] 2022-08-10 14:44
Duplicate of #9001

**Comment by Qix-** [comment] 2022-08-10 15:27
Err, no it's not. This is not added to my path. This is a local file in the CWD being run. **`gh` is not the same as `./gh`**. That is my point.

**Comment by faho** [comment] 2022-08-10 15:38
That's #3117

**Comment by Qix-** [comment] 2022-08-10 20:00
Is it that difficult to do "if this command isn't querying a PATH command, don't issue completions for it"?

Why would I ever want completions on _local_ scripts? Is there a way to disable this behavior?

**Comment by faho** [comment] 2022-08-10 20:15
> Is it that difficult to do "if this command isn't querying a PATH command, don't issue completions for it"?

It was a bug that it didn't, so we enabled it. It's typically the right thing, e.g. when I do `/usr/bin/git`, or when I do `./fish`.

And because names mean things, something that's called "git" should complete like "git", something that's named "rm" should complete like "rm".

>Why would I ever want completions on local scripts? Is there a way to disable this behavior?

There is no global toggle. You can disable the completion script for gh by creating an empty completion script - `touch ~/.config/fish/completions/gh.fish`. Like I said in my first comment.

>And if it's "impossible" how do I turn off completions entirely?

You don't.

**Comment by faho** [comment] 2022-08-11 06:57
Okay, here's what we can do:

We already don't load completions for commands that don't exist, to avoid errors. We can extend that to not load completions for commands that don't exist in $PATH (or as a function/builtin).

That won't fix your completions, because you still have something called "gh" that's not the "gh" we know, but it will remove the error even without fixing #3117 (which we're not even sure *how*).

-----

One more thing I'd love to know is if your error doesn't *mention* that the command wasn't found or if you just missed that line when copying. That threw me off here.

**Comment by krobelus** [comment] 2022-08-11 09:07
> We can extend that to not load completions for commands that don't exist in $PATH (or as a function/builtin).

Sounds like a  reasonable tradeoff. It doesn't solve the whole problem but some of it.
It will also bring false negatives for cases where the user has written completions for a specific commands outside $PATH (`complete -p /path/to/gh`) but given that a workaround is easy it seems fine to disregard this obscure case.

There's the alternative to do this only for specific completions (`command -vq gh || exit` in `gh.fish`) but that's even more complex.

**Comment by Qix-** [comment] 2022-08-11 11:32
> One more thing I'd love to know is if your error doesn't mention that the command wasn't found or if you just missed that line when copying. That threw me off here.

Ope! Sorry, yes you're correct, I missed that when copying, apologies.

This tradeoff sounds reasonable, I appreciate that :)

**Comment by faho** [comment] 2022-08-11 11:41
>It will also bring false negatives for cases where the user has written completions for a specific commands outside $PATH (complete -p /path/to/gh) but given that a workaround is easy it seems fine to disregard this obscure case.

This shouldn't change `complete -p`, because this is about *loading* the completions.

That just means if you do `./gh` we won't `source /usr/share/fish/completions/gh.fish`. If you have defined a completion for a *path*, that won't be autoloaded anyway. In practice `complete -p` is used for one thing:

https://github.com/fish-shell/fish-shell/blob/2191faf17e1bb46a3210c81f6d25c6a7d5352b0a/share/functions/__fish_config_interactive.fish#L109-L119

Which, like the comment says, has to be defined eagerly already.

-----

Tbh I would be fine with removing those completions along with `complete -p`. But that's for another issue and I suspect it might have detractors.

**Closed** 2022-08-11 15:11 UTC
Labels: bug
