### ISSUE TITLE
Provide a mechanism for disabling "sixth edition" "thompson shell" hack

### ISSUE THREAD

**Issue by allisonkarlitskaya** [fish-shell/fish-shell#8679] opened 2022-01-31 11:19 UTC
See https://github.com/fish-shell/fish-shell/pull/7802 for a bit of background.

I pretty much agree with everything that @faho said in that PR.  This is an awful misfeature which is nothing more than a relic from prehistoric times, and only technically required for POSIX conformance.  This is exactly the sort of place where fish ought to be breaking from the standard behaviour, as being hopelessly broken.

Shell scripts without a `#!/bin/sh` line aren't really valid: the kernel itself rejects them.  The average user of fish has basically zero chance of coming across a script which has intentionally excluded it.  On the other hand, it's a pretty common mistake to forget to add the `#!` line on some Python (or whatever) script that you're hacking on.

(bonus points: the `import` command, installed into `/usr/bin` by ImageMagic has a tendency to cause gnome-shell to freeze up, and that's pretty much what's gonna happen when you accidentally run a Python script using the shell).

Please consider adding some kind of a mechanism for disabling this wretched hack, and please strongly consider enabling it by default.

**Comment by faho** [comment] 2022-01-31 11:21
Duplicate of #8086

**Comment by faho** [comment] 2022-01-31 11:21
The answer is: No.

**Closed by faho** 2022-01-31 11:21 UTC
