### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#8012] opened 2021-05-17 17:00 UTC
I could have sworn we already had an issue open, but I can't find it, so here goes:

We should release fish, version 3.3.0.

I think we all would agree that we should probably make a smaller release this time, 

Some data on the releases since 2.0 and the number of commits they included:

| Release | Number of commits |
| --- | --- |
| 2.0.0|1328 |
| 2.1.0|263 |
| 2.1.1|15 |
| 2.1.2|2 |
| 2.2b1|1281 |
| 2.2.0|20 |
| 2.3b1|766 |
| 2.3b2|23 |
| 2.3.0|12 |
| 2.3.1|54 |
| 2.4b1|654 |
| 2.4.0|19 |
| 2.5b1|341 |
| 2.5.0|9 |
| 2.6b1|389 |
| 2.6.0|21 |
| 2.7b1|414 |
| 2.7.0|4 |
| 2.7.1|3 |
| 3.0b1|1795 |
| 3.0.0|13 |
| 3.0.1|67 |
| 3.0.2|3 |
| 3.1b1|2191 |
| 3.1.0|19 |
| 3.1.1|87 |
| 3.1.2|4 |
| 3.2.0|2177 |
| 3.2.1|75 |
| 3.2.2|14 |
| master|302 |

generated with 

```fish
set -l last
for tag in (git tag -l --format='%(tag) %(taggerdate:unix)' | grep -v invert-feature | sort -nk2 | string split " " -f1 | string match -re '.+') master
    set num (git rev-list --count "$last"..$tag)
    echo $tag $num
    set last $tag
end
```

So the last four releases cracked the 1500 or even 2000 commit mark. The releases after 2.7.1 to 3.2.2 already make up 45% of the total commits ever made to fish. Every one of those releases represents more than 10% to the commits made to fish.

We should make smaller releases.

I feel like what we have now in master is already a nice set of improvements that would already make a nice and juicy release. Not the bomb that 3.2 was, but enough to be worthwhile. It would also make it easier to tell if something was changed since 3.2, because right now whenever someone reports a bug with 3.1 all I can do is point them to 3.2 because that changed roughly speaking *everything*.

--------------

Now what's left to be done for 3.3? Personally, I don't see a lot of work in progress that we'd like to wait for or critical bugs that we'd want to have fixed first.

We might want to revert 325599979479ae04ebac1d0556519f973058993e, I've left it in to test and so far haven't had any issues, but then I don't tend to do a lot of signal handling in scripts.

**Comment by zanchey** [comment] 2021-05-19 15:19
Duplicate of #7759, but let's track here.

3255999 causes excitingly platform-specific behaviour! On Debian 10, I see "expected behaviour" with `fish -c 'sleep 100'` and hitting Ctrl-Z; on macOS 10.14, it terminates the process entirely (I assume the sleep gets SIGSTOP, then fish exits, and terminates the stopped process instead of disowning it).

**Comment by zanchey** [comment] 2021-06-24 15:14
OK, I think Integration_3.3.0 is ready. However, I'm about to disappear into the bush for the weekend so I'll hold off on doing the release until I'm back. Trial builds on various platforms seem to be working, though I'd appreciate tests on Cygwin (@andrew-schulman ?) and something Solaris-derived.

**Comment by faho** [comment] 2021-06-24 16:35
Okay, so OpenIndiana *basically* works. I'm gonna commit some more adjustments for its `command false` (which returns 255 - which we already handled in some places) and `ps` (which doesn't have `-o stat`, only `-o s`, which only prints part of the state?).

Python can't do tcgetpgrp (wrong ioctl), pexpect can't:

- Send SIGTSTP
- Set the dimensions (defaults to 80x24)
- Exit via ctrl-d (this one works in an actual terminal)

I'm just gonna leave those for someone else to solve as they don't seem to affect actual functionality and I bloody hate this thing.

Just look at this output from when I dared install pexpect via `pkg`:
![Screenshot_20210624_182549](https://user-images.githubusercontent.com/5185367/123300422-dbe4c100-d51a-11eb-95aa-47c6ca38ee18.png)

**Comment by faho** [comment] 2021-06-24 18:17
OpenBSD fails the math tests because it doesn't read 0x hex numbers in wcstod (like C99 specifies). Apparently that feature just won't be supported there. I don't think we should attempt to work around them failing to implement the C standard after *21* years (especially because the feature is unimportant and the workaround involves *writing your own wcstod*).

It also fails in noshebang - all the posix_spawn runs apparently return 127? I can't reproduce this in an interactive shell.

sigint2.fish hangs. I'm assuming it's down to different signal handling? Disabling this one there.

History tests fail - #6477. Also private_mode.py.

`status fish-path` (i.e. argv[0]) works differently (it's just the name of the executable, not the path), breaking status-command.fish.

The other tests pass.

The history tests have been broken for a while, math/noshebang/fish-path are down to different os semantics that are just annoying to test. Nothing to block a release.

**Comment by faho** [comment] 2021-06-24 18:32
FreeBSD doesn't have a `python3` symlink *at all*, expecting everyone to deal with the full python version at all times (even the pexpect package is called "py39-pexpect". Once they upgrade you get to change the package name).

After just creating my own, it passes all the tests.

**Closed** 2021-06-28 15:01 UTC
Labels: packaging, release notes

**Comment by andrew-schulman** [comment] 2021-06-29 22:00
Late to the party, but 3.3.0 builds and runs fine in Cygwin.

**Comment by floam** [comment] 2022-01-19 06:24
> It also fails in noshebang - all the posix_spawn runs apparently return 127? I can't reproduce this in an interactive shell. I'm assuming it's down to writing to a file and then trying to execute it, from the same script.

See "Asynchronous Error Notification" in the  POSIX.1-2017 posix_spawn update: https://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_spawn.html#tag_16_371_08_06
