### ISSUE TITLE
autocompletion very slow after Mac Big Sur update 

### ISSUE THREAD

**Issue by benkeil** [fish-shell/fish-shell#7613] opened 2021-01-06 23:10 UTC
Version: fish, version 3.1.2

Tried: sh -c 'env HOME=$(mktemp -d) fish' => does not help

When I type any string and want to use autocompletion it took ~7sec until it responds.

**Comment by faho** [comment] 2021-01-06 23:12
duplicate of #7601

**Closed by faho** 2021-01-06 23:12 UTC
