### ISSUE TITLE
Issues with completion after newline.

### ISSUE THREAD

**Issue by mathlover2** [fish-shell/fish-shell#3234] opened 2016-07-14 17:57 UTC
**fish version installed** _(`fish --version`)_: fish, version 2.3.1-384-gf08ac96, but also on version 2.0.0

**OS/terminal used**: Ubuntu 14.04 Trusty Tahr / gnome-terminal

The following issue was discovered when I accidentally pressed the tab key whilst entering a series of files to be downloaded by a `wget` invocation. I have confirmed it on all three of the Linux machines I own (excluding my phone.) I have been using zsh in the meantime, but if this is fixed, I will gladly use fish again.
## Reproduction steps
1. Launch fish
2. Type a command (in my case `wget`).
3. Type a space, then an escaped newline.
4. Press tab key
## Expected results

Fish should do completions as if newline did not exist.
## Actual results

This:
![fish-error](https://cloud.githubusercontent.com/assets/13435808/16849805/3680125e-49ca-11e6-9269-f19d9eedd2e2.png)

**Comment by mathlover2** [comment] 2017-03-04 21:58
This seems to be now fixed as of 2.5. I tried repeating the error, and got normal behaviour.
Should I close this?

**Comment by krader1961** [comment] 2017-03-05 01:44
Thanks for the follow-up, @mathlover2. I too cannot reproduce this using fish 2.5.0 so closing.

**Closed by krader1961** 2017-03-05 01:44 UTC
Labels: bug
