### ISSUE TITLE
Inconsistent indentation in output of `functions`

### ISSUE THREAD

**Issue by SeekingBlues** [fish-shell/fish-shell#8931] opened 2022-05-04 21:22 UTC
Interactively defined functions have no indentation at all:
```fish
> function f
      if true
          if true
              if true
              end
          end
      end
  end

> functions f
# Defined interactively
function f
if true
if true
if true
end
end
end
end
```
When a function is defined inside of other blocks, there will be extra indentation (and an extra newline?):
```fish
> functions grep
# Defined in /usr/local/Cellar/fish/3.4.1/share/fish/functions/grep.fish @ line 6
function grep
        command grep --color=auto $argv

end
```
It should all look like this:
```fish
> functions fish_is_root_user
# Defined in /usr/local/Cellar/fish/3.4.1/share/fish/functions/fish_is_root_user.fish @ line 4
function fish_is_root_user --description 'Check if the user is root'
    if contains -- $USER root toor Administrator
        return 0
    end

    return 1
end
```

Fish version: 3.4.1
OS: macOS 10.15.7; Darwin Kernel Version 19.6.0
Terminal: iTerm2 3.4.15 (xterm-256color)

**Comment by faho** [comment] 2022-05-05 04:45
Duplicate of #5284

**Closed by faho** 2022-05-05 04:45 UTC
