### ISSUE TITLE
cat with a file without trailing newline does not show contents

### ISSUE THREAD

**Issue by Siecje** [fish-shell/fish-shell#3967] opened 2017-04-19 16:30 UTC
If you cat something without a trailing newline you won't see the output. I believe it is because the prompt draws over top of it.

```shell
$ printf "a" > test
$ cat test
$ # The contents of test are not shown
```

I don't know why a longer string has a new line

```shell
printf "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" > test
siecje@Mint18 /h/siecje> cat test
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa⏎   
siecje@Mint18 /h/siecje> 
```

Please tell us which fish version you are using by executing the following:
```shell
~ $ fish --version
fish, version 2.5.0
~ $ echo $version
2.5.0
```

```shell
~ $ uname -a
Linux Mint18 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~ $ echo $TERM
xterm-256color
```

I have tried without third party customizations.

**Comment by faho** [comment] 2017-04-19 16:33
Duplicate of #3850, which is already fixed in git.

**Closed by faho** 2017-04-19 16:33 UTC
