### ISSUE TITLE
unicode \u23CE ⏎ character preceding every prompt

### ISSUE THREAD

**Issue by Ben67366** [fish-shell/fish-shell#4717] opened 2018-02-09 09:07 UTC
After change the 
Every time I run fish using ssh from cmd on windows.
I get this character at the end.
⏎

**System Information:**
Windows 10

**Reproduce steps:**
1. It works now.
![image](https://user-images.githubusercontent.com/25456777/36019776-ac646fc4-0dc3-11e8-8b1f-8396b8efb49e.png)

1. Change the system locale to Japanese(Japan), and restart the computer.
![image](https://user-images.githubusercontent.com/25456777/36019681-5b5151d8-0dc3-11e8-82bb-0d3b1910d940.png)

1. After restarted the computer.
![image](https://user-images.githubusercontent.com/25456777/36020022-7b7fffa8-0dc4-11e8-8d08-c482ef10b506.png)

**Comment by faho** [comment] 2018-02-09 09:56
That character is supposed to show up whenever the last command does not end its output in a newline. The trick however is that it's added every time, and then the terminal cursor is moved so that it is overwritten when it was on a line by itself (because it's directly after a newline). This requires the terminal work in a certain way, and basically every terminal does. It's possible the WSL terminal doesn't when you change the locale.

What's weird is that the dialog above says the locale is only for programs "that do not support Unicode". Fish supports unicode, and so does the WSL terminal. So it shouldn't have any effect here.

Can you give us the output of `locale` both with japanese set and without?

**Comment by mqudsi** [comment] 2018-02-15 01:38
You would probably need the output of `chcp.com` as executed from within a WSL shell (but escaping the WSL subsystem). This is what it _should_ look like, meaning that the terminal is using the UTF8 codepage:

![image](https://user-images.githubusercontent.com/606923/36236931-92c1fe8e-11be-11e8-9df4-37b93f807902.png)

**Comment by xa0082249956** [comment] 2018-02-18 12:01
Maybe have a look at #789?

**Comment by Ben67366** [comment] 2018-02-19 05:57
@faho 
Yeah, provide them.
1. Japanese setting
![image](https://user-images.githubusercontent.com/25456777/36364052-2305cf60-1585-11e8-86c5-6cfe25142fda.png)

2. English(US) setting
![image](https://user-images.githubusercontent.com/25456777/36364062-28e34dc2-1585-11e8-90b8-edaa9e7c59b5.png)



@mqudsi  As I showed above, seems they are the same.

**Comment by Ben67366** [comment] 2018-02-19 05:59
@xa0082249956 
Yeah. I've checked #789 and found something interesting.

I changed the properties of the ClearType from Japanese font to monaca.
![image](https://user-images.githubusercontent.com/25456777/36364102-641bfda8-1585-11e8-964b-eea41c35c49c.png)

![image](https://user-images.githubusercontent.com/25456777/36364104-67415b18-1585-11e8-8cc5-c1a548ddbca8.png)


After:
![image](https://user-images.githubusercontent.com/25456777/36364106-6a43493e-1585-11e8-9573-ba9bed4f4643.png)


and it works.
![image](https://user-images.githubusercontent.com/25456777/36364111-6e11880a-1585-11e8-9f0b-10ee026cdeaa.png)

**Comment by mqudsi** [comment] 2018-02-27 00:53
ConEmu does its own thing with fonts, though. What you're seeing in the "native" CMD settings dialog for ConEmu isn't necessarily the font that's being used by ConEmu (at least from what I'm seeing on my PC). What do your conemu settings look like? Do you observe the same behavior with cmd.exe directly (without conemu at all)?

**Comment by mqudsi** [comment] 2018-02-27 00:59
Here's a screenshot of what I'm talking about. ConEmu is actually displaying a mix of `MS Gothic` and `SF Console Semibold`, but the Win32 cmd.exe properties for ConEmu claims "Lucida Console" which isn't actually rendered anywhere on-screen:

![image](https://user-images.githubusercontent.com/606923/36704718-2caf584a-1b27-11e8-9223-60428ac55080.png)

**Comment by faho** [comment] 2018-02-27 10:48
Sooo... is there anything we can do here?

I'm not really familiar with this, but as far as I know there is no way for us to query width with the current font? We only get $COLUMNS, which gives us the width of the terminal in "cells", and then use "wcwidth" to query the width of a character in "cells". Neither of those takes into account the font, so if that changes anything about how many characters fit onto the line there doesn't appear to be anything we can do to compensate. Which means that the best we can do is to tell people not to do that. Which isn't fantastic.

**Comment by mqudsi** [comment] 2018-03-02 01:09
I'm not sure. The default Windows terminal emulator (i.e. the "real" conemu and not the "ConEmu" in the screenshots and discussion above) still specifies width as columns of cells/characters. "ConEmu" appears to mix things up considerably in that regard.

Unless @Ben67366 can reproduce this with the default terminal emulator without bringing 3rd party software into the picture, I would lean towards closing this as non-standard behavior in ConEmu triggering the occurrence of this bug. If "ConEmu" exposes an environment variable by means of which we could identify it, we could just disable this feature entirely when it is detected at fish startup.

Come to think of it - how do xterm or iterm2 react when a non-proportional-width font is used?

**Comment by Ben67366** [comment] 2018-03-02 01:54
With local cmd.exe it shows like this.
![image](https://user-images.githubusercontent.com/25456777/36879617-0ac6fb64-1e08-11e8-9051-822b3787825f.png)

**Comment by Ben67366** [comment] 2018-03-02 02:01
I think if I can change the setting here, I can fix this problem. 
![image](https://user-images.githubusercontent.com/25456777/36879774-b2c607ce-1e08-11e8-81ff-56e14dfc47e4.png)

But I tried many ways, can't change the default setting of cmd.exe.
   > 1. The Ubuntu fonts can't be showed on this.
   > 1. Change the facename to Ubuntu use regediter can't change the default setting here.

And another funny thing is, the screenshot I took was directly use the cmd.exe
and if I use a bash, it shows the font on the list.
![image](https://user-images.githubusercontent.com/25456777/36879862-16673f78-1e09-11e8-9ddb-2bd0d0f89c04.png)

**Comment by krader1961** [comment] 2018-03-02 02:23
> how do xterm or iterm2 react when a non-proportional-width font is used?

iTerm2 handles this be effectively forcing each char of the proportional font to have the same width. Which looks exceptionally ugly but does preserve fixed width character cell semantics. If other terminals don't do that then they're effectively broken as pretty much every console based app assumes each char takes the same horizontal space (obviously double-width chars take 2x the space).

**Comment by mqudsi** [comment] 2018-03-02 21:31
@krader1961 thank you for that info. 

@Ben67366 you are looking for `HKLM\Software\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont` where a new font can be installed (names should be `0`, `00`, `000` and so on):

![image](https://user-images.githubusercontent.com/606923/36922507-b01b0982-1e2d-11e8-971b-7e110b7bdc33.png)

Define a new entry for the Ubuntu Mono (or a nicer font of your choosing 😉) and you'll be able to choose it.

**Comment by Ben67366** [comment] 2018-03-05 08:51
@mqudsi 
Yeah, I've changed the TrueTypeFont like this. But that doesn't make help.
![image](https://user-images.githubusercontent.com/25456777/36965749-df7876a2-209d-11e8-8417-9c2fd19d4738.png)

**Comment by Ben67366** [comment] 2018-03-05 09:00
I think the underlying reason is the bash can't be initiated under system code using 932.
And the reason why I changed the region to Japan, as I installed some Japan's software and the encode is wrong only if I change it to Japan.

Some related capture:
Though it shows 65001 after started, it didn't initiate correctly.
(I changed the font but it can't be applied.)
![image](https://user-images.githubusercontent.com/25456777/36965896-60054d2c-209e-11e8-90fc-5a1169e8c9e5.png)

![image](https://user-images.githubusercontent.com/25456777/36965960-95205d12-209e-11e8-89c9-062496ffaadc.png)

Opened:
![image](https://user-images.githubusercontent.com/25456777/36965995-a9c8b08e-209e-11e8-9334-e27ee11de4b6.png)

while using cmd.exe
![image](https://user-images.githubusercontent.com/25456777/36966139-1d954838-209f-11e8-9762-300e43a038ec.png)

**Comment by Ben67366** [comment] 2018-03-05 09:02
Continue
If I change the cmd.exe's properties to use font Ubunto mono. it will be okay then.
![image](https://user-images.githubusercontent.com/25456777/36966178-4175cfa2-209f-11e8-85a1-7bce386863b2.png)


![image](https://user-images.githubusercontent.com/25456777/36966198-57707eec-209f-11e8-80e5-abd8d8a887c5.png)

**Comment by mqudsi** [comment] 2018-03-05 20:27
@Ben67366 does this reproduce with zsh?

**Comment by Ben67366** [comment] 2018-03-07 09:04
No, didn't reproduce this with zsh.

![image](https://user-images.githubusercontent.com/25456777/37083122-e4e798a8-2231-11e8-8761-b7418e042813.png)

**Comment by EricWF** [comment] 2018-04-04 06:35
This also seems to occur with the builtin terminal on never versions of IDEA based IDEs. 
See https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-185523

**Comment by faho** [comment] 2018-04-04 14:40
@EricWF: Just to be clear, the linked bug report says:

>breaks things like echo and shell piping, since the additional character will be appended to the output!

Which isn't true - the character _is not_ part of the output of any particular command. Instead what happens is that fish executes whatever command you asked it to, then it prints that character (and some trickery) _to the terminal_. Piping is not affected.

Unless this is talking about some idea-specific integration where it reads contents of the terminal, but that would also break e.g. if color was involved.

-----

@Ben67366: Can you confirm that zsh is still doing the trick? E.g. try `echo -n $TERM`. Bash doesn't do this, so you won't see anything there.

**Comment by EricWF** [comment] 2018-04-04 17:29
@faho I tested and observed that behaviour writing that; it's not exactly hard to test. Perhaps the bug I'm experiencing is distinct from this one.

I'll re-confirm the behaviour I described reproduces and report back.

**Comment by EricWF** [comment] 2018-04-04 18:24
Yeah, it seems I was mistaken. I did `echo banana > /tmp/test.txt; and echo /tmp/test.txt`. Because I saw a arrow character at the end of the echo output, I assumed it was from the file. My mistake.

**Comment by EricWF** [comment] 2018-04-08 22:04
@faho Thanks work working on this! If you're feeling generous could you post your explanation on the IDEA bug? Hopefully that will help it get fixed quicker. (If not, I'm happy too -- but I'm not anywhere close to as knowledgeable about what's happening)

**Comment by devunt** [comment] 2018-04-30 18:50
I'm having exactly the same issue with my WSL installation on Windows 10, except that I'm using Hyper as my termimal emulator and my system locale is Korean. Is this issue fixed by 412c5ae?

**Comment by faho** [comment] 2018-09-22 09:53
I'm assuming this is fixed.

**Closed by faho** 2018-09-22 09:53 UTC
Labels: bug

**Comment by mqudsi** [comment] 2018-09-22 10:58
@faho this response is a little late, but in answer to 

>I'm unsure what, if anything, we should do here. I like the character, and feel like it says more than a simple "%" would. I don't think there is a great alternative character that doesn't also trigger this somewhere.

FWIW, the pilcrow (used in 412c5aeaa63caa3534a0b966e3ad510969904dc6) is an ascii character (0xb6) that's pretty much required for any font to implement, and is basically known as "the paragraph mark".

**Comment by nealot** [comment] 2019-02-10 10:52
I'm having the same problem with VSCode's integrated terminal on Linux, with the exception of ⏎ only preceding the first prompt. Is this something I should report to VSCode?

**Comment by wtdcode** [comment] 2019-02-28 12:46
Same here.
