### ISSUE TITLE
`fish_config`: Ability to preview the prompts in a custom font.

### ISSUE THREAD

**Issue by mandx** [fish-shell/fish-shell#2197] opened 2015-07-13 16:36 UTC
The preview prompt functionality of `fish_config` is very good, but it's lacking the option to choose a custom font to preview them. While it's nice to preview how the characters look with the selected prompt and colors, the main issue is that some people use themes that take advantage of the [Powerline fonts](https://github.com/powerline/fonts) but those prompts look wrong because of being presented with the browser's default monospace font.

**Comment by ridiculousfish** [comment] 2015-07-13 18:07
Nice catch.

**Comment by pickfire** [comment] 2015-07-14 07:12
And I think `fish_config` should also have the function to switch to a **git** directory to be able to show the prompt for git.

**Comment by ridiculousfish** [comment] 2015-07-14 07:43
You can just run it from a git directory and it will show you the prompt for that directory.

**Comment by pickfire** [comment] 2015-07-14 09:05
Yeah, but this may be better for **new** `fish` users and it can also like an example just like the colors.

**Comment by ridiculousfish** [comment] 2015-07-14 18:09
I think some UI for showing and switching the cwd might be nice, if you (or anyone) wanted to take a crack at it.

**Comment by mandx** [comment] 2015-07-14 23:32
I think we are talking about two small features:

- Select a custom font for the prompt preview, which I think this is doable using a bit of HTML/JS/CSS
- Switch the current working directory of the prompt preview, which I believe involves changing the config webserver code

Don't you think the second feature deserves its own ticket?

**Comment by ridiculousfish** [comment] 2015-07-14 23:37
Sure, feel free to peel it off, especially if you plan to take it on.

**Comment by krader1961** [comment] 2017-03-22 04:46
Closing as a duplicate of issue #3625.

The fish_config web UI will never be as good at emulating the behavior of running fish in a real terminal. Expending effort on trying to make it that good is somewhat silly. It would be far better to create a non-web based mechanism that actually ran within the user's terminal for configuring fish's behavior.

**Closed by krader1961** 2017-03-22 04:46 UTC
Labels: duplicate
