### ISSUE TITLE
`funced`/`funcsave` sometimes replaces `--argument-names` with `--argument`

### ISSUE THREAD

**Issue by t-nil** [fish-shell/fish-shell#10465] opened 2024-04-27 11:41 UTC
Fish version: 3.7.1
`uname -a`: Linux ra1n-desktop-manjaro 6.8.7-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Apr 17 13:26:06 UTC 2024 x86_64 GNU/Linux
`$TERM`: tmux-256color

Behaviour still exists in clean environment.

Reproduce: https://asciinema.org/a/CryfObrlR8EbQtBSAL0onnzVc

`--argument` is not documented as flag to `function`, but seems to work intuitively - as in, supply one `-a`/`--argument` per function argument, and they get parsed correctly.

`--argument-names` appearently works _the same as `--argument`_, which is unintuitive (because the naming suggests otherwise). Since it also gets replaced automatically, I assume there has been a deprecation once? Although I couldn't find anything in the changelog part of `man fish-doc`.

So should the documentation be updated to use `--argument`, or is there a correct way to supply a list to `--argument-names`?

**Comment by faho** [comment] 2024-04-27 11:59
Duplicate of #7341

**Closed by faho** 2024-04-27 11:59 UTC

**Comment by faho** [comment] 2024-04-27 12:19
We've inherited a getopt misfeature: It allows you to abbreviate long options as long as it's unambiguous.

So not just `function --argument` works, but also `function --arg` and even `function --a`.

The problem with this is of course that it breaks if you add more options - if we added `function --argument-values` any use of `function --argument` is suddenly ambiguous and won't work anymore.

So it's an awkward foot gun and we've discussed removing it.

**Comment by t-nil** [comment] 2024-04-27 13:35
Ok, thanks for the clarification! My two cents are that a shell which cares so deeply about explicit, readable code should not employ these syntax extensions.

What about the other points though? 
- `funced` or `funcsave` (I never tested exactly which cmd) changing `--argument-names` to `--argument` *by itself*, and
- `--argument-names` being awkwardly named (since it seems you can't supply a list of names but are supposed to use it multiple times for multiple vars).

Should I open multiple tickets? Or am I misinterpreting something?
