### ISSUE TITLE
Big Sur slow autocomplete

### ISSUE THREAD

**Issue by xrisk** [fish-shell/fish-shell#7588] opened 2020-12-30 14:47 UTC
fish version: 3.1.2
OS: macOS Big Sur 11.1 

This seems to be the same issue described in #6270 

Pressing Tab on a partially filled out commend (say gre) takes a long time. 
If I patch `__fish_describe_command` to do nothing, the issue is fixed. 

I have also reproduced it with `sh -c 'env HOME=$(mktemp -d) fish'`.

Let me know if more logs are needed to diagnose the problem.

I was under the impression that this specific issue had been patched in fish.  Is this a macOS regression?

**Comment by zanchey** [comment] 2020-12-30 14:49
This is a duplicate of #7511 which also describes a workaround.

**Comment by xrisk** [comment] 2020-12-30 14:49
apologies I had searched for Big Sur in the issue search and didn't find anything.

**Closed by zanchey** 2020-12-30 14:49 UTC
Labels: duplicate

**Comment by zanchey** [comment] 2020-12-30 14:53
No worries, it happens!
