### ISSUE TITLE
Can not find command(bug report)

### ISSUE THREAD

**Issue by Mabinogiysk** [fish-shell/fish-shell#6003] opened 2019-07-24 04:48 UTC
fish, version 3.0.2
system: CentOS7

Bug repeat:
My home directory: /data/user/
I added a path in $PATH like this: `export PATH=“~/dir/:$PATH”`, fish could not find command in ~/dir/, though which and bash shell did. Then I change it to `export PATH=“/data/user/dir/:$PATH”`, fish is able to find the command in dir.

**Comment by faho** [comment] 2019-07-24 05:09
Fish does not expand the ~ in quotes. We probably should for our "export" helper function, because it's explicitly for compatibility.

However, the fish-native way of setting this is `set PATH ~/dir $PATH`, and that will work.

**Comment by faho** [comment] 2019-07-24 06:01
Duplicate of #2310 

Note that that explains that this behavior is exclusive to *bash* - from my testing, zsh and e.g. dash will also break, so I can't recommend it to begin with.

**Closed by faho** 2019-07-24 06:01 UTC
