### ISSUE TITLE
Wrong directory test in __fish_list_current_token.fish

### ISSUE THREAD

**Issue by DarkPark** [fish-shell/fish-shell#10178] opened 2023-12-31 16:44 UTC
fish, version 3.6.0
Debian 6.1.0-16-amd64
xterm-256color

Type this in command line: `cd /etc/`
Put cursor at the end of the line and press `Alt+L` to get as expected a list of dirs and files in the `/etc`.
Ok. Now try to type `cd ~/documents/` put cursor at the end and press `Alt+L`.
Expected result: see `ls` for directory `~/documents/`
Actual result: see `ls` for current directory (not ~/documents/)

**Comment by faho** [comment] 2023-12-31 17:57
Duplicate of #9954

**Closed by faho** 2023-12-31 17:57 UTC
