### ISSUE TITLE
Feature request: Don't display already completed path components in the pager

### ISSUE THREAD

**Issue by thithib** [fish-shell/fish-shell#8617] opened 2022-01-05 21:12 UTC
I've been trying to move from zsh to fish for a few weeks now but one thing that still bothers me is the fact that **path components** that have already been completed (i.e. that appear on the command line that is being autocompleted, because they have been typed or selected previously) are displayed in the pager as part of the prefix string. I think this is superfluous and uselessly takes space. It makes the pager "too dense" and I find it really harder to distinguish the available completions.

For example, if I'm trying to open a file in `./very/long/path/to/directory`, which contains many files `a`, `b`, `c`, etc. I want to see:
```shell
$ vim ./very/long/path/to/directory/
a    b    c    d    e    f
```
when I hit `Tab`, not:
```shell
$ vim ./very/long/path/to/directory/
…irectory/a    …irectory/b    …irectory/c    …irectory/d    …irectory/e    …irectory/f
```
since what I really care for at this moment is **what path components are available for me to select next**, not the ones I've **already chosen**.

I set `fish_pager_color_prefix` to a dim color so it doesn't stand out too much: it's a little better since it's a bit easier to spot the suggested completions, but it's obviously not satisfying. Plus it also applies to the prefixes of command completions, which is not great.

Am I clear? If so, what do you think about that?
As far as I can tell, there's already a truncation of the prefix string when it's part of a path, so maybe the length of the truncated string could be made customizable so it's possible to set it to 0 to remove it? On the other hand, if I understand the fish philosophy correctly, such a specific setting wouldn't really belong here :/

**Comment by faho** [comment] 2022-01-05 21:14
Duplicate of #7883

**Closed by faho** 2022-01-05 21:14 UTC
