### ISSUE TITLE
Corrupted command line when prompt contains CSI sequences like \e[1m (on Linux)

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#531] opened 2013-01-20 08:26 UTC
Minimal case:

    function fish_prompt
        echo -n \e"[1m\$"
        echo -n \e"[m"
        echo -n " "
    end

After that, press up. The command line now looks like:

    $ fufunction fish_prompt
            echo -n \e"[1m\$"
            echo -n \e"[m"
            echo -n " "
        end

Interestingly, this doesn't happen with color sequences like `\e[32m`, which is why stock `fish_prompt` doesn't break the command line.

**Comment by zanchey** [comment] 2015-02-03 10:15
I can't reproduce this with current master build (df6f1e8) under gnome-terminal 3.4.1.1 on Linux with TERM set to `xterm-256color` or on the virtual console with TERM set to `linux`.

**Comment by faho** [comment] 2015-08-24 20:56
Can't reproduce either, so I'm assuming this has been fixed in the last 2 years.

**Closed by faho** 2015-08-24 20:56 UTC
