### ISSUE TITLE
String match with capturing group

### ISSUE THREAD

**Issue by m0nhawk** [fish-shell/fish-shell#6056] opened 2019-08-23 15:28 UTC
fish seems to broke the behavior of `string match`.

I'm trying to match the part of filename after `_` and before `.`:

```
➜ string match -r "_([^_]*)\." "very_nice_file_whatmatter.csv"
_whatmatter.
whatmatter
```

```
➜ string match -r "_[^_]*\." "very_nice_file_whatmatter.csv"
_whatmatter.
```

I found this issue #4925, but the behavior there is different than what I got.

Not sure if it's the bug or a feature I'm missing.

fish, version 3.0.2

**Comment by krobelus** [comment] 2019-08-23 19:44
This looks like expected behavior to me. You can add a filter to extract the capture group:
```fish
string match -r "_([^_]*)\." "very_nice_file_whatmatter.csv" | awk 'NR == 2'
```
(or `NR%2 == 0` if you have more inputs)

**Comment by m0nhawk** [comment] 2019-08-23 20:15
And was the behavior changed? Because the code in the linked issue ([comment](https://github.com/fish-shell/fish-shell/issues/4925#issuecomment-382710911)) yielding different result for me:

```
string match -r '/.*/' -- some/weird/stuff
/weird/
```

I know I can refine the output, but it looks like a regression or a bug, if it changed since that comment.

**Comment by faho** [comment] 2019-08-23 20:18
>Because the code in the linked issue (comment) yielding different result for me:

No, that was just an oversight. It was always "/weird/".

If you want to have just a certain part of the input, use `string replace`.

Also I'm preparing an additional "--groups-only" option to `string match` that will just print the capturing groups, not the full match as well.

**Comment by mqudsi** [comment] 2019-08-25 16:52
The full match is considered a group, every single regex implementation that I know of defines the entire match to be capture group 0, and further explicit capturing groups are numbered from there.

**Comment by m0nhawk** [comment] 2019-09-05 00:04
@mqudsi I *was* expecting it to be multiple outputs, but the issue confuses me and I wanted to clarify.

@faho The `--groups-only` argument would be awesome. Thanks! 👍

**Comment by mqudsi** [comment] 2019-09-07 16:48
I just ran into this with https://github.com/fish-shell/fish-shell/commit/912421f1cb61fca530fb501b9e6a904dc21e44d6, which could have been much shorter if there were some way to change the default behavior.

I don't think `--groups-only` goes far enough, and I think at the same time it is too rigid. I was giving this some thought in the shower, and I think I would prefer an extension to `string match -r` along the lines of `string replace -r` with an additional parameter describing what to output, e.g.

```fish
echo "foo bar baz" | string match -r 'foo (bar) baz' '$2' 
```

would only print the second group (the first explicitly captured group). To do this now requires using `string replace -r` and inverting the logic, e.g. you must explicitly capture and drop everything you *don't* want in the output string rather than printing only the things you *do* want, which is OK for the general case but does not work when you are trying to match multiple items per line, e.g.

```fish
# Try to extract the numbers found in each 'foo_x' occurence

# this prints the entire word each time, followed by the number
echo "foo1x foo2x foo3x" | string match -ar 'foo(\d)x'

# this prints the number only, but does not match more than once
echo "foo1x foo2x foo3x" | string replace -r '.*foo(\d)x.*' '$1'
# prints only the very last match `3`
```

You can hack around it by using `string match -ar` and constraining the pattern to not consume more than one match, e.g. in this case `string replace -ar '\b\S*foo(\d)x\S*' '$1'` but a) it is not always possible to do so, e.g. in the case of patterns spanning multiple words/values, and b) it is extremely awkward.

My suggestion is going with something like

```fish
echo "foo1x foo2x foo3x | string match -ar 'foo(\d)x' '$1'
```

or 

```fish
echo "foo1x foo2x foo3x | string match -ar 'foo(\d)x' --print '$1' # or similar
```

to tell `string match` to output only a transformation of the match based off the parameter, rather than emitting all captures or the all input plus the captures.

**Comment by faho** [comment] 2019-09-07 17:30
Your suggestion is `string replace -er`.

Mahmoud Al-Qudsi <notifications@github.com> schrieb am Sa., 7. Sep. 2019,
17:48:

**Comment by faho** [comment] 2021-07-14 12:44
> I think I would prefer an extension to string match -r along the lines of string replace -r with an additional parameter describing what to output, e.g.

This isn't possible. What should

```fish
string match -r 'foo (bar) baz' '$2'  "foo bar baz"
```

do? Anything after the first parameter is currently a "string" to act on, this can't be optional or it's ambiguous.

Anyway, I fail to see how --groups-only wouldn't be enough, this would just be

```fish
echo "foo bar baz" | string match -r --groups-only 'foo (bar) baz'
```

> `echo "foo1x foo2x foo3x" | string replace -r '.*foo(\d)x.*' '$1'`

Depending on what you want,

```fish
echo "foo1x foo2x foo3x" | string replace -ar 'foo(\d)x' '$1'
```

would work, which yields one string "1 2 3".

>`echo "foo1x foo2x foo3x | string match -ar 'foo(\d)x' '$1'`

is

```fish
echo "foo1x foo2x foo3x | string match -ar --groups-only 'foo(\d)x'
```

which would yield "1", "2" and "3".

-----

Anyway, I gotta get that branch cleaned up and merged.

**Closed** 2021-07-16 18:31 UTC
Labels: enhancement

**Comment by faho** [comment] 2021-07-16 18:50
Alright, I just added `string match --group-only`. It's pretty straight-forward, just removes the entire match from consideration.

This manages to solve all examples people came up with here, as far as I see, so I don't see the need for further transformations. Of course we can still add that later.
