### ISSUE TITLE
No output if string length == 1

### ISSUE THREAD

**Issue by dxlr8r** [fish-shell/fish-shell#3900] opened 2017-03-16 15:27 UTC
```
# fish --version
2.5.0
```

I've notice that I don't get any output to buffer if output's string length is 1:

`echo -ns _`

No output

While this works as it should:

`$ echo -ns __
__`

Tested on macOS Sierra with Terminal, iTerm and xterm. Locally and to RHEL 7 with two accounts (my personal, and one vanilla fish config test account).

**Comment by faho** [comment] 2017-03-16 15:30
This is a duplicate of #3850. If it's not fixed with current git master, please yell!

**Closed by faho** 2017-03-16 15:30 UTC
