### ISSUE TITLE
Slow tab command completion in macOS Big Sur

### ISSUE THREAD

**Issue by mattdutson** [fish-shell/fish-shell#7565] opened 2020-12-21 02:01 UTC
Fish version 3.1.2
macOS 11.1 Big Sur (Darwin Kernel 20.2.0)
Terminal.app

Tab command autocompletion is slow since updating to macOS Big Sur. For example, pressing tab after typing `ch` (beginning of `chmod`) freezes the shell for ~5 seconds.

This seems to closely related to #6270. Running the Fish profiler via `fish --profile` shows that a large amount of time is being spent invoking `apropos`. Maybe a temporary solution is just to extend that workaround (conditional on `test "$darwin_version[1]" = 19 -a "$darwin_version[2]" -le 3`) to cover Darwin 20.

**Comment by faho** [comment] 2020-12-21 06:32
Duplicate of #7563

**Closed by faho** 2020-12-21 06:32 UTC
