### ISSUE TITLE
git add completer won't offer a dirty file if that file has staged changes

### ISSUE THREAD

**Issue by sanga** [fish-shell/fish-shell#5691] opened 2019-02-23 06:50 UTC
fish: 3.0.2
uname -a: Linux galois 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$TERM: xterm-256color

Running via `sh -c 'env HOME=$(mktemp -d) fish'` gives this:

```
git status
On branch improve_fish_completions
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   sway.fish

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   sway.fish

tsampson@gal /h/t/C/E/s/c/fish> vim swaymsg.fish
tsampson@gal /h/t/C/E/s/c/fish> vim swaynag.fish
tsampson@gal /h/t/C/E/s/c/fish> git add sway
swaymsg.fish  (Modified file)  swaynag.fish  (Modified file)
```

Observe from ^ that swaymsg.fish and swaynag.fish are offered as completions but sway.fish is not

**Comment by faho** [comment] 2019-02-23 07:57
Duplicate of #5648

**Closed by faho** 2019-02-23 07:57 UTC
