### ISSUE TITLE
Program doesn't work in subcommand

### ISSUE THREAD

**Issue by JoshCheek** [fish-shell/fish-shell#1949] opened 2015-02-17 18:04 UTC
Fish Version.

``` sh
$ fish --version
fish, version 2.1.1
```

[This](https://github.com/postmodern/chruby/blob/v0.3.9/bin/chruby-exec) program does not work in a subcommand.

``` sh
# it works when run directly
$ /usr/local/bin/chruby-exec 2.2.0 -- ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]

# it does not work when run in a fish subcommand
$ echo (/usr/local/bin/chruby-exec 2.2.0 -- ruby -v)


# it works when run in a bash subcommand
$ bash -c 'echo `/usr/local/bin/chruby-exec 2.2.0 -- ruby -v`'
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]

# it works when other programs run it or exec it
$ ruby -e '
  puts `ruby -v`
  puts `exec /usr/local/bin/chruby-exec 2.2.0 -- ruby -v`
  exec "/usr/local/bin/chruby-exec", "2.2.0", "--", "ruby", "-v"
'
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]

# it does work when used in a conditional
$ if /usr/local/bin/chruby-exec 2.2.0 -- ruby -v
       echo success
   else
       echo failure
   end
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
success

# it does work when used in a pipeline
$ echo a b c | /usr/local/bin/chruby-exec 2.2.0 -- ruby -e 'p $stdin.read' | cat
"a b c\n"
```

**P.S.** Is "subcommand" the right word for this?

**Comment by ridiculousfish** [comment] 2015-02-17 18:07
What does chruby do? Probably it expects to be in the foreground process group, which makes this basically the same as #1362.

"Command substitution" is the usual term, but I have to confess that subcommand is shorter and easier to say/type :)

**Comment by JoshCheek** [comment] 2015-02-18 13:20
Chruby allows me to switch which ruby is active in my shell. Chruby-exec runs a command with the environment set to find a specific Ruby. This way I can write scripts for my dotfiles against a Ruby specifically dedicated to them (ie install packages there, and my script will work even if the Ruby I'm using doesn't have it)

Based on what that one said, I looked at my processes, and they are just chillin in the bg.

```sh
$ echo (/usr/local/bin/chruby-exec 2.2.0 -- ruby -v)

$ ps aux | grep -i chruby | tail -1
      josh            68858   0.0  0.0  2435416    868 s015  T     5:46AM   0:00.01 /bin/bash -i -l -c chruby 2.2.0  && ruby -v

$ jobs
Job	Group	State	Command
2	68858	stopped	/usr/local/bin/chruby-exec 2.2.0 -- ruby -v
```

Looks like it comes from [this](https://github.com/postmodern/chruby/blob/v0.3.9/bin/chruby-exec#L38) line (which has since changed [master](https://github.com/postmodern/chruby/blob/master/bin/chruby-exec)). Which makes it look like fish is reporting its stdin as a tty, causing it to launch bash with the `-i` flag set, for interactive mode, which triggers the behaviour described in the other post.

```sh
$ man test | sed -n '/-t/p'
       o -t FD returns true if the file descriptor FD is a terminal (TTY).
$ echo | bash -c 'test -t 0 && echo tty || echo file'
file

$ echo (bash -c 'test -t 0 && echo tty || echo file')
tty
```

**Comment by ridiculousfish** [comment] 2015-03-25 00:08
Nice diagnosis @JoshCheek. fish is telling the truth here (fd 0 is a tty), since fish doesn't use subprocesses to run command substitutions. This is related to #1228.

**Comment by nh2** [comment] 2016-09-27 16:37
In #3212 @faho said:

> This is the same thing as #1949, if you squint a bit. The root cause is that we are claiming stdin is a tty, while it's not actually connected.
> Sorry for the inconvenience.

Can you explain me a bit if this is a bug, if you'd like it to be different (e.g. to not go to background), or if this a design choice?

Like in #3212, I have a program that just suspends when used like `echo (myprogram)`. I'd like to fix that, how would I go about that?

**Comment by faho** [comment] 2016-09-27 17:17
>Can you explain me a bit if this is a bug, if you'd like it to be different (e.g. to not go to background), or if this a design choice?

As far as I can see, it's not enabling anything but breaking plenty of applications. So I consider it a bug.

**Comment by JoshCheek** [comment] 2016-09-27 17:31
> Like in #3212, I have a program that just suspends when used like echo (myprogram). I'd like to fix that, how would I go about that?

See if delegating to test command works ([example](https://github.com/JoshCheek/dotfiles/blob/779361b35dd487292735832b7c7a7fab7f87d3d9/fish/functions/inspect.fish#L14)) (default `test` is a builtin)

**Comment by nh2** [comment] 2016-09-27 18:28
@JoshCheek just to be clear, you mean that my program probably uses `test`, from fish being my default shell? (`myprog` is not a shell script)

**Comment by JoshCheek** [comment] 2016-09-27 18:44
Ahh, yeah, I'm just wrong. I don't know of a way to get around this other than to invoke it differently.

**Comment by faho** [comment] 2017-03-29 15:15
This _is_ a duplicate of #1362. Please test #3922, which should fix it.

**Closed by faho** 2017-03-29 15:15 UTC
Labels: bug
