### ISSUE TITLE
After installing bobthefish theme, i get this on my iterm [I]  !  ~ 

### ISSUE THREAD

**Issue by sanyamagrawal** [fish-shell/fish-shell#3245] opened 2016-07-16 09:19 UTC
<img width="430" alt="screen shot 2016-07-16 at 2 49 22 pm" src="https://cloud.githubusercontent.com/assets/2134681/16893931/8575239a-4b64-11e6-95d6-38a9378f32bb.png">

How do i fix this issue?

**Comment by floam** [comment] 2016-07-16 09:27
When you filed this bug, there was a step there with instructions to test that this isn't a problem a third party customization, and for the version of fish you are trying this with.  Could you please provide those details and explain the issue?

**Comment by krader1961** [comment] 2016-07-16 19:21
You didn't explain what the problem is so I'm going to guess you don't understand why you're seeing a square box with a question-mark inside it. That's the symbol you see when the font you're using doesn't support a particular unicode character. If the problem is unique to the bobthefish theme we'll try to help but you'll probably get better help from the author of that theme of other OMF users.

**Comment by brj** [comment] 2016-07-19 18:35
@sanyamagrawal Install https://github.com/powerline/fonts and then select the font you like in your terminal.

**Comment by floam** [comment] 2016-07-31 05:51
Did you figure this out @sanyamagrawal?

**Comment by krader1961** [comment] 2016-08-05 03:29
No updates since the issue was opened three weeks ago so closing.

**Closed by krader1961** 2016-08-05 03:29 UTC
Labels: needs-more-info, question

**Comment by annata83** [comment] 2019-01-16 06:07
Same Here!
![fish-powerlineerror](https://user-images.githubusercontent.com/18301363/51229617-c592ae00-193b-11e9-8927-108b89940b24.png)

**Comment by ridiculousfish** [comment] 2019-01-19 23:48
Are you using Powerline font? What font are you using?

**Comment by kclemens** [comment] 2020-02-18 13:42
I ran into the same problem - the boxes with question marks went away for me after enabling Preferences -> Profiles -> Text -> Use built-in Powerline glyphs in iTerm2

**Comment by iMonZ** [comment] 2020-06-01 20:15
> I ran into the same problem - the boxes with question marks went away for me after enabling Preferences -> Profiles -> Text -> "Use built-in Powerline glyphs" in iTerm2

This worked for me too!
And I tried to reinstall everything and deleted all of the configs
