### ISSUE TITLE
Autocompletion crashes for special characters

### ISSUE THREAD

**Issue by JanczarKurek** [fish-shell/fish-shell#5141] opened 2018-08-11 18:57 UTC
I'm using fish 2.2 and x-term256colors.

Fish has problem with autocompl when using certain characters. Writing
`cd \(`
and then tapping tab leads to following error message:

> Unexpected end of string, parenthesis do not match                                                                                                                               0 < 20:51:44
> - (line 1): begin; printf "%s\n" (*/ 
>  ;end <&3 3<&-
>                                  ^
> from sourcing file -
> 	called on line 60 of file /usr/share/fish/functions/eval.fish
> 
> in function 'eval'
> 	called on line 45 of file /usr/share/fish/functions/__fish_complete_cd.fish
> 
> in function '__fish_complete_cd'
> 	called on standard input
> 
> in command substitution
> 	called on standard input
> 
> source: Error while reading file '-'
> 
>

**Comment by faho** [comment] 2018-08-11 19:00
Duplicate of #952, fixed 3 years ago by 0a99772572ab8632f103f05570da707683980d17.

>I'm using fish 2.2 and x-term256colors.

You _really_ want to upgrade - 2.2 is ancient.

**Comment by JanczarKurek** [comment] 2018-08-11 19:01
Yeah, sorry I always forget how ancient mint linux repos can be. Thx for answer anyway, just upgraded.

**Closed by faho** 2018-08-11 19:00 UTC
