### ISSUE TITLE
cd .. || exit breaks shell

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8408] opened 2021-11-06 08:20 UTC
Fish version: 3.3.0 (built from source)
OS version: Linux Mint 20.2 Cinnamon

When I enter `cd .. || exit` shell freezes. In Bash 5.0 everything works normally.

**Comment by EmilySeville7cfg** [comment] 2021-11-06 08:22
`builtin` helps to avoid this issue.

**Comment by floam** [comment] 2021-11-06 08:30
How did you encounter this? And, `cd ..`, what does that output for you?  No errors about shadowing a variable?

**Comment by EmilySeville7cfg** [comment] 2021-11-06 08:33
> How did you encounter this? And, cd .., what does that output for you? No errors about shadowing a variable?

I simply typed it in my terminal. :) Nothing is printed in output and no errors about shadowing happened.

> Did you recently change your configuration?

Yes, my current configuration is [here](https://github.com/Console-Utils/fish-configs/tree/feature/14).

> Does it actually freeze or does it exit?

The first one.

**Comment by floam** [comment] 2021-11-06 08:33
> I simply typed it in my terminal. :) Nothing is printed in output and no errors about shadowing happened.

I mean, if you do just a `cd ..`, not a `cd .. | exit` - do you get an error? What is $status?

**Comment by floam** [comment] 2021-11-06 08:34
Do you know how to connect a debugger to the process, and generate a backtrace?

**Comment by EmilySeville7cfg** [comment] 2021-11-06 08:35
> > I simply typed it in my terminal. :) Nothing is printed in output and no errors about shadowing happened.
> 
> I mean, if you do just a `cd ..`, not a `cd .. || exit` - do you get an error? What is $status?

Everything works normally when `cd ..` alone. $status is 0.

**Comment by EmilySeville7cfg** [comment] 2021-11-06 08:36
> Do you know how to connect a debugger to the process, and generate a backtrace?

No. But if it allow me to solve this issue I want to understand how.

**Comment by floam** [comment] 2021-11-06 08:44
First, can you check if this is fixed in 3.3.1? It could possibly be the prompt repaint issue.

**Comment by EmilySeville7cfg** [comment] 2021-11-06 09:36
It works perfectly in 3.3.1.

**Comment by floam** [comment] 2021-11-06 09:41
Cool!

Closing as a likely duplicate of #8088.

**Comment by floam** [comment] 2021-11-06 09:42
Wait, it works or it fails?

**Comment by EmilySeville7cfg** [comment] 2021-11-06 09:47
Now it works (I've reopened shell again). Strange things happens. If this problem arise again I will create new issue.

**Comment by floam** [comment] 2021-11-06 10:34
If it happens again just come back to this issue.

**Closed by floam** 2021-11-06 10:34 UTC
Labels: needs more info
