### ISSUE TITLE
Non-existent completion breaks prompt slightly

### ISSUE THREAD

**Issue by plttn** [fish-shell/fish-shell#3093] opened 2016-05-30 22:51 UTC
On 2.3.0, trying to complete a completion that doesn't exist (ex: `git ---`)  spawns a new line/prompt, rather than just flashing the invalid suggestion. 
### Reproduction Steps:
1. Enter a completion that doesn't exist, `git ---`
2. Hit tab
### Expected behavior:

Completion background should flash
### Observed behavior:

Prompt breaks slightly: 
<img width="491" alt="screen shot 2016-05-30 at 3 44 00 pm" src="https://cloud.githubusercontent.com/assets/7369280/15659365/4764d952-267e-11e6-97a6-ca913ea0335c.png">
### Additional information:

Noticed this change with v2.3.0.

---

Fish version: 2.3.0

Operating system: El Capitan, brew

Terminal or terminal emulator: Terminal.app

**Comment by faho** [comment] 2016-05-30 23:33
I can't reproduce it. Can you try with a different terminal? I hear iTerm2 comes heavily recommended.

One possible cause is c79ade9627b116a0dc4aecd27d1ff61e68fe595b - we send a terminal bell when there's no completion, and it's possible your terminal reacts weirdly to that.

_Or_ it's another case of us miscalculating the width of something - can you try resizing the terminal? And IIRC there's some option about "ambiguous width characters" - can you switch that?

**Comment by plttn** [comment] 2016-05-30 23:36
It's reproducing on iTerm as well.

I might have something going on in my config folder functions (i've
overridden one or two semi-core functions).

**Comment by krader1961** [comment] 2016-05-30 23:39
I can't reproduce on OS X using iTerm2. I don't have a right prompt which might be a factor.

**Comment by plttn** [comment] 2016-05-30 23:41
Looks like I can narrow the issue down to something in fisherman. I'll take
a look at what's causing it in there, but it's not a fish-shell core issue.

**Comment by faho** [comment] 2016-05-30 23:46
Keep us updated, then. I'm not sure how a script would be doing this.

**Comment by plttn** [comment] 2016-05-30 23:49
It was most likely a version conflict coming from 2.2.0 and the fisherman I had installed on that, to something in 2.3.0. Nuked my fisher folder in `~/.config` and started over with installing, and it's working fine now.

**Comment by plttn** [comment] 2016-05-30 23:58
I lied. I'm getting the feeling it's definitely an issue with fisherman. Something it's hooking into for any theme is causing the bell jump.  Doing some digging on what it would possibly be.

**Comment by faho** [comment] 2016-05-31 00:01
Well, which prompt are you using? Or can you upload your config somewhere (screened for personal info)?

**Comment by plttn** [comment] 2016-05-31 00:04
I'm using scorphish installed via [fisherman](https://github.com/fisherman/fisherman) (and nothing else). If I don't have scorphish loaded via fisher, the completion bell doesn't break the terminal. If I load scorphish, it breaks the terminal.

**Comment by faho** [comment] 2016-05-31 15:55
@pittn: I can't reproduce with https://github.com/oh-my-fish/theme-scorphish (AFAIK that's the scorphish repo). Can you try to narrow it down to a part of that? Try _just_ the fish_prompt function (i.e. without the right prompt, the greeting and the title), and then try cutting that some - there's a lot it reacts to that might be different on your system than mine (I don't have ruby or virtualenv).

**Comment by plttn** [comment] 2016-05-31 17:20
FWIW, It occurs with scorphish being installed from OMF as well, and doesn't occur with bobthefish, so I think this is some rare edge case with the theme itself, and not any interaction between fisherman/fish.

**Comment by faho** [comment] 2016-05-31 18:45
> It occurs with scorphish being installed from OMF as well

It's the same thing. The bits are identical.

>Looks like multiline prompts freak out, single line prompts don't. 

Does it freak out on _other_ multiline prompts?

**Comment by plttn** [comment] 2016-05-31 18:50
Yeah, it also occurs on `nelsonjchen`.

**Comment by faho** [comment] 2016-05-31 19:07
Okay, if you execute

```fish
functions -e fish_right_prompt
function fish_prompt
    echo $PWD
    echo ">"
end
```

does it still occur?

Also, do you have the "Treat ambiguous-width characters as double width" option in your terminal checked (see #2451)?

**Comment by plttn** [comment] 2016-05-31 19:42
With that prompt, the issue still occurs. I have ambiguous-width characters as double width off.

**Comment by plttn** [comment] 2016-06-23 03:03
FWIW, the issue still occurs when I ssh into my Mac from a Windows machine, so I don't think it's an interaction between fish and the terminal.

**Comment by plttn** [comment] 2016-06-24 01:17
Also, it's the same erroneous output as #3074, so probably tied together somehow?

**Comment by lfiolhais** [comment] 2016-06-24 09:14
Can reproduce with iTerm2 (3.0.3) in OS X (10.11.5) with fish built from master and [`simple-ass-prompt`](https://github.com/lfiolhais/theme-simple-ass-prompt).

**Comment by faho** [comment] 2016-06-24 11:47
@plttn, @lfiolhais: Since all of the themes you've been reporting have a greeting, a prompt, a right prompt and a title function, we need to narrow this down to one of those.

The prompt and right prompt can't be it because apparently the issue also happens with no right prompt and the simplest of prompts, and the greeting seems unlikely (since it's a one-shot thing). So:

Can you please test this without the title function?

**Comment by lfiolhais** [comment] 2016-06-24 15:46
Tested without a title and it still occurs.

**Comment by plttn** [comment] 2016-06-24 16:03
I just redid the test prompt you did, with `fish_title` and `fish_right_prompt` being unset, and it still occurs.

**Comment by plttn** [comment] 2016-06-30 00:39
Interestingly enough, I get the same erroneous results if I zoom a pane in tmux, on a device that wasn't exhibiting that behavior outside of tmux zooming. I know you mentioned something about the width not being calculated properly, is that still a possible cause @faho?

**Comment by lfiolhais** [comment] 2016-07-01 16:31
I've tested on my Rpi and this problem doesn't occur. It might be OS X specific...

**Comment by plttn** [comment] 2016-07-04 04:06
Still occurring in v2.3.1.

**Comment by krader1961** [comment] 2016-08-05 05:16
FWIW, I can now reproduce this. I started a iTerm2 (latest and greatest 3.0.20160711-nightly) and macOS bog standard Terminal.app. Each window was 80 columns wide. I then ran

```
functions -e fish_right_prompt
function fish_prompt
    echo $PWD
    echo ">"
end
```

Followed by `git ---` then [tab]. You can see this at [asciinema](https://asciinema.org/a/bpktmxppb7gz08nusrc829v82). The screen does flash but I also get a new prompt. Note that the asciinema capture shows a terminal that is 50 columns wide but the width doesn't appear to matter as I can reproduce with an 80 column wide terminal.

I tracked this down to commit c79ade9. If I revert the addition of `writestr(L"\a");` by that change against git master the problem disappears. In fairness to @floam I don't see an obvious problem with his change even with the knowledge it has introduced this problem. I suspect it is due to the same MS Windows problem I fixed with commit 82c56bc64b5038d5d5b6fcf49d1ceb9560447790. That is, the issuance of the "bell" character is modifying the tty timestamp that then causes fish to think it needs to issue a fresh prompt.

**Comment by krader1961** [comment] 2016-08-05 05:45
I've confirmed that the `writestr(L"\a");` introduced by commit c79ade9 is causing function `s_check_status()` in *src/screen.cpp* to think the terminal content has changed without fish's knowledge. TBD is how to fix that. Function `s_save_status()` is private to *src/screen.cpp* and thus not directly available to `reader_flash()` in *src/reader.cpp*. It is only indirectly available via `s_write()` which is a public symbol with a very complex signature.

**Comment by floam** [comment] 2016-08-06 05:41
Aw, darn!

**Comment by mqudsi** [comment] 2018-09-19 22:08
I was just about to tackle this but I think @ridiculousfish beat me to it in e6863a9.

**Closed by mqudsi** 2018-09-19 22:08 UTC
Labels: bug
