### ISSUE TITLE
Feature request: smart historical order

### ISSUE THREAD

**Issue by log69** [fish-shell/fish-shell#7712] opened 2021-02-14 09:57 UTC
Dear All,

Thanks for this great piece of tool. I'd like to ask for a feature which would greatly further increase the time it saves for the users.

When storing history, you could store for all the commands the number of times they were used in the past. Let this variable be "n". Along with this, you could also store the time stamp in seconds when they were used in the past. Let this variable be "t".

When offering a command by the pattern matches of the already typed letters from the historical info, you could show these commands by the order of their points, starting with the highest one. And the point for each command can be calculated as n times t:

n * t

This would be awesome because this would automagically weight their orders with geometric mean every time you type anything.

When building this list you could also favor those and bring them to the front that are not older than a preset time, say 30 days. This way the trend would be automatic too, but you'd still have all the past commands, only in a smarter order.

After the list is ordered by the above, you would then take from it only the command text, and then make it unique by keeping their order. So we have the final result.

See my example code below in Ruby, testing is still needed. Cheers.

	# return the most important commands from the list by their recency and their numbers of appearence
	# input:
	#   list is a 2d array where time is a timestamp in seconds: [ [ command, time ], [ command, time ], ... ]
	#   max_days is an integer in days to favor the commands within this recent time interval
	# output is a 1d array: [ command, command ... ]
	def sort_by_importance( list, max_days = nil )
		# count all the same commands
		# this part can be eliminated if this number is stored for every command by default
		d = {}
		list.each{|x|
			c = x[0]
			d[c] = ( d[c] ? d[c] + 1 : 0 )
		}
		# calculate their points and sort them by that
		res = list.map{|c,t|
			# add 1 to the number of times the commands were used so the multiplication will never be zero
			n = d[c] + 1
			point = n * t
			# add more weight to the most recent ones if required
			# let this weight be big enough to surely bring the commands within these days to the front of the list
			point *= 1000000  if (( Time.now.to_i - t ) / 3600 / 24 ) <= max_days
			return [ n * t, c ]
		}.sort.reverse
		# make result unique by taking only one command from the same ones
		res.map!{|x| x[1] }.uniq!
		return res
	end

**Comment by faho** [comment] 2021-02-14 10:10
Duplicate of #2398

**Closed by faho** 2021-02-14 10:10 UTC

**Comment by log69** [comment] 2021-02-14 10:15
@faho - I don't see it as an exact duplicate first because I provide an example solution, and second because the procedure described here is also different. The reasoning there in the comment also fails. Please kindly reopen this because otherwise a valued info gets lost, or at least write some useful comment.

**Comment by faho** [comment] 2021-02-14 10:56
>I don't see it as an exact duplicate first because I provide an example solution,

You don't - your example code is in *ruby*, which we use exactly nowhere. That means it's useless.

>and second because the procedure described here is also different.

The procedure isn't important. Both things deal with history storing the execution count, so we'll collapse both into the one issue. If we didn't do that, we'd have 5000 open issues.

>Third is that I provide a much smarter ordering.

And that can be handled once the execution count is actually *in*, so for now it's at most a part of the idea of adding execution count.

I'm also always wary of smart ordering, because it is unpredicable, which usually makes it *worse* than simple ordering (alphabetically or chronologically). There's a reason e.g. my phone homescreen is ordered alphabetically.

But that, again, can be handled once somebody implements the execution count mechanic.

**Comment by log69** [comment] 2021-02-14 11:42
Smarter ordering makes the hit and miss ratio better on longer time interval. And since you may forget what the last commands' order were from yesterday, then the simple chronological algo does not help you. And the execution count does not consider the trends in usage and may be pretty burdensome after a while when the usage trends and types of commands have changed long ago. The shell will just keep offering commands that will never be needed anymore.

More better features (without overdeveloping it of course) may fulfill more user requirements., Anyways, this is up to personal preference.

**Comment by log69** [comment] 2021-02-14 12:20
Just for the records if someone needs it, I've updated the algo:

	# return the most important values from the list by their recency and their numbers of appearence
	# input is 2d array: [ [ value, timestamp ], [ value, timestamp ], ... ]
	# output is a 1d array: [ value, value ... ]
	def sort_by_importance( list )
		time = Time.now.to_i
		# count all the same values
		# this part can be eliminated if this number is stored for every value by default
		count = {}
		time_max = nil
		time_min = nil
		list.each {|v,t|
			count[v] = ( count[v] ? count[v] + 1 : 0 )
			time_max = t  if not( time_max ) or time_max < t
			time_min = t  if not( time_min ) or time_min > t
		}
		# calculate their points and sort them by that
		temp = list.map {|v,t|
			# add 1 to the number of times the values were used so the multiplication will never be zero
			n = count[v] + 1
			# calculate weight with geometric mean which is multiplication
			# this way the units and ranges of the separate items do not matter
			# also normalize time to [0..1] and raise it to power to favor more recent values
			# plust add 1 to avoid zeros in mutliplication
			t_norm = 1
			t_norm = (( t - time_min ).to_f / ( time_max - time_min )) ** 7 + 1  if ( time_max - time_min ) > 0
			[ n * t_norm, v ]
		}.sort.reverse
		# make result unique by taking only one value with top points from the same ones
		res = []
		temp2 = {}
		temp.each {|p,v|
			if not( temp2[v] )
				temp2[v] = 1
				res << v
			end
		}
		return res
	end

**Comment by log69** [comment] 2021-02-14 13:20
For the record if someone needs it, I've updated and simplified my algo:

	# return the most important values from the list weighted by their recency and their numbers of appearance
	# input is 2d array: [ [ value, timestamp ], [ value, timestamp ], ... ]
	# output is 1d array: [ value, value ... ]
	# geomean is the function of geometric mean
	def sort_by_importance( list )
		d = {}
		list.each {|v,t|
			d[v] = []  if not d[v]
			d[v] << t
		}
		res = d.map{|v,t| [ geomean(t), v ] }.sort_by{|x,v| x }.reverse.map{|x,v| v }
		return res
	end

Testing it on random data with values [0,1,2] and timestamps (ordered by timestamp and top is more recent):

[[2, 1613221601],
 [0, 1612444001],
 [0, 1612012001],
 [1, 1611839201],
 [0, 1611752801],
 [0, 1611061601],
 [0, 1610975201],
 [1, 1610111201],
 [1, 1609679201],
 [2, 1609160801],
 [1, 1608469601],
 [1, 1608210401],
 [1, 1607432801],
 [0, 1607260001],
 [1, 1606914401],
 [0, 1606568801],
 [2, 1605704801],
 [1, 1605618401],
 [1, 1605272801],
 [0, 1604840801]]

There are 9 appearances of value 1 in it, 8 appearances of 0 and 3 appearances of 2.

Chronological order would be [2, 0, 1], counting order would be [1, 0, 2] and the geometrically weighted result of the above algo is [0, 2, 1]

**Comment by zanchey** [comment] 2021-02-14 14:00
I thought we'd talked about frecency in the past, but perhaps not. My gut feeling is that it seems like a useful addition but it makes the behaviour more unpredictable or magic. It's also potentially quite non-performant. There are some early discussions of the Firefox implementation that focus on performance, and I think it is part of the reason the Chrome Omnibox is such a terrible user experience (because results are not available when the list is drawn, it can be reordered while being drawn, which means you can go to tap or click one thing and it suddenly changes to another).

As @faho says, this requires #2398 but goes beyond it, so I'd be tempted to leave it open as an RFC for a little while.
