### ISSUE TITLE
multiline prompt issues with keystrokes: alt-left, alt-right, alt-w

### ISSUE THREAD

**Issue by doubleloop** [fish-shell/fish-shell#2079] opened 2015-05-19 18:15 UTC
Everything works fine on one line prompts.
When I set it to 2 lines, the resulting output of mentioned keystrokes are overlapped with prompt (alt-right alt-left when used as moving forward/backward in the directory history)

version 2.1.2

**Comment by Boudin** [comment] 2015-05-20 11:06
Same problem here.
I tried with both version 2.1.2 and current master.

My prompt is on 3 lines (an empty one, user + hostname + cwd, command line)
Here's what a ls looks like
```

boudin@boudin-portable /home/boudin/chdkptp  
> ls
COPYING  README-OSX.TXT  README-RASPI-LIBS.TXT  README-RASPI.TXT  README.TXT  THANKS.TXT  USAGE.TXT  chdkptp*  chdkptp-sample.sh*  lua/

boudin@boudin-portable /home/boudin/chdkptp  
> 
```

And here's what a <CTRL>+L looks like
```

boudin@boudin-portable /home/boudin/chdkptp  
> 
boudin@boudin-portable /home/boudin/chdkptp  T  README-RASPI.TXT  README.TXT  THANKS.TXT  USAGE.TXT  chdkptp*  chdkptp-sample.sh*  lua/
> 
```

**Comment by ridiculousfish** [comment] 2015-05-20 17:55
What operating system and terminal are you using?

**Comment by Boudin** [comment] 2015-05-20 17:59
I'm on Gentoo. I've tried with urxvt and sakura.

**Comment by doubleloop** [comment] 2015-05-22 14:49
I am on Debian, using standard GNOME Terminal (3.14.1)

**Comment by faho** [comment] 2016-03-06 13:53
This needs to be re-tested for 2.2.0 (and 2.3.0).

**Comment by Boudin** [comment] 2016-03-08 16:22
The problem is still here on either 2.2.0 or master

**Comment by Boudin** [comment] 2016-11-22 23:14
The problem seems to be fixed in the current master

**Closed** 2016-11-23 02:28 UTC
