### ISSUE TITLE
Handle multi-line prompts when Control-C'ing

### ISSUE THREAD

**Issue by ewen-lbh** [fish-shell/fish-shell#7713] opened 2021-02-14 12:05 UTC
<dl>
<dt>fish version
<dd>3.1.2
<dt>operating system
<dd>Linux 5.9.16-1-MANJARO x86_64 GNU/Linux
<dt>terminal
<dd>xterm-kitty
</dl>

Trying without any third-party customization is pointless since the default prompt is not multi-line.

Here's what it looks like: [![asciicast](https://asciinema.org/a/Z9LLRuDAiBxUCQHBJrzHMumfJ.svg)](https://asciinema.org/a/Z9LLRuDAiBxUCQHBJrzHMumfJ)

**Comment by faho** [comment] 2021-02-14 12:23
Duplicate of #3550

**Closed by faho** 2021-02-14 12:23 UTC

**Comment by faho** [comment] 2021-02-14 12:26
> Trying without any third-party customization is pointless since the default prompt is not multi-line.

The reason we ask you to try without third-party customization is so you reduce the issue to what is actually necessary - is this caused by some plugin (in which case it might be a bug in that plugin), or is having any multi-line prompt enough?

So in this case you'd disable customization and try something like

```fish
function fish_prompt
    echo one
    echo two
end
```

The simplest possible multi-line prompt. And as it happens this was caused by the same thing as #3550 and was fixed in fixing it, so I've closed this as a duplicate of that.

**Comment by ewen-lbh** [comment] 2021-02-14 15:05
> The reason we ask you to try without third-party customization is so you reduce the issue to what is actually necessary - is this caused by some plugin (in which case it might be a bug in that plugin), or is having any multi-line prompt enough?

Yeah I kind of knew it but... idk why i said that it's pretty dumb...

regardless, for anyone stumbling upon this, I'll save you a bit of time: [here's the solution](https://github.com/fish-shell/fish-shell/issues/3537#issuecomment-477550193)

I also should've searched for more synonyms before considering that there was no existing issues on this, sorry

**Comment by faho** [comment] 2021-02-14 15:13
>regardless, for anyone stumbling upon this, I'll save you a bit of time: here's the solution

That's the workaround, the solution is in fish's rendering code and is included in the upcoming 3.2.0.
