### ISSUE TITLE
fish_function_path is not treated as array when exported

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#5921] opened 2019-06-05 10:55 UTC
fish, version 3.0.2
Linux msi 5.1.4-arch1-1-ARCH #1 SMP PREEMPT Wed May 22 08:06:56 UTC 2019 x86_64 GNU/Linux
xterm-256color
using temporary environment fish

## Context
The problem arises when I try to export fish_function_path variable. This is needed, for example, when I have local `.functions` folder valid for the current project. I expect that paths added to the fish_function_path will be usable by the other fish instances, executed from the current one.

This behavior was valid for fish v2.*

## MWO
```sh
begin
          echo Default function path
          fish -c 'echo All dirs: $fish_function_path; count $fish_function_path; echo First: $fish_function_path[1]'
          echo

          echo Exported function path
          set -lx fish_function_path ~/ $fish_function_path
          fish -c 'echo All dirs: $fish_function_path; count $fish_function_path; echo First: $fish_function_path[1]'
end
```
The following code prints the contents of `$fish_function_path` environment variable, number of elements and the first element. The output of the first part:

```text
Default function path
All dirs: /tmp/tmp.jFPaXhZT9R/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions
4
First: /tmp/tmp.jFPaXhZT9R/.config/fish/functions
```

By default there are 4 paths.

When I add an extra path, for example `~/` to the function path and make it exported, the nested fish instance will have `$fish_function_path` broken.

```text
Exported function path
/tmp/tmp.zrgGcGzcD2/ /tmp/tmp.zrgGcGzcD2/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions /usr/share/fish/functions
2
/tmp/tmp.zrgGcGzcD2/ /tmp/tmp.zrgGcGzcD2/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions
```

It now contains only 2 paths. First item contains all the paths, that were exported from the parent fish shell, as a single string. It is expected to contain 5 paths: 4 default from the first example and one extra `~/`.

**Comment by faho** [comment] 2019-06-05 11:02
Duplicate of #5348.

The issue is that UNIX doesn't *have* array variables, so when we export them we have the choice of somehow marshalling them (e.g. like fish 2 did, with \x1e between the elements), which means non-fish programs break, or not doing that, which means fish breaks.

For now: Don't export $fish_function_path.

**Closed by faho** 2019-06-05 11:02 UTC

**Comment by faho** [comment] 2019-06-05 11:22
Alternatively, setting $fish_function_path to be a path variable might work.

Try `set -gx --pathvar fish_function_path /whatever`.

Though that means the values can't include ":" (like unix's $PATH et al).

**Comment by maxfl** [comment] 2019-06-05 12:33
No, this doesn't work. The resulting array has the exported path with `:` as separator as the first item now.

I guess currently this may be bypassed only by user actions in the `config.fish`.

Thank you for the comments.

**Comment by faho** [comment] 2019-06-05 13:12
>No, this doesn't work. The resulting array has the exported path with : as separator as the first item now.

Have you set it as path in *both the child and the parent*?

**Comment by faho** [comment] 2019-06-05 13:15
Ah, okay, we add some things to $fish_function_path during initialization, and at that point it's not a path var then, so even though we check whether they are included, we add them because it appears to be a single element.

Anyway, the root problem is #5348, and to be honest I doubt that we'll find a satisfactory solution (others have tried and failed at this particular problem).

**Comment by maxfl** [comment] 2019-06-05 13:22
> > No, this doesn't work. The resulting array has the exported path with : as separator as the first item now.
> 
> Have you set it as path in _both the child and the parent_?

In this case it works, thanks.

The difference from the general case of treating `:` in variables is that `$fish_function_path` is internal fish variable as well as, for example, completion path. I do not know whether it should be expected that the variable may be exported or not. Perhaps some sanity check may be done though, either
- forbid the inheritance of system variables or system path-like variables
- properly treating PATH like fish variables.

**Comment by faho** [comment] 2019-06-05 13:41
>Perhaps some sanity check may be done though, either

What we're doing is to always add our default paths (/usr/fish/functions and such), so you don't get a broken shell.

We used to check for paths existing in $PATH, but removed it because it was too annoying (e.g. because people wanted to add the same paths across systems). I don't think that's the right way to go about it.

**Comment by maxfl** [comment] 2019-06-05 13:59
I understand this. Nevertheless, let me note.

> What we're doing is to always add our default paths (/usr/fish/functions and such), so you don't get a broken shell.

In the example above the first item of the `fish_function_path` is obviously broken and contains most of the paths we had in default case in broken string. In case there are functions not from `/usr/share/fish/functions` executed as the fish starts or prints prompt line there will be errors. These alternative paths include also `/etc/fish/functions` and `/usr/share/fish/vendor_functions.d`. I may imagine that system wide configuration file `/etc/fish/config.fish` may contain calls of functions from these paths. Potentially, this may break the shell.

**Comment by faho** [comment] 2019-06-05 14:38
>In case there are functions not from /usr/share/fish/functions executed as the fish starts or prints prompt line there will be errors

No, there won't be, because /usr/share/fish/functions is added as its own element. The first element is simply ignored because it's not an existing path.

**Comment by maxfl** [comment] 2019-06-06 08:31
In my example there are 3 system paths:
- /etc/fish/functions 
- /usr/share/fish/vendor_functions.d 
- /usr/share/fish/functions 

These paths may be not controlled by the user. Only one of them is added when the `fish_function_path` variable is exported (`/usr/share/fish/functions`). To support the following statement:

> What we're doing is to always add our default paths (/usr/fish/functions and such), so you don't get a broken shell.

other two paths should be also added as separate array elements:
- /etc/fish/functions 
- /usr/share/fish/vendor_functions.d
