### ISSUE TITLE
When several jobs end in the same time the prompt is not recovered.

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#1019] opened 2013-09-26 05:44 UTC
Try to run

``` sh
sleep 2&
sleep 2&
```

And compare the output to

``` sh
sleep 2&
```

In the first case fish prompt disappears, right prompt becomes shifted to the left. The second 'exit message' is not printed until a keypress.

**Comment by floam** [comment] 2016-04-01 14:42
This might be fixed, or at least I seem to get both messages without any further keypress.

**Comment by faho** [comment] 2016-04-01 16:35
Nope, I still get it.

Not that it matters a ton - this is an edgecase's edgecase - but it should still be fixed eventually.

**Comment by krader1961** [comment] 2017-04-01 04:31
Closing because if I run `sleep 2& sleep 2&` the prompts are not messed up in the manner described in the original problem report. So apparently this has been fixed. If anyone can still reproduce this include more details such as your prompt functions, terminal type, and anything else that might be relevant.

**Closed by krader1961** 2017-04-01 04:31 UTC
Labels: bug
