### ISSUE TITLE
Up arrow being disabled is very annoying

### ISSUE THREAD

**Issue by madprops** [fish-shell/fish-shell#10021] opened 2023-09-22 02:19 UTC
version 3.6.1

When I type a partial string and use up arrow to navigate results, but if for some reason I press left arrow, it starts the edit mode and completely disables up arrow to keep navigating to other results. This happens all the time, it gets in the way. So what I do is restart the process to use up arrow again normally.

What I would prefer: Up arrow doesn't get disabled if I move the caret, I can still keep using it.

Thanks.

**Comment by faho** [comment] 2023-09-22 04:20
Duplicate of #2536

**Closed by faho** 2023-09-22 04:20 UTC
