### ISSUE TITLE
unexpected background job in function

### ISSUE THREAD

**Issue by theFool32** [fish-shell/fish-shell#5358] opened 2018-11-21 11:28 UTC
```
$ fish --version
fish, version 2.2.0

$ echo $version
2.2.0

$ uname -a
Linux liuhong-PowerEdge-T630 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM
screen-256color
```

I try the function:
```
function z
    set dst (autojump -s | head -n -7 |  tac | awk '{print $2}' | fzf +s)
    if [ "$dst" != "" ]
        cd $dst
    end
end
```
However,  no response when I type `z`, and I found `autojump` becomes a background job.
Thanks a lot.

**Comment by faho** [comment] 2018-11-21 14:29
Duplicate of #3952

**Comment by faho** [comment] 2018-11-21 14:29
Also, fish 2.2.0 is, by fish standards, ancient. Please upgrade!

**Closed by faho** 2018-11-21 14:29 UTC
