### ISSUE TITLE
Pasting text - blank screen

### ISSUE THREAD

**Issue by chapmanjacobd** [fish-shell/fish-shell#10805] opened 2024-10-21 02:31 UTC
From https://old.reddit.com/r/fishshell/comments/1g86iof/fish_shell_pasting_text_blank_screen/

I've tested this without third-party customizations, on 3.7.1 and ae7b4010 and the behavior seems to be broken in both.

To reproduce, compare the behavior of these commands:

    commandline --insert -- (seq 1 5)
    commandline --insert -- (seq 1 60)
    commandline --insert -- (seq 1 200)

Also, if you type `echo '` and then press `Enter` until the prompt is not visible and then press `'` you will see 5 `'` and 3 `echo`

**Comment by krobelus** [comment] 2024-10-21 06:11
Duplicate of https://github.com/fish-shell/fish-shell/issues/7296

**Closed by krobelus** 2024-10-21 06:11 UTC
