### ISSUE TITLE
Command in parentheses prevents stderr redirection

### ISSUE THREAD

**Issue by Micha-ohne-el** [fish-shell/fish-shell#7691] opened 2021-02-07 21:42 UTC
Hi there, I discovered some strange behavior today and would like to report it.

# Issue
When a command is used in parentheses, its stderr stream cannot be redirected.
## Example
```fish
function stderr_test
    echo "test 1" >&2
    set x (echo "test 2" >&2)
end
stderr_test 2>/dev/null # "test 2" still shows up
```
Same thing goes for redirecting to a real file: `stderr_test 2>test.txt` – the file `test.txt` only contains `test 1`, and `test 2` is printed to the console. Even redirecting using `&>` doesn't work, so the stderr is not somehow redirected to stdout.

I apologize if this is intended behavior and I just missed it. I searched the docs for any mention of this and couldn't find one, and I asked around a bit and no one could explain to me why this happens, which is why I'm thinking it's a bug.
Thanks for your time!

## System info
```fish
$ echo $version
3.1.2
$ uname -a
Linux pc 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```
I tried this with a default fish install with no modifications and it still happened.

**Comment by faho** [comment] 2021-02-07 21:44
Duplicate of #1035

**Closed by faho** 2021-02-07 21:44 UTC
