### ISSUE TITLE
`string replace` should have option to write output only if replacement occurred

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3955] opened 2017-04-16 03:22 UTC
While working on issue #2450 I kept running across this pattern:

```
a_command | __fish_sgrep pattern | sed -e 's/pattern/new_pattern/'
```

It's easy enough to turn that into

```
a_command | string match -r pattern | string replace -r pattern new_pattern
```

But it would be simpler and eliminate duplication and potential errors if `string replace` had something like the sed `-n` flag to not automatically print lines. In this case we want a flag that means only print the line if a replacement was made.

**Comment by faho** [comment] 2017-04-16 13:07
Duplicate of #3348.

**Closed by faho** 2017-04-16 13:07 UTC
Labels: enhancement
