### ISSUE TITLE
Usability: history command unnecessarily sensitive to the way parameters are passed

### ISSUE THREAD

**Issue by 22459** [fish-shell/fish-shell#4709] opened 2018-02-06 05:58 UTC
For example -n 1 will work but -n1 will fail.

**Comment by krader1961** [comment] 2018-02-06 07:04
What fish version are you using? Your example works for me when I added the `argparse` builtin for the 2.7.0 release. I'm not going to try and confirm your problem for earlier fish versions. However, I would expect the problem you reported due to the adhoc nature of argument parsing before I added the `argparse` builtin.

P.S., You should always include the details of your operating system release and fish version when reporting these types of problems. Many problems that exist in versions of the program that people are running have been fixed in subsequent versions. So knowing the version of fish you are running, as well as your operating system, are  important with respect to addressing your issue.

**Comment by 22459** [comment] 2018-02-06 07:56
So I'm on 2.7.1 now, I'd expect `history search -n 1 '.'` to return one result but it seems to be ignored and I get a lot of results.

**Comment by faho** [comment] 2018-02-06 09:52
If this is just about "-n", it's a duplicate of #4588 - we missed a backport to 2.7.X. Sorry!

**Closed by faho** 2018-02-06 09:52 UTC

**Comment by 22459** [comment] 2018-02-06 11:11
Oh of course I hit the one thing thats broken! :)
