### ISSUE TITLE
fish/functions/*.fish only show their description after they are lazy loaded

### ISSUE THREAD

**Issue by andradei** [fish-shell/fish-shell#10660] opened 2024-08-10 03:44 UTC
- fish, version 3.7.1
- Arch (EndeavourOS) Linux 6.10.3-arch1-2 # 1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000 x86_64 GNU/Linux
- wezterm 20240203-110809-5046fc22
- `$TERM: xterm-256color`

- Running `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` doesn't apply because the issue is related to loading functions from `~/.config/fish/functions`

---

The first tab completion for user functions don't show their description.
Since they appear to be lazy loaded, the descriptions appear the second time around (after the functions are evaluated, I think).

Create a function in `~/.config/fish/functions`

```fish
# ~/.config/fish/functions/example.fish
function example --description '>>>>> Description is lazy loaded <<<<<<'
    echo 'example'
end
```

Is there a way to get the description of those functions on the first tab completion?

**Comment by faho** [comment] 2024-08-10 05:00
Duplicate of #328

**Closed by faho** 2024-08-10 05:00 UTC

**Comment by zanchey** [comment] 2024-08-10 07:02
> Is there a way to get the description of those functions on the first tab completion?

Sadly not in any robust way I can think of.

**Comment by andradei** [comment] 2024-08-10 23:59
@faho Thank you for the reference, I did search but missed the issue by the title.
