### ISSUE TITLE
OBS GPG key has expired

### ISSUE THREAD

**Issue by busywhistling** [fish-shell/fish-shell#8869] opened 2022-04-12 15:00 UTC
Seems the OBS GPG key has expired [again](https://github.com/fish-shell/fish-shell/issues/6742) ([also see](https://github.com/fish-shell/fish-shell/issues/8162#issuecomment-885955417)).

While updating on Debian 11, I get the error:
```
Err:2 http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11  InRelease                                                        
  The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 shells:fish OBS Project <shells:fish@build.opensuse.org>
```

**Comment by faho** [comment] 2022-04-12 15:06
cc @zanchey it appears it is 2022 now

**Comment by mrshll** [comment] 2022-04-12 15:33
I'm am hitting this as well when building a Debian 9 container.

![image](https://user-images.githubusercontent.com/339996/162999434-a51ce19c-5771-4313-8ad3-b33fc84f026d.png)

**Comment by kylefelipe** [comment] 2022-04-12 19:19
Same problem here.

**Comment by faho** [comment] 2022-04-12 19:39
Okay, we have established that the problem exists, no need for more confirmation.

**Comment by zanchey** [comment] 2022-04-13 15:02
Should be fixed now, although you'll need to refresh your local copy of the key:

```
curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | 
gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
```

**Comment by kylefelipe** [comment] 2022-04-13 16:32
> Should be fixed now, although you'll need to refresh your local copy of the key:
> 
> ```
> curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | 
> gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
> ```

first, i had to remove all fish keys and then run this and its now fixed.

**Comment by busywhistling** [comment] 2022-04-13 20:57
@kylefelipe is right, I resolved the issue by first deleting the key (with the deprecated `apt-key` sadly): `sudo apt-key del 2CE2AC08D880C8E4` and then running the [command](https://github.com/fish-shell/fish-shell/issues/8869#issuecomment-1098162038) @zanchey provided. I guess I'll close this issue now (?), perhaps a line in the project README or website docs could be useful.

**Closed** 2022-04-13 21:02 UTC
Labels: packaging

**Comment by sarisia** [comment] 2022-04-14 04:20
Confirmed the key https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/Release.key is now fixed
but not for https://download.opensuse.org/repositories/shells:/fish/Debian_11/Release.key (which is a linked repository links to `shells:fish:release:3`).

Will this be updated automatically after a while?

**Comment by zanchey** [comment] 2022-04-19 13:51
Doesn't look like it, I'll push a dummy update to that repository as well.

**Comment by zanchey** [comment] 2022-04-20 13:13
Looks like it's sorted now.

**Comment by tennox** [comment] 2022-07-28 11:47
But the key for Debian_10 is not updated...?

**Comment by zanchey** [comment] 2022-07-28 11:59
Yes; you need to refresh your copy. Use the instructions above.

**Comment by tennox** [comment] 2022-07-28 12:15
It's a fresh install.

I think the key is already loaded:
```
gpg /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg                     Thu 28 Jul 2022 13:14:57 BST
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2013-10-08 [SC] [expires: 2024-06-21]
      24A63B31CAB41B33EC48801E2CE2AC08D880C8E4
uid           shells:fish OBS Project <shells:fish@build.opensuse.org>
```

But the Debian_10 repo might still use the old one?
> EXPKEYSIG 2CE2AC08D880C8E4

**Comment by zanchey** [comment] 2022-07-28 13:03
Those are the same key (the EXPKEYSIG only lists the part of the fingerprint), so I'm not sure what's happening there. `apt-key list` might be helpful.

**Comment by tennox** [comment] 2022-07-28 13:07
`apt-key del ...` fixed it.
Thanks for troubleshooting help :)
