### ISSUE TITLE
ctrl-Backspace and ctrl-Delete should work out of the box

### ISSUE THREAD

**Issue by matklad** [fish-shell/fish-shell#7592] opened 2020-12-31 12:42 UTC
This is essentially a re-opening of https://github.com/fish-shell/fish-shell/issues/1047.

Deleting word forwards/backwards is a standard behavior in GUI applications. It also works out of the box in Emacs (only ctrl+del works in the terminal though). 

Supporting these will be friendly :-)

**Comment by zanchey** [comment] 2020-12-31 13:27
Ctrl-Backspace is probably right out, because that's not a key combination that any terminal I've got hold of reports. You can use `fish_key_reader` to check whether Backspace and Ctrl-Backspace give you the same output.

Ctrl-Delete might be okay if we can work out what common terminals produce for this. In Terminal.app on macOS 10.14 I get `\e\[3\;5~` but iTerm doesn't seem to produce a different output with the default settings.

**Comment by faho** [comment] 2020-12-31 13:56
Duplicate of #4770

**Closed by faho** 2020-12-31 13:56 UTC
