### ISSUE TITLE
string split with variable in index causes Invalid index value

### ISSUE THREAD

**Issue by santpent** [fish-shell/fish-shell#5301] opened 2018-10-31 15:49 UTC
This type of line works ok:
```
echo (echo 'a b c d' | string split ' ' -- )[2] # returns 'b'
```
However when passing a variable into the array index like this:
```
set idx 2
echo (echo 'a b c d' | string split ' ' -- )[$idx]
```
It returns `Invalid index value`.
It can be done on two lines like this:
```
set idx 2
set array1 (echo 'a b c d' | string split ' ' -- )
echo $array1[$idx]
```
That works ok. But it seems unnecessary to have to use two lines.
I've tried to force an int with various things like this, but it doesn't work
```
echo (echo 'a b c d' | string split ' ' -- )[(math "$idx+1")]
```

Tried with fish 2.7.1 and a recent nightly 2.7.1-1628-ga2dda29c. Ubuntu 18.04.

**Comment by faho** [comment] 2018-10-31 15:54
Duplicate of #243.

**Closed by faho** 2018-10-31 15:54 UTC
