### ISSUE TITLE
command substitution does not play nice with g++

### ISSUE THREAD

**Issue by bluehood** [fish-shell/fish-shell#4822] opened 2018-03-15 14:52 UTC
It seems it's not possible to pass more than one option to `gcc` from a fish subcommand:
```
$ g++ asd.cpp (echo -pthread --std=c++11)
g++: error: unrecognized command line option ‘-pthread --std=c++11’; did you mean ‘--std=c++11’?
```

Note that this works in bash, so I'm forced to use bash when I need the feature:
```
g++ asd.cpp $(echo -pthread --std=c++11)
```

I'm using fish v2.7.1 on Arch linux:
```
$ fish --version
fish, version 2.7.1
$ uname -a
Linux meeseeks 4.15.8-1-ARCH #1 SMP PREEMPT Sat Mar 10 00:00:33 UTC 2018 x86_64 GNU/Linux
```

**Comment by mqudsi** [comment] 2018-03-15 20:35
Yes, I first encountered that problem with Clang myself, but here in the issue tracker it's known as "the pkg-config problem": https://github.com/fish-shell/fish-shell/issues/982

**Comment by faho** [comment] 2018-03-15 20:38
@bluehood: This has little to do with g++ - unlike bash, fish splits command substitutions on newline.

Which is a good thing, since splitting on spaces is a major source of issues for bash scripts.

To split on something else in addition to newlines, use `string split`.

E.g. 

```fish
g++ asd.cpp (echo -pthread --std=c++11 | string split " ")
```

I'd still love to know what code you are _actually_ running, since the command substitution in your example is superfluous - just use `g++ asd.cpp -pthread --std=c++11`.

**Comment by bluehood** [comment] 2018-03-15 20:52
Alright, thanks @mqudsi , my github-fu was not good enough to find #982 when searching for similar issues.

@faho , the actual command would be `g++ asd.cpp (root-config --libs --cflags)`, where `root-config` is a command-line tool provided by [ROOT](https://root.cern.ch/) and that kind of invocation is the usual way one compiles a ROOT program by hand.

I find prepending `eval` the nicest workaround, but I'm afraid people will keep be surprised that `cmd (make_cmd_args)` does not work as `cmd $(make_cmd_args)`.

**Comment by mqudsi** [comment] 2018-03-15 22:37
@faho for me, I have custom environment variable set with my `CFLAGS` and `CXXFLAGS`, but many projects require them specified via the command line and not via an environment variable.

For example, from my command line history, nginx takes its `CFLAGS` settings via the environment, but uses CFLAGS provided at the `/.configure` command line to pass on to zlib when building it.

**Comment by faho** [comment] 2018-03-17 20:11
>I find prepending eval the nicest workaround

@bluehood: Please **don't**. `eval` does a whole bunch of stuff, most of which you do _not_ want here.

I assume you know that it might execute code, but it will also split differently than POSIX sh (and e.g. bash), because it'll actually tokenize the input, while bash will just split on spaces, tabs and newlines (or whatever else $IFS is set to). That means `eval` will read quoted output as one token, when in sh it would be multiple.

Just use `string split " "`.

@mqudsi: That might be solved with something like the "tied variable" proposal (#436). That would allow creating list variables that are passed to the environment with a configurable separator (default to ":").

**Comment by bluehood** [comment] 2018-03-18 00:45
@faho I will keep in mind the `string split " "` workaround, thank you. On the other hand I don't think there is any risk that something undesired happens for this use-case, is there?

Anyway I understand that when writing scripts you want `set var (some_cmd)` to set `var` to a single string containing the output of `(some_cmd)`, but it's still very weird that `g++ foo.cpp (get_flags)` does not work out of the box, being such a common use-case. And having seen the other issues, it looks like I'm not alone.

**Comment by faho** [comment] 2018-03-19 15:38
>Anyway I understand that when writing scripts you want set var (some_cmd) to set var to a single string containing the output of (some_cmd)

The common case is actually to have it split on newline, and that's what we do. The reason for that is that UNIX tools are commonly line-oriented. E.g. `grep` will perform matching on every line.

This is the absolute correct thing to do - splitting on other whitespace is one of the most common root causes of issues in POSIX shell scripts.

>it's still very weird that g++ foo.cpp (get_flags) does not work out of the box, being such a common use-case.

It's not uncommon, but it's _one thing_. Really this `*-config` family of tools is weird, because they're the only things to absolutely insist on splitting on space (even though newline would also work in POSIX shell, because that's also included in $IFS).

Everything else is much better off split on newline only.

Anyway, the question has been answered, the issues are tracked elsewhere, so I'm closing this.

**Closed by faho** 2018-03-19 15:38 UTC
