### ISSUE TITLE
Weird message on receiving segmentation fault (SIGSEGV)

### ISSUE THREAD

**Issue by svxsvx** [fish-shell/fish-shell#4276] opened 2017-07-31 12:30 UTC
When **Python**(1) (inner cpython module I guess) segfaults, **fish** v2.6.0 on _Debian Linux_ just prints `fish:` -- that's all. Not very helpful. On the first glance pretty confusing in fact. Notice the colons at the end too. Is this intentional? (Just for verification, `echo $status` returns `139`.)

In comparison **bash**(1) prints at least `Segmentation fault`. That's a lot more helpful. ;)

**Comment by floam** [comment] 2017-07-31 12:42
If you run `python` and then in another window do `kill -abrt %python`, is the behavior any different?

**Comment by faho** [comment] 2017-07-31 13:12
What does `locale` say? And since this is on debian, do you have the corresponding locale packages installed? Fish tries to print a localized error message here, and it's possible it's not getting it.

**Comment by krader1961** [comment] 2017-07-31 14:49
Works for me. I ran `pkill -11 -f 'sleep 888' in another terminal:

```
$ sleep 888
fish: 'sleep 888' terminated by signal SIGSEGV (Address boundary error)
```

And changing my locale to various values, such as `set -x LC_ALL zh_CN.UTF-8`, didn't make any difference.

**Comment by faho** [comment] 2018-01-10 13:20
Nobody could reproduce, no answer in half a year. Closing.

**Comment by lyu** [comment] 2018-11-22 00:18
Hello, I am having the same issue on one machine, and I have verified it by killing python with `kill -segv python`, and killing `sleep` with `pkill`, all I can see in the terminal is `fish:`. This behavior doesn't change even if I delete my `config.fish`.

I do not have admin access on this machine so I installed fish in `~/.local`

Here is the output of `locale`:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I have another machine which doesn't have this issue, and the output of `locale` is identical.

Are there more information I can provide?

**Comment by lyu** [comment] 2018-11-22 03:34
@zanchey I am using fish 2.7.1. The output of the command you provided is:
`%ls: %ls'%ls' terminated by signal %ls (%ls)` (without a newline at the end)

**Comment by zanchey** [comment] 2018-11-22 03:40
Interesting; although you have a UTF-8 locale you're not running a build with Gettext, by the look of it. Not sure where to go from here.

**Comment by lyu** [comment] 2018-11-22 03:59
This fish installation is on an HPC cluster in our school. Because software on this cluster are extremely outdated, I had to install a ton of packages under my home directory. Maybe I messed up somewhere?

Output of `uname -a`:
`Linux login 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Output of `ldd ~/.local/bin/fish`:
```
linux-vdso.so.1 =>  (0x00002aaaaaaab000)
libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaaacb000)
libncurses.so.6 => /<my_home>/.local/lib/libncurses.so.6 (0x00002aaaaacd0000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaaad21000)
librt.so.1 => /lib64/librt.so.1 (0x00002aaaaaf3d000)
libstdc++.so.6 => /<my_home>/.local/lib64/libstdc++.so.6 (0x00002aaaab146000)
libc.so.6 => /lib64/libc.so.6 (0x00002aaaab4cf000)
/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
libm.so.6 => /lib64/libm.so.6 (0x00002aaaab891000)
libgcc_s.so.1 => /<my_home>/.local/lib64/libgcc_s.so.1 (0x00002aaaabb93000)
```

During configuration of fish I didn't set anything except the prefix.

**Comment by faho** [comment] 2019-07-05 19:06
Closing this as a presumptive fluke - we've not managed to reproduce in over 7 months.

**Closed by faho** 2019-07-05 19:06 UTC
Labels: bug, needs more info
