### ISSUE TITLE
The description of my functions is not shown in a new fish session

### ISSUE THREAD

**Issue by VosaXalo** [fish-shell/fish-shell#1915] opened 2015-01-24 14:46 UTC
Hi,
I have created some personal functions, but when I list them in a new fish session, the description is not shown. This is an example:
![fish -home-nicola_001](https://cloud.githubusercontent.com/assets/6298140/5887659/33da1ea2-a3de-11e4-8799-011764b07a32.png)
As you can see, the functions "fsINDEX, fsLEFT, fsLENGTH, fsRIGHT, fsSUBSTR" are listed without the description that I have set.

The description only appears when first I print the code of each function with the command "functions". For example I use the command:
functions fsLEFT
and then the description is present:
![fish -home-nicola_002](https://cloud.githubusercontent.com/assets/6298140/5887670/edcbab96-a3de-11e4-9722-f72a00078f58.png)

It seems that when I open a new terminal there is no "refresh" of the personal functions catalog, and that fish don't recognize them completely (not all the details).

**Comment by VosaXalo** [comment] 2015-01-24 14:50
I use fish 2.1.1-1194-g1ff9aba on Ubuntu 14.04 LTS

**Comment by zanchey** [comment] 2015-01-30 06:27
The problem here is that the function definition (including the description) is only loaded when the function is actually executed; before that happens, just the filename is used to describe the function.

This could be worked around by loading functions from files for completion and not just execution, but that may impact performance.

**Comment by VosaXalo** [comment] 2015-01-31 12:29
Ok, for now I have set this command in my "config.fish" file:
   `for i in (functions);functions $i > /dev/null;end`

Maybe this workaround could be useful to someone :-)

**Comment by faho** [comment] 2015-07-15 18:27
Isn't this a duplicate of #328? Descriptions for functions in e.g. config.fish _are_ loaded, only those for autoloaded functions aren't.

**Comment by ridiculousfish** [comment] 2015-07-15 18:34
Yes, I think so. Thanks!

**Closed by ridiculousfish** 2015-07-15 18:34 UTC

**Comment by frederickjh** [comment] 2017-08-04 07:52
@VosaXalo workaround use to work for me. Just realized that in fish version 2.6.0 it is no longer working.

**Comment by frederickjh** [comment] 2020-04-02 22:09
I have reworked the code in [this comment above](https://github.com/fish-shell/fish-shell/issues/1915#issuecomment-72315918) and have created a function that will load the functions descriptions, however I cannot get this to work in a configuration file at Fish shell start. You will need to run this function after opening a new terminal.

I hope this helps someone else.

`~/.config/fish/functions/load-em.fish`

```fish
function load-em --description 'Loads Fish shell function descriptions.'
# Load function information so it shows up in auto completion
# Original from https://github.com/fish-shell/fish-shell/issues/1915#issuecomment-72315918

  for i in (functions | tr , ' ')
    functions $i > /dev/null
  end
end
```
