### ISSUE TITLE
Stacktrace displayed when git is not installed

### ISSUE THREAD

**Issue by psarka** [fish-shell/fish-shell#4966] opened 2018-05-08 15:06 UTC
## Steps to reproduce

1. Have a fresh Ubuntu machine with fish but without git
2. Run fish in xterm
3. Type `git[space]`

## Results

The following output is observed:

```
psarka@machine ~> git 
Command 'git' not found, but can be installed with:

sudo apt install git

/usr/share/fish/completions/git.fish (line 154): 
git config -z --get-regexp 'alias\..*' | while read -lz alias command _
^
from sourcing file /usr/share/fish/completions/git.fish
	called on standard input

in command substitution
	called on standard input
```

## Expected outcome

Nothing: allow me to type, like for any other non existing command.

## Versions

Everything freshly installed:

fish, version 2.7.1
Linux 4.15.0-20-generic
Ubuntu 18.04
xterm-256color

## Extra

If [space] is replaced by [enter], clean output is produced:

```
psarka@machine ~> git 
Command 'git' not found, but can be installed with:

sudo apt install git
```

**Comment by faho** [comment] 2018-05-08 15:26
Duplicate of #4782, #2365.

You'll be happy to know that they have been fixed by not loading the completions if the command isn't installed.

**Closed by faho** 2018-05-08 15:26 UTC

**Comment by psarka** [comment] 2018-05-08 15:56
Great, happy to know!

And sorry for not digging deeper to find duplicates.
