### ISSUE TITLE
Autosuggestion on existing files in the current directory

### ISSUE THREAD

**Issue by rickalex21** [fish-shell/fish-shell#9606] opened 2023-02-21 14:15 UTC
Is there a way to autosuggest directories and files that exist in the current directory? Not sure if
this is a  duplicate of #2186 .

For Example:

```sh
some_cmd  file-in-current-dir
```

To write my own autosuggestion I would then:

```sh
austosuggest some_cmd opts "ls pwd"
```
Thanks

**Comment by faho** [comment] 2023-02-21 14:22
>Not sure if
this is a duplicate of https://github.com/fish-shell/fish-shell/issues/2186 .

It is. Autosuggestions are currently entirely unconfigurable.

**Closed by faho** 2023-02-21 14:22 UTC
