### ISSUE TITLE
Feature request: support `$(...)`

### ISSUE THREAD

**Issue by mzgubic** [fish-shell/fish-shell#7680] opened 2021-02-04 11:45 UTC
Fish is so great, thanks for building it! This is one of the few things I have to go back to bash for:
```
user@computer ~/my/path (master)> eval $(export One="one"; export Two="two")
fish: $(...) is not supported. In fish, please use '(export)'.
eval $(export One="one"; export Two="two")
     ^
```
It would be nice to support this.

**Comment by faho** [comment] 2021-02-04 11:51
Duplicate of #159

**Closed by faho** 2021-02-04 11:51 UTC

**Comment by faho** [comment] 2021-02-04 11:53
>This is one of the few things I have to go back to bash fo

And no, you don't, fish just spells it `()`:

```fish
foo (bar)
```

(I have no idea what your `eval` example is supposed to do, so I'm not rewriting it)
