### ISSUE TITLE
fish config files are executed twice when start `fish`

### ISSUE THREAD

**Issue by apua** [fish-shell/fish-shell#3803] opened 2017-02-02 16:09 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0

**OS/terminal used**:
FreeBSD 11.0-RELEASE-p1

I add shell commands to fish config files , then start `fish` ,
and it seems config files (both `/usr/local/etc/fish/config.fish` and `~/.config/fish/config.fish`) are executed twice.

## Reproduction steps
1. append a command such as `echo A__A` into fish config
2. run `fish`
3. "A__A" shows twice

## Results
```console
➜  ~ cd /usr/ports/shells/fish/work/fish-2.4.0
➜  fish-2.4.0 ./fish -v                                
fish, version 2.4.0
➜  fish-2.4.0 ./fish                                   
root@freebsd11 /u/p/s/f/w/fish-2.4.0# 
root@freebsd11 /u/p/s/f/w/fish-2.4.0# exit
➜  fish-2.4.0
➜  fish-2.4.0 HOME=`mktemp -d`
➜  fish-2.4.0 mkdir -p $HOME/.config/fish
➜  fish-2.4.0 
➜  fish-2.4.0 echo "echo A____A" >> $HOME/.config/fish/config.fish
➜  fish-2.4.0 ./fish                                                                                               
A____A
A____A
root@freebsd11 /u/p/s/f/w/fish-2.4.0# 
```

**Comment by faho** [comment] 2017-02-02 16:38
This does not happen to me. There is at least one case where we start a second fish instance in the background - to generate completions from man pages.

This should only be done if $XDG_DATA_HOME/fish/generated_completions (or ~/.local/share/fish/generated_completions) does not exist. It is possible that the generation does not work on your system and that the directory will then never be created.

Try `mkdir ~/.local/share/fish/generated_completions`. If that's it, this should be fixed in the next release (after 2.5.0).

**Comment by krader1961** [comment] 2017-02-02 17:50
It's likely that some variant of @faho's answer explains what you're seeing. Note that those config scripts are run by every fish shell -- not just interactive ones. You should always put any statements that might produce output or that are otherwise only suitable for an interactive shell inside a `if status is-interactive; ...; end` block. What do you see if you add the following to your *config.fish*:

```
if status is-interactive
  echo shell is interactive
else
  echo shell is not interactive
  ps -wfp %self
end
```

**Comment by zanchey** [comment] 2017-02-06 14:37
I think this is a duplicate of #2408.

**Comment by ridiculousfish** [comment] 2017-02-06 19:54
Nice find.

**Comment by apua** [comment] 2017-02-07 18:35
@faho yes, it doesn't show twice after `mkdir ~/.local/share/fish/generated_completions` 

@krader1961 when it show twice, both messages come from "is-interactive"

**Comment by krader1961** [comment] 2017-02-07 22:44
Your previous comment, @apua, is perplexing. The shell instance that creates the *generated_completions* directory should not be interactive and isn't on any of my systems when I add the same debug statements to my *config.fish*. I get one instance of each `echo` command output and the `ps` output shows the `fish_update_completions` just as I would expect. This is from my FreeBSD 12 system (I don't have FreeBSD 11 installed anywhere) after I remove the *generated_completions* directory and start an interactive fish shell:

```
$ fish
WTF is interactive
WTF is not interactive
PID TT  STAT    TIME COMMAND
891  1  S    0:00.02 /usr/local/bin/fish -c fish_update_completions >/dev/null ^/dev/null
```

That's more or less what I expected you to report.

**Comment by krader1961** [comment] 2017-02-08 04:26
I can reproduce this using fish 2.4.0 on FreeBSD 12 with the steps in the original problem statement. I cannot reproduce it using fish 2.5.0 or from git head. So, yes, this was broken but has been fixed sometime after the 2.4.0 release. So I'm going to close this.

@apua: If you find that the fish_update_competions subshell is still an interactive shell with fish 2.5.0 or built from git head feel free to reopen this issue. But I'm quite confident you'll find it is working as expected with a newer fish.

**Closed by krader1961** 2017-02-08 04:26 UTC
Labels: needs-more-info, question

**Comment by apua** [comment] 2017-02-12 05:37
@krader1961 thank you so much 👍

**Comment by faho** [comment] 2017-02-12 14:04
The reason this now doesn't occur anymore is that generating completions on FreeBSD now actually works. However, we still execute fish again, which as it turns out is actually unnecessary.

I've just pushed 9598218a, which executes python directly, so there's no second instance of fish involved.

We still might want to `mkdir ~/.local/share/fish/generated_completions` even if generating completions fails, since it's wasteful otherwise. However that would mean if we added support for even more systems to the generator, the user would have to start it again. I'm unaware of any such system (AFAIK we support macOS, Linux, FreeBSD, OpenBSD and Haiku in one way or another), though.
