### ISSUE TITLE
fish hangs after exiting vim

### ISSUE THREAD

**Issue by cykerway** [fish-shell/fish-shell#3654] opened 2016-12-17 01:32 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

fish, version 2.4.0

**OS/terminal used**: 

Linux/urxvt/tmux

**Talk about the the issue here**:

Fish hangs after exiting from vim. Prompt is not shown until after 4-8 seconds. This happens sporadically and I don't know how to reproduce it exactly. I've checked `set -U` and there aren't any long values except for `history`. I don't know how to debug it further.

Update. This happens for other programs as well, such as `man`. It'd be helpful to see what fish is doing during those 4-8 seconds.

## Reproduction steps
1. Run fish.
2. Run vim in fish.
3. Exit vim.

## Results

Nothing is shown upon exit. Prompt shows up after 4-8 seconds.

**Comment by ridiculousfish** [comment] 2016-12-17 03:27
This might be a slow `fish_prompt`. Does changing your `fish_prompt` avoid the slowdown?

**Comment by krader1961** [comment] 2016-12-17 03:44
Why just vim? Surely you're seeing this after running any external command, yes?

The most likely explanation is something in your fish prompt taking a long time. A frequent cause is including VCS (version control software) info in the prompt. You could try running `fish --profile=/tmp/fish.profile`. After reproducing the problem exit the shell and sort the output with `sort -nk2 /tmp/fish.profile`.
 
A less likely explanation is your $HOME directory is on a remote file system that is slow to respond; especially to file locking requests. I'm about to merge a change that will fix that case by refusing to attempt any more lock operations as soon as fish notices they are slow.

**Comment by cykerway** [comment] 2016-12-17 05:27
The `--profile` option is helpful. It shows a command in my `fish_prompt` is very slow: `hostname -s`. This command took about 5 seconds to finish and I suspect it was doing some network search. I remember I got it in from a setting in `fish_config`. Further research shows there are 3 sample prompts in `/usr/share/fish/tools/web_config/sample_prompts` that call `hostname -s` (in version 2.4.0).

The interesting thing is, I didn't find `hostname -s` in those 3 files in the HEAD commit. A new function is introduced to handle the hostname. Then I found these two threads #3479 and #3480 which seem to deal with the same problem. Someone reported `hostname -s` is slower than `hostname`. And, out of curiosity I digged into the source of inetutils. It looks like `hostname -s` implies `hostname -f`, which fires `gethostbyname` where some network search is involved. The plain `hostname` seems to be using the value from `uname` instead.

Anyway, from those two issues it looks like you guys are already working on this. I hope finally we would have something equally good or even better than the `\h` modifier in Bash's prompt. What I can do now is probably removing the `-s` option and waiting for a new release coming soon.

**Comment by krader1961** [comment] 2016-12-17 05:44
Yes, we fixed this with commit 07de13f6 two months ago to address issue #3480. It will be in the next minor release tentatively scheduled for February 2017. The problem is that DNS lookups on your system is slow. You haven't noticed this in other contexts (e.g., your web browser) because it typically only affects your system host name and not external domain names.

**Closed by krader1961** 2016-12-17 05:44 UTC
Labels: needs-more-info

**Comment by faho** [comment] 2016-12-17 11:30
To expand a bit on what @krader1961 said, we've introduced a helper function `prompt_hostname` that shows a hostname suitable for a prompt.

This function calculates the hostname once by taking the first "."-separated component from `hostname` and caches it in a global variable. This means it should both avoid the (apparently costly) `hostname -s` call and repeated `hostname` calls in general (since your hostname doesn't change often), at the cost of being wrong if your hostname either changes or the short hostname is something different from the first FQDN component.
