### ISSUE TITLE
Command substitution breaks on invalid command

### ISSUE THREAD

**Issue by polygonalenippel** [fish-shell/fish-shell#5335] opened 2018-11-13 10:05 UTC
- version 2.7.1
- kernel 4.19.1-1-MANJARO x86_64
- terminal rxvt-256color (rxvt-unicode 9.22-7 from the Manjaro repos)
- running the 'sh' command did not affect anything
- I did not find any relatable issue in the open issues

Upon opening a terminal and typing in 'pacmd', followed by hitting the spacear, the output of the terminal gets appended by the following:

```
fish: Unknown command 'pacmd'
/usr/share/fish/completions/pacmd.fish (line 1): 
pacmd help | string match -r '^ +[-\w]+' | string trim
^
in command substitution
	called on line -1 of file /usr/share/fish/completions/pacmd.fish

from sourcing file /usr/share/fish/completions/pacmd.fish
	called on standard input

in command substitution
	called on standard input


```

The command pacmd is invalid (as tested by other shells on my system) as I do not have the necessary software installed to run the command.

Once this happens and you hit enter to try the same thing in the same terminal, this does not occur again. If you try entering the command without space, the expected result is what you get:

```
~> pacmd
fish: Unknown command 'pacmd'
```

These are the autocompletion that fish could generate when I try to correct `pacmd`:

```
~> pacmd
pacman-db-upgrade    (Executable, 7,8kB)
pamac-system-daemon  (Executable, 209kB)
```

**Comment by faho** [comment] 2018-11-13 10:18
This is in effect a duplicate of #2365.

The issue here is that we run the completion script for `pacmd` (which is an actual thing to control pulseaudio).

In 3.0, we no longer do that.

**Closed by faho** 2018-11-13 10:18 UTC
