### ISSUE TITLE
How can I open file descriptor like it done in bash with `exec 3<>file`?

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#5702] opened 2019-02-25 16:23 UTC
`fish, version 3.0.2`. 

How can I open file descriptor like it done in bash with `exec 3<>file`?

**Comment by faho** [comment] 2019-02-25 16:33
Currently: You don't.

Duplicate of #3948

**Closed by faho** 2019-02-25 16:33 UTC
