### ISSUE TITLE
<E> fish: Unable to create a configuration directory for fish. Your personal settings will not be saved. Please set the $XDG_CONFIG_HOME variable to a directory where the current user has write access."

### ISSUE THREAD

**Issue by aisis** [fish-shell/fish-shell#3545] opened 2016-11-13 09:52 UTC
- [ ] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

**OS/terminal used**: 

I'm encountering this. I'm new to fish shell. 
"<E> fish: Unable to create a configuration directory for fish. Your personal settings will not be saved. Please set the $XDG_CONFIG_HOME variable to a directory where the current user has write access.

**Comment by aisis** [comment] 2016-11-13 09:53
I'm encountering this. I'm new to fish shell. 
"<E> fish: Unable to create a configuration directory for fish. Your personal settings will not be saved. Please set the $XDG_CONFIG_HOME variable to a directory where the current user has write access."

**Comment by zanchey** [comment] 2016-11-13 10:04
Welcome to fish!

Could you tell us what version of fish you are running (with `fish --version`) and what operating system you are using?

**Comment by krader1961** [comment] 2016-11-13 16:48
In addition to the question @zanchey asked what is the value for `$HOME` and what type of file system does it reside on? For example, is it a remote file system like NFS or SMB, or is it a local file system like ext4? Or is it something even more exotic like a FUSE file system?

**Comment by krader1961** [comment] 2016-11-13 19:41
Also please provide the output of the following commands:

```
ls -ld $HOME
ls -ld $HOME/.config
ls -ld $HOME/.config/fish
```

**Comment by PhilT001** [comment] 2016-11-18 10:54
Hi, I am having the same issue. Should I post here or start another issue? I don't want to hijack somebody else's thread.

**Comment by faho** [comment] 2016-11-18 11:01
@PhilT001: Well, this issue is still open but we need some more info, so it'd be nice if you could provide that.

So, what do `ls -ld $HOME`, `ls -ld $HOME/.config` and `ls -ld $HOME/.config/fish` print? Are you using a remote file system (like NFS) for your $HOME? Or NTFS or something, or is it just good old ext4?

**Comment by PhilT001** [comment] 2016-11-18 11:09
┌─[✗]─[user@Nokia-N810-43-7]─[~]
└──╼ ls -ld $HOME
drwxr-x---   67 user     users         4096 Nov 17 23:04 /home/user
┌─[user@Nokia-N810-43-7]─[~]
└──╼ ls -ld $HOME/.config
drwxr-xr-x   18 user     users         4096 Nov 17 09:30 /home/user/.config
┌─[user@Nokia-N810-43-7]─[~]
└──╼ ls -ld $HOME/.config/fish
drwx------    2 user     users         4096 Nov 17 09:47 /home/user/.config/fish
┌─[user@Nokia-N810-43-7]─[~]
└──╼ fish --version
fish, version 2.4.0

Filesystem is ext3

o/s is Maemo, Nokia's version of Debian (lenny I believe) now all but abandoned.

It's an embedded arm device (Nokia N810 internet tablet).

I compiled fish myself using gcc-4.4.4 which I also compiled.

This system does not use XDG, but I have created all the config files and directories that I think are needed.

**Comment by faho** [comment] 2016-11-18 11:41
@PhilT001: Is $HOME set?

>o/s is Maemo, Nokia's version of Debian (lenny I believe) now all but abandoned.

>It's an embedded arm device (Nokia N810 internet tablet).

Oooh I remember maemo. In fact I'm still grieving for my N900.

**Comment by floam** [comment] 2016-11-18 16:21
It looks like his $HOME is set.

**Comment by faho** [comment] 2016-11-18 16:27
Oh, yeah, sorry. 

There's two places where we create this directory - "fishd_get_config()" in env_universal_common.cpp and "path_create_config()" in path.cpp. Both do almost exactly the same thing (@krader1961).

They fail either if both $XDG_CONFIG_HOME and $HOME are empty, or if "create_directory" fails.

So, since $XDG_CONFIG_HOME isn't set but $HOME is, we know that create_directory fails.

**Comment by krader1961** [comment] 2016-11-18 16:55
Notice that @PhilT001's */home/user/.config/fish* exists and seemingly has sane permissions. So on the surface it doesn't look like creating the directory is the problem. Given that this is an embedded device it's more likely there is something unexpected going on with ACLs or the like. I'll take a close look at the fish code that leads to that error later today and try to come up with more debugging steps that will help us get to root cause.

In the meantime @PhilT001 and @aisis if you can tell us anything more about your respective environments it might help. For example, when you start a fish shell is it sandboxed or otherwise run in a manner that would limit its ability to interact with the filesystem? @PhilT001, Did you run those `ls -ld` commands from a fish prompt? Did you create the *$HOME/.config/fish* directory by hand (you kind of implied you did) or were they created by fish? What happens if you `echo hello > $HOME/.config/fish/fishd.test`? And, again, when you run that command is it from a fish shell or some other shell?

**Comment by PhilT001** [comment] 2016-11-18 20:27
Thanks for all the replies. I am running Fish directly in the operating system, though I have to call it with:

`LD_LIBRARY_PATH=/home/user/builds/packages/gcc-4.4.4-1_armel/opt/gcc-4.4.4/lib/ fish`

As I have two different versions of gcc on the device. I did configure fish with rpath to try and get around this, but it doesn't appear to work. I did also temporarily change the symlink to point to the version of gcc that Fish has been compiled with, but that didn't resolve the issue.

Fish creates the .config/fish directory, and creates:

`fishd.Nokia-N810-43-7`

within it.

The only files/folders that I created were the XDG ones, I copied the format from a Debian laptop.

`echo hello > $HOME/.config/fish/fishd.test`

Creates ~/.config/fish/fishd.test. This happen with either Fish, or Bash.

**Comment by PhilT001** [comment] 2016-11-18 20:59
Damn, my sincere apologies to all. I have a slightly different message.

Unable to create a **data** directory for fish. Your **history** will not be saved. Please set the $XDG_DATA_HOME variable to a directory where the current user has write access.

**Comment by krader1961** [comment] 2016-11-19 01:02
> Damn, my sincere apologies to all. I have a slightly different message.

Glad you said that because I was going to point out that you're not seeing the same problem as the O.P. but something slightly different albeit possibly related. What did you set `$XDG_DATA_HOME` to? Was it already set to some value? Because if it wasn't set fish should use *$HOME/.local/share/fish*. So you might want to check the permissions of those directories using `ls -ld` like you did earlier for XDG_CONFIG_HOME.

**Comment by PhilT001** [comment] 2016-11-19 01:38
I hadn't set any value before, but after a bit of searching, I found that if it wasn't set, Fish would use _$HOME/.local/share/fish_ That doesn't exist by default on my device, so I created them myself but the error message remained. I then added:

`export XDG_DATA_HOME="$HOME/.local/share"`

to ~/.bashrc.

By adding that to .bashrc I could then run Fish without the error. 

Fish can create that file/directory, but only when XDG_DATA_HOME is set (on this device)

**Comment by krader1961** [comment] 2016-11-19 04:56
@PhilT001: The problem you saw can only occur if neither `$HOME` or `$XDG_DATA_HOME` is defined. Or one of them is defined and the directory derived from that base value cannot be created or the path exists and is not a writable directory. Are you sure `$HOME` is exported because based on what you've written so far my best guess is that it is not exported. What do you see if you run `env | grep HOME` from your top-level bash shell?

**Comment by PhilT001** [comment] 2016-11-19 09:45
env | grep HOME
XDG_DATA_HOME=/home/user/.local/share
PERLBREW_HOME=/home/user/.perlbrew

**Comment by krader1961** [comment] 2016-11-19 17:20
@PhilT001: Your original comment that was mailed to me did not include HOME. Was that just due to a copy/paste error? Because if HOME is exported as your comment now indicates defining XDG_DATA_HOME as you've done is completely superfluous. Which is to say, I don't see how exporting that var as you did could fix the problem. At this point we'll probably need to resort to adding debug printf()'s to the code to understand what is happening on your system.

@aisis: Are you also running fish in an unusual environment like Linux embedded in a phone or tablet? Can you answer the questions we've asked of @PhilT001?

**Comment by PhilT001** [comment] 2016-11-19 19:42
It was indeed a copy/paste error. In Bash the output is:

`env | grep HOME
XDG_DATA_HOME=/home/user/.local/share
PERLBREW_HOME=/home/user/.perlbrew
HOME=/home/user

In Fish:

env | grep HOME
HOME=/home/user
PERLBREW_HOME=/home/user/.perlbrew
XDG_DATA_HOME=/home/user/.local/share

I've just tried the following, with a curious result:

comment  _XDG_DATA_HOME=/home/user/.local/share_  in ~/.bashrc
log out (I'm working via ssh)  `exit`
log back in  `ssh user@xxx.xxx.x.xxx`
check environment settings  `env | grep HOME`  

`env | grep HOME`
`XDG_DATA_HOME=/usr/share/mime`
`PERLBREW_HOME=/home/user/.perlbrew`
`HOME=/home/user`

Where does the **XDG_DATA_HOME=/usr/share/mime** line come from?

``

**Comment by krader1961** [comment] 2016-11-19 20:51
> Where does the XDG_DATA_HOME=/usr/share/mime line come from?

No idea but that is clearly the source of your problem. You'll need to look at your *~/.bashrc*, *~/.profile*, */etc/profile* and any related files to understand why that is being set. Of course, it's also possible it's being set by a startup script and is inherited by the SSH daemon in which case you won't find it in the bash config scripts.

@aisis: Please login to your system and type `env | grep HOME`. Is your `$HOME` set correctly? Are there any "XDG" vars set?

**Comment by floam** [comment] 2016-11-19 20:54
Maybe if an XDG_DATA_HOME is not writable we could let fish fall back to using HOME.

**Comment by krader1961** [comment] 2016-11-19 22:15
> Maybe if an XDG_DATA_HOME is not writable we could let fish fall back to using HOME.

The problem with that doing so makes it much harder to reason about the behavior. It could also surprise the user if they expect `$XDG_DATA_HOME` to be used but we don't because they made a typo. If we did this we would definitely have to  issue a warning rather than silently falling back to using `$HOME`.

We should definitely improve the error messages to make it clearer whether `$HOME`, `$XDG_DATA_HOME` (or `$XDG_CONFIG_HOME`), or neither was used. And if one of them is set, and thus should be used, why we were unable to do so. The current error messages are too generic to really be helpful..

**Comment by PhilT001** [comment] 2016-11-20 00:24
I have found the offending line in a startup script. Thanks for all your help and advice.

**Comment by krader1961** [comment] 2016-11-26 03:49
@aisis: Since you haven't provided any new information I'm going to assume the discussion up to now has allowed you to resolve your issue.

As I mentioned earlier I'm going to improve the error message for both failure cases described in this issue. Then consider this to be resolved.

**Comment by krader1961** [comment] 2016-11-26 04:17
Fantastic, we have two identical implementations for finding/creating the fish config directory: `fishd_get_config()` in *src/env_universal_common.cpp* and `path_create_config()` in *src/path.cpp*. I'll fix that. There are also two locations that use `$XDG_RUNTIME_DIR` which looks like a pointless duplication at first glance.

**Comment by krader1961** [comment] 2016-11-26 04:27
So we have `path_get_config()` and `path_get_data()` which both claim to cache the path. Yet they don't. Every time they are called the calculate a new path. Bug? Feature? Regardless, it's pretty clear the `fishd_get_config()` function in *src/env_universal_common.cpp* should be placed by a call to `path_get_config()`.

**Comment by krader1961** [comment] 2016-11-26 05:02
Okay, I see I was a bit hasty in making my previous comment. I overlooked that the respective "local" vars in the relevant functions are declared `static` and assigned to when defined. Which means the RHS only gets run on the first invocation. Nonetheless, this is something that will confuse most readers of the code; including those who have advanced knowledge of the quirks of the C language. TBD is how to restructure this code so the behavior is clearer.

**Comment by krader1961** [comment] 2016-12-02 04:41
This turned out to be a larger change than I expected. You can test it by using variations of something like

```
env -u HOME XDG_CONFIG_HOME=/wtf XDG_DATA_HOME=/foobar fish
```

**Closed** 2016-12-02 04:41 UTC
Labels: enhancement
