### ISSUE TITLE
test --help emits no output

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6114] opened 2019-09-14 18:10 UTC
With the documentation built and installed, `test --help` emits no output and exits without any errors, setting `$status` to `0`.

**Comment by floam** [comment] 2019-09-14 20:02
This is by design. `test $x` returns 0 if `x` is not empty. "`--help`" is not empty. It would break compatibility with POSIX test and existing uses in fish.

**Comment by floam** [comment] 2019-09-14 20:04
Note that all of the switches `test` works on require another argument. `test -f` with no more arguments is not looking for file existence or reporting an error about a missing argument. It's returning 0 because `-f` is not empty.

**Comment by mqudsi** [comment] 2019-09-18 18:46
Would it really break existing uses, though?

**Comment by faho** [comment] 2019-09-18 19:00
Yes, it would.

`test` fundamentally sucks, let's not try to paint lipstick on a pig.

**Comment by faho** [comment] 2019-09-19 08:10
In particular, `test` does not *support* `--`.

So because this necessitates a compatibility break, let's close this. Personally, I'd recommend looking for alternatives to test instead.

**Closed by faho** 2019-09-19 08:10 UTC
Labels: RFC
