### ISSUE TITLE
Terminal gets "broken" if I `kill -9` screen

### ISSUE THREAD

**Issue by jvns** [fish-shell/fish-shell#10717] opened 2024-09-12 15:36 UTC
If I start screen and then `kill -9` it, the terminal ends up "broken" -- the cursor jumps around a lot, text disappears or is duplicated, etc.

I think this is because `screen` puts the terminal in raw mode or something. It's very possible that it's unreasonable to expect things to function correctly after `screen` is killed in this way -- I was intentionally trying to break the terminal and this wasn't something that has ever happened to me normally while using fish. Just reporting in case it's of interest.

### how to reproduce

Here's an asciinema recording. I ran `pkill -9` screen in another tab after starting `screen`: https://asciinema.org/a/9BxZAuBjb3WqEWalMqG4xjbS2

The text I'm typing when it gets garbled is `echo "hello there"`, with a couple of newlines afterwards.

### Version info

Fish 3.7.1, using iTerm2, on Mac OS 14.4.1

```
$ fish --version
fish, version 3.7.1
$ echo $version
3.7.1
$ uname -a
Darwin grapefruit.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 arm64
```

I see the same behaviour if I run fish with `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`.

**Comment by faho** [comment] 2024-09-12 16:07
Hmm, this is interesting.

I'm not entirely sure what happens and I can't reproduce this on linux, fish 3.7.1, screen 5.0.0. Looking at the asciinema recording (the .cast file format is readable-ish text!), I don't see anything out of the ordinary. It's all printing color, moving the cursor, regular sort of stuff.

It is possible that screen sets the terminal modes, but fish [tries pretty hard](https://github.com/fish-shell/fish-shell/blob/a979b6341d7fc4c466b3992f25da3209e0808aaa/src/reader.rs#L3600-L3623) to restore it to something usable. (that's the rust, [C++ from 3.7.1 for reference](https://github.com/fish-shell/fish-shell/blob/80394ea4e38138e0ce0bf23b016dc931e22ff788/src/reader.cpp#L959-L985).

That could be confirmed via `stty -a -F /path/to/tty` from another terminal, where /path/to/tty is what `tty` prints in the offending fish instance. (I have GNU stty, I *think* it's also a thing on macOS). If that is the case, we're probably missing an important mode and I would view that as a bug.

Or maybe screen manages to change the window size (TIOCSWINSZ) and fish doesn't notice? This would presumably fix itself if you resized the terminal after. If that's the case, we're probably not checking the terminal size correctly.

**Comment by jvns** [comment] 2024-09-12 16:19
Interesting -- I ran `stty -a` in the broken terminal and compared it to the normal values of `stty -a` and there are definitely a lot of differences -- it's kind of long so I put it in [this gist](https://gist.github.com/jvns/0f61c975a3ef966ae775fcffa2ae250c)

Most noticeably almost all of the control characters (except for Ctrl-D) are missing (and I can confirm that `Ctrl+C` does not work anymore), but there's also `-isig` instead of `isig`, `-pendin` instead of `pendin`, and maybe some others.

**Comment by faho** [comment] 2024-09-12 16:32
Ah, pendin could be it? From my termios man page:

> PENDIN (not in POSIX; not supported under Linux) All characters in the input queue are reprinted when the next character is read.  (bash(1) handles typeahead this way.)  [re‐quires _BSD_SOURCE or _SVID_SOURCE]

Tho I'm pretty confused that we seem to want it *on*?

You can try `stty -F /path/to/tty pendin` from the other terminal to see if that helps. Try it with `-pendin` too if I mixed anything up.

The rest of the differences:

```diff
--- normal_stty	2024-09-12 18:26:13.159640741 +0200
+++ broken_stty	2024-09-12 18:26:29.902974553 +0200
@@ -1,6 +1,6 @@
 speed 38400 baud; 38 rows; 157 columns;
 icanon
-isig
+-isig
 iexten
 echo
 echoe
@@ -13,7 +13,7 @@
 -noflsh
 -tostop
 -flusho
-pendin
+-pendin
 -nokerninfo
 -extproc
 -istrip
@@ -46,21 +46,21 @@
 -dsrflow
 -dtrflow
 -mdmbuf
-discard = ^O
-dsusp = ^Y
+discard = <undef>
+dsusp = <undef>
 eof = ^D
-eol = <undef>;
+eol = <undef>
 eol2 = <undef>
-erase = ^?
-intr = ^C
-kill = ^U
-lnext = ^V;
+erase = <undef>
+intr = <undef>
+kill = <undef>
+lnext = <undef>
 min = 1
-quit = ^\
-reprint = ^R
-start = ^Q
-status = ^T;
-stop = ^S
-susp = ^Z
+quit = <undef>
+reprint = <undef>
+start = <undef>
+status = <undef>
+stop = <undef>
+susp = <undef>
 time = 0
-werase = ^W
+werase = <undef>
```

(yes, I did break these up manually into lines so I could run `diff` on it)

"isig" just disables the signal handling, so it does basically the same thing as undefining the signal-generating keys.

**Comment by jvns** [comment] 2024-09-12 17:10
Some results of experimenting with `pendin`: running `stty pendin; stty isig` in the broken terminal results in [this stty -a output](https://gist.github.com/jvns/23daf16f4281ef3b9b7b1f5532ace2f1) which  the same as what it should be (other than the signals section), but no change in behaviour -- the terminal is still very glitchy (cursor jumping around, characters randomly being removed/added, etc)

Also I noticed this, which I may be just me not understanding properly how to use `stty`.

1. if I run `tty` in the broken terminal I get `/dev/ttys015`
2. `stty -a` in the broken terminal and `stty -a < /dev/ttys015` give me very different output, even though I thought they should be the same thing

**Comment by jvns** [comment] 2024-09-12 17:26
Here's the output of `stty -a < /path/to/broken/tty` from another terminal. I find it hard to believe though because it says that all the signals are enabled, even though they clearly aren't, and it's the exact same as the results of `stty -a ` on a working TTY  https://gist.github.com/jvns/77136b29d14944ab528234f935d3dfbc

**Comment by faho** [comment] 2024-09-13 06:17
Okay, I think I've got something.

Terminal modes are a red herring - I can see this happen in the asciinema recording, which does not record terminal modes. So it's output only.

It starts to go wrong at this point in the .cast:

```
[7.506802, "o", "\u001b[92mbork\u001b(B\u001b[m@\u001b(B\u001b[mgrapefruit\u001b(B\u001b[m \u001b[34m~/w/m/t/break-terminal\u001b(B\u001b[m (main)\u001b(B\u001b[m \u001b(B\u001b[m\u001b[38;2;210;15;57m[\u001b[1m\u001b[38;2;210;15;57mSIGKILL\u001b(B\u001b[m\u001b[38;2;210;15;57m]\u001b(B\u001b[m\u001b(B\u001b[m> \u001b[K\r\u001b[57C"]
[9.3256, "o", "e\r\u001b[58C\u001b[38;2;147;161;161mcho \"hello there\"\u001b[30m\u001b(B\u001b[m\r\u001b[58C"]
[9.326025, "o", "\b\u001b[38;2;220;50;47me\u001b[38;2;147;161;161mcho \"hello there\"\u001b[30m\u001b(B\u001b[m\r\u001b[58C"]
[10.049483, "o", "c\r\u001b[48C"]
[10.050424, "o", "\b\u001b[31m\u001b[91mc\u001b[30m\u001b[39m\r\u001b[48C"]
[10.055097, "o", "\u001b[37mat break.py\u001b[30m\u001b[39m\r\u001b[48C"]
```

Now, this is a bunch of output and it's in an awkward format - `\u001b` is the escape character, what we'd write as `\e`.

You have some sequences like `\u001b[38;2;220;50;47me`, that's an "e" in RGB-colors (#dc322f, a red). You have a bunch of `\r`, the carriage return, that moves the cursor to the beginning of the line.

And, importantly, you have `\r\u001b[58C"` - move the cursor to the beginning of the line, move it to column 58, followed by `c\r\u001b[48C` - print a "c", move the cursor to the beginning of the line, move it to column *4*8.

Notably, your prompt before the signal - "bork@grapefruit ~/w/m/t/break-terminal (main)>", is 46 wide. After it adds a ` [SIGKILL]` and becomes 56 wide.

This also lines up with what you see - if you look carefully, the cursor sometimes ends up in the signal part of the prompt. So something forgets or doesn't know about the signal part of the prompt, but something else knows about it.

Is it possible the fish inside of screen is still running?

Some things to try:

- `echo $fish_pid` in the screen session, try to see if that pid still exists afterwards (`ps -p PID`?)
- Go to a different directory in the screen session, see if that changes where the cursor ends up.

**Comment by faho** [comment] 2024-09-13 07:33
Okay, on linux, where I can't reproduce this, I get a SIGHUP on the inner fish, which then quits. (even with `kill -9` on screen)

That's what I would expect, and that's how I think this is supposed to work.

I'm not sure what causes that to not happen. Is it a macOS thing? A screen version thing? I've now tried screen 5.0 and screen 4.09.

**Comment by krobelus** [comment] 2024-09-13 07:36
Yeah on Linux we get both EOF from `read()` and SIGHUP.
On macOS we get neither; `read()` blocks, unaffected by`pkill -9 screen`.
Then fish competes for stdin with the outer shell, so stdin is randomly distributed.

**Comment by krobelus** [comment] 2024-09-13 09:42
The `screen` command starts two processes, a server and a client.
The server's `argv[0]` is `SCREEN` even though it's the same executable.

    $ ps aux | grep -i screen
    johannes 4104351  0.0  0.0   7332  2924 pts/17   S+   11:01   0:00 screen fish
    root     4104352  0.0  0.0   7464  2256 ?        Ss   11:01   0:00 SCREEN fish

doing something like

    python -c '
    import subprocess;
    subprocess.Popen(["SLEEP", "999"], executable="/bin/sleep").wait()
    '

On Linux, `pgrep sleep` searches the basename of the executable, ignoring any `argv[0]` override.
On macOS, it only searches `argv[0]`.

So on macOS, `pkill -9 screen` only kills the screen client. Observe that `screen -ls` still marks the screen session as "Attached".

When I reproduce on Linux using `fish -C screen` by killing only the screen client, I can type one or two characters and then the outer(!) shell exits. Maybe that's SIGTTIN.
If I use `bash` as instead of fish, it doesn't exit but the terminal is broken, all the cursor movements are messed up etc.

**Comment by faho** [comment] 2024-09-13 10:42
Ah, okay. So the tree looks like

- outer fish
- screen client (called screen)
- screen server (called SCREEN - presumably if you had any other sessions this would already be running?)
- inner fish

The server holds the pty open, which means the inner fish doesn't get a SIGHUP.

The outer fish sees that its child process was killed and so it resumes the session.

I don't know what *can* be done about this. The screen client was SIGKILLed, which means it can't do anything. The server doesn't see that its parent process died, and so it can't do anything. The inner fish sees nothing wrong, and the outer fish sees a simple process exit.

Even if it *did* check that there are processes remaining (via some mechanism like cgroups), it can't really act on it because this is effectively daemonization - a process forks twice and the middle exits. If it holds on to the terminal there really isn't any mechanism stopping it, AFAICT?

> When I reproduce on Linux using fish -C screen by killing only the screen client, I can type one or two characters and then the outer(!) shell exits. Maybe that's SIGTTIN.

I get basically exactly the behavior in the OP, no SIGTTIN or anything, just letters randomly being swallowed and the cursor moving around.

It's possible there's some race here - both fishes will be trying to reacquire the terminal at some point, but I'm not sure what exactly would cause the inner one to do so (the outer fish will do it after the SIGCHLD).

**Comment by krobelus** [comment] 2024-09-13 11:38
> >  Observe that screen -ls still marks the screen session as "Attached".

> I don't know what can be done about this

Yeah. The manual workaround is to run `screen -d` in a different terminal.

On SIGHUP (`kill -HUP (pgrep screen)[1]`) the screen client (it's called "attacher") process will detach automatically. But not on SIGTERM.
On SIGKILL, the server could take care of detaching but given that the server is a child of the attacher, it's not as easy as handling SIGCHLD.

A possible workaround is to wrap `screen` in a function that, on signal exit runs "screen -d" (with the args from context). But that's probably not worth the effort.

I've posted to the screen-users list as well (doesn't show up in [the archives](https://lists.gnu.org/archive/html/screen-users/) yet).

> It's possible there's some race here - both fishes will be trying to reacquire the terminal at some point,

Right, same issue with dash. So the `tcgetpgrp()`/`tcsetpgrp()` calls are probably racing.
We should figure out why the child fish tries to acquire the terminal and why it's not suspended by SIGTTIN.

**Comment by faho** [comment] 2024-09-18 09:09
Okay, this was a fun little mystery, and I think we solved it.

There doesn't really seem to be anything we can do on our end, and the screen mailing list hasn't come up with an answer either (so far).

I'm closing this. Thanks for a fun question tho!

**Closed by faho** 2024-09-18 09:09 UTC
Labels: question

**Comment by jvns** [comment] 2024-09-18 14:05
Thanks for the great investigation, all of this was really fun to read!

**Comment by krobelus** [comment] 2024-09-19 09:11
On Fri, Sep 13, 2024 at 06:58:37AM -0700, Ed Sabol wrote:
> > A possible workaround is to wrap screen in a function that, on signal exit runs "screen -d" (with the args from context). But that's probably not worth the effort.
> 
> That seems like the easiest and best solution to me, tbh. I don't get why you think it's "not worth the effort"?

An implementation in screen itself would be much easier to get right (argument parsing, dealing with race conditions etc).
Also it will work for other shells.

**Comment by esabol** [comment] 2024-09-19 22:47
>>> A possible workaround is to wrap screen in a function that, on signal exit runs "screen -d" (with the args from context). But that's probably not worth the effort.

>> That seems like the easiest and best solution to me, tbh. I don't get why you think it's "not worth the effort"?

> An implementation in screen itself would be much easier to get right (argument parsing, dealing with race conditions etc). Also it will work for other shells.

Oh, I misunderstood. I thought the change you said wasn't worth the effort was in screen itself, but you meant a shell function, I'm gathering from your response. In any case, we agree that fixing this in screen would be best.
