### ISSUE TITLE
How to do this in fish?

### ISSUE THREAD

**Issue by jby** [fish-shell/fish-shell#8325] opened 2021-09-28 16:09 UTC
Any power fish users that can help me with something I find very useful in bash/zsh. If you, in a for loop, put a command in parentheses it "reverts" any (for instance) path changes:

```
for f in *
do
    (cd $f;run command)
done

```
How do I do that in fish?

The above will cd into each dir of '*' and run 'command' but when exiting the () you're back to the dir you started, i.e. you don't have to 'cd ..' to be back at the parent dir.
Can this be done in a similar way in fish?

**Comment by jby** [comment] 2021-09-28 17:34
Ok, I found #1439, which kind of answers this, but if anyone would like to provide more info - be my guest.

**Comment by krobelus** [comment] 2021-09-28 18:29
Yeah I wish the `cd` was local to the command substitution, but it's hard to implement that with fish's implementation of command substitution.

**Comment by krobelus** [comment] 2021-09-28 18:29
Duplicate of #1439

**Closed by krobelus** 2021-09-28 18:29 UTC
