### ISSUE TITLE
colored complete for files

### ISSUE THREAD

**Issue by name-snrl** [fish-shell/fish-shell#9350] opened 2022-11-13 18:10 UTC
Hi. Is it possible to make file completion colored, like in bash?

fish: 
![image](https://user-images.githubusercontent.com/72071763/201537354-6889fdf7-2a88-475b-8fe4-e1eb5e133ec4.png)

bash:
![image](https://user-images.githubusercontent.com/72071763/201537375-2a70856b-329d-4aae-8b07-7188e619adc7.png)

**Comment by faho** [comment] 2022-11-13 18:20
Duplicate of #2868

**Closed by faho** 2022-11-13 18:20 UTC
