### ISSUE TITLE
abbr no longer writing with -U

### ISSUE THREAD

**Issue by chris5335** [fish-shell/fish-shell#9580] opened 2023-02-15 21:54 UTC
**fish, version 3.6.0**
**Linux fedora 6.1.11-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  9 19:20:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux**
**xterm-kitty**
 **yes, the result without third-party customizations is the same behavior**

I am creating abbr like I have since I started using fish earlier last year.  But now it doesn't save the abbr with the -U switch, so it won't persist after I refresh the terminal.  I'm sure it is something I'm doing, but I don't know how to fix it.

```shell
>abbr -a dvr docker volume rm
#then when I look at my whole list it looks like this:
>abbr
abbr -a -U -- ga 'git add .'
abbr -a -U -- gac git-add-commit
abbr -a -U -- gb 'git branch'
abbr -a -U -- gm 'git merge'
abbr -a -- dvr 'docker volume rm'
```
I appreciate any help you can offer.

**Comment by faho** [comment] 2023-02-15 22:39
Duplicate of #9523

**Closed by faho** 2023-02-15 22:39 UTC
