### ISSUE TITLE
Multiline prompt with Alt+L

### ISSUE THREAD

**Issue by mrak** [fish-shell/fish-shell#1395] opened 2014-04-02 05:35 UTC
I have a two-line prompt and I have noticed for some time that when I use the `alt+l` binding to quickly get a directory listing that the _first_ line of my prompt covers part of the _last_ line of the listing.

**Comment by faho** [comment] 2016-04-04 18:11
This is a duplicate of #718, which was fixed in 9f0417b587ac6cec7343e287c12886adc459e01c.

**Closed by faho** 2016-04-04 18:11 UTC
