### ISSUE TITLE
fish uses getopt options that are not supported in OpenBSD

### ISSUE THREAD

**Issue by bonds** [fish-shell/fish-shell#2140] opened 2015-06-18 15:26 UTC
I have Fish installed on OpenBSD 5.7-stable. When I login using the default prompt, everything works fine. But when I login using a different prompt, I see a stream of errors before I get the command prompt:

````
getopt: unknown option -- Q
getopt: unknown option -- o
getopt: unknown option -- Q
getopt: unknown option -- o
getopt: unknown option -- Q
getopt: unknown option -- o
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[I] ~>                                              Thu Jun 18 08:13:47 PDT 2015
````

It would seem the 'Q' and 'o' options for ````getopt```` are not supported on OpenBSD, but Fish is still trying to use them under certain circumstances.

**Comment by ridiculousfish** [comment] 2015-06-18 17:43
I can't wait to get off of `getopt`

**Comment by krader1961** [comment] 2016-09-24 03:56
This is, more or less, a duplicate of issue #478. More generally, if we don't implement a docopt style parsing facility we should at least implement a fish `getopt` command usable by fish functions.

**Closed** 2016-09-24 03:57 UTC
Labels: duplicate, enhancement

**Comment by herrbischoff** [comment] 2018-02-27 23:18
Just as quick question on the progress of getting off `getopt`, as I'm in the same situation of not being able to use fish on OpenBSD.

**Comment by faho** [comment] 2018-02-27 23:49
@herrbischoff: I can't find a single `getopt` invocation in share/ in 2.7.0 or later.
