### ISSUE TITLE
No case insensitive autosuggestions for `cd`

### ISSUE THREAD

**Issue by qfab** [fish-shell/fish-shell#1544] opened 2014-07-12 10:26 UTC
Assume that the current directory contains nothing but the subdirectory “Foo”, i.e.,
```
$ ls
Foo/
```
If I type `ls f`, fish automatically suggests `ls Foo`, just as one would expect. On the other hand, there is no such autosuggestion if I type `cd f`. (The “f” remains red.)

This happens with fish 2.1.0 on a case-sensitive file system (ext3).

A similar issue has already been described two years ago in bug #119, which has been fixed as far as I understand. Is this a new bug?

**Comment by tiagoboldt** [comment] 2015-06-08 22:48
I can't reproduce this issue. It works for me. @qfab care to try again and close the bug if it is also fixed for you?

**Comment by faho** [comment] 2016-06-10 12:41
This works for me and nobody has managed to reproduce it. I'm assuming it's been fixed in the meantime.

**Closed by faho** 2016-06-10 12:41 UTC
