### ISSUE TITLE
Sometimes prompt starts with a ⏎ character and prompt doesn't move when window is resized

### ISSUE THREAD

**Issue by cubetastic33** [fish-shell/fish-shell#7635] opened 2021-01-17 16:45 UTC
fish --version: `fish, version 3.1.2`
uname -a: `Linux hogsmeade 5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 x86_64 GNU/Linux`
echo $TERM: `alacritty`
OS: Arch linux

https://user-images.githubusercontent.com/33519300/104849655-f0d87b00-5910-11eb-961b-049b448bb70f.mp4

As demonstrated in the video, sometimes when I open windows that are not full-sized, a ⏎ character is drown at the top. When windows are resized, the prompt doesn't move to the start of the window, but stays wherever it was drawn at first. In the video I'm using starship prompt, but the issue also happens with the default prompt that comes with fish.

**Comment by faho** [comment] 2021-01-17 17:02
The ⏎ is shown when the previous command didn't end its output in a newline.

In this case it's shown because fish is altering the terminal modes too late, which was fixed in #7489.

**Comment by faho** [comment] 2021-01-17 17:02
Duplicate of #7489

**Closed by faho** 2021-01-17 17:02 UTC

**Comment by cubetastic33** [comment] 2021-01-17 17:05
I don't think this is the same issue, because it happens even when I haven't typed anything prior to its load. That issue also doesn't mention the issue with the prompt's position after window resizing.

**Comment by faho** [comment] 2021-01-17 17:13
Pretty sure it is.

**Comment by cubetastic33** [comment] 2021-01-17 17:16
I see, thank you for the clarification :D
