### ISSUE TITLE
fish tab-completion crashes with "libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string"

### ISSUE THREAD

**Issue by mflider** [fish-shell/fish-shell#1855] opened 2014-12-09 19:01 UTC
For some (but not all!) commands, my fish shell crashes with "libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string". I suspect it's because I have aliases that start with the same few characters that fish is trying to autocomplete

Crash steps:

1. Start typing "git"
2. Fish autocompletes inline: ~ $ git-2-integrate-review 71986
3. Press "tab" to accept the autocomplete suggestion
4. Fish crashes:
~ $ gitlibc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
[Process completed]

The command it's trying to autocomplete is one of the many "git-n-blah" aliases I have set up in my fish config.

This is on Mac OS X Yosemite 10.10.1

**Comment by zanchey** [comment] 2015-07-31 10:32
Did you ever make any progress with this? I wonder if it is any better in fish 2.2.

**Comment by mflider** [comment] 2015-08-07 20:31
Still happens with fish 2.2.0.

**Comment by zanchey** [comment] 2015-08-08 03:24
Annoying! Can you reproduce your aliases somewhere?

**Comment by jrobeson** [comment] 2016-02-28 21:26
just looking through some old issues. Can this still be reproduced, and is information forthcoming? there hasn't been an update here in awhile.

**Comment by faho** [comment] 2016-02-28 23:31
@mflider: If we are to solve this, we need your config. Preferably your full config.fish and related files and how you installed fish.

**Comment by krader1961** [comment] 2016-02-29 03:30
I'd also be interested in the locale related environment variables (e.g., LANG, LC_ALL, etc.) since this is conceivably related to non-ASCII characters.

On OS X you'll probably need to run "ulimit -c unlimited" before reproducing the problem in order to obtain a core dump. Also, did the OS X Crash Reporter window not appear to provide a stack backtrace?

**Comment by faho** [comment] 2016-03-24 19:38
@mflider: I'm closing this for now. If you ever get back to this, we'll reopen!

**Closed by faho** 2016-03-24 19:38 UTC
Labels: needs-more-info
