### ISSUE TITLE
Can't use $CMD_DURATION on fish script

### ISSUE THREAD

**Issue by PicoSushi** [fish-shell/fish-shell#5788] opened 2019-04-03 14:22 UTC
While executing fish script, $CMD_DURATION seems not set.

Example:

```shell
echo "Hello, World!"
sleep 1
echo "$CMD_DURATION"
```
`fish example.sh` outputs
```
Hello, World!
0
```

### Environments
- fish, version 3.0.2
- Linux yukari 4.14.109-1-MANJARO #1 SMP PREEMPT Wed Mar 27 18:51:38 UTC 2019 x86_64 GNU/Linux

**Comment by floam** [comment] 2019-04-03 17:57
Indeed. This is a bug.

**Comment by faho** [comment] 2019-04-03 18:17
Not a bug as CMD_DURATION is currently set after each commandline, by the reader.

The major issue is determining what it should include. E.g. currently I can run `sleep 5s; sleep 10s;` and $CMD_DURATION will be at 15s. This is simple, because it's including the entire commandline.

I don't see a way to specify what it should include, so unless you want it to be updated after _every_ command it doesn't really appear all that helpful.

**Comment by floam** [comment] 2019-05-19 06:44
I think it could indeed be updated after each command. What makes sense to group multiple commands non-interactively would be  `begin` ... `end`, and it should be the time of the whole block.

**Comment by faho** [comment] 2019-05-19 19:54
@floam: What about current uses e.g. in fish_prompt, though? I have set mine up so it prints the CMD_DURATION if it exceeds 100ms.

I mean technically you could require users to save it in the prompt as the first operation, but if you also want to display $status it would require this:

```fish
set -l cmd_duration $CMD_DURATION
set -l old_status $status
```

If you did it the other way around you'd clobber $CMD_DURATION but `set` doesn't alter $status so that can be done as the second step. That's quite the weird contortion.

I think it seems preferable to keep $CMD_DURATION as it is (duration of the last interactive commandline, done automatically) and implement `time` (#117) for other uses. Then you'd do `time begin` if you want to time a block.

**Comment by faho** [comment] 2019-06-23 15:46
After further deliberation, I'm closing this in favor of #117.

**Closed by faho** 2019-06-23 15:46 UTC
Labels: enhancement
