### ISSUE TITLE
git seems broken in fish version 3.3.1?

### ISSUE THREAD

**Issue by tianyma** [fish-shell/fish-shell#8160] opened 2021-07-23 06:20 UTC
my git seems broken in the fish shell.
If I open a shell window, I get an error 
```
fatal not a git repository (or any of the parent directories) .git
```
If I enter a git repository directory, I get another error
```
fatal: Refusing to point HEAD outside of refs/
fatal: Needed a single revision
```
It just automatically ouputs like this 
```
➜  ~ cd dacresult/oyster/
fatal: Refusing to point HEAD outside of refs/
fatal: Needed a single revision
➜  oyster git:() 
```
but in bash shell, the git works okay and does not output error message. Weird. Can someone help me? my fish version is 3.3.1.

**Comment by faho** [comment] 2021-07-23 06:32
Duplicate of #8105.

Fish 3.3.0 disabled the long-deprecated `^` redirection, it seems something you're using hasn't been updated. Use `2>` instead, or enable it temporarily again with

```fish
set -U fish_features no-stderr-nocaret
```

(this will be removed in future so it's just a transitional aid)

**Closed by faho** 2021-07-23 06:32 UTC
