### ISSUE TITLE
`t<tab>` is fast, while `ter<tab>` is super slow to autocomplete

### ISSUE THREAD

**Issue by hashier** [fish-shell/fish-shell#7664] opened 2021-01-29 12:10 UTC
As the title says, if I try to do
```
$ t<tab>
```
I instantly get the result for auto completion.

If I do
```
$ ter<tab>
```
fish hangs for many seconds before returning the results. To illustrate I attached a video:
https://asciinema.org/a/EDo4h9jgS0DZRXofdR6LlPJKI

fish, version 3.1.2
Mac Big Sur 11.1
iTerm 3.4.3 (same behaviour in Terminal.app)
Darwin PinkedFly 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
xterm-256color

`$ sh -c 'env HOME=$(mktemp -d) fish'` shows same behaviour, maybe a tiny bit slower, but still many seconds hang.

**Comment by faho** [comment] 2021-01-29 12:15
Duplicate of #7511

**Comment by faho** [comment] 2021-01-29 12:16
It's a bug in macOS we're working around in the next release.

**Closed by faho** 2021-01-29 12:15 UTC

**Comment by hashier** [comment] 2021-01-29 13:22
Ah nice. Thanks. 

I searched in open issues but not in closed ones. Hence I didn't find the old ticket.
