### ISSUE TITLE
Inconsistent parse depending on whether var is defined: {$var}]

### ISSUE THREAD

**Issue by oconnore** [fish-shell/fish-shell#2493] opened 2015-10-19 01:08 UTC
```
> set -e var
> echo $var]

> echo {$var}]

> set var [
> echo $var]
[]
> echo {$var}]
[]
> echo ]
]
```

**Comment by faho** [comment] 2015-10-19 14:27
It's actually quite consistent - variables are expanded via cartesian product, so an undefined variable will expand to nothing. So this is a duplicate of #2438.

**Closed by faho** 2015-10-19 14:27 UTC

**Comment by Lucretiel** [comment] 2015-10-19 15:30
For an example of why this is consistent, try:

```fish
$ set var  # Sets $var to the empty list
$ echo $var]

$ 
```

**Comment by derekstavis** [comment] 2015-10-19 15:34
Shouldn't this be the result?

```
$ set var  # Sets $var to the empty list
$ echo $var]
]
```

**Comment by faho** [comment] 2015-10-19 15:42
See #2438, that's one of the proposals.

However, it's not quite sure that this is always what you want - think `for i in $PATH/*`.

Anyway, the current behavior is intended that way, it's quite useful, there's just been a bit of discussion to change it, but that discussion should happen in #2438.

**Comment by Lucretiel** [comment] 2015-10-19 17:11
> Shouldn't this be the result?

No- consider this:

```fish
$ set var a b c
$ echo $var]
a] b] c]
$
```

As @faho said, see #2438
