### ISSUE TITLE
implement web browser fish REPL interface where people can learn how fish behaves

### ISSUE THREAD

**Issue by techtonik** [fish-shell/fish-shell#4054] opened 2017-05-23 04:31 UTC
Trying command line tools in browser is quite common nowadays and I used to it. Like on https://python.org or https://play.golang.org

It would be awesome if https://fishshell.com provided the same functionality.

**Comment by krader1961** [comment] 2017-05-23 05:00
That's a great idea, @techtonik. Do you have any ideas how this would be implemented and who would pay for the hosting costs? In other words, we would need to implement a cloud based (e.g., AWS/Amazon EC2) web UI which someone has to pay to keep running. In the case of Go that is Google. In the case of Python it is whomever runs https://www.pythonanywhere.com/. Do you have some ideas on how we might implement something like that for free or so close to free that a volunteer contributor would be willing to pay for it?

**Comment by techtonik** [comment] 2017-05-23 05:15
For now I used https://linuxcontainers.org/lxd/try-it/ which is kind of weird, because it is container with Ubuntu 16.04, so to get Ubuntu 17.04 I had to launch another container inside, login into it, install `fish` and login to `fish`.
```
# start container with ubuntu zesty
lxc launch ubuntu:z fishy
# login into it
lxc exec fishy bash
fishy# apt update
fishy# apt install fish
fishy# fish --version
fish, version 2.4.0
```

I know it is also possible to compile C code to run in browser:
1. https://en.wikipedia.org/wiki/Emscripten
2. https://en.wikipedia.org/wiki/Google_Native_Client
3. http://webassembly.org/

**Comment by techtonik** [comment] 2017-05-24 11:55
If there are any popular Docker images that include `fish`, this can be used - https://www.katacoda.com/

**Comment by ridiculousfish** [comment] 2017-05-26 03:28
https://linuxcontainers.org/ looks rad. Another option is emulation in your browser - see http://copy.sh/v86/?profile=freebsd for an example of what's possible. That's statically hosted so no security concerns or server fees other than S3.

**Comment by zanchey** [comment] 2017-05-26 07:36
Isn't this a duplicate of #1604?

**Comment by techtonik** [comment] 2017-05-26 17:23
Looks so.

**Closed** 2017-05-26 17:42 UTC
Labels: duplicate

**Comment by techtonik** [comment] 2017-05-27 11:22
But #1604 may be too dated.

**Comment by faho** [comment] 2017-05-27 11:27
@techtonik: That doesn't matter - it's still open.

**Comment by techtonik** [comment] 2017-05-27 12:38
@faho some issues stand forever, because it takes half an hour just to read them, so a good practice for the sake of progress is to summarize and reticket them periodically.

**Comment by faho** [comment] 2017-05-27 12:46
@techtonik: Read #1604 - it's not too bad, honestly.

**Comment by techtonik** [comment] 2017-05-27 13:28
I skimmed over. It is not bad, but the last message is still from 2014.
