### ISSUE TITLE
Fish is not compatible with the POSIXLY_CORRECT environment variable

### ISSUE THREAD

**Issue by sstewartgallus** [fish-shell/fish-shell#2369] opened 2015-09-08 20:03 UTC
I can work around this by unsetting POSIXLY_CORRECT and then setting POSIXLY_CORRECT inside fish but it'd be nice if this could be fixed here.

**Comment by ridiculousfish** [comment] 2015-09-08 20:04
What should POSIXLY_CORRECT do?

**Comment by faho** [comment] 2015-09-08 20:09
That's a GNUism - Richard Stallman (IIRC) disagreed heavily with a few of the POSIX decisions, among those the standard blocksize (512 bytes, IIRC) mandated for du, so he chose to not use it by default unless POSIXLY_CORRECT is set.

@sstewartgallus: What exactly doesn't work and why would you want POSIXLY_CORRECT? My guess is some completions break since they run in the interactive environment.

**Comment by faho** [comment] 2015-09-08 20:12
@ridiculousfish: See https://www.gnu.org/software/diffutils/manual/html_node/Standards-conformance.html

I think the important part is

>Normally options and operands can appear in any order, and programs act as if all the options appear before any operands. For example, ‘diff lao tzu -C 2’ acts like ‘diff -C 2 lao tzu’, since ‘2’ is an option-argument of -C. However, if the POSIXLY_CORRECT environment variable is set, options must appear before operands, unless otherwise specified for a particular command. 

But I'm not sure which command this affects. I can't find `diff` in any completion or function.

**Comment by ridiculousfish** [comment] 2015-09-08 20:19
That is hilarious.

**Comment by faho** [comment] 2015-09-08 20:25
Hilarious? That is POSIX.

**Comment by faho** [comment] 2015-09-08 20:39
Okay, I would have thought the offender to be `grep`.... From [the man page](http://linuxcommand.org/man_pages/grep1.html):

>POSIXLY_CORRECT
              If  set,  grep  behaves  as  POSIX.2  requires;  otherwise, grep
              behaves more like other GNU  programs.   POSIX.2  requires  that
              options that follow file names must be treated as file names; by
              default, such options are permuted to the front of  the  operand
              list  and  are  treated as options.  Also, POSIX.2 requires that
              unrecognized options be diagnosed as “illegal”, but  since  they
              are  not  really against the law the default is to diagnose them
              as  “invalid”.   POSIXLY_CORRECT  also  disables   _N_GNU_nonop-
              tion_argv_flags_, described below.

But I looked at all grep invocations in share/* and found that we don't often call grep on files - mostly it's used in pipes, and when we do, it's usually simple `grep SOME_REGEX_NOBODY_CAN_READ_ANYMORE /some/file`. I haven't found a single invocation that could fit.

**Comment by faho** [comment] 2015-09-15 11:41
@sstewartgallus: Ping? What exactly does not work? I have done some cursory testing and I couldn't find anything that didn't. I'm open to making fish work with POSIXLY_CORRECT, but to do that I need to know what currently doesn't.

**Comment by faho** [comment] 2015-09-24 13:20
Sorry @sstewartgallus, without more information we can't do anything since we can't reproduce the issue. So I'm closing this, if you can explain it a bit better, please do so.

**Closed by faho** 2015-09-24 13:20 UTC
Labels: needs_more_info

**Comment by faho** [comment] 2016-05-20 22:37
@sstewartgallus: This seems like it's the same thing as #3039, which was since fixed. The issue was our usage of getopt, which behaves in an annoying way with POSIXLY_CORRECT set.
