### ISSUE TITLE
使用 systemctl 命令时会报错

### ISSUE THREAD

**Issue by eonun** [fish-shell/fish-shell#6127] opened 2019-09-21 16:24 UTC
使用systemctl命令时会报以下错误
```bash
systemctl restart a	Integer 242 in '242 (242.85-2-manjaro)' followed by non-digit:37
	Integer 242 in '242 (242.85-2-manjaro)' followed by non-digit
```

```
Integer 242 in '242 (242.85-2-manjaro)' followed by non-digit:37
	Integer 242 in '242 (242.85-2-manjaro)' followed by non-digit
```

**Comment by faho** [comment] 2019-09-21 16:34
Duplicate of #5746

**Comment by faho** [comment] 2019-09-21 16:34
Which is a duplicate of #5689.

**Closed by faho** 2019-09-21 16:34 UTC
