### ISSUE TITLE
Strange characters with vi bindings in terminator  [1 q⏎    

### ISSUE THREAD

**Issue by nilehmann** [fish-shell/fish-shell#3611] opened 2016-12-02 05:52 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0
**OS/terminal used**: 
Arch linux

When using `fish_vi_key_bindings` in [terminator](https://gnometerminator.blogspot.com/p/introduction.html) I get these strange characters before every prompt.

![screenshot from 2016-12-01 21-49-40](https://cloud.githubusercontent.com/assets/2400776/20824271/21644ebc-b810-11e6-9920-739adaf8f190.png)

I observe a normal behavior in gnome-terminal

**Comment by krader1961** [comment] 2016-12-02 06:09
I  don't understand how [terminator](https://gnometerminator.blogspot.com/p/introduction.html) is relevant. The link you provided hints that it is a "tool for arranging terminals". Is it also a terminal emulator? If so what value does it export for `$TERM`?

A screen capture is not useful for this type of problem. Please use the `script` command to launch a fish shell then exit that shell and upload the *typescript* file so we can see the exact sequence of characters written to stdout.

**Comment by floam** [comment] 2016-12-02 07:04
Looks like an issue with the vi cursor.

**Comment by faho** [comment] 2016-12-02 13:01
This is a duplicate of #3535, which is already fixed in git. Sorry for the inconvenience.

**Closed by faho** 2016-12-02 13:01 UTC
Labels: needs-more-info
