### ISSUE TITLE
Cannot cd into a directory longer than 63 characters

### ISSUE THREAD

**Issue by vivia** [fish-shell/fish-shell#2120] opened 2015-06-03 14:47 UTC
Using fish version 2.1.2 from Debian.
I cannot cd into a directory whose name is 64 characters or longer. Fish just gives up and displays a bare ">" prompt at that point:

vivia@kleio ~> cd 123456789012345678901234567890123456789012345678901234567890123/
vivia@kleio ~/123456789012345678901234567890123456789012345678901234567890123> 
cd ..
vivia@kleio ~> mv 123456789012345678901234567890123456789012345678901234567890123 1234567890123456789012345678901234567890123456789012345678901234
vivia@kleio ~> cd 1234567890123456789012345678901234567890123456789012345678901234/
\>

**Comment by sdroege** [comment] 2015-06-03 14:50
Confirmed, also with
fish, version 2.1.2-1280-gcec1dc2

**Comment by zanchey** [comment] 2015-06-03 15:30
The good news is that this is actually working as intended. Because the prompt would overflow your window with, fish instead displays a simple caret in order to give you space to type commands. `pwd` should show that you are in the directory you expect.

**Comment by vivia** [comment] 2015-06-03 15:36
Thanks for the quick reply! Hmm, that's good news indeed :) but a bit confusing. Maybe shorten it somehow?

**Comment by ridiculousfish** [comment] 2015-06-03 17:48
Truncating the prompt is tricky because it is likely to have escape sequences. Nevertheless this is a common complaint.

**Comment by niedzielski** [comment] 2015-06-04 05:26
+1, seeing just `>` was a little confusing to interpret at first. As a sometimes Bash user, I was expecting the prompt to word wrap when necessary. Perhaps a more exact repro case would be to set the prompt to a long name:

    function fish_prompt
      echo abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
    end

And shrink the terminal window width until `>` is shown.

**Comment by zanchey** [comment] 2015-07-31 04:32
We're tracking improvements to this in #904, so I'm going to close as a duplicate of that for now.

**Closed by zanchey** 2015-07-31 04:32 UTC
Labels: duplicate
