### ISSUE TITLE
directory name too long make prompt change to ">"

### ISSUE THREAD

**Issue by x0rld** [fish-shell/fish-shell#6538] opened 2020-01-26 00:17 UTC
version: 2.7.1

uname: `Linux  5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

term: `xterm-256color`

with the classic prompt there is no problem

I use the nim theme
when I go in a directory and the name is too long 
![image](https://user-images.githubusercontent.com/45242856/73128824-aa8a5d80-3fd5-11ea-80df-600c9bc68ab7.png)

i found a backup from october of the exact same theme who doesn't have the problem in this directory.
But I don't understand why when i do a `git init` in the directory the prompt change to ">"
but it's only when my window terminal is 87*24 is it's bigger there is no problem.

**Comment by x0rld** [comment] 2020-01-26 00:19
this is the fish_prompt of the screenshot
[fish_prompt_actual_fish.fish.txt](https://github.com/fish-shell/fish-shell/files/4113049/fish_prompt_actual_fish.fish.txt)
and this one is the older from my backup
[fish_promptolder.fish.txt](https://github.com/fish-shell/fish-shell/files/4113050/fish_promptolder.fish.txt)

**Comment by faho** [comment] 2020-01-26 06:51
Duplicate of #904

**Closed by faho** 2020-01-26 06:51 UTC

**Comment by faho** [comment] 2020-01-26 06:52
This happens when fish thinks your prompt is wider than your terminal (and if it isn't, your terminal is reporting the wrong width).

If you upgrade to 3.0, you can make your prompt react to it by checking $COLUMNS and e.g. omitting parts.
