### ISSUE TITLE
Autosuggestion should be reactivated by pressing right arrow

### ISSUE THREAD

**Issue by bagohart** [fish-shell/fish-shell#9758] opened 2023-04-27 20:07 UTC
I quite like the autosuggestions that can be accepted by right-arrow.
However, there's one small problem that I often run into:
1) I type some text, an autosuggestion appears
2) I type a wrong letter, the autosuggestion is gone, and then I realize that it would have been better to accept the autosuggestion (or a part of it using alt-right).
3) So I want the autosuggestion back, and in order to do that I have to remove another character, and then enter that exact character again.

That is pretty annoying to me. I checked in the doc on commandline, and there seems no way to activate autosuggestions once they vanish.

My idea is this:
When no autosuggestion is displayed, pressing "right" or "alt-right" should make the autosuggestion appear (if the cursor is at the end of the line), but should not be accepted yet. I think that would be quite intuitive, because "right" does not have any other meaning in this context. I imagine that this would not be hard to implement since it doesn't require storing previous state of the command-line or the displayed autosuggestions.

An alternative would be to add an input function to `commandline -f`, so this can be bound to a custom key.

**Comment by faho** [comment] 2023-04-27 20:09
Duplicate of #3549

**Comment by faho** [comment] 2023-04-27 20:09
This is about what happens with autosuggestions after you delete, so let's keep it in 3549

**Closed by faho** 2023-04-27 20:09 UTC

**Comment by bagohart** [comment] 2023-04-27 20:35
Ah sorry, you're right. I didn't discover that other issue, because I only searched for "autosuggestion".
