### ISSUE TITLE
Cannot use command substitutions in index access on command substitutions

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#8834] opened 2022-03-25 21:18 UTC
Fish version: 3.4.1  
Operating system: Raspbian 10  
Kernel: Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux  
Terminal: xterm-256color (lxterminal)  

The syntax `$...[...]` is treated differently from `(...)[...]`. The latter disallows command substitution in the index list.

```console
pi@raspberrypi ~> set list 1 2 3
pi@raspberrypi ~> echo $list
1 2 3
pi@raspberrypi ~> echo (seq 1 3)
1 2 3
pi@raspberrypi ~> echo $list[2]
2
pi@raspberrypi ~> echo (seq 1 3)[2]
2
pi@raspberrypi ~> echo $list[(echo 2)]
2
pi@raspberrypi ~> echo (seq 1 3)[(echo 2)]
fish: Invalid index value
echo (seq 1 3)[(echo 2)]
               ^
pi@raspberrypi ~ [121]> 
```

**Comment by faho** [comment] 2022-03-25 21:47
Duplicate of #7801

**Closed by faho** 2022-03-25 21:47 UTC
