### ISSUE TITLE
Weird terminal behavior (disappearing text)

### ISSUE THREAD

**Issue by dmig** [fish-shell/fish-shell#9803] opened 2023-05-19 07:52 UTC
Fish version 3.6.1
Terminals used:
- kitty 0.28.1
- gnome-terminal 3.48.0

**Steps to reproduce**:
1. open terminal window
2. paste the provided command:  [cmd.txt](https://github.com/fish-shell/fish-shell/files/11514730/cmd.txt)
3. press `up` or `backspace`

**Screenshots**:
![Screenshot from 2023-05-19 09-47-58](https://github.com/fish-shell/fish-shell/assets/388564/65753dc1-0688-4644-b5ca-0fdc1e2f2f4a)
![Screenshot from 2023-05-19 09-48-36](https://github.com/fish-shell/fish-shell/assets/388564/64471a6f-2cd7-494a-93e3-5e008f01d4ef)
![Screenshot from 2023-05-19 09-50-04](https://github.com/fish-shell/fish-shell/assets/388564/2713149a-b574-46a3-a0f2-221573c9f449)

![Screenshot from 2023-05-19 09-48-15](https://github.com/fish-shell/fish-shell/assets/388564/d6e900d6-44fb-4723-9630-b178e7ad3974)
![Screenshot from 2023-05-19 09-48-45](https://github.com/fish-shell/fish-shell/assets/388564/bcb550ff-2578-42c3-88e1-f3aa0906e6d0)
![Screenshot from 2023-05-19 09-50-11](https://github.com/fish-shell/fish-shell/assets/388564/7718e455-fb7c-42d3-a8ed-d3993e2ea6b5)
![Screenshot from 2023-05-19 09-50-18](https://github.com/fish-shell/fish-shell/assets/388564/3f498665-7117-4df8-b0b7-5f08840ed7c4)

**Comment by dmig** [comment] 2023-05-19 07:54
Pasted command in `bash`:
![Screenshot from 2023-05-19 09-53-29](https://github.com/fish-shell/fish-shell/assets/388564/afbf3e9d-1380-421f-9b77-66d16f0d5cf8)
![Screenshot from 2023-05-19 09-53-32](https://github.com/fish-shell/fish-shell/assets/388564/6a4cd63c-376b-4172-a9ed-1f02d7774867)

**Comment by faho** [comment] 2023-05-19 09:46
Duplicate of #7296

**Closed by faho** 2023-05-19 09:46 UTC
