### ISSUE TITLE
Generic `~/.local/opt` builds?

### ISSUE THREAD

**Issue by solderjs** [fish-shell/fish-shell#7190] opened 2020-07-11 05:44 UTC
Hello! I love `fish`. Thank you.

I'd like to get `fish` on https://webinstall.dev, but that requires a distributable that doesn't require `root` permissions to install.

I'm wondering: Does this _requires_ specific prefixes, or if it's possible to create a generic, self-contained build that would work generically from `$HOME/.local/opt/fish/`?

**Comment by faho** [comment] 2020-07-11 05:46
This is what the appimage is for - see #6475.

Closing this as a duplicate of that.

**Closed by faho** 2020-07-11 05:46 UTC

**Comment by zanchey** [comment] 2020-07-11 10:13
It should work if compiled to that prefix, though - set `CMAKE_INSTALL_PREFIX` and you should be fine. I install builds to my home directory daily.

**Comment by solderjs** [comment] 2020-07-14 23:17
@zanchey I'm intending webinstall.dev for making it easier for novice users to get access to (mostly) cross-platform tools (fish may be an exception for Windows) from the official pre-built releases (so that they don't have to install and use complex toolchains).

I'll keep an eye on the other bug and circle back around to add to `webi` when there's an official build.

Thanks for the quick reply @faho.

**Comment by zanchey** [comment] 2020-07-15 01:48
The `fish.app` package is entirely self-contained but we don't ship anything for Windows or Linux (as you say, this is what the AppImage would be for).
