### ISSUE TITLE
Incorrect TTY settings when running interactive shell with command

### ISSUE THREAD

**Issue by jmendeth** [fish-shell/fish-shell#4356] opened 2017-08-27 00:45 UTC
I can invoke a `fish` interactive shell and run `stty` in it:

~~~
$ fish -i
xavier@xavier-pad ~> stty
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
~~~

I can invoke `fish` with the `stty` command directly:

~~~
$ fish -c stty
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
~~~

However, if I invoke an interactive shell *and* supply a command directly...

~~~
$ fish -i -c stty
speed 38400 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl -imaxbel iutf8
-icanon -iexten -echo
~~~

The command receives incorrect TTY flags. Is this on purpose or a bug?

Now, I know it doesn't make much sense to pass the -i flag if I'm passing a command, but this actually matters for other shells. (for example, -i makes bash load `~/.bashrc` and I can use aliases within the command I'm supplying)

fish, version 2.6.0

(Probably related to #2980)

**Comment by faho** [comment] 2017-09-06 08:21
Duplicate of #2980.

**Closed by faho** 2017-09-06 08:21 UTC
