### ISSUE TITLE
complete long option with optional argument: annoying space character

### ISSUE THREAD

**Issue by luc-j-bourhis** [fish-shell/fish-shell#4821] opened 2018-03-15 02:08 UTC
With the completion `complete -c foo -f -l bar -a "this that"`, when I type `foo -` and then hit TAB, I am offered two choices, `--bar` and `--bar=`, so far so good. If I select `--bar=`, my command line then becomes `foo --bar= ` *with a space after equal*. As a result of this space and the lack of `-x` in the completion, hitting TAB does then not offer the choices `this` and `that`. But if I then move the cursor back by one character so that it sits just after `=`, and then hit TAB, those two choices are offered. The following animated gif shows the behaviour (you might have to reload the page to make it play again, or even click on it; I did not use asciinema because it did not record properly):

![complete](https://user-images.githubusercontent.com/295281/37440017-27ad25da-27fb-11e8-93b7-a2088bdb66c1.gif)

I would suggest that when choosing `--bar=`, fish does not add a space after it, so that the completion immediately works. 

Fish version: 2.7.1
System: 
  - MacOS 10.12.6
    - Darwin zeus.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
    - Terminal: Apple "Terminal.app" ($TERM is xterm-color)
  - Fedora 21
    - Linux raptor 4.1.13-100.fc21.i686+PAE #1 SMP Tue Nov 10 13:30:58 UTC 2015 i686 i686 i386 GNU/Linux
    - Terminal: gnome-terminal ($TERM is xterm256-color)

**Comment by zanchey** [comment] 2018-03-15 14:07
Seems reasonable.

**Comment by faho** [comment] 2021-07-15 12:00
Okay, I can't reproduce this anymore.

`grep --colo<TAB>` offers `--color`, i.e. the version without the optional argument, after which it will add a space and then won't offer the argument anymore.

If also offers `--color=`, after which it won't add a space but will offer the argument.

So it seems to have been fixed in the meantime.

**Closed by faho** 2021-07-15 12:00 UTC
Labels: enhancement
