### ISSUE TITLE
Redefined `set` without scope shadowing is not completely transparent.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1046] opened 2013-10-18 16:50 UTC
Following code doesn't work.

``` sh
~ $ fish -c 'function set --no-scope-shadowing; builtin set $argv; end; type type'
test: Missing argument at index 2
type: Could not find 'type'
```

**Comment by krader1961** [comment] 2017-03-23 02:57
This is still broken although the failure mode appears to have changed:

```
switch: Expected exactly one argument, got 0

/usr/local/share/fish/functions/type.fish (line 17):                 switch $flag
                                                                            ^
in function 'type'
	called on standard input
	with parameter list 'type'

switch: Expected exactly one argument, got 0

/usr/local/share/fish/functions/type.fish (line 27):                 switch $flag
                                                                            ^
in function 'type'
	called on standard input
	with parameter list 'type'

test: Missing argument at index 2
```

**Comment by krader1961** [comment] 2017-03-23 03:23
I just realized this is a duplicate of issue #3540.

**Closed by krader1961** 2017-03-23 03:23 UTC
Labels: duplicate
