### ISSUE TITLE
Cannot save multi-line output in a variable (support $() command substitution syntax)

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#159] opened 2012-06-20 01:44 UTC
There seems to be no way to capture multi-line output in a shell variable. Any attempt to do so splits each line into a separate array element. In bash I'd simply put double-quotes around my `$()` invocation, but in fish you cannot quote a command substitution. This is rather unfortunate because it means I cannot capture multi-line output in a variable and send it back to a separate command without really weird contrivances, such as replacing all newlines with NUL when saving and reverting the process when emitting.

**Comment by derekstavis** [comment] 2015-08-23 02:24
Another great syntax that runs away from `$` is what Swift proposes for string interpolation:

    set CPUINFO "\(cat /proc/cpuinfo)"

**Comment by jakwings** [comment] 2015-12-11 02:41
I'm opposed to `((...))`, `#{...}`, `{...}`, `"\(...)"`. And `"$(...)"` is the best. If we also change the syntax of unquoted command substitution to `$(...)`, that would be better. Then we can use `()` in `test (...) -a (...)` without escaping.

**Comment by imgx64** [comment] 2016-06-23 08:55
Maybe I'm missing something, but isn't this already fixed?

From [the documentation](http://fishshell.com/docs/current/index.html#expand-command-substitution):

> If the output is more than one line long, each line will be expanded to a new parameter. Setting IFS to the empty string will disable line splitting.

So the solution is:
```
> count (echo one\ntwo\nthree)
3
> begin; set -l IFS; count (echo one\ntwo\nthree); end
1
```

**Comment by faho** [comment] 2016-06-23 13:20
@imgx64: That has been mentioned here before.

While mucking with $IFS does solve the issue, it's supremely awkward.

**Comment by dxlr8r** [comment] 2016-08-17 07:04
```
# echo 1 2 3 | read -z flatvar; count $flatvar
1
```

**Comment by anordal** [comment] 2016-08-17 18:12
While `read -z` reads up to NUL, an option to read all the way to EOF would be a more proper solution for this use case.

**Comment by andrewrk** [comment] 2016-08-24 17:49
What's preventing this issue from being resolved? It seems like several reasonable paths forward gave been proposed. Can we pick one and move on with it?

I'll throw in a vote for deprecating `()` in favor of `$()`.

**Comment by faho** [comment] 2016-08-24 22:59
>What's preventing this issue from being resolved? It seems like several reasonable paths forward have been proposed. Can we pick one and move on with it?

Well, we'd have to actually pick one and then someone has to write the code. Or someone writes code that we can agree on.

----

Personally, I now rather strongly believe that switching to "$()" is the right solution.

- Not splitting on newlines would be an awfully breaking change. Just see our scripts. Plenty of our command substitutions use this feature, and finding out which exactly would require auditing everything. Additionally, users would need to do all of that too, and it would have to be a flag-day transition (i.e. fish 3.0 gets released, everyone needs to rewrite everything for it, some people are still on 2.X). See what happened with python.

- Splitting on newlines is a good default. Unix usually operates on a one-thing-per-line basis. E.g. `grep` will print one match per line, `git log` has a "--oneline" switch to print one commit per line, which is quite useful in scripts. Configuration files are usually line-based. Our own `commandline` will print one token per line if told to split by tokens, ........ ("all whitespace" is unworkable because that leads to bogosities like bash's issues with spaces)

- `$()` would be usable inside and outside of double-quotes, without changing the list of characters that start an expansion (and hence need to be escaped) in them. This also means it could be the one-and-only syntax to denote command substitutions.

- `$()` would be the same syntax as POSIX, and inside of double-quotes would have the same semantics. While we don't _need_ to adhere to POSIX, if the POSIX syntax works why invent something else? We don't do `if $COMMAND; then $COMMAND; fi` and `for $COMMAND; do $COMMAND; done` because it's nicer to have just one block separator (that being the `begin` and `end` pair), but we do do `$COMMAND $argument1 $argument2` because that's a perfectly cromulent way to write it.

I believe all this together means that `$()` is better than all other proposals.

----

So, what's my concrete proposal?

First, introduce `$()` as an alternate command substitution syntax. Unquoted, this would work like `()` does currently - it would split the output on newlines, and pass each line as a separate argument. In double-quotes, it would pass the entire output as-is, including newlines.

This would mean you could use it as a drop-in replacement for `()`, and if you wanted to save multi-line output verbatim, you'd just do `set var "$(COMMAND)"`.

Also, start deprecating `()`. With the announcement of fish X.Y.Z, include a notice with a deadline. With a later release, start warning when `()` is used directly on the commandline. With an even later release, start warning always. Then, when the deadline has passed, remove it. We don't want a `\`\`` (backtick) situation.

----

Addendum:

A related thing is splitting on something else. If my proposal is used, this could at least be done with `string split $CHAR "$(COMMAND)"`. Additionally it would be possible to make `string split` special in a command substitution, so `$(COMMAND | string split $CHAR)` splits not on newline but on $CHAR. I don't know how that would interact with quotes.

**Comment by dxlr8r** [comment] 2016-08-25 18:47
My 2 cents. I don't like the $() approach personally, to confusing for new people coming from Bash etc. and not needed the way I see it. Add a flag to _set_ and _read_, that should be adequate.

**Comment by faho** [comment] 2016-08-25 18:50
>I don't like the $() approach personally, to confusing for new people coming from Bash 

Why? With what I propose, the _only_ difference between fish's `$()` would be that when unquoted it splits only on newline and not "any" whitespace (I think it's actually $IFS or newline, tab and space - not non-breaking space and such). That's easily explained (and AFAIK also what zsh does by default).

**Comment by andrewrk** [comment] 2016-08-25 18:51
> My 2 cents. I don't like the $() approach personally, to confusing for new people coming from Bash

Hmm I have the other conclusion, that `$()` would be more familiar to people coming from Bash. I mean, it *is* the same syntax as Bash.

**Comment by dxlr8r** [comment] 2016-08-25 19:05
That is the problem, that could lead to people only using $(). And to be frank I don't see the point, () is fine. And this is about storing, not to be confused by sub shelling etc. I think this belongs to _set_ and _read_ but I would use $() as well because of the functionality, but I don't think that is so clean.

**Comment by faho** [comment] 2016-08-25 19:13
>That is the problem, that could lead to people only using $().

And that is the idea. That people switch to using `$()`, and we can in future dump `()`, leaving only one syntax to do this.

Or do you mean people could come from bash, use `$()` expecting it to split on space? Well, in my experience 90% of splitting on space is actually a bug. IIRC some projects demand all variables in a shellscript be quoted. Zsh has the SH_WORDSPLIT option (that only applies to parameter expansion - command substitution it also splits on spaces, unlike what I mentioned previously) to reenable splitting on spaces, and it defaults to off (and is strongly discouraged).

Or do you mean that people use `$()` when they mean `"$()"`? Well, they need to decide how they want to split the argument. I can't see a way around that. If we added piping to `set` or an option to `read` (that actually took the entire input as one element, not just up to \0), then you'd need to decide if you wanted to split on newlines or not, i.e. whether you'd want `COMMAND | set var` or `set var (COMMAND)` (or read's "--the-entire-thing-as-one-please" option).

Really, you have some command that produces some kind of output. We can offer a default for how to handle it, but if you want it differently, you need to express that.

And for this there's a nice symmetry between comsubs and variable expansion - if you want it split (on newlines/elements) you don't use quotes. If you want it as one, you quote.

**Comment by dxlr8r** [comment] 2016-08-25 19:21
I just don't see the point as I said. Why should $() take over for ()? () is a clean break from Bash syntax, which is confusing. Fish "few" options of doing things are it's strength, it does what it does well and you don't have 5 ways of writing an if statement ( test, [], (), (()), etc.). 

I don't see how/why a prefixing $ before () would make it better, what does the $ add to the syntax? () is cleaner, shorter and less like bash. If people want a lot of features but still be compatible with bash syntax there is zsh for that.

**Comment by faho** [comment] 2016-08-25 19:35
>I don't see how/why a prefixing $ before () would make it better, what does the $ add to the syntax? () is cleaner, shorter and less like bash

What the "$" allows is for this issue to be resolved. "$"s are already special inside double-quotes, so we can reuse that fact to allow for a syntax to command substitutions that also works in double-quotes _without increasing the amount of special characters_. This is then a natural notation for command substitutions that aren't split.

It would also allow for the future removal of `()` would also reduce the amount of special characters in general. That would be nice because any special character needs to handled specially - specifically they need to be escaped, via (single) quotes or `\`.

It also would not add any expressions that work _differently_ since `$()` is currently an error both unquoted and in double-quotes.

>Fish "few" options of doing things are it's strength, it does what it does well and you don't have 5 ways

The idea is that providing two options is very much a temporary thing so that scripts don't need to be rewritten instantly (and with two versions, one for fish before and one for fish after this change). We'd have to communicate this properly.

**Comment by andrewrk** [comment] 2016-08-25 19:51
> () is a clean break from Bash syntax, which is confusing

`$()` isn't inherently confusing. IMO it's one of the cleaner parts of bash syntax.

> what does the $ add to the syntax?

It allows you to execute a sub command inside a quoted string, similar to how `$FOO` lets you expand a variable inside a quoted string.

**Comment by dxlr8r** [comment] 2016-08-25 20:12
I think quoting only should be for strings. And I quote the design docs:

> The many Posix quoting styles are silly, especially $''.

I agree with @Soares to that we should add new commands/arguments instead of redesign. This subject can easily be solved without changing fish's core.

**Comment by andrewrk** [comment] 2016-08-25 20:37
> I agree with @Soares to that we should add new commands/arguments instead of redesign. This subject can easily be solved without changing fish's core.

I'm content with that solution as well. But just to play devil's advocate for the other solution, I'll say that I filed #3329 because fish's behavior was surprising. I expected `set -x foo (cat foo.txt)` to not mangle the contents of foo.txt by default. I tried putting the command in quotes but realized that without `$` or another escape character it wouldn't be possible. Then I tried bash, got the expected behavior, and concluded that fish had a bug. So this would be an argument from intuitiveness of how users would expect things to work.

**Comment by alphapapa** [comment] 2016-09-21 21:15
I like the idea of having flags for `set` and `read` to change the splitting behavior between splitting on newlines or not, but that seems like only half the solution, since command substitution wouldn't be affected by it (and we don't want to force people to capture output into a variable before passing it to a command as arguments).

I think using the `$()` syntax makes sense.  Not only would it allow for fixing this issue by deprecating or maintaining in parallel the `()` syntax, but I think there's also something to be said for using the `$()` syntax in general: it means that substitutions always begin with a `$`, which helps clarity.  While the `()` syntax is cleaner (and even lispy, if you like that), it's very different from other shells, and it's inconsistent with variable substitution.  I think saving one character when typing and visual cleanliness are not as valuable as clarity and consistency.

**Comment by andrewrk** [comment] 2016-11-10 19:19
I think this issue is important. Do we foresee `"$()"` syntax being available anytime soon?

**Comment by s-ol** [comment] 2017-01-24 17:28
this is also very frustrating for me, to work with meteor sometimes I need to read a rather long `settings.json` into an environment variable like so:

    env METEOR_SETTINGS=(cat settings.json) meteor run ....

currently I can't really do this and have to drop into bash for a bit.

**Comment by anordal** [comment] 2017-01-24 22:24
But *if* we play the dollar card, is `$()` or `"$()"` supposed to fix this?

Let's be thankful that quoting variables is not necessary in fish the same way it is in bash. As [Wikipedia sums it up](https://en.wikipedia.org/wiki/Friendly_interactive_shell#bash.2Ffish_Translation_table):

    Quoting not necessary to suppress word splitting and glob interpretation.
    Instead, quoting signifies serialization.

Because quoting means something else in fish, we are able to confidently tell bash programmers «*Come to fish, here you can forget everything you know about quoting*». But if we have to add «*Oh, except for command substitutions*», then it's less convincing.

Which is a reason for a clean break, and not making things look **too familiar** to bash programmers.

**Comment by andrewrk** [comment] 2017-01-24 22:56
> Which is a reason for a clean break, and not making things look too familiar to bash programmers.

I'd rather have the attitude be, let's forget bash and design a good syntax, rather than trying to be so different from bash limit our options.

**Comment by anordal** [comment] 2017-01-24 23:02
… but isn't a good syntax one that is explicit about splitting?

**Comment by faho** [comment] 2017-01-24 23:53
>… but isn't a good syntax one that is explicit about splitting?

A good syntax is one where, if you need to write it, you know what to write, and if you need to read it, you know what it does. 

Being explicit works for that, but isn't necessary, and may also be _too_ explicit.

So, why don't we want required explicit splitting syntax? Well, we _can't_ actually change the default (if no splitting is specified) because that would break the world (of fish, at least). We also wouldn't want to, because the default (splitting on newline) is the right thing to do for 90% of cases - unix is traditionally line-oriented, so handling lines separately by default is nice. Requiring an explicit "split this on newlines please" is annoying explicit syntax.

So what's "good syntax" about `$()`? It's consistent with `$var`. `echo $var` splits, while `echo "$var"` doesn't. That means if you know the latter, you can guess the former. If you need to write it, there's a good chance you'll come up with it, and if you read it, there's a good chance you'll understand it.

>The only reason we can confidently tell bash programmers «Come to fish, here you can forget everything you know about quoting» is that quoting means something else in fish. But if we have to add «Oh, except for command substitutions», then it's less convincing.

No, that'd still work. Without quoting, stuff is split on a good default. If you need something else, add quotes and do what you want.

The problem with quoting in bash isn't that it exists, it's that it's a "do the right thing, please" syntax. For variables, you want quotes almost always. The default is the thing you want only in special cases, and the special syntax is what you usually want. If normal conversation were like that, you'd have to add "and don't scream the answer at me" after every question.

**Comment by s-ol** [comment] 2017-01-25 01:15
similar to @xfix's `pipeset` above, here's what I came up with to solve my problem:

```
function withsub
  if [ (count $argv) -lt 2 ]
    echo need at least two arguments!
    return 1
  end
  set -l cmd
  set -l val (eval $argv[1])
  for arg in $argv[2..-1]
    if [ "$arg" = "[]" ]
      set cmd $cmd "$val"
      else
        set cmd $cmd "$arg"
      end
    end
  eval (string escape -- $cmd)
end
```

to be used like:

    $ withsub "cat test" seperated 1 [] 2
    1
    --
    test string with spaces
    --
    2

if you have something like

```
function seperated
  echo $argv[1]
  for arg in $argv[2..-1]
    echo --    
    echo $arg
  end
end
echo test string with spaces > test
```

**Comment by Pysis868** [comment] 2017-04-05 14:19
Meanwhile, I wanted a newline stored into a variable so I could throw it more cleanly into a `screen -X "...$newLine"` command call.

Since `()` wasn't cooperating, I used this, in case anyone else needs it too: `printf "\n" | read -z newLine;`

**Comment by faho** [comment] 2017-04-05 15:02
@Pysis868: In that case, `set newLine \n` would just work - or later `screen -X "..."\n`.

**Comment by andrewrk** [comment] 2017-05-22 20:38
I just ran into this again and even though I participated in this issue not 4 months ago, I was completely surprised and it took an hour to figure out what was happening. And look above this comment at these other commits referencing this issue, because as it stands *fish is not intuitive*. 

let's acknowledge the design flaw, fix, and move on

**Comment by krader1961** [comment] 2017-05-22 21:03
> let's acknowledge the design flaw, fix, and move on

We would love to review a pull-request from you, @andrewrk, or anyone else that implements this feature. More contributors are always welcome as there are too few [contributing on a regular basis](https://github.com/fish-shell/fish-shell/graphs/contributors).

**Comment by spinningarrow** [comment] 2017-05-23 04:24
@krader1961 I would be happy to contribute but I don't know where to start. Is there something about how the code is organised that I can refer to?

**Comment by krader1961** [comment] 2017-05-23 04:46
@spinningarrow: Not really. We do have a [how to contribute](https://github.com/fish-shell/fish-shell/blob/master/CONTRIBUTING.md) document. But most of that is for people who intend to contribute changes on an on going basis. If you are interested in making infrequent contributions you don't really need to worry about those guidelines since the core developers will take care of style, lint, and similar issues. The only way to learn about how the code is organized is to `git clone` the repo and explore it.

**Comment by GReagle** [comment] 2017-06-22 06:06
Why would we change fish when, as @imgx64 has pointed out, it is already solved and documented as "Setting IFS to the empty string will disable line splitting."

Also, similar result can be achieved with read:  `ls | read -z test`.

I don't agree with @faho that 
> While mucking with $IFS does solve the issue, it's supremely awkward

I think it just slightly awkward.  But, surely, modifying IFS or using  read -z can't be as awkward as **changing the syntax and semantics of fish**.

**Comment by krader1961** [comment] 2017-06-22 06:11
Thanks for the feedback, @GReagle, but you're definitely in the minority. The only reason this hasn't already been done is that it requires more work than most changes and is technically not backward compatible even if we continue to support the current bare `(cmd)` syntax. If we do a fish 3.0 (i.e., major) release this is definitely going to be included. Even if it means not doing some other things we'd like to see in a major release.

**Comment by krader1961** [comment] 2017-06-22 06:36
Also, it should never be necessary to manipulate `IFS` in fish script. That var should die and removing it is something else we should consider for a major release. Whenever I have needed to, or seen it used to, change how strings are split into words in other shells (ksh, bash, zsh) it always made me want to vomit. It is the poster child for what is wrong with POSIX 1003 compatible shells.

**Comment by spinningarrow** [comment] 2017-06-22 11:07
I don't know much about `IFS` and its manipulation. Why is it bad?

**Comment by faho** [comment] 2017-06-22 12:22
>I don't know much about IFS and its manipulation. Why is it bad?

A few things:

It can only be set for an entire command, meaning e.g.

```fish
set -l var (cat file1) (cat file2)
```

means you can only split or not both files (or command substitutions in general) - there's no way to only split file1 other than to do it over two commands.

To use it, you either need to reset it (`set -l oldifs $IFS; set -l IFS; command; set IFS $oldifs`) or mess with scoping (e.g. introduce a `begin; end` block just for it).

It's also pulling double-duty - if IFS is unset or set to empty (and just that, the actual value doesn't matter) command substitutions won't split, and it will be used to split for `read` - e.g. `set -l IFS =; read -l key value < file.ini` to read an ini-file).

It's also kind of inconsistent with how fish does things - we don't use variables to change behavior all that much.

All that means it's easy to mess up and requires more care than usual.

It's not that it's unfit for purpose - yes, it can be used to not split command substitutions - it's that it's an awkward interface.

Or ask yourself what you like more:

```fish
set -l oldifs $IFS
set -l IFS =
somecommand | read -l key value
set IFS oldifs

# or

somecommand | read -l -f = key value # the "-f" option is hypothetical at this point
```

and

```fish
set -l oldifs $IFS
set -l IFS
set -l var (somecommand)
set IFS $oldifs
set var $var (somecommand2)

# or
set -l var (somecommand2)
begin
    set -l IFS
    set var (somecommand1) $var
end

# or

set -l var "$(somecommand)" $(somecommand)
```

Note: There are of course other ways to denote that a command's output should not be split - some things have been mentioned in this thread. But many of them would be better than awkward ifs-trickery. Also in many cases resetting IFS can be skipped - e.g. because that's the end of the function anyway.

**Comment by GReagle** [comment] 2017-06-22 13:35
@faho thanks for that instructive explanation.

**Comment by spinningarrow** [comment] 2017-06-22 16:08
@faho That was a great explanation - thanks!

**Comment by nesl247** [comment] 2018-03-01 18:39
Any update to this? Extremely annoying at the moment.

**Comment by hauleth** [comment] 2018-04-22 12:32
I would like `IFS` to be removed, and default to empty string, if someone wants to split command output as separate params then should use `string split <pattern>` without exceptions.

**Comment by kballard** [comment] 2018-04-22 20:05
`string split` only works *because of* `IFS`.

```fish
> begin
    set -l IFS
    set -l wat (string split x fooxbarxbaz)
    set -S wat
end
$wat: set in local scope, unexported, with 1 elements
$wat[1]: length=11 value=|foo\nbar\nbaz|
$wat: not set in global scope
$wat: not set in universal scope
```

**Comment by kballard** [comment] 2018-04-22 20:07
Or to put it another way, for this to work we'd have to introduce a special class of builtins that can produce multiple arguments regardless of `IFS` (and then figure out some way to expose this feature to fishscript as well). And removing IFS would end up breaking a truly massive amount of fishscript.

**Comment by joelmaxuel** [comment] 2018-07-28 03:04
Maybe there is another way around this for my use case; I am not seeing one without having multi-line output support for a variable.

I use [`screenfetch`](https://github.com/KittyKatt/screenFetch) for a (rather) quick display of system status upon opening a terminal.  I originally set it up the lazy way at the bottom of config.fish:
    set fish_greeting ""
    echo
    screenfetch

However doing it this way has ill effects when pushing files via `scp` to that account with it active (first couple lines of screen appears instead of progress notification; file does not copy).  So I attempted to set `screenfetch` as the `fish_greeting` - `scp` was happy as a result, but due to lack of line breaks, my eyes are not.
    set fish_greeting (screenfetch)

I tried piping `string split '\n'` as mentioned in issue 2490 to no avail.  Also, to ensure this is not a problem unique to output of `screenfetch`, I tried the same methods with `cat /proc/cpuinfo` instead of `screenfetch`.  The newlines get stripped every time.

**Comment by krader1961** [comment] 2018-07-28 03:31
@joelmaxuel You should always predicate anything that should only be done for interactive shells on `if status is-interactive`. You can also capture multiline output without splitting it on newlines easy enough: `screenfetch | read -z fish_greeting`.

**Comment by mhubig** [comment] 2019-03-20 12:18
Lot of stuff to read ... what I am missing is a way to do this:
```
export GOOGLE_CLOUD_SQL_CREDENTIALS=(cat google-cloud-sql-credentials.json)                                           ```
and beeing able to do this, would ease up the use of googled examples:
```
export GOOGLE_CLOUD_SQL_CREDENTIALS=$(cat google-cloud-sql-credentials.json)                                           ```

**Comment by ridiculousfish** [comment] 2019-03-26 03:09
@mhubig simplest way as of fish 3.0:

    export GOOGLE_CLOUD_SQL_CREDENTIALS=(cat google-cloud-sql-credentials.json | string split0)

you can make a little non-splitting helper:

    function cat1 ; cat $argv | string split0 ; end
    export GOOGLE_CLOUD_SQL_CREDENTIALS=(cat1 google-cloud-sql-credentials.json)

though I don't think we can honestly close this yet.

**Comment by jeremy-gu10** [comment] 2019-06-09 05:03
I completely agree with @dag's first fix [here](https://github.com/fish-shell/fish-shell/issues/159#issuecomment-17713601). If there is any form of variable substitution within strings, all of the other forms of substitution should be allowed. Its only function is to "escape" whitespace.
Just replace
`"string"`
with
`eval echo 'string'`
Note: remember to set the (extremely, as discussed above) annoying `IFS` variable to an empty string

**Comment by jeremy-gu10** [comment] 2019-06-09 05:05
I completely agree with @dag's first fix [here](https://github.com/fish-shell/fish-shell/issues/159#issuecomment-17713601). If there is any form of variable substitution within strings, all of the other forms of substitution should be allowed. Its only function is to "escape" whitespace.
Just replace
`"string"`
with
`eval echo 'string'`
Note: remember to set the extremely annoying `IFS` variable to an empty string

**Comment by lilyball** [comment] 2019-06-09 20:49
Maybe we should add a `string nosplit` command for this? `foo | string split0` is a cute hack, but won't quite do what we want if the string actually contains NULs. I realize we can't store NULs in a variable (or, apparently, pass them as an argument to another command), but it might be nice to fix that someday.

Of course, it's still kind of kludgy to say that the official way to disable newline splitting is to pipe to a magical command. I'd prefer some kind of dedicated syntax for this.

**Comment by faho** [comment] 2019-06-10 17:20
>I realize we can't store NULs in a variable (or, apparently, pass them as an argument to another command), but it might be nice to fix that someday.

Sooo.... we can't pass them as an argument because in unix arguments are passed as... NUL-terminated strings. And we also can't pass them as exported variables because in unix the export array is... NUL-terminated.

Which immediately reduces the use of NULs in a shell-context quite a bit. The only possiblity would be to store them internally, allow passing them to builtins (though that alone is a bit of a rearchitecturing), and then allow doing `echo $var | thing`. That's not massively useful because you don't often deal with "binary" data in a shell-context, but there's some merit there. IIRC, that's what zsh does.

But... what would `nosplit` do *right now*? It would have to either do the same as `string split0` (which means lying), or keep the NULs (which means they'd truncate "automatically"), or truncate manually.

I'd probably go for keeping the NULs and just letting unix take its course.

**Comment by lilyball** [comment] 2019-06-10 18:28
Good point about unix not letting us pass them as arguments, but in the past I have wanted to stuff a string with NULs in it into a variable in order to later pipe to a command, like

```fish
set -l foo
if condition
    set foo (cmd-emitting-NULs)
else
    set foo (other-cmd-emitting-NULs)
end
echo "$foo" | xargs -0 …
```

In any case, even if we never support this scenario, it's still just nonobvious that `string split0` is the right thing to use, especially as that won't provide the guarantee that the resulting variable has only one entry. So I'd expect `string nosplit` to literally do no splitting, which would then invoke automatic NUL truncation behavior (and therefore in the future if we ever start preserving NULs then this would automatically preserve them too).

Incidentally, after having thought about it, I'm inclined to call this `string collect` now, because it "collects" all the lines into a single variable. This makes a bit more conceptual sense when considering something like `foo=(echo $arrayVar | string collect)`.

**Comment by paragbaxi** [comment] 2019-06-16 02:05
Just wanted to throw in that this impacts Splunk:
`(clear; '/Applications/Splunk/bin/splunk' start || touch "/tmp/splunk_start_failed_14856"); rm "/tmp/splunk_start_running_32525" 
fish: Command substitutions not allowed`

**Comment by lilyball** [comment] 2019-06-16 03:39
@paragbaxi Your listed command is unrelated to this issue, and is simply a case of you're trying to use a command substitution as the whole command instead of as an argument, and Fish only allows it in argument position. It's not clear why you're using a command substitution at all, you could just delete the parens in the command you listed, but if you have some particular need to group the commands together then this is what `begin; commands_go_here; end` is for.

**Comment by lilyball** [comment] 2019-06-16 05:42
I've gone ahead and submitted a PR for `string collect` as https://github.com/fish-shell/fish-shell/pull/5943. As I state in the PR, I don't think this new command should be sufficient to close this issue, as there's value in having dedicated discoverable syntax for this (a `string` command is not where I'd expect users to look first when trying to figure out how to capture multi-line output).

Also see #5942 wherein I argue that `string join` should disable implicit splitting of its output, as doing something like `set contents (cat filename | string join \n)` is something users might guess, and yet the `string join \n` ends up doing nothing at all.

**Comment by lilyball** [comment] 2019-06-16 23:01
With the new `string collect` command, maybe we should just tweak the parser to detect the attempted use of `$()` inside double-quotes and suggest `| string collect -n` instead? (I say `string collect -n` instead of `string collect` because `"$(foo)" in Bash trims a trailing newline).

**Comment by ngortheone** [comment] 2019-07-03 16:52
I was using Amazon's ECR the other day, and in order to log in they tell me to do

bash/zsh
```
$(aws ecr get-login --no-include-email --region us-east-1)
```

I tried this in fish:
```
(aws ecr get-login --no-include-email --region us-east-1)
fish: Command substitutions not allowed
```
But it says that command substitutions not allowed. Is there something I can do to make this work?

**Comment by lordlycastle** [comment] 2019-07-03 17:01
@ngortheone what is the output of that function. Can you save it to file and show us?

**Comment by faho** [comment] 2019-07-03 17:03
>But it says that command substitutions not allowed. Is there something I can do to make this work?

@ngortheone: This is the entirely wrong issue for this, but here's what you do:

You're trying to run the output of a command substitution as a command. Fish doesn't allow that, but it does allow running variable contents.

So:

```fish
set -l var (aws ecr get-login --no-include-email --region us-east-1)
$var
```

or just

```fish
env (aws ecr get-login --no-include-email --region us-east-1)
```

**Comment by ngortheone** [comment] 2019-07-03 17:37
@faho 
sorry, the issue looked relevant. Is there a relevant issue open?

I tried the suggested above and it didn't work.

the command itself emits another command. Example output (redacted as it has credentials)
```
~ aws ecr get-login --no-include-email --region us-east-1
docker login -u AWS -p VERYVERYLONGBASE64 https://1234567890123.dkr.ecr.us-east-1.amazonaws.com
```


The error messages are
```
 env (aws ecr get-login --no-include-email --region us-east-1)
env: output_of_command_here: File name too long
``` 

Or sometimes base64 credentials end with  '== ' then I get
```
```

**Comment by faho** [comment] 2019-07-03 17:46
> sorry, the issue looked relevant. 

It is not. This is about introducing something similar to `something "$(somethingelse)"`.

>Is there a relevant issue open?

This is one of those things that would work better on gitter.

But anyway:

Unlike bash et al, fish does not split command substitutions on spaces, only newlines. You'll see that it's passing something like `'docker login -u AWS -p...'` as *one argument*, which is why it's complaining that the filename is too long (if it wasn't, it would most likely complain that it doesn't exist).

So what you want is to split them on space, so you need to use `string split`

```fish
 env (aws ecr get-login --no-include-email --region us-east-1 | string split " ")
```

**Comment by ngortheone** [comment] 2019-07-03 17:50
It worked, thanks!

**Comment by graywolf-at-work** [comment] 2019-10-02 12:12
> I assume you mean `printf`, and that would work but it has to spawn a separate process which is slow.

```
+   $ fish
Welcome to fish, the friendly interactive shell
wolf@wsshowmax ~> type printf
printf is a builtin
```

**Comment by lordlycastle** [comment] 2020-08-12 08:33
Last related comment was over a year ago. This is still a big missing feature with no good/standard way of doing it. Are we not happy with `"$(echo $var)"`? Are we waiting for something that can be helped?

**Comment by lilyball** [comment] 2020-08-12 19:13
We have `string collect` now, but as I stated before I think we need to add a discovery mechanism for users before we can close this issue.

**Comment by ridiculousfish** [comment] 2020-08-13 22:20
I agree with keeping this open. We'll probably end up supporting `"$(cmd)"` syntax, but it's a lot of work.

First step I guess is to design it. In bash `"$(cmd)"` establishes a new quoting context:

    echo "$(echo "nested quotes!")"

do we want to allow that, to arbitrary depth? Or can we start with something useful but more restricted, which would be easier to implement?

**Comment by krobelus** [comment] 2020-08-15 13:57
I think we can hack the parser to close double quotes on `$(` and reopen them on the matching`)`.
So `echo "b$(...)c"` is virtually tokenized as `echo "b"$(...)"c"`.
This way we get nesting, syntax highlighting and completion for free  - I'm working on a prototype.

The cost here is the more complex quoting syntax - a single regex will no longer be enough to correctly highlight such strings.
Probably there are ready solutions to support this kind of syntax in most 3rd party highlighters.

If we don't support quotes inside `"$()"`, then the highlighting syntax would remain unchanged.
The nesting is less important than in bash but it feels natural to include it eventually.

Not sure what to do about unquoted `$()`, it could mean `"$()"` or `()`, but we can leave it unsupported for now.

**Comment by mikelei8291** [comment] 2020-10-01 10:57
Why is this still not solved after 8 years of discussions? By not using the `$()` syntax we ended up add two more `"` symbol in the command, e.g.:
```fish
sed -i "s/<uid>/$(id -u)/g" *
```
vs
```fish
sed -i "s/<uid>/"(id -u)"/g" *
```

Is this the so called "user-friendly"?

**Comment by jos128** [comment] 2020-10-15 23:40
As someone rather inexperienced with shell scripting, I think it's intuitive and very hard to debug,  why a variable can't "simply catch the output of a command".

It seems like `string collect` still tampers with the input, by removing the trailing new line. 

```console
# 1
> printf "A\nB\nC\n" | od -a
0000000   A  nl   B  nl   C  nl
0000006

> set var (printf "A\nB\nC\n")
> printf "$var" | od -a
0000000   A  sp   B  sp   C
0000005

# 3 Expected: (1)
> set var (printf "A\nB\nC\n" | string collect)
> printf "$var" | od -a
0000000   A  nl   B  nl   C
0000005
```

So it seems, `string collect` replicates `$()` problems. This gets really messy, if you try to catch something with `CRLF`, like an HTTP header from curl. I really, really like fish, but this issue makes it very impractical for scripting.

**Comment by faho** [comment] 2020-10-16 05:10
>It seems like string collect still tampers with the input, by removing the trailing new line.

@jos128: `string collect -N`, if you really must have the trailing newline.

In many many many cases you don't.

**Comment by jos128** [comment] 2020-10-16 09:37
> In many many many cases you don't.

@faho: That may be true, but it is not what's naively *expected*. Personally, I think stripping the last newline should be the option. As I said, it gets really unintuitive with `CRLF`, as that prints fine itself, but is very obfuscated, if processed in a terminal. E.g.

```bash
> set var (curl "https://example.com" -D - -s -o /dev/null)
> printf "$var"
> printf "$var" | grep server
 content-length: 1256g)
```

Of course, in this case `string collect` does the trick, but I hope you see how this is *not expected*. Especially since it works just fine in bash. Of course, with HTTP headers, stripping the last newline may cause even more significant, but hidden problems downstream.

Sorry, for being OT. I thought the perspective of someone who doesn't take any internals for granted might be of value for design decisions. To me this behaviour of fish seems arcane, so as an outsider it appears to not match fish's design pattern.

**Comment by mikelward** [comment] 2021-01-05 00:51
+1 to supporting command substitution inside double quotes.

It feels really weird that

```
basename (somefunction)
```

will work just fine if `somefunction` produces output, but I get

```
basename: missing operand
Try 'basename --help' for more information.
```

if it produces no output.

I can work around this by doing

```
set -l something (somefunction)
basename "$something"
```

but that feels like it should be unnecessary.

```
basename (somefunction | string collect)
```

also fails in the same way.

Of course in shell, I would just do

```
basename "$(somefunction)"
```

**Closed** 2021-07-13 19:33 UTC
Labels: enhancement

**Comment by pirate** [comment] 2021-07-13 23:20
The new support for `"$(cmd)"` added in #8059 is amazing, thank you so much @krobelus for working on this, and @ridiculousfish for approving it!! 🎉 👏 👏 👏 ✨ 

For anyone curious on how the new `"$(cmd)"` support works, the documentation for it is added here: https://github.com/fish-shell/fish-shell/pull/8059/commits/bf5d2d1d557cac73850782b978b04990a72b9d2a. Here are some quotes:

> A command substitution can have a dollar sign before the opening parenthesis like ``outercommand $(innercommand)``. This variant is also allowed inside double quotes. When using double quotes, the command output is not split up by lines.

> A command like ``echo (cmd | string collect)`` is mostly equivalent to a quoted command substitution (``echo "$(cmd)"``). The main difference is that the former evaluates to zero or one elements whereas the quoted command substitution always evaluates to one element due to string interpolation.

> fish's command substitution syntax has been extended: ``$(cmd)`` now has the same meaning as ``(cmd)`` but it can be used inside double quotes, to prevent line splitting of the results. (:issue:`159`).

Example usage:
```bash
$ echo "zero $(echo one\ntwo\nthree) four"
    zero one
    two
    three four
```

P.S. @krobelus do you have a Paypal/Patreon/Github Sponsors/GitTip/etc.? I'd love to send you a tip as a thank you for working on this feature, your work here closes one of the longest outstanding issues I've been waiting for on the fish project, and I'd love to show my thanks. 🙏
