### ISSUE TITLE
MacOS Sierra breaks `fish help`

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#3449] opened 2016-10-12 20:45 UTC
- [ ] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)? yes
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*? yes

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: MacOS Sierra, iTerm2

Talk about the the issue here. 

## Reproduction steps
1. `help`

## Results
Browser window opens with no address, empty content.

**Comment by krader1961** [comment] 2016-10-12 23:16
Works for me. What is your default browser? Do you have a $BROWSER env var and if so what is its value? On macOS the help function should be doing the equivalent of

```
osascript -e 'open location "file:///usr/local/share/doc/fish/index.html"'
```

What happens if you run that from a shell prompt?

**Comment by nyarly** [comment] 2016-10-12 23:55
I'm using Chrome. I had `BROWSER=chromium-browser`, but unsetting that doesn't make a difference. The `osascript` command has the same result, and unwrapping it down to just `open "file:///usr/local/share/doc/fish/index.html"` likewise (that is: all open a new browser window with nothing in it.) Pasting that URL into any browser window brings up the docs that I expect.

**Comment by krader1961** [comment] 2016-10-13 01:13
Passing the file URL to the `open` command also works for me. So there is something wrong with your installation. The question is what? Can you even `cat /usr/local/share/doc/fish/index.html`? Although, having asked that, I'll point out that if I do `chmod 0 /usr/local/share/doc/fish/index.html` then `open file:///usr/local/share/doc/fish/index.html` fails with

```
LSOpenURLsWithRole() failed with error -5000 for the file /usr/local/share/doc/fish/index.html.
```

So I doubt it's as simple as a permission problem. Can you even open a browser window and paste the file url into it and have the page rendered?

**Comment by nyarly** [comment] 2016-10-13 21:54
As I said, I can paste the URL in directly and get the view I expect. So it looks like it's some behavior of Chrome with file:/// URLs? What's weird is that this just started when I switched to Sierra.

**Comment by krader1961** [comment] 2016-10-13 22:19
I'm using Chrome as well on a MacBook and a MacPro both running macOS Sierra. But I am on the beta testing track. So it's possible this is something that was broken in a general availability release that has been subsequently fixed in a beta release. What happens if you try this with another HTML document that is part of macOS such as `open file:///usr/share/doc/bash/bash.html`?

**Comment by nyarly** [comment] 2016-10-13 22:32
Huh. That works as intended.

In experimenting with it, I now cannot get it broken again. In fact: `help` now works as intended, so :shrug:

**Comment by nyarly** [comment] 2016-10-13 22:34
ACTUALLY: I found the variable. 

Fish bare in iTerm2, it works. 
From within Tmux, it doesn't work.

**Comment by krader1961** [comment] 2016-10-13 22:37
> From within Tmux, it doesn't work.

You're going to find other things don't work inside any shell running within tmux. The solution is a handy utility named `reattach-to-user-namespace`. The way I use it is via this line in my *.tmux.conf*:

```
set-option -g default-command "exec reattach-to-user-namespace -l /usr/local/bin/fish"
```

You can install it with `brew install reattach-to-user-namespace` assuming you're using Homebrew; otherwise Google is your friend.

**Closed by krader1961** 2016-10-13 22:37 UTC
Labels: question

**Comment by nyarly** [comment] 2016-10-13 23:41
In fact, I *am* going exactly this, though. I just doublechecked, and I'm using reattach-to-user-namespace, and I've confirmed that I've brew'd it up to the most recent version.

**Comment by krader1961** [comment] 2016-10-14 00:34
I don't know what to  tell you. I've confirmed that is the solution to your problem. It works for me if I use it and fails if I don't. Did you restart the tmux server after changing your tmux config? Are you literally using the the default-command I put in my previous comment? I ask because there are different opinions about how best to employ reattach-to-user-namespace. What happens if you type

```
reattach-to-user-namespace open file:///usr/share/doc/bash/bash.html
```

P.S., This [web page](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard) is the authoritative source of information about this problem and the solution.

**Comment by nyarly** [comment] 2016-10-14 16:01
Just confirmed: `reattach-to-user-namespace open file:///usr/share/doc/bash/bash.html` opens a new empty browser window (i.e. failure behavior)

I've had `set -g default-command "reattach-to-user-namespace -l fish"` in my tmux.conf for as long as I've run Tmux on a Mac - granted, this isn't exactly the same as your suggestion, but it's nearly identical.

All things considered this is a relatively small issue, but it seemed worth raising.

**Comment by krader1961** [comment] 2016-10-14 17:07
> All things considered this is a relatively small issue, but it seemed worth raising.

Most definitely. And I wish we could find a solution because if one person runs into it the odds are good someone else will as well. So even though it's clearly a problem external to the fish project I'd love to see this issue updated with root cause and a fix. I'd recommend talking to the author of the reattach-to-user-namespace program to see if they can suggest troubleshooting steps.
