### ISSUE TITLE
fish executes completions even when the command doesn't exist

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4634] opened 2018-01-02 20:04 UTC
On a clean installation of fish 2.7.0 on debian buster, I began typing `git clone ...` forgetting I hadn't installed it yet. As soon as I typed in `git `, fish attempted to execute the completions for it:

```fish
mqudsi@armbuild ~> git fish: Unknown command 'git'
/usr/share/fish/completions/git.fish (line 154):
git config -z --get-regexp 'alias\..*' | while read -lz alias command _
^
from sourcing file /usr/share/fish/completions/git.fish
        called on standard input

in command substitution
        called on standard input
```

I'm not sure what to suggest. This would have been an error as soon as I hit the `enter` key.. can we unconditionally require that `type head` return `0` before engaging in argument completion globally?

**Comment by faho** [comment] 2018-01-02 22:15
Duplicate of #2365.

**Closed by faho** 2018-01-02 22:15 UTC
