### ISSUE TITLE
Exiting to bash after "sudo fish" does not release the TTY

### ISSUE THREAD

**Issue by jsternberg** [fish-shell/fish-shell#1960] opened 2015-02-27 18:51 UTC
I'm not entirely sure if the subject of this ticket is correct, but here's a more thorough description.

If I am running bash and I use `sudo fish`, everything is fine. But when I use `exit` or push `Ctrl+D` to exit fish, I cannot see what I type into the bash shell anymore. I can still type, but I just can't see what I'm typing. If I use `reset` in bash, everything returns to normal.

This happens when using `sudo fish` or when `fish` is the default shell for the user. Invoking `fish` without sudo doesn't seem to trigger this problem.

**Comment by ridiculousfish** [comment] 2015-02-27 19:33
I couldn't reproduce on OS X with iTerm2 - What OS and terminal are you using?

**Comment by jsternberg** [comment] 2015-02-27 20:08
I'm able to reproduce it with iTerm2 on OS X and in an SSH session to Ubuntu 14.04. I also use tmux, but I'm able to reproduce it without tmux. I'm also able to reproduce it in "Terminal" on Mac OS X.

About half of the engineers in my team have the problem and the other half have never experienced it. We haven't been able to figure out any rhyme or reason behind this yet.

**Comment by ridiculousfish** [comment] 2015-02-27 20:09
Are you using a released fish or one from HEAD?

**Comment by jsternberg** [comment] 2015-02-27 20:12
I'm on Mac OS X 10.9.5 and iTerm Build 2.0.0.20141103. I'm using fish version 2.1.1. I tried to use a newer fish from a tagged version and it didn't fix the issue.

It doesn't appear to happen when you use zsh. It appears to only happen with bash. Bash on my Mac computer is 3.2.53 and it's 4.3.11 on the Ubuntu machines.

**Comment by zanchey** [comment] 2015-03-11 06:19
I can reproduce this with 2.1.1 on Linux, but not with the current master build (from 1116929).

**Comment by zanchey** [comment] 2015-03-11 07:07
Setting `use_pty` on in `sudoers` makes the behaviour go away.

The tail end of the `strace` output is below:
```
ioctl(0, SNDCTL_TMR_TIMEBASE or TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = ? ERESTARTSYS (To be restarted)
--- SIGTTOU (Stopped (tty output)) @ 0 (0) ---
```

So the TTY write attempt gets SIGTTOU and the process terminates.

**Comment by jsternberg** [comment] 2015-03-11 15:29
I can confirm that `use_pty` in the `sudoers` file appears to fix the problem on Mac OS X and Linux.

**Comment by zanchey** [comment] 2015-03-12 01:45
Could you tell us which version of the master build you tried?

**Comment by ridiculousfish** [comment] 2015-03-24 21:17
I was able to reproduce it with a ubuntu virtual machine. It looks fixed in master to me. I bisected the fix to e05743d0ba1201745d40c5ebc1c8ee336ff43b64 which was the fix for #1002.

**Comment by ridiculousfish** [comment] 2015-03-24 21:20
I think this is likely another symptom of #1002. @jsternberg if you would like to confirm on master that would be helpful, but if you prefer to wait for us to cut a tag, that's fine too. Thanks for reporting this either way!

**Comment by jsternberg** [comment] 2015-03-24 21:22
I'll try to test it within the next day or so to confirm. Thanks for all of the effort in tracking this down.

**Closed** 2015-04-20 05:51 UTC
