### ISSUE TITLE
Fish doesn't handle long prompts correctly, consistently getting the number of lines wrong

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10827] opened 2024-11-01 19:33 UTC
I've recently been doing some work that involves a lot of long-form, multi-line text at the prompt, either piped into a command or provided as a (maybe quoted) argument, and something in fish reader seems to blow up after text exceeds a certain length or number of lines.

In the following asciinema recording, you can see how fish is mixed up about the number of lines a prompt is supposed to take. In the recording, I paste just a few paragraphs into fish (sample text provided below), causing the following issues:

* Although the text does not ~~begin or~~ end in any whitespace (you can see this when I use alt-v to edit the prompt in neovim, inspecting the start and end of the document), fish adds multiple line breaks to the end of the prompt (visible in the recording).
* Navigation via the up/down arrows breaks; when focus is at the end of the prompt (including the incorrect blank lines at the end), pressing `up` repeatedly causes the text to shift (when pressing `up` while the cursor is painted in the incorrect whitespace) and to jump lines (when the cursor is painted in the actual whitespace) and pressing `down` does not "undo" the `up` input (it moves to a different (correct?) location on `down` but not on `up`).
* Clearing the long prompt with `ctrl-c` (bound to `bind ctrl-c 'commandline -f cancel; commandline ""'`) clears only some of the text, leaves text that's no longer actually there visible, does not result in the prompt reappearing (visible in the recording)

[![asciicast](https://asciinema.org/a/OfqZ1GuwaMobYXsqRSlAtzATB.svg)](https://asciinema.org/a/OfqZ1GuwaMobYXsqRSlAtzATB)

You can reproduce this by copy-and-pasting the following nonsense text into fish:

```
What is Lorem Ipsum?

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Why do we use it?

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

Where does it come from?

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
Where can I get some?

There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
```

Unlike many of the terminal emulator-specific issues, this one reproduces in full in the asciinema recording and has been observed consistently across tty emulators and platforms.

**Comment by krobelus** [comment] 2024-11-01 19:47
should be fixed by 04c913427 (Limit command line rendering to $LINES lines, 2024-10-25) and later commits to `src/screen.rs`.
Though that one implements a weird `scrolloff` behavior which could certainly be improved.
Also, if a super-large line is soft-wrapped, the behavior can be a bit surprising but I'm not aware of any glitches.
It's possible that there are some cases left where we fail to redraw the prompt

**Closed by krobelus** 2024-11-01 19:47 UTC

**Comment by mqudsi** [comment] 2024-11-01 23:44
Oh, I missed that commit from last week; thanks for tackling this.

Is there a reason this has to be handled in such a special manner? In particular, I don't understand why it has to be break scrollback.

**Comment by krobelus** [comment] 2024-11-02 01:32
> Is there a reason this has to be handled in such a special manner? In particular, I don't understand why it has to be break scrollback.

that was done mainly because I wasn't sure if we can redraw things that are off-screen.
I think fish redraws the whole commandline buffer fairly frequently, so if we cannot clear what we had previously rendered that would add a lot of redundancy to scrollback.
Probably there is a way to clear this; then we can print the off-screen prefix again but I don't think we can print the off-screen suffix without forcing it to be visible. So if we do this, it will be somewhat inconsistent.

But of course these concerns don't hold for the last time the commandline is rendered (pre execution).
So to fix the scrollback regression we simply need to disable this scrolling logic on the last render
(and make sure that such pre-exec rendering actually happens for scrolled command lines).

In future we should add some ellipses to indicate there's more text above/below.

> The up/down behavior with wrapped lines is indeed non-intuitive (though logical); vim has the same behavior by default

Good point. We are emulating emacs, so we should change that.

**Comment by krobelus** [comment] 2024-11-02 08:52
I have a change to fix scrollback for commands that have been executed.
Maybe we can also fix it before execution.
That needs a command to clear part of the scrollback.
Can't find anything on https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
There is "Erase Saved Lines" but that deletes the entire scrollback.
