### ISSUE TITLE
fzf key bindings not working anymore

### ISSUE THREAD

**Issue by benruijl** [fish-shell/fish-shell#6979] opened 2020-05-07 15:10 UTC
The `fzf` key bindings have an issue: pressing ctrl+r,ctr+t, and alt+c just give me a blinking cursor, text does not appear anymore, and it's hard to get back to the console: ctrl-c works for ctrl+r but not for ctrl+t.

I use the official bindings:
```
function fish_user_key_bindings
    fzf_key_bindings
end
```

with versions:
fish, version 3.1.1
fzf, version 0.21.1

and the bug appears both in gnome-terminal and kitty. My setup used to work.

**Comment by faho** [comment] 2020-05-07 15:17
Fixed in 3.1.2, duplicate of numerous issues.

**Closed by faho** 2020-05-07 15:17 UTC
