### ISSUE TITLE
if first line of a command has scrolled out of view strange behavior happens

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1219] opened 2014-01-01 19:42 UTC
Type `begin`, press enter along with other letters multiple times, so `begin` disappears from the terminal (because it's above terminal length), and scroll up to `begin`. Strange stuff will happen.

**Comment by krader1961** [comment] 2016-11-17 05:56
I can reproduce this. Whether it's worth trying to fix it is debatable. I'd rather see us make something like my `edit_command_line` function a standard part of fish and bound to sequences like \ee and \ev to make it easy to perform non-trivial edits of the command line using a real editor.

**Comment by faho** [comment] 2020-09-26 08:47
Closing in favor of #7296 because that explains the behavior more clearly.

**Closed by faho** 2020-09-26 08:47 UTC
Labels: bug
