### ISSUE TITLE
Completion mode for hierarchical object paths

### ISSUE THREAD

**Issue by jtojnar** [fish-shell/fish-shell#8578] opened 2021-12-23 16:11 UTC
I maintain completions for Nix package manager, which supports nested scopes for packages (packages are accessible through paths like `fish`, `haskellPackages.pandoc` or `python3.pkgs.requests`). For both performance reasons and to avoid overwhelming users, we currently only complete paths on the current level, similarly to how filename completion works. The disadvantage is that when I complete `nix build .#haskellP`, I get `nix build .#haskellPackages ` and need to press backspace, type `.` and tab again to complete the next level.

It would be nice if we could inform fish somehow that it is now completing paths and select a path separator character. That would allow us to have `haskellPackages.` in the completion list and fish would know that since it ends with a path separator, it should not insert a space after it, just like it does not insert a space after one completes a directory name.

**Comment by faho** [comment] 2021-12-23 16:40
Tracked in #7832 (which I've now retitled)

**Comment by faho** [comment] 2021-12-23 16:40
Duplicate of #7832

**Closed by faho** 2021-12-23 16:40 UTC
