### ISSUE TITLE
History is regularly reset (wiped)

### ISSUE THREAD

**Issue by bbc2** [fish-shell/fish-shell#2335] opened 2015-08-26 19:34 UTC
Every few days, my fish history starts back from scratch.  I thus lose many useful suggestions from my shell. I haven't determined how to reproduce it.  I have been using fish for at least a year but I think this problem has only started happening one or two months ago.

I have noticed issue #1572 about a wiped history due to the use of the history files by multiple users.  I'm not sure it is my case although I regularly use `sudo -Es`.

It seems like it is a problem with fish rather than my distribution so I'm posting the report here, upstream.

Additional info:
* fish, version 2.2.0 (2.2.0-3 in Archlinux)
* my Archlinux system is regularly upgraded

**Comment by pickfire** [comment] 2015-08-27 09:15
I am using archlinux too and `wc -l` show 6000+ but I am using the latest fish (git).

**Comment by faho** [comment] 2015-08-27 12:41
>I'm not sure it is my case although I regularly use sudo -Es.

For those reading along at home, that's "launch a shell, keeping the environment variables intact". The shell is read from $SHELL, which should be fish, so this seems like a duplicate of #1572. As that's closed, we should keep this one open and actually solve it - for history _and_ fishd files (#2176).

Currently, the workaround I can offer is simply "don't do that", as the "-E" switch keeps $XDG_CONFIG_HOME, among other things.

**Comment by bbc2** [comment] 2015-08-27 13:33
Thank you for the explanation, I'll try the workaround.  That use of sudo may well be the cause but I'm frustrated because I can't reproduce the problem.  Were you able to?

**Comment by pickfire** [comment] 2015-08-28 16:59
Is it solved?

**Comment by faho** [comment] 2015-08-28 17:10
No.

If it were, this issue should have been closed.

**Comment by bbc2** [comment] 2015-09-19 09:54
I've updated my system and fish (2.2.0-3 to 2.2.0-4) today and experienced the almost full wipe again.  I've subsequently played a bit with `sudo -E` and I managed to truncate the history a few times.  In those cases, it also becomes owned by root, but as soon as I enter a command in a non-privileged fish, it turns back to being owned by my user.  I don't really understand how fish manages the history but I hope this will help in finding a solution.

**Comment by faho** [comment] 2015-09-19 10:24
> In those cases, it also becomes owned by root, but as soon as I enter a command in a non-privileged fish, it turns back to being owned by my user.

Yeah, that's what I would have expected.

> I don't really understand how fish manages the history but I hope this will help in finding a solution.

IIRC, fish creates a new history file and then moves it into place (note that because it doesn't modify a _file_, but a directory entry, you can overwrite a root-owned file with your permissions even though you can't read or write to it because you do have write permission on the directory). What it should do (and currently doesn't) is copy the permissions and ownership of the old file. In that case the history file would never be owned by root and hence this would never(tm) occur.

**Closed** 2015-09-26 09:21 UTC

**Comment by ridiculousfish** [comment] 2015-09-26 09:22
Fixed as 871a2088dbfe89f8d2dabfd07b6cb42f88a042c6 per faho's suggestion (thanks faho!). I verified that I could reproduce the problem before the fix but not after.
