### ISSUE TITLE
Background jobs are not in background

### ISSUE THREAD

**Issue by smoneck** [fish-shell/fish-shell#4020] opened 2017-05-09 12:53 UTC
Since a few months I have the problem of not being able to close the terminal anymore without killing the job started from `fish` that was actually supposed to run in the background.

Reproduce:
> ⋊> ~ zathura test.pdf &
> 
> Press `Ctrl + d`
> 
> > There are still jobs active (use the jobs command to see them).
> > A second attempt to exit will terminate them.

Fish version 2.5.0
xterm-termite
4.10.13-1-ARCH

`sh -c 'env HOME=$(mktemp -d) fish'` is not affecting this issue.

**Comment by maxried** [comment] 2017-05-09 14:20
I think this is expected behaviour, this is what the `disown` command is for.

https://asciinema.org/a/64ywg6azz38gyys4tv72wuqex

**Comment by maxried** [comment] 2017-05-09 14:25
Or use 
`zathura test.pdf & disown`

**Comment by faho** [comment] 2017-05-09 15:22
@smoneck: This has been changed in 2.5.0 on purpose. The idea is that most of the time putting a job in the background isn't because you want it to keep running indefinitely, but because you e.g. want it to to its thing while you continue using that shell instance.

So instead of _opting out_ of having something run (by closing it before you quit the shell), you should _opt in_ with `disown`, as @maxried said.

Unfortunately disown isn't in 2.5.0, but it will be in 2.6.0, which will be released in a matter of weeks.

**Comment by smoneck** [comment] 2017-05-09 18:34
@maxried: To me the idea of the ampersand is to decouple the process from the shell and yes, keep it running indefinitely if it's not terminating by itself. Having to append a `disown` each time I use the apersand is not acceptable to me. So, could you tell me if there is any way to disable this "feature"?

**Comment by krader1961** [comment] 2017-05-11 05:40
Sorry, @smoneck, there is no fish "option" to change the behavior you find objectionable. And, if I have anything to say about it, there never will be. This has been discussed extensively in other issues so I'm not going to rehash those arguments here. Other than to say that fish originally behaved as it currently does. It was then changed, with zero discussion, to behave as you desire after someone, who did not understand how background jobs and terminal job control work, asked that it be changed. As of fish 2.5.0 the behavior was reverted to the old behavior.

When you say

> To me the idea of the ampersand is to decouple the process from the shell and yes, keep it running indefinitely if it's not terminating by itself.

suggests that you may not understand how background jobs launched from an interactive shell are intended to work. Just like the person who requested the behavior that fish implemented for a short interval (see my previous paragraph). Do you not expect to be able to use the `fg` command on those jobs?

That there is confusion about this is in no small part because shells like bash have introduced configuration options to affect how background jobs are handled when the parent interactive shell exits. Adding such options is anathema to fish.

There are several ways to "disable" this behavior. The legacy solution is the `nohup` command. There is also the recently introduced `disown` command. We are also discussing adding an option to `command` in issue #4010 to make this possible when explicitly putting a command in the background. Another solution is to define a function that uses the double-fork trick to detach a process from the current shell. And, lastly, you can use mechanisms like `cron` and `launchctl` (on macOS) and similar mechanisms on other operating systems to run jobs persistently independent of an interactive shell.

**Comment by krader1961** [comment] 2017-05-19 04:10
I'm going to close this since @faho explained why fish, once again, does not let background jobs from an interactive shell continue running by default.

@smoneck, You are welcome to reopen this issue (or open a new one) if you believe you have a cogent argument for the behavior you prefer. In particular since there are multiple methods for obtaining that behavior but zero methods for doing the opposite.

**Closed by krader1961** 2017-05-19 04:10 UTC
Labels: question
