### ISSUE TITLE
Track status of documentation, release-note follow-through on PRs

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3195] opened 2016-07-03 19:47 UTC
We should ~~keep PRs open until we merge~~ try to better keep track of changes to docs, CHANGELOG.md, and tests by using GitHub tasks.
 
By closing PRs before required work associated with them is complete, we're letting things slip through the cracks and lose track of stuff. GitHub tasks (checkboxes) seem like a decent solution which will show up outside the PR itself and affect our milestone completion.

**Comment by floam** [comment] 2016-07-03 19:52
I spent today goofing with templates to try to improve this but I'm interested in other approaches and thoughts.

**Comment by krader1961** [comment] 2016-07-04 02:42
A PR should be closed as soon as it is merged. I do agree that we need to be more careful about letting changes be merged that are missing needed documentation updates. Case in point is the PR #3175 I recently merged. I explicitly pointed out in my feedback that the contributor had not updated the documentation but I would take care of doing so. Given the quirks of our documentation syntax (die, Doxygen, die) I don't think we can demand random contributors deal with updating the documentation. Nor can we reasonably expect them to write unit tests.

Whichever core dev does the merge should be dealing with those aspects of a PR. If that person is dropping the ball the rest of us should be gently reminding them of their duties. If they continue to consistently drop the ball then perhaps their master branch commit privilege should be revoked.

**Comment by faho** [comment] 2016-07-09 08:25
>A PR should be closed as soon as it is merged.

I agree - that's the main task. However, we should try to keep documentation and releasenotes in mind, though I don't think we're doing too bad a job of that. It can certainly be improved, but so can everything.

What I would _love_ is for github to display some kind of marker that, while the PR is merged, there's still some task missing. @floam  has added the tasklists to some of our PRs, which make GH display "X of Y tasks completed" in the PR overview, which isn't bad but requires modifying the opening comment, and is AFAIK unsearchable (I can't look for "is: pr is:closed has:tasks", or maybe just not via the UI).

What we have done so far is to use a "needs-docs" label, but the issue is that that would have to be removed if the docs are added.

**Comment by faho** [comment] 2016-08-04 13:18
@floam: I believe this is now handled by the changes to the PR template.

**Closed by faho** 2016-08-04 13:18 UTC
Labels: RFC
