### ISSUE TITLE
is fish NOT an interactive shell ? 

### ISSUE THREAD

**Issue by bretzel** [fish-shell/fish-shell#6491] opened 2020-01-12 14:04 UTC
fish, version 3.0.2
os: irrelevant;
Terminal: irrelevant
--------------------------------------------
For months I researched a way to get the bash'es equivalent input keystrokes for interactive menu in fish shell:
excerp from my code in a bash script:
[...]
`read -s -n 1 clef &>/dev/null`
             case $clef in
                 a|A)
                 Select normal
[...]

( Note: sorry can't format the 'code mode' ...)

the point is:
"read -s -n 1 clef &>/dev/null"

In fish, there are NO WAYS to achieve it. 
It's very sad. Because the language and syntax in fish scripting are so near a real normal programming language.

**Comment by faho** [comment] 2020-01-12 14:13
As far as I can see, this is a duplicate of #6453 - we don't currently provide a way to just read, without showing the output or prompt.

**Comment by faho** [comment] 2020-01-12 14:14
Duplicate of #6453

**Closed by faho** 2020-01-12 14:14 UTC

**Comment by bretzel** [comment] 2020-01-22 21:07
Sad. Very sad. That is why I have quit fish.
