### ISSUE TITLE
How to use Ctrl-e to end-of-line, and if already eol, eval the command?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4123] opened 2017-06-15 10:34 UTC
fish v2.6.0

By default, `Ctrl-e` is bound to `end-of-line` in **fish_default_key_bindings.fish** file, so I want to define a new function to rebind `Ctrl-e` to not only do the default `end-of-line` action but when I'm already the end of line, execute the command at the prompt, so I don't have to use right hand to hit the `Enter` key, how can I do that?

In fish script:

1. How to check if I'm already the end of line at the prompt line?
2. How to do the `Enter` key to execute the command at the promopt line?

**Comment by faho** [comment] 2017-06-15 10:48
```fish
function end-of-line-or-execute
    set -l line (commandline -L)
    set -l cmd (commandline)
    set -l cursor (commandline -C)
    if test (string length -- $cmd[$line]) = $cursor
        commandline -f execute
    else
        commandline -f end-of-line
    end
end

bind \ce end-of-line-or-execute
```

>How to check if I'm already the end of line at the prompt line?

The approach I've gone for here is to compare the cursor position with the length of the current line.

In future, we might want to have the input-functions return a status (some already do), which would make this a bit easier.

>How to do the Enter key to execute the command at the promopt line?

To do "the thing that Enter is bound to", see what `bind` says for it - `bind \r` says `bind \r execute`. So it is bound to the "execute" function. In this case that's not a fish-script function but an input-function that can be accessed via `commandline -f`.

(To figure out which sequence you need to pass to `bind`, use `fish_key_reader`)

**Comment by c02y** [comment] 2017-06-16 01:22
There is one problem, by default `Ctrl-e`(end-of-line) will jump to the end of line if there is completion (a command in history, the gray part needed to be typed) available, so I don't have to type all of the long command expression. 

But the snippet you posted here will just execute the command I didn't finish, it only works correctly when I already finish typing all the command.

Example: 

    $ man| printf   # (printf is what I didn't type, | is the cursor position)

If I hit `Ctrl-e` here in the "|" position, it will execute `man` command which is definitely what I need. Is it possible to type `Ctrl-e` **once** to jump to the end of line (even jump to the end of completion if available), type **again** to execute it. 

I can modify the snippet a bit to jump to the end of line (even jump to the end of completion if available), but after that it directly executes the command, sometimes I need to modify the completion part. If this is not possible I can just stick to the one-hit-two-actions solution.

**Comment by faho** [comment] 2017-06-16 11:58
>but it seems the results of two commandline are the same, since I already use forward-char (move to the end of line if suggestion is available) or the default end-of-line, shouldn't they be different?

IIRC `commandline -f` executions don't actually wait until the command was executed, so that returns before the commandline has changed.

I'd imagine the easiest thing to do here would be to add a return status to `end-of-line`, so you could do `commandline -f end-of-line or execute` (yes, no semicolon - the arguments to `commandline -f` are slightly weird).

Though in the long run waiting until the input function has finished is probably the best thing to do - that causes quite a bit of weirdness, and isn't at all intuitive.

**Comment by c02y** [comment] 2017-06-16 15:47
> Key:
> Is there any variable or solution that I can know if there is any completion available in the current prompt?

**Comment by faho** [comment] 2017-06-16 15:50
You mean "suggestion", and no, there isn't.

**Comment by c02y** [comment] 2017-06-17 01:11
>> commandline -f end-of-line or execute
    commandline: Unknown input function 'or'
           commandline -- set or get the current command line buffer
    
       Synopsis
           commandline [OPTIONS] [CMD]
    
    commandline: Type “help commandline” for related documentation

**Comment by faho** [comment] 2017-06-19 09:44
@c02y: Oh, sorry, this would have to be _added_ to fish, the "or" input function currently doesn't exist.

**Comment by faho** [comment] 2017-06-22 14:05
This is a slight variation on #3031. Let's close as duplicate of that!

**Closed by faho** 2017-06-22 14:05 UTC
Labels: question

**Comment by c02y** [comment] 2017-06-23 07:26
This issue shouldn't be closed, like you said, "a slight variation", we discussed **multiple ways** to solve for the problem, only one of them is like #3031

**Comment by krader1961** [comment] 2017-06-23 08:06
@c02y: You asked a question. Which was answered thus the issue was closed. Furthermore, resolving issue #3031 appears to be essential and sufficient to implementing the behavior you are requesting.

I have observed your interactions with the tmux project as well as this one. You are not doing a good job of expressing your viewpoint in a manner that is likely to result in the change you desire. Frankly, you are the sort of customer that my former employer wishes would switch to using a competitor's product.

**Comment by c02y** [comment] 2017-06-26 06:49
> You asked a question. Which was answered thus the issue was closed

I posted several paths that may solve this problem, and I'm sorry I cannot find the right solution from #3031, so I think it's better to keep it open since other people may be interested in this issue and may know the answer from other paths besides of `commandline`.

> You are not doing a good job of expressing your viewpoint in a manner that is likely to result in the change you desire. Frankly, you are the sort of customer that my former employer wishes would switch to using a competitor's product.

I like to do customization (modify the configuration file, define new functions et.) with the tools I use, and I can succeed in getting it done most of time, if I couldn't, I will ask for help from the issues page like this one. I admit that some of those posts are not necessary, maybe most people won't need it and think that why bother. But it is the beauty of highly customizeable software or open source projects.

> Frankly, you are the sort of customer that my former employer wishes would switch to using a competitor's product.

I'm not sure what the meaning "competitor's product" you were talking about is. tmux? I use both of them, they are not the same kind of tools.
