### ISSUE TITLE
Solarized Light color theme needs to set fish_pager_color_prefix properly.

### ISSUE THREAD

**Issue by crocket** [fish-shell/fish-shell#5313] opened 2018-11-03 10:27 UTC
```
~> fish --version
fish, version 2.7.1
~> echo $TERM
screen
~> uname -a
Linux gentoo 4.14.65-gentoo #4 SMP Mon Sep 24 00:21:29 KST 2018 x86_64 AMD FX(tm)-8300 Eight-Core Processor AuthenticAMD GNU/Linux
```

* Terminal Environment // tmux on alacritty
* `sh -c 'env HOME=$(mktemp -d) fish'` doesn't fix this issue.

In `~/.config/fish/fishd.gentoo`, I found

```
SET fish_pager_color_prefix:white\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
```

I changed `white` to `red`, and `fish_pager_color_prefix` became conspicuous. Choosing a color theme on fish_config web page doesn't change `fish_pager_color_prefix`.

White is the same color as the background color according to solarized light color theme.

## fish_pager_color_prefix = White

![2018-11-03_sat_10 37 40](https://user-images.githubusercontent.com/748856/47951137-f3549180-df9f-11e8-97c6-4726be8d48c6.png)

## fish_pager_color_prefix = Red

![2018-11-03_sat_10 30 13](https://user-images.githubusercontent.com/748856/47951065-f438f380-df9e-11e8-87c3-692e03b59e55.png)

**Comment by faho** [comment] 2018-11-03 10:41
Duplicate of #3412

**Closed by faho** 2018-11-03 10:41 UTC

**Comment by faho** [comment] 2018-11-03 10:42
The issue here is that the themes don't define the pager colors, IIRC because they were added later.

I'd do that, but I'm the wrong person for the job as I'm partially color-blind and fully artistically untalented.
