### ISSUE TITLE
An error occured while redirecting file '/dev/fd/1'

### ISSUE THREAD

**Issue by JelteF** [fish-shell/fish-shell#1870] opened 2015-01-01 13:26 UTC
When using ssh to get into my server, and then su-ing into a different user with less rights, I get this error when using ls in a fish shell:

```
An error occured while redirecting file '/dev/fd/1'
open: Permission denied
```

It still lists the files and directories though, but it spawns an error before it.

**Comment by JelteF** [comment] 2015-01-02 08:51
I'm quite sure it is because of this line in ls:
https://github.com/fish-shell/fish-shell/blob/4aa38db56f6e138ea9bc15cb6f4ffc3502c3f435/share/functions/ls.fish#L9

**Comment by zanchey** [comment] 2015-01-20 06:09
Not sure what the right thing to do here is, as there will always be some things that don't work if you don't own the TTY.

One possibility is making the FD case `command test -t $argv` instead of using a redirection. @geoff-codes did some work on the `isatty` implementation and perhaps can comment.

**Comment by zanchey** [comment] 2015-01-20 06:51
I'm not actually convinced that `isatty` behaves right at all in a variety of circumstances. `isatty /dev/urandom` returns true?  I think the Right Thing is to replace the various tests with `command test -t 0 < $argv` or similar, although that will still produce errors with some redirections.

**Comment by geoff-codes** [comment] 2015-01-20 16:39
@zanchey I actually re-opened https://github.com/fish-shell/fish-shell/issues/1228#issuecomment-69908137 a few days ago in hopes to get some guidance here from Cory on this very thing. I'm not surprised at all that `isatty` is no longer working nicely in light of 7864d0d (and related), and if I had to take a wild guess, I'd say @JelteF 's issue looks like it could be related as well. @ridiculousfish ?

**Comment by geoff-codes** [comment] 2015-01-20 23:23
@JelteF I was able to reproduce your issue, and this patch should (I hope) fix your issue.
@zanchey `isatty /dev/urandom` should be fixed with this as well, but also see [d711433](https://github.com/fish-shell/fish-shell/commit/d7114332a987272dde63a8755696077c84b0dca0#commitcomment-9365817), #1909.

`command test -t 0 < $argv` isn't a terrible idea, except that we're depending on an external `test`, and when I was taking first hacking at this, support for `-t` seemed all over the map (hence the combination of `command test -c` and `tty 0>$argv>/dev/null`).

I'd like to be able to understand a bit more about how `local_builtin_stdin` works (particularly in re: `fd`s) before doing broader rewrite...

**Comment by zanchey** [comment] 2015-01-21 08:09
Do you mean that `/bin/test -t` isn't well supported across platforms? We're depending on an external command anyway, but using `-t` requires one less fork and it seems to work ok on all the platforms I have available to me.

I am beginning to wonder about the utility of the expanded syntax for `isatty` in any case. I can find no users of the new syntax in the fish source, the oh-my-fish source or a GitHub code search, although obviously as it hasn't been released it will not get wide exposure. It behaves differently from both `tty` and `test -t` and neither of those seem to have suffered terribly as a result.

**Comment by geoff-codes** [comment] 2015-01-21 10:34
> Do you mean that /bin/test -t isn't well supported across platforms?

Er... honestly, I can't recall precisely. There _are_ some difficulties with it, depending on platform — see some of the fun stuff [here](http://www.linuxjournal.com/content/determine-if-shell-input-coming-terminal-or-pipe) — and I know some implementations don't work with `fd`s > 2. But I think for the most part, I was in the "lets expand this into a useful utility" mindset, and I may have even ruled it out before I figured out that [builtin `test` can't do this](https://github.com/fish-shell/fish-shell/issues/1228).

> I am beginning to wonder about the utility of the expanded syntax for isatty in any case.

_I_ am beginning to wonder about the utility of an `isatty` function _at all_.

It appears to have been written solely for the purpose of adding decorators to `ls`, but only when printed to stdout, and only when using GNU ls. There appears to be all of _one_ other use of it, in oh-my-fish, and I don't really understand [why](https://github.com/bpinto/oh-my-fish/blob/master/plugins/dpaste/dpaste.fish#L90).

I'm not really sure why I ever even started hacking on it in the first place; it think I probably came across it was perplexed at why it allowed `stdin`, `stdout`, and `stderr` as arguments, but nothing else that could be considered a tty in `/dev`. So I started playing with it, and, here we are. But I wholeheartedly agree with you, its pretty useless. There's really no reason not to use `[command]` `test -t`, which is in fact usually (always?) just an implementation of `isatty(3)`.

It's also a particularly non-fishy fish command (which I suppose makes it quite fishy, doesn't it?).

That is, how many bundled fish functions simply emulate libc functions? If fish were in that business, `isatty(3)` is certainly **not** [one of the first I'd implement](https://gist.github.com/geoff-codes/1f23957288d371b75a2e).

I kinda think the use in `ls.fish` should just be replaced with a one-off `command test -t 1`, and get rid of `isatty` . (Or better yet, just drop the damn decorators entirely. I mean, why are they enabled by default, but *only* with GNU ls? Why do you need them, when we have all these pretty colors? Personally, I can't stand them; but I'm usually on a Mac or BSD, so I'm basically immune already.)

**Comment by zanchey** [comment] 2015-01-30 08:52
I don't think we can drop the whole thing until next-major at least - it is [definitely in use](https://github.com/search?q=isatty+language%3Afish&type=Code). I'm going to condense it down to using `command test -t` and remove the expanded syntax. If there's a clear use case we can always add it back in.

**Comment by geoff-codes** [comment] 2015-01-30 08:59
Fine by me. Keep in mind that (in the list you linked) there's at least one example that uses the `isatty stdout` syntax, which **is** beyond what `isatty(3)` does. But its probably best to put that bit back in as well, if the aim is to not break things.

**Comment by zanchey** [comment] 2015-02-01 10:18
OK, rolled back to the old behaviour and used `test -t` in preference to `tty`. Both require a fork and `test -t` seems a bit saner.

**Closed** 2015-02-01 10:18 UTC
