### ISSUE TITLE
cd completion acts funny when spaces are present in the path

### ISSUE THREAD

**Issue by tgkokk** [fish-shell/fish-shell#2300] opened 2015-08-13 19:49 UTC
```shell
$ mkdir a\ b\ c
$ cd a\ [TAB]
```
Now, i would expect to autocomplete `a\ b\ c/`, but instead it offers completions for every directory in the CWD. I guess that it treats the space as an argument separator.

Other commands (e.g. `mkdir`) work fine.

**Comment by faho** [comment] 2015-08-13 19:54
Same thing as #2299 - does  #2289 change anything?

**Comment by tgkokk** [comment] 2015-08-13 19:55
Yeah, it autocompletes `a\ a\ b\ c/`. Still not perfect but better.

**Comment by faho** [comment] 2015-08-14 09:59
>Other commands (e.g. mkdir) work fine.

There is no mkdir completion - it falls back to the generic file completion.

There's probably an issue with the completion comparison logic - it seems some of it happens before escaping.

**Comment by faho** [comment] 2016-03-07 12:06
I actually can't reproduce this anymore. Closing.

**Closed by faho** 2016-03-07 12:06 UTC
Labels: bug
