### ISSUE TITLE
vi-mode: a jumps to the end of the line not enter append mode.

### ISSUE THREAD

**Issue by newhook** [fish-shell/fish-shell#2270] opened 2015-08-04 12:16 UTC
If I press 'a' in vi I enter append mode at the current location.

With fish pressing 'a' completes the current line and starts to append to the end of the line. That is incorrect.

**Comment by faho** [comment] 2015-08-04 12:34
```
bind a
```

>bind -m insert a forward-char force-repaint

is the vi-mode default.

Do you have any custom keybindings? Which fish version are you running?

**Comment by newhook** [comment] 2015-08-04 12:35
No custom bindings.

fish -v
fish, version 2.2.0

**Comment by faho** [comment] 2015-08-04 12:38
What does `bind a` say?

**Comment by newhook** [comment] 2015-08-04 12:39
bind a
bind -m insert a forward-char force-repaint

**Comment by newhook** [comment] 2015-08-04 12:41
I'm not sure what is going on here. I cannot reproduce what I saw earlier :(

**Comment by faho** [comment] 2015-08-04 13:01
Please reopen if you can reproduce.

**Comment by newhook** [comment] 2015-08-10 16:08
Not sure how to reopen but I reproduced. Get a command line from history:

$ hello_world how_are_you
Move customer to the middle
$ hello_world how_are_you
                       ^^^^^ - here
Press D to delete to teh end of the line
$ hello_world <how_are_you>
   teh <...> is greyed out.
Now press a to start adding stuff.
It jumps to the end of the line restoring the history.

**Comment by faho** [comment] 2015-08-10 16:26
> Move customer to the middle

I'm assuming "move the cursor to the middle", i.e. between "world" and "how", i.e.

    hello_word how_are_you
              ^here

If so, I still can't reproduce.

>Not sure how to reopen

It appears github only lets collaborators do that - I'm doing it now.

**Comment by newhook** [comment] 2015-08-10 16:40
I recorded a gif of what happens for me.

When it jumps to the end of hte line I'm pressing a. When I added the blah text I pressed i.

http://imgur.com/kEqQ8g3

**Comment by pickfire** [comment] 2015-08-20 12:36
I think I am able to reproduce that too.

![2015-08-20-203418_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9383347/eee2864a-477a-11e5-8d53-3f0e6adeb332.png)

1. I type something in **insert mode**.
2. I press escape to **normal mode**.
3. I press `a` and it *auto completes*.

**Comment by danielmatz** [comment] 2015-08-20 15:17
Most commands that move the cursor forward into the suggested text will accept the entire suggestion.  You should see that `l`, `A`, `$`, etc., all accept the entire suggestion as well.

However, it seems that `w` only accepts the next word of the suggestion.

Maybe more of the vi editing commands should accept parts of suggestions?

Though I think that would still bother you, @newhook, because it would mean that `a` would accept the first character of the suggestion and then put you in insert mode after it.  So in any case, I think you should just use `i` here.

**Comment by krader1961** [comment] 2017-03-23 04:28
This seems to have been fixed in the interim since the issue was opened.

**Closed by krader1961** 2017-03-23 04:28 UTC
Labels: bug, vi-mode
