### ISSUE TITLE
`path dirname //` prints extraneous slash

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9331] opened 2022-11-06 22:44 UTC
These should all have the same output, but there is some idiosyncrasy for `//`:

```shell
> path dirname /
/
> path dirname //
//
> path dirname ///
/
> path dirname ////
/
```

**Comment by ridiculousfish** [comment] 2022-11-07 01:14
This is by design - see [OpenGroup dirname recipe](https://pubs.opengroup.org/onlinepubs/007904875/utilities/dirname.html) step 1. It doesn't make a whole lot of sense to me either.

**Comment by floam** [comment] 2022-11-07 01:26
I wonder why they did that. My `command dirname //` does what I expect - I guess the "implementation-defined" choice they made at step 6 is the one I like more.

**Comment by floam** [comment] 2022-11-07 01:30
I guess it's for UNIX systems like Cygwin. POSIX lets [the implementation do as they wish](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap04.html#tag_04_11) with these UNC-like //paths/.
 
> A pathname that begins with two successive slashes may be interpreted in an implementation-defined manner, although more than two leading slashes shall be treated as a single slash.

**Comment by dahuigeniu** [comment] 2023-02-20 23:19
good

**Comment by faho** [comment] 2024-05-06 10:54
I'm going to say that we appear not to have the appetite to change this.

If someone did carry it forward, that would be fine, but as it stands we're doing a dirname thing and if it's never changed that's fine, too.

So I'm closing this as not-planned.

**Closed by faho** 2024-05-06 10:54 UTC
Labels: posix-me-harder
