### ISSUE TITLE
exec the last command in fish -c "..."

### ISSUE THREAD

**Issue by farnoy** [fish-shell/fish-shell#8839] opened 2022-03-27 15:48 UTC
```sh
$ fish --version
fish, version 3.3.1
```

Other shells have this feature where the very last command given to `-c` is automatically executed in place, terminating the shell process early.

For example:

```sh
$ sh -c "sleep 10 && sleep 50" &
$ ps o pgid,cmd | grep sleep
  32207 sh -c sleep 10 && sleep 50
  32207 sleep 10
  32232 grep --color=auto sleep
# wait for the first sleep to end
$ ps o pgid,cmd | grep sleep
  32207 sleep 50 # the shell exited early
  32241 grep --color=auto sleep
```

The same happens with bash & zsh, but not with fish.

I have no idea how they do it, given that signal routing works as expected if I try to terminate it during `sleep 50`. It would be cool to have in fish though.

**Comment by faho** [comment] 2022-03-27 15:54
Duplicate of #6902

**Comment by faho** [comment] 2022-03-27 15:55
In short: This is an optimization that's simply not worth the complication, so we're not going to do it.

Sorry!

**Closed by faho** 2022-03-27 15:54 UTC
