### ISSUE TITLE
Unicode/emoji causing strange behavior

### ISSUE THREAD

**Issue by clozach** [fish-shell/fish-shell#5272] opened 2018-10-22 22:23 UTC
fish, version 2.7.1
macOS 10.13.6 (17G65)
Terminal 2.8.2 (404)

Attempting to use emoji results in crazy behavior. It's easiest to just show it:

 I  ~/fishbug    sh -c 'env HOME=$(mktemp -d) fish'                                           1.3m  Mon Oct 22 15:20:17 2018
                
Welcome to fish, the friendly interactive shell
clozach@clozach-06503 /U/c/fishbug> fish --version
fish, version 2.7.1
clozach@clozach-06503 /U/c/fishbug> uname -a
Darwin clozach-06503.oak.server.gracenote.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
clozach@clozach-06503 /U/c/fishbug> echo $TERM
xterm-256color
clozach@clozach-06503 /U/c/fishbug> ls
noproblem
clozach@clozach-06503 /U/c/fishbug> rm -rf noproblem/
clozach@clozach-06503 /U/c/fishbug> ls
clozach@clozach-06503 /U/c/fishbug> mkdir noproblem
clozach@clozach-06503 /U/c/fishbug> mkdir with🙂emoji
clozach@clozach-06503 /U/c/fishbug> mkkddmkdir   wwwiitwith emoji
clozach@clozach-06503 /U/c/fishbug> ls
emoji         noproblem     with          with🙂emoji
clozach@clozach-06503 /U/c/fishbug> mkdir withemoji
clozach@clozach-06503 /U/c/fishbug> mkdir wwith🙈emoji
clozach@clozach-06503 /U/c/fishbug> mkdir withaAAaaa!

**Comment by faho** [comment] 2018-10-23 06:51
Duplicate of #5059, #4539, #4609 and numerous other issues.

The summary is that the terminal and fish need to agree on how wide characters are or our cursor movement for doing suggestions goes to wrong places, but this sometimes goes wrong because unicode is hard. Fish 3.0 will have numerous improvements.

**Closed by faho** 2018-10-23 06:51 UTC
