### ISSUE TITLE
Fish invoked from sudo stops itself

### ISSUE THREAD

**Issue by Nikratio** [fish-shell/fish-shell#7388] opened 2020-10-09 10:13 UTC
When I'm running sudo, and root is using the fish shell, the new shell immediately stops:

```
nikratio@vostro ~> fish --version
fish, version 3.0.2

nikratio@vostro ~> sudo cat /root/.bash_profile
echo exec /usr/bin/fish -i
exec /usr/bin/fish -i

nikratio@vostro ~> sudo -i
exec /usr/bin/fish -i
Job 1, 'sudo -i' has stopped
```

Removing the `exec` from `.bash_profile` and executing it manually works just fine:

```
nikratio@vostro ~> sudo cat /root/.bash_profile
#echo  exec /usr/bin/fish -i
#exec /usr/bin/fish -i

nikratio@vostro ~> sudo -i

[0] root@vostro:~
# exec /usr/bin/fish -i
Welcome to fish, the friendly interactive shell
root@vostro ~# 
```

Am I doing something wrong?

**Comment by faho** [comment] 2020-10-09 10:29
Please upgrade to 3.1.2 there were a few fixes in that area. We offer numerous PPAs at fishshell.com.

**Comment by Nikratio** [comment] 2020-10-09 17:13
Same problem, I'm afraid:

```
nikratio@vostro ~> sudo -i
Job 1, 'sudo -i' has stopped
nikratio@vostro ~> fish --version
fish, version 3.1.2
```

**Comment by faho** [comment] 2020-10-09 17:21
Okay, do you have anything in config.fish? Can you try moving that out of the way?

I can't reproduce this on 3.1.2 or 3.0.2.

**Comment by Nikratio** [comment] 2020-10-09 19:43
Nope, config.fish is empty.

**Comment by Nikratio** [comment] 2020-10-09 19:43
(for both root and the user calling sudo)

**Comment by faho** [comment] 2020-10-09 19:56
What operating system is this on?

Do you have anything else in bashrc or profile?

**Comment by faho** [comment] 2020-10-09 20:01
Compare #5147, which was supposedly fixed in 3.0.0.

I don't suppose it's possible the `fish` in your $PATH isn't updated, so `sudo -i` ends up calling an older fish?

Or do you have any `sudo` configuration?

**Comment by Nikratio** [comment] 2020-10-09 20:06
This is on Debian stable.

There are the standard bash init files in /etc that come with Debian, but /root/.bashrc contains nothing else.

Here's the sudo configuration:

```
# cat /etc/sudoers
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Don't modify user's umask
Defaults        umask=0777

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

#includedir /etc/sudoers.d
```

The fish version is the right one:

```
nikratio@vostro ~/i/pyfuse3 (master)> cat /root/.bashrc
#
# ~/.bashrc (executed by bash(1))
# Settings for interactive subshells
#

# Use fish shell instead
if [[ $- = *i* && -z $WHICH_FISH ]] && WHICH_FISH=$(type -p fish); then
  # Safeguard to only activate fish for interactive shells and only if fish
  # shell is present and executable. Verify that this is a new session by
  # checking if $WHICH_FISH is set. If it is not set, we export WHICH_FISH
  # and start fish.
  #
  # If this is not a new session, the user probably typed 'bash' into their
  # console and wants bash, so we skip this.
  #
  # Note that we do not set $SHELL, and neither does fish, because doing so
  # tends to interfere with programs that expect $SHELL to point to a
  # POSIX-compatible shell, which fish is not.
  export WHICH_FISH
  echo "Running exec \"$WHICH_FISH\" -i"
  exec "$WHICH_FISH" -i
fi

nikratio@vostro ~/i/pyfuse3 (master)> sudo -i
[sudo] password for nikratio: 
Running exec "/usr/bin/fish" -i
Job 1, 'sudo -i' has stopped
nikratio@vostro ~/i/pyfuse3 (master)> /usr/bin/fish --version
fish, version 3.1.2
```

**Comment by Nikratio** [comment] 2020-10-09 20:07
It looks like it actually stops twice before it becomes usable:

```
nikratio@vostro ~/i/pyfuse3 (master)> sudo -i
Running exec "/usr/bin/fish" -i
Job 1, 'sudo -i' has stopped
nikratio@vostro ~/i/pyfuse3 (master)> fg
Send job 1, “sudo -i” to foreground
Job 1, 'sudo -i' has stopped
nikratio@vostro ~/i/pyfuse3 (master)> fg
Send job 1, “sudo -i” to foreground
Welcome to fish, the friendly interactive shell

```

**Comment by zanchey** [comment] 2020-10-11 14:24
I can reproduce this on 3.1.2 and on f73ee3011 with the `.bashrc` given above. I've managed to get a (massive) strace of the whole thing, but I don't really have time to dig into it. I suspect funkiness with the PGID handling: when stopped, the output of `ps -Ao user,pid,pgid,command` includes:

```
root     30123 30123 sudo -i
root     30124 30123 /usr/bin/fish -i
```

but then after running `fg` twice, looks more sensible with:

```
root     30123 30123 sudo -i
root     30124 30124 /usr/bin/fish -i
```

**Comment by ridiculousfish** [comment] 2020-10-12 01:31
I have not been able to reproduce on Arch; I will try on a Debian system next.

**Comment by faho** [comment] 2020-10-12 18:09
Okay, I can reproduce on Debian (also not on Arch) with fish 3.1.2, I can't with current-ish master (ca730cf71).

Lemme bisect.

**Comment by faho** [comment] 2020-10-12 19:17
Welp, this is fish's doing.

In https://github.com/fish-shell/fish-shell/blob/13459d4d3a87dc8fe7b6154b52e6dd35e29ebc29/src/reader.cpp#L2053-L2067, fish sends a SIGTTIN to itself, in the hopes of somehow (I don't understand the particular mechanism, tbh) becoming pgroup leader.

Only it actually ends up stopping itself.

I don't understand what this is supposed to achieve given that we reset the signal handlers to default, and IIRC for SIGTTIN that's stopping?

**Comment by krobelus** [comment] 2020-10-12 20:03
I believe fish doesn't stop on `SIGTTIN` because in `set_interactive_handlers` we set a handler for that signal.
No idea why it stops in this case, it doesn't reproduce on Ubuntu 18.

**Comment by faho** [comment] 2020-10-12 20:09
@krobelus Doesn't `signal_reset_handlers()` reset the signal handlers to default, or am I reading that wrong?

**Comment by ridiculousfish** [comment] 2020-10-18 19:37
Nice work. For some context see [this question](https://stackoverflow.com/questions/13718394/what-should-interactive-shells-do-in-orphaned-process-groups).

**Comment by ridiculousfish** [comment] 2020-10-18 20:46
I was able to repro on Debian too. Some background:

So the idea here is, what happens if a shell is started interactively but does not have control of the terminal? For example `bash -i &`? As soon as it tries to do anything it will get SIGTTIN, but interactive shells ignore SIGTTIN. So the operation will fail and it will try again, leading to a 100% CPU loop.

Shells try to detect this case, by comparing their pgroup (`getpgrp`) to the tty owner (`tcgetpgrp`) If interactive and does not have tty control, they temporarily remove their SIGTTIN handler and send SIGTTIN to themselves. [Here's where bash does just that](https://github.com/bminor/bash/blob/3ba697465bc74fab513a26dea700cc82e9f4724e/jobs.c#L4233).

What ends up happening here is very strange: fish is launched in sudo's pgroup, but the tty is assigned to fish's pid (NOT its pgroup). It's extremely weird to assign a tty to a non-pgroup leader. This seems like a sudo bug.

I'll have to see what bash does differently here, but both bash and fish have other code to fix up its pgroup, so bash is probably just working around this.

**Comment by ridiculousfish** [comment] 2020-10-18 21:22
Ha, bash doesn't do anything different here. If you launch `bash` instead of `fish` then bash gets stopped too.

If fish is launched such that its pid (but not the pgrp) owns the tty, then it should probably just put itself into its own pgroup. I can't imagine what that would break. But yeah, this seems like a sudo bug.

**Comment by ridiculousfish** [comment] 2020-10-18 21:45
bbbbe00!

**Comment by ridiculousfish** [comment] 2020-10-18 21:45
"bbbbe00" sweet

**Closed** 2020-10-18 21:44 UTC
Labels: bug
