### ISSUE TITLE
fish incorrectly completes after escaped space character

### ISSUE THREAD

**Issue by tclementdev** [fish-shell/fish-shell#2447] opened 2015-09-30 17:52 UTC
Enter the following:

    sudo /Applications/Font\<space here>

Then hit tab, fish offers completions for the currently directory:

    sudo /Applications/Font\ Book.app/
    $ns/Font\ Applications/  (Command to run)  $ns/Font\ Library/   (Command to run)  $ns/Font\ Public/  (Command to run)
    $ns/Font\ Desktop/       (Command to run)  $ns/Font\ Movies/    (Command to run)  $ns/Font\ Sites/   (Command to run)
    $ns/Font\ Documents/     (Command to run)  $ns/Font\ Music/     (Command to run)  
    $ns/Font\ Downloads/     (Command to run)  $ns/Font\ Pictures/  (Command to run)

Instead of:

    sudo /Applications/Font\ Book.app/

**Comment by faho** [comment] 2015-09-30 18:12
Works for me - what fish version are you using?

**Comment by tclementdev** [comment] 2015-09-30 18:14
The 2.2.0 release. Maybe it has been fixed since then?

**Comment by faho** [comment] 2015-09-30 18:14
Sooo... You only get this when you press tab right after the escaped (or quoted) space, right?

I.e. `sudo /Applications/Font\ <TAB>` causes issues, `sudo /Applications/Font<TAB>` doesn't?

**Comment by faho** [comment] 2015-09-30 18:14
Oh sorry, I deleted that comment because I _was_ able to reproduce something.

**Comment by faho** [comment] 2015-09-30 18:15
Compare also #2274.

**Comment by tclementdev** [comment] 2015-09-30 18:16
Yes, `sudo /Applications/Font\ <TAB>` causes the issue, `sudo /Applications/Font<TAB>` doesn't.

**Comment by faho** [comment] 2015-09-30 20:37
I've investigated this a bit and found there's two issues at play here:

- `complete --do-complete` expects the argument to be double-escaped (i.e. passed as one still escaped argument) - this means if you run `complete -C "/Applications/Font "` you'll get a completion as if the cursor was after a space - i.e. by default a file

Now, this is undoubtedly useful in many cases, and it's quite clean - it accepts a commandline, so you can just hand it a commandline (or part of one) and it'll do the right thing. Well, except it won't since `commandline` breaks quoting (#2210) and also escaping - if I have `echo "echo banana" > a\ b` in my commandline, it outputs `echo echo banana > a b`. But if commandline were bugfree, it'd work.

This part is worked around easy enough - just use `string escape -n`.

However, there's a second part here, and it's one I've mentioned in a previous issue (though I can't find the bugger):

- Even when we output the correct string , the comparison logic is off so it won't be properly inserted

This is probably better explained via example:

If I make it output the normal string (i.e. `/Applications/Font Book.app`), what ends up in the commandline is `/Applications/Font\ /Applications/Font\ Book.app/`.
If I make the completion output the escaped string (i.e. `/Applications/Font\ Book.app/`), what ends up in the commandline is `/Applications/Font\ /tmp/Font\\\ Book.app/`.

If one manages to trigger the completion menu (because there's more than one choice), one can pick both and they correctly replace the commandline.

As I've said before - completion before the space works.

@ridiculousfish: Mind taking a look? I think I've narrowed it down a bit.

**Comment by faho** [comment] 2016-01-20 21:29
Moved @ridiculousfish's self-assignment to this one from #2687.

**Comment by krader1961** [comment] 2016-03-22 03:38
We've only got a handful of issues blocking the 2.3.0 release milestone. This issue isn't one that should block a new minor release so I'm retargeting this to next-2.x so we can focus our efforts on fixing the issues that should be fixed for the 2.3.0 release.

**Comment by lesderid** [comment] 2016-05-19 16:52
This is the only bug I experience with fish, but it happens on a daily basis. It doesn't make fish unusable for general use, but it's not very user friendly.

This should probably get the 'bug' tag.

**Comment by ridiculousfish** [comment] 2016-07-11 21:04
Fixed as f08ac969e9375d9c80c78e489c1670954308fb61. Thanks for filing this.

**Closed** 2016-07-11 21:03 UTC
Labels: bug
