### ISSUE TITLE
`--no-config` is unmentioned in fish(1) `doc_src/cmds/fish.rst`

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#8599] opened 2021-12-31 21:40 UTC
```
fish, version 3.3.1
3.3.1
```

`--no-config` was introduced by #7921, but remains unmentioned in the manpage.

**Comment by faho** [comment] 2021-12-31 21:58
Duplicate of #8176

**Closed by faho** 2021-12-31 21:58 UTC
