### ISSUE TITLE
Abbreviations and colors

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#4674] opened 2018-01-19 14:59 UTC
I have an abbreviations sl which lead to ls

But when i type \sl fish color it like it was a valid command

**Comment by zanchey** [comment] 2018-01-20 06:14
Yes, and `\sl` is not expanded as an abbreviation otherwise would be.

**Comment by zanchey** [comment] 2018-01-20 14:50
I think this is a duplicate of #784.

**Comment by faho** [comment] 2023-09-30 14:56
Duplicate of #784

**Closed by faho** 2023-09-30 14:56 UTC
Labels: bug
