### ISSUE TITLE
`my_function | head -n 10` never terminates early

### ISSUE THREAD

**Issue by ddrcoder** [fish-shell/fish-shell#4171] opened 2017-06-30 20:35 UTC
```
> function test_pipelines; hexdump -C < /dev/urandom | head -n1000000 | tee /tmp/output; end
> test_pipelines | head -n10 > /tmp/output2 # this takes a long time
...
> wc -lc /tmp/output /tmp/output2
 1000000 79000000 /tmp/output
      10      790 /tmp/output2
```

The entire function executes, never stopping early. This isn't how pipelines are supposed to work, right? `/tmp/output` will likely contain more than 10 lines, but it shouldn't be allowed to continue to 1,000,000 lines.

Bash, for comparison, yields this result:

```
$ function test_pipelines() { hexdump -C < /dev/urandom | head -n1000000 | tee /tmp/output; }
$ test_pipelines | head -n10 > /tmp/output2
...
$ wc -lc /tmp/output /tmp/output2
  518 40960 /tmp/output
   10   790 /tmp/output2
```

Here bash properly closes the pipe, stopping `tee` early. This varies depending on how fast these race, but I expect that. I don't expect the function to completely produce all of its output without stopping.

**Comment by krader1961** [comment] 2017-06-30 21:04
Duplicate of #1396. This behavior dates to the first fish implementation. It is going to be hard to change which is why this annoyance is still present. We'd love to see someone who is sufficiently motivated take a stab at changing the implementation.

**Closed by krader1961** 2017-06-30 21:04 UTC
