### ISSUE TITLE
[feature request] Better completion in brace expressions

### ISSUE THREAD

**Issue by ewtoombs** [fish-shell/fish-shell#7890] opened 2021-04-01 18:16 UTC
version: archlinux fish-git 2:3.2.1.r90.ge56d8a8e5-1
fish --version: fish, version 3.2.1-90-ge56d8a8e5

If I start a brace expression like this:
```
cp -r /tmp/{china█
```
then hit tab, I get file completions:
```
cp /tmp/{China_administrative.svg █
```
but some part of the completion logic is still unaware that I'm inside a brace expression. It writes a space instead of a comma, and if I write a comma then attempt another tab completion, it will fail:
```
cp /tmp/{China_administrative.svg,time█<tab>
```

My request is to make fish completion smart enough to handle these cases. As it stands, in order to do multiple completions in a certain directory, I have to set it as the current directory first, which is awkward at times. For an example of better brace-aware completion, see zsh.

**Comment by faho** [comment] 2021-04-01 18:21
Duplicate of #1711

**Closed by faho** 2021-04-01 18:21 UTC
