### ISSUE TITLE
UTF-8 strings on FreeBSD 11, 12 are really interesting 

### ISSUE THREAD

**Issue by kcbark** [fish-shell/fish-shell#3302] opened 2016-08-15 17:06 UTC
fish --version
fish, version 2.3.1-461-gf3e93f0

OS: FreeBSD 12.0-CURRENT
Terminal: terminator, xterm, urxvt

## Reproduction steps
1. Launch fish
# sh -c 'env HOME=$(mktemp -d) fish'

## Expected results
Fish should not print out error message and keybindings should work.

## Actual results
\# sh -c 'env HOME=$(mktemp -d) fish'

There is no fish_key_bindings function called: 'fish_default_key_bindings'
Reverting to default bindings
There is no fish_key_bindings function called: 'fish_default_key_bindings'
Reverting to default bindings
There is no fish_key_bindings function called: 'fish_default_key_bindings'
.. repeated for about 250 times [Edit @faho: Removed a bunch more repetitions]
The function call stack limit has been exceeded. Do you have an accidental infinite loop?
fish: __fish_reload_key_bindings VARIABLE SET fish_key_bindings
      ^
in event handler: handler for variable “fish_key_bindings”

@ ~/usr/home/kc> 

After this keybindings do not work. Adding keybindings manually works.

**Comment by faho** [comment] 2016-08-15 17:46
I cannot reproduce this myself.

This is from https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_config_interactive.fish#L154-L197. That is executed, probably without $fish_key_bindings, so that is set to default. We then check if the function named by that exists - which means we check $fish_function_path for it. It seems that has not yet been initialized or the directories in it cannot be accessed, which results in fish not finding `fish_default_key_bindings.fish` - or finding one without a valid definition for the `fish_default_key_bindings` function.

Can you show the output of `env HOME=(mktemp -d) fish -ic 'echo $fish_function_path'`? Do any of the paths mentioned include a valid `fish_default_key_bindings.fish`?

**Comment by faho** [comment] 2016-08-15 17:48
>Adding keybindings manually works.

Also, what do you mean by this? Adding a `set fish_key_bindings fish_default_key_bindings` to the new config.fish works? That would be highly surprising as the other setup isn't called until after a prompt event happens.

**Comment by kcbark** [comment] 2016-08-15 18:18
@ ~/usr/home/kc> env HOME=(mktemp -d) fish -ic 'echo $fish_function_path'
/tmp/kc/tmp.UklCafxP/.config/fish/functions /usr/local/etc/fish/functions /usr/local/share/fish/vendor_functions.d /usr/local/share/fish/functions

> Also, what do you mean by this? Adding a set fish_key_bindings fish_default_key_bindings to the new config.fish works? That would be highly surprising as the other setup isn't called until after a prompt event happens.

I meant that adding keybindings in the shell works, like so: 
@ ~/tmp/kc/tmp.npYm7bBZ> bind \x7F backward-delete-char

**Comment by faho** [comment] 2016-08-15 18:24
>/tmp/kc/tmp.UklCafxP/.config/fish/functions /usr/local/etc/fish/functions /usr/local/share/fish/vendor_functions.d /usr/local/share/fish/functions

That looks as expected - the ~/.config part is in the new home, the rest in /usr/local. Do any of those contain a valid fish_default_key_bindings.fish?

> I meant that adding keybindings in the shell works, like so:
@ ~/tmp/kc/tmp.npYm7bBZ> bind \x7F backward-delete-char

Ah, we're falling back on the simple hard-coded bindings? So you can do simple stuff like enter a command and execute it?

**Comment by kcbark** [comment] 2016-08-15 18:57
> That looks as expected - the ~/.config part is in the new home, the rest in /usr/local. Do any of those contain a valid fish_default_key_bindings.fish?

Yup. 
$ find /usr/local -name fish_default_key_bindings.fish
/usr/local/share/fish/functions/fish_default_key_bindings.fish

> Ah, we're falling back on the simple hard-coded bindings? So you can do simple stuff like enter a command and execute it?

Yes, entering a command and executing works. But no other key bindings it seems.

**Comment by krader1961** [comment] 2016-08-15 20:16
I can reproduce by deliberately removing *fish_default_key_bindings.fish* or changing the name of the function in that script.

Fish is handling this reasonably well (you  still get a usable interactive shell) but I suppose we could do better in terms of structuring the code to give up before hitting the function stack limit. This should be easier to do after I've implemented issue #3295.

**Comment by krader1961** [comment] 2016-08-15 20:18
@kcbark, Can you check that your */usr/local/share/fish/functions/fish_default_key_bindings.fish* script is readable and contains a valid function with this signature:

```
function fish_default_key_bindings -d "Default (Emacs-like) key bindings for fish"
...
end
```

**Comment by faho** [comment] 2016-08-15 20:43
@kcbark: 790968120d280443be17737c73ff13928a633a37 should at least quiet down the failure. There's really not much we can do if fish_default_key_bindings.fish is bogus, like we suspect here. Like @krader1961 said, we already handle this reasonably - there's a working, if sparse, set of keybindings that gives you a working session.

If this is caused by something else, we'll have to figure out what that is.

**Comment by kcbark** [comment] 2016-08-15 20:56
> @kcbark, Can you check that your /usr/local/share/fish/functions/fish_default_key_bindings.fish script is readable and contains a valid function with this signature:

@krader1961 - Yes, /usr/local/share/fish/functions/fish_default_key_bindings.fish is readable and is what I can see not bogus. Line 2 in this file contains:

function fish_default_key_bindings -d "Default (Emacs-like) key bindings for fish"

**Comment by kcbark** [comment] 2016-08-15 21:03
Thanks @krader1961 and @faho . I updated to the latest revision, recompiled and installed. I still get the same errors and no key bindings. Return works though. Hm.

**Comment by krader1961** [comment] 2016-08-15 21:03
@faho, I've confirmed your change avoids the stack exceeded error.

@kcbark, I don't know what to tell you. There is something wrong with your environment as the only way you can get the failure you reported is if the `fish_default_key_bindings` function cannot be auto-loaded. From the broken shell prompt run `functions fish_default_key_bindings`. I expect it to output nothing and set `$status` to one in your situation. Whereas it will print the function definition if it was auto-loaded.

**Comment by kcbark** [comment] 2016-08-15 21:07
I ran "functions fish_default_key_bindings" and it just gave me the output of the file fish_default_key_bindings.fish it seems.

**Comment by faho** [comment] 2016-08-15 21:13
@kcbark: How have you installed fish? Did you do anything to ./configure?

This only happens if you have fish in a terminal and then run through that `env` line, right? Do you have any configuration in the first layer fish - the "host fish", if you will?

What is your `locale`?

**Comment by krader1961** [comment] 2016-08-15 21:14
> I ran "functions fish_default_key_bindings" and it just gave me the output of the file fish_default_key_bindings.fish it seems.

Okay, there is indeed something very odd about your environment but it isn't what we suspected. Please run the following and attach the */tmp/fish_bindings.txt* file to this issue:

```
script /tmp/fish_bindings.txt
sh -c 'env HOME=$(mktemp -d) fish -d3'
exit
exit
```

**Comment by kcbark** [comment] 2016-08-15 21:31
@faho I cloned the git repo, ran autoconf, then ./configure and then gmake and gmake install. I get the same error running just 'fish' or 'sh -c 'env HOME=$(mktemp -d) fish''. I normally run zsh and then ran fish inside zsh. I  creating a new user with a fresh $HOME and I get the same error. My locale for this user:

$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME=sv_SE.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

@krader1961: attached file.
[fish_bindings.txt](https://github.com/fish-shell/fish-shell/files/419008/fish_bindings.txt)

**Comment by krader1961** [comment] 2016-08-15 23:15
It's an ordering problem. On both of my systems and @kcbark's `function __fish_reload_key_bindings` is invoked when `fish_key_bindings` is first assigned to. On all three systems this test at the top of that function fails:

```
        if test "$fish_key_bindings" = "$__fish_active_key_bindings" -a -n "$fish_key_bindings"
            return
        end
```

At this point the behavior differs. On my system the debug output shows that the sourcing of the auto-loaded function completes:

```
<3> fish: Set status of source /usr/local/share/fish/functions/fish_default_key_bindings.fish to 0 using short circuit
```

So the function is defined and this test fails so we don't error out and instead continue with the rest of `function __fish_reload_key_bindings`:

```
if not functions -q "$fish_key_bindings"
   ...
end
```

On @kcbark's system the auto-load of `fish_default_key_bindings` has not completed so that test is true and we error out:

```
<3> fish: Set status of not functions -q "$fish_key_bindings" to 1 using short circuit
<3> fish: Job is constructed
<2> fish: Fork #8, pid 82760: internal builtin for 'echo'
<3> fish: Job is constructed
There is no fish_key_bindings function called: 'fish_default_key_bindings'
```

This is where it gets weird. The next test fails:

```
<3> fish: Set status of set -q __fish_active_key_bindings to 1 using short circuit
```

Fish then reports that the auto-load has completed successfully but tries to source the script again:

```
<3> fish: Skipping fork: no output for internal builtin 'source'
<3> fish: Set status of source /usr/local/share/fish/functions/fish_default_key_bindings.fish to 0 using short circuit
<3> fish: Job is constructed
<3> fish: proc::read_try('source /usr/local/share/fish/functions/fish_default_key_bindings.fish')
```

Also, in my trace I see that it's actually executing the body of `fish_default_key_bindings` including sourcing and running `__fish_shared_key_bindings` as well as the `bind` commands. I don't see that in @kcbark's trace. I'm starting to suspect something is causing that function to fail. Unfortunately the trace (both mine and theirs) is ambiguous.

**Comment by krader1961** [comment] 2016-08-15 23:30
@kcbark, Please upload a copy of the output of `functions default_key_bindings` from your broken shell and `functions __fish_shared_key_bindings`. Also, this shouldn't make any difference but please try with `LC_ALL=en_US.UTF-8` because the `LC_TIME` value could be causing problems with the locale subsystem.

**Comment by krader1961** [comment] 2016-08-15 23:31
Also, what happens if you run `default_key_bindings` by hand at the broken shell prompt?

**Comment by kcbark** [comment] 2016-08-16 15:52
@krader1961:
```

@ ~/usr/home/test> locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=en_US.UTF-8
@ ~/usr/home/test> default_key_bindings
fish: Unknown command 'default_key_bindings'
@ ~/usr/home/test> 
```

**Comment by floam** [comment] 2016-08-16 15:59
> `@ ~/usr/home/test> default_key_bindings`

Try `fish_default_key_bindings`

**Comment by kcbark** [comment] 2016-08-16 16:02
@floam:
```
@ ~/usr/home/test> fish_default_key_bindings
There is no fish_key_bindings function called: 'fish_default_key_bindings'
Reverting to default bindings
.. repeated X times.
The function call stack limit has been exceeded. Do you have an accidental infinite loop?
fish: __fish_reload_key_bindings VARIABLE SET fish_key_bindings
      ^
in event handler: handler for variable “fish_key_bindings”
```

**Comment by floam** [comment] 2016-08-16 16:03
And, @krader1961 was hoping you could share the contents of the function. Here's an easy way: 

`gem install gist; and funced -e gist fish_default_key_bindings` and paste the URL it creates.

**Comment by kcbark** [comment] 2016-08-16 16:50
@foam and @krader1961  here you go: https://gist.github.com/1e233c54f19a1cbd2da4ac7d410b72b5

That's the content of /usr/local/share/fish/functions/fish_default_key_bindings.fish.

**Comment by faho** [comment] 2016-08-16 17:16
@kcbark:

>There is no fish_key_bindings function called: 'fish_default_key_bindings'
>Reverting to default bindings

This is output from `__fish_reload_key_bindings`, which is being triggered by `fish_default_key_bindings` since the variable isn't set to `fish_default_key_bindings`. (It's a bit convoluted, but this allows us to keep the variable in sync with what the bindings actually are, so that it can then be used to check if e.g. vi-mode is active)

>.. repeated X times.
>The function call stack limit has been exceeded. Do you have an accidental infinite loop?

This makes me think you haven't actually upgraded to the newer revision.

Like you said:

> I still get the same errors and no key bindings. Return works though. Hm.

With 790968120d280443be17737c73ff13928a633a37 you should be getting "Cannot find fish_default_key_bindings, falling back to very simple bindings.", and no repeated messages and nothing about the call stack size.

If you aren't, you might not be running the fish you just built. `fish --version` and `echo $FISH_VERSION` should tell you.

Otherwise, this is quite perplexing. It seems like you are running the correct function, but then after that has exited, fish thinks it doesn't exist. Does `functions -q fish_default_key_bindings; or echo Nope` print "Nope"?

It's either something that makes `functions -q` fail always, or there's something weird about the startup path in particular.

**Comment by kcbark** [comment] 2016-08-16 17:30
> This makes me think you haven't actually upgraded to the newer revision.

> With 7909681 you should be getting "Cannot find fish_default_key_bindings, falling back to very simple bindings.", and no repeated messages and nothing about the call stack size.

Strange:
```
@ ~/usr/home/test> fish --version
fish, version 2.3.1-463-g7909681
@ ~/usr/home/test>  functions -q fish_default_key_bindings; or echo Nope 
@ ~/usr/home/test>
```

**Comment by kcbark** [comment] 2016-08-16 17:35
Oh, and:
```
@ ~/usr/home/test> echo $FISH_VERSION
2.3.1-463-g7909681
@ ~/usr/home/test>
```

**Comment by kcbark** [comment] 2016-08-17 17:02
That's the latest, right? Is there any other information that I can give?

**Comment by kcbark** [comment] 2016-08-17 18:35
Hm, OK. I've done some testing with different FreeBSD and fish-shell versions.
FreeBSD 10.3-RELEASE - fish-shell 2.2.0 works, 2.3.1 also works.
FreeBSD 11.0-RC1 - fish-shell 2.2.0 works, 2.3.1  do not.
FreeBSD 12.0-CURRENT - fish-shell 2.2.0 works, 2.3.1 do not.

**Comment by floam** [comment] 2016-08-17 21:13
I'll install FreeBSD 11 tonight in a VM and see if I can figure anything out.

**Comment by floam** [comment] 2016-08-19 08:55
A locale regression: This goes away when you set LC_ALL to en_US.UTF-8 from C. 


<img width="658" alt="screenshot 2016-08-19 at 1 33 11 am" src="https://cloud.githubusercontent.com/assets/291142/17804332/046914ee-65b0-11e6-9a67-0b1a2d4573a1.png">

**Comment by kcbark** [comment] 2016-08-19 16:23
Right. So, is this fixable? Something is wrong with the locale?

**Comment by floam** [comment] 2016-08-19 16:25
That was a fluke, it's something else. 

I seem to not be experiencing it if I build fish 2.3.1 through Ports. I'm looking into it.

**Comment by floam** [comment] 2016-08-20 07:38
Actually, it's not a keybinding issue, and it's actually related it seems to some terrible bug closer to locales. The universal vars are just going, it seems, downstream of thing happening to strings:

https://asciinema.org/a/ce0rzk18kvy8ggn3f14xngtpp

https://asciinema.org/a/9pusj6n3td0yewltopoqufslv 
WTF?

**Comment by floam** [comment] 2016-08-20 07:41
@kcbark Probably your issue is fine if you comment out the `export` line at the bottom of `__fish_set_locale.fish`

**Comment by krader1961** [comment] 2016-09-25 01:33
@kcbark, Can you still reproduce this problem? if so can you do the equivalent of `env LC_ALL=C fish` and report whether or not that fixes the problem?

**Comment by s-ol** [comment] 2016-09-26 08:35
I'm having somewhat related (?) problems on Arch Linux and I don't want to open another issue here.
When I press insert, home or end that prints `[2~`, `[7~` and `[8~` respectively; `C-Left` and `C-Right` print `0c` and `0d`. It used to work in an earlier version of fish, but I can't say in which.

`env LC_ALL=C` does not make anything better and my system locale is `LANG=en_US.UTF-8`.

I think this is probably some configuration issue on my side, is this a known problem I am just too bad to search for?

**Comment by kcbark** [comment] 2016-09-26 09:39
Hi @krader1961. I can still reproduce this problem with the latest source from github.

However: 
`env LC_ALL=C fish`

seems to fix the problem.

**Comment by faho** [comment] 2016-09-26 12:02
@s-ol: Your problem most likely stems from a wrong $TERM. Frequently it's set to "xterm" when the terminal doesn't send the same sequences. See what `infocmp` says for "kich1", "khome" and "kend".

**Comment by s-ol** [comment] 2016-09-26 12:07
@faho thanks! that was actually it. I had TERM set to xterm-256color for some tmux support reason that I probably don't need anymore. This is was `infocmp` said for reference:

  	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,`

**Comment by krader1961** [comment] 2016-09-27 02:58
This has nothing to do with the $TERM value. It's a consequence of BSD incorrectly classifying Unicode private-use characters. See issue #3050. Closing as a duplicate of that issue.

**Closed by krader1961** 2016-09-27 02:58 UTC
Labels: bug, duplicate

**Comment by bapt** [comment] 2016-10-06 19:54
Fixed on FreeBSD as well https://svnweb.freebsd.org/base?view=revision&revision=306782 (for head at least soon on 11)
