### ISSUE TITLE
Weird bug - Typed characters jump to a new line

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5221] opened 2018-09-30 18:55 UTC
Fish 2.7

Sometimes I have this strange bug and I can't reproduce it, but maybe you have seen it previously:

I type a command, and every character I type goes to a second line.

Actually if I press "g" (which is also an abbr for git for me but I just removed it with `abbr -e g`) I get this horrible thing:

http://image.noelshack.com/fichiers/2018/39/7/1538333396-bug-fish.jpeg
(other link) http://www.noelshack.com/2018-39-7-1538333396-bug-fish.jpeg

I think it can be related to my custom prompt or maybe a plugin I use but I really don't know where to look for so if you have seen this kind of bug before, it would help me (instead of "bisecting" everything). It already happened to me long ago and I had fixed it but it came back lol

**Comment by faho** [comment] 2018-09-30 18:57
Duplicate of #5059, #4539, #4609 and numerous other issues.

The summary is that the terminal and fish need to agree on how wide characters are or our cursor movement for doing suggestions goes to wrong places, but this sometimes goes wrong because unicode is hard. Fish 3.0 will have numerous improvements.

**Closed by faho** 2018-09-30 18:57 UTC

**Comment by BarbzYHOOL** [comment] 2018-09-30 19:15
1) So how do I reproduce this? By typing some weird characters? which characters?

2) And ok, I should update to fish 3.0 now, right? :P

**Comment by BarbzYHOOL** [comment] 2018-09-30 22:01
Ok will switch soon :)

**Comment by BarbzYHOOL** [comment] 2018-11-17 18:59
I'm trying it right now but I still have sometimes a bug where there is one letter on the left (shifted to the left and can't be erased)

no idea how to reproduce but I wanted to report it before I forget
