### ISSUE TITLE
Cargo and Rustc completions triggered whithout them being installed, 

### ISSUE THREAD

**Issue by stagnation** [fish-shell/fish-shell#4078] opened 2017-05-28 16:05 UTC
~ fish --version
fish, version 2.5.0
~ echo $version
2.5.0

~ uname -a
Linux spilldesk 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
~ echo $TERM
rxvt-unicode-256color

Problem
-----------

When I write cargo (not installed) or rustc (not installed) fish spews out a verbose error message. That is before trying to tab complete anything, simply `~ cargo` and upon typing space I get the error message below, and the same for rustc. I am still writing the prompt below the error message.

I can only trigger it once per terminal window. The same applies for rustc.

Reproduce
--------------
~ sh -c 'env HOME=$(mktemp -d) fish'
spill@spilldesk /h/spill> cargo fish: Unknown command 'cargo'
/usr/share/fish/completions/cargo.fish (line 1): cargo --list | tail -n +2 | tr -d " "
                                                 ^
in command substitution
	called on line -1 of file /usr/share/fish/completions/cargo.fish

from sourcing file /usr/share/fish/completions/cargo.fish
	called on standard input

in command substitution
	called on standard input

[]`<prompt is here still inserting>`

I don't have rustc or cargo installed

spill@spilldesk /h/spill> find / -name cargo ^/dev/null
spill@spilldesk /h/spill> find / -name rustc ^/dev/null
spill@spilldesk /h/spill> 

Rustc
--------
spill@spilldesk /h/spill> rustc fish: Unknown command 'rustc'
/usr/share/fish/completions/rustc.fish (line 1): rustc -C help \
                                                 ^
in command substitution
	called on line -1 of file /usr/share/fish/completions/rustc.fish

from sourcing file /usr/share/fish/completions/rustc.fish
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'rustc'
/usr/share/fish/completions/rustc.fish (line 1): rustc -Z help \
                                                 ^
in command substitution
	called on line -1 of file /usr/share/fish/completions/rustc.fish

from sourcing file /usr/share/fish/completions/rustc.fish
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'rustc'
/usr/share/fish/completions/rustc.fish (line 1): rustc -W help  \
                                                 ^
in command substitution
	called on line -1 of file /usr/share/fish/completions/rustc.fish

from sourcing file /usr/share/fish/completions/rustc.fish
	called on standard input

in command substitution
	called on standard input

Picture
---------

http://aelv.se/spill/2017-05-28-180709_1272x1267_scrot.png

**Comment by faho** [comment] 2017-05-28 16:10
Duplicate of #2365. In the meantime, the workaround is "don't do that, then" - there's no harm here, just an ugly error message.

**Closed by faho** 2017-05-28 16:10 UTC
