### ISSUE TITLE
builtin cd: fatal libc++abi error on cd ""

### ISSUE THREAD

**Issue by quackduck** [fish-shell/fish-shell#8600] opened 2022-01-01 00:22 UTC
```shell
$ fish --version
fish, version 3.3.1
$ echo $version
3.3.1
$ uname -a
Darwin ishansnewestair.lan 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```
```shell
$ cd ""
libc++abi: terminating with uncaught exception of type std::out_of_range: basic_string

# fish exited
```

On bash and zsh, running `cd ""` seems to do nothing.

**Comment by zanchey** [comment] 2022-01-01 00:34
Duplicate of #8147

**Closed by zanchey** 2022-01-01 00:34 UTC
Labels: duplicate
