### ISSUE TITLE
history cannot delete multi-line commands

### ISSUE THREAD

**Issue by GitRASQ** [fish-shell/fish-shell#3358] opened 2016-09-07 05:45 UTC
**fish version installed** *(`fish --version`)*:
2.3.1

**OS/terminal used**: 
arch linux / konsole

history cannot delete commands that span multiple lines, including 'if' blocks and those split by backslash+enter.

## Reproduction steps
http://i.imgur.com/r8G8SLq.png
http://i.imgur.com/FTJq3gM.png

**Comment by krader1961** [comment] 2016-09-07 06:28
This is a duplicate of issue #31 AFAICT. if that isn't the true @GitRASQ please provide additional information.

**Closed by krader1961** 2016-09-07 06:28 UTC
Labels: duplicate
