### ISSUE TITLE
typing just `source` hangs the shell

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#4076] opened 2017-05-27 19:50 UTC
fish, version 2.5.0

Darwin nero 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

xterm-256color (iterm2)

just typing `source` hangs the shell. I was going to type something else, but managed to hit enter by accident.

Not able to ctrl+c to get out of it.

**Comment by faho** [comment] 2017-05-27 20:23
Duplicate of #2633 (and #3227).

**Closed by faho** 2017-05-27 20:23 UTC
