### ISSUE TITLE
Autocompletion is really slow

### ISSUE THREAD

**Issue by gubikmic** [fish-shell/fish-shell#7645] opened 2021-01-23 14:23 UTC
fish 3.1.2 in iTerm2 3.4.3 on macOS 11.1

I think this started after I updated to Big Sur 11.1. It takes about 1-2 seconds for most completions.

Is there a way to reset this?
Thank you

**Comment by faho** [comment] 2021-01-23 14:51
Duplicate of #7511

**Comment by faho** [comment] 2021-01-23 14:52
A workaround:

```fish
function __fish_describe_command; end
```

**Closed by faho** 2021-01-23 14:51 UTC
