### ISSUE TITLE
Vi mode: Prefixing commands with numbers doesn't repeat command

### ISSUE THREAD

**Issue by rharish101** [fish-shell/fish-shell#10986] opened 2024-12-31 22:14 UTC
## Details
Fish version: fish, version 4.0b1-103-g64ed47bf4
`uname -a`: Linux artorias 6.12.7-zen1-1.1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 28 Dec 2024 02:08:36 +0000 x86_64 GNU/Linux
`echo $TERM`: `xterm-256color`
OS: Arch Linux
Installation: [fish-git](https://aur.archlinux.org/packages/fish-git) AUR package
Tried with customizations: Yes.

## Description
Commands like `2dw` or `2s` in the normal Vi mode, which should repeat `dw` or `s` respectively twice, don't. The numeric prefixes are just ignored, and the commands act just as a single `dw` or `s` respectively.

## Reproduction
1. Enable Vi mode: `fish_vi_key_bindings`.
2. Type something, like `echo hello world`, in the default insert Vi mode.
3. Switch to normal Vi mode, using the Escape key.
4. Position the cursor at the start of the "hello" (e.g. by repeatedly pressing "h" to move the cursor left).
5. Enter the `2dw` command, which is supposed to delete "hello world", leaving "echo" alone.
6. Observe that only "hello" was deleted, not "world".

**Comment by faho** [comment] 2024-12-31 22:34
Duplicate of #2192

**Closed by faho** 2024-12-31 22:34 UTC
