### ISSUE TITLE
tab completion with [ in filenames produces commands which won't run

### ISSUE THREAD

**Issue by ChrisJefferson** [fish-shell/fish-shell#2297] opened 2015-08-12 23:02 UTC
This is most easily explained with an example: Run the following commands: `` mkdir t; touch "t/[c]a.txt" ``

Now, type ``rm t/[``, then press tab. This will be completed to ``rm t/[c\]a.txt``, but that command won't actually run, it returns: 

````
$ rm t/[c\]a.txt
Unexpected end of string, square brackets do not match
fish: rm t/[c\]a.txt
````

**Comment by faho** [comment] 2015-08-13 09:12
This is a duplicate of #2274.

**Closed by faho** 2015-08-13 09:12 UTC
