### ISSUE TITLE
Command substitution in pipeline doesn't use stdin of that pipeline

### ISSUE THREAD

**Issue by KotlinIsland** [fish-shell/fish-shell#8028] opened 2021-05-24 01:56 UTC
Is this by design?
```fish
> bash -c 'echo foo | echo $(cat)'
foo
> fish -c "echo foo | echo (cat)"
asdf
asdf
```
```
> fish --version
fish, version 3.2.2
```

**Comment by faho** [comment] 2021-05-24 06:15
Duplicate of #206

**Closed by faho** 2021-05-24 06:15 UTC
