### ISSUE TITLE
fish dumps core if its terminal emulator is killed while fish is running a loop from a function definition

### ISSUE THREAD

**Issue by vede1** [fish-shell/fish-shell#3401] opened 2016-09-22 06:35 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.3.1

**OS/terminal used**: Arch/gnome-terminal

~~fish dumps core if it is killed by tmux while running a loop from a function definition~~
fish dumps core if its terminal emulator is killed while fish is running a loop from a function definition

## Reproduction steps
```
tmux new-session -s looptest
function looptest; while true; echo loop; sleep 3; end; end
looptest
```
Ctrl-b d *(detach)*
```
tmux kill-session -t looptest
```

## Results
```
wrz 22 08:28:30 arch systemd-coredump[3997]: Process 3911 (fish) of user 1000 dumped core.
                                             
                                             Stack trace of thread 3911:
                                             #0  0x0000007200000065 n/a (n/a)
```

This does not happen if the loop is run without defining a function for it, `while true; echo loop; sleep 3; end`.

**Comment by krader1961** [comment] 2016-09-22 23:38
I can't reproduce on macOS. I'll try later today when I'm home and can start my Ubuntu VM.

**Comment by vede1** [comment] 2016-09-23 06:09
This was discovered while running tmux, but it occurs in normal terminal sessions. Tested in xterm and gnome-terminal.
GNOME Terminal 3.20.2
```
function looptest; while true; echo loop; sleep 3; end; end
looptest
```
Then in different terminal (xterm):
```
kill -s 15 (pgrep gnome-terminal)
```
```
Process 6328 (fish) of user 1000 dumped core.
                                             
Stack trace of thread 6328:
#0  0x0000007200000065 n/a (n/a)
```

fish is started by adding `exec fish` at the end of `~/.bashrc`

**Comment by floam** [comment] 2016-09-23 06:37
Does this happen for you with fish built from git master?

**Comment by vede1** [comment] 2016-09-23 07:06
Yes, `fish, version 2.3.1-563-g204e791` built with [fish-git](https://aur.archlinux.org/packages/fish-git/), stack trace digits changed to `#0  0x0000006f0000002f n/a (n/a)`.

**Comment by ridiculousfish** [comment] 2016-09-24 20:50
Thank you for the great repro steps. When following the tmux steps on ubuntu mate, we get stuck in `term_steal` in the call to `debug()`, apparently in deallocating a string - very strange. However, when I comment out that line, and build at -O0, I can reproduce a SIGSEGV and catch it in gdb. 

Unfortunately we have no backtrace so it's hard to figure out what's going on. Working on reproing in macOS.

**Comment by ridiculousfish** [comment] 2016-09-24 22:10
Ok, I get better results on a 64 bit Linux. We're crashing in `malloc` (!). It looks like malloc maintains a list of function pointers and we're stomping one.

**Comment by ridiculousfish** [comment] 2016-09-24 22:43
I believe we're stomping the `__malloc_hook` and friends instruction pointers. When I put a watchpoint on `__malloc_hook`, I see it's being written by glibc's `_IO_wfile_xsputn`, which looks like https://bugzilla.redhat.com/show_bug.cgi?id=1161130 and https://bugzilla.redhat.com/show_bug.cgi?id=1292908 . I suspect a glibc bug but more investigation is of course needed.

**Comment by ridiculousfish** [comment] 2016-09-25 00:01
Making progress - notes mostly for my benefit. The glibc `FILE*` type has a `_wide_data` structure that contains pointers `_IO_write_base`, `_IO_write_ptr`, and `_IO_write_end` which are respectively the start, current position, and end of a character buffer.

An invariant is that `_IO_write_base <= _IO_write_ptr <= _IO_write_end`. This invariant is being invalidated [here](https://github.com/lattera/glibc/blob/a2f34833b1042d5d8eeb263b4cf4caaea138c4ad/libio/wfileops.c#L477):

```
  if (f->_wide_data->_IO_write_ptr == f->_wide_data->_IO_buf_end)
    /* Buffer is really full */
    if (_IO_do_flush (f) == EOF)
      return WEOF;
  *f->_wide_data->_IO_write_ptr++ = wch;
```

I think what's happening is we attempt to check if the buffer is full, and if so, flush it to make some space. However in this case the buffer has size zero, so flushing it cannot make more space. Thus the write_ptr exceeds the end_ptr, which ultimately causes the wild writes.

**Comment by ridiculousfish** [comment] 2016-09-25 01:07
Definitely a glibc bug - reduced test case [here](https://gist.github.com/ridiculousfish/11bc1298f08dbd8d244a2e2a521b2428). I'll send it over to them.

**Comment by ridiculousfish** [comment] 2016-09-25 01:43
Filed as https://sourceware.org/bugzilla/show_bug.cgi?id=20632 . Closing this since it's in glibc. Thanks for filing it - nice catch!

**Closed by ridiculousfish** 2016-09-25 01:43 UTC
Labels: bug, needs-more-info
