### ISSUE TITLE
Idea: pipe into set for multi-line single-element variables

### ISSUE THREAD

**Issue by Lucretiel** [fish-shell/fish-shell#2490] opened 2015-10-15 21:18 UTC
One of the issues that keeps coming up with the fish shell is that it's very difficult to set the multi-line output of a command to a variable without splitting the output on newlines into an array. While I personally have found that this isn't really that much of an issue in practice, there's enough clamoring for it that I came up with an idea for how to implement it: with a pipe to set:

``` fish
cat multi_line_file | set -i file_content
```

Rather than introduce new syntax or quoting styles, as many other proposals do, this is a simple extension of the `set` command, with no new shell features being added. Thoughts? Is this worth pursuing an implementation?

**Comment by ridiculousfish** [comment] 2015-10-15 21:26
The plan here is to use `string --join`:

    set file_content (cat multi_line_file | string --join \n)

This doesn't work today because it requires special casing of 'string' in the shell. I don't think we have a bug tracking it. This can be that bug.

**Comment by derekstavis** [comment] 2015-10-15 23:20
@ridiculousfish, wouldn't the opposite work better?

    set file_line_by_line (cat multi_line_file | string --split '\n')
    set file_as_single_string_with_newlines (cat multi_line_file)

imho this is the expected behaviour.

**Comment by ridiculousfish** [comment] 2015-10-15 23:35
It may be for `set`, but there are many other cases where you do want the splitting, e.g. `for i in (seq 10)`...

I don't know which case is more common. It might be worthwhile to survey existing uses of command substitutions. However switching to not splitting by default would be a very breaking change.

**Comment by faho** [comment] 2015-10-16 14:05
>It might be worthwhile to survey existing uses of command substitutions

I count 56 occurences of "for .* in (.*)" alone.

Plus most `complete --arguments` (at least 154) and basically all uses of `commandline --tokenize` (at least 1869). While most of these could be sed-patched, that's still a large conversion which carries risks - and that's just the fish-script we control.

I also think splitting on newline is a reasonable default since that's how plenty of programs operate - think grep, which matches per-line. If you want to undo splitting, it's also become rather easy: `string join \n $var`.

**Comment by derekstavis** [comment] 2015-10-16 14:33
>However switching to not splitting by default would be a very breaking change.

Yeah, you guys are right, I was just wondering about something which impacts are very obvious :stuck_out_tongue_closed_eyes:

I still don't like the `string join` thing because the result of a command substitution isn't a string.

**Comment by Lucretiel** [comment] 2015-10-16 16:16
I have to say I *really* don't like `string join` being a special case in the command substitutions- it completely breaks fish's otherwise phenomenal consistency model. Splitting on newlines simply makes the most sense for command substitution, as many command line utilities are line oriented. Having command substitution NOT split in certain cases- or ONLY split in certain cases (like `string split`)- would, in my opinion, be terrible.

That's why I proposed the pipe syntax, above-rather than introducing inconsistency into a very normalized behavior (command substitution splits on newline), it adds a natural extension of the set command. Remember, that's really the only case we're worried about- we don't want to add a whole new syntax (`"$(cat $file)"`, which I hate), we just want to make it possible to assign multi-line strings to variables.

**Comment by derekstavis** [comment] 2015-10-16 17:22
>That's why I proposed the pipe syntax

Something like `set (--keep | -k )` could also be used: `set --keep (cat $file)`, which could be using in substitutions (the pipe syntax although nice doesn't work anywhere. So it does not fix the issue.

For solving general splitting snafu in subtitution I'd really prefer a new substitution syntax. I also don't like `$(cat $file)`, but different approaches could be taken, `\(cat $file)` maybe?

> we don't want to add a whole new syntax

Yeah, It looks to me that the whole point in `string` thing is not chaging the base shell syntax, by not adding new tokens and/or changing the parsing/ast logic.

**Comment by Lucretiel** [comment] 2015-10-16 17:39
> the pipe syntax although nice doesn't work anywhere

What do you mean by this? Why doesn't it work? One of the main fish features is that pipes never fork, so you can always use it.

I do like `-k|--keep`, but there's a problem with it- the only way it could work is if it simply newline-joins the arguments. That's fine for most cases, but it can't determine whether or not there should be a trailing newline. This came up for me recently, when I was patching virtualenv's `activate.fish` script to properly wrap the user's `fish_prompt`. That's why I like the pipe solution- it makes it clear we want the literal character output of a command, without any alteration in the shell, to be assigned to a variable.

**Comment by derekstavis** [comment] 2015-10-16 17:42
@Lucretiel I have updated my comment with additional arguments and use cases. Please give a look to sort out your doubts.

**Comment by faho** [comment] 2015-10-16 17:47
> I also don't like $(cat $file), but different approaches could be taken, \(cat $file) maybe?

What are the differences in behavior regarding the two? As for the character, I've voiced my concerns already in #2438 - the short of it is that it's quite annoying with `grep` as a major example - you'd have "(" for a literal paren, "\\(" for command substitution and "\\\\(" for a capturing group - plus a differently-escaped ")".

**Comment by Lucretiel** [comment] 2015-10-16 17:49
So is the idea that `-j` leaves off the trailing newline (à la Python's join), while `-k` adds a trailing newline? I like that.

Do you have a better example than `echo (cat $file)`? I understand it's overly simplistic for demonstration purposes, but in general commands don't take big blocks of text as arguments. The major case where they do is storing the output of a command or contents of a file to be outputted later, which I think is solved perfectly well by simply making it possible to assign big blocks of text to variables in some fashion.

Can you elaborate on why you don't like the pipe version, though? I still am favoring it, mainly because it makes it clear semantically that we're skipping the shell's processing of command output.

**Comment by derekstavis** [comment] 2015-10-16 17:57
I like the pipe concept, I never said I don't like it! The problem with it is that it solves the problem in the leaf, not in the root, which is command substitution splitting output by `\n`.

**Comment by Lucretiel** [comment] 2015-10-16 18:06
How is that any different than your `-j|-k` proposal? In both cases we're talking about an extension to `set` to make it possible to store Big Blocks of Text, without altering the semantics of command substitution line splitting.

I think we have a fundamental disagreement about that feature- it's easily one of my favorite features about fish. It's consistent with the broader *nix usage patterns (most utilities are line-oriented), and it's consistent internally with fish's "everything is an Array of Strings" data model. It still works fine with most commands with fixed output, like `hostname` and `expr`, because those things output exactly one line. *Not* splitting on newlines is much more corner-casey, and I think it is elegantly solved by an extension to set- either `-j|-k` reconstruction or `-i` direct piping- instead of "yet another substitution syntax."

**Comment by alphapapa** [comment] 2015-10-17 18:29
I think the `cat multi_line_file | set -i file_content` solution is elegant and natural.  I'm not sure what the `-i` would stand for (maybe `-s/--scalar/--string` would be more descriptive), but it just seems natural.

```
set file_content (cat multi_line_file | string --join \n)
```
This seems awkward to me.  I understand that it's joining lines into a single string containing newlines, but since those lines are...already separated by newlines...which already exist in the raw data from `cat`...it seems redundant and confusing.  Of course, having `string --join character-to-join-with` is a handy and powerful command, but for this use-case, something like Lucretiel's solution seems much more natural and straightforward.

**Comment by ridiculousfish** [comment] 2015-10-17 18:58
`set -i` is very nearly the same as `read`. It would be simple to make `read` read until the end of input. On the other hand, it sort of feels like `read` is already duplicative with `set`.

**Comment by alphapapa** [comment] 2015-10-17 22:21
I guess we should also take into account Bash's `mapfile`/`readarray` command.  Using something like `readarray -t <<<"$(cat file)" works very well, although not many people seem to be familiar with it, even though it's been in Bash for years.

**Comment by ridiculousfish** [comment] 2015-10-17 22:31
Wow, I never heard of `mapfile`. It's [so bash](http://wiki.bash-hackers.org/commands/builtin/mapfile). That 'callback' notion is ridiculous.

**Comment by alphapapa** [comment] 2015-10-18 02:53
Yeah, the callback part is rather obscure.  But `readarray` is a lot nicer than resetting `IFS` and stuff like that.

**Comment by Lucretiel** [comment] 2015-10-19 15:45
> `set file_content (cat multi_line_file | string --join \n)`

This wouldn't work anyway. The `string --join \n` command would output a single block of text, and then fish's `()` command substitution would split that block of text on newline, the same as it always does. Part of the [Law of User Focus](http://fishshell.com/docs/current/design.html#user) is that:

> The differences between built-in commands and shellscript functions should be made as small as possible. Built-ins and shellscript functions should have exactly the same types of argument expansion as other commands, should be possible to use in any position in a pipeline, and should support any I/O redirection.

Having `string --join` behave in an exceptional way inside of command substitutions seems like a major anti-fishism.

Now that you point it out, @ridiculousfish, it does seem like there's some overlap between `read` and `set`. They both have a similar set of flags relating to variable scope. Since their main difference is that one takes input from standard input while the other takes input from command-line arguments, I would update my proposal to add either the `--join` behavior to `set`, and/or a "read all text" behavior to `read`. I'd extend the `read` proposal to be something like:

    read [-a|--all] [-f|--fixed <amount>]

Where `-a` means "read all stdin" and `-f` means "read a fixed number of bytes from stdin."

**Comment by faho** [comment] 2015-10-19 16:05
>-f means "read a fixed number of bytes from stdin."

`read` already has `-n` or `--nchars`, which reads a fixed number of _characters_.

**Comment by Lucretiel** [comment] 2015-10-19 17:04
> read already has -n or --nchars, which reads a fixed number of characters.

Really? I'm not seeing that in my man page. That must be new in 2.2.

I just noticed, while reading the updated docs, that `read` also has the `-z` flag, which causes it to read until a `\0` character. This covers 99% of cases, including basically all "text" cases. Is it worth adding another flag for the 1% case of reading pure binary data into a variable, or null-delimited text?

**Comment by faho** [comment] 2016-03-06 14:08
This seems like a big change to do now for 2.3.0, so I'm retargeting this.

**Comment by krader1961** [comment] 2017-03-15 04:52
This is a duplicate of #159. Feel free to reopen if I am mistaken.

**Closed by krader1961** 2017-03-15 04:52 UTC
Labels: duplicate
