### ISSUE TITLE
Wrong memory limit shown or issue with logic

### ISSUE THREAD

**Issue by quackduck** [fish-shell/fish-shell#7334] opened 2020-09-14 12:14 UTC
```sh
ishan@mac [~] $  ls */*/*/*
Failed to execute process '/bin/ls'. Reason:
The total size of the argument and environment lists 34kB exceeds the operating system limit of 256kB.
Try running the command again with fewer arguments.
```
The wrong limit is shown (or at least there's something wrong with the logic - 34 does not exceed 256). Is this a fish issue? Or is it related to `exec` or something else?

I have `fish, version 3.1.2` on  `Darwin mac 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`
`$TERM` is `xterm-256color` (I'm using iTerm2)

**Comment by quackduck** [comment] 2020-09-14 12:57
Even more weirdly - 
```sh
ishan@mac [~] $  ls ~/*/*/*/*
Failed to execute process '/bin/ls'. Reason:
The total size of the argument and environment lists 377kB exceeds the operating system limit of 256kB.
Try running the command again with fewer arguments.
```
differs from 
```sh
ishan@mac [~] $  ls */*/*/*
Failed to execute process '/bin/ls'. Reason:
The total size of the argument and environment lists 39kB exceeds the operating system limit of 256kB.
Try running the command again with fewer arguments.
```
even though they both are listing the same dir! (right?)

**Comment by faho** [comment] 2020-09-14 19:02
Duplicate of #6800 

The issue here is that the total size of the *list* isn't the issue, it's the size of one argument being above MAX_ARG_STRLEN.

**Comment by faho** [comment] 2020-09-14 19:03
Duplicate of #6800

**Closed by faho** 2020-09-14 19:02 UTC

**Comment by quackduck** [comment] 2020-09-15 06:53
Sorry! My search while looking for similar issues was too specific
