### ISSUE TITLE
options don't work as expected for `history`

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3403] opened 2016-09-23 07:33 UTC
**fish version installed** *(`fish --version`)*:  fish, version 2.3.1-563-g204e791

**OS/terminal used**: OS X

Multiple options for history as interpreted by the fish script don't work as expected, these should be equivalent:

`history -t -p foo `
`history -tp foo`

 so should these:
`history --with-time='%x '`
`history -t'%x '`

this is also reasonable:
`history -t --prefix=foo`

**Comment by krader1961** [comment] 2016-09-24 04:13
I don't understand why this is specific to the `history` function. Every single core fish function that accepts flags, with two exceptions, uses the idiom in the `history` function. And therefore fails to parse flags "correctly". There are only two fish functions that attempt to use the `getopt` command to provide the behavior you're asking for: *share/functions/trap.fish* and *share/functions/umask.fish*. And both of those explicitly fail to handle long options on BSD systems (e.g., macOS). Not to mention their logic for using getopt, because of the BSD vs GNU incompatibility, is baroque.

> this is also reasonable:
>  history -t --prefix=foo

That might be reasonable but it is not what the fish implementation has ever done. I actually think it is not reasonable since the relevant flags are meant to affect how the unbound search string arguments are interpreted. Please think about what it means to type `history search --prefix=abc --contains=def ghi`. That UI is FUBAR.

I'm closing this because the point being made is not specific to the history function. Furthermore, the need for a better mechanism for parsing arguments in fish functions has been made multiple times. The canonical one being issue #478.

Personally I would like to see fish provide its own getopt command usable by fish scripts that provides semantics equivalent to those of the *src/wgetopt.cpp* version.

**Comment by krader1961** [comment] 2016-09-24 04:26
Also, for the record @floam, I was quite aware that the option parsing done by the `history` function was not compatible with the libc `getopt()` function. Not to mention that said parsing predated my changes to that function. You might want think about the bigger picture rather than focusing exclusively on the item that triggered your reaction.

**Comment by floam** [comment] 2016-09-24 06:31
The way to fix it is just to do all argument processing in the builtin.

**Comment by floam** [comment] 2016-09-28 06:32
Still occurs, is this a duplicate?

**Comment by krader1961** [comment] 2016-09-29 03:38
This is a duplicate of #478 since @ridiculousfish and others have decided that is the direction to go rather than implementing a `getopt` or similar command for use in fish scripts.

**Closed by krader1961** 2016-09-29 03:38 UTC
Labels: duplicate, enhancement
