### ISSUE TITLE
Provide replacement/alternative for `set -e` to control makefile execution flow

### ISSUE THREAD

**Issue by apastuhov** [fish-shell/fish-shell#10092] opened 2023-11-08 21:28 UTC
fish: `version 3.6.1`
OS: `Darwin MacBook-Air.local 23.1.0 Darwin Kernel Version 23.1.0; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64`
make: `version 3.82`

Ensure that you have makefile 3.82 or higher. 
Fish doesn't provide a direct replacement for `set -e`, and writing explicit error handling for each command within makefile would be.. too explicit?

## Bash variant (works as expected)
Create makefile with such content:
```
SHELL := bash
.ONESHELL: # Single shell for all commands
.SHELLFLAGS += -e

test:
	cd my-dir
	echo 123
```
Run `make test`.
As soon as there is no `my-dir` directory - execution of Make fails as expected thanks to `-e` shell flag.

## Fish variant
Replace makefile content:
```
SHELL := fish
.ONESHELL: # Single shell for all commands
# .SHELLFLAGS += -e # -e is not supported by fish, so this line is commented out

test:
	cd my-dir
	echo 123
```
### Actual behaviour
Make executes `echo 123` even if previous command failed. Because there is no alternative to stop execution when `.ONESHELL` is used.

**Comment by faho** [comment] 2023-11-08 21:48
Duplicate of #510

**Closed by faho** 2023-11-08 21:48 UTC

**Comment by faho** [comment] 2023-11-08 21:51
Probably also worth noting that makefiles really aren't a common use case for fish, or something that we're gearing it towards.
