### ISSUE TITLE
Problem piping `tail -f` into functions

### ISSUE THREAD

**Issue by oleksiyk** [fish-shell/fish-shell#2683] opened 2016-01-18 17:13 UTC
- fish, version 2.2.0
- Mac OS X 10.11.2

alias definition:
```fish
function grep
    command /usr/bin/grep --color=auto --line-buffered $argv
end
```

This works:
```fish
tail -f ./console.log | grep info                                                                                                                                                
2016-01-18 17:11:23.072 [info] <0.21809.3>@riak_kv_index_hashtree:build_or_rehash:928 ...
```

This doesn't work (no output at all, event after CTRL-C):

```fish
tail -f ./console.log | grep info | grep info
```
Here, if we check running processes with `ps` only one grep process is actually running:

```fish
ps -ef | grep grep                                                                         
  501  2203   795   0  7:10pm ttys023    0:00.00 grep --color=auto --line-buffered info
```

Running commands explicitly works fine:
```fish
tail -f ./console.log | /usr/bin/grep --color=auto --line-buffered info | /usr/bin/grep --color=auto --line-buffered info
2016-01-18 17:11:23.072 [info] <0.21809.3>@riak_kv_index_hashtree:build_or_rehash:928 ...
```

And exactly same setup works with bash:

```bash
alias grep='grep --color=auto --line-buffered'
```

```bash
tail -f ./console.log | grep info | grep info
2016-01-18 17:11:23.072 [info] <0.21809.3>@riak_kv_index_hashtree:build_or_rehash:928 ...
```

**Comment by faho** [comment] 2016-01-18 17:21
This is a duplicate of #1396 - fish will buffer the output fully, which _can't_ work for something that doesn't return, like `tail -f`.

**Closed by faho** 2016-01-18 17:21 UTC

**Comment by krader1961** [comment] 2016-01-18 22:07
@oleksiyk You can solve this in a couple of ways. Option 1: use an abbreviation:

```fish
abbr grep='grep --color=auto --line-buffered'
```

Option 2: Make it a script:

```fish
#!/usr/bin/env fish
exec grep --color=auto --line-buffered
```

If you do the latter make sure you give it a different name; e.g., __cgrep__. That way your custom grep won't be invoked every place (e.g., other functions and scripts) that want plain grep.

**Comment by oleksiyk** [comment] 2016-01-18 22:22
Thanks! I solved this with scripts.
