### ISSUE TITLE
Emoji modifiers are treated incorrectly for length computation

### ISSUE THREAD

**Issue by dimaqq** [fish-shell/fish-shell#9978] opened 2023-08-24 05:33 UTC
Similar to https://github.com/fish-shell/fish-shell/issues/8275

Example, 🐈‍⬛ (black cat `"\U0001F408\U0000200D\U00002B1B"`)

```command
> string length -V \U0001F408\U0000200D\U00002B1B
4
```

**Comment by faho** [comment] 2023-08-24 05:40
Duplicate of #8276

**Comment by faho** [comment] 2023-08-24 05:40
No use in keeping multiple of these open. It's all asking for "proper unicode support".

**Closed by faho** 2023-08-24 05:40 UTC
