### ISSUE TITLE
cannot cd path which is an env var

### ISSUE THREAD

**Issue by ericshenjs** [fish-shell/fish-shell#3903] opened 2017-03-20 01:57 UTC
1，
 /c/U/admin> fish -v
fish, version 2.5.0
 /c/U/admin> echo $GOBIN
F:\openProject\Platform\Golang\goX64\bin
 /c/U/admin> cd $GOBIN
cd: The directory 'F:\openProject\Platform\Golang\goX64\bin' does not exist
 /c/U/admin>
2，bash is ok：
 admin@IT-QTP-Client msys ~
$ echo $GOBIN
F:\openProject\Platform\Golang\goX64\bin
admin@IT-QTP-Client msys ~
$ cd $GOBIN
admin@IT-QTP-Client msys /f/openProject/Platform/Golang/goX64/bin
$

**Comment by krader1961** [comment] 2017-03-20 03:20
Using a var to store a path works just fine. Including on MS Windows. I started fish on MS Windows 10 inside Cygwin and found that `cd 'c:\temp'` fails in the identical manner that assigning that path to `$x` and doing `cd $x` does. So the real problem is that a) we don't support backslashes in paths and b) we don't support drive letters.

**Comment by krader1961** [comment] 2017-03-20 04:03
Duplicate of #2961.

**Closed by krader1961** 2017-03-20 04:03 UTC
Labels: duplicate
