### ISSUE TITLE
Fish suggests removed entry from history on up-arrow

### ISSUE THREAD

**Issue by pvonmoradi** [fish-shell/fish-shell#8149] opened 2021-07-19 07:47 UTC
There is an inconsistency in fish behavior compared to bash regarding commands started with leading space:  
In Bash:  
```bash
$echo "ok"
ok
# note the leading space in command below
$ echo "not ok"
not ok
# now if I press up arrow, I only see `echo "ok"` which is expected
```  
However, when I do the same in `fish`, on pressing up-arrow, I see `echo "not ok"`.  
This behavior is unexpected because this line should have been deleted from **both** fish history **and** fish's current shell history. Currently it only deletes it from fish history but the command is still visible on hitting up-arrow.
`fish, version 3.3.1`

**Comment by faho** [comment] 2021-07-19 07:51
Duplicate of #8052.

This was an intentional change - #1383. The last element is kept in memory even if it was prefixed with a space. This is so you can e.g. correct typos.

**Closed by faho** 2021-07-19 07:51 UTC
