### ISSUE TITLE
Running bash command always prints out the lines of code

### ISSUE THREAD

**Issue by wan54** [fish-shell/fish-shell#2373] opened 2015-09-09 20:54 UTC
When I run the command in a native bash shell this doesn't happen. Any switches that I'm missing?

**Comment by ridiculousfish** [comment] 2015-09-09 20:54
You run `bash` from fish and it does something you don't expect? I'm lost.

**Comment by wan54** [comment] 2015-09-09 20:58
the command runs okay, only that it's printing out the code from the function inside the bash script that gets executed..

**Comment by ridiculousfish** [comment] 2015-09-09 20:59
I'm still lost. If you run `bash` it shouldn't execute any bash functions other than startup. Can you please give detailed steps to reproduce?

**Comment by wan54** [comment] 2015-09-09 21:01
It's a bash script, not bash shell that I ran. Third party bash script that I installed and ran

**Comment by ridiculousfish** [comment] 2015-09-09 21:06
How did you run it? Can you give steps to reproduce please?

**Comment by wan54** [comment] 2015-09-09 21:08
from fish shell: `bash -c "the-bash-script"`

also tried with `bash "the-bash-script"`

always prints out the code from the function in `the-bash-script` that gets executed.

**Comment by ridiculousfish** [comment] 2015-09-09 21:12
I can't reproduce:

    > cat the-bash-script
    #!/bin/bash
    echo This is bash
    > bash -c "./the-bash-script"
    This is bash

Can you please give more information? What is the script and the exact command you are running?

**Comment by wan54** [comment] 2015-09-09 21:26
this is function from the third party script:

```bash
function check_for_shared_folders {
  local readonly vbox_shared_folders=$(find_vboxsf_mounted_folders)

  if [[ ! -z "$vbox_shared_folders" ]]; then
    log_error "Found VirtualBox shared folders on your Boot2Docker VM. These may void any performance benefits from using docker-osx-dev:\n$vbox_shared_folders"
    log_instructions "Would you like this script to remove them?"

    local choice=""
    select choice in "yes" "no"; do
      case $REPLY in
        y|Y|yes|Yes )
          umount_vboxsf_mounted_folder "$vbox_shared_folders"
          break
          ;;
        n|N|no|No )
          log_instructions "Please remove the VirtualBox shares yourself and re-run this script. Exiting."
          exit 1
          ;;
      esac
    done
  fi
}
```

the above function is invoked from another function and when the above function get executed it prints out the following:

```bash
+ echo -e '\033[0;31m2015-09-10 07:24:42 [ERROR] Found VirtualBox shared folders on your Boot2Docker VM. These may void any performance benefits from using docker-osx-dev:\n/Users\033[0m'
2015-09-10 07:24:42 [ERROR] Found VirtualBox shared folders on your Boot2Docker VM. These may void any performance benefits from using docker-osx-dev:
/Users
+ log_instructions 'Would you like this script to remove them?'
++ format_timestamp
++ date '+%Y-%m-%d %H:%M:%S'
+ log '\033[0;37m' '\033[0m' '2015-09-10 07:24:42' INSTRUCTIONS 'Would you like this script to remove them?'
+ [[ 5 -gt 4 ]]
+ do_log '\033[0;37m' '\033[0m' '2015-09-10 07:24:42' INSTRUCTIONS 'Would you like this script to remove them?'
+ local readonly 'color=\033[0;37m'
+ shift
+ local readonly 'color_end=\033[0m'
+ shift
+ local readonly 'timestamp=2015-09-10 07:24:42'
+ shift
+ local readonly log_level=INSTRUCTIONS
+ shift
+ local readonly 'message=Would you like this script to remove them?'
++ index_of INSTRUCTIONS DEBUG INFO WARN ERROR INSTRUCTIONS
++ local readonly value=INSTRUCTIONS
++ shift
++ array=("$@")
++ local readonly array
++ local i=0
++ (( i = 0 ))
++ (( i < 5 ))
++ '[' DEBUG = INSTRUCTIONS ']'
++ (( i++  ))
++ (( i < 5 ))
++ '[' INFO = INSTRUCTIONS ']'
++ (( i++  ))
++ (( i < 5 ))
++ '[' WARN = INSTRUCTIONS ']'
++ (( i++  ))
++ (( i < 5 ))
++ '[' ERROR = INSTRUCTIONS ']'
++ (( i++  ))
++ (( i < 5 ))
++ '[' INSTRUCTIONS = INSTRUCTIONS ']'
++ echo 4
++ return
+ local readonly log_level_index=4
++ index_of INFO DEBUG INFO WARN ERROR INSTRUCTIONS
++ local readonly value=INFO
++ shift
++ array=("$@")
++ local readonly array
++ local i=0
++ (( i = 0 ))
++ (( i < 5 ))
++ '[' DEBUG = INFO ']'
++ (( i++  ))
++ (( i < 5 ))
++ '[' INFO = INFO ']'
++ echo 1
++ return
+ local readonly current_log_level_index=1
+ [[ 4 -ge 1 ]]
+ echo -e '\033[0;37m2015-09-10 07:24:42 [INSTRUCTIONS] Would you like this script to remove them?\033[0m'
2015-09-10 07:24:42 [INSTRUCTIONS] Would you like this script to remove them?
+ local choice=
+ select choice in '"yes"' '"no"'
1) yes
2) no
#?
```

**Comment by wan54** [comment] 2015-09-09 21:28
btw, I'm on Yosemite 10.10.5

**Comment by wan54** [comment] 2015-09-09 21:32
basically when the bash script gets executed from the fish shell all of the lines of codes inside the script will be printed out.. the above is just a sample, in reality there are heaps of lines of codes printed out

**Comment by faho** [comment] 2015-09-09 21:42
Sorry, can't reproduce with that either - though I had to uncomment `find_vbox...`, `log_*` and `umount_vbox...` because I don't have that code (and I'm running bash 4.3.39, made in this decade). Can you reproduce with anything you are willing and able to share?

You are saying running

```sh
$ bash
$ bash script.sh
```

works and

```sh
$ fish
$ bash script.sh
```
doesn't?

**Comment by wan54** [comment] 2015-09-09 22:00
It works properly if I set bash as default shell 

If fish is the default shell, doing the above prints out the code.

The full code is in https://github.com/brikis98/docker-osx-dev/tree/master/src

**Comment by wan54** [comment] 2015-09-09 22:04
it's unfortunate for me that only for this command I need to revert back to bash.. enjoy the productivity offered by fish already and that's why I'm asking for help in case I've missed something :)

**Comment by faho** [comment] 2015-09-09 22:57
That still doesn't work for me, though I had to comment/stub out a bunch of stuff to "run" it on linux, so it might only be on OSX.

>It works properly if I set bash as default shell

>If fish is the default shell, doing the above prints out the code.

What exactly do you mean by "default shell"? `chsh`? What about running it via `bash docker-osx-dev` in fish or in bash? What's in your config.fish? What value does $BASH_ENV have (in fish, bash and bash-launched-via-fish)?

**Comment by wan54** [comment] 2015-09-09 23:17
yes setting the default shell via `chsh`

running `bash docker-osx-dev` in fish (as default shell) or switch to bash when in fish shell doesn't work.

I've got nothing in config.fish nor BASH_ENV (freshly install fish)

**Comment by faho** [comment] 2015-09-09 23:27
>running bash docker-osx-dev in fish (as default shell) or switch to bash when in fish shell doesn't work.

It doesn't run or triggers this bug? Or did you mean "does work"?

**Comment by bucaran** [comment] 2015-09-09 23:29
My understanding is that he is saying that running `bash docker-osx-dev` from fish when fish is his default shell triggers this bug.

**Comment by wan54** [comment] 2015-09-09 23:34
it does run but prints out the codes only when fish is the default shell

**Comment by ridiculousfish** [comment] 2015-09-09 23:34
I can't reproduce when running that boot2docker script.

Maybe there's some weird environment variable. What does `env` output in fish? Anything suspicious?

**Comment by bucaran** [comment] 2015-09-09 23:35
I noticed `docker-osx-dev` runs `eval` several times inside subshells `$(eval echo "..."))`. Could that have something to do with this?

**Comment by wan54** [comment] 2015-09-09 23:44
output from `env`:

```bash
DOCKER_CERT_PATH=/Users/me/.docker/machine/machines/default
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
HOME=/Users/me
LANG=en_US.UTF-8
LOGNAME=me
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/me
SHELL=/usr/local/bin/fish
SHLVL=1
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=614C8D15-EC3F-42D9-AE2A-B1017D7E8344
TMPDIR=/var/folders/m7/05f9gkfn14lc55kd6s2brc5c0000gp/T/
USER=me
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
__CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
__fish_bin_dir=/usr/local/Cellar/fish/2.2.0/bin
__fish_datadir=/usr/local/Cellar/fish/2.2.0/share/fish
__fish_help_dir=/usr/local/Cellar/fish/2.2.0/share/doc/fish
__fish_sysconfdir=/usr/local/Cellar/fish/2.2.0/etc/fish
```

**Comment by zanchey** [comment] 2015-09-09 23:46
This happens with bash when you do `set -x`, or equivalent.

**Comment by ridiculousfish** [comment] 2015-09-09 23:50
@wan54 Does the bash code get printed and also executed? Or is it only printed, and not executed?

**Comment by wan54** [comment] 2015-09-09 23:56
both

**Comment by faho** [comment] 2015-09-10 00:00
>This happens with bash when you do set -x, or equivalent.

Yep, the script also has a `backtrace` function that does something similar, though, that is called via `assert_non_empty` which is called via `env_is_defined` which is called via `determine_boot2docker_exports_for_env_file` which is called via `add_environment_variables`, in which `boot2docker shellinit` is also called, so if that does anything weird, it could also be triggered. (Note: All of those are the only callsites)

boot2docker seems to be an external program.

**Comment by faho** [comment] 2015-09-10 00:07
boot2docker also [seems to be deprecated](https://github.com/boot2docker/boot2docker-cli) in favor of [docker machine](https://docs.docker.com/machine/) and the documentation seems to be sparse and focused on the tutorial side of things (do this, then that, then that and now you've got a boot2docker) without explaining the steps.

**Comment by wan54** [comment] 2015-09-10 00:10
I've never thought of this as an issue on the Fish side. Just want to make sure that I haven't missed anything. 

I'm happy to close this issue.

**Comment by ridiculousfish** [comment] 2015-09-10 00:42
@wan54 No, please don't close, you have the finest fish minds all intrigued :)

This is definitely the output you'd expect from having `set -x` set. It's possible to set this from the commandline, e.g. `bash -x somescript.sh` will do the same.

One possibility is that you have either a bash wrapper function, or multiple bashs installed. If fish has a different value for `$PATH` it could be picking an unexpected one. Try checking for your bashs with `which -a`. I have two:

    > which -a bash
    /usr/local/bin/bash
    /bin/bash

Now run each one in turn:

    /usr/local/bin/bash docker-osx-dev

does it reproduce with one bash but not another?

Also you may have a function. Does `functions bash` output anything?

**Comment by faho** [comment] 2015-09-10 08:40
>This is definitely the output you'd expect from having set -x set. It's possible to set this from the commandline, e.g. bash -x somescript.sh will do the same.

On a closer look, it's _not_ the `backtrace` function (which is quite clever, really), because that outputs like this

```bash
      log_error "  at ${bt_file}:${bt_line} ${bt_function}()"
```

so we'd see the word "at", and a different format in the output. Shame, really, I was just feeling quite clever myself.

**Comment by ridiculousfish** [comment] 2015-09-29 01:07
@wan54 ping, did you ever get to the bottom of this? Did you get a chance to try my ideas from [this comment](https://github.com/fish-shell/fish-shell/issues/2373#issuecomment-139081536)?

**Comment by wan54** [comment] 2015-09-30 10:00
Sorry for not responding. I just saw the GH notification today. I have not tried yet. I'll try it when I'm healthy again. I'm sufferring from nerve inflammation on my right hand

**Comment by faho** [comment] 2015-09-30 10:32
Then all I've got to say is: Get well soon!

**Comment by krader1961** [comment] 2016-04-08 02:04
Closing since it doesn't look like we'll ever get to root cause.

**Closed by krader1961** 2016-04-08 02:04 UTC
Labels: needs-more-info, question
