### ISSUE TITLE
PROMPT_COMMAND !== variable event handler?

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2165] opened 2015-07-03 02:25 UTC
I am trying to setup Tmux to use `pwd` as the window name. I have it partially working with a variable event handler per https://github.com/fish-shell/fish-shell/issues/981#issuecomment-23469985. My command is:

    function tmux_pane_title --on-variable PWD
    	printf "\033k$PWD\033\\"
    end

It works but only if I add it in config.fish. This results in it being executed and printing the working directory before the prompts in all new panes. I am guessing there may be a better way to do this though. Sorry if I missed it in the documentation (http://fishshell.com/docs/current/index.html#event).

**Comment by ridiculousfish** [comment] 2015-07-03 02:47
Does defining `fish_title` do what you want, e.g. `function fish_title; pwd; end`?

**Comment by ElijahLynn** [comment] 2015-07-03 16:30
I just tried it and doesn't appear to work. I did a `funced fish_title` and then a `funcsave` with `function fish_title; pwd; end`

**Comment by ridiculousfish** [comment] 2015-07-03 19:19
Sorry, I see now you want to set the window name, not title. By that, you mean to say that the PWD is output in the console? I tried your function and it seemed to work fine for me.  Perhaps your terminal doesn't ignore the tmux name-setting escape sequence. Would that explain what you're seeing?

**Comment by zanchey** [comment] 2015-07-06 06:22
It works OK for me with fish 2.2b1 and tmux 1.9.

**Comment by ElijahLynn** [comment] 2015-07-06 22:05
Are you saying that you source the function in config.fish and it works? Or that you just declare the function and it works?

It may explain it but I am not sure, I don't have much knowledge of escape codes.

To be more clear about what I am doing, I have a ~/.config/fish/functions/tmux_pane_title.fish with:

   function tmux_pane_title --on-variable PWD
       printf "\033k$PWD\033\\"
   end

When Tmux loads it doesn't change the pane title but if I then run the function manually, `tmux_pane_title`, just once, then it starts working for just that window, if I make a new window it does not work.

Then if I put `tmux_pane_title` in the config.fish file it will work for all windows but before the first prompt of the first window it will output the $PWD.

I am using 2.2b1-44-g976ce1e and Tmux 2.0.

Thanks

**Comment by zanchey** [comment] 2015-07-12 07:09
I think I understand now - as you have discovered, event handlers aren't automatically installed if you define them in saved functions (#845).

I can reproduce your problem if I install the same function as you have described. I don't see it in the first window of tmux, but I do see it when I launch my terminal for the first time. What about using `switch $TERM; case screen*` to only emit the sequence when in screen/tmux?

**Comment by faho** [comment] 2016-02-26 11:40
Closing as duplicate of 845.

**Closed by faho** 2016-02-26 11:40 UTC
