### ISSUE TITLE
What fish pitfalls can I describe in cheatsheet page?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#9306] opened 2022-10-26 13:33 UTC
I wanna to create cheatsheet for Fish shell [here](https://github.com/cheat/cheatsheets). I am searching for smth like [Bash Pitfalls](https://mywiki.wooledge.org/BashPitfalls) but for Fish. Is it a good idea to use [FAQ](https://fishshell.com/docs/current/faq.html) for this purpose?

**Comment by zanchey** [comment] 2022-10-26 13:38
There's a couple of longstanding issues that have the potential to blow up in people's faces:

#1040 (`psub` has some warts with long-running processes)

#238 (can't background fish functions)

Also `test` has a lot of bad edge-cases, though they're the same in bash.

**Comment by faho** [comment] 2022-10-26 13:55
Depends on what you want. The FAQ is both for scripting and interactive use, so if you only want to document scripting pitfalls a lot of those don't apply.

It's also often "pitfalls" that are simply differences from bash. Which I suppose are things that people stumble over if they come from bash.

Listing a few:

- Command substitutions (`(command)` and `$(command)`) are split on newlines only - typically this is a big win, but sometimes you *need* splitting on spaces (usually with `pkg-config` and friends)
- Variables are all lists, and expanded to one argument per element outside of quotes, no word splitting happens. This basically fixes issues with filenames with spaces, but sometimes confuses people coming from bash because `set foo "bar baz"` and `set foo bar baz` are different things.
- If a variable has no elements, it will expand to nothing outside of quotes, including any adjacent string - `$foo/file` will be eliminated if $foo hasn't been set
- Fish *always* reads its configuration, even non-interactively. This might increase the time needed to run a fish script, or it might blow up ssh if your config.fish prints something
- Unconditionally appending to universal variables in config.fish will cause them to grow
- Wildcards operate like with bash's failglob, so `apt install postgres-*` will print an error instead of passing it through unchanged (unless you have one file called e.g. `postgres-foo`, which will cause bash to silently do the wrong thing instead)
- `set` takes a variable *name* - it's `set foo`, not `set $foo`. This is completely consistent (every `set` call just undergoes ordinary expansion), but sometimes trips people up who don't fully grok expansions

You might notice that a few of these are the inverse of bash's pitfalls - people expect bash's behavior that is responsible for some brokenness and are surprised.

For example that glob behavior is called out in Bash Pitfall Nr 1 as a secondary pitfall:

> Question: What happens if there are no *.mp3-files in the current directory? Then the for loop is executed once, with file="./*.mp3", which is not the expected behavior!

A bunch of these also apply to unix semantics in general, for example https://mywiki.wooledge.org/BashPitfalls#cat_file_.7C_sed_s.2Ffoo.2Fbar.2F_.3E_file - here the issue is simply reading and writing to the same file.

Or there are things like https://mywiki.wooledge.org/BashPitfalls#echo_.22.2BAH4.22 - fish also only expands `~` outside of quotes. Or https://mywiki.wooledge.org/BashPitfalls#printf_.22.24foo.22, because printf is essentially the same thing in fish.

Some of these are the kind where it works in bash but doesn't in other shells. Those aren't a thing in fish because it's incompatible with them to begin with.

So you'll have to decide what sort of pitfalls you're interested in. Is it only scripting? Is it things that trip up users coming from bash?

**Comment by mqudsi** [comment] 2022-10-26 18:30
For people coming from general-purpose programming languages: 

* Indexing starts at 1, not 0.
* Setting a variable is done without the `$`, as is querying it (`set foo bar`, `set -q foo`).
* Concatenating with an unset variable or an empty variable elides all output (`set foo; echo 42_$foo;` prints nothing).

(@faho has already covered two of these, but I felt the need to stress them.)

**Comment by faho** [comment] 2022-11-01 08:00
Question appears to have been answered, closing!

**Closed by faho** 2022-11-01 08:00 UTC
Labels: question
