### ISSUE TITLE
Fish becomes unresponsive when starting it with no tty/pty

### ISSUE THREAD

**Issue by crschnick** [fish-shell/fish-shell#9907] opened 2023-07-21 16:47 UTC
```
fish, version 3.6.1
Linux ip-172-31-17-92.eu-central-1.compute.internal 6.1.27-43.48.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May  2 04:53:36 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```

When running fish in a shell with no allocated tty or pty, e.g. when you `ssh -T user@host`, fish just becomes unresponsive. You can type input but nothing ever happens and you can't exit as well, so you have to kill the session.

**Comment by faho** [comment] 2023-07-21 17:12
Try pressing Ctrl-D.

Fish reads all input before doing anything so it can syntax-check it fully, so it will do nothing before the stream is closed.

**Comment by crschnick** [comment] 2023-07-21 17:17
I tried that and it didn't work. Do signals even work without tty/pty?

![image](https://github.com/fish-shell/fish-shell/assets/72509152/19a471cb-e366-457e-8b39-0d0fff3910b5)

**Comment by faho** [comment] 2023-07-22 15:11
Works for me.

"Ctrl-D" is a simplification - you want to close the stream, and that's the default EOL char.

**Comment by crschnick** [comment] 2023-07-22 15:40
Ok, just for context here, I'm working implementing fish support for https://github.com/xpipe-io/xpipe.

What the application does is first launch the shell process in the background, i.e. with no tty/pty, and interact with it from there. This has worked with all other shells so far and I didn't need to close any stdin.

For something like bash for example, I just write the command followed by a newline character into the stdin of the shell and it works fine, the command gets executed. So do I understand you correctly that this is not possible with fish as you have to send an EOF, not a newline to execute the command?

**Comment by faho** [comment] 2023-07-22 15:46
> This has worked with all other shells so far and I didn't need to close any stdin.

Yes, fish isn't other shells.

> So do I understand you correctly that this is not possible with fish as you have to send an EOF, not a newline to execute the command?

Correct. Like I said initially: Fish wants to read the entire file before it does anything.

It does not do non-interactive runs line-by-line.

This is fundamentally different from bash where you can have a script file that has a syntax error on line 10, and it will execute lines 1 through 9.

**Comment by crschnick** [comment] 2023-07-22 15:53
> It does not do non-interactive runs line-by-line.

Technically this is an interactive scenario though in my case, at least that's how I interpret it. It's not like I'm feeding static scripts into fish, I am feeding multiple independent commands into it and interact with them.

Is there a way to force fish to use interactive mode with no tty/pty? I tried with the `-i` switch but that does not seem to make a difference.

**Comment by faho** [comment] 2023-07-22 15:54
>Is there a way to force fish to use interactive mode with no tty/pty?

There is not.

**Comment by faho** [comment] 2023-07-22 15:56
I'm gonna close this as a duplicate of #6967, because that seems like what you're asking for.

**Closed by faho** 2023-07-22 15:56 UTC
Labels: needs more info
