### ISSUE TITLE
universal exported environment variable not exported anymore on subsequent assignations

### ISSUE THREAD

**Issue by shouze** [fish-shell/fish-shell#6895] opened 2020-04-13 22:14 UTC
| Environment    |                                                            |
|----------------|------------------------------------------------------------|
| fish --version | fish, version 3.1.0                                        |
| uname -a       | Linux sebastien-XPS-13-7390 4.15.0-1076-oem #86-Ubuntu SMP |
| echo $TERM     | xterm-256color                                             |

## How to reproduce?

If I run a parent fish process:
```fish
fish --debug="env-export" --debug-output=/tmp/parent.output -D 128 -l
```

When I execute the following commands, exported values are not recalculated on subsequent assignments:
```fish
echo "1. First assignment"
set -e my_var
set -S my_var
env | grep my_var && echo "env $my_var"
fish --debug="env-export" --debug-output=/tmp/child.output -D 128 -c 'set -Ux my_var foo'
# produces env-export: create_export_array() recalc: 1 in parent, 2 in child
env | string match my_var=\* && echo "env $my_var"
echo
echo "2. Second assignment, parent fish process is no more consistent about variable value"
fish --debug="env-export" --debug-output=/tmp/child.output -D 128 -c 'set -Ux my_var bar'
# produces env-export: create_export_array() recalc: 0 in parent, 2 in child
env | string match my_var=\* && echo "env $my_var"
echo
echo "3. Unless it reloads"
source ~/.config/fish/config.fish
# produces env-export: create_export_array() recalc: 2 in parent, 0 in child (no child exec)
env | string match my_var=\* && echo "env $my_var"

1. First assignment
$my_var: not set in local scope
$my_var: not set in global scope
$my_var: not set in universal scope

my_var=foo
env foo
$my_var: not set in local scope
$my_var: not set in global scope
$my_var: set in universal scope, exported, with 1 elements
$my_var[1]: length=3 value=|foo|

my_var=foo
env foo

2. Second assignment, parent fish process is no more consistent about variable value
my_var=bar
env bar
$my_var: not set in local scope
$my_var: not set in global scope
$my_var: set in universal scope, exported, with 1 elements
$my_var[1]: length=3 value=|bar|

my_var=foo
env bar

3. Unless it reloads
my_var=bar
env bar

```

**Comment by shouze** [comment] 2020-04-13 22:27
This is maybe related to https://github.com/fish-shell/fish-shell/issues/5258 and https://github.com/fish-shell/fish-shell/pull/6218?

**Comment by krobelus** [comment] 2020-04-13 22:50
Yeah, the exported variables need to be updated here

**Comment by shouze** [comment] 2020-04-13 23:01
And maybe related to https://github.com/fish-shell/fish-shell/issues/6653? ping @ridiculousfish 

Looks like there's a regression between 3.0.2 and 3.1.1 as I don't reproduce it on 3.0.2:
![image](https://user-images.githubusercontent.com/54712/79167562-fc2dd180-7de7-11ea-9cd0-1aceab3e7ccf.png)

**Comment by krobelus** [comment] 2020-04-13 23:16
Duplicate of #6612

**Closed by krobelus** 2020-04-13 23:16 UTC
Labels: bug, regression

**Comment by shouze** [comment] 2020-04-13 23:46
@krobelus Ok, seen your fix, but I have bad news, I can still reproduce it. working on another issue to explain how. I'm now using HEAD's repo fish to ensure this gets fixed :wink:

**Comment by shouze** [comment] 2020-04-14 01:06
@krobelus ok no in fact all is good since your latest patch! :tada: 
I had issues related to a Makefile in the project I've found the env var bug. I've also fixed on my side now.

**Comment by krobelus** [comment] 2020-04-14 14:29
Sounds good, thanks for filing, please report if you find anything else that's fishy.
