### ISSUE TITLE
`fish_trace` doesn't print commands from hooks

### ISSUE THREAD

**Issue by ajeetdsouza** [fish-shell/fish-shell#8966] opened 2022-05-19 12:56 UTC
If I setup a hook in fish shell like so:

```fish
function asdf_hook --on-variable PWD
    echo "asdf"
end
```

Despite enabling `fish_trace`:

```fish
set fish_trace 1
```

I don't see `asdf_hook` in `fish_trace`'s output, even though it does actually run when you change directories:

```console
$ cd ..
> cd ..
--> set -l MAX_DIR_HIST 25
--> if
---> count ..
---> test .. = --
---> echo 1
--> test 1 -gt 1
--> end if
--> if
--> status --is-command-substitution
--> end if
--> set -l previous /home/ajeet/ws
--> if
--> test .. = -
--> end if
--> cd ..
asdf # <-------------------------------------------------------------- notice this!
--> set -l cd_status 0
--> if
--> test 0 -eq 0 -a /home/ajeet != /home/ajeet/ws
---> set -q dirprev
---> set -q 'dirprev[25]'
---> set -U -q dirprev
---> set -g -a dirprev /home/ajeet/ws
---> set -U -q dirnext
---> set -e dirnext
---> set -U -q __fish_cd_direction
---> set -g __fish_cd_direction prev
--> end if
--> return 0
```

If this is by design, is there any Fish debug feature that does this, such as `set -x` in Bash?

## Environment:

- fish 3.4.1
- Nix over Ubuntu 20.04.4, running on WSL2 (Windows 11)
- Windows Terminal

**Comment by faho** [comment] 2022-05-19 13:20
Duplicate of #7781

**Closed by faho** 2022-05-19 13:20 UTC
