### ISSUE TITLE
`set -U -x` in script doesn't immediately update the var

### ISSUE THREAD

**Issue by cben** [fish-shell/fish-shell#2151] opened 2015-06-25 15:57 UTC
Tested on ubuntu, ppa:fish-shell/release-2, version 2.1.1.dfsg-2.

Setting a universal *env* var in a non-interactive script doesn't seem to take effect until the shell exits:

```
$ cat t.fish
printenv FOO
echo '$FOO =' $FOO
set -U -x | grep FOO

set -U -x FOO (random)
sleep 5

printenv FOO
echo '$FOO =' $FOO
set -U -x | grep FOO

$ pgrep -fa fishd
14723 /usr/bin/fishd

$ fish t.fish; echo After = $FOO
30404
$FOO = 30404
FOO 30404
30404
$FOO = 30404
FOO 30404
After = 20590
```

It does work reliably (even without the `sleep`!) in an interactive shell:

```
$ . t.fish; echo After = $FOO
3303
$FOO = 3303
FOO 3303
25258
$FOO = 25258
FOO 25258
After = 25258
```

This is specific to universal env vars — setting a non-exported universal var (`set -U`) or an exported global var (`set -g -x`) takes immediate effect in all cases.

**Comment by zanchey** [comment] 2015-06-26 08:45
This is working by design, but it's a complicated side-effect of variable scoping - see #806. A warning gets produced on 2.2b1 which is what clued me in.

The problem is that when you execute `fish t.fish`, you are exporting the value of the universal variable, which the new process then inherits as a global variable. Global variables are always expanded in preference to universal variables, so `set -U` updates the universal variable but not the global. When the new process exits, there is no global variable in the original process' scope, and so the updated value of the new variable is printed.

On 2.2b1, a warning is printed: `set: Warning: universal scope selected, but a global variable “FOO” exists.`

I'm going to close this for now as I think this is intended behaviour - reopen if you disagree.

**Closed by zanchey** 2015-06-26 08:45 UTC
