### ISSUE TITLE
[Documentation]: PATH vs INCLUDE_PATH (etc.) treatment

### ISSUE THREAD

**Issue by leezu** [fish-shell/fish-shell#4009] opened 2017-05-04 05:26 UTC
fish automatically creates arrays from the variables PATH, CDPATH and MANPATH when it is started. (Previous versions created arrays from all colon-delimited environment variables.)

Therefore PATH can be updated as `> set PATH /usr/local/bin /usr/sbin $PATH`.

However, if variables such as INCLUDE_PATH, LIBRARY_PATH, LD_LIBRARY_PATH, LD_RUN_PATH, CPATH, PKG_CONFIG_PATH (...) are treated as arrays by the user:

`set -x INCLUDE_PATH /usr/local/cuda-8.0/include $INCLUDE_PATH`

downstream programs are commonly not able to process the array, as they expect a colon separated string. I.e. the user must not use the array feature for these kind of variables. A naive user may assume that fish will automatically transform the array to a colon separated string before passing it downstream.

I feel this should be mentioned in the tutorial when introducing the array / list feature and talking about  how to set $PATH. Otherwise it can lead to confusion.

What do you think?

**Comment by krader1961** [comment] 2017-05-04 06:24
I would prefer we actually implement a means to allow the user to define env vars that should be automatically split/joined on a character like ":" on import/export. Something like the "tied" variables available in zsh via `typeset -T`. This is already being discussed in issue #2090 and #436.

I am tempted to close this as a duplicate of #436 but am going to leave it open since someone may feel strongly that we should better document the current situation until that issue is resolved.

**Comment by krader1961** [comment] 2017-05-26 04:16
It could be a long time before we implement support for auto split/join of other env vars. So I'm going to propose a small change to the tutorial that should address this issue.

**Closed** 2017-05-26 15:00 UTC
Labels: enhancement
