### ISSUE TITLE
`grep -r foo &| grep -v bar` hangs

### ISSUE THREAD

**Issue by SandaruKasa** [fish-shell/fish-shell#9772] opened 2023-05-03 22:38 UTC
fish 3.6.1 (from Archlinux repo) on Linux 6.1

Running
```fish
grep -r python &| grep -v somepath
```
hangs.

I suspect it has something to do with this:
```fish
$ type grep
grep is a function with definition
# Defined in /usr/share/fish/functions/grep.fish @ line 6
function grep
        command grep --color=auto $argv
end
```

I've tried different combinations of commands, piping, flags, etc. The minimal necessary conditions seem to be as follows:
1. piping with '&|'
2. fish functions on both sides
3. left function writes a ton to stderr

For example,
```fish
function foo
    xxd /dev/zero /dev/fd/2 
end
function bar
end
foo &| bar
```
hangs.

If I redefine `bar` to call, for example, `python bar.py`, where `bar.py` is just
```python
while True:
    pass
```
it still hangs, and using, say, `htop` I can see that `xxd` is indeed running but `python` is not.

Also, Ctrl+Z is not working when stuff like this hangs. Ctrl+C does.

**Comment by SandaruKasa** [comment] 2023-05-03 22:43
`foo 2>&1 | bar` behaves the same way

**Comment by zanchey** [comment] 2023-05-03 23:46
Duplicate of #1396

**Closed by zanchey** 2023-05-03 23:46 UTC
