### ISSUE TITLE
Can't accept autosuggestion word and insert other character using bind

### ISSUE THREAD

**Issue by QianChenglong** [fish-shell/fish-shell#10312] opened 2024-02-19 04:05 UTC
fish, version 3.7.0
<img width="1142" alt="image" src="https://github.com/fish-shell/fish-shell/assets/1881126/ed40b577-90e0-4575-a55c-ec88afd871de">
`  bind -M insert \cA 'commandline -f forward-bigword; commandline -a " "'`

Expect:
accept autosuggestion word and append space
Actually:
only  append space

**Comment by krobelus** [comment] 2024-02-19 06:25
`commandline -a` is not ideal in this case because it doesn't append at the cursor.
Unfortunately we can't use `commandline -i` because the cursor position is only updated after running the binding.
Maybe we can revisit that.

For now I recommend not using such a complex binding. Space is easy to type

**Comment by QianChenglong** [comment] 2024-02-19 09:02
Accepting single word completion is a high-frequency operation. Need to manually type in a space every time, which is not very comfortable.

**Comment by faho** [comment] 2024-02-19 09:31
Duplicate of #3031

**Closed as completed by faho** 2024-02-19 09:31 UTC
Labels: duplicate
