### ISSUE TITLE
Fish outputs ? before each prompt on windows

### ISSUE THREAD

**Issue by corinnaerin** [fish-shell/fish-shell#2092] opened 2015-05-26 17:36 UTC
I just switched to a windows machine and I'm trying to get fish configured correctly. I installed it through the default route, as a shell selected through cygwin setup. When I directly run fish.exe or run fish.exe through IntelliJ's built in terminal, it outputs a ? before very prompt: 

![y7szf](https://cloud.githubusercontent.com/assets/2001071/7818689/04ac09ba-0392-11e5-8767-829d089e6487.png)

I googled the problem, and found a possible solution on the FAQ: http://fishshell.com/docs/current/faq.html#faq-titlebar. According to that, the issue is caused by running fish inside a terminal which doesn't support setting the terminal window title, and instead it gets output to the screen. However, the suggested solution (changing the fish_title) function did not fix the problem.

It doesn't have this behavior when using fish through mintty.exe, most likely since that terminal supports setting the title, but I really prefer to use the terminal inside intelliJ instead of having it in a separate window. It also didn't have this problem when I used fish through IntelliJ on Ubuntu or MacOSX, it appears to be isolated to Windows

**Comment by zanchey** [comment] 2015-05-28 08:57
Are you using the default prompt? If so, it's getting very confused.

**Comment by corinnaerin** [comment] 2015-05-28 17:47
I am not using the default prompt, however the issue persists with the default prompt as well:

![fish](https://cloud.githubusercontent.com/assets/2001071/7866827/d0882f2e-0526-11e5-8560-14131914660b.PNG)

A colleague of mine installed fish on his windows machine as well, and has the exact same issue in IntelliJ and fish.exe

**Comment by ridiculousfish** [comment] 2015-05-28 21:00
This may be the ⏎ character that fish outputs. What does this output: `echo -n hi`. Is there a question mark after the hi?

**Comment by corinnaerin** [comment] 2015-05-28 21:13
No additional question mark, anyway:

![fish](https://cloud.githubusercontent.com/assets/2001071/7871250/8c5e866e-0543-11e5-92f1-b20298a716ca.png)

**Comment by ridiculousfish** [comment] 2015-05-28 21:15
Yeah, that looks to be it. Try this:

    echo abc\rdef

That should output 'def'. What do you get?

**Comment by corinnaerin** [comment] 2015-05-28 21:16
![fish](https://cloud.githubusercontent.com/assets/2001071/7871347/2d7607e8-0544-11e5-8630-d6311f0586d1.png)

**Comment by ridiculousfish** [comment] 2015-05-28 21:22
Maybe your term thinks it can do Unicode but can't. How about `echo \U23CE`? That should output a Unicode arrow.  Also, what does `locale` output?

**Comment by corinnaerin** [comment] 2015-05-28 21:25
Aha! I thought it might have something to do with the charset. Looks like my charset is UTF-8.

![fish](https://cloud.githubusercontent.com/assets/2001071/7871533/4c033ab8-0545-11e5-973e-5350db8f8574.png)

**Comment by corinnaerin** [comment] 2015-05-28 22:46
Quick additional note, this problem occurs when running fish through:
* cmd then calling fish.exe
* bash.exe directly then calling fish.exe
* fish.exe directly
* IntellIj terminal calling fish.exe

The only time this doesn't happen is when using cygwin terminal (mintty.exe).

Is there any way to work around the issue? Either by changing how the characters are handled, or changing the character that is being output to something the terminal knows how to render?

**Comment by ridiculousfish** [comment] 2015-05-28 23:09
The basic problem is that your locale claims to be UTF-8 savvy, but your terminal is not. Try setting the environment variable `LC_ALL` to `C`. Does that fix it?

**Comment by corinnaerin** [comment] 2015-05-29 00:29
It's now showing a tilde instead of a question mark. Where is this character coming from? It doesn't appear to be part of fish_prompt, because this happens even when I do ```function fish_prompt;end```

**Comment by ridiculousfish** [comment] 2015-05-29 00:34
This is coming from `s_reset`, which is used to ensure that each prompt starts on a new line (if it doesn't, then things can get very screwy when there's a right prompt).

The way this works is that it outputs the "omitted_newline_char" (⏎ if Unicode is supported, tilde otherwise), then a bunch of spaces, then CR, then a few more spaces, then CR again. The idea is that if we are at the beginning of a line, we'll end up back where we started with no net effect, but if we are in the middle of a line, the spaces will push us to the next line. The idea comes from zsh.

It's possible that fish is getting the wrong value for the width of your terminal. What does `echo $COLUMNS` show? Is it the correct value?

**Comment by corinnaerin** [comment] 2015-05-29 00:41
It appears to be correct, yes.

**Comment by ridiculousfish** [comment] 2015-05-29 00:51
Hmm, ok. We can try what fish does and see what happens.

Try this:

    echo -n \r'~                                                                               '\r' '\r

where the number of spaces after the tilde should be equal to one less than $COLUMNS (here it's 79). What should appear is no apparent output, but if you resize your window a little smaller and rerun it you should see the tilde on its own line. What happens if you do that?

I appreciate your patience with this!

**Comment by corinnaerin** [comment] 2015-05-29 00:52
Oh interesting.... the # of columns do seem to be related though.... the problem disappears when I reduce the size of the terminal window (using fish.exe directly)

![fish](https://cloud.githubusercontent.com/assets/2001071/7874265/2297cae6-0562-11e5-9e0f-d784be18fda2.png)

**Comment by corinnaerin** [comment] 2015-05-29 00:58
Sorry, I'm not sure if I'm following your instructions correctly, but if I execute ```echo -n \r'~```, it just hangs with the cursor aligned with the $, but I can't do anything else afterward, regardless of the screen size:

![fish](https://cloud.githubusercontent.com/assets/2001071/7874341/1fb5b080-0563-11e5-8e46-8cdd58c18dcb.png)

**Comment by ridiculousfish** [comment] 2015-05-29 01:01
err, looks like my comment got scrolled too far to the right.

Try this:

    echo -n \r'~      '\r' '\r

This should not print a tilde. Rerun the command, adding spaces after the tilde, until it does print - it should be at 79 spaces if COLUMNS is 80. Does that happen?

**Comment by corinnaerin** [comment] 2015-05-29 01:12
I sized my window at 38, but the breakpoint occurred at 35 rather than 37

**Comment by ridiculousfish** [comment] 2015-05-29 01:14
That's the problem then - if the line breaks early, then we'll never overwrite our line break character, so it will show up every time. What terminal emulator are you using? Is it good old cmd.exe?

**Comment by corinnaerin** [comment] 2015-05-29 01:17
No, I use the terminal in IntelliJ. I've also been testing using
C:/cygwin64/bin/fish.exe

**Comment by ridiculousfish** [comment] 2015-05-29 03:17
I tested with IntelliJ on OS X and it appears to be working correctly; I couldn't reproduce the problem.

**Comment by corinnaerin** [comment] 2015-05-29 03:25
As I mentioned in my original comment, the issue only occurs in IntelliJ on
Windows, not Linux or Mac

**Comment by ridiculousfish** [comment] 2015-05-29 03:29
Ahh, sorry I missed that

**Comment by ridiculousfish** [comment] 2015-05-29 03:31
I suspect https://youtrack.jetbrains.com/issue/IDEA-117552

**Comment by corinnaerin** [comment] 2015-05-29 06:20
Hmm ok I'll try that workaround when I get into the office tomorrow and let
you know if that fixes it.

**Comment by corinnaerin** [comment] 2015-05-29 19:46
Hmm I'm actually not sure that's the issue. My text isn't getting truncated, and when I do something like tail a log, the long lines are correctly wrapped to the next line. I actually can't replicate the issue their talking about, even when I change IntelliJ to use bash instead of fish.

I find it interesting that the problem is solved by shrinking the fish.exe window, but changing the size of IntelliJ has no effect.

**Comment by zanchey** [comment] 2015-06-19 08:06
I'm seeing this in cmd.exe as well, although only when there is no horizontal scrollbar (i.e. the width of the buffer is the same as the size of the window).

**Comment by alkemir** [comment] 2015-06-23 04:51
Same here, I am using Console2 and resizing does not help (but $columns gets changed)
If I do it in cmd.exe as zanchey tried, it appears at $COLUMNS=80 (no scrollbar), but disappears at $COLUMNS=79 (horizontal scrollbar).

**Comment by alkemir** [comment] 2015-06-23 05:38
Trying your command echo -n \r'~       '\r' '\r on Console2 (width 80 columns) prints a tilde at 79 spaces, but not at 78, I guess it is off by 1 in my case.

So I just replaced 
`abandon_line_string.append(screen_width - non_space_width, L' ');`
with 
`abandon_line_string.append(screen_width - non_space_width -1, L' ');`

And that fixed it for me. I also tried commenting the line that outputs the omitted_newline_character and that worked too. Not sure why, but this might help.

Cheers!

**Comment by ridiculousfish** [comment] 2015-06-23 06:05
@alkemir Are you using the console in IntelliJ too?

**Comment by alkemir** [comment] 2015-06-23 06:27
@ridiculousfish  No, I am using Console2. I think it is strange that we get different "off-by" for different consoles, but they might have their own temper... If you are using IntelliJ, you could try finding how much your console is off by (I am guessing 3 from corinnaerins experience) and then try my horrible patch.

**Comment by doxxx** [comment] 2015-11-08 15:00
I get this in ConEmu but not mintty.

**Comment by krader1961** [comment] 2016-03-17 21:24
Duplicate of issue #789.

**Closed** 2016-03-17 21:39 UTC
Labels: duplicate, windows
