### ISSUE TITLE
fish_config won't save settings

### ISSUE THREAD

**Issue by cperezabo** [fish-shell/fish-shell#4357] opened 2017-08-27 02:13 UTC
I am using version 2.6.0, installed via brew in macOS 10.12.6

fish_config is not saving settings, I select one of the available prompts, press "SET" button, but nothing changes

What can I do ?

**Comment by krader1961** [comment] 2017-08-27 03:07
Works for me. After you set the  prompt it can take up to 15 seconds before it is autoloaded again. Does `ls -l ~/.config/fish/functions/fish_prompt.fish` show a timestamp matching when you set the prompt with `fish_config`? It's also possible that `fish_config` is unable to create a file in that directory due to incorrect permissions. In fact I just confirmed that `fish_config` doesn't report anything after I've done `chmod 0 ~/.config/fish/functions` making it impossible to create a file in that directory. Which itself is something that should be fixed.

**Comment by faho** [comment] 2017-09-06 08:20
@cperezabo: Ping?

Have you checked the permissions for ~/.config/fish/functions/fish_prompt.fish?

**Comment by cperezabo** [comment] 2017-09-06 21:06
Hi again! Thanks to everyone.. 

The problem was that I had installed `omf` and it has symlinked the config file. After removing omf the symlink broked up and that's the reason why the config was always on default values and never saved!.

After removing the broken symlink, everything started working again!

Should I close the issue?

**Comment by zanchey** [comment] 2017-09-07 09:29
Thanks. You might consider taking this up with the oh-my-fish developers.

**Closed by zanchey** 2017-09-07 09:29 UTC

**Comment by rijans** [comment] 2022-02-09 16:52
> Hi again! Thanks to everyone..
> 
> The problem was that I had installed `omf` and it has symlinked the config file. After removing omf the symlink broked up and that's the reason why the config was always on default values and never saved!.
> 
> After removing the broken symlink, everything started working again!
> 
> Should I close the issue?

How do I remove the broken symlink? Can you/anyone help?

**Comment by dunstorm** [comment] 2023-02-26 13:13
Currently, facing this issue after upgrading fish to `3.6.0` using `brew`.

How do I find out what the issue is?
