### ISSUE TITLE
`~` expansion confusingly different from bash

### ISSUE THREAD

**Issue by ilyagr** [fish-shell/fish-shell#10794] opened 2024-10-17 18:22 UTC
I am not sure whether this is a question or a bug, but `~` expansion failed for me in a very confusing way. My system (MacOS) has a `printenv` command that makes the following easier to see:

## Bash 5.2.37:

(The behavior I expected)

```console
bash:~$ a=~ printenv a
/Users/ilyagr
bash:~$ env a=~ printenv a
/Users/ilyagr
```

## Fish
```console
🐟 a=~ printenv a
/Users/ilyagr
🐟 env a=~ printenv a
~
```

This caused me some confusion with https://github.com/astral-sh/uv/issues/8300.

I'm tested this on both a nightly fish and fish 3.7.1, they act the same.

Is this something that can be fixed?

**Update:** `dash` and `zsh` acts the same as `fish`, so perhaps this is a bashism. 😞 This can probably be closed, unless there's some helpful advice you can impart.

**Comment by faho** [comment] 2024-10-17 19:17
Duplicate of #1410

**Closed by faho** 2024-10-17 19:17 UTC
