### ISSUE TITLE
fish behaves badly when called on a directory

### ISSUE THREAD

**Issue by multixrulz** [fish-shell/fish-shell#8752] opened 2022-03-01 05:52 UTC
When I call fish on a directory, e.g.

```
fish .
```

fish endlessly prints "error: Unable to read input file: Is a directory" and cannot be killed with Control-C.  I would expect a single error to be printed, and then fish would exit.

System details:
fish version 3.3.1
Archlinux (Linux alpha 5.16.9-arch1-1 #1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux)
terminal: xfce4-terminal

`sh -c 'env HOME=$(mktemp -d) fish'` makes no difference

**Comment by faho** [comment] 2022-03-01 07:01
Duplicate of #8258

**Closed by faho** 2022-03-01 07:01 UTC
