### ISSUE TITLE
Xcode build can fail due to stale config.h from ./configure

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#1366] opened 2014-03-26 17:37 UTC
If `./configure` was run in the past, Xcode can fail to build due to stale configuration data after updating to ToT. Xcode should not be seeing the root config.h generated from `./configure`, but it is and it's giving it priority over `osx/config.h`.

---

Was: Xcode doesn't build with current master, due to missing `#define __packed`.

**Comment by zanchey** [comment] 2015-07-24 14:30
This might have been sorted out since #2208 was merged.

**Comment by ridiculousfish** [comment] 2015-07-24 17:57
I think it's not :(

**Comment by zanchey** [comment] 2015-07-29 14:08
I can't reproduce it, though - I have both config.h and osx/config.h, and the USER_HEADER_SEARCH_PATHS option in Xcode seems to force the latter to be picked first? Certainly putting `#error foo` in `config.h` breaks the autoconf build, but not the OS X build.

**Comment by ridiculousfish** [comment] 2015-07-29 19:45
Whoa, it does work. I can't explain why but I'm not complaining :+1: Thanks!

**Closed by ridiculousfish** 2015-07-29 19:45 UTC
Labels: bug
