### ISSUE TITLE
Indicate Remote Changesets in Mercurial Prompt

### ISSUE THREAD

**Issue by Siecje** [fish-shell/fish-shell#2858] opened 2016-03-25 16:02 UTC
The git prompt will indicate if there are changes on the remote server that you don't have locally.

```
#     upstream_ahead  (↑)
#     upstream_behind (↓)
```

This would be a nice addition to the Mercurial prompt.

**Comment by faho** [comment] 2016-03-25 16:33
Sure. Not having used hg much, what's the command to get this? Googling suggests `hg incoming` and `hg outgoing`?

Of course you could also open a PR :wink:.

**Comment by faho** [comment] 2016-04-04 10:43
Removing the easy-pick label because this doesn't seem so easy.

**Comment by danielmatz** [comment] 2016-08-19 15:07
The issue with putting hg information in a prompt is that each call to hg is relatively slow, because of the Python startup time.  So if we put together a sophisticated prompt using 2 or 3 hg calls, the lag to redraw the prompt will probably be pretty bad.

To get around this, I've been using the hg prompt extension:

https://bitbucket.org/sjl/hg-prompt/src

It lets you build up a prompt and only make 1 call to hg.  The problem is, it isn't part of the hg distribution, so a user would have to install it.

**Comment by faho** [comment] 2016-08-19 15:12
@danielmatz: Has that extension been updated? We tested it in #2869, and at that point it was woefully out of date and broken with current hg versions.

I mean, we might be okay with a hg extension (just because every other possibility is just waaaay too slow), but it would have to actually work.

**Comment by danielmatz** [comment] 2016-08-20 00:31
It is indeed fairly inactive, but someone seems to fix it whenever a new release of Mercurial breaks it.  I've been using it for a few years without any issue.

I looked through the other issue, and I'm not sure why it wasn't working for you...  I just tested it with Mercurial 3.6, and it worked fine.

**Comment by faho** [comment] 2016-08-20 19:30
@danielmatz: I still don't get any output for `hg prompt "{outgoing|count]"` (one of the calls in #2869). This is with Mercurial 3.**9**.

Or am I missing something (especially as someone not really familiar with hg)? I cloned the hg-prompt repo, added it to my hgrc. Then I modified a file, committed it and ran that hg prompt command. No output and no error status. Do I need to do anything else before this is expected to show something?

**Comment by Siecje** [comment] 2016-08-20 20:05
@faho Thanks for putting in so much effort considering you don't use Mercurial. :+1: 

Yeah you just clone the repo and then specify the path to the repo in .hgrc

**Comment by faho** [comment] 2016-08-20 20:19
So, should that have resulted in output? As far as I know, "outgoing" refers to the number of commits that should go into the upstream repo. Since I've cloned it (and because `hg push` seems to work that way), I assume that mercurial knows it's referring to the original repo. So since I've just made a commit and it's obviously not on bitbucket, shouldn't the "outgoing count" be "1"?

And if I didn't have a new commit, shouldn't that print "0"? Also, my `python` is 3.5.2, in case that matters.

@Siecje: If you do what I outlined, do you get any output?

**Comment by danielmatz** [comment] 2016-08-24 00:13
My prompt call is pretty complicated, since you want to get all of the prompt information in one call to hg.

But `{outgoing|count}` is part of the command I use, and it does indeed work for me.  I've even tested it with Mercurial 3.9, now, with success.

Note, however, that when there are no outgoing changesets, it doesn't print a 0.  This is to let you have parts of the prompt that are conditional.  For example,

```
hg prompt '{{outgoing|count} outgoing}'
```

would print `4 outgoing` if there were 4 outgoing changes.  And if there were no outgoing changes, it wouldn't print anything at all.

Also, the hg prompt is internally caching the incoming and outgoing values.  I have noticed that it occasionally takes a second call to get it to print what I want.  Did you try calling hg prompt more than once?

And FYI, Mercurial doesn't support Python 3, yet.  It should be using Python 2.

**Comment by faho** [comment] 2016-08-24 10:06
>Also, the hg prompt is internally caching the incoming and outgoing values. I have noticed that it occasionally takes a second call to get it to print what I want. Did you try calling hg prompt more than once?

Okay, now I did. For me it takes three calls to get _anything_ (i.e. to go from empty output to some output). But after I make a new commit, the `hg prompt` will not adjust. It'll be stuck at the old output, forgetting to invalidate the cache.

That means sometimes you'll get output, and sometimes that output may be outdated. And that you'll get only if you install a third-party tool. It doesn't appear usable.

>And FYI, Mercurial doesn't support Python 3, yet. It should be using Python 2.

Doesn't seem to make a difference. Well, mercurial itself is doing python2, but it seems hg prompt can also be executed with python3.

**Comment by krader1961** [comment] 2016-09-28 05:07
This is now more than a month old with the "needs-more-info" label. Do we in fact need more info for someone to implement the requested enhancement? The issue itself is now six months old. If no one cares enough to provide a solution I'm inclined to close it.

**Comment by faho** [comment] 2016-09-28 15:21
Yes, let's close until someone comes up with a usable solution.

**Closed by faho** 2016-09-28 15:21 UTC
Labels: enhancement, needs-more-info

**Comment by Siecje** [comment] 2016-09-28 15:48
What information is required?

**Comment by faho** [comment] 2016-09-28 16:14
@Siecje: Well, how to write a prompt function that indicates remote changesets always, that picks up changes, is fast enough (preferably to be run by default) and if possible requires no third-party tools.
