### ISSUE TITLE
`fish: Unknown command: fish_add_path` on launching fish

### ISSUE THREAD

**Issue by brandones** [fish-shell/fish-shell#8718] opened 2022-02-11 20:33 UTC
## Context

```console
~ $ fish --version                                                                                  12:28:07
fish, version 3.1.2
~ $ echo $version                                                                                   12:28:34
3.1.2
~ $ uname -a                                                                                        12:28:37
Linux arturo 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
~ $ lsb_release -a                                                                                  12:30:26
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
~ $ echo $TERM                                                                                      12:30:30
screen-256color
```

Running in terminal Termite version 14.

Reproduces with `sh -c 'env HOME=$(mktemp -d) fish'`.

## Problem

As of today, I get the following error any time I start a terminal (or execute `fish`). I have changed nothing regarding my fish configuration. Presumably a fish update broke things.

```console
fish - the friendly interactive shell
fish: Unknown command: fish_add_path
/usr/share/fish/vendor_conf.d/snapd.fish (line 3):                                                          
fish_add_path -aP $snap_bin_path                                                                            
^                                                                                                           
from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish                                                 
        called on line 294 of file /usr/share/fish/config.fish                                              
from sourcing file /usr/share/fish/config.fish                                                              
        called during startup                                                                               
/usr/share/fish/vendor_conf.d/snapd.fish (line 3):                                                          
fish_add_path -aP $snap_bin_path                                                                            
^                                                                                                           
from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish                                                 
        called on line 294 of file /usr/share/fish/config.fish                                              
from sourcing file /usr/share/fish/config.fish                                                              
        called during startup   
```

**Comment by faho** [comment] 2022-02-11 20:39
Duplicate of #8713

**Comment by faho** [comment] 2022-02-11 20:40
Already reported upstream: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1957948

Next time please check the issues for a duplicate, this has been reported twice in the last two days already

**Closed by faho** 2022-02-11 20:39 UTC
