### ISSUE TITLE
Command substitution as command

### ISSUE THREAD

**Issue by jney** [fish-shell/fish-shell#2427] opened 2015-09-25 19:37 UTC
while trying to use command substitution it seems when the first instruction is a command substitution it doesn't work : 
- `(some command) # doesn't work`
- `sh (some command) # works`

**Comment by ridiculousfish** [comment] 2015-09-25 19:47
What would you expect to happen with a  command substitution first?

**Comment by faho** [comment] 2015-09-25 22:15
What it seems to do in bash is do the command substitution and then run the result as a command. I.e.

```bash
 $ $(echo printf "%s\t%s\n" flounder catfish)
 flounder        catfish
```

I feel like this would need to be looked at in light of other forms of "non-literal commands", e.g. `some command | $PAGER` or `$EDITOR somefile` or `$HOME/bin/somecommand` (yes, variables are the only thing I can think of). I believe we currently don't do that because it makes it hard to reason about the line for e.g. completions and highlighting.

**Comment by ridiculousfish** [comment] 2015-09-28 21:34
@jney ping - what are/were your expectations here?

**Comment by jney** [comment] 2015-09-28 22:14
sorry i missed github notifications.
using `npm` your library binaries are usually store in `node_modules/.bin` and `npm` provides a facility to call it, ie: using bash : `$(npm bin)/gulp` i guessed using fish it would be as simple as `(npm bin)/gulp` but it doesn't work.
i'm sure there are a lot of other use cases where using command substitution at first expression would be a good thing

**Comment by faho** [comment] 2015-09-28 22:59
See also #154. I haven't found an issue requesting the pure `$PAGER file` form.

**Comment by faho** [comment] 2017-01-07 16:22
Closing as duplicate of #154, since the proposed changes there should also fix this.

**Closed by faho** 2017-01-07 16:22 UTC
Labels: enhancement
