### ISSUE TITLE
Pager strangeness with certain items not bolding only when selecting by up/left arrow.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3507] opened 2016-10-28 22:25 UTC
This is a strange one that's been around for a while that I haven't reported until now.

See the screen recording, keep eye on "autoscan.log" for example: https://drive.google.com/file/d/0B9nS3wSv15QjNEduMDhTbUJfc2c/view

Certain filename completions (always the same ones?) will not bold when traversing back up the list through up arrow or when moving leftwards through the list with the left arrow. They highlight correctly when traversing forwards with the down/right arrows.

**Comment by floam** [comment] 2016-10-28 22:36
It may not be specific to the filenames, but the pager positions. Brief testing shows this is at least often happening for the item at column 1 row 2, at least when there's an even number of columns.

**Comment by floam** [comment] 2016-10-28 22:45
There is also strangeness after pushing down to the second page of completions. I'll try to make a screencast later.

**Comment by floam** [comment] 2019-04-01 06:21
Still happens today. Here's a GIF. Keep your eye on the white bold text in the pager status line ("row n of n") in the first part of the video, then the selected filenames bolding or not bolding in the second part of the video.

![bold](https://user-images.githubusercontent.com/291142/55307203-af10d480-540b-11e9-809e-d09cdbe0c996.gif)

**Comment by faho** [comment] 2023-09-30 13:39
Duplicate of #9617

**Closed by faho** 2023-09-30 13:39 UTC
Labels: bug
