### ISSUE TITLE
fish2.5.0 "Unknown command '--description'" in function

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3888] opened 2017-03-11 12:43 UTC
This only appears in 2.5, not in 2.4

Try this:

alias gg "ga; and gc; and gu"

then run `gg',
we got:
fish: Unknown command '--description'
in function 'gg'
        called on standard input
.....

**Comment by faho** [comment] 2017-03-11 13:20
Duplicate of #3860, which should be fixed in 2.6.0.

Of course I still strongly recommend defining anything more complicated than `$command --$option` as a proper function.

**Closed by faho** 2017-03-11 13:20 UTC
