### ISSUE TITLE
Standard colors no longer behave as expected

### ISSUE THREAD

**Issue by sagebind** [fish-shell/fish-shell#3555] opened 2016-11-15 18:25 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: OS X / iTerm2

After upgrading to 2.4.0, I've noticed that colors don't behave like they did in 2.3.1. It _seems_ like a bug to me, but it might be intended behavior?

## Reproduction steps
1. Install Fish 2.4.0
2. Install some colorful prompts

## Results
I ran the same commands in Fish 2.3.1 and 2.4.0, and attached screenshots of how the colors differ. Same OS, same terminal:

### 2.3.1
![fish-2 3 1-colors](https://cloud.githubusercontent.com/assets/2192863/20317929/ce92a4d4-ab2d-11e6-998d-57a86faa8faf.png)

### 2.4.0
![fish-2 4 0-colors](https://cloud.githubusercontent.com/assets/2192863/20317936/d83780ea-ab2d-11e6-9640-420970dab702.png)

The prompt demoed in the above screenshots is the default Oh My Fish theme (https://github.com/oh-my-fish/theme-default), which uses the standard color variables, like so:

```fish
set_color $fish_color_quote
# ...
set_color $fish_pager_color_progress
```

Is this an expected change? Should the values of `$fish_color_*` not be relied on?

**Comment by faho** [comment] 2016-11-15 20:02
What are the color variables set to? In particular $fish_pager_color_progress?

@floam did a bunch of work in our color system, so he might be able to help here.

I can already say though that $fish_pager_color_progress isn't meant for a success indicator. We don't have a variable for just that, but $fish_color_status might be a better match.

**Comment by sagebind** [comment] 2016-11-15 20:06
Looks like it was set to `cyan` on 2.3.1 and is now set to `brwhite --background=cyan` by default.

**Comment by faho** [comment] 2016-11-15 20:09
This looks like the default setting - __fish_config_interactive has this:

```fish
    if not set -q __fish_init_2_39_8
        # snip
        set -q fish_pager_color_progress
        or set -U fish_pager_color_progress brwhite --background=cyan
        # snip
        set -U __fish_init_2_39_8
    end
```

In other words, it's possible when you first started 2.4.0 $fish_pager_color_progress wasn't set, so it got set to the default.

This prompt uses that color for something, and it's shown correctly. What remains to be seen is why this color got set? How did you set the colors before? Is it possible that this variable just was never set? The OMF prompt defaults to cyan but doesn't set the variable, so that would cause precisely what you are seeing.

**Comment by floam** [comment] 2016-11-15 20:09
Yes, I did change that one. I just thought it looked better now that bright colors could be more safely used.

**Comment by faho** [comment] 2016-11-15 20:13
Soo.... @sagebind: Assuming you never had 2.3.1 or earlier installed, this is behaving as intended. In case you like the old color better, do `set fish_pager_color_progress cyan`.

If you did have 2.3.1 installed, it's a bit weird that this change was triggered. Do you have more than one fishd* file in ~/.config/fish?

**Comment by floam** [comment] 2016-11-15 21:50
I'm sorry for the trouble caused here - but there's not really any particular reason to assume that the theme components will be any particular color. You're going to get different behavior depending on how the user has configured the pager status bar - or if we change it.

**Comment by sagebind** [comment] 2016-11-15 22:51
Not major trouble, I just found it odd that the colors had all changed which affected several Oh My Fish themes that were using the Fish color variables. The idea of said themes was to use the same color scheme as the built-in parts of Fish.

@faho This issue isn't mine really, I'm just relaying it from one of the Oh My Fish users that reported it. I've had Fish installed for much longer than since 2.3.1. The screenshots above were taken from brand new Docker containers with nothing in them but Fish, similar to a user who just downloaded Fish 2.4.0 and was surprised that it looked different (ugly IMHO) compared to the screenshots we had made.

**Comment by krader1961** [comment] 2016-11-15 22:58
@sagebind: I don't think the 2.4.0 release is changing the colors. There was a short period when building from git head included code to save the current color scheme and replace it with equivalent but "better" colors. I thought that code had been backed out before the 2.4.0 release was created. So I'm guessing your user ran one of those interim builds when the code was in flux. I certainly noticed it and was rather annoyed :smile: But after that I just restored my color scheme from the backup file that was in *~/.config/fish* and they weren't changed again.

**Comment by sagebind** [comment] 2016-11-15 23:00
@krader1961 I don't think that is the case. As I said, it can be reproduced by creating a brand new Docker container, compiling Fish 2.4.0 from source, and running it for the first time.

**Comment by krader1961** [comment] 2016-11-15 23:04
I misunderstood. Yes, I believe that as part of revamping the `set_color` logic @floam also changed some of the defaults and that was intentional. Whether or not it was a good idea is subject to debate and doesn't have a black and white answer.

**Comment by sagebind** [comment] 2016-11-15 23:07
I think the solution for _my_ reason of raising this issue would be to either:

- Use different `$fish_*` variables that have more preferred default colors for the user themes in question.
- Use a specific color (e.g. `cyan`) in user themes to ensure themes always appear the same regardless of Fish version or color scheme.

**Comment by floam** [comment] 2016-11-15 23:18
I think to be able to do what is being attempted best, we'd have to have defined our colors in more general terms - `fish_color_good` - `fish_color_highlighted` - `fish_color_emphasis` - etc. Some of our colors like the error color can probably safely be used this way. But the pager progress color is rather specific.

**Comment by krader1961** [comment] 2016-12-12 18:58
I'm going to close this because the original question has been answered. If anyone has a concrete proposal for improving how colors are defined and used by themes please open an enhancement request. Keep in mind that whatever we do needs to be backward compatible.

**Closed by krader1961** 2016-12-12 18:58 UTC
Labels: question

**Comment by cbsghost** [comment] 2017-07-22 22:55
I wrote a plugin to solve the problem temporary.

https://github.com/cbsghost/fish-legacycolor
