### ISSUE TITLE
Certain loops do not run if $status != 0

### ISSUE THREAD

**Issue by teresaejunior** [fish-shell/fish-shell#6165] opened 2019-10-03 15:24 UTC
Weird behaviour in fish 3.0.2. I can only run certain loops if `$status` from previous command is equal to `0`.

    $ sh -c 'env HOME=$(mktemp -d) fish' # try on a clean profile
    ~> false
    ~> while :; echo 1; sleep 1; end # $status was 1, loop skipped
    ~> while :; echo 1; sleep 1; end # $status was 0, now it works
    1
    ^C⏎
    ~> while :; echo 1; sleep 1; end # $status was 130, loop skipped
    ~> while :; echo 1; sleep 1; end # $status was 0, now it works
    1
    ^C⏎

System info:

    ~> fish --version
    fish, version 3.0.2
    ~> echo $version
    3.0.2
    ~> uname -a
    Linux laptop 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    ~> echo $TERM
    xterm-256color

**Comment by faho** [comment] 2019-10-03 17:35
So, I know we've had some changes related to this in master, including 4530a4100437276afef117c113bdedb1080a877c, which ends up fixing this.

I would love to know which issue that discussion was in but it doesn't connect to any - @mqudsi if you happen to know that'd be nice.

Conceptually, previously `:` did absolutely nothing, not even modify $status. Now it is effectively the same thing as `true`, which matches bash's behavior. And because it didn't modify $status, `while` executed the condition, checked $status, saw that it was still false...

Personally I consider this an anti-pattern. Just use `true` if you want something that's always true. `:` is now just an obtuse spelling of it.

Anyway, closing as a duplicate of that unknown issue.

**Closed by faho** 2019-10-03 17:35 UTC

**Comment by mqudsi** [comment] 2019-10-07 18:55
This actually had nothing to do specifically with `:`, if I recall correctly. I refactored some things and broke a test that explicitly expected an empty function to *not* alter `$status`; I remember opening a PR or making some comments here on GitHub... I *think* it may have been @zanchey that agreed with my request to change this "specified" (via tests) behavior. I did compare it to bash at the time and looked it up in the POSIX reference, I believe.

With regards to `:` - bash, which does not have the same quirk of processing line continuations starting with comments but followed by another continuation that fish does, doesn't offer a nice way to comment in-band a multiline command, so there `:` is used along the lines of batch (aka dos) `REM`, the difference between `:` and `true` is not technical but rather semantic, e.g.

```bash
foo bar && \
: now we need to do something else but only if that succeeded && \
something_else
```

which would read very awkwardly if written with `true`:

```bash
foo bar && \
true now we need to do something else but only if that succeeded && \
something_else
```

---

(There was *another* change which was made in the 3.x line which was to have `while` set `$status` to an actually useful value, which changed the result of functions ending in `while` loops, but that does not seem to be related to this PR.)

**Comment by zanchey** [comment] 2019-10-17 14:16
I didn't even know we had a `:` function until the change went in, so I don't think it was me - sorry!

**Comment by mqudsi** [comment] 2019-10-28 17:51
No, I meant discussing whether or not an empty function should set the status. As mentioned, it was actually unrelated to `:`.

**Comment by zanchey** [comment] 2019-10-30 09:59
Oh, right, I don't remember that either.
