### ISSUE TITLE
commandline --replace some_text doesn't seem to work in a fish completion

### ISSUE THREAD

**Issue by gsalsero** [fish-shell/fish-shell#9710] opened 2023-04-04 17:12 UTC
`fish --version`
fish, version 3.6.1

`uname -a`
Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64

`echo $TERM`
xterm-256color
(iTerm2 Build 3.4.19)

I am having trouble using `commandline --replace some_text` in a fish completion. Below is a simple completion that demonstrates the problem. 

```fish
function __my_custom_complete
    commandline --replace some_text
end

complete -c third-party-command -f -a '(__my_custom_complete)'
```

When I have the following command line:

`$> third-party-command `

It's not replaced with some_text when I press the `TAB` key.

It seems to work from the terminal although I'm not clear if this is a valid test. 
I start with the following:

`$> commandline --replace some_text`

Press `ENTER` and I get this

`$> some_text`

On another Mac I am running `fish version 3.3.1` and this completion works fine.

**Comment by faho** [comment] 2023-04-04 17:16
Duplicate of #663

**Closed by faho** 2023-04-04 17:16 UTC

**Comment by faho** [comment] 2023-04-04 17:18
In short: Replacing the commandline inside of completions isn't supposed to work, and it isn't something we want to support.

Instead, I suggest working *with* the completion system by just printing what you want to complete.

Alternatively, if you want to replace a short thing with a long thing, like e.g. `git s` becoming `git status`, look into [abbreviations](https://fishshell.com/docs/current/interactive.html#abbreviations).

**Comment by gsalsero** [comment] 2023-04-05 02:02
Thanks that make sense., For posterity, I ended up just creating a function that does what I needed. This third-party command I'm using has various options and I wanted "nicknames" for some of the most used combinations. I moved the functionality to replace the command line into a function with the same name as the command so I can continue to use tab-completion. 

```fish
function dict
    set -l -- first -a -b something -c another
    set -l -- second -a -b something_else -f
    $argv
end

function get --no-scope-shadowing -a __key
    echo $$__key
end

function third-party-command
    set key (string replace --all - _ $argv[1])
    if test -n "$key"
        set -l value (dict get $key)
        if test -n "$value"
            set -l args (string split " " -- $value)
            echo "calling: third-party-command $value $argv[2..-1]"
            command third-party-command $args $argv[2..-1]
            return
        end
    end
    command third-party-command $argv
end

```
