### ISSUE TITLE
High CPU usage after just showing a curl 

### ISSUE THREAD

**Issue by stirp** [fish-shell/fish-shell#7914] opened 2021-04-09 12:38 UTC
hi,
I'm running into a situation that always get high CPU usage. my fish version is 3.2.1, and reproduce the annoying problem even after running   sh -c 'env HOME=$(mktemp -d) fish'.

Just copy the following into fish and do nothing would simply cause the problem:

~~~bash
curl 'https://www.test.com/FHH/EM1HNCRM/API/v1/object/ActiveRecordObj/controller/WebDetail?traceId=E-E.78532.1000-12936408&_fs_token=DMHcCZOuPJKjOpHXDIqqDZ5YBJWnDpajPc9aCZ8vOZHcDcCu' \
          -H 'authority: www.ceshi112.com' \
          -H 'x-trace-id: 78532_1000_1617796056198:257' \
          -H 'accept: application/json, text/javascript, */*; q=0.01' \
          -H 'x-requested-with: XMLHttpRequest' \
          -H 'accept-language: zh-CN,zh-TW;0.9,en;0.8' \
          -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.54' \
          -H 'content-type: application/json; charset=UTF-8' \
          -H 'origin: https://www.ceshi112.com' \
          -H 'sec-fetch-site: same-origin' \
          -H 'sec-fetch-mode: cors' \
          -H 'sec-fetch-dest: empty' \
          -H 'referer: https://www.ceshi112.com/XV/Home/Index' \
          -H 'cookie: Hm_lvt_06d5233541e92feb3cc8980700b1efa6=1617358013; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%22178920cc2512be-03aa28026248a6-1d4e3717-2073600-178920cc252892%22%2C%22props%2%3A%7B%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%7D%7D; guid=d607e58f-969f-fe55-ff26-b178920cc2b6; mirrorId=0000; _ga=GA1.2.930868514.1617358013; enterprise=78532; lang=h-CN; Hm_lpvt_06d5233541e92feb3cc8980700b1efa6=1617742845; EPXId=c54359f23ecb4a2e926b2536878e54d9; fs_token=DMHcCZOuPJKjOpHXDIqqDZ5YBJWnDpajPc9aCZ8vOZHcDcCu; FSAuthX=0G7lnDxCvm80000gAgyFbXzqWd1kaPlK93IuYBoebT6pFZsKFHJuw9z3GvzwCHuh2yzNJFekn9TurCw1iY0XeQjfThB9Hnc3h4rrQf076pOyfwqzxy2ydwpAy2bAe0HmKFCm5V8dyCaclkQsqYZykwo2HRVzVy90WwmDE6CxtiPjBz9nc5E1eaBQHw4HoFozIyVGSDoIEELsFDQfAyG8rdehuG3Zl8odAQkK0Q1; FSAutXC=0G7lnDxCvm80000gAgyFbXzqWd1kaPlK93IutYBoebT6pFZsKFHJuw9z3GvzwCHuh2yzNJFekn9TurCw1iY0XeQjfThB9Hnc3h4rrQf076pOyfwqzxy2ydwpAy2bAe0HmKFCm5V8dyCaclkQsqYZykwo2HRVzVy90WwmDE6CxtiPjBz9nc5E1eaBQHw4HoFozIyVGSDIEELsFDQfAyG8rdehuG3Zl8odAQkK0Q1; sso_token=db8aac79-df93-4456-a672-681cf968dd81; JSESSIONID=C0350B42C8CA8E33002B29131E8F99E7' \
          --data-raw '{"layoutVersion":"V3","objectDataId":"60700342d617520001514401","objectDescribeApiName":"ActiveRecordObj","fromRecycleBin":false,"management":false,"serializeEmpty":false}' \
          --compressed
~~~

Running sample [PID] 5 -file myfishsample.txt, I noticed stack like below:

~~~
    4689 Thread_79865
      4689 thread_start  (in libsystem_pthread.dylib) + 15  [0x7fff2063447b]
        4689 _pthread_start  (in libsystem_pthread.dylib) + 224  [0x7fff20638950]
          4689 thread_pool_t::run_trampoline(void*)  (in fish) + 14  [0x106f11442]
            4689 thread_pool_t::run()  (in fish) + 243  [0x106f11187]
              4689 std::__1::__function::__func<debounce_t::perform_impl(std::__1::function<void ()>, std::__1::function<void ()>)::$_0, std::__1::allocator<debounce_t::perform_impl(std::__1::function<void ()>, std::__1::function<void ()>)::$_0>, void ()>::operator()()  (in fish) + 22  [0x106f13188]
                4689 debounce_t::impl_t::run_next(unsigned long long)  (in fish) + 251  [0x106f12079]
                  4689 std::__1::__function::__func<iothread_trampoline_t<std::__1::function<(anonymous namespace)::highlight_result_t ()>, reader_data_t::super_highlight_me_plenty()::$_2, (anonymous namespace)::highlight_result_t>::iothread_trampoline_t(std::__1::function<(anonymous namespace)::highlight_result_t ()> const&, reader_data_t::super_highlight_me_plenty()::$_2 const&)::'lambda'(), std::__1::allocator<iothread_trampoline_t<std::__1::function<(anonymous namespace)::highlight_result_t ()>, reader_data_t::super_highlight_me_plenty()::$_2, (anonymous namespace)::highlight_result_t>::iothread_trampoline_t(std::__1::function<(anonymous namespace)::highlight_result_t ()> const&, reader_data_t::super_highlight_me_plenty()::$_2 const&)::'lambda'()>, void ()>::operator()()  (in fish) + 42  [0x106f467c0]
                    4689 std::__1::__function::__func<get_highlight_performer(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, bool)::$_8, std::__1::allocator<get_highlight_performer(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, bool)::$_8>, (anonymous namespace)::highlight_result_t ()>::operator()()  (in fish) + 250  [0x106f44594]
                      4689 highlight_shell(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::vector<highlight_spec_t, std::__1::allocator<highlight_spec_t> >&, operation_context_t const&, bool)  (in fish) + 180  [0x106ef48bd]
                        4689 highlighter_t::highlight()  (in fish) + 607  [0x106ef2f45]
                          4689 is_potential_path(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::vector<std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >, std::__1::allocator<std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > > > const&, operation_context_t const&, unsigned int)  (in fish) + 1498  [0x106ef135e]
                            4689 wbasename(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&)  (in fish) + 62  [0x106f590dc]
                              4689 str2wcstring(char const*)  (in fish) + 21  [0x106eb8709]
                                4689 _platform_strlen  (in libsystem_platform.dylib) + 18  [0x7fff2067a5d2]
~~~
[myfishsample.txt](https://github.com/fish-shell/fish-shell/files/6285684/myfishsample.txt)

It seems the highlight function causing the problem.

Other infomations may useful:

MacOS 11.2.1,
pyhton version is Python 2.7.16

**Comment by faho** [comment] 2021-04-09 13:27
Duplicate of #7837

**Comment by faho** [comment] 2021-04-09 13:28
Please upgrade to 3.2.2.

**Closed by faho** 2021-04-09 13:27 UTC

**Comment by stirp** [comment] 2021-04-09 18:02
Cool!
