### ISSUE TITLE
Way to manually apply syntax coloring

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#5114] opened 2018-07-26 11:19 UTC
I have a function which prepends `sudo ` to the commandline and then runs `commandline -f execute`. This is a simplified version:
```
function __fish_plz_bind
    set -l cmdln_old (commandline)
    set -l cmdln_new 'sudo '"$cmdln_old"
    commandline -r $cmdln_new
    commandline -f execute
end

bind \ep __fish_plz_bind
```
This all works fine but the syntax highlighting of the commandline isn't updated after prepending sudo. Is there a command to manually update syntax highlighting that I could add to the function?

fish, version 2.7.1 on ArchLinux

**Comment by ridiculousfish** [comment] 2018-07-27 07:10
None yet. The hope is to express this stuff through declarative parsing (e.g. argparse based) someday.

**Comment by floam** [comment] 2019-01-22 00:39
I think this is the same bug as #4439.

**Comment by faho** [comment] 2019-03-14 19:58
Duplicate of #4439

**Closed by faho** 2019-03-14 19:58 UTC
Labels: enhancement
