### ISSUE TITLE
Korean in macOS breaks command suggestion and completion

### ISSUE THREAD

**Issue by boltlessengineer** [fish-shell/fish-shell#8974] opened 2022-05-26 10:29 UTC
```fish
> fish --version
fish, version 3.4.1
> echo $version
3.4.1
> sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
> echo $TERM
xterm-256color
```

Hi! I'm been using fish-shell for almost a year now, and I really enjoy using it.
But when I input Korean(Hangul texts) to completely handle all my tasks in fish, fish doesn't seem to handle Korean texts properly.

https://user-images.githubusercontent.com/60088301/170421053-20bd4a2c-ab7f-44e9-ba55-3a2cd1fff644.mov

1. tab-completion works in empty string. But there are extra spaces behind. If I remove some auto-completed texts, the auto-completion starts to break. Enter with some spaces removed behaves like I removed some Korean texts('한글폴더' -> '한글폴ㄷ').
2. Just typing Korean text my self works fine, but fish highlights the typed folder name to red (even `cd` works well).
3. tab-completion doesn't work with my typed text.

expectation :
```
'한글<tab>|' -> '한글폴더|'
```

Every thing works fine if I make the folder with `mkdir`.
But if I name the folder in macOS Finder, the problem occurs.

I have found that there has been a similar issue(#5729) in the past, but I'm not sure if this is the same issue to that.

Edit : More specific explain about what's happening
Edit2 : More specific explain about the situation (sorry for frequent edits, I'm not used to making new issues)

**Comment by boltlessengineer** [comment] 2022-05-26 10:32
I also check japanese(romanji), but it works fine.

**Comment by faho** [comment] 2022-05-26 11:01
One possibility is that this is, at least in part, a terminal rendering issue.

What happens if you copy `한글폴더|` out of your browser and copy it into a terminal running fish? Does the empty space appear?

Another is that macOS filesystem handling is awkward - it uses unicode normalization, which we do not currently support. So we check for a directory called `한글폴더|`, but the real directory has a name *equivalent* to that - e.g. it has the same characters, but in a decomposed. See #474

**Comment by boltlessengineer** [comment] 2022-05-26 11:52
Thanks for the fast reply.

> What happens if you copy `한글폴더|` out of your browser and copy it into a terminal running fish? Does the empty space appear?

Empty space doesn't show when I paste `한글폴더` to terminal (I put `|` to describe the cursor position).
Direct typing works fine. I think this is not an rendering issue.

> Another is that macOS filesystem handling is awkward - it uses unicode normalization, which we do not currently support. So we check for a directory called `한글폴더|`, but the real directory has a name _equivalent_ to that - e.g. it has the same characters, but in a decomposed or precomposed form (can't recall which they chose). See #474

Yes, macOS filesystem handling (unicode normalization) seems to be the problem. zsh works fine, bash and fish doesn't.

Didn't know that fish doesn't supports unicode normalization. I set unicode normalization option in iterm2 to NFC because the Korean file/folder names (named in Finder) breaks in None option.

**Comment by faho** [comment] 2022-05-26 12:02
>Yes, macOS filesystem handling (unicode normalization) seems to be the problem. zsh works fine, bash and fish doesn't.

Okay, looks like a duplicate of #474 then.

**Closed by faho** 2022-05-26 12:02 UTC
