### ISSUE TITLE
Enable true color support in NeoVim terminal

### ISSUE THREAD

**Issue by blahgeek** [fish-shell/fish-shell#4615] opened 2017-12-21 07:50 UTC
In #2600, fish disabled true color support in NeoVim terminal. It seems that current version of NeoVim can display true color from fish correctly (if I set $fish_term24color manually). The workaround introduced to fix that issue may be reverted if someone can confirm this.

My envs:

- fish, version 2.7.0
- NVIM v0.2.2
- $TERM = xterm-256color (qterminal)

**Comment by faho** [comment] 2017-12-21 12:14
Already enabled by 13fd9be1d9c5055ab142de6ddf9019b5a48a8656, which will be in the upcoming 3.0 release.

**Comment by faho** [comment] 2017-12-21 12:15
Which would make this a duplicate of #2792.

**Closed by faho** 2017-12-21 12:14 UTC

**Comment by blahgeek** [comment] 2017-12-21 14:10
Oh, thanks, I should have searched it more :P
