### ISSUE TITLE
Invalid commands result with warning messages from pacman

### ISSUE THREAD

**Issue by valters-tomsons** [fish-shell/fish-shell#7899] opened 2021-04-03 17:16 UTC
Hi!

I have noticed that for a few months now, whenever I run any "unknown commands", there are some mysterious warning messages from [`pacman`](https://wiki.archlinux.org/index.php/Pacman). 

![Screenshot_2021-04-03-37_854x268](https://user-images.githubusercontent.com/4209639/113485859-71425d00-94b8-11eb-8f28-88269f6f9c82.png)

Fish version: 3.2.1
Operating system: Arch Linux 5.11.11
Terminal: [`st`](https://st.suckless.org/) [fork](https://github.com/valters-tomsons/st), happens also gnome-terminal 

I have tried fish without third-party customizations, resulting with same behavior.

**Comment by faho** [comment] 2021-04-03 17:32
Yes, this means fish told pacman to figure out which package contains the command but you don't have the database downloaded.

We're disabling this particular thing in 3.2.2, so I'm closing this as a duplicate of #7841

**Closed by faho** 2021-04-03 17:32 UTC
