### ISSUE TITLE
the fish U+23CE character can't be encoded in LANG=zh_CN.GBK@cjknarrow

### ISSUE THREAD

**Issue by gMan1990** [fish-shell/fish-shell#3503] opened 2016-10-28 04:30 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_: fish, version 2.3.1

**OS/terminal used**: 
OS: Windows 7 Professional with Service Pack 1 Build 7601 x64 zh-cn
terminal: D:\Cygwin\cygwin64\bin\mintty.exe

locale
LANG=zh_CN.GBK@cjknarrow
LC_CTYPE="zh_CN.GBK@cjknarrow"
LC_NUMERIC="zh_CN.GBK@cjknarrow"
LC_TIME="zh_CN.GBK@cjknarrow"
LC_COLLATE="zh_CN.GBK@cjknarrow"
LC_MONETARY="zh_CN.GBK@cjknarrow"
LC_MESSAGES="zh_CN.GBK@cjknarrow"
LC_ALL=

Talk about the the issue here. 
![19af790e-9d02-11e6-8eff-95dfd1c4ed8a](https://cloud.githubusercontent.com/assets/5050994/19795031/4df33702-9d0a-11e6-8685-04367d5f3841.png)

**Comment by krader1961** [comment] 2016-10-28 05:25
I happen to have a MS Windows 7 system with Cygwin and Fish installed. I can reproduce this problem by building from git head (`make fish`) and running

```
env LANG= zh_CN.GBK@cjknarrow ./fish
```

The problem does not occur with `LANG=en_US.UTF-8` in Cygwin inside MS Windows 7. It also does not occur with `LANG=zh_CN.utf8` or `LANG=zh_CN.utf8@cjknarrow`.

This problem is due to the locale not supporting Unicode code points. Specifically, the locale of the O.P. uses the GB18030 encoding standard.

I am interested in how others feel about this but I vote that we not add support for non-Unicode locales. Adding that support might have made sense a decade ago. Today that added complexity cannot be justified in my opinion.

**Comment by faho** [comment] 2016-10-28 09:43
@gMan1990: Any particular reason you are using this encoding? Would utf8 not be strictly better?

@krader1961: Can we just not skip printing the return character in this case?

**Comment by gMan1990** [comment] 2016-10-28 10:23
@faho Windows 7 Professional with Service Pack 1 Build 7601 x64 zh-cn
**the system lang is zh-cn zh-cn zh-cn zh-cn zh-cn zh-cn zh-cn**
if I set like this:
![qq 20161028181607](https://cloud.githubusercontent.com/assets/5050994/19803452/5abc2f8a-9d3b-11e6-9d93-79c6650b2bc3.png)
output will be like this
![qq 20161028182150](https://cloud.githubusercontent.com/assets/5050994/19803478/7c0e4376-9d3b-11e6-89c1-9a8894f3e15c.png)

**Comment by krader1961** [comment] 2016-10-28 20:53
> Can we just not skip printing the return character in this case?

We'd have to make it conditional on `wctomb()` failing for that character. What we currently do is check if we're in a ASCII or ISO 8859 locale by seeing if `wcwidth()` returns one. If we are we don't use the fancy Unicode return char. Otherwise we assume we're in a Unicode enabled locale.

I'm pretty confident this is a bug in the Cygwin locale subsystem. That's because [GB18030](https://en.wikipedia.org/wiki/GB_18030) is a Unicode transformation standard. That is, it defines how to convert Unicode code points to a multibyte encoding and vice versa. It's like UTF-8 but uses a different algorithm for doing the encoding/decoding. So it should be possible to use the U+23CE code point that gives a fancy return symbol. I'm not home right now but I suspect that on Cygwin the configure script is defining `HAVE_BROKEN_WCWIDTH`. That causes us to use our fallback implementation which says that is in fact a multibyte char. But we still use the system provided `wctomb()` which says in effect "sorry charlie I can't encode that code point".

Before we implement any workarounds we need to answer a few questions. Starting with whether wcwidth() is broken on Cygwin. Also, why does wctomb() fail to convert U+23CE?

Sadly we'll have to do something about this since GB18030 is a national standard that China requires all software sold in the country to support. While we're under no obligation to support GB18030 since we're not selling fish I think everyone would agree we want fish to be usable by people in China.

P.S., When I said earlier the "problem is due to the locale not supporting Unicode code points" that was incorrect.

**Comment by krader1961** [comment] 2016-10-29 06:23
From *src/fallback.cpp*:

```
// Big hack to use our versions of wcswidth where we know them to be broken, which is
// EVERYWHERE (https://github.com/fish-shell/fish-shell/issues/2199)
#ifndef HAVE_BROKEN_WCWIDTH
#define HAVE_BROKEN_WCWIDTH 1
#endif
```

And that symbol isn't defined anywhere else. Including the output of `./configure`. So we always assume we're in a broken wcwidth environment and use our non-broken implementation. Which assumes a sane Unicode implementation. The output of `git blame src/fallback.cpp` says this behavior dates back to 2012 and probably earlier.

We need to figure out if we should still be always using our fallback implementation for wcwdith().

**Comment by krader1961** [comment] 2016-10-29 06:33
See also issue #2199. I think we should explore how fish behaves if we don't always force the use or our fallback `wcswidth()` function.

**Comment by krader1961** [comment] 2016-10-30 03:23
Using the system provided `wcwidth()` function rather than our fallback makes no difference. I've confirmed the problematic locale causes both `wctomb()` and `wcrtomb()` (the latter is the function fish actually uses) to return -1 for U+23CE but 3 for a normal UTF-8 locale. Running `env LC_ALL=zh_CN.GB18030 fish` on macOS 10.12 (Sierra) produces the same `fish: Wide character 9166 has no narrow representation` diagnostic.

So despite my understanding of the GB181030 standard that particular Unicode code point cannot be encoded to the appropriate multi byte sequence. Too, upon further reflection I think the current test of the `fish_wcwidth()` return value to decide if we can use this Unicode code point is fundamentally flawed. We should instead do as @faho has suggested and test whether it can actually be encoded using the current locale.

**Comment by krader1961** [comment] 2016-10-30 04:56
I still think we should stop using our `fish_wcwidth()` implementation but that is orthogonal to this issue. So I'm not going to make that change as part of resolving this issue. I think we should limit fixing this to the change least likely to cause problems. Which means empirically testing whether the U+23CE code point can be encoded.

**Closed** 2016-11-07 21:23 UTC
Labels: bug
