### ISSUE TITLE
fish should silently ignore unmapped keys during startup

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4431] opened 2017-09-27 04:41 UTC
If `fish` is configured to use a certain key bindings that are available under the usual `$TERM` but is started under a different `$TERM`, it will spew that output to the terminal.

For example, I normally use fish almost exclusively under `xterm-256color`, but sometimes the shell is spawned from a script or similar and I run into this:

```fish
mqudsi@ZBook ~> ssh mqudsi@192.168.1.103 'true'
bind: Key with name 'right' does not have any mapping
bind: Key with name 'ppage' does not have any mapping
bind: Key with name 'npage' does not have any mapping
bind: Key with name 'btab' does not have any mapping
bind: Key with name 'up' does not have any mapping
bind: Key with name 'f1' does not have any mapping
bind: Key with name 'right' does not have any mapping
bind: Key with name 'dc' does not have any mapping
```

By checking what that script configuration sets `$TERM` to, I can see that it's set to `su`:

```fish
mqudsi@ZBook ~> ssh mqudsi@192.168.1.103 'env'
bind: Key with name 'right' does not have any mapping
bind: Key with name 'ppage' does not have any mapping
bind: Key with name 'npage' does not have any mapping
bind: Key with name 'btab' does not have any mapping
AUTOJUMP_ERROR_PATH=/usr/home/mqudsi/.local/share/autojump/errors.log
AUTOJUMP_SOURCED=1
BLOCKSIZE=K
GOPATH=/usr/home/mqudsi/go
HOME=/home/mqudsi
LC_CTYPE=en_US.UTF-8
LOGNAME=mqudsi
MAIL=/var/mail/mqudsi
OSTYPE=freebsd11.0
PATH=/usr/home/mqudsi/.autojump/bin:/home/mqudsi/.cargo/bin:/usr/home/mqudsi/.config/nvim/dein/repos/github.com/junegunn/fzf/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/mqudsi/bin
PWD=/usr/home/mqudsi
SHELL=/usr/local/bin/fish
SHLVL=1
SSH_CLIENT=192.168.2.6 63814 22
SSH_CONNECTION=192.168.2.6 63814 192.168.1.103 22
TERM=su
USER=mqudsi
fish_user_paths=/home/mqudsi/.cargo/bin/usr/home/mqudsi/.config/nvim/dein/repos/github.com/junegunn/fzf/bin
bind: Key with name 'up' does not have any mapping
bind: Key with name 'f1' does not have any mapping
bind: Key with name 'right' does not have any mapping
bind: Key with name 'dc' does not have any mapping
```

This causes problems for scripts that don't distinguish between stdout and stderr (which unfortunately are not as rare as I'd like), such as vim.

Not sure if we should ignore bind errors during the fish startup stage or if we should explore a different option.

**Comment by mqudsi** [comment] 2017-09-27 04:56
Note that there may be a second bug here as well, since these are the default fish key bindings. So fish certainly shouldn't be trying to _automatically_ bind to keys that aren't defined in termcap for the current `$TERM`.

**Comment by krader1961** [comment] 2017-09-27 05:12
Isn't this a duplicate of issue #4188?

**Comment by faho** [comment] 2017-09-27 12:30
Yes, duplicate of #4188 - note that I've also suggested removing the warnings there.

>So fish certainly shouldn't be trying to automatically bind to keys that aren't defined in termcap for the current $TERM.

The `bind` call will take care of ignoring any keys that aren't set - that's why it prints a warning.

**Closed by faho** 2017-09-27 12:30 UTC
