### ISSUE TITLE
Flat to set which appends if not present?

### ISSUE THREAD

**Issue by max-sixty** [fish-shell/fish-shell#7408] opened 2020-10-20 22:00 UTC
To preface — thank you for building such a brilliant tool, I use `fish` everyday and it makes my life easier and my work more productive.

It's great we have a canonical way to set paths as defined, now at the top of https://github.com/fish-shell/fish-shell/issues/527

There was some discussion at the bottom of the thread about having a more succinct way of adding paths in a script that's run repeatedly. For example, consistent with the canonical approach, I currently I have a bunch of lines in `config.fish` like:

```fish
    contains "$HOME/.cargo/bin" $fish_user_paths; or set -Ua fish_user_paths "$HOME/.cargo/bin"
    contains "$HOME/.local/bin" $fish_user_paths; or set -Ua fish_user_paths "$HOME/.local/bin"
    contains "$HOME/.poetry/bin" $fish_user_paths; or set -Ua fish_user_paths "$HOME/.poetry/bin"
```

One idea I wanted to raise is a flag for `set` which would only append the value to the variable if the value is not already present in the variable (aka "overwrite" it). 
If the flag were `-o` the above lines would then become:

```fish
    set -Uao $fish_user_paths "$HOME/.cargo/bin" 
    set -Uao $fish_user_paths "$HOME/.local/bin"
    set -Uao $fish_user_paths "$HOME/.poetry/bin"
```

This would also be more flexible than a custom solution for paths, like `fish_add_path`, which was also suggested on the linked issue.

Any thoughts?

**Comment by faho** [comment] 2020-10-20 22:36
Duplicate of #6960

**Closed by faho** 2020-10-20 22:36 UTC

**Comment by max-sixty** [comment] 2020-10-20 22:46
Thanks @faho — sorry I missed that. Great to see!
