### ISSUE TITLE
[ctrl-C] fails to terminate job when read is involved (bis)

### ISSUE THREAD

**Issue by mgautierfr** [fish-shell/fish-shell#8985] opened 2022-05-31 10:02 UTC
This issue is pretty closed to #4238 but I cannot comment on it.

Fish version : 3.4.1 (on fedora 35)

I have the following function which launch a inotifywait 

```
function onchange
    set -l command $argv[1]
    set -l files $argv[2..-1]
    inotifywait -mr -e modify  $files | while read line
        echo "Running $command ..."
        fish -c $command
        echo "Done"
    end
end
```

To run with : `onchange "sleep 10" afile.txt`
(I use more useful command, but it is enough to reproduce the bug)

- launching onchange and `Ctrl-C` just after correctly exits the function
- `Ctrl-C` during sleep correctly exits the whole function
- `Ctrl-C` after a first (or other) sleep doesn't exit the function. However, triggering event from inotify (by saving `afile.txt`) after a `Ctrl-C` ends to exits the function (but I need several (2) saves)

In all case the final $status is 130 (SIGINT)

**Comment by faho** [comment] 2022-05-31 12:11
Duplicate of #8699

**Closed by faho** 2022-05-31 12:11 UTC

**Comment by faho** [comment] 2022-05-31 12:12
This doesn't look exactly the same as #8699, but the root cause is the same and it's fixed by the same commit - I just ran a `git bisect` to confirm.

The issue is this:

Once the first "sleep" has finished, fish reclaims the terminal. Only where in #8699 less would try to manipulate the terminal and be stopped, here inotifywait doesn't get the SIGINT.
