### ISSUE TITLE
Fish crashes/exits entering certain characters.

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2226] opened 2015-07-19 11:59 UTC
A few examples are `.` `,` `\` `[0-9]` `!` `@` `$` `q` , this happens both in a TTY and urxvt.

It only seems to happen when it is the first character, `.` makes fish exit, but `a.` doesn't.

**Comment by zanchey** [comment] 2015-07-19 12:05
I can't reproduce this on 2.2.0; what version are you running?

**Comment by onodera-punpun** [comment] 2015-07-19 12:05
fish, version 2.2.0-48-g7954b95

**Comment by onodera-punpun** [comment] 2015-07-19 12:07
terminal output:
``
~ fish
(I enter a `.` here)
~ .fish: 'fish' terminated by signal SIGSEGV (Address boundary error)
``
A reboot will probably fix this problem, but it's still kinda weird and doesn't happen with bash.

**Comment by zanchey** [comment] 2015-07-19 12:09
It will not surprise you that this is unlikely to be a common problem! If you are not keen on restarting, you could try running fish under GDB and see where it's crashing.

**Comment by onodera-punpun** [comment] 2015-07-19 12:11
Recompiling & reinstalling fish just fixed the problem, no idea what caused it...

**Comment by zanchey** [comment] 2015-07-19 12:54
I'll close this for now, but if you can reproduce it let us know!

**Closed by zanchey** 2015-07-19 12:54 UTC
