### ISSUE TITLE
SSH completion does not work with the "include" directive

### ISSUE THREAD

**Issue by meiyopeng** [fish-shell/fish-shell#4487] opened 2017-10-18 05:10 UTC
SSH completion does not recognize the "include" directive in my SSH configuration.
My SSH config file ~/.ssh/config:
```
Host *
    Include conf.d/*
```

Typing `SSH <TAB>` in fish shell causes an error:
```
-> ssh - (line 1): No matches for wildcard “conf.d/*”. See `help expand`.
begin; echo conf.d/*
            ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

in command substitution
        called on standard input

in function “_recursive”
        called on standard input

in function “_ssh_include”
        called on line 2 of file /usr/share/fish/functions/__fish_print_hostnames.fish
        with parameter list “/root/.ssh/config”

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_print_hostnames.fish

in function “__fish_print_hostnames”
        called on line 2 of file /usr/share/fish/functions/__fish_complete_subcommand.fish

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_complete_subcommand.fish

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_complete_subcommand.fish

in function “__fish_complete_subcommand”
        called on standard input

in command substitution
        called on standard input

- (line 1): No matches for wildcard “conf.d/*”. See `help expand`.
begin; echo conf.d/*
            ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

in command substitution
        called on standard input

in function “_recursive”
        called on standard input

in function “_ssh_include”
        called on line 2 of file /usr/share/fish/functions/__fish_print_hostnames.fish
        with parameter list “/root/.ssh/config”

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_print_hostnames.fish

in function “__fish_print_hostnames”
        called on line 2 of file /usr/share/fish/functions/__fish_complete_subcommand.fish

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_complete_subcommand.fish

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_complete_subcommand.fish

in function “__fish_complete_subcommand”
        called on standard input

in command substitution
        called on standard input

- (line 1): No matches for wildcard “conf.d/*”. See `help expand`.
begin; echo conf.d/*
            ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

in command substitution
        called on standard input

in function “_recursive”
        called on standard input

in function “_ssh_include”
        called on line 2 of file /usr/share/fish/functions/__fish_print_hostnames.fish
        with parameter list “/root/.ssh/config”

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_print_hostnames.fish

in function “__fish_print_hostnames”
        called on standard input

in command substitution
        called on standard input

- (line 1): No matches for wildcard “conf.d/*”. See `help expand`.
begin; echo conf.d/*
            ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

in command substitution
        called on standard input

in function “_recursive”
        called on standard input

in function “_ssh_include”
        called on line 2 of file /usr/share/fish/functions/__fish_print_hostnames.fish
        with parameter list “/root/.ssh/config”

in command substitution
        called on line 0 of file /usr/share/fish/functions/__fish_print_hostnames.fish

in function “__fish_print_hostnames”
        called on standard input

in command substitution
        called on standard input

```

My fish and terminal:
```
-> fish --version
fish, version 2.6.0
-> uname -a
Linux sid 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux
-> echo $TERM
xterm-256color
```

**Comment by faho** [comment] 2017-10-18 10:40
Duplicate of #4253, which has already been fixed and will be included in the upcoming 2.7.0 release.

**Closed by faho** 2017-10-18 10:40 UTC
