### ISSUE TITLE
macOS Big Sur has revived the slow __fish_describe_command issue

### ISSUE THREAD

**Issue by offbyone** [fish-shell/fish-shell#7601] opened 2021-01-02 22:30 UTC
I believe that #6270 is still a going concern on macOS Big Sur:

```
~/.emacs.d on  develop [⇡] on  (pdx) took 4s  0 🐟
❯ fish --version
fish, version 3.1.2

~/.emacs.d on  develop [⇡] on  (pdx)  0 🐟
❯ echo $version
3.1.2

~/.emacs.d on  develop [?⇡] on  (pdx)  0 🐟
❯ uname -a
Darwin MacBook-Pro.lan.offby1.net 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

~/.emacs.d on  develop [?⇡] on  (pdx)  0 🐟
❯ echo $TERM
xterm
```
_Note that `xterm` is a lie; this is iTerm2_

I have tested that `apropos` is slow on my OS:

```
# this is in my regular shell:
> time apropos man | cat
# ... stuff
________________________________________________________
Executed in    1.45 secs   fish           external
   usr time  305.63 millis  243.00 micros  305.38 millis
   sys time  947.82 millis  1426.00 micros  946.40 millis

# this is in the bare shell from `sh -c 'env HOME=$(mktemp -d) fish'`
> time apropos man | cat
# ... lots of noise
________________________________________________________
Executed in    1.79 secs   fish           external
   usr time  313.87 millis  183.00 micros  313.69 millis
   sys time  1288.66 millis  811.00 micros  1287.85 millis
```

At its worst this ran for >5 sec; clearly something in the OS caches it over time.

**Comment by faho** [comment] 2021-01-02 22:31
Duplicate of #7588

**Closed by faho** 2021-01-02 22:31 UTC

**Comment by offbyone** [comment] 2021-01-02 22:34
*facepalm* Thanks, faho, much appreciated.
