### ISSUE TITLE
Setting $fish_history to anything causes a SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by GloverDonovan** [fish-shell/fish-shell#4686] opened 2018-01-28 03:06 UTC
Hello,

I was following along with the [fish documentation](https://fishshell.com/docs/current/index.html#variables-special) when `set -U fish_history default` caused all my future fish sessions to immediately SIGSEGV. Any string I used to set `$fish_history`, including the default `"fish"` and empty `""`, caused a SIGSEGV.

No customizations of any kind, just straight fish. Tested on a fresh install and got the same behavior.

Workaround: Unset `$fish_history` and the shell will work again.

```shell
set -e fish_history
```

I don't think this should be expected behavior since `set -U fish_greeting ""` worked just fine.

fish version: 2.7.1
OS: Arch GNU/Linux
Related: #4619

**Comment by faho** [comment] 2018-01-28 12:53
> Related: #4619

I'd go even further, and say it's a duplicate of #4619. While the report there only talks about setting it to empty, the root cause was simply that it was set too early, which caused fish to crash.

I think you'll find that it works with 75ac482.

**Closed by faho** 2018-01-28 12:53 UTC

**Comment by GloverDonovan** [comment] 2018-01-28 17:34
Hello,

Just tested with the latest build of fish and it works, thanks!

Apologies for the duplicate, I'm not familiar with the codebase and couldn't tell whether or not that would fix this.
