### ISSUE TITLE
warn if exiting fish with a unsaved but edited function

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3701] opened 2017-01-06 01:52 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

This would save me a lot of time. I always forget to save the function I just edited with `funced` :(

**Comment by krader1961** [comment] 2017-01-06 02:07
I'm ambivalent about this proposal. Personally, I only use `funced` when I expressly want to make a transient change. If I want the change to be permanent I edit the underlying file and just let it be reloaded via the autoload mechanism. Rather than warn at exit time it would be simpler and safer, in my opinion, to modify `funced` to issue the warning after the user exits their editor. It would be best to write the warning only if the function was initially autoloaded but that will require implementing issue #3295.

**Comment by ridiculousfish** [comment] 2017-01-07 20:43
How about an option to `funced` like `--save` which will run `funcsave` if the editor succeeds?

**Comment by krader1961** [comment] 2017-01-08 01:56
Adding a `-s` / `--save` option is okay by me. However, I think a reminder message if the user didn't specify that option is still a good idea.

**Comment by floam** [comment] 2017-01-08 07:02
I agree. I know I lost a number of functions as a new fish user that could have been rescued with a helpful reminder.

**Comment by nhooyr** [comment] 2017-01-08 11:14
@ridiculousfish how about an option to just straight up open the file in the editor?

**Comment by ridiculousfish** [comment] 2017-01-08 22:17
@nhooyr `funced` prefers to use `$EDITOR` if set, is that what you mean?

**Comment by nhooyr** [comment] 2017-01-08 22:23
@ridiculousfish but it opens a temporary file, I mean if a file exists for the function, it automatically opens that file in `$EDITOR` or if it doesn't, then it creates that file and opens that in `$EDITOR`. So no temp files if you set an option.

**Comment by krader1961** [comment] 2017-01-08 22:43
> if it doesn't, then it creates that file and opens that in $EDITOR.

Do you propose to do that only if a specific option (e.g., the proposed `--save` option) is used or make that the default behavior?

**Comment by nhooyr** [comment] 2017-01-08 22:47
Either is fine with me, I'll just alias it if we go with an option. However, I think most people would prefer that the behaviour I described becomes the default behaviour and the other is hidden behind an option.

**Comment by krader1961** [comment] 2017-01-09 00:00
I don't think there is an overwhelming argument for either the current `funced` behavior to not automatically save the edit or the proposed behavior to do so. I think the tie-breaker is that changing existing default behavior should be avoided. So we should instead introduce something like a `--perm` / `-p` or `--save` / `-s` option pair to mean the edit should be persisted to the file system. And, as I said earlier, if that option isn't specified then display a reminder that the user may want to run `funcsave` to avoid losing their edit.

Also, I feel like @nhooyr is missing the main reason for the current behavior. It makes it easy to test a change without worrying about accidentally breaking the version that is stored in the file system. That is, I can use `funced` to easily add some diagnostic `printf` statements or explore "what if" questions without having to first save a copy of the autoloaded script (or have it under version control). If I'm happy with the change I can then run `funcsave` to persist it to disk. So while I wholeheartedly agree that fish should remind the user that they will lose those changes unless they use one of the aforementioned solutions I don't want those edits to be persisted to an autoloaded script by default.

**Comment by krader1961** [comment] 2017-01-10 07:08
Closing as a duplicate of issue #391. This issue discusses an aspect of the problem that was not previously discussed in #391 but it is essentially the same issue.

**Closed by krader1961** 2017-01-10 07:08 UTC
Labels: enhancement
