### ISSUE TITLE
vi mode: 'r' doesn't work.

### ISSUE THREAD

**Issue by newhook** [fish-shell/fish-shell#2191] opened 2015-07-13 11:38 UTC
It should replace the character under the cursor.

**Comment by pickfire** [comment] 2015-07-13 13:25
Yeah, the current **replace** *mode* in `fish_vi_mode` works just like **append**.

**Comment by faho** [comment] 2015-07-17 21:37
Soo.. either this should be seen as a duplicate of #1417 (we don't have a _proper_ replace mode after all), or that one should be closed since we _do_ have a replace mode, just a broken one.

**Comment by pickfire** [comment] 2015-07-19 08:01
Close this duplicate?

**Comment by zanchey** [comment] 2015-07-24 11:05
Yep, let's track in #1417.

**Closed by zanchey** 2015-07-24 11:05 UTC
Labels: duplicate
