### ISSUE TITLE
Comments at the beginning of a function are lost

### ISSUE THREAD

**Issue by yatharth** [fish-shell/fish-shell#6463] opened 2019-12-30 09:26 UTC
### Summary

Every time a function is created or edited, Fish silently gets rid of the first non-empty line in the function if the function’s first non-empty line is a comment.

This has caused me loss of data in the comments! I’m using a workaround, but this can easily lose data for users unaware of this bug.

### Steps to reproduce

* Type in

```
function foo
        
  # Hello 1
        
  # Hello 2

  echo Hello

  # Bye 
  echo Bye

end 
```

1. Then run `functions foo`

### Expected Behavior

`functions foo` displays the function exactly as typed:

```
function foo
        
  # Hello 1
        
  # Hello 2

  echo Hello

  # Bye 
  echo Bye

end 
```

### Actual Behavior

The first comment line is lost:

```
function foo
        
        
  # Hello 2

  echo Hello

  # Bye 
  echo Bye

end 
```

### Steps to Reproduce (continued)

1. Type in `funced foo` and just save/quit without making any modifications
1. Type in `functions foo` again

### Expected Behavior

`functions foo` displays the function exactly as typed again:

```
function foo
        
  # Hello 1
        
  # Hello 2

  echo Hello

  # Bye 
  echo Bye

end 
```

### Actual Behavior

The next comment line is once again lost: 

```
function foo


  echo Hello

  # Bye 
  echo Bye

end 
```

### Environment

Fish version 3.0.2 with Oh My Fish version 6.  
Installed using Homebrew on macOS 10.15.2

**Comment by yatharth** [comment] 2019-12-30 09:28
### Workaround until this is fixed

I simply add a noop command like `true` at the beginning of my functions before any comments.


### Why do I have comments at the start of functions?

They provide extensive documentation on the internals of the function for when I am editing the function later.

**Comment by mqudsi** [comment] 2020-01-03 07:10
I believe it's a duplicate of https://github.com/fish-shell/fish-shell/issues/5285

**Comment by floam** [comment] 2020-01-03 07:49
Duplicate of #5285

**Closed by floam** 2020-01-03 07:50 UTC
Labels: bug
