### ISSUE TITLE
In Windows Subsystem for Linux, piping from cat to sed causes an error.

### ISSUE THREAD

**Issue by robertoloja** [fish-shell/fish-shell#3454] opened 2016-10-14 04:37 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [X] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_: 2.3.1

**OS/terminal used**: Windows 10 (Windows Subsystem for Linux), mintty (also checked on cmd.exe)
## Reproduction steps
1. Launch a WSL terminal (cmd.exe or mintty; the bug is reproducible in both). By default, this will be `bash`.
2. Launch `fish`.
3. Create a text file.
4. Pipe the contents of the text file through sed with a simple substitution.

## Results

``` console
~ $  echo "text" > file.txt
~ $  cat file.txt | sed 's/e/f/g'
Could not send process 212, 'sed' in job 1, 'cat file.txt | sed 's/e/f/g'' from group 3 to group 211
setpgid: Operation not permitted
sed: read error on stdin: Input/output error
~ $
```
## Notes

Piping from echo to sed works as expected. 
The above steps work as expected in `bash`, both in mintty and cmd.exe

**Comment by faho** [comment] 2016-10-14 11:25
The obvious question here is if this is something fish should do anything about. WSL is meant to be bug-for-bug binary compatible with linux, and I've never seen this error in linux.

Of course it's possible this is something we should cope with.

**Comment by krader1961** [comment] 2016-10-14 18:06
FWIW,I can reproduce the problem. Replacing `cat` with `head` and `tail` fail in a similar manner. But using `grep` works because it's a function that wraps the external command and thus doesn't fork that side of the pipe. This is clearly an artifact of an incomplete mapping of Linux semantics for process management to the Windows model. TBD is whether there is anything fish can reasonably do to workaround this WSL quirk.

**Comment by ridiculousfish** [comment] 2016-10-22 07:51
This seems surprising to me - why isn't bash, etc. affected? I'll try to take a look.

**Comment by saschagehlich** [comment] 2016-11-24 18:17
@ridiculousfish Were you able to find something out about this?

**Comment by ridiculousfish** [comment] 2016-11-26 09:40
I had to reinstall Windows and haven't taken a look yet

**Comment by krader1961** [comment] 2017-04-06 06:19
I updated my Windows 10 WSL environment and fish. I can no longer reproduce this failure so I'm closing the issue.

**Closed by krader1961** 2017-04-06 06:19 UTC
Labels: bug, windows-subsystem-for-linux
