### ISSUE TITLE
Change directory in a subshell (only)

### ISSUE THREAD

**Issue by OJFord** [fish-shell/fish-shell#8414] opened 2021-11-06 17:58 UTC
fish, version 3.3.1
Linux
No third-party customisations

----

In bash, a change of directory in any kind of sub-shell does not affect the `$PWD` of the parent shell: 
```
~$ echo $(cd /tmp && echo $PWD)
/tmp
~$ echo $PWD
/home/OJFord
```

In fact, that's a little contrived, but it's very convenient for executing a command in a different directory where the output doesn't need to be used in a substitution:
```
~/project$ (cd frontend-src && npm install)
~/project$ (cd backend-src && make)
```

I was wondering if fish has an equivalent to the latter (since the same syntax in fish is a substitution, which then isn't allowed without a command - and if it were, it's meaning would be that the output should be substituted as a command (#5575) - not what we want here.

In doing so, I discovered that in fish even in the substitution case, the directory change is propagated, the example from above in fish:
```
~> echo (cd /tmp && echo $PWD)
/tmp
/tmp> echo $PWD
/tmp
```

Is this a deliberate design decision? Is there any way _not_ to, to execute a command elsewhere and come back, besides explicitly `cd`ing (or `popd`) back and `fish -c '...'`?

**Comment by floam** [comment] 2021-11-06 19:14
Long term, with concurrent functions and whatnot I think this may end up being solved somehow.

Per-thread working directories are tricky. On macOS, it's syscall 348 (SYS___pthread_chdir) aka `pthread_chdir_np`, and I think on Linux you can do it somehow with the `unshare(CLONE_FS)` syscall to unshare the CWD? (threads in Linux were only ever implemented as a kind of a weird special case of a process, and you almost fork off a thread, you clone off a thread.)

**Comment by floam** [comment] 2021-11-06 19:44
But to answer your question directly: right now the best you can do is is use push/popd or use `fish -c` for an actual subshell fork.

**Comment by krobelus** [comment] 2021-11-07 05:56
For grouping we use begin/end. Using parentheses was discussed in https://github.com/fish-shell/fish-shell/issues/8083

These are not real subshells, so the isolated `cd` isn't done automatically. Would be nice though.

**Comment by krobelus** [comment] 2021-11-07 05:57
Duplicate of #1439

**Closed by krobelus** 2021-11-07 05:57 UTC
Labels: question
