### ISSUE TITLE
echo redirect splits up the writes, potentially producing unexpected behaviour

### ISSUE THREAD

**Issue by nagisa** [fish-shell/fish-shell#8075] opened 2021-06-19 12:41 UTC
Version: 3.2.2
NixOS

---

Certain (most? all?) `/sys` files expect the contents to be written in a single atomic operation. It is also extremely commonplace to write to these files by redirecting echo, as e.g. such:

```
$ echo "50 60" > /sys/devices/platform/huawei-wmi/charge_control_thresholds
```

Somewhat recently something changed in `fish` that causes this write end up as

```
openat(AT_FDCWD, "/sys/devices/platform/huawei-wmi/charge_control_thresholds", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 4
write(4, "5", 1)                        = -1 EINVAL (Invalid argument)
```

thus producing a pretty opaque

```
write: Invalid argument
```

error message. I recall this working okay in the past, so it must be a somewhat recent regression (though checking past system profiles, this was broken as far back as in March of 2021). This pattern continues to work okay with bash. I think it is important that this is addressed. Otherwise people may see unintended behaviour and potentially broken hardware due to sys/dev/proc files only interpreting a partial write.

**Comment by faho** [comment] 2021-06-19 12:43
Duplicate of #7836

**Closed by faho** 2021-06-19 12:43 UTC
