### ISSUE TITLE
dnf autocompletions don't work on Fedora 41

### ISSUE THREAD

**Issue by adriankwiat** [fish-shell/fish-shell#10823] opened 2024-10-31 21:49 UTC
On Fedora 41 (which has new dnf5) autocompletions for `dnf install` and `dnf remove` doesn't work (maybe for other commands too): for `dnf install` it doesn't complete any packages, just files in current directory; for `dnf remove` it makes lists all packages (even with written prefix of name) without any separation and colors, then many blank lines, then again whole typed command, list of all packages (now colored) and many blank lines.

https://github.com/user-attachments/assets/312c3049-c1d8-4b6f-b803-1702b3446542

https://github.com/user-attachments/assets/5d27aace-f0ad-4b82-908e-7c885f32ccc7

This happens on Fedora 41, in many terminal emulators. Fish was run without any customizations with `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'`. In Bash all completions work.

**Comment by faho** [comment] 2024-10-31 21:54
Duplicate of #9862

**Closed by faho** 2024-10-31 21:54 UTC
