### ISSUE TITLE
Emoji in history make fish go haywire

### ISSUE THREAD

**Issue by OJFord** [fish-shell/fish-shell#4609] opened 2017-12-18 16:04 UTC
Fish 2.7.0; macOS 10.13.2

Reproduction:

1. Run a command with a non-ascii unicode character
2. Begin re-writing the same command

Observe:

- Goes crazy, re-writing the line and all sorts. Exactly what happens probably varies with what's typed and what the offending character was.
- Commands that do not contain emoji write out normally
- Commands that are not the most recent item in history write out normally

**Comment by faho** [comment] 2017-12-18 19:10
Yes. The problem here is that your terminal and fish disagree on the width of those characters.

This is a duplicate of #4539. Please try #4554.

**Closed by faho** 2017-12-18 19:10 UTC
