### ISSUE TITLE
Feature to show command synopsis

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8435] opened 2021-11-11 13:37 UTC
Completion feature and autosuggestions don't always give us enough info about how actually to use command. What about to show command synopsis (on which cursor is) in interactive session under entered command?

Displayed synopsis could be parsed automatically from man page or specified manually:

```fish
synopsis --command argparse -- [OPTIONS] OPTION_SPEC... -- [ARG...]
```

Syntax highlighting for optional options and other synopsis parts can be customized via some environment variables.

This feature could look like this:

```fish
~ Thu 11:36💲argparse --help
synopsis: argparse [OPTIONS] OPTION_SPEC... -- [ARG...]
```

It is very close to tldr be interactive.

**Comment by faho** [comment] 2021-11-11 13:50
This seems very close to the idea of argument hints, I'm closing it in favor of that.

**Comment by faho** [comment] 2021-11-11 13:50
Duplicate of #2201

**Closed by faho** 2021-11-11 13:50 UTC
