### ISSUE TITLE
Restrict autocomplete to nearest whitespace

### ISSUE THREAD

**Issue by aeonios** [fish-shell/fish-shell#1505] opened 2014-06-13 19:15 UTC
The current autocomplete behavior dictates that when you hit the right arrow key, the current suggestion is fully instantiated including all arguments. In many cases this behavior makes autocomplete useless, for example if I type 'w' for 'wget' and hit right arrow, I get wget+the link of whatever I downloaded last, which I then must delete before I can paste a new link. I've ended up typing out 'wget' manually instead simply because it's less work. Ideally, autocomplete should only complete to the next whitespace, and then push the cursor onto the first character of the next suggested argument without actually selecting it until you hit right arrow again. That would also make browsing through history items with a filter (or browsing complete options by typing) require fewer keystrokes.

There are some cases where one-argument selection behavior might make things slower, but I think it's acceptable as long as the behavior is consistent (which it currently doesn't feel like it). Rather, the current autocomplete behavior with directories works intuitively, but for commands does not.

**Comment by faho** [comment] 2017-03-23 16:22
>already bound to several key sequences such as [ctrl-F] in emacs mode.

Note: "forward-bigword" is available, but not bound to anything by default.

**Comment by krader1961** [comment] 2017-03-23 18:17
I had forgotten that I added it to my `fish_user_key_bindings` function. It is bound to some keys by default but only in vi mode, not default/emacs mode.

**Comment by floam** [comment] 2019-02-07 09:07
Is this something we want to provide a bind for with the default keybindings?

**Comment by faho** [comment] 2019-02-07 16:06
The problem is finding a good key to put it on.

right-arrow is bound to forward-char (and should stay that way), so a modified version of that would work.

But ctrl-right is bound to forward-word and alt-right is bound to nextd-or-forward-word.

So unless we want to change one of those, we'd have to find a different combination.

**Comment by floam** [comment] 2019-02-07 16:28
shift-left/shift-right isn't bound to anything (or at least isn't with the escapes my terminal sends)

**Comment by floam** [comment] 2019-02-07 16:30
shift-right: `[1;2C`, which is actually bindable with just `bind -k sright`

**Comment by floam** [comment] 2019-02-07 16:33
That seems totally fine, mind if I bind `sleft` to `backward-bigword` and `sright` to `forward-bigword` by default?

**Comment by faho** [comment] 2019-02-07 18:15
Yeah, that'll work.

**Comment by floam** [comment] 2019-02-07 21:18
Fixed in https://github.com/fish-shell/fish-shell/commit/0abcf9265efe5eb43e9992133638356f0f9c5c09 ... appear I referenced the wrong issue number in the commit message. (Doh!)

**Closed by floam** 2019-02-07 21:18 UTC
Labels: enhancement
