### ISSUE TITLE
Documentation on shell translation

### ISSUE THREAD

**Issue by patrickf3139** [fish-shell/fish-shell#5854] opened 2019-04-30 23:46 UTC
I've been converting some of my coworkers bash from fish. 🎊 
Unfortuantely, one bump I keep hitting is teaching them the exact differences between bash and fish syntax. Even I'm not sure anymore as I haven't used bash in so long.

I did find https://github.com/fish-shell/fish-shell/wiki/Shell-Translation-Dictionary but it hasn't been kept up-to-date. Not only does it miseducate fish users, but the fact that it hasn't been updated in years would deter people evaluating fish to not switch because it makes fish look poorly documented. (Aside: I took the liberty of updating the section on logical ANDS section with remarks on the 3.0 `&&` compatibility change.) (Aside 2: https://github.com/fish-shell/fish-shell/wiki/Bash-Style-Command-Substitution-and-Chaining-(!!-!%24-&&-%7C%7C) is also out of date.) Even if it was kept up to date, I think it's very hard for most users to find. It would be much more discoverable if it were placed where new fish users expect it--in the official fish documentation.

So, I would like to propose that we add a new section to the fish docs that gives the low down on how former bash users can quickly adapt to fish syntax. What do ya'll think? 🙂

**Comment by faho** [comment] 2019-05-02 15:19
>So, I would like to propose that we add a new section to the fish docs that gives the low down on how former bash users can quickly adapt to fish syntax. What do ya'll think? slightly_smiling_face

I agree. In fact I agree enough that I had opened #2382 years ago.

Closing this one as duplicate of that!

**Closed by faho** 2019-05-02 15:19 UTC
