### ISSUE TITLE
abnormal display when spliting window on tmux

### ISSUE THREAD

**Issue by haodong** [fish-shell/fish-shell#5440] opened 2018-12-29 09:13 UTC
It was mentioned in https://github.com/fish-shell/fish-shell/issues/5231 and https://github.com/fish-shell/fish-shell/issues/1086 
Now I've upgraded to v3.0.0 but still experiencing the same problem.

![screen shot 2018-12-29 at 5 06 28 pm](https://user-images.githubusercontent.com/8103074/50536226-0ee9ac00-0b8d-11e9-9084-59533ae9ebc8.png)
![screen shot 2018-12-29 at 5 06 40 pm](https://user-images.githubusercontent.com/8103074/50536227-101ad900-0b8d-11e9-9c73-3235e616b99d.png)

Any plan to fix this?

**Comment by zanchey** [comment] 2018-12-29 13:57
This is still a duplicate of #1086. There's nobody working on it as far as I know.

**Closed by zanchey** 2018-12-29 13:57 UTC
