### ISSUE TITLE
"&" doesn't work correctly with aliases

### ISSUE THREAD

**Issue by z3ntu** [fish-shell/fish-shell#4644] opened 2018-01-05 09:38 UTC
I'm running fish, version 2.7.0.

Running e.g. the command `streamlink "https://www.youtube.com/watch?v=-rWPZtM1eRs" 480p &` doesn't put the command in the background and has to be done via Ctrl+Z and `bg`.
Normal commands work just fine and also in a new shell.
Sorry if this is weird but I've discovered why it doesn't work while experimenting a bit while writing this issue.
Demonstration:
```
alias testcommand="cat"
testcommand &
```
and this doesn't put cat / testcommand into background mode.

asciinema recording (of the streamlink example): https://asciinema.org/a/WdFpuCB8WxvSGNQSYJK6xpnBL
streamlink doesn't work because I've put
```
alias streamlink="streamlink --player mpv"
```
into my config.fish.

Sorry again, if my text got a bit weird ^^

**Comment by faho** [comment] 2018-01-05 11:03
Duplicate of #238 - aliases are functions (it's really just syntactic sugar - see `type alias`), and functions cannot be backgrounded currently.

**Closed by faho** 2018-01-05 11:03 UTC

**Comment by z3ntu** [comment] 2018-01-05 11:28
Thanks, I've made myself a workaround for now
```
function monstercatinstant
   /usr/bin/streamlink --player mpv "https://www.youtube.com/watch?v=-rWPZtM1eRs" 480p &
   disown
end
```
which works as expected :)
