### ISSUE TITLE
Error writing config? files on cygwin when config folder symlinked

### ISSUE THREAD

**Issue by zovt** [fish-shell/fish-shell#3173] opened 2016-06-26 02:20 UTC
Fish seems to be spamming the console with the following message under Cygwin when the `.config\fish` folder is symlinked: 
Unable to rename file from '/cygdrive/c/Users/zovt/.config/fish/fishd.tmp.8V6a2i' to '/cygdrive/c/Users/zovt/.config/fish/fishd.DESKTOP-S1S6RU9.x86_64': Permission denied

### Reproduction Steps:

1. Open Cygwin and run Fish

### Expected behavior:
Fish doesn't spam the console

### Observed behavior:
Fish spams the console

### Additional information:
Seems to happen all the time. However, not when creating the symlink from a "working" fish session

---
Fish version: 2.3.0

Operating system: Cygwin

Terminal or terminal emulator: ConEmu

**Comment by krader1961** [comment] 2016-06-26 02:30
Closing as a duplicate of issue #2590.

Note that MS Windows doesn't have symlinks in the UNIX sense of the term. Please read the earlier issue and try to answer some of the questions therein.

**Closed by krader1961** 2016-06-26 02:30 UTC
Labels: duplicate
