### ISSUE TITLE
Custom Coloring in Tab Completion

### ISSUE THREAD

**Issue by Rincewind34** [fish-shell/fish-shell#8968] opened 2022-05-21 15:47 UTC
» fish, version 3.4.1
» MacBook Pro 2021 M1 Max
» Default Terminal from MacOS

I think it would be great if my custom tab completion would support adding colours to the options. It would make it easier to distinguish the possible options (an easy MVP could be to color the files tab completer the same way `ls` would do).
What I tried so far is using `set_color` inside the `--arguments` option of `complete` (inside a sub shell opened to calculate the possible arguments) but that just printed the special characters in front of the coloured argument options.

Thanks in advance for taking this into consideration!
Best, Rincewind

**Comment by faho** [comment] 2022-05-26 11:02
Duplicate of #2868

**Closed by faho** 2022-05-26 11:02 UTC
