### ISSUE TITLE
add friendly stdout and stderr redirection &>

### ISSUE THREAD

**Issue by bleepnetworks** [fish-shell/fish-shell#6192] opened 2019-10-11 10:18 UTC
fish, version 3.0.2
macos mojave 10.14.6 (18G103)
Darwin Kernel Version 18.7.0
xterm-256color
sh -c 'env HOME=$(mktemp -d) fish' <- does not resolve the issue

reproduction:
```
> ls -l /bogus > output 2>&1
> ls -l /bogus &> output
fish: Expected a command, but instead found a redirection
ls -l /bogus &> output
              ^
>
```
bash:
```
$ bash --version | head -n 1
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
$ ls -l /bogus > output 2>&1
$ ls -l /bogus &> output
$
```

bash has supported the '&>' short form [since version 4](https://www.tldp.org/LDP/abs/html/io-redirection.html) and zsh [supports it as well](http://zsh.sourceforge.net/Doc/Release/Redirection.html). '&>' is way easier to remember than 'cmd > file  2>&1', would be great if fish added support for it

**Comment by faho** [comment] 2019-10-11 15:28
For those watching along at home, #689 asked for the same thing, but was closed as a duplicate of #110 because that was just titled "Syntax improvements for redirection & pipes". However it was then closed because the only thing that was really asked for was a way to pipe stderr and stdout together, which is now possible with `2>&1 | ` (i.e. pipe stdout, redirect stderr to stdout).

Personally, I don't think this is useful often enough to warrant yet more syntax, but if anyone else thinks it's important enough to implement, go ahead.

**Comment by bleepnetworks** [comment] 2019-10-11 15:42
hi @faho it's one less barrier to adoption of a new shell. if bash and zsh support it why not fish.

I am a long time bash user considering a new shell, and the more changes I have to make to my existing conf files the less likely I am to make the switch.

plus it's a much more intuitive syntax.

**Comment by faho** [comment] 2019-10-11 16:07
> if bash and zsh support it why not fish.

Fish is neither bash nor zsh. It's different, on purpose.

**Comment by bleepnetworks** [comment] 2019-10-11 16:11
> > if bash and zsh support it why not fish.
> 
> Fish is neither bash nor zsh. It's different, on purpose.

oh sure, but it's still a shell right? so why not make it easier to switch?

**Comment by floam** [comment] 2019-10-12 18:20
I think what bash and zsh came up with here are pretty reasonable.

**Comment by ridiculousfish** [comment] 2019-10-13 21:55
fish has pretty much bought into the bash syntax for redirections already, so I think it makes sense to match  this.

**Comment by amosbird** [comment] 2019-10-14 00:31
I guess that means we can also support `&|` ?

**Comment by floam** [comment] 2019-10-14 02:47
Since I haven't seen `^>` mentioned here yet, way back in 2013 @xfix preferred `^>` over `&>` when it was suggested in #689.

**Comment by ridiculousfish** [comment] 2019-10-15 19:16
We're moving away from ^ as a stderr redirection (`stderr-nocaret` feature flag).

**Comment by mqudsi** [comment] 2019-10-27 21:04
I'm OK with this since & is already a reserved character.

**Comment by zanchey** [comment] 2019-10-30 03:00
Closed by #6206?

**Comment by faho** [comment] 2019-10-31 21:14
Yep.

**Closed by faho** 2019-10-31 21:14 UTC
Labels: enhancement

**Comment by lucasb-eyer** [comment] 2020-03-15 14:22
I have updated fish shell after a while, and now the syntax `^&-` does not work anymore. I checked the changelog and this is the closest change I can associate that may have caused this.

**Comment by krobelus** [comment] 2020-03-15 14:54
@lucasb-eyer that's #6591, a 3.1.0 regression that will be fixed in 3.1.1, although `^` is deprecated, see https://fishshell.com/docs/current/index.html#future-feature-flags

**Comment by skerit** [comment] 2020-04-21 18:32
What's the suggested alternative for `^&-` then? Because Ubuntu 20.04 is shipping with Fish 3.1.0, my current fish prompt script broke.

**Comment by faho** [comment] 2020-04-21 18:55
>What does the - even mean in ^&-?

It means the close the file descriptor, rather than redirect it - some people *think* it's the same thing as redirecting to /dev/null, but it's not. The writing program will receive errors, which you'll have to hope it swallows.

The alternative is to just redirect to /dev/null, with `2>/dev/null`, or, if you need to redirect both stdout and stderr `>/dev/null 2>&1`.

**Comment by skerit** [comment] 2020-04-21 19:00
I actually just tried that! But my original line doesn't seem to work anymore.

The original line btw was `git diff --quiet HEAD ^&-`, which I now changed to `git diff --quiet HEAD >/dev/null 2>&1`, but that doesn't seem to do the same thing.

Maybe it has something to do with the `-` closing the file descriptor? Anyway, changing it to `&>&-` does not work either, that throws an error :/

**Comment by faho** [comment] 2020-04-21 19:04
>The original line btw was git diff --quiet HEAD ^&-, which I now changed to git diff --quiet HEAD >/dev/null 2>&1, but that doesn't seem to do the same thing.

What happens? What do you want to happen?

Typically closing the file descriptor is strictly *wrong* (as in the program will *fail*) or doesn't matter. It fixing things is quite unexpected.

**Comment by faho** [comment] 2020-04-21 19:10
Okay, I think I got it. You want to silence *just stderr*. In that case use `2>/dev/null`.

Because the bit that signifies "close the file descriptor" is "&-", not just "-", and the `^` is the old fish-specific  way of spelling `2>`, stderr.

This entire issue is of no interest to you (and wasn't to the first person to mention `^&-` either).

**Comment by skerit** [comment] 2020-04-21 19:14
Yeah, sorry for taking this so off-topic. It was a shell prompt I found a long time ago. But even when just using `2>/dev/null` it doesn't seem to work.

I'll look for another shell prompt, thanks for the help anyway!

**Comment by faho** [comment] 2020-04-21 19:15
>Yeah, sorry for taking this so off-topic. It was a shell prompt I found a long time ago. But even when just using 2>/dev/null it doesn't seem to work.

Some context would be quite nice, then I might be able to help you.

**Comment by skerit** [comment] 2020-04-21 19:40
Well, it's getting quite confusing. I installed `fish` 3.1.0 on another device, and replaced it with `2>/dev/null` as you previously said, and it DID work there!

Somehow I seriously broke something in my fish install, but yeah `2>/dev/null` does fix the prompt.
