### ISSUE TITLE
Completing a folder misses an escape on the first char

### ISSUE THREAD

**Issue by Profpatsch** [fish-shell/fish-shell#2274] opened 2015-08-05 14:18 UTC
When completing a folder and selecting an entry from the list, if that entry starts with a character that should be escaped, it isn’t.

Example:

<kbd>~/Downloads/[</kbd><kbd>TAB TAB TAB</kbd>
select entry `[foobar] my file`

Completion: `~/Downloads/[foobar\]\ my\ file`

Note the missing `\` before the first `[`.

**Comment by faho** [comment] 2015-08-05 16:04
I can't reproduce with that _specific_ case:

    $ touch ~/Downloads/"[foobar] my file"
    $ rm ~/Downloads/ # and tab-select the right file
    $ rm ~/Downloads/\[foobar\]\ my\ file

I can however get this if I enter a literal "[" and then complete. Fish will complete the file, but won't escape the "[" (and then highlight it as invalid).

**Comment by Profpatsch** [comment] 2015-08-05 17:49
@faho Then that was that.

**Comment by Profpatsch** [comment] 2015-08-06 15:17
Oh, and aditionally: When starting the completion item with `\` it doesn’t find anything. So there is no way to complete in a working way.

**Comment by adriaanzon** [comment] 2017-01-30 16:29
I noticed today when [yarn created a directory named `~`](https://github.com/yarnpkg/yarn/issues/2008), the completion doesn't escape the tilde character.

So imagine you're typing `rm -rf <TAB><TAB>`, it will produce `rm -rf ~/` which is not quite what you had in mind.

**Comment by bmwalters** [comment] 2018-02-04 21:42
I ran into this issue today (Fish 2.7.1), and was ready to file a new issue report when I found this one. Here's  my writeup.

[![asciicast](https://asciinema.org/a/7ZZIdlEE1gEsZQ7CPelp0EO4T.png)](https://asciinema.org/a/7ZZIdlEE1gEsZQ7CPelp0EO4T)

This can cause a surprising behavior when interacting with a file named `~<your username>` and selecting it using tab completion. Since the `~` is not escaped, the resulting command will reference `~<your username>` which Fish helpfully expands to your home directory.

Notice that the tilde is actually escaped in the list of completion suggestions before selecting one, oddly enough.

**Comment by Profpatsch** [comment] 2018-02-05 11:38
> the resulting command will reference ~<your username> which Fish helpfully expands to your home directory.

Hooooo, boy. That’s bad.

**Comment by ridiculousfish** [comment] 2018-02-17 23:31
This should be fixed in 01d87455e1dd06df4340f3f5181276bed8e71823. Thanks for filing!

**Closed** 2018-02-17 23:31 UTC
Labels: bug

**Comment by XenGi** [comment] 2018-06-25 15:32
Which fish release will include that fix? Is there a schedule for 2.7.2?

**Comment by faho** [comment] 2018-06-25 16:19
>Which fish release will include that fix?

@XenGi: Like the milestone says, 3.0. Which is the next release and expected in the near future.

>Is there a schedule for 2.7.2?

No. We don't have the man power to maintain multiple release branches.

**Comment by XenGi** [comment] 2018-06-25 16:24
ah. didn't see that. thx!
