### ISSUE TITLE
Add standard unix tool completion by default

### ISSUE THREAD

**Issue by creack** [fish-shell/fish-shell#1375] opened 2014-03-28 17:24 UTC
It would be nice if fish could ship by default with common unix tools completion:
Non exhaustive list, but the most important I think:
- ip
- ~~iptables~~
- ~~ifconfig~~
- brctl*
- ~~mount / umount*~~
- tcpdump*
- ~~sysctl~~
- ~~gcc*~~

(marked *: nice to have, others seem like must have)

**Comment by faho** [comment] 2015-07-16 16:23
I've gotten a bit of progress with iptables as well, and I have even tried ip.

The main issues there are that

a) Some things we just can't complete properly, like ip addresses (see #2201)

b) Fish likes to complete files when all it can offer are options (so e.g. `iptables -A INPUT <TAB>` will show all the crap in pwd, but not the "-m" or "-j" that would be actually helpful) (see #112 and #379)

c) `ip`'s syntax sucks. Rotten caviar. (which makes a good completion all the more helpful, I guess)

(though I wouldn't call any of these "standard UNIX tools", they are pretty linux-specific AFAIK)

If anyone wants to take a look, see [my WIP-completions branch](https://github.com/faho/fish-shell/tree/WIP-completions) (WARNING: I may force-push on that one)

**Comment by faho** [comment] 2015-08-05 19:10
iptables is now included in a Work-In-Progressy-form, I've shelved `ip` for now.

I will edit @creack's post to strike them through.

**Comment by oni303** [comment] 2016-05-18 12:43
Hi,

I just started very basic completion for [ip](https://github.com/oni303/fish-ip-completion).
If you think it is useful I will send a pull-request. 
It is not that fancy yet but it is able to suggest interfaces directly after "dev" and to suggest some objects and commands if a object was uses before. Also a some options are available.

**Comment by faho** [comment] 2016-05-18 20:24
@oni303: I have a very basic completion ready myself. The issue is making something useful. Ip's syntax does _not_ gel well with our current system (or basic taste, really).

**Comment by oni303** [comment] 2016-05-19 08:38
well, I experienced that the current system is not optimal to handle ip`s syntax.
I think having a basic completion is better than none, especially for interface name if your machine has more than two interfaces.

**Comment by faho** [comment] 2016-05-19 11:26
I've now committed a half-working ip completion. For `ip address`, it should be working okay.

Since every must-have has been fulfilled, I'm closing this.

**Closed by faho** 2016-05-19 11:26 UTC
Labels: completions, enhancement
