### ISSUE TITLE
strange error when opening new terminal

### ISSUE THREAD

**Issue by EricG-Personal** [fish-shell/fish-shell#6629] opened 2020-02-20 02:00 UTC
fish, version 3.1.0
Darwin ericgs-iMac.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
xterm-256color

When I create a new terminal, I am now seeing:

```
Last login: Wed Feb 19 20:51:28 on ttys000
source: Error encountered while sourcing file '/var/folders/tl/789tp6ms2vv3dmkz6h_bchbc0000gn/T//.psub.Il9Va4hHfx':
source: No such file or directory
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

when I try:

```
$ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```

Any idea what might be going wrong?

This does appear to be related to the fish shell as if I change to a different shell, I do not see the same error message.

**Comment by floam** [comment] 2020-02-20 03:04
Duplicate of #6613

**Closed by floam** 2020-02-20 03:04 UTC
