### ISSUE TITLE
Fish fails to build on CentOS7 due to pcre2-10.20 configured with autotools 1.15

### ISSUE THREAD

**Issue by tannerb** [fish-shell/fish-shell#2469] opened 2015-10-09 02:34 UTC
pcre10.20 is configured with autotools 1.15, causing fish build to fail, as CentOS7 is on autotools 1.13

./configure in pcre2-10.20 solves the issue

**Comment by ridiculousfish** [comment] 2015-10-09 03:07
I'm confused - ./configure in the pcre directory is normally run as part of the build process, right?

**Comment by zanchey** [comment] 2015-10-09 04:12
It certainly should be - 3ffbf9a7ea added `AC_CONFIG_SUBDIRS([pcre2-10.20])` to the configure script.

Unfortuantely, git doesn't store last-modified timestamps, and so if the `configure.ac` checkout time is newer then `aclocal.m4` the PCRE2 build system tries to update the various files by running the aclocal version it is expecting to find.

The right way to fix it is to run `autoreconf` in the main source directory, rather than `autoconf` as suggested in the README. That will pick up the subdirectory from `configure.ac`. However, in 09ff1e7a there's a note that `autoreconf` is less than desirable on OS X.

**Comment by ridiculousfish** [comment] 2015-10-09 05:14
I was able to reproduce with a fresh checkout and a vagrant box.

**Comment by zanchey** [comment] 2015-10-09 06:35
I think the only viable option is to require automake of some description, and to use `autoreconf` instead of `autoconf` when doing development builds. Is there a reason this isn't plausible on OS X?

**Comment by ridiculousfish** [comment] 2015-10-09 07:02
Maybe this is a dumb question, but...can we just run automake on a system with 1.13 and check the result (aclocal.m4, configure, etc.) into the repo?

**Comment by zanchey** [comment] 2015-10-09 07:08
It's not really the Right Thing but it would work - I'm happy with that.

**Comment by zanchey** [comment] 2015-10-09 11:53
What am I saying? No, that will still add a dependency on automake, at which point we're in the same place except the PCRE2 will configure itself twice.

**Comment by ridiculousfish** [comment] 2015-10-09 20:04
To make sure I understand correctly: that would allow CentOS7's automake to work, but the goal is to allow building without automake installed at all?

**Comment by zanchey** [comment] 2015-10-15 09:20
That's not even required to make CentOS' automake work - all that requires is changing `autoconf` to `autoreconf` in the build steps. Ideally, shipping the artifacts of automake in the tree would drop the dependency on automake entirely. Unfortunately, git doesn't store enough metadata to make this reliable.

**Comment by zanchey** [comment] 2016-02-24 02:29
@ridiculousfish, is there a reason that we shouldn't run `autoreconf` on OS X - particularly now that that's only required with the Homebrew build and Autotools aren't shipped by Xcode on OS X any more?

**Comment by ridiculousfish** [comment] 2016-02-24 03:07
Running autoreconf on OS X sounds fine to me.

**Comment by zanchey** [comment] 2016-02-24 10:19
This is actually much easier than I thought - by turning on autotools' maintainer mode, it doesn't try to rebuild the build artefacts in the PCRE2 directory, which fixes the problem.

**Comment by ridiculousfish** [comment] 2016-02-24 23:03
Nice!!

**Comment by jaseg** [comment] 2016-03-22 11:48
Even though this fix is in master now, I just had this very same problem on a fresh (master) checkout on a pretty fresh debian (stable) install. Running ```autoreconf -f -i -m``` in ```pcre2-10.20``` fixed it for me. Possible regression? Did someone accidentially re-commit a broken Makefile?

**Comment by zanchey** [comment] 2016-03-22 13:48
It still works OK for me, on a fresh checkout on various platforms. Are you running `autoreconf` or `autoconf` before you run `./configure`?

**Comment by jaseg** [comment] 2016-03-22 14:00
I was running ```autoconf``` from the fish source tree, not ```autoreconf```. I just tried and the latter fixes the problem. It seems, somewhere in the pcre tree there are remains of a previous build leftover that ```autoreconf``` will clean up, but ```autoconf``` will not.

**Comment by zanchey** [comment] 2016-03-29 09:26
You shouldn't need `autoreconf` at all - that's the idea behind the `--enable-maintainer-mode` in the invocation contained in `configure.ac`/`configure`.

I can't reproduce the problem on my CentOS 6/7 installs with either the git source tree or the nightly tarballs.

**Comment by floam** [comment] 2016-04-01 08:43
Why isn't pcre2 hooked into autoconf with AC_CONFIG_SUBDIRS?

**Comment by zanchey** [comment] 2016-04-01 09:17
> Why isn't the pcre2 directory just hooked into autoconf with AC_CONFIG_SUBDIRS?

It is.

Interestingly, I'm now not convinced that the fix I merged actually works in the way I intended it to - I'll have more of a look over the weekend.

**Comment by floam** [comment] 2016-04-01 11:35
> It is.

Doh! I've never seen `--enable-maintianer-mode` used on config.status - I must have thought I was looking at ./configure being called manually and assumed that it wasn't set up right.

**Comment by zanchey** [comment] 2016-04-07 03:06
OK, so, here are the options:

 - Take a dependency on automake, remove the PCRE2 autotools artefacts from the repository, modify the build scripts to run `autoreconf` and change the README. The disadvantage is that it requires all contributors to have automake installed, that different versions of autotools might produce different output and cause problems, and that we are solving the problem with autotools by adding more autotools.

- Remove the pcre2 directory and instead ship the release tarball, with the configure script extracting it if required - this is how we used to ship xsel. It is difficult to do this cleanly and means shipping a binary blob in the repository and tarball.

- Ask everyone to install a post-receive git hook which updates the timestamps on the PCRE2 build artefacts... that's pretty much never going to happen.

- Add `AM_MAINTAINER_MODE` to the PCRE2 automake/autoconf files, rebuild the generated files and commit them. This is my preferred option, as it's using the Autotools option designed specifically for this scenario, and is easy to forward port. It works by setting up maintainer mode and disabling it by default, so that the autoconf/automake artefacts don't get regenerated without specific instruction to do so.

I'm going to implement the fourth option above for now, although I'd be keen to hear other perspectives. `AM_MAINTAINER_MODE` is largely considered harmful for upstream projects to be shipping, but I think it's appropriate for us.

**Comment by zanchey** [comment] 2016-04-07 03:09
e1e1e558ce3191dcbda451 implements `AM_MAINTAINER_MODE`.

**Comment by zanchey** [comment] 2016-04-07 03:10
@jaseg, @tannerb, could you see if you can reproduce the problem on a new checkout?

**Comment by jaseg** [comment] 2016-04-07 10:36
Works for me now. Thank you.

**Comment by zanchey** [comment] 2016-04-08 02:50
Thanks @jaseg - I'll close this for now.

**Closed by zanchey** 2016-04-08 02:50 UTC
Labels: bug, packaging
