### ISSUE TITLE
Autocompletion after non-whitespace separators

### ISSUE THREAD

**Issue by jonclayden** [fish-shell/fish-shell#2178] opened 2015-07-10 11:38 UTC
The current fish release, and `master`, do not seem to allow path autocompletion after non-whitespace separators such as `=` and `:`. For example if I type

    env VAR=/usr

and then press `<TAB>`, I would expect to be able to autocomplete the path. This works fine in `bash`, but I miss it in `fish`. If I've broken something locally then I'm sorry, but if not, please consider this a feature request... :)

**Comment by faho** [comment] 2015-07-14 16:05
This is a duplicate of #2066, although I do like the (implied) larger scope.

For example it would be nice to be able to write a proper [journalctl](http://www.freedesktop.org/software/systemd/man/journalctl.html) completion - currently I don't know how I could coax fish to complete `journalctl PROPERTY=<TAB>`, even though I can get a full list of values (with "--field=").

**Comment by jonclayden** [comment] 2015-07-14 16:15
Sorry for the duplicate; I did search first, but missed the issue you mention. Another relevant example would be

    git show branch:<TAB>

with the expectation of completing paths after the colon. Again, `bash` allows this.

**Comment by faho** [comment] 2015-07-14 18:27
Soo... I've now done something like this in PR #2203, but it's a bit hacky, and it needs patches to every single affected completion.

**Comment by zanchey** [comment] 2015-07-24 10:44
You can do this sort of thing "by hand", with `__fish_complete_path` and friends, but it could be easier.

**Comment by ridiculousfish** [comment] 2015-07-24 17:30
We should just do this. I'm surprised it doesn't already work.

**Comment by ridiculousfish** [comment] 2015-07-27 20:45
Previously, the = separator was supported but only for tokens that started with two dashes. In 85dad6913e77d81730f3aea478695429f441ebd5 we support = and : separators unconditionally. Thanks for filing this.

**Closed** 2015-07-27 20:44 UTC

**Comment by jonclayden** [comment] 2015-07-27 21:10
Great to see this implemented - thanks!
