### ISSUE TITLE
Backgrounding of blocks doesn't work quite right.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1148] opened 2013-11-29 14:30 UTC
If I press CTRL+Z while block executes, it tries to run next commands, without waiting for the job to continue. This bug also exists in bash, but it doesn't in zsh.

```
~ $ jobs
jobs: There are no jobs
~ $ begin
        sleep 60 # CTRL-Z before it finishes
        cd /
    end
Job 1, 'sleep 60 # CTRL-Z before it finishes' has stopped
/ $ fg
Send job 1, 'sleep 60 # CTRL-Z before it finishes' to foreground
```

**Comment by krader1961** [comment] 2017-03-18 05:27
This is closely related to not being able to background fish functions. That is, arbitrary blocks of fish code. Closing as a duplicate of issue #238.

**Closed by krader1961** 2017-03-18 05:27 UTC
Labels: duplicate
