### ISSUE TITLE
Key bindings are not executed in the specified order

### ISSUE THREAD

**Issue by mamiu** [fish-shell/fish-shell#7419] opened 2020-10-24 16:20 UTC
Some key bindings are not executed in the correct order. The [doc says](https://fishshell.com/docs/current/cmds/bind.html):

> When multiple `COMMAND`s are provided, they are all run in the specified order when the key is pressed.

Here's an example to reproduce that issue:

```fish
bind \cc 'commandline -f beginning-of-line; commandline -i "# "; commandline -f execute'
```

It's not working on my MacBook Pro as well on the Ubuntu server:

fish version: 3.1.0 and 3.0.2
`echo $TERM`: xterm-256color
`uname -a`:
 - `Linux server.com 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - `Darwin my-mbp.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin`

**Comment by faho** [comment] 2020-10-24 16:22
No, the commands are executed in that order, it's just that `commandline -f`` *queues up* bind functions, and they're only executed once fish gets to it, while `commandline -i` just acts immediately.

That makes this a duplicate of #3031.

**Closed by faho** 2020-10-24 16:22 UTC

**Comment by faho** [comment] 2020-10-24 16:23
Also this looks like you just want ` __fish_toggle_comment_commandline`, bound to alt+# by default, which already does the right thing here.
