### ISSUE TITLE
Using the abbr functions throws an error using `fish -n`

### ISSUE THREAD

**Issue by MindTooth** [fish-shell/fish-shell#4991] opened 2018-05-17 10:09 UTC
## Issue

Hi,

I've noticed when using `fish -n` that I get a syntax error with the `abbr` command.  _(First noticed via `ale` for Vim)_.

I reread the [docs](https://fishshell.com/docs/current/commands.html#abbr) and searched the issue tracker for mistakes I may have made, etc.  But it seems to follow the correct syntax.

Note!  It functions as normal, but I thought I would ask if this were a bug, or if I've made mistake.

## Clean output
```sh
mt@MindBookPro /U/mt> fish -n .config/fish/conf.d/aliases.fish 
.config/fish/conf.d/aliases.fish (line 23): 
  abbr --add src 'pushd ~/Source'
  ^
```

### abbr section
```fish
if status --is-interactive
  set -g fish_user_abbreviations
  abbr --add src 'pushd ~/Source'
end
```

### Complete file
It's a mess right now, as I try navigation between the different ways to deal with shortcuts.
```fish
# Reload config.fish to activate changes
alias rf 'source ~/.config/fish/config.fish'

# Fast config edit
function e -w vim -d 'editor shorthand'
  vim $argv
end
alias ea   'vim ~/.config/fish/conf.d/aliases.fish'
alias ef   'vim ~/.config/fish/config.fish'
alias eg   'vim ~/.config/git/config'
alias ek   'vim ~/.config/kitty/kitty.conf'
alias en   'vim ~/.config/newsboat/config'
alias et   'vim ~/.tmux.conf'
alias ev   'vim ~/.vimrc'

if status --is-interactive
  set -g fish_user_abbreviations
  abbr --add src 'pushd ~/Source'
end

alias vi   'vim'

# brew aliases
# alias bri  'brew install'
# alias bri  'brew install'
function bri -w 'brew install' -d 'brew install'
  brew install $argv
end
alias brii 'brew info'
alias brl  'brew list -1'
alias brr  'brew remove'
alias brs  'brew search'
alias brci 'brew cask install'
alias brcii 'brew cask info'
alias brcl 'brew cask list -1'
alias brcr 'brew cask uninstall'
alias brcs 'brew cask search'

# Quick software launch
alias nb   'newsboat'
```

## System
```sh
$ fish --version
$ fish, version 2.7.1-1181-g18a163dc
```
```sh
$ echo $version
$ 2.7.1-1181-g18a163dc
```

## Sceenshots

[![asciicast](https://asciinema.org/a/90p8L2D76en0OgIKGpeCJxGNw.png)](https://asciinema.org/a/90p8L2D76en0OgIKGpeCJxGNw)

`ale` reporting issues.
<img width="859" alt="screen shot 2018-05-17 at 12 00 33" src="https://user-images.githubusercontent.com/33870508/40170870-ef574926-59c9-11e8-839b-b835a3ad2367.png">

<img width="859" alt="screen shot 2018-05-17 at 11 57 01" src="https://user-images.githubusercontent.com/33870508/40170705-7292f1b0-59c9-11e8-8ea2-5ddd5fd4f2a5.png">

**Comment by faho** [comment] 2018-05-17 11:06
Duplicate of #977 - `abbr` is a function, and `fish -n` does not autoload functions.

**Closed by faho** 2018-05-17 11:06 UTC
