### ISSUE TITLE
find doesn't work properly

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#2840] opened 2016-03-21 19:01 UTC
Find doesn't work properly based on their man page. Solution is to escape the `{}`

this is a bit dodgy and I guess we can blame find's manpage but ...

### Reproduction Steps:

1. run `find . -type f -exec echo {} \;` in a directory with just single file (or anywhere, but this illustrates the problem)

### Expected behavior:

it should print the files in the directory

### Observed behavior:

it prints blank lines

### Additional information:

happens all the time

---
Fish version: 2.2.0-692-g168a156

Operating system: 
Darwin Kernel Version 15.4.0 (El Capitan 10.11.4)
installed from source `autoconf && make && make install`

Terminal or terminal emulator: iTerm2

**Comment by faho** [comment] 2016-03-21 19:10
Hi, this is a duplicate of #1109 - fish expands braces even if there is nothing in them, so you're executing `echo`, without arguments everytime.

**Comment by faho** [comment] 2016-03-21 19:11
Sorry, 1109 is also a dup of #434.

**Closed by faho** 2016-03-21 19:10 UTC
