### ISSUE TITLE
24bit colors forced even if 256 are set for the terminal

### ISSUE THREAD

**Issue by c10b10** [fish-shell/fish-shell#3720] opened 2017-01-10 16:00 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**:  MacOs 10.12.2, iTerm 3.0.13

* `set_color` always uses 24bit for colors instead of 256 even if $TERM is set to `xterm-256color`
* `tput colors` returns `256`
* tried setting `fish_term256` to `1`

What am I missing?

**Comment by faho** [comment] 2017-01-10 16:23
You can `set -e fish_term24bit` or `set fish_term24bit 0`.

However, the question is why you want this? 24bit is obviously more accurate than 256 colors.

**Comment by c10b10** [comment] 2017-01-11 11:34
Tried setting it fish_term24bit to 0, still doesn't work. 

Additionally, - I might be wrong in thinking this - I'm under the impression that if I don't build it on 256, I might have a hard time when I install it on VPS machines. Is this wrong? 256 refers to the capability of the terminal app, not the shell, right?

It's easier for me to experiment with colors, because I can just list all of them in the terminal.

**Comment by faho** [comment] 2017-01-11 15:12
So, here's what happens here:

```fish
~► set_color ABE | od -t x1z
0000000 1b 5b 33 38 3b 32 3b 31 37 30 3b 31 38 37 3b 32  >.[38;2;170;187;2<
0000020 33 38 6d                                         >38m<
0000023
~► set fish_term24bit 0
~► set_color ABE | od -t x1z
0000000 1b 5b 33 38 3b 35 3b 31 34 37 6d                 >.[38;5;147m<
0000013
```

>256 refers to the capability of the terminal app, not the shell, right?

Well, yes. But terminfo (what `tput` uses) doesn't support a "truecolor" entry (well, there is one, but it's not widespread enough to use), so we use a different heuristic to determine if a terminal can do it. iTerm can do it, so we enable it when we think we're in iTerm. That $TERM is set to "xterm-256color" isn't meaningful here, since

- That's the iTerm default (in fact it's the default for most terminals)

- iTerm can do it, but xterm (which has the same $TERM) can't

- There is no "xterm-truecolor" entry or similar

If fish uses truecolor by default and your terminal doesn't support it, that's a bug in fish.

If fish still uses truecolor even though you've set the variable to 0 or unset it, that's a bug in fish.

If fish uses truecolor by default and your terminal can handle it (as is the case with iTerm), that's working as intended.

>I'm under the impression that if I don't build it on 256, I might have a hard time when I install it on VPS machines. Is this wrong? 

I'd say so, yes. As I said above, we should disable truecolor if your terminal doesn't support it. Of course if you use e.g. ssh and your client terminal can do it, then you should have truecolor support. If you don't, your colors might be slightly different, but that's only because truecolor gives us more precision. In practice, if you're really particular about your colors, you'll want truecolor.

**Comment by faho** [comment] 2017-01-16 08:46
@c10b10: What's happening in your shell when you change $fish_term24bit?

**Comment by c10b10** [comment] 2017-01-17 14:21
I will get back to you tomorrow.

**Comment by krader1961** [comment] 2017-02-02 07:05
Ping? Is this still an issue for you @c10b10?

**Comment by c10b10** [comment] 2017-02-02 12:25
I have worked around the issue by converting the 256 code colors to 24bit code, but it seems to me that the fish uses true color even if is set it to 0.

<img width="227" alt="screen shot 2017-02-02 at 14 25 26" src="https://cloud.githubusercontent.com/assets/306633/22549323/7912af18-e953-11e6-8c01-334783b23eba.png">

**Comment by faho** [comment] 2017-02-02 12:48
Then let me ask some questions:

- Why do you not want truecolor?

- What does `set_color ff5f00 | od -t x1z` say? 

For me, the sequence that set_color outputs changes depending on the value of fish_term24bit, so it seems to work as intended. Note that even with truecolor disabled, fish will accept hex-values as arguments to `set_color`, only it will then map them to the nearest supported color from the 256 color palette (or 88 colors, or 16 colors, or 8 or whatever your terminal supports).

**Comment by c10b10** [comment] 2017-02-02 23:20
At this point I don't really care if it's true type or not, I wanted 256 for ease of experimentation for my themes.

```sh
❯ set_color ff5f00 | od -t x1z
od: z: unrecognised format character
```

**Comment by krader1961** [comment] 2017-02-02 23:25
Yeah, some `od` implementations are still from the bronze age of computing. If you have `xxd` use that otherwise just `od -b`.

**Comment by c10b10** [comment] 2017-02-04 09:17
<img width="476" alt="screen shot 2017-02-04 at 11 17 20" src="https://cloud.githubusercontent.com/assets/306633/22617362/8882c25c-eacb-11e6-8053-90c6f84cb299.png">

**Comment by faho** [comment] 2017-02-04 10:15
That's `\e[38;5;202m` - i.e. the 256-color sequence.

That means this is working as intended in just about every respect.

**Comment by krader1961** [comment] 2017-02-04 17:19
@c10b10: You misunderstood me. I meant for you to use the `xxd` command, not use that as an option to `od`; e.g.,:

```
$ set_color ff5f00 | xxd
00000000: 1b5b 3338 3b32 3b32 3535 3b39 353b 306d  .[38;2;255;95;0m
$ set_color ff5f00 | od -ba
0000000 033 133 063 070 073 062 073 062 065 065 073 071 065 073 060 155
        esc   [   3   8   ;   2   ;   2   5   5   ;   9   5   ;   0   m
0000020
```

The problem with `od -tx` is it reorders the bytes if your system is little-endian (which is true for Intel X86 processors) but not if it's big-endian (such as PowerPC). In any event that output told us what we needed to know.

@c10b10: Note that the output I showed above is what you would get if 24-bit color sequence was written. As @faho noted you are seeing the 256 color sequence. Which I've reproduced below. So both @faho and I are confused as to what the problem is. Fish seems to be working as advertised.

```
$ set fish_term24bit 0
$ set_color ff5f00 | od -ba
0000000 033 133 063 070 073 065 073 062 060 062 155
        esc   [   3   8   ;   5   ;   2   0   2   m
0000013
$ set_color ff5f00 | od -tx
0000000 38335b1b 323b353b 006d3230
0000013
```

**Comment by faho** [comment] 2017-02-09 18:06
@c10b10: Since everything seems to work, I'm going to close this.

If anything doesn't, feel free to reopen!

**Closed by faho** 2017-02-09 18:06 UTC
Labels: question
