### ISSUE TITLE
Syntax highlighting for output of functions <function>

### ISSUE THREAD

**Issue by lordlycastle** [fish-shell/fish-shell#2608] opened 2015-12-13 06:22 UTC
There should be syntax highlighting for `type` when used with function argument. It would really improve readability. There is currently support for `function` so shouldn't be that difficult to implement.

**Comment by pickfire** [comment] 2015-12-13 06:48
Do you mean to highlight something like `sudo` and `command` differently?

**Comment by faho** [comment] 2015-12-13 13:12
@pickfire: Red is already used to signify unknown commands, so that'd be confusing. Plus, this is about the _argument_ to `type` being colored differently.

I'm not actually sure why `function banana` makes the banana look differently than `type aaaa`.

**Comment by lordlycastle** [comment] 2015-12-13 19:18
No. I was talking about syntax highlighting of the function which is output when you do `type my_function`. Rather than it all being monochromatic, it would better to have it highlighted, similar to when you're editing/creating that function.

**Comment by ridiculousfish** [comment] 2015-12-13 20:30
I suppose `functions` could pipe through fish_indent when output is to a tty.

**Comment by pickfire** [comment] 2015-12-14 02:53
@faho: What about Orange? Or like what you say banana -> Yellow (but I think it looks weird).

@lordlycastle, isn't `type` highlighted in dark blue and `my_function` highlighted in light blue?

**Comment by adamcavendish** [comment] 2015-12-14 09:48
I don't understand, @lordlycastle . `functions ls` does not give us syntax highlighting, I believe.

**Comment by lordlycastle** [comment] 2015-12-14 10:12
I just had a quick read through `type`, and it uses `functions` to print the definitions. So I would like `functions` to have syntax highlighting, in the __output__, instead. Anyhow, to clear the confusion up, as you all can see in the screen below, when functions definition printed through `type`/`functions` it's all white, I would like that to be similar to what's show below it. It helps in reading large functions significantly.
![screen shot 2015-12-14 at 11 00 27](https://cloud.githubusercontent.com/assets/11729541/11777989/ecf19a2e-a251-11e5-8da1-0242231e5bc4.png)
@ridiculousfish I tried piping through `fish_indent` didn't seem to do any good.

**Comment by faho** [comment] 2015-12-14 10:17
>I tried piping through fish_indent didn't seem to do any good.

`fish_indent --ansi` - see the "--help" output.

**Comment by pickfire** [comment] 2015-12-14 13:27
@lordlycastle Weird, mind seems different from yours.

![2015-12-14-212704_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/11782058/704bb2c2-a2a9-11e5-81a9-cfcef3c063ed.png)

**Comment by adamcavendish** [comment] 2015-12-14 15:29
I think @faho means this:

![type_syntax_highlight](https://cloud.githubusercontent.com/assets/1346161/11785002/6cac0dcc-a2ba-11e5-9144-0ae07cf7298b.png)

**Comment by pickfire** [comment] 2015-12-15 00:12
That fails with the same error too.

**Comment by adamcavendish** [comment] 2015-12-15 05:25
@pickfire Looks like your shell does not regard itself being interactive in the terminal. What terminal are you using? And probably you can think of reinstalling / rebuilding your shell from source.

**Comment by pickfire** [comment] 2015-12-15 06:37
@adamcavendish I did build it from source. I am using `st-256color` which support true colors.

I did build it from source using `pkgbuild`.

**Comment by adamcavendish** [comment] 2015-12-19 03:01
@pickfire Weird enough, I cannot reproduce your bug.

**Comment by faho** [comment] 2016-02-26 11:45
Ooh, this is a duplicate of #2059!

**Closed by faho** 2016-02-26 11:45 UTC
