### ISSUE TITLE
`fish_config` doesn't work in WSL (again?)

### ISSUE THREAD

**Issue by wesalvaro** [fish-shell/fish-shell#7688] opened 2021-02-07 09:23 UTC
I just installed Ubuntu 20.04 WSL and the first thing I did was install fish.

It seems like there was an issue before with detecting WSL.
Is this a dup that has not been released, yet?  
If so, sorry for the noise.

When I run `fish_config` the screen blanks.  
Sometimes an error would flash so I redirected the output to a file.  
Below is what I got:

```
$ fish_config 2> error.log
^C
Shutting down.
$ cat error.log
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "file:///tmp/web_config4nbg7j1w.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

$ fish --version
fish, version 3.1.2
$ uname -a
Linux DESKTOP-MH8DK7I 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

**Comment by wesalvaro** [comment] 2021-02-07 09:24
Oh, I think this is a dup of #7027

**Comment by faho** [comment] 2021-02-07 09:37
Duplicate of #7027

**Closed** 2021-02-07 09:36 UTC
