### ISSUE TITLE
Add option not to search for the current commandline when searching history

### ISSUE THREAD

**Issue by anakimluke** [fish-shell/fish-shell#8663] opened 2022-01-22 23:59 UTC
Often I'm working on a command and want to go up the command history.

Fish doesn't allow that. You'd have to delete everything in the line you are working on and *then* trigger `history-search-backward` to get a similar behavior.

Here's a workaround code I figured:
```fish
function history-search-go-back-once
    if not commandline --search-mode
        commandline ""
    end
    commandline --function history-search-backward
end
# binds up key
bind \e\[A history-search-go-back-once
```
I suggest for a function like the above to be added to fish's repertuar.

Additionally, one could consider adding the feature of saving the original line that was being worked on, and restoring it if the user goes *forward* in history up to the end. Bash behaves like this.

I'm not sure what the behavior should be when the user is navigating the history and then decides to modify an entry:
1. Do it like bash: Changes to entries while navigating history are kept; the user can move back and forth to modify several lines. Entries that have been edited receive a mark.(see bash's `mark-modified-lines`) 
2. Quit search mode and discard the original copy of the line that was being worked on.

I'd prefer (2) because I find the mark distracting and, if disabled, may lead the user into thinking they had issued a command that they actually had not.

**Comment by faho** [comment] 2022-01-23 08:11
Duplicate of #602

**Closed by faho** 2022-01-23 08:11 UTC

**Comment by anakimluke** [comment] 2022-01-23 13:12
@faho Are you sure it's a duplicate? The request is related to, but different than reverse incremental search. ;)
