### ISSUE TITLE
Nested script run as other user

### ISSUE THREAD

**Issue by Campano** [fish-shell/fish-shell#3019] opened 2016-05-10 13:56 UTC
While trying to execute a bash script which included a `su user otherscript.sh` command, the other script would not work as expected.

### Reproduction Steps:

1. Make fish your default shell so /bin/sh redirects to fish
2. Create the following test scripts:
```
user@machine~/d/fishtest> ls -l
total 16
-rwxrwxr--  1 user  staff   31 May 10 15:28 1.sh
-rwxrwxr--  1 user  staff  114 May 10 15:38 2.sh
user@machine~/d/fishtest> cat 1.sh
#!/bin/sh
su user 2.sh
user@machine~/d/fishtest> cat 2.sh
#!/bin/sh
# Better OS/400 detection: see Bugzilla 31132
os400=false
case "`uname`" in
  OS400*) os400=true;;
esac
user@machine~/d/fishtest> ./1.sh
Password:
'case' builtin not inside of switch block
~/dev/fishtest/2.sh (line 4): case "`uname`" in
                              ^
fish: Error while reading file /Users/user/dev/fishtest/2.sh
```
3. execute 1.sh

The first script executes the second script with the default shell for this user. If it's configured to be fish, not matter what command you use to execute the first script, the second one will use fish and crash.

### Expected behavior:

There should be a command to execute a bash script whith /bin/sh redirecting to bash. 

### Additional information:

Not sure if this is a os x issue or a fish one, but the result was clearly an annoyance so I had to switch to bash unitl I found a solution. I "fixed" the problem by resetting my default shell to bash, but telling Apple Terminal to open the shell with a command to fish instead of using the default shell...
  

---
Fish version: 2.2.0

Operating system: OS X 10.11.4, installed via homebrew

Terminal or terminal emulator: Apple_Terminal

**Comment by krader1961** [comment] 2016-05-10 21:38
> Make fish your default shell so /bin/sh redirects to fish.

I can't make sense of that sentence. Making fish your default shell does not affect the behavior of /bin/sh in any way; unless, of course, you've manually done something like `rm /bin/sh; ln -s /usr/local/bin/fish /bin/sh` which is guaranteed to make you system unusable. But I'm pretty certain that's irrelevant since you probably just mean you ran `chsh -s /usr/local/bin/fish user`.

The behavior you're seeing has nothing to do with fish. It's a consequence of how the `su` command behaves. It's simply passing any arguments after the user name to the login shell for the account. Which means it's doing the same thing as if you had simply typed `fish 2.sh`. Since 2.sh isn't a valid fish script you get the error you're seeing. You'd have the same problem if you changed your login shell to any shell that wasn't 100% POSIX compatible (e.g., `/bin/csh`).

You're probably wondering why the shebang line is being ignored. Again, that's the expected behavior in this scenario. If you run any shell (csh, zsh, etc.) and give it a file name (e.g., `csh 2.sh`) it will simply open the file and attempt to process the content. You have to tell the shell to treat the script as a command for the shebang line to have any effect: `csh -c 2.sh`. And `su` never passes the `-c` flag.

The solution is to use `sudo` rather than `su`.

**Comment by ridiculousfish** [comment] 2016-05-11 01:59
Yes, as krader says, `su` invokes the target user's login shell by default, passing it the argument. So the #!/bin/sh shebang is ignored.

You can override this with `--shell`:

    su --shell /bin/sh user ./2.sh

but if you want to run a script, instead of logging in, you should probably use `sudo`:

    sudo -u user ./2.sh

this will use the shell specified in the shebang.

Closing as it's not a fish issue. Thanks for filing this!

**Closed by ridiculousfish** 2016-05-11 01:59 UTC
Labels: question

**Comment by krader1961** [comment] 2016-05-11 02:21
FYI for future readers of this issue the OS X (and presumably other BSD variants) version of `su` doesn't support the `--shell` flag. Too, it seems to me the `--shell` flag is a bogosity since there is absolutely no reason the user should be expected to know a) the file is a script rather than a binary executable, and b) which interpreter is appropriate to interpret the script. In other words: never use `su` for anything other than to obtain an interactive shell. Any other use should be replaced by the `sudo` command.

**Comment by Campano** [comment] 2016-05-11 08:48
Thank you very much for the clarifications.
