### ISSUE TITLE
set not assigning properly

### ISSUE THREAD

**Issue by suuuehgi** [fish-shell/fish-shell#5307] opened 2018-11-01 11:43 UTC
From a users perspective, I would consider this a bug:

```
> function t
        echo (count $argv)
        and if [ (count $argv) > 2 ] 
            set options $argv[2..-2]
        else
            set options ""
        end
        echo $options
    end
> t test1 test2
2
test2 test1
```

Did I miss something?

```fish
> fish --version
fish, version 2.7.1
> uname -a
Linux hostname 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
> echo $TERM
xterm-termite
```
Without customizations, `sh -c 'env HOME=$(mktemp -d) fish'` does not change the outcome.

**Comment by zanchey** [comment] 2018-11-01 11:55
What behaviour are you expecting?

The first problem I notice with your script is that this test invocation:
```
if [ (count $argv) > 2 ]
```

is wrong; it should be `if [ (count $argv) -gt 2 ]` - otherwise you are redirecting the output.

**Comment by faho** [comment] 2018-11-01 16:41
Duplicate of #4897 

This is fixed in git. Now if only the end is negative we force going forward, and if only the start is we force going backward.

**Comment by faho** [comment] 2018-11-01 16:41
Duplicate of #4897

**Closed by faho** 2018-11-01 16:41 UTC
