### ISSUE TITLE
completions: fixup wg-quick completions

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#9033] opened 2022-06-23 05:06 UTC
Actually it looks like that works for non-root too, so we can just get rid of the kluge altogether:

```sh
>wg show
Unable to access interface mlvd-ch2: Operation not permitted
[1]>wg show interfaces
my_wg_interface
```

_Originally posted by @ammgws in https://github.com/fish-shell/fish-shell/pull/8687#discussion_r904522552_

**Comment by faho** [comment] 2022-06-28 16:06
Duplicate of #8954

**Closed by faho** 2022-06-28 16:06 UTC
