### ISSUE TITLE
`history --delete` command does not work as documented

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#3270] opened 2016-07-27 12:27 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1-421-g49008d7

**OS/terminal used**: 4.6.4-1-ARCH termite v11

The following behavior is documented:

> -d or --delete deletes history items. Without the --prefix or --contains options, the **exact match** will be deleted. With either of these options, a prompt will be displayed before any items are deleted asking you which entries are to be deleted.

But it is not doing an exact match.

I had a command that did the following on the event `fish_prexec`:

```
history --delete fg bg
```

This was working until I upgraded my fish version the other day and then every command execution got presented with the list to delete matching entries.

Is there a way to silently drop commands from the history based on exact matches?

## Reproduction steps

1. Launch fish
2. `ls`
3. `ls -la`
4. `history --delete ls`

## Expected results
Fish should only delete the entries matching `ls` exactly.

## Actual results
Fish is displaying of list of all the matches containing `ls`.

**Comment by krader1961** [comment] 2016-07-28 04:52
You're correct, @terlar. While trying to reconcile the inconsistent behavior between the history builtin and function I broke this particular behavior. I'll fix it ASAP.

Having said that the history interface is a nightmare. For example, before my change the history function treated `--contains` and `--prefix` as taking an argument while the builtin did not. Those sorts of differences means that it is literally impossible to reconcile the two implementations in a manner that doesn't result in some user visible changes in behavior. So while it appears that fixing this particular issue so the implementation matches the original behavior should be possible I can't promise that is true for all behaviors of the history function.

**Comment by faho** [comment] 2016-07-28 11:30
@terlar: As a workaround, `builtin history` should work.

**Comment by krader1961** [comment] 2016-07-30 04:32
FWIW, I have a change that fixes this regression but I want to add some unit tests before merging it. As @faho noted, @terlar, you should probably switch to `builtin history --delete` even if my pending fix were merged. If for no other reason than it will be more efficient. Which, given your use case, could be noticeably faster since you don't want or need the overhead of the history function.

**Comment by krader1961** [comment] 2016-08-01 02:43
@ridiculousfish, I am perplexed by commit 067dff84 that you authored 4.5 years ago. I noticed this because my fix added an explicit `--exact` option for searching and `--contains` for the same string doesn't return the entry matched by `--exact`. This is the relevant block of code:

```
        case HISTORY_SEARCH_TYPE_CONTAINS: {
            // We consider equal strings to NOT match a contains search (so that you don't have to
            // see history equal to what you typed). The length check ensures that.
            return contents.size() > term.size() && contents.find(term) != wcstring::npos;
```

If I remove the ` contents.size() > term.size() &&` portion of that statement I don't observe any adverse effects and `builtin history --search --contains fg` includes the history entry that is literally just `fg` as does a `--exact` search.

**Comment by ridiculousfish** [comment] 2016-08-01 03:06
Thank you for checking!

The history search machinery is used by the `history` command, the history search binding (up arrow), and also autosuggestions.

The intent of that `contents.size() > term.size()` check is that, if you have some text entered on the command line and you press up arrow, you should never get that same command from history. Up-arrow searches should always return something new, else the user would have just run the command they wrote.

I tested this and this logic is being inadvertently duplicated by the "don't show the autosuggestion command as a history item," which comes from this part of reader.cpp:

```
                    if (!suggest.empty() && !data->screen.autosuggestion_is_truncated) {
                        data->history_search.skip_matches(wcstring_list_t(&suggest, 1 + &suggest));
                    }
```

So to produce the adverse effects, you can do the following:

1. Type and run a long command (long enough to wrap in the terminal).
2. Run an even longer command that has the first as a substring.
3. Type (but don't run) the command from #1 again
4. Press up arrow twice

You'll see that history search offers the command from #1 again, even though it was on the commandline.

I didn't anticipate that this would interfere with the `history` command's search. I think a good fix would be to remove that `contents.size() > term.size()` check, and instead have the reader add its commandline to the `external_skips` by including it in the call to `skip_matches()`.

**Comment by krader1961** [comment] 2016-08-01 03:23
Thank you for the detailed response, @ridiculousfish. That clarifies matters. I hadn't yet tried the [up-arrow]  scenario. Your recommendation looks reasonable to me. I'll explore that and attempt to add relevant unit tests.

**Comment by krader1961** [comment] 2016-08-02 04:56
I executed your steps to produce adverse effects due to removing the length restriction, @ridiculousfish, and I'm not entirely convinced the result is bad behavior. It was pretty clear from the highlighting that what I typed exactly matched a previously run command. Having said that I think there are reasonable arguments pro and con for the current behavior. Given that it has been in place for 4.5 years, and there is no compelling reason to change it, we should retain the existing behavior. So I'll modify my change to do what you suggested while also fixing the regression I introduced for `history --delete`.

**Closed** 2016-08-11 04:57 UTC
Labels: bug, regression
