### ISSUE TITLE
psub substitute input stream rather than output

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#7068] opened 2020-06-01 07:41 UTC
`psub` works for substitution of process' stdout, in bash it is `>(process)`.

Is there a `psub` to substitute process' stdin, in bash it is `<(process)`

**Comment by faho** [comment] 2020-06-01 08:46
Duplicate of #1786

**Closed by faho** 2020-06-01 08:46 UTC

**Comment by faho** [comment] 2020-06-01 08:48
>psub works for substitution of process' stdout, in bash it is >(process).

Wrong way around - `psub` is `<()`.

What you want is `>()`, which is asked for in #1786.

Tbh I've not really found a use case for it - typically you just want a pipe.

**Comment by kuvaldini** [comment] 2020-06-04 06:37
My use case is:
```
somedata | tee >(process1) >(process2) >(process3)
```

**Comment by nipunarora** [comment] 2020-06-13 04:01
I have a similar use case, can anyone comment on how this can be achieved?

**Comment by gokulsoumya** [comment] 2020-06-13 04:39
@nipunarora A working solution posted in the linked duplicate: https://github.com/fish-shell/fish-shell/issues/1786#issuecomment-612369426
