### ISSUE TITLE
handle broken locking on remote filesystems better

### ISSUE THREAD

**Issue by eassmann** [fish-shell/fish-shell#685] opened 2013-04-22 09:21 UTC
On my CentOS 5.8 system, fish hangs for a long time (minutes) after every command, built-in or external, though not after a blank line.  The command output and new prompt will be printed, then the hang occurs.

It also hangs after entering a comment, although in this case _before_ printing a prompt.

It does not hang when a command is executed as 'fish -c ls'

strace snippet executing 'ls', the blank lines indicate long waits:

```
write(1, "assmann@n101 \33[32m~\33[30m\33(B\33[m> "..., 35) = 35
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or TCGETS, {B38400 opost isig -icanon -echo
...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig -icanon -echo
...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or TCGETS, {B38400 opost isig -icanon -echo
...}) = 0
select(5, [0 3 4], NULL, NULL, NULL)    = 1 (in [4])
read(4, "\2", 1)                        = 1
futex(0x9980030, FUTEX_WAIT_PRIVATE, 2, NULL

) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], NULL, 8) = 0
open("/home/assmann/.config/fish/fish_history", O_WRONLY|O_APPEND) = 6
fcntl(6, F_GETFD)                       = 0
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=30, ...}) = 0
fcntl(6, F_SETLKW, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0}

) = -1 EIO (Input/output error)
close(6)                                = 0
rt_sigprocmask(SIG_UNBLOCK, ~[RTMIN RT_1], NULL, 8) = 0
open("/home/assmann/.config/fish/fish_history", O_RDONLY) = 6
fcntl(6, F_GETFD)                       = 0
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
fcntl(6, F_SETLKW, {type=F_RDLCK, whence=SEEK_SET, start=0, len=0}

) = -1 ENOLCK (No locks available)
close(6)                                = 0
```

**Comment by zanchey** [comment] 2015-10-19 13:24
Was there ever any progress with this? I wondered idly if NFSv4 might be displaying some unusual semantics here, but there hasn't been any activity in the last two years. I'm not sure if @xebtl is still having the problem?

**Comment by xebtl** [comment] 2015-10-19 13:33
From my side, no progress.  More precisely, I simply stopped trying after the previous discussion — I do not use the machine in question (a cluster) all that much, so it was not worth more effort to me.  I actually use the machine even less these days, but if it is of interest to you, I can certainly try the current version of fish.

On the other hand, is NFSv4 a new version?  The NFS on our cluster is not being updated, if that was your point.

**Comment by zanchey** [comment] 2015-10-19 13:46
NFSv3 and NFSv4 are two quite different protocols, and certainly at our site we have aggressively avoided migration to NFSv4 due to a variety of problems - Linux server performance, reduced fault tolerance and changed semantics. We have picked up at least one problem in fish that occurs only on NFSv4 mounts, though.

I'd be interested to know if it still happens. There's been quite a bit of change to the code in this area.

**Comment by xebtl** [comment] 2015-10-19 16:13
How do I find out if my cluster is using v3 or v4?

**Comment by xebtl** [comment] 2015-10-22 08:57
@zanchey: `nfsstat` says “Client nfs v3”, so I guess it is NFSv3.

**Comment by xebtl** [comment] 2015-10-22 09:07
I compiled the current 2.2.0 tarball from the website.  Unfortunately, it seems that the problem persists:

```
futex(0x184cb980, FUTEX_WAIT_PRIVATE, 2, NULL) = 0 <289.078032>
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], NULL, 8) = 0 <0.000058>
open("/home/assmann/.config/fish/fish_history", O_WRONLY|O_APPEND) = 6 <0.326795>
fcntl(6, F_GETFD)                       = 0 <0.000029>
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0 <0.000021>
fstat(6, {st_mode=S_IFREG|0644, st_size=182, ...}) = 0 <0.000020>
fcntl(6, F_SETLKW, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0}) = -1 ENOLCK (No locks available) <59.370349>
```

**Comment by zanchey** [comment] 2015-10-22 14:10
My suspicion is that the NFS server isn't running an NFS locking manager (`rpcinfo -p SERVERNAME | grep nlockmgr` should produce some output if the locking manager is present). If that's all OK, could you try building the current git master? Or using a nightly build?

**Comment by xebtl** [comment] 2015-10-27 13:09
It seems the locking manager is present.

I failed to build from master because the configuration needs autoconf 2.60 but only 2.59 is available for my OS (CentOS 5.11).  Installing the nightly RPM failed as well, I think also because the OS release is too old.  Is there any way to get around the autoconf dependency?

**Comment by zanchey** [comment] 2015-10-27 13:31
Try `autoreconf` rather than `autoconf` to get the source to build.

**Comment by xebtl** [comment] 2015-10-27 15:35
Sorry, but that still complains 
```
$ autoreconf                                                                       
configure.ac:13: error: Autoconf version 2.60 or higher is required                                                    
configure.ac:13: the top level                                                                                         
autom4te: /usr/bin/m4 failed with exit status: 63                                                                      
aclocal: autom4te failed with exit status: 63                                                                          
autoreconf: aclocal failed with exit status: 63                                                                        
```
I tried to remove the constraint from `configure.ac`, but then `autoreconf` reports an error and the resulting `configure` fails with
```
./configure: line 2069: AC_PROG_SED: command not found
CXXFLAGS: -g -O2
checking for msgfmt... msgfmt
./configure: line 2236: syntax error near unexpected token `$doxygen_version,'
./configure: line 2236: `            AS_VERSION_COMPARE($doxygen_version, $doxygen_minimum,'
```

**Comment by zanchey** [comment] 2015-10-29 07:31
Of course - my apologies.

Try the nightly tarball, which has the configure file generated. You should just be able to use `./configure; and make install`. You can download it from [the openSUSE build service](https://build.opensuse.org/package/show/shells:fish:nightly:master/fish) - e.g. https://build.opensuse.org/source/shells:fish:nightly:master/fish/fish_2.2.0-392-g1055864.orig.tar.gz?rev=f9588125472c5df5b3f2f240d2cda346

**Comment by xebtl** [comment] 2015-10-29 09:33
That tarball built, but the problem is still there.  Sorry.

**Comment by zanchey** [comment] 2015-10-30 14:10
No, that's good to know!

**Comment by krader1961** [comment] 2016-12-13 00:11
Is anyone still interested in debugging this? If not we should close it. Getting a strace with timing data along with `fish -d5` output would be really helpful.

**Comment by eassmann** [comment] 2016-12-13 13:45
I ran another test with the the build of fish-2.2.0-392-g1055864 on the same machine, using the command `strace -fTostrace ./fish -d 5 2>stderr`.  I entered `ls^M^D` and waited for fish to exit.

I put the complete output in a [gist](https://git.io/fish-nfs-strace).  The syscalls that take a long time are
```
#line   PID
----- -----
 4999 28559 fcntl(6, F_SETLKW, {type=F_RDLCK, whence=SEEK_SET, start=0, len=0} <unfinished ...>
 5107 28561 futex(0x1d7d4b60, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
 5196 28551 futex(0x1d7d4b60, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
 5197 28559 <... fcntl resumed> )             = -1 ENOLCK (No locks available) <30.004000>
 5203 28561 <... futex resumed> )             = 0 <29.925293>
 5210 28551 <... futex resumed> )             = 0 <29.597652>
 5241 28551 fcntl(6, F_SETLKW, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0} <unfinished ...>
 5351 28551 <... fcntl resumed> )             = -1 EIO (Input/output error) <150.011093>
```
As far as I could tell, fish's corresponding debug output was
```
fish: path_get_path( 'l' )
fish: path_get_path( 'ls' )
fish: path_get_path( 'ls' )
fish: path_get_path( 'ls' )
```

If you want to see output with different options, just let me know.  If you want me to try with a newer version, ditto, though I would have to compile that.

**Comment by krader1961** [comment] 2016-12-13 16:03
This is a bug in the NFS `statd` service. See for example https://bugzilla.kernel.org/show_bug.cgi?id=8159. Your OS is broken. Nothing fish can do about it other than not attempt to obtain locks on the history file and I don't think we're going to do that.

**Comment by krader1961** [comment] 2016-12-13 18:37
@eassmann: You can fix your immediate problem by setting `$XDG_DATA_HOME` to a path on a local file system so your fish history file is no longer on NFS.

While walking my dogs this morning it occurred to me we can deal with this type of situation better. Simply time how long it takes to obtain the lock (or fails as the case may be) and if it is above a threshold (say 250 ms) then emit a warning and stop trying to lock the history file. It's better to risk losing history than to have an unusable shell.

**Comment by eassmann** [comment] 2016-12-14 09:29
@krader1961: Thanks for the tip about `$XDG_DATA_HOME`.

> It's better to risk losing history than to have an unusable shell.

I absolutely agree.

**Closed** 2016-12-17 05:24 UTC
Labels: enhancement
