### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5934] opened 2019-06-11 15:30 UTC
Considering that [the 3.1.0 milestone](https://github.com/fish-shell/fish-shell/milestone/20) has 210 closed issues assigned to it, which is more than 2.7.0's 173, 2.6.0's 192 and 2.5.0's 156, and less only than 2.2.0 (382), 2.3.0 (412) and 3.0.0 (514), it's probably time to earnestly consider making a release.

There's a few blockers still, including:

- [x] the fallout from the sphinx switch (#5696), especially remaining formatting errors
- [x] `history` hanging (#5855)
- [x] string-replace-fewer-backslashes being maybe not ideal as a name (#5805)

Plus a bunch of things I've probably forgotten.

Also #5280 - a new logo - would always be nice to include in a release.

**Comment by zanchey** [comment] 2019-06-13 04:09
The concurrency model that @ridiculousfish is working on is getting closer, but it might be better to land that early in a release cycle and give it lots of testing?

**Comment by ridiculousfish** [comment] 2019-06-16 22:01
The concurrent execution will initially be behind a feature flag, with the possible exception of explicit background functions (#238).

**Comment by faho** [comment] 2019-08-07 22:10
Looking at [the milestone](https://github.com/fish-shell/fish-shell/milestone/20) again, I'd rather have a release "now" (ish).

I don't think we'll figure out a way to do that styling that's basically the last missing thing in sphinx, so we can just remove it for now and add it back later, and `string-replace-fewer-backslashes` isn't the worst name ever.

On the other hand, there's a few sweet bugfixes and features in 3.1.0 and we've not done a 3.0.3.

**Comment by zanchey** [comment] 2019-08-14 05:13
Yes, I think that's a good idea. 3.0.3 isn't much less work than 3.1.0, and there's a lot more fixes in master that deserve shipping.

**Comment by floam** [comment] 2019-08-14 05:18
I can push a `string-replace-fewer-backslashes` commit tonight.

**Comment by zanchey** [comment] 2019-09-02 15:02
I've got a few patches to push through and then I'll make a start on the release notes.

**Comment by zanchey** [comment] 2019-10-03 13:36
I've been working on this but I'm about to be without much access for the next couple of weeks. More on my return.

**Comment by Delapouite** [comment] 2019-10-17 08:26
A new version (10.33) of pcre2 has been released in April. Fish currently uses the previous one (10.32).

https://www.pcre.org/changelog.txt

Is it worth upgrading to the new pcre2 version before releasing fish 3.1.0?

**Comment by ridiculousfish** [comment] 2019-10-17 21:00
I think we should incorporate the new PCRE but after 3.1.0, it seems like a potentially risky late change.

**Comment by floam** [comment] 2019-10-17 21:03
OTOH, if there's any issues caused by 10.33, people are going to run into them when they update that package anyway because most packages just link the system pcre2 (or should have run into issues already).

**Comment by zanchey** [comment] 2019-10-20 14:06
I'm not fussed either way, but it is low priority and will not block the release.

**Comment by faho** [comment] 2019-10-20 14:15
I have been running pcre2 10.33 since May, so I don't think there are any issues to expect.

**Comment by robinwhittleton** [comment] 2019-11-25 12:28
pcre 10.34 came out last week with 39 changes. I’m not qualified to say how they might affect fish.

**Comment by datenreisender** [comment] 2019-12-12 13:50
What is currently holding back releasing 3.1.0? “Only” that someone has to do it? 

Looking e.g. at the above list it looks like only Sphinx issues still should be done, but looking at #5696 it seems to me like there are no issues with Sphinx that are really so critical that they should hold back a release.

**Comment by zanchey** [comment] 2019-12-12 14:24
The release notes, which I'm nearly finished. As you will understand, feeding the family (both figuratively and literally) takes priority.

**Comment by chenrui333** [comment] 2020-01-05 18:09
Just curious what is the timeline for the new release? It looks it has past the due date 4 months?

**Comment by faho** [comment] 2020-01-05 18:10
"When it's done"

**Comment by zanchey** [comment] 2020-01-20 13:33
(this means that the beta is very close)

**Comment by zanchey** [comment] 2020-01-25 08:32
I fast-forwarded along master to pick up a bunch of low risk changes, which have been added to the milestone.

**Comment by zanchey** [comment] 2020-01-26 15:04
The beta is out now! [Get it while it's hot!](https://github.com/fish-shell/fish-shell/releases/tag/3.1b1)

**Comment by anrddh** [comment] 2020-01-29 02:53
Any word on when 3.1 stable will be released?

**Comment by zanchey** [comment] 2020-01-29 07:55
In general I'll roll the final release about two weeks after the release of the beta, but of course that is dependent on no show-stoppers being identified, other demands on my spare time, internet service, phase of the moon, and so on.

Sadly, it is impossible for me to give you information that you can act on in response to your question.

**Closed** 2020-02-12 15:59 UTC
Labels: packaging, release notes
