### ISSUE TITLE
Multi bytes characters breaking the prompt in Termux

### ISSUE THREAD

**Issue by christianrondeau** [fish-shell/fish-shell#4269] opened 2017-07-30 03:50 UTC
* fish 2.6.0
* os termux `Linux localhost 3.18.14-11422779 #1 SMP PREEMPT Thu Jun 1 19:35:14 KST 2017 aarch64 Android` with `TERM=xterm-256color`

It's been a while I had this problem with my prompt: going back into the history using the up key sometimes jumbled my lines (one character is repeated at the beginning of the command, and modifications are then offset by one). 

I tried to simplify my problem, and I realized the issue was my prompt is the lambda character. 

I tried to then just type `¥` and I had this:

![fish utf-8 bug on Termux](https://i.imgur.com/fXGWJ1g.jpg) 

The first three commands used the up key. Note the missing prompt. Also note the missing space in the second command. In the third, I only typed ¥ once. In the fourth, I typed ¥, then backspace, then "oops". 

Any idea? It feels like a character vs byte count issues.

**Comment by krader1961** [comment] 2017-07-30 04:07
What is your locale? What does `locale` output? That character when I copy/paste it from this issue, for me, is the two bytes 0xc2 0xa5. Which is not valid UTF8. In ISO 8859-15 the 0xA5 code point is a similar, but not identical, symbol.

**Comment by krader1961** [comment] 2017-07-30 04:09
Also, notice that the character in your screen shot is not the same as in the text of your problem report. Which strongly suggests you are not use Unicode but some unusual encoding.

**Comment by krader1961** [comment] 2017-07-30 04:11
Haha! The [ISO 8859-15 Wikipedia page](https://en.wikipedia.org/wiki/ISO/IEC_8859-15) shows that  "ÿ" is codepoint 0xFF in that encoding. Which will cause problems if your locale is not ISO 8859-15.

**Comment by christianrondeau** [comment] 2017-07-30 12:38
There's no `locale` executable on Termux. `printenv` prints `LANG=en_US.UTF-8` and I have no issues in vim nor bash. I have this as an example, but I tried using multiple android keyboards, and getting the character from another machine through git... Same issue.

I have the same bytes (`c2a5`) than you, but using (copy pasting)   `efbfa5` (`￥`) yields the same result... 

Any idea? Thanks for your help! I think it might be related to busybox but I'm really not sure.

**Comment by krader1961** [comment] 2017-07-30 16:28
The problem is that 0xA5 is a continuation byte in UTF-8. It is not a legal character by itself. And 0xC2 is not a valid value as the first character of a multi-byte sequence that would contain 0xA5. See https://en.wikipedia.org/wiki/UTF-8.

The reason this works in bash is that bash doesn't really care very much what encoding you're using. It internally just stores the sequence of bytes. So if, as in your case, you've said you're using UTF-8 but then hand bash an invalid UTF-8 sequence it just metaphorically shrugs its shoulders and says "okay, I'll store those without really understanding what they mean."

The valid UTF-8 sequence, 0xEf 0xBF 0xA5, is the character ￥ that you pasted into your most recent comment. Fish correctly handles that. The character in your screenshot is known as "[latin small letter y with diaeresis](http://www.fileformat.info/info/unicode/char/ff/index.htm)". It's unicode code point is \u00FF which is 0xC3 0xBF in UTF-8 form. 

It looks like your environment is screwed up. You've told fish that all input to it will be valid UTF-8 but it isn't. I'm guessing you're actually using something like ISO 8859-15 (the old western european) standard where 0xFF is the literal ÿ you showed in your screenshot. But in `LANG=en_US.UTF-8` that value is illegal.

**Comment by christianrondeau** [comment] 2017-07-30 20:51
What you're saying makes sense, though I'm not sure how to use this information. 

    e© > test # here in reality I typed echo, fish scrambled it
    
    localhost:~
    λ cat test | od -t x1 -t c
    0000000  c2  a9  0a
            302 251  \n
    0000003
    
    localhost:~
    λ file -i test
    test: text/plain; charset=utf-8

I'm on Android, in termux where `locale` does not exist. I tried multiple keyboards, and termux uses en_US utf-8 by default. I'm from Canada but I use en_US everywhere so I'd be surprised if i had a western European configuration :) 

But when I paste `α`, I get `

I'm open to debugging deeper, but I'm not sure where to start.

**Comment by christianrondeau** [comment] 2017-07-30 20:54
Oops, sorry touched the close button :|

But when I paste α, I get `ceb1 instead of `u3b1`. 

Any clue on how to get started would be appreciated. I'll try opening an issue with Termux if we can't find anything here. 

Thank you very much for your help!

**Comment by krader1961** [comment] 2017-07-30 21:18
Only one other user has opened issues regarding fish on termux, @fornwall, and there is no indication they were having input problems. I don't know what to tell you. The sequences you're reporting, like 0xCE 0xB1, are not valid UTF-8. Neither do they appear to be UTF-16. Yet the [termux changelog](https://termux.com/changelog.html) implies it uses Unicode. But clearly the characters you're typing or pasting are not encoded as UTF-8.

If the input is a single byte encoding like one of the [ISO 8859 encodings](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) you could try `set -gx LANG C`. If the locale you've told fish to use (via the `LANG` and related variables) doesn't match what your terminal sends to fish then you'll have problems like you're seeing.

**Comment by christianrondeau** [comment] 2017-07-31 00:10
Thanks a lot. I'll do my homeworks, try to get some help on Termux's side (by the way, @fornwall is Termux's creator and maintainer). I'll reach out here if I find a solution, or if for some reason fish is causing this (based on your feedback, it shouldn't)

**Comment by christianrondeau** [comment] 2017-07-31 00:39
Ok, I'm a little bit clueless. Here's what I have tested, on Termux (bash and fish), Linux Alpine (both directly on a VM and in a brand new Docker instance in fish), and Bash on Ubuntu on Windows (both bash and fish).

I copied the `α` character from here http://www.fileformat.info/info/unicode/char/3b1/index.htm, and ran:

    echo "α" > test

Then, on all installations:

    cat test | od -t x1 -t c
    0000000 ce b1 0a
            316 261  \n
    0000003

Indeed, `ceb1` matches the utf-8 code on fileformat.info. I also tried `isutf8` in `moreutils`, and `iconv -f UTF-8 test`, everything confirms it is indeed valid utf-8, and that the character is valid. The only place where it breaks is when using fish _on_ termux. I'll go create an issue in Termux right away, hopefully it's either a fish dependency or the fish build _on_ termux that is in cause...

Again, thanks for your help @krader1961.

**Comment by krader1961** [comment] 2017-07-31 02:25
The sequence 0xCE 0xB1 is indeed a valid UTF-8 sequence. It corresponds to codepoint \u03B1. Most of the other sequences you provided, like 0xC2 0xA9, are not valid UTF-8. If valid UTF-8 encoded characters cause problems running fish inside termux one possibility is that there is no locale definition for `en_US.UTF-8` installed. Are you setting `LANG` in your *config.fish* or is it inherited from termux?

Whatever the answers to the above questions I am willing to bet money that this is not a fish bug. It is going to be a problem with the OS fish is running on. We have had to implement workarounds for bugs in various operating systems like Haiku. So we're willing to do so for termux on Android OS if you can provide more details about the problem.

Are you able to build fish from source? If so it would be interesting to add some debug statements to show what is happening when fish processes a character like \u03B1 on your platform.

**Comment by christianrondeau** [comment] 2017-07-31 21:44
I won't bet against you, and do my best to diagnose what's happening exactly. I'm not able to compile yet (`configure: error: cannot find sources (fish) in . or ..`, I believe something is going wrong with `autoreconf`) but unless you already know what the problem might be, I'll save you the trouble and figure it out. The fish package in Termux is already patched (https://github.com/termux/termux-packages/tree/master/packages/fish) , so we might not need a PR here. We'll see. Thanks!

**Comment by krader1961** [comment] 2017-07-31 22:06
I can find only one other instance of the configure error you reported, issue #3456, building on Solaris. Try doing `touch fish` first. That shouldn't be needed but allowed that other user to get past that stage. Also, does `ls .git` show that you have that directory?

**Comment by christianrondeau** [comment] 2017-08-01 01:30
@krader1961 well, that worked. I was trying to go backwards from the error in `configure`, guessing flags, trying to figure out whether this `fish` was a file, a folder or a prefix... never thought of just creating it.

I passed the `autoreconf --no-recursive` part and the `./configure` part successfully (if it's useful for someone, here's my `termux-configure` script: https://gist.github.com/christianrondeau/ce00b6a91abf7ac9da4fa33d5b1fecf3)

I had to do a few patches for fish to `make` successfully. Here's the fork and branch: https://github.com/christianrondeau/fish-shell/tree/gh-4269 - everything I did came from https://github.com/termux/termux-packages/tree/master/packages/fish

I also looked at Haiku-specific Fish issues, and my issue strangely looks like this one: https://github.com/fish-shell/fish-shell/issues/3646 (the "double slash" looks like the character offset I'm seeing, but I might be wrong).

So, let's win some time:

    for var in LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL
      echo $var \'$$var\'
    end

gave

    LANG 'en_US.UTF-8'
    LC_CTYPE
    LC_NUMERIC
    LC_TIME
    LC_COLLATE
    LC_MONETARY
    LC_MESSAGES
    LC_PAPER
    LC_NAME
    LC_ADDRESS
    LC_TELEPHONE
    LC_MEASUREMENT
    LC_IDENTIFICATION
    LC_ALL 'POSIX'

I don't have the `locale` software though. Note that for now, I run a prompt that uses `>` rather than `λ` and I have no issue (so since I'm not using UTF-8 characters in my day-to-day usage of fish, this is more about contributing; at least I have a fallback). If for some reason you want to see my fish configuration: https://github.com/christianrondeau/dotfiles/tree/master/fish/.config/fish

Let me know where you think I should go from there, otherwise I'll fiddle around (I have no idea where to start though)

**Comment by krader1961** [comment] 2017-08-01 02:09
In general you should not set both `LANG` and `LC_ALL` as the latter has higher precedence. So fish is not actually using UTF-8. It's using the C (single-byte) locale. Depending on your libc implementation that may be limited to ASCII (values 0x0 thru 0x7F) or allow the characters in the upper half of the table that have their high bit set. Try unsetting that: `set -e LC_CALL`.

**Comment by christianrondeau** [comment] 2017-08-01 03:06
Mmmh, I don't know how `LC_ALL` ended up being set to `POSIX`. Clearing it didn't help, even after restarting fish. 

    LANG 'en_US.UTF-8'
    LC_CTYPE
   ... 
    LC_ALL

**Comment by krader1961** [comment] 2017-08-01 03:16
Okay, you're going to need input from the termux community because I have no idea what it's environment is like. Does it even provide support for `LANG=en_US.UTF-8`? What happens if you run `echo (echo \u03B1)`?

As for your fish config it has some problems. You do `if test -d /usr/local/bin` three times but only the first one is correct. You also do `. "$HOME/.config/fish/prompt.fish"` but that isn't needed if you just rename the script to *~/.config/fish/functions/fish_prompt.fish*. Finally, you shouldn't do `set -g __fish_vi_mode 1`. Just call `fish_vi_key_bindings`.

**Comment by christianrondeau** [comment] 2017-08-01 12:38
As far as I know the only place where utf-8 characters behave like this is in fish prompt (not stdout) :

    localhost:~
    > echo \u03B1
    ?
    
    localhost:~
    > echo \uCEB1
    ?
    
    localhost:~
    > echo -e '\xe2\x82\xac'
    €

Since the euro sign shows up, i tried to see if this specific character broke the prompt, and it does. 

I can curl http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt and the output is fine, so as far as I know utf-8 prints fine. 

I'm not sure _what_ to ask the Temux folks :) is there a specific library I could make a test app against to pinpoint the problem? 

Oh and thanks for the recommendations for my fiah config, that is awesomely nice of you :) Hopefully I can pay back by figuring out and fixing this thing...

**Comment by faho** [comment] 2017-08-01 13:20
>Mmmh, I don't know how LC_ALL ended up being set to POSIX. 

This is something you need to figure out.

Note that it's not the root cause of this issue (I don't have that on termux, yet I still get this issue). But if it isn't removed, it'll be a secondary cause (i.e. fix the root cause, and then suddenly this breaks it again).

I would imagine this is caused by termux's wcwidth returning something different from ours (fish is a bit of a stickler for width because of all the trickery it does with cursor movement) .

We've previously discussed dropping our wcwidth implementation in favor of the system one - e7273e1d81e1ef7c6151624087b4e73661005b33 made it so we used our fallback everywhere, since the system wcwidth implementations seemed to be broken everywhere. Maybe we should try reverting that here.

**Comment by faho** [comment] 2017-08-01 14:07
>We've previously discussed dropping our wcwidth implementation in favor of the system one - e7273e1 made it so we used our fallback everywhere, since the system wcwidth implementations seemed to be broken everywhere. Maybe we should try reverting that here.

See #2199. Cursory testing on linux-with-glibc 2.25 seems to show no change in behavior in that case.

**Comment by krader1961** [comment] 2017-08-01 19:26
What does `echo -n \u03B1 | od -tx1z` output? Substitute `xxd` or similar tool for `od` if necessary. It should report the byes 0xCE 0xB1 were written by fish. What happens if you run `echo \u20ac`? That should result in the same three bytes representing the UTF-8 encoding for the euro character. If it doesn't then the problem is likely with the `wcstombs()` function in your libc.

**Comment by krader1961** [comment] 2017-08-01 19:28
Obviously the commands in my previous comment need to be done without `LC_ALL` being set to `POSIX`. Otherwise any "wide" characters with code points higher than 0xFF won't work by definition.

**Comment by krader1961** [comment] 2017-08-01 19:33
Note that we expect a question-mark to be written by `echo \u03B1` (or any other wide character) if you have set the locale to POSIX/C. For example:

```
$ env LC_ALL=C fish -c 'echo \\u03B1 | od -tx1z'
0000000 3f 0a                                            >?.<
0000002
```

That's because that wide character can't be represented in a single byte locale like POSIX.

**Comment by faho** [comment] 2017-08-01 19:52
>What does echo -n \u03B1 | od -tx1z output? Substitute xxd or similar tool for od if necessary. It should report the byes 0xCE 0xB1 were written by fish. What happens if you run echo \u20ac? That should result in the same three bytes representing the UTF-8 encoding for the euro character. If it doesn't then the problem is likely with the wcstombs() function in your libc.

"?" (0x3f) in both cases. Only $LANG is set (to en_US.UTF-8).

Yes, it's borked.

**Comment by krader1961** [comment] 2017-08-01 20:06
Thanks, @faho. The next question is whether the bug is with fish or with the android OS. Does android even have a en_US.UTF-8 locale? If it doesn't then it seem reasonably for libc to fallback to POSIX/C as the locale. Which in turn will cause the symptoms being reported.

As I said earlier it doesn't surprise me that bash works since bash uses narrow chars internally and has its own private functions for deciding if a UTF-8 locale is in effect and performing appropriate conversions. Whereas fish relies almost entirely on libc for that functionality (notwithstanding the few exceptions like our `fish_wcswidth()` function). So, if android either doesn't have a valid en_US.UTF-8 locale definition or its libc doesn't correctly implement it then fish won't handle anything other than ASCII correctly.

**Comment by faho** [comment] 2017-08-01 20:16
See https://github.com/termux/termux-packages/commit/845a978a46710b19066f6393ec593e88706b1576.

We do `setlocale(LC_ALL, "")` as that commit mentions, so we hit that android bug.

That commit was made 16 days ago, and the last commit to the fish package 19 days ago. So rebuilding the fish termux package should work. At least if I'm understanding this correctly (which is always a bit of a gamble).

**Comment by krader1961** [comment] 2017-08-01 20:27
Right, we do `setlocale(LC_ALL, "")` early in our startup to ensure we have initialized the libc locale subsystem to something sane based on the locale env vars. So the problem is in the stdlib/libc code and they've recently patched the problem. Yay! I'm kind of surprised @fornwall didn't report this issue to us but perhaps, like me, he makes little use of wide unicode chars.

I'm closing this because I think we've reached the root cause and there is nothing for the fish project to do. Feel free to reopen, @christianrondeau, if you disagree.

**Closed by krader1961** 2017-08-01 20:27 UTC
Labels: needs-more-info, question

**Comment by faho** [comment] 2017-08-01 23:08
Fixed in Termux.

**Comment by christianrondeau** [comment] 2017-08-02 00:21
I confirm https://github.com/termux/termux-packages/issues/1183 fixed it. Thanks a lot @krader1961 and @faho for your help, I'm off to work and back and it's fixed and deployed, even though this was not an easy one! Hats off, that was impressive!
