### ISSUE TITLE
Brackted paste mode doesn't work under tmux

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#7815] opened 2021-03-12 15:09 UTC
Inside tmux under item2.

Pressing CMD+V 
![image](https://user-images.githubusercontent.com/669045/110958695-f047e800-8387-11eb-8f10-2cf5f2a89df6.png)

Where the text is:
```
npx react-native start

```

**Comment by faho** [comment] 2021-03-12 15:13
Duplicate of #7770

**Comment by faho** [comment] 2021-03-12 15:14
No, it works, it's just that the text *also* shows upcon screen, but that's purely cosmetic.

It's fixed and will be released in 3.2.1

**Closed by faho** 2021-03-12 15:13 UTC
