### ISSUE TITLE
Smart autocomplete - in the middle of words

### ISSUE THREAD

**Issue by lucmp** [fish-shell/fish-shell#413] opened 2012-11-29 02:58 UTC
Sometimes we have a command line already written and would like to go back and change it ever so slightly that we can reuse almost everything, but the file(s) referenced will be completely different. For example, autocomplete suggests a certain file name, but we want another one with a pretty similar name. 

In such cases, we are forced to go back to a certain insertion point, insert a space, autocomplete, then remove that space manually and perhaps even delete some residue. All this trouble is due to the fact that autocomplete currently will not work "from the middle" of a word.

Humans should not be subjected to such drudge work. Let the automaton do it for us, and autocomplete also from the middle of words, like a good servant.

This feature is already available in other shell implementations.

**Comment by faho** [comment] 2016-04-04 16:53
This is a duplicate of #357.

**Closed by faho** 2016-04-04 16:53 UTC
