### ISSUE TITLE
Tab completes into sub directories if there is only one sub directory

### ISSUE THREAD

**Issue by ryan27968** [fish-shell/fish-shell#5431] opened 2018-12-25 22:20 UTC
So I'm certain this is intended behavior, but I can't find anywhere in the documentation that explains how to disable it. Basically, if I only have one directory in my Documents folder, and I tab complete `cd Doc` from `~`, it'll tab complete into the sub directory instead of just the directory I specified. Again, this is probably intended behavior but it can be very annoying. It's as if the tab completion for directories uses `**` instead of `*` globbing behavior. Is there any way to disable this feature? If so, it should be added to the FAQ or the "Tab completion" section of the documentation. If not, there should be a method of disabling it added. I would argue that the extra effort in tapping tab a few times to go into a deep directory structure is far offset by the annoyance of having to `cd ..` after completing too deep in the cases where you don't want it.

**Comment by faho** [comment] 2018-12-26 09:51
Duplicate of #4402

Which is solved in 3.0 (the beta of which is available [right now](https://github.com/fish-shell/fish-shell/releases/tag/3.0b1)) by not doing it anymore.

**Closed by faho** 2018-12-26 09:51 UTC

**Comment by ryan27968** [comment] 2018-12-26 10:35
Ok great thanks! I searched for about an hour to find any similar issues but I didn't get my phrasing the same as his. Apologies for the duplicate post.

**Comment by ryan27968** [comment] 2018-12-26 10:35
Ok great thanks! I searched for about an hour to find any similar issues but I didn't get my phrasing the same as his. Apologies for the duplicate post.
