### ISSUE TITLE
set_color truncates output when passed invalid arguments

### ISSUE THREAD

**Issue by clarfonthey** [fish-shell/fish-shell#7873] opened 2021-03-28 17:25 UTC
What happened to me was I had code that did something like this:

```
echo (set_color --bg red)text
```

And all that got output was a single line. The reason is because of this code here: https://github.com/fish-shell/fish-shell/blob/a7df92e1874dc347c9f82457e7ab921e24f5bb8d/src/builtin_set_color.cpp#L130-L134

Since command-expansion treats an empty string as an empty *array* of strings, the `text` is appended to each element of the array, resulting in… zero arguments being printed. The correct argument is `--background`, not `--bg`.

I'm not really sure why there needs to be a silent error here, but it seems to, at least in this one case, result in very bad behaviour. I'm not sure what the best answer would be, whether it's to update how `set_color` works to actually error here, whether the command expansion should be fixed, whether this should just be properly documented, etc., but I think that it's enough of a problem to warrant a discussion.

**Comment by faho** [comment] 2021-03-28 17:31
Duplicate of #5443

**Closed by faho** 2021-03-28 17:31 UTC

**Comment by clarfonthey** [comment] 2021-03-28 17:32
Oof, open since 2018. Thanks, I should have searched before posting. ><
