### ISSUE TITLE
Autocomplete breaks with emojis

### ISSUE THREAD

**Issue by hsalazr** [fish-shell/fish-shell#5047] opened 2018-06-13 19:31 UTC
If you use an emoji on a command string param then fish autocomplete breaks.

[![asciicast](https://asciinema.org/a/5ISXQkz8dWz3BavrxvYK4mP9c.png)](https://asciinema.org/a/5ISXQkz8dWz3BavrxvYK4mP9c)
```
fish, version 2.7.1
Darwin 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
xterm-256color
```

**Comment by faho** [comment] 2018-06-14 08:40
Duplicate of #4539. The good news is that the upcoming 3.0 has some attempts to improve this.

**Closed by faho** 2018-06-14 08:40 UTC
