### ISSUE TITLE
unzip completion does not complete home path

### ISSUE THREAD

**Issue by Azenet** [fish-shell/fish-shell#7630] opened 2021-01-15 15:27 UTC
Hi,

When completing unzip, the completion will not complete folders or files if `~` is used. For example, if a file /home/user/test.zip exists:
```
unzip /home/user/te<tab> # completes
unzip ../te<tab> # completes
unzip ~/te<tab> # doesn't complete
unzip $HOME/te<tab> # doesn't complete
```

Using fish, version 3.1.2.

**Comment by faho** [comment] 2021-01-15 16:39
Duplicate of #7350

**Closed by faho** 2021-01-15 16:39 UTC
