### ISSUE TITLE
Key input after piping to `fzf` does not work with new extended keyboard input functionality

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10407] opened 2024-04-02 18:09 UTC
Using https://github.com/fish-shell/fish-shell/commit/695b408396e690f19b6f5e21859b4d5848ab83ae and iTerm 2 (v3.4.23)

---

Installed the latest commit on `main` to try out the [awesome new keyboard input functionality](https://github.com/fish-shell/fish-shell/pull/10359). So far, so good. But spotted a small issue around key inputs after piping.

Piping [`z`](https://github.com/jethrokuan/z) to [`fzf`](https://github.com/junegunn/fzf) and then hitting a keybind (in this case, `ctrl-c`) results in:

![image](https://github.com/fish-shell/fish-shell/assets/8544900/f736a5b0-155f-4268-9089-aa9162152d79)

And does not exit `fzf`. The only way out is to create a new terminal window and close the old one.

**Comment by faho** [comment] 2024-04-02 18:20
What is happening here is that the keyboard enhancement hasn't been disabled, and so fzf gets the new encoding for ctrl-c, which it doesn't understand.

I can't reproduce this in konsole or kitty and I do not have access to a machine that can run iTerm.

**Comment by krobelus** [comment] 2024-04-02 19:25
should be fixed by 8164855b7 (Disable terminal protocols throughout evaluation)

**Closed as completed** 2024-04-02 19:33 UTC
Labels: regression
