### ISSUE TITLE
Can't delete the first letter of a command when used to navigate through the suggestions. 

### ISSUE THREAD

**Issue by Hunsu** [fish-shell/fish-shell#3132] opened 2016-06-10 08:44 UTC
Can't delete the first letter of a command you typed and used the tab to navigate through the suggestions. 
### Reproduction Steps:
1. cd to folder where there are at least two sub-folders 
2. type `cd` and then `tab` `tab`to navigate through the suggestions 
3. Now delete the command 
### Expected behavior:

The command is deleted.
### Observed behavior:

We can't delete the `c`letter from the `cd`command.  

---

Fish version: [from the output of fish --version]
fish, version 2.3.0-235-g9d2092b

Ubuntu 16.04 and I use the nightly build of fish.

Terminal or terminal emulator: 
GNOME Terminal

**Comment by krader1961** [comment] 2016-06-10 13:34
I can't reproduce the problem. I can press \cU to delete the entire command line, or \cW to delete individual words, including the "cd", or [backspace] to delete individual letters, including the initial "c" without any difficulty.

What does `locale` output? Do your directory names contain non-ASCII characters? I ask the latter because I'm thinking this might be an issue handling characters with ambiguous widths or the character classification tables are telling fish the width is one when the terminal is using a width of two for one of the characters. If that hypothesis is correct then simply pressing [enter] after you've deleted the command will give you a new prompt without running a command named "c". If my guess is wrong then fish will tell you `unknown command 'c'`.

**Comment by Hunsu** [comment] 2016-06-10 13:42
> I can't reproduce the problem. I can press \cU to delete the entire command line, or \cW to delete individual words, including the "cd", or [backspace] to delete individual letters, including the initial "c" without any difficulty.

What's \cU and \cW? I use [backspace] to delete individual letters.

> What does locale output? 

    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC=fr_FR.UTF-8
    LC_TIME=fr_FR.UTF-8
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY=fr_FR.UTF-8
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER=fr_FR.UTF-8
    LC_NAME=fr_FR.UTF-8
    LC_ADDRESS=fr_FR.UTF-8
    LC_TELEPHONE=fr_FR.UTF-8
    LC_MEASUREMENT=fr_FR.UTF-8
    LC_IDENTIFICATION=fr_FR.UTF-8
    LC_ALL=

> Do your directory names contain non-ASCII characters?

No, but when I type [enter] I get a new prompt.

**Comment by krader1961** [comment] 2016-06-10 16:32
> What's \cU and \cW?

If you're using the default key bindings (as opposed to the vi bindings) they are respectively backward-kill-line and backward-kill-path-component (you can type `bind \cU` and `bind \cW` to see this).

> when I type [enter] I get a new prompt.

Which makes it pretty clear that fish is miscalculating the number of characters that need to be erased rather than it being impossible to delete the first character of the command. Your locale is an unusual combination of values but that shouldn't cause any problems.

Does your prompt contain any non-ASCII characters? For example, are you using the PowerLine font in your prompt? How certain are you those directory names are pure ASCII? Did you confirm it by doing something like `echo * | od -tx1z` to confirm no non-ASCII characters?

This is a situation where using https://asciinema.org/ and the `script` command together can help us understand the problem.

**Comment by faho** [comment] 2016-06-10 16:54
> If you're using the default key bindings (as opposed to the vi bindings) they are respectively backward-kill-line and backward-kill-path-component (you can type bind \cU and bind \cW to see this).

To be clear: "\cU" means "Control and 'u'".

**Comment by floam** [comment] 2016-06-10 18:05
I am reproducing this all of a sudden on OS X.

**Comment by floam** [comment] 2016-06-10 18:23
https://asciinema.org/a/1t1ktf3xvsdue141wqia1kj6n

You can download the screencast as JSON and see the escaped stuff you might inspect typescript for.

**Comment by floam** [comment] 2016-06-10 18:28
(you can't control-anything over them, or backspace)

**Comment by floam** [comment] 2016-06-13 02:22
https://asciinema.org/a/az9g5oxq206qdfcmnkhvcklw6

Hitting tab first causes the cursor to move to the right, and then it will not have the issue. Other than that, it does this all the time, if Terlar is selected as theme.

**Comment by floam** [comment] 2016-06-13 02:25
`<any character>`+`<TAB>`+`backspace` will leave the leftover character on screen.

**Comment by EduardoBautista** [comment] 2016-12-07 18:43
I having the same issue.

**Comment by RaphyJake** [comment] 2018-07-09 14:32
I was using the [AcidHub prompt](https://github.com/fish-shell/fish-shell/tree/master/share/tools/web_config/sample_prompts) wich uses some extended ascii characters and it gave me this exact problem.
Changing my prompt fixed it.

**Comment by JanczarKurek** [comment] 2019-06-17 22:10
Have the same issue, very annoying. Currently, i use fish on three different setups (all very similar) but only on my desktop it happens.

Just type ls and then hit tab few times and then backspace all text.

It has something to do with unicode - take for example my prompt https://github.com/JanczarKurek/random-stuff/blob/master/fish_prompt.fish

It is popular lambda theme, but without this clunky unicode "╭─" symbols.

With them, issue occurs, but not if i remove them.

**Comment by faho** [comment] 2019-06-19 10:26
Yeah, I'm gonna close this one.

This is another of a large group of issues with unicode and width. The answer is always the same:

fish and your terminal need to agree on character width. If they don't, issues occur. We now generate our width table directly from unicode's official documentation (https://github.com/ridiculousfish/widecharwidth), plus we have a few additional quirks e.g. for variation selectors. We also offer a variable to choose if your terminal supports unicode 9 ($fish_emoji_width - set it to 2 for >= unicode 9, 1 otherwise, with auto-detection in the upcoming 3.1 release) and  one to choose how wide ambiguous characters are supposed to be ($fish_ambiguous_width, set it to 1 or 2). At this point, if you have issues, you probably need to set those variables, and if that doesn't help it's quite likely your terminal is just wrong in its width calculation, and there's nothing we can do about that.

@JanczarKurek: Those characters are ambiguous, so you need to set $fish_ambiguous_width to the correct setting. For me that's 1.

**Closed by faho** 2019-06-19 10:26 UTC
Labels: bug
