### ISSUE TITLE
Request: Posix Complance when called as sh

### ISSUE THREAD

**Issue by GregDavidson** [fish-shell/fish-shell#10732] opened 2024-09-18 22:01 UTC
I would really love to use and recommend fish instead of bash and zsh on all of my systems (mostly BSD & Gnu/Linux).  Alas, bash and zsh have a killer feature: When called via a link named sh they emulate a Poxix-Compatible (Bourne-ish) shell.  Bash and zsh can be installed as a System Shell, process my logins, including the system customization scripts under /etc, and pass my extensions to all processes in my session via the environment.  There are many nicer modern shells yet none of them have this essential feature.  Fish would be the ideal shell to break through the glass ceiling and finally obsolete bash and zsh!  (Note that dash strips extensions from the environment and is therefore a terrible choice!)

**Comment by zanchey** [comment] 2024-09-19 01:29
Duplicate of #522

**Closed by zanchey** 2024-09-19 01:29 UTC
Labels: duplicate

**Comment by zanchey** [comment] 2024-09-19 01:32
This has been discussed before, in #522 and #4973. The general consensus from the committers is that we're not going to actively work on this. You can use fish as your login shell in many instances, and in others just start it from the existing environment. (System customisation scripts that are Bourne-shell-only have never been a great option anyway - tcsh has existed for many years!)

**Comment by krobelus** [comment] 2024-09-19 08:46
I want to be able to selectively enable a "practically compatible" mode, which would cover this.
