### ISSUE TITLE
Turn off fish greeting with command line parameter

### ISSUE THREAD

**Issue by Flurrywinde** [fish-shell/fish-shell#7571] opened 2020-12-22 15:05 UTC
Fish version: 3.1.2
Operating system: Arch Linux 5.4.84-1-lts #1 SMP x86_64 GNU/Linux
 $TERM: xterm-kitty

I currently have a fish_greeting function, and it runs each time a new interactive shell gets spawned. This is correct behavior, but sometimes I'd like to suppress the greeting for a particular situation, like if I'm using tmux. I have a layout that splits the screen into many little windows, and currently, I get the fish greeting in all of them. That's a little too much. LOL. In a case like this, I'd like just the command line prompt to appear, no greeting.

My thought was that it'd be nice if there was a command line option to suppress the greeting, or... is there some other way to suppress the greeting?

I tried `fish_greeting="" fish`, but it seems the greeting function takes precedence.

**Comment by faho** [comment] 2020-12-22 15:26
Duplicate of #7570.

**Closed by faho** 2020-12-22 15:26 UTC
