### ISSUE TITLE
 function __fish_git_files does not work for file path completions in git.fish

### ISSUE THREAD

**Issue by javamuc** [fish-shell/fish-shell#5498] opened 2019-01-08 22:03 UTC
With fish 2.7 the following was working, e.g

```
> git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
(use "git add/rm <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)

`deleted:    a/b/c/d/filename`

no changes added to commit (use "git add" and/or "git commit -a")
```

Then I was able to type `git add filen` and <tab> to have it completed to `git add a/b/c/d/filename`

Now with fish, version 3.0.0, this is not working anymore. I searched for the culprit and it seems that the new `__fish_git_files` does not work. I removed the file git.fish from the completions directory and added git.fish from fish version 2.7 and with that it works.

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
> 
>   sh -c 'env HOME=$(mktemp -d) fish'

Yes I did and it did not change the behavior.

**Comment by faho** [comment] 2019-01-08 22:04
Duplicate of #5476

**Closed by faho** 2019-01-08 22:04 UTC
