### ISSUE TITLE
suggest/request safety for getting commands from history

### ISSUE THREAD

**Issue by BMaxV** [fish-shell/fish-shell#9646] opened 2023-03-08 11:15 UTC
So, I had `rm -rf .git` in my history and I "up arrow + enter" 'ed faster than I read and thought and nuked my project history.

Which is 100% my fault. (and relatively tame compared to the alternatives)

But, since https://fishshell.com/docs/current/cmds/history.html exists, maybe it would be a cool feature to have another list of things that just aren't saved to history or automatically removed.

`rm rf` being one of them.

I also assumed that the history of a shell would be tied to the instance. I didn't expect it to be a global thing. Again, my mistake, but clearing the history when the instance is closed would be another way to deal with this.

Also, thanks for fish, it's great software!

**Comment by faho** [comment] 2023-03-08 11:53
Duplicate of #4441

**Comment by faho** [comment] 2023-03-08 11:53
Sorry, this isn't really possible.

There aren't really any ways for the shell to tell which commands are "safe".

**Closed by faho** 2023-03-08 11:53 UTC

**Comment by BMaxV** [comment] 2023-03-08 12:35
It could have been a by default empty list that users can populate with things that they consider dangerous. Safety as opt-in.

I understand the decision to close it but I find it a bit disappointing since it's clear this is a problem for certain users.

I can of course handle this myself by editing the history file. In that sense fish does provide the tools to do it already.
