### ISSUE TITLE
Runtime path not available after su.

### ISSUE THREAD

**Issue by Vintodrimmer** [fish-shell/fish-shell#3916] opened 2017-03-26 14:58 UTC
Good day.

If I run fish in the terminal from the regular user and then execute  `su root ` and  `fish`, I get the following errors:

```
<E> fish: Runtime path not available.
<E> fish: Try deleting the directory /tmp/fish.eichhorn and restarting fish.
```

Deleting the aforementioned directory removes the error, but I get following error when I try to launcd fish from the regular user:
```
<E> fish: Runtime path not available.
<E> fish: Try deleting the directory /tmp/fish.eichhorn and restarting fish.
<E> fish: Unable to open a pipe for universal variables using '.notifier': Permission denied
```

Information about the system:

```
# fish --version
fish, version 2.5.0
# echo $version
2.5.0
```
```
uname -a
Linux chrysalis 4.10.5-chrysalis #1 SMP PREEMPT Fri Mar 24 13:34:49 UTC 2017 x86_64 GNU/Linux
echo $TERM
rxvt-unicode-256color
```

Distribution is Void Linux.

I've tried to execute `sh -c 'env HOME=$(mktemp -d) fish'` from user and then switch to root, but the problem persisted

**Comment by krader1961** [comment] 2017-03-26 23:53
What is printed if you `echo $USER $XDG_RUNTIME_DIR` as yourself and after `su root`?

**Comment by Vintodrimmer** [comment] 2017-03-27 10:45
```
echo $USER $XDG_RUNTIME_DIR
eichhorn
su root
fish
echo $USER $XDG_RUNTIME_DIR
root

```

**Comment by krader1961** [comment] 2017-03-28 03:01
When you ran the commands I asked you to run, @Vintodrimmer, did you or did you not get the "Runtime path not available" error when you ran fish after `su root`? Because a) I can't reproduce your problem and b) fish should have created a */tmp/fish.root* directory given that `$USER` was "root" so there should not have been any conflict. What does `ls -ld /tmp/fish.*` output? What about `ls -l /tmp/fish.*`?

**Comment by Vintodrimmer** [comment] 2017-03-28 16:31
Good day, once again.

I did get an error, however I should clarify that I also get this [issue](https://github.com/fish-shell/fish-shell/issues/2745).

So I added `export USER=root` to my root's `~/.config/fish/config.fish`.

May that cause the problem?

The only folder that is created in the /tmp is for `eichhorn`.

```
ls -ld /tmp/fish.*
drwx------ 2 eichhorn eichhorn 60 Mar 28 18:25 /tmp/fish.eichhorn/
```
```
ls -l /tmp/fish.*
total 0
prw------- 1 eichhorn eichhorn 0 Mar 28 18:25 fishd.chrysalis.notifier|
```

**Comment by faho** [comment] 2017-03-28 17:02
>So I added export USER=root to my root's ~/.config/fish/config.fish.

>May that cause the problem?

No, but it will mask it.

@krader1961: Isn't using geteuid(3) the correct thing to do here instead of getuid(3)?

**Comment by krader1961** [comment] 2017-03-28 21:33
Never, ever, explicitly set `USER` except for testing purposes. If you don't set it is it `eichorn` after `su root`? After you `su root` what does `id -ru` output? If it isn't zero your su command is broken and that's why you're having this problem.

**Comment by Vintodrimmer** [comment] 2017-03-29 08:48
Sorry, for a bit of derailing, but what is a correct way to make fish aware, that I'm now running from root? If I don't set it explicitly, the only difference is the style of the promt.

Here's the output of the comands:
![commands](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2017-03-29-10%3A42%3A17-screenshot.png)

`id -ru ` returns zero.

May it be, becaurse I lack some package? I run a pretty bare-bones installation and may be missing some dependency that is responsible for the actions after `su`.

**Comment by faho** [comment] 2017-03-29 11:27
>May it be, becaurse I lack some package? I run a pretty bare-bones installation and may be missing some dependency that is responsible for the actions after su.

No. No dependency is needed here, the issue is much simpler:

- `su` changes the user and starts a new fish

- It leaves the $USER intact, meaning fish simply inherits it

- Fish assumes the $USER value it has been given is correct (which it _usually_ is)

Now, this can be fixed via simply always setting $USER, but I'm not sure if there isn't some sort of problem with that e.g. in networked setups (where querying the user database for the name takes a network round-trip). We could just use the UID for the filename, but then we'd still have $USER for prompts and such. Also, $HOME could possibly need similar treatment - my su sets it properly (and it also sets $USER, _unless_ you are switching to root), but maybe others don't.

**Comment by krader1961** [comment] 2017-03-29 23:45
Some `su` commands leave `$USER` unchanged only when switching to the root account and only if you don't use the `-l` flag. And some always set it to the id being switched to even if that user is root. `$HOME` is also unchanged unless you do `su -l`. In short you really should always use `su -l`. :smile: In fact, what I recommend is `sudo su -l` so you only need your password, not the root password.

We've been asked about this behavior at least twice that I could find: #2745 and #1828. And I'm pretty sure I've seen the same question on IRC/Gitter. We can certainly modify fish to display a warning and then "fix" the HOME and USER vars. Whether we should do so depends on whether anyone can think of how that could cause a different set of problems. Obviously we'll probably only want to do this for the root user since a) that's the only case where people are experiencing problems and b) if we always did it then the `sh -c 'env HOME=$(mktemp -d) fish'` trick wouldn't work.

**Comment by Vintodrimmer** [comment] 2017-03-30 09:23
>  In short you really should always use `su -l`

And that completely solves the problem. Thank you very much!

And thanks to everyone trying to help.

**Comment by faho** [comment] 2017-04-07 13:31
You know, that failure mode is unacceptable, I'm reopening this.

**Comment by krader1961** [comment] 2017-04-07 21:56
I agree, @faho. I would have reopened it myself but didn't notice that it was closed. We should definitely be friendlier than other shells in the face of this `su` bogosity. So the question is whether my proposal in my previous comment is the right fix or should we do something else.

**Comment by faho** [comment] 2017-04-07 22:08
@krader1961: Check out https://github.com/faho/fish-shell/commit/ec39b49f0e2b1553bca48032c739dd12d2485a51, which is my attempt.

What it does is just always set $USER and $HOME if uid == 0, otherwise it keeps trusting the inherited values. The idea behind it was that this was the only case we actually practically encountered.

I don't think this warrants a warning or error - the only thing that would do would annoy people who use `su`. They're not gonna stop, `su` isn't gonna change. What happens when an unstoppable force meets a small object (say, a fish)? Yeah, right.

Of course more elaborate solutions are also possible:

- We could introduce a $UID variable, like bash has - here $USER would stay at the old value while $UID would be 0. Note that some BSDs apparently have 2 users with uid 0 ("root" and "toor"), so having the uid might be helpful. OTOH we're not going to stop people from using $USER.

- We could use the uid as much as possible (for finding the tmp file, for getting $HOME) and just punt on the issue of telling the user "you are root" entirely - have them use `id`.

- We could force getting $USER more often - as I said above, I'm not sure how that interacts with more elaborate environments than my humble home, with ldap and kerberos and whatnot. I'm under the impression that in these cases `getuid` will be a local call, while `getpw` and friends might go over the network, which is slow.

- Combinations of these are also possible - introduce $UID, get $USER if uid == 0 _and_ rely on $USER less.

**Comment by krader1961** [comment] 2017-04-07 22:26
My thought behind issuing a warning is that it would also encourage the user to use `su -l` to avoid the warning. But you're probably right that it will just annoy people rather than get them to change their habits.

I'd prefer your simple solution assuming no one can see how that would cause problems And I can't see how it would other than possibly in some only vaguely UNIX like OS (e.g., Haiku). And if that happens we can always special-case that environment.

**Comment by zanchey** [comment] 2017-04-09 09:39
I'm not convinced that exchanging a modifiable behaviour for an unmodifiable one is the right thing to do here.

**Comment by faho** [comment] 2017-04-09 10:39
Okay, so how about this then:

- We check if the uid for $USER is equal to getuid()

- If it is, we use $USER and $HOME

- It is isn't, we get a new $USER and $HOME

That way, you could still use the `env HOME` trick, but to use it with `su` you'd need to either also override $USER, or you'd need to use `su -l`. The common case of just launching `su -c fish` would work properly (instead of how it is now).

(Note: We could also just use $HOME if $USER == "root" and uid == 0, but that might fail with the "toor" user or similar)

**Closed** 2017-04-18 13:12 UTC
Labels: enhancement
