### ISSUE TITLE
Auto-complete `apt install` for files

### ISSUE THREAD

**Issue by FWDekker** [fish-shell/fish-shell#7148] opened 2020-06-23 12:20 UTC
### Feature description
`apt install` can be used to install `.deb` files. For example `apt install ./firefox.deb` can be used to install Firefox if I have a file `firefox.deb` in the current directory.

Fish currently does not auto-complete filenames after writing `apt install`, which is bothersome when the file has a very long name.

### Version info
| Software | Version |
| --- | --- |
| Linux | 4.19.0-9 |
| Debian | 10 |
| fish | 3.0.2 |

No third-party modifications to fish.

**Comment by zanchey** [comment] 2020-06-23 12:26
Duplicate of #6209

**Closed by zanchey** 2020-06-23 12:26 UTC
Labels: duplicate

**Comment by FWDekker** [comment] 2020-06-23 12:29
Strange, must have overlooked that. Sorry!
