### ISSUE TITLE
lines with a long prompt are wrapped incorrectly

### ISSUE THREAD

**Issue by Kejia** [fish-shell/fish-shell#5425] opened 2018-12-20 15:35 UTC
please see the attached screenshot:
![incorrectly_long_lines_wrapping](https://user-images.githubusercontent.com/1039073/50293486-b0605780-0441-11e9-9de6-97dfa88d89fb.png)

long lines starting from a long prompt, which usually happens working on a git branch with a long branch name, are automatically wrapped at the second last char, leaving the last char to a new line. this also causes inputs not to be placed well.

not sure whether this is caused by a theme (in my case, the theme puts timestamp at the right margin for each command). i am confident that this is not caused by unicode chars in a prompt, because everything works well with short prompts. 

> $ fish --version                                                                                                     
> fish, version 2.7.1
> $ echo $version                                                                                                      
> 2.7.1
> $ uname -a                                                                                                           Darwin crystal.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
> $ echo $TERM                                                                                                         xterm-256color
> $ sh -c 'env HOME=$(mktemp -d) fish'                                                                                 Welcome to fish, the friendly interactive shell

**Comment by faho** [comment] 2018-12-22 08:55
>i am confident that this is not caused by unicode chars in a prompt

It ultimately still is. Doing a right prompt necessitates doing more cursor movement, so there's more opportunities to get it wrong.

I am confident this has improved in 3.0 - I've seen it happen with VTE a bunch - so I'm closing this as a duplicate of one of our numerous unicode issues, e.g. #4539.

**Closed by faho** 2018-12-22 08:55 UTC
