### ISSUE TITLE
Local function definition?

### ISSUE THREAD

**Issue by AlexSWall** [fish-shell/fish-shell#10298] opened 2024-02-13 19:10 UTC
In fish, I define multiple functions in different files in the usual way, and in multiple of these I create an inner function called `usage` to call should the arguments be wrong in some way.

Example: https://github.com/AlexSWall/dot-files/blob/main/fish/fish/functions/bak.fish

However, if I call one function, called `foo`, define a local `usage` function in it, and then if `foo` calls `bar` somewhere along the way and then later attempts to call the `usage` function, it will call the `usage` function of `bar` if `bar` has defined one.

Is there a way to declare a local function, in the same way as `set --local`? Am I doing something dumb?

**Comment by faho** [comment] 2024-02-13 19:55
Duplicate of #1799

**Closed by faho** 2024-02-13 19:55 UTC

**Comment by faho** [comment] 2024-02-13 19:57
At the moment, all functions in fish are global.

In this specific case, I would recommend making your usage message a variable and then simply printing that at point of use:

```fish
set -l usage 'Back up a file or directory.' \
             'Usage:' \
             ''
	     '    bak [-m/--mv] <path> [optional-postfix]'
	     '    bak -h/--help'

# and then later:

printf %s\n $usage
```
