### ISSUE TITLE
Issue with $PATH set in /etc/fish/config.fish after update to 3.3.0

### ISSUE THREAD

**Issue by JonnyCodewalker** [fish-shell/fish-shell#8106] opened 2021-07-03 10:25 UTC
Version: 3.3.0
OS: Solus 4.2

After updating I got some errors about the jdk-11 path.
Tracking it down I saw that in etc/fish/config.fish the following line was set, resulting in folder not found errors:
`set PATH /usr/lib64/openjdk-11/bin:$PATH`

Changing it to: 
`set PATH /usr/lib64/openjdk-11/bin  $PATH`
the errors disappeared.

Solus is trying to be stateless, so that configuration file should come from fish itself.

Hope this is not a duplicated, I did look around and not see the issue mentioned somewhere else.

**Comment by faho** [comment] 2021-07-03 10:28
Duplicate of #8095

**Comment by faho** [comment] 2021-07-03 10:28
>Solus is trying to be stateless, so that configuration file should come from fish itself.

It does not. Fish does not ship a /etc/fish/config.fish with that included.

**Closed by faho** 2021-07-03 10:28 UTC

**Comment by JonnyCodewalker** [comment] 2021-07-03 10:29
Interesting, not sure where that line came from then. Sorry about the duplicate.
