### ISSUE TITLE
Regex-friendly quote mode

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10696] opened 2024-09-01 19:54 UTC
Does anyone have an opinion on supporting triple single quotes to enter a context where both `'` and `\` have no special meaning? It increases the complexity to parse and *technically* breaks code that no one would normally write, but would really simplify a lot of the quoting and escaping special cases.

**Comment by faho** [comment] 2024-09-01 21:26
Duplicate of #9694

**Closed by faho** 2024-09-01 21:26 UTC
