### ISSUE TITLE
[completion] Allow no space delimiter between argument and its accepted completion string

### ISSUE THREAD

**Issue by FollieHiyuki** [fish-shell/fish-shell#9198] opened 2022-09-10 18:28 UTC
```sh
$ fish --version
fish, version 3.5.1
```

Hi! I'm trying to create fish completion for [vifm](https://vifm.info/) (the progress can be seen here https://github.com/vifm/vifm/pull/820). Right now there is 1 option I can't get to work:
```
vifm +<command>
    run <command> on startup.
```

Basically I want fish to pop the autocompletion menu for `__fish_complete_subcommand` after the user puts `+` into the command line and presses `<TAB>`. I tried manipulating the command line buffer in the completion list function (`complete -a`) with no luck so I'm putting a Github issue here.

Ideally I'd like `complete` command to have an option to set the delimiter between the argument and its accepted completion string (right now I assume it is ' ' and '='). So, in this specific case I can set the delimiter to '\0' and completion will work without messing with command line buffer.

I did read through https://github.com/fish-shell/fish-shell/issues/7832 but that issue concerns about space character after the completion string, not the one between it and the argument.

If this is already doable without any functional changes to fish's code base then I would appreciate any advice. My fish-fu is not really great to be honest.

**Comment by faho** [comment] 2022-09-10 18:29
Duplicate of #7832

**Comment by faho** [comment] 2022-09-10 18:29
>I did read through https://github.com/fish-shell/fish-shell/issues/7832 but that issue concerns about space character after the completion string, not the one between it and the argument.

Same thing. The completion string you would construct here would be `+foo`.

**Closed by faho** 2022-09-10 18:29 UTC

**Comment by FollieHiyuki** [comment] 2022-09-10 19:10
Thanks for clarification. It makes sense that way.

Though I still want `+` and `foo` to be separated entities (not to be a single completion string) because otherwise it would clutter up the completion menu in my case (there is also completion for file paths). So normally if the user types `vifm <TAB>` there will be no `+foo` completion. `+foo +bar` will only appears after the user type `vifm +<TAB>` for example.

So ideally I would imagine something like this:
```fish
# File completion and '+'
complete -c vifm -F -a "+"
# Complete commands only when '+' exists, maybe trim ' ' in some way
complete -c vifm -n "__fish_seen_subcommand_from +" -a "(__fish_complete_subcommand)"
```

and not feeding everything to the command directly:
```fish
complete -c vifm -a "+foo +bar <other things>"
```

Sorry if I'm still not understanding the linked issue correctly.

**Comment by faho** [comment] 2022-09-10 19:58
The linked issue would allow you to specify something like

```fish
complete -c vifm --unfinished -a "+"
complete -c vifm -a "<other things that are finished>"

# if the current token starts with a plus, start offering +commands.
complete -c vifm -n 'string match -q "+*" -- (commandline -ct)' -a "+foo +bar"
```

I.e. it would allow you to explain that a specific completion is not finished and so fish shouldn't insert a space to move on to the next token.

This allows you to only offer `+` initially, so you aren't overwhelmed by `+command` things.

**Comment by FollieHiyuki** [comment] 2022-09-11 02:46
Thanks for all the explanation. I'll follow the linked issue.
