### ISSUE TITLE
High CPU Usage on command substitution

### ISSUE THREAD

**Issue by syntonym** [fish-shell/fish-shell#5790] opened 2019-04-03 15:52 UTC
I have a helper script written in python for fuzzy changing directory, which I use in a command substitution:

```
cd (python ~/git/filemanager/ci_ls.py)
```

While the `ci_ls.py` script waits for user input fish CPU usage goes up to 100%. If I run the helper separately (just `python ~/git/filemanager/ci_ls.py`) this doesn't happen, so it's not the script that is using the CPU.

Is this a usage error? Are fish subshells not supposed to be "long running" (e.g. fish pulls continiously if stuff finished in subshells)?
```
~> fish --version
fish, version 3.0.2-800-gaa3dff0
~> uname -a
Linux kassandra 5.0.5-arch1-1-ARCH #1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux
~> echo $TERM
xterm-termite
```

This also happens if I use an empty config i.e. `sh -c 'env HOME=$(mktemp -d) fish'`

Actually it also happens when just sleeping, so it does reproduce by `cd (python -c "import time; time.sleep(20)")`

**Comment by faho** [comment] 2019-04-03 19:29
Duplicate of #5761.

**Closed by faho** 2019-04-03 19:29 UTC
