### ISSUE TITLE
Input FD redirections where fd>=3 doesn't work for builtins

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#532] opened 2013-01-20 08:39 UTC
Minimal case:

```
echo lorem ipsum > /tmp/a
cat 3</tmp/a <&3
read a 3</tmp/a <&3
```

The `cat` works as expected, it prints out the content of `/tmp/a`. `read` doesn't. It exits with code 1 and leaves `$a` as is.

As a result, `eval read` doesn't work - it brings up no `read>` prompt and (also) exits with code 1. FYI, the gut of `eval` is just

```
echo "begin; $argv ;end eval2_inner <&3 3<&-" | . 3<&0
```

BTW, this is not caused by my recently merged `split-io` branch; it is broken at least since acbb6fb8e2a12c9071b9729e4033cdb2a3d39c07. I'm not sure whether it ever worked...

**Comment by krader1961** [comment] 2017-04-12 02:43
This is duplicate of #3303 and #3948. Normally we would leave the older issue open and close the newer issues but in this instance I think closing the older issue makes more sense.

**Closed by krader1961** 2017-04-12 02:43 UTC
Labels: duplicate
