### ISSUE TITLE
urxvt -cd doesn't work with fish shell

### ISSUE THREAD

**Issue by heppu** [fish-shell/fish-shell#5656] opened 2019-02-13 13:41 UTC
I'm trying to set working directory for new terminal but it doesn't seem to work with fish shell. If I switch to bash everything seem's to be working fine. Is there some workaround/fix for this?

With bash:
```
$ pwd
/home/heppu
$ urxvt -cd /etc
$ pwd
/etc
```

With fish:
```
$ pwd
/home/heppu
$ urxvt -cd /etc
$ pwd
/home/heppu 
```

Fish version: 3.0.1
Linux: 4.20.7-arch1-1-ARCH
Terminal: rxvt-unicode-256color

**Comment by faho** [comment] 2019-02-13 13:45
Duplicate of #5647

**Closed by faho** 2019-02-13 13:45 UTC
