### ISSUE TITLE
TAB no reponse with a soft link directory which is linked to an offline NFS directory

### ISSUE THREAD

**Issue by Hacksign** [fish-shell/fish-shell#3026] opened 2016-05-13 07:42 UTC
what I have done :
1. ln -svf 192.168.1.100:/nfs/directory/path /home/xxx/test
2. poweroff 192.168.1.100
3. login as user xxx,then under home directory 'ls <TAB><TAB>' (tab is keyboard keycap click)

what happend :
shell no response, no auto-complete result appears.

Is there any solution to solve this problem ?

**Comment by zanchey** [comment] 2016-05-13 07:58
Annoyingly not - this is a duplicate of #23 with the added bonus that on systems where the NFS filesystem is hard-mounted, the process will hang in uninterruptible sleep forever! Hooray! I'm going to close in favour of the original.

**Closed by zanchey** 2016-05-13 07:58 UTC
