### ISSUE TITLE
Simplify completion candidates

### ISSUE THREAD

**Issue by yamatsum** [fish-shell/fish-shell#8293] opened 2021-09-14 14:45 UTC
Completion output seems verbose when trying to move directories with the cd command.
<img width="1100" alt="CleanShot 2021-09-14 at 23 42 20@2x" src="https://user-images.githubusercontent.com/42740055/133279154-f1a58d18-aea4-4d7e-80c6-ca91e72d6963.png">

For example, is it possible to have only `fish/` as a candidate for completion instead of `.config/fish/`?
<img width="1086" alt="CleanShot 2021-09-14 at 23 44 24@2x" src="https://user-images.githubusercontent.com/42740055/133279507-eac11390-355a-46a3-a943-7438920a195a.png">
This is the result of zsh's complementary plugin

**Comment by faho** [comment] 2021-09-14 15:18
Duplicate of #3732

**Comment by faho** [comment] 2021-09-14 15:18
We've rejected this before, sorry.

**Closed by faho** 2021-09-14 15:18 UTC

**Comment by yamatsum** [comment] 2021-10-05 15:26
@faho At #3732, most people seem to be wondering about this specification.
Why is it closed while the complementary candidates are in favor of simplicity?
