### ISSUE TITLE
`test -z $foo` and `test -n $foo` both return true for an undefined variable.

### ISSUE THREAD

**Issue by terrycloth** [fish-shell/fish-shell#2328] opened 2015-08-24 05:38 UTC
Pick a variable name which is not in use yet, e.g., `foo`. Then try this.

``` fish
> if test -z $foo; echo "zero"; end
> if test -n $foo; echo "not zero"; end
```

Both tests return true and `echo` executes, even though the if statements use opposite tests.

I'm running fish on Fedora 22 x64. I've tried this on both the version available in the Fedora repos (2.1.1) and from compiling the latest release (2.2.0).

**Comment by zanchey** [comment] 2015-08-24 05:51
You're being bitten by the behaviour standardised in [POSIX/SUS](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html), which fish follows but perhaps shouldn't. I'm going to close this as a duplicate of #2037 for now, as we are thinking about breaking compatibility. See #2133 for an explanation as well.

**Closed by zanchey** 2015-08-24 05:51 UTC
