### ISSUE TITLE
Add set --function

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7778] opened 2021-03-04 20:12 UTC
This idea has been floated, and accepted I believe, elsewhere. However, I think everything should be tracked in one spot and not in people's brains, so I'm opening this issue.

Basically we want to remove this idiom where we set a bunch of variables outside of a block so that they will persist afterwards:

```fish
set -l staged
set -l dirty
set -l untracked
set -l conflicted
set -l stash

if test "$isInsideWorkTree" = true
    set -l gitInfo (git status --porcelain)
    set staged (string match --regex '^[ADMR] ' $gitInfo | count) || set -e staged
    set dirty (string match --regex '^ [ADMR]' $gitInfo | count) || set -e dirty
    set untracked (string match --regex '^\?\?' $gitInfo | count) || set -e untracked
    set conflicted (string match --regex '^UU' $gitInfo | count) || set -e conflicted
    set stash (git stash list | count) || set -e stash
end

# Use the local variables
```

and replace it with

```fish
if test "$isInsideWorkTree" = true
    set -l gitInfo (git status --porcelain)
    set -f staged (string match --regex '^[ADMR] ' $gitInfo | count) || set -e staged
    set -f dirty (string match --regex '^ [ADMR]' $gitInfo | count) || set -e dirty
    set -f untracked (string match --regex '^\?\?' $gitInfo | count) || set -e untracked
    set -f conflicted (string match --regex '^UU' $gitInfo | count) || set -e conflicted
    set -f stash (git stash list | count) || set -e stash
end
```

**Comment by faho** [comment] 2021-03-04 20:13
Duplicate of #565

**Closed by faho** 2021-03-04 20:13 UTC

**Comment by IlanCosman** [comment] 2021-03-04 20:14
Ah, ok, wow that's a really old issue 😂
