### ISSUE TITLE
Current master cannot be compiled on Ubuntu Trusty (LTS)

### ISSUE THREAD

**Issue by languitar** [fish-shell/fish-shell#2509] opened 2015-10-29 11:26 UTC
The PCRE-version in the current master contains a makefile which requires aclocal 1.15 (automake). Ubuntu trusty as the current LTS version only ships 1.14. Therefore, compiling the current master fails on trusty:
```
make[1]: Entering directory `/homes/jwienke/local/trusty/x86_64/src/fish-shell/pcre2-10.20'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /homes/jwienke/local/trusty/x86_64/src/fish-shell/pcre2-10.20/missing aclocal-1.15 -I m4
/homes/jwienke/local/trusty/x86_64/src/fish-shell/pcre2-10.20/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [aclocal.m4] Error 127
make[1]: Leaving directory `/homes/jwienke/local/trusty/x86_64/src/fish-shell/pcre2-10.20'
make: *** [pcre2-10.20/.libs/libpcre2-32.a] Error 2
```

**Comment by faho** [comment] 2015-10-29 12:17
This is a duplicate of #2469.

As a workaround, use the nightly tarballs (the orig.tar.gz things) from [the opensuse build service](https://build.opensuse.org/package/show/shells:fish:nightly:master/fish) which already has that stuff generated.

**Closed by faho** 2015-10-29 12:17 UTC

**Comment by zanchey** [comment] 2015-10-29 15:14
Alternatively, just run `autoreconf` instead of `autoconf`.
