### ISSUE TITLE
Zero Length Interpolation Problem

### ISSUE THREAD

**Issue by tony-o** [fish-shell/fish-shell#8461] opened 2021-11-19 07:45 UTC
### Problem:

String interpolation seems to fail on zero length:

```
~ 8s ❱ echo "test '"(echo -n 'test')"'"
test 'test'
~ ❱ echo "test '"(echo -n)"'"

~ ❱ # expected output:

bash-5.1$ echo "test '$(echo -n)'"
test ''
```

### Environment

```
~ ❱ fish --version
fish, version 3.3.1
~ ❱ uname -a
Darwin tonyos-MacBook-Air.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
~ ❱ echo $TERM
xterm-256color
```

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

```
 ~ 12.6s ❱ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
tonyo@tonyos-MacBook-Air /U/tonyo> echo "test '"(echo -n)"'"

tonyo@tonyos-MacBook-Air /U/tonyo>
```

**Comment by faho** [comment] 2021-11-19 07:53
Duplicate of #4961

**Closed by faho** 2021-11-19 07:53 UTC

**Comment by faho** [comment] 2021-11-19 07:56
What happens here is that fish combines every element in the command substitution with the strings around it, but since there's no element in the command substitution this leads to nothing.

This is often what you want - e.g. `for i in $list/foo` will go through all the "foo" files in the directories given in $list, and if $list is empty it won't check "/foo". It does lead to this, which does often confuse people. Unfortunately it's not clear anything else would be better.

Also the upcoming fish 3.4.0 features `"$()"` command substitutions which collapse to the empty string if nothing was printed, so the bash syntax works exactly the same.
