### ISSUE TITLE
fish 3.1.1 hangs when editing functions with 'funced <func name>

### ISSUE THREAD

**Issue by zeheater** [fish-shell/fish-shell#6988] opened 2020-05-09 13:53 UTC
#fish --version
fish, version 3.1.1

#uname -a
Linux 5.6.11-arch1-1

TERM : xterm

Happens with and without third party

Step to reproduce:
Install fish, and install terminal editor (i use neovim)

set -g EDITOR `nvim`

then execute: 

funced ll

then it hangs, 

This doesn't happen in fish 3.1.0

![1589031860](https://user-images.githubusercontent.com/6127739/81475396-1f586f00-9236-11ea-9277-fcb71c768e58.png)

<Ctrl+c>

![1589032304](https://user-images.githubusercontent.com/6127739/81475526-1025f100-9237-11ea-9a9d-788c3bfab85f.png)

**Comment by krobelus** [comment] 2020-05-09 13:58
Duplicate of #6975, upgrade to 3.1.2

**Closed by krobelus** 2020-05-09 13:58 UTC
