### ISSUE TITLE
eval during Startup not working

### ISSUE THREAD

**Issue by kz89** [fish-shell/fish-shell#6487] opened 2020-01-09 22:37 UTC
```
fish, version 2.7.1-1591-gfb0c1460
Darwin MacBook-XXX.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
xterm-256color
```

Hi,

So I'm trying to edit the _~/.config/fish/config.fish_ so that during the startup it changes Docker's machine context. Command to do that is:
`docker-machine env`
and the output of that command is:
```
set -gx DOCKER_TLS_VERIFY "1";
set -gx DOCKER_HOST "tcp://192.168.99.100:2376";
set -gx DOCKER_CERT_PATH "/Users/XXX/.docker/machine/machines/default";
set -gx DOCKER_MACHINE_NAME "default";
# Run this command to configure your shell:
# eval (docker-machine env)
```
So I have created the _~/.config/fish/config.fish_ file with content like:
```
echo starting
eval (docker-machine env)
echo done
```
And now every time I open new fish shell I'm seeing "starting" and then... nothing. The shell hangs. I cannot type anything, I cannot ctrl+c. All I can do is close the tab. [Proof.](https://i.imgur.com/rStzlBh.png)

So my other idea was to create an autoloading function "dock" like:
```
function dock
  eval (docker-machine env)
end
```
When I'm calling this function from the shell it works fine. When I'm calling this function from the _~/.config/fish/config.fish_ file like:
```
echo starting
dock
echo done
```
it's the same story - shell hangs.

Any ideas?

**Comment by zanchey** [comment] 2020-01-10 02:22
Duplicate of #5210 which is fixed in fish 3.0.0. If you upgrade then this problem should be resolved.

(Side note - it would be worth guarding your `config.fish` statements with `if status is-interactive ...` , otherwise you might run into trouble with non-interactive processes.)

**Closed by zanchey** 2020-01-10 02:22 UTC
Labels: duplicate
