### ISSUE TITLE
[?2004h before prompt randomly after pressing enter

### ISSUE THREAD

**Issue by sph3** [fish-shell/fish-shell#8803] opened 2022-03-16 23:11 UTC
Fish version: 3.4.0
WSL Ubuntu 21.10
xterm-256color
Linux wsl 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Tabby Terminal v1.0.173

Issue happens both with and without customizations. With several different fonts too.

It doesn't happen consistently, but whenever I press enter to send a command or just press enter with a blank line, it shows this weird "[?2004h" before the prompt.
Asciinema doesn't record it.

![16_Tabby_20h-12m_Growing](https://user-images.githubusercontent.com/59633047/158706316-c26bc9b7-e370-4369-971f-59e4b4c2b17e.jpg)

**Comment by ridiculousfish** [comment] 2022-03-17 03:21
This looks like the escape sequence to [enable bracketed paste](http://www.xfree86.org/current/ctlseqs.html#Bracketed%20Paste%20Mode), which Tabby claims to support so this should not be printed. What does:

    printf "\e[?2004h"

show for you?

**Comment by faho** [comment] 2022-03-17 06:29
Duplicate of #8240

**Comment by faho** [comment] 2022-03-17 06:29
It's a bug in Windows' conpty

**Closed by faho** 2022-03-17 06:29 UTC
Labels: question

**Comment by sph3** [comment] 2022-03-17 15:42
> This looks like the escape sequence to [enable bracketed paste](http://www.xfree86.org/current/ctlseqs.html#Bracketed%20Paste%20Mode), which Tabby claims to support so this should not be printed. What does:
> 
> ```
> printf "\e[?2004h"
> ```
> 
> show for you?

![image](https://user-images.githubusercontent.com/59633047/158837542-a4315eb4-1def-41da-a37b-807f9decab8e.png)
