### ISSUE TITLE
Can't redirect stderr if it occurs in if statement

### ISSUE THREAD

**Issue by JBlaschke** [fish-shell/fish-shell#6459] opened 2019-12-28 21:43 UTC
I am trying to capture the `stderr` output (`my_parent_func`) from a fish function, which calls another function (`my_child_func`) as a subprocess using:

```fish
# in my_parent_func
if set output (my_child_func)
```
`my_child_func` can write to `stderr`, so when I call `my_parent_func`, I redirect `stderr` to `stdout` as follows:
```fish
set all_output (my_parent_func 2>&1)
```
This does not capture the `stderr` from `my_child_func` (see simple example below)

## Environment:

1. fish, version 3.0.2
2. `TERM` = xterm-256color
3. reproducible within `sh -c 'env HOME=$(mktemp -d) fish'`

## Reproducing the Problem

1. Define the following functions:
```fish
function cause_error
	echo "this is an error" 1>&2
	return 1
end

function spam
	if set output (cause_error)
		echo "no error: $status"
	else
		echo "error: $status"
	end
end
```

2. Run
```fish
set all_output (spam 2>&1)
```

### Expected behaviour: 

No `stderr` output, and `all_output` contains:
```
error: 1
this is an error
```

### Current behaviour:

The `stderr` output from spam (`this is an error`) is not rerouted to `stdout`. Running
```fish
set all_output (spam 2>&1)
```
leaves `this is an error` in `stderr`, and `all_output` contains only:
```
error: 1
```

**Comment by faho** [comment] 2019-12-28 22:00
Duplicate of #1035

The issue being that we don't pass on stderr redirections from the command substitutions.

**Closed by faho** 2019-12-28 22:00 UTC

**Comment by JBlaschke** [comment] 2019-12-28 22:03
Ah! I didn't see that. Thanks.

What is the recommended way of dealing with command substitutions? Manually capturing the stderr?

**Comment by JBlaschke** [comment] 2019-12-29 19:43
In the mean time, I've written a function that will manually capture `stdout`, `stderr`, and `status` for me. Based on the solutions in #2463, and [this answer on stack exchange][se_solution]. This seems the natural thing to do, if anyone has a better idea, let me know

```fish
function capture_all
	begin;
		begin;
			eval $argv[1]
			set $argv[2] $status  # read sets the `status` flag => capture here
		end 2>| read -z __err
	end 1>| read -z __out

	# output arrays
	set $argv[3] (echo $__out | string split \n)
	set $argv[4] (echo $__err | string split \n)

	return 0
	end
```
This function sets global variables (which the user specifies) to the captured output. For example:
```fish
set -g stat
set -g out
set -g err
capture_all "cause_error" stat out err
```
(the command needs to passed as a single string).
[se_solution]: https://unix.stackexchange.com/questions/379996/capture-stdout-and-stderr-as-separate-variables-in-fish-shell
