### ISSUE TITLE
Fish as the leader of fastest shell

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2776] opened 2016-02-28 11:28 UTC
``` fish
> cat test.fish
for i in (seq 1000)
    command ls > /dev/null
end
> cat test.sh
for i in $(seq 1000) ; do
    ls > /dev/null
done
> time fish test.fish; time mksh test.sh; time bash test.sh
0.62user 1.09system 0:07.28elapsed 23%CPU (0avgtext+0avgdata 4396maxresident)k
0inputs+0outputs (0major+108240minor)pagefaults 0swaps
0.21user 0.62system 0:06.92elapsed 11%CPU (0avgtext+0avgdata 1888maxresident)k
0inputs+0outputs (0major+116674minor)pagefaults 0swaps
0.29user 0.81system 0:07.78elapsed 14%CPU (0avgtext+0avgdata 2780maxresident)k
0inputs+0outputs (0major+145628minor)pagefaults 0swaps
```

@ridiculousfish Benchmarks are taken on latest git fish with archlinuxarm on raspberry pi 2.

**Comment by oranja** [comment] 2016-02-28 11:48
This benchmark is not really fair. Even on the relatively simple Pi-2, I expect the first run to be much slower then the rest, due to caching.

**Comment by pickfire** [comment] 2016-02-28 11:50
@oranja, it's not the first run, I took many run (5) and get the best result.

**Comment by faho** [comment] 2016-02-28 12:47
There's a few things to note here:

- When comparing fish to other shells, config files are of interest - fish will read all of them, while other shells only read special (presumably stripped-down) files for non-interactive use.

@pickfire: You've cleared your config.fish, so that's not included, but this is something to keep in mind. Though presumably if the end result is the same you don't care how much more work fish did to get there.

- fish has a `--profile` option that might be of use here.

- #2498 _will_ slow this down when it's used (i.e. when you have snippets) - though none of my attempts have sped it up much

- We're actually doing okay when it comes to this test (i.e. starting and calling a command) - other things are much more in need of optimization (see #2007)

**Comment by pickfire** [comment] 2016-02-28 13:03
@faho, I really hope that `fish` can be faster than `mksh`, if you are interested in `--profile` that I had done:

[log.txt](https://github.com/fish-shell/fish-shell/files/149905/log.txt)

**Comment by faho** [comment] 2016-02-28 13:19
@pickfire: Okay, that log shows (`sort --numeric-sort -k 2` is your friend here) that 7.5s were spent on the entirety of the for-loop, plus 23.8ms on sourcing /usr/share/fish/config.fish - i.e. about as long as 3 ls-calls. So it's completely dominated by calling ls. (The numbers are probably a bit higher here because the profiling itself isn't free)

So it's actually interesting that mksh manages to be faster.

On my system it's close enough to not matter either way (consistently mksh < fish < bash < zsh, but within 0.08s of each other - this is _with_ extensive fish customization, a medium bashrc and a comparatively tiny zshrc).

**Comment by pickfire** [comment] 2016-02-28 13:52
Ah, I didn't know there is `/usr/share/fish/config.fish`. It is actually for completion, totally worthless.

Yeah, I figured it out, like you said `mksh < fish < bash < zsh` but not sure why `mksh` always wins.

@faho And one more thing, mkshrc by default is actually a bit huge which has 600+ lines (comments included).

**Comment by faho** [comment] 2016-02-28 14:13
>Ah, I didn't know there is /usr/share/fish/config.fish. It is actually for completion, totally worthless.

Not quite - look at the very first non-comment line: `set -g IFS \n \t`. I don't think you'd want to run a shell without that. Setting up the function path is also rather important.

>@faho And one more thing, mkshrc by default is actually a bit huge which has 600+ lines (comments included).

I didn't actually have that because arch only puts it in /etc/skel. Though even after copying it to ~ it doesn't slow mksh down even one centisecond. That's rather impressive. Though of course size doesn't matter (.............) - this file has everything protected from aliasing by prepending "\\".

And, as we saw earlier, the config file doesn't matter - it barely shows up in fish, even with my (comparatively) extensive customization.

**Comment by pickfire** [comment] 2016-02-28 14:33
Woah, now to get the **fastest shell** title, I guess we really need to be faster than `mksh` which can doesn't even slow down a centisecond by loading a 600+ lines file.

**Comment by ridiculousfish** [comment] 2016-02-28 20:24
Universal variables are also relevant  - it's easy to forget about those.

**Comment by pickfire** [comment] 2016-02-29 02:13
@ridiculousfish My universal variable is no more than 25, I don't know if universal variables can be optimized. Well, of course it is better so.

**Comment by bucaran** [comment] 2016-02-29 06:46
@pickfire If you don't mind, can you post the output of `set -U`?

**Comment by pickfire** [comment] 2016-02-29 13:11
@bucaran Oh I found it a lot now.
[log.txt](https://github.com/fish-shell/fish-shell/files/150935/log.txt)

**Comment by faho** [comment] 2016-02-29 13:38
@pickfire: That's the short version. You'll want to add "-L" to the options you pass to set - for all we know, these CFLAGS or fish_user_abbreviations could be gigantic. They're probably not, as what your times look about right, but something like `set -U fish_user_paths $fish_user_paths ~/.local/bin` in config.fish would baloon the variable and cause fish to become slower (if only because it'd need to allocate all that memory).

(Also, there's some sort of token in there you might want to censor)

@bucaran: fishtape is yours, right? Any reason why you're keeping all those variable copies around?

**Comment by bucaran** [comment] 2016-02-29 14:04
I thought so. @pickfire Please update fishtape, that is caused by a bug in an older version. The latest fishtape correctly removes those variables.

**Comment by pickfire** [comment] 2016-02-29 14:39
Updated fishtape.

@faho, ah there is some password there. By the way, I didn't know that gigantic `$fish_user_paths` can make fish slow too.

@bucaran, it seems like the `xargs` command that I give you didn't worked, it is just updating the index, didn't work. Let me check.

**Comment by pickfire** [comment] 2016-03-20 13:18
@ridiculousfish I did another benchmark recently, now including `dash` and the results for fish is a lot worse. There results are the following (I did three test and get the best result):

    dash < mksh < bash < fish

```fish
> fish -v
fish, version dedc7f6
> bash --version
GNU bash, version 4.3.42(1)-release (armv7l-unknown-linux-gnueabihf)
> echo $KSH_VERSION
@(#)MIRBSD KSH R52 2016/03/04
> pacman -Qs dash
local/dash 0.5.8-1
> time fish test.fish
0.68user 1.98system 0:09.15elapsed 29%CPU (0avgtext+0avgdata 4712maxresident)k
0inputs+0outputs (0major+109838minor)pagefaults 0swaps
> time bash test.sh
0.27user 1.12system 0:08.86elapsed 15%CPU (0avgtext+0avgdata 2840maxresident)k
0inputs+0outputs (0major+149668minor)pagefaults 0swaps
> time mksh test.sh
0.15user 0.80system 0:07.74elapsed 12%CPU (0avgtext+0avgdata 1900maxresident)k
0inputs+0outputs (0major+119260minor)pagefaults 0swaps
> time dash test.sh
0.10user 0.63system 0:06.98elapsed 10%CPU (0avgtext+0avgdata 1900maxresident)k
0inputs+0outputs (0major+100868minor)pagefaults 0swaps
```
Even after I reset those fish configuration files, the result are even worse.

**Comment by ridiculousfish** [comment] 2016-03-21 04:32
What exactly were the test scripts? What was the contents of the config files? What was the contents of the universal variable file?

**Comment by pickfire** [comment] 2016-03-21 12:46
@ridiculousfish The test scripts are the same as the first post on this page.

I had test it with all the lines in the config files removed, it is even slower. So I don't think it will be the case, https://github.com/pickfire/dotfiles/blob/alarm/home/config/fish/config.fish

[env.txt](https://github.com/fish-shell/fish-shell/files/182179/env.txt), it is a lot longer than before. My password is there, anyone can help me to play the wargames and earn points for me. :)

**Comment by ridiculousfish** [comment] 2016-03-21 19:44
Removing stuff like `source $fisher_home/config.fish` makes running the script in the first post slower? That's rather suspicious, don't you think?

I still can't reproduce this incidentally.

**Comment by pickfire** [comment] 2016-03-22 14:17
Now I still don't get why the results is so different compared to last time. Even `mksh` surprised me.

**Comment by krader1961** [comment] 2016-03-25 02:34
@pickfire: In a previous job working for Sequent Computer Systems one of my duties was dealing with performance issues reported by customers and doing benchmarking. Benchmarking is really, really, hard if you care about reproducibility of the results. Heck, just designing an appropriate benchmark that measures something meaningful is really hard.

In the benchmarking community there are a huge number of micro-benchmarks that people (mostly companies who want to sell you something) use to show that product X is better than Y. They're mostly crap, or at least don't tell a consumer anything useful about how a system will behave under typical conditions.

I modified the simple scripts in your original comment. I replaced the `ls` command with `true`. So outside of whatever external commands each shell runs during startup (as well as other things like reading config files) we're measuring just the speed of the parser and execution engine in each shell. Furthermore, I ensured fish wasn't using my personal configuration or universal vars:

```
mkdir /tmp/bogus
env XDG_CONFIG_HOME=/tmp/bogus XDG_DATA_HOME=/tmp/bogus time fish test.fish
```

Fish took almost three times longer, both elapsed and cpu user mode time, than bash on OS X, and more than 20x slower than ksh. Profiling showed that all the extra time was in running `builtin source /usr/local/share/fish/config.fish`. So I did `mv /usr/local/share/fish /usr/local/share/fish.old` and reran the test. That resulted in fish being indistinguishable from ksh and an order of magnitude faster than bash.

So there might be opportunities to improve the efficiency of the global *config.fish* file to reduce the cost of starting a new fish shell. Beyond that I don't know what you're trying to accomplish with this issue. Fish is never going to be a speed daemon due to its, by design, far larger dependency on external commands than other shells.

**Comment by pickfire** [comment] 2016-03-25 06:34
@krader1961 Yup, I am going to benchmark it with your benchmarking script, I guess it is really important to keep the startup process fast as it not only waste our own time and instead it waste the time of the fishers.

I will benchmark it without my configurations file and variables but `/usr/local/share/fish` must be included, that's runned by everyone during startup. The file should now be:

```fish
for i in (seq 1000)
    command true > /dev/null
end
```
And will be runned by `env XDG_CONFIG_HOME=/tmp/bogus XDG_DATA_HOME=/tmp/bogus time fish test.fish`.

**Comment by alphapapa** [comment] 2016-03-25 08:02
Just want to say thanks to all of your for your work on speeding up Fish.  :)

**Comment by pickfire** [comment] 2016-03-25 12:56
@krader1961 This test is even insane, fish is almost *10x slower* compare to other shells.

```fish
> cat test.fish
for i in (seq 1000)
    command true > /dev/null
end
> cat test.sh
for i in $(seq 1000) ; do
    true > /dev/null
done
> env XDG_CONFIG_HOME=/tmp/bogus XDG_DATA_HOME=/tmp/bogus time fish test.fish
0.67user 2.01system 0:07.28elapsed 36%CPU (0avgtext+0avgdata 4548maxresident)k
0inputs+0outputs (0major+83066minor)pagefaults 0swaps
> time bash test.sh
0.13user 0.04system 0:00.18elapsed 91%CPU (0avgtext+0avgdata 2820maxresident)k
0inputs+0outputs (0major+312minor)pagefaults 0swaps
> time mksh test.sh
0.04user 0.03system 0:00.08elapsed 85%CPU (0avgtext+0avgdata 1528maxresident)k
0inputs+0outputs (0major+202minor)pagefaults 0swaps
> time dash test.sh
0.03user 0.01system 0:00.05elapsed 74%CPU (0avgtext+0avgdata 1744maxresident)k
0inputs+0outputs (0major+164minor)pagefaults 0swaps
```
The results are still the same as above, `dash < mksh < bash < fish`

**Comment by krader1961** [comment] 2016-03-25 14:46
@pickfire: Why did you modify my script? Specifically, why did you change `true` to `command true > /dev/null`? That will cause fish to run the external `/usr/bin/true` (or perhaps `/bin/true`). Whereas in the other shells it's going to be a builtin. You're not comparing apples to apples. And drop the redirection to `> /dev/null` from both scripts. The true command doesn't produce any output and the redirection is just noise.

**Comment by pickfire** [comment] 2016-03-26 04:42
@krader1961 Fish is still the slowest if so.
```fish
> env XDG_CONFIG_HOME=/tmp/bogus XDG_DATA_HOME=/tmp/bogus time fish test.fish
0.27user 0.02system 0:00.30elapsed 95%CPU (0avgtext+0avgdata 4664maxresident)k
0inputs+0outputs (0major+1096minor)pagefaults 0swaps
```

**Comment by pickfire** [comment] 2016-03-26 04:45
After dropping redirection, fish is still the slowest too:
```fish
> cat test.sh
for i in $(seq 1000) ; do
    true
done
> cat test.fish
for i in (seq 1000)
    true
end
> env XDG_CONFIG_HOME=/tmp/bogus XDG_DATA_HOME=/tmp/bogus time fish test.fish
0.21user 0.04system 0:00.26elapsed 94%CPU (0avgtext+0avgdata 4548maxresident)k
0inputs+0outputs (0major+1103minor)pagefaults 0swaps
> time bash test.sh
0.08user 0.00system 0:00.09elapsed 86%CPU (0avgtext+0avgdata 2824maxresident)k
0inputs+0outputs (0major+310minor)pagefaults 0swaps
> time mksh test.sh
0.02user 0.01system 0:00.03elapsed 76%CPU (0avgtext+0avgdata 1604maxresident)k
0inputs+0outputs (0major+203minor)pagefaults 0swaps
> time dash test.sh
0.01user 0.00system 0:00.02elapsed 43%CPU (0avgtext+0avgdata 1532maxresident)k
0inputs+0outputs (0major+165minor)pagefaults 0swaps
```

**Comment by ridiculousfish** [comment] 2016-03-27 04:18
Yes, fish is the slowest at running `true` because `true` is a builtin in other shells, but not fish. If we think this is interesting or important, we could easily make `true` a builtin in fish too. But I don't think we need to - nobody has asked for it.

@pickfire it's dangerous to report benchmark results without also reporting what exactly we're measuring, and why the results are what they are. People can latch onto them and draw wrong conclusions. 

I'd love to have you involved in crafting a real benchmarking suite, with benchmarks for specific areas: startup, external command execution, builtin / function execution, memory usage, and real-world scripts are some that come to mind. Having analogous scripts for other shells could be part of that too. If you'd like to propose some scripts to be part of the benchmark suite, I'll be glad to help review them.

**Comment by pickfire** [comment] 2016-03-27 04:47
@ridiculousfish Nice job, I would love it. So should I start the benchmarking suite project in fish-shell? I guess it would be nice but I am actually not very sure about how to do a good benchmarking suite.

**Comment by faho** [comment] 2016-03-27 12:54
>Yes, fish is the slowest at running true because true is a builtin in other shells, but not fish. 

@ridiculousfish: It's in `builtin -n`, so it should already be a builtin. `builtin true` also succeeds.

**Comment by ridiculousfish** [comment] 2016-03-27 19:14
Oh, so it is! Shows what I know!

**Comment by ridiculousfish** [comment] 2016-03-27 19:37
@pickfire Here's one way to go about it:

1. Build a test harness. This is a wrapper script that isolates the environment, runs a benchmark script N times, does the results aggregation (best-of-N or whatever), and then outputs the results in some nice format.

2. Build the actual benchmark scripts. These should either be highly focused (testing just startup, just external command execution, just the `test` builtin, etc) or realistic, like the git command completion or other real-world scripts.

A fine way to start would be to make a `benchmark` directory like the `test` directory, have one simple benchmark in it, and be able to run `make benchmark` to get benchmark results.

**Comment by krader1961** [comment] 2016-03-28 03:09
There are two reasons to run benchmarks:

1) Verify that a change doesn't make the project slower relative to its current implementation.

2) Compare the performance to another implementation.

@pickfire has been focused on the latter. I would argue that the former, avoiding performance regressions, is more valuable at this point in fish's evolution. Our performance relative to comparable shells is "good enough" that there is little reason to invest in improving it. Especially when you consider all the other open issues that are bugs or enhancement requests that would greatly improve the usability of fish.

Once we have a framework that helps us know when we're introducing changes that make performance worse we can worry about improving performance relative to our competition.

**Comment by pickfire** [comment] 2016-03-28 08:59
So basically the building blocks are:
```
directory
|-- Makefile
|-- bench.sh
|-- bench.fish
`-- README.md
```
The `Makefile` should be the command for `make all` (benchmark), `make clean` (clean up) and `make version` (show version). I guess I will include `dash`, `bash`, `fish`, `mksh` (`zsh` not selected as it is as slow as a sloth).

The `bench.sh` and `bench.fish` should be the same as the testing script in above and probably more features like:

- Shell startup time (`bash -c exit` or similar)
- External command execution (probably some commands like `git`)
- Testing loops (`if`, `for`, `while`)

Did I miss anything?

**Comment by ridiculousfish** [comment] 2016-03-28 18:42
Yes! but let's try to avoid recursive Makefiles, which are inevitably painful.

One way is to structure it roughly like the `test` directory:

```
benchmark
|-- driver.fish
|-- bench1.fish
|-- bench1.sh
```

`driver.fish` would be the entry point, and would be passed the instance of fish to test, and an optional list of benchmarks to run. (It doesn't have to be a fish script - it could be Python or whatever instead)

Then a top-level Makefile target:

```
.PHONY benchmark
benchmark:
    ./benchmark/driver.fish ./fish ALL
```

etc.

**Comment by floam** [comment] 2016-03-28 20:33
Ideally the driver would make some attempt to use something better than `time` if possible. On OS X it's usually `dtruss` and `procsystime` I reach for.

**Comment by floam** [comment] 2016-03-28 20:43
FWIW, pickfire's last posted scripts, even though we shouldn't compare:

```
floam@AaronBook ~> env XDG_CONFIG_HOME=/tmp/bogus2 XDG_DATA_HOME=/tmp/bogus2 procsystime -a /usr/local/bin/zsh test.sh
/usr/local/bin/zsh: can't open input file: test.sh

Elapsed Times for command /usr/local/bin/zsh test.sh,

         SYSCALL          TIME (ns)
         geteuid                841
         getppid                981
     sigprocmask               1111
       getrusage               1178
        getlogin               1519
bsdthread_register               1681
shared_region_check_np               1824
          getuid               1907
       fstatfs64               2167
           lseek               2465
          getpid               2944
       proc_info               3563
   thread_selfid               3594
       issetugid               3732
            pipe               3816
          munmap               4116
       sigaction               4189
             dup               4552
           csops               4628
        shm_open               6882
  write_nocancel               7142
           fcntl               8906
       getrlimit               9483
           pread              11008
        mprotect              14589
         fstat64              15755
  close_nocancel              27696
           close              35781
          access              46174
          sysctl              68159
            open              68220
   read_nocancel              69073
            mmap              88273
 getdirentries64              91796
   open_nocancel             126708
          stat64             167158
         lstat64            1006840
           ioctl          116401566
          TOTAL:          118322017

CPU Times for command /usr/local/bin/zsh test.sh,

         SYSCALL          TIME (ns)
         geteuid                159
         getppid                256
     sigprocmask                459
          getuid                492
       getrusage                509
          getpid                696
        getlogin                833
       issetugid                927
   thread_selfid                951
bsdthread_register               1064
shared_region_check_np               1098
           lseek               1285
       fstatfs64               1408
       sigaction               1482
             dup               1789
           csops               2460
       getrlimit               2633
       proc_info               2765
            pipe               3072
          munmap               3337
           fcntl               5282
        shm_open               5727
  write_nocancel               6357
           pread               8604
         fstat64               9199
        mprotect               9485
  close_nocancel              22395
           close              27744
          access              44757
   read_nocancel              60255
          sysctl              61708
            open              63514
            mmap              80701
 getdirentries64              89216
   open_nocancel             120148
          stat64             134547
         lstat64             819012
           ioctl          116387022
          TOTAL:          117983348

Syscall Counts for command /usr/local/bin/zsh test.sh,

         SYSCALL              COUNT
bsdthread_register                  1
            exit                  1
       fstatfs64                  1
         geteuid                  1
        getlogin                  1
         getppid                  1
       getrusage                  1
          munmap                  1
            pipe                  1
       proc_info                  1
shared_region_check_np                  1
        shm_open                  1
     sigprocmask                  1
  write_nocancel                  1
          access                  2
          getpid                  2
          getuid                  2
           lseek                  2
   thread_selfid                  2
           csops                  3
 getdirentries64                  4
       issetugid                  4
           pread                  4
             dup                  5
       sigaction                  5
           fcntl                  6
           ioctl                  6
            open                  6
        mprotect                  8
  close_nocancel                  9
   open_nocancel                  9
          sysctl                  9
         fstat64                 11
       getrlimit                 11
           close                 12
            mmap                 12
   read_nocancel                 13
          stat64                 52
         lstat64                338
          TOTAL:                551

floam@AaronBook ~> env XDG_CONFIG_HOME=/tmp/bogus2 XDG_DATA_HOME=/tmp/bogus2 procsystime -a /usr/local/bin/fish test.fish
dtrace: 2767 dynamic variable drops with non-empty dirty list

Elapsed Times for command /usr/local/bin/fish test.fish,

         SYSCALL          TIME (ns)
       getrlimit               1782
bsdthread_register               1838
shared_region_check_np               1838
__pthread_canceled               1895
          getpid               2373
           lseek               2586
       proc_info               3591
       sigreturn               3923
       issetugid               4056
          munmap               4591
   thread_selfid               5377
       fstatfs64               6318
  fcntl_nocancel               6456
           csops               8126
           wait4               8739
           pread               9892
        mprotect              14819
         fstat64              23530
       sigaction              28441
     getattrlist              31295
            pipe              45932
 getdirentries64              50458
  close_nocancel              55881
            mmap              68431
          sysctl              80814
          access              87335
           close             108585
           fcntl             118939
   open_nocancel             125170
            open             145220
          stat64             366181
   read_nocancel             976718
     posix_spawn            1432014
__pthread_sigmask            1489325
            read            2259105
           ioctl          121649709
            fork          129857684
          select          142370254
          TOTAL:          401459221

CPU Times for command /usr/local/bin/fish test.fish,

         SYSCALL          TIME (ns)
__pthread_canceled                445
          getpid                582
       getrlimit                708
shared_region_check_np               1046
           lseek               1160
bsdthread_register               1192
       issetugid               1929
       sigreturn               2022
   thread_selfid               2482
       proc_info               2860
  fcntl_nocancel               3179
          munmap               3753
       fstatfs64               4294
           csops               4734
           wait4               6362
       sigaction               6778
           pread               8025
        mprotect               9754
         fstat64              13591
     getattrlist              26198
            pipe              38062
 getdirentries64              46309
  close_nocancel              46716
            mmap              63013
          sysctl              76841
           fcntl              79073
          access              82350
           close              89713
   open_nocancel             117211
            open             129371
          select             198706
   read_nocancel             249547
          stat64             302703
__pthread_sigmask             349688
            read             357926
     posix_spawn             425506
           ioctl          121551821
            fork          129278812
          TOTAL:          253584462

Syscall Counts for command /usr/local/bin/fish test.fish,

         SYSCALL              COUNT
bsdthread_register                  1
            fork                  1
       getrlimit                  1
          munmap                  1
     posix_spawn                  1
       proc_info                  1
shared_region_check_np                  1
__pthread_canceled                  2
          getpid                  2
       issetugid                  2
           lseek                  2
       sigreturn                  2
   thread_selfid                  2
           csops                  3
       fstatfs64                  3
           pread                  3
           wait4                  4
  fcntl_nocancel                  5
          sysctl                  5
 getdirentries64                  6
          access                  7
            mmap                  7
     getattrlist                  8
        mprotect                  8
   open_nocancel                 11
            pipe                 11
            open                 13
  close_nocancel                 14
          select                 15
         fstat64                 16
           ioctl                 16
   read_nocancel                 21
           close                 31
       sigaction                 41
           fcntl                 71
          stat64                101
            read                148
__pthread_sigmask               1982
          TOTAL:               2569


```

**Comment by floam** [comment] 2016-03-28 21:22
Yeah that's just the trace happening.

**Comment by pickfire** [comment] 2016-03-29 05:31
@ridiculousfish Of course! No recursive Makefile.

@floam Woah, that is some stuff that I don't know about.

I would like to ask one question, what is actually the `driver` that both of you are talking about?

**Comment by ridiculousfish** [comment] 2016-03-29 05:47
driver is the test harness, which I sketched as step 1 in [this comment](https://github.com/fish-shell/fish-shell/issues/2776#issuecomment-202129978).

**Comment by krader1961** [comment] 2017-01-01 04:14
Thanks, @pickfire, for making us think about this. However, I'm going to close it because it is too broad. Issue #2007 is an example that is sufficiently precise to allow us to know when the issue has been addressed. Making fish fast is a desirable goal but is so open ended as to be useless as an actionable issue.

**Closed by krader1961** 2017-01-01 04:14 UTC
Labels: enhancement, RFC
