### ISSUE TITLE
Bracket pairing breaks comments

### ISSUE THREAD

**Issue by kopischke** [fish-shell/fish-shell#8022] opened 2021-05-21 16:04 UTC
Running fish version 3.2.2-325-g7123e2f25 (built from HEAD via Homebrew) on macOS 11.3.1 in the stock Terminal.app. I tried fish without third-party customisations by executing `sh -c 'env HOME=$(mktemp -d) fish'` and checked whether it affected the behaviour I am reporting (it did not).

---------

This seems related to #7970 and, unlike that issue, does not seem to be covered by #2485: **fish’s somewhat eccentric bracket pairing triggers across comment boundaries, effectively breaking comments.** I submit for your consideration the following code:

```fish
echo f[oo # not valid, no matching ]
```

To my best understanding, the argument to that `echo` command is  `f[oo`, followed by a “not valid, no matching ]” comment, and executing that snippet should trigger the “unexpected end of string” error, as there is an unmatched opening bracket that is not in first word character position. Note GitHub’s fish syntax highlighting concurs with my interpretation, for what that is worth. **However.**

What fish actually does is to treat this as a valid `f[oo # not valid, no matching ]` argument, which it executes without complaining. I find this utterly baffling, as [there is no paired bracket syntax construct outside variable indexing that justifies this](https://github.com/fish-shell/fish-shell/issues/7970#issuecomment-831411751).

The current behaviour can’t be right, can it?

**Comment by faho** [comment] 2021-05-21 16:31
Duplicate of #7866

**Closed by faho** 2021-05-21 16:31 UTC

**Comment by kopischke** [comment] 2021-05-21 16:44
Uh, what? #7866 is about the parser erroneously trying to balance quotes inside a comment; this issue is about the parser looking for a match to an opening bracket that is found outside a comment inside the following comment. I mean, yeah, the underlying parser issue may be the same, but I could never tell from looking at #7866 – the behaviour I describe here is not ever hinted at there …

**Comment by faho** [comment] 2021-05-21 17:09
The underlying issue is comments not commenting enough, so I'm calling it the same for  now.

**Comment by kopischke** [comment] 2021-05-21 17:11
The #7866 _definitely_ needs to be renamed. I’m taking that as “this is a bug, right enough”, ja?

**Comment by zanchey** [comment] 2021-05-22 03:37
Yes.
