### ISSUE TITLE
Command names duplicated in the `NAME` section of their manuals

### ISSUE THREAD

**Issue by americanhanko** [fish-shell/fish-shell#5269] opened 2018-10-20 20:28 UTC
# Issue

In the `NAME` section of the manual, the command names appear twice in succession.

For example, `man cd` shows `cdcd` as the title, `man set` shows `setset` as the title, etc.

## Evidence

```
$ cat cd.1 | head -8
.TH "cd" 1 "Sat Dec 23 2017" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cdcd - change directory
 \-
.PP
.SS "Synopsis"
```

```
$ cat fish_indent.1 | head -8
.TH "fish_indent" 1 "Sat Dec 23 2017" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fish_indentfish_indent - indenter and prettifier
 \-
.PP
.SS "Synopsis"
```

## Environment

```
$ fish --version
fish, version 2.7.1
$ echo $version
2.7.1
```
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14 (18A391)
      Kernel Version: Darwin 18.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: americanhanko
      User Name: americanhanko
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 6:54
```

```
$ uname -a
Darwin magnapinna 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

```
$ echo $TERM
xterm-256color
```

> Have you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting?

Yes

**Comment by faho** [comment] 2018-10-20 20:39
Duplicate of #4016.

Fixed in 3.0, sorry for the inconvenience!

**Closed by faho** 2018-10-20 20:39 UTC
