### ISSUE TITLE
Frozen fish after `python && pip ` + tab

### ISSUE THREAD

**Issue by remisalmon** [fish-shell/fish-shell#7850] opened 2021-03-22 00:46 UTC
fish, version 3.2.1
Linux 5.11.7
Gnome Terminal 3.38.1 (xterm-256color)

Steps to reproduce:
`python && pip ` (note the space after pip) then press tab: the Python console opens but nothing happens, Ctrl+C shows `KeyboardInterrupt` but does not quit.

**Comment by IlanCosman** [comment] 2021-03-22 01:48
Can reproduce on Arch and MacOS. Opens the python console but keyboard is ignored.

**Comment by zanchey** [comment] 2021-03-22 08:17
It's our old friend, `eval` - or by its full name, `eval` Considered Harmful!

pip produces its own completion code, and it's wrong, because it does not support completions in a compound statement:

```
function __fish_complete_pip
    set -lx COMP_WORDS (commandline -o) ""
    set -lx COMP_CWORD ( \
        math (contains -i -- (commandline -t) $COMP_WORDS)-1 \
    )
    set -lx PIP_AUTO_COMPLETE 1
    string split \  -- (eval $COMP_WORDS[1])
end
```

The `commandline` invocations here almost certainly need a `-p` in them, but this needs to be fixed in pip.

Annoyingly, because of the way functions are loaded, you can't easily fix this yourself.

**Comment by mqudsi** [comment] 2021-03-28 02:43
I’ve been wanting to redirect all input, output, and error fds for pipelines launched in completion handlers but never really found a clean way to do it. I don’t think there is ever a valid use case for a completion to read from stdin (although I’ve abused it to provide credentials to completions before) or write to the actual tty (though we’ve all abused that for debugging purposes) - manipulation of the tty should be done via `commandline`

Although error output is helpful for finding broken completions...

**Comment by faho** [comment] 2021-07-08 15:23
A PR has been opened for pip, so there's nothing more to do on our side.

We don't really have a "fixed elsewhere" label, so I'm using "question", because there's no change in fish required.

**Closed by faho** 2021-07-08 15:23 UTC
Labels: question
