### ISSUE TITLE
Parallel (&) function fail to run parallel in a script

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2782] opened 2016-03-01 11:19 UTC
### Reproduction Steps:

```fish
function testing
    echo test
    sleep 5
end

for i in (seq 10)
    testing &
end
```

### Expected behavior:

`testing` should be runned parallely.

### Observed behavior:

`testing` isn't runned parallely.

### Additional information:

This is what I am going to achieve since `fish` has no `wait`:
```fish
for i in (seq 10)
    while math $i % (nproc) == 0
        testing &
    end
end
```

More information in fisherman/fisherman#138

---
Fish version: fish, version fb5a8a0
Operating system: alarm
Terminal or terminal emulator: st

**Comment by bucaran** [comment] 2016-03-01 11:33
Just a note.

OS X does not have nproc, so I think you will need a function to test the operating system and return the appropriate call at some point.

```fish
function proc
    switch (uname)
        case Darwin
            sysctl -n hw.ncpu
        case \*
            # ...
    end
end

```

**Comment by pickfire** [comment] 2016-03-01 11:34
@bucaran Ah, okay, thank a lot for that.

**Comment by faho** [comment] 2016-03-01 11:44
This is a duplicate of #563, I believe.

**Closed by faho** 2016-03-01 11:44 UTC

**Comment by pickfire** [comment] 2016-03-01 12:23
Ah, it seems so, that's a very old issue, over 2000.
