### ISSUE TITLE
Completions pager should redraw if the subbed completion wraps/unwraps the line

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#8405] opened 2021-11-05 17:27 UTC
If the user has a command typed out that is approaching the width of the terminal and attempts to page through completions for an argument, an argument may be subbed in that causes the line to wrap (e.g. the prompt now takes n+1 lines), while tabbing away to a different suggested completion may cause the line to then unwrap (prompt goes back to n lines). Neither the prompt nor the pager are redrawn when this wrapping/unwrapping happens, so what's displayed in the tty emulator (apart from the selected completion's line which *is* redrawn) does not match the actual contents (off-by-one error). This causes corruption of the prompt regardless of whether a completion is ultimately chosen or which completion was chosen, leaving the terminal in a corrupted state (the prompt is broken up, incorrect, and scrolled out of view).

This doesn't happen under asciinema because the emulated `TERM` doesn't support our rich completions pager but here's a video capture:

https://user-images.githubusercontent.com/606923/140552997-eae44c3d-e051-4765-92db-64dcae102a60.mp4

You can see when the prompt first breaks (when the first too-long completion is selected) and if you look closely you can observe the oddities in the appearance of the selected item as I tab to and from the long completion. After the pager is closed (completion abandoned), I scroll up and you can see the detritus of the wrapping and unwrapping.

**Comment by floam** [comment] 2021-11-05 18:16
Ew, command line guts!

**Comment by krobelus** [comment] 2021-11-06 06:36
I'm struggling to reproduce this.
Looks like something that should have been fixed by ada03d350 (Correct pager size when command line soft-wraps, 2020-07-05).
There are other issues like https://github.com/fish-shell/fish-shell/issues/7296 where we redraw wrongly when we occupy all lines on the screen.

**Closed** 2021-12-02 03:59 UTC

**Comment by krobelus** [comment] 2021-12-02 04:04
This might be fixed by 0cd3ed4b84e4cf02e560f0fd65a49c1633f915cb but I didn't verify that (I wasn't sure if github would interpret "Possibly closes <issue-number>" like that).
Also, I forgot the changelog again, maybe it should be left out since it's not so actionable for users (who didn't notice the bug)?
