### ISSUE TITLE
keybindings can't switch to foreground normally >1 times

### ISSUE THREAD

**Issue by rbong** [fish-shell/fish-shell#2765] opened 2016-02-26 19:08 UTC
Concerning job control: I have a keybinding which switches to the job in the foreground. When used once, it works correctly, but if used a second time, fish requires that the enter key is pressed before it reads any input, including keybindings. 

### Reproduction Steps:

1. bind \cf fg
2. man man
3. C^Z C^F C^Z C^F

#### Alternatively

1. bind \cf fg
2. man man
3. C^Z C^F
4. Exit the program

### Expected behavior:

The command "man man" becomes active in the foreground.

#### Alternatively

The program is exited and the command prompt is activated.

### Observed behavior:

fish does not execute any input until the enter key is pressed. Syntax highlighting is broken and the prompt is not activated.

### Additional information:

Ran with an empty fish configuration.

---
Fish version: 2.2.0

Operating system: Linux 4.4.1-2-ARCH x86_64 GNU/Linux

Terminal or terminal emulator: tested on st and urxvt

**Comment by faho** [comment] 2016-02-26 19:23
This is a duplicate of #2114 - though the title there probably isn't great.

**Closed by faho** 2016-02-26 19:23 UTC

**Comment by rbong** [comment] 2016-02-26 20:56
Thank you. The issue should be easier to find now.
