### ISSUE TITLE
Fish garbage output during command line editing in Haiku

### ISSUE THREAD

**Issue by extrowerk** [fish-shell/fish-shell#3646] opened 2016-12-14 08:50 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version unknown
it is 2.4.0 with Haiku specific patches, not in mainline yet.
Current recipe: https://github.com/haikuports/haikuports/pull/928
Patchset: https://github.com/miqlas/haikuports/blob/b34ed504a7925d53e4be384ecad3b235fbb9d0e4/app-shells/fish/patches/fish-2.4.0.patchset
**OS/terminal used**: 
Haiku hrev 50762 x86_64, Terminal

Talk about the the issue here.
BTW, the problem can lie in ncursesw Haiku port, and in Haiku's Terminal too. My current Fish config is here: https://github.com/miqlas/dotfiles/tree/master/config/settings/fish.
I would like to try it later without custom prompt and clean settings. This aren't exactly a new bug, i had it all the time with earlkier Fish versions too.
I can test it trough ssh from OSX box with iTerm, if it helps.

## Reproduction steps
1. type a long command with `/`, for example, paths and so on
2. navigate with the cursor keys and edit some parts of the command
3. Fish shows unnecessary characters here and there. I see double `//` and extra characters. Ctrl+L helps.

Will do screenshots later.

## Results
```console
~ $ math 2 + 2
4
```

**Comment by krader1961** [comment] 2016-12-14 16:21
What does `locale` report? Are you entering any non-ASCII characters? If you are can you reproduce the problem with only ASCII characters?

> I can test it trough ssh from OSX box with iTerm, if it helps.

Please do so. This type of problem is frequently due to fish and the terminal assigning different widths to characters.

**Comment by miqlas** [comment] 2016-12-14 19:19
Locale Reports nothing.

**Comment by krader1961** [comment] 2016-12-14 19:21
If running `locale` reports nothing then your locale command is broken. You should get output that resembles the following. Do you have any locale env vars set? Does the problem still occur if you `set -x LC_ALL POSIX`?

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by miqlas** [comment] 2016-12-14 23:32
Is this local a built in command or an external one?

**Comment by faho** [comment] 2016-12-14 23:46
local**e**, with a trailing "e". It's a standard UNIX command. So yeah, external. Anyway, what we need to know is how the system would behave with regard to language and encoding and such. Maybe haiku has another way of figuring that out.

Also, we still need to know if this only happens with "weird" (read: non-latin) characters. An asciinema or similar would be helpful.

**Comment by miqlas** [comment] 2016-12-15 09:10
Okay, it looks like Haiku defines it here: https://github.com/haiku/haiku/blob/b65adbdfbc322bb7d86d74049389c688e9962f15/data/system/boot/SetupEnvironment#L41

And profile sources and redefines it here:
https://github.com/haiku/haiku/blob/766191919df43b68aa543a1c17cff895cf4c3653/data/etc/profile#L25
But i think none of them sourced by fish.

Actually the launch daemon sources it too:
https://github.com/haiku/haiku/blob/b65adbdfbc322bb7d86d74049389c688e9962f15/data/launch/user#L23

but with /bin/sh. I think the Haiku fish package doesn't have /bin/sh alias, so i suppose it get sourced by bash and never by fish. It would explain, why locale reports nothing.

I'll check it later.

**Comment by faho** [comment] 2016-12-15 10:14
@miqlas: Your locale command is unlike anything I've seen before - `locale -t` prints an "invalid option" error for me.

So run this instead:

```fish
for var in LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL
    echo $var \'$$var\'
end
```

**Comment by miqlas** [comment] 2016-12-15 10:23
Maybe it is a BeOS legacy. You know, we arent respect the rules ;D
I'm working right now, so i can test it at night or at weekend. Thanks for your help!

**Comment by miqlas** [comment] 2016-12-15 17:27
Ok, after a cloean boot without any changes `env` reports the following:

LC_COLLATE=hu_HU.UTF-8
LC_CTYPE=hu_HU.UTF-8
LC_MESSAGES=hu_HU.UTF-8
LC_MONETARY=hu_HU.UTF-8
LC_NUMERIC=hu_HU.UTF-8
LC_TIME=hu_HU.UTF-8@string-messages
LC_TYPE= en_US.UTF-8

So it is already sourced.

**Comment by miqlas** [comment] 2016-12-15 17:34
faho, your script reports the following:
```
~ ❯❯❯ for var in LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL
              echo $var \'$$var\'
      end
LANG
LC_CTYPE 'hu_HU.UTF-8'
LC_NUMERIC 'hu_HU.UTF-8'
LC_TIME 'hu_HU.UTF-8@strings=messages'
LC_COLLATE 'hu_HU.UTF-8'
LC_MONETARY 'hu_HU.UTF-8'
LC_MESSAGES 'hu_HU.UTF-8'
LC_PAPER
LC_NAME
LC_ADDRESS
LC_TELEPHONE
LC_MEASUREMENT
LC_IDENTIFICATION
LC_ALL
~ ❯❯❯  
```

**Comment by krader1961** [comment] 2016-12-15 19:06
It looks like you have a typo somewhere because your env output included `LC_TYPE= en_US.UTF-8` and there is no such locale var. The correct spelling is `LC_CTYPE`. But that's not really important.

What is important is that you're using a locale that makes it more likely you are using non ASCII characters. And that can be the source of the problem you're observing. type `echo ` followed by the long command that causes the backspace problem followed by `| od -tx1z`. If your system doesn't have an `od` command that recognizes the z option try `| od -tx1`. Then show us the output of the od. For example:

```
$ echo long command with path /really/long/path | od -tx1z
0000000 6c 6f 6e 67 20 63 6f 6d 6d 61 6e 64 20 77 69 74  >long command wit<
0000020 68 20 70 61 74 68 20 2f 72 65 61 6c 6c 79 2f 6c  >h path /really/l<
0000040 6f 6e 67 2f 70 61 74 68 0a                       >ong/path.<
0000051
```

**Comment by miqlas** [comment] 2016-12-15 19:24
krader1961, i got you an od output:

""

But here is an screenshot about the problem. See, there is no e in echo, but it shows me. I had to jum to the beginning of the command line with Home, delete a character (e)  and i got a ghost e. Hovewer it looks good, you will get error messages and headache.

![3b69600b476043cebe63b55f4ca38d1a](https://cloud.githubusercontent.com/assets/5569059/21238694/41a8e15c-c304-11e6-97b3-2d785de61ab6.png)


There is another screenshot, the command looks wrong, but it works. A space not showing but it is there.

![e21b6aedd5a0410e8a45476e0c1f95ea](https://cloud.githubusercontent.com/assets/5569059/21238728/659ced24-c304-11e6-8d01-02edf2b317c5.png)

**Comment by faho** [comment] 2016-12-15 20:29
Okay, so we need to narrow this down a bit more. As you can see, there are no multi-byte characters in your command, everything is ASCII. (With UTF-8, multi-byte characters are above 0x80, everything below that is single-byte ASCII)

So there's a few other possibilities. One is that there's an escape we print while you are typing that the terminal handles weirdly, another is that there's some interaction with the left or right prompt.

Can you try this without configuration? `sh -c 'env HOME=$(mktemp -d) fish'`?

It would also be great if you could record an asciinema session (which will record all the output and store it as json, which you can then view on the asciinema website or in a text editor), or at the very least a `script` one.  These things both record _all_ of the stuff that fish is sending to the terminal, including the stuff you're not supposed to see.

Now, I've installed haiku in a VM and I can find neither command - not in haikudepot and not in haikuports. I also can't figure out how to install fish 2.4.0 - it complains about a ".dependencyInfo" file being missing.

**Comment by krader1961** [comment] 2016-12-15 20:33
In addition to what @faho said I'd like to see the output of `functions fish_prompt` and `functions fish_right_prompt`.

**Comment by miqlas** [comment] 2016-12-15 22:05
I need to finis a project, but i can give all the reqested info at weekend. Thanks for your help!

Btw, you need a recent Haiku image (search for nightly). If you installed it already, let me know what `uname -a` returns, and i'll provide all the required packages prebuilt.

If you wan't to compile it, you need to install haikuporter (you can find it in the HaikuDepot), then you should clone the haikuports tree ( `git clone https://github.com/haikuports/haikuports.git` ) somewhere. Then you should setup haikuporter as written here: https://github.com/haikuports/haikuports/wiki

Then you can open a Terminal, and if `gcc --version` returns 2.95.3, then compile fish like `haikuporter fish_x86` , if gcc reports recent version, then a simple `haikuporter fish` should be enough.

Be warned, haikuporter tries to build all the dependencies. You should tell them to not do it with `--get-dependencies`.

Haikuporter have a steep learning curve, but you can write me, if you have any problem, and we are on IRC too: #haiku-os on freenode :) We are nice!

**Comment by faho** [comment] 2016-12-15 22:42
>If you installed it already, let me know what uname -a returns, and i'll provide all the required prebuilt packages.

I think you're interested in the "hrev50766" part.

>If you wan't to compile it, you need to install haikuporter (you can find it in the HaikuDepot), then you should clone the haikuports tree ( git clone https://github.com/haikuports/haikuports.git ) somewhere. Then you should setup haikuporter as written here

Had already done that.

>gcc --version returns 2.95.3

Yes.

>compile fish like haikuporter fish_x86

Ah, I had changed the architecture setting in haikuporter.conf.

>You should tell them to not do it with --get-dependencies

This actually does seem to get further. Now it doesn't find libpcre2_32_x86.

Even without "--get-dependencies" it doesn't actually complete everything.

**Comment by miqlas** [comment] 2016-12-15 23:10
Yeah, libpcre2 arent in depot yet, make the same like with fish, but now with libpcre2_x86, so you need to build libpcre2 first, and then install the created packages (be careful, you will get 2, one for the runtime, one for the developer files). haikuporter will drop the created packages into the $haikuports_folder_where_you_cloned_the_recipes/packages folder. You will find them there, and you can install them with double click.
Or you can press Alt and click on the result filename in Terminal.

(Actually i wanted to know, which arch have you installed, so the x86 or x86_64 part, but i see, you got the gcc2h one).

**Comment by faho** [comment] 2016-12-16 00:10
Okay, I got it installed now, and I can't reproduce.

My locale is mainly "de.UTF-8". In addition I also have (in addition to LC_CTYPE=de.UTF-8) "LC_TYPE" (without C) set to "en_US.UTF-8".

There's also a bunch of niggling issues here - `gettext` apparently isn't a thing, neither is `hostname -s` (this is already fixed by accident in git). `fish_config` refuses to run twice because the cache directory already exists (?). It also prints errors about tcsetpgrp.

The errnos are apparently wrapped around or something - I get "-2147459070" for "file or directory already exists".

I'll try to test a bit more later.

**Comment by miqlas** [comment] 2016-12-16 05:20
Happy, that you got it work, nice work mate!

It doesn't happen all the time :(

I have no idea about LC_TYPE, sorry.

What's wrong with  `gettext` and `hostname`? `fish_config`: known, but i have no idea, where it comes from. I already tried to put debug printfs in the python files, found nothing, yet.

errno.h? It is actually EEXIST.

**Comment by miqlas** [comment] 2016-12-16 07:36
Ok, i think i found something.

My fish_prompt is:

> function fish_prompt
>     echo -n (set_color cyan)(prompt_pwd) (set_color red)'❯'(set_color yellow)'❯'(set_color green)'❯ '
> end

If there is no right prompt defined, i don't see any ghost characters, but if i echo anything in right prompt, it comes back.

Tested with:

> function fish_right_prompt
>     echo 'something'
> end

So it must be something with fish or Haiku right prompt handling.

**Comment by krader1961** [comment] 2016-12-16 07:49
Your `fish_prompt` includes non-ASCII characters. Specifically the [U+276F](https://codepoints.net/U+276F?lang=en) character. You did not show us your `fish_right_prompt` function. So I do not think this has anything to do with your right prompt. I am inclined to conclude that your terminal and fish have a different idea about the width of code point U+276F ; the "heavy right-pointing angle quotation mark ornament" character in your prompt. If you replace that character with a simple right-angle, `>`, in your `fish_prompt` function does the problem still occur?

**Comment by miqlas** [comment] 2016-12-16 08:14
krader1961, good observation, i'll check it later.

Actually i did in the issue description, there is my whole dot folder, but here is a direct link: https://github.com/miqlas/dotfiles/blob/master/config/settings/fish/functions/fish_prompt.fish

In case you wonder why does it prints the gcc version: in default Haiku comes with 2 GCC toolchain (2.95.3 for legacy and 5.4.0 for recent things) and one can switch with the `setarch` command. But if i have plenty Terminals, i forget all the times, wich is wich, so i just let it echo the current arch and ofc the git branch.

Really helpful...

**Comment by miqlas** [comment] 2016-12-16 08:26
Just tested it as you told, so i replaced every U+276F instance with ">", and made a simple right prompt, like before:

> function fish_right_prompt
> echo 'something'
> end

The ghost-characters problem stays reproducable.

**Comment by krader1961** [comment] 2017-04-23 03:32
@miqlas: Are you still seeing this if you use fish 2.5.0 or one built from the current git head?

**Comment by miqlas** [comment] 2017-04-23 07:00
I still see it with 2.5.0, but not tested with any got version. Should i?

**Comment by krader1961** [comment] 2017-05-21 06:01
@miqlas: Using the Haiku VM image you provided me to debug issue #4030 I see that simply typing a command and pressing [enter] results in the output of the command being on the same line rather than a new line. In other words, pressing [enter] does not result in the cursor moving down to a new line. This happens even if I remove my fish config. Here I typed `ls` and pressed [enter]:

```
~> rm -rf .config/fish
~> private/bin/fish
Welcome to fish, the friendly interactive shell
user@haiku ~> lsbin/  build-fish*  config/  Desktop/  lib/  mail/  private/  projects/  symlinks/
user@haiku ~>
```

Can you explain why you, presumably, are not seeing that behavior? Because that behavior might be related to this issue.

**Comment by miqlas** [comment] 2017-05-21 07:12
I see that too and hovewer i tried to explain this behaviour, i suppose i failed :)

**Comment by miqlas** [comment] 2017-07-31 18:06
Just for info: Tested with the lates git version: still here.

**Comment by miqlas** [comment] 2017-08-15 16:01
I just tested all the test-cases from https://github.com/fish-shell/fish-shell/issues/4269
Got theese results on current Haiku:

https://0x0.st/nqi.txt

Sorry, i just can't paste it here.

**Comment by miqlas** [comment] 2017-08-15 16:12
According to https://github.com/termux/termux-packages/commit/845a978a46710b19066f6393ec593e88706b1576
we got theese on Haiku:

https://0x0.st/nq-.txt

Sorry, i cannot paste here.

**Comment by faho** [comment] 2019-07-05 19:11
Sorry, this issue has gotten pretty stale and is likely to have been fixed, closing!

**Closed by faho** 2019-07-05 19:11 UTC
Labels: bug, needs more info
