### ISSUE TITLE
Korean hangul input bug only in fish 3, linux

### ISSUE THREAD

**Issue by palindrom615** [fish-shell/fish-shell#5830] opened 2019-04-19 16:21 UTC
I found some bug only occurs in fish 3. 

no problem with fish 2 or bash or zsh. does not care whether x11 or wayland. no problem with macOS. only linux.

as you can see in gif, the text I actually typing and the string shown in fish prompt has differences in hangul. it seems fish's auto completion is broken with hangul. 

![record (1)](https://user-images.githubusercontent.com/10936496/56432521-ac1d4b80-6308-11e9-92b4-58e13318c761.gif)

If it needs any help to support Korean language, let me help. Thanks!

**Comment by faho** [comment] 2019-04-19 16:27
Duplicate of #5729

**Closed by faho** 2019-04-19 16:27 UTC
