### ISSUE TITLE
__fish_describe_command is slow

### ISSUE THREAD

**Issue by MaxKh** [fish-shell/fish-shell#5825] opened 2019-04-18 08:44 UTC
fish, version 3.0.2
Archlinux

The `__fish_describe_command` function is slow and slows down `<TAB>` completion for commands.

I have to overwrite the function with
```
function __fish_describe_command
  return
end
```
and now the completion speed is not annoying.

As far as I remember fish 2.x worked fine without the trick.

**Comment by faho** [comment] 2019-04-18 13:24
>As far as I remember fish 2.x worked fine without the trick.

The commits to __fish_describe_command since 2.**0**.0 (!):

- 11a60c8374c21c299bab35ae12a30b54a44bc9e3, which reformatted it
- 7659554deafd7a6f8c710fc42b52328be4561c05, which exclusively changed `^` to `2>`.
- 6a6ffe68cb5d215ac0dc84f500ce6c2dba9e30e9, which runs one additional `string match` before
- e8a35bfaa83c3a93cd7e9c214c410a01eeb8781b, which runs `type -q apropos` before doing anything

While those latter two did add a teensy bit of work, it shouldn't really matter. I just measured and confirmed that this is indeed the case.

So if this appeared faster, then that's only because there were some cases where we didn't even try to describe the command in 2.7.1. The function never was faster.

And considering that 99% of its time is spent in `apropos`, unless anyone has a proposal for how we should get this information faster, I'm inclined to close this as unfixable. If you don't want to spend the time, you can override the function like you already did.

**Comment by floam** [comment] 2019-04-19 20:45
This takes about 30ms here. I think we could improve performance by caching the results.

**Comment by floam** [comment] 2019-04-19 20:55
Or just read the `whatis` file directly on a few platforms.

**Comment by mqudsi** [comment] 2019-06-09 01:15
For what (very) little it is worth, `apropos -e -l foo` is what we actually should be using, and it is ~8% faster than `apropos foo` (tested against `ip`, benchmarked with `hyperfine`).

**Comment by faho** [comment] 2019-06-10 16:44
>But someone has to find out if it's portable.

It's not: https://man.openbsd.org/apropos.1.

And it's only ~8%, which would be ~3ms.

If it actually is "too slow", then 10% isn't really going to make it. Caching is an interesting idea, but invalidating that is going to be annoying.

**Comment by floam** [comment] 2019-08-11 23:59
Are there any implementations where you cannot simply `grep` the whatis database and get the right result?

**Comment by zanchey** [comment] 2019-09-03 06:56
The `whatis` database is a binary format, at least on FreeBSD.

**Comment by floam** [comment] 2019-09-15 16:51
Can you share an example file from FreeBSD?

**Comment by zanchey** [comment] 2019-09-16 09:47
[mandoc.db.gz](https://github.com/fish-shell/fish-shell/files/3615576/mandoc.db.gz)

**Comment by zanchey** [comment] 2019-09-16 09:48
It's a binary format on Debian as well (in `/var/cache/man/index.db`).

**Comment by floam** [comment] 2019-09-17 07:06
And there is no `/usr/share/man/whatis`? Fish 1.x used to just suck in this whole text file if it existed otherwise use `apropos`.

**Comment by zanchey** [comment] 2019-09-17 07:44
There is, but it's very out of date.

**Comment by jonashaag** [comment] 2020-01-02 12:37
Problem on Catalina does not seem to be slow search (i.e. grepping whatis files), but rather the absence of whatis files altogether. So apropos rebuilds them every time it's run, which takes around 500ms on my machine. Looks like this is a bug in Catalina.

See also https://apple.stackexchange.com/questions/374025/errors-from-whatis-command-unable-to-rebuild-database-with-makewhatis

**Comment by floam** [comment] 2020-02-11 12:27
Apple fixed this in 10.15.4 Beta (19E224g).

**Comment by ridiculousfish** [comment] 2020-02-13 18:10
Nice! Did they mention it in their release notes?

**Comment by floam** [comment] 2020-02-13 18:52
No.

**Comment by ridiculousfish** [comment] 2020-02-16 22:41
```
> sudo /usr/libexec/makewhatis
makewhatis: /usr/share/man/whatis.tmp: Read-only file system
```

I guess that's...better.

**Comment by floam** [comment] 2020-02-16 22:43
Huh. I didn't see that when I used `apropos` on the beta. I was about to post that I still want a better workaround because it takes like 250ms as they appear not to generate `whatis` files at all anymore even with the LaunchDaemon not enabled.

**Comment by Darkshadow2** [comment] 2020-02-17 11:56
@ridiculousfish It prints the same thing on the current release too. I have a job that runs `makewhatis` once a month, and I see that in the output.

**Comment by faho** [comment] 2020-09-17 15:51
Okay, I'm closing this since it appears nobody really wants to do the work of opening the whatis database in C++ to save a few milliseconds.

**Closed by faho** 2020-09-17 15:51 UTC
Labels: RFC, completions

**Comment by folke** [comment] 2020-10-01 12:36
I've created a little plugin that fixes the slowness on macos, while still retaining the functionality.

Simply copy the gist [file](https://gist.github.com/folke/cded312c972ff3164dd405aad423b00f) to your `cond.d` directory.
