### ISSUE TITLE
fish under cmd.exe under Windows Terminal breaks line widths

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#8948] opened 2022-05-10 20:59 UTC
fish works fine if used directly as the startup shell for either conhost/cmd.exe or Windows Terminal. It also works fine if, under a regular conhost cmd.exe session running fish, you invoke `cmd.exe /c wsl.exe` and run fish from there. But if you start a WSL Windows Terminal session, then execute `cmd.exe /c wsl.exe` to start a nested fish session, fish's calculation of line/character widths breaks and you get things like

```
> cmd.exe /c wsl.exe
Welcome to fish, the friendly interactive shellh
```

(notice the `h` appended to `shell`)

and if you type in 

```
> echo hello
```

followed by enter, that results in 

```
> echo hellolh
hello
> 
```

(notice the `lh` appended to the `hello` after pressing Enter)

**Comment by faho** [comment] 2022-05-10 21:02
Duplicate of #8240

**Closed by faho** 2022-05-10 21:02 UTC

**Comment by faho** [comment] 2022-05-10 21:03
It's an upstream issue, they leak the bracketed paste sequences.

Tracked in https://github.com/microsoft/terminal/issues/395 AFAICT.

**Comment by mqudsi** [comment] 2022-05-10 21:15
Thanks. I searched for "Windows Terminal" but that's not a keyword for the other thread.

I assumed it was related to width calculations because my prompt also sometimes changes from `foo > ` (with a trailing space) to `foo >` (without a trailing space) under the circumstances that trigger this bug.
