### ISSUE TITLE
`source` custom arg completion is broken

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4292] opened 2017-08-07 20:01 UTC
Running under master (`2.6.0-295-g9fa0edcb`) and under major (`2.6.0-394-gfb764565`), I'm unable to get path completions for the `source` builtin that start with `~` to expand, but I cannot reproduce this behavior for other builtins or external commands. Completions for `source` other than `~/something` work fine.

I have confirmed that under the 2.6.0 release they work fine. I know there was another thread in here about ~/ completions but I cannot find it (can't search for tilde) - perhaps it is related?

**Comment by krader1961** [comment] 2017-08-07 20:16
Huh? Commit 9fa0edcb was a one paragraph change to `bind` documentation. It couldn't possibly affect fish behavior. Also, can you clarify what the problem is? When I type `ls` followed by [tab], for example, I see the expected path based command completions.

**Comment by mqudsi** [comment] 2017-08-07 20:17
@krader1961  Sorry, I updated my post. I did not mean to refer to any particular commit.

`ls ~/<TAB>` works fine and lists completions accordingly
`source /<TAB>` works fine and lists completions accordingly
`source ~/<TAB>` gives a console error (beep) and flashes the prompt

**Comment by faho** [comment] 2017-08-07 20:29
`source` uses (via the completions for `.`) `__fish_complete_suffix`, which.... isn't my favorite fish function.

That does `eval "set files $base*$suff"`, where `$base` is the current token minus its current extension and $suff is ".fish". Of course that ends up executing `set files ~/*.suff`, and expands the "~". That means you get `/home/mqudsi/something.fish`, when the completion system expects "~/something.fish". It's possible this was working differently before.

Personally, I'd be okay with ditching that function altogether. If we do want to support something like that, we should do the `expand` command I've proposed (and half-implemented before becoming distracted). However, this also shows we'd need some way to unexpand it back to whatever the token is.

**Comment by mqudsi** [comment] 2017-08-07 21:27
@faho thanks for that info. Is there a default path provider that is used across completions for commands taking a file path? Or is it implemented separately for everything?

**Comment by krader1961** [comment] 2017-08-07 21:28
Under 2.6, 2.5, and 2.3.1 I don't get the expected completions. It looks like it is falling back to the builtin path completion. On fish from `major` I see the symptom you describe. This is with a file named `~/zzz.fish`. So it looks like this has been broken for quite some time its just that the symptom of the problem has changed recently.

Git bisect traces the change to commit a3a06923: "Don't complete files if no completion can be found". Which removed these four lines from the builtin completion logic:

```
-                    // If we have found no command specific completions at all, fall back to using
-                    // file completions.
-                    if (completer.empty()) do_file = true;
-
```

**Comment by krader1961** [comment] 2017-08-07 21:29
@mqudsi, path completions are implemented in the core C++ code in *src/complete.cpp* because it's a generic, near universally applicable, completion.

**Comment by krader1961** [comment] 2017-08-07 21:30
Basically the `source` custom completion has always been broken. But it used to be that fish would fall back to path name completion. Itself a bug that was fixed by the aforementioned fix by @faho.

**Comment by krader1961** [comment] 2017-08-07 21:40
Also, the completion for `.` and therefore indirectly, `source` is itself wrong even if it that function wasn't broken:

```
complete -c . -x -a "(__fish_complete_suffix .fish)"
```

There is absolutely no requirement that a sourced file have a `.fish` suffix. Those trivial completion scripts should simply be removed so that the builtin path completion is used. Go for it, @mqudsi.

**Comment by mqudsi** [comment] 2017-08-07 22:05
@krader1961 where are you seeing that? @faho's commit from Aug 9 2015 fixed that:

6b92c4867d1d0e4cdb6ea827b63078b9ee7ef26b

**Comment by mqudsi** [comment] 2017-08-07 22:11
I think `source.fish` is the only one that is using the dot completion, unless I'm not doing it right?

```fish
> rg "complete .* (\-w|\-\-wraps).* \."
share/completions/source.fish
1:complete -c source -w .
```

(I tried other permutations of the search, too.)

**Comment by krader1961** [comment] 2017-08-07 22:13
> @krader1961 where are you seeing that? @faho's commit from Aug 9 2015 fixed that: 6b92c48

That change simply fixed the completions for the `.` command. Which is just an alias for `source`. And the completion script for `source` now wraps the completions for the `.` command as a result of @faho's change that you linked to.

My point is that neither command should limit the completions to files ending with `.fish` since there is no such requirement. It's not even a strong convention. Of course, there's still the issue of the __fish_complete_suffix function not behaving properly but that's a separate issue.

**Comment by mqudsi** [comment] 2017-08-07 22:14
Sorry, I realized my mistake after I posted. I wasn't seeing `..fish` because my search tool was ignoring dot files, which led to some confusion on my end.

**Comment by krader1961** [comment] 2017-08-07 22:22
No worries. We've actually talked about removing the `.` command. It's a bogosity in my opinion and that of others. It dates back to the days of very slow terminals such as when 300 bps and 1200 bps connections were common. Nobody types it interactively often enough to warrant the single letter alias. Not even 30 years ago AFAIK. In fact, I'm going to open a fish 3.0 issue to remove the damn thing since it no longer serves a useful purpose (if it ever did).

**Comment by mqudsi** [comment] 2017-08-07 22:23
I was just about to open a PR with the fix for the `source` builtin that also removed `..fish` and asked if that was OK or if it would be considered a breaking change for 3.0

I guess I should split it into two separate PRs.

**Comment by mqudsi** [comment] 2017-08-07 22:24
Running `.` now already prints this:

> source: '.' command is deprecated, and doesn't work with STDIN anymore. Did you mean 'source' or './'?

**Comment by krader1961** [comment] 2017-08-07 22:30
Yeah, we can't remove it in the master branch since that's for 2.7.

**Comment by krader1961** [comment] 2017-08-08 00:53
We've removed the completions in the major (fish 3.0) branch. The broader issue of the `__fish_complete_suffix` function not always producing the correct result will be addressed when the `expand` command is implemented.

**Closed by krader1961** 2017-08-08 00:53 UTC
Labels: bug, completions

**Comment by zanchey** [comment] 2017-08-09 06:51
Should we remove the `.` completions in 2.7.0 and allow them to fall back? They don't work, right?

**Comment by mqudsi** [comment] 2017-08-09 11:49
I think we might have to since it was falling back in 2.6.0 (albeit inadvertently) and do completions were working but not aren't in 2.7.0.

**Comment by krader1961** [comment] 2017-08-09 18:07
Yes. I'll remove them from 2.7 since they're a) not really correct and b) never worked but now make it impossible to get the correct builtin path completions.

**Comment by zanchey** [comment] 2017-08-19 11:27
Removed in 11f5bbf83d3c2083e770e3859e5891353272b840.
