### ISSUE TITLE
function --on-variable is not persistent

### ISSUE THREAD

**Issue by thibran** [fish-shell/fish-shell#2839] opened 2016-03-21 18:38 UTC
When assigning the `--on-variable` flag to a function, the created function is not active in another terminal.

### Reproduction Steps:

1. Open a terminal.
2. Create a new function: `funced echo_on_pwd_changed`
3. Enter:

    function echo_on_pwd_changed --on-variable PWD
        echo $PWD
    end

4. Save the file with `funcsave echo_on_pwd_changed`
5. `cd /tmp`

### Expected behavior:

Switching to the /tmp folder using any new opened terminal should print `/tmp` to the screen.

### Observed behavior:

Switching to the /tmp folder using the terminal-window in which the `funced echo_on_pwd_changed` command was issued, results in the expected behavior. All other newly opened terminal-windows don't work as expected.

---

Fish version: 2.2.0

OS: Ubuntu 15.10 - 64-Bit  

Terminal or terminal emulator: x-terminal-emulator

**Comment by faho** [comment] 2016-03-21 19:12
Duplicate of #845 - event handlers can't be autoloaded, so any function that defines one must be explicitly sourced. Our current idea is that event handlers can be defined either in config.fish or in a configuration snippet (new in 2.3).

**Closed by faho** 2016-03-21 19:12 UTC
