### ISSUE TITLE
Old version (3.2.x) are gone from ubuntu PPA

### ISSUE THREAD

**Issue by chbiel** [fish-shell/fish-shell#8094] opened 2021-06-30 09:09 UTC
With the new 3.3.0 release, the 3.2.x versions seem to be gone from the PPA: https://launchpad.net/~fish-shell/+archive/ubuntu/release-3

Is there a reason for this, as fish 3.3 seems to breaks my setup.

Downgrading is not possible at the moment without rebuilding on my own, as download and subscribe do not contain the 3.2.x packages anymore (https://fishshell.com/)

**Comment by faho** [comment] 2021-06-30 09:26
Duplicate of #6957

**Comment by faho** [comment] 2021-06-30 09:27
This isn't something that PPAs easily support. Sorry!

You probably still have the package in your cache - /var/cache/apt/archives, IIRC?

**Closed by faho** 2021-06-30 09:26 UTC

**Comment by chbiel** [comment] 2021-06-30 09:55
thanks for pointing me there. still bad as the archive still already has the newest version.
