### ISSUE TITLE
Error message about snap along with the welcome message

### ISSUE THREAD

**Issue by pramodhrachuri** [fish-shell/fish-shell#8715] opened 2022-02-10 21:14 UTC
I have just installed updates and opened up a new terminal. Now I am seeing an error message every time I open fish.

Error message -
```
/usr/share/fish/vendor_conf.d/snapd.fish (line 3): 
fish_add_path -aP $snap_bin_path
^
from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish
	called on line 294 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup
```

Recording - 
https://asciinema.org/a/6t0wMslrJlerKiwJWah94dUSJ

```
$ fish --version
fish, version 3.1.0

$ echo $version
3.1.0
```

```
$uname -a
Linux pramodh-Lenovo-ideapad-FLEX-4-1580 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$echo $TERM
xterm-256color
```

**Comment by faho** [comment] 2022-02-10 21:29
Duplicate of #8713

**Comment by faho** [comment] 2022-02-10 21:29
Already reported upstream: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1957948

**Closed by faho** 2022-02-10 21:29 UTC
