### ISSUE TITLE
Redirecting stdout to directory from piped command causes crash

### ISSUE THREAD

**Issue by gregdan3** [fish-shell/fish-shell#7517] opened 2020-11-30 19:15 UTC
# Version
`fish --version`: `fish, version 3.1.2`

# Reproducing the bug

In fish shell, perform the following command:
```sh
cat any_file | sed 's/any/string/g' > ~/
```
The exact commands you use don't seem to matter, nor their arguments; all that matters is you pipe, then redirect with valid commands. For example, this also causes the same crash:
```sh
jq | ls > /
```

The following will result:
```
<W> fish: An error occurred while redirecting file '/home/gregdan3/'
open: Is a directory
```
Then, any future interaction with `fish` (pressing any key) will crash.

# Details of the crash

The above described issue appears to behave differently depending on what commands are executed and/or the circumstances in which `fish` is running; the crash always occurs, but exactly what it does changes. As the prompt of my terminal `st`, I get the behavior I described before where the shell will crash, and this takes `st` with it, closing the window. 

However, if you were to run `bash`, then open `fish` inside it, the crash will instead cause the terminal to lock up and become uninteractable, as well as consuming an entire CPU core.

**Comment by faho** [comment] 2020-11-30 19:22
Duplicate of #7038

**Comment by faho** [comment] 2020-11-30 19:22
I can confirm it's indeed fixed in master.

**Closed by faho** 2020-11-30 19:22 UTC

**Comment by gregdan3** [comment] 2020-11-30 19:33
Glad to hear, thanks!
