### ISSUE TITLE
Unnecessary capitalization / completion for command `scp`

### ISSUE THREAD

**Issue by huangyxi** [fish-shell/fish-shell#10537] opened 2024-05-30 09:51 UTC
fish: `fish, version 3.7.1`
OS: `Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64`

Currently, Fish completes and/or capitalizes remote paths using the local directory in commands like `scp`, even if the same directory doesn't exist. However, this behavior doesn't affect the actual command, only the display. I think this could confuse users.

[![asciicast](https://asciinema.org/a/45gAu1Y67G92Gf21sqbTAXLp5.svg)](https://asciinema.org/a/45gAu1Y67G92Gf21sqbTAXLp5)>

**Comment by faho** [comment] 2024-05-30 09:55
Duplicate of #3134

**Closed by faho** 2024-05-30 09:55 UTC
