### ISSUE TITLE
Problem with pkg-config

### ISSUE THREAD

**Issue by nlw0** [fish-shell/fish-shell#982] opened 2013-08-29 02:54 UTC
I am trying to compile an opencv program, using pkg-config to help assemble the compile command. In bash I would use

```
g++ -o code code.cc `pkg-config opencv --cflags --libs`
```

and the corresponding in fish would be

`g++ -o code code.cc (pkg-config opencv --cflags --libs)`

But something happens, and it seems the correct command is not being executed. If I `echo` that, and then copy-paste the command, it works. What can be happening?

**Comment by zanchey** [comment] 2015-11-28 06:31
Seeing as it comes up fairly frequently - #1947, #2568, #2569 - should fish provide a wrapper around `pkg-config` that just DTRT?

**Comment by faho** [comment] 2015-11-28 16:11
As in 

```fish
function pkg-config
    command pkg-config $argv | string split " "
end
```
?

I'd be okay with that, though the comments should make it clear what's going on.

**Comment by faho** [comment] 2015-12-03 12:14
That actually breaks for e.g. `pkg-config --list-all`.

**Comment by Streppel** [comment] 2016-02-14 05:29
Just ended here, after struggling for about two hours. *my face* when I saw @xfix explanation. A wrapper would be nice - I'll be following @nlw0 suggestion. Thanks.

**Comment by tonytonyjan** [comment] 2016-05-24 18:02
below is my solution using `eval`:

    eval g++ -o code code.cc (pkg-config opencv --cflags --libs)

**Comment by zanchey** [comment] 2016-07-06 12:56
Perhaps the pkg-config developers could alter the output for fish. I've asked them at https://bugs.freedesktop.org/show_bug.cgi?id=96830

If not, a wrapper function that does `if status --is-command-substitution` before transforming the next might be the best method.

**Comment by jbarlow83** [comment] 2016-12-18 21:13
Just ran into this with python3-config -- worth noting that there are some forms of {package}-config that wrap or behave similarly to pkg-config that exhibit this problem.

I think the best course of action is to wrap pkg-config and friends - then it can be fixed in fish for all *existing* versions of pkg-config rather than waiting for the (somewhat reluctant sounding) developer of pkg-config to maybe include a patch.

**Comment by faho** [comment] 2016-12-18 21:26
Unfortunately, the wrapper solution doesn't seem workable.

The problem is that pkg-config has a lot of options, and only some of those are space-separated - e.g. "--list-all" prints two padded columns. So we'd be stuck parsing pkg-config's arguments for it.

This needs to be documented in general (not just for pkg-config), and it'd be swell if pkg-config would get a patch - we could even add a wrapper function that calls "pkg-config --fish-syntax".

I mean I can't currently see in what way pkg-config would break if it would just always use newlines (AFAIK every shell _also_ splits on newlines), but I can also see why the pkg-config maintainers would be reluctant to change that for what is a small portion of their users, with little to no benefit for "everyone else".

**Comment by zanchey** [comment] 2016-12-18 23:14
The pkg-config maintainer says:

> I suppose I'd take a patch that prints each argument on a newline if it's not too intrusive. I'd prefer not to autodetect it but rather have it be an explicit option (--fish-syntax?). Not really sure, this is an unusual environment. I don't really see how command substitution is going to work well in fish unless all other tools are changed to output newlines or fish handles this natively.

**Comment by faho** [comment] 2017-12-13 17:40
I think I completely missed @zanchey's idea of only doing it in command substitutions.

That actually sounds like it could work - it might make people think we split on newlines, but at this point, I've heard about this issue enough that I'm inclined to believe it's bad enough to be worth it.

However, while `pkg-config` is certainly the most well-known of these things, there are a whole bunch of other tools like it. On my system I count:

```
aalib-config
caca-config
croco-0.6-config
cups-config
curl-config
freetype-config
gdlib-config
gpg-error-config
gpgme-config
gphoto2-config
gphoto2-port-config
ijs-config
imlib2-config
js24-config
krb5-config
ksba-config
libassuan-config
libgcrypt-config
libmikmod-config
libotf-config
libpng-config
libpng-config-32
libpng16-config
libpng16-config-32
m17n-config
Magick++-config
MagickCore-config
MagickWand-config
ncursesw6-config
npth-config
nspr-config
onig-config
pcap-config
pcre-config
python-config
python2-config
python2.7-config
python3-config
python3.6-config
python3.6m-config
rasqal-config
redland-config
sane-config
sdl-config
sdl-config-32
sdl2-config
smpeg-config
taglib-config
taglib-extras-config
xml2-config
xmlsec1-config
xslt-config
```

(generated with the quite dangerous `for program in /usr/bin/*config*; eval $program --libs ^/dev/null | grep "^-[lL]" >/dev/null; and echo $program; end`)

That's 52 things that all need a function along the lines of

```fish
function $tool-config
    if status is-command-substitution
        command $tool-config $argv | string split ' '
    else
        command $tool-config $argv
    end
end
```

For comparison, we currently have a total of 185 function files. This would inflate that number quite a bit.

However, the only alternative I can come up with is to do something like

```fish
for tool in #list
    function $tool
```

in share/config.fish. Which strikes me as quite ugly.

Any ideas?

**Comment by mqudsi** [comment] 2018-03-05 22:40
I'm highly against writing a function for each of those commands both because it's unmaintainable and because it's a workaround against something that should be _somehow_ possible in fish (i.e. command substitution without escaping).

**Comment by faho** [comment] 2018-03-06 14:13
>it's a workaround against something that should be somehow possible in fish (i.e. command substitution without escaping).

?

I don't think you quite understand the issue. What is needed here is to split on spaces, not just newlines. And that _is_ possible - just use `string split " "`. The problem is that users need to know about that, and use it with these tools pretty much always.

**Comment by mqudsi** [comment] 2018-03-06 16:13
It's not sufficient to split on spaces, though. That's just a hack that happens to work in _some_ cases:

```fish
mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" "Mahmoud Al-Qudsi" "today"
Hello Mahmoud Al-Qudsi, What can I do for you today?⏎                                                                                       mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" (echo "Mahmoud Al-Qudsi" "today")
Hello Mahmoud Al-Qudsi today, What can I do for you ?⏎                                                                                      mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" (echo "Mahmoud Al-Qudsi" "today" | string split " ")
Hello Mahmoud, What can I do for you Al-Qudsi?Hello today, What can I do for you ?⏎ 
```

**Comment by mqudsi** [comment] 2018-03-06 16:16
The problem is that splitting on spaces is just a workaround that does not address the core issue and also does not cover anything other than the most basic case.

```
mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" "Mahmoud Al-Qudsi" "today"
Hello Mahmoud Al-Qudsi, What can I do for you today?⏎                                                                                       
mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" (echo "Mahmoud Al-Qudsi" "today")
Hello Mahmoud Al-Qudsi today, What can I do for you ?⏎                                                                                      
mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" (echo "Mahmoud Al-Qudsi" "today" | string split " ")
Hello Mahmoud, What can I do for you Al-Qudsi?Hello today, What can I do for you ?⏎                                                         
mqudsi@ZBook ~/r/fish-shell> printf "Hello %s, What can I do for you %s?" (echo \"Mahmoud Al-Qudsi\" \"today\" | string split " ")
Hello "Mahmoud, What can I do for you Al-Qudsi"?Hello "today", What can I do for you ?⏎
```

**Comment by faho** [comment] 2018-03-06 16:50
>The problem is that splitting on spaces is just a workaround that does not address the core issue and also does not cover anything other than the most basic case.

Aaaah, now I get what you want, and now I get what you mean in #4781 with "unescaped" substitution.

So, I gather you assume command substitutions work like this:

- Fish executes the command, buffers the output

- It then goes through that output and escapes (by inserting a `\\` or similar) all the things that would end a token, except for newlines

- It then runs all that output through the tokenizer, which causes one token per line to appear

If so, that's not what happens. Fish doesn't escape only to then undo that escaping.

What happens is:

- Fish runs command, buffers output.

- Fish goes through the output and splits it on newlines (unless $IFS is not set, in which case it doesn't split at all).

- Fish inserts the resulting tokens into the arguments to be passed to the next command.

Adding some way to read tokens (as if they appeared on the commandline) is something we definitely want to add. See #3823.

However, that's not what is needed here - bash doesn't tokenize this either (it splits on every char in $IFS, which defaults to space, tab and newline), so the command wouldn't work with bash either if it expected tokenization. POSIX's (and therefore bash's) `read` builtin works like that by default, and it's a frequent source of problems. Which is why http://mywiki.wooledge.org/BashFAQ/001 (yes, question number 1) recommends using `IFS= read -r line` and says:

>You should almost always use the -r option with read.

Anyway, let's track tokenization in #3823. This is about adding a workaround to a common issue with the `*-config` tools, that just requires splitting on spaces.

**Comment by mqudsi** [comment] 2018-03-06 18:58
Thanks. Yes, now you get what I meant :)

**Comment by faho** [comment] 2018-04-30 19:00
>those one-liners won't correctly cover corner cases like quoted spaces in the input string

That doesn't actually happen here. In POSIX, command substitutions are just split on $IFS, quotes have no special meaning.

E.g.

```sh
$ printf '%s\n' $(echo "a string 'with spaces'")
a
string
'with
spaces'
```

Note how `'with` and `spaces'` appear on separate lines? That's because they're separate arguments to `printf`.

>when IFS is set to a different character in Fish

I don't think we need to support that, because $IFS would be set on the fish side.

What technically would have to be done is to split _runs_ of the splitting characters, so instead of `string split " " | string split \t` (because tab is also in POSIX' IFS by default), we'd have to do something like `string replace -ra '[ \t]+' \n` (because fish splits on newlines, replacing all runs of spaces or tabs with that will work).

I don't think that quite requires a wrapper - with these `*-config` things, all cases I've seen can be handled via just `string split " "`, and the issue is more that something needs to be done at all, which means you need to know to do something.

**Comment by faho** [comment] 2018-10-24 20:40
This has now been made an FAQ entry.

It doesn't appear like there's any movement here, so I'm closing this.

**Closed by faho** 2018-10-24 20:40 UTC
Labels: docs, enhancement
