### ISSUE TITLE
ls tab completion lockup when using custom aliases

### ISSUE THREAD

**Issue by sheenobu** [fish-shell/fish-shell#6512] opened 2020-01-19 22:33 UTC
This is an interesting lockup, if you configure 'ls' to group directories first. I didn't see this problem on Fedora 30/31 but as I switched over to NixOS I see this problem now. I do not have the OS details/fish version from Fedora. 

OS details:

```
> fish --version
fish, version 3.0.2
> echo $version
3.0.2
> uname -a
Linux talos 4.19.96 #1-NixOS SMP Tue Jan 14 19:07:09 UTC 2020 x86_64 GNU/Linux
```

Reproduction: 

```
sheenobu@talos ~> sh -c 'env HOME=$(mktemp -d) fish'
sheenobu@talos /h/sheenobu> ls f<tab>iles/^C
sheenobu@talos /h/sheenobu> alias ls 'ls --group-directories-first --color=auto'
sheenobu@talos /h/sheenobu> ps
  PID TTY          TIME CMD
 9267 pts/10   00:00:00 fish
 9315 pts/10   00:00:00 fish
 9387 pts/10   00:00:00 ps
sheenobu@talos /h/sheenobu> ls fi<tab>
```

GDB shows stuff actually happening. Thread 1 looks like it's operating. as i continue the running operation (c, then ctrl-c, then bt) i do see syscalls like access happening. Don't know if this is a real lockup or an edge case causing this to recurse through my whole file tree? 

https://gist.github.com/sheenobu/426ddcbc647601572d24ca91c94c0974

fish processes stick around after closing my term (alacritty). I'm having to pkill fish to clean it all up.

**Comment by sheenobu** [comment] 2020-01-19 22:37
https://github.com/fish-shell/fish-shell/issues/2771

this is a similar issue but the problem was chalked up to size. but 'files' is really small and not networked:

```
sheenobu@talos ~> dir -1 files | wc -l
7
sheenobu@talos ~> dir -1 files | wc -l^C
sheenobu@talos ~> find files | wc -l
23
```

**Comment by sheenobu** [comment] 2020-01-19 22:50
alias ls 'ls --group-directories-first --color=tty' - locks up
alias ls 'ls --color=never' - locks up
alias ls 'ls --color=tty' - doesn't lockup

**Comment by krobelus** [comment] 2020-01-20 16:00
Probably a duplicate of #5949 which is fixed in master

**Comment by faho** [comment] 2020-01-20 16:16
Duplicate of #5949

**Comment by faho** [comment] 2020-01-20 16:17
Yeah, same thing as 5949.

**Closed by faho** 2020-01-20 16:16 UTC
