### ISSUE TITLE
Pipes between functions behaves differently than pipes between processes

### ISSUE THREAD

**Issue by account-login** [fish-shell/fish-shell#8577] opened 2021-12-23 13:28 UTC
```fish
echo $version
3.2.2
```

Try the following pipe:
`grep --line-buffered a |grep --line-buffered b`
Now type something that should emit some output (eg `abc`), but no output is printed because the process `grep b` is not created at all. The `grep b` command won't execute until the `grep a` is exited.
The `grep` command is a function defined by fish at `/usr/share/fish/functions/grep.fish`

**Comment by faho** [comment] 2021-12-23 13:28
Duplicate of #1396

**Closed by faho** 2021-12-23 13:28 UTC
