### ISSUE TITLE
Fish should not hang on tab completion

### ISSUE THREAD

**Issue by WillDignazio** [fish-shell/fish-shell#7194] opened 2020-07-13 21:23 UTC
Fish exhaustively tries to figure out the tab-completions available for the given command. It can spend a considerable amount of time finding the completions, and visually is noticeable. Fish should have a deadline that is less than the time it takes to 'feel' that fish is hung (think like 100ms).

Ideally the alternative behavior is to to give some indication that the tab completions are still loading, or short out and not print out completions.

**Comment by faho** [comment] 2020-07-13 21:29
Duplicate of #23

**Closed by faho** 2020-07-13 21:29 UTC
