### ISSUE TITLE
Fish is placing non-config files in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ZyX-I** [fish-shell/fish-shell#1257] opened 2014-01-21 18:33 UTC
In `$XDG_CONFIG_HOME/fish/` there are two files which should not be there for them not being a user configuration: `fishd.${HOST}` and `fish_history`. Both are generated by fish and not by user meaning that they are not user configuration meaning that they should go to `$XDG_CACHE_HOME` or `$XDG_DATA_HOME` (`fish_history`) and `$XDG_RUNTIME_DIR` (`fishd.$HOST`).

Ref #744. It talks about history only though, I am also talking about `fishd` file.

**Comment by RSully** [comment] 2015-07-13 13:02
@zanchey is this still slated for 3.0 or might we see 2.3, now that 2.2 is out and fishd is out of the picture (I'm not sure how the fishd.${HOST} file fits in now with fishd gone).

**Comment by zanchey** [comment] 2015-07-24 10:40
The fishd process has gone, but the file is still used - there has to be some shared storage between multiple processes!

I'd happily merge a patch that handles this move sensitively, but I don't know that anyone's actively working on it.

**Comment by jrobeson** [comment] 2016-02-28 21:37
at least the history one will be solved in the next release :) . I wonder if the issue title should be updated.

**Comment by zanchey** [comment] 2016-05-21 21:58
I think we might be done here! History was moved in #2399, and completions in #1343 - there shouldn't be anything except configuration left in XDG_CONFIG_HOME.

**Comment by nhooyr** [comment] 2016-10-12 23:30
I still see a `fishd.80e6500e4c3e` in ~/.config on version 2.3.1. Should that be there?

**Comment by faho** [comment] 2016-10-12 23:54
Yes. Thats where the universal variables are stored.

**Comment by daleeidd** [comment] 2016-12-29 23:00
@faho The problem is that the file contains non-user generated content. See below:
```
SET __fish_init_2_39_8:\x1d
SET __fish_init_2_3_0:\x1d
```

This will never be set by the user. In fact, that file is full of variables I have not set. For those who wish to use configs over the universal variables, the file is an eyesore. Even the name of the file is generated.

**Comment by etu** [comment] 2016-12-29 23:04
Then you can do it like I do: use set -U in config.fish. it's a hack, I
know. But it really works.

**Comment by zanchey** [comment] 2017-01-02 10:33
On a second look, I think you're right - the fishd file should be in the `$XDG_DATA_HOME` directory. Moving it is going to be tricky, though.

**Comment by nhooyr** [comment] 2017-01-04 20:28
With what @etu is doing, what is the point of universal variables anyway?

**Comment by etu** [comment] 2017-01-05 08:46
Then it would be nice to have one file for user set universal variables
that are stored in XDG_CONFIG_HOME and non-user-set that are stored in
XDG_DATA_DIR (If I remember the name).

And keeping track of what's user set and what's default is quite easy if we
always store the default one in XDG_DATA_DIR and have overrides in
XDG_CONFIG_HOME.

**Comment by nhooyr** [comment] 2017-02-21 01:25
Why are fishd files machine dependant? I think it'd be really neat to just configure my abbreviations or universal variables interactively and not have to worry about them, knowing they are stored in my fishd file and I can share this across systems to immediately access my abbreviations and once again edit and then test them interactively.

**Comment by ridiculousfish** [comment] 2017-02-21 17:10
fishd files are machine independent to support the shared home directory use case. There's ongoing discussions about how to make this work better for syncing in #1912

**Comment by faho** [comment] 2019-03-15 18:36
We now have changed the uvar file to be machine-independent, so you can just sync it along with your config.

The only remaining issue is purely cosmetic, and doesn't warrant the effort of moving.

So I'm closing this.

**Closed by faho** 2019-03-15 18:36 UTC
Labels: enhancement
