### ISSUE TITLE
fish_title gives no output in 2.4.0

### ISSUE THREAD

**Issue by chriszarate** [fish-shell/fish-shell#3578] opened 2016-11-22 20:01 UTC
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0
**OS/terminal used**: OS X Terminal.app

After upgrading to fish 2.4.0 from 2.3.1, my custom `fish_title` function no longer produces output. The same function named differently produces the correct output (but of course does not update the window title).

## Reproduction steps
1. `echo "function fish_title; echo "hello"; end" > ~/.config/fish/functions/fish_title.fish`
2. `echo "function fish_title_copy; echo "hello"; end" > ~/.config/fish/functions/fish_title_copy.fish`
3. reload shell

## Results
title is not updated, running `fish_title` at prompt produces no output:

```console
> fish_title
> fish_title_copy
hello
>
```

**Comment by faho** [comment] 2016-11-22 20:21
I cannot reproduce this, neither with stock 2.4.0 nor with a recent git build.

@chriszarate: Can you confirm that `functions fish_title` shows the correct thing? It's possible your $fish_function_path doesn't actually contain that. `printf "%s\n" $fish_function_path` would also be nice.

Also, we offer the `funced` and `funcsave` functions to open a function in your editor and save a function to a file, respectively. Those should always use the correct path.

**Comment by chriszarate** [comment] 2016-11-22 21:20
Thanks, that let me gather more info but it leads to some puzzling behavior.

```console
> functions fish_title
function fish_title

end
> cat /Users/username/.config/fish/functions/fish_title.fish
function fish_title; echo hello; end
> printf "%s\n" $fish_function_path
/Users/username/.config/fish/functions
/usr/local/Cellar/fish/2.4.0/etc/fish/functions
/usr/local/share/fish/vendor_functions.d
/usr/local/Cellar/fish/2.4.0/share/fish/functions
> 
```

Neither `/usr/local/Cellar/fish/2.4.0/etc/fish/functions` nor `/usr/local/share/fish/vendor_functions.d` exists. There is no `fish_title.fish` in `/usr/local/Cellar/fish/2.4.0/share/fish/functions`.

Next I tried using `funced` and `funcsave`, which can provide a working `fish_title` in the current session. Things get a little weird here.

```console
> cat /Users/username/.config/fish/functions/fish_title.fish
function fish_title; echo "hello"; end
> functions fish_title
function fish_title

end
> funced fish_title # edited as below
> functions fish_title
function fish_title
	echo "hola"
end
> funcsave fish_title # from this point it sets the window title correctly
> cat /Users/username/.config/fish/functions/fish_title.fish
function fish_title
        echo "hola"
end
> funcsave fish_title
> fish_title 
hola
>
```

However, as soon as I open another shell, `fish_title` "resets" back to an empty function:

```console
> functions fish_title
function fish_title

end
> cat /Users/username/.config/fish/functions/fish_title.fish
function fish_title
        echo "hola"
end
>
```

In fact, if I look quickly I will see "hola" flash in the window title briefly before it is replaced with the default window title (I assume because it was set to an empty string).

Next I tried `brew uninstall --force fish; brew install fish` but end up with the same results. OS X 10.11.4.

**Comment by faho** [comment] 2016-11-22 21:32
Aaaaah..... I know what it is.

@floam committed 2c8bc05826bc44f67a0a0b9163da2f55ec0f6453, which  disables fish_title for Terminal.app because it would compose a nicer title if we don't try to provide a custom one. Only because it's in `__fish_config_interactive.fish`, it'll be done _after_ your configuration has been read so any customization will be for naught.

@floam: Would it be nicer to do this in share/config.fish, maybe still guarded with `status is-interactive`?

**Comment by krader1961** [comment] 2016-11-22 23:59
@faho and @floam: I think the `function fish_title; end` should be removed from *__fish_config_interactive.fish*. Fish has no business overriding the user's function. At most we might want to issue a one time warning if they've done so that explains why they might prefer the result if they didn't.

**Comment by faho** [comment] 2016-11-23 10:02
@krader1961: We set a default `fish_title` in c++ (DEFAULT_TITLE in src/reader.cpp) if no function has been defined. That's what @floam was trying to stop.

How about `functions -q fish_title; or function fish_title; end`? So we don't use our default title, so the terminal goes to its default, but only if the user hasn't customized it.

**Comment by floam** [comment] 2016-11-24 03:38
Makes sense to me.

**Closed** 2016-11-27 04:03 UTC
Labels: bug, regression

**Comment by timkite** [comment] 2016-12-12 21:48
I'm also having this issue. I found that reverting to fish 2.3.1 fixes the issue. Apple's terminal sets a title, sure, but I like to add info that it can't (like current hostname and, when remote, the tier of server I'm connected to).
