### ISSUE TITLE
Could fish include column number for --no-execute's output?

### ISSUE THREAD

**Issue by yuutayamada** [fish-shell/fish-shell#3331] opened 2016-08-24 20:35 UTC
- [X] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1-483-g476ffe1
**OS/terminal used**: 
Ubuntu16.04 LTS/urxvt

Hi, I would make on the fly syntax checker for emacs using [flycheck](http://www.flycheck.org/en/latest/).

But, flycheck parses linter's output by regex and current output of --no-execute option doesn't include column number. (if there is column number, it would be so much easier to implement on the fly syntax checker for fish)

Could you include column number to --no-execute option's output?
(or maybe adding --verbosity option?)

## Reproduction steps

1. Launch fish
2. check incorrect fish file with `fish -n XXX.fish`

## Expected results
something like:
```sh
$ fish -n foo.fish                                                                           (master ⚡↑) 
foo.fish (line 2 column 1): abbr -a gco='git checkout'
                            ^
```

## Actual results
```sh
$ fish -n foo.fish                                                                           (master ⚡↑) 
foo.fish (line 2): abbr -a gco='git checkout'
                   ^
```

**Comment by faho** [comment] 2016-08-24 21:02
What fish is complaining about here is that it can't find anything by that name because it's a function. $fish_function_path is defined in a script which is also not executed, so fish can't know which functions exist in this mode.

We should probably just stop checking that (since we can never get the user's full function path without executing anything).

**Comment by faho** [comment] 2016-08-24 21:06
Sorry, wrong tab.

**Comment by faho** [comment] 2016-09-04 23:42
This is a duplicate of #539.

**Closed by faho** 2016-09-04 23:42 UTC
