### ISSUE TITLE
Calling a fish function from a git alias fails

### ISSUE THREAD

**Issue by dideler** [fish-shell/fish-shell#1258] opened 2014-01-21 20:16 UTC
I have a fish function (`~/.config/fish/functions/git-clean.fish`) that I'm trying to call from a git alias set in my  `~/.gitconfig`.

The git alias is `rm-untracked = !fish -c 'git-clean'`.

The function works fine when called directly, calling it through the alias fails:

```
$ git rm-untracked  # Calling function through Git alias fails
fish: Couldn't grab control of terminal
tcsetpgrp: Interrupted system call

$ git-clean  # Calling function directly works
Would remove app/models/order.rb
Would remove db/migrate/20140121194853_create_orders.rb
Would remove test/factories/orders.rb
Would remove test/models/order_test.rb
Continue? [Yn]
> y
Removing app/models/order.rb
Removing db/migrate/20140121194853_create_orders.rb
Removing test/factories/orders.rb
Removing test/models/order_test.rb
```

**Comment by faho** [comment] 2015-07-17 19:21
I am guessing here you're trying to `read` user input in that function.

Executing fish functions via git aliases works:

In ~/.config/fish/functions/ni.fish

    function ni
        echo "NI"
    end

alias is `ni = !fish -c 'ni'`.

    $ git ni
    NI

Change ni to

    function ni
        echo "NI"
        read ni
        echo $ni
    end

and suddenly `git ni` yields:

>NI                                                                                                                                                                                      
>fish: Couldn't grab control of terminal                                                                                                                                                 
>tcsetpgrp: Interrupted system call

I'm not sure if this is a fish issue - seems like git doesn't connect stdin (or something).

**Comment by pickfire** [comment] 2015-07-19 08:58
And I hope alias in alias works too.

**Comment by faho** [comment] 2015-07-19 11:31
What do you mean? Using a fish-alias in a git-alias? That works too, since aliases are just functions.

**Comment by pickfire** [comment] 2015-07-21 09:28
```fish
alias a='asdf'
alias q='qwerty'
```
`a q` -> `asdf qwerty`

**Comment by faho** [comment] 2015-07-21 09:40
That's basically what zsh calls "global aliases", and it won't work with fish's current approach, which is to have `alias` as a shortcut to defining functions.

I.e. that'd be a feature request, and not one that would be accepted, I think. Extending `abbr` might work, but that would then need a way to _not_ expand.

**Comment by zanchey** [comment] 2015-07-24 15:17
Shortly after fish sets itself into its own process group, `tcsetpgrp` gets SIGTTOU, which causes a return with EINTR.

[The POSIX documentation says](http://pubs.opengroup.org/onlinepubs/9699919799/functions/tcsetpgrp.html):

> Attempts to use tcsetpgrp() from a process which is a member of a background process group on a _fildes_ associated with its controlling terminal shall cause the process group to be sent a SIGTTOU signal. If the calling thread is blocking SIGTTOU signals or the process is ignoring SIGTTOU signals, the process shall be allowed to perform the operation, and no signal is sent.

That sounds bananas to me, but it might be worth a go.

I can't really understand why fish is so insistent on being in its own process group; bash and zsh don't seem to bother in this situation.

**Comment by krader1961** [comment] 2017-03-23 00:26
This still doesn't work but the symptoms are now different. Probably due to the reworking of signal management I did recently. The fish process now blocks in the ioctl done by the `tcsetpgrp()` call done from `reader_push()` from `builtin_read()`. The act of dumping the call stack using a process debugger results in the shell exiting with the following output when the debugger detaches from the process:

```
<E> fish: Couldn't grab control of terminal
tcsetpgrp: Interrupted system call
```

**Comment by faho** [comment] 2017-07-24 17:02
I'm gonna declare this a duplicate of #3805. Both feature fish being unable to `read` as a result of being started from something else. I find 3805 has a nicer test case.

**Closed by faho** 2017-07-24 17:02 UTC
Labels: bug
