### ISSUE TITLE
cd multi up level

### ISSUE THREAD

**Issue by RustJason** [fish-shell/fish-shell#2671] opened 2016-01-10 10:42 UTC
Does fish support ```cd ...``` like zsh?
This will cd to the parent of the parent folder

**Comment by faho** [comment] 2016-01-10 11:17
It does not.

How far does zsh take this? Is `cd ....` "go three directories up" and `cd .....` four?

**Comment by faho** [comment] 2016-01-10 14:22
Also, how does it work if there's an actual directory called "...", i.e.:

```zsh
echo $PWD
mkdir ...
cd ...
echo $PWD
```

**Comment by faho** [comment] 2016-01-10 14:39
Okay, zsh by default actually doesn't do that, so I assume you're using one of those framework things?

**Comment by pickfire** [comment] 2016-01-10 14:46
@RustJason There is already an issue for this, this is duplicated. (I am the other one who did another duplicate issue)

The problem is that this will cause `ls ...` to fail, it will be ugly. I hope that this feature will be implemented too, but it may destroy other applications.

**Comment by faho** [comment] 2016-01-10 15:05
@pickfire: #2109, you mean?

>The problem is that this will cause ls ... to fail

It's not that `ls ...` will _fail_, it's that the "..." there will mean something different than the "..." for `cd`. That's the inconsistency @xfix was talking about.

I'm not quite so sure that it's an issue. I've been testing this (and path replacement). Here's my current cd.fish:


```fish
function cd --description "Change directory"

	# Skip history in subshells
	if status --is-command-substitution
		builtin cd $argv
		return $status
	end

	# Avoid set completions
	set -l previous $PWD

	if test $argv[1] = - ^/dev/null
		if test "$__fish_cd_direction" = next ^/dev/null
			nextd
		else
			prevd
		end
		return $status
	end

	# Path replacement - in /home/alfa/Music, `cd alfa bravo` should go to /home/bravo/Music
	if set -q argv[2]
		set argv[1] (string replace -- $argv[1] $argv[2] $PWD)
	end

	# If argument consists solely of dots, go up number of dots - 1 directories - `cd ...` goes up to the grandparent
	if string match -qr '^\.{3,}$' -- $argv[1]
		# Only do this if there's no directory called "..." - which is theoretically allowed
		test -d $argv[1]; or set argv[1] (string replace "." "" -- $argv[1] | string replace -a "." "../")
	end

	builtin cd $argv[1]
	set -l cd_status $status

	if test $cd_status = 0 -a "$PWD" != "$previous"
		set -g dirprev $dirprev $previous
		set -e dirnext
		set -g __fish_cd_direction prev
	end

	return $cd_status
end
```

(in case you're running a released fish, replace `string match` with grep and `string replace` with sed)

I'll test-drive this a bit and think about it some more.

**Comment by pickfire** [comment] 2016-01-11 11:32
@faho, nice taking this issue up. This is a nice feature to be implemented.

(I hope that @xfix doesn't close this issue)

**Comment by krader1961** [comment] 2016-01-27 02:23
If you want to change directory to the grandparent directory you can type `cd ../..`. That's just two additional characters. This is the type of feature that very few people will find useful but will complicate the implementation and documentation. The fact that a directory named __...__ (for an arbitrary number of periods >= 3) affects the behavior is itself a warning sign that the idea is a bad idea. I vote no on implementing this feature.

**Comment by krader1961** [comment] 2016-03-23 02:41
This feature isn't compelling. That is, it doesn't allow fish users to do anything they can't already do. It doesn't even provide a meaningful reduction in the number of characters someone has to type. Furthermore, it introduces ambiguities since a directory can contain a file with an arbitrary number of dots as long as the number is greater than two. Sorry, @pickfire, but this is exactly the type of enhancement that, if adopted, would turn fish into zsh. I left zsh for fish precisely because of these types of ad-hoc features that almost no one uses.

**Closed by krader1961** 2016-03-23 02:41 UTC
Labels: enhancement, will-not-fix

**Comment by pickfire** [comment] 2016-03-23 14:08
No problem, this is just a minor feature, I guess it doesn't affect much without it.

**Comment by nickeb96** [comment] 2019-05-26 03:51
If anyone is still interested in this feature, I wrote a plugin for the [fisher](https://github.com/gorgebucaran/fisher) plugin manager.  Just run the following command to install it:
```
> fisher add nickeb96/expanddots
```
Or ``fisher rm nickeb96/expanddots`` to remove it.  Let me know if you have any problems with it or would like any additional functionality.

**Comment by LinxiFan** [comment] 2019-12-21 06:39
Simply hard-code it:
```
function ...
     cd ../..
end

function ....
     cd ../../..
end
```
You don't even have to `cd`, just type `...` to go up two levels. I doubt you'll need anything beyond `....`, but feel free to add more.
