### ISSUE TITLE
binding to self-insert followed by ShellScript enters infinite loop

### ISSUE THREAD

**Issue by BoxMiles** [fish-shell/fish-shell#4457] opened 2017-10-10 00:27 UTC
```
[I] ~ ⟩ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
mspielberg@mbp-007213 /U/mspielberg> echo $version
2.6.0
mspielberg@mbp-007213 /U/mspielberg> bind '' self-insert backward-char
mspielberg@mbp-007213 /U/mspielberg> #skool ti naht redrah si sihT
mspielberg@mbp-007213 /U/mspielberg> bind '' self-insert
mspielberg@mbp-007213 /U/mspielberg> #This is harder than it looks
mspielberg@mbp-007213 /U/mspielberg> bind '' self-insert "commandline -f backward-char"
mspielberg@mbp-007213 /U/mspielberg> (any keystroke enters infinite loop here, 100% CPU usage)
```

I ran into this issue while refactoring a bulky bind of mine into a fish function.

**Comment by zanchey** [comment] 2017-10-31 11:46
The documentation now says "don't do this", but fish should produce an error rather than rendering your session unusable.

**Comment by faho** [comment] 2024-04-02 17:31
Duplicate of #5595

**Closed by faho** 2024-04-02 17:31 UTC
Labels: bug
