### ISSUE TITLE
The pre-installed theme has a bug on it

### ISSUE THREAD

**Issue by 0wx** [fish-shell/fish-shell#8048] opened 2021-06-06 20:57 UTC
Fish Version: 3.1.2
OS: Ubuntu 21.04

I've tried the ```sh -c 'env HOME=$(mktemp -d) fish'```, and it work just fine!

I just fresh install ubuntu on my laptop and want to using fish, back then I'm using the regular fish with no theme neither omf. The pre-installed theme looks nice but it still has bug on it when I try resize the terminal window... 

https://user-images.githubusercontent.com/28288911/120939607-096ff300-c743-11eb-94ab-7a3ba82779ab.mp4

I tried looking for the actual author of the theme at https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md but didnt find it.

**Comment by faho** [comment] 2021-06-06 21:14
1. That's the OMF theme, not ours. This definitely is not "the regular fish with no theme neither omf"
2. That's not a bug in the theme, that's your terminal reflowing it while fish also reflows the prompt
3. We've disabled resizing for terminals we know reflow on their own

So: Duplicate of #7491, upgrade fish.

**Closed by faho** 2021-06-06 21:14 UTC
