### ISSUE TITLE
Mnemonics for short options

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8507] opened 2021-11-30 09:55 UTC
There are some programs supporting only short options which are less memorizable than long ones. I suggest add ability to `complete` to write custom long mnemonics for those options. These mnemonics could be highlighted in another color (green for instance) than normal options and replaced automatically on typing  with short options while autocomplete.

For instance when I write:

```fish
complete --command crontab --short-option e --mnemonic edit --description 'option is used to edit the current crontab using the editor specified by the …'
```

I define `--edit` mnemonic which on accept will be replaced with `-e`.

**Comment by faho** [comment] 2021-11-30 13:00
Duplicate of #2201

**Closed by faho** 2021-11-30 13:00 UTC
