### ISSUE TITLE
"re" causes crash

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#1421] opened 2014-04-21 20:20 UTC
Hello,

I'm a new fish convert and pretty excited about upgrading from tcsh to something from the 90s :) The scripting language looks really great. Unfortunately I am working under Cygwin/Windows 7 and fish is crashing left and right. I will try to narrow down the issues one by one.

The most replicable issue is whenever I type "re" the autoguessing causes a problem in two possible ways. 

<code>~> reWarning: exec_subshell called off of main thread. Break on debug_thread_error to debug.</code>

Or even more bizarrely a bunch of Chinese characters flash by, and fish exits (not back to the prompt, but back to tcsh where I invoked fish from). Here's an example:

<code>~> re慗湲湩㩧硥捥獟扵桳汥蕞糀㌅䃀࣫댍쀳쉝쳌쳌诌嗿䖋茌ⱴ瓵茖ㅵꅤ䂋謰၀䂋搠ᢡ謀぀䂋謐᱀࿫ꅤ䂋謰၀䂋＠⁵䶋ᯙ菉ˡｑᡵ痿４ၵｐࡵᗿᅠ畆삅ռ쀳倈諨ʲ㌀巀᳂찀쳌쳌ﾋ譕诬ࡅ瓴茬ᙴ痶搱ᢡ謀぀䂋謐ᡀ⃫ꅤ䂋謰၀䂋搏ᢡ謀぀䂋謐⁀jɪ䶍儈Ѫｐ搕䘑蕵糀㌛㣀ࡅŴ聀ॽ琀范ˈ䶋褌㌁䃀࣫눁쀳 쳌쳌诌嗿譖ࡵﺃ瓴茬ᙴﺃ痶搱ᢡ謀぀䂋謐ᡰ⃫ꅤ䂋謰၀炋搏ᢡ謀぀䂋謐⁰jɪ䖍倈Ѫｖ搕䘑蕵糀౅謁၅ࡴ좊蠁ࡍ䗶ȌݴĤ䖈樉贂</code>

I ran this through Google Translate and it's people's proper names and a repeating sentence-fragment about "fake sounds of people eating". Has nothing to do with computers or computer-code it's really strange where these characters came from (they are consistent, the same characters each time). I'm not Chinese and presumably don't have Chinese text on my computer, though who knows.

My system:
<code>~> uname -a
CYGWIN_NT-6.1-WOW64 shuttle-intel-7 1.7.29(0.272/5/3) 2014-04-07 13:44 i686 Cygwin
</code>
fish, version 2.1.0

I turned on debug level 4 and this is the last few lines before the re crash .. note that fish shell exits back to tcsh after the Chinese characters:

fish: proc::read_try('pwd | sed -e 's-^/cygdrive/\(.\)/\?-\u\1:/-'')
fish: Job is constructed
fish: Continue job 1, gid 0 (__fish_pwd), COMPLETED, NON-INTERACTIVE
fish: proc::read_try('__fish_pwd')
fish: io_buffer_t::read: blocking read on fd 4
fish: Create barrier
fish: before write of 8 chars to fd 3
fish: Wrote message 'BARRIER '
fish: Sent barrier request
fish: End barrier
~> rfish: path_get_path( 'r' )
fish: path_get_path( 're' )
fish: path_get_path( 'rehash' )                                                                       r
fish: path_get_path( 'rm' )
fish: path_get_path( 're' )
fish: peath_get_path( 're' )
fish: path_get_path( 'rehash' )
慗湲湩㩧硥捥獟扵桳汥蕞糀㌅䃀࣫댍쀳쉝쳌쳌诌嗿䖋茌ⱴ瓵茖ㅵꅤ䂋謰၀䂋搠ᢡ謀぀䂋謐᱀࿫ꅤ䂋謰၀䂋＠⁵䶋ᯙ菉ˡｑᡵ痿４ၵｐࡵᗿᅠ畆삅ռ쀳倈諨ʲ㌀巀᳂찀쳌쳌ﾋ譕诬ࡅ瓴茬ᙴ痶搱ᢡ謀぀䂋謐ᡀ⃫ꅤ䂋謰၀䂋搏ᢡ謀぀䂋謐⁀jɪ䶍儈Ѫｐ搕䘑蕵糀㌛㣀ࡅŴ聀ॽ琀范ˈ䶋褌㌁䃀࣫눁쀳 쳌쳌诌嗿譖ࡵﺃ瓴茬ᙴﺃ痶搱ᢡ謀぀䂋謐ᡰ⃫ꅤ䂋謰၀炋搏ᢡ謀぀䂋謐⁰jɪ䖍倈Ѫｖ搕䘑蕵糀౅謁၅ࡴ좊蠁ࡍ䗶ȌݴĤ䖈樉贂ࡅ橐嘄ᗿᅨ畆삅ռ쀳倈峨ʱ㌀廀쉝
                                               쳌쳌诌嗿綃瑖荡ࡽ瓵茵ࡽ瓶茅ￎ擫ꅤ䂋謰၀䃷h琀㌄摕

Note the spurious "r" (after path_get_path( 'rehash' )) and spurious "e" (in the middle of fish: peath_get_path( 're' )) .. in the debug display these two letters are highlighted. 

It might be a problem with tcsh rehash? Rehash is a tcsh builtin command, and since I invoked fish from tcsh, is information being passed to fish that it thinks rehash exists but actually doesn't?

-Steve

**Comment by danieljabailey** [comment] 2016-05-17 14:13
I have just had similar garbled Chinese text mixed with what appeared to be the contents of random files on my computer. I got many pages of this before fish crashed, and then the terminal emulator crashed. For me it was triggered by using 'rm' with a wildcard. Also on cygwin on windows 7. fish version 2.2.0

**Comment by krader1961** [comment] 2016-05-18 05:20
@danieljabailey: Can you reproduce the failure? Can you provide more details regarding what lead up to the failure? What wildcard did you type and what is the content of the relevant directories? Also, what is your locale (i.e., `$LANG` and related variables)? Are you able to test the fish 2.3.0 beta build or build and run from git head? If so does the failure still occur?

**Comment by danieljabailey** [comment] 2016-05-18 08:08
Unfortunately this issue appears to be triggered randomly. I'm not sure how
to reproduce it reliably. I think it was related to rm with wildcard but it
doesn't happen for every such command. Also, this is on a work machine
where I'd rather only install cygwin packages that I can get via the cygwin
installer. Currently this is only fish 2.2.0. language is English.

Sorry I can't be of much more help.

**Comment by krader1961** [comment] 2016-05-18 14:45
I'm confident this is a duplicate of issue #1451 and the issue has already been fixed in fish 2.3.0 which is about to be released.

**Closed** 2016-08-02 08:17 UTC
Labels: bug, duplicate, windows
