### ISSUE TITLE
Using aliases with sudo

### ISSUE THREAD

**Issue by nihaals** [fish-shell/fish-shell#7044] opened 2020-05-27 12:53 UTC
I was wondering if there's an equivalent to `alias sudo='sudo '` which allows `sudo x` to use an alias for `x`. The reason why something like `sudo -s` wouldn't work is that the alias changes `sudo apt-get` to `sudo apt` for any relevant subcommand which can be useful when copying examples.

I'm using fish 3.1.2 and tried `alias sudo 'sudo '` but had no success.

**Comment by faho** [comment] 2020-05-27 13:09
There is not, and it would be a massive hack. Use abbreviations instead.

Nihaal Sangha <notifications@github.com> schrieb am Mi., 27. Mai 2020,
14:53:

**Comment by nihaals** [comment] 2020-05-27 13:28
Since abbreviations only work at the start and can't contain spaces I don't think this would work (otherwise I could add one for `sudo apt-get install` for example), which I think is related to #5003 although it couldn't require a different input e.g. `Ctrl + Space` but instead just on paste. I guess this is a feature request that either expands on #5003 or one to allow for abbreviations with spaces.

**Comment by faho** [comment] 2020-05-27 15:21
Okay, what do you want to *do* here?

How do you want to override `apt-get`?

**Comment by nihaals** [comment] 2020-05-27 16:58
As I’m very new to fish I have no idea what the best course would be. My [current solution](https://gist.github.com/nihaals/12c98546531e7df3b6c3614e6e2030dc) completely replaces it then either calls apt or if there isn’t an equivalent, just calls what you gave it, but I think with fish there could be a more efficient way

**Comment by faho** [comment] 2020-05-27 17:03
Okay, I would just make this a script.

Call it "myapt", give it a shebang (which you already have), put it in $PATH and use it.

(Or, if you have to call it `apt` it needs to call the actual apt with a full path, e.g. `/usr/bin/apt`)

**Comment by nihaals** [comment] 2020-05-27 17:06
Wouldn’t it need to be called `apt-get`? Also, if they both have the same name how would it decide to use my proxy version instead of the original when I would just be calling `apt-get`?

**Comment by nihaals** [comment] 2020-05-27 17:08
I think I might have been unclear with my goal, the point is so when I copy something from a README for example, if it uses `apt-get`, it would still use `apt` anyway, effectively replacing `apt-get` with `apt` without changing how you use it

**Comment by faho** [comment] 2020-05-27 17:09
>Wouldn’t it need to be called apt-get?

It would need to be called whatever you call it. You would of course then have it *call* "apt-get" instead of its name.

>Also, if they both have the same name how would it decide to use my proxy version instead of the original when I would just be calling apt-get?

And if it is called "apt-get", you would then have it call the real apt-get via its full path - "/usr/bin/apt-get".

**Comment by nihaals** [comment] 2020-05-27 17:58
I’m still confused on how this would help with https://github.com/fish-shell/fish-shell/issues/7044#issuecomment-634808168 and not provide an alternative way of using apt-get

**Comment by faho** [comment] 2020-05-27 18:10
Okay, here is what you do if you want a thing you can call as `apt-get cache thing` and it will invoke `apt-cache thing`, and as `apt-get install thing` and it will call `apt install thing`:

- Write a script that calls `apt-cache thing` if called with the arguments `cache thing`
- If called as e.g. `apt-get install thing`, call `apt install thing`
- If called with a thing that would have to call the real apt-get, call `/usr/bin/apt-get $restofarguments`
- Save it as `apt-get` in ~/.local/bin
- Add ~/.local/bin to $PATH
- Make it executable
- ???
- Profit

**Comment by nihaals** [comment] 2020-05-27 19:56
That's what I tried to describe in https://github.com/fish-shell/fish-shell/issues/7044#issuecomment-634807047 but I haven't done a very good job :(
Thanks for the explanation!
Out of interest, how would fish decide to pick my custom version instead of the original? Is there a preference to use things later on in the path?

**Comment by faho** [comment] 2020-05-27 20:07
>Out of interest, how would fish decide to pick my custom version instead of the original? Is there a preference to use things later on in the path?

Yes. $PATH is checked front to back, the first match wins.

E.g. my $PATH contains ~/.local/bin and /usr/bin. If something exists in ~/.local/bin that will be executed, not the thing in /usr/bin.

**Comment by nihaals** [comment] 2020-05-27 22:13
[I've got bash working with the new system](https://github.com/nihaals/apt-get-replace/tree/dev), but I can't get fish working, despite using shebangs. I also haven't figured out a nice way to add it to the path for any user as good as `~/.profile`, but I added it to my path with `set -gx PATH /opt/apt-get-replace $PATH` manually and checked with `which` and it was using my script. When I run `sudo apt-get ...` it always uses apt-get in fish and apt in bash.

**Comment by faho** [comment] 2020-05-28 15:43
Most likely something in that configuration is causing `sudo` to use a different $PATH.

Try `sudo which apt-get`

(also the separate `apt-get-replace` script is pretty unnecessary - the extensibility you think you have isn't useful)

**Comment by nihaals** [comment] 2020-05-28 15:58
Yeah you're right, sudo has a different PATH. What's the recommended way to add it so that it applies to everyone? I tried `sudo set` and got command not found, but `sudo echo $SHELL` gave me fish.

I made the script separate just so code isn't repeated. I couldn't think of a nice way to hide it from suggestions other than adding a `_` prefix.

**Comment by faho** [comment] 2020-05-28 16:04
>but sudo echo $SHELL gave me fish.

If you run

```fish
sudo echo $SHELL
```

that $SHELL will be expanded before it ever hits `sudo`.

I would check your sudo configuration, apparently /etc/sudoers has an "env_keep" setting.

**Comment by nihaals** [comment] 2020-05-28 16:27
`sudo printenv SHELL` managed to give me bash.

I created a file in `/etc/sudoers.d/` and added my directory to the path.

Can't say I imagined this being so much more complicated compared to simple aliases :cold_sweat: 

It would still be nice to have `alias sudo 'sudo '` as it would make these things significantly easier.

**Comment by faho** [comment] 2020-05-28 16:29
> It would still be nice to have alias sudo 'sudo ' as it would make these things significantly easier.

Any way to add that would be super hacky, so I don't think it should be.

Closing this as a question.

**Closed by faho** 2020-05-28 16:29 UTC
Labels: question

**Comment by nicolas-oliveira** [comment] 2024-02-13 18:35
I'm reopening this question because I believe that there are ways for the user to change the behavior of sudo and be able to change, for example, command1 to command2.

I know that this is extremely unrecommended and I also know that there are risks, but I did it in such a way that it guarantees that the previous behavior will happen again

I changed the sudo command so that I could use nala in apt-get update or any other command, I did this manually, I know the risks but out of habit I didn't use nala and eventually I even forgot the name of the command. To do this, I made this if statement that only executes nala if it is 'sudo apt-get ..'.
The code looks like this:
```
function sudo
    switch $argv[1]
        case apt-get
            switch $argv[2]
                case autopurge autoremove clean fetch history install list purge remove search show update upgrade
                    command sudo nala $argv[2]
                case '*'
                    command sudo apt-get $argv[2]
            end
        case '*'
            command sudo $argv
    end
end
```

**Comment by ErrorNoInternet** [comment] 2024-06-25 17:29
What if the user has a bunch of aliases like this:

alias ls 'eza --icons --git -g -M'
alias l 'ls -l'
alias l@ 'ls -l@'
alias la 'ls -la'
alias laT 'ls -laT'
alias li 'ls -li'
alias ll 'ls -l'

And they want to make these work under sudo?

**Comment by diniamo** [comment] 2024-07-10 12:35
For anyone still looking, you can do this:
```fish
function sudo --wraps sudo
    if functions -q $argv[1]
        command sudo -E fish -c "$(functions $argv[1]); $argv"
    else
        command sudo $argv
    end
end
```
There might be issues with this, but I couldn't find any yet.

**Comment by repsac-by** [comment] 2024-07-10 13:21
@diniamo,
> There might be issues with this, but I couldn't find any yet.

In your case, the issue is that arguments enclosed in quotes are not being handled correctly.
Now let's verify this with a simple example:
```fish
function sudo_test
    printf 'sudo_test: %s\n' $argv
end

> sudo sudo_test a 'b c'
sudo_test: a
sudo_test: b
sudo_test: c
```

Here is my version of sudo with aliases:

```fish
function sudo
    if functions -q -- "$argv[1]"
        set -- argv -- fish -C "$(functions --no-details -- $argv[1])" -c '$argv' -- $argv
    end

    command sudo $argv
end
```

Let's check again:
```fish
function sudo_test
    printf 'sudo_test: %s\n' $argv
end

> sudo sudo_test a 'b c'
sudo_test: a
sudo_test: b c
```

Also, such an alias does not solve the issue of running sudo with additional arguments when the function is not the first argument. To solve this challenge would require parsing the arguments, as sudo does.

**Comment by diniamo** [comment] 2024-07-10 13:23
And another problem is nested aliases, damn.

**Comment by diniamo** [comment] 2024-07-10 13:59
Ladies and gentlemen, here is a snippet that fixes all the issues from above:
```fish
function sudo --wraps sudo
    for i in (seq 1 (count $argv))
        if command -q "$argv[$i]" 2&>1
            command sudo $argv
            break
        else if functions -q $argv[$i] 2&>1
            if test $i != 1
              set -l sudo_args $argv[..(math $i - 1)]
            end
            command sudo $sudo_args -E fish -C "source $(functions (functions | string split ', ') | psub)" -c '$argv' -- $argv[$i..]

            break
        end
    end
end
```
Not sure about performance concerns, but it should be fine since functions are loaded lazily, and `/tmp` - on most computers - exists in memory.

**Comment by repsac-by** [comment] 2024-07-11 09:05
This is my function that skips the sudo arguments and checks the actual command against the alias function substitution.

```fish
function sudo
    set sudo_args_with_value (LANG=C command sudo --help | string match -gr '^\s*(-\w)*,\s*(--[\w-]*)=')
    set sudo_args

    while set -q argv[1]
        switch "$argv[1]"
            case '--'
                set -a sudo_args $argv[1]
                set -e argv[1]
                break
            case $sudo_args_with_value
                set -a sudo_args $argv[1]
                set -e argv[1]
            case '-*'
            case '*'
                break
        end
        set -a sudo_args $argv[1]
        set -e argv[1]
    end

    if functions -q -- $argv[1]
        set -- argv fish -C "$(functions --no-details -- $argv[1])" -c '$argv' -- $argv
    end

    command sudo $sudo_args $argv
end
```

At this point, passing all functions for the purpose of dependency handling seems like overkill to me.

**Comment by AtifChy** [comment] 2024-07-15 16:23
at this rate make a plugin

**Comment by diniamo** [comment] 2024-07-15 16:45
Possible, but it would just have the function I sent.

**Comment by kipavy** [comment] 2025-10-25 12:31
> I was wondering if there's an equivalent to `alias sudo='sudo '` which allows `sudo x` to use an alias for `x`. The reason why something like `sudo -s` wouldn't work is that the alias changes `sudo apt-get` to `sudo apt` for any relevant subcommand which can be useful when copying examples.
> 
> I'm using fish 3.1.2 and tried `alias sudo 'sudo '` but had no success.

Simple solution that works for me:

```bash
echo '
function sudo
    if functions -q $argv[1]
        set cmd "command sudo fish -c \"$argv\""
        eval $cmd
    else
        command sudo $argv
    end
end
' > ~/.config/fish/functions/sudo.fish
```
