### ISSUE TITLE
Tab completion doesn't work with an `; and`

### ISSUE THREAD

**Issue by danielcompton** [fish-shell/fish-shell#2705] opened 2016-02-03 01:04 UTC
I get completion for homebrew if I run 

```
$ brew up<TAB>
update  (Fetch newest version of Homebrew and formulas)
upgrade                        (Upgrade outdated brews)
```

but it doesn't work if I type

``` sh
$ echo ""; and brew up<TAB>
```

**Comment by bucaran** [comment] 2016-02-03 01:07
I was able to reproduced this not only with `brew`, but other commands including my own.

**Comment by krader1961** [comment] 2016-02-03 01:34
That's not surprising given that compound statements aren't actually parsed as such (causing completion context to change) until [enter] is pressed. Although in this case you don't even need the compound statement (i.e., the semicolon). Just type `and brew up<TAB>`.  The `and` command doesn't have any meaningful completions.

**Comment by krader1961** [comment] 2016-02-03 01:36
The fish completion system has limited context awareness. It's not as smart as the completion subsystems provided by a typical IDE like Eclipse. Patches to improve it are welcomed.

**Comment by bucaran** [comment] 2016-02-03 01:52
That explains why creating completions for **sub commands**, for example `git init` or `git commit`, is tricky, and what you actually end up doing is simply creating completions for `git` when there is a sub command present or not.

**Comment by ridiculousfish** [comment] 2016-02-03 01:58
#478 provides real subcommand support, I just need to beat it into better shape.

**Comment by krader1961** [comment] 2016-03-25 02:50
@faho and @ridiculousfish: Will "real subcommand support" address this issue? I don't see how it would.  Are we going to create a completion for `and` and `or` that supports completing any command that follows? It would be really cool if it did but that seems like a really bad way to expend our limited development resources given all the other issues such as `psub` not actually working very well or piping into or out of functions causing unexpected behavior due to the buffering.

**Comment by faho** [comment] 2016-03-25 14:10
This is caused by the [__fish_brew_needs_command](https://github.com/fish-shell/fish-shell/blob/master/share/completions/brew.fish#L1-L7) function (and similar for other completions).

It checks if `commandline -opc`, i.e. the current "process" has one token only, under the assumption that that one token is going to be "brew".

However if it is called with `and brew`, it will be two tokens.

Check it with e.g. `systemctl` (we currently complete even if you don't have a command installed), which uses a different approach.

-----

@krader1961: The problem is that parsing whether we need a command is quite difficult to do in the current completion system because we can't just check for bare words (at least theoretically, currently it's the best approach we have without blowing every script up massively, see #2462 for an attempt with the current system). What we need is a system that remembers whether a given token is an argument to a flag or can be a subcommand, and that also looks at ordering more for commands that need it.

 For example: 

`git -C log`

This still needs a command despite having a token that looks like one, and the "-C" option can't come after a command (i.e. `git log -C log` is invalid).

**Comment by faho** [comment] 2016-04-30 14:43
The currently affected completions are:

brew
bundle
cabal
canto
composer
fossil
heroku
lein
lunchy
mix
netctl
npm
opam
rbenv
ruby-build
tmuxinator
travis
vagrant

Adding this to easy-picks.

**Comment by faho** [comment] 2016-05-19 11:39
It seems there's an underlying cause to this that makes it work with e.g `sudo` but not with `and` - we seem to have completions in the c++ code for our logical operators, so we don't actually call our `__fish_complete_subcommand` function - which would (correctly, IMHO) remove the first command from the commandline.

@ridiculousfish: Do you know where that completion is? I can't find it and it's rather hard to grep.

**Comment by ridiculousfish** [comment] 2016-05-19 20:25
fish is calling out to the git completion. I think where we go wrong is in `__fish_git_needs_command`:

        set -l skip_next 1
        # Skip first word because it's "git" or a wrapper
        for c in $cmd[2..-1]

here `$cmd` is `and git`, so it skips over `and` and then thinks the git command is `git`.

Maybe `commandline -p` should remove decorations like `command`, `and`, etc. What do you think?

**Comment by faho** [comment] 2016-05-19 23:39
Umh... it already should. The `and` completions include `__fish_complete_subcommand`, which should strip that (via `complete -C`). Only, after the command has been completed, it's not called anymore. For `sudo` and e.g. `env`, this works (though env _adds_ the subcommand completions to its own).

That's what I meant - it appears we're calling some other completions here, not the scripted ones.

**Comment by ridiculousfish** [comment] 2016-05-20 20:16
Oh I see - the C++ calls the `git` completion, but you expect to have the `and` completion called, which will trampoline to the `git` completion. Makes perfect sense.

**Comment by ridiculousfish** [comment] 2016-05-20 20:17
Assigning to me

**Comment by krader1961** [comment] 2017-07-21 06:22
I'm going to close this because people do not type a sequence of characters similar to those in the original comment except to prove a point. Fish is meant to be a friendly shell. Not a shell that behaves in whatever demented manner the user wants. There are several hundred issues that deserve to be addressed. This is not one of them.

**Comment by faho** [comment] 2017-07-21 15:20
@krader1961: That "sequence of characters" is just an example. Any command used with "and", "or" or "not" has this issue.

I'm reopening this.

**Closed** 2019-11-04 15:44 UTC
Labels: bug, completions
