### ISSUE TITLE
It doesn't fire fish_prompt nor fish_postexec on <c-c>

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#3273] opened 2016-07-28 11:53 UTC
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1
**OS/terminal used**: 
ITerm on El Capitan

Talk about the the issue here. 

## Reproduction steps
Launch fish and run these commands:
```
function test --on-event fish_prompt
  echo 1
end
function test2 --on-event fish_postexec
  echo 2
end
sleep 10 # press <c-c> before it finishes
```
It doesn't echo 1 nor 2. None of these events got triggered.

## Expected results
1
2

## Actual results
Nothing

**Comment by faho** [comment] 2016-07-28 14:09
This is a duplicate of #2356.

**Closed by faho** 2016-07-28 14:09 UTC

**Comment by sassanh** [comment] 2016-07-29 01:36
Thanks
