### ISSUE TITLE
run set_color normal after fish_prompt

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7594] opened 2020-12-31 16:48 UTC
Recently had a user submit a bug report where my prompt was leaking its colors into what a user copy-pasted into the terminal: https://github.com/IlanCosman/tide/issues/64. I believe what caused this is that the user's `fish_color_command` was simply `--bold`, letting the `white` be assumed. This is partially user error and partially my error for not running `set_color normal` at the end of my prompt. 

However, I can't really imagine a situation in which someone would want their prompt to effect the color of the commands they type/copy-in. Thus, I believe that Fish should take on the responsibility of running `set_color normal` after `fish_prompt`.

**Comment by krobelus** [comment] 2020-12-31 17:38
Duplicate of #6563

**Closed by krobelus** 2020-12-31 17:38 UTC

**Comment by krobelus** [comment] 2020-12-31 17:40
A downside to always resetting colors is that `script(1)`'s output will be more noisy.
