### ISSUE TITLE
For non-interactive single-command runs do `exec`  (when possible?)

### ISSUE THREAD

**Issue by kolayne** [fish-shell/fish-shell#9788] opened 2023-05-13 19:43 UTC
I am running `fish, version 3.6.1` on the system `Linux KoLin 6.3.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Wed, 10 May 2023 08:54:47 +0000 x86_64 GNU/Linux`.

My command launcher (`dmenu`) uses my default shell (which `fish` has recently become) to run commands. What I previously liked about bash was that when given a simple command (without pipelines or conjunction operators) in the non-interactive mode, bash would `exec` that command instead of forking and creating an additional process. In a system where a lot of processes are started via a command launcher, it affects the number of processes significantly.

Here's the described behavior:
```fish
nikolay@KoLin ~> bash -c "/usr/bin/sleep 10 && true" &  # Running a complex command
nikolay@KoLin ~> pstree $fish_pid  # Bash is there
fish─┬─bash───sleep
     ├─pstree
     └─2*[{fish}]
nikolay@KoLin ~> wait

fish: Job 1, 'bash -c "/usr/bin/sleep 10 && t…' has ended
nikolay@KoLin ~> bash -c "/usr/bin/sleep 10" &  # Running a simple command
nikolay@KoLin ~> pstree $fish_pid  # Bash has disappeared!
fish─┬─pstree
     ├─sleep
     └─2*[{fish}]
nikolay@KoLin ~> wait

fish: Job 1, 'bash -c "/usr/bin/sleep 10" &' has ended
nikolay@KoLin ~> fish -c "/usr/bin/sleep 10" &  # Running a simple command with fish
nikolay@KoLin ~> pstree $fish_pid  # Fish is there
fish─┬─fish───sleep
     ├─pstree
     └─2*[{fish}]
nikolay@KoLin ~> wait

fish: Job 1, 'fish -c "/usr/bin/sleep 10" &' has ended
nikolay@KoLin ~> 
```
Notice that in the second run, unlike the other two, the shell has replaced itself with `sleep`.

It would be nice to have this feature in fish! I have noticed that, for some reason, bash treats commands with output redirection (e.g. `bash -c "/usr/bin/sleep > /dev/null"`) as complex ones. I think it would be ideal if fish treated these kinds of commands as simple too, but even running the simplest commands (consisting of just an executable and its arguments) with self-replacement would already have a notable benefit.

**Comment by kolayne** [comment] 2023-05-13 19:48
And I want to add that I see that this is some sort of magic behavior taking place in some special case and, what's worst, implicitly. But this could very well be a non-default configurable behavior, which one can enable with an explicit command in their `config.fish`

**Comment by faho** [comment] 2023-05-13 19:53
Duplicate of #6902

**Closed by faho** 2023-05-13 19:53 UTC

**Comment by faho** [comment] 2023-05-13 19:55
This is unlikely to happen - it's weird implicit behavior and rarely matters.

Even in your case, your argumentation is about "number of processes", which I doubt makes a measurable difference.

>But this could very well be a non-default configurable behavior, which one can enable with an explicit command in their config.fish

We don't do configuration like that.

Sorry, that's a no.
