### ISSUE TITLE
Prevent overriding of `test` (or all builtins?)

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4742] opened 2018-02-21 01:02 UTC
While filing #4741 I ran into a nasty case where I broke `test` and my system went haywire and almost overwrote critical data, as both the default fish prompt and the completions for virtually all system commands end up invoking `test` which wound up calling my function, most infelicitously also named `test`.

I think we either need a policy to only ever use `builtin builtin_name` instead of `builtin_name` directly for all of our scripts or else forbid overriding them with a similarly named function (or at least for something as innocuous-sounding as `test`, but that feels like just a bandaid).

**Comment by zanchey** [comment] 2018-02-21 01:35
Duplicate of #3000 - we tried a new `--shadow-builtin` option but it produced some pretty undesirable compatibility behaviour.

**Closed by zanchey** 2018-02-21 01:35 UTC

**Comment by mqudsi** [comment] 2018-02-21 16:29
Thanks, @zanchey
