### ISSUE TITLE
Fish throws syntax errors for valid commands

### ISSUE THREAD

**Issue by Geweldig** [fish-shell/fish-shell#7610] opened 2021-01-05 14:44 UTC
| command | output |
|----|----|
| `fish --version` | `fish, version 3.1.2` |
| `echo $version` | `3.1.2` |
| `uname -a` | `Linux computer 5.10.4-arch2-1 #1 SMP PREEMPT Fri, 01 Jan 2021 05:29:53 +0000 x86_64 GNU/Linux` |
| `sh -c 'env HOME=$(mktemp -d) fish'` | Tested, same behaviour |

When running `/usr/bin/[ --help` fish displays the error:
```
[~] > /usr/bin/[ --help
fish: Unexpected end of string, square brackets do not match
```

Running the command in bash returns the expected output:
```
$ /usr/bin/[ --help
Usage: test EXPRESSION
  or:  test
  or:  [ EXPRESSION ]
  or:  [ ]
  or:  [ OPTION
Exit with the status determined by EXPRESSION.
<truncated>
```

I do not actually believe this is a serious problem that any sane person will ever encounter, but I do believe it is a bug nonetheless.

**Comment by faho** [comment] 2021-01-05 14:53
Duplicate of #2485

**Comment by Geweldig** [comment] 2021-01-05 14:54
Ah sorry about that, I tried searching for a previous issue but couldn't find one!

**Closed by faho** 2021-01-05 14:53 UTC

**Comment by faho** [comment] 2021-01-05 14:55
What happens is that fish doesn't end up running the command because it interprets the `[` as the beginning of a `var[1..5]` slice.

The solution is to escape the `[` (or ideally not use `[` in the first place - use `test` or something else)

>Ah sorry about that, I tried searching for a previous issue but couldn't find one!

Yeah, github's issue search is awful.

**Comment by Geweldig** [comment] 2021-01-05 14:57
> The solution is to escape the [ (or ideally not use [ in the first place - use test or something else)

Yes I agree the scenario is pretty ridiculous, but I figured it should be mentioned anyhow.
