### ISSUE TITLE
Fish Beta Version: Missing Asset Files Warning on Startup Despite Installation

### ISSUE THREAD

**Issue by MrAru** [fish-shell/fish-shell#10916] opened 2024-12-18 13:58 UTC
Hi developers, I'm thrilling with the beta version of fish release and I immediately tried it today.  I download the static build from github release (https://github.com/fish-shell/fish-shell/releases/download/4.0b1/fish-static-linux-x86_64.tar.xz), decompress the tar file and move `fish*` executable files into `~/.local/bin`.

When I switch to the beta version of fish, the fish shell keeps displaying the following message during startup (sorry for the extensive redaction, as my use case is on a company server).

```
PS C:\Users\...> ssh ...@xxx.xx.xx.xx
Warning: Permanently added 'xxx' (ECDSA) to the list of known hosts.
Last login: Wed Dec 18 13:38:24 2024 from xxx

... in ~                                                                                                                                                                                               at 21:51:53
❯ echo $SHELL
/bin/bash

... in ~                                                                                                                                                                                               at 21:51:58
❯ which fish
~/.local/bin/fish

... in ~                                                                                                                                                                                               at 21:52:02
❯ fish
warning: Fish's asset files are missing. Trying to install them.
Can't find $HOME
error: Fish cannot find its asset files in '/mnt/lustre/home/.../.local/share/fish'.
Refusing to read configuration because of this.
error: If you installed via `cargo install`, please run `fish --install` and restart fish.
```

This prompt appears every time I start a new shell. I also tried `fish --install` but nothing changed. Strangely, whether in bash or fish, `echo $HOME` always works, and it returns my home path on lustre:

```
> echo $HOME
/mnt/lustre/home/...
```

Could you suggest any directions for troubleshooting? Thank you very much. My environment is as follows:

```
> fish --version
fish, version 4.0b1-4-g687001f8b
> echo $version
4.0b1-4-g687001f8b

> uname -a
Linux ... 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> echo $TERM
xterm-256color
```

Btw, when I run `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'`, the same prompt shows again so I cannot provide this info.

**Comment by faho** [comment] 2024-12-18 14:07
The error is this:

> Can't find $HOME

It can't find your user's home directory. That means `getpwuid_r` errors or does not return a home directory. This is quite possibly down to more involved user configuration on your company server.

Unlike what the message says, this doesn't check the $HOME variable, on purpose - it is usually wrong when running e.g. via `sudo`, and we don't want to override files in your user's home dir with root-owned ones.

**Comment by MrAru** [comment] 2024-12-18 14:12
Hi @faho , thank you for your explanation! I do understand that in a company server environment, where there may be many unusual configurations, this cautious approach is beneficial by default. So, is there an environment variable, or another 'escape hatch' method, that would allow users who clearly know what they're doing to complete this installation step? Thanks!

**Comment by faho** [comment] 2024-12-18 14:18
> So, is there an environment variable, or another 'escape hatch' method

There currently is not.

I'm *thinking* of falling back on $HOME if this fails, but of course that would mean if you `sudo`'d on that machine it would overwrite files in your $HOME.

I assume $HOME is set for you?

**Comment by MrAru** [comment] 2024-12-18 14:19
> I assume $HOME is set for you?

YES, `echo $HOME` correctly return my home path.

**Comment by faho** [comment] 2024-12-18 16:25
Okay, I have an idea for what to do here.

I am really wary of using $HOME for this, so since we wanted to make it possible to change the install location anyway, in 4b1d8ae you can pass a path to `fish --install`, like `fish --install=$HOME/.local/` (yes, `$HOME`, `~/` will not work). This will install fish into a "relocatable tree", meaning the data files will go into .local/share/fish, and it will copy the binary (if necessary) to .local/bin/fish and tell you to reexecute it.

If you run it, it will figure out where the files are, so there's no need to tell it specifically.

The main weirdness here is that it will interpret the "sysconf" dir to be path/etc, e.g. ~/.local/etc/fish, not the main /etc/fish in the root of the filesystem. That's something I never quite got and also the cause of #10748.

I have also generated some builds at https://github.com/faho/fish-shell/actions/runs/12397052316.

Note that **THESE ARE LIGHTLY TESTED. I WILL NOT BE HELD RESPONSIBLE IF YOU BREAK YOUR COMPANY SERVER. TRY AT YOUR OWN RISK**.

**Comment by MrAru** [comment] 2024-12-19 13:46
Hi fabo, thanks for your quick fix. I've tried the build from https://github.com/faho/fish-shell/actions/runs/12400628574 today with `fish --install=<my home path>/.local` and it really works well. I'll close this issue as completed, thanks!

**Comment by faho** [comment] 2024-12-19 13:47
I'll close it once it's merged

**Closed** 2024-12-22 17:16 UTC

**Comment by janos-r** [comment] 2025-04-16 22:40
I also tried to install the latest fish binary on a company server where I don't have sudo access. So ran fish from ~/bin and it successfully installed itself by loading its files into ~/.local/share/fish. But still, every time I log in, even though everything seems to work well, I get on every start of fish:
```
error: Cannot find home directory and will refuse to read configuration.
 Consider installing into a directory tree with `fish --install=PATH`.
```

**Comment by faho** [comment] 2025-04-17 05:41
@janos-r That should be gone with #11143.
