### ISSUE TITLE
Disable scope shadowing for fish's wrapper functions?

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#5175] opened 2018-09-07 16:49 UTC
This doesn't work:
```
set -lx MANPAGER more
man ls
```
But this does:
```
set -lx MANPAGER more
command man ls
```
So I was wondering if it might be a good idea to disable scope shadowing for fish's wrappers for standard command line utilities like man, grep, ls etc.

**Comment by faho** [comment] 2018-09-07 17:16
This is a duplicate of #1091.

The problem is that exported variables aren't "exported" to functions. When they are global (or universal), that doesn't matter, but with "-lx", this happens. #4149 copies the variables by creating new locals with the value.

So it doesn't matter anymore whether your `man` is a function or not, it'll have $MANPAGER defined.

**Closed by faho** 2018-09-07 17:16 UTC
