### ISSUE TITLE
fish man pages have misformatted names

### ISSUE THREAD

**Issue by akalin** [fish-shell/fish-shell#4640] opened 2018-01-04 14:45 UTC
version info:
```
> fish --version
fish, version 2.7.1
> echo $version
2.7.1
> uname -a
Darwin Freds-MBP 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
> echo $TERM
screen
```

fish is install via homebrew.

`man fish` shows:

```
NAME
       fishfish - the friendly interactive shell
```

and e.g. `man fishindent` shows:

```
NAME
       fish_indentfish_indent - indenter and prettifier
```

So the name of the command is weirdly doubled. Not sure if this is a homebrew-only problem, but I took a look at the formula and it seems pretty standard.

**Comment by faho** [comment] 2018-01-04 15:43
Duplicate of #4628, #4016. It's fixed on master.

**Closed by faho** 2018-01-04 15:43 UTC
