### ISSUE TITLE
Autocomplete/History suggestion key map suggestion.

### ISSUE THREAD

**Issue by eGNUph** [fish-shell/fish-shell#4990] opened 2018-05-17 04:29 UTC
Select next option only of autocomplete/history should be Ctrl-F/ Select all options suggested, Alt-F, for obvious emacs related reasons.

Kind regards,

Phillip
phill@gnu.org

**Comment by faho** [comment] 2018-05-17 09:38
ctrl-f currently does "forward-char", while alt-f is "forward-word", which is precisely what emacs does (the functions are actually called the same!).

Only forward-char is hardcoded to accept _all_ of the suggestion if it moves over any of it, because accepting just one character (which it would otherwise do) is not really all that useful.

Changing this, or at least allowing configuration has been requested in #4984, so I'm closing this as a duplicate of it.

**Closed by faho** 2018-05-17 09:38 UTC

**Comment by eGNUph** [comment] 2018-05-18 14:35
On Thu, 2018-05-17 at 02:38 -0700, Fabian Homborg wrote:
> ctrl-f currently does "forward-char", while alt-f is "forward-word",
> which is precisely what emacs does (the functions are actually called
> the same!).
> 
> Only forward-char is hardcoded to accept all of the suggestion if it
> moves over any of it, because accepting just one character (which it
> would otherwise do) is not really all that useful.
> 
> Changing this, or at least allowing configuration has been requested
> in #4984, so I'm closing this as a duplicate of it.

But, to be like Emacs, when selecting options, cntl-f should only
select one option of those listed. Alt-f should select them all.
Phill
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/fish-
> shell/fish-shell","title":"fish-shell/fish-shell","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/fish-shell/fish-
> shell"}},"updates":{"snippets":[{"icon":"PERSON","message":"@faho in
> #4990: ctrl-f currently does \"forward-char\", while alt-f is
> \"forward-word\", which is precisely what emacs does (the functions
> are actually called the same!).\r\n\r\nOnly forward-char is hardcoded
> to accept _all_ of the suggestion if it moves over any of it, because
> accepting just one character (which it would otherwise do) is not
> really all that useful.\r\n\r\nChanging this, or at least allowing
> configuration has been requested in #4984, so I'm closing this as a
> duplicate of it."}],"action":{"name":"View Issue","url":"https://gith
> ub.com/fish-shell/fish-shell/issues/4990#issuecomment-389807526"}}}
> {"@type":"MessageCard","@context":"http://schema.org/extensions","hid
> eOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-
> a9160fc62647","title":"Re: [fish-shell/fish-shell]
> Autocomplete/History suggestion key map suggestion.
> (#4990)","sections":[{"text":"","activityTitle":"**Fabian
> Homborg**","activityImage":"https://avatars1.githubusercontent.com/u/
> 5185367?s=160\u0026v=4","activitySubtitle":"@faho","facts":[]}],"pote
> ntialAction":[{"name":"Add a
> comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"
> TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name
> ":"Comment","@type":"HttpPOST","target":"https://api.github.com","bod
> y":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"fish-
> shell/fish-
> shell\",\"issueId\":4990,\"IssueComment\":\"{{IssueComment.value}}\"}
> "}]},{"targets":[{"os":"default","uri":"https://github.com/fish-
> shell/fish-shell/issues/4990#issuecomment-
> 389807526"}],"@type":"OpenUri","name":"View on
> GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://a
> pi.github.com","body":"{\"commandName\":\"MuteNotification\",\"thread
> Id\":336171977}"}],"themeColor":"26292E"}
