### ISSUE TITLE
The builtin fish echo can't echo -h

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2744] opened 2016-02-19 15:48 UTC
When I run any other echo, for example GNU echo, it outputs "-h", however the fish one outputs nothing.

**Comment by faho** [comment] 2016-02-19 16:03
The fish one _should_ output the help for echo if it's the only argument (though IIRC this was supposed to be only if it's entered interactively).

**Comment by onodera-punpun** [comment] 2016-02-19 16:14
https://punpun.xyz/d79b.png

Doesn't output anything for me...

**Comment by faho** [comment] 2016-02-19 16:18
Did you have doxygen installed when you built fish?

**Comment by onodera-punpun** [comment] 2016-02-19 16:20
Yes.

**Comment by faho** [comment] 2016-02-19 16:26
Does `__fish_print_help echo` print the help?

**Comment by onodera-punpun** [comment] 2016-02-19 16:32
nope, it prints nothing, however the `__fish_print_help echo` command does exist.

I had doxygen installed at compile time, is there any way I can check the compile time options fish has been build with?

**Comment by faho** [comment] 2016-02-19 16:34
Currently not, no. I assume `$__fish_datadir/man/man1/echo.1` doesn't exist?

**Comment by onodera-punpun** [comment] 2016-02-19 16:37
It actually does exist, all the mans are in .gz format.

This is the build script used to build fish: https://github.com/6c37/crux-ports-git/blob/3.2/fish/Pkgfile
This is the footprint of the package: https://github.com/6c37/crux-ports-git/blob/3.2/fish/.footprint#L661-L736

**Comment by faho** [comment] 2016-02-19 17:42
>It actually does exist, though all the mans are in .gz format.

In that case, your build system is probably zipping it up, which means __fish_print_help isn't prepared to deal with it (even if the filename's correct and it's not "echo.1.gz") since `nroff` doesn't handle it. Mine prints crap ("MQkÂ0ßó+¾ª") and some empty lines. Yours might just print empty lines. Stop the build system from doing that - it's 344K in uncompressed form.

**Comment by onodera-punpun** [comment] 2016-02-19 20:59
A very nice person on the CRUX irc channel created a patch that makes it possible for __fish_print_help to read tarred man files, it's also easily extensible for other formats: http://pastebin.com/raw/pyHtk7pJ

**Comment by onodera-punpun** [comment] 2016-02-19 21:01
Anyways this still doesn't fix my issue, is it possible to print `-h` in any way? I also noticed it's impossible to print `-s` and `-e`.

**Comment by ridiculousfish** [comment] 2016-02-19 21:05
Bash has the [same class of issues](http://stackoverflow.com/questions/320313/echo-e-doesnt-print-anything). You can fall back to printf: `printf "%s" -e`

**Comment by krader1961** [comment] 2016-02-19 21:43
@ridiculousfish: Shouldn't the builtin echo honor the `--` switch to signal the end of options? That is, shouldn't `echo -- -h` work (at the moment it echoes both args)?

**Comment by ridiculousfish** [comment] 2016-02-19 21:54
You'd think, but...see #1013

**Comment by krader1961** [comment] 2016-03-23 03:01
> Anyways this still doesn't fix my issue, is it possible to print -h in any way?

Yes, `printf '%s\n' -h`. But since the core issue is a duplicate of issue #1013 I'm going to close this.

**Closed by krader1961** 2016-03-23 03:01 UTC
Labels: duplicate, posix-me-harder
