### ISSUE TITLE
auto show candidates without press TAB

### ISSUE THREAD

**Issue by wuyudi** [fish-shell/fish-shell#9115] opened 2022-08-06 05:44 UTC
```bash
fish --version
fish, version 3.5.1-173-g095c093af

echo $version
3.5.1-173-g095c093af

uname -a
Linux archlinux 5.18.15-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Jul 2022 22:52:41 +0000 x86_64 GNU/Linux

echo $TERM
tmux-256color
```

I wonder if fish can auto show a drop-down menu.

for example:

```bash
ls d <TAB>
data/  deep_learning_from_scratch/  device.json  downloads/
```

can these candidates show automatically without pressing TAB? (just like in editor.)

**Comment by faho** [comment] 2022-08-06 06:07
Showing a menu without pressing TAB involves a lot of cursor movement all the time and is quite disruptive, also completions are performance-sensitive and we have no way of guaranteeing they complete within a sensible-enough time to not delay typing meaningfully.

I don't believe this is feasible or that we want to do it. Sorry.

**Comment by krobelus** [comment] 2022-08-06 06:34
> Showing a menu without pressing TAB involves a lot of cursor movement all the time and is quite disruptive, also completions are performance-sensitive and we have no way of guaranteeing they complete within a sensible-enough time to not delay typing meaningfully.

Those are technical problems that we can solve eventually.

The exception is the "disruptive" part but I think it's not too bad. They should behave like autosuggestions, i.e. do nothing if the user keeps typing (and avoid evaluating command substitutions to  avoid delays).

Here's what it looks like in the [Kakoune](http://kakoune.org/) editor

![image](https://user-images.githubusercontent.com/6853872/183237282-c883daac-70b1-4faa-aa80-977afc6391cb.png)

**Comment by wuyudi** [comment] 2022-08-06 15:12
I found that https://fig.io/ has a similar function. But only mac.

![image](https://camo.githubusercontent.com/74884a83c88c19b27b1a451b7e618fe773c6a48f6cb209a02d3fe70381a4f9d9/68747470733a2f2f6669672e696f2f676966732f64656d6f2d776974682d6865616465722e676966)

**Comment by faho** [comment] 2022-08-08 19:05
Can I be honest? I don't like those.

Call me an old fart but those displays are too much for me. And we have completion *scripts*, that can run *arbitrary* computations. There's no good way to do that, unless we solved #23. And you see how that's issue *number twenty-three*? I do not believe it sensible to leave this issue open.

(wuyudi: sorry I hid your comment because the GIANT GIF was bothering me. I wish github had a reduced motion mode (or browsers didn't hobble their autoplay settings))

**Comment by floam** [comment] 2022-08-14 01:40
I unhid his comment and made it a thumbnail.

**Comment by kidonng** [comment] 2022-09-06 10:47
I'm in favor of this idea. Netscape Navigator 4.0 is considered a rival on https://fishshell.com/, and browsers these day typically show a completion menu along with autosuggestions.

For the sake of studying, I tried a [zsh plugin](https://github.com/marlonrichert/zsh-autocomplete) that adds this feature and noticed a couple of issues:

- "zsh: do you wish to see all 00 possibilities (00 lines)?" may be triggered unexpectedly while typing. Fish does not ask this kind of stuff though.

- As @faho said:

  > no way of guaranteeing they complete within a sensible-enough time to not delay typing meaningfully.

- When the cursor is near the bottom of the terminal, high completion will force the scrollback (and the cursor) to move up

<details>
<summary>Video demo</summary>

https://user-images.githubusercontent.com/44045911/188615656-aaaf6be9-3acc-42ac-a96f-1d305aadf28b.mov

</details>

Fish already has a decent pager so things are already half-done, if these pitfalls can be avoided I think it could make another compelling feature.

**Comment by faho** [comment] 2023-05-17 19:57
Duplicate of #3567

**Closed by faho** 2023-05-17 19:57 UTC
Labels: enhancement
