### ISSUE TITLE
Problems with Starship Prompt & Kitty

### ISSUE THREAD

**Issue by basbebe** [fish-shell/fish-shell#7087] opened 2020-06-06 16:51 UTC
I'm on Mac OS 10.15.5, fish 3.1.2, [kitty Terminal](https://github.com/kovidgoyal/kitty) 0.17.4, [Starship Prompt](https://github.com/starship/starship) 0.41.3

If I have entered text into my prompt line and do one of the following, a new prompt line is being emitted:
- press escape (vim normal mode)
- cancel the command (CTRL + C)
- paste something using a kitten

<img width="724" alt="83947800-96732a00-a819-11ea-9195-4d4ab51c07fe" src="https://user-images.githubusercontent.com/7083188/83949857-6e3df800-a826-11ea-9389-f05a314facec.png">

I already created issues with Starship https://github.com/starship/starship/issues/1271 and kitty https://github.com/kovidgoyal/kitty/issues/2743 but I'm not sure what is creating the issue.

**Comment by faho** [comment] 2020-06-06 17:26
So, what happens when you press escape is that fish switches the mode and then tries to repaint the mode prompt. In starship I believe that doesn't exist, so it repaints the entire prompt, which involves re-running the `fish_prompt` function, and then putting that output over the existing output.

In your case, that last bit fails somehow, and I have no idea why. I can't reproduce it.

**Comment by basbebe** [comment] 2020-06-06 18:24
thanks for the support @faho 
The problem persists when I run fish with a temporary home directory.

`kitty @ launch sh -c 'env HOME=$(mktemp -d) fish'`


<img width="845" alt="Bildschirmfoto 2020-06-06 um 20 22 42" src="https://user-images.githubusercontent.com/7083188/83951674-7e100900-a833-11ea-8985-8cc01df2d14c.png">

My locale:
```
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
```

My config.fish: https://github.com/basbebe/.dotfiles/blob/master/.config/fish/config.fish
kitty.conf: https://github.com/basbebe/.dotfiles/blob/master/.config/kitty/kitty.conf
starship.toml: https://github.com/basbebe/.dotfiles/blob/master/.config/starship.toml

I'm not aware of any other special config / setting.
tmux is not in use in this case.

**Comment by basbebe** [comment] 2020-06-07 15:32
if I start ZSH the problem does _not_ persist.

**Comment by faho** [comment] 2020-06-28 11:40
Sorry, I can't reproduce this, so I'm closing it.

If anyone figures out reproduction steps I'd be happy to take a look.

**Closed by faho** 2020-06-28 11:40 UTC
Labels: needs more info
