### ISSUE TITLE
commandline -f repaint breaks on multiline prompt

### ISSUE THREAD

**Issue by nunzioc** [fish-shell/fish-shell#5860] opened 2019-05-04 12:26 UTC
I'm using fish, version 3.0.2 on fedora 30 with gnome terminal.

I'm binding a command that changes the pwd. A simplified version is this:

function '__tmp_cd'
  cd -
  commandline -f repaint
end
bind \cc '__tmp_cd'

When using a multiline prompt (I'm using terlar), characters from the old prompt are visible after running the command when the new prompt is shorter than the old one.

**Comment by faho** [comment] 2019-05-05 11:38
Duplicate of #5033

**Comment by bruce-hill** [comment] 2019-06-10 21:01
I believe this issue is not a duplicate of #5033 despite the similar bug titles. When redrawing a multi-line prompt in this fashion, fish is positioning the prompt correctly, but failing to fully erase the old prompt. A simple fix is to put `\033[J` (the escape sequence for "clear to bottom of screen") at the beginning of your prompt, but I think fish should do that clearing automatically, because the current behavior of `commandline -f repaint` is very counterintuitive.

My steps to reproduce:

    function fish_prompt; printf "["(pwd)"]\n> "; end
    bind \cB 'cd ..; commandline -f repaint'
    cd /usr/local

Then hit Ctrl-b. The prompt will now display

    [/usr]local]
    >

instead of

    [/usr]
    >

A fixed version of the same prompt that has no issues: `function fish_prompt; printf "\033[J["(pwd)"]\n> "; end`

**Comment by zanchey** [comment] 2019-06-14 14:24
Yes, I agree.

**Comment by rouge8** [comment] 2020-12-18 05:09
This appears to be fixed as of 75dcbed700881c10c216665196ba0288061c09fa 🎉

**Comment by zanchey** [comment] 2020-12-27 14:59
Yep. This is actually a duplicate of #3550, I think!

**Closed by zanchey** 2020-12-27 14:59 UTC
Labels: bug
