### ISSUE TITLE
Bracketed paste mode causes fish to hang on WSL if started as PID=2

### ISSUE THREAD

**Issue by sarum9in** [fish-shell/fish-shell#4582] opened 2017-12-10 04:20 UTC
## Environment
$ fish --version
fish, version 2.7.0
$ uname -a
// Note: this is [WSL Ubuntu](https://docs.microsoft.com/en-us/windows/wsl/reference)
Linux XXX 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
Tested on terminal emulators:
cmder.exe
cmd.exe

## strace output (this is infinite loop)
```
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1512877281
time(NULL)                              = 1512877281
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1512877281
time(NULL)                              = 1512877281
write(1, "\33[?2004l", 8)               = 8
```
## Issue
If fish is started with pid=2 on WSL it gets stuck inside `__fish_config_interactive`. Printf debugging suggests that stuckness happens on `if not type -q __fish_command_not_found_handler` line, inside `__fish_disable_bracketed_paste` handler. Commenting-out `printf` inside that handler mitigates the issue.

### Naive way in line how issue was noticed
1. From cmd.exe run bash
2. Verify that pid=2 via `echo $$`
3. From bash run `exec fish`
4. At this point fish hangs and terminal is unresponsive.
5. Start another terminal emulator and perform steps 1 and 2.
6. In 2nd terminal emulator you have working fish instance.
7. Run `pkill fish` to kill all running fish instances. Go to step 1 to reproduce again.

### Another way to reproduce proving that it is related to pid=2
1. From cmd.exe run `bash`
2. From another cmd.exe run `bash`
3. Run `echo $$` in both terminals
4. Run `exec fish` in a terminal where pid!=2, this starts fish just fine
5. Run `exec fish` in a terminal where pid==2, this instance hangs

4 and 5 can be reordered.

## Further actions
I am open to debug this further but I am not sure what to look for.

## Use case
This is useful if you want to run fish as your main shell in WSL. fish can replace bash on startup via ~/.bashrc. Bash normally starts as pid=2 so as I would expect any other default shell to:
![image](https://user-images.githubusercontent.com/1058248/33801875-258125ac-dd61-11e7-991a-39a75bc3d799.png)

## Possible mitigations
Make it possible to disable [bracketed paste mode](https://github.com/fish-shell/fish-shell/pull/3871#issuecomment-321034918). Currently this can be done by either overriding __fish_config_interactive or setting FISH_UNIT_TESTS_RUNNING.

**Comment by sarum9in** [comment] 2017-12-10 04:49
Attaching execution logs 
- `exec fish -d 5 &>log5.txt` [log5.txt](https://github.com/fish-shell/fish-shell/files/1545324/log.txt)
- `exec fish -d 4 &>log4.txt` [log4.txt](https://github.com/fish-shell/fish-shell/files/1545326/log4.txt)

This seems to be stuck in recursion:
```
<4> fish: Continue job 3, gid -2 (__fish_reload_key_bindings), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job 'not set -q FISH_UNIT_TESTS_RUNNING' with id 4
<3> fish: Skipping fork: no output for internal builtin 'set'
<3> fish: Set status of not set -q FISH_UNIT_TESTS_RUNNING to 1 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 4, gid -2 (not set -q FISH_UNIT_TESTS_RUNNING), COMPLETED, NON-INTERACTIVE
<3> fish: register: EVENT_GENERIC(fish_prompt): "__fish_enable_bracketed_paste"
<3> fish: register: EVENT_GENERIC(fish_preexec): "__fish_disable_bracketed_paste"
<3> fish: register: EVENT_EXIT(pid 2): "__fish_disable_bracketed_paste"
<4> fish: Exec job '__fish_enable_bracketed_paste' with id 5
<4> fish: Exec job 'printf "\e[?2004h"' with id 4
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004h<3> fish: Set status of printf "\e[?2004h" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 4, gid -2 (printf "\e[?2004h"), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 6
<4> fish: Exec job 'printf "\e[?2004l"' with id 7
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 7, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Continue job 6, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 4
<4> fish: Exec job 'printf "\e[?2004l"' with id 8
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 8, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Continue job 4, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 6
<4> fish: Exec job 'printf "\e[?2004l"' with id 9
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 9, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Continue job 6, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 7
<4> fish: Exec job 'printf "\e[?2004l"' with id 10
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 10, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Continue job 7, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 6
<4> fish: Exec job 'printf "\e[?2004l"' with id 11
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 11, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Continue job 6, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 9
<4> fish: Exec job 'printf "\e[?2004l"' with id 12
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Continue job 12, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Continue job 9, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 4
<4> fish: Exec job 'printf "\e[?2004l"' with id 13
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
```

**Comment by zanchey** [comment] 2017-12-10 12:06
@mqudsi is our resident expert here, I think.

**Comment by faho** [comment] 2017-12-10 19:35
This seems rather weird to me. Specifically, the bracketed paste disabler is triggered on _job_ exit!

> <4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 6

It's only defined to run on _process_ exit (when fish itself exits).

@sarum9in: Can you confirm that in your __fish_config_interactive.fish `__fish_disable_bracketed_paste` is defined as

```fish
        function __fish_disable_bracketed_paste --on-event fish_preexec --on-process-exit %self
            printf "\e[?2004l"
        end
```

specifically that it says "on-**process**-exit", not "on-job-exit"? Because in that case it would be triggered when the job with an id equal to fish's pid exits, which is very likely to happen if that pid is 2.

I'm afraid you'll have to look at the actual file for this.

**Comment by faho** [comment] 2017-12-10 19:59
Nope, we're definitely gonna need @mqudsi on this one. From proc.cpp:process_clean_after_marking():

```c++
proc_fire_event(L"JOB_EXIT", EVENT_EXIT, -j->pgid, 0);
```

It's firing the exit event (with description "JOB_EXIT") for the PGID of the job. We store PGIDs as negative PIDs. 

Now, together with the "gid -2" above, that means that process-exit event gets triggered whenever a job with a P**G**ID of 2 exits, which incidentally is our "sentinel" pgid for "new jobs" that haven't had their process group assigned yet. So it seems most likely (since this isn't triggered anywhere else, and seems specific to a PID of 2) that one of our code paths that is triggered on WSL does not set the process group.

**Comment by faho** [comment] 2017-12-10 20:01
And since @mqudsi's pgroup handling rework (#4349) only landed in master (not 2.7.0) you might like to try that.

@sarum9in: Can you try building fish from git master?

**Comment by sarum9in** [comment] 2017-12-11 19:44
@faho yes, this function is define like this, on-process-exit
```
        # Disable BP before every command because that might not support it.
        function __fish_disable_bracketed_paste --on-event fish_preexec --on-process-exit %self
            printf "\e[?2004l"
        end
```

@faho I am going to build fish from head and try the same tests I described in first message. Will write here as soon as I have results.

**Comment by sarum9in** [comment] 2017-12-12 01:47
## Build
Commit version: ba04c2af3db927deebb672a176d0c5de53311341
```
mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
make install DESTDIR=/tmp
mv /usr/share/fish /usr/share/fish.bak
mv /usr/bin/fish /usr/bin/fish.bak
mv /tmp/usr/share/fish /usr/share/fish
mv /tmp/usr/bin/fish /usr/bin/fish
```

## Tests
No user configuration (clean /home).

### Test 1

```
% bash
$ echo $$
2
exec fish
// stuck indefinitely
```
#### Log (-d 4)
[head-bad-log-4.txt](https://github.com/fish-shell/fish-shell/files/1549952/head-bad-log-4.txt)
```
[?2004h<3> fish: Set status of printf "\e[?2004h" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Start job 4, gid -2 (printf "\e[?2004h"), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 6
<4> fish: Exec job 'printf "\e[?2004l"' with id 7
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Start job 7, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Start job 6, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 4
<4> fish: Exec job 'printf "\e[?2004l"' with id 8
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
```

#### Log (-d 5)
[head-bad-log-5.txt](https://github.com/fish-shell/fish-shell/files/1549955/head-bad-log-5.txt)
```
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Start job 7, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Start job 6, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_job with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_decorated_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_plain_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_continuation with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_optional_background with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_terminate>
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 4
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_job with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_decorated_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_plain_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_continuation with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_optional_background with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_terminate>
<4> fish: Exec job 'printf "\e[?2004l"' with id 8
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
<3> fish: Job is constructed
<4> fish: Start job 8, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
<3> fish: Job is constructed
<4> fish: Start job 4, gid -2 (__fish_disable_bracketed_paste JOB_EXIT 2 0), COMPLETED, NON-INTERACTIVE
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_job with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_decorated_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_plain_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_continuation with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_optional_background with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_terminate>
<4> fish: Exec job '__fish_disable_bracketed_paste JOB_EXIT 2 0' with id 6
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_job with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_decorated_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_plain_statement with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument_or_redirection with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_argument with input token <parse_token_type_string>
<5> fish: Resolving production for symbol_arguments_or_redirections_list with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_continuation with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_optional_background with input token <parse_token_type_terminate>
<5> fish: Resolving production for symbol_job_list with input token <parse_token_type_terminate>
<4> fish: Exec job 'printf "\e[?2004l"' with id 9
<3> fish: Skipping fork: ordinary output for internal builtin 'printf'
[?2004l<3> fish: Set status of printf "\e[?2004l" to 0 using short circuit
```


### Test 2
```
% bash
$ echo $$
12
exec fish
// normal prompt
```

[head-ok-log-4.txt](https://github.com/fish-shell/fish-shell/files/1549949/head-ok-log-4.txt)
[head-ok-log-5.txt](https://github.com/fish-shell/fish-shell/files/1549961/head-ok-log-5.txt)

#### Highlights
- `printf "\e[?2004l"` is not even executed

## Strace (same)
```
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
write(1, "\33[?2004l", 8)               = 8
time(NULL)                              = 1513042056
time(NULL)                              = 1513042056
```

**Comment by sarum9in** [comment] 2017-12-25 23:57
Hi @faho, you marked it as "needs more info" but it is not clear what else you would like me to provide here.

**Comment by faho** [comment] 2017-12-26 09:41
@sarum9in: I don't think there's really something _you_ can provide. I'd really love to get @mqudsi on this - he's touched the job control code before, and he uses WSL.

What I'd love to know is how:

>one of our code paths that is triggered on WSL does not set the process group.

Which would at least explain why it's specific to PID 2.

**Comment by itsjoel** [comment] 2017-12-28 23:17
Is there any workaround for this in the mean time? I keep having to open two windows in order for one of them to work.

**Comment by sarum9in** [comment] 2017-12-28 23:38
If you mean for `exec fish` in bash, you can always write `fish; exit $?` instead.

**Comment by itsjoel** [comment] 2017-12-28 23:47
It actually works fine when I start it from bash, but when I set it as my default shell, I need to open two windows for one of them to work. That's what this issue is about, no?

**Comment by sarum9in** [comment] 2017-12-29 14:28
If you start it as default shell it means that it will be started right under init, as pid=2. But there are different ways to start fish as process with id=2. If you want to make it default shell I would suggest adding /bin/fish-starter script which would do this:
```
#!/bin/bash
fish "$@"
exit $?
```
this will effectively start bash as pid=2 and then invoke fish as subprocess, so it will have higher PID.

**Comment by doxxx** [comment] 2018-01-02 19:00
This also happens in WSL (in Windows 10 v1709) if you use `chsh` to change your default shell to fish. The `fish-starter` workaround described above works if you add it to `/etc/shells` before setting `/bin/fish-starter` as the default shell with `chsh`.

**Comment by faho** [comment] 2018-02-02 22:33
I think I've got this: Jobs that solely consist of builtins don't have a "real" process attached and hence don't have a pgid. That means it stays at -2.

So what I'll do now is to just not fire the exit event for those jobs, which should solve the issue.

@sarum9in, @doxxx, @itsjoel: Please try 4204b8ccaea04822d, on my "no-exit-without-a-process" branch.

**Comment by zanchey** [comment] 2018-02-03 12:21
Hey, here's how to reproduce on other systems (this will kill your terminal window):

```fish
function foo --on-process-exit 2
  echo foo
end
echo &
```

Job handling strikes again! I don't know what the right answer here is. Fixing the conflation of PIDs and PGIDs in event handlers would be nice, but wouldn't actually help.

**Comment by faho** [comment] 2018-02-03 12:56
>Hey, here's how to reproduce on other systems (this will kill your terminal window):

Oooh, I did not think of that, that's neat! What's nice is that 4204b8c seems to actually help.

>Job handling strikes again! 

\*Cue ominous music\*

>Fixing the conflation of PIDs and PGIDs in event handlers would be nice, but wouldn't actually help.

Sooo.... fish currently fires the process-exit event for the job PGID, which means it fires it for the process group _leader_. Which is an issue by itself - if you have a job with more than one external command (e.g. `command cat | command grep`, it'll only be fired for the first of those. Instead, it should fire for every process in the job, by PID. But only for processes that _have_ a PID, otherwise you'll end up with this situation.

So how about this:

```c++
            // Fire the exit-event for every external process in the group.
            for (auto& proc : j->processes) {
                if (proc->type == EXTERNAL) {
                    proc_fire_event(L"JOB_EXIT", EVENT_EXIT, proc->pid, 0);
                }
            }
```

**Comment by doxxx** [comment] 2018-02-03 13:20
@faho I just compiled 4204b8c under WSL, installed it and then configured it as my default shell using `chsh`. Closed my WSL window and then re-opened it, and it launched into fish correctly.

Do you want me to try 06ffb55?

**Comment by faho** [comment] 2018-02-03 14:15
>Do you want me to try 06ffb55?

@doxxx: Yes, please!

**Comment by doxxx** [comment] 2018-02-03 14:34
Works with the head of no-exit-without-a-process (be4a28f).

**Comment by faho** [comment] 2018-02-03 15:07
Okay, so both work. Very nice. That confirms my assumptions.

Since 06ffb55 changes the behavior, I'm going to merge 4204b8c instead, which just fixes this bug (even if in a slightly unclean way).

I think we need to have some general discussion about the process-exit event.

**Closed** 2018-02-03 15:23 UTC
Labels: bug, needs more info, windows subsystem for linux

**Comment by sarum9in** [comment] 2018-02-03 15:40
Awesome, thank you @faho

**Comment by mqudsi** [comment] 2018-02-03 22:28
@faho awesome job fixing this. I'm sorry I never chimed in - I had github set to notify me on all activity which led to my being unable to distinguish between notifications for mentions and general notifications, so I never ended up seeing this. :\

**Comment by faho** [comment] 2018-02-03 23:12
@mqudsi: Yeah, github's notifications seem to have gotten worse in the last couple of months, especially when you're relying on the RSS feed.

No worries!

**Comment by zanchey** [comment] 2018-02-04 00:18
Why does JOB_EXIT fire *twice* anyway?!

**Comment by faho** [comment] 2018-02-04 09:36
>Why does JOB_EXIT fire twice anyway?!

That's a very good question. Though "JOB_EXIT" is the _text_ added as an argument. The event is called "EVENT_EXIT". When it fires after any process has exited, it fires with "PROCESS_EXIT" as argument. When it then fires again once the complete job has exited, it fires with "JOB_EXIT".

So I'd assume the idea was something like notifying you that the job has exitted. Only that doesn't work, because we also have the `EVENT_JOB_ID` event.

Since both were added in 838ba08eaa883026d6fb88cd65dde33b16a564fd - in 2005, I'd assume the real reason is "because Axel had a thinko, and nobody bothered to double-check".
