### ISSUE TITLE
Fish 3.0.2 doesnt play well with systemctl

### ISSUE THREAD

**Issue by siyia2** [fish-shell/fish-shell#5746] opened 2019-03-17 03:03 UTC
fish-3.02

Manjaro/Debian 10

run `systemctl disable/enable` in a terminal and use autosuggestion and/or autocomplete to disable/enable a service.
you will get: 

> Integer 241 in '241 (241)' followed by non-digit
> Integer 241 in '241 (241)' followed by non-digit

it is a regression of fish 3.02, fish 3.01 worked perfectly fine with systemctl and systemd 241, as far as i can remember

**Comment by faho** [comment] 2019-03-17 07:46
Duplicate of #5689

**Closed by faho** 2019-03-17 07:46 UTC
