### ISSUE TITLE
Wanting to replicate tcsh's vi-search-backward

### ISSUE THREAD

**Issue by clintolsen** [fish-shell/fish-shell#7753] opened 2021-02-28 03:20 UTC
```
fish, version 3.1.2
Darwin poly 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```
This is not a bug, it's more of a question. I've fiddled around with `fish` keybindings a bit to try to understand how to do this, and I've seen a thread documented elsewhere trying to address it.

https://github.com/fish-shell/fish-shell/issues/2271

Is the final answer given with a custom function still req'd? It's not clear to me why `fzf` is needed. We could be using `grep` for that.

I was trying to review the keybindings in the help, and there are so many references to `history-search` it was not clear what's relevant and what isn't. I tried mapping `history-search-backward` and it didn't do what I expected, so I don't understand how the heck this stuff works.

I don't care if I need to code this up myself. I just need to get enough info to be dangerous.

Behavior I desire:

1. In command/visual mode be able to type `/`
2. Type in a pattern, hit return, and the first history item to have this submatch should come up.
3. Be able to use `n` to iterate through them.

Any pointers and cluepons are appreciated.

**Comment by faho** [comment] 2021-02-28 07:26
>Is the final answer given with a custom function still req'd?

Yes.

>It's not clear to me why fzf is needed. We could be using grep for that.

`fzf` is the thing that allows you to interactively select the entry. It draws the pager and such. `grep` is not a replacement.

That is the best you're gonna do currently. Fish has no way to open the pager programmatically #2805, so there's no way to get an interactive menu without external means. So I'm closing this as a duplicate of #2271 (and #602), because it needs actual work inside fish.

**Closed by faho** 2021-02-28 07:26 UTC
