### ISSUE TITLE
exported list variables "flattened" when inherited by new fish shell 

### ISSUE THREAD

**Issue by koedx** [fish-shell/fish-shell#10017] opened 2023-09-13 05:05 UTC
Fish 3.6.1 (Android 10 / Termux)

I have some multi-element list variables (var1, var2) marked -gx (global, exported). This is confirmed by `set -S`.

However, when exported to a new fish shell, the multiple "list" elements seem to be flattened into a space delimited string (ie. a single element var). 

running `set -S var1; set -S var2; fish -c 'set -S var1; set -S var2'` confirms this "flattening".

Is this a know issue/by design? Would appreciate any guidance on the suggested work around if so. Thx 🙏

**Comment by faho** [comment] 2023-09-13 05:08
Duplicate of #5348

**Closed by faho** 2023-09-13 05:08 UTC

**Comment by faho** [comment] 2023-09-13 05:10
> Is this a know issue/by design?

In short: Unix has no lists, so there is no good way to transfer them to another process. It's not fixable.
