### ISSUE TITLE
fish_color_valid_path only works for last entered token

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#714] opened 2013-05-07 10:27 UTC
If I type, say, `ls Pictures ` then `Pictures` is underlined but as soon as I type another argument the underlining is gone.  If the next argument is also a valid path then that one is also underlined, and also reset once I type a third argument, et cetera.  Same problem if I type multiple commands, either with semicolon or Alt-Enter.  If I move the cursor within the commandline and type in a valid file path, that one is underlined and any other underlining is reset.  Only the last entered token in one command line is ever affected by `fish_color_valid_path`.

**Comment by floam** [comment] 2016-06-18 14:23
I'm gonna call this a duplicate of #847; this report came first but there is more discussion over there.

**Closed by floam** 2016-06-18 14:23 UTC
