### ISSUE TITLE
Expand glob with tab/autocomplete

### ISSUE THREAD

**Issue by septatrix** [fish-shell/fish-shell#8489] opened 2021-11-25 12:14 UTC
* `fish, version 3.3.1`
* `Linux thinkpad-e570 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* `xterm-256color`
* same happens with a clean shell (`sh -c 'env HOME=$(mktemp -d) fish'`)

When writing globs (especially with `*`) it would be useful to have them expand when pressing <kbd>TAB</kbd>. Currently this is just treated as a word and pressing tab inserts a space.

This is especially useful when executing dangerous commands like `rm` where it is vital to double check the files which will get matched. As a workaround for such cases I prefix the command with an echo though this is not idea.

Zsh for example provides this feature out of the box. It works with any globs to my knowledge (e.g. asterisks, question marks, subdirectories etc.). Also their implementation respects escaped glob characters.

[![asciicast](https://asciinema.org/a/YgCKEs6wCuzpS5w6pjCWxVLbC.svg)](https://asciinema.org/a/YgCKEs6wCuzpS5w6pjCWxVLbC)

**Comment by faho** [comment] 2021-11-25 12:21
Duplicate of #751

**Closed by faho** 2021-11-25 12:21 UTC
