### ISSUE TITLE
Reproducable hang with futex = EAGAIN

### ISSUE THREAD

**Issue by jfortmann** [fish-shell/fish-shell#442] opened 2012-12-12 05:11 UTC
This might be a dupe of #311.

I'm running fish on a raspberry pi running debian Linux. I've got a (sometimes, not always) reproducable hang when I kill my ssh connection to the machine while it's updating the prompt. Running strace on the  process gives the following

>futex(0x40420a74, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
>futex(0x40420a74, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
>futex(0x40420a74, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)

and so on.

Attaching with gdb gives the following
>#0  0x4011025c in __lll_lock_wait () from /lib/arm-linux-gnueabihf/libpthread.so.0
>#1  0x4010c420 in pthread_rwlock_rdlock () from /lib/arm-linux-gnueabihf/libpthread.so.0
>#2  0x4031ec48 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
>#3  0x00000018 in ?? ()
>#4  0x00000018 in ?? ()
>Backtrace stopped: previous frame identical to this frame (corrupt stack?)
>(gdb) info threads
>  Id   Target Id         Frame 
>* 1    Thread 0x40038720 (LWP 10415) "fish" 0x4011025c in __lll_lock_wait () from /lib/arm-linux-gnueabihf/libpthread.so.0

which of course isn't very helpful.

**Comment by faho** [comment] 2015-07-17 19:44
This is old. Can anyone still reproduce?

**Comment by zanchey** [comment] 2015-07-26 03:22
We had one user who somehow managed to trip over this all the time, but it hasn't happened since I installed 2.2b1. I'm going to close it for now; if anyone can reproduce please speak up!

**Closed by zanchey** 2015-07-26 03:22 UTC
