### ISSUE TITLE
command substitutions with variable indices don't work

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#9179] opened 2022-09-05 17:35 UTC
Fish 3.5.1, macOS

```fish
~
❯ set foo 1 2 3 4 5

~
❯ set bar 3

~
❯ echo $foo[3]
3

~
❯ echo $foo[$bar]
3

~
❯ echo (printf %s\n $foo)[3]
3

~
❯ echo (printf %s\n $foo)[$bar]
fish: Invalid index value
echo (printf %s\n $foo)[$bar]
                        ^
```

For some reason command substitutions and variable indices don't play nicely together.

**Comment by faho** [comment] 2022-09-05 17:40
Duplicate of #243

**Closed by faho** 2022-09-05 17:40 UTC
