### ISSUE TITLE
fish_config doesn't save changes for abbreviations

### ISSUE THREAD

**Issue by leomayer** [fish-shell/fish-shell#9530] opened 2023-02-02 12:16 UTC
```
fish, version 3.6.0
Linux ws3 6.1.8-1-default #1 SMP PREEMPT_DYNAMIC Tue Jan 24 06:29:25 UTC 2023 (baebfe0) x86_64 x86_64 x86_64 GNU/Linux
```

I run the command `fish_config` and change one of the abbreviations. After pressing the ENTER key the changes are not saved. I've tried as well with remove and rename the abbreviations - but this won't help.

I see the commands from on the shell. As well `shutting down` . But when I start again the same abbreviations are displayed.

**Comment by faho** [comment] 2023-02-02 12:40
Duplicate of #9460 and #9489

**Closed by faho** 2023-02-02 12:40 UTC

**Comment by leomayer** [comment] 2023-02-02 15:10
Just a comment: Wouldn't it be better - instead of removing the tab - 

- to display the content of the current abbreviations (as now)
- do NOT allow changes on the UI
- make a hint what the user should do instead to change the configuration (otherwise I would guess more similar issues are raised)
