### ISSUE TITLE
tests are locale-dependent

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3110] opened 2016-06-03 09:30 UTC
While working on #277, I managed to set locale to something that localized the messages. which managed to break the "status" test:

LANG=de_DE.UTF-8
LC_MESSAGES=en_US.UTF_8

In particular, it will print "open: Ist ein Verzeichnis" instead of the expected "open: Is a directory" (which seems the wrong way around to me).

**Comment by faho** [comment] 2016-06-03 10:12
If anyone can figure out why it only starts printing messages in german when LC_MESSAGES is set to english (!) I'd be grateful.

**Comment by krader1961** [comment] 2016-06-04 01:06
The `handle_locale()` function is overly complicated. There is no need for it to check whether or not a LC_ALL env var exists and fallback to LANG and other LC_ vars. The `setlocale()` function will take care of all that. However, we have to ensure those vars are in the process environment. Should be easy to fix. Too, I need to fix it because I hadn't noticed that the change I just committed added a bunch of LC_ var names that don't exist in the `cat` array inside `handle_locale()`. So that inner loop will now blow up because the two arrays aren't the same length.

**Comment by krader1961** [comment] 2016-06-04 03:09
I wrote this trivial script:

```
#!/bin/sh
export LANG=de_DE.UTF-8
export LC_MESSAGES=en_US.UTF-8
fish
```

Notice that I assign `en_US.UTF-8` rather than the, incorrect, `en_US.UTF_8` @faho was using for LC_MESSAGES. That causes fish to produce the expected results and is why @faho was seeing test failures. If I use the invalid `en_US.UTF_8` then all the locale categories are set to "C" with the exception of LANG. The current fish code handles that incorrectly.

**Comment by faho** [comment] 2016-06-04 09:21
>Notice that I assign en_US.UTF-8 rather than the, incorrect, en_US.UTF_8 @faho was using for LC_MESSAGES.

That was a typo _here_. It doesn't matter which of those I assign.

**Comment by krader1961** [comment] 2016-06-05 01:46
@faho, No matter what I try I cannot reproduce your problem. The closest I can get is by doing

```
set -x LC_MESSAGES de_DE.UTF-8
```

That breaks the tests because *test_utils.fiish* doesn't correctly clean the locale env vars due to the `set IFS` that precedes that block of code. But the test failures are different than you're reporting. I thought it might be because you're setting LANGUAGE (which the test framework also ignores) but setting it to various values doesn't break the tests in the manner you describe.

What does `locale` report? Also, presumably you're running the tests via `make test` but please confirm.

**Comment by krader1961** [comment] 2016-06-05 02:27
Also, @faho, please try the latest version of PR #3112. Since we don't yet understand what's happening on your system I don't expect it to fix your issue but it might since I changed the *test_utils.fish* script.

**Comment by faho** [comment] 2016-06-05 09:40
>What does locale report? 

>LANG=de_DE.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES=en_US.UTF_8
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

>Also, presumably you're running the tests via make test but please confirm.

Yes.

**Comment by faho** [comment] 2016-06-05 09:49
>Also, @faho, please try the latest version of PR #3112. 

That version works.

**Comment by floam** [comment] 2016-06-05 10:50
> LC_MESSAGES=en_US.UTF_8

Shouldn't that be UTF-8?

**Comment by faho** [comment] 2016-06-05 11:49
Yeah it should, it makes no difference either way though.

**Comment by krader1961** [comment] 2016-06-05 14:00
What is almost certainly happening is you've set the `LANGUAGE` env var to german. That the test setup code didn't remove it was an oversight. The test setup code also wasn't correctly initializing the `LC_` vars due to redefining `IFS` a few lines earlier. So the tests weren't actually hermetic vis-a-vis the local locale. My most recent change to the PR fixed those problems.

And, as an unintended side-effect, this issue caused me to look closely at what the `handle_locale()` function was doing and rewrite it into a more understandable form.

**Closed** 2016-06-05 22:58 UTC
Labels: bug
