### ISSUE TITLE
`builtin test -t` is not compatible with standard `test -t`

### ISSUE THREAD

**Issue by norio-nomura** [fish-shell/fish-shell#6579] opened 2020-02-10 14:35 UTC
```terminal.sh-session
$ builtin test -t 1|builtin test -t 0|cat; echo $pipestatus
0 0 0
$ command test -t 1|command test -t 0|cat; echo $pipestatus
1 1 0
$ fish --version
fish, version 3.1b1-137-g4c66e69cd
$ echo $version
3.1b1-137-g4c66e69cd
```
Bash builtin:
```terminal.sh-session
$ [[ -t 1 ]]|[[ -t 0 ]]|cat; echo ${PIPESTATUS[@]}
1 1 0
```
Zsh builtin:
```terminal.sh-session
$ [[ -t 1 ]]|[[ -t 0 ]]|cat; echo ${pipestatus[@]}
1 1 0
```

**Comment by faho** [comment] 2020-02-10 14:39
Nah, it's just broken.

**Comment by faho** [comment] 2020-02-10 14:39
Duplicate of #1228

**Closed** 2020-02-10 14:39 UTC

**Comment by norio-nomura** [comment] 2020-02-10 14:50
Thanks.
