### ISSUE TITLE
fish on Raspberry Pi does not get the same default $PATH as bash/sh

### ISSUE THREAD

**Issue by Testato** [fish-shell/fish-shell#3494] opened 2016-10-26 08:24 UTC
I recompiled Fish on an Raspberry.
It work correctly if i manually start fish.
After i decided to set fish to my standard shell by:

```
echo /usr/local/bin/fish | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish
```

but now all /sbin command do not work, the original Path is loosed ?

```
osmc@osmc ~> sudo reboot
sudo: reboot: command not found
osmc@osmc ~> echo $PATH
/usr/local/bin /usr/bin /bin /usr/games
```

I installed Fish on an Ubuntu16 also, by regularly `sudo apt install fish` and the path rpoblem there isn't, so only when manually recompile fish appear this problem ?

**Comment by krader1961** [comment] 2016-10-27 04:18
Fish would only have something like `/sbin` in `$PATH` it was in the var when fish was started or was in a system wide config file such as */etc/paths*. See the global *config.fish* script (e.g., */usr/local/share/fish/config.fish*). If you login to your computer as a non-root user it is very unlikely that `/sbin` will be in `$PATH`. You'll need to add that yourself. Either via the fish universal var `fish_user_paths` or appropriate `set -x PATH` statements in your *~/.config/fish/configl.fish* file.

**Comment by Testato** [comment] 2016-10-27 07:59
I'm on a untouched osmc distro for rpi, with standard user osmc and password osmc.
Befoure Fish rebuild/install i can use reboot, after i cannot.

**Comment by ridiculousfish** [comment] 2016-10-27 08:01
@Testato if you just want to get `/sbin` back in PATH, you can run:

    set -U fish_user_paths /sbin

Please let us know if that doesn't work.

I haven't confirmed this, but my guess is that there is some bash-specific initialization that adds `/sbin` to the path if you're root.

**Comment by faho** [comment] 2016-11-10 17:09
@Testato: Is there anything more to do here?

**Comment by Testato** [comment] 2016-11-10 20:01
Sorry but i'm not agree and sorry if i repeat, but befoure Fish installation on osmc is it possible do sudo reboot, on osmc standard user named pi.
Now if I simply install Fish and loose the sudo reboot command (and all other command in sbin), i think that Fish have some bug, or Fish must be declared not compatible with OSMC distro.

**Comment by faho** [comment] 2016-11-10 20:29
@Testato: Have you tried what @ridiculousfish suggested - `set -U fish_user_paths /sbin`? Executing that command once interactively should be enough to make it work.

**Comment by krader1961** [comment] 2016-11-10 21:09
You said

> It work correctly if i manually start fish.

That's because $PATH already contained */sbin*. Nothing you've said suggests that fish has a bug. What it does suggest is that the config files for your original login shell was adding /sbin to $PATH. Most likely it is */etc/profile* (or some file sourced from that config script). Fish is not a POSIX compatible shell and thus does not use any of the config files used by bash, zsh, or any other POSIX compatible shell.

All you need to do is implement either my suggestion or @ridiculousfish's.

**Comment by Testato** [comment] 2016-11-10 21:12
nope
sorry for my english but with
`It work correctly if i manually start fish`
I mean that fish start, so the compilation was fine, not that the /sbin command work

**Comment by Testato** [comment] 2016-11-10 21:15
and Yes, if i run
`set -U fish_user_paths /sbin`
the sbin command return to work

**Comment by krader1961** [comment] 2016-11-10 21:17
Use `chsh -s` to put your login shell back to bash or whatever you were using before fish. Then login and type `echo $PATH`. I'm betting it contains */sbin*. If you look at */etc/profile*, *~/.profile* and any scripts they source I'm quite confident you will find $PATH being set so that it includes /sbin. As I said before fish doesn't use any of those config files.

**Comment by Testato** [comment] 2016-11-10 21:26
yes, i agree with you, OSMC have /sbin on "pi" user, not only on "root" user.
But why if i change my shell from bash to fish i must loose the original bash path ?
Isn't normal that a new shell copy and reuse the current path ?

If I install ZSH i do not loose the current path for the current user

**Comment by faho** [comment] 2016-11-10 21:34
> Isn't normal that a new shell copy and reuse the current path ?

Fish isn't another POSIX shell. It does not read POSIX shell scripts. Since $PATH on your distribution is configured in a POSIX shell script, fish will not read it. zsh is another POSIX shell, it can and will read /etc/profile, as will bash (and ksh, and dash, and ....).

When you configure bash or zsh (or one of the others) as your user's shell, that will then read /etc/profile, which will set $PATH. When you configure fish to be your shell, that won't happen, because fish cannot understand that file, because it uses an incompatible dialect.

You have now fixed your issue by configuring fish to add /sbin to $PATH - $fish_user_paths, which you have set above, will be added to $PATH, and it is a universal variable, which fish saves in a file and reads when it starts.

**Comment by Testato** [comment] 2016-11-10 21:40
but wait a moment, I installed Fish on many machine, 
examples i installed it in this moment on an Ubuntu16 desktop, and on this desktop i do not use "root".

Why i do not loose the /sbin path here also ?

**Comment by krader1961** [comment] 2016-11-10 21:51
> Why i do not loose the /sbin path here also ?

I don't know but it could be any number of reasons. Perhaps you already did `set -U fish_user_paths /sbin` on those systems. Perhaps you modified your *~/.config/fish/config.fish* to add */sbin* to $PATH. Perhaps you've configured the PAM (pluggable authentication module) subsystem to add */sbin* to path before launching the login shell. I use Ubuntu 16.04 with fish as my login shell and */sbin* is not automatically in my $PATH. So I am quite certain you've done something non-standard to have it included in your $PATH.

**Comment by Testato** [comment] 2016-11-10 22:17
ok, i can accept that this is the actual functionality of Fish, so now we want change it ?

If Fish cannot read directly the actual path because it is not Posix, etc, he can at the first boot start a script for read the actual path and set it by internal Fish command.

If an user install a Shell he want it's path working, a root user want this but also a non-root user want this.
What do you think ?
Do you remember you path and re-set it manually every times that you install Fish ? It's not what an user want i think.

**Comment by Testato** [comment] 2016-11-10 22:23
on homepage there is:

```
Works Out of the Box Thumbnail fish will delight you with features like tab completions and syntax highlighting that just work, with nothing new to learn or configure.
```

But you loose you path, and must learn how configure it. It's sure that this is a good thinghs ?

**Comment by krader1961** [comment] 2016-11-10 22:24
I think there is more than just a language barrier keeping us from understanding each other, @Testato, so I'm going to disengage and see if @faho or someone else can explain to you how environment vars work. But I will say I think you are making this more difficult than it needs to be. Just put the following in your *~/.config/fish/config.fish*:

```
if not contains /sbin $PATH
    set -x PATH $PATH /sbin
end
```

Whenever you setup fish on a new system just install that config file.

**Comment by faho** [comment] 2016-11-10 22:27
>he can at the first boot start a script for read the actual path and set it by internal Fish command.

I'm having trouble understanding you here. Do you suggest that, when you first start fish, a "wizard" appears:

```fish
~> Hello, I'm fish!
~> What is your $PATH?
```

if so, that's

- annoying
- solves an unusual problem
- in the wrong place

The better solution for this is to not use /etc/profile at all. The better solution is /etc/environment. This file is read whenever you login however you login (by "pam"). Even if you don't start a "shell", if you use e.g. `python` or if it's not a normal user at all, but a daemon user.

Also, /sbin is kind of being removed all over the linux world - my distribution doesn't have it any more, neither does Fedora. I think Ubuntu also removed it. (Or rather, they have a symlink).

The problem with /sbin is that it was supposed to be a place for programs only useful to root - only it's not being used like that, because many programs also do a thing that is useful if you're not root (like e.g. `ifconfig` or `ip` just to _show_ your ip). And that's why it is not in $PATH by default (i.e. without /etc/environment or /etc/profile or whatever).

**Comment by MauroMombelli** [comment] 2016-11-10 23:12
sorry for intromission, but here the issue is pretty clear, he saw "Works Out of the Box", installed it, tryed, 
and found out most of the commands necessary for the distribution to work corretly are NOT working.

So the first issue is: if this does not get somehow solved, that statement should be removed, or a *  added and (*if your distribution follow certain rule or it has been packaged with correct configuration)

Why and how solve this temporaly is a secondary issue for testato, its user experience had been ruined. and also all of the people who blindly install fish and find themself missing pieces of PATH and so programs not working properly.

That said I understand what that distribution does may be non standard, bad and ugly, but i also undestand PATH is something quite important for a consolle to work as expected, so a workaroud, or a special case should be considereded; grabbing the PATH out of bash/sh at the first run could be an ugly but effective hack.

**Comment by floam** [comment] 2016-11-10 23:30
We do a pretty good job of figuring out what $PATH should be on OS X. Maybe we should add in similar magic for other systems.

**Comment by faho** [comment] 2016-11-11 00:45
>We do a pretty good job of figuring out what $PATH should be on OS X.

We do that via /etc/paths{,.d}. That's just not a thing on linux.

**Comment by krader1961** [comment] 2016-11-11 01:09
> ... or it has been packaged with correct configuration)

That's implicit, @MauroMombelli. In general it's going to be impossible for fish to setup the PATH exactly the same as you would get if you were using, say, bash on every possible platform that fish runs on. Consider how different macOS, OpenBSD, Solaris, RHEL, SLES, Ubuntu, Arch, etc. are in terms of the mechanisms they use to configure such things. Fish already has knowledge of many of them; e.g., the */etc/paths.d* directory on macOS. And nothing stops us from adding more as we learn about them. However, expecting fish to support the quirks of every random platform, like a Raspberry Pi, is unreasonable.

The simplest solution is to simply augment the fish global config to do something like the following:

```
if not contains /sbin $PATH
and test -d /sbin
    set -x PATH $PATH /sbin
end

if not contains /usr/sbin $PATH
and test -d /usr/sbin
    set -x PATH $PATH /usr/sbin
end
```

That can obviously be extended to include other commonly used directories such as */usr/local/bin*. The question is whether this is likely to cause more problems than it solves. And even if we do something like that there is no guarantee we'll duplicate the PATH that would have been setup by the POSIX config scripts.

As for

> grabbing the PATH out of bash/sh at the first run could be an ugly but effective hack.

That is indeed a hack and a potentially dangerous one since launching a bash/sh login subshell may have unwanted side-effects. Seems like the risks, and costs, outweigh the value. Not to mention it isn't as simple as capturing the value of $PATH from that subshell. We'd need to figure out how to merge any differences into the $PATH that fish inherits. Not to mention the question of whether mutating the $PATH in such a manner is itself safe if we don't append to the existing $PATH. And if we instead attempt to maintain the same relative ordering then we risk picking the wrong external command if we inherit a $PATH in which the user has explicitly arranged for a command to be found in some other directory (e.g., *~/sbin*).

**Comment by MauroMombelli** [comment] 2016-11-11 08:48
I partially understand your concern (I don't see how spawning a bash, read
path and killing it could be problematic), then let's look at other
solution :)

/bin /sbin and /usr/bin are fundamental and pretty standard (HFS if irc),
many distribution as decided that keeping them separate makes no more sense
(arch Linux does for sure from a couple years), so maybe if not all PATH,
at least those folder need a special treatment.

**Comment by floam** [comment] 2016-11-11 18:50
Something along the lines of grabbing the stuff in `env -i sh -ci 'echo $PATH' | string split ':'` in the one-time init parts of __fish_config_interactive might work.

**Comment by faho** [comment] 2016-11-11 19:03
@floam: No, it wouldn't. We'd be launching a shell in an unusual mode - I've seen people configure login shells to launch X11 sessions automatically. You don't want that to happen when fish starts up.

Also, people might configure $PATH in ~/.bashrc instead. Or ~/.zshrc.

Really, this is solved as well as it can be. You might need to add /sbin (and maybe /usr/sbin) to your $PATH once, if your distribution is configured wrong. 

Plus, this is only going to get more unusual.

**Comment by floam** [comment] 2016-11-11 20:40
Do any Linux distributions still use `/etc/environment` the same way MacOS is doing what it does?

**Comment by floam** [comment] 2016-11-11 20:41
Wait, except that should get applied at boot - and inherited by fish.

**Comment by MauroMombelli** [comment] 2016-11-11 20:44
I would like to say people that configure their own path are not the issue
as they know what they do. The issue are missing system path. For testator
seems like they don't get inherited then.. @testato?

**Comment by faho** [comment] 2016-11-11 21:03
>For testator seems like they don't get inherited then.. @testato?

@MauroMombelli: I think you missed something here. The issue isn't _inheritance_. The issue is that the path is never applied.

The way it works here is that the kernel starts init, that then starts getty (or ssh or whatever), which allows testato to login and then starts fish. Nowhere in that chain is there anything that ever reads /etc/profile, so these directories never get added to $PATH.

If you used e.g. bash as your user's shell, then getty would start that as a login shell, so it would read it, which would then set the distribution configured $PATH value.

When you add it to /etc/environment, then getty, which goes via "pam" anyway to confirm your password, would set those values, no matter what shell you use (and yes, you could also run with "python" as your shell). That's why it (or something like it) is the right solution.

**Comment by MauroMombelli** [comment] 2016-11-11 21:12
Sorry but AFAIK at the first run testato launched it from a shell and it
wasn't working anyway

**Comment by faho** [comment] 2016-11-11 21:13
No - re-read the original comment:

>It work correctly if i manually start fish.
After i decided to set fish to my standard shell by:

>echo /usr/local/bin/fish | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish

>but now all /sbin command do not work, the original Path is loosed ?

**Comment by MauroMombelli** [comment] 2016-11-11 21:15
Oh sorry, I understand was not working even if launched from bash, my bad!

**Comment by krader1961** [comment] 2016-11-11 22:10
It's pretty clear the O.P. doesn't understand how env vars work. Especially ones like PATH which often get set via multiple mechanisms. Obviously on Raspberry Pi someone on the distro maint team decided it made sense to automatically include */sbin* in $PATH but did so in a manner that only works for a subset of shells. If Raspberry Pi has something analogous to */etc/path.d* or */etc/paths* we should probably utilize it. Even if it doesn't we still might want to add something like the snipped I added above to the global *config.fish* if doing so is deemed low risk.

**Comment by Testato** [comment] 2016-11-11 22:17
I normally use Win10 :-)

**Comment by MauroMombelli** [comment] 2016-11-11 22:21
@faho reading the other testator comment, is clear when he say "working" he meant the compilation and running the shell worked, but even if running fish from bash inheritance didn't work:


Krader1961: he does not about path (or he is playing dumb) and he chooses fish as it say to be "out of the box" but isn't.
"""
nope
sorry for my english but with
It work correctly if i manually start fish
I mean that fish start, so the compilation was fine, not that the /sbin command work
"""

**Comment by krader1961** [comment] 2016-12-18 00:05
@MauroMombelli: You've said the following twice:

> when he say "working" he meant the compilation and running the shell worked, but even if running fish from bash inheritance didn't work

That is not what @Testato said. It's quite clear that when the login shell was bash and he then typed "fish" `$PATH` was set as expected; i.e., included */sbin*. It was only when they set fish to be the login shell, thus bypassing the environment var setup that bash performs, that */sbin* was no longer in `$PATH`. And that is to be expected since fish will not read the same config files, such as */etc/profile*, that bash reads. Fish does correctly inherit the environment vars, including `$PATH`, when launched from a bash shell.

The simplest solution, and one I don't see mentioned in this issue, is to not change the login shell. Instead of doing `chsh -s /usr/local/bin/fish` leave the login shell set to bash. The add `exec /usr/local/bin/fish -l` to to the bottom of the *~/.bash_login*. That way you let bash setup the env vars using whatever mechanisms that employs on a Raspberry Pi then drops you into a fish login shell which will inherit that environment.

I'm going to close. If anyone with knowledge of the Raspberry Pi can tell us if it uses something like macOS */etc/paths.d* to customize `$PATH` we'll be happy to add support for it.

**Closed by krader1961** 2016-12-18 00:05 UTC
Labels: enhancement, RFC

**Comment by Testato** [comment] 2016-12-18 07:55
I will re-test the inheritance behavior, becouse it is the key of this issue

**Comment by MauroMombelli** [comment] 2016-12-18 10:30
@krader1961 testao may not be very clean to explain, but please note he (and me) are not that good in english, so please don't analize our word "mathematically" but try understand what we want to say.

> It's quite clear that when the login shell was bash and he then typed "fish" $PATH was set as expected; i.e., included /sbin.

absolutely not, he wrote:

> It work correctly if i manually start fish I mean that fish start, so the compilation was fine, not that the /sbin command work

so this mean the *compilation* and running is fine but not the path behaviur. and this interpretation has been reinforced by Testato's last comment:

> I will re-test the inheritance behavior, becouse it is the key of this issue

so unless Testao had a fault with his test (after all if you don't know where the issue come from iits easy to change something that alter the bug behaviur without noticing) the issue is there and hopefully easy to reproduce

**Comment by Testato** [comment] 2016-12-18 17:29
the inheritance work:
```
osmc@osmc:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/osmc/bin:/opt/vc/bin
osmc@osmc:~$ fish
osmc@osmc ~> echo $PATH
/usr/local/bin /usr/bin /bin /usr/local/games /usr/games /sbin /usr/sbin /usr/osmc/bin /opt/vc/bin
osmc@osmc ~> echo $fish_user_paths

osmc@osmc ~>

```

**Comment by Testato** [comment] 2016-12-18 17:46
Now I reconfigured Fish as the default shell, and this is my actual shell:
```
osmc@osmc ~> echo $PATH
/usr/local/bin /usr/bin /bin /usr/games
```
Is it a standard Fish behavior ?

**Comment by Testato** [comment] 2016-12-18 17:48
Now I reconfigured Fish as the default shell, and this is my actual shell:
```
osmc@osmc ~> echo $PATH
/usr/local/bin /usr/bin /bin /usr/games
```
I lost this path:
` /usr/games /sbin /usr/sbin /usr/osmc/bin /opt/vc/bin`
Is it a standard Fish behavior ?

**Comment by faho** [comment] 2016-12-18 18:14
@testato: Like we've explained before, the issue is that your distribution adds those paths in /etc/profile. When you start bash, it reads that file (simplifying a bit here). When you start fish, it won't, because that file is in bash-syntax. Fish doesn't understand that.

If you need those paths in $PATH, you should add them, either in config.fish or via $fish_user_paths.

Or you could move that bit of configuration to /etc/environment, which is applied when logging in, outside of any particular shell.

**Comment by Testato** [comment] 2016-12-18 21:31
ok, so last question, from where it is read the paths that fish do not lost ?
`/usr/local/bin /usr/bin /bin /usr/games`

Finally, I still think that, especially for a Shell program, you can not write on the homepage `"Works Out Of The Box"` and then go to lose the Path when you set Fish as a system shell.
At least one asterisk with a warning, and a small page dedicated to how to handle the Path problem is a must to meet the user.
Thanks to the interesting and informative discussion.

**Comment by faho** [comment] 2016-12-18 21:44
>ok, so last question, from where it is read the paths that fish do not lost ?

Most likely /etc/login.defs. Which, come to think of it, would probably also be a better place for setting it for all users.

>Finally, I still think that, especially for a Shell program, you can not write on the homepage "Works Out Of The Box" and then go to lose the Path when you set Fish as a system shell.

As we've said multiple times before, this is a distribution issue. Your distribution decided to set PATH in a weird way, without thinking of alternative shells. 

This is a very unusual configuration.
