### ISSUE TITLE
History function garbles output

### ISSUE THREAD

**Issue by tusj** [fish-shell/fish-shell#895] opened 2013-06-25 10:29 UTC
There seems to be some awkward bug with the history function. I wanted to do a git commit in a directory, but it's now impossible because fish suggests the commit command I already did, but doing so, it garbles the command completely, so that I cannot even remove what's already typed.

It's hard to see what's happening here because of the loss of coloring, but I'll try to explain.

When I type "git c" in order to enter "git commit...", fish autosuggests on the "c", but then, when I continue to type the command, as in "git commit", the "ommit" I already typed becomes appended AFTER the suggestion from fish, leaving me with a useless command. Only way to exit from this state is typing ctrl-C. This is with version 2.0.0 installed on arch linux.

Error message:
git commit -m "cleaned up, fixed some naming
ommcommimitit t -m "cleaned up, fixed some naming

**Comment by faho** [comment] 2015-07-16 12:21
Is this a duplicate of #2199 (there's special characters in the screenshot)?

**Comment by nyarly** [comment] 2015-07-17 18:49
It might be - until I patched out system wcwidth, I was having much the same issue (on top of the issues reported in 2199)

**Comment by krader1961** [comment] 2016-06-15 15:48
This has been in the "needs more info" state for nearly a year. It also concerns a really old fish version (2.0.0) that is no longer supported. Lastly, we've made so many changes relevant to the problem that it's quite likely we've already fixed the issue.

**Closed by krader1961** 2016-06-15 15:48 UTC
Labels: needs-more-info
