### ISSUE TITLE
Store working directory for commands in history?

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3373] opened 2016-09-12 09:12 UTC
Related to #3368, it would be handy if Fish stored in history the working directory that commands are run from.  It would make it easy to recall a previous command that must be run from a certain directory and quickly either change to that directory to run the command, or convert the paths to absolute paths using that working directory as a base.

**Comment by floam** [comment] 2016-09-12 10:49
That'd be nice. That'd let directory history potentially work across sessions too if they were stored there.

**Comment by krader1961** [comment] 2016-09-29 05:31
I agree that fish should store the cwd in effect when a command was run in the interactive command history. Primarily for display by the `history` command. I don't understand the rest of your proposal, @alphapapa.

Why would it be useful to "quickly ... change to that directory to run the command"? How would that work from a UI perspective? Since the vast majority of commands I run, such as `git diff`, are perfectly reasonable in whatever the cwd is why would I need or want to change my cwd just because I retrieved a command (e.g., via [up-arrow]) from my command history?

What do you mean "convert the paths to absolute paths using that working directory as a base"? What paths? What would initiate the conversion? Alternatively, under what conditions would that conversion occur?

**Comment by alphapapa** [comment] 2016-09-29 05:50
I'll try to give an example:

```fish
~ $ pwd
/home/me
~ $ cd src/fish-shell
~/src/fish-shell $ less README.md
~/src/fish-shell $ cd ~/somewhere/else
~/somewhere/else $ # do stuff
~/somewhere/else $ cd ~/somewhere/nice
~/somewhere/nice $ # do stuff
~/somewhere/nice $ # want to look at Fish readme again
~/somewhere/nice $ less <up-arrow>
~/somewhere/nice $ less README.md
README.md: No such file or directory
$ less ~/src/fish-shell/README.md  # Had to type the full path
```
Now imagine if, after typing `less` and pressing the up-arrow, I could press another key (maybe Alt+C, but whatever) to change to the directory that the command currently displayed from history was run in.  It would look like this:
```fish
~/somewhere/nice $ # want to look at Fish readme again
~/somewhere/nice $ less <up-arrow>
~/somewhere/nice $ less README.md <Alt+C>
cd ~/src/fish-shell  # Fish changes to the right directory for me
~/src/fish-shell $ less README.md
```
Then all I have to do is press Enter and the `less` command will work.

Another possibility is to have a command that converts relative paths in the commandline to absolute ones, based on the directory the currently displayed command was run in (if it is a history completion).  Then I could just hit Enter and run the command successfully without changing directories. 

This would save a *lot* of `cd`ing around.  ;)

**Comment by krader1961** [comment] 2016-09-29 06:14
There is no way this would work sensibly in any but the most trivial situations. Again, how will fish determine which arguments on the command line are relative paths rather than arbitrary text? And if my cwd is a directory that does not have a `README.md` file why in the hell would I want fish to magically convert that to the absolute path of the `README.md` file the last time I ran that command? Rather than let the `less` command either show me the `README.md` file in the cwd or tell me the file doesn't exist?

I'm sorely tempted to just close this issue because your use cases are FUBAR. Notwithstanding the fact that I agree fish should store the cwd when an interactive command is run and make that information accessible.

**Comment by alphapapa** [comment] 2016-09-29 20:54
> There is no way this would work sensibly in any but the most trivial situations.

What you call "trivial" I call "the vast majority of situations."  It would save time and effort and keystrokes every day, and the few times it did not apply, the user would have nothing more to do than Ctrl+C and hit the up arrow again.  This argument is no better than arguing that history itself "wouldn't work sensibly" because it's possible to recall commands with relative paths and execute them in the wrong directory--a situation which this is intended to fix.

> Again, how will fish determine which arguments on the command line are relative paths rather than arbitrary text?

I have already explained this and demonstrated it.  Have you yet to read this source code?
```fish
function commandline-paths-to-absolute
      set -l tokens (commandline --tokenize)
      set -l new_tokens
      for token in $tokens
          if test -e $token
              set new_tokens $new_tokens (readlink -m $token)
          else
              set new_tokens $new_tokens $token
          end
      end
      commandline -r (echo $new_tokens | tr '\n' ' ')
  end

bind \ea commandline-paths-to-absolute
```
If a command line token is arbitrary text, `test -e` will fail, and the token will not be changed.  If a token is a valid relative path, `test -e` will pass, and `readlink -m` will convert it to an absolute path.  It's very simple.

> And if my cwd is a directory that does not have a README.md file why in the hell would I want fish to magically convert that to the absolute path of the README.md file the last time I ran that command?

So you don't have to change back to that directory to view the file.  I *just* illustrated this in detail with a log of commands showing how it works with and without this feature.  Did you read my previous comment?

>  Rather than let the less command either show me the README.md file in the cwd or tell me the file doesn't exist?

If there is also a `README.md` in the current directory, and you want to view the one in the current directory, you simply press Enter instead of pressing Alt+A or whatever to convert the paths.  It's not activated automatically with some heuristic, it's manually activated by the user when necessary.

> I'm sorely tempted to just close this issue because your use cases are FUBAR.

I have explained the use cases in careful detail.  That you still don't understand them does not make them invalid.  If you are not interested in this feature, I invite you to ignore further discussion and let interested parties continue.  Your aggressive, confrontational attitude is tiresome.

**Comment by krader1961** [comment] 2016-09-29 23:26
I agree that you and I rub each other the wrong way. Nonetheless, I did read your proposal quite carefully. You say

> Have you yet to read this source code?

Then provide the example implementation that was in issue #3368. I did read that but it doesn't make this proposal work if your pwd is not that in effect the last time you ran the command. It does work if you invoke it before executing the command and the command is stored in your history (modulo false positives by the `test -e`). Which is fine but your original example in this issue shows quite clearly you intend for the function bound to [alt-C] to use the directory stored in the history when that command was last run rather than the cwd. So now your `commandline-paths-to-absolute` function needs to look something like the following. This is pseudo-code obviously since I've introduced a hypothetical `--history-cwd` flag:

```
set -l cmd_pwd (commandline --history-pwd)
if test -z "$cmd_cwd"  # command not retrieved from history
    if test -e $token
            set new_tokens $new_tokens (readlink -m $token)
    else
        set new_tokens $new_tokens $token
    end
else
    if test -e $cmd_pwd/$token
            set new_tokens $new_tokens $cmd_pwd$token
    else
        set new_tokens $new_tokens $token
    end
end
```

Does that accurately capture what you're thinking? Should the hypothetical `commandline --history-pwd` return a value if the command has been modified in any way after being retrieved from the history? Perhaps this should be implemented via a new flag that could be used with `history search --exact` to return just the pwd for the command line (which makes the previous question moot).

Also, keep in mind the BSD `readlink` doesn't have a `-m` flag. And depending on which flavor of BSD it may or many not have `readlink -f`. Which is why we introduced fish_realpath.

P.S., It probably would have been less confusing had you simply made this and issue #3368 a single issue since the two are effectively asking for the same feature.

**Comment by alphapapa** [comment] 2016-09-30 02:10
> I did read that but it doesn't make this proposal work if your pwd is not that in effect the last time you ran the command. It does work if you invoke it before executing the command and the command is stored in your history 

Yes, because that would require Fish to store the cwd with history, which it currently doesn't.  #3368 was specifically about "a command that could convert relative paths on the command line to absolute ones," which is what we ended up with after jinliu helpfully pointed out that it was already possible to implement that.

After that, I realized that it would also be helpful if Fish stored the cwd with the history, so that users could effectively do the same thing after the fact, even if they hadn't thought to do so before running the command.  (Of course, storing the cwd could also prove useful otherwise, if the feature wouldn't prove troublesome as far as speed and file size.)  Since it's asking for a different feature (one that requires support in Fish itself, rather than merely a shell function), I filed it separately.  They are surely related, but they are not the same thing.  #3368 was then intended to consider adding the `commandline-paths-to-absolute` function to Fish, regardless of whether this saving-cwd-with-history idea is implemented.

> (modulo false positives by the test -e).

Yes, this could happen.  Of course, it's very unlikely for a `--option` or `-o` type token to exist as a file in the current directory, though not impossible.  More likely would be a situation like being in a directory with a file named `install` and running the path-converting function with a command like `apt install` on the command line, which would transform `apt install` into `apt /a/b/install`.  However, I don't think that would present a problem, certainly not more of a problem than simply running a command from history in the wrong directory.  The user would still see the transformed command before executing it, just like with any history entry.  I think the potential usefulness of the command would outweigh any potential confusion, although I suppose testing could reveal otherwise.  I would certainly not be in favor of implementing default functionality that could be confusing or dangerous to new users.

> So now your commandline-paths-to-absolute function needs to look something like the following....Does that accurately capture what you're thinking?

Thanks for putting that together.  That's close, but I think that we're talking about what are, or should probably be, two distinct operations: a) converting paths on the current command line from relative to absolute, and b) executing a command recalled from history in the directory it was originally run in.  However, it might be good to implement *b* by effectively doing *a*, converting the paths to absolute based on the original cwd, and then displaying the converted command to the user before executing it.  

Another possibility would be to wrap the command in a block that changes to the original working directory, runs the command, and changes back to the *current* working directory, something like:

```fish
function with_history_cwd
    set -l orig_command (commandline)
    set -l orig_cwd (commandline --history-cwd) 
    commandline --replace "begin
    cd \"$orig_cwd\"; or return 1
    $orig_command
    cd -
    end"
end
```
So, as you suggest, it might work well to implement them as a combined command.  What I think would be necessary is an additional option to the one you suggested, something like `commandline --command-is-from-history-p` (Emacs predicate-style, but it could be named whatever seems best), which would return 0 if the current command line is one recalled from history, or 1 if it either a) was typed by the user, or b) was recalled from history and then modified by the user.  

I suggest *b* because changing it after recalling it effectively turns it into a new command.  However I might be wrong about this, and it might be better to preserve the from-history status even after the user modifies it, so that then running the Alt+C (or whatever) command would still convert the paths; otherwise the user would have to Ctrl+C, recall the command from history again, convert the paths, and *then* modify it.

> Should the hypothetical commandline --history-pwd return a value if the command has been modified in any way after being retrieved from the history?

This is a good question.  I think it would be best to split the cwd-recalling from the is-this-command-from-history-checking into two options.  That way, users can implement the behavior they prefer in their own shell functions, either ignoring whether the command has been modified, or refusing to convert the paths after the command has been modified.  If implemented, we should probably consider which behavior seems safest by default.

> Perhaps this should be implemented via a new flag that could be used with history search --exact to return just the pwd for the command line (which makes the previous question moot).

I'm not familiar with Fish's internals, but I can imagine that simplifying the implementation a bit, since `history search --exact` could be used in place of a separate `commandline --is-from-history` option.  However, that might not be quite enough, because if a command were in the history multiple times, with a different cwd in each, it would seem necessary to get the cwd for the instance that the user has currently displayed.  If the user has executed several commands in sequence, and specifically skips over one to a duplicate that he knows was run in a certain directory, it would seem like a bug to him if Fish recalled the cwd for the latest instance of that command.  But then, it might be good enough to just recall the cwd from the most recent instance.  (Perfect being the enemy of the good, etc.)  Maybe testing would help figure out the best behavior here.

> Also, keep in mind the BSD readlink doesn't have a -m flag. And depending on which flavor of BSD it may or many not have readlink -f. Which is why we introduced fish_realpath.

Yes, this is a good point.  Any implementation of this must take this into account.  I still have Fish 2.2 on  my main system, so I haven't looked into that yet...

> It probably would have been less confusing had you simply made this and issue #3368 a single issue since the two are effectively asking for the same feature.

I'm sorry if I was confusing.  To me they seem like related but separate features, especially since one of them can already be implemented with a shell function.  But as you point out, if the cwd-recording were implemented, maybe they could be combined into a single, "smart" command.

**Comment by krader1961** [comment] 2016-09-30 03:26
> Yes, because that would require Fish to store the cwd with history, which it currently doesn't. #3368 was specifically about "a command that could convert relative paths on the command line to absolute ones," which is what we ended up with after @jinliu helpfully pointed out that it was already possible to implement that. 

Okay, I see where I went off the rails. I read the two proposals back-to-back. Which caused me to conflate the two proposals since, in light of this issue, you seemed to be arguing for a way to re-execute the `rsync` command by magically converting all the relative paths to absolute paths so that if the cwd had changed it wouldn't matter. Which is itself problematic for other reasons I won't go into here.

> because if a command were in the history multiple times, with a different cwd in each,

By design a command will be in the history exactly once. By analogy with how we handle the timestamp associated with when the command was executed the cwd would be another attribute that is ignored when deciding if a command should result in an equivalent history entry being replaced. Too, your use case does not benefit from considering the cwd when deciding if a command is a duplicate of another already in the history. It seems your use case always wants the cwd from the most recent execution. So what would be the point of recording `less README.md` multiple times in the history just because the cwd was different? We can all think of esoteric scenarios where that might be useful but if we implement that we might as well use the bash/zsh pattern of appending every command to the history without removing an earlier duplicate just because the timestamp is different.

>> (modulo false positives by the test -e).
> Yes, this could happen. Of course, it's very unlikely for a --option or -o type token to exist as a file in the current directory, though not impossible.

Note that such false positives are not limited to values associated with a flag (i.e., option). Consider the `grep` command. If I type `grep foo *` and there happens to be a file named `foo` in my cwd I wouldn't want it expanded to an absolute path. That's why I say this is fragile. And therefore should not be default behavior. I have no objection to enhancing fish to make such behavior possible for users such as yourself, @alphapapa, who want it and understand the failure modes. But I strongly feel this (and the solution in issue #3368) should not be out of the box (i.e., standard) behavior. Yes, you can argue that...

> The user would still see the transformed command before executing it, just like with any history entry.

The reality is that it is far to easy to invoke the key binding that performs the transformation and then press [enter] before realizing that wasn't what you intended. Sure, most of the time the result is likely to be correct or at least harmless. Nor can we eliminate the possibility of people shooting themselves in the foot. Nonetheless, I feel that something like this feature should be a conscious decision of the user to enable rather than default behavior.

> Another possibility would be to wrap the command in a block that changes to the original working directory, runs the command, and changes back to the current working directory,

That opens up too many possibilities for surprising behavior. Not to mention that given a process has a single That approach is a non-starter.

**Comment by alphapapa** [comment] 2016-10-01 02:39
> a way to re-execute the rsync command by magically converting all the relative paths to absolute paths so that if the cwd had changed it wouldn't matter. Which is itself problematic for other reasons I won't go into here.

I agree that the command displayed should be the one executed, i.e. if paths are converted from relative to absolute, that should be done and displayed separately from executing the command.  There should never be any kind of hidden, path-converting behavior that runs a command with arguments other than the ones displayed to the user.  If some...enterprising...user wanted to use a hook to do that in his personal shell, well, more power to him, but there be dragons.  D:

> By design a command will be in the history exactly once. By analogy with how we handle the timestamp associated with when the command was executed the cwd would be another attribute that is ignored when deciding if a command should result in an equivalent history entry being replaced.

I'm confused here: I'm looking at my `fish_history` file, and I can see multiple entries with the same `cmd` but different `when`.  Do you mean that the in-memory representation stores each `cmd` once with multiple timestamps?

> It seems your use case always wants the cwd from the most recent execution

Not strictly, but it would be the most straightforward implementation, and I think it would be useful enough to be worth doing.  After some experience was gained from using that, if it seemed that it would be useful to handle older, duplicate entries with different cwd, we could consider that. 

> So what would be the point of recording less README.md multiple times in the history just because the cwd was different? We can all think of esoteric scenarios where that might be useful but if we implement that we might as well use the bash/zsh pattern of appending every command to the history without removing an earlier duplicate just because the timestamp is different.

Like you said, I can imagine scenarios where that would be useful, but I think in order to be practical, there would need to be a feature to display the cwd alongside the command when recalling from history; otherwise it would be like the user was feeling around blindly for the right instance of the command. Displaying the cwd alongside the recalled command might actually be doable, similar to how completions can display in a line below the current prompt.  Probably shouldn't be default behavior, but I think it could be a powerful option for advanced users.

> Note that such false positives are not limited to values associated with a flag (i.e., option). Consider the grep command. If I type grep foo * and there happens to be a file named foo in my cwd I wouldn't want it expanded to an absolute path. That's why I say this is fragile. And therefore should not be default behavior. 

Yes, that's a good point.  It could seem fragile in some cases, so the user who uses it should know what he's doing.  I agree that it shouldn't be enabled by default.

> The reality is that it is far to easy to invoke the key binding that performs the transformation and then press [enter] before realizing that wasn't what you intended....I feel that something like this feature should be a conscious decision of the user to enable 

I agree, there shouldn't be a default binding to convert paths or alter the command line based on the cwd of a history entry.  If the feature were implemented, I'd suggest it be documented in the manual in an "advanced usage" or "tips for advanced users" section, something like that.  (I hereby volunteer to write the documentation in the event the feature is implemented.  ;)

> That opens up too many possibilities for surprising behavior. 

Hm, well, maybe this deserves some prototyping; if the cwd-storing/recalling were implemented, the cd-block idea could be done in a shell function.  Probably not worth including as a built-in function, but maybe, if it worked well enough, it could be given as an example in the docs.

> Not to mention that given a process has a single That approach is a non-starter.

A single...?  (I guess you accidentally cut something out.)

Thanks for your feedback.

**Comment by krader1961** [comment] 2016-10-01 04:58
> I'm confused here: I'm looking at my fish_history file, and I can see multiple entries with the same cmd but different when. Do you mean that the in-memory representation stores each cmd once with multiple timestamps?

Not exactly. Each interactive fish instance only recognizes the most recent history entry for a given command. That you can find multiple instances of a command in the history file is not surprising. It is a consequence of each interactive fish shell appending to the history file. That is done to minimize the likelihood of not recording a command with the minimum cost. However, at some point the file will be rewritten with duplicates removed by one of the fish shell instances.

Even when you can find multiple entries of the same command in the *~/.local/share/fish/fish_history* file you should find that the builtin `history search` command only returns the most recent instance. And that is also true for autosuggestion matching.

Run this command a few times in different shell sessions:

```
grep '^- cmd: ' ~/.local/share/fish/fish_history | sort | uniq -c | sort -rn | head
```

You should see the output has different output for the command that appear more than once in the history based on when you run that command and from which shell. Basically, the *fish_history* file is meant to be an opaque container. Despite being in YAML format.

**Comment by alphapapa** [comment] 2016-10-01 07:34
Thanks for explaining that.

**Comment by krader1961** [comment] 2017-02-09 00:24
This is a duplicate of issue #518.

**Closed by krader1961** 2017-02-09 00:24 UTC
Labels: duplicate
