### ISSUE TITLE
Automatically jump when inputting

### ISSUE THREAD

**Issue by haodong** [fish-shell/fish-shell#5318] opened 2018-11-05 12:49 UTC
`fish, version 2.7.1`

![wx20181105-204607](https://user-images.githubusercontent.com/8103074/47999064-42cfc480-e13c-11e8-8966-976e8bb23c0d.png)

I just input the command as normal `zip -r "..."`

**Comment by faho** [comment] 2018-11-05 13:47
Duplicate of #5059, #4539, #4609 and numerous other issues.

The summary is that the terminal and fish need to agree on how wide characters are or our cursor movement for doing suggestions goes to wrong places, but this sometimes goes wrong because unicode is hard. Fish 3.0 will have numerous improvements.

**Closed by faho** 2018-11-05 13:47 UTC

**Comment by haodong** [comment] 2018-11-05 13:50
@faho I feel so passionate to expect the up coming v3.0 fish. Thank you.
