### ISSUE TITLE
Allow using stdout of a command as multiple arguments to a new command

### ISSUE THREAD

**Issue by sdroege** [fish-shell/fish-shell#896] opened 2013-06-27 07:22 UTC
Currently something like
touch (echo 1 2)
will create a single file called "1 2". In many cases it is useful to have the the output used as multiple arguments, e.g. when doing something like
gcc -o test test.c (pkg-config --cflags --libs glib-2.0)
(which currently fails because gcc wants multiple arguments instead of one large).

Maybe a new syntax could be added for that, maybe double () e.g.
gcc -o test test.c ((pkg-config --cflags --libs glib-2.0))

**Comment by faho** [comment] 2015-09-26 11:33
This is a duplicate of #693. Please yell at me if you don't think it is.

**Closed by faho** 2015-09-26 11:33 UTC

**Comment by ibqn** [comment] 2018-05-14 14:54
So, the usage for the above example from the comment 1 would be something like this:

```g++ -o test (pkg-config gtkmm-3.0 --cflags --libs | string split ' ') test.cpp```
