### ISSUE TITLE
No way to configure system PATH with higher priority than vendor PATH

### ISSUE THREAD

**Issue by thefloweringash** [fish-shell/fish-shell#5641] opened 2019-02-11 07:38 UTC
On macOS, I want to configure system local PATH entries:
 - before `/etc/paths` and `/etc/paths.d`
 - for login shells
 - applying to all snippet directories

I don't believe this is possible. Control starts in `share/config.fish`, which runs the `path_helper` followed by user snippet directories.

The current version of the [package I'm using][fish preinit] patches in a configuration hook by appending to `__fish_build_paths.fish`. Having to patch this in a package manager is undesirable, and hopefully we can clean it up. For my use case, this is insufficient because it runs before the `path_helper`, so the paths are not higher priority.

[fish preinit]: https://github.com/NixOS/nixpkgs/blob/3e50fba209f373635af0cb5f8b82e356ea83198c/pkgs/shells/fish/default.nix#L159

---
fish, version 3.0.0 from nixpkgs
macOS 10.14.3

**Comment by faho** [comment] 2019-02-11 18:18
>For my use case, this is insufficient

So, I'd love to know what your use case is, exactly, and especially why you want to set this in the shell.

Do you have multiple actual human users or just computer-users?

If these are all humans, you want to set these sorts of variables outside of any shell, because the user could be picking a different shell (unless you have a weirdly locked down system).

**Comment by faho** [comment] 2019-02-13 11:09
Okay, so going by https://github.com/LnL7/nix-darwin/issues/122#issuecomment-462046128, this just looks like #5456.

**Comment by faho** [comment] 2019-02-13 11:10
Duplicate of #5456

**Closed by faho** 2019-02-13 11:10 UTC
Labels: needs more info

**Comment by thefloweringash** [comment] 2019-02-16 12:04
This is not a duplicate of #5456, which deals with the behavior of non-login, interactive shells with custom paths, and should be remedied by #5637. This issue is specifically talking about login, interactive shells and how the initial path is set.

The exact use case here is to configure a secondary package manager as a system-wide install. In my case this is the Nix package manager configured by the nix-darwin configuration management layer. The same should apply for things like Homebrew and Linuxbrew, though typically they're configured in `~/.profile` instead.

nix-darwin configures most shells by setting environment  variables, including `PATH`, through `/etc/profile`, and `/etc/zprofile`. For fish, this injection point doesn't exist. nix-darwin generally follows the much larger NixOS project, which configures things the same way. To achieve this with fish, there's an additional patch to the startup process that causes fish to source `/etc/fish/nixos-env-preinit.fish` about the same time a different shell would be sourcing `/etc/profile`. However this happens to break for nix-darwin, because the env preinit runs before path_helper. The end result is the configuration management layer is rendered ineffective by path_helper, and fish's path is incorrect (LnL7/nix-darwin#122).

Ideally nixpkgs wouldn't be patching the initialization. Patching it again to make nix-darwin work would also be sub-optimal. In this ticket I'm hoping to find the canonical configuration recommendation for things that would otherwise live in `/etc/profile`.

---

There's still a difference between relying on inheriting environment for configuration, and making it explicit in an `/etc/profile` file. Running a login shell as a subshell will typically reset most of the environment, but won't if it's only inherited. I don't know if this is a particularly useful distinction though.

**Comment by faho** [comment] 2019-02-16 12:09
>#5456, which deals with the behavior of non-login, interactive shells with custom paths, and should be remedied by #5637.

It's not. Which is why it's not closed.

It's about $PATH changing order when $fish_user_paths and /etc/paths is read.

Solving that would also solve your problem.

**Comment by kevingriffin** [comment] 2019-04-24 15:38
Correct me if I'm wrong, but the change in https://github.com/fish-shell/fish-shell/pull/5637 will only enable the above-mentioned patch to work, not to allow for this kind of initialization natively, correct?

In absence of patching fish's startup, there's still no good way to achieve this. Preventing the shuffle will just allow the patch to work without Darwin stomping on it later in the process.
