### ISSUE TITLE
Make argparse/fish_opt short option optional

### ISSUE THREAD

**Issue by etcusrvar** [fish-shell/fish-shell#7647] opened 2021-01-23 14:57 UTC
fish 3.1.2
enhancement, change request

For [fist_opt](https://fishshell.com/docs/current/cmds/fish_opt.html#description) - "-s or --short takes a single letter that is used as the short flag in the option being defined. This option is mandatory."

Can the mandatory short option be made optional?

Motivation: I'm writing a function that takes several long options where either
- a) I don't care to have a short option
- b) The short options seem to overlap and don't make sense

A contrived example:
```
function fn
    set s "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    for i in (seq (string length $s))
        set c (string sub -s $i -l 1 $s)
        set -a options (
            fish_opt --short $c \
                --long (printf "foo-arg-%s" $i) \
                --long-only)
    end
    argparse $options -- $argv
    set -ln | string replace --filter _flag_ ""
    #echo $options
    echo $options[1..3] $options[-3..-1]
end

> fn --foo-arg-18 --foo-arg-29 --foo-arg-47
foo_arg_18
foo_arg_29
foo_arg_47
a-foo-arg-1 b-foo-arg-2 c-foo-arg-3 7-foo-arg-60 8-foo-arg-61 9-foo-arg-62
```

(Aside: There appears to be a max of 62 option specs argparse can take due to the short option being mandatory. Is this correct?)

A real world example-- the volatile list of chrome/chromium flags:
https://www.chromium.org/developers/how-tos/run-chromium-with-flags
https://peter.sh/experiments/chromium-command-line-switches

A real world fish function should most likely be heavily refactored if it had this many options. But the point is that long options don't necessarily need an associated short option, especially if they're not even being used.

**Comment by faho** [comment] 2021-01-23 14:59
Duplicate of #7585

**Closed by faho** 2021-01-23 14:59 UTC
