### ISSUE TITLE
bind to \cz (ctrl-z) does not work

### ISSUE THREAD

**Issue by ferreum** [fish-shell/fish-shell#1879] opened 2015-01-08 10:22 UTC
I tried the following:
```
bind \cz 'echo bind works'
```

but when i press ctrl-z, nothing happens. Running `strace fish` and
pressing ctrl-z suggests that SIGTSTP is sent to fish so i tried:

```
function __ctrl_z --on-signal TSTP
    echo signal works
end
```
but no luck there either...

**Comment by bucaran** [comment] 2015-01-08 10:31
I guess you can't bind to `z`.

**Comment by ferreum** [comment] 2015-01-08 10:47
I just tried this:
1. run `bind \cz 'echo bind works'`
2. find out the terminal path by running `tty`
3. in another terminal, run `stty -F <tty-path> -isig`

Now pressing ctrl-z actually works, but after executing a command, the
changes done with `stty` get reset.

**Comment by zanchey** [comment] 2015-01-23 06:37
Shall we track the problems with `stty` in #1041?

**Comment by krader1961** [comment] 2016-09-20 23:24
Yes, let's close this as a dup of #1041 since the problem is the tty driver is intercepting the character before fish has a chance to read it and we don't allow changing those special chars from within a fish session.

**Closed by krader1961** 2016-09-20 23:24 UTC
Labels: duplicate, enhancement
