### ISSUE TITLE
`cd ''` crashes shell

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8458] opened 2021-11-19 01:09 UTC
fish, version 3.3.1

Passing an empty string to `cd` crashes the whole shell with a C++ exception:

```
❯ builtin cd ''
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
```

For comparison, Bash, Dash, and Zsh all do nothing at all for `cd ''` (meaning they retain the current pwd).

**Comment by zanchey** [comment] 2021-11-19 03:33
Duplicate of #8147

**Closed** 2021-11-19 03:34 UTC
Labels: duplicate
