### ISSUE TITLE
fish doesn't work on Windows10 + msys2

### ISSUE THREAD

**Issue by cjun714** [fish-shell/fish-shell#5569] opened 2019-01-22 08:12 UTC
fish --version: 3.0.0

fish doesn't work on window10 + msys2.
I have reinstalled msys2 and fish, but issue still exists.

``` shell
> pacman -S fish
> fish
D:/tool/dev/msys64/usr/bin/fish.exe: error while loading shared libraries: msys-pcre2-16-0.dll: cannot open shared object file: No such file or directory
> pacman -S pcre2
> fish --version
fish, version 3.0.0
> fish  <------------- dead here
```

Please help to check, thanks a lot!

**Comment by bitraid** [comment] 2019-01-22 09:40
See issue #5426

**Comment by zanchey** [comment] 2019-01-22 11:02
Yes, this is a duplicate of #5426 which we hope to have fixed in the upcoming 3.0.1. Thanks for filing though!

**Closed by zanchey** 2019-01-22 11:02 UTC

**Comment by mqudsi** [comment] 2019-01-22 17:03
In the future please search past issues before filing. Thanks!

**Comment by VACUUMSONG** [comment] 2020-02-28 03:26
pacman -S pcre2
pacman -S libpcre2_16
pacman -S mingw-w64-x86_64-pcre2
