### ISSUE TITLE
Completions: poor dnf autocomplete

### ISSUE THREAD

**Issue by sebastien** [fish-shell/fish-shell#4244] opened 2017-07-25 14:14 UTC
I recently moved to Fedora and noticed that the completions for `dnf` could be improved:

1) `dnf install ipyth<TAB>` does not present any option containing `ipython` (the package is actually `python2-ipython`)
2) `dnf install python2-ipy<TAB>` does not present any match at all (while there is definitely such a package)
3) `dnf install zer<TAB>` does not yield any match, while there are matches (like `zeromq`)

```
fish, version 2.3.1
Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```

**Comment by faho** [comment] 2017-07-25 14:24
Duplicate of #3062. Note that no member of the fish team uses Fedora (AFAIK), so PRs are very much welcome.

**Closed by faho** 2017-07-25 14:24 UTC
